- doc/_utils/utils.py
- doc/kconfig/conf.py
- doc/matter/conf.py
- doc/mcuboot/conf.py
- doc/nrf/conf.py
- doc/nrfx/conf.py
- doc/nrfxlib/conf.py
- doc/tfm/conf.py
- doc/zephyr/conf.py
Add a banner on top informing about the transition to the Zoomin documentation platform.
> doc: add Zoomin info banner to doc

- applications/nrf5340_audio/README.rst
- doc/nrf/libraries/bin/bt_ll_acs_nrf53/index.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added a mention of the missing support for +20 dBm when using the controller with the nRF21540 FEM, because of a class restriction in the controller's QDID.
OCT-2735.
> doc: nrf5340_audio: note about +20 dBm limitation

- samples/matter/common/src/bridge/bridge_manager.cpp
- samples/matter/common/src/bridge/util/bridge_util.h
This patch allows to add different Matter devices tied to the same data provider
in multiple steps - up till now it has to be added in a single call.
> applications: Matter Bridge: make adding new devices more flexible

- samples/bluetooth/mesh/dfu/distributor/src/dfu_dist.c
Aligne dfu sample with:
https://github.com/zephyrproject-rtos/zephyr/pull/61389
bt_mesh_dfu_slot no longer has 'uri' param.
> bluetooth: samples: mesh: remove uri info prints in dfu sample

- sysbuild/CMakeLists.txt
Introduce two new functions in NCS sysbuild code:
- store_ncs_vars
- restore_ncs_vars
the store_ncs_vars() pushes all CMake variables prefixed with NCS_` which exists in the top-level sdk-nrf sysbuild CMake file to a property and upon calls to sysbuild hooks, those NCS variables are restored.
This allows CMake code in sdk-nrf to share CMake variables between sysbuild configure stages.
> cmake: create store / restore functions for NCS prefixed variables

- west.yml
Pull Zephyr noup change that adds the NVS lookup cache hash function optimized for NVS used as the settings backend. Pull Matter change that enables the hash function for Matter applications, by default.
> matter: enable NVS lookup cache settings optimization

- include/debug/ppi_trace.h
- subsys/debug/ppi_trace/ppi_trace.c
For current `ppi_trace_config` it is impossible to trace events for which PUBLISH register is overwritten in run-time after `ppi_trace_config` is called. This function allows also to trace just one event and does not allow to trace many-to-one topologies which are possible with use of DPPIs.
To overcome above limitations `ppi_trace_dppi_ch_trace` is added. In contrast to `ppi_trace_config` the function `ppi_trace_dppi_ch_trace` focuses on tracing rather the DPPI channel leaving the preparation of event network publishing to it to a user.
> ppi_trace: add ppi_trace_dppi_ch_trace function

- west.yml
Adding mesh v1b1 PTS tester and fixes for mesh 1.1 qualification
> manifest: sdk-zephyr: mesh v1b1 PTS tester support and fixes

- applications/serial_lte_modem/README.rst
- applications/serial_lte_modem/doc/AT_commands_intro.rst
- applications/serial_lte_modem/doc/slm_description.rst
- doc/nrf/device_guides/working_with_nrf/nrf91/nrf91_features.rst
- doc/nrf/device_guides/working_with_nrf/nrf91/thingy91.rst
- doc/nrf/libraries/modem/lte_lc.rst
- doc/nrf/libraries/modem/modem_battery.rst
- doc/nrf/libraries/modem/modem_key_mgmt.rst
- doc/nrf/libraries/modem/pdn.rst
- doc/nrf/libraries/networking/nrf_provisioning.rst
- doc/nrf/links.txt
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/at_client/README.rst
- samples/cellular/lwm2m_client/provisioning.rst
- samples/cellular/modem_shell/README.rst
- samples/cellular/nrf_cloud_multi_service/README.rst
- samples/cellular/pdn/README.rst
- samples/cellular/slm_shell/README.rst
- samples/cellular/udp/README.rst
- west.yml
* Rename "nRF91 AT Commands Reference Guide" to "nRF9160 AT Commands".
* Add AT Commands Reference Guide for the nRF9161 DK.
> doc: Rename nRF91 AT Commands Reference Guide

- west.yml
For RTC0 events the RTC1 pretick event was not cleared what caused the WDT to be not stopped. This resulted in increased power usage.
This commit brings in zephyr with the fix to this issue.
> manifest: update zephyr with nrf53 pretick power usage fix

- doc/nrf/security/ap_protect.rst
AP-Prot guide uses SoC in text and tables even when nRF9160 is listed or mentioned. Use the term device instead for those cases (NCSDK-21451).
> doc: Remove use of SoC when referencing SiPs

- drivers/wifi/nrf700x/Kconfig
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_cmd.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/radio_test/fmac_api.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/cmd.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/default/fmac_api.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/radio_test/fmac_api.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
Provide a Kconfig option and driver API to disable beamforming.
> drivers: wifi: Provide option to disable beamforming

- doc/nrf/introduction.rst
Edited the introduction page to include distinguishing features similar to the section in Zephyr docs.
NCSDK-22322.
----
> doc: introduction: distinguishing NCS features

- applications/asset_tracker_v2/src/cloud/lwm2m_integration/lwm2m_integration.c
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/net/lwm2m_client_utils.h
- samples/cellular/lwm2m_client/src/main.c
- subsys/net/lib/fota_download/src/util/fota_download_delta_modem.c
- subsys/net/lib/fota_download/src/util/fota_download_full_modem.c
- subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_adv_firmware.c
- subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c
- tests/subsys/net/lib/lwm2m_fota_utils/src/firmware.c
Fota_download:
- Updated Delta & Full modem utils apply update to support reconnect after update
LwM2M client utils library:
- Added support for update modem firmware without reboot.
- New FOTA CB event type for request modem init and connect.
LwM2M Client:
- LwM2M client sample support new event for init modem and connect Client again to server.
- New state for Modem init and client reconnect
Asset Tarcker v2:
- Added handler for new event but keeps original functionality still system reboot.
> Lwm2m modem firmware udate

- doc/nrf/releases_and_maturity/known_issues.rst
- subsys/bootloader/bl_storage/nrf_nv_counters.c
The NRF non-volatile counters function boot_nv_security_counter_get is called by MCUBOOT using the macro FIH_CALL(). When the fault injection protection is enabled this macro increases a counter in MCUBOOT which is expected to be the same before and after the call to the function. The counter is increased by FIH_CALL() and is expected to get decreased by the FIH_RET() macro. This means that all the functions which are called by FIH_CALL() need to return with FIH_RET(), otherwise the fault injection protection will stop the execution.
This change fixes a bug with our implementation of nv_counters which didn't return FIH_RET(). This had as a consequence that when the hardware downgrade prevention and the fault injection protection was enabled in MCUBOOT: …
> bl_storage: Fix nv_counters bug with FIH

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- subsys/net/lib/download_client/src/download_client.c
- tests/subsys/net/lib/download_client/src/main.c
- tests/subsys/net/lib/download_client/src/mock/socket.c
Send error event before disconnect event.
Disconnect event should be the last one.
This should fix the issue reported as NCSDK-23789.
> net: lib: download_client: Send error before disconnect

- drivers/wifi/nrf700x/CMakeLists.txt
The anomaly 43 workaround introduces extra delay due to waiting for QSPI ready and causes BLE throughput drops as Wi-Fi driver is waiting and halting the APP.
But this anomaly is only for XIP, so, can be disabled when using QSPI for Wi-Fi comms.
Fixes SHEL-1633.
> drivers: wifi: Fix throughput degradation in BLE

- subsys/net/lib/rest_client/src/rest_client.c
Change keep alive message to `LOG_DBG`.
Add new `LOG_DBG` for when the socket is closed.
Set `used_socket_is_alive flag` to false since the `connect_socket` value is set to -1 after `close()` is called.
> net: lib: rest_client: update rest_client_close_connection() log msgs

- subsys/net/lib/nrf_cloud/coap/cddl/nrf_cloud_coap_agps.cddl
- subsys/net/lib/nrf_cloud/coap/include/agps_encode_types.h
- subsys/net/lib/nrf_cloud/coap/src/agps_encode.c
The number of types of A-GPS elements has increased to support QZSS, so the nrf_cloud/coap/cddl/nrf_cloud_coap_agps.cddl has been changed to match, and the encoder has  been regenerated.
> net: lib: nrf_cloud: Update A-GPS cddl

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/net/nrf_cloud.h
- include/net/nrf_cloud_coap.h
- include/net/nrf_cloud_codec.h
- samples/cellular/nrf_cloud_multi_service/Kconfig
- samples/cellular/nrf_cloud_multi_service/src/message_queue.c
- samples/cellular/nrf_cloud_multi_service/src/shadow_support_coap.c
- subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c
- subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c
- subsys/net/lib/nrf_cloud/include/nrf_cloud_codec_internal.h
- subsys/net/lib/nrf_cloud/src/nrf_cloud_codec.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_fsm.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c
nRF Cloud Multi Service Sample:
Enable PSM by default.
Increase connection_mgr stack size to prevent crashes with Wi-Fi.
Do not count server-side CoAP errors against send_failure_count, or else we disconnect from the cloud for no reason.
Clean up check_shadow function.
nRF Cloud Library:
Make logging and alert control section usable for CoAP in addition to MQTT.
Add error checking and handling to bad shadow delta values for control section.
Add nrf_cloud_shadow_delta_response_encode() for library users to accept or reject custom shadow deltas.
Improve error logging for CoAP so that server side errors get displayed.  An example is the JSON error returned when a customer exceeds their monthly quota for messages or location services.
Jira: IRIS-6800
> Improve shadow delta handling

- applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
- applications/serial_lte_modem/src/slm_at_socket.c
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Numbering has changed for: TLS_DTLS_CID, TLS_DTLS_CID_STATUS and TLS_DTLS_HANDSHAKE_TIMEO.
Edit: If these keep on changing, we should consider string names for options.
Edit edit: SO_BINDTODEVICE has been replaced with SO_BINDTOPDN.
> applications: serial_lte_modem: Fix socket options.

- doc/nrf/device_guides/working_with_nrf/nrf52/features.rst
- doc/nrf/device_guides/working_with_nrf/nrf53/nrf5340.rst
- doc/nrf/libraries/bluetooth_services/mesh.rst
- doc/nrf/libraries/bluetooth_services/mesh/dk_prov.rst
- doc/nrf/protocols/bt/ble/index.rst
- doc/nrf/protocols/bt/bt_mesh/index.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- doc/nrf/samples.rst
- doc/nrf/samples/bl.rst
- doc/nrf/samples/mesh.rst
- samples/bluetooth/mesh/ble_peripheral_lbs_coex/README.rst
- samples/bluetooth/mesh/chat/README.rst
- samples/bluetooth/mesh/dfu/distributor/README.rst
- samples/bluetooth/mesh/dfu/target/README.rst
- samples/bluetooth/mesh/light/README.rst
- samples/bluetooth/mesh/light_ctrl/README.rst
- samples/bluetooth/mesh/light_dimmer/README.rst
- samples/bluetooth/mesh/light_switch/README.rst
- samples/bluetooth/mesh/sensor_client/README.rst
- samples/bluetooth/mesh/sensor_server/README.rst
- samples/bluetooth/mesh/silvair_enocean/README.rst
The list of Bluetooth samples, including the Bluetooth mesh samples, has gotten longer. Bluetooth mesh samples drown a little and are not easily spotted.
Splitting out mesh samples onto a separate page.
> doc: bluetooth: mesh: Split out mesh samples

- subsys/net/lib/nrf_cloud/src/nrf_cloud_rest.c
A-GNSS data download usually requires more than one HTTP request. Now the same TCP/TLS connection is used for all HTTP requests.
> subsys: net: lib: nrf_cloud: Reuse socket for A-GNSS

- applications/serial_lte_modem/src/nrfcloud/slm_at_nrfcloud.c
To this end, issue a disconnect before attempting to connect and allow disconnecting from nRF Cloud unconditionally.
> applications: serial_lte_modem: AT#XNRFCLOUD: fix connected-but-not case

- applications/serial_lte_modem/src/gnss/slm_at_gnss.c
The rest is taken care of by PR #12568.
> applications: serial_lte_modem: update last references to A-GPS

- applications/serial_lte_modem/doc/GNSS_AT_commands.rst
- applications/serial_lte_modem/src/gnss/slm_at_gnss.c
Currently GNSS scheduled download is disabled for SLM AGPS/PGPS periodical tracking to save power as AGPS/PGPS data has the info.
There is a need to disable it for SLM GPS periodical tracking as well, due to scheduled download would generate fixes not according to the interval configuration, i.e. fix per second.
From mfw_2.0 the fix by scheduled download will be flagged and the libmodem GNSS could filter the unwanted fix.
> application: serial_lte_modem: BUG-FIX GNSS scheduled download

- applications/matter_bridge/src/bridged_device_types/onoff_light.cpp
- samples/matter/common/src/bridge/bridged_device_data_provider.h
- samples/matter/common/src/bridge/matter_bridged_device.h
- west.yml
This PR pulls important commits cherry-picked from the Matter SDK:
- Matter shell refinements
- compilation time optimization
- root certification expiration fixes
- RAM size optimization
- performance improvements
- subscriptions and reporting fixes
- Matter spec conformance fixes
- configuration fix
> manifest: pull recent vital Matter SDK patches

- doc/nrf/libraries/others/network_core_monitor.rst
- include/net_core_monitor.h
- subsys/net_core_monitor/Kconfig
- subsys/net_core_monitor/app_core.c
- subsys/net_core_monitor/common.h
- subsys/net_core_monitor/net_core.c
The `__weak ncm_net_core_event_handler` function is used to notify the application about the network core staus.
This repleace the periodic call of the
`ncm_net_status_check` function.
This makes it easier to use and configure.
> net_core_monitor: Make it easy to use

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/modem/pdn.h
- lib/pdn/pdn.c
Add events for APN rate control.
Have not been able to tests the new functionality yet..
The modem won't send `CGEV APNRATECTRL STAT` notifications upon CFUN mode changes (NW detach) or PDN deactivation.
Should this library send the APN rate control events "spontaneously" in those cases?
> lib: pdn: add APN rate control events

- CODEOWNERS
This was missed when the module was introduced.
@rlubos let me know if you want me to add as well, initially I wanted to duplicate https://github.com/nrfconnect/sdk-hostap/blob/main/CODEOWNERS but then as @jukkar  started working hostap I have replaced you with him. We should probably have the same list of people on both, @carlescufi WDYT?
> codeowners: Add entry for hostap module

- include/net/fota_download.h
Make the doxygen briefs for fota_download_event_id explicitly describe the meaning of each event.
> net: fota_download: Add explicit descriptions for fota_download_evt_id

- doc/nrf/protocols/bt/ble/index.rst
The SoftDevice Controller supports an extensive feature set from the newest, Bluetooth version 5.4 version.
To reduce the change of forgetting to update this in future releases, remove the version reference.
> doc: Bluetooth: Remove version name when mentioning the SoftDevice

- CODEOWNERS
Both exist only for the Serial LTE Modem application.
> CODEOWNERS: add SLM maintainers to ftp_client lib, slm_shell sample

- doc/nrf/protocols/matter/end_product/index.rst
- doc/nrf/protocols/matter/end_product/last_fabric_removal_delegate.rst
- doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
- Added the page to describe the mechanism and reactions to the last fabric removal.
- Added instruction on how to implement the custom Fabric Table delegation.
- Updated the advanced kncofigs pages to describe all possible reactions to the last fabric removal.
> doc: matter: Add documentation for last fabric removal

- doc/_utils/redirects.py
- doc/nrf/links.txt
- doc/nrf/protocols/matter/end_product/ecosystems_certification.rst
- doc/nrf/protocols/matter/end_product/index.rst
- doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added dedicated page describing how to certify the Matter product for the specific ecosystem cases. Additionally extended the FFS configuration with the information about the rotating device uid selection.
> doc: nrf: Added page about Matter ecosystems certification

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_adv_firmware.c
- tests/subsys/net/lib/lwm2m_fota_utils/src/firmware.c
Fixed interoperability issue with AVSystem Coiote server for do Firmware update with Push-mode.
Server cancel at idle state was not accepted and cause failure to FOTA process.
> net: lwm2m_client_utils: Advanced FOTA push fix

- .checkpatch.conf
The checker still checked images that were deeper
in the path. Extending the exclusion.
Ref: https://github.com/nrfconnect/sdk-nrf/pull/10772
> compliance: extend image exclusions in the checker

- west.yml
It might happen that while some interrupt handler other than for RTC0 or RTC1 (e.g. for RADIO) is executed, the scheduled pretick CC triggers. This starts pretick pulses due to the loop through IPC. The change in pretick schedule did not stop the pretick pulses going through IPC loop, what caused heavy increase in power consumption.
This commit fixes this behavior by bringing in zephyr with the fix.
> manifest: update zephyr with nrf53 pretick power usage fix 2

- samples/cellular/modem_shell/src/location/location_shell.c
Moved `k_work_init()` call from `location_ctrl_event_handler()` function to the init function to prevent the work item from being re-initialized while the item is being executed.
> samples: cellular: modem_shell: Move work item initialization

- doc/nrf/links.txt
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/bluetooth/peripheral_fast_pair/prj.conf
This reverts commit 2b3c8971bea2fef5da40cb1b9b6a30ea0babce9a, because the Zephyr issue is already fixed.
> Revert "samples: peripheral_fast_pair: Disable CCC Lazy Loading to allow for rebond"

- applications/nrf_desktop/README.rst
- samples/bluetooth/peripheral_fast_pair/README.rst
Aligns the Fast Pair documentation due to Google Nearby Console redesign.
Jira: NCSDK-22647
> doc: fast_pair: Align the doc due to Google Nearby Console redesign

- subsys/net/lib/download_client/src/download_client.c
- tests/subsys/net/lib/download_client/src/main.c
- tests/subsys/net/lib/download_client/src/mock/socket.c
When connect() fails the return value is -1. Use errno to report error in error_evt_send().
> net: lib: download_client: Report correct connect() error

- west.yml
This aims to keep memory footprint after NRF700X_LOG_VERBOSE is enabled by default in NCS.
> manifest: pull disabling of the nRF70 verbosity in Matter

- drivers/wifi/nrf700x/Kconfig
- drivers/wifi/nrf700x/osal/os_if/inc/osal_api.h
Should be merged after https://github.com/nrfconnect/sdk-nrf/pull/12634 to avoid Matter failures as this increases memory.
> wifi: nRF70 enable verbose logging

- samples/cellular/nrf_cloud_multi_service/src/main.c
Small typo in preprocessor directives is causing the coap_fota thread to never start.
Fix this typo by updating CONFIG_NRF_CLOUD_COAP_FOTA to CONFIG_COAP_FOTA
> samples: cellular: MSS: Fix CoAP FOTA thread startup

- tests/bluetooth/tester/src/bttester.h
- tests/bluetooth/tester/src/mesh.c
Mesh initalization has been split in upstream into MESH_INIT and MESH_STAR commands in this PR:
https://github.com/zephyrproject-rtos/zephyr/pull/63658
This commits alignes these changes in sdk-nrf tester.
> tests: bluetooth: tester: Add MESH_START command from upstream tester

- doc/nrf/protocols/matter/getting_started/adding_clusters.rst
Corrected path to MatterPostAttributeChangeCallback in the Matter guide
> doc:matter: correction in the documentation

- doc/nrfx/nrfx.doxyfile.in
- west.yml
Updated hal_nordic contains improved workaround
for nRF91 anomaly 7.
> manifest: update sdk-zephyr revision to have updated hal_nordic

- doc/matter/conf.py
Edited the name, html heading, and the docset subtitle for Matter. Reason: clearly differentiate the Matter SDK docset from the NCS docs in Zoomin, regardless of placement.
> doc improvement: matter: update docset info for zoomin

- samples/peripheral/lpuart/boards/nrf21540dk_nrf52840.overlay
Disconnect CTS and RTS lines from pins.
This is a temporary workaround for increased current consumption observed on nRF21540 v2.0.0 only (~450 uA more than on v1.0.0).
Ref: NCSDK-24113
> samples: peripheral: lpuart: Decrease current draw on nRF21540 DK 2.0.0

- .github/test-spec.yml
Aws_iot and azure_iot_hub samples have moved from samples/cellular to samples/net/ folder.
Adjusted for library changes.
> test-spec: Update for CI-thingy91-test

- lib/fatal_error/Kconfig
Some tests that were not using ZTEST (but were tests with CONFIG_TEST=y) were failing to compile because this gets default y when n is expected. Broadening default value dependency to check for TEST instead of ZTEST.
Jira: NCSDK-6850.
> lib: fatal_error: Fix Kconfig option default

- doc/nrf/protocols/matter/end_product/ecosystems_certification.rst
The nRF7002 DK passed Amazon FFS certification for Matter, so the table containing platforms should be updated.
> doc: nrf: Added information about nRF7002 Amazon FFS certification

- samples/cellular/http_update/application_update/src/main.c
The carrier library integration was broken as the link controller would never connect with carrier library enabled
> samples: cellular: http_update: Fix Carrier Library integration

- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
Remove an if case block which does not seem to be doing anything
Signed-off-by: Vivekananda Uppunda <vivekananda.uppunda@nordicsemi.no>
> drivers: wifi: Remove dead code

- applications/serial_lte_modem/doc/FTP_AT_commands.rst
- applications/serial_lte_modem/src/ftp_c/slm_at_ftp.c
- subsys/net/lib/ftp_client/src/ftp_client.c
Fix a too early return of ftp_client lib functions. They now return only when the data transfer is complete.
Additionally, feed the received data to UART in chunks to allow receiving data bigger than the size of the UART buffer (2048 bytes) *if* the size of the ring buffer (ftp_data_buf) is increased, because it is currently the limiting factor.
NCSDK-20213
> applications: serial_lte_modem: fix FTP data reception

- include/bluetooth/mesh/gen_loc_srv.h
- include/bluetooth/mesh/light_temp_srv.h
- subsys/bluetooth/mesh/gen_loc_srv.c
- subsys/bluetooth/mesh/gen_plvl_srv.c
- subsys/bluetooth/mesh/gen_ponoff_srv.c
- subsys/bluetooth/mesh/light_ctl_srv.c
- subsys/bluetooth/mesh/light_ctrl_srv.c
- subsys/bluetooth/mesh/light_hsl_srv.c
- subsys/bluetooth/mesh/light_hue_srv.c
- subsys/bluetooth/mesh/light_sat_srv.c
- subsys/bluetooth/mesh/light_temp_srv.c
- subsys/bluetooth/mesh/light_xyl_srv.c
- subsys/bluetooth/mesh/lightness_srv.c
- subsys/bluetooth/mesh/scene_srv.c
- subsys/bluetooth/mesh/scheduler_srv.c
- subsys/bluetooth/mesh/sensor_srv.c
- subsys/bluetooth/mesh/time_srv.c
Adds correspond relationship to models as specified in MshMDL1.1. Requires the KCONFIG CONFIG_BT_MESH_COMP_PAGE_1
to register correspondence.
Adds an init callback for Generic Location Setup Server to register model extension and correspondence to Generic Location Server.
Adds a field to the 'bt_mesh_light_temp_srv' struct in 'light_temp_srv.h' which contains the address of the corresponding Light CTL server (used to register correspondence).
Signed-off-by: Håvard Reierstad <haavard.reierstad@nordicsemi.no>
> Bluetooth: mesh: Add model correspond relation

- CODEOWNERS
Remove duplicate entry of /modules/ that caused previous more specific entries to be overwritten. Also moved /modules/tfm/ next to the other /modules/ entries.
> CODEOWNERS: remove duplicate entry

- applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c
- Use presentation delay from BASE
- Clean up active_stream when cleaning up BIS
OCT-2714
> applications: nrf5340_audio: Use PD from BASE

- applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/Kconfig.defaults
Fix the compaitability issues for Android14 by:
* Disable automatic security re-establishment request in peripheral.
* Enable sink PAC notification.
* Enlarge the codec config max metadata size. 
OCT-2755
> applications: nrf5340_audio: compaitability issue fix for Android14

- applications/asset_tracker_v2/src/cloud/cloud_codec/lwm2m/lwm2m_codec_helpers.c
- applications/asset_tracker_v2/tests/lwm2m_codec_helpers/src/lwm2m_codec_helpers_test.c
The storage type for RSRP in the connmon object is now int16_t so there is no need to cast to int8_t anymore.
Without this change, encoding fails due to size mismatch when updating the object.
Fixes NCSDK-24120
> applications: asset_tracker_v2: Remove typecast and use int16 function

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- scripts/partition_manager.py
This happened in a case where two placement specs were identical. When disambiguating one of them, the alignment spec was not preserved.
Jira: NCSIDB-1032
> partition_manager.py: Fix a bug where 'align' spec was deleted.

- applications/nrf5340_audio/src/audio/sw_codec_select.c
- applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c
- applications/nrf5340_audio/src/modules/audio_usb.c
- Remove unused header include
- Check pointer for NULL reference
- Initialize variable before use
- Remove deprecated config
- Use uint16_t for sw_codec_lc3 size
OCT-2670
> applications: nrf5340_audio: Fix coverity issues

- applications/nrf_desktop/doc/config_channel.rst
- scripts/hid_configurator/README.rst
PR introduces documentation for configuration channel peers cache. PR also updates documentation of HID configurator script.
Jira: NCSDK-22775
> applications: nrf_desktop: Document peers cache

- scripts/hid_configurator/README.rst
Change adds information about the fwupd dependency. The fwupd daemon must be stopped before HID configurator script is used.
Jira: NCSDK-22769
> scripts: hid_configurator: Document fwupd dependency

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- subsys/net/lib/nrf_cloud/src/nrf_cloud_codec.c
The "doReply" flag should be placed inside the "data" object, not at the root level.
IRIS-7363
> net: lib: nrf_cloud: fix encoding of "doReply" flag

- samples/bluetooth/mesh/dfu/distributor/sysbuild.conf
- samples/bluetooth/mesh/dfu/target/sysbuild.conf
enable MCUBOOT build in sysbuild to build DFU samples.
> Bluetooth: Mesh: Fix sysbuild build in DFU samples

- samples/wifi/scan/boards/nrf9160dk_nrf9160_ns.overlay
UART1 shares few pins with Wi-Fi GPIOs causing boot failure, this is already fixed in shell and location samples, but missed in scan sample.
> samples: wifi: scan: Fix pin conflicts with Wi-Fi on nRF9160

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change introduces a release note for configuration channel peers cache feature.
Jira: NCSDK-22775
> doc improvement: applications: nrf_desktop: Add peers cache release note

- applications/matter_bridge/src/app_task.h
- applications/matter_weather_station/src/app_task.h
- doc/nrf/protocols/matter/end_product/last_fabric_removal_delegate.rst
- doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
- samples/matter/common/src/fabric_table_delegate.h
- samples/matter/light_bulb/src/app_task.h
- samples/matter/light_switch/src/app_task.h
- samples/matter/lock/src/app_task.h
- samples/matter/template/src/app_task.h
- samples/matter/thermostat/src/app_task.h
- samples/matter/window_covering/src/app_task.h
- west.yml
In tests, we noticed that the action on the last Matter fabric removal doesn't work stable. To fix it and improve stability we need to postpone the factory reset to allow the device to finish all needed operations.
> samples: matter: Fix the Last Fabric Removal feature

- samples/cellular/nrf_cloud_rest_device_message/src/main.c
Only print "Message sent" log message if message send function returns success.
IRIS-7376
> samples: cellular: nrf_cloud_rest_device_message: fix log msg

- samples/cellular/nrf_cloud_multi_service/src/main.c
A renaming of CONFIG_NRF_CLOUD_COAP_SHADOW to CONFIG_COAP_SHADOW was incomplete. This fixes one missed edit.
Jira: NCSDK-24184
> samples: cellular: nrf_cloud_multi_service: fix shadow thread

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/nrf_cloud_multi_service/Kconfig
- samples/cellular/nrf_cloud_multi_service/overlay_full_modem_fota.conf
- samples/cellular/nrf_cloud_multi_service/src/message_queue.c
Reduce the message queue size to prevent potential heap issues.
IRIS-7393
Increased the value CONFIG_HEAP_MEM_POOL_SIZE in the full modem
FOTA overlay to prevent a boot loop on full modem image installation.
IRIS-7377
> samples: cellular: nrf_cloud_multi_service: heap size related config updates

- samples/cellular/nrf_cloud_multi_service/overlay_nrf7002ek_wifi_no_lte.conf
Revert Wi-Fi overlay to using NEWLIB_LIBC, since hostap currently is not compatible with PICOLIB_C
IRIS-7397
> samples: cellular: multi service: Revert Wi-Fi overlay to NEWLIB_LIBC

- applications/nrf_desktop/README.rst
- applications/nrf_desktop/doc/dfu_mcumgr.rst
- applications/nrf_desktop/doc/smp.rst
- doc/nrf/device_guides/working_with_nrf/nrf52/developing.rst
- doc/nrf/libraries/caf/ble_smp.rst
Switch from nRF Connect for Mobile to nRF Connect Device Manager
as the app for DFU purposes.
Switch from using *.bin files to dfu_application.zip and let
the mobile app handle the details.
Jira: NCSDK-24144
> caf/nrf_desktop: Improve DFU over SMP docs

- subsys/bluetooth/mesh/light_ctrl_srv.c
Fixes a bug that got introduced in PR #12651 due to different handling of occupancy messages. Previously the 'delayed_action_timeout()' function was not processing occupancy when Occupancy Mode was off.
Now the function would, additionally, process the occupancy event in FADE, PROLONG, and FADE STANDBY AUTO.
Local checks:
PTS tests pass:
```
1/16   MMDL      MMDL/SR/LLC/BV-01-C    ←[32mPASS           89.018                  ←[0m
2/16   MMDL      MMDL/SR/LLC/BV-02-C    ←[32mPASS           95.787                  ←[0m
3/16   MMDL      MMDL/SR/LLC/BV-03-C    ←[32mPASS           94.119                  ←[0m
4/16   MMDL      MMDL/SR/LLC/BV-04-C    ←[32mPASS           175.578                  ←[0m
5/16   MMDL      MMDL/SR/LLC/BV-05-C    ←[32mPASS           75.379                  ←[0m
6/16 …
```
> Bluetooth: Mesh: Process Occupancy when OCC Mode is off

- doc/nrf/libraries/bin/bt_ll_acs_nrf53/index.rst
Added information about using the nRF5340 Audio conteroller always in the latest version. OCT-2682.
> doc: nrf5340audio controller: add version note

- drivers/wifi/nrf700x/osal/os_if/inc/osal_api.h
- drivers/wifi/nrf700x/osal/os_if/src/osal.c
Using Zephyr macros without Zephyr header files make all the code enabled for compilation costing memory, as we cannot use Zephyr macros in OSAL, define a new ones matching to Zephyr.
> drivers: wifi: Fix inclusion of macros

- doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
- west.yml
This commit brings changes in sdk-connectedhomeip that fixes the incorrect value of Wi-Fi TX tokens, as well as increases the delay before factory reset is done.
It depends on the #12802 which fixes more generic issues.
> matter: fix Wi-Fi TX tokens configuration

- doc/_scripts/software_maturity/software_maturity_features.yaml
- doc/_scripts/software_maturity/software_maturity_scanner.py
Added the possibility to add a display name for each listed KConfig symbol dependency in the `boards_and_shields` section of the input file to the SML scanner. If no display name is given, the previous substring is used instead.
> doc: sml: add display names to dependency list

- subsys/bootloader/bl_boot/bl_boot.c
This is a follow-up to commit 56d117d442c9148c75c621359e22283ffd7caef0 ("bootloader: bl_boot: update UART Kconfigs").
- add missing `CONFIG_` prefixes to `HAS_HW_NRF_*` symbols
- remove invalid entries that refer to non-existing peripherals (UART1 and UART2)
- move `#ifdef CONFIG_UART_NRFX` to the function, where it is actually needed (`CONFIG_UART_NRFX_UART` and `CONFIG_UART_NRFX_UARTE` imply `CONFIG_UART_NRFX`, as they cannot be defined otherwise, so there is no need for that additional `#ifdef` in inclusions).
> bootloader: bl_boot: Fix disabling of UARTs

- samples/cellular/udp/Kconfig
- samples/cellular/udp/README.rst
- samples/cellular/udp/src/main.c
* Add `SO_RAI_NO_DATA` and `SO_RAI_ONGOING`
to this sample to showcase their functionality within
the application.
* Add enable of Access Stratum RAI support during
initialization.
* Update documentation to show how to test the RAI
feature.
> samples: cellular: udp: add more RAI options 

- doc/nrf/releases_and_maturity/known_issues.rst
Added v2.5.0 tag to known issues.
----
> doc: update known issues for NCS v2.5.0

- doc/nrf/device_guides/working_with_nrf/nrf52/developing.rst
- doc/nrf/device_guides/working_with_nrf/nrf70/developing/soc_combo.csv
- doc/nrf/links.txt
- doc/nrf/protocols/zigbee/index.rst
- doc/nrf/releases_and_maturity.rst
- doc/nrf/releases_and_maturity/known_issues.rst
- doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
- doc/nrf/releases_and_maturity/release_notes.rst
- doc/nrf/releases_and_maturity/releases/release-notes-2.5.0.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- doc/nrf/releases_and_maturity/software_maturity.rst
- samples/cellular/lwm2m_client/sample_description.rst
Add release notes and other changes
> doc: Add release notes for 2.5

- share/ncs-package/cmake/NcsConfig.cmake
Since ihttps://github.com/zephyrproject-rtos/zephyr/pull/59811 then PYTHON_PREFER has been deprecated in favor of Python3_EXECUTABLE as artifact specifier.
Remove PYTHON_PREFER setting.
This will also remove the CMake deprecation warning being printed during CMake configure time.
> cmake: remove deprecated PYTHON_PREFER setting

- cmake/sysbuild/modules/ncs_sysbuild_extensions.cmake
The ExternalProject_Add_Step() has an undesired side-effect. The variant image would initially be using a regular generated .config which would be replaced with the .config of the original image during build.
Unfortunately the CMake configure of the variant image can in some cases end with a CMake failure, which means the build stage is never reached and thus the .config is never overwritten.
Fix this by copying the .config as part of the CMake configure stage as is available in existing implementation.
> sysbuild: adjust variant image to use existing variant kconfig impl

- modules/hostap/src/supp_api.c
_wpa_cli_cmd_v macro lands in the `out` section in case of an error, yet it does not set the triggered error code, so it is not passed to the caller or higher layers. This gets deceptive, especially in apps that cannot afford supplicant logging.
> modules: hostap: fixed wpa_cli_cmd error codes propagation

- lib/location/Kconfig
Increased HTTP receive buffer size when HERE location service is used. If resolving the location failed, the response from the server was too large to fit in the receive buffer.
> lib: location: Increase HTTP receive buffer with HERE

- applications/serial_lte_modem/src/slm_settings.c
Settings that were previously saved but have been removed from the code should not provoke error logs that may cause concern to the end user.
Simply ignore unrecognized settings from the slm subtree.
> applications: serial_lte_modem: ignore obsolete settings

- drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
If a user selects all statistics, only UMAC is being seen because of using "else if".
Move to if and also remove duplicate check for stats type.
Fixes SHEL-2096.
> drivers: wifi: Fix statistics for all

- samples/cellular/nrf_cloud_multi_service/sample.yaml
Add to sample.yaml rules to build with all the various overlays.
Jira: IRIS-6808
> samples: cellular: nrf_cloud_multi_service: Build all supported overlays

- .github/workflows/compliance.yml
Change compliance workflow to do a narrow west update so that the
workflow runs faster.
It now takes roughly 1.5 to 2.5 minutes to complete instead of about 3.5 to 5.5 minutes
> workflow: Increase the speed of compliance workflow by doing narrow west update

- subsys/net/openthread/Kconfig.defconfig
Removing deprecated config `IEEE802154_2015`.
> net: openthread: remove deprecated config config `IEEE802154_2015`

- modules/mcuboot/hooks/nrf53_hooks.c
boot_image_check_hook() implementation shall return fih_ret value type. The function should return FIH_BOOT_HOOK_REGULAR instead of BOOT_HOOK_REGULAR.
If the Fault Injection Hardening (FIH) is enabled then fih_int type is different than fih_ret type. Also BOOT_HOOK_REGULAR and FIH_BOOT_HOOK_REGULAR are not the same things.
ref. NCSDK-24203
Consequence of this is that when FIH is enabled, the standard boot_image_check() call is never performed by the mcuboot (for real images) and subsequent checks gets BOOT_HOOK_REGULAR as its results. In mcuboot loader.c this prematurely cause identification of invalid image.
> modules/mcuboot/nrf53_hooks: fix boot_image_check_hook()

- .github/workflows/pip-requirements.yml
* The git user name for the auto commit needs to be formated with 'firstname' 'lastname' for the compliance check
Currently the auto commit to pip requirements changes are failing at the compliance check.
> ci: pip-requirements workflow fix mail

- subsys/nrf_security/src/drivers/Kconfig
Change CC3XX DRBG dependencies from CRYPTOCELL_USABLE to NRF_CC3XX_PLATFORM.
NRF_CC3XX_PLATFORM is more restrictive than CRYPTOCELL_USABLE.
This prevents invalid configurations where the CC3XX platform is disabled while the CC3XX DRBG driver (which uses the platform) is enabled.
> nrf_security: cc3xx: Kconfig: Change dependencies for DRBG

- applications/serial_lte_modem/src/slm_at_socket.c
After sending traffic with #XSENDTO in normal mode, the next #XSEND failed to send traffic in data mode.
> applications: serial_lte_modem: Fix #XSEND after #XSENDTO

- west.yml
This patch allows to avoid unwanted connection request when there is no valid SSID found after scanning.
> manifest: pull Matter Wi-Fi recovery optimization

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/matter/common/src/bt_nus_service.cpp
Implemented support for NUS commands terminated with various EOL (\n, \r, \r\n, none).
> samples: matter: lock NUS: EOL agnostic commands

- subsys/zigbee/osif/zb_nrf_platform.c
- west.yml
Associated PRs:
- https://github.com/nrfconnect/sdk-mcuboot/pull/280 (can be merged now, no dependency on this PR)
- https://github.com/nrfconnect/sdk-trusted-firmware-m/pull/110 (can be merged now, no dependency on this PR)
- https://github.com/nrfconnect/sdk-connectedhomeip/pull/333
- https://github.com/nrfconnect/sdk-homekit/pull/480 (confirmed by sdk-homekit maintainers that it is already merged)
- https://github.com/nrfconnect/sdk-find-my/pull/169
> Integrate nrfx 3.2.0

- samples/cellular/modem_shell/src/gnss/gnss.c
Added deleting of TOW precision to "gnss delete all" shell command.
> samples: cellular: modem_shell: Add deleting of GNSS TOW precision

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/modem_shell/src/main.c
- samples/cellular/modem_shell/src/shell.c
- samples/cellular/modem_shell/src/utils/mosh_print.c
- samples/cellular/modem_shell/src/utils/mosh_print.h
Added printing of last reset reason(s) when the application starts.
Added new shell command `version` which prints the application version information.
MOSH-468
> samples: cellular: modem_shell: Add printing of reset reason

- applications/serial_lte_modem/boards/thingy91_nrf9160_ns.conf
- applications/serial_lte_modem/boards/thingy91_nrf9160_ns.overlay
Disable hw-flow-control and increment buffer space to better match with default buffer sizing of Connectivity Bridge.
> applications: serial_lte_modem: Disable hwfc with Thingy:91

- .github/mergify.yml
- .github/test-spec.yml
- doc/_scripts/software_maturity/software_maturity_features.yaml
- doc/nrf/integrations.rst
- doc/nrf/introduction.rst
- doc/nrf/releases_and_maturity/repository_revisions.rst
- doc/nrf/releases_and_maturity/software_maturity.rst
- scripts/tag_west_repos.sh
- west.yml
With the introduction of Matter, all HomeKit customers are recommended to use Matter for new designs of smart home products. As a result, HomeKit Accessory Development Kit has been deprecated and removed from NCS.
Depends on:
> treewide: remove HomeKit from NCS

- doc/nrf/releases_and_maturity/known_issues.rst
The issue has been fixed in upstream and doesn't occure anymore in NCS v. 2.5.0.
> doc: Mark known issue NCSDK-18518 (BLE sample) as fixed for 2.5.0.

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/crypto/aes_cbc/src/main.c
- samples/crypto/aes_ccm/src/main.c
- samples/crypto/aes_ctr/src/main.c
- samples/crypto/aes_gcm/src/main.c
- samples/crypto/chachapoly/src/main.c
- samples/crypto/ecdh/src/main.c
- samples/crypto/ecdsa/src/main.c
- samples/crypto/hkdf/src/main.c
- samples/crypto/hmac/src/main.c
- samples/crypto/persistent_key_usage/src/main.c
- samples/crypto/rsa/src/main.c
Remove use of deprecated PSA type psa_key_handle_t. This concept has been merged with psa_key_id_t and this type should be used instead.
> samples: crypto: Remove use of deprecated PSA type psa_key_handle_t

- .github/test-spec.yml
Added additional triggers for Find My integration tests.
Jira: NCSDK-23909
> ci: Update CI-find-my-test test spec

- samples/bluetooth/mesh/light_ctrl/src/model_handler.c
- Fix wrongly used "printf" in Light control sample.
- Moves variable declaration outside label in light control sample to avoid build error for older compilers.
> samples: Bluetooth: Mesh: Fix Light CTRL sample issues

- applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/Kconfig.defaults
Set BT_GATT_AUTO_RESUBSCRIBE to n for unicast server, which prevents compatibility issue with Android 14. 
OCT-2755
> applications: nrf5340_audio: Disable auto resubscribe for unicast server

- doc/nrf/releases_and_maturity/releases/release-notes-1.3.0.rst
Replaces reference to the to-be-removed mpsl_radio_notification doc section. This module will be removed from mpsl.
> doc: fix ref to removed doc section

- doc/nrf/documentation/glossary.rst
Added description of GNSS scheduled downloads into glossary.
> doc: glossary: Add GNSS scheduled downloads into glossary

- CODEOWNERS
- applications/asset_tracker_v2/sample.yaml
- doc/nrf/device_guides/working_with_nrf/nrf91/nrf9160.rst
- doc/nrf/libraries/modem/nrf_modem_lib/nrf_modem_lib_trace.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- snippets/tfm-enable-share-uart/overlay-tfm-enable-share-uart.conf
- snippets/tfm-enable-share-uart/snippet.yml
Add snippet for tfm loggging sharing the same uart as the application utilizes. This allows the same configuration to be used for all samples without duplicationg it.
sharing the uart with the application can be useful when modem traces occupies the other uart.
> snippets: add snippet for tfm logging on shared uart

- west.yml
Update sdk-zephyr to pull in samples/bluetooth/hci_uart_async.
> manifest: Update zephyr for hci_uart_async

- CODEOWNERS
Add Aegir team to ncs/nrf/modules/trusted-firwmare-m as they own this code.
> CODEOWNERS: Add Aegir team to ncs/nrf/modules/trusted-firwmare-m

- lib/lte_link_control/lte_lc.c
Fixed a bug which would have caused connecting to LTE always fail after a failing attempt to read the current LTE registration status. Recovery would have required a reboot, but fortunately reading the LTE registration status should always succeed.
NRF91-1905
> lib: lte_link_control: Fix persistent LTE connect failure

- applications/nrf5340_audio/src/audio/Kconfig
Too high stack usage for BIS headset - LE_AUDIO_MSG_SUB
> Applications: nrf5340_audio: Increased stack size

- doc/nrf/device_guides/pmic.rst
- doc/nrf/device_guides/working_with_pmic/npm1300/developing.rst
- doc/nrf/device_guides/working_with_pmic/npm1300/features.rst
Added developing with npm1300 page.
Includes information on how to use PowerUP overlays.
> doc: working_with_pmic: Added developing with npm1300

- subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_rai.c
Sending of dummy packet after setting socket option SO_RAI_LAST is not needed anymore. Modem lib handles this.
Add dummy parameter to socket commands.
> net: lib: lwm2m_client_utils: Update RAI

- drivers/entropy/Kconfig
- subsys/nrf_security/Kconfig.legacy
- subsys/nrf_security/src/drivers/Kconfig
- subsys/nrf_security/src/legacy/CMakeLists.txt
- west.yml
Remove the configurations for cryptocell usable and use the standard HAS_HW configurations instead.
> manifest: Remove cryptocell usable configs and use HAS_HW instead

- samples/cellular/modem_shell/src/at/at_shell.c
- samples/cellular/modem_shell/src/link/link_shell.c
- samples/cellular/modem_shell/src/location/location_shell.c
- samples/cellular/modem_shell/src/ping/icmp_ping_shell.c
- samples/cellular/modem_shell/src/ppp/ppp_shell.c
- samples/cellular/modem_shell/src/rest/rest_shell.c
- samples/cellular/modem_shell/src/sms/sms_shell.c
- samples/cellular/modem_shell/src/sock/sock_shell.c
- samples/cellular/modem_shell/src/startup_cmd/startup_cmd_shell.c
Changing modules which parse subcommands manually into using Zephyr shell command macros.
Jira: MOSH-522
test-sdk-nrf: sdk-nrf-pr-12896
> samples: cellular: modem_shell: Subcommands into Zephyr macros

- applications/serial_lte_modem/src/slm_at_fota.c
Restore the call to dfu_target_reset() while making sure that it works upon application reset as well.
> slm: fix full modem firmware update corner case

- .github/test-spec.yml
Add subsys/nrf_security entry in test-spec.yml file as Sidewalk relays on crypto
> test-spec: Trigger Sidewalk on nrf_security changes

- doc/nrf/samples.rst
Added a note requested by PMT that states that the Zephyr examples are not tested by Nordic Semiconductor to work with the NCS releases. NCSDK-23685.
> doc: samples: Zephyr examples testing note

- applications/asset_tracker_v2/src/modules/location_module.c
When there is no cloud connection, the data won’t be sent to cloud but ATv2 is waiting for the cloud response. This causes location library to wait for the feedback too and hence further location requests are blocked until this ongoing request times out (5mins by default). The issue occurs after cloud wrapper is able to respond differently (success, fail, unknown) to LOCATION_EVT_CLOUD_LOCATION_EXT_REQUEST:
PR https://github.com/nrfconnect/sdk-nrf/pull/12116
This change checks if there is a cloud request pending when new sampling starts and cancels previous location request.
Jira: NCSDK-24105
> applications: asset_tracker_v2: Cancelling previous location request

- .github/workflows/pip-requirements.yml
* Adding `persist-credentials: false` to the checkout step
* Dropping checkout -> switch steps for checkout with ref
> ci: pip requirements workflow

- include/identity_key.h
- lib/identity_key/identity_key.c
- samples/keys/identity_key_usage/src/main.c
Add identity_key_free function which calls the
nrf_cc3xx_platform_identity_key_free function.
This makes the identity_key library a complete abstraction over the
nrf_cc3xx_platform library.
Make the identity_key_usage sample independent of the HW backend for
the identity key.
Remove the call for nrf_cc3xx_platform_init as this is handled by
existing initialization code, which also addresses initialization
without entropy.
Use identity_key library function for clearing identity key from
memory.
> identity_key: Make identity key abstraction independent of HW backend

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/nrf_cloud_multi_service/src/cloud_connection.c
MSS does not wait for connection success before printing "Connected to nRF Cloud".
This commit fixes this by making the connect_cloud function correctly block until connection either succeeds or fails.
IRIS-7090
> samples: cellular: mss: Wait for connection before printing connected.

- subsys/bluetooth/controller/hci_internal.c
This HCI command will replace the existing commands vs_set_auto_power_control_request_param and
vs_set_power_control_apr_handling. The two existing commands are interdependent.
> bluetooth: controller: add vs command set_power_control_request_params

- drivers/wifi/nrf700x/CMakeLists.txt
- drivers/wifi/nrf700x/Kconfig
- drivers/wifi/nrf700x/src/fw_load.c
- west.yml
Removes C based patch headers support and instead adds support for binary based patch.
> wifi: Bin patch loader

- applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_broadcast.c
- Reducing PA_SYNC_SKIP from 5 to 2
Since the timeout is set to PA_interval * 6 we shouldn't set the PA_SYNC_SKIP to 5, meaning we only have one shot at getting the PA per every 6 intervals
> applications: nrf5340_audio: Reduce PA_SYNC_SKIP

- applications/nrf5340_audio/tools/buildprog/buildprog.py
If there is a json file specified by the
AUDIO_KIT_IDS environmental variable, use this as
an alternative to the json file in the buildprog folder when building.
> applications: nrf5340_audio: Check if local json file exists.

- modules/tfm/zephyr/CMakeLists.txt
- modules/trusted-firmware-m/Kconfig
- subsys/nrf_security/Kconfig.psa
- subsys/nrf_security/cmake/psa_crypto_config.cmake
- subsys/nrf_security/configs/legacy_crypto_config.h.template
- subsys/nrf_security/configs/psa_crypto_config.h.template
Adds a configuration option to set the TF-M MM-IOVEC through Kconfig.
Also adds a configuration to set MBEDTLS_PSA_KEY_SLOT_COUNT through Kconfig.
> Add crypto-related configuration options

- applications/nrf5340_audio/src/audio/audio_datapath.c
- If a stream is started before data has been sent to the controller, the receiver will receive NULL packets with timestamp=0. These should not print a duplicated sdu_ref warning
> applications: nrf5340_audio: Ignore invalid duplicated SDUs

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- modules/trusted-firmware-m/Kconfig
Stop enabling TFM_LOG_LEVEL_SILENCE from the TFM_PROFILE_TYPE_MINIMAL option.
Without logging it becomes more difficult to debug failures, both in the non-secure image (secure faults), and in TF-M.
I assume we disabled logging at some point due to the 32kB resource usage limit. But my testing shows that we have space for this now, presumably due to some optimization work that we have done.
> tfm: Kconfig: Enable TF-M logging by default also with minimal conf

- drivers/wifi/nrf700x/src/qspi/inc/qspi_if.h
- drivers/wifi/nrf700x/src/qspi/src/device.c
- drivers/wifi/nrf700x/src/qspi/src/rpu_hw_if.c
This fixes a crash introduced in commit 2fb13ee104f("drivers: wifi: Move QSPI init to shim"). The QSPI/SPI configuration isn't proper assigned but used in RPU layer.
> drivers: wifi: Fix QSPI crash

- doc/nrf/releases_and_maturity/known_issues.rst
Remove KRKNWK-14756 as currently there are no requirements for latency time and the issue has been closed for v2.1.0
reference: KRKNWK-18018
> doc: openthread: remove KRKNWK-14756 from known issues

- drivers/serial/uart_ipc.c
- include/bluetooth/conn_ctx.h
- include/bluetooth/services/hids.h
- include/bluetooth/services/nsms.h
One of the ARM architure files, defined since long ago CONCAT having the exact same purpose as Zephyr's _CONCAT. Unfortunately this header is included almost always and the macro defined in all ARM based platforms,
which seems to have lead to many uses of this macro instead of _CONCAT.
Fix it by using _CONCAT instead, so that code works also with other architectures.
-----
Related to:
- https://github.com/zephyrproject-rtos/zephyr/pull/64839
- https://github.com/zephyrproject-rtos/zephyr/issues/64841
> treewide: Replace all uses of CONCAT with _CONCAT

- subsys/bluetooth/controller/Kconfig
- subsys/bluetooth/controller/hci_driver.c
- subsys/bluetooth/controller/hci_internal.c
CONFIG_BT_CTLR_SDC_CENTRAL_ACL_EVENT_SPACING_DEFAULT allows the user to set the central ACL event spacing and event length separately.
Read the API docs for more information.
> Bluetooth: Controller: New config for central event spacing

- west.yml
This API can be used to reduce code duplication.
> manifest: Update sdk-zephyr with bt_hci_get_ver_str()

- subsys/shell/Kconfig
Zephyr commit 188d2dfcca7 introduced changes where the log buffer size 
is not hardcoded, but calculated based on the LOG_MESSAGE_QUEUE_SIZE configuration.
This commit aligns the log queue size.
> shell: Align log message queue size for backends

- doc/_extensions/static/page_filter.mjs
The filtertag-container was not always inserted as the last element in the parent container.
> doc: extensions: page_filter: append tag container to parent

- applications/asset_tracker_v2/doc/cloud_module.rst
- applications/asset_tracker_v2/doc/data_module.rst
- applications/asset_tracker_v2/src/events/data_module_event.c
- applications/asset_tracker_v2/src/events/data_module_event.h
- applications/asset_tracker_v2/src/modules/cloud_module.c
- applications/asset_tracker_v2/src/modules/data_module.c
- lib/location/location.c
- lib/location/location_core.c
Moved P-GPS request handling from data module to cloud module. Simplified P-GPS request handling and aligned P-GPS and A-GNSS implementations.
Added a missing value to cloud module backoff delay table.
Did a couple of minor documentation fixes.
NCSDK-18093
> applications: asset_tracker_v2: Cleanup P-GPS integration

- lib/modem_antenna/Kconfig
- lib/modem_antenna/modem_antenna.c
Adds Kconfig entries and logic to support the external MIPI RFFE interface.
> lib: modem_antenna: add support for MIPI RFFE configuration

- .github/test-spec.yml
Some dependencies for lwm2m carrier lib was missing and a new project had been added to the bin folder so had to change that filter option.
> tools: added more filters to downstream tests for lwm2m carrier lib

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/bluetooth/throughput/src/main.c
By the same logic we used when we decided to encrypt the llpm sample in https://github.com/nrfconnect/sdk-nrf/pull/11720
we should also encrypt throughput sample. We should demonstrate the throughput we can get, with encryption on.
And conenct with 7.5ms interval to speed up encryption. The sample will switch to the interval selected by console (or 400ms if nothing is selected) before doing the throgputmeasurment.
Currently failing sample nightly test run, so that needs to be looked into before mergeing. https://jenkins-ncs.nordicsemi.no/blue/organizations/jenkins/latest%2Fsub%2Ftest-fw-nrfconnect-ble_samples/detail/master/9307/pipeline/
Disconnect with BT_HCI_ERR_INSTANT_PASSED
> samples: bluetooth: encrypt throughput sample

- doc/nrf/releases_and_maturity/known_issues.rst
fota_download library sends FOTA_DOWNLOAD_EVT_FINISHED when unable to connect.
> doc: Add known issue if NCSDK-24305

- drivers/mpsl/flash_sync/flash_sync_mpsl.c
This change allows the core dump module to store coredumps to flash when a fault exception has been raised.
Ref. NCSIDB-1033
> drivers: mpsl: permit non-sync flash operations from fault exceptions

- samples/bluetooth/central_uart/src/main.c
On failure to send data using the `bt_nus_client_send` function
the allocated buffer was not freed. This commit fixes that.
> samples: bluetooth: central_uart: Fix memory leak

- drivers/mpsl/flash_sync/flash_sync_mpsl.c
1cd8b82110b3dc4d344b52f58bb149d3edaf9134
introduced a check to see if the flash operation
is running on a hardfault or not.
But that check works only in ARM devices.
Let's fix it by adding a variant for the
POSIX architecture and an error for other
architectures.
-----
Related to https://github.com/nrfconnect/sdk-nrf/pull/12533
> drivers: mpsl: Fix for simulation

- samples/net/aws_iot/certs/ca-cert.pem
- samples/net/aws_iot/certs/client-cert.pem
- samples/net/aws_iot/certs/private-key.pem
Change the dummy credential file format according to credentials as generated by AWS IoT, to avoid mistake in copying certificate and private key.
> sample: aws_iot: Dummy credential format

- samples/wifi/scan/src/main.c
Previously, the code was only handling PSK (Pre-Shared Key) and open security types in scan results.
Add the change to handle all supported security types.
Fixes SHEL-2163
> samples: wifi: scan: Display security settings properly

- applications/nrf5340_audio/src/bluetooth/bt_management/controller_config/bt_mgmt_ctlr_cfg.c
The added API replaces an internal copy.
> applications: nrf5340_audio: Use bt_hci_get_ver_str()

- include/net/download_client.h
- subsys/net/lib/download_client/src/download_client.c
- subsys/net/lib/fota_download/src/fota_download.c
- tests/subsys/net/lib/download_client/src/main.c
Only the ECONNRESET is documented in Download Client as a possibility to rettry.
* Fix up the documentation regarding other error codes.
* Fix the FOTA download so that we don't assume retry.
* Add testcases for download client errors.
> net: fota_download: Only retry on ECONNRESET

- samples/net/aws_iot/src/main.c
- samples/net/azure_iot_hub/src/main.c
- samples/net/coap_client/src/main.c
- samples/net/mqtt/src/modules/network/network.c
- samples/net/udp/src/main.c
Add explicit calls to `conn_mgr_all_if_connect()` to connect to the network using the Zephyr NET connection manager.
This is needed due to `CONFIG_NRF_MODEM_LIB_NET_IF_AUTO_CONNECT` not being set by default anymore. This ensures that users gets a clear understanding of when connection is attempted by the sample.
> samples: net: Add explicit calls to `conn_mgr_all_if_connect()`

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/modem/lte_lc.h
- lib/lte_link_control/Kconfig
- lib/lte_link_control/lte_lc.c
- lib/lte_link_control/lte_lc_helpers.c
- lib/lte_link_control/lte_lc_helpers.h
- samples/cellular/modem_shell/src/link/link_shell.c
- tests/lib/lte_lc/src/main.c
- tests/lib/lte_lc_api/src/lte_lc_api_test.c
A new function for giving periodic TAU and active time in seconds. The library will handle conversion to bit field string representation specified in AT Commands Reference Guide, and 3GPP 24.008 Ch. 10.5.7.4a and Ch. 10.5.7.3.
Jira: NCSDK-23286
> lib: lte_link_control: Support for PSM config in seconds

- subsys/bluetooth/controller/Kconfig
- subsys/bluetooth/controller/hci_internal.c
Connection event triggers are an old feature from SoftDevice which we've decided to port to NCS.
> bluetooth: Add VS cmd for the connection event trigger feature

- doc/nrf/releases_and_maturity/releases/release-notes-2.2.0.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- lib/lte_link_control/Kconfig
- lib/nrf_modem_lib/Kconfig.modemlib
- lib/nrf_modem_lib/nrf_modem_lib.c
- lib/nrf_modem_lib/trace_backends/flash/Kconfig
- subsys/dfu/fmfu_fdev/Kconfig
- subsys/mgmt/fmfu/Kconfig
Remove deprecated KConfig options
- `NRF_MODEM_LIB_SYS_INIT`
- `NRF_MODEM_LIB_IPC_PRIO_OVERRIDE`
> lib: nrf_modem: remove deprecated Kconfig options

- west.yml
Fixes for WPA supplicant control interface socket response handling.
> manifest: sdk-hostap: Pull fixes for socket response handling

- .github/labeler.yml
This should be automatically added for nrf Wi-Fi related changes. This is used to enforce a mandatory QA upvote even though it is ready to be merged.
We are seeing an issue where the PRs are getting merged as they pass all mandatory checks but QA hasn't had a chance to verify it. So, this label which is enabled by default can be used similar to `doc-required`, and if its trivial and developer is confident enough then the label can be manually removed.
> ci: Add a new Wi-Fi QA required label

- doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
- doc/nrf/protocols/matter/index.rst
- doc/nrf/protocols/matter/overview/data_model.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- west.yml
Added information about ICD and their configuration to the low power configuration guide. Also updated the list of changes
introduced with the Matter v1.2.
> doc: matter: Extended low power configuration with ICD information 

- samples/cellular/location/sample.yaml
nrf9161dk_nrf9161_ns added to sample.yaml for all configurations.
> samples: cellular: location: Add nRF9161 to twister

- samples/wifi/scan/sample.yaml
- samples/wifi/shell/sample.yaml
Apart from checking the build these are also needed for generating memory footprints.
> samples: Add nRF9161 Wi-Fi tests to twister

- subsys/nrf_security/src/psa_crypto_driver_wrappers.c
In all the functions apart of the AEAD ones
the operation ID is set only if the setup call
of the driver returns success. This makes sure
that any subsequent calls (update/finish) will
not even reach the driver call if the setup was
not succesful. This aligns the AEAD to follow
the same pattern.
> nrf_security: Align AEAD setup of operation

- subsys/bluetooth/controller/hci_driver.c
- subsys/mpsl/init/mpsl_init.c
Previously it was a requirement that logging was enabled to print out assertions. As this configuration has significant memory footprint, allow printing the assertion message using verbose assertions or printk if it is enabled.
> MPSL/SoftDevice Controller: Lower footprint of assertion print

- applications/serial_lte_modem/src/main.c
> applications: serial_lte_modem: fix compilation with SLM_START_SLEEP

- subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c
- subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_security.c
Updated settings storage and load path buffer usage.
Fixed settings path buffer stack overlow at lwm2m_security.
> net: lwm2m_client_utils: LwM2M utils settings fix

- scripts/quarantine_zephyr.yaml
Adds a quarantine required for a new workflow, where tests from sdk-zephyr are executed within nrf context (using manifest from nrf)
> twister: quarantine: Add quarantine for tests from sdk-zephyr

- applications/nrf5340_audio/include/nrf5340_audio_common.h
- applications/nrf5340_audio/src/audio/Kconfig
- applications/nrf5340_audio/src/audio/streamctrl_broadcast_sink.c
- applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_broadcast.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c
- Delete PA sync if BIG sync is lost
- Restart scanning if PA sync create times out
- Increase stack size to account for additional pa_sync_delete
> applications: nrf5340_audio: Add timeout when creating PA sync

- doc/nrf/libraries/networking/lwm2m_location_assistance.rst
- include/net/lwm2m_client_utils_location.h
- samples/cellular/lwm2m_client/src/main.c
- subsys/net/lib/lwm2m_client_utils/CMakeLists.txt
- subsys/net/lib/lwm2m_client_utils/location/location_assistance.c
- subsys/net/lib/lwm2m_client_utils/location/location_retry_timer.c
- subsys/net/lib/lwm2m_client_utils/lwm2m/gnss_assistance_obj.c
- subsys/net/lib/lwm2m_client_utils/lwm2m/ground_fix_obj.c
- subsys/net/lib/lwm2m_client_utils/lwm2m/include/gnss_assistance_obj.h
- subsys/net/lib/lwm2m_client_utils/lwm2m/include/location_assistance.h
- tests/subsys/net/lib/lwm2m_client_utils/src/location_assistance.c
Removed location_assistance_init_resend_handler() and added location_assistance_retry_init() for dynamically
support resend handler functionality.
Updated location_assistance_set_result_code_cb: added Object id for indicate which Location object result code is updated.
New result code LOCATION_ASSIST_RESULT_CODE_NO_RESP_ERR which will be informed if server is not send any response.
Updated  assistance data request for do trigger lwm2m registration update in 60 seconds period for fixing to get pending requested data. After 3 minute Assistance data will be re-sended if re-send is enabled other wise LOCATION_ASSIST_RESULT_CODE_NO_RESP_ERR.
Updated Unit test and added test for timeout and re-send.
Signed-off-by: Juha Heiskanen <juha.heiskanen@nordicsemi.no>
> net: lwm2m_client_utils: Location assintance retry update

- subsys/nrf_security/Kconfig.psa
- subsys/nrf_security/cmake/psa_crypto_config.cmake
- subsys/nrf_security/configs/psa_crypto_config.h.template
- subsys/nrf_security/src/psa_crypto_driver_wrappers.c
Remove PSA_CRYPTO_ACCELERATOR_DRIVER_PRESENT, this is always true as all our drivers are considered "accelerators".
Remove PSA_CRYPTO_DRIVER_PRESENT, this appears to not have any valid use.
Remove PSA_CRYPTO_SECURE, this is not used anyway and is not set correctly currently, i.e. it is always false.
The configuration MBEDTLS_PSA_CRYPTO_SPM is the one that is being used.
NCSDK-22761
> nrf_security: Remove not useful PSA definitions

- doc/nrf/device_guides/working_with_nrf/nrf91/nrf9160.rst
- doc/nrf/device_guides/working_with_nrf/nrf91/nrf9160_gs.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added the steps for getting started with the Quick Start app for the soft launch stage.
NCSDK-23362.
----
> doc: nrf91: add quick start to nrf91 GSG

- west.yml
Patch from upstream with improvements of adv and
tfm psa usage to run them on CI on regular base
as well as improve system tests.
> manifest: sdk-zephyr: ble mesh adv and tfm psa usage improvements

- applications/nrf_desktop/src/modules/dfu.c
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
The currently booted image slot can be determined in build time. The commit also increases flexibility of bootloader integration.
Jira: NCSDK-24197
> applications: nrf_desktop: Remove dfu_slot_id function from dfu module

- doc/nrf/installation/install_ncs.rst
- doc/nrf/links.txt
- doc/nrf/protocols/matter/getting_started/tools.rst
- doc/nrf/releases_and_maturity/developing/adding_code.rst
This includes pulling some changes from upstream Zephyr that clarify the installation on macOS, aside from reworking the system-wide installation instructions.
> doc: getting started: Update system-wide instructions

- scripts/bootloader/keygen.py
A change calculates the digest out of the public key encoded in DER, and makes sure that it does not contain ‘ffff’, but provision.py still calculates the digest out of the raw public key (raw EC point), hence it may contain ‘ffff' and raise an error
This changes `keygen.py` to check the uncompressed points(raw EC points) digest if it contains `ffff`.
> bootloader: keygen: Fix regression in 0xFFFF check

- subsys/caf/modules/ble_state.c
Remove header include providing no symbols.
> caf: ble_state: Remove unneeded header

- doc/nrf/releases_and_maturity/known_issues.rst
Update workaround's known issue with the infomation about fixing the software diagnostic's feature-map.
> docs: update KRKNWK-17718 workaround's known issue in Matter

- samples/bluetooth/mesh/light/boards/nrf5340dk_nrf5340_cpuapp_ns.conf
- samples/bluetooth/mesh/light_ctrl/boards/nrf5340dk_nrf5340_cpuapp_ns.conf
- samples/bluetooth/mesh/light_dimmer/boards/nrf5340dk_nrf5340_cpuapp_ns.conf
- samples/bluetooth/mesh/light_switch/boards/nrf5340dk_nrf5340_cpuapp_ns.conf
Changes disable all host functionality that uses
tinycrypt in mesh samples.
> samples: Bluetooth: Mesh: no more tinycrypt in tfm psa based mesh

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/modem/nrf_modem_lib.h
- lib/nrf_modem_lib/lte_net_if/Kconfig
- lib/nrf_modem_lib/lte_net_if/lte_net_if.c
This PR adds a KConfig option which allows the default value of the NRF_MODEM_LIB_NET_IF_DOWN option to be changed at build time.
Also, while I was in the area, I updated the flag overrides to use a newly available API
> Allow build-time configuration of NRF_MODEM_LIB_NET_IF_DOWN

- lib/lte_link_control/lte_lc_helpers.c
- lib/lte_link_control/lte_lc_modem_hooks.c
Moved all logging from the library under one logging module. Added missing log level configuration, so that logging level can be configured at build time for the whole library.
> lib: lte_link_control: Improve logging

- CODEOWNERS
Change ownership from CIA to IOT team for the
/samples/cellular/modem_trace_flash sample.
> CODEOWNERS: Change for /samples/cellular/modem_trace_flash

- lib/nrf_modem_lib/Kconfig
- west.yml
Bring in build system updates.
> manifest: update nrf_modem build system files

- applications/matter_bridge/src/bridged_device_types/onoff_light.cpp
- applications/matter_bridge/src/bridged_device_types/onoff_light.h
- doc/nrf/releases_and_maturity/known_issues.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- west.yml
Added declaration of groups cluster and handling attribute read operations for the OnOff Light device.
> applications: Added support for groups in the Matter bridge

- samples/matter/common/src/bridge/bridge_manager.cpp
- samples/matter/common/src/bridge/bridge_manager.h
The Matter bridge application crashes after adding provider that exceeds the max allowed number. It happens only if the max number of allowed bridged endpoints is bigger and would allow to complete this operation.
Removed unique pointers used to manage the objects lifetime, as AddSingleDevice method already releases the memory, what leads to double-delete operations and application crash.
> samples: matter: Fixed crash after exceeding providers number

- applications/asset_tracker_v2/src/cloud/Kconfig.lwm2m_integration
Use path relative to Zephyr SDK to support out of tree builds.
> applications: asset_tracker_v2: Use path relative to Zephyr SDK

- doc/nrf/libraries/dfu/dfu_target.rst
A Kconfig option was missing the prefix CONFIG,
which made the link fail.
> doc: fix Kconfig option link in DFU target library doc

- CODEOWNERS
Update the CODEOWNERS file to use the ncs-cia team for code that the CIA team owns.
> CODEOWNERS: Replace individuals from CIA team with the ncs-cia team

- doc/nrf/device_guides/working_with_nrf/nrf52/developing.rst
- doc/nrf/protocols/bt/bt_mesh/dfu_over_bt_mesh.rst
- doc/nrf/protocols/bt/bt_mesh/fota.rst
DFU spec is adopted.
Experimental flag has been removed https://github.com/zephyrproject-rtos/zephyr/pull/64866
> doc: bluetooth: mesh: Remove experimental and not adopted sentences

- doc/nrf/libraries/networking/nrf_cloud.rst
One of the Kconfig options was missing the CONFIG prefix, which made the link fail. Fixed that and a few other minor things.
> doc: formatting fixes in the nRF Cloud library doc

- doc/_scripts/software_maturity/software_maturity_features.yaml
Add power management software maturity features.
software_maturity_scanner.py only runs on main nightly, so the new feature table will not be usable until after it has been merged.
Adding this information to the software maturity document will be handled as a later PR.
> doc: scripts: software_maturity: Added PMIC section

- samples/cellular/modem_shell/overlay-lwm2m.conf
- samples/cellular/modem_shell/src/cloud/cloud_lwm2m.c
Made LwM2M configuration more power efficient by taking tickless mode into use.
> samples: cellular: modem_shell: Take LwM2M tickless mode into use

- lib/location/method_gnss.c
- samples/cellular/modem_shell/src/gnss/gnss.c
- samples/cellular/modem_shell/src/location/location_srv_ext_lwm2m.c
Took LwM2M location assistance result callback into use. Added printing of an error if the location assistance request fails.
Fixed a Location library compilation error when both `CONFIG_LOCATION_METHOD_CELLULAR` and `CONFIG_NRF_CLOUD_AGNSS` are disabled.
> samples: cellular: modem_shell: Add handling for LwM2M location assistance errors

- samples/matter/thermostat/src/thermostat.matter
- samples/matter/thermostat/src/thermostat.zap
- samples/matter/thermostat/src/zap-generated/CHIPClusters.h
- samples/matter/thermostat/src/zap-generated/IMClusterCommandHandler.cpp
- samples/matter/thermostat/src/zap-generated/endpoint_config.h
Enabled mandatory thermostat attributes: occupied cooling setpoint and occupied heating setpoint.
> samples: matter: Enable mandatory thermostat attributes in zap

- subsys/net/lib/wifi_mgmt_ext/wifi_mgmt_ext.c
For the initial network no explicit select is needed. Once a Wi-Fi network is removed, then just adding and enable of the network won't suffice, we need to select the network for the WPA supplicant to start the association process.
This fixes a basic bug for non-initial associations.
> wifi: Fix L2AC non-initial associations

- doc/nrf/libraries/debug/memfault_ncs.rst
A couple of Kconfig options were not formatted
properly to make links. Fixed them and did some
minor language fixes.
> doc: Kconfig option fixes in Memfault library doc

- doc/nrf/libraries/networking/azure_iot_hub.rst
Added the missing def group for Azure IoT Hub DPS API.
> doc: fixing API docs of the Azure IoT Hub library

- modules/hostap/Kconfig
- subsys/nrf_security/Kconfig
- west.yml
Fix nrf_security enabling MBEDTLS options such as
MBEDTLS_MAC_SHA256_ENABLED when MBEDTLS itself is disabled.
Instead of enabling these options when not using MBEDTLS_BUILTIN only enabling these when the option to use the NRF_SECURITY mbedtls implementation choice.
> nrf_security: Fix nrf_security enabling options with MBEDTLS disabled

- samples/multicore/hello_world/Kconfig
It failed due to the Kconfig warning "BOARD_ENABLE_CPUNET defined without a type".
> samples: hello_world: fix build

- west.yml
Pull fixes for TCP queueing to prevent TX window overflow.
> manifest: Pull sdk-zephyr TCP queueing fixes

- sysbuild/CMakeLists.txt
- sysbuild/Kconfig.sysbuild
Prevents running PM (by default) on some boards which are either native (linux) or emulated
> sysbuild: Prevent running PM on some boards

- doc/nrf/libraries/modem/location.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/modem/location.h
- lib/location/scan_cellular.c
- tests/lib/location/prj.conf
- tests/lib/location/src/location_test.c
Change neighbor cell searches as follows:
- Do NCELLMEAS=1
- If more than one cell is requested, do NCELLMEAS=3,15
- If not enough GCI cells are found (by default 3), do NCELLMEAS=4,X, where X=3 by default
Even more significant change compared to the algorithm is that the cell count is not taking normal neighbors into account but only the current cell and GCI cells.
Jira: NCSDK-24585
> lib: location: Use NCELLMEAS=3,X

- doc/nrf/libraries/nrf_security/doc/driver_config.rst
Fix some small issues in the naming of the drivers and a few other stuff
> doc: nrf_security: Fix driver naming in configs

- doc/nrf/libraries/nfc/tnep/ch.rst
- doc/nrf/libraries/nfc/tnep/poller.rst
- doc/nrf/libraries/nfc/tnep/tag.rst
A few API links were not working due to
incorrect formatting.
Fixed them and some language, as well.
> doc: fixing API links in NCF TNEP library docs

- west.yml
Pulled fixed to enable commissioning of Matter over Wi-Fi device to 5 fabrics.
> manifest: Pulled fix for Matter over Wi-Fi

- samples/cellular/lwm2m_carrier/src/main.c
Fix use of implicitly defined function lte_lc_connect_async. When LWM2M_CARRIER is not enabled the header file is not included.
> samples: lwm2m_carrier: Fix use of implicitly defined function

- subsys/bluetooth/controller/hci_internal.c
Allows the controller to establish connections through the initiator and PAwR advertiser at the same time.
> bluetooth: add VS command

- applications/serial_lte_modem/doc/GNSS_AT_commands.rst
> applications: serial_lte_modem: fix AT#XGPS documentation example

- applications/serial_lte_modem/src/slm_at_host.c
- applications/serial_lte_modem/src/slm_uart_handler.c
- applications/serial_lte_modem/src/slm_uart_handler.h
Do not trigger the indicate pin when preparing to sleep.
Edit: Needed for 2.5.1 as well, I will create PR when this has gone into main.
> applications: serial_lte_modem: Fix indications in #XSLEEP=2

- samples/matter/common/src/bridge/Kconfig
- samples/matter/common/src/bridge/bridge_manager.cpp
- samples/matter/common/src/bridge/bridge_manager.h
Currently in the Matter bridge the dynamic endpoints doesn't have parent id set, which makes them do not work with some commercial ecosystems. This change fixes it by setting parent endpoint it to 1 (Aggregator).
> applications: Fixed setting parent ep id for the Matter bridge

- subsys/bluetooth/controller/Kconfig
- subsys/bluetooth/controller/hci_driver.c
* BT_CTLR_SDC_MAX_CONN_EVENT_LEN_DEFAULT can now be set to 0
* New: BT_CTLR_MIN_VAL_OF_MAX_ACL_TX_PAYLOAD_DEFAULT. To allow packing events tighter
> SoftDevice Controller: Update Kconfig entries managing event lengths

- sysbuild/Kconfig.sysbuild
Disables PM from being used on non-physical boards used in CI
> sysbuild: Disable PM by default for other CI boards

- modules/tfm/zephyr/CMakeLists.txt
Properly fixes an issue whereby the wrong (default) zephyr hex file was used for TF-M images when using sysbuild, when it should instead use the merged hex file
> tfm: Fix wrong sysbuild hex file when MCUboot is disabled

- applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
- applications/serial_lte_modem/src/lwm2m_carrier/slm_at_carrier.c
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
LWM2M_CARRIER_EVENT_APP_DATA event now carries path information, as it applies to more than a single object. To eliminate the possible ambiguity, an optional URI path parameter is added to the #XCARRIEREVT AT notification.
> applications: serial_lte_modem: add optional path to #XCARRIEREVT

- CODEOWNERS
This makes it easier to add and remove code owners for these areas. These folders are well known by the entire team.
> CODEOWNERS: Use @ncs-dragoon as code owners for MPSL and SDC

- west.yml
Regular OpenThread update to \`dc6bf36\`
> manifest: openthread: update to \`dc6bf36\`

- applications/nrf5340_audio/src/audio/audio_system.c
- applications/nrf5340_audio/src/audio/sw_codec_select.c
Fix bug where gateway got error
"Unsupported number of channels"
when doing bidir.
> applications: nrf5340_audio: Define channel_mode for decoder on bidir gw

- modules/hostap/Kconfig
MBO and WMM-AC are mandatory for WFA certification, so, cannot be disabled for memory saving.
> modules: hostap: Fix WFA mandatory features

- applications/nrf_desktop/doc/dfu.rst
- scripts/hid_configurator/README.rst
Change switches to using non-volatile memory term instead of flash in the documentation. Other non-volatile memory may be used for the update image slot. Change also applies a few additional doc improvements.
Jira: NCSDK-24518
> applications: nrf_desktop: Non-volatile memory instead of flash in docs

- samples/matter/light_bulb/Kconfig.sysbuild
- samples/matter/light_bulb/sysbuild/hci_rpmsg/prj.conf
- samples/matter/light_switch/Kconfig.sysbuild
- samples/matter/light_switch/sysbuild/hci_rpmsg/prj.conf
- samples/matter/lock/Kconfig.sysbuild
- samples/matter/lock/sysbuild/hci_rpmsg/prj.conf
- samples/matter/template/Kconfig.sysbuild
- samples/matter/template/sysbuild/hci_rpmsg/prj.conf
- samples/matter/thermostat/Kconfig.sysbuild
- samples/matter/thermostat/sysbuild/hci_rpmsg/prj.conf
- samples/matter/window_covering/Kconfig.sysbuild
- samples/matter/window_covering/sysbuild/hci_rpmsg/prj.conf
- sysbuild/CMakeLists.txt
- sysbuild/Kconfig.mcuboot
- sysbuild/Kconfig.netcore
- sysbuild/Kconfig.secureboot
- added support for nRF7002 DK to the sysbuild scripts
- adapted Matter samples configuration to support nRF7002 DK builds with sysbuild
> matter: samples: Integrated nRF7002 targets with sysbuild

- west.yml
These fix scan timeout races between wpa_supplicant and nRF70 driver.
> manifest: sdk-hostap: Pull scan timeout handling fixes

- samples/wifi/shutdown/README.rst
- samples/wifi/shutdown/src/main.c
In case the interface auto-start is disabled, Wi-Fi driver initializes and waits for user to bring the interface up. This options is useful for customers that need finer control over when Wi-Fi driver starts comms to nRF70 chipset (depends on driver).
The sample doesn't attempt to bring the Wi-Fi until user presses the button1.
Implements NRF7X-109.
> samples: wifi: shutdown: Add an option to disable auto-start

- west.yml
Pull Matter change that explicitly selects Wi-Fi interface for Matter over Wi-Fi instead of assuming it's the default.
> matter: make Wi-Fi manager use Wi-Fi interface only

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/modem/nrf_modem_lib.h
- lib/nrf_modem_lib/lte_net_if/Kconfig
- lib/nrf_modem_lib/lte_net_if/lte_net_if.c
- tests/lib/nrf_modem_lib/lte_net_if/src/main.c
This driver has a flag controlling the behavior of `net_if_down()`. One value of the flag lets `net_if_down()` bring the interface down, the other lets `net_if_down()` disconnect from the network. This flag can be set at run-time.
The application has at its disposal a dedicated API to bring the interface down, i.e. `net_if_down()`, and a dedicated API
to disconnect, i.e. `conn_mgr_disconnect()`.
Thus there is not need to change the behavior of `net_if_down()` based on a run-time flag to perform another API's operation.
At run-time, the application shall call one of the two functions to achieve the desired behavior.
However, the application may want to align `net_if_down()` behavior with that of other interfaces for the purpose of behaving similarly when `net_if_down()` is called outside …
> lib: nrf_modem: remove lte_net_if `_NET_IF_DOWN` flag

- applications/matter_bridge/src/bridged_device_types/humidity_sensor.cpp
- applications/matter_bridge/src/bridged_device_types/humidity_sensor.h
- applications/matter_bridge/src/bridged_device_types/onoff_light.cpp
- applications/matter_bridge/src/bridged_device_types/onoff_light.h
- applications/matter_bridge/src/bridged_device_types/temperature_sensor.cpp
- applications/matter_bridge/src/bridged_device_types/temperature_sensor.h
- samples/matter/common/src/bridge/bridge_manager.cpp
- samples/matter/common/src/bridge/matter_bridged_device.cpp
- samples/matter/common/src/bridge/matter_bridged_device.h
* implemented Identify cluster on all bridged devices
* aligned mandatory clusters' configuration
* removed redundant Descriptor cluster implementation
> applications: MatterBridge: added support for mandatory clusters

- doc/_extensions/software_maturity_table.py
If a feature is not available (e.g. homekit), just log it as a debug message but do not error, so the build can continue.
> doc: extensions: software_maturity_table: skip missing features

- subsys/bootloader/cmake/packaging.cmake
- sysbuild/CMakeLists.txt
- sysbuild/secureboot.cmake
sysbuild: Add missing network core secure boot configuration
Adds missing network core secure boot configuration for rpc_host
and multiprotocol_rpc images
sysbuild: Remove undefined code
Removes code that seemingly has never done anything
sysbuild: packaging: Fix network core image variables
Fixes not fetching the network core image default image
> sysbuild: Add missing network core secure boot config and remove undefined code

- west.yml
* Fix for SHEL-2196
* Fix for SHEL-2212
* WPA3 failure in low-memory conditions
Note: As the changes from 2.5.0 are all critical fixes, not creating a v2.5 maintenance branch.
> manifest: sdk-hostap: Pull in fixes from MAIN

- subsys/nonsecure/Kconfig
- west.yml
Fix nrf91 I2S and PDM peripherals not configured as non-secure.
> manifest: Update tf-m for nrf91 fix

- scripts/memory-threshold-list.yaml
This commit is part of a solution addressing developers' need to be aware of increases of memory footprints of applications under their maintainership.
The list added in this commit stores information about configurations, whose memory footprints should be monitored in the CI. Additionally, this list contains thresholds passing of which will trigger an automated warning on PRs introducing such changes. This dictionary is used as an input by a script computing memory increases, called by the CI after the twister stage.
jira: NCSDK-23524
> scripts: Add memory thresholds' list

- include/modem/lte_lc.h
- lib/lte_link_control/lte_lc.c
- lib/lte_link_control/lte_lc_helpers.c
- lib/lte_link_control/lte_lc_helpers.h
- tests/lib/lte_lc/src/main.c
- tests/lib/lte_lc_api/src/lte_lc_api_test.c
Improved Active-Time and periodic TAU interval descriptions in the API.
Improved periodic TAU interval parsing from `AT%XMONITOR` response. TAU is always reported either using T3412 extended or T3412 (legacy) timer by the network. If the TAU interval is missing, the API returns an error instead of `-1`, because periodic TAUs can not be disabled.
> lib: lte_link_control: Improve Active-Time and periodic TAU reporting

- west.yml
Pulls in switch of the remote for hal_nordic to nrfconnect/sdk-hal_nordic which contains hal_nordic with nrfx 3.1.0 with MDK 8.58.0 + minor fixes requested for the release
> manifest: Update sdk-zephyr with nrfx 3.1 with fixes for NCS 2.5.1

- west.yml
Pull cleanup of default Kconfig options for Matter applications to make the configuration easier to maintain and less error-prone.
> matter: pull Kconfig.defaults cleanup

- applications/nrf_desktop/README.rst
- applications/nrf_desktop/doc/dfu.rst
- applications/nrf_desktop/doc/dfu_lock.rst
- applications/nrf_desktop/doc/dfu_mcumgr.rst
- applications/nrf_desktop/doc/settings_loader.rst
- doc/nrf/releases_and_maturity/releases/release-notes-1.4.0.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change switches to using non-volatile memory term instead of flash in the documentation. Other non-volatile memory may be used aswell.
Jira: NCSDK-24793
> applications: nrf_desktop: NVM instead of flash in doc

- ext/oberon/psa/drivers/oberon_spake2p.c
- subsys/nrf_security/cmake/psa_crypto_config.cmake
- subsys/nrf_security/configs/psa_crypto_config.h.template
- subsys/nrf_security/src/drivers/Kconfig
Set's the define in Oberon could so Matter compatible of SPAKE2+ is used.
> crypto: Use Matter version of SPAKE2+

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/bluetooth/nrf/host_extensions.h
- subsys/bluetooth/CMakeLists.txt
- subsys/bluetooth/controller/Kconfig
- subsys/bluetooth/host_extensions/CMakeLists.txt
- subsys/bluetooth/host_extensions/hci_types_host_extensions.h
- subsys/bluetooth/host_extensions/host_extensions.c
- west.yml
This commits adds the vendor-specific API's for the LE Power Control Request Feature in Zephyr.
The support of feature is provided with the controller-based feature selection with BT_CTLR_LE_POWER_CONTROL_SUPPORT and is selectable via BT_TRANSMIT_POWER_CONTROL.
With the new APIs, the applications will:
be able to request a tx power change on remote device be able to set automatic Power Control Request when out of golden range of RSSI be able to set APR handling of remote apr to use in local tx power setting
Vendor-specific HCI commands:
Write remote transmit power level
Set LE Power Control Request parameters
> Bluetooth: Host: Add LE Power Control Request Procedure APIs

- doc/nrf/releases_and_maturity.rst
- doc/nrf/releases_and_maturity/migration_guides.rst
Created the landing page for the migrationg guides in their directory. This fixes subsection coming at the end of the releases page, which was hard to spot after the long ToC.
> doc: migration_guides: create index for guides

- applications/matter_bridge/Kconfig
- applications/matter_bridge/README.rst
- applications/matter_bridge/src/ble_providers/ble_environmental_data_provider.cpp
- applications/matter_bridge/src/bridge_shell.cpp
- applications/matter_bridge/src/simulated_providers/simulated_humidity_sensor_data_provider.h
- applications/matter_bridge/src/simulated_providers/simulated_onoff_light_data_provider.cpp
- applications/matter_bridge/src/simulated_providers/simulated_onoff_light_data_provider.h
- applications/matter_bridge/src/simulated_providers/simulated_temperature_sensor_data_provider.h
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/matter/common/src/bridge/bridge_manager.cpp
- samples/matter/common/src/bridge/bridge_manager.h
- samples/matter/common/src/bridge/matter_bridged_device.cpp
* added new Kconfig options allowing to select if the simulated OnOff data provider 
generates data autonomously or is controlled from CLI
* fixed unaligned copying of the generic data (void*)
* extended the documentation with the description of new Kconfigs
> applications: Matter Bridge: extend CLI with data provider setters

- subsys/net/l2_wifi_if_conn/l2_wifi_conn.c
If the persistence is enabled and In case WPA supplicant disconnects for seem reason e.g., AP de-auth due to wrong PSK, then L2AC should not issue a disconnect until the connection timeout is hit.
But default timeout is 0, so, we should check before we reschedule the timer to avoid disconnecting immediately, as we have a separate API which properly does this, use it.
Fixes SHEL-2249.
> wifi: l2ac: Fix connection persistence

- lib/location/scan_cellular.c
- tests/lib/location/src/location_test.c
Changing cellular positioning history search cell count from 15 to the maximum of 5 and requested cell count. While we can get more than requested number of cells fairly cheaply in terms of power and time, the measurements done with history search still require some power, and adding more and more cells doesn't provide clear benefits.
Jira: NCSDK-24585
> lib: location: NCELLMEAS=3,X to use MAX(5,cell_count)

- subsys/nrf_security/tfm/CMakeLists.txt
It is only the platforms with CC3XX that need NRF_CC3XX_PLATFORM so make this conditional.
Also, only set MBEDTLS_PLATFORM_ZEROIZE_ALT on CC3XX platforms because it is the CC3XX binary that provides this function.
> kconfig: tfm: Conditionally set NRF_CC3XX_PLATFORM and ZEROIZE_ALT

- subsys/bluetooth/scan.c
Fix scan filter for appearance, using the wrong byte-order to compare the appearance value.
NCSIDB-1145
> bluetooth: scan: Fix scan filter for appearance

- applications/asset_tracker_v2/README.rst
- applications/asset_tracker_v2/doc/firmware_architecture.rst
- applications/asset_tracker_v2/doc/modules.rst
To clean up the ToC for the Asset Tracker v2 docs, added a separate wrapper page for the modules.
> doc: Asset Tracker v2: adding modules wrapper page

- samples/crypto/psa_tls/src/psa_dtls_functions_client.c
In case psa_tls_send_buffer fails break ended the while loop without closing the socket, which is a potential resource leak and causes a coverity warning.
Also this way didn't allow any reconnect try, therefore changed the code to not stoop the processing loop and just make the logging output conditional
> samples: psa_tls: Fix resource leak error

- doc/nrf/device_guides/working_with_nrf/nrf91/nrf9160_gs.rst
- doc/nrf/device_guides/working_with_nrf/nrf91/thingy91.rst
- doc/nrf/device_guides/working_with_nrf/nrf91/thingy91_gsg.rst
- doc/nrf/links.txt
The Getting started documentation had small errors. This fixes those errors.
> doc: fix minor error in Thingy:91 documentation

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- lib/location/scan_cellular.c
Since GCI search won't return GCI cells but only normal neighbors in RRC connected mode, we will wait for RRC idle mode for 10s and proceed to GCI searches when RRC idle mode is reached. If RRC is still connected after 10s, GCI searches are skipped and we use results from NCELLMEAS=1 for cellular positioning.
Jira: NCSDK-24814
> lib: location: Wait RRC idle before GCI search

- Kconfig.nrf
- drivers/hw_cc3xx/hw_cc3xx.c
- modules/trusted-firmware-m/Kconfig
- modules/trusted-firmware-m/tfm_boards/common/tfm_hal_platform.c
- subsys/bluetooth/services/fast_pair/fp_crypto/Kconfig.fp_crypto
- subsys/nrf_security/Kconfig
- subsys/nrf_security/src/drivers/zephyr/Kconfig
- subsys/nrf_security/src/zephyr/CMakeLists.txt
- west.yml
> nrf_security: Do not select ENTROPY_GENERATOR from NRF_SECURITY

- subsys/nrf_security/configs/legacy_crypto_config.h.template
- subsys/nrf_security/configs/psa_crypto_config.h.template
Fix CMAC_ALT implementation requiring CBC cipher mode to be enabled.
> nrf_security: Fix CMAC_ALT requiring CBC cipher mode

- modules/nrfxlib/nrf_802154/sl/platform/nrf_802154_platform_sl_lptimer_zephyr.c
Use the kconfig options set by both the real HW
and the simulated targets so this module works equally in both.
> modules/nrfxlib 802154_platform_sl_lptimer: Support also nrf5340bsim

- west.yml
While printing SSID in wifi status command,
If the length is maximum(32 character).
It leads to buffer overflow. Changing the Format
Specifiers to print proper SSID.
> manifest: sdk-zephyr: Fix Print of SSID in WIFI status

- applications/matter_bridge/CMakeLists.txt
- applications/matter_bridge/Kconfig
- applications/matter_bridge/README.rst
- applications/matter_bridge/src/ble_providers/ble_bridged_device_factory.cpp
- applications/matter_bridge/src/ble_providers/ble_bridged_device_factory.h
- applications/matter_bridge/src/ble_providers/ble_lbs_data_provider.cpp
- applications/matter_bridge/src/ble_providers/ble_lbs_data_provider.h
- applications/matter_bridge/src/bridge_shell.cpp
- applications/matter_bridge/src/bridged_device_types/generic_switch.cpp
- applications/matter_bridge/src/bridged_device_types/generic_switch.h
- applications/matter_bridge/src/simulated_providers/simulated_bridged_device_factory.cpp
- applications/matter_bridge/src/simulated_providers/simulated_bridged_device_factory.h
- applications/matter_bridge/src/simulated_providers/simulated_generic_switch_data_provider.cpp
- applications/matter_bridge/src/simulated_providers/simulated_generic_switch_data_provider.h
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/matter/common/src/bridge/matter_bridged_device.h
* implemented new Matter device type: Generic Switch that is based on the Switch cluster
* combined the Generic Switch with the LBS BT device implementation
* updated documentation
* updated changelog
> applications: Matter Bridge: added support for Generic Switch

- applications/matter_bridge/src/chip_project_config.h
- west.yml
The DFU over BT SMP was sometimes failing becase advertising restart was not properly handled in the Matter BLEManager, due to the CHIP_DEVICE_CONFIG_CHIPOBLE_SINGLE_CONNECTION flag. Additionally it was required to pull changes in Matter code that removes collissions in handling peripheral and central related BT callbacks.
> applications: Fixed DFU over SMP for Matter bridge

- modules/hostap/src/supp_api.c
Enabling a network would trigger a scan. Since frequency is being set after enable_network, first scan is issued without any specific frequency.
> modules: hostap: Set frequency before enabling the network

- samples/wifi/shutdown/README.rst
The command is correct, but the Kconfig option in description is wrong.
> samples: wifi: shutdown: Fix typo in Kconfig

- doc/nrf/links.txt
This updates the links to the cloud integration example
to a version that has been aligned with nRF Connect SDK
v2.5.x
> app: asset_tracker_v2: update cloud integration example

- doc/nrf/releases_and_maturity/known_issues.rst
Add known issue for nrf9160 peripherals NRF_PDM and NRF_I2S are configure as secure peripherals and cannot be accessed by the nonsecure application without triggering a security violation.
> doc: known_issues: Add known issue peripherals are secure on nrf91

- doc/nrf/config_and_build/config_and_build_system.rst
- doc/nrf/config_and_build/modifying.rst
- doc/nrf/config_and_build/multi_image.rst
- doc/nrf/device_guides/working_with_nrf/nrf53/nrf5340.rst
- doc/nrf/device_guides/working_with_nrf/nrf91/nrf9160.rst
- doc/nrf/documentation/glossary.rst
- doc/nrf/installation/recommended_versions.rst
- doc/nrf/protocols/matter/getting_started/transmission_power.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Edited the overview page to gather conceptual information on one page. This removes some duplication and allows to expand procedures with more content in a future PR.
NCSDK-22324.
> doc: config_and_build: gather concepts on one page

- doc/nrf/external_comp/nrf_cloud.rst
- doc/nrf/includes/nrf_cloud_rest_sample_requirements.txt
- doc/nrf/links.txt
Change the securely generated credentials link
to match with the cloud document, as now we have
support for nRF9161.
NCSDK-23335
> doc: Change securely generating credentials link

- west.yml
Bring the commits needed by twister to pass parameters to pytest subprocess. It allows to select a specific testcase from a test suite.
> manifest: update twister to pass pytest parameters

- scripts/memory-threshold-list.yaml
Some changes cause memory bloat indirectly.
Author of commit  may be unaware of this,
and code owners may find out too late about the impact
of proposed changes on memory usage in their areas.
This commit adds information of who is maintaining
a given area. Listed gh accounts will be pinged 
in the automated warning messages.
Jira: NCSDK-21206
> scripts: memory-threshold-list: Add codeowners to the monitored test configurations

- subsys/nrf_security/Kconfig
- subsys/nrf_security/src/zephyr/CMakeLists.txt
Change select of entropy generator to depends on instead. This is to allow the PSA entropy generator to select nrf-security to provide PSA. To avoid any loops all nrf-security dependencies to entropy-generator needs to be depends instead.
> nrf_security: Change select of entropy generator to depends instead

- doc/nrf/links.txt
- doc/nrf/test_and_optimize/testing.rst
Monitor-mode debugging greatly enhances the debugging experience of Bluetooth applications and other applications where timing-critical code needs to continue execution when paused on a break-point.
This commit adds a section about this topic under the section `Testing and debugging an application`. This section should make it more visible to users how Monitor-mode debugging can be used in the context of the nRF Connect SDK with the tools provided by us.
References to documentation provided by the Zephyr project and SEGGER are added for users that want to get a deeper insight on how this works and how it can be used.
> doc: debugging: Document how to use Monitor-mode debugging

- samples/bluetooth/central_hids/README.rst
This change updates the sample output,
since the report ID in the HIDs keyboard is 0.
> samples: bluetooth: central_hids: Update documentation

- west.yml
This commit brings-in Zephyr with customizable asserts for the nRF 802.15.4 Radio Driver.
> manifest: zephyr: nRF 802.15.4 customizable asserts

- west.yml
This patch pulls the Matter fix for unexpected WiFi connection request that may happen when the SSID of interest is not available at first attempt during commissioning (which results in commissioning failure).
> manifest: Pull Matter fix for unwanted WiFi connection request

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_agnss.c
Switch to new /loc/agnss endpoint. Remove code that blocked QZSS requests over CoAP. Improve wording of comments.
Change the qzss_assistance_is_supported() function to check at compile-time instead of at runtime.
Jira: IRIS-7788, IRIS-7158
> net: lib: nrf_cloud: Update CoAP to support QZSS

- applications/serial_lte_modem/src/slm_util.c
- applications/serial_lte_modem/src/slm_util.h
Using nrf_modem_at_scanf() instead of nrf_modem_at_printf() allows to parse some of the AT response contents.
With some gymnastics we are effectively able to receive AT responses of up to two lines, which covers most use cases.
This need was discovered when realizing that interception of AT write commands also intercepts the corresponding test commands. Test commands have one response line of usage explanation, which must be forwarded properly to the caller.
> applications: serial_lte_modem: allow slm_util_at_cmd to receive AT response contents

- include/modem/at_cmd_custom.h
> lib: at_cmd_custom: remove prototypes of undefined functions

- applications/nrf5340_audio/CMakeLists.txt
Code should not be relying upon envrionmental values that were deprecated years ago, this resolves that issue
> applications: nrf5340_audio: Do not rely on environmental values

- boards/arm/thingy91_nrf9160/CMakeLists.txt
- boards/arm/thingy91_nrf9160/Kconfig.board
- boards/arm/thingy91_nrf9160/Kconfig.defconfig
- boards/arm/thingy91_nrf9160/thingy91_nrf9160_defconfig
- boards/arm/thingy91_nrf9160/thingy91_nrf9160_ns_defconfig
- boards/arm/thingy91_nrf9160/thingy91_pm_static_secure_boot.yml
- doc/nrf/device_guides/working_with_nrf/nrf91/thingy91.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- lib/adp536x/Kconfig
- subsys/bootloader/Kconfig
This PR fixes some problems that appears when trying to build for thingy:91 with `CONFIG_SECURE_BOOT` enabled:
- ADP536X needed to be excluded from the secure bootloader. Created a new kconfig symbol `IS_BOOTLOADER` to make it easier to check for both mcuboot and the secure bootloader at the same time.
- The thingy:91 board CMakeLists.txt enforced a static partition layout that did not include partitions for the secure bootloader and an extra slot for updating mcuboot. Added new kconfig options to allow the user to select what partition layout to use.
- Not directly related, but also added a kconfig option (`CONFIG_THINGY91_PARTITION_MANAGER`) to not inject a thingy:91 board static configuration for those that want to use dynamic or an application specific static partition layout.
This …
> boards: arm: thingy91: Secure boot

- modules/trusted-firmware-m/Kconfig.tfm.pm
Reduce the default amount of RAM given to TF-M on 53.
The less RAM given to TF-M, the more we have for other things.
The new value is guessed, not calculated.
> tfm: pm: Reduce the default amount of RAM given to TF-M on 53

- west.yml
This pulls in a null point dereference fix for Raw packet transmit
> manifest: sdk-nrfxlib: pull in Null point dereference fix

- doc/nrf/device_guides/working_with_nrf/nrf70/gs.rst
- doc/nrf/links.txt
- doc/nrf/protocols/wifi/index.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added a link to the Wi-Fi course on the Getting started and Protocols pages.
> doc: wifi: add link to Wi-Fi DevAcademy course

- CODEOWNERS
Added codeowners for documentation files at the top level of hierarchy.
> codeowners: add doc codeowners for top level

- lib/at_monitor/at_monitor.c
Make sure this situation is well visible during development.
> lib: at_monitor: assert when out of memory for notifications

- applications/connectivity_bridge/app.overlay
- boards/arm/thingy91_nrf52840/thingy91_nrf52840.dts
- boards/arm/thingy91_nrf9160/thingy91_nrf9160_common.dts
uart1 was enabled by default which was causing initialization in bootloader. It impacted application which was using uart1 because probably it was not uninitialized by the bootloader.
Ref: NCSIDB-1073.
> boards: arm: thingy91: Do not enable uart1 by default

- CODEOWNERS
Adding `subsys/net/openthread` as new codeowners entry.
> codeowners: add new codeowners entry for openthread.

- applications/serial_lte_modem/doc/HTTPC_AT_commands.rst
- applications/serial_lte_modem/doc/TCPUDP_AT_commands.rst
- applications/serial_lte_modem/src/http_c/slm_at_httpc.c
- applications/serial_lte_modem/src/slm_at_tcp_proxy.c
- applications/serial_lte_modem/src/slm_at_udp_proxy.c
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Allow #XTCPCLI, #XUDPCLI and #XHTTPCCON to set PEER_VERIFY socket option, and to disable the hostname verification via TLS_HOSTNAME socket option.
By default PEER_VERIFY is TLS_PEER_VERIFY_REQUIRED and hostname verification is done.
> applications: serial_lte_modem: allow to skip cert verify

- applications/nrf_desktop/doc/watchdog.rst
- applications/nrf_desktop/src/modules/watchdog.c
- boards/arm/nrf52810dmouse_nrf52810/nrf52810dmouse_nrf52810.dts
- boards/arm/nrf52810dmouse_nrf52810/nrf52810dmouse_nrf52810.yaml
- boards/arm/nrf52820dongle_nrf52820/nrf52820dongle_nrf52820.dts
- boards/arm/nrf52820dongle_nrf52820/nrf52820dongle_nrf52820.yaml
- boards/arm/nrf52833dongle_nrf52833/nrf52833dongle_nrf52833.dts
- boards/arm/nrf52833dongle_nrf52833/nrf52833dongle_nrf52833.yaml
- boards/arm/nrf52840gmouse_nrf52840/nrf52840gmouse_nrf52840.dts
- boards/arm/nrf52840gmouse_nrf52840/nrf52840gmouse_nrf52840.yaml
- boards/arm/nrf52dmouse_nrf52832/nrf52dmouse_nrf52832.dts
- boards/arm/nrf52dmouse_nrf52832/nrf52dmouse_nrf52832.yaml
- boards/arm/nrf52kbd_nrf52832/nrf52kbd_nrf52832.dts
- boards/arm/nrf52kbd_nrf52832/nrf52kbd_nrf52832.yaml
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Using the alias makes module's configuration more flexible.
Jira: NCSDK-25080
> applications: nrf_desktop: Use watchdog0 alias in watchdog module

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_agnss.c
This reverts commit 43dcee5b87298781746df22bb6fcae76cd3c35d8.
The agnss resource is not yet deployed to the
production server.
> Revert "net: lib: nrf_cloud: Update CoAP to support QZSS"

- doc/nrf/protocols/thread/tools.rst
Commit fixes:
- `ot-daemon` invoke command
- change default `ot-daemon` build command to build with newest thread version.
> doc: openthread: Update Thread tools documentation.

- west.yml
Pulls changed filter in spi_flash sample that allows to run Nordics' SoCs in the Twister. Before that they were filtered out for the sample.
> manifest: zephyr: Update sdk-zephyr with modified filter for spi_flash

- scripts/partition_manager/partition_manager.rst
The function add_partition_manager_config was prefixed with nvs_ to get exposed to OOT users to let them add partition manager configuration files since the commit bb1da8c7e25e368341634114a2746f733bb763e3.
The references in the documentation were not updated since then, and it still uses the former name.
This updates all the references for the function in the repository.
Jira: NCSDK-5493
> doc: update references to add_partition_manager_config

- applications/nrf5340_audio/CMakeLists.txt
Disable the RTC pretick anomaly workaround for B0N. The workaround causes a resource conflict between B0N and the controller, causing the controller to never start advertising. As the controller does not use RTC to wake up from sleep it is not affected by the anomaly.
> applications: nrf5340_audio: Disable RTC pretick workaround for B0N

- include/modem/lte_lc.h
- samples/cellular/modem_shell/src/link/link_shell.c
- samples/cellular/modem_shell/src/sock/sock_shell.c
- sock: Warn about the use of many RAI options
- link: a Better error text made when reading search configuration failed due to missing search configuration
> samples: cellular: modem_shell: Few small misc items

- samples/cellular/modem_shell/src/sms/sms.c
An error was shown for a valid SMS registration when the handle was a positive value instead of zero.
This was likely a leftover from early versions of SMS library which supported just one SMS registration.
> samples: cellular: modem_shell: Fix sms registration

- doc/nrf/libraries/others/supl_os_client.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- lib/supl/Kconfig
- samples/cellular/gnss/overlay-supl.conf
The SUPL client library requires the newlib C library. Added dependency to newlib in the Kconfig.
Added a configuration overlay file for building the GNSS sample with SUPL assistance support.
test-sdk-nrf: sdk-nrf-pr-13462
> lib: supl: Add dependency to newlib C library

- lib/edge_impulse/CMakeLists.txt
- scripts/quarantine.yaml
The edge impulse library is created using ExternalProject_Add.
This means the library is not a regular CMake library but an imported
library.
In general CMake is happy to link directly to a library using its path,
however in the edge_impulse library case, the edge_impulse itself
needs to link against the Zephyr kernel library as it calls kernel
functions. Therefore a link dependency to Zephyr kernel lib must be
created and to do so, edge impulse must be a known library target.
A static imported Edge impulse pointing to the external project
generated library file is created so that a CMake library target exists.
Jira: NCSDK-24520
> cmake: define edge_impulse as a static imported library

- samples/debug/memfault/sample.yaml
- samples/net/aws_iot/sample.yaml
- samples/net/azure_iot_hub/sample.yaml
- samples/net/coap_client/sample.yaml
- samples/net/download/overlay-tfm.conf
- samples/net/download/sample.yaml
- samples/net/https_client/sample.yaml
- samples/net/mqtt/sample.yaml
- samples/net/udp/sample.yaml
samples built for wifi is no longer using static credentials as default.
the static credential configs are now removed from twister tests.
> samples: net: wifi: update twister tests

- west.yml
Fixes a shell freeze seen during nightly stress test.
> manifest: sdk-hostap: Pull fix for shell freeze

- .github/test-spec.yml
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/udp/Kconfig
- samples/cellular/udp/README.rst
- samples/cellular/udp/src/main.c
This commit adds a new Kconfig option for configuring
the number of data transmissions to the server.
Shutdown the modem library when there are no more
transmissions to execute.
Moved sample to `CI-iot-samples-test` plan.
> samples: cellular: udp: cleanup and add way to shutdown modem

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- lib/location/method_gnss.c
If timeout for waiting for RRC idle mode expires and we are still in RRC connected mode, let's not try to get GNSS fix. It will only spend time and power without getting a fix. We also spend the location request timer and fallbacks are not even tried.
In addition, lowering the waiting time for getting to RRC idle mode and PSM from 5mins to 2mins.
> lib: location: Skip GNSS if not in RRC idle

- applications/asset_tracker_v2/doc/data_module.rst
- applications/asset_tracker_v2/src/main.c
- applications/asset_tracker_v2/src/modules/Kconfig.data_module
- applications/asset_tracker_v2/src/modules/data_module.c
- applications/asset_tracker_v2/src/modules/location_module.c
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Removed location from sample request when the Location module is disabled. Earlier also location was requested and because of this the sending of data was delayed until sampling timed out.
Removed battery and environmental data sampling when Sensor module is disabled.
Improved handling of case where all configured location methods are disabled using the run-time configuration.
Added missing Kconfig option for Wi-Fi sampling default value.
> applications: asset_tracker_v2: Fix requested data in sample request

- applications/matter_bridge/Kconfig
- applications/matter_bridge/prj_release.conf
- doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/matter/light_switch/Kconfig
- samples/matter/thermostat/Kconfig
- west.yml
Disable Read Client functionality for all samples except Matter Light Switch and Matter Bridge App.
It added around 6 kB of free space in some samples.
> samples: matter: update manifest and disable Read Client

- samples/matter/common/src/board.cpp
- samples/matter/common/src/board.h
After the recent samples' refactor we noticed a problem with the LED handling module. The LED state has to be saved before calling the ResetAllLeds method and restored after finishing some actions.
> samples: matter: Repair the common LED handling module

- doc/nrf/libraries/networking/nrf_provisioning.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
The library is used only with nRF Cloud.
Thus, renaming it to nRF Cloud device provisioning.
> doc: rename nRF Device provisioning library

- applications/serial_lte_modem/Kconfig
- applications/serial_lte_modem/doc/AT_commands_intro.rst
- applications/serial_lte_modem/doc/PPP_AT_commands.rst
- applications/serial_lte_modem/src/slm_at_host.c
- applications/serial_lte_modem/src/slm_ppp.c
- applications/serial_lte_modem/src/slm_ppp.h
This adds auto-start functionality so that the PPP link goes up/down when the network connection goes up/down.
Also, auto-restart is performed when the PPP peer disconnects so that reconnection can happen successfully.
Documentation for the #XPPP AT command is added. The rest is not yet documented as this is still a work in progress.
> applications: serial_lte_modem: second half implementation of PPP

- subsys/nrf_security/Kconfig.tls
Add Kconfig option for MBEDTLS_SSL_MAX_FRAGMENT_LENGTH since we have it as configurable in the configuration file but there was way of enabling it.
> nrf_security: Add Kconfig for SSL max fragment

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- west.yml
PSA Crypto API can be enabled in Matter samples by adding selecting `CONFIG_CHIP_CRYPTO_PSA` to y.
> manifest: matter: Initial version of PSA Crypto in Matter

- modules/hostap/src/supp_api.c
RSSI should only be retrieved for STA mode, but the check was wrong.
Fixes SHEL-2331.
> modules: hostap: Fix RSSI check for STA mode

- samples/wifi/shell/prj.conf
The wpa_cli configuration was put accidentally.
Remove it from shell sample.
> samples: wifi: Remove wpa_cli configuration

- samples/app_event_manager/sample.yaml
- samples/app_event_manager_profiler_tracer/sample.yaml
- samples/edge_impulse/data_forwarder/sample.yaml
- samples/edge_impulse/wrapper/sample.yaml
- samples/nrf_profiler/sample.yaml
- samples/peripheral/lpuart/sample.yaml
- tests/drivers/nrfx_integration_test/testcase.yaml
- tests/lib/edge_impulse/testcase.yaml
- tests/subsys/app_event_manager/testcase.yaml
- tests/subsys/bluetooth/fast_pair/storage/account_key_storage/testcase.yaml
- tests/subsys/bluetooth/fast_pair/storage/factory_reset/testcase.yaml
- tests/subsys/nrf_profiler/testcase.yaml
- tests/unity/example_test/testcase.yaml
- tests/unity/wrap_test/testcase.yaml
Entries in platform_allow are copies of integration_platforms. This change is needed for dynamic scope optimization for twister. A test_plan.py script selects which configurations to add to the scope. If a test is modified, it is scoped for all applicable platforms. This means for cases in the commit, selecting >600 platforms available in the upstream and nrf. Platform_allow works as a filter limiting the scope.
> tests: samples: Add platform_allow section to configs without it

- samples/matter/common/src/binding_handler.cpp
- samples/matter/light_switch/src/light_switch.h
- samples/matter/light_switch/src/shell_commands.cpp
After the unification of the matter-binding mechanism in the BindingData struct there is an additional callback for invoking the command function.
It must be assigned because it is used within the
BindingManager module.
Moreover, the RunBoundClusterAction method must check whether the InvokeCommandFunc is not NULL and does not allow doing any binding action otherwise..
The InvokeCommandFunc callback was not being assigned when we used UART CLI to send on/off command requests which cused a crash.
> samples: matter:  Repair bindings via uart in Light Switch Sample

- doc/nrf/releases_and_maturity/known_issues.rst
Add known issue for SDC when it stops generating HCI advertising reports after receiving extended advertising with AUX_CHAIN_IND packet
> doc: known_issues: Add known issue to SoftDevice Controller section

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- west.yml
This commit disable wpa config to reduce memorry usage.
> manifest: WPA supplicant advanced features disabled in Matter

- applications/asset_tracker_v2/src/ext_sensors/ext_sensors.c
Air pressure value was scaled incorrectly and the values sent to the cloud were not in Pascals. When the BSEC library is used, the value is already in Pascals and no scaling is needed, however the BME680 driver reports the pressure in kPascals.
> applications: asset_tracker_v2: Fix air pressure value

- applications/asset_tracker_v2/src/cloud/cloud_codec/lwm2m/lwm2m_codec_helpers.c
- applications/asset_tracker_v2/tests/lwm2m_codec_helpers/src/lwm2m_codec_helpers_test.c
Use signed 16 flavor for RSRP resource. The storage variable for RSRP has been changed in the connmon object. This is needed to avoid an error returned when writing to the variable using the signed 8 flavor.
> applications: asset_tracker_v2: Use signed 16 flavor for RSRP resource

- doc/nrf/installation/install_ncs.rst
Updated formatting in parsed-literal and code-blocks. Changed \ to / for Windows commands.
> doc: install_ncs: fix slash formatting

- applications/nrf5340_audio/src/audio/streamctrl_broadcast_sink.c
- applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_broadcast.c
* Delete PA sync if creating failed.
* Do not return if bt_bap_broadcast_sink_delete() return -EBADMSG.
> applications: nrf5340_audio: Improve broadcast sink error handling

- applications/serial_lte_modem/doc/AT_commands_intro.rst
- applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
- applications/serial_lte_modem/doc/FOTA_AT_commands.rst
- applications/serial_lte_modem/doc/FTP_AT_commands.rst
- applications/serial_lte_modem/doc/GNSS_AT_commands.rst
- applications/serial_lte_modem/doc/GPIO_AT_commands.rst
- applications/serial_lte_modem/doc/Generic_AT_commands.rst
- applications/serial_lte_modem/doc/HTTPC_AT_commands.rst
- applications/serial_lte_modem/doc/ICMP_AT_commands.rst
- applications/serial_lte_modem/doc/MQTT_AT_commands.rst
- applications/serial_lte_modem/doc/NRFCLOUD_AT_commands.rst
- applications/serial_lte_modem/doc/SMS_AT_commands.rst
- applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
- applications/serial_lte_modem/doc/TCPUDP_AT_commands.rst
- applications/serial_lte_modem/doc/TWI_AT_commands.rst
- applications/serial_lte_modem/doc/slm_data_mode.rst
- applications/serial_lte_modem/src/slm_at_host.c
- Fix and homogenize the first sentence of the AT command pages.
- Sort the pages by alphabetical order except from the "Generic AT commands" one that remains first.
> applications: serial_lte_modem: minor documentation improvements

- applications/machine_learning/README.rst
- applications/matter_bridge/doc/matter_bridge_description.rst
- applications/matter_weather_station/README.rst
- applications/nrf_desktop/README.rst
- applications/zigbee_weather_station/README.rst
- doc/nrf/config_and_build/config_and_build_system.rst
- doc/nrf/config_and_build/modifying.rst
- doc/nrf/documentation/glossary.rst
- doc/nrf/links.txt
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- doc/nrf/releases_and_maturity/software_maturity.rst
- doc/nrf/shortcuts.txt
Moved and expanded information in "Additions in the NCS" section of the build and config overview page. 
Edited build type sections.
Replaced includes with links in some application readme files.
NCSDK-22324.
> doc: config_and_build: reorganize additions in NCS

- CODEOWNERS
- west.yml
Replaced tomchy and sebastiandraus with milewr as Zigbee code owner.
> CODEOWNERS: Assign all Zigbee parts to milewr

- doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- west.yml
We need a mechanism to move the DAC private key from the factory data set to PSA ITS NVM storage during the first boot of the device.
The DAC private key will not exist in the factory data anymore after it moves and is protected from overwriting.
This feature is available only if the CONFIG_CHIP_CRYPTO_PSA config is set to y.
> manifest: Update Matter revision to pull PSA Crypto changes

- subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_shadow_info
- subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c
- subsys/net/lib/nrf_cloud/include/nrf_cloud_codec_internal.h
- subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
Fix the behavior of the automatic shadow info section sending.
Only send section data if the config is enabled.
Do not clear section data if the config is disabled. 
IRIS-6851
> net: lib: nrf_cloud: fix auto info section send

- applications/matter_bridge/CMakeLists.txt
- applications/matter_bridge/src/app_task.cpp
- applications/matter_bridge/src/app_task.h
- applications/matter_weather_station/CMakeLists.txt
- applications/matter_weather_station/src/app_task.cpp
- applications/matter_weather_station/src/app_task.h
- samples/matter/common/src/matter_init.cpp
- samples/matter/common/src/matter_init.h
- samples/matter/light_bulb/CMakeLists.txt
- samples/matter/light_bulb/src/app_task.cpp
- samples/matter/light_bulb/src/app_task.h
- samples/matter/light_switch/CMakeLists.txt
- samples/matter/light_switch/src/app_task.cpp
- samples/matter/light_switch/src/app_task.h
- samples/matter/lock/CMakeLists.txt
- samples/matter/lock/src/app_task.cpp
- samples/matter/lock/src/app_task.h
- samples/matter/template/CMakeLists.txt
- samples/matter/template/src/app_task.cpp
- samples/matter/template/src/app_task.h
- samples/matter/thermostat/CMakeLists.txt
- samples/matter/thermostat/src/app_task.cpp
- samples/matter/thermostat/src/app_task.h
- samples/matter/window_covering/CMakeLists.txt
- samples/matter/window_covering/src/app_task.cpp
- samples/matter/window_covering/src/app_task.h
- samples/matter/window_covering/src/window_covering.cpp
- west.yml
* Added common initialization module for all Matter samples to reduce maintenance effort and simplify code
* Documented Matter::Init module API
* Adapted all Matter samples and applications
* Cleaned up includes
> samples: matter: common initialization module

- scripts/quarantine_no_optimization.yaml
A nightly plan has a stage where tests are built executed on native_posix with NO_OPTIMIZATIONS confg. This stage requires its own quarantine.
> tests: Add quarantine for no optimizations plan

- doc/_extensions/options_from_kconfig.py
This option currently generates Kconfig warnings. Disable them to avoid polluting the build.
> doc: extensions: options-from-kconfig: Disable warnings

- subsys/net/lib/nrf_cloud/src/nrf_cloud_credentials.c
Removed the client certificate check for CoAP builds in nrf_cloud_credentials_check().
Only a CA and private key are required for the CoAP connection.
IRIS-7978
> net: lib: nrf_cloud: client cert not req'd for coap

- doc/nrf/libraries/caf/caf_overview.rst
- doc/nrf/libraries/caf/net_state.rst
Added APIs of the following events
to CAF docs:
* CAF Bluetooth LE SMP events
* CAF net state events
> doc: Add missing APIs to CAF

- samples/cellular/modem_trace_flash/README.rst
Remove `|connect_terminal|` entry to prevent having two serial terminals connected to the device at the same time when choosing the nRF Connect for Desktop Serial Terminal app. Having two serial terminals connected to the device will cause a garbled output.
> samples: cellular: modem_trace_flash: doc: fix

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- subsys/nfc/lib/Kconfig
- subsys/nfc/lib/platform_internal_thread.c
Fix handling data with 0 size when issuing a callback.
Jira: NCSDK-25211
> nfc: Fix handling 0 size data in nfc_platform

- subsys/bluetooth/services/hids.c
A number of erros paths in various _write functions do early returns after acquiring conn_ctx without releasing the context first. Fix this by converting affected early returns in to error cleanup gotos and sharing the "happy path" cleanup sequence.
> bluetooth: hids: Don't leak conn_ctx on error paths in writes

- doc/nrf/protocols/matter/getting_started/tools.rst
This commit fixes the URL format for GN binary.
I believe extra `\ ` characters are needed when URL is in highlights section, not in the console section.
> doc: matter: fix links to GN binary

- west.yml
This is before making the zephyr module separation.
> manifest: sdk-wi-fiquicktrack-controlappc: Update snapshot tag

- samples/wifi/radio_test/sample.yaml
Add nRF7000EK build support in twister using nRF9160DK to enable radio_tests on the nRF9160DK+nRF7000 combination.
> samples: wifi: radio_test: Add nRF7000EK to twister

- doc/nrf/releases_and_maturity/known_issues.rst
- west.yml
There was a bug discovered that in specific scenarios lead to Matter over Thread device application crash while processing DNS resolve response.
This PR pulls commit with a fix and adds known issues entry that describes the problem.
> manifest: Pulled fix for the Matter over Thread DNS resolution

- subsys/bluetooth/controller/Kconfig
When ISO is enabled, we want to set asside as much time as possible for ISO activities.
By setting BT_CTLR_SDC_MAX_CONN_EVENT_LEN_DEFAULT=0, we ensure that the ACL will utilize as little time as possible and avoid increasing the data length capabilities.
The BT_CTLR_SDC_CENTRAL_ACL_EVENT_SPACING_DEFAULT needs to be updated accordingly - we want the ACLs to be spaced apart to avoid scheduling conflicts. By selecting the value of 30 ms, we ensure that:
- The ACLs are non-overlapping given that they are using an interval which is greater than 30 ms.
- The ACL events are not overlapping with ISO events, given that the ISO interval is a multiple of 7.5 ms or 10 ms.
> Bluetooth: Controller: New default event length and spacing for ISO

- .github/labeler.yml
- .github/workflows/labeler.yml
- .github/workflows/license-reusable.yml
- .github/workflows/stale.yml
There are node.js deprecation warnings in GH Actions. This change will update actions to newer versions.
> ci: fix node.js deprecation warning

- doc/nrf/releases_and_maturity/known_issues.rst
Replaced TODO with commit sha containing workaround for the KRKNWK-18256 known issue.
> doc: Fixed Matter known issue that has TODO instead of commit sha

- west.yml
Pulled a fix from Matter that solves problem with update of mDNS records after new IPv6 prefix assignment.
> manifest: Pulled fix for the Matter over Wi-Fi mdns prefixes

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/net/nrf_cloud_coap.h
- subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c
This patch adds a method to nRF Cloud CoAP to send raw bytes. (tested on dev stage)
> lib: nrf_cloud: add nrf_cloud_coap_bytes_send

- include/net/wifi_credentials.h
- subsys/net/lib/wifi_credentials/wifi_credentials_shell.c
- subsys/net/lib/wifi_mgmt_ext/wifi_mgmt_ext.c
This patch adds management frame protection settings to the wifi_credentials library.
> lib: wifi_credentials: add support for setting MFP

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/net/download/src/main.c
- samples/net/https_client/src/main.c
For some devices, like the nrf91 series, it's important to gracefully bring down the network interface post-sample execution. This is fundamental for CI where many samples are executed and a lack of graceful bring down may lead to [reset loop restriction](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fnwp_042%2FWP%2Fnwp_042%2Fintro.html) being triggered.
> samples: net: add graceful bring down of network interfaces

- include/bluetooth/mesh/sensor.h
- subsys/bluetooth/mesh/sensor.c
- subsys/bluetooth/mesh/sensor.h
- subsys/bluetooth/mesh/sensor_cli.c
- subsys/bluetooth/mesh/sensor_srv.c
- subsys/bluetooth/mesh/sensor_types.c
This adds utility functions for converting struct bt_mesh_sensor_value
values to and from float and sensor value, and to string.
Signed-off-by: Ludvig Jordet <ludvig.jordet@nordicsemi.no>
> Bluetooth: Mesh: Add sensor value utils

- drivers/wifi/nrf700x/src/qspi/inc/rpu_hw_if.h
- drivers/wifi/nrf700x/src/qspi/src/rpu_hw_if.c
- drivers/wifi/nrf700x/src/shim.c
QSPI initialization reads QSPI slave registers, and if RPU isn't powered on this causes undefined behaviour (works on DK, but doesn't work on customer board with different QSPI).
Fix this by dividing the RPU configuration into init and enable, init doesn't use QSPI, and both QSPI init and RPU enable use QSPI.
Fixes SHEL-2375.
> drivers: wifi: Fix QSPI initialiation

- west.yml
The required property easydma-maxcnt-bits was missing for nrf5340_cpunet. This commit brings in zephyr with the fix.
> manifest: update zephyr nrf5340_cpunet easydma-maxcnt-bits

- doc/mcuboot/links.txt
Updated an outdated link on MCUboot doc set landing page. Bug reported by a developer.
> doc: mcuboot: update link to output files page

- applications/matter_bridge/src/bridge_shell.cpp
Fixed the string to int conversion for the Matter bridge pincode command. Before it was not able to correctly convert pincodes with leading 0 characters.
> applications: Fixed pincode command for the Matter bridge

- drivers/sensor/bme68x_iaq/Kconfig
- drivers/sensor/bme68x_iaq/bme68x_iaq.c
- drivers/sensor/bme68x_iaq/bme68x_iaq.h
- samples/sensor/bme68x_iaq/boards/nrf9160dk_nrf9160_ns.overlay
- samples/sensor/bme68x_iaq/sample.yaml
Adds support for a bme680x sensor SPI bus.
> drivers: sensor: bme68x_iaq: Add support for SPI bus

- samples/matter/common/src/bridge/bridge_manager.cpp
By the way of adding new Nrf namespace to the common module, the Matter callbacks were accidentally put into namespace and because of that they are not overriding the default weak implementations anymore and do not allow to handle external attributes by the bridge.
> samples: matter: Fixed namespaces for the Matter bridge

- tests/subsys/net/lib/lwm2m_client_utils/src/cellconn.c
- tests/subsys/net/lib/lwm2m_client_utils/src/connmon.c
- tests/subsys/net/lib/lwm2m_client_utils/src/security.c
3 test cases were named "init" which affected twister results. Ztest added 3 tests under the same name, parsed result of one of them and the rest were obtaining status null in the json report. With the new names all 3 tests are reported individually.
> tests: Resolve duplicates in test names

- scripts/memory-threshold-list.yaml
Add absolute limits for RAM and ROM usage for multiprotocol_rpmsg sample for nRF5340 network core:
* RAM: at least 10kB must be free
* ROM: at least 10% of the available memory must be free
> scripts: memory-threshold-list: add codeowners for multiprotocol_rpmsg

- samples/cellular/modem_shell/src/location/location_srv_ext_nrf_cloud.c
PR #13417 introduced a bug where location is never requested back to the device with external nRF Cloud service config on MQTT.
> samples: cellular: modem_shell: location: Ext service cellular fix

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/bluetooth/mesh/light_ctrl.h
- include/bluetooth/mesh/light_ctrl_cli.h
- include/bluetooth/mesh/light_ctrl_srv.h
- subsys/bluetooth/mesh/light_ctrl_cli.c
- subsys/bluetooth/mesh/light_ctrl_internal.h
- subsys/bluetooth/mesh/light_ctrl_srv.c
This adds support for running the light_ctrl model when the new Sensor
API is enabled.
Some API signatures in the light_ctrl_cli have been changed to use the
new bt_mesh_sensor_value when the new API is enabled.
Signed-off-by: Ludvig Jordet <ludvig.jordet@nordicsemi.no>
> Bluetooth: Mesh: Add new Sensor API support to light_ctrl

- west.yml
Updated Matter fork version to pull fixes for the DNS and memory leaks required for the v2.5.2.
> manifest: Updated Matter repository revision to pull v2.5.2 fixes

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps_utils.c
Fixed a bug which caused the prediction set update to fail. The failure happened when all downloaded predictions could not be written to flash sequentially.
NCSDK-25224
> net: lib: nrf_cloud_pgps: Fix bug in prediction set update

- lib/nrf_modem_lib/lte_net_if/lte_net_if.c
Add handling of reset loop event to notify users when this occurs.
> lib: nrf_modem_lib: lte_net_if: Add handling of reset loop event

- applications/asset_tracker_v2/doc/asset_tracker_v2_description.rst
- doc/nrf/device_guides/working_with_nrf/nrf91/nrf9161.rst
- doc/nrf/libraries/modem/nrf_modem_lib/nrf_modem_lib_trace.rst
- samples/cellular/modem_trace_flash/README.rst
Minor fixes to the following:
* Asset tracker - formating update after upmerge
* Modem_trace_flash - Removed a step from testing as the action is automatically done when Wireshark window is open
* developing with guide - minor fix
* Modem lib - Update for modem trace
> doc: Minor fixes to app, sample, and lib

- CODEOWNERS
Add @umapraseeda and @b-gent as code owners for
the Zoomin tag file.
> CODEOWNERS: Add new code owners for Zoomin tag file

- applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
OCT-2864
Change so timestamp is sent on every interval over zbus
> Applications: nrf5340_audio: timestamp fix

- doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
The Matter samples implementation has been significantly changed after v2.5.0, so the migration guide to v2.6.0 was required. Added the guide that describes code changes and presents how to apply them to the NCS 2.5.0 compliant application.
> doc: nrf: Added migration guide for the Matter samples

- west.yml
Fixes a crash during Zperf + iface down-up SNS test in SHEL-2359.
> manifest: sdk-nrfxlib : Pull Fix for TX de-init crash

- drivers/wifi/nrf700x/Kconfig
Default scan operation includes DFS channels which are passive. A significant amount of time is taken for scan to complete.
To reduce overall scan duration user can disable scanning on DFS channels.
> Support to disable DFS channels in scan

- west.yml
Fix the maximum channels allow for scan command
input. Also, example in scan arguments.
> manifest: sdk-zephyr: Fix the max channels in scan

- applications/serial_lte_modem/boards/nrf9160dk_nrf9160_ns.overlay
- applications/serial_lte_modem/boards/nrf9160dk_nrf9160_ns_0_14_0.overlay
- applications/serial_lte_modem/doc/FOTA_AT_commands.rst
- applications/serial_lte_modem/overlay-full_fota.conf
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
nRF9160 DK board revision 0.14 added external flash that is required for Full Modem FOTA.
Separate overlays for board revisions so we can build for older DK without using the flash.
> applications: serial_lte_modem: Allow building on older DK

- doc/requirements.txt
Make sure only new versions are used starting from >=0.27. This avoids pip querying old versions in PyPI with deprecated setuptools features.
> doc: requirements: update plantuml extension requirements

- doc/nrf/device_guides/working_with_nrf/nrf91/nrf9161.rst
- doc/nrf/links.txt
Add content and links of Board Configurator
in the developing with guide for nRF9161.
NCSDK-25358
> doc: Add board configurator info in the nRF9161 guide

- samples/bluetooth/throughput/src/main.c
This commit changes the order of the connection configuration. Negotiate the connection params with higher connection latency before changing the packet len.
This way we may be sure that the connection would not break due to timeout after the high packet len was set that cannot fit into configured connection latency.
JIRA: NCSDK-25371
> samples: bluetooth: throughput: Negotiate con params before packet len

- scripts/quarantine_zephyr.yaml
Adds sample.bindesc to the quarantine list due to instabilities of this sample.
> scripts: quarantine_zephyr: Add quarantine for sample.bindesc

- doc/_utils/redirects.py
Added redirect for links pointing to README, which now is gone.
> doc: nrf5340audio: add redirect

- doc/nrf/external_comp/nrf_cloud.rst
- doc/nrf/libraries/networking/nrf_cloud_coap.rst
- doc/nrf/links.txt
The nrf_cloud_provision.py script has been renamed to nrf_cloud_onboard.py.
IRIS-7817
> doc: nrf: handle script name change

- applications/matter_weather_station/src/app_task.cpp
- applications/matter_weather_station/src/chip_project_config.h
- samples/matter/common/src/board/board.cpp
Led Updates were handled wrongly and due to that Matter Weather Station signalized bad states.
Removed also redundant configs to not override Configs anymore.
> application: matter: Fix Matter Weather Station LEDs

- samples/matter/common/src/Kconfig
- samples/matter/common/src/app/task_executor.h
std::function<void()> is currently used as a task that is to be executed in the application thread, but this class is not trivially copyable so passing it over Zephyr's msgq may lead to resource leaks or other unexpected behavior in certain circumstances (for example, when a functor that std::function is initialized with is big enough that it cannot fit in the std::function static storage and must be allocated on heap).
Replace std::function with a lightweight replacement that ensures that it is only used with simple lambda functions that can be safely serialized.
> samples: matter: replace std::function with custom task

- samples/wifi/sr_coex/src/main.c
Now that WPA supplicant APIs enforce band requirement, need to properly configure the band in the connection as 0 (memset) is 2.4GHz only.
> samples: wifi: sr_coex: Fix 5GHz connection

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/net/download_client.h
- subsys/net/lib/download_client/Kconfig
- subsys/net/lib/download_client/src/download_client.c
Change the IPv6 to IPv4 fallback to also try to connect before doing the fallback. This will fix two known issues:
1. A DNS request for an IPv6 address may be successful even if the device does not have an IPv6 address.
2. The host is not reachable using IPv6 because of a network routing issue.
Change IPv6 support from compile time to runtime.
* Default attempt IPv6 connection first and fallback to IPv4 if DNS lookup or connect fails.
* Add configuration to struct download_client_cfg for the device to optimize the download sequence when it only support IPv4 or IPv6.
* Remove CONFIG_DOWNLOAD_CLIENT_IPV6.
Change the "Connecting to" log from repeating the full URL to show the resolved IP address. This will also show IP version used.
> Download client IPv6 to IPv4 fallback improvements

- west.yml
Pulls in a fix related to Bluetooth Isochronous channels.
> manifest: update sdk-zephyr revision with BT fix

- west.yml
Removed an unwanted debug message in sdk-nrfxlib that was checked in unintentionally.
> manifest: sdk-nrfxlib: pulling fix for unwanted debug message

- applications/matter_bridge/doc/matter_bridge_description.rst
- applications/matter_bridge/src/bridge_shell.cpp
The bridge pincode command has a bug that makes it use incorrect BT index and in result does not allow to insert pincode for devices with index different than 0.
> applications: Fixed pincode shell command in the Matter bridge

- samples/wifi/raw_tx_packet/src/wifi_connection.c
- samples/wifi/twt/src/main.c
Now that WPA supplicant APIs enforce band requirement, need to properly configure the band in the connection as 0 (memset) is 2.4GHz only.
> samples: wifi: Fix 5GHz connection

- samples/matter/light_bulb/README.rst
Add note about content length option instructing users to increase CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN for larger generated certificates that are provisioned to the TLS stack.
> samples: matter: light_bulb: Add note about content length option

- doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
The ICD related documentation describes idle mode duration parameter, as a base to distinguish SIT and LIT devices, while it should be slow polling interval.
> docs: Fixed Matter ICD related documentation

- west.yml
Updated the Zephyr revision in the manifest file to pull the new Bluetooth GATT API.
> manifest: update zephyr to pull new Bluetooth GATT API

- subsys/nrf_security/configs/nrf-config.h
mbedtls only requires that either AES or DES is enabled when CMAC is enabled.
But oberon requires that CIPHER is also enabled.
Fix this missing dependency to fix a check_config.h error I had at some point.
I don't know why we are translating from PSA to legacy or why ARM and Oberon have different check_config.h.
See "MBEDTLS_CMAC_C defined, but not all prerequisites" in oberon's and mbedtls's check_config.h files.
> nrf_security: mbedtls: define MBEDTLS_CIPHER_C when WANT_ALG_CMAC

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/net/nrf_cloud_coap.h
- samples/cellular/nrf_cloud_multi_service/Kconfig
- samples/cellular/nrf_cloud_multi_service/src/message_queue.c
- subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_alert.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_codec.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_log.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_log_backend.c
Add a bool confirmable flag to all the nrf_cloud_coap functions which previously assumed NON transfers were sufficient.
Update the nrf_cloud_multi_service sample with a Kconfig setting to enable use off CON transfers all the time.
Update nrf_cloud_alert.c and nrf_cloud_log_backend.c to choose CON transfers.
Jira: IRIS-8081
> net: lib: nrf_cloud: Add control over CoAP message reliability

- drivers/wifi/nrf700x/src/wifi_mgmt.c
- samples/wifi/twt/src/main.c
UMAC is not sending any feedback for the local teardown CMD, to keep the application design consistent, driver should always inform with the teardown status, it would be always success till UMAC implements the feedback.
> drivers: wifi: Notify app of local TWT tear down

- doc/nrf/links.txt
Update the broken link to TF-M ITS in the
"Running applications with Trusted Firmware-M" page.
NCSDK-25619
> doc: update TF-M ITS link

- applications/nrf5340_audio/src/bluetooth/Kconfig
- applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
OCT-2846
For bonding testing, only the Bluetooth address must change after each re-flash of the tester device. This also requires the bonding information on the tester to be cleared. A new testing menu for the Bluetooth has been added with a config to select the additional testing code within bt_mgmt.c to perform the desired tester actions.
> applications: nrf5340_audio: Fix bonding test with SDC

- subsys/net/lib/nrf_cloud/include/nrf_cloud_transport.h
- subsys/net/lib/nrf_cloud/src/nrf_cloud.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c
- tests/subsys/net/lib/nrf_cloud/cloud/src/fakes.h
- tests/subsys/net/lib/nrf_cloud/cloud/src/main.c
Reason is conflicting naming with zephyr native simulator nct_if.h
> net: lib: nrf_cloud: rename nct_ to nrfcloud_transport_

- applications/matter_weather_station/CMakeLists.txt
- doc/nrf/protocols/matter/index.rst
- doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/matter/common/src/Kconfig
- samples/matter/common/src/app/matter_init.cpp
- samples/matter/common/src/app/matter_init.h
- samples/matter/common/src/migration/migration_manager.cpp
- samples/matter/common/src/migration/migration_manager.h
- samples/matter/light_bulb/CMakeLists.txt
- samples/matter/light_switch/CMakeLists.txt
- samples/matter/lock/CMakeLists.txt
- samples/matter/template/CMakeLists.txt
- samples/matter/template/sample.yaml
- samples/matter/thermostat/CMakeLists.txt
- samples/matter/window_covering/CMakeLists.txt
- west.yml
In this commit added a mechanism that migrates all existing operational keys from mbedTLS-related settings storage to the PSA ITS secure storage.
After the migration the entries in the settings storage will not be avaliable anymore.
> manifest: Update Matter SDK revision to pull new crypto changes

- subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_security.c
Use SUPPORTED instead of ENABLED for the Connection Identifier settings.
This causes modem to send zero length CID to server, indicating that we support CID but don't require one for the reponse packets.
If server supports CID, it will generate one for us that we use for uplink packets.
There is really no benefit for using CID on both
direction. Using it uplink direction is enough.
> net: lwm2m_client_utils: Use DTLS_CID_SUPPORTED

- samples/matter/common/src/bridge/ble_connectivity_manager.cpp
We need to unpair the bounded device while the connection is closed.
Without that, the newconnection to the same device causes a fault.
> applications: matter: Add unpair to BLE disconnection handler.

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/modem_shell/CMakeLists.txt
- samples/cellular/modem_shell/Kconfig
- samples/cellular/modem_shell/README.rst
- samples/cellular/modem_shell/src/gpio_count/CMakeLists.txt
- samples/cellular/modem_shell/src/gpio_count/gpio_count.c
- samples/cellular/modem_shell/src/gpio_count/gpio_count.h
- samples/cellular/modem_shell/src/gpio_count/gpio_count_shell.c
- samples/cellular/modem_shell/src/mosh_defines.h
Added command `gpio_count` to count pulses on a GPIO pin. When pulse counting has been enabled, LED 2 on nRF91 Series DKs also shows the state of the pin input.
> samples: cellular: modem_shell: Add support for counting pulses

- applications/matter_weather_station/src/app_task.cpp
- samples/matter/common/src/board/board.cpp
In the UpdateDeviceState there was a mistake because we should not reset all LEDs in each state update.
> samples: matter: Fix device state updating

- subsys/nfc/lib/Kconfig
- subsys/nfc/lib/platform.c
- west.yml
Update nrfxlib manifest to new NFC library.
Add missing functionality to nfc_platform (including nRF54 support).
> manifest: nfc: Update nrfxlib manifest and update nfc_platform

- doc/nrf/protocols/matter/overview/data_model.rst
Fix typo in appliance device types table
Signed-off-by: Kelly Helmut Lord <kellyhlord@gmail.com>
> docs: matter: refrigerator typo fix

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/modem_shell/README.rst
- samples/cellular/modem_shell/src/uart/uart_shell.c
Added `uart baudrate` subcommand for changing the shell UART baudrate at runtime.
> samples: cellular: modem_shell: Add command for changing UART baudrate

- modules/hostap/src/supp_api.c
Enabling a network would trigger a scan. Since frequency is being set after enable_network, first scan is issued without any specific frequency.
Fixes SHEL-2417.
> wifi: Fix channel selection

- modules/trusted-firmware-m/tfm_boards/include/zephyr/sys/__assert.h
__assert.h declares the macro
\#define __ASSERT_POST_ACTION() tfm_core_panic()
which references tfm_core_panic().
But __assert.h is not including utilities.h which is the header that provides tfm_core_panic.
Fix the include dependency.
> tfm: __assert.h: Fix include

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/modem/location.h
- lib/location/location_core.c
- samples/cellular/modem_shell/src/location/location_shell.c
- tests/lib/location/src/location_test.c
Added event when location request has been started. This is useful when collecting metrics from positioning procedure. This event is only sent when CONFIG_LOCATION_DATA_DETAILS=y
> lib: location: Add LOCATION_EVT_STARTED

- drivers/wifi/nrf700x/CMakeLists.txt
- drivers/wifi/nrf700x/Kconfig
- drivers/wifi/nrf700x/inc/wifi_mgmt.h
- drivers/wifi/nrf700x/src/fmac_main.c
- drivers/wifi/nrf700x/src/wifi_mgmt.c
- west.yml
This code removes CONFIG_NRF700X_RAW_DATA_TX for setting mode.
> Remove raw tx config check for mode

- applications/matter_bridge/prj.conf
- applications/matter_bridge/src/bridge_shell.cpp
- samples/matter/common/src/bridge/Kconfig
- samples/matter/common/src/bridge/ble_bridged_device.h
- samples/matter/common/src/bridge/ble_connectivity_manager.cpp
- samples/matter/common/src/bridge/ble_connectivity_manager.h
The bridge BT recovery mechanism was refactored to:
* add backoff mechanism, which makes it scan the less frequently, the longer there are no lost devices detected
* optimize the recovery time by not repeating scan operation before adding every device
> samples: matter: Extended BT bridge recovery implementation

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/matter/template/CMakeLists.txt
- samples/matter/template/sample.yaml
Bluetooth LE SMP DFU has been added to the template sample, but it is disabled by default.
> samples: matter: Add SMP DFU to template sample

- drivers/wifi/nrf700x/src/fmac_main.c
In case Wi-Fi interface init fails and we get a multicast event, the RPU context is NULL causing a crash.
Add a NULL check for RPU context.
> drivers: wifi: Fix a crash in case Wi-Fi init fails

- modules/hostap/src/supp_api.c
Due to a typo, channel and frequency were compared causing the connection to fail for any combination.
> modules: hostap: Fix channel comparison

- drivers/wifi/nrf700x/src/wpa_supp_if.c
As VHT is 5GHz only, the VHT capabilities are NULL and causes a crash, add NULL checks for both VHT and HT.
> drivers: wifi: Fix crash in 2.4GHz association

- doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
Update the migration guide with the RSA config change.
> doc: Update migration guide with RSA config change

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- lib/modem_key_mgmt/modem_key_mgmt.c
Add mutex to protect the scratch_buf so it would be thread safe.
> lib: modem_key_mgmt: Protect shared buffer with mutex

- subsys/net/lib/lwm2m_client_utils/location/location_assistance.c
Fix a build warning regarding one static function being defined without a use.
All use is under #ifdef, so protect this as well.
> net: lwm2m_client_utils: Fix build warning

- samples/cellular/lwm2m_client/overlay-avsystem-bootstrap.conf
- samples/cellular/lwm2m_client/overlay-avsystem.conf
AVSystem uses TLV on its default settings.
> samples: lwm2m-client: Enable TLV on AVSystem overlays

- applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
OCT-2876
Warning prints will be supressed if the conn is down
> Applications: nrf5340_audio: Supress prints on ENOTCONN

- doc/nrf/applications.rst
- doc/nrf/links.txt
- doc/nrf/samples.rst
Added mention of the Filter by Board feature in the nRF VSC extension. VSC-2387.
> doc: apps and samples: filter by board in VSC

- west.yml
This patch pulls the change that sets the proper default configuration of the Wi-Fi band to support both 2.4 and 5G bands in all Matter Wi-Fi based samples.
> manifest: pull Matter fix for 5G Wi-Fi connection

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/nrf_cloud_multi_service/src/provisioning_support.c
Deactivate GNSS during certificate installation so that modem does not reject installation commands. This can sometimes happen if GNSS is not explicitly disabled and is in use prior to the cert installation provisioning command execution.
IRIS-8139
> samples: cellular: mss: Deactivate GNSS during provisioning

- west.yml
OSAL hdr cleanup changes to use internal hdrs [CAL-3923].
[CAL-3923]: https://nordicsemi.atlassian.net/browse/CAL-3923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> manifest: sdk-nrfxlib: Pull Osal header cleanup

- west.yml
This commit fix problem with interruption done by thread stack while preforming factory reset.
> manifest: matter: Lock thread stack before factory reset

- scripts/requirements-extra.txt
- scripts/requirements-fixed.txt
- scripts/tools-versions-darwin.yml
- scripts/tools-versions-linux.yml
- scripts/tools-versions-win10.yml
toolchain: zephyr-sdk:0.16.5
pip: upgrade packages with CVE notifications
| Name      | Version | ID                  | Fix Versions |
| --------- | ------- | ------------------- | ------------ |
| gitpython | 3.1.37  | PYSEC-2024-4        | 3.1.41       |
| jinja2    | 3.1.2   | GHSA-h5c8-rqwp-cp95 | 3.1.3        |
| pillow    | 10.0.1  | GHSA-3f63-hfp8-52jq | 10.2.0       |
No fix available yet, added to whitelist. 
| Name      | Version | ID                  | Fix Versions |
| --------- | ------- | ------------------- | ------------ |
| ecdsa     | 0.18.0  | GHSA-wj6h-64fc-37mp |              |
> toolchain: zephyr-sdk:0.16.5

- applications/nrf5340_audio/src/audio/le_audio_rx.c
- applications/nrf5340_audio/src/modules/audio_usb.c
OCT-2889
In high CPU use conditions we may get USB TX warnings. This may in turn cause an overload of prints
further stressing the CPU
> Applications: nrf5340_audio: Reduced prints

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/modem_shell/src/sock/sock.c
This commit updates the sample to also connect UDP sockets. UDP sockets are connectionless, however
the modem library supports invoking `connect` on a UDP socket to set its peer address.
This simplifies the use of `send` which will internally use the peer address.
This also fixes a problem when setting `RAI_NO_DATA` on a UDP socket, since `RAI_NO_DATA` requires the socket to be connected.
> samples: cellular: modem_shell: connect UDP sockets

- applications/matter_bridge/sample.yaml
- applications/matter_bridge/src/ble_providers/ble_lbs_data_provider.cpp
- applications/matter_bridge/src/bridge_shell.cpp
- applications/matter_bridge/src/bridged_device_types/onoff_light_switch.cpp
- applications/matter_bridge/src/bridged_device_types/onoff_light_switch.h
- applications/matter_bridge/src/simulated_providers/simulated_onoff_light_switch_data_provider.cpp
The binding support was refactored for the onoff light switch in a wrong way and CI didn't caught it, because the build was not in twister.
Fixed the implementation and added configuration including onoff switch to sample.yaml.
> applications: Fixed onoff light switch in Matter bridge

- samples/wifi/radio_test/radio_test_subcommands.rst
Remove the "Experimental" comment from compute_optimal_xo_val description.
SHEL-2429
> doc: wifi: remove "experimental" comment from Radio sample

- applications/asset_tracker_v2/src/cloud/cloud_codec/lwm2m/lwm2m_codec_helpers.c
- applications/asset_tracker_v2/tests/lwm2m_codec_helpers/src/lwm2m_codec_helpers_test.c
Two issues were found on Asset Tracker when LwM2M protocol is used:
* Device data is initialized only after we have registered to server. This might lead to situation that server fetch empty strings from Device object. Move few initialization calls to setup function.
* String terminator was not counted in the buffer length. This is a bug as `lwm2m_set_res_buf()` requires full buffer, not just `strlen()`. Some payload codecs have been ignoring this, but current CBOR codec seem to strip last character from strings.
This does not completely fix Asset Tracker v2 as I am not familiar with the state machines. Someone should go through the state machine and ensure that following data is filled up before we register to server:
* lwm2m_codec_helpers_set_modem_dynamic_data
* …
> Asset tracker: Fix LwM2M device data

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/gzp.h
- subsys/gazell/Kconfig
- subsys/gazell/gzp_device.c
Gazell improvement for nrf_desktop integration.
The PR includes the following change.
- gzp_config header overrides to make application change host id and secret key without modifying subsys.
- Clear host id and sys address in memory without handling it in application.
> gazell improvement

- applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h
- applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
OCT-2852
After the upmerge, some of the prints where incorrect and there was a increase in the files built. 
The printing issue was due to the change in the return data from bt_audio_codec_cfg_get_freq() and bt_audio_codec_cfg_get_frame_dur(). These now return the frequency and duration as  enums IDs from bt_audio_codec_config_freq and bt_audio_codec_config_frame_dur respectively. Previously these functions returned the Hz and us values. Two new functions have been included that read the IDs and convert them to the required format. 
The number of build files has increased as the CMSIS-DSP library is build with all functions. The functions are in separate files and where optionally built by CONFIGs. These CONFIGs have been removed and the complete library is now built. Resulting in a …
> applications: nrf5340_audio: Issues after upmerge

- drivers/wifi/nrf700x/src/fmac_main.c
- samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
- west.yml
[SHEL-1493]: Replace the string with a structure definition for better readability.
[SHEL-1493]: https://nordicsemi.atlassian.net/browse/SHEL-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> manifest: sdk-nrfxlib: Replace RF parameter string with a structure definition

- subsys/dfu/dfu_target/src/dfu_target.c
- subsys/dfu/dfu_target/src/dfu_target_stream.c
* Unset the current DFU target on successful reset.
* Do not trigger a flash erase if stream reset is triggered on an unspecified flash device. This can happen after reset is done on a DFU target that failed to initialize properly.
> subsys: dfu: dfu_target: fix reset of uninitialized targets

- applications/nrf5340_audio/broadcast_source/main.c
- applications/nrf5340_audio/include/nrf5340_audio_common.h
- applications/nrf5340_audio/src/audio/audio_datapath.c
- applications/nrf5340_audio/src/audio/audio_system.c
- applications/nrf5340_audio/src/audio/audio_system.h
- applications/nrf5340_audio/src/audio/sw_codec_select.h
- applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h
- applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
- applications/nrf5340_audio/unicast_client/main.c
- applications/nrf5340_audio/unicast_server/main.c
- Send direction from bt_stream to main.
- Differentiate between timestamp used for pres and drift compensation
- Change log in main files to prefix main
- Add helper function for getting stream direction
- Turn on just-in-time for bidirectional gateways
- OCT-2875
> applications: nrf5340_audio: Add direction to zbus from bt_stream

- doc/nrf/protocols/matter/index.rst
The table for SDK and specification versions for Matter is missing some releases. This adds them to the table.
Also updates the wording on the PSA Crypto API note to not mention a version of the nRF Connect SDK that isn't out yet.
> doc: Matter: update version table

- samples/cellular/lwm2m_client/src/shell.c
- subsys/net/lib/lwm2m_client_utils/location/location_assistance.c
net: lwm2m_client_utils: Don't expect result from inform event
Do not always expect the result from Ground Fix events.
When we only do "inform" event, where 'Send location back' is
set to false, the Coiote server is not sending any response back
towards us.
When we receive acknoledgement from send operation, assume the
whole ground fix event is OK.
FYI: @simensrostad   I found the root cause for ground fix retrying.
> net: lwm2m_client_utils: Don't expect result from inform event

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- subsys/net/lib/download_client/src/download_client.c
When receiving data from HTTP stream, we might end up in a situation where we have received just few bytes more than an HTTP header.
Forwarding too little data to the callback may cause problems on libraries that try to detect the download type from the first bytes.
Prevent this by always trying to fetch full buffer, until we forward that to the callback.
> net: lib: download_client: Only forward full buffers to app

- subsys/bluetooth/controller/hci_internal.c
Add support for vendor specific hci command iso_read_tx_timestamp.
> Bluetooth: Controller: add vs tx timestamp support

- subsys/mpsl/fem/Kconfig
We want to use the more generic HAS_HW_NRF_PPI or HAS_HW_NRF_DPPIC instead as this is more future proof.
The selection mechanism will also fit the new 54H and 54L once that is supported.
> mpsl: fem: kconfig: No soc-specific config entries to select PPI/DPPI

- include/memfault_ncs.h
- modules/memfault-firmware-sdk/Kconfig
- modules/memfault-firmware-sdk/memfault_ncs_metrics.c
Permit overriding the built-in NCS
`memfault_metrics_heartbeat_collect_data()` with a custom version.
Application will need to select
`CONFIG_MEMFAULT_NCS_IMPLEMENT_METRICS_COLLECTION=n`, then implement the function elsewhere.
Expose the `memfault_ncs_metrics_collect_data()` data collection function so a user can run that in addition to their own metrics.
> modules: memfault: Enable user-provided heartbeat collect

- applications/asset_tracker_v2/overlay-lwm2m.conf
- applications/asset_tracker_v2/src/cloud/lwm2m_integration/lwm2m_integration.c
- applications/asset_tracker_v2/tests/lwm2m_integration/src/lwm2m_integration_test.c
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Asset Tracker seem to be lacking some of the power optimizations that have been done in LwM2M engine and LwM2M client sample, so I'll create this draft PR to propose these into the Asset Tracker as well.
Our LwM2M client sample uses all of these already.
Configure various LwM2M related settings to optimize power usage of the device:
* Enable DTLS Connection Identifier
* Keep sockets open while in QUEUE_RX_OFF (Stop polling)
* Do update once a hour and try to request similar periodic tracking area update intervall from LTE network.
* Do LwM2M Udate when LTE Tracking area update is requested.
* Request same active time as our QUEUE mode polling time is.
* Enable eDRX with smallest interval and short paging window. This is responsive so CoAP timeouts usually don't happen.
* Enable LwM2M …
> applications: asset_tracker_v2: Power optimize LTE usage

- doc/nrf/dev_model_and_contributions/ncs_distro.rst
Use our Nordic-maintained example-application as a model for redistributing NCS using a manifest repo.
> doc: distro: Point to example-application

- doc/nrf/protocols/matter/getting_started/testing/thread_one_otbr.rst
The instructions for configuring the Thread Border Router and controller on one device mention macOS as an option. While macOS should work, we don't test and verify, so this removes the mention from the page.
NCSDK-22350
> doc: Matter: remove mention of macOS from one device Thread Border

- applications/matter_bridge/Kconfig
Set CONFIG_BT_EXT_ADV to support simultaneous BT central scan and peripheral advertising also for configuration with security layer disabled.
Reference: BLUETOOTH CORE SPECIFICATION Version 5.4 | Vol 4, Part E 7.8.4
> applications: Matter Bridge: allow parallel scan and advertising

- lib/modem_info/modem_info.c
- modules/memfault-firmware-sdk/memfault_lte_metrics.c
Set the Memfault metric `ncs_lte_operator` to "Not reported" when
the modem does not provide an operator name to the application.
> modules: memfault: Report unkown operator if modem doesn't give one 

- samples/cellular/lwm2m_client/src/lwm2m/lwm2m_device.c
- subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_adv_firmware.c
- subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c
- tests/subsys/net/lib/lwm2m_fota_utils/src/stubs.c
- tests/subsys/net/lib/lwm2m_fota_utils/src/stubs.h
In LwM2M Device object, as well as Advanced firmware object, we have modem hardware type visible.
Query this information from modem_info library, instead of using build-in values.
This allows same FW to run on 9161 and 9151 and we still see from server side which HW is used.
> net: lwm2m_client_utils: use modem_info to find HW version

- subsys/bluetooth/controller/Kconfig
- subsys/bluetooth/controller/hci_driver.c
Define CONFIG_BT_CTLR_SDC_CONN_EVENT_EXTEND_DEFAULT to allow
users to enable and disable connection event extension in a simpler
way.
We do not want to enable connection event extension when
802.15.4 protocols are enabled as we would like to reserve as much time
as possible for those protocols.
Disabling the setting has no practical consequence when connected
to a single Bluetooth device, but it improves performance
significantly when connected to two or more Bluetooth devices.
Ref: DRGN-21305
> Bluetooth: Controller: Define BT_CTLR_SDC_CONN_EVENT_EXTEND_DEFAULT and disable it for 802.15.4

- samples/wifi/raw_tx_packet/src/wifi_connection.c
- samples/wifi/scan/src/main.c
- samples/wifi/shutdown/src/main.c
- samples/wifi/sr_coex/src/main.c
- samples/wifi/sta/src/main.c
- samples/wifi/twt/src/main.c
The samples are showing junk character in SSID because of the length of ssid is maximum(32 character) which leads to buffer overflow.
> Buffer Overflow fix

- subsys/bluetooth/controller/hci_driver.c
With the new ISO API some values were left unitialised, as they were thought to be the default values.
These have to be explicitly set, otherwise are garbage.
> bluetooth: controller: hci_driver: Fix ISO API use

- scripts/requirements-build.txt
- scripts/requirements-fixed.txt
- scripts/tools-versions-darwin.yml
- scripts/tools-versions-linux.yml
- scripts/tools-versions-win10.yml
This compiler is used for nRF54 code samples.
> tools: add riscv64-zephyr-elf to toolchain

- drivers/wifi/nrf700x/src/net_if.c
- drivers/wifi/nrf700x/src/wifi_mgmt.c
- drivers/wifi/nrf700x/src/wifi_mgmt_scan.c
- drivers/wifi/nrf700x/src/wpa_supp_if.c
To fix crashes during interface de-init, add a lock + NULL check before de-referencing FMAC handle and invoking FMAC APIs. As this is expected during de-init only debug logs are used.
Ideally a locking mechanism like RCU is perfect for this and low overhead, but we don't have that in Zephyr.
Fixes SHEL-2436.
> drivers: wifi: Add VIF locking to public APIs

- west.yml
Update nrfxlib to contain the latest versions of MPSL and SDC. See the changelog in nrfxlib for a list of changes.
This brings in changes in from this nrfxlib update: https://github.com/nrfconnect/sdk-nrfxlib/pull/1202
> manifest: update MPSL and SDC

- applications/serial_lte_modem/boards/nrf9151dk_nrf9151_ns.conf
- applications/serial_lte_modem/boards/nrf9151dk_nrf9151_ns.overlay
Add overlay files for nrf9151dk_nrf9151_ns.
These are identical to 9161 overlay files.
> applications: serial_lte_modem: Add 9151 overlay files

- drivers/wifi/nrf700x/Kconfig
- drivers/wifi/nrf700x/inc/net_if.h
- drivers/wifi/nrf700x/inc/wifi_mgmt.h
- drivers/wifi/nrf700x/src/fmac_main.c
- drivers/wifi/nrf700x/src/net_if.c
- drivers/wifi/nrf700x/src/shim.c
- drivers/wifi/nrf700x/src/shim.h
- drivers/wifi/nrf700x/src/wifi_mgmt.c
- drivers/wifi/nrf700x/src/wpa_supp_if.c
- west.yml
This brings in driver changes for monitor mode, filter settings driver changes and handling TX injection mode command as a NET_REQUEST_ETHERNET command
> Txinjection monitor changes

- subsys/bluetooth/controller/Kconfig
- subsys/bluetooth/controller/hci_driver.c
If the host uses timestamps for HCI ISO data packets which are not based on the controller's clock, the controller needs to be configured accordingly.
Added a KConfig which exposes this possibility.
> Bluetooth: set configuration for HCI ISO data timestamps

- applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c
OCT-2822
The disconnect and reconnect of a headset, causes the gateway to print an error in the stream sent callback. The error only occurs when the gateway is streaming. This is caused by the disconnect interrupting the send data process and when the sent callback is executed the connection can not be found, as it has been closed. 
Adding a test of the streaming state to the sent callback before the channel index is retrieved and tested solves the issue.
> applications: nrf5340_audio: Error print in sent callback

- samples/matter/window_covering/src/window_covering.cpp
We were leaking 8 bytes each time the new attribute change was reported by the WindowCovering Server. It was resulting in running out of heap when stressing the device (by sending multiple up-or-open/down-or-close commands).
More specifically the `ChipCertificateSet::Init()` was failing to allocate the ~1k certificate buffer during CASE session
establishment after ~8 up-or-open/down-or-close sequences having been sent before.
> samples: matter: Fix memory leak in Window Covering

- doc/nrf/device_guides/working_with_fem.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
The documentation stated that the 2-pin a.k.a "Simple GPIO" implementation was intended just for SKY66112-11 device specifically while actually it should work for many devices that use the same interface.
> doc: FEM user guide: clarify the purpose of the simple 2-pin mode.

- west.yml
Use stack over heap to avoid OOM during runtime.
> manifest: sdk-hostap: Pull OOM fixes in WPA cli

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/nrf_cloud_multi_service/README.rst
- samples/cellular/nrf_cloud_multi_service/overlay_nrf7002ek_wifi_no_lte.conf
- samples/cellular/nrf_cloud_multi_service/sample.yaml
This commit alters the Wi-Fi connectivity overlay so that:
- TFM Protected Storage is used for cert storage instead of hard-coded certs
- TLS Credentials shell is enabled, allowing for easy cert installation
Documentations is also updated accordingly.
Finally, a few mistakes in the sample docs are corrected here as well.
IRIS-7728
> samples: cellular: MSS: Secure credentials storage for Wi-Fi

- subsys/mpsl/fem/Kconfig
This commit fixes reads of DT properties in MPSL FEM Kconfig.
> mpsl: fem: fix DT accesses in Kconfig

- samples/cellular/modem_shell/src/sock/sock.c
- samples/cellular/modem_shell/src/sock/sock_shell.c
Retry sending random data only when send() fails with EAGAIN. Other errors should not trigger retry because this could cause an infinite send loop.
Always print error from send(), except from when having EAGAIN in non-blocking mode (which is a normal case). The TCP send flow control issue have been fixed.
Fixed print format for wrong blocking mode value in send and recv.
Align some error messages printing errno.
> samples: cellular: modem_shell: Error message improvements

- subsys/mpsl/fem/simple_gpio/mpsl_fem_simple_gpio.c
`nrfx_gpiote_*` functions must now be called now with a pointer to a specific GPIOTE instance. This commit aligns MPSL FEM simple gpio implementation that was missed earlier.
> mpsl: align to changed nrfx_gpiote driver API

- scripts/quarantine_windows_mac.yaml
Native_sim is an enhanced implementation of native_posix and is not available on Windows, causing several tests to fail, instead of being skipped.
> quarantine: Add native_sim to quarantine for Windows

- doc/nrf/libraries/networking/aws_iot.rst
If the command is missing file URI scheme the user will get this cryptic error message: "CSR violates constraints".
This commit updates the docs with correct example command.
> doc: aws_iot: Fix create-certificate-from-csr command

- samples/cellular/modem_shell/README.rst
This commit adds a reference example for creating a DTLS IPv6 socket. Also point the user to the relevant information on how to use the credential storage management.
> samples: cellular: modem_shell: add sock secure example to README

- west.yml
Few CIs are removed from mpsl&sdc test scope, due to the fact that many ble scenarios are already covered in ble CI
> manifest: update nrfxlib revision with test spec update

- samples/wifi/softap/sample.yaml
The changed name looks like a copy-paste error from the sta sample and was causing errors due to name duplication
> sample: wifi: Fix softap sample name

- include/bluetooth/mesh/light_ctrl.h
- subsys/bluetooth/mesh/light_ctrl_cli.c
- subsys/bluetooth/mesh/light_ctrl_internal.h
- subsys/bluetooth/mesh/light_ctrl_srv.c
- tests/bluetooth/tester/src/mmdl.c
- tests/subsys/bluetooth/mesh/light_ctrl/src/main.c
Moves the `prop_format_get` function to public light control header to allow access to the sensor formats for
use with the new sensor API.
> Bluetooth: Mesh: Make prop_format_get public

- samples/crypto/persistent_key_usage/boards/nrf52840dk_nrf52840.conf
- samples/crypto/persistent_key_usage/boards/nrf5340dk_nrf5340_cpuapp.conf
- samples/crypto/persistent_key_usage/boards/nrf9160dk_nrf9160.conf
- samples/crypto/persistent_key_usage/src/main.c
- samples/crypto/persistent_key_usage/src/secure_storage_init.c
- subsys/secure_storage/Kconfig
- subsys/secure_storage/src/aead/aead_crypt_psa_chachapoly.c
- subsys/secure_storage/src/aead/secure_backend_aead.c
- subsys/secure_storage/src/storage_backend.h
- subsys/secure_storage/src/storage_backend_settings.c
Instead of spreading nonce, size, flags and data over several files these are now stored in one blob. This should solve issues related to cleanup when one of the storage operation fails.
Ref: NCSDK-25493
test-sdk-nrf: test-pr-13893
> secure_storage: Store data in one file

- applications/nrf5340_audio/doc/firmware_architecture.rst
- applications/nrf5340_audio/doc/requirements.rst
- applications/nrf5340_audio/index.rst
- doc/nrf/libraries/bin/bt_ll_acs_nrf53/index.rst
Added link to SD Controller LE ISO Channels.
Moved the table about differences.
Fixed naming of HCI RPMsg.
> doc: nrf5340audio: minor additions and fixes

- scripts/tools-versions-darwin.yml
- scripts/tools-versions-linux.yml
- scripts/tools-versions-win10.yml
Currently used 3.20.6 cmake version does not allow for applying cmake policies necessary for armclang compiler
> scripts: upgrade cmake version to 3.21.0

- lib/nrf_modem_lib/trace_backends/uart/Kconfig
- samples/cellular/modem_shell/prj.conf
The default value for `CONFIG_UART_USE_RUNTIME_CONFIGURE` has been changed, so it needs to be explicitly enabled for those who need `uart_config_get()`.
> Enable UART runtime configuration

- samples/openthread/cli/README.rst
- samples/openthread/cli/boards/nrf52840dongle_nrf52840.conf
- samples/openthread/cli/boards/nrf52840dongle_nrf52840.overlay
- samples/openthread/coprocessor/README.rst
- samples/openthread/coprocessor/boards/nrf52840dongle_nrf52840.conf
- samples/openthread/coprocessor/boards/nrf52840dongle_nrf52840.overlay
enable rebooting to bootloader for nRF52 Dongle with `ot reset bootloader` command triggering GPIO pin.
> samples: openthread: enable rebooting to bootloader for nRF52 Dongle

- .github/test-spec.yml
- applications/nrf_desktop/src/modules/Kconfig.caf_ble_adv.default
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- subsys/bluetooth/adv_prov/providers/Kconfig.device_name
- subsys/bluetooth/adv_prov/providers/device_name.c
Change updates device name provider to, by default, provide data only if advertising in pairing mode. Introduced a new Kconfig option that allows to keep old behavior (always providing device name).
Jira: NCSDK-25593
> bluetooth: adv_prov: device_name: Add device name only in pairing mode

- west.yml
brings a new revision of Zephyr with several
UBSAN warnings fixed in Bluetooth Host
and new hw models for babblesim with UBSAN
warnings fixed and other improvements
> manifest: update zephyr to fix UBSAN warnings

- samples/cellular/battery/README.rst
This commit fixes a typo in the README.
> samples: cellular: battery: fix typo in README

- subsys/bluetooth/services/fast_pair/Kconfig.fast_pair
- subsys/bluetooth/services/fast_pair/fp_registration_data.c
- subsys/bluetooth/services/fast_pair/include/common/fp_registration_data.h
Add possibility to read Fast Pair Model ID before calling bt_fast_pair_enable().
Jira: NCSDK-25424
> bluetooth: fast_pair: Expose Model ID before Fast Pair is ready

- applications/nrf5340_audio/src/bluetooth/bt_management/advertising/Kconfig
- applications/nrf5340_audio/src/bluetooth/bt_management/advertising/bt_mgmt_adv.c
- applications/nrf5340_audio/src/bluetooth/bt_management/advertising/bt_mgmt_adv_internal.h
- applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
- applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.h
- applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_conn.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/Kconfig.defaults
- applications/nrf5340_audio/unicast_server/Kconfig.defaults
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- If already bonded, do a short burst of directed advertising before reverting back to a slower pace advertising
- OCT-2618
> applications: nrf5340_audio: Revert to adv after short burst of dir_adv

- scripts/quarantine_zephyr.yaml
- west.yml
Updated hal_nordic restores APPROTECT handling on nRF91 target. Align nrfx samples to the updated GPIOTE API on the occasion.
> manifest: sdk-zephyr: update hal_nordic to restore APPROTECT on nRF91

- samples/wifi/softap/Kconfig
- samples/wifi/softap/README.rst
Update default settings for SoftAP to use WPA2 security by default.
> samples: wifi: softap: Modify default values for SoftAP configuration

- samples/matter/common/src/bt_nus/bt_nus_service.cpp
For some reason the BT NUS module adds _NUS suffix to BT name, while it creates own advertising data. It is sort of confusing, because the device changes BT name after Matter BLE advertising timeout and switching to advertising NUS.
> samples: matter: Removed _NUS suffix from BT device name

- doc/nrf/releases_and_maturity/known_issues.rst
The Known issues page defaults to 2.5.1.
Fixed it to point to 2.5.2.
> doc: Known issues version fix

- west.yml
The libraries for 54H/L were moved.
> manifest: Update nrfxlib with MPSL and SDC

- include/bluetooth/mesh/light_ctrl.h
Multiplies the default Kconfig illuminances
by 100 to get correct unit (centilux).
> Bluetooth: Mesh: fix LC lux unit

- applications/nrf5340_audio/include/nrf5340_audio_common.h
- applications/nrf5340_audio/src/audio/audio_datapath.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
OCT-2888
The first sent ISO channel uses seq_num,
further channels will be synced using timestamp.
max transport latency reduced
> Applications: nrf5340_audio: Refactored use of timestamps

- applications/nrf5340_audio/tools/buildprog/ble5-ctr-rpmsg_sign.py
- applications/nrf5340_audio/tools/buildprog/buildprog.py
OCT-2903	
Buildprog and DFU script only allows four digits for PCFT hex.
These scripts are updated to allow filenames for the controller to have one or more digits for the build number.
> applications: nrf5340_audio: PCFT build number of more than 4 digits

- applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h
- applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
Move calculation of the codec bitrate into le_audio module to reduce code duplication.
The integration of sample rate conversion will introduce the bitrate calculation in three more places, so the gain from creating a function for this will increase when that is merged.
> applications: nrf5340_audio: Move bitrate calculation into le_audio

- doc/nrf/config_and_build/bootloaders/bootloader_external_flash.rst
[NCSIDB-1160](https://nordicsemi.atlassian.net/browse/NCSIDB-1160)
Add config option to troubleshooting section of Bootloaders > Using external flash memory partitions.
[NCSIDB-1160]: https://nordicsemi.atlassian.net/browse/NCSIDB-1160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> doc: add config option to bootloader extflash

- west.yml
Revert accidental change to non-zephyr code.
> manifest: sdk-hostap: Pull fix for non-zephyr code

- doc/nrf/releases_and_maturity/known_issues.rst
Only the first mentioning of Bluetooth on the page is marked with registered trademark symbol
and in italics.
> doc: cleanup bluetooth trademark for known issues

- .github/workflows/labeler.yml
Labeler v5 (by default) does not remove labels when matching files are reverted or no longer changed by the PR. This change will enable the old behavior.
> ci: update labeler to sync labels

- applications/nrf5340_audio/broadcast_sink/Kconfig.defaults
Enlarge codec cfg max metadata size to prevent compatibility issue. 
OCT-NONE
> applications: nrf5340_audio: Extended codec cfg max metadata size

- modules/hostap/src/supp_api.c
Key management for SAP should be retrieved from the network block rather than using the per-interface global structure.
Fixes SHEL-2466.
> modules: hostap: Fix key management for SAP

- applications/matter_bridge/doc/matter_bridge_description.rst
- applications/matter_bridge/src/app_task.cpp
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/matter/common/src/board/board.cpp
- samples/matter/common/src/bridge/ble_connectivity_manager.cpp
- samples/matter/common/src/bridge/ble_connectivity_manager.h
- BLE connectivity manager now supports registering callbacks for state change. The callback can be defined in the application to indicate the current state using for example LEDs, LCDs, etc.
- There are several states defined:
- Idle
- Scanning
- Pairing
- LostDevice
- Implemented Indication for Bridge sample utilizing LED 2 located on the nRF7002DK board.
> applications: matter: Add Bluetooth LE state indications

- applications/nrf5340_audio/src/audio/audio_datapath.c
- Removed print since it is already printed in le_audio_rx
> applications: nrf5340_audio: Removed bad frame print

- subsys/bluetooth/controller/hci_internal.c
The "Zephyr Read Chip Temperature" HCI command will only work if the internal temperature sensor is available.
> Bluetooth: Controller: Require TEMP for temperature HCI command

- west.yml
Needed before 2.6 to unlock development. Without it a quarantine is ignored with dynamic scope and  known errors blocks PRs
> manifest: sdk-zephyr: Fix quarantine and test plan interaction

- subsys/dfu/dfu_target/src/dfu_target_stream.c
Delete write progress to flash stream when resetting the target.
> dfu: dfu_target: delete stream write progress on reset

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/date_time.h
- lib/date_time/date_time.c
- lib/date_time/date_time_core.c
- lib/date_time/date_time_core.h
- lib/date_time/date_time_modem.c
- lib/date_time/date_time_modem.h
This provides a substitute for localtime() since it isn't implemented in Zephyr's minimal libc. The resulting timestamp can be used with <ctime> or <chrono> for manipulation and logging.
> lib: date_time: Add local time API function

- modules/mcuboot/CMakeLists.txt
Change fixes build errors triggered while looking for boot signature key file if mcuboot_CONF_FILE is passed explicitly as a CMake option.
Jira: NCSIDB-1056
> modules: mcuboot: Fix looking for boot signature key file

- modules/hostap/Kconfig
SAP mode adds more functionality that increases the heap usage, based on experiments, 40000 works well to avoid startup failures.
> modules: hostap: SAP mode needs more heap

- cmake/mesh_dfu_metadata.cmake
- scripts/bluetooth/mesh/mesh_dfu_metadata.py
- subsys/bluetooth/mesh/CMakeLists.txt
- subsys/bluetooth/mesh/Kconfig
Adds script that can parse Mesh metadata from application .elf and .config file. The script is automatically run if the extract Mesh metadata config option is enabled. The output from this script is appended to dfu_application.zip in the project build folder.
> Bluetooth: Mesh: Add metadata extraction for DFU

- ext/oberon/psa/drivers/oberon_ec_keys.c
Fix for gcc warning: 'res' may be used uninitialized
For some reason I only see the warning when CONFIG_DEBUG_OPTIMIZATIONS=y
> ext: fix oberon driver uninitialized variable

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/bluetooth/mesh/time_srv.h
- subsys/bluetooth/mesh/time_srv.c
- tests/subsys/bluetooth/mesh/time_model/src/main.c
Commit fixes the known issue when the Time model changes the configured publishing ttl after sending any
unsolicited Time status.
> Bluetooth: Mesh: restore ttl in Time model after unsolicited statuses

- applications/nrf_desktop/src/modules/Kconfig.caf_ble_adv.default
- doc/nrf/libraries/caf/ble_adv.rst
- doc/nrf/libraries/caf/ble_state.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/caf/events/ble_common_event.h
- subsys/caf/events/ble_common_event.c
- subsys/caf/modules/Kconfig.ble_adv
- subsys/caf/modules/ble_adv.c
- subsys/caf/modules/ble_state.c
Force power down if bonded peer disconnects with reason 0x15 (Remote Device Terminated due to Power Off).
PR also adds broadcasting reason to ble_peer_event and integrates the new feature to nRF Desktop application.
Jira: NCSDK-24458
> caf: modules: ble_adv: Power down on disconnection with reason 0x15

- west.yml
This makes it possible for nRF I2S to provide master clock even when operating in I2S Slave mode.
> manifest: sdk-zephyr: Update I2S driver to generate master clock

- subsys/bluetooth/controller/Kconfig
Isochronous channels has production support now.
Rename BT_LL_SOFTDEVICE_EXPERIMENTAL_ISO to BT_LL_SOFTDEVICE_ISO, and remove experimental wordings.
> bluetooth: controller: Kconfig: remove BT_LL_SOFTDEVICE_EXPERIMENTAL_ISO

- lib/modem_key_mgmt/modem_key_mgmt.c
After adding a mutext to protect the internal buffer, the modem_key_mgmt_exists() contained a mistake that it always returned zero, instead of erro code from AT command.
> lib: modem_key_mgmt: Return errors from _mgmt_exists()

- applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
- applications/serial_lte_modem/src/slm_at_socket.c
- applications/serial_lte_modem/src/slm_at_socket.h
- applications/serial_lte_modem/src/slm_sockopt.h
Previously SLM socket options would change if there were changes in zephyr or nrf socket options. Having our own definitions for socket options allows us to minimize the changes visible outside of SLM.
> applications: serial_lte_modem: socket option definitions

- drivers/serial/uart_nrf_sw_lpuart.c
Fix compilation failure when interrupt driven API is enabled but not used by the low power UART.
> drivers: serial: lpuart: Fix build failure in certain configuration

- modules/trusted-firmware-m/tfm_boards/partition/region_defs.h
PSA_INITIAL_ATTEST_TOKEN_MAX_SIZE was renamed in TF-M, but we didn’t
update our symbol name.
It appears that this symbol is now provided by TF-M's
initial_attestation.h.in and that we should therefore delete, not
rename, this symbol.
Interestingly, it’s documented that region_defs.h should define this,
but no-one is doing so for the new symbol name. The docs are probably
wrong.
> tfm: Delete deprecated symbol PSA_INITIAL_ATTEST_TOKEN_MAX_SIZE

- modules/trusted-firmware-m/Kconfig
- subsys/nrf_security/cmake/legacy_crypto_config.cmake
Enable HMAC DRBG when we build TFM with minimal profile since it reduces the ROM usage.
Ref: NCSDK-25891
> modules: trusted-firmware-m: HMAC DRBG for minimal

- doc/nrf/releases_and_maturity/known_issues.rst
When dimming a light/bulb over time or changing color, the thread network can be spammed - fix.
> doc: update known issues with Matter's redundant Thread traffic

- applications/matter_bridge/src/simulated_providers/simulated_onoff_light_switch_data_provider.cpp
- samples/matter/common/src/binding/binding_handler.cpp
- samples/matter/common/src/binding/binding_handler.h
- samples/matter/common/src/bridge/bridged_device_data_provider.h
- samples/matter/light_switch/src/light_switch.cpp
- samples/matter/light_switch/src/shell_commands.cpp
- samples/matter/thermostat/src/temperature_measurement/sensor.cpp
The BindingData structure requires setting IsGroup argument, which can be used to apply specific command to only a part of binding entries (groups only or unicast only). This can be useful, but the default behavior should be sending command to all targets present in the binding table.
Changed IsGroup field to be optional. If it's not present the command will be sent to all targets. Otherwise the old filtering scheme will be used.
> samples: matter: Made IsGroup binding parameter optional

- west.yml
So that more peripherals are accessible.
> manifest: pull nRF54H20 extended DT from Zephyr

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/modem_shell/src/sock/sock.c
- samples/cellular/modem_shell/src/sock/sock.h
- samples/cellular/modem_shell/src/sock/sock_shell.c
Allow security tag values up to 4294967295.
> samples: cellular: modem_shell: Make sec_tag unsigned

- applications/asset_tracker_v2/src/modules/location_module.c
- doc/nrf/libraries/modem/location.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/modem/location.h
- lib/location/location.c
- lib/location/location_core.c
- lib/location/location_core.h
- lib/location/method_cloud_location.c
- lib/location/method_cloud_location.h
- lib/location/method_gnss.c
- lib/location/scan_cellular.c
- lib/location/scan_cellular.h
- lib/location/scan_wifi.c
- lib/location/scan_wifi.h
- samples/cellular/modem_shell/src/location/location_shell.c
- samples/cellular/nrf_cloud_multi_service/src/location_tracking.c
- tests/lib/location/CMakeLists.txt
- tests/lib/location/src/location_test.c
Adding LOCATION_EVT_FALLBACK to be sent when a methods times out or fails and a new method is tried.
Adding `satellites_used` and `search_time` for GNSS details. Also creating Wi-Fi and cellular details with number of APs and cells.
Adding a new method type `LOCATION_METHOD_WIFI_CELLULAR` that cannot be used in the method list for location request but may occur in the events.
Jira: NCSDK-25618
> lib: location: Fallback event and more data details

- samples/net/azure_iot_hub/src/main.c
* Reduce log level to DBG for the message logged when a `telemetryInterval` object is not found in the incoming device twin document. This is a common occurrence and the log message is confusing when for instance receiveing FOTA metadata.
* Add DBG level log message for when the incoming device twin document contains only a `desired` object.
> samples: net: azure_iot_hub: Reword log messages for device twin

- applications/serial_lte_modem/src/slm_uart_handler.c
In case of garbage inputted in RX port, the SLM outputs way too much of RX Stop/RX Start messages.
Change the logging level to decrease those messages.
> applications: serial_lte_modem: Decrease UART loggin

- drivers/wifi/nrf700x/src/net_if.c
- west.yml
This set of changes pulls in raw tx failure count updation when tx done from firmware indicates failure
> Update failure stats for raw tx failure

- doc/nrf/device_guides/working_with_nrf/nrf70/developing/fw_patches_ext_flash.rst
- doc/nrf/device_guides/working_with_nrf/nrf70/developing/stack_partitioning.rst
- doc/nrf/device_guides/working_with_nrf/nrf70/gs.rst
- doc/nrf/drivers/wifi/nrf700x/nrf700x.rst
Replaced "nRF70 Series Wi-Fi driver" with "nRF Wi-Fi driver" in user guides under "Working with nRF70 Series".
> doc: wifi: replace "nRF70 Series Wi-Fi driver" with nRF Wi-Fi driver

- drivers/wifi/nrf700x/inc/wifi_mgmt.h
- west.yml
filter settings have been missed from being placed under CONFIG_NRF700X_PROMISC_DATA_RX check. enable filter code for Promiscuous mode
> Fix build issue for promiscuous mode

- samples/cellular/nrf_cloud_multi_service/overlay-coap_nrf_provisioning.conf
- subsys/net/lib/nrf_cloud/coap/src/coap_codec.c
- subsys/net/lib/nrf_provisioning/Kconfig.nrf_provisioning_cbor
CONFIG_ZCBOR_CANONICAL needs to be disabled or else we receive a ZCBOR_ERR_ADDITIONAL_INVAL error on an otherwise valid response.
This error arose after the upgrade to ZCBOR 8.1 was merged.
Jira: NCSDK-26221
> net: lib: nrf_cloud_coap: Fix ground-fix response error

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c
The function nrf_cloud_pgps_request_reset() resets the state to one that nrf_cloud_pgps_loading() considered a loading state. This prevented the next opportunity to download again from issuing another PGPS_EVT_REQUEST.
Only set the state to PGPS_NONE on unrecoverable errors.
Jira: NCSDK-25969
> net: lib: nrf_cloud: Fix P-GPS non-MQTT download retries

- west.yml
Disable synchronous printk to avoid blocking IRQs
which may affect time sensitive components (like 15.4 radio).
> manifest: Pull Matter change to disable PRINTK_SYNC

- applications/matter_bridge/CMakeLists.txt
- applications/matter_weather_station/CMakeLists.txt
- doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/matter/common/cmake/source_common.cmake
- samples/matter/light_bulb/CMakeLists.txt
- samples/matter/light_switch/CMakeLists.txt
- samples/matter/lock/CMakeLists.txt
- samples/matter/template/CMakeLists.txt
- samples/matter/thermostat/CMakeLists.txt
- samples/matter/window_covering/CMakeLists.txt
This commit move cmake directives repeated in all applications/samples to one common cmake file.
> samples: matter: common: Integrate Matter common module with CMake

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- subsys/net/lib/nrf_cloud/CMakeLists.txt
- subsys/net/lib/nrf_cloud/include/nrf_cloud_pgps_utils.h
- subsys/net/lib/nrf_cloud/src/nrf_cloud_fota_poll.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps_utils.c
The FOTA poll thread was using fota_download_start_with_image_type() directly rather than nrf_cloud_download_start() which  coordinates downloads to prevent multiple simultaneous ones.
Switch to nrf_cloud_download_start(). Debug handling of aborting the P-GPS download at the start -- the first allocated block was
not freed. 
Jira: IRIS-8255
**NOTE** this is stacked on top of https://github.com/nrfconnect/sdk-nrf/pull/14082. Merge that one first, then I can rebase and push this one.
> net: lib: nrf_cloud: Prevent simultaneous FOTA and PGPS DL

- drivers/wifi/nrf700x/src/qspi/src/qspi_if.c
- drivers/wifi/nrf700x/src/qspi/src/rpu_hw_if.c
- drivers/wifi/nrf700x/src/qspi/src/spi_if.c
Fixed Wi-Fi driver bus layer logger registering (duplicated logger symbol with different log levels)
@krish2718 the problem with Wi-Fi driver is not visible in Wi-Fi samples because they use the same default
value for both `CONFIG_WIFI_NRF700X_LOG_LEVEL` and `CONFIG_WIFI_NRF700X_BUS_LOG_LEVEL`.
Note that it was not reproducible with LOG_MODE_MINIMAL, because this mode does not really use log objects.
> drivers: wifi: Fix duplicated logger object names

- scripts/quarantine.yaml
Remove ATv2 and MOSH configurations from quarantine. They were put into quarantine by PR #13662, which increased memory usage. The fix was made by PR #14034.
Jira: NCSDK-25891
> scripts: quarantine: remove samples/apps due to TF-M FLASH overflow fix

- west.yml
Cherry-pick for adding nRF5340 audio DK NET arduino header. OCT-NONE
> manifest: sdk-zephyr: add nrf5340 audio dk NET arduino header define

- applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c
- applications/nrf5340_audio/unicast_client/main.c
Fixed the issue that CIS gateway might not setup MIC stream properly. There could be a chance the sink stream setup failed, but before the retry, the source stream from same ISO setup properly which also setup the sink. This cause the state out of sync for retrying, and leads to retry mechanism failed.
OCT-NONE
> applications: nrf5340_audio: Fix CIS TWS MIC stream disappeared

- doc/nrf/releases_and_maturity/known_issues.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
* update known issues for Matter
* update changelog with the patch that disabled CONFIG_PRINTK_SYNC in Matter fork
> doc: update documentation with sync. printk limitations in Matter

- doc/nrf/protocols/zigbee/adding_clusters.rst
- doc/nrf/protocols/zigbee/index.rst
The Adding ZCL clusters to application page in the Zigbee documentation has been outdated for some while now. This orphans the page so it isn't visible in the table of contents until the page can be updated.
> doc: Zigbee: orphan ZCL clusters page

- doc/_scripts/software_maturity/software_maturity_features.yaml
- samples/wifi/monitor/sample.yaml
- samples/wifi/raw_tx_packet/sample.yaml
- samples/wifi/shell/sample.yaml
This set of changes does the following:
1) SML table update for TX injection, Monitor and promiscuous mode
2) add CI build for Monitor, TX injection and promiscuous mode in SHELL sample
3) update Monitor, TX injection and promiscuous mode board and shields support in software_maturity_features.yaml
> SML table updation, add to CI build and update software maturity yaml file for Monitor, tx injection and promiscuous mode 

- applications/nrf5340_audio/src/audio/audio_datapath.c
Disable the pres-comp feature on TWS CIS bidir gateway when using audio subsystem controller.
OCT-2867
> applications: nrf5340_audio: Disable pres-comp for CIS bidir gateway

- ext/oberon/psa/core/include/psa/crypto_platform.h
- ext/oberon/psa/core/include/psa/crypto_struct.h
This is similar to https://github.com/Mbed-TLS/mbedtls/pull/8729
> ext: oberon: Add a client view of the multipart contexts

- west.yml
Bring fix for MCUboot issue:
- swap_move: boot_read_image_header mixes slot numbers when more than one image is swapped in multi-image configuration https://github.com/mcu-tools/mcuboot/issues/1768
> manifest: Update sdk-mcuboot to bring fix for upstream issue #1768

- doc/nrf/device_guides/working_with_nrf/nrf53/nrf5340.rst
The commit adds note on how to pass Kconfig options to child image, here MCUboot specifically.
Ref: NCSIDB-1020
> doc: config_and_build: Note on how to pass Kconfig to child image

- doc/nrf/protocols/matter/end_product/versioning.rst
- west.yml
This commit changes the default string representation of version to include the tweak.
> samples: matter: update versioning scheme for Matter applications

- include/bluetooth/mesh/sensor.h
- include/bluetooth/mesh/sensor_types.h
- subsys/bluetooth/mesh/light_ctrl_srv.c
- subsys/bluetooth/mesh/sensor.c
- subsys/bluetooth/mesh/sensor_types.c
- tests/subsys/bluetooth/mesh/sensor_subsys/src/main.c
- tests/subsys/bluetooth/mesh/sensor_subsys_new/CMakeLists.txt
- tests/subsys/bluetooth/mesh/sensor_subsys_new/prj.conf
- tests/subsys/bluetooth/mesh/sensor_subsys_new/sensor_types.ld
- tests/subsys/bluetooth/mesh/sensor_subsys_new/src/main.c
- tests/subsys/bluetooth/mesh/sensor_subsys_new/testcase.yaml
First commit, fixing issues discovered during testing
-----------------------------------------------------
> This fixes several issues with sensor that were discovered during
> testing:
> 
>   * Switch to using rounding instead of truncating when dividing and
>     converting between float and int.
>   * Handle overflow when converting raw values to micro/sensor_value
>     by returning BT_MESH_SENSOR_VALUE_CLAMPED and clamping the value.
>   * Add public declaration of `bt_mesh_sensor_total_dev_runtime` which
>     was missing.
>   * Add tailroom checking to `sensor_ch_encode`
>   * Don't write format pointer if buffer is too short in
>     `sensor_ch_decode`.
>   * Clamp input value correctly in `scalar_from_float`
>     (float values >= `INT64_MAX` would overflow with the previous
> …
> bluetooth: mesh: add unit tests for new sensor API

- applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
Update the SMP log level, since SMP failed could happen during power on/off testing, which should not block us from continuing the test.
OCT-NONE
> applications: nrf5340_audio: change SMP log level

- samples/cellular/modem_shell/prj.conf
AT+COPS=? network search may cause system work queue getting stuck as follows:
- AT+COPS=? is issued
- +CEREG notification is received
- +CEREG will trigger another AT command (AT%XMONITOR)
- AT%XMONITOR cannot be started before AT+COPS=? completes
- System work queue is blocked
- Incoming AT notifications are reserved and sending them is put to system work queue
- AT monitor heap runs out if there are too many notifications before AT+COPS=? completes
Jira: MOSH-551
> samples: cellular: modem_shell: Increase CONFIG_AT_MONITOR_HEAP_SIZE

- cmake/mesh_dfu_metadata.cmake
- scripts/bluetooth/mesh/mesh_dfu_metadata.py
Adds utility command that prints BLE Mesh DFU metadata for the target application folder.
> Bluetooth: Mesh: Add cmd to print DFU metadata

- samples/matter/common/src/bridge/ble_connectivity_manager.cpp
- samples/matter/common/src/bridge/ble_connectivity_manager.h
This PR includes two fixes for the BT bridge recovery:
* usage fault in case of re-connection failure (this is a condition directly caused by the second problem)
* GATT discovery failure if some device was recovered soon after recovering the previous one (e.g. in case of bridge reboot)
> samples: matter: Fixed BT bridge recovery procedure

- applications/matter_bridge/doc/adding_ble_bridged_device_service.rst
- applications/matter_bridge/doc/adding_bridged_matter_device.rst
- doc/nrf/protocols/matter/getting_started/adding_clusters.rst
After Matter common modules refactor, the code API changed a lot, so guides for creating a new Matter accessory and extendind the bridge application had to be updated.
> doc: Updated Matter guides containing code snippets.

- applications/serial_lte_modem/src/slm_cmux.c
Nothing is to be done on MODEM_PIPE_EVENT_TRANSMIT_IDLE.
> applications: serial_lte_modem: fix compilation warning

- applications/serial_lte_modem/src/slm_at_tcp_proxy.c
Avoid blocking call to recv with native TLS. It is not returning correctly after the remote end terminates the connection.
> applications: serial_lte_modem: Fix native TLS with 2.6.0

- applications/serial_lte_modem/overlay-external-mcu.overlay
- applications/serial_lte_modem/overlay-zephyr-modem-external-mcu.conf
- applications/serial_lte_modem/overlay-zephyr-modem-nrf9160dk-nrf52840.conf
- applications/serial_lte_modem/overlay-zephyr-modem-nrf9160dk-nrf52840.overlay
- applications/serial_lte_modem/overlay-zephyr-modem.conf
> applications: serial_lte_modem: add reference overlays for Zephyr modem driver

- applications/matter_bridge/overlay-bt_max_connections_app.conf
The overlay for max number of BT connections does not increase max number of paired devices, so BT SMP module does not allow to connect the expected number.
> applications: Fixed BT max connection overlay for Matter bridge

- applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
- applications/serial_lte_modem/src/lwm2m_carrier/slm_at_carrier.c
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added more descriptive documentation of custom AT commands in the LwM2M Carrier library integration.
> applications: serial_lte_modem: improve AT Carrier documentation

- applications/nrf_desktop/doc/wheel.rst
- applications/nrf_desktop/src/hw_interface/Kconfig.wheel
- applications/nrf_desktop/src/hw_interface/wheel.c
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change updates application module's configuration to allow using GPIO1 in wheel.
Jira: NCSDK-26115
> applications: nrf_desktop: Allow using GPIO1 in wheel

- applications/nrf_desktop/src/modules/hid_state.c
Change fixes `empty_rd` handling in `update_report` function. The `empty_rd` does not link to a subscriber (`linked_rs` is set to `NULL`). Because of that, it's not allowed to access `report_state` through `linked_rs` pointer. Since `empty_rd` contains no data (the event queue is always empty), we can use an early return here.
Jira: NCSDK-25928
> applications: nrf_desktop: Fix `empty_rd` handling in HID state module

- applications/nrf_desktop/doc/fast_pair_app.rst
- doc/nrf/external_comp/bt_fast_pair.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/bluetooth/services/fast_pair.h
Aligns the Fast Pair documentation after new Fast Pair enable API was introduced via this PR: https://github.com/nrfconnect/sdk-nrf/pull/13315.
> Add user guide to new Fast Pair enable API

- doc/nrf/config_and_build/bootloaders/bootloader_adding.rst
- doc/nrf/config_and_build/bootloaders/bootloader_signature_keys.rst
Removed Python script from suggested methods for key generation. Added caution note on private key secrecy.
> doc: NCSDK 18366 Updated bootloader_signature_keys.rst

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/bluetooth/mesh/dfu/target/README.rst
- samples/bluetooth/mesh/dfu/target/pm_static_nrf52840dongle_nrf52840.yml
- samples/bluetooth/mesh/dfu/target/sample.yaml
- samples/bluetooth/mesh/light_ctrl/README.rst
- samples/bluetooth/mesh/light_ctrl/pm_static_nrf52840dongle_nrf52840.yml
- samples/bluetooth/mesh/light_ctrl/sample.yaml
- samples/bluetooth/mesh/light_dimmer/README.rst
- samples/bluetooth/mesh/light_dimmer/pm_static_nrf52840dongle_nrf52840.yml
- samples/bluetooth/mesh/light_dimmer/sample.yaml
- scripts/bluetooth/mesh/mesh_dfu_metadata.py
* Added dongle support for:
* Light Dimmer and Light Fixture samples
* DFU target sample
* Fixed hardcoded core type in mesh_dfu_metadata.py
* Updated docs
> Bluetooth: mesh: samples: add support for nRF52840 dongle

- samples/bluetooth/mesh/ble_peripheral_lbs_coex/boards/nrf52dk_nrf52832.conf
- samples/bluetooth/mesh/chat/boards/nrf52dk_nrf52832.conf
- samples/bluetooth/mesh/light/boards/nrf52dk_nrf52832.conf
- samples/bluetooth/mesh/light_ctrl/boards/nrf52dk_nrf52832.conf
- samples/bluetooth/mesh/light_dimmer/boards/nrf52dk_nrf52832.conf
- samples/bluetooth/mesh/light_switch/boards/nrf52dk_nrf52832.conf
- samples/bluetooth/mesh/sensor_client/boards/nrf52dk_nrf52832.conf
- samples/bluetooth/mesh/sensor_server/boards/nrf52dk_nrf52832.conf
- samples/bluetooth/mesh/silvair_enocean/boards/nrf52dk_nrf52832.conf
nrf52832 doesn't support partial erase functionality. Enabling the feature by default generates warning for the platform.
> samples: Bluetooth: Mesh: remove partial erase warning for nrf52832

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/bluetooth/services/fast_pair.h
- subsys/bluetooth/services/fast_pair/fp_advertising.c
- subsys/bluetooth/services/fast_pair/fp_gatt_service.c
- subsys/bluetooth/services/fast_pair/fp_storage_integration.c
Specifies which functions from Fast Pair API must be run from cooperative thread context and adds assertions for it.
Jira: NCSDK-25120
Release notes will be updated after https://github.com/nrfconnect/sdk-nrf/pull/14170 merge to not generate conflicts.
> bluetooth: fast_pair: Align cooperative thread approach

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- lib/pdn/pdn.c
If we do not do this a list lookup will find this PDN. If the context_id happens to be valid and the callback not null then we will crash.
> lib: pdn: Init PDN before adding it to the list

- doc/nrf/includes/cert-flashing.txt
- doc/nrf/libraries/networking/azure_iot_hub.rst
- doc/nrf/links.txt
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Reworking the Azure IoT Hub documentation
so it has a step by step guide in order to
faster get started with the library and
azure IoT Hub sample.
Also added description on how to provision
credentials for nrf7002.
> docs: azure-iot-hub: rework docs

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- lib/hw_unique_key/Kconfig
- subsys/net/openthread/Kconfig
- subsys/nrf_security/src/psa_crypto_driver_wrappers.c
- enabled HUK provisioning during `psa_driver_wrapper_init` for non-TFM builds
- enabled HUK in OpenThread for non-TFM nrf5340 samples
> nrf_security: enable HUK provisioning during `psa_driver_wrapper_init`

- applications/matter_bridge/boards/nrf5340dk_nrf5340_cpuapp.overlay
- applications/matter_bridge/child_image/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay
- applications/matter_bridge/child_image/mcuboot/boards/nrf5340dk_nrf5340_cpuapp_release.overlay
- applications/matter_bridge/configuration/nrf5340dk_nrf5340_cpuapp/pm_static_dfu.yml
- applications/matter_bridge/doc/matter_bridge_description.rst
- applications/matter_bridge/sample.yaml
- doc/nrf/config_and_build/dfu/index.rst
- doc/nrf/config_and_build/dfu/nrf70_fw_patch_update.rst
- doc/nrf/device_guides/working_with_nrf/nrf70/developing/fw_patches_ext_flash.rst
- drivers/wifi/nrf700x/CMakeLists.txt
- drivers/wifi/nrf700x/Kconfig
- modules/mcuboot/CMakeLists.txt
- samples/matter/lock/CMakeLists.txt
- samples/matter/lock/README.rst
- samples/matter/lock/configuration/nrf5340dk_nrf5340_cpuapp/pm_static_dfu_wifi_ext_patch.yml
- samples/matter/lock/sample.yaml
- west.yml
This commit allows performing Direct Firmware Update of Wi-Fi firmware patch that is located in the external memory.
This solution requires an additional MCUBoot partition pair (primary and secondary) and including the nrf70_wifi_fw partition within the primary partition.
- Added Kconfig option to enable DFU support: NRF_WIFI_FW_PATCH_DFU
- Aligned mcuboot's CMakeLists.txt file to sign the nrf70 FW patch
image and create the signed hex.
- Added WiFi FW patch singed image to the multi-image target.
-Aligned Matter samples
TODO:
> Added support for DFU of wi-fi firmware patch 

- doc/nrf/libraries/bluetooth_services/mesh/light_ctrl_cli.rst
- doc/nrf/libraries/bluetooth_services/mesh/light_ctrl_srv.rst
- doc/nrf/libraries/bluetooth_services/mesh/sensor.rst
- doc/nrf/libraries/bluetooth_services/mesh/sensor_cli.rst
- doc/nrf/libraries/bluetooth_services/mesh/sensor_srv.rst
- doc/nrf/libraries/bluetooth_services/mesh/sensor_types.rst
- include/bluetooth/mesh/sensor.h
This updates the sensor and light ctrl documentation to align with the new Sensor API. It also adds a note about the API change and information about the documention for the old API being available in the previous NCS release to relevant locations.
> doc: bluetooth: mesh: update sensor docs to new API

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/wifi/shell/CMakeLists.txt
- samples/wifi/shell/README.rst
- samples/wifi/shell/src/wifi_promiscuous_shell.c
This set of changes adds a promiscuous mode shell command to shell sample to configure promiscuous mode for the nRF Wi-Fi driver.
> Promiscuous mode shell command

- lib/location/scan_cellular.c
When the following config was set, scan_cellular.c didn't compile because it tried to use cellular details:
CONFIG_LOCATION_DATA_DETAILS=y
CONFIG_LOCATION_METHOD_CELLULAR=n
CONFIG_LOCATION_METHOD_GNSS=y
scan_cellular.c is also compile for GNSS as it uses NCELLMEAS to obtain current cell.
> lib: location: Fix compile issue without cellular

- doc/nrf/protocols/bt/bt_mesh/configuring.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/bluetooth/mesh/light/sysbuild/hci_ipc/prj.conf
- samples/bluetooth/mesh/light_ctrl/sysbuild/hci_ipc/prj.conf
- samples/bluetooth/mesh/light_dimmer/sysbuild/hci_ipc/prj.conf
- samples/bluetooth/mesh/light_switch/sysbuild/hci_ipc/prj.conf
- samples/bluetooth/mesh/sensor_server/sysbuild/hci_ipc/prj.conf
- samples/bluetooth/mesh/silvair_enocean/sysbuild/hci_ipc/prj.conf
This PR enables the extended advertising API support and the necessary amount of advertising sets in the Bluetooth controller on the network core required by the Bluetooth Mesh when a sample is build with
`--sysbuild` option.
This PR also describes which options must be enabled on the network core for the bluetooth controller to work with mesh.
> Bluetooth: Mesh: Fix sysbuild configuration for mesh samples

- modules/mcuboot/CMakeLists.txt
The image signing has been taking, as --slot-size parameter, size of primary internal slot rather than expected external slot it has been signing image for.
> modules/mcuboot: Fix incorrect size used for signing external image

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/modem_shell/src/sock/sock.c
- samples/cellular/modem_shell/src/sock/sock.h
- samples/cellular/modem_shell/src/sock/sock_shell.c
Add an option to sock connect to keep socket open when its PDN connection is lost. This is useful to keep DTLS connections when network is lost for a short period.
> samples: cellular: modem_shell: Add sock connect --keep_open

- samples/wifi/monitor/sample.yaml
- samples/wifi/raw_tx_packet/sample.yaml
- samples/wifi/shell/sample.yaml
- samples/wifi/softap/sample.yaml
The idea was to skip twister for these variants to save CI time, but still add an entry for SML. But SML in current state needs access to "build.log" and ".config" build artifacts, so, the experimental SML isn't updated properly.
Till we figure out a way to get experimental status without build artifacts, enable these experimental features for boards nRF7000 and nRF7001 in the twister.
> samples: wifi: Fix SML experimental update for nRF7000 and nRF7001

- doc/nrf/libraries/networking/azure_iot_hub.rst
- doc/nrf/links.txt
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- scripts/cert_tool.py
This is a script to generate elliptic curve private keys, create a certificate signing request for a private key, create root CA and subordinate CA certificates and sign a certificate signing request with a CA.
The keys are not encrypted with a password or any other protection. It is strictly for testing and evaluation purposes.
usage: cert_tool.py [-h] {client_key,root_ca,sub_ca,csr,sign,sign_root}
It is only tested with Azure IoT Hub and Azure DPS, but doesn't include anything specific for Azure, so in theory it should work with other cloud vendors.
All file-related arguments have default values. Client key/csr/cert is stored in ./certs folder and CA keys/certs are stored in ./ca.
Documentation and release notes will be handled in a separate PR.
> scripts: add cert_tool.py

- drivers/wifi/nrf700x/Kconfig
- drivers/wifi/nrf700x/src/fmac_main.c
- samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
- west.yml
[SHEL-2481]: Support for applying frame format dependent edge backoff
in PHY firmware.
[SHEL-2481]: https://nordicsemi.atlassian.net/browse/SHEL-2481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> manifest: Edge backoff support using RF params

- CODEOWNERS
- doc/nrf/links.txt
- doc/nrf/protocols/thread/index.rst
- doc/nrf/protocols/thread/tcat.rst
- samples/openthread/cli/README.rst
This commit add TCAT documentation section in NCS Thread related docs.
> doc: openthread: Adding documentation about TCAT.

- west.yml
Fix the CI and now we see compliance errors, so, pull the fixes for compliance.
> manifest: sdk-hostap: Pull compliance fixes

- doc/nrf/protocols/matter/getting_started/index.rst
- doc/nrf/protocols/matter/getting_started/matter_api.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added a documentation on how to use:
* nRF Connect Matter Initialization API
* nRF Connect Matter Event Handler API
* Matter Data Model callbacks
> doc: Added a new page about nRF Connect Matter APIs

- doc/nrf/glossary.rst
- doc/nrf/libraries/dfu/pcd.rst
Adds PCD to the glossary (as requested [here](https://github.com/nrfconnect/sdk-nrf/pull/14226#discussion_r1507107714))
Fix SoC typo in PCD lib page
> doc improvement: add gloss entry

- applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
- applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_conn.c
Update the error check for scanning for bypassing the scan start/stop already return code.
OCT-2858
> applications: nrf5340_audio: Update error check for scanning

- cmake/partition_manager.cmake
- modules/mcuboot/boot/zephyr/Kconfig
Changes to Kconfig and CMake that allow MCUboot to work with NRF54L. The Kconfig has been changed to change size of MCUboot header and CMake to properly invoke partition manager script with RRAM as NVM.
> partition_manager: NRF54L support for MCUboot added

- lib/bin/lwm2m_carrier/os/lwm2m_os.c
The MCUBoot Image manager functions used in the OS function to validate application update are dependent on CONFIG_MCUBOOT_IMG_MANAGER, not CONFIG_BOOTLOADER_MCUBOOT.
> lib: bin: lwm2m_carrier: fix conditional compilation

- doc/nrf/protocols/matter/getting_started/matter_api.rst
* increase indentations in the code snippets for better readability
* use more representative Matter event in the example event handler
> doc: fix code snippet indentations in the Matter API documentation

- applications/asset_tracker_v2/src/modules/modem_module.c
- applications/serial_lte_modem/src/lwm2m_carrier/slm_at_carrier.c
- samples/cellular/http_update/application_update/src/main.c
- samples/cellular/lwm2m_carrier/src/main.c
- samples/cellular/modem_shell/src/shell.c
Add logs for the events `LWM2M_CARRIER_EVENT_MODEM_DOMAIN` and `LWM2M_CARRIER_EVENT_APP_DATA` to the samples and applications where these were missing.
> Add missing Carrier library event logs

- doc/nrf/links.txt
- doc/nrf/protocols/matter/end_product/attestation.rst
- doc/nrf/protocols/matter/end_product/certification.rst
Request from PMT to update links that point to the Infocenter to instead point to the new docs site. This handles links in the Matter protocol section.
Also updates the links to Matter Certification Specification to point to the Matter Resource Kit instead of the github source.
> doc: Matter: Update links to point to the new docs site

- applications/matter_bridge/Kconfig
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
This commit deletes EXPERIMENTAL symbol for the matter bridge application.
> applications: Matter Bridge is no more experimental

- lib/bin/lwm2m_carrier/Kconfig
The lwm2m_carrier_thread stack size must be bigger when building with NEWLIB libc.
> lib: bin: lwm2m_carrier: Fix lwm2m_carrier_thread size

- applications/serial_lte_modem/src/lwm2m_carrier/Kconfig
Defined a maximum range for SLM_CARRIER_APP_DATA_BUFFER_LEN to prevent stack overflow on the system work queue, whose size is configured independently, and to conform with a requirement from one of the operators.
> applications: serial_lte_modem: set range for data buffer length

- lib/bin/lwm2m_carrier/os/lwm2m_carrier.c
Prevent an illegal combination of configured server binding and server URI in the LwM2M Carrier library
> lib: bin: lwm2m_carrier: Prevent illegal Carrier library configuration

- doc/nrfx/nrfx.doxyfile.in
GENERATE_HTML must be set to avoid warnings about undocumented parameters. Additionally, alias for refhal function was missing.
Ref: NRFX-5192
> doc: nrfx: fix missing refhal and undocumented parameters

- doc/nrf/libraries/networking/aws_fota.rst
Include section regarding increased memory usage
when using presigned URLs.
Removed modem nRF91 modem specific section from
the library doc. The library docs are chip agnostic.
NCSDK-26360
> doc improvement: aws_fota: Extend troubleshooting section

- doc/nrf/config_and_build/dfu/index.rst
- doc/nrf/device_guides/working_with_nrf/nrf70/developing/index.rst
- doc/nrf/device_guides/working_with_nrf/nrf70/developing/nrf70_fw_patch_update.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Follow-up to https://github.com/nrfconnect/sdk-nrf/pull/14075
- Move Wi-FI FW patch update page from DFU page to Developing with nRF70 Series
- Added a release note entry for what was covered in https://github.com/nrfconnect/sdk-nrf/pull/14075
- Added cross-ref links to 2 device specific guides in the DFU page
> doc improvement: move wifi fw page

- applications/asset_tracker_v2/tests/ui_module/testcase.yaml
Remove testcase for qemu cortex m3.
We already support native sim which is sufficient.
NCSDK-26369
> applications: asset_tracker_v2: Remove testcase

- doc/nrf/protocols/bt/bt_mesh/dfu_over_bt_mesh.rst
Add a clarification that only the nRF Connect Device Manager app on Android supports shell access, used for Mesh DFU.
> doc: bluetooth: mesh: Clarify that DFU shell using app requires Android

- applications/serial_lte_modem/doc/slm_description.rst
Fix connectivity bridge documentation for Thingy:91. It is pre-programmed and does not necessarily need to be updated.
> applications: serial_lte_modem: Fix connectivity bridge doc

- applications/nrf5340_audio/CMakeLists.txt
- Only use empty_net_core if LL_ACS_nRF53 is chosen
- Only run ble5-ctr-rpmsg_sign.py on LL_ACS_nRF53 images
> applications: nrf5340_audio: Only build empty_net_core if LL_ACS_nRF53

- drivers/wifi/nrf700x/src/wifi_mgmt.c
The change fixes an issue where in monitor mode was able to be configured when station was in connected state. Disallow monitor mode to be set when station is in connected state.
Fixes SHEL-2555
> drivers: wifi: Fix setting monitor mode when station is connected

- west.yml
Fixes a false positive warning print when user issues a disconnect.
Fixes SHEL-2561.
> manifest: sdk-hostap: Pull fix for false disconnection failure

- samples/bluetooth/mesh/sensor_client/README.rst
This commit should add some clarity in what each button does in the sensor_client sample.
> Bluetooth: Mesh: Clarify buttons description in sensor client sample

- subsys/bootloader/bl_boot/bl_boot.c
These pins might be source of the current leakage, which actually is observed on PCA 10095 2.0.1
Added procedure for setting these pins to default state.
Ref.: NCSDK-26253
> subsy/bootloader/bl_boot: uninitialized UARTE pins

- doc/nrf/libraries/security/nrf_security/doc/driver_config.rst
Extend the table with RSA key sizes to list the support by different crypto  backends
Ref: NCSDK-22536
> doc: nrf_security: Add RSA key size support table

- modules/hostap/src/supp_main.c
In presence of non-Wi-Fi interfaces such as netusb, thread etc this print pops up as error, but it's an expected behaviour, we should silently ignore non-Wi-Fi interfaces. Convert to a debug print.
Also, improve the print by logging the interface name in question.
Fixes SHEL-2569.
> modules: hostap: Fix log level for an expected print

- subsys/bluetooth/mesh/shell/shell_sensor_cli.c
This commit fixes access to uninitialized `mod` variable by getting `cli` address only after fetching the model address.
> Bluetooth: Mesh: Fix bus fault in shell_sensor_cli.c

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- lib/dk_buttons_and_leds/Kconfig
- lib/dk_buttons_and_leds/dk_buttons_and_leds.c
Add no interrupts mode for buttons (CONFIG_DK_LIBRARY_BUTTON_NO_ISR). This option avoids relying on GPIO interrupts at all and unconditionally periodically scan all of the buttons.
It can be used on the nRF54L15 PDK revision 0.2.X, where buttons 3 and 4 are connected to GPIO PORT2 which does not support GPIOTE. Because of that, the PDK cannot rely on GPIO interrupts for the mentioned buttons.
Jira: NCSDK-23210
> lib: dk_buttons_and_leds: Add no interrupts mode for buttons

- drivers/wifi/nrf700x/Kconfig
Short Range(SR) side RF switch configuration is not happening as expected because of the typo in Wi-Fi driver Kconfig.
Fixes SHEL-2572.
> drivers: wifi: Fix SR switch configuration

- cmake/partition_manager.cmake
- modules/mcuboot/boot/zephyr/Kconfig
Change fixes references to a Kconfig option that does not exist.
Jira: NCSDK-26123
> partition_manager: Fix nRF54L support

- west.yml
This commit fixes the uninitialized variable warning appearing when compiling the door lock app.
> manifest: Fix the build warning in matter door-lock-server

- .github/workflows/docker.yml
- scripts/docker/Dockerfile
- scripts/docker/entrypoint.sh
As docker push operation has failed we are switching to using bot user for pushing docker image.
> ci: hotfix for ncs-toolchain docker image 

- applications/matter_bridge/Kconfig
- applications/matter_weather_station/Kconfig
- samples/matter/light_bulb/Kconfig
- samples/matter/light_switch/Kconfig
- samples/matter/lock/Kconfig
- samples/matter/template/Kconfig
- samples/matter/thermostat/Kconfig
- samples/matter/window_covering/Kconfig
Avoid using ZEPHYR_BASE in relative paths when sourcing Kconfig. Use ZEPHYR_NRF_MODULE_DIR instead.
> samples: matter: Fix Kconfig paths

- west.yml
Pull a fix for a crash that might happen if a Matter device would receive a lot of commands at the same time.
> matter: fix crash on packet buffer allocation failure

- samples/caf_sensor_manager/Kconfig.sysbuild
- samples/caf_sensor_manager/boards/nrf54h20pdk_nrf54h20_cpuapp_multicore.conf
- samples/caf_sensor_manager/boards/nrf54h20pdk_nrf54h20_cpuapp_multicore.overlay
- samples/caf_sensor_manager/boards/nrf54h20pdk_nrf54h20_cpuapp_singlecore.conf
- samples/caf_sensor_manager/boards/nrf54h20pdk_nrf54h20_cpuapp_singlecore.overlay
- samples/caf_sensor_manager/remote/boards/nrf54h20pdk_nrf54h20_cpuppr.conf
- samples/caf_sensor_manager/remote/boards/nrf54h20pdk_nrf54h20_cpuppr.overlay
- samples/caf_sensor_manager/sample.yaml
- samples/caf_sensor_manager/sysbuild.cmake
- samples/caf_sensor_manager/sysbuild/nrf54h20pdk_nrf54h20_cpuppr.conf
Add two configurations for nRF54H20.
One with a single core operation and another with PPR working as a remote provider of sensor data.
nRF54H20 requires sysbuild.
> samples: caf_sensor_manager: Add nrf54h20 configuration

- applications/serial_lte_modem/Kconfig
- applications/serial_lte_modem/README.rst
- applications/serial_lte_modem/doc/AT_commands.rst
- applications/serial_lte_modem/doc/CMUX_AT_commands.rst
- applications/serial_lte_modem/doc/PPP_AT_commands.rst
- applications/serial_lte_modem/doc/nRF91_as_Zephyr_modem.rst
- applications/serial_lte_modem/doc/slm_description.rst
- doc/nrf/releases_and_maturity/releases/release-notes-1.9.0.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/cellular/slm_shell/README.rst
Document the newly introduced support for Zephyr's generic modem driver.
> applications: serial_lte_modem: document the Zephyr modem compatibility

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/wifi/radio_test/radio_test_subcommands.rst
- samples/wifi/radio_test/sample_description.rst
[SHEL-2521]: The documentation for recently incorporated RF test commands has been updated within the radio test sample. Furthermore, the TX command sequences have been revised to demonstrate the utilization of these newly integrated commands.
[SHEL-2521]: https://nordicsemi.atlassian.net/browse/SHEL-2521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> doc: wifi: Update radio test documents to reflect new commands

- applications/nrf5340_audio/dfu/conf/Kconfig.dfu
- applications/nrf5340_audio/sample.yaml
- Only change default to y if building for LL_ACS_NRF53
- OCT-2839
> applications: nrf5340_audio: Only enable empty_core for ACS_NRF53

- doc/nrf/protocols/wifi/scan_mode/scan_operation.rst
- doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
- samples/wifi/scan/src/main.c
Correct the Kconfig options that are assigned to dwell_time in test profiles defined for active scan and passive scan. Update the corresponding documentation as well.
> samples: wifi: scan: Rectify the Kconfig options for dwell_time

- doc/_extensions/manifest_revisions_table.py
- west.yml
.git suffix cannot be used to form valid URLs.
> manifest: remove .git suffixes from repository paths

- samples/bluetooth/fast_pair/input_device/boards/nrf54l15pdk_nrf54l15_cpuapp.conf
- samples/bluetooth/fast_pair/input_device/sample.yaml
Depends on: 
* https://github.com/nrfconnect/sdk-nrf/pull/14285 -> buttons workaround
* https://github.com/nrfconnect/sdk-nrf/pull/14368 -> partition manager for nRF54L fix
* https://github.com/nrfconnect/sdk-nrf/pull/14409 -> partition manager for nRF54L support in sysbuild
Jira: NCSDK-26123
> samples: bluetooth: fast_pair: input_device: Add init nRF54L support 

- samples/ipc/ipc_service/sample.yaml
This commit gives the network core just enought time to be able to log data as expected in cpuapp_sending test.
JIRA: NCSDK-26392
> samples: ipc: ipc_service: Fix cpunet logging for nrf5340

- doc/nrf/libraries/networking/nrf_cloud.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- include/net/nrf_cloud.h
- include/net/nrf_cloud_fota_poll.h
- samples/cellular/nrf_cloud_multi_service/src/cloud_connection.c
- samples/cellular/nrf_cloud_multi_service/src/fota_support_coap.c
- samples/cellular/nrf_cloud_multi_service/src/fota_support_coap.h
- samples/cellular/nrf_cloud_rest_fota/prj.conf
- samples/cellular/nrf_cloud_rest_fota/src/main.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_fota_poll.c
The nrf_cloud_rest_fota sample failed to build when JITP
was enabled.
Update the nrf_cloud_fota_poll module to allow for the
pending job type to be accessed by the application.
Moved fota_download_init into nrf_cloud_fota_poll_init.
Added function comments and moved into nrf_cloud_fota_poll.h
Increased AT host stack size for the nrf_cloud_rest_fota
sample.
Also, corrected changelog entries from https://github.com/nrfconnect/sdk-nrf/pull/13545.
IRIS-8444
> net: lib: nrf_cloud: fix build issue with FOTA poll support

- scripts/quarantine_windows_mac.yaml
Asset_tracker tests with sysbuild are failing on Windows. The root cause it not yet known. However, those are not assured to work before the sysbuild is full ported to NCS.
> quarantine: windows: Update quarantine for Windows CI

- samples/bluetooth/peripheral_uart/src/uart_async_adapter.c
This commit updates the timing in uart_async_adapter to match the values described in UART API.
The API describes timeout values to be in microseconds unit while uart_async_adapter was asuming them to be in miliseconds.
JIRA: NCSDK-26241
> samples: bluetooth: peripheral_uart: Fix timing in uart_async_adapter

- west.yml
This commit pulls bugfix for Network Commissioning cluster certification issues as well as critical issue with connection error handling.
ref.: KRKNWK-18610
> manifest: Update sdk-connectedhomip revision

- doc/nrf/libraries/security/nrf_security/doc/driver_config.rst
The cryptocell driver can only produce 1024 random bytes per request, so we should list tis limitation
Ref: NCSDK-24840
> doc: cc3xx: Add limitation of rng driver
