nrfconnect/sdk-nrf

applications/serial_lte_modem/boards/thingy91_nrf9160_ns.conf
applications/serial_lte_modem/boards/thingy91_nrf9160_ns.overlay

applications: serial_lte_modem: Disable hwfc with Thingy:91

---

west.yml

Update to include latest changes to nrfxlib and dragoon.

manifest: Update nrfxlib and dragoon to latest

---

doc/nrf/external_comp/memfault.rst
doc/nrf/links.txt

Fixed and updated a few links + cleaning
up the language a bit.

doc: Memfault integration: link fixes

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/cellular/nrf_cloud_multi_service/boards/thingy91_nrf9160_ns.conf
samples/cellular/nrf_cloud_multi_service/boards/thingy91_nrf9160_ns.overlay

Get the sample to build again for the Thingy91.

samples: cellular: nrf_cloud_multi_service: Fix Thingy91

---

subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_adv_firmware.c
subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_conneval.c
subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c

Remove unnecessary header includes.
Check return value from functions.

Lwm2m client utils fixes

---

samples/cellular/modem_shell/src/link/link_shell.c
samples/cellular/modem_shell/src/location/location_shell.c
samples/cellular/modem_shell/src/ping/icmp_ping_shell.c
samples/cellular/modem_shell/src/ppp/ppp_shell.c
samples/cellular/modem_shell/src/rest/rest_shell.c
samples/cellular/modem_shell/src/sms/sms_shell.c
samples/cellular/modem_shell/src/sock/sock_shell.c
samples/cellular/modem_shell/src/startup_cmd/startup_cmd_shell.c

Improve error handling of invalid command line options.
Jira: MOSH-530

samples: cellular: modem_shell: link: Improve command line parsing

---

applications/nrf_desktop/README.rst

Change improves memory layout configuration documentation to simplify gettings started for new users.
Jira: NCSDK-24518

applications: nrf_desktop: Improve memory layout documentation

---

applications/nrf_desktop/README.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

nRF Desktop docs improvements: Bootloader and Background DFU section

---

CODEOWNERS

Add codeowners entry for samples/debug/memfault

codeowners: Update memfault sample

---

CODEOWNERS

CODEOWNERS: Remove jheiskan81

---

applications/matter_bridge/src/ble_providers/ble_onoff_light_data_provider.cpp
applications/matter_bridge/src/ble_providers/ble_onoff_light_data_provider.h

Implemented subscription to the button characteristic of LBS service.

applications: Added handling button subscriptions in Matter bridge

---

.github/test-spec.yml

Add net/udp sample to thingy91-test label.

test-spec: Add samples/net/udp

---

west.yml

Applications: nrf5340_audio: Manifest update for sdk-mcu-drivers

---

samples/matter/thermostat/README.rst

This commit fix documentation of thermostat

matter: samples: thermostat: doc: Fixed thermostat documentation

---

doc/nrf/device_guides/working_with_nrf/nrf70/developing/powersave.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Updated the Power Save modes section in the "Operating in power save modes user guide".
SHEL-2236

doc: wifi: update Power save modes user guide

---

west.yml

Fixes WPA supplicant interval events reception.

manifest: sdk-hostap: Pull WPA supplicant internal event fixes

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/bluetooth/direct_test_mode/README.rst
samples/bluetooth/direct_test_mode/no-dfe.overlay

Add option and overlay to disable Direction Finding in DTM sample.
Jira: NCSDK-23414

samples: Add option to disable DF in DTM

---

doc/nrf/libraries/dfu/pcd.rst

doc: PCD library: link fix

---

applications/asset_tracker_v2/tests/nrf_cloud_codec_mocked_cjson/CMakeLists.txt
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/net/nrf_cloud.h
include/net/nrf_cloud_coap.h
include/net/nrf_cloud_codec.h
include/net/nrf_cloud_defs.h
samples/cellular/nrf_cloud_multi_service/src/cloud_connection.c
samples/cellular/nrf_cloud_multi_service/src/shadow_support_coap.c
subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c
subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c
subsys/net/lib/nrf_cloud/include/nrf_cloud_codec_internal.h
subsys/net/lib/nrf_cloud/include/nrf_cloud_transport.h
subsys/net/lib/nrf_cloud/src/nrf_cloud.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_codec.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_fsm.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c

Improve shadow data processing and provide application specific shadow data to the application.
IRIS-5661

nrf_cloud shadow processing updates

---

subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c

Function cleanup and comments.
IRIS-6853

net: lib: nrf_cloud: cleanup nrf_cloud_state_encode

---

west.yml

PR in sdk-zephyr cherry-picks update of the hal_nordic project with QSPI workaround fix

manifest: Update sdk-zephyr revision with QSPI workaround fix

---

doc/nrf/device_guides/working_with_nrf/nrf70/developing/powersave.rst

Dynamic power save feature is used in both TX and RX, so, reword to reflect that and also fix the mode transitions.
Also fix the typo in the link.

doc: nrf70: Improve dynamic power save

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/net/mqtt_helper.h
subsys/net/lib/mqtt_helper/mqtt_helper.c

Add support for setting MQTT password.

net: lib: mqtt_helper: Add password support

---

include/modem/pdn.h
lib/pdn/pdn.c

To retrieve parameters returned by AT+CGCONTRDP=<cid>.

lib: pdn: add function to retrieve dynamic parameters

---

applications/serial_lte_modem/doc/CARRIER_AT_commands.rst

Fix the bulleted list documenting the AT#XCARRIERCFG commands.

applications: serial_lte_modem: doc: fix bulleted list

---

applications/matter_bridge/src/bridged_device_types/generic_switch.cpp
applications/matter_bridge/src/bridged_device_types/humidity_sensor.cpp
applications/matter_bridge/src/bridged_device_types/onoff_light.cpp
applications/matter_bridge/src/bridged_device_types/temperature_sensor.cpp

Updated device type versions to match the spec.

applications: Changed bridged device endpoints version from 1 to 2

---

CODEOWNERS

Remove `marouszpos` from openthread.
Add `maciejbaczmanski` to openthread.

codeowners: Change codeowners for openthread.

---

west.yml

Regular OpenThread update to \`266a97b\`

manifest: openthread: update to \`266a97b\`

---

CODEOWNERS

Remove gopiotr from CODEOWNERS list.

CODEOWNERS: remove gopiotr

---

applications/nrf5340_audio/src/audio/streamctrl_broadcast_sink.c

- Bugfix: Change return from a thread to a break

applications: nrf5340_audio: Remove return from thread

---

samples/wifi/provisioning/sample.yaml
samples/wifi/radio_test/sample.yaml
samples/wifi/scan/sample.yaml
samples/wifi/shell/sample.yaml
samples/wifi/shutdown/sample.yaml
samples/wifi/sta/sample.yaml

Fix docs for nRF7001

---

applications/serial_lte_modem/src/slm_at_socket.c

applications: serial_lte_modem: Fix bind with IPv6

---

west.yml

Fix for assocaition request capture failure on QT tool.

manifest: Pull fix for association request capture failure

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
lib/pdn/pdn.c

Make use of nrf_modem_at_scanf() and add a changelog entry.

lib: pdn: improve pdn_dynamic_params_get()

---

samples/openthread/coap_client/src/coap_client_utils.c
samples/openthread/coap_server/src/coap_server.c

Using system workqueue with thread API calls causes deadlocks on some newer chips. Removed all tasks from system workqueue.

samples: remove workqueue from coap

---

subsys/net/openthread/Kconfig

Temporarily disable HUK usage until HUK provisioning is implemented

kconfig: openthread: Temporarily disable HUK usage

---

doc/nrf/links.txt
samples/cellular/nrf_cloud_multi_service/README.rst

Corrected links to nRF Cloud portal pages.

doc: nRF Cloud multi-service sample: link fixes

---

subsys/secure_storage/src/aead/aead_crypt_psa_chachapoly.c
subsys/secure_storage/src/aead/aead_ctr_nonce.c
subsys/secure_storage/src/aead/secure_backend_aead.c

The counter used as a nonce for the secure storage was 16 bytes but the implementation on the AEAD backend expected a 12 byte nonce. This corrupted the key material when the nonce was written.
This fixes the issue by making the counter to be 12 bytes as expected by the AEAD backend. It also ensures the AEAD backend and the counter have the same length and fails at runtime without corrupting any buffers if they differ.

secure_storage: Fix counter bug

---

drivers/entropy/Kconfig
drivers/hw_cc310/Kconfig
subsys/bootloader/bl_crypto/CMakeLists.txt
subsys/bootloader/bl_crypto/Kconfig
west.yml

Ensures nrf_cc310_bl is enabled only in bootloader settings

NSIB nrf_cc310_bl enabled only in bootloaders

---

CODEOWNERS

Remove joerchan from CODEOWNERS file.

CODEOWNERS: remove joerchan

---

west.yml

Regular OpenThread update to \`1e82c4e\`

manifest: openthread: update to \`1e82c4e\`

---

doc/nrf/releases_and_maturity/known_issues.rst

Document a known issue found during testing.
This will be fixed for NCS 2.6.

doc: document known issue

---

modules/hostap/src/wpa_cli.c
samples/wifi/shell/prj.conf
west.yml

Remove non-output status "OK/FAIL" multipal times.

manifest: update sdk-hostap revision

---

doc/nrf/releases_and_maturity/known_issues.rst

doc: Remove link

---

doc/nrf/device_guides/working_with_nrf/nrf91/nrf91_features.rst

Rearranged the heading levels. Improved `GNSS`, `Band lock` and `System mode` sections.
NCSDK-24641

doc: Improve "Features of the nRF91 Series" documentation

---

west.yml

manifest: sdk-nrfxlib: Pull fix to remove unnecessary file

---

west.yml

Regular OpenThread update to \`6751122\`

manifest: openthread: update to \`6751122\`

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/bluetooth/scan.h
subsys/bluetooth/scan.c

Commit adds connet_if_match flag update function.

bluetooth: scan: Add connect_if_match flag update function.

---

doc/nrf/releases_and_maturity/known_issues.rst
west.yml

Fix memory leak in DeferredAttributePersister class.

matter: pull deferred attribute persister fix

---

samples/matter/thermostat/sample.yaml
scripts/quarantine_integration.yaml

Additonal configuration will be used to test the thermostat with external temperature sensor and provide data via thermostat UI.

samples: matter: Add configuration for matter thermostat

---

west.yml

Regular OpenThread update to \`666a9bd\`

manifest: openthread: update to \`666a9bd\`

---

samples/cellular/nrf_cloud_multi_service/src/fota_support_coap.c

Make sure network connection is up before processing FOTA job.
Jira: IRIS-7907

samples: cellular: nrf_cloud_multi_service: Fix CoAP FOTA status report

---

drivers/wifi/nrf700x/src/wpa_supp_if.c
modules/hostap/src/supp_api.c

Fixes for issues found during integration testing.

wifi: ap: Fixes 

---

scripts/quarantine_no_optimization.yaml
subsys/net/lib/aws_iot/src/aws_iot.c
tests/subsys/net/lib/aws_iot/src/aws_iot_test.c

- net: lib: aws_iot: Add null pointer check in strnstr
- test: aws_iot: Fix segfault in unit test

test: aws_iot: Fix segfault in unit test

---

west.yml

Regular OpenThread update to \`b28bb1d\`

manifest: openthread: update to \`b28bb1d\`

---

samples/cellular/nrf_cloud_multi_service/README.rst

Converted a bullet list to a table, thus
avoiding some redundancy.

doc: list to table in nRF Cloud multi-service sample

---

applications/nrf5340_audio/src/audio/streamctrl_unicast_client.c
applications/nrf5340_audio/src/audio/streamctrl_unicast_server.c
applications/nrf5340_audio/src/bluetooth/bt_stream/CMakeLists.txt
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/Kconfig.defaults
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.h
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.h
applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/CMakeLists.txt
applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.h
applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c
applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/Kconfig.defaults
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.h
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.h
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Applications: nrf5340_audio: refactored sending iso data

---

samples/pmic/native/npm1300_one_button/CMakeLists.txt
samples/pmic/native/npm1300_one_button/README.rst
samples/pmic/native/npm1300_one_button/nrf52840dk_nrf52840.overlay
samples/pmic/native/npm1300_one_button/nrf52dk_nrf52832.overlay
samples/pmic/native/npm1300_one_button/nrf5340dk_nrf5340_cpuapp.overlay
samples/pmic/native/npm1300_one_button/nrf9160dk_nrf9160.overlay
samples/pmic/native/npm1300_one_button/prj.conf
samples/pmic/native/npm1300_one_button/sample.yaml
samples/pmic/native/npm1300_one_button/src/CMakeLists.txt
samples/pmic/native/npm1300_one_button/src/main.c

Added one button nPM1300 PMIC sample

samples: pmic: npm1300_one_button: Added sample

---

.github/workflows/compliance.yml
.github/workflows/create-upmerge-PRs.yml
.github/workflows/docbuild.yml
.github/workflows/license-reusable.yml
.github/workflows/oss-history.yml
.github/workflows/pip-requirements.yml

Use separate action for checking out the source code. Composite action can be found from here: https://github.com/NordicBuilder/action-checkout-west-update/

ci: use composite checkout action

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Added the forgotten changelog entry.

doc: add changelog entry for nPM1300 One button sample

---

doc/nrf/releases_and_maturity/known_issues.rst

Update known_issue.rst with Matter KRKNWK-18315 issue

doc: update known_issue.rst with Matter issue

---

applications/matter_bridge/src/ble_providers/ble_bridged_device_factory.cpp
applications/matter_bridge/src/bridge_shell.cpp

Added check that prevents from adding the same Bluetooth LE device to the bridge multiple times.

applications: Fixed duplicated add issue for Matter BT bridge

---

samples/cellular/lwm2m_client/CMakeLists.txt
samples/cellular/lwm2m_client/src/shell.c

Add shell commands for testing functionality that
would trigger on a button press.
uart:~$ app
app - LwM2M client application commands
Subcommands:
gnss  : Trigger GNSS search
gfix  : Trigger Ground Fix location request

samples: lwm2m_client: Add shell commands for testing

---

doc/kconfig/conf.py
doc/matter/conf.py
doc/mcuboot/conf.py
doc/nrf/conf.py
doc/nrfx/conf.py
doc/nrfxlib/conf.py
doc/tfm/conf.py
doc/zephyr/conf.py

Update copyright year to 2024 in docs.

doc: update copyright year in conf.py files

---

doc/nrf/libraries/networking/nrf_cloud_coap.rst
include/net/lwm2m_client_utils.h
samples/cellular/lwm2m_client/prj.conf
samples/cellular/lwm2m_client/src/main.c
samples/cellular/modem_shell/src/cloud/cloud_lwm2m.c
samples/net/coap_client/src/main.c
subsys/net/lib/download_client/src/coap.c
subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_rai.c
subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_utils_con_management.c
subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_coap
subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c
subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c
tests/subsys/net/lib/nrf_provisioning/testcase.yaml
west.yml

* Fetch LwM2M and CoAP related updates from upstream Zephyr.
* Refactor LwM2M client utils RAI module to use new socket state indication.
* Refactor CoAP client to use transmission parameters.

Fetch LwM2M and CoAP related updates from upstream Zephyr.

---

west.yml

Regular OpenThread update to \`f75e2bb\`

manifest: openthread: update to \`f75e2bb\`

---

doc/nrf/includes/net_connection_manager.txt
samples/debug/memfault/README.rst
samples/net/aws_iot/README.rst
samples/net/azure_iot_hub/README.rst
samples/net/coap_client/README.rst
samples/net/download/README.rst
samples/net/https_client/README.rst
samples/net/mqtt/doc/description.rst
samples/net/udp/README.rst

Add connection manager content to networking samples.

doc: Add connection manager content to networking samples

---

samples/peripheral/802154_phy_test/sample.yaml

Build additional nrf52833dk_nrf52833 platform

samples: peripheral: 802154_phy_test: update platforms

---

west.yml

Updated sdk-zephyr to add change scope to run test suite for PMIC samples

manifest: sdk-zephyr: Added scope for PMIC samples tests

---

doc/tags.yml

Edit the tags file to include nRF9161

doc: Edit the tags file to include nRF9161

---

west.yml

manifest: sdk-nrfxlib: Pull nRF70 patch update rev#4fbb188dc93

---

west.yml

This manifest updates chip to the latest version.

manifest: matter: Update to the latest sdk-connectedhomeip

---

subsys/dfu/dfu_target/src/dfu_target_modem_delta.c

Translate the most common modem delta DFU errors concerning image integrity checks and OOM failures into discernible errno values. This information may be required by applications to better understand the reason behind the failure.

subsys: dfu: dfu_target: extend errno translation

---

applications/serial_lte_modem/CMakeLists.txt
applications/serial_lte_modem/Kconfig
applications/serial_lte_modem/overlay-cmux.conf
applications/serial_lte_modem/src/slm_at_commands.c
applications/serial_lte_modem/src/slm_cmux.c
applications/serial_lte_modem/src/slm_cmux.h
applications/serial_lte_modem/src/slm_uart_handler.c
applications/serial_lte_modem/src/slm_uart_handler.h

2 channels are configured and simply echo what is received.

slm: preliminary CMUX implementation

---

tests/subsys/net/lib/nrf_provisioning/src/coap.c

Fix warning from coap_client's API change.

tests: nrf_provisioning: Fix warning

---

west.yml

manifest: update

---

west.yml

Regular OpenThread update to \`7761b81\`

manifest: openthread: update to \`7761b81\`

---

samples/matter/template/sample.yaml

Add sample with migrate DAC private key config.

samples: matter: template with migrate DAC priv key config added

---

doc/mcuboot/links.txt
doc/mcuboot/readme-ncs.rst

[NCSIDB-1184](https://nordicsemi.atlassian.net/browse/NCSIDB-1184) as reported by SH in tech support
Update NCS links on the [Using MCUboot page](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/mcuboot/readme-ncs.html)
[NCSIDB-1184]: https://nordicsemi.atlassian.net/browse/NCSIDB-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc: update mcuboot links

---

samples/matter/common/src/board/board.cpp

In updateStatus LED there was one state missing.

samples: matter: Add missing state for LEDs

---

samples/hw_id/src/main.c

Initialize modem for overlays that require it.

samples: hw_id: Initialize modem for overlays

---

west.yml

Introduce cherry picks into zephyr-sdk with openthread PSA related fixes.

manifest: zephyr: Update zephyr with PSA related fixes.

---

west.yml

Includes fixes and some documentation covering Isochronous channels. More fixes and more documentation will be added later.

manifest: Update nrfxlib with new SoftDevice Controller

---

west.yml

Regular OpenThread update to \`ab28127\`

manifest: openthread: update to \`ab28127\`

---

applications/asset_tracker_v2/boards/nrf9151dk_nrf9151_ns.conf
applications/asset_tracker_v2/boards/nrf9151dk_nrf9151_ns.overlay
applications/asset_tracker_v2/child_image/mcuboot/boards/nrf9151dk_nrf9151.conf
applications/asset_tracker_v2/child_image/mcuboot/boards/nrf9151dk_nrf9151.overlay
applications/asset_tracker_v2/include/nrf9151dk_nrf9151_ns/led_state_def.h

Add nRF9151 support in asset_tracker_v2.

applications: asset_tracker_v2: add 9151 support

---

west.yml

manifest: update psa-arch-tests

---

drivers/wifi/nrf700x/Kconfig
drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
modules/hostap/src/supp_api.c
modules/hostap/src/supp_api.h
samples/wifi/sr_coex/src/main.c
samples/wifi/sta/src/main.c
samples/wifi/twt/src/main.c
subsys/net/lib/wifi_mgmt_ext/Kconfig
subsys/net/lib/wifi_mgmt_ext/wifi_mgmt_ext.c
west.yml

Customer has requested for a band selection fixes to be backported to 2.5.2

wifi: Fix band selection

---

applications/nrf5340_audio/src/audio/audio_datapath.c
applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c

OCT-2809
integrate timestamps for L-R sync

Applications: nrf5340_audio: timestamp implementation

---

include/net/download_client.h
subsys/net/lib/download_client/src/download_client.c

typo: Fix typo in download_client

---

west.yml

updating sdk-nrfxlib and dragoon revision to bring changes and bugfixes for softdevice controller and mpsl.

manifest: update sdk-nrfxlib and dragoon rev

---

doc/_utils/redirects.py
doc/nrf/create_application.rst
doc/tags.yml

Minor updates to redirect and tag files plus a typo fix. NCSDK-22325.

doc: minor redirect and tag fixes

---

west.yml

manifest: sdk-nrfxlib: Pull nRF70 patch update rev#1c581c70da5

---

doc/nrf/config_and_build/programming.rst
doc/nrf/links.txt

Updated mentions of nRF Connect Programmer.
Updated links to the latest version of the app docs. NCD-651.

doc: update mentions of nRF Connect Programmer

---

applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c

- Some devices set their preferred pres delay to 0, in those cases we need to set pres delay to common minimum

applications: nrf5340_audio: Handle pref_pres_dly of 0

---

west.yml

Brings in new functionality and documentation.
See CHANGELOG for additional details.

manifest: Update nrfxlib with new SoftDevice Controller revision

---

applications/nrf5340_audio/broadcast_sink/README.rst
applications/nrf5340_audio/broadcast_source/README.rst
applications/nrf5340_audio/doc/building.rst
applications/nrf5340_audio/doc/configuration.rst
applications/nrf5340_audio/doc/user_interface.rst
applications/nrf5340_audio/unicast_client/README.rst
applications/nrf5340_audio/unicast_server/README.rst
doc/nrf/config_and_build/multi_image.rst
doc/nrf/libraries/bin/bt_ll_acs_nrf53/index.rst
doc/nrf/releases_and_maturity/software_maturity.rst

Added doc fixes from testing the new app split.

doc: nrf5340audio: fixes from testing

---

west.yml

Regular OpenThread update to \`75abc7c\`

manifest: openthread: update to \`75abc7c\`

---

drivers/wifi/nrf700x/src/fmac_main.c
west.yml

Update regulaory related info like channels supported, dfs support  etc.

wifi: Extend regulatory information

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
doc/nrf/test_and_optimize/optimizing/power_general.rst

The new sections describe the possible options for power optimization in Gazell and NFC libraries.

doc: add Gazell and NFC sections in the power optimization guide.

---

west.yml

Update MCUBoot to include board overlays for the thingy91x.

[manifest] update mcuboot

---

applications/nrf5340_audio/unicast_client/main.c
applications/nrf5340_audio/unicast_server/main.c

Remove play/pause feature for CIS bidir mode.
OCT-2892

applications: nrf5340_audio: Remove pause feature for bidir CIS

---

scripts/quarantine_zephyr.yaml

Updates quarantine with a recently failing tests.
Move "won't fix" tests to a dedicated section for clarity.

Quarantine update

---

subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_conneval.c

Remove work item used to pause lwm2m_engine and call directly lwm2m_engine_pause().

net: lwm2m_client_utils: Remove work item from conneval

---

west.yml

Bring in latest changes from nrfxlib and dragoon to nrf

manifest: nrfxlib and dragoon: Update to latest

---

applications/matter_bridge/src/ble_providers/ble_bridged_device_factory.cpp
samples/matter/common/src/bridge/ble_bridged_device.h
samples/matter/common/src/bridge/ble_connectivity_manager.cpp
samples/matter/common/src/bridge/ble_connectivity_manager.h
samples/matter/common/src/bridge/bridge_manager.cpp
samples/matter/common/src/bridge/bridge_manager.h

* Fixed ownership violation of the provider object
* Fixed races occurring when the provider cannot be added to the
BridgeManager
* Secured the edge cases when the BLE discovery fails
* Enhanced InitializeBridgedDevice API and its documentation

applications: Matter Bridge: fixed handling of the provider object

---

subsys/bluetooth/controller/hci_driver.c

Update to use the new API, the old one will be removed.

bluetooth: controller: hci_driver: Use new ISO buffer config

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/cellular/modem_shell/src/sock/sock.c
samples/cellular/modem_shell/src/sock/sock.h
samples/cellular/modem_shell/src/sock/sock_shell.c

* Add a sock command to do getaddrinfo().
* Allow PDN CID 0 for connect().

samples: cellular: modem_shell: Add sock getaddrinfo

---

samples/cellular/lwm2m_client/scripts/atclient.py

Allow different line endings in provisioning script.
If the device is flashed with Serial LTE Modem, we should use \r, instead of \n what the AT client is accepting.

samples: lwm2m-client: Allow different line ending

---

doc/nrf/installation/install_ncs.rst
doc/nrf/links.txt

Aligned installation steps with the Dev Academy exercise. Requested by stakeholders.

doc: install_ncs: align with Dev Academy

---

west.yml

Update new version of mpsl and nrfxlib

manifest: update mpsl and sdc in nrfxlib

---

doc/nrf/device_guides/working_with_nrf/nrf70/developing/constrained.rst
doc/nrf/device_guides/working_with_nrf/nrf70/developing/fw_patches_ext_flash.rst
doc/nrf/device_guides/working_with_nrf/nrf70/features.rst
doc/nrf/device_guides/working_with_nrf/nrf70/nrf7002eb_gs.rst
doc/nrf/device_guides/working_with_nrf/nrf70/nrf7002ek_gs.rst
doc/nrf/protocols/wifi/raw_tx_operation.rst
doc/nrf/protocols/wifi/regulatory_support.rst
doc/nrf/protocols/wifi/sap.rst
doc/nrf/protocols/wifi/wifi.rst

Minor fixes to various wi-fi documents.

doc: wifi: minor doc fixes

---

applications/serial_lte_modem/doc/slm_description.rst
doc/nrf/device_guides/working_with_nrf/nrf91/nrf91_features.rst
doc/nrf/device_guides/working_with_nrf/nrf91/thingy91.rst
doc/nrf/includes/nrf_cloud_rest_sample_requirements.txt
doc/nrf/includes/sample_board_rows.txt
doc/nrf/libraries/modem/modem_battery.rst
doc/nrf/libraries/modem/modem_key_mgmt.rst
doc/nrf/libraries/modem/pdn.rst
doc/nrf/links.txt
doc/nrf/security/ap_protect.rst
samples/cellular/lwm2m_client/provisioning.rst
samples/cellular/pdn/README.rst
samples/cellular/udp/README.rst
west.yml

Add links of Hardware and PS docs
to NCS.
NCSDK-23571

doc: Add links of the nRF9161 Hardware and PS guides in the NCS docs

---

west.yml

Regular OpenThread update to \`905a22e\`

manifest: openthread: update to \`905a22e\`

---

samples/cellular/modem_shell/CMakeLists.txt
samples/cellular/modem_shell/src/at/at_cmd_ping.c
samples/cellular/modem_shell/src/drivers/nrf91_non_offloaded_dev.c
samples/cellular/modem_shell/src/link/link.c
samples/cellular/modem_shell/src/link/link_api.c
samples/cellular/modem_shell/src/main.c
samples/cellular/modem_shell/src/ping/icmp_ping.c
samples/cellular/modem_shell/src/shell.c
samples/cellular/modem_shell/src/sock/sock_shell.c
samples/cellular/modem_shell/src/th/CMakeLists.txt
samples/cellular/modem_shell/src/th/th_ctrl.c
samples/cellular/modem_shell/src/th/th_shell.c

Cleaned up include directories in CMakeLists.txt.

samples: cellular: modem_shell: Cleanup include directories

---

applications/serial_lte_modem/src/slm_at_socket.c
applications/serial_lte_modem/src/slm_at_socket.h

Use socket options instead of polling with socket send and recv.

applications: serial_lte_modem: Replace poll in send/recv

---

doc/_scripts/software_maturity/software_maturity_features.yaml
doc/nrf/protocols/wifi/raw_tx_operation.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

This documentation update handles the change in TX injection mode command becoming a network shell command from a Wi-Fi shell command

nrf: doc: Update TX injection documentation

---

subsys/bluetooth/mesh/sensor.c

After removing `HAS_UNDEFINED` flag from `percentage_delta_trigger` sensor format, MMDL/SR/SNRS/BV-09-C PTS test started failing, because the sensor server started publishing with the fast cadence instead of the normal cadence.
The investigation showed that the multiplication of the threshold and the previous sensor state could cause int64_t overflow. This is because both are scaled preliminary by the `SENSOR_MILL` macro. Due to the overflow, the `bt_mesh_sensor_delta_threshold` function was always returning `true`, which made the sensor incorrectly use the fast cadence.
This change does the multiplication of both parts of the `sensor_value` separately before scaling it by the `SENSOR_MILL` macro to avoid the overflow.

Bluetooth: Mesh: Fix threshold value overflow

---

doc/nrf/device_guides/working_with_nrf/nrf70/gs.rst

The workflow described here is not supported in NCS so we delete this documentation.

doc: nrf70: Remove documentation for unsupported feature

---

west.yml

Brings in libraries for nrf54H/L.

manifest: Update nrfxlib with mpsl and sdc

---

applications/matter_weather_station/src/app_task.cpp

We need to initialize advertising and BLE SMP service before starting the "DFU over SMP" server. Schedule starting the server beyond the Application's init and do it in the Matter's thread.

applications: matter: Repair Weather Station BLE advertising

---

subsys/mpsl/pin_debug/mpsl_pin_debug_radio_core.c

added &gpiote instance to all GPIOTE API calls
It is needed due to recent changes in nrfx.
Use hard-coded GPIOTE0 instance for now.

MPSL: Fix CONFIG_MPSL_PIN_DEBUG option

---

west.yml

manifest: sdk-nrfxlib: Pull nRF70 patch update rev#70c67b7418a

---

applications/matter_bridge/src/ble_providers/ble_bridged_device_factory.cpp

Fixed hypothetical memory leakage that could happen in case some device objects would be created, but then creation of one in a row would fail. In such scenario the already allocated objects has to be deleted.

applications: Fixed hypothetical memory leakage in Matter bridge

---

west.yml

* 992936300bf - net: lwm2m: Use CID_SUPPORTED instead
* bf872870eab - net: lwm2m: Fix segfault on failed boo
* 9eee8d2be59 - net: lwm2m: Allow send operations when sleeping

manifest: Fetch upstream LwM2M changes

---

applications/matter_bridge/sample.yaml

Commit adds additional matter simulated bridge sample with smp dfu enabled.

samples: matter: Matter simulated bridge with SMP DFU sample

---

west.yml

OCT-2902
Cherry-pick relevant upstream bugfixes

manifest: Update Zephyr version

---

doc/nrf/libraries/networking/azure_iot_hub.rst
doc/nrf/shortcuts.txt
samples/cellular/ciphersuites/README.rst
samples/cellular/lwm2m_carrier/provisioning.rst
samples/net/download/README.rst
samples/net/https_client/README.rst

doc: Minor doc fixes

---

subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_rai.c

Sometimes LwM2M engine is already indicating NO_DATA but we are not yet on QUEUE_RX_OFF state.
If we receive CoAP packet during this period, it means that server have something for us.
But as the callback does not get any indication on RX side we only know that we have received CoAP traffic if the state transitions from NO_DATA to LAST.
When this transition happen, stop the RAI indications until we are in silent period for a while (QUEUE_RX_OFF).
This fix a behaviour seen on Nb-IoT where RRC connection is released and started between each CoaP GET/Ack pair.

net: lwm2m_client_utils: Set RAI_ONGOIN if we receive cmd

---

west.yml

Brings in latest sdk-zephyr updates including
host channel classification fix.

manifest: Update to latest sdk-zephyr version

---

doc/nrf/installation/recommended_versions.rst
doc/nrf/links.txt
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Updated the OS support table.
NRFU-891.

doc: reqs: update OS support table

---

west.yml

Pull upstream commits with DHCPv4 server improvements to sdk-zephyr.

manifest: Pull Zephyr DHCPv4 server improvements

---

west.yml

Regular OpenThread update to \`49c59ec\`

manifest: openthread: update to \`49c59ec\`

---

applications/nrf5340_audio/src/audio/audio_datapath.c
applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c

OCT-2916
Throwing data on negative timestamps

Applications: nrf5340_audio: Neg timestamp fix

---

samples/net/download/sample.yaml

samples: net: download: Add default config to CI

---

samples/cellular/lwm2m_client/README.rst
samples/cellular/lwm2m_client/sample_description.rst

Add link to Zephyr LwM2M sample which is demonstrates basic LwM2M functionality.
Update some configuration values.

doc: lwm2m_client: Update documentation

---

doc/nrf/protocols/wifi/sniffer_rx_operation.rst

Update Monitor mode documentation for filter settings and minor corrections in documentation.

doc: nrf: Update Monitor mode documentation

---

doc/nrf/protocols/matter/overview/dev_model.rst

Added entry describing overview of changes introduced with Matter 1.2.0.

doc: Matter: Add v1.2.0 to Matter versions table

---

doc/nrf/libraries/nrf_security/doc/configuration.rst

Add disclaimer about thread safety.

doc: nrf_security: Add disclaimer about thread safety

---

lib/supl/os/lte_params.c

Implemented a workaround for a bug in the SUPL client library. The library causes a crash if the `status` field in the `lte_params` structure is set to `false`. As a workaround, the `status` field is now always set to `true`. If LTE registration information is not available, all parameters in the structure are zeroes, which is handled gracefully by the library.

lib: supl: Implement workaround for a SUPL client library bug

---

west.yml

manifest: sdk-nrfxlib: Pull nRF70 patch update rev#cce490be224

---

samples/matter/common/src/board/board.cpp
west.yml

* bump Matter manifest to pull BLEMgr fixes
* allow matter samples to retry to start advertising when the previous request failed

samples: matter: allow matter samples to retry BT advertising

---

applications/nrf5340_audio/prj.conf
applications/nrf5340_audio/src/bluetooth/bt_management/CMakeLists.txt
applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan.c

- Workaround to avoid k_forever in host

applications: nrf5340_audio: Print loccal address from internal struct

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

doc: qspi changelog entry

---

west.yml

Regular OpenThread update to \`3aa3cbc\`

manifest: openthread: update to \`3aa3cbc\`

---

drivers/wifi/nrf700x/Kconfig
drivers/wifi/nrf700x/inc/net_if.h
drivers/wifi/nrf700x/src/fmac_main.c
drivers/wifi/nrf700x/src/net_if.c
drivers/wifi/nrf700x/src/shim.c
drivers/wifi/nrf700x/src/shim.h
drivers/wifi/nrf700x/src/wifi_mgmt.c
west.yml

This set of changes adds promiscuous mode support to nrf Wi-Fi driver.

Promiscuous mode checkin

---

boards/arm/nrf7002dk_nrf5340/nrf5340_cpuapp_common.dts
boards/arm/nrf7002dk_nrf5340/nrf7002dk_nrf5340_cpuapp.dts
boards/arm/nrf7002dk_nrf5340/nrf7002dk_nrf5340_cpuapp_ns.dts
boards/arm/nrf7002dk_nrf7001_nrf5340/nrf5340_cpuapp_common.dts
boards/arm/nrf7002dk_nrf7001_nrf5340/nrf7002dk_nrf7001_nrf5340_cpuapp.dts
boards/arm/nrf7002dk_nrf7001_nrf5340/nrf7002dk_nrf7001_nrf5340_cpuapp_ns.dts
boards/arm/thingy91x_nrf9151/thingy91x_nrf9151.dts
boards/arm/thingy91x_nrf9151/thingy91x_nrf9151_common.dts
boards/arm/thingy91x_nrf9151/thingy91x_nrf9151_ns.dts
boards/shields/nrf7002eb/nrf7002eb.overlay
boards/shields/nrf7002ek/nrf7002ek.overlay
boards/shields/nrf7002ek_nrf7000/nrf7002ek_nrf7000.overlay
boards/shields/nrf7002ek_nrf7001/nrf7002ek_nrf7001.overlay
drivers/wifi/nrf700x/src/fmac_main.c
modules/hostap/Kconfig
modules/hostap/src/supp_main.c
west.yml

Add DT definitions for Wi-Fi device

---

subsys/bluetooth/mesh/shell/shell_ctrl_cli.c

* Light Ctrl shell can be used in an application with new sensor API.
* Small fix: updated shell_ctrl_cli.c to comply with split model structure.

Bluetooth: Mesh: Add new Sensor API support to Light Ctrl shell

---

applications/nrf5340_audio/src/bluetooth/bt_management/Kconfig
applications/nrf5340_audio/src/bluetooth/bt_management/controller_config/bt_mgmt_ctlr_cfg.c

OCT-2917
Now performing hci_sync call in separate work q
to avoid blocking system work q

Applications: nrf5340_audio: Ctlr poll in separate work q

---

doc/nrf/external_comp/bt_fast_pair.rst
doc/nrf/libraries/bluetooth_services/services/fast_pair.rst
doc/nrf/templates/Integration_template_README.rst

Update Fast Pair guide to match the integration template.
NCSDK-19382

doc: Update Fast Pair guide to match the integration template

---

samples/cellular/nrf_cloud_rest_device_message/README.rst

Fixed typos on-board to onboard.

doc: nRF Cloud REST Device Message sample fixes

---

west.yml

Brings in new features and bugfixes.
See CHANGELOGs for additional details.

manifest: Update nrfxlib with updated SDC and MPSL

---

applications/serial_lte_modem/doc/MQTT_AT_commands.rst
applications/serial_lte_modem/src/mqtt_c/slm_at_mqtt.c

Fix QoS2 and related MQTT client documentation. Note that MQTT client deviates from MQTT v3.1.1.

applications: serial_lte_modem: Fix MQTT QoS2

---

doc/nrf/device_guides/working_with_nrf/nrf70/features.rst

Added Monitor mode and Promiscuous mode to the
"Features of nRF70 Series" page.

doc: wifi: add new modes to Features page

---

subsys/bluetooth/controller/Kconfig
subsys/bluetooth/controller/hci_driver.c
subsys/bluetooth/controller/hci_internal.c

Add support for a VS HCI command to adjust the reserved time in a BIG.

bluetooth: controller: add support for HCIVSBigReservedTimeSet

---

west.yml

Pull in the latest improvements.

manifest: sdk-zephyr: apply modem cherry picks

---

applications/asset_tracker_v2/boards/thingy91x_nrf9151_ns.conf
applications/asset_tracker_v2/boards/thingy91x_nrf9151_ns.overlay
applications/asset_tracker_v2/include/thingy91x_nrf9151_ns/led_state_def.h
applications/asset_tracker_v2/sample.yaml
applications/asset_tracker_v2/src/ext_sensors/ext_sensors.c
boards/arm/thingy91x_nrf9151/thingy91x_nrf9151_common.dts
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
west.yml

This patch adds support for the Thingy:91 X
to the Asset Tracker V2.

applications: asset_tracker_v2: thingy91x support

---

subsys/bluetooth/controller/Kconfig
subsys/bluetooth/controller/hci_driver.c
subsys/bluetooth/controller/hci_internal.c

Adds command to:
* Set reserved CIG time
* Set ISO subinterval

Bluetooth: Controller: Add more HCI VS commands

---

doc/nrf/protocols/wifi/advanced_modes/raw_tx_operation.rst

This commit adds error reporting section to TX injection documentation

doc: wifi: Update TX injection documentation for error section

---

subsys/nrf_security/src/drivers/nrf_oberon/CMakeLists.txt

nrf_security: Turn off warnings that are triggering in Oberon

---

lib/location/method_gnss.c

Added printing of deadline missed flag of GNSS PVT notification.

lib: location: Add deadline missed flag to GNSS debug prints

---

applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c

Update the log for fitting the CI test system.
OCT-NONE

applications: nrf5340_audio: Update the log for CI test system

---

west.yml

This PR updates the sdk-connectedhomeip revision.

manifest: Update Matter SDK to the newest revision

---

west.yml

This pulls in fix for raw tx done buffer free issue

manifest: sdk-nrfxlib: Pull fix for tx done buffer free issue

---

samples/wifi/raw_tx_packet/src/main.c
samples/wifi/shell/src/wifi_raw_tx_pkt_shell.c

Improve log message for enhanced context.
SHEL-2448

sample: wifi: Update print statement

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Updated Wi-Fi entries in the Changelog

doc: wifi: Update changelog for Wi-Fi

---

samples/wifi/shell/sample.yaml

This adds promiscuous mode in CI build for the purpose of SML update in SHELL sample

samples: wifi: shell: Add promiscuous mode for 7001 SML update

---

applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_conn.c

- Check if a bonded device that is direct adv is still connected
- Can happen if it is still waiting to timeout the ACL
- Don't connect in that case

applications: nrf5340_audio: Fixes connection loop for reconnect

---

applications/serial_lte_modem/doc/AT_commands_intro.rst
applications/serial_lte_modem/doc/CMUX_AT_commands.rst
applications/serial_lte_modem/doc/PPP_AT_commands.rst
applications/serial_lte_modem/doc/slm_description.rst
applications/serial_lte_modem/src/slm_cmux.c
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

CMUX is added to the documentation while PPP is updated/finalized.

applications: serial_lte_modem: document CMUX and PPP

---

subsys/trusted_storage/src/aead/trusted_backend_aead.c
subsys/trusted_storage/src/internal_trusted_storage/backend_interface.c
subsys/trusted_storage/src/protected_storage/backend_interface.c

Align return codes and some behavior with the PSA ITS tests provided by the TF-M project.
Ref: NCSDK-26234

trusted_storage: Fix Return code errors

---

west.yml

manifest: TF-M fix cmake build warning

---

west.yml

Regular OpenThread update to \`b9dcdbc\`

manifest: openthread: update to \`b9dcdbc\`

---

samples/bluetooth/mesh/light_dimmer/prj.conf

Align light dimmer sample with CDP1 change.

Bluetooth: Mesh: Align light dimmer sample with CDP1 changes

---

west.yml

Update sdk-sidewalk revision in manifest

manifest: Update Sidewalk

---

doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst

Added migration description on how to do migration from the deprecated Sensor API to the new Sensor API.

doc: Bluetooth: Mesh: Added new Sensor API migration doc

---

applications/matter_bridge/README.rst

Added missing bits:
* List of supported bridged devices
* Clarification of the possible extensions of the app

doc: Fix Matter bridge application overview

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Minor edits for the mesh entries in the changelog

doc improvement: cleanup mesh changelog

---

samples/cellular/lwm2m_client/overlay-aggressive-psm.conf
samples/cellular/lwm2m_client/src/main.c

Disbale -> Disable on two location.

samples: lwm2m-client: Fix minor typo

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Remove 54L support from changelog.

doc: Remove 54L support from changelog

---

doc/_scripts/software_maturity/software_maturity_features.yaml

Trusted Storage maturity documentation.

doc: Trusted Storage maturity

---

applications/serial_lte_modem/doc/CMUX_AT_commands.rst

Add details about the CMUX configuration.

applications: serial_lte_modem: improve CMUX documentation

---

samples/wifi/throughput/sample.yaml
scripts/quarantine_integration.yaml

Add samples for memory footprints for these profile
1. IoT Deviceis - overlay-iot-devices.conf
2. Memory Optimized - overlay-memory-optimized.conf
3. High Performance - overlay-high-performance.conf
4. TX prioritized - overlay-tx-prio.conf
5. RX prioritized - overlay-rx-prio.conf

samples: wifi: throughput: Add profile for memory footprints.

---

doc/nrf/libraries/networking/azure_iot_hub.rst
doc/nrf/links.txt
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Update to content added for cert_tool.py script
in the Azure IoT hub documentation.
A following PR of https://github.com/nrfconnect/sdk-nrf/pull/14256/files

doc improvement: update to Azure IoT hub cert_tool.py script

---

samples/bluetooth/mesh/ble_peripheral_lbs_coex/README.rst

Add a note that LBS Service advs are stopped after someone connected to the advs.

Bluetooth: Mesh: Add note about LBS service adv

---

modules/trusted-firmware-m/tfm_boards/common/tfm_hal_platform.c
samples/crypto/persistent_key_usage/boards/nrf54l15pdk_nrf54l15_cpuapp.conf
samples/crypto/persistent_key_usage/sample.yaml
subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_primitives.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/aead.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/asymmetric.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/blkcipher.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/jpake.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/pake.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/spake2p.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/srp.c
subsys/nrf_security/src/drivers/cracen/psa_driver.Kconfig
subsys/nrf_security/src/psa_crypto_driver_wrappers.c
west.yml

see commit messages
test-sdk-nrf: test_cracen_ncs

Misc. fixes for Bugs found during NCS 2.6.0 release Testing

---

doc/nrf/releases_and_maturity/software_maturity.rst

Added trusted storage table to software maturity document.

doc: software_maturity: Added trusted storage table

---

west.yml

This pulls in fix for SHEL-2551

manifest: sdk-nrfxlib: Pull fix for SHEL-2551

---

applications/serial_lte_modem/doc/PPP_AT_commands.rst
applications/serial_lte_modem/doc/slm_description.rst
applications/serial_lte_modem/src/slm_ppp.c

Add a section about testing with pppd on a Linux host.

applications: serial_lte_modem: improve PPP documentation

---

doc/tags.yml

doc improvement: Update tag files for nRF9151

---

samples/wifi/monitor/README.rst

Update the decoding for rate flags and rate.
Fixes SHEL-2565.

samples: wifi: monitor: Update Wireshark Lua dissector

---

samples/bluetooth/mesh/sensor_server/src/model_handler.c

Fix amb_light_level_ref initialization.

Bluetooth: Mesh: Fix amb_light_level_ref initialization

---

doc/nrf/libraries/bin/lwm2m_carrier/API_documentation.rst
doc/nrf/libraries/bin/lwm2m_carrier/CHANGELOG.rst
doc/nrf/libraries/bin/lwm2m_carrier/app_integration.rst
doc/nrf/libraries/bin/lwm2m_carrier/requirements.rst
lib/bin/lwm2m_carrier/include/lwm2m_os.h

Fixes and clarifications to the documentation

doc: lwm2m_carrier: doc improvements

---

applications/asset_tracker_v2/doc/asset_tracker_v2_description.rst
applications/asset_tracker_v2/doc/cloud_module.rst
applications/asset_tracker_v2/doc/cloud_wrapper.rst
doc/nrf/external_comp/avsystem.rst
doc/nrf/includes/lwm2m_common_server_setup.txt
doc/nrf/libraries/bin/lwm2m_carrier/CHANGELOG.rst
doc/nrf/libraries/bin/lwm2m_carrier/app_integration.rst
doc/nrf/libraries/bin/lwm2m_carrier/msc.rst
doc/nrf/libraries/networking/lwm2m_client_utils.rst
doc/nrf/libraries/networking/lwm2m_location_assistance.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
doc/nrf/releases_and_maturity/releases/release-notes-1.7.0.rst
doc/nrf/releases_and_maturity/releases/release-notes-2.0.0.rst
doc/nrf/releases_and_maturity/releases/release-notes-2.1.0.rst
doc/nrf/releases_and_maturity/releases/release-notes-2.2.0.rst
doc/nrf/releases_and_maturity/releases/release-notes-2.5.0.rst
include/net/lwm2m_client_utils_location.h
lib/bin/lwm2m_carrier/include/lwm2m_carrier.h
lib/bin/lwm2m_carrier/include/lwm2m_settings.h
samples/cellular/lwm2m_carrier/sample_description.rst
samples/cellular/lwm2m_client/README.rst
samples/cellular/lwm2m_client/provisioning.rst
samples/cellular/lwm2m_client/sample_description.rst
samples/cellular/modem_shell/README.rst
samples/cellular/nidd/README.rst

The following terms are changed to follow
the OMA-TS specs:
* LwM2M Server
* LwM2M Client
* Non-IP

doc improvement: updates to LwM2M Server, client and non-IP terms

---

doc/nrf/links.txt
doc/nrf/shortcuts.txt

Updated version numbers for NCP Host package and ZBOSS release.

doc: zboss: update version numbers

---

doc/tags.yml

Check and update Zoomin tags for 2.6 release

doc: Check and update Zoomin tags for 2.6

---

doc/nrf/libraries/security/trusted_storage.rst
doc/nrf/protocols/matter/end_product/security.rst
doc/nrf/security/security.rst

Add documentation regarding:
* Cryptography
* Trusted Storage

doc: extend Matter security section

---

doc/_scripts/software_maturity/software_maturity_features.yaml

Update and add KConfig rules to yaml input file for Sidewalk.
KRKNWK-18447

doc: software_maturity: update Amazon Sidewalk

---

applications/asset_tracker_v2/doc/asset_tracker_v2_description.rst
doc/nrf/libraries/networking/azure_iot_hub.rst

This includes some corrections and explanations in the Azure setup.

doc improvement: Corrections for Azure IoT Hub setup

---

west.yml

[fix_tfm_rebuild] manifest: tfm

---

west.yml

Update sdk-nrfxlib with nrf_modem doc fixes.

manifest: update sdk-nrfxlib with nrf_modem doc fixes

---

doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst

Applications: nrf5340_audio: Updated migration doc

---

west.yml

Update revision to rebased sdk-zephyr, sdk-mcuboot, and sdk-trusted-firmware-m.

manifest: point to OSS rebase PRs

---

samples/caf/boards/nrf54h20pdk_nrf54h20_cpuapp.conf
samples/caf/boards/nrf54h20pdk_nrf54h20_cpuapp.overlay
samples/caf/configuration/nrf54h20pdk_nrf54h20_cpuapp/buttons_def.h
samples/caf/configuration/nrf54h20pdk_nrf54h20_cpuapp/led_state_def.h

Add configuration for nRF54H20PDK.

samples: caf: Add nrf54h20pdk configuration

---

applications/nrf5340_audio/src/bluetooth/bt_management/advertising/Kconfig
applications/nrf5340_audio/src/bluetooth/bt_management/advertising/bt_mgmt_adv.c
applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.h
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
applications/nrf5340_audio/unicast_server/main.c

- Add manufacturer ID UUID to the advertisement packet
- OCT-2730

applications: nrf5340_audio: Add manufacturer ID to adv

---

samples/bluetooth/mesh/ble_peripheral_lbs_coex/src/main.c
samples/bluetooth/mesh/chat/src/main.c
samples/bluetooth/mesh/dfu/distributor/src/main.c
samples/bluetooth/mesh/dfu/target/src/main.c
samples/bluetooth/mesh/light/boards/nrf54l15pdk_nrf54l15_cpuapp.conf
samples/bluetooth/mesh/light/sample.yaml
samples/bluetooth/mesh/light/src/main.c
samples/bluetooth/mesh/light_ctrl/src/main.c
samples/bluetooth/mesh/light_dimmer/src/main.c
samples/bluetooth/mesh/light_switch/src/main.c
samples/bluetooth/mesh/sensor_client/src/main.c
samples/bluetooth/mesh/sensor_server/src/main.c
samples/bluetooth/mesh/silvair_enocean/src/main.c

Add support of nrf54l15pdk_nrf54l15_cpuapp in mesh light
sample.

samples: Bluetooth: Mesh: add nrf54l support for mesh light sample

---

.github/workflows/docbuild.yml

for PRs: doc_build_pr_XYZ.zip
for main: doc_build_latest.zip
for releases: doc_build_x.y.z.zip

ci: docbuild: change archive naming scheme

---

subsys/net/openthread/Kconfig.defconfig
west.yml

Regular OpenThread update to \`39fcc5e\`

manifest: openthread: update to \`39fcc5e\`

---

samples/bluetooth/central_uart/app.overlay
samples/bluetooth/central_uart/boards/nrf54l15pdk_nrf54l15_cpuapp.conf
samples/bluetooth/central_uart/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay
samples/bluetooth/central_uart/sample.yaml
samples/bluetooth/central_uart/src/main.c

Add support to bt central uart sample for 54l15
Signed-off-by: Pierce Lowe <pierce.lowe@nordicsemi.no>

samples: bluetooth: central_uart: add support for 54l15

---

applications/ipc_radio/README.rst
doc/nrf/links.txt

Update the ipc_radio documentation with Sysbuild notes and comments from PR-12588.
Jira: NCSIDB-1210

applications: doc: Update the ipc_radio documentation

---

doc/nrf/config_and_build/dfu/dfu_image_versions.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

[NCSDK-26586](https://nordicsemi.atlassian.net/browse/NCSDK-25919)
As reported by SH in support:
Update image version instruction for MCUboot section
[NCSDK-26586]: https://nordicsemi.atlassian.net/browse/NCSDK-26586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc: dfu update image ver instruction

---

doc/nrf/releases_and_maturity/known_issues.rst

DRGN-20444 affects NCS 2.4.3 as well and this is a missing information

doc: missing affected version for known issues

---

doc/nrf/releases_and_maturity/known_issues.rst

Update date-time known issue with nRF52840 platform

doc: Update date-time known issue with nRF52840 platform

---

applications/asset_tracker_v2/src/cloud/aws_iot_integration.c

This patch fixes the string generation of the
shadow topic in the AWS module of the ATV2.

applications: asset_tracker_v2: fix aws shadow topic

---

west.yml

The new SoftDevice Controller contains some bugfixes.

manifest: Update nrfxlib revision with new SDC revision

---

samples/pmic/native/npm1300_fuel_gauge/README.rst
samples/pmic/native/npm1300_one_button/README.rst

Added links from the PMIC samples to the product and evaluation kit hardware landing pages.

samples: pmic: Added links to hardware documentation

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/net/nrf_cloud_location.h
subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_location
subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_fsm.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_location.c

Add support for a list of anchor names to be received by the application when a location request response is parsed. 
IRIS-8036

net: lib: nrf_cloud: add support for anchor name list

---

west.yml

Regular OpenThread update to \`51ab865\`

manifest: openthread: update to \`51ab865\`

---

west.yml

This patch brings small fixes in the nrfconnect
Matter platform Wi-Fi code.

manifest: pull Matter Wi-Fi minor refinements

---

doc/nrf/links.txt

Updated links to nRF Tools apps.
Cleaned up according to guidelines at the top of the page.

doc: links: update nRF Tools links + cleanup

---

west.yml

Adds sample.yaml configuration

manifest: Update sdk-zephyr with 54l15 smp_svr sample

---

samples/wifi/radio_test/radio_test_subcommands.rst
samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c

[SHEL-2606] Corrected command description.
[SHEL-2606]: https://nordicsemi.atlassian.net/browse/SHEL-2606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

samples: wifi: radio_test: Improve command description

---

applications/nrf5340_audio/index.rst

Fixed inconsistencies in the landing page table.
OCT-2954.

doc: nrf5340audio: fixes to overview table

---

samples/nrf_profiler/sample.yaml
tests/subsys/bluetooth/fast_pair/crypto/testcase.yaml
tests/subsys/bluetooth/fast_pair/storage/account_key_storage/testcase.yaml
tests/subsys/bluetooth/fast_pair/storage/factory_reset/testcase.yaml
tests/subsys/nrf_profiler/testcase.yaml

Changes nrf9160dk_nrf9160_ns to nrf5340dk_nrf5340_cpuapp_ns in SPG SI BlueBagel .yaml files.
Jira: NCSDK-26615

Change nrf9160dk_nrf9160_ns to nrf5340dk_nrf5340_cpuapp_ns in .yaml files

---

west.yml

Regular OpenThread update to \`58b230f\`

manifest: openthread: update to \`58b230f\`

---

applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c
applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c

Check and config codec setting in both subgroup/BIS level. OCT-2953

applications: nrf5340_audio: Update BASE decode feature

---

README.rst

Edited the link to the latest documentation set.

readme: update documentation links

---

scripts/bluetooth/mesh/mesh_dfu_metadata.py

This commit fixes an issue where metadata extraction script would fail if a firmware is compiled with `CONFIG_LTO` and
`CONFIG_ISR_TABLES_LOCAL_DECLARATION` enabled.
When LTO is enabled, the DW_AT_location attribute is stored under separate DW_TAG_variable die which has reference to the original die through DW_AT_abstract_origin attribute.
With this change the script will also try to find the composition data variable through a die which has DW_AT_abstract_origin attribute with DW_FORM_ref_addr.

scripts: bluetooth: mesh: metadata: Fix extraction with LTO enabled

---

scripts/memory-threshold-list.yaml
scripts/quarantine_integration.yaml

Update Matter samples ROM/RAM requirements.

scripts: memory-threshold-list: update values for matter samples

---

doc/nrf/links.txt
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
doc/nrf/test_and_optimize/debugging.rst

Reworked the debugging tools section into a table with more tools listed. NCSDK-22325.
----

doc: test_and_optimize: debugging tools list edits

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/net/wifi_credentials.h
subsys/net/lib/wifi_credentials/wifi_credentials.c
subsys/net/lib/wifi_credentials/wifi_credentials_shell.c
subsys/net/lib/wifi_mgmt_ext/wifi_mgmt_ext.c
tests/subsys/net/lib/wifi_credentials/src/main.c

Add function to clear all stored credentials and to check if there are any valid entries in storage.
Add storing of channel.
Make wifi exts auto connect feature pass in preferred channel to the wifi stack.

net: lib: wifi_credentials: Add new functions and params

---

west.yml

Two commits from zephyr upstream.

manifest: Update Zephyr's net stack.

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/nfc/record_launch_app/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
samples/nfc/record_launch_app/sample.yaml
samples/nfc/record_text/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
samples/nfc/record_text/sample.yaml
samples/nfc/shell/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
samples/nfc/shell/sample.yaml
samples/nfc/system_off/sample.yaml
samples/nfc/tnep_tag/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
samples/nfc/tnep_tag/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay
samples/nfc/tnep_tag/sample.yaml
samples/nfc/writable_ndef_msg/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
samples/nfc/writable_ndef_msg/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay
samples/nfc/writable_ndef_msg/sample.yaml
subsys/nfc/lib/Kconfig
subsys/nfc/lib/platform_internal_thread.c
west.yml

Add nfc_platform and NFC samples support for nRF54.

Add support for nRF54 in NFC.

---

CODEOWNERS

- Change from using individuals to group
- OCT-NONE

codeowners: Update CODEOWNERS to use audio group

---

subsys/bluetooth/services/fast_pair/fp_crypto/Kconfig.fp_crypto
tests/subsys/bluetooth/fast_pair/crypto/testcase.yaml
tests/subsys/bluetooth/fast_pair/storage/account_key_storage/testcase.yaml
tests/subsys/bluetooth/fast_pair/storage/factory_reset/testcase.yaml

Added nRF54L15 PDK target to Fast Pair tests.
Jira: NCSDK-26582

tests: subsys: bluetooth: fast_pair: Add nRF54L15 PDK target 

---

applications/nrf5340_audio/child_image/hci_ipc.conf
applications/nrf5340_audio/src/bluetooth/bt_management/advertising/Kconfig
applications/nrf5340_audio/src/bluetooth/bt_management/advertising/bt_mgmt_adv.c
applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_conn.c
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c
applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c

applications: nrf5340_audio: Improvements from UPF London

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
west.yml

Pulled fix that merges two factory data related scripts into one.

manifest: Updated Matter revision to pull factory data fix

---

west.yml

samples: Add support for Sidewalk over BLE on nrf54l15
fix: flash_sync_mpsl: timeout
fix: remove sleep from dfu timer callback to avoid asserts in isr
samples: static partition no dfu for platforms

manifest: Add support for nrf54l15 in Sidewalk

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/bluetooth/mesh/dfu/target/README.rst

Add a note how to easily create a new composition data and see how device becomes unprovisioned after DFU.

samples: bluetooth: mesh: target: Add a note how to create new cdp0

---

samples/crypto/pbkdf2/boards/nrf9161dk_nrf9161_ns.conf
samples/crypto/pbkdf2/sample.yaml
west.yml

TF-M update to add PBKDF2 support.
NS targets added to PBKDF2 sample.

manifest: TF-M update

---

scripts/tools-versions-darwin.yml
scripts/tools-versions-linux.yml
scripts/tools-versions-win10.yml

tools: Update sdk-ng to v0.16.5-1

---

scripts/quarantine_windows_mac.yaml

Remove resolved issues from quarantine

ci: Update quarantine used in on-windows plan

---

samples/cellular/lwm2m_client/fota.rst

Fixed a typo in LwM2M Client sample FOTA page.

doc: Minor typo fix to LwM2M Client sample

---

applications/matter_bridge/doc/matter_bridge_description.rst
doc/nrf/protocols/matter/getting_started/adding_clusters.rst
samples/matter/light_bulb/README.rst
samples/matter/lock/README.rst
samples/matter/template/README.rst
samples/matter/thermostat/README.rst
samples/matter/window_covering/README.rst

We missed the proper instructions on how to factory reset the device.

doc: Fix factory reset description in Matter samples

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/peripheral/radio_test/boards/nrf54h20dk_nrf54h20_cpurad.conf
samples/peripheral/radio_test/boards/nrf54h20dk_nrf54h20_cpurad.overlay
samples/peripheral/radio_test/sample.yaml
west.yml

Add support for nRF54h20 target in Radio Test sample

samples: Radio Test: Support for nRF54h20

---

west.yml

Regular OpenThread update to \`30aa3e8\`

manifest: openthread: update to \`30aa3e8\`

---

west.yml

For both UARTs connected to debbuger chip.

manifest: update zephyr - HWFC for nrf54h20

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/bluetooth/mesh/light/README.rst
samples/bluetooth/mesh/light/sample.yaml

Commit adds support p2p dfu for Moonlight in CI and docs.

samples: Bluetooth: Mesh: add p2p dfu for Moonlight

---

drivers/wifi/nrf700x/src/net_if.c

MAC address setting is a local operation i.e., doesn't need any FMAC interaction and is essential for bringing the up driver in case OTP has no programmed MAC address. This doesn't need any FMAC context checks.
Fixes SHEL-2675.

drivers: wifi: Fix MAC address set regression

---

applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
applications/nrf5340_audio/unicast_server/Kconfig.defaults

- Set ASE_SRC_COUNT to 0 if not BIDIR
- OCT-2972

applications: nrf5340_audio: Only expose source PAC if BIDIR

---

applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c

- Check that only one bit is set in chan_location
- Don't sync if more than one bit is set
- OCT-2978

applications: nrf5340_audio: Only sync to BISes with single channel

---

west.yml

This commit increases number of available packet buffers in the system.

manifest: matter: pull fix for insufficient resources

---

doc/nrf/create_application.rst
doc/nrf/installation.rst
doc/nrf/installation/install_ncs.rst
doc/nrf/installation/recommended_versions.rst

Applied edits from the recent getting started testing. Requested by @ihansse and tracked in NCSDK-27019.

doc: install: edits from review

---

doc/nrf/config_and_build/bootloaders/index.rst
doc/nrf/config_and_build/dfu/index.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

[NCSIDB-1161](https://nordicsemi.atlassian.net/browse/NCSIDB-1161)
Update table to include info on SMP for MCUboot
[NCSIDB-1161]: https://nordicsemi.atlassian.net/browse/NCSIDB-1161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc: bootloader update table

---

west.yml

samples: replace log messages in on dev cert to shell print
samples: demo app disable notify in dfu mode
build: search config file as a list
build: add experimental sybol for nrf54l15
build: fix cmake error on non-pristing build

manifest: Update Sidewalk project

---

west.yml

Pull in a fix for TFMV-7 security advasory (CVE-2023-51712)
Ref: NCSDK-26942

manifest: tfm: Fix TFMV-7

---

samples/bluetooth/iso_time_sync/README.rst

Aligned the sample doc with the template.

doc: BT ISO time synch sample: align with the sample template

---

doc/nrf/protocols/wifi/station_mode/powersave.rst
west.yml

manifest: sdk-zephy: Pull cleanup of unused ops

---

doc/nrf/device_guides/nrf54l.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

fixed changelog linking.
added a workaround note.

doc: link fix for nrf54l15

---

doc/nrf/protocols/thread/configuring.rst
doc/nrf/protocols/thread/prebuilt_libs.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/openthread/coprocessor/README.rst
samples/openthread/coprocessor/prj.conf
west.yml

Commit adds new feature set option to nrfxlib and modifies RCP sample accordingly.

manifest: openthread: Add new featureset option.

---

applications/nrf5340_audio/broadcast_sink/main.c
applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_broadcast.c

The name, id and address will be printed.
OCT-2971

Applications: nrf5340_audio: Added info to PA synced print

---

doc/nrf/links.txt
doc/nrf/protocols/wifi/wifi_certification.rst

Updated Certification page with information about
recertification process and related links.
SHEL-2677

doc: wifi: Update Certification page

---

samples/wifi/radio_test/sample_description.rst

samples: wifi: radio_test: Fix error

---

modules/hostap/CMakeLists.txt
modules/hostap/Kconfig
west.yml

Add new nw sel

---

doc/_utils/redirects.py
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
doc/nrf/test_and_optimize.rst
doc/nrf/test_and_optimize/test_framework/index.rst
doc/nrf/test_and_optimize/test_framework/testing_unity_cmock.rst

Added information about Ztest in a new section about frameworks. NCSDK-22325.

doc: test_and_optimize: add info about ztest

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/net/http_server/boards/native_sim.conf
samples/net/http_server/src/main.c

Adding support for native_sim board.

samples: net: http_server: support for native_sim

---

west.yml

Pull in pytest support for nrfutil.

manifest: update sdk-zephyr.

---

doc/nrf/libraries/bluetooth_services/rpc.rst
doc/nrf/protocols/bt/index.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/bluetooth/bt_rpc.h
subsys/bluetooth/rpc/CMakeLists.txt

Rework the ble_rpc doc to align with template
and be more informative.
Jira: NCSDK-25478

doc: Rework ble_rpc documentation

---

west.yml

Update sdk-zephyr revision to include TCP fixes.
Fixes SHEL-2687

[v2.6-branch] manifest: Update sdk-zephyr revision

---

west.yml

Update sdk-zephyr revision to include TCP fixes.
Fixes SHEL-2687

[v2.5-branch] manifest: Update sdk-zephyr revision

---

subsys/bluetooth/controller/crypto.c

It has been replaced by mpsl_ecb.h

bluetooth: controller: remove usage of sdc_soc.h in crypto.c

---

west.yml

Updates Oberon PSA core module with client view support fixes.

manifest: Oberon PSA core update

---

samples/bluetooth/connection_event_trigger/README.rst
samples/bluetooth/connection_event_trigger/src/main.c

Improves user-friendliness by printing out the interval in ms

bluetooth: samples: improve log for connection event trigger sample

---

subsys/bluetooth/controller/hci_driver.c

When HCI vendor specific extensions are disabled, we now reuse the implementation of sdc_hci_cmd_vs_zephyr_read_static_addresses().
This implementation is also future proof for future platforms, and works for 54H and 54L. Previously this code didn't build for these platforms.

Bluetooth: Controller: Reuse implementation in bt_read_static_addr

---

west.yml

Updating nRF70 release/v2.6 firmware patch.

manifest: sdk-nrfxlib: Pull nRF70 v2.6 patch update rev#8fe7ff0425f

---

tests/subsys/suit/unit/app_specific/cmake/test_template.cmake
tests/subsys/suit/unit/app_specific/suit_plat_fetch_app/testcase.yaml
tests/subsys/suit/unit/app_specific/suit_plat_retrieve_manifest_app/testcase.yaml
tests/subsys/suit/unit/cmake/test_template.cmake
tests/subsys/suit/unit/mocks/CMakeLists.txt
tests/subsys/suit/unit/plat_devconfig/testcase.yaml
tests/subsys/suit/unit/suit_metadata/testcase.yaml
tests/subsys/suit/unit/suit_plat_authorize_component_id/testcase.yaml
tests/subsys/suit/unit/suit_plat_authorize_process_dependency/testcase.yaml
tests/subsys/suit/unit/suit_plat_check_image_match/testcase.yaml
tests/subsys/suit/unit/suit_plat_class_check/testcase.yaml
tests/subsys/suit/unit/suit_plat_component_compatibility/testcase.yaml
tests/subsys/suit/unit/suit_plat_components/testcase.yaml
tests/subsys/suit/unit/suit_plat_digest_cache/testcase.yaml
tests/subsys/suit/unit/suit_plat_memptr_size_update/testcase.yaml
tests/subsys/suit/unit/suit_plat_override_image_size/testcase.yaml
tests/subsys/suit/unit/suit_plat_retrieve_manifest/testcase.yaml
west.yml

NCSDK-26629: Enable SUIT unit tests

---

samples/matter/light_switch/sample.yaml
samples/matter/thermostat/sample.yaml
scripts/quarantine_integration.yaml

- Added nrf54l15pdk v0.3.0 build target to Light Switch and Thermostat Matter samples.

samples: matter: Added nRF54L15 0.3.0 to rest Matter samples.

---

applications/matter_bridge/src/app_task.cpp
applications/matter_bridge/src/ble_providers/ble_bridged_device_factory.cpp
applications/matter_bridge/src/simulated_providers/simulated_bridged_device_factory.cpp
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/matter/common/src/bridge/bridge_manager.cpp
samples/matter/common/src/bridge/bridge_storage_manager.cpp
samples/matter/common/src/bridge/bridge_storage_manager.h

Refactored Matter bridge storage implementation to use different data structure with a fewer keys what allowed to use ~2.5 times less memory. Additonally, provided a mechanism that detects currently used structure version and migrates data from the older structure to ensure backward-compatibility.

applications: Refactored Matter bridge storage implementation

---

subsys/net/lib/lwm2m_client_utils/lwm2m/ground_fix_obj.c

When we received ground fix location, update the timestamp of location object as well.

net: lwm2m_client_utils: Update Location timestamp on Ground Fix

---

samples/multicore/hello_world/sample.yaml

For testing power consumption.

samples: multicore: hello_world: allow power measurements

---

doc/nrf/releases_and_maturity/software_maturity.rst

doc: SML table fix for 54L maturity

---

samples/multicore/hello_world/Kconfig.sysbuild
samples/multicore/hello_world/power_management_app.overlay
samples/multicore/hello_world/remote/power_management_ppr.overlay
samples/multicore/hello_world/remote/power_management_rad.overlay
samples/multicore/hello_world/sample.yaml
samples/multicore/hello_world/src/main.c
samples/multicore/hello_world/sysbuild.cmake
samples/multicore/hello_world/sysbuild/nrf54h20dk_nrf54h20_cpurad_ppr.conf

Add configuration for app + rad + ppr cores for hello world on nrf54h20
Jira: none

samples: Power_Management: Add hello world con for 3 cores

---

doc/nrf/conf.py
doc/nrf/dev_model_and_contributions/adding_code.rst
doc/nrf/releases_and_maturity.rst
doc/nrf/releases_and_maturity/known_issues.rst
doc/nrf/releases_and_maturity/migration/migration_guide_1.x_to_2.x.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.7.rst
doc/nrf/releases_and_maturity/migration_guides.rst
doc/nrf/releases_and_maturity/release_notes.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
doc/nrf/shortcuts.txt

Standard post-release changes in docs.

doc: post-release doc update after 2.6.99-cs1

---

west.yml

Add plausibility checks for ECC keys
Ref: NCSDK-24820
test_crypto: PR-618

manifest: oberon-core: Add ECC key checks

---

scripts/docker/Dockerfile
scripts/docker/entrypoint.sh

Add qemu and libffi to docker image

tools: Add qemu and libffi to docker image

---

samples/crypto/persistent_key_usage/sample.yaml

Added nrf54l15pdk_nrf54l15_cpuapp_ns to persistent_key_usage sample.yaml
test_crypto: PR-627

samples: crypto: Added nrf54l15-ns for persistent_key_usage

---

west.yml

manifest: sdk-nrfxlib: Pull nRF70 patch update rev#11df71029cc

---

applications/nrf5340_audio/src/bluetooth/bt_management/Kconfig
applications/nrf5340_audio/src/bluetooth/bt_management/controller_config/bt_mgmt_ctlr_cfg.c
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c

OCT-3004
Fix a config bug on unicast server
Changed so controller/NET Watchdog will not halt entire system.

Applications: nrf5340_audio: Size mismatch and WDT fix

---

drivers/wifi/nrf700x/inc/fmac_main.h
drivers/wifi/nrf700x/inc/wpa_supp_if.h
drivers/wifi/nrf700x/src/fmac_main.c
drivers/wifi/nrf700x/src/wpa_supp_if.c

This helps WPA supplicant kick off inactive STAs.

wifi: sap: Implement inactivity timer retrieval

---

doc/nrf/config_and_build/config_and_build_system.rst
doc/nrf/config_and_build/configuring_app/cmake/index.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.7.rst
doc/nrf/shortcuts.txt
scripts/partition_manager/partition_manager.rst

Updated documentation about file suffixes for added support for Partition Manager's static partition files.

doc: file_suffix: update for PM support

---

doc/nrf/protocols/wifi/wifi_certification.rst

Updated Certification page with the information
about the derivative recertification process.
SHEL-2729

doc: wifi: add derivative recertification process

---

doc/nrf/config_and_build/bootloaders/bootloader_config.rst
doc/nrf/links.txt
scripts/partition_manager/partition_manager.rst

[NCSDK-22733](https://nordicsemi.atlassian.net/browse/NCSDK-22733)
Add info about config options
in the Partition Manager doc
[NCSDK-22733]: https://nordicsemi.atlassian.net/browse/NCSDK-22733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc: improve PM config info

---

subsys/bluetooth/mesh/light_temp_srv.c

Commit solves situation when the level client sends Set command with exact values but Status has different levels. It happens when Level model extends the temperature model. Double conversion happens. Conversions from level
to temperature and back have division result rounding that causes precision losing.

Bluetooth: Mesh: avoid double conversion precision losing

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps_utils.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c

Improve error handling when valid predictions exist but none are actually for the current GPS time.
Also improve error handling for all error returns from nrf_cloud_pgps_find_prediction().
Jira: IRIS-8818

net: lib: nrf_cloud_pgps: Fix NULL pointer injection

---

doc/nrf/releases_and_maturity/known_issues.rst

Update Matter known issue with the issue found during testing.

doc: known_issue: Matter add known issue to KRKNWK-18673 bug

---

doc/nrf/releases_and_maturity/known_issues.rst

Update a Matter known issues with the two issues regarding a reaction to the last fabric removal.

doc: known_issue: Matter add known issue to KRKNWK-18916 bug

---

west.yml

Include changes from:
https://github.com/nrfconnect/sdk-zephyr/pull/1640

manifest: Update sdk-zephyr with watchdog tests for error cases

---

CODEOWNERS

codeowners: Remove stale entries

---

west.yml

Regular OpenThread update to \`226f239\`

manifest: openthread: update to \`226f239\`

---

applications/nrf_desktop/board_configuration.rst
applications/nrf_desktop/description.rst

Updated the following build target on the nRF desktop application docs:
nrf54l15pdk_nrf54l15_cpuapp@0.3.0

doc: update of nrf54l15pdk v0.3.0 on the nRF desktop application

---

applications/matter_bridge/Kconfig
doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/matter/common/src/Kconfig
samples/matter/common/src/persistent_storage/backends/persistent_storage_secure.h
samples/matter/lock/CMakeLists.txt
samples/matter/lock/Kconfig
samples/matter/lock/README.rst
samples/matter/lock/src/bolt_lock_manager.cpp
samples/matter/lock/src/bolt_lock_manager.h
samples/matter/lock/src/credentials/credentials_data_types.cpp
samples/matter/lock/src/credentials/credentials_data_types.h
samples/matter/lock/src/credentials/credentials_manager.cpp
samples/matter/lock/src/credentials/credentials_manager.h
samples/matter/lock/src/credentials/credentials_storage.cpp
samples/matter/lock/src/credentials/credentials_storage.h
samples/matter/lock/src/zcl_callbacks.cpp

* implemented generic door lock credentials manager with  secure persistent storage support
* refine door lock sample to use the module and manage PIN credentials
TODO:

samples: matter: added lock credentials manager module

---

doc/nrf/libraries/networking/azure_iot_hub.rst

A few corrections and improvements in the steps to set up Azure IoT Hub Device Provisioning Service. This allows group enrollment using subordinate CA certificate for DPS attestation.

doc improvement: Improve Azure IoT Hub DPS setup

---

doc/nrf/security/security.rst

Be more precise about prioritization.

doc: nrf_security: Be more precise about prioritization

---

subsys/suit/Kconfig
subsys/suit/stream/Kconfig

SUIT extmem Kconfig adjustments

---

scripts/ci/tags.yaml
scripts/ci/twister_ignore.txt

Files copied from sdk-zephyr.
Will be adjusted when test plan mechanisms will be enabled.

scripts: ci: Add test plan configuration files

---

.github/workflows/compliance.yml
.github/workflows/create-upmerge-PRs.yml
.github/workflows/docbuild.yml
.github/workflows/license-reusable.yml
.github/workflows/oss-history.yml
.github/workflows/pip-requirements.yml
.github/workflows/src-mirror.yml

Actions located under nordicbuilder account will be transferred to nrfconnect organization.

ci: use actions from nrfconnect org

---

west.yml

Regular OpenThread update to \`0a4d6d3\`

manifest: openthread: update to \`0a4d6d3\`

---

west.yml

Pull in the memory map update.

[v2.6.99-cs2] manifest: Update zephyr

---

applications/nrf_desktop/src/modules/usb_state.c

Change makes set_report and get_report functions more generic to allow code reuse.
Jira: NCSDK-27014

applications: nrf_desktop: Make set/get report more generic in USB state

---

doc/nrf/links.txt
doc/nrf/protocols/wifi/sap_mode/sap.rst

Remove mention of static IP address configuration for station devices in SAP mode.
Fixes SHEL-2758

doc: nrf70: Update IP configuration in SAP mode

---

scripts/memory-threshold-list.yaml

This change makes variable of the memory increase more readible.

scripts: memory-threshold-list: Rename the variable of memory increase

---

scripts/quarantine_integration.yaml

Added at least one Find My build test in the release configuration for the nRF5340 DK Non-Secure target to the on-commit testing scope.

scripts: find_my: add one build for the nrf5340 DK NS to integration

---

samples/net/aws_iot/sample.yaml
samples/net/azure_iot_hub/sample.yaml
samples/net/coap_client/sample.yaml
samples/net/download/sample.yaml
samples/net/http_server/sample.yaml
samples/net/http_server/src/main.c
samples/net/https_client/sample.yaml

Native_sim was missing from several sample.yaml files.

samples: net: Add native_sim to sample.yaml

---

cmake/version.cmake

The gitdir (usually .git) does not exist in the nrf folder when using git worktrees.
This commit looks up the absolute path to the gitdir before adding the gitdir dependencies.
More info about [git worktrees in the official docs](https://git-scm.com/docs/git-worktree).

kernel: Fix git commit banner when using worktrees

---

doc/nrf/links.txt
doc/nrf/releases_and_maturity/known_issues.rst

Add known issue about LwM2M Carrier Library failing to bootstrap.

doc: add known issue NCSDK-26682

---

doc/_utils/utils.py

Update the banner informing about when the current developer website will be taken offline.

doc: update banner in documentation

---

subsys/dfu/dfu_target/CMakeLists.txt
subsys/dfu/dfu_target/Kconfig
subsys/dfu/dfu_target/src/dfu_target.c
subsys/dfu/dfu_target/src/dfu_target_suit.c

Add a DFU target variant that is capable of handling SUIT envelopes.

dfu_target: suit: Add handlers for SUIT

---

CODEOWNERS
scripts/memory-threshold-list.yaml

Update codeowners to reflect the current assignment of responsibilities.

CODEOWNERS: update codeowners

---

applications/machine_learning/configuration/nrf52840dk_nrf52840/prj.conf
applications/machine_learning/configuration/nrf52840dk_nrf52840/prj_nus.conf
applications/machine_learning/configuration/nrf52840dk_nrf52840/prj_release.conf
applications/machine_learning/configuration/nrf5340dk_nrf5340_cpuapp/prj.conf
applications/machine_learning/configuration/thingy53_nrf5340_cpuapp/prj.conf
applications/machine_learning/configuration/thingy53_nrf5340_cpuapp/prj_release.conf
applications/machine_learning/configuration/thingy53_nrf5340_cpuapp/prj_rtt.conf
applications/machine_learning/configuration/thingy53_nrf5340_cpuapp_ns/prj.conf
applications/machine_learning/configuration/thingy53_nrf5340_cpuapp_ns/prj_release.conf
applications/machine_learning/configuration/thingy53_nrf5340_cpuapp_ns/prj_rtt.conf
samples/edge_impulse/wrapper/prj.conf

Changing backup download source for Edge Impulse model.

lib: edge_impulse: Change backup download source

---

west.yml

Regular OpenThread update to \`a57d927\`

manifest: openthread: update to \`a57d927\`

---

doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst
doc/nrf/links.txt
doc/nrf/releases_and_maturity/release_notes.rst
doc/nrf/releases_and_maturity/releases/release-notes-2.6.99-cs2.rst

Documentation edits post 2.6.99_CS2 release

doc: post 2.6.99_CS2 release edits

---

subsys/net/lib/nrf_cloud/src/nrf_cloud_fota.c

Update the last job string when job validation is done. 
IRIS-8846

net: lib: nrf_cloud: properly update last job string

---

cmake/sysbuild/b0_mcuboot_signing.cmake

Fixes an issue in the naming of files in the zip and including manifest data for a file that might not be present

sysbuild: Fix b0 signing code

---

cmake/sysbuild/suit.cmake
subsys/suit/provisioning/CMakeLists.txt
subsys/suit/provisioning/soc/Kconfig.nrf54h20
subsys/suit/provisioning/soc/Kconfig.template.manifest_config
subsys/suit/storage/src/suit_storage_nrf54h20.c
tests/subsys/suit/orchestrator/orchestrator_sdfw_nrf54h20/boards/native_posix.overlay
tests/subsys/suit/storage_nrf54h20/boards/native_posix.overlay
west.yml

test-sdk-nrf: sdk-nrf-pr-15322

Fix suit storage address

---

subsys/suit/stream/stream_sources/src/suit_ipc_streamer_provider.c
subsys/suit/stream/stream_sources/src/suit_ipc_streamer_requestor.c

Ensure that the chunk data is properly flushed by the provider before sending, and the memory area is flushed by the provider before processing the chunk.

suit: add cache operations to IPC requestor/provider

---

lib/sms/sms.c
tests/lib/sms/src/sms_test.c

AT+CNMA=1 has been sent with nrf_modem_at_printf synchronously. Changing it to use nrf_modem_at_cmd_async to avoid blocking system workqueue.
AT+CNMA=1 can take tens of seconds, if network is unresponsive, before modem's timers expire.
Jira: NCSDK-27510

lib: sms: Send SMS ACK asynchronously

---

CODEOWNERS

Added ncs-matter to Matter-related directories.

CODEOWNERS: Add Matter team to Matter-related directories

---

applications/matter_bridge/sample.yaml
applications/matter_weather_station/sample.yaml
samples/matter/light_bulb/sample.yaml
samples/matter/light_switch/sample.yaml
samples/matter/lock/sample.yaml
samples/matter/template/sample.yaml
samples/matter/thermostat/sample.yaml
samples/matter/window_covering/sample.yaml
scripts/quarantine_integration.yaml

- Added .lto samples configs
- Adjusted other samples so thereis .debug and .release in every yaml

samples: matter: lto samples added

---

samples/bluetooth/mesh/light_ctrl/README.rst

Fixed inconsistent or wrong naming, and clarified some parts in the Testing section.

Samples: Bluetooth: Mesh: Fix Light fixture documentation

---

subsys/emds/Kconfig
tests/subsys/emds/emds_api/src/main.c

Commit adds preliminary writing timings for flash driver based on rram.

emds: add preliminary timings for rram

---

doc/nrf/device_guides/working_with_nrf/nrf52/features.rst
doc/nrf/device_guides/working_with_nrf/nrf91/nrf91_features.rst
doc/nrf/external_comp/memfault.rst
doc/nrf/index.rst
doc/nrf/links.txt
doc/nrf/test_and_optimize/debugging.rst

suggest memfault in NCS docs
Provide more context around remote observability

doc: suggest memfault in NCS docs

---

samples/cellular/ciphersuites/README.rst
samples/cellular/ciphersuites/src/main.c

Add a reference to IANA register and general cleanup.

samples: cellular: ciphersuites: add reference to IANA register

---

doc/nrf/samples.rst
doc/nrf/samples/bl.rst
doc/nrf/samples/fast_pair.rst

Add a new category for Fast Pair samples

doc: Add new category for Fast Pair samples

---

.github/workflows/backport.yml

This is taken directly from:
https://github.com/zephyrproject-rtos/zephyr/commit/260d054092a5781c873834cbdffdff5496000e1a

actions: backport: Update action and run only if the org PR is merged

---

doc/nrf/gsg_guides.rst
doc/nrf/links.txt

doc: Mention of nRF9151 in the GSG

---

modules/hostap/src/supp_api.c
modules/hostap/src/supp_api.h
modules/hostap/src/supp_events.c
modules/hostap/src/supp_main.c
west.yml

Support for configuring BSS parameters max_inactivity, skip_inactivity_poll and max_num_sta

nrf_wifi: Set bss params max_inactivity, skip_inactivity_poll and max_num_sta

---

drivers/wifi/nrf700x/Kconfig
drivers/wifi/nrf700x/inc/fmac_main.h
drivers/wifi/nrf700x/src/fmac_main.c
drivers/wifi/nrf700x/src/net_if.c
drivers/wifi/nrf700x/src/wifi_util.c
west.yml

test-sdk-wifi: test-sdk-wifi-pr-15333

wifi: RPU watchdog recovery

---

west.yml

[nrf noup] Bluetooth: Mesh: Disable processing of ext ADV packets https://github.com/nrfconnect/sdk-zephyr/pull/1730

manifest:update sdk-zephyr

---

doc/nrf/config_and_build/configuring_app/advanced_building.rst
doc/nrf/device_guides/working_with_nrf/nrf52/developing.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
doc/nrf/samples.rst
doc/nrf/shortcuts.txt

[NCSIDB-1135](https://nordicsemi.atlassian.net/browse/NCSIDB-1135)
Add info about Samples common in:
* Samples' index.page
* Advanced building procedures page
~~Move content from Developing with nRF52 Series and nRF5340 DK FOTA information --> Configuring and building > DFU~~ (Moved to separate ticket)
[NCSIDB-1135]: https://nordicsemi.atlassian.net/browse/NCSIDB-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc: add info about samples common

---

applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_broadcast.c

Reuse the timeout calculation from Zephyr upstream, and also extended the PA sync timeout.
OCT-2924

applications: nrf5340_audio: Reuse PA sync timeout set from Zephyr

---

CODEOWNERS

Since Sebastian has left Nordic, remove him from the file.

CODEOWNERS: Remove Sebastian Bøe

---

west.yml

Updating nRF70 release/v2.6 firmware patch.

manifest: sdk-nrfxlib: Pull nRF70 v2.6 patch update rev#ff06137d3d7

---

sysbuild/CMakeLists.txt

Fixes a wrong path to this file

sysbuild: Fix external flash override file path

---

doc/nrf/releases_and_maturity/known_issues.rst

This commit adds two new issues found for Matter stack.

doc: known_issues: Add known issues for Matter stack

---

samples/matter/common/src/bridge/bridge_manager.cpp

When adding multiple devices to the bridge it may happen that we run out of heap. In such case the allocation of mDataVersion may fail and we end up with nullptr that is later passed to the Span causing its constructor to abort().
Avoid abort() by adding a sanity check and more error handing to the BridgeManager.
BTW. It doesn't seem to be a particularly good design that we allocate objects in MatterBridgedDevice c'tors.
As a follow up I suggest to either use static memory for mDataVersion, similarly to the mDeviceTypeList,
or consider adding Init() methods that would pose errors in case of lack of memory.

applications: Matter Bridge: avoid runtime crash caused by bad alloc

---

samples/benchmarks/coremark/Kconfig
samples/benchmarks/coremark/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
samples/benchmarks/coremark/boards/nrf54h20dk_nrf54h20_cpurad.overlay

samples: coremark: Add buttons and leds for rad core

---

scripts/quarantine.yaml

This reverts commit eb5326ddb42fea9411934550018af2581fa1f604.

Revert "scripts: Qurantine nRF54H Wi-Fi test"

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Adds entry explaining new random MAC Kconfig

doc: wifi: add random mac address changelog entry

---

doc/nrf/releases_and_maturity/known_issues.rst

Document Thread known issue:
High power consumption after parent loss.

doc: add Thread related known issue

---

samples/suit/recovery/README.rst
samples/suit/smp_transfer/sample.yaml

Minor doc and sample.yaml fixes.

samples: suit: recovery: minor bug fixes

---

scripts/hid_configurator/modules/dfu.py

Change introduces support for `manifest.json` with `format-version=2`.
Jira: NCSDK-27569

scripts: hid_configurator: Support manifest.json with format-version=2

---

applications/nrf5340_audio/unicast_client/main.c
applications/nrf5340_audio/unicast_server/main.c

OCT-3051
Print more specific conn info.

Applications: nrf5340_audio: Print num conns

---

doc/nrf/glossary.rst
doc/nrf/index.rst
doc/nrf/links.txt
doc/nrf/protocols.rst
doc/nrf/protocols/dect/index.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Add a page about DECT NR+ under protocols.

doc: add page about DECT under protocols

---

doc/nrf/device_guides/nrf54l.rst
doc/nrf/device_guides/working_with_nrf/nrf54l/features.rst
doc/nrf/device_guides/working_with_nrf/nrf54l/nrf54l15_gs.rst
doc/nrf/device_guides/working_with_nrf/nrf54l/testing_dfu.rst

adjusted the doc structure for nRF54L15

doc: nrf54l15 structure reorg

---

samples/suit/smp_transfer/README.rst

Align the SUIT sample documentation to reflect the latest state.

doc: update SUIT sample documentation

---

west.yml

Update SUIT generator revision.
Ref: NCSDK-27887

manifest: Update suit-generator revision

---

tests/subsys/suit/cache_pool_digest/testcase.yaml
tests/subsys/suit/cache_sink/testcase.yaml
tests/subsys/suit/flash_sink/testcase.yaml

tests: suit: Use sysbuild

---

applications/nrf5340_audio/src/bluetooth/bt_management/advertising/bt_mgmt_adv.c
applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.h
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.h
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c

- Correct some corrupted in the PBA advertising
- Created a function for adding metadata LTV's to PBA
- OCT-2949

applications: nrf5340_audio: Correct PBA data in adv

---

subsys/zigbee/lib/zigbee_app_utils/zigbee_app_utils.c
subsys/zigbee/osif/zb_nrf_platform.c
subsys/zigbee/osif/zb_nrf_platform.h
west.yml

Major modification: NVRAM improvements

manifest: nrfxlib update with new ZBOSS libraries

---

west.yml

Crypto EC for SAE has a memory leak.

manifest: sdk-hostap: Pull fix for crypto memleak

---

applications/machine_learning/configuration/nrf54h20dk_nrf54h20_cpuapp/app.overlay

This change updates the memory layout to prevent FLASH overflow. 
Expands the APP slot partition and removes the DFU partition.

applications: machine_learning: Update memory layout

---

samples/bluetooth/llpm/README.rst
samples/bluetooth/llpm/src/main.c

Error in my previous. Prited wrong message.

samples: bluetooth: Fixing print on connection

---

doc/nrf/releases_and_maturity/software_maturity.rst

Updated the Wi-Fi support to experimental

doc: small software maturity update

---

doc/nrf/libraries/bluetooth_services/services/fast_pair.rst
doc/nrf/links.txt
samples/bluetooth/fast_pair/locator_tag/src/main.c
subsys/bluetooth/services/fast_pair/Kconfig.fast_pair
subsys/bluetooth/services/fast_pair/fp_gatt_service.c

https://developers.google.com/nearby/fast-pair/specifications/devicefeaturerequirement/devicefeaturerequirement_locatortags

Alignment with Locator Tag specification

---

doc/_scripts/software_maturity/software_maturity_features.yaml

Add DECT NR+ PHY to software maturity page.

doc: software maturity: add DECT NR+ PHY

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

applications: nrf5340_audio: Update changelog for 2.7.0

---

west.yml

Update zephyr with fix in GRTC driver.

manifest: Update zephyr with GRTC fix

---

west.yml

Updates MCUboot to include MCUboot in the boot banner

manifest: Update sdk-mcuboot

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/bluetooth/fast_pair/input_device/README.rst
samples/bluetooth/iso_time_sync/README.rst
samples/bluetooth/peripheral_hids_mouse/README.rst
samples/peripheral/802154_phy_test/README.rst

Follow up PR of the https://github.com/nrfconnect/sdk-nrf/pull/15756  because the previous one got merged prematurely.
The list of the reviewers pulled from the code owners of the previous PR.
Please double-check the (already) live documentation of the samples samples you're working on: 
[Coremark](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/benchmarks/coremark/README.html)
[Central and peripheral HR](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/bluetooth/central_and_peripheral_hr/README.html)
[Central BAS](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/bluetooth/central_bas/README.html)
[Central HIDS](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/bluetooth/central_hids/README.html) …

doc: New button and LED numbering follow-up PR

---

applications/matter_weather_station/Kconfig
applications/matter_weather_station/Kconfig.sysbuild
applications/matter_weather_station/sample.yaml

Fixed Matter Weather Station on Thingy53 + nRF7002EB variant.
JIRA: KRKNWK-19062

applications: matter: Fix Weather Station WiFi variant.

---

west.yml

This commits updates the suit-processor repository with coverity fixes.

manifest: Update suit-processor

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Add information about new ZBOSS libraries.

doc: zigbee: update changelog about new libraries

---

applications/nrf5340_audio/unicast_client/main.c

- Check ACL interval before lowering it down
- Don't change it if it's already changed
- OCT-3035

applications: nrf5340_audio: Check ACL interval before changing

---

doc/_scripts/software_maturity/software_maturity_features.yaml
subsys/bluetooth/services/fast_pair/Kconfig.fast_pair

Added new Fast Pair features that will be used in the Software Maturity documentation.

doc: sml: add new fast pair features

---

west.yml

Update Zephyr version for Bluetooth Host fromtree commits.

manifest: Update Zephyr version for Bluetooth Host fromtree commit

---

doc/nrf/config_and_build/board_support/board_names.rst
doc/nrf/includes/sample_board_rows.txt

fixed the board name for crypto samples.
updated the board revision

doc: fix board revision and board name

---

samples/ipc/ipc_service/sample.yaml

Enable automatic testing by checkout console output.

samples: ipc: ipc_service: verify host console

---

west.yml

nRF53 still requires special partition manager quirks.

manifest: pull PM fixes for sysbuild hello_world

---

doc/nrf/config_and_build/dfu/index.rst
samples/suit/flash_companion/README.rst
samples/suit/recovery/README.rst

Fix title for samples
Link to SUIT in DFU doc

doc: improvement: suit

---

scripts/tag_west_repos.sh

Add suit repositories to the tag_west_repos.sh script
Ref: NONE

scripts: add suit repositories to tag_west_repos

---

samples/suit/smp_transfer/README.rst

Added instructions to the readme on how to build the external flash and external flash plus BLE configurations.

samples: suit: add instructions for building extflash config

---

samples/matter/lock/Kconfig.sysbuild
samples/matter/template/Kconfig.sysbuild
samples/matter/template/sample.yaml

Fixed the WiFi variant for nRF54H20.

samples: matter: Fix radio core image for nRF54H20 + nRF7002EK

---

.github/test-spec.yml
samples/event_manager_proxy/sample.yaml

Enable automatic testing by checkout console output.

samples: event_manager_proxy: verify host console

---

scripts/quarantine_zephyr.yaml

Samples will be automatically filtered after upmerging https://github.com/zephyrproject-rtos/zephyr/pull/73777.

scripts: update quarantine for nrf54h20/cpurad.

---

samples/tfm/tfm_psa_template/README.rst

Update documentation to reflect sysbuild changes.
Sample code changes in: https://github.com/nrfconnect/sdk-nrf/pull/15885

samples: tfm: tfm_psa_template: Update documentation

---

applications/protocols_serialization/client/sysbuild.conf
applications/protocols_serialization/server/sysbuild.conf

Commit adds sysbuild configuration files to
protocol serialization application.

applications: add sysbuild configuration

---

subsys/bluetooth/rpc/client/bt_rpc_conn_client.c
subsys/bluetooth/rpc/client/bt_rpc_gap_client.c
subsys/bluetooth/rpc/client/bt_rpc_gatt_client.c
subsys/bluetooth/rpc/host/bt_rpc_conn_host.c
subsys/bluetooth/rpc/host/bt_rpc_gap_host.c
subsys/bluetooth/rpc/host/bt_rpc_gatt_host.c

Commit adds key word static to all local functions.

bluetooth: rpc: add static to local functions

---

applications/nrf_desktop/src/modules/Kconfig.usb_state
applications/nrf_desktop/src/modules/usb_state.c

Adds option to call usbd_enable/usbd_disable on USB cable connection/disconnection. It workarounds USB issues on nRF54H20.
Jira: NCSDK-27880
Jira: NCSDK-27878

applications: nrf_desktop: Fix USB state when disconnecting cable

---

scripts/quarantine_zephyr.yaml

Failing tests for nrf54l15 flpr and nrf54h20 ppr.

scripts: update quarantine for nrf54.

---

applications/serial_lte_modem/src/slm_at_commands.c

Allow custom command handling in libmodem to finish processing, before restarting libmodem.
Fixes instability with full modem FOTA.

applications: serial_lte_modem: Fix AT#XMODEMRESET

---

samples/bluetooth/peripheral_hids_mouse/src/main.c

Added a check to ensure Bluetooth advertising is not initiated if it is already running.

samples: bluetooth: peripheral_hids_mouse: Don't start advertising when active

---

samples/matter/lock/README.rst
samples/matter/template/README.rst

- Fixed missing WiFi configuration for nR54H20 in docs.
- Fixed HW model v2 for nrf54l15 in tempalte.

doc: matter: Fixes for Matter samples

---

subsys/nrf_rpc/nrf_rpc_uart.c

Adding calculation of CRC to HDLC framer in uart transport.

nrf_rpc: Add CRC16_CCITT calculation to hdlc frame.

---

samples/bluetooth/mesh/dfu/distributor/sysbuild.cmake

Updating the bin path with correct directory.

samples: bluetooth: mesh: fix bin path for fwid script

---

samples/bluetooth/mesh/dfu/target/sysbuild.cmake

Updating the bin path with correct directory for dfu target sample.

samples: bluetooth: mesh: fix bin path for dfu target sample

---

applications/nrf_desktop/board_configuration.rst
applications/nrf_desktop/bootloader_dfu.rst
applications/nrf_desktop/description.rst
applications/nrf_desktop/doc/dfu.rst
applications/nrf_desktop/doc/dfu_mcumgr.rst
scripts/hid_configurator/README.rst

Change adds documentation for SUIT
Jira: NCSDK-27409

applications: nrf_desktop: Document SUIT support

---

scripts/quarantine_zephyr.yaml

Clear:
buildsystem.kconfig.utf8_in_values
sample.modules.canopennode.no_storage

scripts: quarantine: clear quarantine

---

west.yml

Include fixes for socs in hwmv1

manifest: Update sdk-soc-hwmv1 version

---

doc/nrf/links.txt
doc/nrf/shortcuts.txt

Updated ZBOSS to v3.11.4.0 and NCP Host package to v2.2.3.

doc: zboss: update version number

---

subsys/shell/shell_bt_nus.c

The tx_try function is called by both cooperative and preemptible threads.
A mutex has been added to ensure data integrity in the tx_ringbuf ring buffer.

shell: shell_bt_nus: Prevent data corruption in the tx_ringbuffer

---

applications/nrf_desktop/description.rst
applications/nrf_desktop/doc/usb_state.rst

doc: nrf_desktop: Describe nRF54H USB support

---

west.yml

sidewalk dfu over fuota - bugfixing and documentation
[KRKNWK-19101] [KRKNWK-19097]
[KRKNWK-19101]: https://nordicsemi.atlassian.net/browse/KRKNWK-19101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KRKNWK-19097]: https://nordicsemi.atlassian.net/browse/KRKNWK-19097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

manifest: sidewalk update

---

sysbuild/Kconfig.bt_fast_pair
sysbuild/Kconfig.dfu
sysbuild/Kconfig.matter
sysbuild/Kconfig.mcuboot
sysbuild/Kconfig.netcore
sysbuild/Kconfig.secureboot

Updates Kconfig text to make things clearer

sysbuild: Update Kconfig text

---

doc/nrf/protocols/matter/getting_started/adding_clusters.rst

The `Adding cluster in Matter` instruction update with additional notes to be more precise, and fix the testing steps.

doc: nrf: matter: Updating the `Adding cluster` instruction

---

west.yml

Change NRFS logs to debug level to avoid breaking tests.
Jira: NCSDK-27870

manifest: zephyr: Change NRFS logs to debug level

---

doc/nrf/create_application.rst
doc/nrf/installation/install_ncs.rst

Fixed GUI references to the VS Code extension.

doc: extension: fix GUI references

---

doc/nrf/config_and_build/board_support/board_names.rst
doc/nrf/releases_and_maturity/migration/migration_hwmv2.rst

Edited the hwmodelv2 migration guide.

doc: hwmodelv2 migration guide fix

---

doc/nrf/config_and_build/bootloaders/bootloader_downgrade_protection.rst
doc/nrf/config_and_build/configuring_app/zephyr_samples_sysbuild.rst
doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst
doc/nrf/includes/nRF54H20_erase_UICR.txt

Change introduces some small fixes and improvements to documentation.

doc-improvement: doc: nrf: Small fixes and improvements

---

doc/nrf/samples/suit.rst

Changed SUIT sample order on the SUIT samples container page. Requested by @maciejpietras.

doc: suit: change sample order

---

samples/bluetooth/rpc_host/README.rst

Update the building example application documentation with changes related to sysbuild.

samples: rpc_host: Update the building documentation

---

doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_external_memory.rst
samples/suit/smp_transfer/README.rst

Correct build and test steps in the documentation.

samples: suit: Documentation update

---

doc/nrf/images/nrf5340_audio_structure_generic.svg

Fixed the outdated ref to HCI RPMSG on one of the images.

doc: nrf5340_audio: SVG update for HCI IPC

---

doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7.rst
doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/migration_guide_2.4.99-cs3_to_2.7_application.rst
doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/migration_guide_2.6.99-cs2_to_2.7_application.rst
doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/migration_guide_2.6.99-cs2_to_2_7_environment.rst
doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/transition_guide_2.4.99-cs3_to_2.7_environment.rst

doc: Fixed 54H migration homepage

---

scripts/quarantine.yaml
scripts/quarantine_zephyr.yaml

Remove elements which are already passing.

scripts: quarantine: clean quarantine

---

doc/nrf/releases_and_maturity/migration/migration_hwmv2.rst

Fixed links in migration guide.

doc: Fixed links in migration guide

---

cmake/sysbuild/partition_manager.cmake

Fixes issues with partition manager dependency watching
NCSDK-22499

sysbuild: cmake: Fix PM dependency watching

---

west.yml

Include https://github.com/nrfconnect/sdk-soc-hwmv1/commit/32b1ee3e4576815bebf9ce3e8d63efe73bd89c62

manifest: Update SHA to include fix in sdk-soc-hwmv1

---

west.yml

Update sdk-zephyr to pull in root path list fixes for sysbuild.

 manifest: Update sdk-zephyr revision

---

doc/nrf/links.txt
doc/nrf/releases_and_maturity/known_issues.rst

Added v2.7.0 tag to known issues.
----

doc: update known issues for NCS v2.7.0

---

doc/nrf/releases_and_maturity.rst
doc/nrf/releases_and_maturity/known_issues.rst

Unorphan known issues after 2.7.0.

doc: bring back known issues to latest

---

west.yml

Manifest update with fix for OpenThread.
KRKNWK-19036
test_thread: master

manifest: update `sdk-zephyr` with OpenThread fix

---

doc/nrf/releases_and_maturity/known_issues.rst

Documents ppi channel bug for platforms using DPPI.

doc: Add known issue about VS Set Connection Event Trigger command

---

samples/bluetooth/central_and_peripheral_hr/src/main.c

This fixes coverity issues in Central and Peripheral HR sample.
Jira: NCSDK-27145

samples: central_and_peripheral_hr: Fix coverity

---

applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.h
applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.h
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
applications/nrf5340_audio/unicast_client/main.c
include/audio_defines.h

- Each stream now has a three level index
- Group
- Subgroup
- Stream_number
- Change le_audio_tx to accept new index and cap streams
- OCT-3042

applications: nrf5340_audio: Use three level index per stream

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/net/nrf_cloud_rest.h
samples/cellular/nrf_cloud_rest_fota/Kconfig
samples/cellular/nrf_cloud_rest_fota/README.rst
samples/cellular/nrf_cloud_rest_fota/src/main.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_rest.c

Add function nrf_cloud_rest_shadow_transform_request to the nrf_cloud_rest library.
Add demo of new function using the nrf_cloud_rest_fota sample.
IRIS-9188

net: lib: nrf_cloud_rest: add shadow transform request function

---

doc/nrf/releases_and_maturity/known_issues.rst

The issue is also present in these releases.

doc: known_issues: Make DRGN-16013 apply to v2.6 and v2.7

---

applications/matter_weather_station/src/app_task.cpp
applications/matter_weather_station/src/main.cpp

Added few logs informing about the currently measured values by the Matter weather station. This is required mainly for the QA verification purposes.

applications: Added debug logs to the Matter weather station

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
west.yml

manifest: sdk-nrfxlib: Pull nRF70 patch update rev#32c836f2a83

---

cmake/mesh_dfu_metadata.cmake
cmake/sysbuild/b0_packaging.cmake
cmake/sysbuild/fast_pair_hex.cmake
sysbuild/CMakeLists.txt
sysbuild/Kconfig.zip

Removes include functions and just includes files directly where this is appropriate

sysbuild: Remove include functions

---

tests/benchmarks/multicore/idle/boards/nrf54h20dk_nrf54h20_cpuapp_ram_high_usage.overlay
tests/benchmarks/multicore/idle/boards/nrf54h20dk_nrf54h20_cpuapp_ram_low_usage.overlay
tests/benchmarks/multicore/idle/testcase.yaml

NRFX-5697: Implement E2E RAM retention test
small vs big RAM usage by app and current measurements

tests: benchmarks: multicore: idle: Implement E2E RAM retention test

---

applications/matter_bridge/sample.yaml
applications/matter_weather_station/sample.yaml
samples/matter/light_bulb/sample.yaml
samples/matter/light_switch/sample.yaml
samples/matter/lock/sample.yaml
samples/matter/template/sample.yaml
samples/matter/thermostat/sample.yaml
samples/matter/window_covering/sample.yaml
scripts/ci/tags.yaml

Extend list of paths used to check if matter

samples: matter: add matter tag for samples

---

samples/suit/smp_transfer/sample.yaml

Added sample variant merging the extmem and BT functionality to the smp_transfer sample.yaml file.

samples: suit: add extmem plus BT variant to sample.yaml

---

samples/crypto/aes_cbc/sample.yaml
samples/crypto/aes_ccm/sample.yaml
samples/crypto/aes_ctr/sample.yaml
samples/crypto/aes_gcm/sample.yaml
samples/crypto/chachapoly/sample.yaml
samples/crypto/ecdh/sample.yaml
samples/crypto/ecdsa/sample.yaml
samples/crypto/ecjpake/sample.yaml
samples/crypto/eddsa/sample.yaml
samples/crypto/hkdf/sample.yaml
samples/crypto/hmac/sample.yaml
samples/crypto/pbkdf2/sample.yaml
samples/crypto/persistent_key_usage/sample.yaml
samples/crypto/psa_tls/sample.yaml
samples/crypto/rng/sample.yaml
samples/crypto/rsa/sample.yaml
samples/crypto/sha256/sample.yaml
samples/crypto/spake2p/sample.yaml
scripts/ci/tags.yaml
tests/crypto/testcase.yaml

Extend list of paths used to check if crypto tests/samples should be executed.

samples: crypto: add crypto tag for samples

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/blkcipher.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ctr_drbg.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/include/sxsymcrypt/aes.h
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/include/sxsymcrypt/blkcipher.h
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/blkcipher.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/hw.h
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/platform/baremetal/cmdma_hw.c

cracen: Stack size reduction

---

samples/zigbee/light_bulb/sample.yaml
samples/zigbee/light_switch/sample.yaml
samples/zigbee/ncp/sample.yaml
samples/zigbee/network_coordinator/sample.yaml
samples/zigbee/shell/sample.yaml
samples/zigbee/template/sample.yaml
scripts/ci/tags.yaml
tests/subsys/zigbee/osif/crypto/testcase.yaml
tests/subsys/zigbee/osif/nvram/testcase.yaml
tests/subsys/zigbee/osif/serial/serial_async_api/testcase.yaml
tests/subsys/zigbee/osif/serial/serial_basic_api/testcase.yaml
tests/subsys/zigbee/osif/serial/serial_via_logger/testcase.yaml
tests/subsys/zigbee/osif/timer_counter/testcase.yaml
tests/subsys/zigbee/osif/timer_ktimer/testcase.yaml
tests/subsys/zigbee/zboss_api/alarm_api/testcase.yaml
tests/subsys/zigbee/zboss_api/callback_api/testcase.yaml

Extend list of paths used to check if zigbee

samples: zigbee: add zigbee tag for samples

---

samples/openthread/cli/sample.yaml
samples/openthread/coap_client/sample.yaml
samples/openthread/coap_server/sample.yaml
samples/openthread/coprocessor/sample.yaml
scripts/ci/tags.yaml

Extend list of paths used to check if openthread

samples: openthread: add openthread tag for samples

---

west.yml

Update suit-processor revision.
Ref: NCSDK-23439

manifest: Update suit-processor revision

---

samples/tfm/provisioning_image/sample.yaml
samples/tfm/provisioning_image_net_core/sample.yaml
samples/tfm/tfm_hello_world/sample.yaml
samples/tfm/tfm_psa_template/sample.yaml
scripts/ci/tags.yaml
tests/tfm/tfm_psa_test/testcase.yaml
tests/tfm/tfm_regression_test/testcase.yaml

Extend list of paths used to check if tfm
tests/samples should be executed.

samples: tfm: add tfm tag for samples

---

scripts/ci/tags.yaml
tests/subsys/suit/cache_fetch/testcase.yaml
tests/subsys/suit/copy/testcase.yaml
tests/subsys/suit/envelope_decoder/testcase.yaml
tests/subsys/suit/execution_mode/testcase.yaml
tests/subsys/suit/fetch/testcase.yaml
tests/subsys/suit/fetch_integrated_payload_flash/testcase.yaml
tests/subsys/suit/fetch_source_mgr/testcase.yaml
tests/subsys/suit/flash_sink/testcase.yaml
tests/subsys/suit/integrated_fetch/testcase.yaml
tests/subsys/suit/invoke/testcase.yaml
tests/subsys/suit/mci/testcase.yaml
tests/subsys/suit/memptr_sink/testcase.yaml
tests/subsys/suit/ram_sink/testcase.yaml
tests/subsys/suit/sink_selector/testcase.yaml
tests/subsys/suit/storage/testcase.yaml
tests/subsys/suit/storage_nrf54h20/testcase.yaml
tests/subsys/suit/suit_memptr_storage/testcase.yaml
tests/subsys/suit/write/testcase.yaml

Extend list of paths used to check if suit

tests: subsys: suit: add suit tag for samples

---

subsys/bluetooth/adv_prov/providers/fast_pair.c

adv_prov: fast_pair: Fix uninitialized structure

---

subsys/bluetooth/services/hids.c

services: hids: Fix possible out-of-bound access

---

subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c

Set SDK version string reported to the cloud to the correct value.

net: lib: nrf_cloud: Fix SDK version string

---

applications/zigbee_weather_station/sample.yaml

Add zigbee tag, so it can be skipped for no zigbee related changes.

applications: zigbee_weather_station: add zigbee tag

---

doc/nrf/security/tfm.rst
lib/bin/lwm2m_carrier/pm.yml.lwm2m_carrier
modules/trusted-firmware-m/tfm_boards/common/assert.c
modules/trusted-firmware-m/tfm_boards/partition/region_defs.h
subsys/partition_manager/Kconfig
subsys/partition_manager/pm.yml.emds
subsys/partition_manager/pm.yml.file_system
subsys/partition_manager/pm.yml.memfault
subsys/partition_manager/pm.yml.nvs
subsys/partition_manager/pm.yml.tfm
subsys/partition_manager/pm.yml.zboss
west.yml

See commit messages for descriptions.

Fix TF-M flash region configuration for nRF54L15

---

subsys/suit/platform/app/src/suit_plat_copy.c
subsys/suit/platform/app/src/suit_plat_swap.c
subsys/suit/platform/app/src/suit_plat_write.c
subsys/suit/platform/sdfw/src/suit_plat_copy.c
subsys/suit/platform/sdfw/src/suit_plat_swap.c
subsys/suit/platform/sdfw/src/suit_plat_write.c
subsys/suit/platform/src/suit_plat_fetch.c
tests/subsys/suit/cache_pool_digest/src/main.c
tests/subsys/suit/copy/src/main.c
tests/subsys/suit/fetch/src/main.c
tests/subsys/suit/unit/mocks/include/mock_suit_platform.h
tests/subsys/suit/write/src/main.c
west.yml

SUIT procssor is responsible for decoding encryption info. The SUIT platform is responsible for performing the decryption. Pass the encryption info through the dedicated structure to the platform, so it can perform the decryption.
Ref: NCSDK-28262

suit: Pass encryption info to the platform

---

scripts/ci/tags.yaml
west.yml

Fix depencies for nrf_destkop downstream.

manifest: update zephyr with test-spec for nrf_desktop

---

samples/net/aws_iot/sample.yaml
samples/net/azure_iot_hub/sample.yaml
samples/net/coap_client/sample.yaml
samples/net/download/sample.yaml
samples/net/http_server/sample.yaml
samples/net/https_client/sample.yaml
samples/net/mqtt/sample.yaml
samples/net/udp/sample.yaml
scripts/ci/tags.yaml
tests/subsys/net/lib/aws_fota/aws_fota_json/testcase.yaml
tests/subsys/net/lib/aws_iot/testcase.yaml
tests/subsys/net/lib/azure_iot_hub/dps/testcase.yaml
tests/subsys/net/lib/azure_iot_hub/iot_hub/testcase.yaml
tests/subsys/net/lib/download_client/testcase.yaml
tests/subsys/net/lib/fota_download/testcase.yaml
tests/subsys/net/lib/lwm2m_client_utils/testcase.yaml
tests/subsys/net/lib/lwm2m_fota_utils/testcase.yaml
tests/subsys/net/lib/mcumgr_smp_client/testcase.yaml
tests/subsys/net/lib/mqtt_helper/testcase.yaml
tests/subsys/net/lib/nrf_cloud/fota_common/testcase.yaml
tests/subsys/net/lib/nrf_provisioning/testcase.yaml
tests/subsys/net/lib/wifi_credentials/testcase.yaml
tests/subsys/net/lib/wifi_credentials_backend_psa/testcase.yaml
tests/subsys/net/lib/wifi_credentials_backend_settings/testcase.yaml

Extend list of paths used to check if net tests/samples should be executed.

samples: net: add net tag for samples

---

scripts/ci/tags.yaml

scripts: ci: tags: add tags for sidewalk

---

west.yml

manifest: sdk-sidewalk: Update revision

---

.github/test-spec.yml
test-manifests/99-default-test-nrf.yml

Trigger Protocols Serialization system integration tests on a NCS PR

samples: suit: Protocols Serialization tests trigger

---

samples/cellular/lwm2m_client/sample_description.rst

Documentation for Firmware Update using Leshan is just copy-pasted from Coiote and therefore it is wrong. Fix the documentation to reflect Leshan Demo UI.

doc: lwm2m_client: Fix the Leshan FOTA process

---

doc/nrf/device_guides/nrf91/nrf91_programming.rst
doc/nrf/device_guides/nrf91/nrf91_snippet.rst

Edited the snippet page under Developing with nRF91 for style and consistency.
NRFU-1011.

doc: nrf91: snippet page edits

---

west.yml

Add upstream changes to the BT host which are accepted and are waiting for the merge-window to open again.

manifest: drag in bt host changes in zephyr

---

scripts/twister/alt/zephyr/tests/drivers/i2c/i2c_bme688/testcase.yaml

NRFX-6040: Align tests/drivers/i2c/i2c_bme688 to PPR and FLPR

tests: drivers: i2c: Run i2c_bme688 test on nrf54h PPR and nrf54l FLPR

---

samples/peripheral/802154_phy_test/sample.yaml
samples/peripheral/802154_sniffer/sample.yaml
samples/peripheral/radio_test/sample.yaml
scripts/ci/tags.yaml

samples: peripheral: add tags for 802154 and radio samples

---

applications/protocols_serialization/client/src/ot_shell.c

The "ot state <role>" command cannot be procesed by the RPC client because APIs like otThreadBecomeRouter() are not serializeable yet. Send such commands to be processed by the RPC server to keep the existing functionality.

applications: protocols_serialization: fix "ot state" command

---

samples/wifi/thread_coex/src/ot_utils.c

Exit the test with an error message if the device becomes router instead of child. This avoids infinite wait on getting child role.

samples: wifi: thread_coex: Handle OT role becoming router

---

samples/keys/hw_unique_key/sample.yaml
scripts/ci/tags.yaml

samples: keys: add tags for samples/keys

---

samples/esb/esb_prx/sample.yaml
samples/esb/esb_ptx/sample.yaml
scripts/ci/tags.yaml

samples: esb: add tags for samples/esb

---

scripts/ci/tags.yaml
tests/subsys/bluetooth/fast_pair/crypto/testcase.yaml
tests/subsys/bluetooth/fast_pair/storage/account_key_storage/testcase.yaml
tests/subsys/bluetooth/fast_pair/storage/factory_reset/testcase.yaml

tests: subsys: bluetooth: fast_pair: add fast_pair tag

---

samples/edge_impulse/data_forwarder/sample.yaml
samples/edge_impulse/wrapper/sample.yaml
scripts/ci/tags.yaml

samples: edge_impulse: add tags for samples/edge_impulse

---

applications/matter_bridge/Kconfig.sysbuild
applications/matter_bridge/boards/nrf54h20dk_nrf54h20_cpuapp.conf
applications/matter_bridge/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
applications/matter_bridge/doc/matter_bridge_description.rst
applications/matter_bridge/sample.yaml
applications/matter_bridge/sysbuild/ipc_radio/boards/nrf54h20dk_nrf54h20_cpurad.conf
applications/matter_bridge/sysbuild/ipc_radio/boards/nrf54h20dk_nrf54h20_cpurad.overlay
applications/matter_bridge/sysbuild/ipc_radio/overlay-bt_max_connections_net.conf
applications/matter_bridge/sysbuild/ipc_radio/prj.conf
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

introduce changes to konfig.sysbuild files

Applications:added nrf54h to matter-bridge

---

scripts/ci/tags.yaml
tests/subsys/bootloader/bl_crypto/testcase.yaml
tests/subsys/bootloader/bl_storage/testcase.yaml
tests/subsys/bootloader/bl_validation/testcase.yaml
tests/subsys/bootloader/bl_validation_ff_key/testcase.yaml
tests/subsys/bootloader/bl_validation_neg/testcase.yaml
tests/subsys/bootloader/bl_validation_unittest/testcase.yaml
tests/subsys/bootloader/boot_chains/testcase.yaml

tests: subsys: bootloader: add bootloader tag

---

samples/app_event_manager/sample.yaml
scripts/ci/tags.yaml
tests/subsys/app_event_manager/testcase.yaml

samples: app_event_manager: add tags for samples/app_event_manager

---

scripts/quarantine_zephyr.yaml
west.yml

Include changes introduced with:
https://github.com/nrfconnect/sdk-zephyr/pull/1891
https://github.com/zephyrproject-rtos/zephyr/pull/73024

manifest: update sdk-zephyr - get latest MBOX driver

---

doc/nrfxlib/nrfxlib.doxyfile.in

__ALIGN was not defined in the doxyfile

doc: nrfxlib: Fix doxygen warnings for SDC api

---

applications/ipc_radio/sample.yaml
scripts/ci/tags.yaml

Extend tags for CI test scope selection.

applications: ipc_radio: add tags for app ipc_radio

---

CODEOWNERS

Since he doesn't work for Nordic anymore.

CODEOWNERS: Remove mswarowsky

---

applications/machine_learning/sample.yaml
scripts/ci/tags.yaml

Extend tags for CI test scope selection.

applications: machine_learning: add tags for app machine_learning

---

subsys/nrf_security/Kconfig
subsys/nrf_security/src/drivers/Kconfig
west.yml

With support for legacy and PSA for
nRF54L15.

manifest: Bring Oberon PSA repo

---

applications/nrf_desktop/sample.yaml
scripts/ci/tags.yaml

bluetooth tag does not fits here.

applications: nrf_desktop: use nrf_deskop specific tag

---

doc/nrf/releases_and_maturity/known_issues.rst

Adds details on NCSDK-28451, NCSDK-28461 and NCSDK-28462

doc: known_issues: Add NCS 2.7 sysbuild known issues

---

samples/matter/common/src/dfu/ota/ota_util.cpp
samples/matter/lock/boards/nrf54h20dk_nrf54h20_cpuapp.conf
samples/matter/lock/sample.yaml
samples/matter/template/boards/nrf54h20dk_nrf54h20_cpuapp.conf
samples/matter/template/sample.yaml
sysbuild/CMakeLists.txt
sysbuild/Kconfig.matter
west.yml

Modified configuration files to allow enabling Matter OTA even if DFU multi image is not used (SUIT case).

samples: matter: Added support for Matter OTA with SUIT

---

subsys/nfc/tnep/tag.c

nfc:tnep: Fix dereferencing null pointer records

---

scripts/ci/tags.yaml

- zephyr/cmake/
- zephyr/share/
- nrf/cmake/
- nrf/sysbuild/

scripts: ci: tags: add common build system code for dep

---

west.yml

pull in adc_accuracy test aligned to nrf devices.

manifest: update sdk-zephyr revision.

---

samples/cellular/modem_shell/sample.yaml

Replace OVERLAY_CONFIG with EXTRA_CONF_FILE in sample.yaml.
Jira: MOSH-593

samples: cellular: modem_shell: Take EXTRA_CONF_FILE into use

---

samples/bluetooth/fast_pair/locator_tag/src/ui/platform_dk.c

Reorganized the UI implementation for DKs.
Added FP advertising mode indication for DKs using the provisioning LED (LED3).
Jira: NCSDK-22828
Jira: NCSDK-28077

samples: bluetooth: fast_pair: locator_tag: Add FP adv LED ind for DKs

---

doc/nrf/device_guides/working_with_nrf/nrf54l/nrf54l15_gs.rst

removed an obsolete section from the getting started

doc: remove a section from nRF54l15 gs

---

scripts/ci/tags.yaml
tests/drivers/flash/flash_rpc/testcase.yaml
tests/drivers/lpuart/testcase.yaml
tests/lib/at_cmd_custom/testcase.yaml
tests/lib/contin_array/testcase.yaml
tests/lib/data_fifo/testcase.yaml
tests/lib/date_time/testcase.yaml
tests/lib/gcf_sms/testcase.yaml
tests/lib/hw_unique_key/testcase.yaml
tests/lib/hw_unique_key_tfm/testcase.yaml
tests/lib/lte_lc/testcase.yaml
tests/lib/lte_lc_api/testcase.yaml
tests/lib/modem_battery/testcase.yaml
tests/lib/modem_info/testcase.yaml
tests/lib/modem_jwt/testcase.yaml
tests/lib/pcm_mix/testcase.yaml
tests/lib/pcm_stream_channel_modifier/testcase.yaml
tests/lib/pdn/testcase.yaml
tests/lib/qos/testcase.yaml
tests/lib/ram_pwrdn/testcase.yaml
tests/lib/sample_rate_converter/testcase.yaml
tests/lib/sfloat/testcase.yaml
tests/lib/sms/testcase.yaml
tests/lib/tone/testcase.yaml
tests/nrf5340_audio/macros/testcase.yaml
tests/nrf5340_audio/sw_codec_lc3/testcase.yaml
tests/unity/example_test/testcase.yaml
tests/unity/wrap_test/testcase.yaml

scripts: ci: tags: add tags part 3

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/bluetooth/conn_time_sync/README.rst

Adding some entries that were missed out earlier

Doc: Changelog entries for Bluetooth samples

---

applications/nrf_desktop/src/modules/usb_state.c

PR simplifies HID reports handling in USB state module.
Jira: NCSDK-28375

applications: nrf_desktop: Simplify HID report handling in USB state

---

.github/test-spec.yml
CODEOWNERS
tests/drivers/pwm/gpio_loopback/CMakeLists.txt
tests/drivers/pwm/gpio_loopback/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
tests/drivers/pwm/gpio_loopback/boards/nrf54h20dk_nrf54h20_cpuppr.overlay
tests/drivers/pwm/gpio_loopback/boards/nrf54h20dk_nrf54h20_cpuppr_launcher.overlay
tests/drivers/pwm/gpio_loopback/boards/nrf54h20dk_nrf54h20_cpuppr_launcher.toml
tests/drivers/pwm/gpio_loopback/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay
tests/drivers/pwm/gpio_loopback/boards/nrf54l15pdk_nrf54l15_cpuflpr.overlay
tests/drivers/pwm/gpio_loopback/dts/bindings/test-pwm-to-gpio-loopback.yaml
tests/drivers/pwm/gpio_loopback/prj.conf
tests/drivers/pwm/gpio_loopback/src/main.c
tests/drivers/pwm/gpio_loopback/src/test_pwm_to_gpio_loopback.c
tests/drivers/pwm/gpio_loopback/src/test_pwm_to_gpio_loopback.h
tests/drivers/pwm/gpio_loopback/testcase.yaml

tests: drivers: pwm: add test with gpio loopback

---

subsys/net/lib/nrf_cloud/src/nrf_cloud_download.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps_utils.c

Add handling for canceled CoAP downloads.
IRIS-9371

net: lib: nrf_cloud: handle canceled coap downloads

---

samples/bootloader/sample.yaml
samples/dect/dect_phy/hello_dect/sample.yaml
samples/nrf_rpc/entropy_nrf53/cpuapp/sample.yaml
samples/nrf_rpc/entropy_nrf53/cpunet/sample.yaml
samples/peripheral/lpuart/sample.yaml
samples/sdfw/ssf_client/sample.yaml
samples/sensor/bh1749/sample.yaml
samples/sensor/bme68x_iaq/sample.yaml
scripts/ci/tags.yaml
tests/drivers/pwm/gpio_loopback/testcase.yaml

scripts: ci: tags: add tags part 5

---

boards/nordic/thingy91x/nrf70_support.c

Fixes the nrf_wifi_if_zep_stop_board() function to properly disable the wifi regulator when the interface is stopped.

boards: thingy91x_nrf9151: Improve wifi power management

---

samples/crypto/psa_tls/boards/nrf54l15pdk_nrf54l15_cpuapp_ns.conf
samples/crypto/psa_tls/sample.yaml

Add support for nrf54l15pdk/nrf54l15/cpuapp/ns for psa_tls sample.
test_crypto: PR-638

samples: crypto: psa_tls: Add nrf54l15-ns support

---

doc/nrf/libraries/networking/lwm2m_client_utils.rst

* Remove outdated information of Nb-IoT and not supporting Bootstrap.
* Remove outdated information regarding read-callbacks. lwm2m_set_*() API should be used. Otherwise Notify operation does not work.
* Use LWM2M_OBJ_INIT() and LWM2M_APP_INIT() macros on sample.

doc: lwm2m_client_utils: Update documentation regarding objects

---

applications/nrf5340_audio/broadcast_sink/main.c
applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.h
applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_broadcast.c
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c

Pass broadcast code ptr instead of duplicated copies.

applications: nrf5340_audio: Improve broadcast code delivery

---

drivers/wifi/nrf700x/Kconfig
west.yml

Option to select power save data retrieval mechanism.

Option to select power save data retrieval mechanism  from AP

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

This commit adds the changelog for commit:
57daf41e953086d5d023b11599155e15c2d46b2e

Bluetooth: Mesh: add changelog for added metadata to mesh models

---

drivers/wifi/nrf700x/Kconfig
drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fw/host_rpu_sys_if.h
drivers/wifi/nrf700x/osal/fw_if/umac_if/src/cmd.c

[SHEL-2947] Changing naming of power save mode to mechanism(Text change).
[SHEL-2947]: https://nordicsemi.atlassian.net/browse/SHEL-2947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

drivers: wifi: Change mode to mechanism

---

subsys/net/openthread/Kconfig.defconfig
west.yml

Regular OpenThread update to \`602167f\`

manifest: openthread: update to \`602167f\`

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/zigbee/light_switch/Kconfig
samples/zigbee/light_switch/README.rst
samples/zigbee/light_switch/include/zb_mem_config_custom.h
samples/zigbee/light_switch/src/main.c

Configure light switch tx power to a different value than default.

samples: zigbee: make light switch tx power configurable

---

applications/nrf5340_audio/doc/configuration.rst
applications/nrf5340_audio/doc/firmware_architecture.rst
applications/nrf5340_audio/sample.yaml

OCT-3067
Added more explicitly the use of flags in the doc. Cleaned up sample.yaml

Applications: nrf5340_audio: Doc and sample.yaml update

---

west.yml

This change pulls in the null checks added for
malloc calls.

manifest: sdk-wi-fiquicktrack-controlappc: Pull fix for malloc check

---

applications/nrf_desktop/src/modules/usb_state.c

The local HID report buffering ensures that memory passed to USB next stack is valid until HID report is sent. It also allows to enqueue multiple HID reports in the USB state module.
Jira: NCSDK-28375
Jira: NCSDK-28224

applications: nrf_desktop: Add local HID report buffering to USB state

---

west.yml

Regular OpenThread update to \`a759a4a\`

manifest: openthread: update to \`a759a4a\`

---

doc/CMakeLists.txt
doc/_utils/utils.py
doc/internal/conf.py
west.yml

Add internal documentation docset for documentation builds in the environments with access to the private internal documentation repository.

Add internal documentation

---

west.yml

Update the doc-internal repository revision

manifest: update doc-internal revision

---

drivers/wifi/nrf700x/src/net_if.c

[SHEL-1063] Add calculation of drop packets in tx due to lack of buffer memory.
[SHEL-1063]: https://nordicsemi.atlassian.net/browse/SHEL-1063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

drivers: wifi: Add tx packets drop count calculation

---

applications/serial_lte_modem/src/slm_cmux.c
applications/serial_lte_modem/src/slm_ppp.c
applications/serial_lte_modem/src/slm_ppp.h

applications: serial_lte_modem: CMUX and PPP logic fixes

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ctr_drbg.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/blkcipher.c

Fixes caching issues in PRNG implementation.

cracen: Cache maintenance fix for PRNG

---

west.yml

Add exception on lack of connected remotes.
Also add information about remote repository in readme requirements.
Jira: NCSDK-28668

manifest: Update find-my revision

---

subsys/bluetooth/mesh/shell/shell_time_cli.c

Commit fixes model id in time model shell client.

Bluetooth: Mesh: fix model id in time shell client

---

doc/nrf/links.txt
samples/pmic/native/npm1300_fuel_gauge/README.rst

Added link to fuel gauge application note in summary.

samples: npm1300_fuel_gauge: README: Added app note link.

---

subsys/nrf_security/Kconfig
subsys/nrf_security/src/drivers/cracen/cracenpsa/cracenpsa.cmake
subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_key_ids.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.ld
subsys/nrf_security/src/drivers/cracen/psa_driver.Kconfig

Support for keys that are embedded into FW.

cracen: Platform keys support

---

subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c
subsys/net/lib/nrf_cloud/include/nrf_cloud_download.h
subsys/net/lib/nrf_cloud/src/nrf_cloud_download.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_fota_poll.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps_utils.c

Use the offset parameter when resuming a CoAP download. 
IRIS-9337

net: lib: nrf_cloud: coap dowload resume with offset

---

applications/serial_lte_modem/Kconfig
applications/serial_lte_modem/src/slm_ppp.c
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

See release notes/the Kconfig option's help.

applications: serial_lte_modem: add CONFIG_SLM_PPP_FALLBACK_MTU

---

subsys/bluetooth/controller/bt_ctlr_used_resources.h

Free DPPI channel 12 in DPPIC020 and DPPIC10

bluetooth: controller: free DPPI 12 on 54L & 54H

---

subsys/net/lib/download_client/src/http.c

When parsing http header, download_client checks whole http packet for header data, limit to checking http header area only.

subsys: download_client: Fix bug in header parser

---

west.yml

manifest: Oberon core update

---

subsys/nrf_security/cmake/psa_crypto_config.cmake
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c
subsys/nrf_security/src/psa_crypto_driver_wrappers.c

Fixes issues caused by wrong size being required.

cracen: Fix for SICR platform keys

---

lib/lte_link_control/lte_lc.c
lib/lte_link_control/lte_lc_helpers.c
tests/lib/lte_lc_api/src/lte_lc_api_test.c

Cleaning up the code related to lte_lc_periodic_search_get() to make it easier to test. Added few tests to cover periodic search functions with 100% branch coverage.

lib: lte_link_control: Periodic search clean up

---

applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.h
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c

Reset buffer allocate counter in stream start callback. Fix buffer allocate counter reference issue.
OCT-3096

applications: nrf5340_audio: fix ISO allocated issue

---

samples/crypto/aes_cbc/sample.yaml
samples/crypto/aes_ccm/sample.yaml
samples/crypto/aes_ctr/sample.yaml
samples/crypto/aes_gcm/sample.yaml
samples/crypto/chachapoly/sample.yaml
samples/crypto/ecdh/sample.yaml
samples/crypto/ecdsa/sample.yaml
samples/crypto/ecjpake/sample.yaml
samples/crypto/eddsa/sample.yaml
samples/crypto/hkdf/sample.yaml
samples/crypto/hmac/sample.yaml
samples/crypto/pbkdf2/sample.yaml
samples/crypto/rng/sample.yaml
samples/crypto/sha256/sample.yaml
samples/crypto/spake2p/sample.yaml

samples: crypto: extend ci tag for new configurations

---

lib/lte_link_control/lte_lc.c
lib/lte_link_control/lte_lc_helpers.c
tests/lib/lte_lc_api/src/lte_lc_api_test.c

Misc tests to increase test branch coverage.
Adding few logs here and there to log the API calls better.
Also fixing minor bug/flaw in the code so that unknown reg status and LTE mode are handled in CEREG.

lib: lte_link_control: More test coverage and some logs

---

samples/wifi/provisioning/softap/scripts/provision.py

Add --ssid and --passphrase arguments for
scripted provisioning.

samples: wifi: provisioning: softap: scripted provisioning

---

applications/peripheral_sensor_node/sample.yaml

Simple checking application with sensor attached.

applications: peripheral_sensor_node: add expected console regex

---

doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_adding_sysbuild.rst

Fixes an issue with a variable being used
NCSIDB-1326

doc: app_dev: bootloaders: sysbuild: Fix variable usage

---

applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c

OCT-3113
Fixed minor Coverity include issue

Applications: nrf5340_audio: Minor Coverity fix

---

doc/nrf/libraries/bluetooth_services/rpc.rst

Update the bt_rpc doc with sysbuild options.
Promote the ipc_radio application.
Jira: NCSDK-28519

doc: Update the bt_rpc doc with sysbuild

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/net/nrf_cloud_coap.h
subsys/net/lib/nrf_cloud/coap/src/coap_codec.c
subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c
subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c

Update handling of CoAP GET and FETCH operations to ensure proper return values and data.
NCSIDB-1324

net: lib: nrf_cloud_coap: update coap get and fetch handing 

---

applications/nrf_desktop/description.rst
applications/nrf_desktop/doc/usb_state.rst
applications/nrf_desktop/src/modules/Kconfig.usb_state
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Change introduces documentation for USB SOF integration.
Jira: NCSDK-28688

applications: nrf_desktop: Document USB SOF

---

tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_boot_mode.c
tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_recovery_boot_mode.c
tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_recovery_update_mode.c
tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_update_mode.c
tests/subsys/suit/orchestrator/orchestrator_sdfw_nrf54h20/testcase.yaml

Remove duplicates in SUIT test cases.
Ref: NCSDK-28580

tests: suit: Remove test case name duplicates

---

subsys/nrf_security/include/psa/nrf_platform_key_ids.h

Copy of key id header file from internal docs.

nrf_security: Add haltium key id definitions

---

tests/subsys/suit/cache_sink/src/main.c

tests: suit: Defect fix in cache_sink tests

---

lib/lte_link_control/lte_lc.c
tests/lib/lte_lc_api/src/lte_lc_api_test.c

Manually search for correct number of commas has been used for XMONITOR parsing. Changing this to use at_parser.
This also saves a little more than 100 bytes of flash with logging enabled.

lib: lte_link_control: Change XMONITOR parsing to use at_parser

---

doc/_utils/redirects.py

The changes are intended to get rid of the intermediate pages in Zoomin

doc: Fixes to the redirects.py

---

subsys/net/lib/nrf_cloud/include/nrf_cloud_download.h
subsys/net/lib/nrf_cloud/src/nrf_cloud_download.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_fota_poll.c

Add function to cancel an active download.
IRIS-9565

net: lib: nrf_cloud: add nrf_cloud_download_cancel()

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/cellular/nrf_cloud_multi_service/src/shadow_config.c
subsys/net/lib/nrf_cloud/include/nrf_cloud_codec_internal.h
subsys/net/lib/nrf_cloud/include/nrf_cloud_transport.h
subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_fsm.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c

Use nRF Cloud's new custom shadow topics instead of the generic $aws topics.
IRIS-8718

net: lib: nrf_cloud: use custom shadow topics

---

samples/nrf_rpc/protocols_serialization/client/src/ot_shell.c
subsys/net/openthread/rpc/client/CMakeLists.txt
subsys/net/openthread/rpc/client/ot_rpc_message_client.c
subsys/net/openthread/rpc/client/ot_rpc_udp_client.c
subsys/net/openthread/rpc/common/ot_rpc_common.c
subsys/net/openthread/rpc/common/ot_rpc_common.h
subsys/net/openthread/rpc/common/ot_rpc_ids.h
subsys/net/openthread/rpc/common/ot_rpc_types.h
subsys/net/openthread/rpc/server/CMakeLists.txt
subsys/net/openthread/rpc/server/ot_rpc_message_server.c
subsys/net/openthread/rpc/server/ot_rpc_message_server.h
subsys/net/openthread/rpc/server/ot_rpc_udp_server.c

List of APIs added:
- otUdpOpen
- otUdpClose
- otUdpBind
- otUdpConnect
- otUdpSend

nrf_rpc: Add OT udp api to nRF RPC.

---

west.yml

Regular OpenThread update to \`d60aaab\`
test_thread: PR-1209

manifest: openthread: update to \`d60aaab\`

---

doc/nrf/app_dev/create_application.rst
doc/nrf/links.txt

Added more information about repository apps and link to the extension documentation. VSC-2644.

doc: create_application: updates for repo app

---

doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs1.rst

Updated the 2_7_99-cs1 migration guide.

doc: 2_7_99-cs1 migration guide update

---

applications/nrf_desktop/src/modules/Kconfig.dvfs
applications/nrf_desktop/src/modules/Kconfig.dvfs_state_template
applications/nrf_desktop/src/modules/dvfs.c

Add nrf_desktop DVFS module kconfig template for choosing state default frequency and timeout.
JIRA: NCSDK-27381

applications: nrf_desktop: Add DVFS module kconfig template

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c

Allows key access for local domains in some life cycle states.

cracen: Update platform key access checks for LCS

---

applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c

Create CIG after read the PACS from the first connected unicast server.
OCT-3108

applications: nrf5340_audio: create CIG after read PACS

---

west.yml

Various UART fixes for nRF54L with TF-M

manifest: Bring TF-M with UART fixes

---

doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs1.rst

Updated cs1 migration guide.
Updated 54H getting started.

doc: updated 54H cs1 migration guide and gs.

---

lib/lte_link_control/lte_lc_helpers.c

Add plmn_param_string_to_mcc_mnc() function to parse PLMN string into MCC and MNC.
The same code used to be in two places and there will be new functionality where this is also used.

lib: lte_link_control: Add PLMN parsing function

---

west.yml

Regular OpenThread update to \`db63932\`

manifest: openthread: update to \`db63932\`

---

samples/bluetooth/direct_test_mode/boards/nrf54l15dk_nrf54l15_cpuapp.conf
samples/bluetooth/direct_test_mode/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
samples/bluetooth/direct_test_mode/sample.yaml
samples/bluetooth/direct_test_mode/src/dtm.c
samples/peripheral/radio_test/boards/nrf54l15dk_nrf54l15_cpuapp.conf
samples/peripheral/radio_test/sample.yaml
samples/peripheral/radio_test/src/main.c

Adds support for nRF54L15DK in DTM and Radio Test samples.

DTM, Radio Test: Add support for nRF54L15DK

---

samples/esb/esb_prx/sample.yaml
samples/esb/esb_prx/src/main.c
samples/esb/esb_ptx/src/main.c

Adds support for nRF54L15DK in ESB.

esb: Add support for nRF54L15DK

---

samples/bluetooth/mesh/light_switch/README.rst

Changed the tab heading to nRF54 DKs

doc: tab fix for mesh light switch sample

---

doc/nrf/app_dev/device_guides/nrf91/nrf91_features.rst
doc/nrf/app_dev/device_guides/nrf91/thingy91_updating_fw_programmer.rst
doc/nrf/libraries/bin/lwm2m_carrier/CHANGELOG.rst
doc/nrf/libraries/bin/lwm2m_carrier/certification.rst
doc/nrf/libraries/bin/lwm2m_carrier/index.rst
doc/nrf/libraries/networking/nrf_cloud_coap.rst
doc/nrf/links.txt

Add nRF9151 comp matrix ref links

doc: Add nRF9151 comp matrix ref links

---

west.yml

Regular OpenThread update to \`2aeb8b8\`

manifest: openthread: update to \`2aeb8b8\`

---

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_custom_pcb.rst
doc/nrf/links.txt

Updated the 54H custom pcb guide

doc: 54H custom pcb guide update

---

doc/nrf/libraries/dfu/suit_dfu.rst
doc/nrf/links.txt
include/dfu/suit_dfu.h
include/dfu/suit_dfu_fetch_source.h
include/sdfw/sdfw_services/suit_service.h

Add documentation for SUIT DFU API.
Ref: NCSDK-28303

doc: Add SUIT DFU API group

---

samples/cellular/gnss/src/main.c

Changed the time to fix to be printed with more precision in TTFF test mode.
Added printing of new PVT values.
Added indication for scheduled navigation data download.

samples: cellular: gnss: Improve sample output

---

west.yml

Update the manifest file with NCS v2.6.2 tagged repositories.

manifest: NCS 2.6.2

---

subsys/mgmt/suitfu/Kconfig
subsys/mgmt/suitfu/src/suitfu_mgmt_img.c

Extension of SMP image management group for SUIT. Now it is possible to upload DFU cache raw image DFU cache partition.
Ref: NCSDK-29122
test-sdk-nrf: sdk-nrf-pr-17287

mgmt: Extension of SUIT-Firmware-Update service

---

doc/_zoomin/ncs.tags.yml

* Update the tag file with respect to the
top level structural changes
* Added tags for nRF9131.
* Added tags for nRF9151

doc: update tag file with respect to structure changes

---

samples/wifi/thread_coex/README.rst

Minor edits to suit the latest documentation style.

samples: wifi: thread_coex: Readme update

---

scripts/docker/Dockerfile

Update nrfutil device to version 2.5
Update JLink version to v794i

docker: Update nrfutil device and JLink

---

doc/nrf/releases_and_maturity.rst
doc/nrf/releases_and_maturity/abi_compatibility.rst

Added ABI compatibility doc page.

doc: Added ABI compatibility doc page

---

samples/bluetooth/broadcast_config_tool/sample.yaml

Add sample.yaml for broadcast configuration tool sample.
OCT-NONE

samples: broadcast_config_tool: Add sample.yaml

---

doc/nrf/app_dev/device_guides/nrf54h.rst
doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_custom_pcb.rst
doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst
doc/nrf/links.txt
doc/nrf/releases_and_maturity/abi_compatibility.rst
doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs2.rst

doc: Updated documentation for CS2 release
Updated 54H custom pcb guide.
Updated links.txt
Updated 54H gs guide.
Added CS2 migration notes.

    doc: Updated documentation for CS2 release

---

subsys/net/openthread/rpc/client/ot_rpc_udp.c
tests/mocks/nrf_rpc/mock_nrf_rpc_transport.c
tests/subsys/net/openthread/rpc/client/src/udp_suite.c
tests/subsys/net/openthread/rpc/common/test_rpc_env.h

Commit adds OT RPC unit tests for UDP client part.

nrf_rpc: adding OT rpc udp client tests.

---

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_logging.rst

doc: small documentation edits pre-CS2

---

cmake/sysbuild/partition_manager.cmake

Adds a warning when a static PM file has been updated and project has not been reconfigured with a pristine build as this may cause the configuration of pre-configured images to be stale and wrong

cmake: sysbuild: partition_manager: Add warning for stale file

---

applications/nrf5340_audio/broadcast_source/main.c
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.h
samples/bluetooth/broadcast_config_tool/README.rst
samples/bluetooth/broadcast_config_tool/src/main.c

- Add command for setting a fixed broadcast_ID
- OCT-3139

samples: broadcast_config_tool: Add option for broadcast_ID

---

west.yml

manifest: Bring in support for SHA512 in MCUboot

---

doc/CMakeLists.txt
doc/nrf/dev_model_and_contributions/documentation/build.rst
doc/requirements.txt

https://github.com/user-attachments/assets/c6e0c2a8-e3d4-4c59-9011-9f592543adbb

doc: add support for hot reloading

---

cmake/sysbuild/suit.cmake
cmake/sysbuild/suit_utilities.cmake
config/suit/templates/nrf54h20/default/v1/app_recovery_envelope.yaml.jinja2
config/suit/templates/nrf54h20/default/v1/rad_recovery_envelope.yaml.jinja2
samples/suit/recovery/prj.conf
samples/suit/recovery/sysbuild/hci_ipc.conf
west.yml

This commit introduces changes allowing for an automatic creation of a separate .zip file for DFU when buildin an application together with a SUIT recovery application.

suit: Creation of separate .zip file for recovery application

---

west.yml

Fix failing ED25519 TinyCrypt configuration

manifest: Fix MCUboot TinyCrypt broken ED25519

---

doc/nrfxlib/nrfxlib.doxyfile.in
west.yml

- Fix all issues found in Doxygen
- Fix issues in Doxyfile (incorrect MDFILE setting)
- Introduce __DOXYGEN__ to allow including conditional regions in headers.

doc: nrfxlib: fix/improve Doxygen

---

west.yml

tag sdk-openthread with ncs-thread-reference-20241002 tag

manifest: openthread: tag OpenThread

---

west.yml

manifest: Update MCUboot with fixups for ED25519

---

west.yml

Update revision of sdk-nrf-802154 in west.yml manifest file

manifest: sdk-nrf-802154: Update revision of nrf-802154

---

samples/bluetooth/broadcast_config_tool/src/main.c

- Add check to see if BIG is streaming before starting
- OCT-3148

samples: broadcast_config_tool: Only start pending broadcasters

---

west.yml

Update sdk-find-my revision to pull fix for Kconfig typo.

manifest: Update sdk-find-my revision

---

samples/sdfw/ssf_client/boards/nrf9280pdk_nrf9280_cpuapp.conf
samples/sdfw/ssf_client/boards/nrf9280pdk_nrf9280_cpuapp.overlay
samples/sdfw/ssf_client/boards/nrf9280pdk_nrf9280_cpurad.conf
samples/sdfw/ssf_client/boards/nrf9280pdk_nrf9280_cpurad.overlay
samples/sdfw/ssf_client/sample.yaml
subsys/sdfw_services/Kconfig

sdfw_services: Add support for nRF92

---

doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_mcuboot_nsib.rst
doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_partitioning.rst
doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_quick_start.rst

fixed acronym and an obsolete reference.

doc: bootloader small fix

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/net/nrf_cloud.h
include/net/nrf_cloud_codec.h
include/net/nrf_cloud_defs.h
subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_mqtt
subsys/net/lib/nrf_cloud/include/nrf_cloud_codec_internal.h
subsys/net/lib/nrf_cloud/include/nrf_cloud_transport.h
subsys/net/lib/nrf_cloud/src/nrf_cloud.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_fsm.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c

Support shadow transform (JSONata) requests over MQTT and REST.
IRIS-8721 IRIS-9188

net: lib: nrf_cloud: add support for mqtt shadow transform requests

---

applications/serial_lte_modem/Kconfig
applications/serial_lte_modem/src/slm_cmux.c
applications/serial_lte_modem/src/slm_ppp.c

Fixes to CMUX and PPP after upmerge.
---
@tomi-font: Turned out to be rather straightforward after all.

applications: serial_lte_modem: Fix CMUX and PPP

---

lib/sms/sms.c

Received message and status reports have been first scheduled to queue before the acknowledgement of the message with `AT+CNMA=1`. The order is changed because acknowledgement to network is more important and can be delayed if application does too many things in the callback, which it shouldn't do anyway.
Jira: NCSDK-29532

lib: sms: ACK before APP callback

---

doc/nrf/releases_and_maturity/known_issues.rst

Add DRGN-23511 and remove the statement that say that issues in "Bluetooth LE" are controller specific.

doc: known issues: add Bluetooth LE entry

---

.github/workflows/src-mirror.yml

Change compression type for ncs package from 7z to tar

CI:Change compression method in workflow

---

samples/peripheral/radio_test/src/radio_test.c

Aligned radio configurations for Ieee802154_250Kbit mode for the nRF54L series.

samples: radio_test: Align Radio configuration for 802.15.4 mode

---

samples/cellular/nrf_cloud_multi_service/Kconfig.sysbuild
samples/cellular/nrf_cloud_multi_service/README.rst
samples/cellular/nrf_cloud_multi_service/boards/thingy91x_nrf9151_ns.overlay
samples/cellular/nrf_cloud_multi_service/sample.yaml

Fix various minor issues with THingy91x that seem to have originated from the recent upmerge.
Fixes IRIS-9781

samples: mss: Thingy91x fixes

---

doc/nrf/releases_and_maturity/known_issues.rst

Added KRKNWK-19263 as a known issue.

doc: known issues: Add KRKNWK-19263 related to Zigbee FOTA bug on nRF53

---

scripts/west_commands/sbom/input_build.py
scripts/west_commands/sbom/scancode_toolkit_detector.py

Get licenses from the new place.

scripts: sbom: Fix directory interface change in scancode

---

samples/bluetooth/central_hids/src/main.c
samples/bluetooth/peripheral_gatt_dm/src/main.c
samples/bluetooth/peripheral_hids_keyboard/src/main.c
samples/bluetooth/peripheral_hids_mouse/src/main.c
samples/bluetooth/peripheral_uart/src/main.c
samples/bluetooth/throughput/src/main.c

Updated the button configurations to align with the latest PDK and DK revisions for the nRF54.

samples: bluetooth: Update Button numbering

---

doc/nrf/app_dev/create_application.rst
doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst
doc/nrf/installation/install_ncs.rst
doc/nrf/shortcuts.txt

Updated the note about Toolchain Manager.
Applied minor fixes to different areas.
NCSDK-29557.

doc: install: update TM note plus minor fixes

---

subsys/nrf_rpc/nrf_rpc_uart.c

Commit adds protection against receiving the same frame twice due to missed ack on the previous try that triggered reliability functionality.

nrf_rpc: add protection against frame duplication

---

include/modem/modem_jwt.h
include/net/nrf_cloud.h
include/net/nrf_cloud_coap.h
include/net/nrf_cloud_location.h

Improve documentation in header comments.

Misc doc updates

---

cmake/sysbuild/suit.cmake
config/suit/templates/nrf54h20/matter/v1/app_envelope.yaml.jinja2
config/suit/templates/nrf54h20/matter/v1/rad_envelope.yaml.jinja2
tests/subsys/dfu/dfu_target/suit/regenerate_manifests.sh

Fix Matter SUIT manifest templates.
SUIT: Minor fix for cmake and tests.

samples: matter: Fix Matter SUIT manifest templates

---

samples/bluetooth/direct_test_mode/src/dtm.c
samples/bluetooth/direct_test_mode/src/dtm_hw.c
samples/peripheral/radio_test/src/radio_cmd.c
samples/peripheral/radio_test/src/radio_test.c
subsys/esb/esb.c

Adjusted the radio transmit power levels with nrfx-3.7.0 release.

Radio samples: Align Radio TX power levels

---

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_custom_pcb.rst
doc/nrf/links.txt
doc/nrf/releases_and_maturity/abi_compatibility.rst
doc/nrf/releases_and_maturity/migration/2.4.99-cs3_to_2.6.99-cs2/migration_guide_2.4.99-cs3_to_2.6.99-cs2_environment.rst
doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7.rst
doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs1.rst
doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs2.rst
doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/migration_guide_2.4.99-cs3_to_2.7_application.rst
doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/migration_guide_2.6.99-cs2_to_2.7_application.rst
doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/migration_guide_2.6.99-cs2_to_2_7_environment.rst
doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/transition_guide_2.4.99-cs3_to_2.7_environment.rst

Miscellaneous doc updates and fixes.

doc: Miscellaneous doc updates

---

.github/workflows/west-commands.yml

Adding a bit more tests for ncs west commands.

ci: add ncs west command testing

---

doc/nrf/protocols/wifi/station_mode/images/nRF70_ug_twt_wake_interval.svg

Updated twt wake interval image.

doc: wifi: update wake interval image

---

samples/bluetooth/direct_test_mode/src/dtm.c
samples/peripheral/radio_test/src/main.c
subsys/esb/esb.c

Add HMPAN-102 workaround for:
-ESB
-DTM sample
-radio_test sample
Jira: NCSDK-29392

esb: samples: Add HMPAN-102 workaround to ESB and samples

---

samples/pmic/native/npm1300_fuel_gauge/README.rst
samples/pmic/native/npm1300_one_button/README.rst

Add note in sample readme regarding using of nRF54L15-DK LED1 pin.

samples: pmic: npm1300: Add pin assignment note

---

subsys/suit/envelope_info/include/suit_envelope_info.h
subsys/suit/envelope_info/src/suit_envelope_info.c
subsys/suit/orchestrator_app/Kconfig
subsys/suit/orchestrator_app/src/suit_orchestrator_app.c

Cleanup on DFU and DFU cache partitions as part of SUIT initialization

suit: Cleanup on DFU partitions

---

applications/nrf_desktop/sample.yaml

Update name and description to support meaningful lookup.

applications: nrf_desktop: Update name and description

---

drivers/gpio/Kconfig
drivers/gpio/gpio_nrfe.c
dts/bindings/gpio/nordic,nrfe-gpio.yaml
snippets/emulated-gpio/icmsg/emulated-gpio.overlay
snippets/emulated-gpio/mbox/emulated-gpio.overlay

nrf-egpio to nrfe-gpio naming cleanup.

drivers: gpio: eGpio naming cleanup

---

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_architecture.rst
doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_architecture_reset.rst
doc/nrf/links.txt

Added 54H nrfutil reset kinds documentation.

doc: 54H nrfutil reset kinds documentation

---

snippets/hw-flow-control/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
snippets/hw-flow-control/boards/nrf54l15dk_nrf54l15_cpuapp.overlay

Needed to receive all data from DK.

snippets: hw-flow-control: configure nrf54*

---

doc/nrf/libraries/networking/nrf_cloud.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/net/nrf_cloud.h
include/net/nrf_cloud_fota_poll.h
subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_fota
subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_download.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_fota.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_fota_common.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_fota_poll.c

Enable SMP FOTA capability for CoAP and REST protocols. 
IRIS-9481

net: lib: nrf_cloud: add smp fota for coap and rest

---

tests/benchmarks/multicore/idle_outside_of_main/testcase.yaml

Test function specific for this code.

tests: benchmarks: multicore: idle_outside_of_main: adjust test fun

---

tests/benchmarks/current_consumption/system_off/CMakeLists.txt
tests/benchmarks/current_consumption/system_off/boards/nrf54l15dk_nrf54l15_cpuapp_ret_mem.overlay
tests/benchmarks/current_consumption/system_off/testcase.yaml

Add tests combining system off and  memory retention with current consumption checking.

tests: benchmarks: Add sysoff with mem retention test.
