nrfconnect/sdk-nrf

modules/hostap/src/supp_events.c
Make sure to copy LEN -1 bytes to the destination, to accommodate the terminating null byte.
=> modules: hostap: Resolve build warning with strncpy

applications/nrf5340_audio/unicast_server/main.c
- uuid_buf has to be static for the adv data to be correct
- OCT-NONE
=> applications: nrf5340_audio: Change uuid_buf to static

scripts/bluetooth/mesh/mesh_dfu_metadata.py
This fixes in particular parsing such Kconfig option: CONFIG_MODEM_ANTENNA_AT_MAGPIO="AT%XMAGPIO=1,0,0,1,1,1574,1577"
=> Bluetooth: Mesh: Fix parsing Kconfig with multiple equals signs

scripts/ncs-toolchain-version-minimum.txt
'2.6.20240304' is pointer to 'v2.6.0-rc2' in toolchain-manager index. 
This is required by [CMAKE_VERSION](https://cmake.org/cmake/help/latest/variable/CMAKE_VERSION.html)
=> scripts: Update minimum required toolchain for the v2.6.0 release

samples/bluetooth/peripheral_uart/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/bluetooth/peripheral_uart/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/bluetooth/peripheral_uart/sample.yaml, samples/bluetooth/peripheral_uart/src/main.c
Add support to bt peripheral uart sample for 54l15
Signed-off-by: Pierce Lowe <pierce.lowe@nordicsemi.no>
=> samples: bluetooth: peripheral_uart: add support for 54l15

drivers/wifi/nrf700x/Kconfig
[SHEL-2587] Updating frame dependent edge backoffs comments
[SHEL-2587]: https://nordicsemi.atlassian.net/browse/SHEL-2587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> drivers: wifi: Correct frame dependent edge backoffs comment

west.yml
Bring in commit to support EAD in the BT shell.
=> manifest: sdk-zephyr: EAD support in BT shell

applications/nrf_desktop/board_configuration.rst, applications/nrf_desktop/description.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
PR adds documentation for nRF54L PDK support in nRF Desktop.
Jira: NCSDK-26216
=> applications: nrf_desktop: Add support for nRF54L PDK (documentation)

applications/matter_bridge/src/ble_providers/ble_lbs_data_provider.cpp, applications/matter_bridge/src/bridged_device_types/humidity_sensor.h, applications/matter_bridge/src/bridged_device_types/onoff_light.cpp, applications/matter_bridge/src/bridged_device_types/onoff_light.h, applications/matter_bridge/src/bridged_device_types/onoff_light_switch.h, applications/matter_bridge/src/bridged_device_types/temperature_sensor.h, applications/matter_bridge/src/simulated_providers/simulated_generic_switch_data_provider.cpp, applications/matter_bridge/src/simulated_providers/simulated_onoff_light_data_provider.cpp, applications/matter_bridge/src/simulated_providers/simulated_onoff_light_switch_data_provider.cpp, samples/matter/common/src/bridge/bridge_manager.cpp, samples/matter/common/src/bridge/bridged_device_data_provider.h
* Added read/write support for missing OnOff cluster attributes to conform with the spec
* Slightly refactored constants in bridge device classes
* Fixed the case when an attribute update is not supported on the provider side
=> applications: Matter Bridge: add support for missing OnOff attributes

drivers/wifi/nrf700x/CMakeLists.txt, scripts/quarantine_windows_mac.yaml
Using single quotes causes issues while building samples on Windows.
=> wifi: Fix SyntaxError on Windows

applications/nrf5340_audio/src/audio/audio_system.c
- OCT-2951
- Only enable LC3 encoder if bitrate is set
- Only enable LC3 decoder if decoder sample rate is set
=> applications: nrf5340_audio: Only enable encoder and decoder when used

applications/nrf_desktop/doc/wheel.rst, applications/nrf_desktop/src/hw_interface/wheel.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change adds DT alias that allows to configure QDEC instance used in wheel application module. This is needed to use the module for platforms that support multiple QDEC instances and do not provide "qdec" DT label.
Jira: NCSDK-26468
=> applications: nrf_desktop: Add DT alias to configure QDEC in wheel

scripts/quarantine_integration.yaml
For:
nrf/tests/subsys/dfu/dfu_target/mcuboot
nrf/tests/modules/mcuboot/direct_xip
nrf/samples/nrf_profiler
nrf/tests/subsys/bluetooth/fast_pair/storage/factory_reset nrf/tests/subsys/bluetooth/fast_pair/storage/account_key_storage nrf/tests/subsys/bluetooth/fast_pair/crypto
nrf/tests/subsys/nrf_profiler
nrf/applications/nrf_desktop/nrf/applications/nrf_desktop find-my/samples/coexistence
find-my/samples/qualification
find-my/samples/simple
find-my/applications/thingy
=> scripts: add integration quarantine part 2

applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/Kconfig, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
OCT-2723
Set the default SIRK and test this against the SIRK to be used. A warning will be logged if these are the same.
=> applications: nrf5340_audio: We should improve how the SIRK is set

samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
[SHEL-2606] Add RU Tone and RU Index in show config, correct RX_BB display. Remove Experimental tag and add description.
[SHEL-2606]: https://nordicsemi.atlassian.net/browse/SHEL-2606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> samples: wifi: radio_test: Add show config options & command description

applications/serial_lte_modem/boards/nrf9131ek_nrf9131_ns.conf, applications/serial_lte_modem/boards/nrf9131ek_nrf9131_ns.overlay, applications/serial_lte_modem/sample.yaml
Add the overlay files to support nRF9131 EK.
NOTE UART_2 cannot be used as I2C_2 is in use on the EK.
=> application: serial_lte_modem: Support nRF9131 EK

doc/nrf/device_guides/working_with_nrf/nrf70/gs.rst, doc/nrf/links.txt
Added link to the precompiled version of the
scan sample in the Getting started with nRF7002 DK UG.
NCSDK-25710
=> doc: wifi: Adding link to precompiled scan sample

samples/bluetooth/mesh/dfu/common/src/dfu_target.c
This fixes an incorrect comparison of minor and revision parts of the version number when checking if the incoming firmware is newer than the current in the DFU target implementation for the Mesh samples.
=> Samples: Bluetooth: Mesh: Fix dfu target version comparison

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/chat/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/bluetooth/mesh/chat/sample.yaml
Add support of nrf54l15pdk_nrf54l15_cpuapp in mesh Chat sample.
=> samples: Bluetooth: Mesh: add nrf54l support for Chat sample

lib/fatal_error/fatal_error.c
The fatal_error.c file is compiled only if CONFIG_RESET_ON_FATAL_ERROR is enabled. The removed check is not needed.
=> lib: fatal_error: Remove dead code

drivers/wifi/nrf700x/CMakeLists.txt, drivers/wifi/nrf700x/Kconfig, drivers/wifi/nrf700x/inc/wifi_mgmt.h, drivers/wifi/nrf700x/src/fmac_main.c, drivers/wifi/nrf700x/src/wifi_mgmt.c, west.yml
Use separate patch file for System + Raw modes
=> wifi: Flash size optimizations

samples/matter/lock/sample.yaml
This commit adds config enabling smp dfu on thread wifi swithed lock sample.
=> samples: matter: SMP DFU added to thread wi-fi switched lock sample

boards/arm/thingy91x_nrf5340/nrf5340_cpunet_reset.c
This patch updates the reset of the nRF5340 CPU net to use the nrfx driver. This is done to ensure that the
necessary workarounds are applied.
=> boards: thingy91x_nrf5340: Update reset of nRF5340 CPU net

west.yml
When there is a wrong password for AP, the
send_wifi_mgmt_conn_event is missing for WRONG_KEY.
[SHEL-2627] https://nordicsemi.atlassian.net/browse/SHEL-2627
[SHEL-2627]: https://nordicsemi.atlassian.net/browse/SHEL-2627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> manifest: Add connection event for wrong key

applications/matter_bridge/doc/matter_bridge_description.rst, applications/matter_bridge/overlay-bt_max_connections_app.conf, applications/matter_bridge/src/bridge_shell.cpp, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/common/src/bridge/Kconfig, samples/matter/common/src/bridge/ble_connectivity_manager.cpp, samples/matter/common/src/bridge/ble_connectivity_manager.h
We need to ensure that the BLE provider doesn't exist on the recovery list to avoid putting it there once again.
=> applications: matter: Avoid provider duplicates on the recovery list

samples/cellular/modem_shell/src/ping/icmp_ping.c, samples/cellular/modem_shell/src/ping/icmp_ping.h
Re-reading PDN ctx info if receiving new reg status home/roaming indication during pinging.
DUT couldn't send ping are crossing border from Sweden to Denmark. DUT IP address was changing when running ping but mosh ping set source and destination IP just once, at the beginning of the sequence. Now, src/dst are set if receiving new reg status indication from lte_lc. 
Jira: MOSH-526, MOSH-547
=> samples: cellular: modem_shell: ping: cross-border fix

samples/cellular/modem_shell/src/link/link_shell_pdn.c, samples/cellular/modem_shell/src/ppp/ppp_ctrl.c
Following fixes to mosh PPP functionality:
- Consecutive `ppp down` and _ppp up_ again wasn't working always correctly. Will work even better when Zephyr PR is included in ncs: https://github.com/zephyrproject-rtos/zephyr/pull/67731
With that also PC side notices `ppp down`.
- mosh ppp side is notified about the PDN detach.
=> samples: cellular: modem_shell: ppp: fixes

subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c
As explained in https://nordicsemi.atlassian.net/browse/NCSDK-26534
Cancelling the FOTA process is now broken.
Two issues found:
1. Empty string might be `"\0"` which is not same as zero length data. This should be handled similarly.
2. LwM2M FOTA utils wrote 16bit value using `sizeof(int)` which caused value to wrap over on certain cases.
=> lwm2m: Fix FOTA cancellation issues

doc/nrf/releases_and_maturity/known_issues.rst
The issue DRGN-21619 has a simple workaround.
=> doc: Add known issue for CIS Peripheral upon central reset

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/app_event_manager/Kconfig, subsys/app_event_manager/app_event_manager.c
Change improves out of memory error handling for default application event allocator. The CONFIG_APP_EVENT_MANAGER_REBOOT_ON_EVENT_ALLOC_FAIL Kconfig option was introduced to allow user to select between system reboot or kernel panic.
=> app_event_manager: Improve OOM error handling

doc/nrf/libraries/networking/nrf_provisioning.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_provisioning.h, subsys/net/lib/nrf_provisioning/src/nrf_provisioning.c, subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c, subsys/net/lib/nrf_provisioning/src/nrf_provisioning_shell.c
Add new API and shell command to set provisioning interval.
Change DTLS CID from enabled to supported .
Update documentation and change log.
=> net: nrf_provisioning: Add new API to set provisioning interval 

modules/hostap/src/supp_api.c
If user selects a band, then we should restrict scanning channels to that band, but using freq_list will only filter the results.
Fixes SHEL-2626.
=> modules: hostap: Fix band selection

west.yml
This allows to seek only for the SSID of interest and avoid
multiple scan result callbacks in the application.
=> manifest: Matter directed scaning with single scan

subsys/mpsl/init/mpsl_init.c
The GRTC-specific one has been removed
=> mpsl: Use `NRFX_CONFIG_MASK_DT`

applications/machine_learning/src/modules/ml_runner.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change updates ML runner application module to allow running ML model without anomaly support.
Jira: NCSDK-25938
=> applications: machine_learning: Allow running ML model with no anomaly

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/bluetooth/mesh/light_switch/overlay-lpn.conf, samples/bluetooth/mesh/light_switch/sample.yaml
This PR adds support for nRF54L15 in Light Switch sample. It also disables `CONFIG_CONSOLE` and `CONFIG_LOG` in `overlay-lpn.conf` as they aren't needed in that configuration and cause build warning and issues on nRF54L15.
=> samples: bluetooth: mesh: Add nRF54L15 support to Light Switch

drivers/mpsl/flash_sync/Kconfig
Made MPSL based synchronization mechanism available for nRF54L15 too.
=> drivers/mpsl/flash_synch: MPSL choice for nRF54L15

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud_coap.h, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
Use the state/desired resource to modify the desired section of the shadow. This is usually used to reject a shadow delta value that the application cannot
accept.
Jira: IRIS-8338
=> net: lib: nrf_cloud: CoAP invalid delta rejection

samples/net/coap_client/src/main.c
Supplicant now enables POSIX_API. So we need to include the relevant header files.
=> samples: coap_client: Fix compile error for nrf7002dk

scripts/quarantine_integration.yaml
For:
nrf/samples/cellular/nrf_cloud_multi_service
nrf/samples/cellular/nrf_cloud_rest_device_message nrf/samples/cellular/nrf_cloud_rest_cell_location
nrf/samples/cellular/nrf_cloud_rest_fota
=> scripts: add integration quarantine part 3

lib/location/method_cloud_location.c
Semaphore wifi_scan_ready has been reserved from the stack. This doesn't sound good when it's used from different threads. Moving it to static RAM.
Jira: NCSDK-26707
=> lib: location: Make wifi_scan_ready semaphore to static

subsys/nrf_rpc/nrf_rpc_os.c
__CLZ is a CMSIS marco and may not always be available in all build configurations, for example when building a minimal configuration with nrf_rpc enabled.
Use Zephyr's u32_count_leading_zeros instead.
=> nrf_rpc: use u32_count_leading_zeros instead of __CLZ

applications/serial_lte_modem/src/ftp_c/slm_at_tftp.c, applications/serial_lte_modem/src/http_c/slm_at_httpc.c, applications/serial_lte_modem/src/mqtt_c/slm_at_mqtt.c, applications/serial_lte_modem/src/slm_at_socket.c, applications/serial_lte_modem/src/slm_at_tcp_proxy.c, applications/serial_lte_modem/src/slm_at_udp_proxy.c, applications/serial_lte_modem/src/slm_util.c, applications/serial_lte_modem/src/slm_util.h
Don't pass log instances around.
=> application: serial_lte_modem: fix compilation with CONFIG_LOG=n

samples/wifi/raw_tx_packet/Kconfig, samples/wifi/raw_tx_packet/src/wifi_connection.c
Implement semaphore to wait for DHCP completion after connection, fixing raw packet transmission issue.
Fixes SHEL-2598.
=> samples: wifi: raw_tx_packet: Fix raw packet transmission issue

subsys/net/lib/download_client/src/download_client.c
Change log level for failure to resolve hostname
on a specific ip familiy, from warning to debug.
This is quite typical for services to not support
a specific family. AWS S3 for instance doesnt support IPv6.
=> net: lib: download_client: Change log level

west.yml
Update upstream SHA for sdk-connectedhomeip project to be able to get a correct list of downstream patches with `west ncs-loot matter` command.
=> manifest: update upstream SHA for Matter

doc/nrf/protocols/matter/overview/dev_model.rst
The Release date column of the Matter versions table could be read as meaning the release date for support in the NCS. This makes the column clearer, and adds another column that specifies the version of the NCS that added support for the given Matter specification version.
=> doc: Matter: improve Matter versions table

subsys/net/lib/nrf_cloud/src/nrf_cloud_agnss.c
If A-GNSS data contained an invalid element count, the parser was left into invalid state and no error was logged. Because of this further parsing attempts failed. Also, the end of parsing was not detected in a successful case and the "Parsing finished" debug log was missing.
=> net: lib: nrf_cloud: Improve A-GNSS data parsing robustness

samples/bluetooth/direct_test_mode/README.rst
nRF Connect Serial Terminal does not support HEX
formatted commands. Taking out reference to it.
=> doc: terminal emulator fix in Bluetooth DTM sample

scripts/quarantine_zephyr_integration.yaml
For:
zephyr/tests/lib/cmsis_dsp
=> scripts: add integration quarantine part 4

west.yml
fix build of unit test after Zephyr upmerge
fix: compilaiton warning about strncpy
fix: warning pointed out by static analysis
=> manifest: Update Sidewalk

samples/wifi/scan/src/main.c
Scan sample doesn't need 128MHz, default CPU clock of 64MHz is good enough.
=> samples: wifi: scan: Don't use highest CPU

subsys/net/lib/nrf_cloud/CMakeLists.txt, tests/subsys/net/lib/nrf_cloud/fota_common/CMakeLists.txt
Only include nrf_cloud_fota_common.c in build when actually needed.
Jira: NCSDK-26679
=> net: lib: nrf_cloud: Improve FOTA build order

.github/workflows/src-mirror.yml
Triggered by adding tag. It packs whole repository and sends it to artifactory.
=> ci: Pack&send NSC workspace to Artifactory 

modules/hostap/CMakeLists.txt
Fix missing CONFIG in the Kconfig name.
=> modules: hostap: Fix the Kconfig name

applications/nrf5340_audio/src/audio/sw_codec_select.h
Remove the started variable from struct sw_codec_encoder as it is never used. The variable was introduced in 100db2a.
=> applications: nrf5340_audio: Remove unused codec struct member

samples/matter/common/src/board/board.cpp
Matter Network events that come from Thread or WiFi were being handled wrongly in the common board module.
When we can use Thread and WiFi on the same device there must not be elsif for choosing thread and WiFi during handling Matter Event.
=> samples: matter: Fix network events for WiFi/Thread switched

scripts/quarantine_integration.yaml
=> scripts: add integration quarantine part 5

drivers/wifi/nrf700x/Kconfig
Restrict band configuration by user, for nrf7001 and let the band configuration ``CONFIG_NRF_WIFI_2G_BAND`` derive its value from other symbols.
=> drivers: wifi: Disable band configuration for nrf7001

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/ble_peripheral_lbs_coex/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/bluetooth/mesh/ble_peripheral_lbs_coex/sample.yaml
Adds mesh BLE coex sample support for the nrf54l15 board and updates documentation.
=> samples: Bluetooth: mesh: Add nrf54l15 support in BLE coex sample

subsys/bluetooth/controller/Kconfig
Puts the SDC ECDH driver in the MPSL work queue by default, unless SMP is used.
=> bluetooth: controller: Put ECDH driver in the MPSL work queue by default

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/bluetooth/mesh/Kconfig
Make it possible to extract metadata at build time even if BT_MESH_DFU_METADATA is not enabled in the image. There is no need to have this enabled in the new firmware for it to make sense, as long as it is enable in the firmware currently running on the target. Removing the dependency allows things like removing Mesh DFU support by performing a Mesh DFU update, or changing metadata schemes by performing a DFU update.
Also remove the default y for BT_MESH_DFU_CLI. It makes no sense to enable it by default for distributor images, unless they support self-update, in which case they would also enable BT_MESH_DFU_SRV.
=> Bluetooth: Mesh: Remove unneeded dependency from metadata extraction

modules/nrfxlib/nrf_802154/sl/platform/nrf_802154_platform_sl_lptimer_grtc.c
The current implementation of the nRF 802.15.4 SL lptimer platform for GRTC-based devices might miss valid interrupts. This commit fixes that.
=> modules: nrfxlib: nrf_802154: fix missed interrupts

sysbuild/Kconfig.netcore
There is a missing entry for nrf54h20 DK that enables SUPPORT_NETCORE and sets up NETCORE_REMOTE_BOARD_NAME. That breaks the multi-core builds e.g. BLE samples for nRF54h20 DK.
=> sysbuild: Add missing RAD core to Kconfig.netcore

west.yml
The new MPSL contains the new FEM API and marks some parts as deprecated. The SDC is aligned with the new API.
=> manifest: Update nrfxlib revision with new SDC and MPSL revisions

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added changelog entry for the nRF54L15 PDK support in the Fast Pair Input Device sample.
Jira: NCSDK-26517
=> doc: releases: Add changelog for nRF54L15 PDK support in input_device

samples/cellular/http_update/modem_delta_update/boards/nrf9160dk_nrf9160_ns.conf
The modem FW image is already in server, so we should support it.
=> samples: cellular: http_update: Support 1.3.6 on nRF9160

doc/nrf/external_comp/bt_fast_pair.rst, doc/nrf/libraries/bluetooth_services/services/fast_pair.rst
Corrected the outdated Fast Pair configuration names in the documenation.
Ref: NCSDK-26591
=> treewide: doc: fast_pair: correct the outdated Kconfig names

tests/subsys/bluetooth/mesh/metadata_extraction/CMakeLists.txt, tests/subsys/bluetooth/mesh/metadata_extraction/Kconfig, tests/subsys/bluetooth/mesh/metadata_extraction/prj.conf, tests/subsys/bluetooth/mesh/metadata_extraction/src/main.c, tests/subsys/bluetooth/mesh/metadata_extraction/testcase.yaml, tests/subsys/bluetooth/mesh/metadata_extraction/verify_metadata.py
This adds build-only tests with targets with verious layouts of composition data, and runs a verification script as part of the build.
Currently tested:
- Single composition data variables
- Multiple composition data variables
- Array containing multiple composition data
=> Bluetooth: Mesh: Add test to verify metadata extraction output

samples/cellular/lwm2m_client/overlay-avsystem-bootstrap.conf, samples/cellular/lwm2m_client/overlay-avsystem.conf, subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c
FOTA object has list of supported protocols.
We assumed that when CA chain is present in certain sec_tag,
we can use HTTPS or CoAPS. This is OK.
But AVSystem uses mutual DTLS authentication on CoAPS so
the sec_tag we use, might not have CA chain at all.
So when only PSK credentials are present, claim that we
support CoAPS but not HTTPS.
AVSystem FOTA defaults to CoAPS so use same security tag where our
DTLS credentials are stored.
=> lwm2m: Fix supported protocols list for FOTA

subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/hci_driver.c
Prepares the hci driver to allocate memory for the initiator
=> bluetooth: controller: prepare hci_driver to separate scan/init mem

doc/nrf/device_guides/working_with_nrf/nrf70/gs.rst, doc/nrf/protocols/wifi/index.rst, doc/nrf/protocols/wifi/wifi.rst, doc/nrf/protocols/wifi/wifi_certification.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added Wi-Fi certification page under the Wi-Fi protocols. Moved the Wi-Fi certification section from the Overview page to the new page.
Added certification info to the nRF7002 DK gsg.
SHEL-1666
=> doc: wifi: Add Wi-Fi certification page

applications/matter_bridge/sample.yaml, samples/matter/common/src/Kconfig, samples/matter/light_bulb/sample.yaml, scripts/quarantine_integration.yaml, west.yml
Enabled NCS_SAMPLE_MATTER_SETTINGS_SHELL if CHIP_MEMORY_PROFILING is set.
Disabled SHELL_MINIMAL when the memory profiling is enabled.
=> samples: matter: Improve Matter memory profiling.

samples/matter/light_bulb/README.rst, samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/light_bulb/sample.yaml, samples/matter/light_bulb/src/app_task.cpp, samples/matter/light_bulb/src/zcl_callbacks.cpp, samples/matter/light_switch/README.rst, samples/matter/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/matter/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/light_switch/sample.yaml, samples/matter/template/README.rst, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/template/sample.yaml, samples/matter/thermostat/README.rst, samples/matter/thermostat/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/thermostat/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/matter/thermostat/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/thermostat/sample.yaml, scripts/quarantine_integration.yaml
Added support for nRF54L15 platform in the following samples:
* Light Bulb
* Light Switch
* Template
* Thermostat
Additionally, modified light bulb sample to use PWM conditionally to address the fact that nRF54L does not support PWM yet.
=> samples: matter: Introduced initial support for nRF54L15

samples/bluetooth/iso_time_sync/boards/nrf5340_audio_dk_nrf5340_cpuapp.conf
Enable TIMER0 for fixing compile error when using nrf5340 audio DK.
=> samples: bluetooth: Enable TIMER0 for nrf5340 audio DK

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/silvair_enocean/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/bluetooth/mesh/silvair_enocean/sample.yaml
This adds support for the nRF54L15 PDK to the Silvair Enocean sample.
=> Samples: Bluetooth: Mesh: Add nRF54L15 support to Enocean sample

applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c, applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c, applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
- Check the sample rate for BIS/CIS and reject if not supported
- Fixed bug where right headset wouldn't sync to a single BIS in BIG
- OCT-2716
=> applications: nrf5340_audio: Only accept supported sample rate

doc/nrf/config_and_build/configuring_app/advanced_building.rst, doc/nrf/config_and_build/configuring_app/cmake/index.rst, doc/nrf/config_and_build/configuring_app/hardware/index.rst, doc/nrf/config_and_build/configuring_app/index.rst, doc/nrf/config_and_build/configuring_app/kconfig/index.rst, doc/nrf/installation/install_ncs.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Reworked information about CMake variables with link to more details in Zephyr. NCSDK-22324.
----
Originally part of PR #14518 , but separated to make changes go in in smaller PRs.
=> doc: config_and_build: expand cmake section

applications/nrf5340_audio/src/bluetooth/bt_management/advertising/bt_mgmt_adv.c
- Fix bug where adv data was missing after first doing directed advertising and timing out
- OCT-2615
=> applications: nrf5340_audio: Add data to adv after directed

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/net/http_server/src/main.c
Set `DNS_SD_REGISTER_TCP_SERVICE` so that mDNS services can locate and address the server using its hostname.
=> samples: net: http_server: Register SD service

applications/asset_tracker_v2/doc/cloud_module.rst, applications/asset_tracker_v2/doc/cloud_wrapper.rst, applications/asset_tracker_v2/doc/unit_test.rst, applications/serial_lte_modem/doc/Generic_AT_commands.rst, applications/serial_lte_modem/doc/slm_testing.rst, doc/nrf/device_guides/working_with_nrf/nrf91/nrf9160.rst, doc/nrf/device_guides/working_with_nrf/nrf91/nrf91_features.rst, doc/nrf/external_comp/avsystem.rst, doc/nrf/glossary.rst, doc/nrf/protocols/bt/bt_mesh/concepts.rst, doc/nrf/releases_and_maturity/known_issues.rst, samples/cellular/lwm2m_carrier/provisioning.rst, samples/cellular/lwm2m_carrier/sample_description.rst, samples/cellular/lwm2m_client/sample_description.rst, samples/cellular/nrf_cloud_multi_service/README.rst, samples/crypto/psa_tls/README.rst, samples/debug/memfault/README.rst
Fixed the following terms:
* west
* P-GPS
* pre-shared key (PSK)
* Fota upgrade -> fota update in the nRF91 Series
working with guide to be consistent across all 
doc-sets.
=> doc: Fix some terms in the docs

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
This adds missing changelog entries about Mesh samples which have had nRF54L15 PDK support added.
=> Doc: Add missing changelog about Mesh samples nrf54 support

doc/nrf/releases_and_maturity/migration/migration_guide_2.7.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/fem_al/fem_al.h, lib/fem_al/fem_al.c, lib/fem_al/fem_interface.h, lib/fem_al/generic_fem.c, lib/fem_al/nrf21540.c, samples/bluetooth/direct_test_mode/README.rst, samples/bluetooth/direct_test_mode/src/dtm.c, samples/peripheral/radio_test/README.rst, samples/peripheral/radio_test/src/radio_cmd.c, samples/peripheral/radio_test/src/radio_test.c, samples/peripheral/radio_test/src/radio_test.h
In the PR to sdk-nrfxlib https://github.com/nrfconnect/sdk-nrfxlib/pull/1276
the MPSL provided a new FEM API and deprecated parts of the old API.
This PR migrates the fem_al lib, radio_test and direct_test_mode samples to the new API.
In the radio_test the cli command
`fem tx_gain <gain>`
makes no more sense and is turned into:
`fem tx_power_control <tx_power_control>`
In the direct_test_mode the DTM command
`FEM_GAIN_SET` allowing to set "gain" of the FEM makes no more sense
and is turned into:
`FEM_TX_POWER_CONTROL_SET` allowing to set the FEM tx power control
which is FEM type-specific.
=> Migrate to new FEM API

samples/openthread/cli/README.rst
Commit fixes CSL period in openthread cli sample README to correct value set in us.
=> samples: openthread: Fix CSL period in sample doc.

subsys/net/lib/download_client/CMakeLists.txt, subsys/net/lib/download_client/include/download_client_internal.h, subsys/net/lib/download_client/src/download_client.c, subsys/net/lib/download_client/src/http.c, subsys/net/lib/fota_download/CMakeLists.txt, subsys/net/lib/fota_download/src/util/fota_download_util.c, subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c, tests/subsys/net/lib/download_client/CMakeLists.txt, tests/subsys/net/lib/fota_download/CMakeLists.txt, tests/subsys/net/lib/lwm2m_fota_utils/src/firmware.c, tests/subsys/net/lib/mcumgr_smp_client/CMakeLists.txt
Parse URI before starting the download client
and return parsing failures from _start().
Also, check that download_client parses the protocol,
which means that it knows the protocol.
NCSDK-26790
=> net: lib_ fota_download: Return errors from URI parsing

scripts/print_toolchain_checksum.sh
If yaml files are present, toolchain bundler uses them instead of txt
files as source of required tools.
=> Update print toolchain script

subsys/net/lib/download_client/src/download_client.c
Trying to query IPv6 address on IPv4 network is not necessary error, so change the log level from WRN to DBG.
Then error is show if both queries have failed.
=> net: lib: download_client: Suppress extra DNS warnings

west.yml
Fix MCUboot's application image confirmation issue.
Ref.: NCSDK-26693
=> manifest: zephyr sdk-update

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/central_and_peripheral_hr/sample.yaml, samples/bluetooth/central_hids/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/bluetooth/central_hids/sample.yaml, samples/bluetooth/peripheral_hids_keyboard/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/bluetooth/peripheral_hids_keyboard/sample.yaml, samples/bluetooth/peripheral_hids_mouse/README.rst, samples/bluetooth/peripheral_hids_mouse/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/bluetooth/peripheral_hids_mouse/sample.yaml, samples/bluetooth/peripheral_lbs/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/bluetooth/peripheral_lbs/sample.yaml
Adds support for samples: 
- central_hids
- peripheral_hids_mouse
- peripheral_hids_keyboard
- central_and_peripheral_hr
- peripheral_lbs
=> Add nRF54L15 support in BLE samples

tests/subsys/bluetooth/mesh/metadata_extraction/testcase.yaml
Adds a testcase for metadata extraction with LTO enabled.
=> tests: Bluetooth: Mesh: add LTO to metadata extraction test

scripts/quarantine_integration.yaml
For:
nrf/samples/bluetooth/peripheral_lbs
nrf/samples/bluetooth/peripheral_uart
nrf/samples/bluetooth/peripheral_hids_mouse
nrf/samples/bluetooth/peripheral_hids_keyboard
nrf/samples/bluetooth/central_hids
nrf/samples/bluetooth/central_smp_client
nrf/samples/bluetooth/central_bas
nrf/samples/bluetooth/central_uart
nrf/samples/bluetooth/peripheral_mds
nrf/samples/bluetooth/peripheral_cgms
nrf/samples/bluetooth/peripheral_power_profiling
nrf/samples/bluetooth/peripheral_rscs
nrf/samples/bluetooth/peripheral_gatt_dm
nrf/samples/bluetooth/peripheral_cts_client
nrf/samples/bluetooth/throughput
nrf/samples/bluetooth/peripheral_nfc_pairing
nrf/samples/bluetooth/peripheral_ancs_client
nrf/samples/bluetooth/multiple_adv_sets
nrf/samples/bluetooth/peripheral_ams_client …
=> scripts: add integration quarantine part 7

doc/nrf/libraries/security/nrf_security/doc/drivers.rst
Document that on nRF54L Series devices CRACEN is the only source of entropy, so disabling CONFIG_PSA_CRYPTO_DRIVER_CRACEN is not possible when the Zephyr entropy driver has been enabled.
=> doc: cracen: Document that DRIVER_CRACEN must be enabled sometimes

doc/nrf/security/tfm.rst
Few Kconfig options are referenced with wrong
name, and the links are broken.
=> doc: Fix Kconfig references in TF-M ug

applications/nrf5340_audio/src/bluetooth/bt_content_control/bt_content_ctrl.h, applications/nrf5340_audio/src/bluetooth/bt_content_control/media/bt_content_ctrl_media.c, applications/nrf5340_audio/unicast_server/main.c
- Use the media player state to decide between play/pause in main on unicast_server and not the state of the streaming.
- OCT-2715
=> applications: nrf5340_audio: Disconnect MCP and ISO stream

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/direct_test_mode/boards/nrf54h20dk_nrf54h20_cpurad.conf, samples/bluetooth/direct_test_mode/boards/nrf54h20dk_nrf54h20_cpurad.overlay, samples/bluetooth/direct_test_mode/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/bluetooth/direct_test_mode/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/bluetooth/direct_test_mode/sample.yaml, samples/bluetooth/direct_test_mode/src/dtm.c, samples/bluetooth/direct_test_mode/src/dtm_hw.c, samples/bluetooth/direct_test_mode/src/dtm_hw.h, samples/bluetooth/direct_test_mode/src/transport/dtm_uart_wait.c
Adapts a DTM sample to the nRF54L15 and nRF54H20.
=> samples: bluetooth: direct_test_mode: Add support for nRF54L15

subsys/bluetooth/controller/hci_internal.c
These indicate support for the LL state combinations:
- Initiating State + Passive Scanning
- Initiating State + Active Scanning
=> bluetooth: controller: set bits 22 and 23 in LE Read Supported States

subsys/bluetooth/controller/Kconfig
The current default is way too small. It's expected that most realistic applications will want at least 3.
=> bluetooth: controller: increase default tx buffers for PAwR adv

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, scripts/bluetooth/mesh/mesh_dfu_metadata.py, tests/subsys/bluetooth/mesh/metadata_extraction/verify_metadata.py
This adds the core type, used in constructing the encoded metadata string, as a separate field in the JSON file output by the metadata extraction script.
=> Bluetooth: Mesh: Add core type to metadata JSON

subsys/bluetooth/controller/hci_driver.c
By memsetting it before use it becomes simpler to add new items to it later as these new members are guaranteed to be initialized to zero.
=> bluetooth: controller: hci_driver: memset iso buffer config

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/thermostat/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/thermostat/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, west.yml
- Allowed merging the factory data .hex file with the firmware .hex file without utilizing partition manager.
- Enabled factory data support in all required matter samples for nrf54l15 target.
=> samples: matter: Enable factory data support on nRF54L15 target.

doc/nrf/libraries/bluetooth_services/mesh/sensor_srv.rst, doc/nrf/protocols/bt/bt_mesh/configuring.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/sensor_server/README.rst
Clarifies what possible entries in the Settings NVS name cache may be by using the Mesh Sensor Server sample as an example.
Reduces the depth level of paragraphs in the persistent storage section to fit with the added example.
=> Bluetooth: Mesh: Doc: Clarify settings cache configuration

applications/serial_lte_modem/src/nrfcloud/slm_at_nrfcloud.c, doc/nrf/libraries/networking/nrf_cloud.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud.h, samples/cellular/modem_shell/src/cloud/cloud_rest_shell.c, samples/cellular/nrf_cloud_rest_cell_location/Kconfig, samples/cellular/nrf_cloud_rest_cell_location/README.rst, samples/cellular/nrf_cloud_rest_cell_location/src/main.c, samples/cellular/nrf_cloud_rest_fota/src/main.c, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_shadow_info, subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
nRF Cloud no longer uses the UI service info section in the device shadow.
Mark UI-related Kconfig options as deprecated.
Remove the UI section from the shadow instead of updating it.
Update samples to no longer send UI service info.
IRIS-8636
=> net: lib: nrf_cloud: deprecate ui service info section

west.yml
This algo is essential to fix issues in a Mesh/Enterprise environments.
Fixes SHEL-2626.
=> manifest: sdk-hostap: Pull new algo for network selection

samples/bluetooth/central_uart/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/bluetooth/direct_test_mode/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/bluetooth/peripheral_uart/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay
Align nRF54l15 UART instance with one used
in upstream Zephyr in Peripheral and Central
UART samples.
=> samples: bluetooth: Update nRF54l15 UART instance

samples/cellular/lwm2m_client/src/main.c
Initialization of application image was accidentally removed on last refactoring on PR https://github.com/nrfconnect/sdk-nrf/pull/14610
=> samples: lwm2m_client: Fix app image initialization

applications/protocols_serialization/user_guide.md
This commit modifies user_guide for protocols serialisation.
- fix extra whitespaces at end of line
- fix path of uart wiring
- table of content adjustments
=> doc: applications: Fix protocol serialisation documentation.

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/nrf_cloud_multi_service/overlay-nrf7002ek-wifi-scan-only.conf
We need to allocate enough IPv4 and IPv6 address structures so the nrf91_socket always gets a slot, regardless of order that it and nordic_wlan0 are placed in the net_if array.
Jira: IRIS-8626
=> samples: cellular: nrf_cloud_multi_service: Fix Wi-Fi scanning

samples/tfm/tfm_psa_template/child_image/mcuboot/prj.conf
Remove two EMPTY_ partitions by aligning MCUboot inside SPU regions.
=> samples: Align partitioning to free space

subsys/pcd/src/pcd.c
Fix build error 'CONFIG_FW_INFO_MAGIC_LEN' undeclared here. Including the fw_info_bare.h header file without CONFIG_FW_INFO enabled causes issues in struct definition array size, and in static inline functions.
=> subsys: pcd: Fix build error 'CONFIG_FW_INFO_MAGIC_LEN' undeclared here

scripts/quarantine_integration.yaml
For:
nrf/tests/drivers/fprotect
nrf/tests/subsys/fw_info
nrf/tests/drivers/flash_patch
nrf/tests/drivers/lpuart
=> scripts: add integration quarantine part 8

applications/nrf5340_audio/src/utils/nrf5340_audio_dk.c
- Use clock control to enable high freq clock
- OCT-2847
=> applications: nrf5340_audio: Use clock control to turn on HFClock

applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c, applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c
If codec chan alloc returns -ENODATA channel allocation is set to 0. OCT-2982
=> Applications: nrf5340_audio: Support for no channel alloc

modules/coremark/Kconfig, samples/benchmarks/coremark/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/benchmarks/coremark/prj.conf
Increase iterations in order to meet required test duration of 10s.
Jira: none
=> samples: CoreMark: Increase CoreMark iterations for moonlight platforms

doc/nrf/protocols/matter/end_product/test_event_triggers.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/common/src/Kconfig
Enabled Test Event Triggers feature by default in all Matter samples and applications. Enabled also the pre-defined test event triggers.
=> samples: matter: Enable Test Event Triggers by default

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/bluetooth/enocean.c
This fixes an issue where the EnOcean module would incorrectly parse sensor data as if it were switch commissioning, which causes device slots to be filled up with garbage data if run in an environment where sensors are present.
=> Bluetooth: Fix EnOcean module parsing sensor data as commissioning

doc/nrf/config_and_build/configuring_app/hardware/use_gpio_pin_directly.rst
[NCSDK-26162](https://nordicsemi.atlassian.net/browse/NCSDK-26162)
Fix typo in GPIO doc code block
[NCSDK-26162]: https://nordicsemi.atlassian.net/browse/NCSDK-26162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: fix gpio code

doc/nrf/protocols/esb/index.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/esb/esb_prx/sample.yaml, samples/esb/esb_prx/src/main.c, samples/esb/esb_ptx/sample.yaml, samples/esb/esb_ptx/src/main.c, subsys/esb/Kconfig, subsys/esb/esb.c, subsys/esb/esb_dppi.c, subsys/esb/esb_peripherals.h, subsys/esb/esb_ppi_api.h
PR introduces fast switching between RX to TX and TX to RX radio states without entering the disable state.
=> esb: Enable fast switching for nRF54H20

samples/crypto/aes_cbc/sample.yaml, samples/crypto/aes_ccm/sample.yaml, samples/crypto/aes_ctr/sample.yaml, samples/crypto/aes_gcm/sample.yaml, samples/crypto/chachapoly/sample.yaml, samples/crypto/ecdh/sample.yaml, samples/crypto/ecdsa/sample.yaml, samples/crypto/ecjpake/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/crypto/ecjpake/sample.yaml, samples/crypto/eddsa/sample.yaml, samples/crypto/hkdf/sample.yaml, samples/crypto/hmac/sample.yaml, samples/crypto/pbkdf2/sample.yaml, samples/crypto/persistent_key_usage/sample.yaml, samples/crypto/rng/sample.yaml, samples/crypto/rsa/sample.yaml, samples/crypto/sha256/sample.yaml, samples/crypto/spake2p/sample.yaml
- Use correct tags when running on CC3xx/CRACEN/Oberon
- Add _ns boards for ecjpake and spake2p
- Use CRACEN for ecjpake on nRF54L15
test_crypto: PR-625
=> samples: crypto: Crypto samples cleanup

applications/machine_learning/README.rst, applications/matter_bridge/doc/matter_bridge_description.rst, applications/matter_weather_station/README.rst, applications/nrf5340_audio/doc/building.rst, applications/nrf5340_audio/doc/configuration.rst, applications/nrf_desktop/description.rst, applications/zigbee_weather_station/README.rst, doc/nrf/config_and_build/config_and_build_system.rst, doc/nrf/config_and_build/configuring_app/advanced_building.rst, doc/nrf/config_and_build/configuring_app/cmake/index.rst, doc/nrf/config_and_build/multi_image.rst, doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_debugging.rst, doc/nrf/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_matter_thread.rst, doc/nrf/glossary.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.7.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, doc/nrf/shortcuts.txt, doc/nrf/test_and_optimize/debugging.rst, samples/bluetooth/peripheral_lbs/README.rst, samples/event_manager_proxy/README.rst, samples/matter/light_bulb/README.rst, samples/matter/light_switch/README.rst, samples/matter/lock/README.rst, samples/matter/template/README.rst, samples/matter/thermostat/README.rst, samples/matter/window_covering/README.rst, samples/zigbee/light_switch/README.rst, samples/zigbee/ncp/README.rst, samples/zigbee/shell/README.rst, scripts/partition_manager/partition_manager.rst
Added information about FILE_SUFFIX variable in build and config
section. Added deprecation info to sections about build types.
Replaced mentions of build types with mention of file suffixes
in some samples and apps. Updated build and configuration section.
Added an important note about missing support for Partition Manager.
NCSDK-22324.
----
Related Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/66141
----
=> doc: add information about FILE_SUFFIX

applications/nrf5340_audio/doc/fota.rst, doc/nrf/device_guides/working_with_nrf/nrf53/nrf5340.rst
Remove instructions using the buildprog script from DFU chapter. Update the DFU chapter to explain how to build the application with DFU support for SDC.
=> applications: nrf5340_audio: doc: Remove buildprog from DFU chapter

cmake/extensions.cmake, cmake/multi_image.cmake, cmake/partition_manager.cmake
Adds FILE_SUFFIX support to partition manager so that the correct
configuration will be used instead of the default
and
cmake: partition_manager: Fix missing sysbuild static PM file
Fixes an issue whereby when a static PM file is defined on the
command line when building with sysbuild, it would be completely
absent
and
cmake: multi_image: Add FILE_SUFFIX support
Adds FILE_SUFFIX support to child/parent image, this diverges from
how it operates in sysbuild due to child/parent's inability to have
a named prefix for the main application, and requires that child
images have the child name prefix for FILE_SUFFIX to be applied
=> cmake: extensions: Add support for FILE_SUFFIX with PM

modules/trusted-firmware-m/tfm_boards/nrf9120/CMakeLists.txt
The config.cmake for nRF9120 (used also for nRF9161) was not placed in the correct path for the non secure application. This mainly affected the TF-M regression tests since they use the non secure application building from TF-M.
Ref: NCSDK-26131
=> modules: tf-m: Fix 9161 building issue

cmake/extensions.cmake, sysbuild/extensions.cmake
```
Fixes an issues whereby adding file overlays to child images/sysbuild images would replace files that should be present, e.g. <board>.overlay, instead of appending to them
```
=> cmake: Fix file overlays replacing existing overlays

lib/location/method_gnss.c
In method_gnss_location_get(), 'running' variable is set after submitting method_gnss_prepare_work_fn() into location_api_workq. It has been seen that 'running' is not set when
method_gnss_prepare_work_fn() is executed meaning that location_request() was called from a lower priority thread than location_api_workq. We need to set 'running' before submitting method_gnss_prepare_work_fn() into location_api_workq.
Jira: NCSDK-27001
=> lib: location: gnss: Fix setting of 'running' variable

west.yml
Update nRF70 release/v2.6 firmware patch.
Fixes SHEL-2684.
=> manifest: sdk-nrfxlib: Pull nRF70 v2.6 patch update rev#352850030ab

west.yml
Fixes SHEL-2685.
Updating nRF70 release/v2.6 firmware patch.
=> manifest: sdk-nrfxlib: Pull nRF70 v2.6 patch update rev#3fa8ab52fae

tests/subsys/emds/emds_flash/src/main.c
Commit excludes writing time measurement for nrf54l. There are no still RRAM programming digits in documentation.
=> emds: exclude write time measurement for nrf54

subsys/bluetooth/controller/hci_internal.c
This PR introduces commands and feature bits for the LE Path Loss Monitoring feature.
Adds support for the following HCI commands:
- sdc_hci_cmd_le_set_path_loss_reporting_params
- sdc_hci_cmd_le_set_path_loss_reporting_enable
=> bluetooth: controller: Add HCI commands for LE Path Loss Monitoring

samples/keys/identity_key_usage/README.rst
Fixed formatting and removed a redundant
sentence.
=> doc: Identity key usage sample: formatting fix

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, west.yml
Pull a fix for PBKDF2 key generation API in OpenThread
KRKNWK-18797
=> [backport-v2.6] manifest: update Zephyr revision

subsys/bluetooth/controller/hci_driver.c
Utilize the configurations CONFIG_BT_ISO_TX_MTU and CONFIG_BT_ISO_RX_MTU to save RAM when a smaller MTU is needed.
For a typical audio use case where the maximum MTU is at max 140 bytes, this can result in a lot of RAM saved.
Example: For the sample iso_time_sync, the RAM usage is reduced by more than 700 bytes
=> Bluetooth: Controller: Configurable ISO SDU size

west.yml
Define RTS and CTS pins and enable HWFC for uart connected to debugger.
=> manifest: update zephyr - HWFC for nrf54l15

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/light_bulb/src/chip_project_config.h, west.yml
The current 800ms is not enough in real setups, where Thread routers must serve as intermediate hops for many parallel conversations. Bump this to 2s.
=> matter: Increase default retry interval for Thread

modules/hostap/Kconfig
Due to recent changes in hostap to move few buffers from heap->stack (to improve the reliability of allocations) this has increased the stack size and with another recent change to increase the max polling sockets this puts over the 4096 stack size for net_mgmt causing stack overflow.
Increase the stack size for net_mgmt to fix SHEL-2640 and SHEL-2676.
=> modules: hostap: Increase the stack size for net_mgmt

west.yml
Pull in a fix in pinctrl that prevents the nrf_qspi_nor driver from failing to initialize when the flash chip is configured to work in non-Quad mode.
=> [backport-v2.5] manifest: Update zephyr revision

lib/hw_unique_key/Kconfig
Enables hw_unique_key library on TF-M with Cracen.
Support was added in https://github.com/nrfconnect/sdk-nrf/pull/14885, but missed configuration update when rebasing.
=> hw_unique_key: Enable TF-M and Cracen

west.yml
Configuration for MCUboot and smp_svr which
allows to use nRF54L15pdk external flash as location for the secondary partition.
~~west build  -b nrf54l15pdk_nrf54l15_cpuapp -d build/smp_svr_54l zephyr/samples/subsys/mgmt/mcumgr/smp_svr/ -- -DEXTRA_CONF_FILE=overlay-bt.conf -DCONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=y -DCONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y  -DDTC_OVERLAY_FILE=boards/nrf54l15pdk_ext_flash.overlay -Dmcuboot_EXTRA_DTC_OVERLAY_FILE=~/codedev/NCS/zephyr/samples/subsys/mgmt/mcumgr/smp_svr/boards/nrf54l15pdk_ext_flash.overlay -Dmcuboot_CONF_FILE=boards/nrf54l15pdk_ext_flash.conf~~
~~For transferring extra overlay an absolute path must be used as build system can't handle any relative path for subimages.~~
Build commndline:
``` console
west build  -b …
```
=> manifest: smp_svr@nRF54l15pdk with external flash

scripts/quarantine_windows_mac.yaml
This sample overflows FLASH region.  The Matter team will investigate 
﻿
Signed-off-by: Thomas Stilwell <thomas.stilwell@nordicsemi.no>
=> ci: quarantine `sample.matter.light_bulb.memory_profiling` for MacOS

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/common/src/dfu/ota/ota_util.cpp, samples/matter/common/src/dfu/ota/ota_util.h, samples/matter/light_bulb/README.rst, samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/light_bulb/child_image/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/light_bulb/pm_static_nrf54l15pdk_nrf54l15_cpuapp_release.yml, samples/matter/light_switch/README.rst, samples/matter/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/light_switch/child_image/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/light_switch/pm_static_nrf54l15pdk_nrf54l15_cpuapp_release.yml, samples/matter/template/README.rst, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/template/child_image/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/template/pm_static_nrf54l15pdk_nrf54l15_cpuapp_release.yml, samples/matter/thermostat/README.rst, samples/matter/thermostat/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/thermostat/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/thermostat/child_image/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/thermostat/pm_static_nrf54l15pdk_nrf54l15_cpuapp_release.yml, samples/matter/window_covering/README.rst, samples/matter/window_covering/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/window_covering/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/window_covering/child_image/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp_release.conf, samples/matter/window_covering/pm_static_nrf54l15pdk_nrf54l15_cpuapp_release.yml, west.yml
Added support for DFU and Partition Manger to nrf54l15 Matter samples for internal MRAM only. It means that the MCUBoot secondary partition is located in the internal MRAM memory. This configuration can be used in the release build type only.
- Created pm_static.yaml with the partitioning map for internal MRAM memory only.
- Enabled Partition Manager
- Enabled DFU over BLE
- Enabled DFU over Matter (OTA)
=> samples: matter: Enable Partition Manager and DFU for nrf54l15.

doc/nrf/libraries/security/trusted_storage.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/trusted_storage/Kconfig
Add Kconfig option CONFIG_TRUSTED_STORAGE_STORAGE_BACKEND_CUSTOM This allows to use the non-default Storage backend that uses Settings + NVS
=> trusted_storage: Add Kconfig for custom storage backend

samples/matter/light_bulb/sample.yaml
Add configuration to enable memory profile testing for nRF54L15
=> samples: matter: add memory profiling configuration for nRF54L15

applications/matter_bridge/doc/matter_bridge_description.rst
Kconfig options that were application-specific had not been documented. This resulted in mentions in documentation not linking to anything.
=> doc: Matter: add missing Kconfig option documentation to Matter bridge

doc/nrf/libraries/bluetooth_services/adv_prov.rst, doc/nrf/libraries/bluetooth_services/gatt_pool.rst, doc/nrf/libraries/bluetooth_services/scan.rst, doc/nrf/libraries/bluetooth_services/services/ams_client.rst, doc/nrf/libraries/bluetooth_services/services/ancs_client.rst, doc/nrf/libraries/bluetooth_services/services/bas_client.rst, doc/nrf/libraries/bluetooth_services/services/bms.rst, doc/nrf/libraries/bluetooth_services/services/cgms.rst, doc/nrf/libraries/bluetooth_services/services/cts_client.rst, doc/nrf/libraries/bluetooth_services/services/dfu_smp.rst, doc/nrf/libraries/bluetooth_services/services/fast_pair.rst, doc/nrf/libraries/bluetooth_services/services/gattp.rst, doc/nrf/libraries/bluetooth_services/services/hids.rst, doc/nrf/libraries/bluetooth_services/services/hogp.rst, doc/nrf/libraries/bluetooth_services/services/latency.rst, doc/nrf/libraries/bluetooth_services/services/latency_client.rst, doc/nrf/libraries/bluetooth_services/services/mds.rst, doc/nrf/libraries/bluetooth_services/services/nus_client.rst, doc/nrf/libraries/bluetooth_services/services/rscs.rst, doc/nrf/libraries/bluetooth_services/services/wifi_prov.rst
Aligning the terminology in the library and service docs. Subsystem and module to library. Also some minor language fixes.
Ref: NCSDK-25270
=> doc improvement: BT libs and services: terminology alignments

samples/matter/common/src/board/board.cpp
Bluetooth LE connection to the Matter Controller was not been handled properly.
Moved the UpdatingDeviceState invocation outside the Matter Event Handler switch.
=> samples: matter: Fix for device state indications on LEDs

subsys/bluetooth/controller/hci_internal.c
The vendor specific API can be used to set the primary advertising channels that should be used for scanning and initiating.
=> Bluetooth: Controller: Add support for setting scanning channel map

drivers/wifi/nrf700x/Kconfig, drivers/wifi/nrf700x/osal/fw_if/umac_if/src/cmd.c
This is handy esp. in crowded channel environments to avoid false AP dead detections, the default is chosen accordingly.
Implements SHEL-2689.
=> drivers: wifi: Add a config option for AP dead detection timeout

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, modules/hostap/src/supp_api.c, samples/wifi/shell/README.rst
Support WPA Auto security mode wherein supplicant can
implicitly choose one of WPA, WPA2 and WPA3 for association
with a network.
Fixes SHEL-1131.
=> modules: hostap: Add support for WPA Auto security 

applications/nrf_desktop/configuration/nrf52840dk_nrf52840/app.overlay
Change fixes labels of "Num Lock" and "Caps Lock" LEDs.
=> applications: nrf_desktop: Fix LED labels on nRF52840DK

doc/nrf/links.txt, doc/nrf/protocols/matter/end_product/certification.rst
CSA has changed the structure of their website.
This fixes the affected links in our documentation.
KRKNWK-18898
=> doc: fix links to Matter resource kit

applications/matter_bridge/doc/matter_bridge_description.rst
A couple of application-specific Kconfigs got left out from the previous batch.
=> doc: Matter bridge: More missing Kconfigs

applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c, applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c, applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.h, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.h, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.h, applications/nrf5340_audio/src/modules/led.h, applications/nrf5340_audio/src/utils/nrf5340_audio_dk.c, applications/nrf5340_audio/src/utils/nrf5340_audio_dk.h, applications/nrf5340_audio/unicast_client/main.c, applications/nrf5340_audio/unicast_server/main.c
- Set channel for unicast_server from main
- Remove hard-coded dependencies on BT_RX
- Check both sink and source stream states
- Choose direction to start/stop for unicast
- OCT-NONE
=> applications: nrf5340_audio: Hackathon improvements

doc/nrf/releases_and_maturity/migration/migration_guide_2.7.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/peripheral/radio_test/README.rst
Added sample-specific Kconfig options and links
to them.
---
=> doc: fixing Kconfig option links

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_connmon.c
Fix reporting on Connection Monitor object version 1.3.
=> net: lwm2m_client_utils: Fix LAC reporting on ConnMonn v1.3

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, west.yml
This commit increases number of available packet buffers in the system.
=> manifest: matter: pull fix for insufficient resources

doc/nrf/protocols/esb/index.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/esb/esb_prx/sample.yaml, samples/esb/esb_ptx/sample.yaml, subsys/esb/Kconfig, subsys/esb/esb.c
Adds fast radio channel switching.
Allows the radio channel to be changed in RX radio mode
without the need to switch the radio to DISABLE mode.
=> esb: Enable fast radio channel switching for nRF54H20

doc/nrf/protocols/bt/bt_mesh/dfu_over_ble.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/dfu/distributor/README.rst, samples/bluetooth/mesh/dfu/target/CMakeLists.txt, samples/bluetooth/mesh/dfu/target/README.rst, samples/bluetooth/mesh/dfu/target/overlay-ptp_dfu.conf, samples/bluetooth/mesh/dfu/target/src/main.c
Adding point to point DFU together with Mesh DFU
so the point to point DFU can be used as a fallback solution.
=> Bluetooth: Mesh: Point to point and Mesh DFU

applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.h, applications/nrf5340_audio/src/modules/led.h
- Remove parameters that are not used in led.h
- OCT-3003
=> applications: nrf5340_audio: Fix doc build

samples/bluetooth/central_and_peripheral_hr/sample.yaml, samples/bluetooth/central_hids/sample.yaml, samples/bluetooth/central_uart/sample.yaml, samples/bluetooth/direct_test_mode/sample.yaml, samples/bluetooth/peripheral_hids_keyboard/sample.yaml, samples/bluetooth/peripheral_hids_mouse/sample.yaml, samples/bluetooth/peripheral_lbs/sample.yaml, samples/bluetooth/peripheral_uart/sample.yaml, samples/esb/esb_prx/sample.yaml, samples/esb/esb_ptx/sample.yaml, samples/nfc/record_launch_app/sample.yaml, samples/nfc/record_text/sample.yaml, samples/nfc/shell/sample.yaml, samples/nfc/system_off/sample.yaml, samples/nfc/tnep_tag/sample.yaml, samples/nfc/writable_ndef_msg/sample.yaml, samples/peripheral/radio_test/sample.yaml
Add entry about support for nrf54l15dk_nrf54l15_cpuapp@0.3.0 revision in all samples yaml files that support it.
=> samples: Add nRF54l15 0.3.0 rev in sample yaml files

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, west.yml
Pull inn update of RC accuracy nRF devices.
=> manifest: update sdk-zephyr, nrf53/nrf54

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud_location.h, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_location, subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
Add Kconfig option NRF_CLOUD_LOCATION_PARSE_ANCHORS to control if the anchor names are parsed from the location response data. 
IRIS-8813
=> net: lib: nrf_cloud: add config option to control anchor parsing

west.yml
Updated Matter manifest version to pull the mcuboot configuration fix that does not allo to change external flash backends between SPI and QSPI (and opposite).
=> manifest: Pulled fix for mcuboot configuration in Matter

west.yml
Configuring XL1 and XL2 Pin, which are needed for
low-frequency crystal oscillator (LFXO)
Ref: NCSDK-26595
Ref: NCSDK-25047
Ref: NCSDK-20678
=> manifest: tf-m: Add LFXO and CTRL-AP support on 54L

tests/subsys/suit/cache_pool_digest/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/subsys/suit/cache_sink/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/subsys/suit/envelope_decoder/boards/native_posix.overlay, tests/subsys/suit/envelope_decoder/boards/native_posix_64.overlay, tests/subsys/suit/fetch_integrated_payload_flash/boards/native_posix.overlay, tests/subsys/suit/fetch_integrated_payload_flash/boards/native_posix_64.overlay, tests/subsys/suit/fetch_integrated_payload_flash/boards/nrf52840dk_nrf52840.overlay, tests/subsys/suit/flash_sink/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/subsys/suit/orchestrator/orchestrator_sdfw/boards/native_posix.overlay, tests/subsys/suit/orchestrator/orchestrator_sdfw/boards/native_posix_64.overlay, tests/subsys/suit/orchestrator/orchestrator_sdfw/boards/nrf52840dk_nrf52840.overlay, tests/subsys/suit/sink_selector/boards/native_posix.overlay, tests/subsys/suit/sink_selector/boards/native_posix_64.overlay, tests/subsys/suit/storage/boards/native_posix.overlay, tests/subsys/suit/storage/boards/native_posix_64.overlay, tests/subsys/suit/storage/boards/nrf52840dk_nrf52840.overlay
Labes on partiions in NCS are nor needed nor allowed on all platforms.
=> tests: suit: Remove labels from DTS overlays

doc/nrf/includes/sample_board_rows.txt
Replaced the Getting Started page links
to Developing with nRF70 Series page
for nRF70 Series devices in the
sample_board_rows.txt.
NCSDK-25668
=> doc: wifi: replace gsg links to developing ug

drivers/wifi/nrf700x/src/fmac_main.c, drivers/wifi/nrf700x/src/wpa_supp_if.c
[SHEL-2661] If regulatory set is called before WPA supplicant is initialized, then as NM is not registered the calls gets re-routed to driver directly skipping WPA supplicant. In that case, the command should be failed at driver.
[SHEL-2661]: https://nordicsemi.atlassian.net/browse/SHEL-2661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> driver: wifi: Make WPA supplicant regulatory aware

subsys/suit/storage/src/suit_storage_nrf54h20.c, tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_boot_mode.c, tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_init.c, tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_recovery_boot_mode.c, tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_recovery_update_mode.c, tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_update_mode.c, tests/subsys/suit/storage/src/test_envelopes.c, tests/subsys/suit/storage/src/test_report.c, tests/subsys/suit/storage/src/test_update.c, tests/subsys/suit/storage_nrf54h20/boards/native_posix.overlay, tests/subsys/suit/storage_nrf54h20/src/test_common.h
The names were changed in dts to match the new convention, this commit aligns the code.
=> suit: aligned to new storage node names in dts

doc/_utils/redirects.py, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, doc/nrf/security/ap_protect.rst
Added information about which Kconfig option is the default in the NCS. NCSDK-22526.
----
=> doc: ap_protect: clarify default setting

samples/wifi/shell/README.rst
Correct the display of the `Set regulatory domain` command in the testing SAP mode procedure section of the shell sample documentation.
Fixes SHEL-2732
=> samples: wifi: shell: Fix regulatory domain setting reference

dts/arm/nordic/nrf54l15_cpuapp_peripherals_ns.dtsi
nrfx has hardcoded in nrf_gpiote.h that non-secure and secure should use different IRQs.
So we change the IRQs in the non-secure board to match this encoding.
=> 54l: ns: Fix the ns board configuration wrt. gpiote IRQs

boards/shields/nrf7002eb/boards/nrf52840dk_nrf52840.overlay, boards/shields/nrf7002eb/boards/nrf5340dk_nrf5340_cpuapp.overlay, boards/shields/nrf7002eb/boards/thingy53_nrf5340_cpuapp.overlay, boards/shields/nrf7002eb/nrf7002eb.overlay, boards/shields/nrf7002ek/boards/nrf52840dk_nrf52840.overlay, boards/shields/nrf7002ek/boards/nrf5340dk_nrf5340_cpuapp.overlay, boards/shields/nrf7002ek/boards/thingy53_nrf5340_cpuapp.overlay, boards/shields/nrf7002ek/nrf7002ek.overlay, boards/shields/nrf7002ek_nrf7000/boards/nrf52840dk_nrf52840.overlay, boards/shields/nrf7002ek_nrf7000/boards/nrf5340dk_nrf5340_cpuapp.overlay, boards/shields/nrf7002ek_nrf7000/boards/thingy53_nrf5340_cpuapp.overlay, boards/shields/nrf7002ek_nrf7000/nrf7002ek_nrf7000.overlay, boards/shields/nrf7002ek_nrf7001/boards/nrf52840dk_nrf52840.overlay, boards/shields/nrf7002ek_nrf7001/boards/nrf5340dk_nrf5340_cpuapp.overlay, boards/shields/nrf7002ek_nrf7001/boards/thingy53_nrf5340_cpuapp.overlay, boards/shields/nrf7002ek_nrf7001/nrf7002ek_nrf7001.overlay, doc/_scripts/software_maturity/software_maturity_features.yaml, drivers/wifi/nrf700x/Kconfig, drivers/wifi/nrf700x/inc/coex.h, drivers/wifi/nrf700x/src/coex.c, drivers/wifi/nrf700x/src/qspi/inc/rpu_hw_if.h, drivers/wifi/nrf700x/src/qspi/src/rpu_hw_if.c, samples/wifi/ble_coex/src/main.c, samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
GPIOs are limited, so, exclude the SR co-ex GPIOs if they aren't necessary.
Tried to avoid duplication by including a common definitions, this also gives us flexibility in the future to go custom way. Also, used the per-board overlays so that co-ex overlays are picked without user intervention (If user needs to explicitly enable co-ex then a simple snippet would suffice rather than too many per-board files).
=> wifi: sr_coex: Exclude SR co-ex GPIOs for nRF91 series

subsys/suit/provisioning/soc/Kconfig.nrf54h20
The SOC_NRF54H20 symbol remains unavailable in SDFW.
=> suit: Use SOC series insted of SOC_NRF54H20

doc/nrf/links.txt
Converted links as far as possible.
Some of them are only available in old releases
that are not included in TechDocs.
=> doc: convert links in links.txt to point to TechDocs

applications/connectivity_bridge/boards/thingy91x_nrf5340_cpuapp_readme.txt
The README file for thingy91x had duplicate sentences. This is now fixed.
=> applications: connectivity_bridge: Remove duplicate text in readme

lib/date_time/date_time_core.c, lib/date_time/date_time_modem.c, lib/date_time/date_time_modem.h, lib/lte_link_control/lte_lc.c, lib/lte_link_control/lte_lc_helpers.c, lib/lte_link_control/lte_lc_helpers.h, samples/cellular/modem_shell/prj.conf, tests/lib/lte_lc/src/main.c, tests/lib/lte_lc_api/src/lte_lc_api_test.c
Components shouldn't be sending AT commands from system work queue because other AT commands might be ongoing, and the 2nd command will be stuck until the first one completes.
If there is an AT command ongoing by other apps/libraries, and CEREG is received from AT monitor:
- lte_lc will query for PSM parameters using `AT%XMONITOR` when we go to connected state (status 1 or 5). This was done in AT monitor event handler, which is executed in the system workqueue.
- date_time library is sending `AT%XTIME=1` whenever modem goes to search state (CEREG: 2). This happens in lte_lc event handler which is called from at_monitor in system work queue.
As the event handlers are not executed, AT monitor heap will run out and assert.
AT%XMONITOR is moved to an own work queue within lte_lc.
`AT%XTIME=1` …
=> lib: lte_link_control/date_time: No AT%XMONITOR or AT%XTIME=1 from AT monitor event handler

doc/nrf/libraries/nrf_rpc/nrf_rpc_uart.rst, include/nrf_rpc/nrf_rpc_uart.h
Add a documentation page that describes the nRF RPC UART transport frame encoding and API.
=> nrf_rpc: add documentation page for the UART transport

applications/nrf_desktop/configuration/nrf54l15pdk_nrf54l15_cpuapp/boards/nrf54l15pdk_nrf54l15_cpuapp_0_2_0.overlay, applications/nrf_desktop/configuration/nrf54l15pdk_nrf54l15_cpuapp/boards/nrf54l15pdk_nrf54l15_cpuapp_0_3_0.overlay, west.yml
Add support for PWM LEDs configuratoin to run PWM samples on nRF54 DKs.
=> manifest: Update sdk-zephyr witm PWM support in samples for nRF54

doc/nrf/config_and_build/dfu/index.rst, doc/nrf/device_guides/working_with_nrf/nrf52/developing.rst, doc/nrf/device_guides/working_with_nrf/nrf53/nrf5340.rst
[NCSIDB-1158](https://nordicsemi.atlassian.net/browse/NCSIDB-1158)
Improve FOTA docs with interlinks to NCS docs and existing guides within "Working with nRF52/nRF53..." pages,
and existing Device Firmware Updates page
[NCSIDB-1158]: https://nordicsemi.atlassian.net/browse/NCSIDB-1158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: improve fota info with NCS pages interlinking

CODEOWNERS
Both of the Thingy:91 boards are the responsibility of the CIA team.
=> codeowners: add CIA team to Thingy91 boards

modules/trusted-firmware-m/Kconfig.tfm.pm
Reduce the default amount of RAM for TFM from 200kB to 65kB.
This makes it possible to fit TF-M with other applications that use a lot of RAM, like Matter.
=> tfm: 54l: Use a more reasonable amount of RAM by default for TFM

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud_codec.h, samples/cellular/nrf_cloud_multi_service/CMakeLists.txt, samples/cellular/nrf_cloud_multi_service/Kconfig, samples/cellular/nrf_cloud_multi_service/README.rst, samples/cellular/nrf_cloud_multi_service/src/application.c, samples/cellular/nrf_cloud_multi_service/src/application.h, samples/cellular/nrf_cloud_multi_service/src/cloud_connection.c, samples/cellular/nrf_cloud_multi_service/src/shadow_config.c, samples/cellular/nrf_cloud_multi_service/src/shadow_config.h, samples/cellular/nrf_cloud_multi_service/src/shadow_support_coap.c, samples/cellular/nrf_cloud_multi_service/src/shadow_support_coap.h, subsys/net/lib/nrf_cloud/include/nrf_cloud_codec_internal.h, subsys/net/lib/nrf_cloud/src/nrf_cloud_codec.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
Add configuration handling.
The test counter can now be enabled/disabled by using
the device shadow.
IRIS-7709
=> samples: cellular: nrf_cloud_multi_service: add cfg handling

CMakeLists.txt, CODEOWNERS, Kconfig.nrf, cmake/commit.h.in, cmake/gen_commit_h.cmake, cmake/version.cmake, cmake/version_app.cmake, kernel/CMakeLists.txt, kernel/Kconfig, kernel/banner.c
Adds an enhanced boot banner which can be configured to show application name and version, NCS version, and underlying zephyr version.
=> kernel: Add NCS boot banner

subsys/trusted_storage/src/storage_backend_settings.c
Aligns the error codes of PSA persistent key generation/importing for TF-M and non TF-M builds.
=> trusted_storage: Fix error codes for PSA persistent keys

west.yml
Fixes issue with not catching WPA CLI commands failure processing.
=> manifest: sdk-hostap: Pull fix for WPA CLI failure processing

boards/nordic/thingy91x/thingy91x_nrf9151_common.dts
This patch adds support for using the expansion board. When using the expansion board, the corresponding power-enable pin must be asserted.
The most convenient way to do this is the HOG feature.
=> board: thingy91x_nrf9151: Add support for expansion board

modules/trusted-firmware-m/Kconfig.tfm.defconfig
The minimal profile type actually means consuming 32kB of FLASH, and for 53/91 this is the minimal that TF-M can consume. But for 54L, with a trustzone granularity of 4kB instead of 32kB, this is no longer the minimal size that TF-M can consume.
Change the default TF-M profile type to be NOT_SET for 54L.
=> tfm: Change the default TF-M profile type to be NOT_SET for 54L

include/bluetooth/nrf/host_extensions.h, subsys/bluetooth/controller/hci_internal.c, subsys/bluetooth/host_extensions/CMakeLists.txt, subsys/bluetooth/host_extensions/host_extensions.c
By default, the initiator in the SoftDevice Controller operates at a higher priority than other BT roles. This may result in unwanted scheduling conflicts with other roles.
On the primary channel, the initiator can be scheduled such that conflicts can be avoided, by choosing an interval that is equal or a multiple of the interval of other roles. However, the secondary channel timings are set by the peer device. This new host extension allows to (temporarily) reduce the priority the initiator uses when following AUX pointers.
=> Bluetooth: Host: allow reducing initiator priority

CODEOWNERS
The codeowners entry was added in parallel to HWMv2 transition, the CI was not rerun after the upmerge so this was missed and CODEOWNERS check is now failing.
=> codeowners: Fix board location for thingy91* boards

CODEOWNERS, cmake/sysbuild/suit.cmake, cmake/sysbuild/suit_utilities.cmake, subsys/suit/provisioning/soc/Kconfig.nrf54h20, sysbuild/CMakeLists.txt, west.yml
Migration of SUIT from  NEXT to NCS.
`sdsc bundle` (ver>=2) need to be downloaded to be able to build configurations listed above if SUIT_ENVELOPE_NORDIC_TOP_DIRECTORY is overwriten by some path, `CONFIG_SUIT_ENVELOPE_NORDIC_TOP_DIRECTORY` points to folder in which bundle is unpacked (nordic-top.suit manifest is available)
SUIT build system can be tested using multicore/hello_world sample:
```
west build -b nrf54h20dk/nrf54h20/cpuapp -p --sysbuild -- -DSB_CONF_FILE=sysbuild/nrf54h20dk_nrf54h20_cpurad.conf -DCONFIG_SUIT_ENVELOPE=y -DCONFIG_SUIT_ENVELOPE_NORDIC_TOP_DIRECTORY=\"/work/nordic-top/\" -DCONFIG_SUIT_MPI_GENERATE=y
```
With signing enabled (example key_private.pem need to be copied into modules/lib/suit-generator/ncs/ directory):
```
west build -b nrf54h20dk/nrf54h20/cpuapp -p …
```
=> suit: migration of SUIT DFU build system to NCS

doc/nrf/installation/install_ncs.rst, doc/nrf/installation/recommended_versions.rst, doc/nrf/links.txt
Added mention of nrf-udev rules as requirement for the NCS. NCSDK-27198.
=> doc: install: mention nrf-udev rules as required

samples/bluetooth/iso_time_sync/include/iso_time_sync.h, samples/bluetooth/iso_time_sync/src/bis_receiver.c, samples/bluetooth/iso_time_sync/src/cis_central.c, samples/bluetooth/iso_time_sync/src/cis_peripheral.c, samples/bluetooth/iso_time_sync/src/iso_rx.c
Add callback that is triggered when an RX ISO channel disconnects. The usecase is to start scanning for a new connection. Scanning for a new connection is also done in the ACL disconnection callback in this sample, but the ISO channel might disconnect after the ACL, which will prevent the central from starting to scan for a new ISO connection.
=> bluetooth: samples: add iso_rx disconnect cb.

subsys/bluetooth/host_extensions/host_extensions.c
The include of hci_types_host_extensions.h was removed by mistake. Adding it back.
=> Bluetooth: Host: Add missing include

samples/bluetooth/mesh/light_dimmer/README.rst
The Light Dimmer sample documentation falsely stated that Thingy:53 only has one button and that therefore some functionality would not work on Thingy:53
=> samples: Bluetooth: Mesh: Fix documentation for Light Dimmer sample

scripts/quarantine_integration.yaml
For:
nrf/samples/wifi/shell
nrf/samples/wifi/scan
nrf/samples/wifi/radio_test
nrf/samples/wifi/sta
nrf/samples/wifi/provisioning
=> scripts: add integration quarantine part 10

CODEOWNERS
The directory is now renamed to match HWMv2.
=> codeowners: Fix the directory path

west.yml
=> manifest: sdk-hostap: Pull fix for NULL de-reference

west.yml
Updated the Zephyr revision to pull in a workaround for the IPC service module.
=> manifest: update zephyr to pull in ipc workaround

boards/shields/nrf700x_nrf54h20dk/Kconfig.shield, boards/shields/nrf700x_nrf54h20dk/boards/nrf54h20dk_nrf54h20_cpuapp.conf, boards/shields/nrf700x_nrf54h20dk/nrf700x_nrf54h20dk.overlay, samples/wifi/shell/sample.yaml, samples/wifi/shell/src/main.c
Tested Wi-Fi open association and ping.
=> wifi: Add 54h support

scripts/quarantine_integration.yaml, scripts/quarantine_zephyr_integration.yaml
For:
zephyr/tests/subsys/mgmt/mcumgr/os_mgmt_info
zephyr/tests/subsys/mgmt/mcumgr/fs_mgmt_hash_supported
zephyr/tests/subsys/mgmt/mcumgr/smp_version
zephyr/tests/subsys/mgmt/mcumgr/os_mgmt_echo
zephyr/samples/subsys/mgmt/mcumgr/smp_svr
nrf/tests/subsys/dfu/dfu_target_stream
=> scripts: add integration quarantine part 11

samples/cellular/modem_shell/src/location/location_cmd_utils.c
Added sending of GNSS fix altitude, speed and heading to nRF Cloud using `location` command option `--gnss_cloud_pvt`, when `CONFIG_LOCATION_DATA_DETAILS` is enabled.
=> samples: cellular: modem_shell: Add sending of additional GNSS data

doc/CMakeLists.txt
CMake policy CMP0148 deprecates usage of PythonInterp/Libs in favor of Python/2/3 starting from CMake 3.12. Let's update our CMake, and require the same version Zephyr sets as its minimum.
=> doc: cmake: fix Python check

boards/shields/pca63566/Kconfig.shield, boards/shields/pca63566/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, boards/shields/pca63566/doc/index.rst, boards/shields/pca63566/pca63566.overlay
Add PCA63566 teting shield with env. sensors and CAN transceiver
=> boards: shields: add support for PCA63566

scripts/quarantine_zephyr_integration.yaml
=> scripts: add integration quarantine part 12

modules/wfa-qt/src/utils.c
Replace usage of the deprecated `net_if_ipv4_set_netmask` with the `net_if_ipv4_set_netmask_by_addr`.
=> modules: wfa-qt: use net_if_ipv4_set_netmask_by_addr

boards/shields/pca63565/Kconfig.shield, boards/shields/pca63565/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, boards/shields/pca63565/doc/index.rst, boards/shields/pca63565/pca63565.overlay
Define SHIELD PCA63565 that is compatible with
for example nrf54l15pdk PCA10156.
=> boards: shields: Add definition of PCA63565

doc/nrf/libraries/networking/download_client.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.4.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/download_client.h, subsys/net/lib/download_client/src/download_client.c
Remove deprecated `download_client_connect()` function.
=> net: download_client: remove deprecated function

west.yml
Update zephyr to enable DCACHE by default for nrf54h20.
=> manifest: Update zephyr with nrf54h20 DCACHE enabling

west.yml
Some globbing issues on MAINTAINERS.yml, pulled by some docs extensions, are fixed.
=> manifest: update Zephyr to fix docs build on Python >= 3.11

doc/nrf/external_comp/bt_fast_pair.rst, samples/bluetooth/fast_pair/input_device/README.rst
Added a note about selecting the input device option in the Device Type field during device model registration in the Google Nearby console.
=> samples: bluetooth: fast_pair: add note about device type in readme

applications/nrf5340_audio/src/modules/audio_sync_timer_rtc.c
After manifest commit 17b4dc7 Zephyr drivers enables the network core twice for bluetooth applications: once by board cpunet reset file, once by HCI driver (nrf53_support.c). The HCI driver uses the cpunet management module which assumes multiple calls to enable function will enable cpunet only once, but as the board cpunet reset doesn't use the management module the network core is started twice which causes application and SDC to have different time references. This change ensures both cores have the sme time reference, and is a workaround while issue is being handled upstream.
OCT-3026
=> applications: nrf5340_audio: Enable RTC timer in audio sync module

CODEOWNERS, include/mpsl/mpsl_pm_utils.h, include/mpsl/mpsl_work.h, subsys/mpsl/CMakeLists.txt, subsys/mpsl/Kconfig, subsys/mpsl/init/mpsl_init.c, subsys/mpsl/pm/CMakeLists.txt, subsys/mpsl/pm/Kconfig, subsys/mpsl/pm/mpsl_pm_utils.c, tests/subsys/mpsl/pm/CMakeLists.txt, tests/subsys/mpsl/pm/pm_test.c, tests/subsys/mpsl/pm/prj.conf, tests/subsys/mpsl/pm/testcase.yaml
This approach enables us to call appropriate Power Management policies
from zephyr Power Management.
Within MPSL a global struct is defined and modified from high priority
context whenever an event is scheduled/rescheduled/...
Within nrf-sdk this global struct is read and appropriate zephyr
functions are called.
Note: If High Prio changed the parameters already before we could
process them, do nothing, we will get back here with next workqueue
item.
Unit Tests are added accordingly.
=> Bluetooth: Controller: Integrate Zephyr PM calls in MPSL

boards/nordic/nrf7002dk/nrf5340_nrf7001_shared_sram_planning_conf.dtsi
Align nRF7001 shared SRAM to fix crashes that occur immediately when running samples/wifi/shell with OpenThread overlay applied.
=> boards: nordic: nrf7002dk: align nRF7001 shared SRAM

boards/nordic/nrf7002dk/nrf5340_cpuapp_common.dtsi, boards/nordic/nrf7002dk/nrf5340_cpuapp_nrf7001_common.dtsi, boards/shields/nrf7002eb/nrf7002eb_coex.overlay, boards/shields/nrf7002ek/nrf7002ek_coex.overlay, boards/shields/nrf7002ek_nrf7000/nrf7002ek_nrf7000_coex.overlay, boards/shields/nrf7002ek_nrf7001/nrf7002ek_nrf7001_coex.overlay, drivers/wifi/nrf700x/Kconfig, drivers/wifi/nrf700x/src/coex.c, drivers/wifi/nrf700x/src/qspi/inc/rpu_hw_if.h, drivers/wifi/nrf700x/src/qspi/src/rpu_hw_if.c, dts/bindings/radio_coex/nordic,nrf700x-coex.yaml, samples/wifi/ble_coex/src/main.c
[SHEL-2535] Rename bt* to sr*. Avoid duplication of functions
and restructure the code.
[SHEL-2535]: https://nordicsemi.atlassian.net/browse/SHEL-2535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ble coex review and revamp

subsys/mgmt/suitfu/src/suitfu_mgmt_suit_image_fetch.c
The URI string is not null-terminated, which results in non-printable characters being transmitted over UART. Use the hexdump log function to print the URI instead.
=> mgmt: prevent unbound printing of URI string

west.yml
Update sdk-zephyr so functional changes aligning PWM driver to nRF54H20 are available.
=> manifest: update sdk-zephyr to have functional support for nRF54H20 PWM - v2.6.99

CODEOWNERS, subsys/sdfw_services/services/extmem/extmem_remote.c, subsys/suit/stream/address_streamer_selector/src/suit_address_streamer_selector.c
Added cache operations to the extmem service to ensure no loss or out-of-date data.
Re-ordered stream sources to ensure that the extmem, which has the highest overhead and lowest probability of being used compared to other sources, is the last source checked.
=> extmem: remote improvements

drivers/wifi/nrf700x/src/wpa_supp_if.c
In case RPU is uninitialized e.g., FW loading failure, then WPA supplicant gets uninitialized extended capabilities from the driver.
Though this doesn't affect directly, but can cause issue without boundary checks. Initialized before the error checks.
Fixes SHEL-2763.
=> drivers: wifi: Fix initialization of extended capabilities length

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
The changelog entry related to IPC service sample
was misplaced under Multicore samples.
Moved it to the proper location under Other samples.
=> doc: move a misplaced changelog entry

applications/nrf5340_audio/Kconfig.defaults, applications/nrf5340_audio/boards/nrf5340_audio_dk_nrf5340_cpuapp.conf, applications/nrf5340_audio/boards/nrf5340_audio_dk_nrf5340_cpuapp_release.conf, applications/nrf5340_audio/boards/nrf5340dk_nrf5340_cpuapp.overlay, applications/nrf5340_audio/src/drivers/CMakeLists.txt, applications/nrf5340_audio/src/drivers/Kconfig, applications/nrf5340_audio/src/modules/CMakeLists.txt, applications/nrf5340_audio/src/modules/Kconfig, applications/nrf5340_audio/src/nrf5340_audio_common.c, applications/nrf5340_audio/src/utils/CMakeLists.txt, applications/nrf5340_audio/src/utils/nrf5340_audio_dk.c
Optionally include HW codec, power measurement and SD card features as these are tied to the nRF5340 audio DK and not the audio application. Move initializations of high frequency clock, button handler and channel assignments from audio DK module and to application.
=> applications: nrf5340_audio: Optionally include nRF5340 ADK features

subsys/bluetooth/mesh/gen_lvl_srv.c
Fixes issue in publishing of generic level status message in response to a move set action. It should use the publishing parameters of the model, not the sender context it received the original message on.
=> Bluetooth: Mesh: Fix status pub for move set in gen_lvl_srv

applications/serial_lte_modem/src/main.c, applications/serial_lte_modem/src/slm_at_fota.c, applications/serial_lte_modem/src/slm_uart_handler.c, modules/trusted-firmware-m/tfm_boards/src/tfm_platform_system.c, subsys/bootloader/bl_storage/bl_storage.c, subsys/dfu/dfu_target/src/dfu_target_smp.c
The commit removes pm_config.h inclusions and other storage headers where are not needed or not used.
=> partition_manager: Remove pm_config.h inclusions where not needed

applications/nrf5340_audio/src/audio/Kconfig, applications/nrf5340_audio/src/bluetooth/Kconfig, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/Kconfig, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Using low latency configuration as default.
* Set transport latency to 5ms
* Set minimal presentation delay to 3ms
* Set prefer minimal presentation delay to 3ms 
OCT-2995
=> applications: nrf5340_audio: Using low latency setting as default

applications/ipc_radio/README.rst, applications/ipc_radio/sample.yaml, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add support for nRF54H20 in ipc_radio application.
Jira: NCSDK-27180
=> applications: Add support for nRF54H20 in ipc_radio

west.yml
Pull in updates of the 'tests/drivers/uart_elementary' suite
=> manifest: Pull in sdk-zephyr with uart_elementary update

scripts/twister/alt/zephyr/tests/drivers/i2c/i2c_bme688/testcase.yaml
'i2c_bme688' is an upstream test
which requires NRF internal SHIELD.
=> tests: drivers: Add alt config for 'tests/drivers/i2c/i2c_bme688'

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/dfu/distributor/README.rst, samples/bluetooth/mesh/dfu/distributor/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/bluetooth/mesh/dfu/distributor/sample.yaml
Add support for nrf54l15pdk_nrf54l15_cpuapp in Mesh DFU Distributor sample.
Removes statement from Distributor sample README which says that the DFU spec is not yet adopted.
=> samples: Bluetooth: Mesh: add nrf54l support for Distributor sample

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/dfu/target/README.rst, samples/bluetooth/mesh/dfu/target/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/bluetooth/mesh/dfu/target/sample.yaml
Add support for nrf54l15pdk_nrf54l15_cpuapp in Mesh DFU Target sample.
Removes statement from Target sample README which says that the DFU spec is not yet adopted.
=> samples: Bluetooth: Mesh: add nrf54l support for Target sample

west.yml
Pull documentation page that contains the initial nRF RPC protocol specification.
=> nrf_rpc: pull protocol specification

applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c, applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c, applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.h, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c, applications/nrf5340_audio/unicast_client/Kconfig.defaults, applications/nrf5340_audio/unicast_client/main.c, applications/nrf5340_audio/unicast_server/Kconfig.defaults, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- Use CAP procedure for starting and stopping streams
- Play/pause enabled for both sink and source in bidirectional mode
- OCT-2542
=> applications: nrf5340_audio: Use CAP procedures for unicast_server

doc/_extensions/table_from_rows.py
Twister files support giving extra_args as string or list. Until now, lists haven't been used, but when used they'll cause the extension to crash producing cryptic Sphinx errors.
=> doc: extensions: table_from_rows: handle extra_args as list

lib/lte_link_control/lte_lc.c, lib/lte_link_control/lte_lc_helpers.c, lib/lte_link_control/lte_lc_helpers.h, lib/lte_link_control/lte_lc_modem_hooks.c, tests/lib/lte_lc/src/main.c, tests/lib/lte_lc_api/src/lte_lc_api_test.c
lte_lc used to enable eDRX with AT+CEDRXS and send AT%XPTW immediately after. This causes an unnecessary TAU when PTW is set same value that network reported.
Now AT%XPTW is not sent if PTW value given by the network is the one we are supposed to request.
Jira: NRF91-2041
TODO:
=> lib: lte_link_control: Avoid unnecessary eDRX enable

subsys/bluetooth/mesh/gen_lvl_srv.c
Changes the generic level server CB to only do publishing if the incoming message is a new transaction.
=> Bluetooth: Mesh: Reduce gen_lvl_srv set publication

samples/matter/common/src/util/finite_map.h
Insert method returns true in case there is no place to put new object, what is counterintuitive.
=> samples: matter: Fixed FinitMap Insert implementation

subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c
The `PGPS_EVT_AVAILABLE` event was skipped also when predictions had been downloaded during library initialization, but no prediction had been injected to GNSS. This behavior was introduced in https://github.com/nrfconnect/sdk-nrf/commit/9c58294a79467bac17103e0a0d7a5bede209906e. This broke the P-GPS support at least in the modem_shell sample, but could also affect end user applications.
=> net: lib: nrf_cloud: Fix for PGPS_EVT_AVAILABLE not being sent

subsys/suit/cache/Kconfig, subsys/suit/cache/src/suit_dfu_cache_rw.c
The SUIT cache partitions 1..n may contain left-over data after the last update. To ensure that the cache does not contain left-over data, the partition is erased if it were not empty already.
This can be enabled or disabled with SUIT_CACHEX_ERASE_ON_INIT Kconfig.
=> suit: add option to erase cache on init

doc/nrf/device_guides/working_with_fem.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.6.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
The Front-end module user guide contains misleading information and has several incomplete sections. This commit fixes that by restructuring, clarifying and completing the documentation.
=> doc: improve FEM user guide

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/common/src/app/fabric_table_delegate.h, west.yml
- Repaired a reaction on the last fabric removal when the CONFIG_CHIP_LAST_FABRIC_REMOVED_ERASE_AND_PAIRING_START option is selected.
- Cherry-picked a commit from Matter upstream to disable the IPv6 interface after the factory reset.
- Enabled clearing SRP host services on factory reset.
This repairs a known issue: KRKNWK-18916
=> samples: matter: Repair reaction to last fabric removal

samples/wifi/shell/src/main.c
In order to add support for nRF54H20DK commit 5a20cee36f3 ("samples: wifi: shell: Fix nRFx clock configuration) introduced a regression where instead of choosing one of the clock sources HF or HF192M, it enforced both to be available, this causes the CPU to be stuck at lower frequency impacting peak performance.
Fixes SHEL-2771.
=> samples: wifi: shell: Fix HF CPU frequency configuration

applications/matter_bridge/prj.conf, applications/matter_bridge/prj_release.conf, applications/matter_weather_station/prj.conf, applications/matter_weather_station/prj_release.conf, doc/nrf/protocols/matter/getting_started/low_power_configuration.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/light_bulb/README.rst, samples/matter/light_bulb/prj.conf, samples/matter/light_bulb/prj_release.conf, samples/matter/light_switch/README.rst, samples/matter/light_switch/prj.conf, samples/matter/light_switch/prj_release.conf, samples/matter/lock/README.rst, samples/matter/lock/prj.conf, samples/matter/lock/prj_release.conf, samples/matter/lock/prj_thread_wifi_switched.conf, samples/matter/template/prj.conf, samples/matter/template/prj_release.conf, samples/matter/thermostat/prj.conf, samples/matter/thermostat/prj_release.conf, samples/matter/window_covering/README.rst, samples/matter/window_covering/prj.conf, samples/matter/window_covering/prj_release.conf
Enabled by default BLE extended announcement in all Matter samples. Also, enabled pairing autostart in Window Covering and Light Switch samples (according to spec all devices shall use it besides door lock, or define custom commissioning flow).
=> samples: matter: Enabled BLE extended announcement

samples/suit/smp_transfer/sample.yaml, samples/suit/smp_transfer/sysbuild.cmake
The smp_transfer needs to be able to access the value of SB_CONFIG_SUIT_ENVELOPE_SEQUENCE_NUM inside the source code for demonstration purposes.
The value of SB_CONFIG_SUIT_ENVELOPE_SEQUENCE_NUM is propagated into CONFIG_SUIT_ENVELOPE_SEQUENCE_NUM, which is defined locally for the sample.
=> samples: suit: propagate SB_CONFIG_SUIT_ENVELOPE_SEQUENCE_NUM

applications/nrf_desktop/src/modules/Kconfig.usb_state, applications/nrf_desktop/src/modules/hid_forward.c, applications/nrf_desktop/src/modules/usb_state.c
Change cleans up USB state application module implementation and aligns Kconfig configuration dependencies to allow integrating USB next stack. The module can only be built with USB next stack - the USB next API is not yet used.
Jira: NCSDK-27014
=> applications: nrf_desktop: Cleanup USB state module

applications/nrf5340_audio/src/audio/Kconfig, applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c, applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c
OCT--2976
Ensure the preferred presentation delay is within the range of the	min and max delays, rail if not.
Search for the presentation delay function updated to search over the end points for the direction.
=> applications: nrf5340_audio: Rail the presentation delay.

applications/nrf_desktop/src/modules/hid_state.c, applications/nrf_desktop/src/modules/hids.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
PR fixes emitting error logs:
* in `hid_state` module:
The "Error while sending report" log should not use error log level. It may appear for example during disconnection of a HID transport.
*  in `hids` module:
Functions that send GATT notification with HID report may return `-EACCES` if HID report is sent right after remote peer unsubscribes. HIDS library uses an asynchronous callback to indicate subscription state changes. `hid_notification_event` is used to synchronize handling of the subscription state changes. Processing of the event introduces a delay which may lead to trying to send a GATT notification by HIDS application module after the asynchronous callback was called.
Change adds a warning log to avoid displaying an error log under the circumstances described above.
Jira: …
=> applications: nrf_desktop: Fix emitting error logs in HIDS module and HID state module

west.yml
Update sdk-mcuboot to romeve warnigs with cleanup
unusable slot when direct xip mode is enabled.
=> manifest: update sdk-mcuboot, fix build warnings

doc/nrf/device_guides/working_with_nrf/nrf91/nrf9161.rst, doc/nrf/links.txt
The link to the nRF9161 board control section was missing both from the guide and the links.txt file. Added now.
=> doc improvement: adding link to nRF9161 guide

samples/matter/light_bulb/sysbuild/ipc_radio/prj.conf, samples/matter/light_switch/sysbuild/ipc_radio/prj.conf, samples/matter/lock/sysbuild/ipc_radio/prj.conf, samples/matter/template/sysbuild/ipc_radio/prj.conf, samples/matter/thermostat/sysbuild/ipc_radio/prj.conf, samples/matter/window_covering/sysbuild/ipc_radio/prj.conf
This adds missing prj.conf file for matter samples ipc radio network core image.
=> samples: matter: Fix ipc_radio image configuration

scripts/requirements-build.txt, scripts/requirements-fixed.txt, west.yml
Update nrf-regtool to v5.3.0 which is able to set CTRLSEL for most peripherals automatically.
Update sdk-zephyr to pull in a change that increases the number of ports supported by the NRF_PSEL macro, which is required alongside the nrf-regtool version.
=> scripts: requirements-build: update nrf-regtool to 5.3.0

scripts/requirements-build.txt, scripts/requirements-fixed.txt, west.yml
Update nrf-regtool to v5.3.0 which is able to set CTRLSEL for most peripherals automatically.
Update sdk-zephyr to pull in a change that increases the number of ports supported by the NRF_PSEL macro, which is required alongside the nrf-regtool version.
=> [v2.6.99-cs2] update nrf-regtool to v5.3.0

Jenkinsfile
On v2.6.99-cs2-branch sdk-zephyr's test suite is disabled.
=> ci: Use pipeline from v2.6.99-cs2-branch

samples/matter/light_bulb/src/light_bulb.zap, samples/matter/light_bulb/src/zap-generated/IMClusterCommandHandler.cpp, samples/matter/light_bulb/src/zap-generated/endpoint_config.h
Enable mandatory CopySceneResponse command in Scene Management Cluster in light bulb sample.
=> samples: matter: light_bulb: enable mandatory resposne command in zap

applications/serial_lte_modem/src/slm_ppp.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/modem/pdn.h, lib/pdn/pdn.c
The MTU parameter is optional in `+CGCONTRDP`.
Let `pdn_dynamic_params_get()` handle this scenario without raising an error.
Additionally, make all parameters optional, that is, passing `NULL` prevents the information to be copied in the parameters.
=> lib: pdn: do not error in `pdn_dynamic_params_get()` when MTU is missing

applications/nrf5340_audio/src/nrf5340_audio_common.c, applications/nrf5340_audio/src/utils/channel_assignment.c, applications/nrf5340_audio/src/utils/channel_assignment.h
Move initialization of the channel assignment module to APPLICATION level of SYS_INIT. This ensures that the module is initialized correctly before any code references it - regardless if app is running on audio DK or not.
OCT-3029
=> applications: nrf5340_audio: SYS_INIT channel assignment module

cmake/sysbuild/suit.cmake, west.yml
Allow usage of custom vid/cid defined using SUIT MPI settings.
```
west build -b nrf54h20dk/nrf54h20/cpuapp --sysbuild -p -- -DFILE_SUFFIX=bt -DCONFIG_SUIT_MPI_APP_LOCAL_1_CLASS_NAME=\"test_acme_application\" -DCONFIG_SUIT_MPI_RAD_LOCAL_1_CLASS_NAME=\"test_acme_radio\" -DCONFIG_SUIT_MPI_APP_LOCAL_1_VENDOR_NAME=\"acme.com\" -DCONFIG_SUIT_MPI_RAD_LOCAL_1_VENDOR_NAME=\"acme_radio.com\"
```
Ref: NCSDK-27373
=> suit: allow usage of custom vid/cid

modules/trusted-firmware-m/Kconfig.peripheral_secure, modules/trusted-firmware-m/tfm_boards/common/tfm_hal_platform.c
Mitigate the risk of pin security misconfiguration by giving more reasonable default values and by logging which pins are configured as secure.
=> Mitigate risk of pin security misconfiguration

subsys/suit/stream/stream_sinks/src/suit_extmem_sink.c
Drop `extmem_area_end` from `is_address_supported()`.
=> suit: stream: extmem: Remove unused variable

doc/nrf/config_and_build/config_and_build_system.rst, doc/nrf/device_guides/working_with_nrf/nrf70/developing/fw_patches_ext_flash.rst, doc/nrf/device_guides/working_with_nrf/nrf91/nrf91_snippet.rst, doc/nrf/protocols/thread/certification.rst, doc/nrf/protocols/wifi/debugging.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Moved info about snippets from VSC extension docs to where it should belong.
=> doc: snippets: move info from VSC extension docs

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/light_ctrl/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/bluetooth/mesh/light_ctrl/sample.yaml, samples/bluetooth/mesh/light_ctrl/src/main.c
This adds support for the nRF54L15 PDK to the light_ctrl sample. It changes the interrupt line used, as the one that was there was not available on the nRF54L15.
Note: Currently, there is an issue with PWM LEDs on the nRF54L15 PDK where the LED dims inverted. I have not handled this here, since the same incorrect behavior shows up in other samples and I expect it to be fixed in Zephyr.
=> Samples: Bluetooth: Mesh: add nRF54L15 support to light_ctrl

samples/nrf5340/extxip_smp_svr/child_image/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/nrf5340/extxip_smp_svr/child_image/mcuboot/boards/thingy53_nrf5340_cpuapp.overlay
Adds back files that were removed in the child/parent image cleanup for a sample that has not been converted
=> samples: nrf5340: extxip_smp_svr: Add in accidentally removed files

include/bluetooth/services/fast_pair/fast_pair.h
Improved the documentation for the bt_fast_pair_enable and the bt_fast_pair_factory_reset API functions in the Fast Pair header file to describe additional requirements for the FMDN extension.
Ref: NCSDK-25234
=> bluetooth: fast_pair: improve doc for enable and factory reset APIs

samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp_0_2_1.overlay, samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp_0_3_0.overlay, samples/matter/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/matter/thermostat/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/matter/window_covering/boards/nrf54l15pdk_nrf54l15_cpuapp_0_2_1.overlay, samples/matter/window_covering/boards/nrf54l15pdk_nrf54l15_cpuapp_0_3_0.overlay
Disable previously used UART30 and switch to the default UART20. It means that from now the second port of the PDK's VCOM will be in use.
=> samples: matter: Switch VCOM to the default UART20 on nRF54L15 PDK

applications/nrf5340_audio/tools/buildprog/buildprog.py
Update which hex files are used for flashing by buildprog, as these have changed with the introduction of sysbuild.
=> applications: nrf5340_audio: Update paths for hex files in builprog

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/udp/src/main.c
This commit updates the sample to use the `SO_RAI` socket option and removes the use of deprecated RAI socket options `SO_RAI_ONGOING` and `SO_RAI_NO_DATA`.
=> samples: cellular: udp: remove use of deprecated RAI

subsys/nrf_security/Kconfig.psa
Increase the range of the available PSA slots because some use cases require more than 64. The maximum number is an educated guess, I don't expect that any application will need more than 65K keys in our devices.
=> nrf_security: Increase range of PSA key slots

samples/wifi/shell/overlay-openthread.conf
Since it is required by WIFI.
Ref: SHEL-2566
=> samples: wifi: Enable SHA1

samples/matter/window_covering/pm_static_nrf54l15pdk_nrf54l15_cpuapp_release.yml, scripts/quarantine.yaml, scripts/quarantine_windows_mac.yaml
Due to current issue with memory overflow for specific configuration on nRF7002 DK in Matter samples, these configuration are disabled to build in CI.
Additionally the commit include quick fix in pm_static definition for Matter Window Covering sample on nRF54L15.
=> quarantine: add specific Matter samples/app to quarantine

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud_coap.h, samples/cellular/nrf_cloud_multi_service/src/shadow_support_coap.c, subsys/net/lib/nrf_cloud/coap/include/nrf_cloud_coap_transport.h, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c
Expose transport functions so that external coap_client instances can be used with nRF Cloud.
IRIS-8806
=> net: lib: nrf_cloud_coap: expose CoAP transport functions

applications/nrf_desktop/sample.yaml
Change fixes release Fast Pair configuration for nrf52840gmouse. The configuration must explicitly disable B0 bootloader.
Jira: NCSDK-27571
=> applications: nrf_desktop: Fix sample.yaml

subsys/suit/memory_layout/src/suit_memory_layout.c
The memory range checks were off by one, which could result the following example scenario to yield a wrong result:
Memory region has 32kB and begins at address 0x0. A range check with parameters address=0x0 and size=32kB should return true. However, due to off by one error, the end address was actually calculated as 0x8000, which is outside of the memory region. The funcion would return false.
The implementation was changed to subtract one byte from end address to ensure it falls within the region.
Also zero-sized range checks are now treated as one-byte range checks.
=> suit: fix off by one error in address range check

scripts/quarantine_integration.yaml
For:
nrf/tests/subsys/bootloader
nrf/samples/bootloader
nrf/samples/event_manager_proxy
nrf/applications/machine_learning
=> scripts: add integration quarantine part 14

doc/nrf/releases_and_maturity/known_issues.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/zigbee/osif/zb_nrf_transceiver.c
Zephyr's net packet data handling APIs were modified.
KRKNWK-19026
=> zigbee: use proper API to get RSSI

doc/nrf/external_comp/bt_fast_pair.rst
Aligned the name of the Kconfig option that is used to trigger the Fast Pair provisioning script during the build process.
=> doc: external comp: fast_pair: align kconfig name for script trigger

cmake/sysbuild/b0_packaging.cmake, sysbuild/CMakeLists.txt
Adds a dfu_application.zip output file which contains the update bin files when secure boot is used without MCUboot being enabled
=> sysbuild: Add b0 zip update output generation without MCUboot

subsys/suit/provisioning/CMakeLists.txt
The SUIT storage address is currently defined only for nRF54H20 devices.
=> suit: fix: Limit suit storage address to nRF54H20

samples/cellular/lwm2m_client/src/main.c
LwM2M engine recovers automatically from following events:
* LWM2M_RD_CLIENT_EVENT_REGISTRATION_FAILURE
* LWM2M_RD_CLIENT_EVENT_REG_TIMEOUT
So the application does not need to stop&restart the client.
=> samples: lwm2m-client: Don't unnecessary stop the client

include/bluetooth/services/fast_pair/uuid.h, subsys/bluetooth/services/fast_pair/fmdn/include/fp_fmdn_beacon_actions.h
Added the Beacon Actions characteristic UUID, that is used by the Find My Device Network (FMDN) extension, to the Fast Pair UUID header.
=> bluetooth: fast_pair: uuid: add beacon actions uuid to the api header

samples/ipc/ipc_service/Kconfig
This removes stale childimage configuration related Kconfigs options from IPC sample
=> IPC service sample remove stale configuration

doc/nrf/protocols/matter/end_product/test_event_triggers.rst, samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp_0_2_1.overlay, samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp_0_3_0.overlay, samples/matter/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/matter/thermostat/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/matter/window_covering/boards/nrf54l15pdk_nrf54l15_cpuapp_0_2_1.overlay, samples/matter/window_covering/boards/nrf54l15pdk_nrf54l15_cpuapp_0_3_0.overlay
Some parts of the event triggers guide have not been aligned with the recent changes.
wdt30 is reserved for Secure purposes and we need to switch to the wdt31 instance for application purposes.
=> Fix Event triggers docs and switch watchdog instance for nrf54l15

drivers/wifi/nrf700x/src/work.c, modules/hostap/src/supp_main.c
Set names to Wi-Fi ralated stacks.
Fixes SHEL-2547
=> drivers: wifi: Set names to Wi-Fi related stacks

subsys/net/lib/nrf_cloud/coap/include/nrf_cloud_coap_transport.h
Fix non-CoAP builds with NRF_CLOUD_LOG_BACKEND enabled.
=> net: lib: nrf_cloud: fix non-coap logging build

applications/nrf_desktop/configuration/nrf52840dk_nrf52840/app_mcuboot_qspi.overlay
Use build type specific DTS overlays for nRF52840DK to clean up configuration and avoid enabling unnecessary features.
Jira: NCSDK-27014
=> applications: nrf_desktop: Use build type specific DTS overlays

modules/hostap/src/supp_events.c
[SHEL-2326] When user tries to disconnect the shell, it's always printing "Disconnection request failed". Here setting status as 0 when disconnection is requested by user. (wifi disconnect command). If disconnection happens due to any other reason, it will take reason code.
[SHEL-2326]: https://nordicsemi.atlassian.net/browse/SHEL-2326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> wifi: hostap: Fix user disconnection request

doc/nrf/config_and_build/config_and_build_system.rst, doc/nrf/config_and_build/configuring_app/cmake/index.rst, doc/nrf/config_and_build/multi_image.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.7.rst, doc/nrf/shortcuts.txt
Added or updated deprecation notes for features that will be replaced by sysbuild.
Updated CMake option list with image-related variables. Updated the migration guide with generic notice.
=> doc: sysbuild: add related deprecation notes

doc/nrf/libraries/security/bootloader/bl_storage.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bootloader/README.rst, samples/bootloader/sample.yaml
nrf9151 and nrf9161 to tests and documentation.
This stems from adding nrf9151 and nrf9161 support for crypto and security samples.
=> samples: bootloader: Add 9151 and 9161 support

modules/nrfxlib/nrf_802154/sl/platform/nrf_802154_platform_sl_lptimer_grtc_hw_task.c, modules/nrfxlib/nrf_802154/sl/platform/nrf_802154_platform_timestamper.c
FIxes IPC declarations for nRF54H20 build with IEEE 802.15.4
=> Fixes to support 802.15.4 on nRF54H20

doc/nrf/links.txt
Updated entries pointing to the VSC extension docs in links.txt.
=> doc: update VSC extension links in links.txt

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/at_host/Kconfig
Use CRLF termination as default as that is the standard AT termination characters and also used by the Serial Terminal in nRF Connect for Desktop.
=> lib: at_host: use CRLF termination as default

doc/nrf/libraries/bluetooth_services/mesh/model_types.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added a paragraph to model_types.rst in the Bluetooth Mesh library documentation to explain restrictions on using blocking API calls.
=> Bluetooth: Mesh: Add note on blocking API calls to CLI headers

modules/trusted-firmware-m/Kconfig
Encryption of ITS on 54L is broken so we stop enabling it by default.
Allowing ITS to be used on 54L while we debug encryption of ITS.
=> tfm: 54l: Stop encrypting ITS by default

west.yml
Fixes data type for time.
Fixes SHEL-2731.
=> manifest: sdk-hostap: Pull fix for time

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/nrf_cloud_multi_service/src/cloud_connection.c, samples/cellular/nrf_cloud_multi_service/src/cloud_connection.h, samples/cellular/nrf_cloud_multi_service/src/fota_support_coap.c, samples/cellular/nrf_cloud_multi_service/src/location_tracking.c, samples/cellular/nrf_cloud_multi_service/src/shadow_support_coap.c, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_coap, subsys/net/lib/nrf_cloud/coap/include/nrf_cloud_coap_transport.h, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c, subsys/net/lib/nrf_cloud/coap/src/nrfc_dtls.c
Enable the SO_KEEPOPEN socket option to reduce the need to close and reopen the socket and perform DTLS negotiation whenever the PDN disconnects and reconnects or LTE goes offline and online.
Store paused condition whether session pause/resume succeeded or not. Use to determine if ready to perform a request. Set a finite timeout for callback from NON transfers. When CoAP socket is paused, prevent outgoing requests. Fix error handling in client_transfer() so serial_sem is not left open. Cancel ongoing coap_client requests when pausing or disconnecting. If we cannot save the CID when pausing, we will need to do a full reconnect. When receiving a callback, validate the user_data thoroughly. Initialize the result code to an error value rather thanstart uninitialized.
Jira: IRIS-8593
=> net: lib: nrf_cloud_coap: Enable SO_KEEPOPEN

applications/serial_lte_modem/src/slm_at_host.c
Calling slm_at_send_indicate() before the AT backend is initialized will dereference a NULL pointer, which may happen as several modules can dispatch custom notifications at any point.
=> applications: serial_lte_modem: check for uninitialized send callback

tests/bluetooth/tester/sysbuild.conf
Disables partition manager for the BT tester. After migration to sysbuild, the partition manager was enabled by default.
=> Bluetooth: Tester: Disable partition manager

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/crypto/ecjpake/boards/nrf9161dk_nrf9161.conf, samples/crypto/ecjpake/boards/nrf9161dk_nrf9161_ns.conf, samples/crypto/rng/prj.conf, samples/crypto/rsa/prj.conf, samples/crypto/spake2p/boards/nrf9161dk_nrf9161_ns.conf, samples/tfm/provisioning_image/sample.yaml, samples/tfm/tfm_hello_world/boards/nrf9161dk_nrf9161_ns.conf, samples/tfm/tfm_hello_world/sample.yaml, samples/tfm/tfm_psa_template/boards/nrf9161dk_nrf9161_ns.conf, samples/tfm/tfm_psa_template/sample.yaml, samples/tfm/tfm_secure_peripheral/boards/nrf9161dk_nrf9161_ns.conf, samples/tfm/tfm_secure_peripheral/boards/nrf9161dk_nrf9161_ns.overlay, samples/tfm/tfm_secure_peripheral/sample.yaml, tests/crypto/README.rst, tests/crypto/testcase.yaml, tests/tfm/secure_services/testcase.yaml, tests/tfm/tfm_psa_test/README.rst, tests/tfm/tfm_psa_test/testcase.yaml, tests/tfm/tfm_regression_test/README.rst, tests/tfm/tfm_regression_test/testcase.yaml
* Add 9161 support to t-fm samples and tests
* Add 9161 support to crypto tests and samples
=> TF-M and Crypto samples: add 9161 support

doc/nrf/links.txt
Updated entries pointing to the old doc site.
While at it, fixed a few Infocenter links as well.
=> doc: update nRF Asset Tracker links in links.txt

samples/zigbee/light_switch/sample.yaml, samples/zigbee/light_switch/sysbuild_fota.conf
Enable west build of FOTA variant.
=> samples: zigbee: move FOTA sysbuild configuration to a conf file

doc/nrf/releases_and_maturity/known_issues.rst
Add a known issue for an assert on the Sofdevice Controller peripheral which may happen after receiving a connection update indication.
There is currently no known workaround.
=> doc: Add known issue for SDC peripheral assert

applications/serial_lte_modem/Kconfig, applications/serial_lte_modem/doc/CMUX_AT_commands.rst, applications/serial_lte_modem/doc/GNSS_AT_commands.rst, applications/serial_lte_modem/doc/nRF91_as_Zephyr_modem.rst, applications/serial_lte_modem/src/gnss/Kconfig, applications/serial_lte_modem/src/gnss/slm_at_gnss.c, applications/serial_lte_modem/src/slm_cmux.c, applications/serial_lte_modem/src/slm_cmux.h, applications/serial_lte_modem/src/slm_ppp.c, applications/serial_lte_modem/src/slm_uart_handler.c
Allow GNSS NMEA sentences to be output on a dedicated CMUX channel.
This is for the still in-progress integration of SLM with Zephyr's GNSS (and cellular) driver.
=> applications: serial_lte_modem: GNSS NMEA output on its own CMUX channel

drivers/wifi/nrf700x/Kconfig, drivers/wifi/nrf700x/inc/net_if.h, drivers/wifi/nrf700x/src/net_if.c
Adds random run-time generated MAC address as a Kconfig
Also adds build asserts to; ensure that a fixed MAC address
is of the correct length, ensure that fixed and random MAC
addresses are not enabled at the same time.
Signed-off-by: Helmut Lord <kellyhlord@gmail.com>
=> drivers: wifi: add random MAC

drivers/wifi/nrf700x/inc/fmac_main.h, drivers/wifi/nrf700x/src/fmac_main.c, drivers/wifi/nrf700x/src/wpa_supp_if.c, modules/hostap/src/supp_api.c, west.yml
Memory leak fixes and misc improvements.
UMAC team for reviewing the removal of per-iface extended capabilities.
=> wifi: Fix memory leaks

boards/shields/pca63566/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
Instance 130 can't be i2c and spi at the same time.
Fix build error resulting from not enabled DTS nodes.
=> bords: shields: pca63566: Fix overlay for nrf54h20

applications/nrf5340_audio/Kconfig, applications/nrf5340_audio/broadcast_source/main.c, applications/nrf5340_audio/include/nrf5340_audio_common.h, applications/nrf5340_audio/src/bluetooth/bt_management/advertising/bt_mgmt_adv.c, applications/nrf5340_audio/src/bluetooth/bt_management/advertising/bt_mgmt_adv_internal.h, applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c, applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.h, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.h, applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c, applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.h, applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h, applications/nrf5340_audio/unicast_server/main.c
- Allow user to input their own create_param
- Create helper function to produce create_param
- Alter the API of broadcast_source_enable to take in a struct.
- Struct will determine the number of subgroups, BISes and their info.
- OCT-3016
=> applications: nrf5340_audio: Expand broadcast_source_enable

subsys/suit/provisioning/soc/Kconfig.nrf54h20
Enabling this by default caused the devices fail to boot after flashing.
=> suit: disable recovery mpi generation by default

subsys/net/openthread/Kconfig.defconfig
Remove not needed konfigs related to rng and IPC.
Change crypto backend to Nordic security.
=> kconfig: openthread: Change konfigs for nrf54.

subsys/bluetooth/mesh/scheduler_srv.c
Warning reported by Coverity, fix done to
remove warning.
Overflowed integer argument (INTEGER_OVERFLOW)
=> Bluetooth: Mesh: Coverity warning fixed

applications/connectivity_bridge/boards/thingy91x_nrf5340_cpuapp.overlay, applications/connectivity_bridge/sample.yaml, applications/connectivity_bridge/src/modules/ble_handler.c, boards/nordic/thingy91x/thingy91x_nrf5340_cpuapp_common.dts, doc/nrf/includes/sample_board_rows.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
For enabling BLE on the thingy91x, the short range RF Front end module needs to be enabled. This patch enables it when BLE is needed and disables it otherwise. It does so only for the boards that have the short range rf froend end module in device tree. The zephyr,user node is used for this purpose.
=> applications: connectivity_bridge: Enable BLE on thingy91x

doc/nrf/samples.rst, doc/nrf/samples/fast_pair.rst, samples/bluetooth/fast_pair/input_device/README.rst, samples/bluetooth/fast_pair/locator_tag/README.rst
Aligned names of Fast Pair samples with their new documentation location.
=> samples: bluetooth: fast_pair: align sample name with new doc location

subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_primitives.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_derivation.c
Add states for PSA_ALG_TLS12_ECJPAKE_TO_PMS so
functions like set_capacity works as expected.
=> cracen: Fix for EC J-PAKE to PMS KDF

cmake/sysbuild/suit.cmake, samples/suit/recovery/Kconfig, samples/suit/recovery/app_recovery_envelope.yaml.jinja2, samples/suit/smp_transfer/sample.yaml, subsys/suit/provisioning/soc/Kconfig.nrf54h20, sysbuild/CMakeLists.txt, sysbuild/Kconfig.suit
This PR allows to build the recovery image as a child image of a main application by using the SB_CONFIG_SUIT_BUILD_RECOVERY option.
=> suit: build recovery image from main application

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/location/Kconfig, lib/location/method_gnss.c, samples/cellular/modem_shell/sample.yaml
Added support for sending GNSS coordinates to nRF Cloud. This is only supported with nRF Cloud and is configured with a Kconfig option.
Jira: NCSDK-24322
=> lib: location: Send GNSS coordinates to nRF Cloud

doc/nrf/external_comp/dult.rst, doc/nrf/integrations.rst, doc/nrf/libraries/others/dult.rst, doc/nrf/links.txt, include/dult.h
Follow-up upstreaming activity for the documentation content after the following PR (sample Readme):
https://github.com/nrfconnect/sdk-nrf/pull/15412
=> FMDN upstream part 7: DULT documentation

boards/shields/nrf700x_nrf54l15pdk/nrf700x_nrf54l15pdk.overlay, scripts/quarantine.yaml
Remove FLPR RAM partition as Wi-Fi doesn't use to fix the RAM overflow.
Fixes SHEL-2832.
=> shields: nrf54l15pdk: Fix RAM overflow

samples/matter/lock/src/access/access_manager_credentials.cpp
... on fabric removal. This patch makes sure that we don't overwrite the credentials that are not supposed to be cleared when the given fabric is removed.
=> samples: matter: fix CredentialsManager credentials clearing

drivers/wifi/nrf700x/src/qspi/inc/spi_if.h, drivers/wifi/nrf700x/src/qspi/src/device.c, drivers/wifi/nrf700x/src/qspi/src/spi_if.c, drivers/wifi/nrf700x/src/shim.c, west.yml
De-initialization sequence in nRF70 driver was not properly implemented and has never been tested (init + reboot was the usecase), but we need this to work properly in order to put RPU in lowest power state, recover RPU etc.
This PR fills the gaps, fixes race conditions etc to solve numerous crashes.
Note: needs to be rebase once https://github.com/nrfconnect/sdk-nrf/pull/15599 is merged (top two commits are taken from this PR to enable tests/build).
=> wifi: Fix de-initialization sequence

samples/wifi/provisioning/ble/Kconfig.sysbuild
The sample is not included in recent effort to convert to sysbuild manner. Add the missing kconfig file to enable hci_ipc for net core.
The kconfig file is copied from https://github.com/nrfconnect/sdk-nrf/pull/15435
=> sample: wifi_privisioning: add missing sysbuild file

applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
- Remove double adv start after directed adv times out
- OCT-NONE
=> applications: nrf5340_audio: Remove double adv start

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_security.c
Enable socket option SO_KEEPOPEN for hardware that supports modem FW 2.0.1.
This allows LwM2M engine to resume DTLS CID connection even after network have been lost for a while.
=> net: lwm2m_client_utils: Enable SO_KEEPOPEN

doc/nrf/protocols/matter/getting_started/adding_clusters.rst, doc/nrf/protocols/matter/getting_started/hw_requirements.rst, doc/nrf/protocols/matter/getting_started/tools.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- Removed the obsolete ZAP tool guides.
- Added guides for Matter west commands.
- Updated the adding cluster section with the new ZAP tool west commands.
=> doc: matter: Added documentation to Matter west commands

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, modules/memfault-firmware-sdk/memfault_lte_metrics.c
The connectivity stats should not be reset when samplet, as that may result in an accumulated rounding error over time due to the kilobyte resolution of the counters.
=> modules: memfault: Avoid resetting connectivity stats when sampling

samples/cellular/location/sample.yaml
Moved Thingy:91 X and added Thingy:91 into the default configuration. Added `integration_platforms` parameter for the Thingy:91 X Wi-Fi configuration.
=> samples: cellular: location: Fix Thingy:91 configurations in sample.yaml

samples/cellular/modem_shell/src/location/location_shell.c
Used satellites were printed from satellites_tracked instead of satellites_used variable.
=> samples: cellular: modem_shell: location: Satellites used printed wrong

boards/deprecated.cmake
This was missed in the original commit, add support for backward compatibility and also mark old naming as deprecated.
=> boards: Add Wi-Fi boards backward compatibility

doc/nrf/libraries/networking/nrf_cloud_coap.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud_coap.h, lib/location/cloud_service/cloud_service_nrf.c, samples/cellular/nrf_cloud_multi_service/src/cloud_connection.c, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_coap, subsys/net/lib/nrf_cloud/coap/include/nrf_cloud_coap_transport.h, subsys/net/lib/nrf_cloud/coap/include/nrfc_dtls.h, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c, subsys/net/lib/nrf_cloud/coap/src/nrfc_dtls.c
Now that cloud support is released, enable CoAP support for the ground fix configuration flags do_reply, hi_conf, and fallback.
Also set default value for .config to NULL when initializing struct nrf_cloud_rest_location_request in the location library. This structure is shared for REST and CoAP use.
Improve recent SO_KEEPOPEN support to better handle mfw_2.0.0.
Jira: IRIS-9014
=> net: lib: nrf_cloud_coap: Enable ground fix conf

cmake/sysbuild/provision_hex.cmake, cmake/sysbuild/sign.cmake
Fixes an issue with sysbuild whereby settings were changed and the provision data was not re-generated, which would then cause an unbootable image
=> sysbuild: Fix issue with re-generating provision data

samples/cellular/nrf_cloud_multi_service/Kconfig, samples/cellular/nrf_cloud_multi_service/prj.conf, samples/cellular/nrf_cloud_multi_service/sample.yaml
Not enough RAM to build the coap + nrf_provisioning + modem_trace combination. Lowering heap usage to make space.
=> samples: nrfcloud_multi_service: Decrease heap usage

doc/nrf/external_comp/bt_fast_pair.rst
Follow-up upstreaming activity for the documentation content after the following PR (DULT documentation):
https://github.com/nrfconnect/sdk-nrf/pull/15643
=> FMDN upstream part 8: Fast Pair Integration guide update with the FMDN content

subsys/net/lib/lwm2m_client_utils/lwm2m/ground_fix_obj.c
When we receive Ground Fix results from the server, it helps testing to see the result code on debug output.
=> net: lwm2m_client_utils: Add debug print for ground fix result

samples/matter/light_bulb/sample.yaml, scripts/quarantine_integration.yaml
Sample light bulb with psub merged with sample with mem profiling.
=> samples: matter: light bulb psub merged with mem profiling

applications/nrf5340_audio/include/nrf5340_audio_common.h, applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c, applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.h, applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_conn.c, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c, applications/nrf5340_audio/unicast_client/main.c
- Use SIRK to discover and connect to other members of the same set.
- If device is not part of set, scan by device name as normal.
- Move restart of scanning after connected to one device to main.
- OCT-3024
=> applications: nrf5340_audio: Implement parts of CSIP

doc/nrf/libraries/security/nrf_security/doc/driver_config.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
PBKDF2 algorithms are supported with TF-M
Removed note in nrf_security lib stating the opposite Added an entry in changelog for TF-M
=> doc: Support for PBKDF2 algorithms with TF-M

applications/nrf5340_audio/doc/requirements.rst, doc/nrf/libraries/others/emds.rst, doc/nrf/protocols/bt/bt_qualification/index.rst, doc/nrf/protocols/thread/certification.rst, doc/nrf/test_and_optimize/optimizing/power_general.rst
Several places Infocenter is mentioned as the source of documentation for e.g. product specification and comp matrices.
Rewriting to remove its mentions.
=> doc: Remove infocenter mentions

doc/nrf/libraries/modem/lte_lc.rst
Mention that modem library is required to run
the LTE link control library.
=> doc: mention modem library in the link ctrl docs

doc/nrf/libraries/bluetooth_services/services/fast_pair.rst
Follow-up upstreaming activity for the documentation content after the following PR (Fast Pair user guide documentation update):
https://github.com/nrfconnect/sdk-nrf/pull/15688
This PR contains the final part of the upstreaming activity.
=> FMDN upstream part 9 (final): new FMDN content for the Fast Pair service documentation 

samples/cellular/modem_shell/src/sock/sock.c
PR #13772 added an assert requiring family to be 'inet' or 'inet6' when port is set into address structure.
This must be removed for 'packet' (raw) sockets to work.
Jira: MOSH-588
=> samples: cellular: modem_shell: sock: Fix 'packet' socket connect

tests/subsys/bootloader/bl_crypto/testcase.yaml, tests/subsys/bootloader/bl_storage/testcase.yaml, tests/subsys/bootloader/bl_validation/testcase.yaml, tests/subsys/bootloader/bl_validation_ff_key/testcase.yaml, tests/subsys/bootloader/bl_validation_neg/testcase.yaml, tests/subsys/bootloader/bl_validation_unittest/testcase.yaml, tests/subsys/bootloader/boot_chains/testcase.yaml
- Add support for nRF9151 and nRF9161.
- Add native_sim support to bl_validation_unittest.
=> tests: bootloader: Add 9151 and 9161 support

samples/openthread/cli/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, samples/openthread/cli/sample.yaml
Adding nrf54h20 single and multiprotocol to twister builds.
=> openthread: samples: Add nrf54h20 to twister build.

applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/app.overlay, applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/prj.conf, applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/prj_release.conf, applications/nrf_desktop/src/modules/Kconfig.usb_state, applications/nrf_desktop/src/modules/usb_state.c
**Yet to be done:**
Adds nRF54H USBHS support.
Problems with USB initialization on nRF54H.
For the nRF54HX SoC use-case, the usb_init() function blocks while waiting for a synchronization object that is received after the system controller sends the USB service event through the NRFS and IPC with the ICMSG backend to the application core.
The ICMSG backend uses the system workqueue context for both, initialization and on the incoming message handling so calling the usb_init() function from the same context causes deadlock during application boot.
Workaround: Delay usb_init and execute in other thread rather than in system workqueue.
Jira: NCSDK-27010
Jira: NCSDK-22779
=> applications: nrf_desktop: Add USBHS init thread + nrf54H USBHS support

doc/nrf/external_comp/bt_fast_pair.rst
Fixed syntax in the Fast Pair integration guide for unavailable API elements.
=> doc: external comp: fast_pair: fix syntax for unavailable API elements

cmake/sysbuild/zip.cmake
Change ensures that manifest.json included in the dfu_application.zip follows the agreed format.
Jira: NCSDK-27569
=> cmake: sysbuild: Align zip.cmake for MCUboot with new manifest format

lib/lte_link_control/lte_lc.c
Fix compiler warning about err may be used unintialized.
=> lib: lte_lc: Fix compiler warning

drivers/wifi/nrf700x/Kconfig, drivers/wifi/nrf700x/inc/fmac_main.h, drivers/wifi/nrf700x/src/fmac_main.c, scripts/quarantine.yaml
SHEL-2800 : Support for passing frequency dependent PCB loss parameters.
test_wifi:test-sdk-wifi-PR-15630
=> manifest: PCB loss information from RF params

cmake/fw_zip.cmake, scripts/bootloader/generate_zip.py
Change updates `format-version` in `manifest.json` of generated `dfu_application.zip` files. The new `format-version` is necessary
because changes introduced by HW model v2 and sysbuild break backwards compatibility.
PR also updates `generate_zip.py` to allow specifying `format-version`.
Jira: NCSDK-27569
=> cmake: Update format-version of generated dfu_application.zip

cmake/sysbuild/b0_packaging.cmake
Change ensures that manifest.json included in the dfu_application.zip follows the agreed format.
Jira: NCSDK-27569
=> cmake: sysbuild: Align b0_packaging.cmake with new manifest format

drivers/wifi/nrf700x/src/wifi_mgmt.c
set packet filter setting to previously configured packet filter settings if application only attempts to set packet length.
The SHA - fc4c87fc28cb007d3ac86b5ce5b6d082cf920086 for sdk-nrfxlib for this PR has been superseded and taken into sdk-nrf with 4e13396f2fb03b61b0adc9db2717af786fed7bbf for sdk-nrfxlib. So removing the manifest update from the PR
=> Set filter settings for packet len

applications/serial_lte_modem/src/gnss/slm_at_gnss.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
When carrier library is enabled the GNSS data will be provided using the lwm2m_carrier_location_set() and lwm2m_carrier_velocity_set() API.
=> applications: serial_lte_modem: Add GNSS data to carrier library

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/fota_download.h, subsys/net/lib/fota_download/Kconfig, subsys/net/lib/fota_download/src/fota_download.c, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_coap, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_fota, subsys/net/lib/nrf_cloud/include/nrf_cloud_download.h, subsys/net/lib/nrf_cloud/src/nrf_cloud_download.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_fota_poll.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps_utils.c
Update `fota_download` to allow for FOTA updates to be performed using an external download source.
Update `nrf_cloud` library to enable downloading FOTA and P-GPS data using nRF Cloud's CoAP proxy download resource.
=> Add nRF Cloud CoAP download support

west.yml
The filter settings for control and data are set incorrectly. The change pulls in that fix for setting data and control filter settings properly for sniffer operation
Resolves SHEL-2790
=> manifest: sdk-zephyr: Pull fix for filter settings

applications/nrf5340_audio/broadcast_source/Kconfig.defaults, applications/nrf5340_audio/broadcast_source/main.c, applications/nrf5340_audio/src/bluetooth/bt_management/advertising/Kconfig, applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c, applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.h, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/Kconfig, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.h, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c, applications/nrf5340_audio/unicast_server/main.c
OCT-2949
While adding the manufacturer ID in the advertisement packet it was noticed that the adv packet for unicast_client and broadcast_source are done in completely different ways. This rewrites both to make them closer and with a view to setting these later with a shell.
The implementation has moved any Kconfig CONFIG_* into the populate routine in preparation for driving externally.
=> applications: nrf5340_audio: Rewrite adv population for broadcast_source

cmake/sysbuild/suit.cmake, cmake/sysbuild/suit_utilities.cmake
The build system now generates a ZIP file containing all necessary artifacts necessary to perform SUIT DFU.
=> suit: generate DFU ZIP artifact

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud_coap.h, samples/cellular/nrf_cloud_multi_service/src/shadow_support_coap.c, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c
Add option to specify content format in nrf_cloud_coap_shadow_get(). Also, make the length argument a pointer to an integer, so that the function can return the actual length of the payload.
=> net: lib: nrf_cloud: Add option to specify content format

doc/nrf/device_guides/working_with_nrf/nrf53/nrf5340.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Replaced nRF53 commands using nrfjprog with the nRF Util ones.
=> doc: nrf53: replace nrfjprog with nrfutil

subsys/sdfw_services/Kconfig
Ensure that ZCBOR_CANONICAL is set for SSF clients.
This is required since SDFW uses ZCBOR_CANONICAL.
This is a sub-optimal solution, see PR-15776 for proper one.
Ref: NCSDK-27818
=> kconfig: ssf: select zcbor canonical

subsys/nrf_security/Kconfig.legacy, subsys/nrf_security/cmake/legacy_crypto_config.cmake, subsys/nrf_security/configs/legacy_crypto_config.h.template, west.yml
This commit allows application to set mbedTLS option that allow to remove support for AES operations that use 192- or 256-bit keys.
It also enables it by default for Matter over Wi-Fi applications.
=> nrf_security: add MBEDTLS_AES_ONLY_128_BIT_KEY_LENGTH option

subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/hci_internal.c
Move the feature to a temporary KConfig until it has been marked as supported by the SoftDevice Controller.
=> bluetooth: controller: Move LE Path Loss Monitoring to separate KConfig

snippets/nordic-bt-rpc/boards/nrf54h20dk_nrf54h20-mem-map-move.dtsi
Currently there is a dfu_partition defined between app code and settings partition.
This PR shrinks the DFU partition to fit radio settings and leave the code partitions as-is.
Additionally, the radio core settings end at 0xe1e9000, which is the final location of Secure storage area.
=> snippets: bt-rpc: Align overlay with new Zephyr

samples/cellular/modem_shell/src/utils/net_utils.c
When setsockopt() fails to bind socket with PDN ID it return -1. Change the error message to show errno.
=> samples: cellular: modem_shell: Show errno on setsockopt error

boards/nordic/thingy91x/CMakeLists.txt
This patch resolves warnings about empty libraries from the thingy91x board files.
=> boards: thingy91x: resolve build warnings

samples/matter/window_covering/pm_static_nrf54l15pdk_nrf54l15_cpuapp.yml, scripts/quarantine.yaml, scripts/quarantine_windows_mac.yaml
* Fix nRF54L15 pm_static in window covering matter samples
* Add matter specifc sample to quarantine due to memory overflow
=> samples: matter: fix the pm static for nRF54L15 in window covering

applications/asset_tracker_v2/src/modules/modem_module.c, samples/cellular/http_update/application_update/src/main.c, samples/cellular/lwm2m_carrier/src/main.c, samples/cellular/modem_shell/src/shell.c
This new error type was introduced in the latest release of the LwM2M Carrier library but not all the existing integrations have been updated to handle it.
=> applications: samples: add handling for LWM2M_CARRIER_ERROR_CONNECT

west.yml
fix: add DTS configuration for nrf54 bootloader to have working DFU on nrf54L15
samples: remove child image support
Automatically created by Github Action from PR: github.com/nrfconnect/sdk-sidewalk/pull/570
=> manifest: sdk-sidewalk: Update revision

applications/nrf5340_audio/src/audio/audio_datapath.c
Disable pres-comp in CIS bidir gateway since there's only one mic stream in CIS gateway, and also pres-comp only defined in unicast server side.
OCT-3040
=> applications: nrf5340_audio: Fix CIS bidir mic return issue

doc/nrf/config_and_build/bootloaders/index.rst
Clarified that MCUboot can only by use as second-stage bootloader if NSIB is the first-stage.
=> doc/nrf/bootloaders: clarify MCUboot as second-stage boot setup

subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c
When FOTA push starts by modem erasing,
the block 0 is retryed, which causes FOTA to restart unless we actively skip the already downloaded block.
=> net: lwm2m_client_utils: Fix Push FOTA

applications/ipc_radio/README.rst, doc/nrf/libraries/bluetooth_services/rpc.rst, samples/bluetooth/peripheral_uart/README.rst, snippets/nordic-bt-rpc/README.rst
There were updated documentation related to Bluetooth RPC host interface in following parts of SDK:
- nordic-bt-rpc snippet
- BLE RPC subsystem
- ipc_radio
- peripheral_uart
=> doc: Bluetooth RPC Host related documentation updates

lib/lte_link_control/lte_lc_helpers.c, tests/lib/lte_lc/src/main.c
The reg_status param is allowed to be set to NULL by the call. So we should not derefence it without a NULL check. This patch uses the status variable instead of dereferencing the reg_status parameter.
Added unit test to cover this scenario. The unit test fails with a segmentation fault without this fix.
Found as violation of CWE-476 by SonarCloud.
https://sonarcloud.io/project/issues?open=AY8xkfuQ-1NVyxUQu2Ht&id=balaji-nordic_sdk-nrf
=> lib: lte_link_control: Fix null pointer access

applications/serial_lte_modem/boards/thingy91x_nrf9151_ns.conf, applications/serial_lte_modem/boards/thingy91x_nrf9151_ns.overlay
Enable hardware flow control for Thingy91 X.
=> applications: serial_lte_modem: HWFC for Thingy91 X

applications/serial_lte_modem/src/lwm2m_carrier/slm_at_carrier.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
The data sent in the #XCARRIER: 12 unsolicited notification is a string and so should be enclosed in double quotes.
Print the data on the same line.
=> applications: serial_lte_modem: fix the format of Carrier app data

applications/serial_lte_modem/src/nativetls/slm_native_tls.c
Fix listing credentials with AT#XCMNG=1.
=> applications: serial_lte_modem: Fix AT#XCMNG=1

samples/bluetooth/mesh/common/smp_bt.c
SMP service UUID must be presented in adv data.
=> Samples: Bluetooth: Mesh: fix common mesh adv data

CODEOWNERS, subsys/bluetooth/enocean.c, tests/subsys/bluetooth/enocean/CMakeLists.txt, tests/subsys/bluetooth/enocean/prj.conf, tests/subsys/bluetooth/enocean/src/main.c, tests/subsys/bluetooth/enocean/testcase.yaml
Adds a simple unit test for enocean module using sample data from
enocean specifications and real devices.
Also, updates the CODEOWNERS file to add Ludvig as code owner for
this test.
=> Bluetooth: enocean: Add unit test

drivers/wifi/nrf700x/Kconfig
SAP is now production quality for Wi-Fi provisioning (not general usage), this has been proven with "samples/wifi/provisioning/wifi" sample.
Implements SHEL-2859.
=> drivers: wifi: SAP is now production quality

applications/nrf5340_audio/src/bluetooth/bt_management/scanning/Kconfig, applications/nrf5340_audio/unicast_client/main.c
- Set ACL interval to 10ms during discovery and configuration
- Set ACL back to 80ms before ISO starts streaming to free up air time
- Fixes bug where set up time is too long
- OCT-3035
=> applications: nrf5340_audio: Speed up discovery process

applications/nrf_desktop/src/modules/Kconfig.usb_state
Change adds missing dependency to CONFIG_DESKTOP_USB_REMOTE_WAKEUP. Enabling USB remote wakeup without CONFIG_DESKTOP_USB_PM_ENABLE results in missing force_power_down_event on USB suspend. Because of this, CAF Power Manager does not suspend application and there is no related wake_up_event on user activity. The wake_up_event is needed to trigger USB remote wakeup.
Jira: NCSDK-27912
=> applications: nrf_desktop: Add missing dependency to USB remote wakeup

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/nrf_cloud_multi_service/README.rst
Update Multi Service Sample docs to include updated build instructions for sybuild overlays.
Also fix minor tabs formatting issue.
IRIS8989
=> docs: samples: mss: Update docs to match sysbuild overlays

include/net/nrf_cloud_coap.h, subsys/net/lib/nrf_cloud/coap/include/nrf_cloud_coap_transport.h
The multi service sample fails to build with the logging overlay due to a recent change to the nrf_cloud_coap.h header.
Move conflicting definitions from nrf_cloud_coap_transport.h to nrf_cloud_coap.h.
Jira: IRIS-9135
=> net: lib: nrf_cloud_coap: Simplify headers

west.yml
Pulls in the fixes for mesh friendship timing corrections and advertiser device name for PB-GATT server.
=> manifest: sdk-zephyr: update sdk-zephyr revision for mesh fixes

samples/suit/smp_transfer/templates/extflash/app_envelope.yaml.jinja2, samples/suit/smp_transfer/templates/extflash/rad_envelope.yaml.jinja2, west.yml
The manifest URI now contains only the binary filename instead of full path from the file system. This is made to match the structure of the generated dfu_suit.zip file.
Additional context:
The Device Manager mobile application will expect that payloads are specified by filename alone. Therefore this is a bugfix.
=> samples: suit: use binary filename when fetching

applications/matter_bridge/doc/matter_bridge_description.rst, doc/nrf/includes/matter_sample_button.txt, doc/nrf/includes/matter_sample_state_led.txt, doc/nrf/includes/matter_segger_usb.txt, doc/nrf/protocols/matter/getting_started/adding_clusters.rst, samples/matter/light_bulb/README.rst, samples/matter/light_switch/README.rst, samples/matter/lock/README.rst, samples/matter/template/README.rst, samples/matter/thermostat/README.rst, samples/matter/window_covering/README.rst
The nRF54L and nRF54H series PDKs have a new numbering system. This makes the required adjustments to Matter samples that support those boards.
=> doc: Matter: new button and LED numbering

doc/nrf/device_guides/nrf53/qspi_xip_guide_nrf5340.rst, samples/nrf5340/extxip_smp_svr/README.rst
Clarified that childimage must be used.
=> doc/nrf/../nrf5340_qspi_xip: note on childimage reqirement

applications/matter_bridge/src/ble_providers/ble_environmental_data_provider.cpp, applications/matter_bridge/src/ble_providers/ble_lbs_data_provider.cpp, applications/matter_bridge/src/bridged_device_types/generic_switch.h, applications/matter_bridge/src/bridged_device_types/humidity_sensor.h, applications/matter_bridge/src/bridged_device_types/onoff_light.cpp, applications/matter_bridge/src/bridged_device_types/onoff_light.h, applications/matter_bridge/src/bridged_device_types/onoff_light_switch.h, applications/matter_bridge/src/bridged_device_types/temperature_sensor.h, applications/matter_bridge/src/simulated_providers/simulated_generic_switch_data_provider.cpp, applications/matter_bridge/src/simulated_providers/simulated_humidity_sensor_data_provider.cpp, applications/matter_bridge/src/simulated_providers/simulated_onoff_light_data_provider.cpp, applications/matter_bridge/src/simulated_providers/simulated_onoff_light_switch_data_provider.cpp, applications/matter_bridge/src/simulated_providers/simulated_temperature_sensor_data_provider.cpp, samples/matter/common/src/bridge/bridge_manager.cpp, samples/matter/common/src/bridge/matter_bridged_device.cpp, samples/matter/common/src/bridge/matter_bridged_device.h
It is not possible to modify the bridged device node label e.g. using controller commands, despite the spec says this is R/W attribute.
Changed attribute type to writable and exteded implementation to allow handling write requests for it. Additionally added parsing the write requests with string type, as it turned out to not work properly.
=> applications: Fixed writing the bridged device node label

boards/shields/nrf700x_nrf54h20dk/nrf700x_nrf54h20dk.overlay
Due to recent DFU additions, adjust the offsets to account for increased Flash.
Fixes SHEL-2858.
=> shields: nrf54h20dk_nrf700x: Fix DFU partition offsets

drivers/wifi/nrf700x/Kconfig
[SHEL-2874]: Description of PCB loss info parameters in different bands is updated.
[SHEL-2874]: https://nordicsemi.atlassian.net/browse/SHEL-2874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> drivers: wifi: nrf700x: Updates to Kconfig file

west.yml
The soc-hwmv1 module adds support for nRF52/nRF53/nRF91 SoCs in HWMv1 (Hardware Model V1), so that users can continue using the old hardware model while they transition to HWMv2.
=> manifest: add soc-hwmv1 module

applications/nrf_desktop/doc/usb_state.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change adds USB next stack integration documentation for USB state application module.
Jir: NCSDK-27661
=> doc-improvement: applications: nrf_desktop: Document USB next support

samples/app_event_manager/sample.yaml
This adds support for nRF54h20 target in app_event_manager sample.
=> samples: app_event_manager: Add support for nRF54h20

subsys/bootloader/cmake/packaging.cmake
There was a wrong nRF70 WiFi patch file taken into account for multi-image package.
=> sysbuild: Fix nRF70 firmware patch multi-image package

doc/nrf/links.txt
Updated the links to the Golioth Zephyr SDK to use the latest v0.13.1 release.
This is a new PR that implements the same changes that were approved in #12551 (the difference is the version numbers have been updated to latest).
That PR was approved more than once but never merged. If there is anything I can do to help get this across the finish line, please let me know.
Approvers of the previous PR:
- @gregersrygg 
- @nordicjm 
- @peknis 
- @wiba-nordic
=> doc: redistributing: use latest tag for Golioth

west.yml
Allow to use legacy uart shim for nrf54h20 (in particular PPR).
=> manifest: Update zephyr with uart legacy shim for nrf54h20

doc/nrf/config_and_build/bootloaders/bootloader_downgrade_protection.rst, doc/nrf/device_guides/nrf91/nrf91_snippet.rst, doc/nrf/libraries/bluetooth_services/rpc.rst, doc/nrf/protocols/matter/getting_started/hw_requirements.rst, doc/nrf/test_and_optimize/test_framework/running_unit_tests.rst, samples/bluetooth/fast_pair/locator_tag/README.rst, samples/bluetooth/mesh/light/README.rst, samples/bluetooth/mesh/light_switch/README.rst, samples/cellular/nrf_cloud_multi_service/README.rst, samples/suit/flash_companion/README.rst, tests/tfm/tfm_psa_test/README.rst
Applied consistent formatting to west build commands that mention board_targets.
=> doc improvement: board_target: align formatting

samples/bluetooth/mesh/light_ctrl/README.rst
This removes the paragraph about using the Sensor Setup Server to send and receive settings messages in the Light Fixture sample, since the Light Fixture sample has no sensor settings to set.
=> Samples: Bluetooth: Mesh: Remove sensor settings ref from LC readme

doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst, snippets/matter-diagnostic-logs/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, snippets/matter-diagnostic-logs/snippet.yml
Several issues were found in the matter diagnostic logs snippet. Added an important note to the documentation about using snippets.
JIRA: KRKNWK-19076
=> samples: matter: Fix diagnostic logs snippet

drivers/wifi/nrf700x/src/net_if.c
During interface bringup to handle any failures and synchronize with other threads (e.g., WPA supplicant) use the VIF lock to protect.
Fixes SHEL-2502.
=> drivers: wifi: Use VIF lock for bringing up the interface

doc/nrf/protocols/bt/ble/index.rst
The controller now supports more families. The provided link gives more detailed info on which platforms that are supported.
=> doc: bluetooth: Remove ref to 52 and 53 when mentioning SDC

tests/subsys/bluetooth/enocean/CMakeLists.txt
Fixed an issue when optimization is turned off
the linking of the twister test failed. Default
optimization is turned on and the log functions
will be optimized away, and the twister test will
compile without any issues.
=> tests:Bluetooth:Enocean: Missing linker file

drivers/wifi/nrf700x/Kconfig
Raw modes work with and without WPA supplicant, so, rejig to make default as scan only to cater all combinations.
=> drivers: wifi: Fix mode selection for raw modes

applications/serial_lte_modem/src/lwm2m_carrier/Kconfig
The buffer used to set application data via AT#XCARRIER="app_data_set" is of size SLM_CARRIER_APP_DATA_BUFFER_LEN. This buffer however must also accommodate a null-terminator on top of the actual data when retrieving the string from the issued AT command. Increase the size by one byte as it is crucial to pass a test item of a certain operator, which verifies the upper limit of data that can be set.
=> applications: serial_lte_modem: adjust SLM_CARRIER_APP_DATA_BUFFER_LEN

doc/nrf/config_and_build/config_and_build_system.rst, doc/nrf/config_and_build/configuring_app/cmake/index.rst, doc/nrf/config_and_build/configuring_app/hardware/index.rst
Aligned information about conf_file and dtc_overlay_file usage in the NCS with documentation in Zephyr.
Added cross-links.
VSC-2598.
----
=> doc: build: conf_file and dtc_overlay_file edits

samples/cellular/nrf_cloud_multi_service/README.rst
Fix copy and paste error introduced in the last mss docs commit.
No changelog update necessary, this just fixes a
copy and paste error from previous commit.
IRIS-9157
=> doc: samples: mss: Wi-Fi scan build instructions

doc/nrf/libraries/networking/nrf_cloud.rst
Explain which option is default.
Explain Modem JWT prerequisite for using INTERNAL_UUID.
=> docs: nrf_cloud: Client id improvements

subsys/bluetooth/rpc/client/bt_rpc_gatt_client.c, subsys/bluetooth/rpc/common/bt_rpc_common.c
1. Fix bug with not correct subscription parameters length for bt client without smp service
2. Move initialization back for backward compatibility
=> bluetooth: rpc: minor fixes

sysbuild/Kconfig.sysbuild
Now that SoC configs are available in sysbuild, use them to enable PM for nRF devices only, except the nRF54H series which won't support it.
=> sysbuild: Simplify conditions for enabling partition manager

samples/bluetooth/mesh/chat/src/model_handler.c
Removes shell print statement from the model handler initialization which would cause a warning due to the shell not being initialized yet.
=> Samples: Bluetooth: Mesh: Fix chat sample warning

samples/matter/common/src/persistent_storage/backends/persistent_storage_secure.cpp
The SecureRemove method removes object only if it is NOT present in the map, what seems to be a broken condition.
=> samples: matter: Fixed secure backend remove condition

subsys/bluetooth/services/mds.c
This is a copy of #15911 to be able to fix the commit message in time for 2.7.0 release.
MDS allows registration of a user supplied callback function to control acces to the Memfault characteristic and descriptors data. However, when the presence of this callback registration is tested in data_export_write, data_export_ccc_write, and mds_read, it is falsely assumed that the callback structure itself is always registered. Since this can considered programming mistake, an assert would also resolve this but that would bypass the optional nature of the registration API.
=> bluetooth: Fix potential nullptr dereference in mds

applications/matter_bridge/doc/matter_bridge_description.rst, applications/matter_weather_station/README.rst, doc/nrf/includes/sample_custom_config_intro.txt, samples/matter/light_bulb/README.rst, samples/matter/light_switch/README.rst, samples/matter/lock/README.rst, samples/matter/template/README.rst, samples/matter/thermostat/README.rst, samples/matter/window_covering/README.rst
Sample documentation still refers to build types, which are deprecated. This updates the wording to match the use of the FILE_SUFFIX variable.
=> doc: Matter: update from build type to suffix description

scripts/quarantine_zephyr.yaml
Tests were fixed in https://github.com/nrfconnect/sdk-zephyr/pull/1777 and https://github.com/nrfconnect/sdk-mcuboot/pull/316.
=> scripts: update quarantine for zephyr samples.

samples/matter/lock/src/access/access_manager.cpp
Door lock sample uses LOG_MODULE_DECLARE(cr_manager, ...) in several files, but there is no LOG_MODULE_REGISTER anywhere, so the compilation ends with linker error.
=> samples: matter: Fixed logging on a door lock

west.yml
This update brings fixes for ns targets, and board identifier for nrf52840dk_nrf52840_v1.
=> manifest: pull hwmv1 soc/board fixes

tests/lib/lte_lc/testcase.yaml
This is a unit tests, it shouldn't run on target.
There is no point in running it in `qemu_cortex_m3` and `qemu_x86` either.
Change from `native_posix` to `native_sim`.
=> tests: lib: lte_lc: correct platforms

subsys/bluetooth/mesh/light_ctrl_srv.c
When recalling a scene during when the controller is not in standby, the Light Lightness Server would turn off the light even if the scene had the light turned on.
This commit fixes the issue by removing a check for whether the light is on when recalling a scene. The check was added to prevent recalling the same scene multiple times, but it is not necessary as this is checked in in `bt_mesh_scene_srv_set` (in `scene_srv.c`).
=> Bluetooth: Mesh: Fix scene recall for LLC server

.gitignore, scripts/hid_configurator/README.rst, scripts/hid_configurator/configurator_cli.py
Adding the path to find a .dll to PATH
environment variable has been removed in Python 3.8. Now os.add_dll_directory is recommended solution for adding dll. This commit adds an optional argument to script with path to dll folder.
Jira: NCSDK-27863
=> scripts: hid_configurator: Add support in Windows for dll folder

samples/cellular/nrf_cloud_multi_service/overlay_nrfcloud_logging.conf, subsys/net/lib/nrf_cloud/src/nrf_cloud_log_backend.c
Due to an upstream Zephyr change, CONFIG_LOG_FMT_SECTION_STRIP was being enabled when CONFIG_LOG_BACKEND_NRF_CLOUD_OUTPUT_DICTIONARY was enabled, which causes a hard crash when text logging to the UART (because the strings the UART logger needs are missing from the image).
Add documentation to the overlay_nrf_cloud_logging.conf and a build assert to detect this.
Jira: IRIS-9177
=> net: lib: nrf_cloud_log: Fix crash with dictionary fmt

doc/nrf/config_and_build/dfu/index.rst, doc/nrf/device_guides/nrf91/index.rst, doc/nrf/device_guides/nrf91/nrf91_board_controllers.rst, doc/nrf/device_guides/nrf91/nrf91_features.rst, doc/nrf/includes/sample_board_rows.txt, doc/nrf/links.txt
Updated the following:
* nRf91 Series table with nRF9151, nRF9131, and Thingy:91 X details.
* provided a ref link on DFU page for nRF91 Series FOTA updates
* Feature page with nRF9151, nRF9131, and Thingy:91 X details.
* Board controller page for the nRF9151.
=> doc improvement: Update to nRF91 table and features

samples/wifi/radio_test/sample.yaml
Add CONFIG_NRF700X_RADIO_TEST_COMBO option to CI build.
=> samples: wifi: radio_test: Fix combo build config

samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_switch/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/lock/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/template/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/template/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp_internal.conf, samples/matter/thermostat/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/window_covering/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf
Currently, without tickless kernel, the SYSCOUNTER value after the software reset is not set properly and due to that the first system interrupt is not called in the proper time, the SYSCOUNTER value is set to the value from before reset + 1. Hence, the reboot time increases more and more.
To avoid it enable tickles kernel for mcuboot.
=> samples: matter: Provide a fix for unacceptable booting time

doc/nrf/protocols/bt/bt_mesh/dfu_over_bt_mesh.rst
Add a note about the need to cancel the Distribution Server after a successful firmware distribution.
=> doc: Bluetooth: Mesh: Add note about cancel after successful dist

doc/nrf/device_guides/working_with_nrf/nrf54l/nrf54l15_gs.rst
removed the --erase argument from west flash command.
VS code runs it by default.
=> doc: nRF54L15 getting started small fix

samples/wifi/sta/README.rst
Correct Kconfig option name in documentation
to CONFIG_WIFI_READY_LIB for `wifi_ready` library usage.
=> samples: wifi: sta: Update Kconfig option in README

applications/ipc_radio/README.rst
Correct the ipc_radio configuration Kconfig for enable.
The Pr is related to the comment: https://github.com/nrfconnect/sdk-nrf/pull/15830#pullrequestreview-2112128392
Jira: NCSDK-27939
=> doc: Update the ipc_radio enable doc section

scripts/quarantine_zephyr.yaml, west.yml
Pull in changes enabling coverage calculation in adc samples.
Extend quarantine to make CI green.
=> manifest: update sdk-zephyr revision.

sysbuild/CMakeLists.txt
Flashes the merged network core image first when partition manager is enabled, this prevents issues if security modes become active after the main core image is flashed first
=> sysbuild: Flash network core image first, if enabled

applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
- Due to high ACL traffic we might get a cancelled ACL creation.
- Change error print for these cases to a warning.
- OCT-NONE
=> applications: nrf5340_audio: Handle known disconnect reason

samples/openthread/cli/README.rst, samples/openthread/cli/sample.yaml
Commit adds missing `FILE_SUFFIX=ble` to sample yml for TCAT feaure.
=> samples: openthread: Add missing `FILE_SUFFIX` to OT cli.

boards/nordic/thingy91x/board.cmake
This patch, in combination with a new nrfutil release fixes the issue where it is very easy to brick thingy91x-nrf53 chips by flashing the nrf91 image. The new version of nrfutil will refuse to flash if the device family doesn't match.
=> boards: thingy91x: migrate to nrfutil

scripts/ci/tags.yaml, scripts/ci/twister_ignore.txt
Tags and ignores are paths with root at NCS,
thus add specific path for nrf or zephyr.
=> scripts: ci: test_plan: Align tags and ignores for NCS

sysbuild/extensions.cmake
add_overlay() uses image specific variables for passing extra settings like EXTRA_CONF_FILE / EXTRA_DTC_OVERLAY_FILE to images.
However, the main app image also supports the use of the general EXTRA_CONF_FILE / EXTRA_DTC_OVERLAY_FILE variable, but where the image specific setting still takes precedence when both are specified.
Extend `add_overlay()` to check if the image passed in the main app, and ensure the correct variable is used when extending the list, so that user specified values are honored.
Jira: NCSDK-27868
=> sysbuild: update add_overlay to handle main app variables

samples/edge_impulse/data_forwarder/prj.conf
Include floating point support in printk/snprintf functions.
=> samples: edge_impulse: data_forwarder: Enable picolib float support

samples/bluetooth/mesh/light_ctrl/README.rst
This updates the LED numbering for the nRF54 DKs. The nRF54L15 PDK will output PWM output for pwm_led0 on the second LED (LED 1) instead of the first LED like on other DKs, because of limitations in pin assignment.
=> Samples: Bluetooth: Mesh: Update LC LED number for nRF54

scripts/quarantine_zephyr.yaml
For new failures in sdk-zephyr on nrf54l and h
=> quarantine: Update zephyr related quarantine

applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/app.overlay, applications/nrf_desktop/doc/ble_qos.rst, applications/nrf_desktop/src/modules/Kconfig.ble_qos, applications/nrf_desktop/src/modules/ble_qos.c
Change updates dependencies and documentation of the CONFIG_DESKTOP_BLE_QOS_STATS_PRINTOUT_ENABLE Kconfig option.
Jira: NCSDK-27883
=> applications: nrf_desktop: Update BLE QoS stats printout

doc/nrf/device_guides/nrf91/index.rst, doc/nrf/device_guides/nrf91/nrf91_board_controllers.rst, doc/nrf/device_guides/nrf91/nrf91_dk_updating_fw_programmer.rst, doc/nrf/device_guides/nrf91/nrf91_features.rst, doc/nrf/libraries/bin/lwm2m_carrier/CHANGELOG.rst, doc/nrf/libraries/bin/lwm2m_carrier/certification.rst, doc/nrf/libraries/bin/lwm2m_carrier/index.rst, doc/nrf/links.txt
* Added nRF9161 comp matrix ref links to the NCS docs.
* Updated the nRF91 Series table to add GSG link.
NCSDK-25959
=> doc improvement: Minor updates on nRF91 Series and LwM2M carrier

doc/_scripts/software_maturity/software_maturity_features.yaml
Rename the entry from DECT_PHY to DECT NR+ PHY.
Change the KConfig rule, eventually that might apply to nRF91x1 only.
=> doc: software maturity: DECT updates

lib/lte_link_control/Kconfig, lib/lte_link_control/lte_lc_modem_hooks.c
The PLMN selection optimization is disabled by default in the modem firmware from version v2.0.1.
A new `AT%FEACONF` parameter is added to control the feature.
Enabling PLMN selection optimization typically makes the initial search faster, and thus use less power.
There are no known adverse effects.
Introduce a KConfig in `lte_lc` to enable this feature upon modem firmware initialization.
Let this Kconfig be enabled by default.
=> lib: lte_lc: add a new option to control PLMN selection optimization

west.yml
So that only devices implementing JLink trait are taken into account.
=> manifest: pull nrfutil device list fixes

lib/edge_impulse/CMakeLists.txt
Fixes parsing URI from the Kconfig options in Edge Impulse library cmake files.
=> lib: edge_impulse: Fix building with different cmake

subsys/bluetooth/mesh/light_ctrl_srv.c
If the LLC state machine is in the RUN, PROLONG or STANDBY states (or
transitioning to one of these), and receives a prop_set message
modifying the lightness level for the active or target state, the
level will be updated.
=> Bluetooth: Mesh: Improve LLC light property update

samples/bluetooth/mesh/dfu/distributor/sample.yaml
Adding nrf54l15 target for integration platforms for twister tests.
=> Samples: Bluetooth: Mesh: add nrf54l15 back to dfu integration test

scripts/tools-versions-darwin.yml
There was a pypi environment issue (4 missing packages) that is now fixed
This comment will change the input file hash, and rebuild the bundle. 
Signed-off-by: Thomas Stilwell <thomas.stilwell@nordicsemi.no>
=> tools: rebuild v2.7.0-rc2 darwin tool bundle

west.yml
This is implementation of ICBMsg endpoint deregistration. The underlying ICMsg instance and blocks are not affected by deregistration, so it is possible to reuse the same address during the re-registration of the same endpoint.
=> manifest: icbmsg: Allow deregistration of the endpoints

doc/nrf/releases_and_maturity/software_maturity.rst
Override the broken script that incorrectly
showed nRF54 as Supported in several tables.
-----
The script is currently broken and I had to manually override the tables. This means the nRF54 columns need to be thouroughly reviewed to make sure we don't have mistakes.
Preview page -> https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-16080/nrf/releases_and_maturity/software_maturity.html
Please review the following areas:
Please delegate to a proper person if I misassigned you.
=> doc: SML table manual fix for 2.7.0

applications/nrf5340_audio/tools/buildprog/buildprog.py
Update the naming in buildprog.py for FEM.
OCT-NONE
=> applications: nrf5340_audio: Update buildprog.py for FEM

applications/nrf5340_audio/unicast_client/main.c
- Fixes bug where ACL connection interval was not changed
- Checked a config that didn't exist
- OCT-3066
=> applications: nrf5340_audio: Check correct config

applications/nrf_desktop/bluetooth.rst, applications/nrf_desktop/board_configuration.rst, applications/nrf_desktop/bootloader_dfu.rst, applications/nrf_desktop/description.rst, applications/nrf_desktop/doc/dfu.rst, applications/nrf_desktop/memory_layout.rst, applications/nrf_desktop/nRF21540ek_support.rst
Jira: NCSDK-27889
The https://github.com/nrfconnect/sdk-nrf/pull/15851 PR aligns partialy few modules that are also aligned here:
* `dfu_mcumgr.rst`
* `dfu.rst`
Depends on: ~https://github.com/nrfconnect/sdk-nrf/pull/15851~, ~https://github.com/nrfconnect/sdk-nrf/pull/16022~
=> application: nrf_desktop: Align docs after upmerge + migration to sysbuild

applications/nrf_desktop/bootloader_dfu.rst, samples/suit/smp_transfer/README.rst
It is required to use the newest mobile app to perform SUIT-based DFU.
=> samples: suit: Update mobile app versions

samples/crypto/aes_cbc/sample.yaml, samples/crypto/aes_ccm/sample.yaml, samples/crypto/aes_ctr/sample.yaml, samples/crypto/aes_gcm/sample.yaml, samples/crypto/chachapoly/sample.yaml, samples/crypto/ecdh/sample.yaml, samples/crypto/ecdsa/sample.yaml, samples/crypto/ecjpake/sample.yaml, samples/crypto/eddsa/sample.yaml, samples/crypto/hmac/sample.yaml, samples/crypto/rng/sample.yaml, samples/crypto/rsa/sample.yaml, samples/crypto/spake2p/sample.yaml
nRF54H20 app core doesn't yet have access to CRACEN entropy from secure domain. Remove nRF54H20 from sample.yaml until crypto service is available from secure domain firmware.
=> samples: crypto: Remove nRF54H20 from failing crypto samples

scripts/ncs-toolchain-version-minimum.txt
'2.6.20240605' is pointer to 'v2.7.0-rc2' in toolchain-manager index This is required by CMAKE_VERSION.
https://cmake.org/cmake/help/latest/variable/CMAKE_VERSION.html
=> scripts: Update minimum required toolchain for the v2.7.0 release

doc/nrf/config_and_build/board_support/images/spe_nspe.svg
Aligned build target to board target on the SPE/NSPE image.
Missed in #15213
=> doc: tfm: align terminology in an SVG

west.yml
Turn off suspending MRAM for NRF54H20 DK
This change is required so sections of code
depending on critical timings will not have unacceptable latency.
Jira: NCSDK-27870
=> manifest: zephyr: Turn off MRAM suspend for NRF54H20 DK

sysbuild/Kconfig.dfu, sysbuild/Kconfig.zip
Empty netcore is a normal app that can be used
for testing. Do not block adding empty netcore
to DFU package or zip.
=> sysbuild: Allow empty netcore to be in DFU package

samples/event_manager_proxy/README.rst, samples/event_manager_proxy/sample.yaml, samples/event_manager_proxy/sysbuild.cmake
This commit allows to build Event Manager Proxy
sample for all target in default configuration
without a need for passing additional parameters
to the build command.
=> samples: event_manager_proxy: Add default configuration

cmake/sysbuild/debug_keys.cmake
Fixes an issue whereby the public key files for secure boot were not looked up using the application's configuration directory as the base
=> cmake: sysbuild: Fix secure boot public key relative path usage

doc/_extensions/table_from_rows.py
Targets in row sections still use `_`, so set lookup failed as shields set uses `/` (from HWMv2).
=> doc: extensions: table_from_rows: fix shield list not displaying

Kconfig.nrf, subsys/partition_manager/CMakeLists.txt, subsys/partition_manager/Kconfig, subsys/partition_manager/pm.yml.vpr_launcher
Add case for cpuflpr_sram in PM_SRAM_(BASE|SIZE)
Add pm.yml.vpr_launcher file
Include a noup patch in Zephyr that overwrites FLASH_BASE_ADDRESS and
FLASH_SIZE to allow Partition Manager to use the whole RRAM instead of
trying to put both the flpr firmware and the vpr_launcher into the flpr
RRAM partition.
=> partition_manager: Add support for nrf54l15_cpuflpr with vpr_launcher

applications/ipc_radio/README.rst, doc/nrf/config_and_build.rst, doc/nrf/config_and_build/companion_components.rst, doc/nrf/glossary.rst, samples/suit/flash_companion/README.rst, samples/suit/recovery/README.rst
Added a generic user guide about the FW companion components in the NCS. NCSDK-10551.
----
=> doc: companion components: add generic user guide

cmake/multi_image.cmake
Function `get_board_without_ns_suffix` cannot recognize the non-secure suffix if the board revision is placed after it, as is the case in the old hardware model. Example: `nrf9160dk_nrf9160_ns@0.14.0`
Before d7a19af4fe5b5d944befb66b6d9d1de3df67e275, board revisions were not passed to `get_board_without_ns_suffix`, because they are handled independently in the `ncs_file` call further down. Undo this change.
=> cmake: multi_image: Fix handling of HWMv1 boards with revisions

scripts/docker/Dockerfile
Using sdk-nrf-toolchain image you are able to flash hexes on boards
Jira: NCSDK-28174
=> NCSDK-28174: Add nrfutil device to sdk-nrf-toolchain

doc/nrf/links.txt, doc/nrf/releases_and_maturity/migration/migration_hwmv2.rst
Introduce a guide to help users migrate from the previous to the current hardware model. This guide is mostly just a copy, adapted to NCS, of the corresponding section of the Zephyr documentation:
https://docs.zephyrproject.org/latest/hardware/porting/board_porting.html#transition-to-the-current-hardware-model
=> doc: Introduce a hardware model v2 migration guide

samples/suit/flash_companion/prj.conf, scripts/quarantine_zephyr.yaml, west.yml
Turn on NRFS globally so turning off
suspending MRAM for NRF54H20 DK will work.
Jira: NCSDK-27870
=> manifest: zephyr: Turn on NRFS for NRF54H20 DK

cmake/sysbuild/debug_keys.cmake
Removes using the environmental or command line parameters for specifying a key as the underlying functionality in child/parent has never worked so does not need reimplementation in sysbuild
=> sysbuild: Remove non-functional environmental key support

samples/ipc/ipc_service/remote/boards/nrf54h20dk_nrf54h20_cpurad.overlay
hw-flow-control disabled to prevent sample blocking during UART data transmission when the terminal is not connected.
=> samples: ipc: ipc_service: disable hw_flow_control for cpurad nRF54H20

applications/nrf_desktop/src/modules/usb_state.c
Change fixes "undefined reference to `usb_wakeup_request'" build error.
Jira: NCSDK-28196
=> applications: nrf_desktop: Fix USB stack next builds in release config

cmake/sysbuild/partition_manager.cmake
Pass the dynamic partition to partition manager when a DOMAIN is passed to CMake partition_manager() function.
Remove the CPUNET domain restriction as the use of any domain should be handled. Domain is only passed to the function when it's not the domain of the main application.
This fixes the issues like:
```
Traceback (most recent call last):
File "/<path>/partition_manager_output.py", line 251, in <module>
main()
File "/<path>/partition_manager_output.py", line 247, in main
write_gpm_config(gpm_config, greg_config, name, header_file)
File "/<path>/partition_manager_output.py", line 142, in
write_gpm_config
if any('span' in x for x in gpm_config[domain][image]):
~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'empty_app_core'
```
as the dynamic partition is now passed to the partition manager …
=> sysbuild: pass the dynamic partition to partition manager

.github/test-spec.yml, samples/ipc/ipc_service/sample.yaml
Utilizing yaml "folding" with ">" for extra_args split into multiple lines without spurious newline added.
Affected was `sample.ipc.ipc_service.nrf5340dk_rpmsg_default:`
=> samples/ipc/ipc_service: fix sample.yaml caused -D <empty> issue

doc/nrf/config_and_build/bootloaders/bootloader_adding_sysbuild.rst
Change replaces outdated references to child images in "Adding a bootloader chain using sysbuild" documentation.
=> doc-improvement: doc: nrf: Fix outdated references to child images in sysbuild doc

doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/migration_guide_2.4.99-cs3_to_2.7_application.rst, doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/migration_guide_2.6.99-cs2_to_2.7_application.rst
Change adds small fixes and improvements to NCS 2.7 migration guides. nRF54H20 was not supported by nRF Desktop and CoreMark in v2.6.99-cs2 so it's removed from the related migration guide.
=> doc: nrf: Small fixes and improvements to NCS 2.7 migration guides

doc/nrf/config_and_build/bootloaders/bootloader_adding_sysbuild.rst, doc/nrf/config_and_build/bootloaders/bootloader_downgrade_protection.rst, doc/nrf/config_and_build/configuring_app/sysbuild_images.rst, doc/nrf/releases_and_maturity/migration/migration_hwmv2.rst, doc/nrf/releases_and_maturity/migration/migration_sysbuild.rst
Edited capitalization of sysbuild for consistency with Zephyr docs. Added reference to doc placement next to links.
=> doc: sysbuild: link consistency and capitalization

CODEOWNERS
This commit updates code owners for the applications/protocols_serialization  directory
=> CODEOWNERS: Add Protocols Serialization team to the related application directory

samples/bluetooth/connection_event_trigger/sysbuild.cmake, samples/bluetooth/direct_test_mode/Kconfig.sysbuild, samples/bluetooth/direct_test_mode/sysbuild.cmake, samples/esb/esb_prx/sysbuild.cmake, samples/esb/esb_ptx/sysbuild.cmake, samples/mpsl/timeslot/sysbuild.cmake, samples/peripheral/802154_phy_test/sysbuild.cmake, samples/peripheral/radio_test/sysbuild.cmake
Adds the empty_app_core application to the build so that it works out of the box on the nrf53 without needing a separate image built and flashed
=> samples: mpsl: timeslot: Fix missing empty_app_core in build

doc/nrf/installation/updating.rst, doc/nrf/releases_and_maturity/migration/migration_hwmv2.rst
Added a section about using terminal environment, as a target for different references in docs.
Requested by @carlescufi.
=> doc: installation: add section about terminal env

doc/nrf/config_and_build/config_and_build_system.rst, doc/nrf/config_and_build/configuring_app/advanced_building.rst, doc/nrf/config_and_build/configuring_app/cmake/index.rst, doc/nrf/config_and_build/configuring_app/index.rst, doc/nrf/create_application.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/migration/migration_sysbuild.rst, doc/nrf/shortcuts.txt
Try to clarify the behaviour of west with the command-line ``--sysbuild`` option and the configuration options.
=> doc: migration: sysbuild: Add clarifications

doc/nrf/releases_and_maturity/migration/migration_sysbuild.rst
Removes a note that refers to not being able to build with the nRF5340 network core being the default device, as this issue has been fixed
=> doc: nrf: releases: migration: sysbuild: Remove fixed issue

scripts/docker/Dockerfile, scripts/docker/README.md, scripts/docker/entrypoint.sh, scripts/docker/interactive-setup.sh, scripts/docker/jlink/install.sh, scripts/docker/jlink/license.txt, scripts/docker/non-interactive-setup.sh
Add possibility to install JLink tools if user accepts license terms.
If you want to test image, it can be pull from Nordic Docker Registry
`docker-dtr.nordicsemi.no/jag1/public-with-nrfutil:ask_for_jlink`
You can also test publicly available docker:
`ghcr.io/nrfconnect/sdk-nrf-toolchain:pr-16290`
=> [NCSDK-28174] docker: Install JLink in sdk-nrf-toolchain image

west.yml
Update zephyr revision with a snapshot tag. There is no need for a new tag in sdk-mcuboot as that -rc3 one will preserve the history. Other OSS repositories do not need to be rebased.
Update zephyr and mcuboot revisions after they were rebased.
=> NCS 2.7.0 rebase

cmake/multi_image.cmake
When a ROOT cache variable is set by the user in the parent image then those cache variables should be passed to child images so that the child images will use the same root folders.
Jira: NCSDK-28257
=> cmake: pass root cache variables to child images

doc/nrf/releases_and_maturity/migration/migration_hwmv2.rst
The script will not automatically convert all boards, specially those using multicore or non-secure targets. Add a note warning the users about this limitation.
=> doc: migration: hwmv2: inform about board conversion script limitations

doc/nrf/releases_and_maturity/migration/migration_hwmv2.rst
Add `-n <newboard>` to conversion script example.
This will help to ensure users having SoC in their board name, like `plank_nrf52840` will know how to name the new board as `-n plank`, as the SoC should no longer be part of the board name in HWMv2.
Following details are added to the description:
- board names must be unique
- board variants must be converted manually
- board in v1 description is removed as part of the conversion
=> doc: improve board migration hwmv1 to hwmv2 description

tests/benchmarks/multicore/idle/testcase.yaml
Common harness is appended not replaced by specific testcase. harness_config is replaced by specific testcase.
=> tests: benchmarks: multicore: idle: add harness explicit

doc/nrf/protocols/bt/bt_qualification/index.rst, doc/nrf/protocols/matter/end_product/certification.rst
The Matter certification page now links to the Bluetooth certification page. Also clarified the inheritance section so it can't be read as being able to inherit Matter certification.
=> doc: Matter: clarify Bluetooth certification documentation

samples/wifi/ble_coex/CMakeLists.txt, samples/wifi/shell/sample.yaml, samples/wifi/thread_coex/CMakeLists.txt, samples/wifi/throughput/sample.yaml, samples/wifi/wfa_qt_app/README.rst
Replace deprecated `OVERLAY_CONFIG` and `DTC_OVERLAY_FILE` with `EXTRA_CONF_FILE` and `EXTRA_DTC_OVERLAY_FILE`.
Fixes SHEL-1997.
=> samples: wifi: Fix deprecated configuration variables

include/bluetooth/hci_vs_sdc.h, subsys/bluetooth/CMakeLists.txt, subsys/bluetooth/hci_vs_sdc.c
The SDC provides vendor specific Bluetooth functionality through vendor specific HCI commands.
The APIs added in this commit handles:
- Building the VS HCI commands
- Sending the VS HCI command to the controller. This works both when the controller is on the same core, or if the controller is separated from the host by another HCI layer.
- Return parameters
This removes the need for boilerplate code in applications.
Some of the vendor specific APIs take in handles.
Those can be obtained from host types using the APIs defined in `zephyr/bluetooth/hci.h`.
The API documentation is referring to the HCI command documentation to avoid duplication.
=> Bluetooth: Add hci_vs_sdc.h which expose wrappers VS HCI commands

samples/bluetooth/peripheral_uart/README.rst
The documentation was referring to the wrong snippet. Now it matches what is found in the sample.yaml.
=> samples: bluetooth: peripheral_uart: Fix RPC build docs

boards/shields/pca63565/boards/nrf54l15pdk_nrf54l15_cpuflpr.overlay, boards/shields/pca63565/boards/nrf54l15pdk_nrf54l15_vpr_launcher.overlay, boards/shields/pca63566/boards/nrf54h20dk_nrf54h20_cpuppr.overlay, boards/shields/pca63566/boards/nrf54h20dk_nrf54h20_vpr_launcher.overlay, scripts/twister/alt/zephyr/samples/sensor/accel_polling/sample.yaml, scripts/twister/alt/zephyr/samples/sensor/bme680/sample.yaml
samples/sensor/bme680 was manually tested and confirmed to work on both FLPR and PPR (missing i2c on supported list).
samples/sensor/accel_polling was manually tested and confirmed to work on FLPR. It doesn't compile on PPR due to missing SPI support.
=> Nrfx-6038 run samples sensor bme and accel_polling on nrf54l15/cpuflpr and nrf54h20/cpuppr

include/bluetooth/hci_vs_sdc.h, subsys/bluetooth/hci_vs_sdc.c
Those were removed in pull request sdk-nrf #16323, [nrfxlib PR #1403.](https://github.com/nrfconnect/sdk-nrfxlib/pull/1403)
=> Bluetooth: Remove VS HCI wrappers for coex

samples/matter/common/src/app/fabric_table_delegate.h, samples/matter/common/src/app/group_data_provider.h, samples/matter/common/src/app/matter_init.cpp, samples/matter/common/src/board/board.cpp, samples/matter/common/src/event_triggers/default_event_triggers.cpp, samples/matter/common/src/migration/migration_manager.cpp
Currently the Matter core uses generic implementation of GroupDataProvider that performs multiple operations on persistent storage (including erasing of the related keys) even though the KVS is erased at the end and the device is rebooted. Implemented custom GroupDataProvider that can be configured at runtime to avoid redundant and time-consuming tasks.
It decreases the factory reset time on nRF52 by ~40%.
=> samples: matter: optimize the factory reset time

samples/ipc/ipc_service/sample.yaml
When rad/net is sending, there will be only single tranfser from app core.
=> samples: ipc: ipc_service: align test config when rad/net is sending

samples/wifi/ble_coex/sample.yaml, samples/wifi/monitor/sample.yaml, samples/wifi/promiscuous/sample.yaml, samples/wifi/provisioning/ble/sample.yaml, samples/wifi/provisioning/softap/sample.yaml, samples/wifi/radio_test/sample.yaml, samples/wifi/raw_tx_packet/sample.yaml, samples/wifi/scan/sample.yaml, samples/wifi/shell/sample.yaml, samples/wifi/shutdown/sample.yaml, samples/wifi/softap/sample.yaml, samples/wifi/sta/sample.yaml, samples/wifi/thread_coex/sample.yaml, samples/wifi/throughput/sample.yaml, samples/wifi/twt/sample.yaml, samples/wifi/wfa_qt_app/sample.yaml, scripts/ci/tags.yaml
Extend list of paths used to check if wifi
=> samples: wifi: add wifi tag for samples

samples/bluetooth/peripheral_hids_mouse/sample.yaml, scripts/ci/tags.yaml, tests/bluetooth/iso/testcase.yaml, tests/subsys/bluetooth/gatt_dm/testcase.yaml
Extend list of paths used to check if bluetooth tests/samples should be executed.
=> tests: bluetooth: extend bluetooth tag for tests

subsys/mpsl/init/mpsl_init.c
z_mpsl_used_nrf_ppi_channels and z_mpsl_used_nrf_ppi_groups haven't been used since 2021 (5ef63d83136aaa6e3e67ca7b5ccbc1b526475020), and the ppi reservations for MPSL on nrf52 have been broken ever since.
=> mpsl: Clean up ppi reservations

modules/hostap/src/supp_main.c
As Zephyr still doesn't have a way to convey the choice of algo for WPA3 (HaP or H2E), set the default method to allow both, else if AP sets H2E only then association will fail.
Fixes SHEL-2930.
=> modules: hostap: Fix H2E default value

subsys/net/lib/nrf_cloud/coap/src/coap_codec.c
For an AGNSS request, allow the net_info request parameter to be null.
Jira: NCSDK-28192
=> net: lib: nrf_cloud_coap: Allow null net_info

subsys/net/lib/nrf_cloud/src/nrf_cloud_log_backend.c
Add a build assert to enforce limiting dictionary logging to MQTT connectivity.
Jira: IRIS-8684
=> net: lib: nrf_cloud_logging: Build assert dict log

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud.h, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_client_id, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c, subsys/net/lib/nrf_cloud/include/nrf_cloud_client_id.h, subsys/net/lib/nrf_cloud/src/nrf_cloud_client_id.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_jwt.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c
Add function nrf_cloud_client_id_runtime_set.
Allow runtime client ID for CoAP and REST.
IRIS-9081
=> net: lib: nrf_cloud: allow runtime client id for coap

doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, west.yml
Updated Matter revision to pull new Kconfigs that allow configure parameters impacting the persistence subscriptions re-establishment procedure.
=> manifest: Updated Matter revision to pull new Kconfigs

tests/subsys/bluetooth/fast_pair/crypto/prj_psa.conf
Fixed the stack overflow issue for the nRF54L15 PDK and the PSA configuration in the Fast Pair Crypto test. Increased the stack size globally for all platforms to avoid potential issues with other board targets.
Ref: NCSDK-28342
=> tests: bluetooth: fast_pair: crypto: fix stack overflow for PSA config

scripts/ci/tags.yaml
Remove tags which are only set at zephyr.
=> scripts: ci: tags: include paths for tests and samples

west.yml
This fixes an issue in case a platform has no CSRNG drivers (e.g., nRF53 in Zephyr upstream).
Workaround for bug NCSIDB-1303.
=> manifest: sdk-hostap: Pull CSRNG fix

boards/shields/nrf700x_nrf54h20dk/Kconfig.defconfig, boards/shields/nrf700x_nrf54l15pdk/Kconfig.defconfig
Problem statement:
Sample or standalone application has no `WIFI` config set by default and build fails due to missing Kconfig dependencies:
```
warning: NRF_WIFI_COMBINED_BUCKEN_IOVDD_GPIO (defined at /home/maga/WorkingDirectory/workspace/nrf/drivers/wifi/nrf700x/Kconfig:717) has direct dependencies WIFI with value n, but is currently being y-selected by the following symbols:
- SHIELD_NRF700X_NRF54H20DK (defined at /home/maga/WorkingDirectory/workspace/nrf/boards/shields/nrf700x_nrf54h20dk/Kconfig.shield:9, /home/maga/WorkingDirectory/workspace/nrf/boards/shields/nrf700x_nrf54h20dk/Kconfig.shield:9), with value y, direct dependencies y (value: y)
- SHIELD_NRF700X_NRF54H20DK (defined at /home/maga/WorkingDirectory/workspace/nrf/boards/shields/nrf700x_nrf54h20dk/Kconfig.shield:9, …
```
=> boards: shield: Add defconfigs for nRF54 shields.

applications/nrf5340_audio/src/modules/sd_card.c
Remove semaphores in sd_card module so multiple files can be opened and read from at the same time. The Zephyr FS supports multiple open files, and there are no relevant limitiations of the SD card module to not allow multiple files.
OCT-3031
=> Application: nrf5340_audio: Allow opening multiple files on SD card

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud.h, subsys/net/lib/nrf_cloud/CMakeLists.txt, subsys/net/lib/nrf_cloud/Kconfig, subsys/net/lib/nrf_cloud/src/nrf_cloud_credentials.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_fota.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_fota_poll.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_jwt.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_rest.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_sec_tag.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c
Added functions nrf_cloud_sec_tag_set() and nrf_cloud_sec_tag_get() to set and get the sec tag used for nRF Cloud credentials.
IRIS-9080
=> net: lib: nrf_cloud: allow sec tag to be set at runtime

subsys/bluetooth/rpc/client/bt_rpc_conn_client.c, subsys/bluetooth/rpc/client/bt_rpc_gap_client.c, tests/subsys/bluetooth/enocean/src/main.c, west.yml
This PR contains a selection of cherry-picks to
support concurrent scanning and initiating.
In addition, this PR adds the following commits:
* Commits that fixes bugs related to concurrent scanning and initiating or bugfixes required to verify this feature.
* Commits that ensure the other commits can be applied without merge conflicts.
* Simple useability improvements.
=> manifest: zephyr: Add Bluetooth cherry-picks

subsys/bluetooth/rpc/client/bt_rpc_conn_client.c, subsys/bluetooth/rpc/client/bt_rpc_gap_client.c, subsys/bluetooth/rpc/client/bt_rpc_gatt_client.c, subsys/bluetooth/rpc/host/bt_rpc_conn_host.c, subsys/bluetooth/rpc/host/bt_rpc_gap_host.c, subsys/bluetooth/rpc/host/bt_rpc_gatt_host.c
PR fixes minor bug with RPC GATT implementation without SMP. Also, `static` keyword was added to all local functions to improve compiler optimization ability.
=> bluetooth: rpc: rpc clean up and optimization

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/nrf_modem_lib/lte_net_if/lte_net_if.c
Print log warning instructing user to install
SIM card if UICC error is detected.
IRIS-7432
=> lib: nrf_modem: net_if: Include SIM help message

applications/nrf_desktop/sample.yaml, scripts/quarantine_integration.yaml
PR adds harness to sample.yaml to introduce a simple validation. The harness is used only by configurations that provide logs over UART. PR also moves part of test configuration under common to avoid duplication.
PR also adds USB next release configuration to sample.yaml to ensure that the configuration builds without problems.
Jira: NCSDK-26996
=> applications: nrf_desktop: Add harness to sample.yaml

samples/nfc/record_launch_app/sample.yaml, samples/nfc/record_text/sample.yaml, samples/nfc/shell/sample.yaml, samples/nfc/system_off/sample.yaml, samples/nfc/tag_reader/sample.yaml, samples/nfc/tnep_poller/sample.yaml, samples/nfc/tnep_tag/sample.yaml, samples/nfc/writable_ndef_msg/sample.yaml, scripts/ci/tags.yaml
Extend list of paths used to check if nfc
=> samples: nfc: add nfc tag for samples

subsys/suit/orchestrator/src/suit_orchestrator_sdfw.c, subsys/suit/storage/include/suit_storage.h, tests/subsys/suit/orchestrator/orchestrator_sdfw_nrf54h20/src/test_init.c
In case of duplicate MPIs, it is better to enter failed state than reboot the device.
Ref: NCSDK-28377
=> suit: Handle duplicate MPIs as icorrect MPI value

doc/nrf/releases_and_maturity/migration/migration_sysbuild.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, sysbuild/CMakeLists.txt, sysbuild/Kconfig.mcuboot, sysbuild/Kconfig.sysbuild, west.yml
Adds a Kconfig option to sysbuild that will allow using all available RAM on the nRF5340 when using TF-M, will automatically select the clean up Kconfig option in MCUboot
NCSDK-28329
Note: sub-optimal solution, needs an upstream enhancement to allow sysbuild to know if it is targeting a TF-M non-secure board
=> sysbuild: Add TF-M MCUboot option to use all nRF5340 RAM

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/nrf_cloud_rest_device_message/overlay_nrfcloud_logging.conf
Updated the overlay_nrfcloud_logging.conf to remove the comments for dictionary-based logging which is not available for the REST protocol.
=> samples: cellular: nrf_cloud_rest_device_message: update logging

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/nrf_cloud_multi_service/Kconfig, samples/cellular/nrf_cloud_multi_service/src/application.c
Add the CONFIG_TEST_COUNTER_MULTIPLIER KConfig option, which multiplies the number of test counter messages sent every time the test counter updates.
IRIS-9198
=> samples: cellular: mss: Add test counter multiplier

doc/nrf/external_comp/bt_fast_pair.rst, doc/nrf/libraries/bluetooth_services/services/fast_pair.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/bluetooth/adv_prov/fast_pair.h, include/bluetooth/services/fast_pair/fast_pair.h, samples/bluetooth/fast_pair/locator_tag/src/fp_adv.c, subsys/bluetooth/adv_prov/providers/Kconfig.fast_pair, subsys/bluetooth/adv_prov/providers/fast_pair.c, subsys/bluetooth/services/fast_pair/Kconfig.fast_pair, subsys/bluetooth/services/fast_pair/fp_advertising.c, subsys/bluetooth/services/fast_pair/fp_gatt_service.c, subsys/bluetooth/services/fast_pair/fp_keys.c
Added a new Kconfig option for the Fast Pair Subsequent Pairing feature. As a result, this previously supported feature is now configurable and can be disabled for the locator tag use case, which does not support subsequent pairing.
Aligned the Fast Pair Advertising Provider with the new Kconfig option for the Fast Pair service, which controls the Subsequent Pairing feature.
Removed the unavailable API call of the Fast Pair Advertising Provider from the Fast Pair Locator Tag sample.
Ref: NCSDK-27955
=> bluetooth: fast_pair: separate subsequent pairing feature into Kconfig

west.yml
Pull in new I2C BME688 test cases
Signed-off-by: Bartosz Miller <bartosz.miller@nordicsemi.no>
=> manifest: Pull in sdk-zephyr with updated i2c test

samples/matter/lock/sample.yaml, scripts/quarantine_integration.yaml
This PR adds sample.matter.lock.nus on nrf54l15 and adds it to quarantine on integration
=> samples: matter: lock sample on nRF54l15 added

subsys/nrf_security/Kconfig, subsys/nrf_security/src/drivers/CMakeLists.txt
This adds support for the configuration
NRF_SECURITY_LEGACY_AND_PSA with the nRF54L15
devices.
Ref: NCSDK-27932
=> nrf_security: Support legacy and PSA APIs in 54L15

samples/matter/common/src/dfu/smp/dfu_over_smp.cpp, samples/matter/common/src/dfu/smp/dfu_over_smp.h, west.yml
Updated Matter repository to pull the change introducing DFUSync module and use in the DFU over SMP implementation in Matter.
=> samples: matter: Used DFUsync module in the DFU over SMP

subsys/mpsl/cx/Kconfig, subsys/mpsl/cx/bluetooth/mpsl_cx_1w_bluetooth.c
To support Coex 1W with nrf52_bsim, SOC_COMPATIBLE_NRF52X is used instead of SOC_SERIES_NRF52X.
=> mpsl: Use soc compatible definition to include bsim

samples/pmic/native/npm1300_fuel_gauge/src/fuel_gauge.c
Use BIT instead of BIT_MASK when masking CC charge status bit.
=> samples: npm1300_fuel_gauge: Fix CC bitmask

subsys/suit/mci/src/suit_mci_nrf54h20.c
This PR disables The validation skip of SDFW and
nordic top manifests based on LCS.
This way the signature of these manifests is always checked.
=> subsys: suit: Always validate signatures for secdom

west.yml
Pull fixes for ICD LIT config and `zap-generate` `-o` path.
=> manifest: sdk-connectedhomeip: Update revision

scripts/ci/tags.yaml
Missing path to sample in dependencies.
=> scripts: ci: tags: add suit samples path

doc/nrf/links.txt, doc/nrf/test_and_optimize/debugging.rst, samples/peripheral/radio_test/README.rst
Updated links pointing to the documentation for the nPM PowerUP and RSSI Viewer apps in nRF Connect for Desktop. NCD-684 and NCD-686.
----
=> doc: update links to nPM PowerUP and RSSI Viewer

doc/nrf/releases_and_maturity/migration/migration_sysbuild.rst
Removes a comment about missing OpenSSL signing support for MCUboot images as this feature has actually never been supported in ncs, only secure boot signing has supported it
=> doc: nrf: releases: migration: sysbuild: Remove MCUboot comment

modules/trusted-firmware-m/tfm_boards/services/include/tfm_platform_user_memory_ranges.h, modules/trusted-firmware-m/tfm_boards/src/tfm_platform_system.c, west.yml
Adds a service which allows writing to secure memory from the non-secure application for specific memory locations.
Adds an option to configure the RRAMC controller to low power mode from the non-secure application.
Ref: NCSDK-27159
=> modules: TF-M: Allow RRAMC configuration from the non-secure app

applications/nrf_desktop/configuration/nrf54l15pdk_nrf54l15_cpuapp/prj.conf, applications/nrf_desktop/configuration/nrf54l15pdk_nrf54l15_cpuapp/prj_fast_pair.conf, applications/nrf_desktop/configuration/nrf54l15pdk_nrf54l15_cpuapp/prj_keyboard.conf, applications/nrf_desktop/configuration/nrf54l15pdk_nrf54l15_cpuapp/prj_release.conf, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Assign RRAM write buffer size to ensure short write slots. Trying to allocate long write slots while maintaining a BLE connection with short interval and no connection latency may lead to timeouts in flash_sync_mpsl.
Jira: NCSDK-28416
=> applications: nrf_desktop: Use smaller write buffer size for RRAM

drivers/wifi/nrf700x/Kconfig, drivers/wifi/nrf700x/src/fmac_main.c
[SHEL-2054] A wmm was by default set to 1. Adding a kconfig option for WMM. By default it will be enabled. If user needs to disable it, set it as the n.
[SHEL-2054]: https://nordicsemi.atlassian.net/browse/SHEL-2054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> wifi: Add kconfig option to disable wmm mode

applications/asset_tracker_v2/sample.yaml, applications/asset_tracker_v2/tests/debug_module/testcase.yaml, applications/asset_tracker_v2/tests/json_common/testcase.yaml, applications/asset_tracker_v2/tests/location_module/testcase.yaml, applications/asset_tracker_v2/tests/lwm2m_codec_helpers/testcase.yaml, applications/asset_tracker_v2/tests/lwm2m_integration/testcase.yaml, applications/asset_tracker_v2/tests/nrf_cloud_codec/testcase.yaml, applications/asset_tracker_v2/tests/nrf_cloud_codec_mocked_cjson/testcase.yaml, applications/asset_tracker_v2/tests/ui_module/testcase.yaml, scripts/ci/tags.yaml
Extend list of paths used to check if asset_tracker application and test should be executed.
=> applications: asset_tracker_v2: add tag for asset_tracker

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/peripheral/802154_sniffer/prj.conf
I observed that with the default number of RX buffers, 16, the sniffer starts dropping frames when sending 40 frames of size 115B, with the gap of 1ms (tested with "ltx 40 1" PHY test sample's command).
Increase the number of RX buffers to reduce the frame drops. With the new setting, I am able to run "ltx 250 1" without a drop.
=> samples: 802154_sniffer: reduce chances of missed frames

cmake/sysbuild/partition_manager.cmake
Fixes an issue in sysbuild whereby relative path static PM files provided by the user were not used because the path was being treated as relative to the sysbuild folder in zephyr, not the application configuration directory
NCSDK-28451
=> sysbuild: Fix broken partition manager handling of static PM files

subsys/bluetooth/controller/hci_internal.c
Add new VS command VS Set Event Start Task to the hci driver.
=> sdc: handle opcode for VS Set Event Start Task

samples/bluetooth/central_hids/README.rst, samples/bluetooth/fast_pair/input_device/README.rst, samples/bluetooth/fast_pair/locator_tag/README.rst, samples/bluetooth/peripheral_hids_keyboard/README.rst, samples/bluetooth/peripheral_hids_mouse/README.rst
Change adds note referring to nRF Desktop to BLE HID samples. Change also adds reference to nRF Desktop from Fast Pair input device sample.
Jira: NCSDK-28448
=> samples: bluetooth: Link to nRF Desktop from samples using BLE HID

scripts/ci/tags.yaml, tests/modules/mcuboot/direct_xip/testcase.yaml, tests/modules/mcuboot/external_flash/testcase.yaml
Extend tags for CI test scope selection.
=> tests: modules: mcuboot: add tags for mcuboot tests

scripts/ci/tags.yaml, tests/subsys/dfu/dfu_multi_image/testcase.yaml, tests/subsys/dfu/dfu_target/mcuboot_bootloader/testcase.yaml, tests/subsys/dfu/dfu_target/smp/testcase.yaml, tests/subsys/dfu/dfu_target_stream/testcase.yaml
Extend tags for CI test scope selection.
=> tests: subsys: dfu: add tags for dfu tests

subsys/bluetooth/CMakeLists.txt, subsys/bluetooth/Kconfig
When using a remote HCI image, the LL KConfig is not available. Match the approach used by host_extensions and always build the VS command wrappers if CONFIG_BT is set.
The remote LL can return unsupported BTLE command if it's not SDC.
=> bluetooth: Always build hci_vs_sdc if CONFIG_BT is selected

cmake/sysbuild/image_signing_firmware_loader.cmake, sysbuild/CMakeLists.txt, sysbuild/image_configurations/firmware_loader_image_default.cmake
Adds support for having an image designated as a firmware loader image
NCSDK-27560
=> sysbuild: Fix firmware loader for MCUboot support

subsys/nrf_rpc/nrf_rpc_os.c
=> nrf_rpc: Fix too large a bit shift value

include/bluetooth/mesh/light_hsl_srv.h, include/bluetooth/mesh/light_temp_srv.h, include/bluetooth/mesh/lightness_srv.h
This commit adds metadata to the Light Lightness Server, Light HSL
Server, Light CTL Temperature Server models in form of an optional parameter.
Note: Metadata is only supported if the Large Composition Data Server model is supported.
=> Bluetooth: Mesh: add metadata to lighting models

samples/wifi/radio_test/sample.yaml
With sysbuild the issue NCSDK-22755 is fixed, so, add a combo build for radio test.
=> samples: wifi: radio_test: Add BLE combo

subsys/bluetooth/controller/Kconfig
This has been replaced by new zephyr path loss monitoring kconfig.
=> bluetooth: controller: kconfig: remove old sdc plm kconfig

applications/protocols_serialization/client/Kconfig
By default BT_CTLR is set to BT on nRF52 and nRF54 DKs, but for the client application we need this to be 'n'.
=> applications: protocols_serialization: set BT_CTLR to n on client

applications/protocols_serialization/sample.yaml, applications/protocols_serialization/snippets/log_rpc/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, applications/protocols_serialization/snippets/log_rpc/snippet.yml, samples/nrf_rpc/ps_client/sample.yaml, subsys/logging/log_rpc_group.h, subsys/mpsl/cx/software/mpsl_cx_software_rpc.c
Commit adds config nesessary to compile nrf54l with `coex` and `log_rpc` snippets. Also adds former to sample.yml for twister build.
=> aplications: protocols_serializations: Add config for nrf54l.

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c
Adds basic handling and roll back of KMU in case of power failures.
test_crypto: PR-645
=> cracen: Add handling of power failures

doc/nrf/protocols/matter/end_product/certification.rst
Added information about Test Event Triggers to the generic Matter certification page.
=> doc: Matter certification: add a link to the Test Event Triggers page

samples/matter/common/cmake/source_common.cmake, samples/matter/common/src/Kconfig, samples/matter/common/src/app/matter_init.cpp, samples/matter/common/src/test/test_shell.cpp, samples/matter/common/src/test/test_shell.h, samples/matter/template/sample.yaml, scripts/quarantine_integration.yaml
This commit adds test_shell module.
It also implements `resstorage clear` command which cleans Resumption Storage for given fabric id (or all fabrics if fabric id not specified).
=> samples: matter: Add test specific commands

subsys/mpsl/fem/simple_gpio/mpsl_fem_simple_gpio.c
The vaiables `ctx_gpiote_channel` and `crx_gpiote_channel` were marked as uninitialized by static analysis tool.
There is no bug, because these values are set by successful call to `nrfx_gpiote_channel_alloc`. In case of failure the variables are not used.
This commit just makes static analysis happy.
Ticket: KRKNWK-19242
=> mpsl: fem: fix initial values to happify static analysis

include/bluetooth/hci_vs_sdc.h, subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/hci_internal.c, subsys/bluetooth/hci_vs_sdc.c
This is a proprietary SDC feature which allows the controller to produce reports for all ACL connections whenever	  a connection anchor point is updated. The reporting is enabled through a HCI command.
This information can be utilized for time synchronization between a central and peripheral.
=> Bluetooth: Expose API to obtain connection event anchor point

samples/bluetooth/peripheral_uart/README.rst
Several subsections in the sample README.txt used to link to "Activating sample extensions" section that discribe how to build this sample in different configuration variants. The addition of a specific BLE RPC subsection made the links point to the new section instead of the correct one ("Activating...")
=> doc: BLE peripheral_uart - fix linking to sample extensions section

applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.h, doc/nrf/glossary.rst, include/bluetooth/nrf/host_extensions.h, include/bluetooth/radio_notification_cb.h, samples/bluetooth/direct_test_mode/README.rst, samples/bluetooth/direct_test_mode/src/dtm.c, samples/bluetooth/direction_finding_connectionless_rx/src/main.c, samples/bluetooth/iso_time_sync/src/cis_central.c, samples/bluetooth/iso_time_sync/src/iso_tx.c, subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/ecdh.c, subsys/bluetooth/controller/hci_internal.c, subsys/bluetooth/services/mds.c
The section numbers do not change between revisions, therefore we can safely remove them.
By removing them we also avoid having to update
code when a new spec comes out.
References were found by looking for the regex pattern `Core[_ ]v?[45]`.
=> Bluetooth: Remove core spec version number from refs

subsys/bluetooth/controller/hci_driver.c
The 3-wire mpsl_coex interface was removed in NCS 2.4, so these Kconfigs no longer exist. This API is now removed from the controller, so remove dead code related to it.
=> bluetooth: controller: Remove call to deprecated SDC coex method

subsys/bluetooth/controller/hci_internal.c
If sdc_hci_get did not have an event we were reading uninitialized memory.
=> Bluetooth: Controller: Fix reading uninitialized memory

scripts/partition_manager_output.py
In the documentation we have to following example:
```yaml
fatfs_storage:
affiliation: disk
extra_params: {
disk_name: "SD",
disk_cache_size: 4096,
disk_sector_size: 512,
disk_read_only: 0
}
placement:
before: [end]
align: {start: 4096}
inside: [nonsecure_storage]
size: 65536
```
Unfortunately this does not compile in NCS this is due to the affiliation parameter is assumed to be a list in the python code. Resulting in the parsed parameter to be `['d', 'i', 's', 'k']` instead of `['disk']`.
To generate the correct parameter the correct example would be:
```yaml
fatfs_storage:
affiliation:
- disk
extra_params: {
disk_name: "SD",
disk_cache_size: 4096,
disk_sector_size: 512,
disk_read_only: 0
}
placement:
before: [end]
align: {start: 4096}
inside: [nonsecure_storage]
size: 65536
```
However …
=> partition_manager_output.py: Convert affiliation string to list

applications/nrf_desktop/description.rst
Aligned the Fast Pair model for mouse in the  nRF Desktop application with the Google Nearby Console configuration.
=> applications: nrf_desktop: doc: align Fast Pair demo model for mouse

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/blkcipher.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_derivation.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
PSA specifies that key bits should be determined from the key buffer when bits=0 is specified in attributes at import.
test_crypto: PR-646
=> cracen: Fix handling of key_bits=0

include/bluetooth/mesh/light_hsl_srv.h, include/bluetooth/mesh/light_temp_srv.h, include/bluetooth/mesh/lightness_srv.h, include/bluetooth/mesh/sensor_srv.h, include/bluetooth/mesh/time_srv.h
This commit adds metadata to the Sensor Server, and Time Server models in form of an optional parameter.
Note: Metadata is only supported if the Large Composition Data Server model is supported.
=> Bluetooth: Mesh: add metadata to missing models

doc/nrf/config_and_build/bootloaders/bootloader_adding_sysbuild.rst
Some correction to MCUboot firmware loader documentation.
- Emphasise the bigger space for main application as the advantage of this mode.
- Described requirements for the firmware_loader partition.
=> doc/../bootloaders: mcuboot firmware loader correction

applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c, applications/nrf_desktop/src/modules/ble_conn_params.c, applications/nrf_desktop/src/modules/ble_qos.c, samples/bluetooth/connection_event_trigger/src/main.c, samples/bluetooth/iso_time_sync/src/iso_tx.c, samples/bluetooth/llpm/src/main.c, subsys/bluetooth/host_extensions/host_extensions.c, subsys/caf/modules/ble_state.c
The new header `hci_vs_sdc.h` provides APIs that wraps handling of HCI commands creating code that is simpler to understand and maintain. This PR updates some existing code to use these APIs.
=> Bluetooth: Get rid of HCI boilerplate code for vendor specific commands

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c
We can use /d2c/bulk now instead of the older verbose form that included the device_id.
Jira: IRIS-8337
=> net: lib: nrf_cloud_coap: use shorter rsc

CODEOWNERS
Those files controls twister test scope selection.
=> CODEOWNERS: add owners for scripts/ci tags and ignores

doc/nrf/security/ap_protect.rst
Added information about AP-Protect support for nRF9151, nRF9131, nRF54H20, and nRF54L15 to the matrix table. Hardware documentation links to be updated when available. ICPS-1150.
=> doc: ap-protect: add new SoCs to the list

samples/wifi/thread_coex/README.rst
Update the readme. overlay-ot.conf was removed to make the build work for default configuration and so updating the readme accordingly.
=> samples: wifi: thread_coex: Readme update

samples/wifi/ble_coex/sample.yaml
Add mising ci_build tag for nRF7001 EK.
=> samples: wifi: ble_coex: Add missing tag

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/bluetooth/adv_prov.h, samples/bluetooth/fast_pair/input_device/src/bt_adv_helper.c, samples/bluetooth/fast_pair/locator_tag/src/fp_adv.c, subsys/bluetooth/adv_prov/providers/tx_power.c, subsys/caf/modules/ble_adv.c
The tx_power advertising provider used advertising handle hardcoded to 0.
Added adv_handle parameter to the struct bt_le_adv_prov_adv_state so it can be configurable.
Aligned all users of the adv_prov to properly initialize the structure.
Jira: NCSDK-28077
=> bluetooth: adv_prov: Add adv_handle parameter

applications/serial_lte_modem/overlay-ppp-without-cmux.conf, applications/serial_lte_modem/prj.conf
TF-M logs were observed to use blocking send with UART1, which together with hw-flow-control for UART1 caused the device to jam until the remote end of the UART1 was accessed.
hw-flow-control for UART1 is utilized for SLM when RTT and modem traces are needed simultaneously.
=> applications: serial_lte_modem: Disable TF-M logs

samples/wifi/twt/README.rst, samples/wifi/twt/prj.conf
TWT sample fails without extra `TRAFFIC_GEN_REMOTE_IPV4_ADDR` config, so added it as a default configuration in prj.conf.
=> samples: wifi: twt: Fix build with default configuration

doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/modem/lte_lc.h, lib/lte_link_control/lte_lc.c
Removing the following functions that have been deprecated by PR #13057:
- lte_lc_init()
- lte_lc_init_and_connect()
- lte_lc_init_and_connect_async()
- lte_lc_deinit()
=> lib: lte_link_control: Remove deprecated (de)init functions

applications/nrf_desktop/src/modules/Kconfig.hid_forward, applications/nrf_desktop/src/modules/hid_forward.c, applications/nrf_desktop/src/util/CMakeLists.txt, applications/nrf_desktop/src/util/Kconfig, applications/nrf_desktop/src/util/hid_reportq.c, applications/nrf_desktop/src/util/hid_reportq.h
Change adds generic HID report queue implementation for HID dongle and switches from internal HID report queue to the common utility in HID forward module.
Jira: NCSDK-27400
=> applications: nrf_desktop: Add HID reportq utility and integrate it to HID forward

samples/bluetooth/iso_combined_bis_and_cis/src/combined_bis_cis.c, samples/bluetooth/iso_time_sync/src/cis_central.c
The returned reference is unused.
Found using the semantic patch file:
```
@@
local idexpression conn;
identifier e;
statement S1;
@@
* e = bt_conn_le_create(..., &conn);
... when != bt_conn_unref(conn)
when != if (e == 0) { <+... bt_conn_unref(conn) ...+> } else S1
```
=> Samples: Bluetooth: Fix use of local obtained conn refs

samples/cellular/modem_shell/src/main.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c
Make nRF Cloud and cJSON libraries use system heap instead of kernel heap in `modem_shell` also with CoAP transport. This is needed to avoid running out of memory in some use cases.
The P-GPS implementation used `k_malloc()` to allocate memory, while all other allocations in the nRF Cloud library were done using nrf_cloud_mem hooks. Updated also P-GPS to use the mem hooks.
=> samples: cellular: modem_shell: Make cJSON use system heap with CoAP

lib/lte_link_control/lte_lc.c, lib/lte_link_control/lte_lc_helpers.c, lib/lte_link_control/lte_lc_helpers.h, tests/lib/lte_lc/src/main.c
Added a warning log for registration reject EMM cause from the network. Cleaned up `+CEREG` notification parsing.
=> lib: lte_link_control: Add logging for LTE registration reject

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/dfu/dfu_target/src/dfu_target_modem_delta.c, subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c, tests/subsys/net/lib/lwm2m_fota_utils/src/firmware.c
This PR contains 3 separate fixes for push-mode FOTA.
We should take care to not return any other error than
what lwm2m_obj_firmware.c handles. If we for example return
-EACCESS, then LwM2M content format writer ignores that as
it is supposed to skip over write requests to read-only
resources. So we now default to -EFAULT, so we don't
cause any undefined behaviour.
Push mode handler should follow what fota_download.c does.
When FOTA fails, we should call dfu_target_done(false), so it also
tells modem to reset FOTA process in case of delta package.
dfu_target_reset() does not seem to be enough, it only erases the area.
Handle erasing when a new FOTA process starts, but only if offset is
showing that we need it.
When Block N=0 is retransmitted, our FOTA handler might see that
as a …
=> lwm2m: Fixes for push mode FOTA

applications/nrf5340_audio/tools/buildprog/buildprog.py
Add --sysbuild in buildprog.py for handling the build out of default path.
OCT-NONE
=> applications: nrf5340_audio: Add sysbuild config in buildprog.py

.github/workflows/pip-requirements.yml
Setuptools==72.0.0 removes 'setuptools.command.test' used by some package.
=> workflows: Fix setuptools version

include/data_fifo.h, lib/data_fifo/data_fifo.c, tests/lib/data_fifo/src/main.c
The data FIFO module did not have a deinitialise function, so added one, with a twister test.
=> applications: nrf5340_audio: Add a deinitialise function

drivers/wifi/nrf700x/src/fmac_main.c, drivers/wifi/nrf700x/src/net_if.c, drivers/wifi/nrf700x/src/shim.c, drivers/wifi/nrf700x/src/wifi_mgmt.c, drivers/wifi/nrf700x/src/wifi_mgmt_scan.c, drivers/wifi/nrf700x/src/wifi_util.c, drivers/wifi/nrf700x/src/wpa_supp_if.c, samples/wifi/radio_test/src/nrf_wifi_radio_ficr_shell.c, west.yml
Removes the requirement for the different layers in the OS agnostic parts of the driver having to maintain a handle to the OS interface layer in order to call the OS interface calls. The OS interface layer now maitains the handle to OS-specific ops internally and invokes the appropriate functions.
Fixes SHEL-2639
=> nrf_wifi: Remove dependency on OSAL layer handle

applications/nrf5340_audio/broadcast_sink/Kconfig.defaults, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c, applications/nrf5340_audio/unicast_server/Kconfig.defaults
Add available/support context type to PACS in broadcast sink. Enable BT_PAC_SRC_NOTIFIABLE for unicast client.
OCT-3089
=> applications: nrf5340_audio: Improve PACS contents for BIS/CIS

applications/serial_lte_modem/doc/SOCKET_AT_commands.rst, applications/serial_lte_modem/src/slm_at_socket.c
Allow to specify address_family in DNS query request. Support 4 configurations
No hint (default)
With hint, but address_family is unspecified
With hint, address_family is IPv4
With hint, address_family is IPv6
This is further combined with PDN types for test of all DNS query behavior by modem firmware in specific network.
JIRA ticket TNSW-61994
=> application: serial_lte_modem: DNS query enhancement

applications/serial_lte_modem/doc/CARRIER_AT_commands.rst, applications/serial_lte_modem/src/lwm2m_carrier/Kconfig, applications/serial_lte_modem/src/lwm2m_carrier/slm_at_carrier.c
Add `CONFIG_SLM_CARRIER_AUTO_CONTROL` to control automatical handling of below requests from LwM2M in SLM, instead of by host MCU:
- Link down/up
- Power off modem
- Reboot
By default this CONFIG is enabled.
JIRA-ticket: NCSDK-28267
JIRA-ticket: NCSDK-28431
=> application: serial_lte_modem: Automation of LwM2M requests

doc/nrf/config_and_build/configuring_app/building.rst, doc/nrf/config_and_build/configuring_app/output_build_files.rst
Added mention of the `-vvv` option to the optional build params list. Also propagated as a tip to the output build files page. NCSDK-27695.
=> doc: building: mention -v for verbose builds

applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_broadcast.c
Fixed undefined variable.
OCT-NONE
=> applications: nrf5340_audio: Compile error fix

doc/nrf/libraries/nrf_rpc/nrf_rpc_uart.rst, include/nrf_rpc/nrf_rpc_uart.h
Add a documentation page that describes the nRF RPC UART
transport frame encoding and API.
=> nrf_rpc: add documentation page for the UART transport 

samples/bluetooth/fast_pair/locator_tag/CMakeLists.txt, samples/bluetooth/fast_pair/locator_tag/include/app_factory_reset.h, samples/bluetooth/fast_pair/locator_tag/include/app_fp_adv.h, samples/bluetooth/fast_pair/locator_tag/src/factory_reset.c, samples/bluetooth/fast_pair/locator_tag/src/factory_reset_callbacks.ld, samples/bluetooth/fast_pair/locator_tag/src/fp_adv.c, samples/bluetooth/fast_pair/locator_tag/src/fp_adv_trigger.ld, samples/bluetooth/fast_pair/locator_tag/src/main.c
Reworked fp_adv module so the triggers request the state of the advertising instead of setting it directly (works as a mediator).
Jira: NCSDK-28077
Depends on: 
+ https://github.com/nrfconnect/sdk-nrf/pull/16626
=> samples: bluetooth: fast_pair: locator_tag: Rework fp_adv module

scripts/requirements-base.txt, scripts/requirements-fixed.txt
certifi >=2024.7.4 # from requests above;  https://nvd.nist.gov/vuln/detail/CVE-2024-39689
=> scripts: requirements-base.txt update certifi because of CVE

scripts/requirements-build.txt, scripts/requirements-fixed.txt
Update version to align with a bellboard compatible name change in order to fix UICR MAILBOX generation.
=> scripts: requirements-build: update nrf-regtool to 5.5.1

doc/nrf/device_guides/nrf70/nrf7002ek_dev_guide.rst
It's supposed to be EK not EB.
=> doc: nrf: Fix typo in shield name

samples/nrf_rpc/ps_client/snippets/log_rpc/log_rpc.conf
CONFIG_LOG_FORWARDER_RPC requires CONFIG_LOG,
currently we can't build use log_rpc withoud building with
debug snippet.
Signed-off-by: Tomasz Kobylarz <tomasz.kobylarz@nordicsemi.no>
=> samples: nrf_rpc: ps_client: update snippet

subsys/partition_manager/Kconfig
The configurations: NRF_TRUSTZONE_FLASH_REGION_SIZE and NRF_TRUSTZONE_RAM_REGION_SIZE are added after the release and they are not included in the hardware
model 1. This is a workaround for this use case,
since we don't expect to support the nRF54L15 devices with this model this workaround should work for the older generation of devices.
Ref: NCSDK-28479
=> partition_manager: TrustZone HW model 1 workaround

include/bluetooth/services/fast_pair/fmdn.h, subsys/bluetooth/services/fast_pair/fmdn/state.c
Improved management of the FMDN advertising set lifetime in the FMDN extension of the Fast Pair library. The advertising set is now allocated during the bt_fast_pair_enable operation and released during the bt_fast_pair_disable operation.
Ref: NCSDK-22229
=> bluetooth: fast_pair: fmdn: improve fmdn adv set lifetime management

CODEOWNERS
OCT-2935
ncs-audio now used for all relevant areas.
=> Codeowners: Migrate to ncs-audio

applications/protocols_serialization/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, applications/protocols_serialization/snippets/ble/ble.conf
Increase stack size for nRF54l in protocol serialization server. Currently crypto operations take over 5KiB to compleate.
=> nrf_rpc: protocol_serialization: Increase stack size for nrfrpc.

include/logging/log_rpc.h, samples/nrf_rpc/ps_client/src/log_rpc_shell.c, subsys/logging/log_backend_rpc.c, subsys/logging/log_forwarder_rpc.c, subsys/logging/log_rpc_group.h
Add RPC command to configure the maximum level of messages that are expected to be streamed to the RPC client.
=> logging: add RPC command to configure log level

samples/zigbee/light_switch/README.rst
Clarify that tx power is now set to 0 dBm for light switch.
=> doc: samples: zigbee: extend light switch sample tx power info

doc/nrf/config_and_build/configuring_app/building.rst, samples/bluetooth/peripheral_hids_mouse/README.rst
Replaced the bullet-point list of params with a table.
=> doc: building: add table for build params

samples/pmic/native/npm1300_one_button/README.rst, samples/pmic/native/npm1300_one_button/nrf52840dk_nrf52840.overlay
Pin allocation for PMIC interrupt output on nRF52840 DK has been fixed.  It was previously allocated to a pin that is not available on a pin header.
=> samples: npm1300_one_button: Fix irq allocation for nRF52840 DK.

include/nrf_rpc/nrf_rpc_uart.h, subsys/nrf_rpc/Kconfig, subsys/nrf_rpc/nrf_rpc_uart.c
1. Capitalize enum constants.
2. Use Kconfig instead of hard-coded constants.
3. Use more intuitive variable naming.
4. Replace semaphore with mutex for critical section.
5. Move RX work queue stack to the nrf_rpc_uart struct.
This hopefully addresses comments from #16406.
=> nrf_rpc: address UART transport review comments

applications/matter_weather_station/prj.conf, applications/matter_weather_station/prj_release.conf, doc/nrf/protocols/matter/end_product/bootloader.rst, doc/nrf/releases_and_maturity/known_issues.rst, samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/lock/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/thermostat/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/window_covering/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, west.yml
Several configurations contain settings partition of a size inconsistent with the default NVS sectors count, which results in using smaller NVS size than expected.
=> samples: matter: Fixed NVS sectors count in samples configurations

applications/nrf_desktop/sample.yaml
Change adds missing CONFIG_DESKTOP_USB_STACK_NEXT=y to make sure that the application is built with USB next stack.
=> applications: nrf_desktop: Fix USB next release config in sample.yaml

applications/serial_lte_modem/doc/slm_testing.rst
The description for what is required to test acting as a TCP server or UDP server uses a wrong term and isn't clear. This fixes these two sections.
=> doc: update Serial LTE modem testing description

scripts/hid_configurator/NrfHidManager.py
Change adds nrf54h20dk to TYPE2BOARDLIST to ensure that the board is tagged as gaming mouse.
=> scripts: hid_configurator: Add nRF54H20 DK to NrfHidManager's list

applications/nrf_desktop/src/modules/CMakeLists.txt, applications/nrf_desktop/src/modules/Kconfig, applications/nrf_desktop/src/modules/Kconfig.dvfs, applications/nrf_desktop/src/modules/ble_latency.c, applications/nrf_desktop/src/modules/dvfs.c
Add DVFS module for nrf_desktop. It makes sure
application core works on 64MHz by deafult.
It upscales cores frequency to 320MHz when USB is used. It upscales cores frequency to 128MHz when LLPM is used.
JIRA: NCSDK-27399
I will add documentation and changelog in documentation task
=> applications: nrf_desktop: Add DVFS module

doc/nrf/config_and_build/configuring_app/kconfig/index.rst
Edited a line that incorrectly referenced `west build` instead of `west config`. NCSDK-27696.
=> doc: kconfig: fix west config ref description

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/nrf_modem_lib/lte_net_if/lte_net_if.c
Currently, if IPv4 is disabled or was not assigned, the cellular network is incorrectly treated as
offline, even if an IPv6 gets assigned.
This patch fixes this behavior.
=> lib: modem: lte_net_if: Fix handling of missing IPv4

CODEOWNERS
Commit adds Paladin group responsibility for all mesh related sources as well as emds.
=> CODEOWNERS: assign paladin responsibility for mesh and emds

samples/bluetooth/conn_time_sync/src/central.c, samples/bluetooth/conn_time_sync/src/peripheral.c, subsys/bluetooth/host_extensions/host_extensions.c
This file was temporary included until the needed APIs were exposed.
Now we no longer need to include it.
=> Bluetooth: Remove inclusion of conn_internal.h

west.yml
Use secure/nonsecure libraries for secure/nonsecure targets
=> manifest: sdk-nrfxlib: mpsl: Choose nonsecure libraries if building for nonsecure variant

doc/nrf/libraries/modem/at_cmd_custom.rst, doc/nrf/libraries/modem/at_cmd_parser.rst, doc/nrf/libraries/modem/at_params.rst, doc/nrf/libraries/modem/gcf_sms_lib.rst, doc/nrf/libraries/modem/location.rst, doc/nrf/libraries/modem/modem_attest_token.rst, doc/nrf/libraries/modem/modem_jwt.rst, doc/nrf/libraries/modem/modem_slm.rst
Fix incorrect source file paths in the documentation.
=> doc: libraries: modem: correct source file paths for various libraries
