nrfconnect/sdk-nrf

west.yml

Changing the limitations section in bsdlib doc.

manifest: update for bsdlib doc

---

doc/nrf/gs_ins_windows.rst
doc/nrf/release_notes.rst
doc/release-notes-1.1.0.rst

[nRF Connect SDK v1.1.0 Release Notes.pdf](https://github.com/NordicPlayground/fw-nrfconnect-nrf/files/3852295/nRF.Connect.SDK.v1.1.0.Release.Notes.pdf)

Release notes for v1.1.0

---

doc/nrf/gs_ins_windows.rst
doc/nrf/release_notes.rst
doc/release-notes-1.1.0.rst

Manual backport from https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1521

[Manual backport] Backport 1521 to v1.1 branch

---

west.yml

No function change.
Signed-off-by: Rubin Gerritsen <Rubin.Gerritsen@nordicsemi.no>

manifest: Update manifest for ble controller without version number

---

Jenkinsfile

this will be replaced with better solution in v2

ci: fix downstream job selection for PRs with CHANGE_TARGET

---

scripts/hid_configurator/configurator_core.py

Change fixes misleading log for DFU.

scripts: hid_configurator: Fix misleading DFU log

---

scripts/hid_configurator/gui/gui_backend.py

Fix filtering devices in configurator GUI.

scripts: hid_configurator: Fix filtering devices in GUI

---

include/dk_buttons_and_leds.h
lib/dk_buttons_and_leds/Kconfig
lib/dk_buttons_and_leds/dk_buttons_and_leds.c

Adds ability to add and remove any number of button handlers at runtime.

lib: dk_buttons_and_leds: Multiple button handlers

---

applications/asset_tracker/src/cloud_codec/cloud_codec.c
applications/asset_tracker/src/cloud_codec/cloud_codec.h
applications/asset_tracker/src/main.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c

Add high/low threshold config command handling for sensor data.

applications: asset_tracker: add sensor threshold cfg

---

CODEOWNERS
doc/nrf/samples.rst
samples/mpsl/timeslot/CMakeLists.txt
samples/mpsl/timeslot/README.rst
samples/mpsl/timeslot/prj.conf
samples/mpsl/timeslot/sample.yaml
samples/mpsl/timeslot/src/main.c

Add MPSL sample that demonstrates how to use basic MPSL Timeslot
functionality.
Signed-off-by: Solveig Fure <Solveig.Fure@nordicsemi.no>

samples: mpsl: timeslot: Add MPSL Timeslot example.

---

samples/mpsl/timeslot/src/main.c

Make MPSL timeslot sample thread-safe by calling all MPSL functions
from cooperative thread. This way, MPSL function calls cannot be
interrupted by mpsl_low_priority_process().
Signed-off-by: Solveig Fure <Solveig.Fure@nordicsemi.no>

samples: mpsl: timeslot: thread-safe MPSL timeslot sample

---

subsys/bluetooth/controller/hci_driver.c

When using interrupts with ISR_DIRECT_CONNECT(), ISR_DIRECT_DECLARE()
should be used.
Signed-off-by: Rubin Gerritsen <Rubin.Gerritsen@nordicsemi.no>

bluetooth: controller: Use ISR_DIRECT_DECLARE for ble controller ISRs

---

lib/at_notif/at_notif.c

Documentation update of the module header file.
Signed-off-by: Christopher Métrailler <christopher.metrailler@nordicsemi.no>

lib: at_notif: Update documentation

---

scripts/partition_manager.py

It is not allowed for a partition to define an empty 'placement' property.
Raise a RunTimeError if this is found.
Also add a test ensuring that the error is raised.

partition_mananger: ensure no empty 'placement' properties

---

include/at_cmd_parser/at_cmd_parser.rst
include/at_cmd_parser/at_params.h

Documentation update of the module header file.
Signed-off-by: Christopher Métrailler <christopher.metrailler@nordicsemi.no>

lib: at_cmd_parser: Update documentation

---

applications/nrf_desktop/src/modules/ble_scan.c
samples/bluetooth/llpm/src/main.c

The vendor specific HCI API removes the use of hidden RFU values in the HCI Connection Parameter Update command. This API is future compatible, the Connection Parameter Update Command may not. It becomes easy to understand how to update the connection interval to 2 ms or similar.

bluetooth: llpm: Use hci vs conn update

---

samples/bluetooth/mesh/light/README.rst

Removes merge conflict from samples/mesh/light/README.rst

Bluetooth: Mesh: Address merge conflict commit

---

subsys/bluetooth/services/hids.c

Use the bt_gatt_is_subscribed function instead of having our own
implementation of it in hids. This is safer because the API can check
for correct ID in case multiple identities are used. And the ccc_cfg
structure is internal and cannot be relied on to be non-changing.

Bluetooth: services: hids: Use bt_gatt_is_subscribed instead

---

samples/bluetooth/central_bas/sample.yaml
samples/bluetooth/central_dfu_smp/sample.yaml
samples/bluetooth/central_hids/sample.yaml
samples/bluetooth/central_uart/sample.yaml
samples/bluetooth/llpm/sample.yaml
samples/bluetooth/mesh/light/sample.yaml
samples/bluetooth/peripheral_gatt_dm/sample.yaml
samples/bluetooth/peripheral_hids_keyboard/sample.yaml
samples/bluetooth/peripheral_hids_mouse/sample.yaml
samples/bluetooth/peripheral_lbs/sample.yaml
samples/bluetooth/peripheral_uart/sample.yaml
samples/bluetooth/shell_bt_nus/sample.yaml
samples/bluetooth/throughput/sample.yaml
samples/nfc/record_text/sample.yaml
samples/nfc/tag_reader/sample.yaml
samples/nfc/writable_ndef_msg/sample.yaml

This PR provides a valid setup platform for CI and also alignment for name and description in
Bluetooth and NFC samples

Sample yaml CI platform, name and desciptions align

---

applications/nrf_desktop/configuration/common/hid_report_desc.c

Change updates HID feature reports to use vendor specific data. Fixes hidapi problems observed on Windows.

applications: nrf_desktop: Update HID feature reports

---

applications/nrf_desktop/src/modules/usb_state.c

Change fixes USB get_report and set_report. Only feature reports are currently supported.

applications: nrf_desktop: Fix USB get_report and set_report

---

drivers/bt_ll_nrfxlib/clock_control/clock_control_nrfxlib.c

According to https://github.com/zephyrproject-rtos/zephyr/issues/16273
it is necessary to check if the context is necessary to check if the
context is atomic before obtaining a lock. Otherwise, if a spinlock is held while
you call lock/unclock, the scheduling might get corrupted.
Signed-off-by: Rubin Gerritsen <Rubin.Gerritsen@nordicsemi.no>

bluetooth: drivers: Check if context is atomic before obtaining lock

---

applications/nrf_desktop/src/modules/usb_state.c

Change fixes logs for set and get report (USB).

applications: nrf_desktop: Fix logs for set and get report

---

applications/asset_tracker/src/cloud_codec/cloud_codec.c
applications/asset_tracker/src/cloud_codec/cloud_codec.h
applications/asset_tracker/src/main.c

Modified command format to match format used by
nrf cloud.

applications: asset_tracker: cloud cmd json format

---

applications/nrf_desktop/src/modules/ble_scan.c

Change adds setting initial connection parameters on dongle.

applications: nrf_desktop: Set initial connection parameters

---

applications/nrf_desktop/src/hw_interface/Kconfig.buttons
applications/nrf_desktop/src/hw_interface/buttons.c

Change fixes starting initial scan in buttons module and reduces scan interval.

[DNM] applications: nrf_desktop: Fix initial buttons scan

---

doc/nrf/ug_multi_image.rst

Minor doc changes to multi-image

nrf: doc: Minor doc changes to multi-image

---

applications/nrf_desktop/src/modules/hid_forward.c

When peripheral device connected via dongle disconnects with pressed key, the information about key release is never propagated to the host. Change adds sending HID report with all the keys released on peripheral disconnection.

applications: nrf_desktop: Fix key pressed forever on disconnection

---

doc/nrf/links.txt
samples/nrf9160/coap_client/README.rst

nRF9160 CoAP Client sample documentation improvement
ref: https://projecttools.nordicsemi.no/jira/browse/NCSDK-3269
[nRF9160_ nRF CoAP Client — nRF Connect SDK 1.1.99 documentation.pdf](https://github.com/NordicPlayground/fw-nrfconnect-nrf/files/3956032/nRF9160_.nRF.CoAP.Client.nRF.Connect.SDK.1.1.99.documentation.pdf)

doc: nRF9160 CoAP Client sample documentation improvement

---

subsys/bluetooth/controller/hci_driver.c
west.yml

Also fixed an issue on nRF53 where the radio stayed in the TX state longer than expected.

Ble controller: Support configurable dle

---

scripts/partition_manager.py

Fix a bug where the 'app' partition would not be included in the
output configuriton in the case where a static configuration
was given, and there was no unresolved partitions.

scripts: fix bug for static configuration with nothing to resolve

---

scripts/bootloader/asn1parse.py
scripts/bootloader/do_sign.py
scripts/bootloader/keygen.py
scripts/partition_manager_output.py

Fix pylint issues for all bootlader related python files.

scripts: fix pylint issues

---

drivers/lte_link_control/lte_lc.c

When issuing a CEREG? command an additional parameter <n> signifying the
current supported unsolicited results code is included in the modem
response. This resulted in the wrong index being used when reading out
the current network registration status.
Signed-off-by: Simen S. Røstad <simen.rostad@nordicsemi.no>

drivers: lte_lc: Use correct index for network reg statuses

---

scripts/partition_manager.py

Fix bug where the first partition could not have alignment requirement.

partition_manager: allow alignment of first partition

---

applications/nrf_desktop/README.rst

Changed the structure of the nrf_desktop doc for updates by the desktop team.

doc: update nrf_desktop doc structure

---

west.yml

west.yml changes for the new zephyr history.

Zephyr history 2.1

---

applications/nrf_desktop/README.rst

Change adds building and running description for the project.

applications: nrf_desktop: Add building and running description

---

.github/workflows/backport.yml
CODEOWNERS
west.yml

Using NordicBuilder user and free-tier actions

ci: Adding Github-Actions:Backport-Bot

---

Jenkinsfile

also fix ci-tools python requirements

ci: add common cron configuration

---

include/bluetooth/scan.h
subsys/bluetooth/scan.c

Change adds initial connection parameters update function.

Bluetooth: scan: Add initial conn parameters update function

---

cmake/multi_image.cmake
subsys/spm/CMakeLists.txt

Create a function for writing to the shared vars file for
a child image.

cmake: function to write to shared_vars file

---

applications/nrf_desktop/README.rst

applications: nrf_desktop: Add user guide

---

applications/asset_tracker/src/env_sensors/bsec.c

Updated the BSEC integration to work with the improved env_sensors api.
It is now possible to build asset tracker application with BSEC library
support again.
Jira:TG91-150

applications: asset_tracker: Update BSEC to improved env_sensors api

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/porting_guide.rst
doc/nrf/images/nrf_desktop_arch.svg
doc/nrf/images/nrf_desktop_arch_dmouse.svg
doc/nrf/images/nrf_desktop_arch_dongle.svg
doc/nrf/images/nrf_desktop_arch_gmouse.svg
doc/nrf/images/nrf_desktop_arch_kbd.svg

applications: nrf_desktop: Architecture overview image

---

applications/nrf_desktop/README.rst

applications: nrf_desktop: Update info about thread and memory

---

samples/bluetooth/throughput/src/main.c

Fix throughput test not achieving the expected throughput.
The occurred because the scanner was active during the throughput test
as bt_le_create_conn had already been called when the slave connection
was established.
It was not possible to cancel this connection object in the connecting
state because the same object is used to reference the slave connection.
This happens because the test is trying to establish connections in both
master and slave role at the same time. This use case is not supported
by the zephyr host, and can lead to connection object confusion as two
contexts are connected to the same bluetooth device. The API
bt_conn_lookup_addr_le does not work for this scenario.
Also fixed issues where wrong variable was used for err, mixing u8_t and
int, as well other cases where …

samples: bluetooth: throughput: Fix scan active during throughput test

---

applications/nrf_desktop/src/modules/ble_adv.c

Delay advertising start using k_work to ensure that disconnected connection will be unref before advertising starts.

applications: nrf_desktop: Delay advertising start

---

include/at_cmd.rst

moved the doc to include/drivers, updated the document
after a language review

doc: moved the doc to include/drivers, language review

---

applications/asset_tracker/Kconfig
applications/asset_tracker/src/gps_controller/gps_controller.c
applications/asset_tracker/src/gps_controller/gps_controller.h
applications/asset_tracker/src/main.c
lib/at_cmd/at_cmd.c

application: asset_tracker: Add a separate workqueue for application.

---

include/net/cloud.rst
samples/nrf9160/cloud_client/CMakeLists.txt
samples/nrf9160/cloud_client/Kconfig
samples/nrf9160/cloud_client/README.rst
samples/nrf9160/cloud_client/prj.conf
samples/nrf9160/cloud_client/sample.yaml
samples/nrf9160/cloud_client/src/main.c

This sample is intended to showcase the generic cloud API and
its functionality. The generic cloud API makes it possible to change
cloud backends statically and at run-time
Signed-off-by: Simen S. Røstad <simen.rostad@nordicsemi.no>

samples: nrf9160: Added Cloud Client sample

---

applications/asset_tracker/src/gps_controller/gps_controller.c

applications: asset_tracker: Fix issue building QEMU target

---

include/lte_lc.h
include/net/bsdlib.h
include/net/download_client.h

A handful of fixes to libraries to make life in C++ land a little easier.

Cplusplus fixups

---

west.yml

Update the manifest to point to new nrfxlib master.

manifest: nrfxlib: bsdlib update

---

scripts/west_commands/ncs_commands.py

These changes should make west ncs-loot and west ncs-compare a bit more predictable and easier to use, and also include a fix.

West commands tweaks

---

applications/asset_tracker/src/main.c

Changes the way RSRP messages are rate-limited. The transmission
function now schedules itself on the work queue with the configured
interval, ensuring that the latest value is sent after the timeout.
Fixes Jira TG91-124.

applications: asset_tracker: Rework RSRP transmission

---

subsys/net/lib/aws_fota/src/aws_fota.c

`CONNACK` events and `PUBLISH` events were consumed by the `aws_fota`
library. This resulted in MQTT handlers using it not being able to
correctly handle events as expected.

net: lib: aws_fota: Fix return code for CONNACK and PUBLISH

---

samples/nrf9160/lwm2m_client/README.rst

Replace Leshan server IP with URL in the sample document.

doc: specify LwM2M server URL

---

west.yml

Related to:
~~https://github.com/NordicPlayground/fw-nrfconnect-zephyr/pull/273~~

west: update manifest with rpmsg hci bugfix

---

west.yml

Update repos references to match -rc2 tags.

west.yml: Update -rc2 references

---

doc/mcuboot/conf.py
doc/nrf/conf.py
doc/nrfxlib/conf.py
doc/zephyr/conf.py

Update copyright date for the different doc sets.

doc: update copyright date

---

scripts/profiler/plot_nordic.py

Change cleans up closing plot.

scripts: profiler: Cleanup - closing plot

---

applications/nrf_desktop/src/modules/hid_forward.c

Change fixes config channel state handling in HID forward module. This removes the race condition.

applications: nrf_desktop: Fix forwarding HID feature reports

---

applications/nrf_desktop/src/modules/ble_scan.c

Change sets proper initial connection parameters. This is workaround required by nrfxlib Link Layer.

applications: nrf_desktop: Set proper initial connection parameters

---

lib/bsdlib/nrf91_sockets.c

bsdlib expects to receive specific sizes in `p_addrlen` for IPv4 and
IPv6, so we need to add extra address handling when translating from nrf
types to Zephyr types.
Also, add NULL pointer handling.

lib: bsdlib: Fix accept address handling

---

samples/nrf9160/http_application_update/src/main.c

Added a serial output for the specific sample you are running.
Signed-off-by: Martin Lesund <martin.lesund@nordicsemi.no>

samples: nrf9160: http_application_update:  startup message

---

lib/bsdlib/nrf91_sockets.c

bsdlib: nrf91_socket.c
Added error code mapping from nrf to zephyr. 
Signed-off-by: Tommi Mämmelä <tommi.mammela@nordicsemi.no>

Lib: bsdlib: Fix error codes in getaddrinfo

---

doc/nrf/links.txt
include/bluetooth/mesh/models.rst

NCSDK-3361: added details about common parts of models.

doc: expand information about mesh models

---

cmake/s1.cmake
west.yml

This to minimize patches and simplify development
depends https://github.com/NordicPlayground/fw-nrfconnect-zephyr/pull/265

cmake: move s1 patches to nrf repo

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/porting_guide.rst
doc/nrf/links.txt

applications: nrf_desktop: Porting guide

---

doc/nrf/links.txt
include/bluetooth/enocean.h
include/bluetooth/enocean.rst
samples/bluetooth/enocean/CMakeLists.txt
samples/bluetooth/enocean/README.rst
samples/bluetooth/enocean/prj.conf
samples/bluetooth/enocean/sample.yaml
samples/bluetooth/enocean/src/main.c
subsys/bluetooth/CMakeLists.txt
subsys/bluetooth/Kconfig
subsys/bluetooth/Kconfig.enocean
subsys/bluetooth/enocean.c

Adds EnOcean library for observing BLE based EnOcean devices,
as well as a sample demonstrating basic functionality.

Bluetooth: Enocean: Added EnOcean library

---

include/bluetooth/mesh/lightness.h
include/bluetooth/mesh/lightness.rst
include/bluetooth/mesh/lightness_cli.h
include/bluetooth/mesh/lightness_srv.h
include/bluetooth/mesh/models.h
include/bluetooth/mesh/models.rst
subsys/bluetooth/mesh/CMakeLists.txt
subsys/bluetooth/mesh/Kconfig.models
subsys/bluetooth/mesh/lightness_cli.c
subsys/bluetooth/mesh/lightness_internal.h
subsys/bluetooth/mesh/lightness_srv.c

Adds the Light Lightness models:
- Light Lightness Client
- Light Lightness Server
- Light Lightness Setup Server

Bluetooth: Mesh: Light Lightness models

---

applications/nrf_desktop/src/modules/ble_adv.c

Change removes general discoverable from Bluetooth advertising packet in case Peripheral is bonded.

applications: nrf_desktop: Limit discoverability if bonded

---

doc/nrf/libraries.rst
doc/nrf/libraries/lib_bin.rst
doc/nrf/libraries/lib_bluetooth_services.rst
doc/nrf/libraries/lib_networking.rst
doc/nrf/libraries/lib_nfc.rst
doc/nrf/libraries/lib_others.rst

Created subpages for libraries to improve the structure.
ref:https://projecttools.nordicsemi.no/jira/browse/NCSDK-4349

doc: Created subpages for libraries

---

scripts/hid_configurator/configurator_core.py

Change updates report ID used by hid_configurator.
The report ID must match report ID on connected HID device.

scripts: hid_configurator: Update report ID

---

doc/nrf/links.txt
samples/nrf9160/mqtt_simple/README.rst

Added References section with link to a devzone tutorial.

doc: add link to MQTT simple samples

---

doc/nrf/ug_nrf5340.rst

Covered the description of connections for flow control lines in the
network core logging section.
Signed-off-by: Kamil Piszczek <Kamil.Piszczek@nordicsemi.no>

doc: nrf5340_ug: flow control description for logging on net core

---

samples/nrf9160/secure_services/src/main.c

- Allow services to be disabled.
- Print FICR.INFO.VARIANT

Small improvements in secure service sample

---

scripts/partition_manager.py

fix two issues
- one of dicts could not have 'start' and 'end' as references
- empty partitions were not cleared in the correct way

Pm fixes 2

---

west.yml

mcuboot: Add small fix for EXT_API forwarding

---

applications/nrf_desktop/src/modules/ble_adv.c
applications/nrf_desktop/src/modules/ble_bond.c
applications/nrf_desktop/src/modules/ble_scan.c
applications/nrf_desktop/src/modules/fn_keys.c

Change switches to use static settings handlers to save memory.

applications: nrf_desktop: Use static settings handlers

---

west.yml

See corresponding PR for more details: https://github.com/NordicPlayground/nrfxlib/pull/144

manifest: Update nrfxlib revision for new MPSL + BLE controller

---

scripts/hid_configurator/configurator_cli.py
scripts/hid_configurator/configurator_core.py
scripts/hid_configurator/devices.py
scripts/hid_configurator/gui/gui_backend.py
scripts/hid_configurator/modules/config.py
scripts/hid_configurator/modules/dfu.py
scripts/hid_configurator/modules/led_stream.py
scripts/hid_configurator/modules/music_led_stream.py

Move the code related to given functionalities to separate files.

scripts: hid_configurator: Code cleanup

---

drivers/mpsl/clock_control/Kconfig
subsys/mpsl/mpsl_init.c
west.yml

For more details see https://github.com/NordicPlayground/nrfxlib/pull/145

Mpsl with more clock sources

---

applications/nrf_desktop/src/modules/ble_qos.c
scripts/hid_configurator/devices.py

Change fixes configuration update in ble_qos module.

applications: nrf_desktop: Fix ble_qos configuration

---

applications/nrf_desktop/src/modules/hid_forward.c

applications: nrf_desktop: Use single list for stored reports

---

applications/nrf_desktop/src/modules/hid_state.c

application: nrf_desktop: HID state module cleanup

---

west.yml

The libraries are reduced in size.
See https://github.com/NordicPlayground/nrfxlib/pull/146

manifest: Update MPSL + BLE controller

---

applications/asset_tracker/README.rst

Expanded Asset Tracker Overview table with data units.

doc: add data unit column

---

applications/nrf_desktop/src/hw_interface/leds.c

Change adds missing error check in leds module.

applications: nrf_desktop: Add missing error check in leds

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/dev_descr.rst

Change adds Device Description (`dev_descr`) module documentation.

applications: nrf_desktop: Add Device Description documentation

---

applications/nrf_desktop/doc/bas.rst

Change adds BAS documentation.

applications: nrf_desktop: Add BAS documentation

---

applications/nrf_desktop/README.rst

applications: nrf_desktop: Add partition configuration doc

---

applications/nrf_desktop/src/modules/hid_state.c

applications: nrf_desktop: Fix control reports

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/buttons_sim.rst
applications/nrf_desktop/doc/passkey.rst

Change adds passkey module documentation.

applications: nrf_desktop: Add passkey documentation

---

applications/nrf_desktop/configuration/common/hid_report_mouse.h
applications/nrf_desktop/src/modules/hid_state.c

applications: nrf_desktop: Add genric axes support

---

applications/nrf_desktop/doc/buttons_sim.rst

Change adds buttons simulator module documentation.

applications: nrf_desktop: Add buttons_sim documentation

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/ble_adv.rst
applications/nrf_desktop/doc/ble_discovery.rst
applications/nrf_desktop/doc/ble_latency.rst
applications/nrf_desktop/doc/ble_scan.rst
applications/nrf_desktop/doc/ble_state.rst
applications/nrf_desktop/doc/hid_forward.rst
applications/nrf_desktop/doc/power_manager.rst

Change adds BLE state module documentation.

applications: nrf_desktop: Add ble_state documentation

---

doc/nrf/doc_styleguide.rst

Added new sections. Reorganized RST part.

doc: update NCS style guide

---

scripts/partition_manager.py
scripts/partition_manager_output.py

Without these the provision page is not included in merged.hex.

Small Partition Manager fixes for B0 on 91 and 53

---

samples/nrf9160/gps/src/main.c
samples/nrf9160/gps/src/supl_support.c

GPS is stopped while AGPS data is downloaded
Add looping to getaddrinfo
Signed-off-by: Puusaari <kimmo.puusaari@nordicsemi.no>

samples: nrf9160: gps: Improve gps sample

---

applications/nrf_desktop/src/modules/hid_state.c

applications: nrf_desktop: Explicit link report data and sink

---

applications/nrf_desktop/doc/battery_charger.rst

Fix syntax in battery charger module doc.

applications: nrf_desktop: Fix warning in batcharger module doc

---

doc/nrf/templates/mesh_model_main_README.rst
doc/nrf/templates/mesh_model_server_client_template.rst

Added template file for mesh models.

doc: add template for mesh models

---

applications/nrf_desktop/doc/ble_latency.rst

Change adds ble_latency module documentation.

applications: nrf_desktop: Add BLE latency documentation

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/settings_loader.rst

Change adds settings_loader module documentation.

applications: nrf_desktop: Add settings loader documentation

---

applications/nrf_desktop/src/modules/Kconfig.ble

applications: nrf_desktop: ble_adv Kconfig cleanup

---

west.yml

Also updates mpsl and ble controller build revision.
See https://github.com/NordicPlayground/nrfxlib/pull/152

manifest: Update nrfxlib to include mpsl with API docs

---

applications/nrf_desktop/src/modules/hids.c

Change fixes notifying HIDS about the connection. The HID Service should be notified earlier to make sure that the connection context will be allocated in time.

applications: nrf_desktop: Fix HIDS notifying

---

applications/nrf_desktop/doc/config_channel.rst

Change updates documentation for configuration channel.

applications: nrf_desktop: Update config channel doc

---

subsys/bootloader/bl_validation/Kconfig
subsys/bootloader/bl_validation/bl_validation.c

To make it easier to create B0N.

For B0N: Add hash validation to bl_validation

---

applications/nrf_desktop/README.rst

applications: nrf_desktop: Readme cleanup

---

applications/nrf_desktop/src/modules/Kconfig.ble

applications: nrf_desktop: Increase stack size to prevent overflow

---

lib/at_cmd_parser/at_cmd_parser.c

Quoted string split across multiple lines were not parsed correctly.
Added a new state for parsing quoted strings that will ignore line
breaks and carriage returns when looking for the closing quote.

lib: at_cmd_parser: fix parsing of quoted strings

---

applications/nrf_desktop/sample.yaml

Change fixes sample.yaml description. The name and description fields were swapped.

applications: nrf_desktop: Fix sample.yaml

---

scripts/west_commands/ncs_commands.py

This makes the ncs-loot command match the ncs-compare command in
always looking at manifest-rev instead of project.revision.
That in turn lets you run 'west update' and then run 'west ncs-loot'
after that on the results of the update.

scripts: west ncs-loot: work with manifest-rev

---

doc/nrf/images/nrf_desktop_arch.svg
doc/nrf/images/nrf_desktop_arch_dmouse.svg
doc/nrf/images/nrf_desktop_arch_dongle.svg
doc/nrf/images/nrf_desktop_arch_gmouse.svg
doc/nrf/images/nrf_desktop_arch_kbd.svg

Change updates architecture images.

applications: nrf_desktop: Update architecture images

---

applications/nrf_desktop/doc/ble_adv.rst

Change adds ble_adv module documentation.

applications: nrf_desktop: Add BLE advertising documentation

---

cmake/partition_manager.cmake

Easier to maintain, and use, and you don't need different versions
of the macro when providing a different set of arguments.

cmake: use argument parsing for 'add_region'

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/led_stream.rst
applications/nrf_desktop/src/modules/Kconfig.led_stream

Change adds LED stream module documentation.

applications: nrf_desktop: Add led_stream documentation

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/main.rst
applications/nrf_desktop/doc/power_manager.rst
applications/nrf_desktop/doc/watchdog.rst

applications: nrf_desktop: Power Manager documentation

---

doc/nrf/templates/cheat_sheet.rst

Added steps about how to add snippets in .rst files.

doc: Update cheat sheet with code snippets

---

applications/nrf_desktop/doc/ble_discovery.rst
applications/nrf_desktop/src/modules/Kconfig.ble

Change adds ble_discovery module documentation.

applications: nrf_desktop: Add BLE discovery documentation

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/dfu.rst

applications: nrf_desktop: Add DFU module documentation

---

applications/nrf_desktop/doc/usb_state.rst
applications/nrf_desktop/src/modules/Kconfig.usb_state

applications: nrf_desktop: usb state module doc

---

applications/nrf_desktop/doc/ble_scan.rst

Change adds `ble_scan` module documentation.

applications: nrf_desktop: Add BLE scanning module documentation

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/ble_qos.rst

Change adds `ble_qos` module documentation.

applications: nrf_desktop: Add BLE QoS module documentation

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/ble_state.rst
applications/nrf_desktop/doc/led_state.rst

Change adds guide describing Bluetooth configuration.

applications: nrf_desktop: Add Bluetooth guide

---

applications/nrf_desktop/doc/hids.rst

Change adds HID Service documentation.

applications: nrf_desktop: Add HID Service documentation

---

samples/nrf9160/aws_fota/src/main.c

The output buffer was too small to contain the max length of the
response buffer for the AT Command.
NCSDK-4819

samples: aws_fota: Fix compile warning for truncated output

---

applications/nrf_desktop/doc/hid_state.rst

applications: nrf_desktop: Add hid_state documentation

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/dfu.rst
applications/nrf_desktop/doc/watchdog.rst

applications: nrf_desktop: Add DFU chapter to readme

---

west.yml

nrfxlib: bsdlib: bsdlib update version 0.7.0

---

applications/nrf_desktop/src/hw_interface/buttons.c

applications: nrf_desktop: Workaround for Zephyr ISR pins bug

---

samples/bluetooth/throughput/README.rst
samples/bluetooth/throughput/src/main.c

This commit provides rewriten throughput application to eaccept
s or m character input to start either master or slave role
Signed-off-by: Kamil Gawor <Kamil.Gawor@nordicsemi.no>

samples: throughput: Add role device role changes

---

applications/asset_tracker/Kconfig
applications/asset_tracker/README.rst
applications/asset_tracker/lwm2m_carrier_overlay.conf
applications/asset_tracker/src/main.c
drivers/gps/nrf9160_gps/Kconfig
include/modem/modem_info.h
lib/at_cmd/at_cmd.c
lib/lte_link_control/lte_lc.c
lib/modem_info/modem_info.c
lib/modem_info/modem_info_params.c
subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c

added support for lwm2m_carrier lib and device/cloud connections improvements.
TG91-178
Signed-off-by: Justin Morton justin.morton@nordicsemi.no

applications: asset_tracker: Add lwm2m_carrier lib support

---

doc/nrf/links.txt
include/net/nrf_cloud_agps.h
include/net/nrf_cloud_agps.rst
samples/nrf9160/nrf_cloud_agps/README.rst

Adds documentation for nRF Cloud A-GPS library and sample application.

nrf_cloud_agps: Add documentation

---

doc/CMakeLists.txt
doc/nrfxlib/conf.py
west.yml

Manifest PR for https://github.com/NordicPlayground/nrfxlib/pull/157

Ncsdk 3898 add links.txt to nrfxlib

---

Jenkinsfile

* better status reports - 2 reports are sent now: FULL_CI and repo-specific. 
* better workspace clean

ci: improve github statuses from jenkins

---

applications/nrf_desktop/src/modules/ble_state.c

applications: nrf_desktop: Add missing statics

---

cmake/multi_image.cmake
cmake/partition_manager.cmake
subsys/partition_manager/CMakeLists.txt

Support changing binary dir
Remove printing
Add domain of root image.

cmake: partition_manager: fix issues with domains

---

scripts/partition_manager.py

Generalize the concept. and add 'app' span over dynamic partition.

scripts: partition_manager: improve dynamic partition handling

---

scripts/hid_configurator/configurator_cli.py
scripts/hid_configurator/requirements.txt
scripts/hid_configurator/requirements_gui.txt
scripts/hid_configurator/requirements_music_led_stream.txt

scripts: hid_configurator: Requirements cleanup

---

applications/nrf_desktop/src/events/Kconfig
applications/nrf_desktop/src/events/ble_event.c
applications/nrf_desktop/src/events/ble_event.h
applications/nrf_desktop/src/modules/CMakeLists.txt
applications/nrf_desktop/src/modules/Kconfig.ble
applications/nrf_desktop/src/modules/ble_conn_params.c
applications/nrf_desktop/src/modules/ble_latency.c
applications/nrf_desktop/src/modules/ble_scan.c
applications/nrf_desktop/src/modules/ble_state.c
applications/nrf_desktop/src/modules/hid_forward.c

Change updates connection latency handling on nRF Desktop central.

applications: nrf_desktop: Update connection latency handling on central

---

scripts/hid_configurator/README.rst

scripts: hid_configurator: Documentation cleanup

---

cmake/extensions.cmake
cmake/mcuboot.cmake
subsys/bootloader/image/CMakeLists.txt

Leverage 'extensions.cmake' to share common functionality

cmake: extract common overlay file functionality to funtion

---

subsys/bluetooth/controller/hci_driver.c

Fix deadlock between the hci_core rx_thread and the hci_driver
rx_thread.
The hci_core rx_thread is during processing of the encryption change
event will send new HCI commands to the controller and waits on a
semaphore for the command complete event.
The hci_core tx_thread successfully sends this to the controller so
it is now up to the hci_driver rx_thread to fetch the command complete
event.
The hci_driver rx_thread is waiting for an available buffer for HCI
events after having used up all the HCI event buffers from the pool
and is now waiting for the hci_core rx_thread to free up buffers.
Handle this by marking advertising reports and the QoS conn event
reports as discardable events. In a combined build this make the
hci_driver retrieve the buffers for these events for a different HCI …

Bluetooth: hci_driver: Fix deadlock when system runs out of evt bufs

---

applications/nrf_desktop/README.rst
doc/nrf/gs_modifying.rst
doc/nrf/ug_app_dev.rst

Moved section to Modifying application. Reorganized nRF Desktop.

doc: move build type section from nRF Desktop

---

include/bluetooth/mesh/dk_prov.rst

Review documentation and formatting.

doc: Mesh DK prov handler review

---

lib/lte_link_control/lte_lc.c

AT+CSCON was introduced in nRF9160 modem firmware version v1.1.0.
Earlier versions will return ERROR when the command is received,
which would cause w_lte_lc_init() return with an error code.
Failed AT+CSCON will result in RRC mode change notifications
not being received. The only effect for the link controller users
is that they will not receive RRC events, which they would anyway not
expect due to the too-old modem firmware for this functionality.
If application FOTA is performed on a device with a modem
older than v1.1.0, calls to lte_lc_init() and
lte_lc_init_and_connect() would fail without this patch,
resulting in a device without LTE connection and likely no way to recover
the error with FOTA.
Because of this, failed AT+CSCON should not return an error code,
and this patch removes …

lib: lte_lc: Do not return error if AT+CSCON fails

---

west.yml

nrfxlib: bsdlib: bsdlib update version 0.7.1

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/hids.rst
applications/nrf_desktop/doc/passkey.rst
applications/nrf_desktop/doc/settings_loader.rst

Change updates board names to match the new board naming convention.

applications: nrf_desktop: Update board names

---

west.yml

Introduce post upmerge_w17_2020 bugfix
https://github.com/NordicPlayground/fw-nrfconnect-zephyr/pull/300

manifest: upgrade zephyr revision

---

cmake/partition_manager.cmake

If a subsys is requiring a partition through its pm.yml we need
to execetue the partition manager.
NCSDK-5160

partition_manager: run partition manager for subsys partitions

---

doc/nrf/links.txt
samples/bluetooth/mesh/light/README.rst
samples/bluetooth/mesh/light_switch/README.rst

Review and align documentation.

doc: review mesh light samples

---

applications/nrf_desktop/src/modules/hid_forward.c

Change fixes handling HID subscription in hid_forward module.

applications: nrf_desktop: Fix handling HID subscription

---

west.yml

Ref: DESK-939
mcuboot PR: https://github.com/NordicPlayground/fw-nrfconnect-mcuboot/pull/96

west.yml: Update west.yml for mcuboot serial recovery fix

---

scripts/profiler/merge_data.py

Change improves clock synchronization for the connected devices.

scripts: profiler: Improve merging data from two devices

---

lib/bsdlib/bsdlib.c
west.yml

Added trace and memory parameters.
Signed-off-by: Tommi Mammela <tommi.mammela@nordicsemi.no>

lib: bsdlib: Updated bsd_init() to use new bsdlib version

---

README.rst
doc/mcuboot/readme-ncs.rst
doc/mcuboot/wrapper.rst
doc/nrf/gs_installing.rst
doc/nrf/links.txt
doc/nrf/release_notes.rst
doc/nrf/ug_dev_model.rst
doc/nrf/ug_thingy91.rst
doc/release-notes-0.1.0.rst
doc/release-notes-0.3.0.rst
doc/release-notes-0.4.0.rst
doc/release-notes-1.1.0.rst
doc/release-notes-1.2.0.rst

Document the repository move

---

doc/nrf/links.txt
doc/nrf/ug_thread.rst

Expanded Thread user guide with tools section.

doc: Add Thread tools section

---

west.yml

Adding GNSS conceptual documentation, manifest update

bsdlib: doc: Adding GNSS conceptual documentation

---

include/nfc/ndef/le_oob_rec.h
samples/nfc/tnep_tag/src/main.c
subsys/nfc/tnep/tag.c

- Allows creation of the static or global OOB records
- Change order in the TNEP Initial Message
- Remove trash from sample testing

NFC TNEP OOB arrangements

---

doc/nrf/doc_build.rst

Minor doc fixes in doc_build.rst file

doc: Minor doc fixes in doc_build.rst file

---

samples/nrf9160/lwm2m_client/README.rst
samples/nrf9160/lwm2m_client/overlay-queue.conf
samples/nrf9160/lwm2m_client/src/config.h
samples/nrf9160/lwm2m_client/src/main.c

This feature is now available in NCS after the recent upmerge.

samples: lwm2m_client: Add overlay to enable queue mode

---

samples/zigbee/light_bulb/sample.yaml
samples/zigbee/light_switch/sample.yaml
samples/zigbee/network_coordinator/sample.yaml
subsys/zigbee/Kconfig
tests/subsys/zigbee/osif/crypto/testcase.yaml
tests/subsys/zigbee/osif/logger/testcase.yaml
tests/subsys/zigbee/osif/nvram/testcase.yaml
tests/subsys/zigbee/osif/timer/testcase.yaml
tests/subsys/zigbee/zboss_api/callback_api/testcase.yaml

Add nrf52833dk_nrf52833 support in Zigbee samples and tests.
This PR depends on:
#2317

samples: zigbee: Add nrf52833dk_nrf52833 support

---

doc/nrf/links.txt
doc/nrf/ug_bt_mesh.rst
doc/nrf/user_guides.rst

Adds basic user guide for Bluetooth Mesh.

Bluetooth: Mesh: User guide

---

doc/nrf/images/nrf_desktop_arch.svg
doc/nrf/images/nrf_desktop_arch_dmouse.svg
doc/nrf/images/nrf_desktop_arch_dongle.svg
doc/nrf/images/nrf_desktop_arch_gmouse.svg
doc/nrf/images/nrf_desktop_arch_kbd.svg

Change updates application architecture schematics.

applications: nrf_desktop: Update schematics

---

doc/nrf/gs_installing.rst
doc/nrf/ug_dev_model.rst

Document the format of development tags in the Development Model user
guide.

doc: Document dev tags

---

doc/nrf/links.txt
doc/nrf/ug_thread.rst
doc/nrf/ug_zigbee.rst
samples/zigbee/light_bulb/README.rst
samples/zigbee/light_switch/README.rst
samples/zigbee/network_coordinator/README.rst

Fixes for T/Z user guide and samples. Added sniffer tool.

doc: add Zigbee tools

---

subsys/net/lib/nrf_cloud/src/nrf_cloud.c

When backend polling is enabled, a disconnect event could be sent
twice to the application; once from the transport layer callback
and once from the socket polling thread.
TG91-264

net: lib: nrf_cloud: Only send disconnect event once

---

applications/asset_tracker/src/main.c

Adds a workaround for corner-case where the A-GPS request would
never be sent if the A-GPS work was submitted immediately.
The solution is to add a delay of 1 seconds before sending
the request.
The PR is rebased on top of upmerge #2284.

application: asset_tracker: Send A-GPS request with small delay

---

doc/nrf/ug_zigbee.rst
samples/zigbee/light_switch/README.rst
samples/zigbee/light_switch/src/main.c
subsys/zigbee/common/zigbee_helpers.c
subsys/zigbee/common/zigbee_helpers.h

- Enable sleepy behavior at end device sample
- Implement unused RAM powering down for Zigbee samples

samples: zigbee: Enable sleepy behavior at Light Switch sample

---

applications/nrf_desktop/sample.yaml

applications: nrf_desktop: CI build 52820 & 52833 dongles

---

applications/nrf_desktop/README.rst

applications: nrf_desktop: Adding a new sensor

---

doc/nrf/links.txt
lib/bin/lwm2m_carrier/lwm2m_carrier.rst
samples/nrf9160/lwm2m_carrier/README.rst

Added more information about what the carrier library is,
and how to integrate it into applications.
Signed-off-by: Vermeer <havard.vermeer@nordicsemi.no>

Documentation: lwm2m carrier library documentation

---

include/event_manager.rst

Change updates documentation for the Event Manager subsystem.

subsys: event_manager: Update documentation

---

applications/nrf_desktop/README.rst

applications: nrf_desktop: Hint how to change irq priority

---

applications/nrf_desktop/src/modules/hids.c

applications: nrf_desktop: Suppress error when disconnected

---

samples/profiler/README.rst

Change updates profiler sample documentation.

samples: profiler: Update documentation

---

applications/nrf_desktop/configuration/nrf52820dongle_nrf52820/pm_static_ZReleaseMCUBoot.yml

applications: nrf_desktop: Fix 52820 dongle flash layout

---

doc/nrf/ug_zigbee.rst
samples/zigbee/light_bulb/README.rst
samples/zigbee/light_switch/README.rst
samples/zigbee/network_coordinator/README.rst
west.yml

Manifest update for nrfxlib PR #191.

doc: manifest update for zboss doc landing page

---

doc/CMakeLists.txt
doc/nrf/examples.rst
doc/nrf/includes/build_and_run_test.txt
doc/nrf/links.txt
doc/nrf/tests.rst
tests/crypto/README.rst
west.yml

doc: crypto test doc

---

samples/nrf9160/cloud_client/README.rst

samples: cloud_client: Add testing description to documentation

---

west.yml

Introduce bugfix for UART.
NCSDK-5581

west.yml: Update sdk-zephyr reference

---

samples/bluetooth/mesh/light/README.rst
samples/bluetooth/mesh/light_switch/README.rst
samples/bluetooth/throughput/README.rst

Reviewed lines added in PR#2396.

doc: Mesh samples compatibility note review

---

README.rst
doc/nrf/index.rst

Update the note on which devices and protocols are (not) supported
for development and production.
https://projecttools.nordicsemi.no/jira/browse/NCSDK-5619
Output:

doc: update note about what is supported

---

samples/nrf9160/aws_fota/src/main.c

Fixes so that the `aws_fota` sample does not tries to go online even
if it never went offline.

nrf9160: aws_fota: Fix going online only if it has gone offline

---

doc/nrf/examples.rst
doc/nrf/gs_installing.rst
doc/nrf/links.txt
doc/nrf/release_notes.rst
doc/nrf/ug_dev_model.rst
doc/nrf/ug_nrf52.rst

Doc fixes as discussed in the doc review meeting.

Doc fixes v1.3.0

---

west.yml

Pull in some BT fromtree bug fix patches (https://github.com/nrfconnect/sdk-zephyr/pull/315)

west.yml: update zephyr [DESK-954]

---

doc/nrf/links.txt
doc/nrf/ug_thread.rst
doc/nrf/ug_zigbee.rst

Add links to new RD docs in nrfxlib and Infocenter.
Reworks updates from PR#2299 (KRKNWK-5824) due to TECHDOC-1544.

docs: link radio driver docs

---

samples/nrf9160/cloud_client/README.rst

[Jira 5583](https://projecttools.nordicsemi.no/jira/browse/NCSDK-5583)
Corrects the path to prj.conf for location of configuration options.
Signed-off-by: Richard McCrae <richard.mccrae@nordicsemi.no>

samples: nrf9160: Cloud Client README correction

---

west.yml

Pull in some new documentation PRs.

west.yml: update nrfxlib

---

doc/nrf/gs_installing.rst

Minor doc fix in gs_installing.rst

doc: Minor doc fix in gs_installing.rst

---

west.yml

Fixes documentation build on master

doc: update west.yml to latest nrfxlib

---

scripts/hid_configurator/modules/music_led_stream.py

Change fixes synchronization problem for music LED stream in case predicted number of samples in speaker's buffer is negative. Change also updates duration increment factors.

scripts: hid_configurator: Fix music LED stream

---

doc/nrf/gs_installing.rst

doc: update gnu arm embedded toolchain version

---

dts/bindings/net/nfc/st,st25r3911b.yaml
lib/st25r3911b/st25r3911b_common.c
lib/st25r3911b/st25r3911b_common.h
samples/nfc/tag_reader/nrf52840dk_nrf52840.overlay
samples/nfc/tag_reader/nrf52dk_nrf52832.overlay
samples/nfc/tag_reader/nrf5340pdk_nrf5340_cpuapp.overlay
samples/nfc/tnep_poller/nrf52840dk_nrf52840.overlay
samples/nfc/tnep_poller/nrf52dk_nrf52832.overlay
samples/nfc/tnep_poller/nrf5340pdk_nrf5340_cpuapp.overlay

This PR contains:
- Fix st25r3911b irq pin for nrf5340 dk
- Loading LED data from DTS

NFC Poller samples pin fix

---

samples/bluetooth/central_hids/README.rst

ref: https://projecttools.nordicsemi.no/jira/browse/NCSDK-5742
Doc update of Bluetooth central HIDS sample rst

doc: Doc update of Bluetooth central HIDS sample rst

---

doc/nrf/examples.rst
doc/nrf/introduction.rst
doc/nrf/links.txt
doc/nrf/mcuboot.rst
doc/nrf/ug_ble_controller.rst
doc/nrf/ug_dev_model.rst
doc/nrf/ug_nrf52.rst
doc/nrf/zephyr.rst

Clarify the text in "About the nRF Connect SDK".
Output:

doc: update "About the nRF Connect SDK"

---

applications/nrf_desktop/src/modules/ble_adv.c
applications/nrf_desktop/src/modules/ble_bond.c

Change fixes peer disconnection in ble_adv module. With previous implementation a central that was connected, but not yet bonded was not properly disconnected.

applications: nrf_desktop: Fix peer disconnection

---

samples/nrf9160/http_application_update/prj.conf

Changed location of which file to be downloaded so that it downloads a
file which is compatible with the 1.2-branch version.

nrf9160: http_application_update: Change download file target

---

applications/nrf_desktop/src/modules/hid_state.c

applications: nrf_desktop: Limit reports sent to subscriber

---

applications/nrf_desktop/src/hw_interface/motion_sensor.c
applications/nrf_desktop/src/modules/hid_state.c
applications/nrf_desktop/src/modules/usb_state.c

Change fixes problems with boot reports.

applications: nrf_desktop: Boot reports fix

---

applications/nrf_desktop/src/modules/dfu.c
scripts/hid_configurator/NrfHidDevice.py
scripts/hid_configurator/configurator_cli.py
scripts/hid_configurator/gui/gui.kv
scripts/hid_configurator/gui/gui.py
scripts/hid_configurator/gui/gui_backend.py
scripts/hid_configurator/modules/dfu.py
scripts/hid_configurator/requirements.txt

Change adds support for both bootloaders (B0 and MCUBoot) in nrf_desktop application and in hid_configurator scripts.

applications: nrf_desktop: Add MCUBoot support

---

lib/bsdlib/nrf91_sockets.c
west.yml

Add MSG_TRUNC flag and SO_SNDTIMEO socket option support
in nRF91 offloading.
Signed-off-by: Tommi Mammela <tommi.mammela@nordicsemi.no>

lib: bsdlib: Update nRF91 offloading support

---

samples/openthread/cli/README.rst
samples/openthread/coap_client/README.rst
samples/openthread/coap_server/README.rst

ref https://github.com/nrfconnect/sdk-nrf/pull/2425 and
NCSDK-3933
Fixed board names in Thread samples

doc: Fixed board names in Thread samples

---

doc/nrf/index.rst
doc/nrf/links.txt
doc/nrf/release_notes.rst
doc/release-notes-1.2.1.rst

Add release notes for v1.2.1 and link to the documentation.

doc: add release notes for v1.2.1

---

subsys/net/lib/nrf_cloud/src/nrf_cloud_codec.c

Improve log messages when unhandled shadow data is received.
TG91-273

net: lib: nrf_cloud: log msg update for shadow delta error

---

samples/zigbee/light_switch/src/main.c

Use Zephyr timer alarms in light switch sample.
This PR depends on: #2416

samples: zigbee: use Zephyr alarms in light switch sample

---

west.yml

It also enables controller to host flow control.

manifest: BLE controller connection event length is configurable

---

applications/nrf_desktop/configuration/common/hid_report_keyboard.h
applications/nrf_desktop/configuration/common/hid_report_user_config.h

applications: nrf_desktop: Fix non-compliant report data

---

samples/nrf9160/lwm2m_client/src/lwm2m/lwm2m_firmware.c

In case PULL FW update mode is used, the server does not report the total image size, therefore it's not possible to calculate the percentage download progress. Report byte progress in this case instead.
Additionaly, delay the system reboot when Update command is executed, to allow the engine to send an ACK reply.

samples: lwm2m_client: Fix PULL FW update progress

---

west.yml

* Updated support for bsd_shutdown() and multiple bsd_init().

lib: bsdlib: update for bsdlib 0.7.5

---

applications/nrf_desktop/src/modules/ble_qos.c

Change updates usage of deprecated DT macro in ble_qos module.

applications: nrf_desktop: Fix DT macro in ble_qos

---

applications/nrf_desktop/src/modules/ble_conn_params.c

Change switches to updating connection parameters only after the peripheral discovery is completed. This prevents race condition that results in setting connection interval from 10 ms to 7.5 ms. Then update from 7.5 ms to 1 ms causes Link Layer scheduling conflicts and report rate drops.

applications: nrf_desktop: Fix race condition for conn params update

---

applications/nrf_desktop/src/modules/usb_state.c

applications: nrf_desktop: Ignore USB_DC_INTERFACE event

---

applications/nrf_desktop/README.rst

applications: nrf_desktop: Add known issues section

---

doc/nrf/ug_zigbee.rst

Removed one invalid line after KRKNWK-6389 ZBOSS dev guide review.

docs: update Zigbee ug power saving section

---

subsys/bluetooth/services/hids.c

Change fixes permissions for Control Point characteristic.

bluetooth: hids: Fix permissions for Control Point

---

doc/nrf/links.txt
doc/nrf/ug_zigbee_configuring.rst

Made edits to ZBOSS stack start information (KRKNWK-6383).

docs: update zigbee stack start section

---

applications/nrf_desktop/src/modules/Kconfig.ble
applications/nrf_desktop/src/modules/ble_scan.c

Change adds support for more than one device of given kind.

applications: nrf_desktop: Support more than one device of a kind

---

applications/nrf_desktop/src/events/Kconfig
applications/nrf_desktop/src/events/ble_event.c
applications/nrf_desktop/src/events/ble_event.h
applications/nrf_desktop/src/modules/Kconfig.ble
applications/nrf_desktop/src/modules/ble_qos.c
applications/nrf_desktop/src/util/chmap_filter/include/chmap_filter.h

applications: nrf_desktop: QoS on peripheral

---

include/net/cloud.h
include/net/cloud.rst
include/net/nrf_cloud.rst

Added the sections 'Using nRF Cloud with Cloud API' to
nRF Cloud library Readme with details of typical events
and error codes.Also added the error descriptions to
Cloud API.

doc: Added sections to nRF cloud library documentation

---

west.yml

Includes:
- Known issues
- Some more HCI commands to control and read TX power

manifest: Update nrfxlib with new MPSL and BLE controller

---

samples/nrf9160/nrf_cloud_agps/README.rst

Added sample output to the documentation
[nRF9160_ nRF Cloud A-GPS — nRF Connect SDK 1.3.99 documentation.pdf](https://github.com/nrfconnect/sdk-nrf/files/4919192/nRF9160_.nRF.Cloud.A-GPS.nRF.Connect.SDK.1.3.99.documentation.pdf)

doc: Doc enhancement of nRF Cloud A-GPS sample README

---

cmake/mcuboot.cmake
scripts/bootloader/zb_add_ota_header.py
subsys/zigbee/Kconfig

Add generating Zigbee OTA package
Signed-off-by: Mariusz Poslinski <mariusz.poslinski@nordicsemi.no>

mcuboot: Add generating Zigbee OTA package

---

samples/bluetooth/mesh/light_ctrl/README.rst

Fix error in the documentation of the sample
Signed-off-by: Anders Storrø <anders.storro@nordicsemi.no>

Bluetooth: Mesh: Light controller example doc fix

---

samples/openthread/coap_client/README.rst

Link to the right page which describes how to provide CMake options
if you work with SES or on the command line.

samples: openthread: doc: Adjust with SES support

---

doc/nrf/links.txt
doc/nrf/ug_nrf9160.rst

ref: NCSDK-5969
Added information about different modem FW versions
and linked to compatibility matrix.

doc: Doc update for Working with nRF9160 user guide

---

lib/at_cmd/at_cmd.c

Matching `OK` with `strstr()` won't work in case we are reading out
a certificate for example, where the occurence of `OK` can be quite
common; in that case the response would be incorrectly terminated
making it impossible to obtain the whole payload.
Only match `OK` or `ERROR` in the response if they are at the end.

lib: at_cmd: match `OK` or `ERROR` only at the end of the response

---

doc/CMakeLists.txt
doc/nrf/doc_build.rst
doc/nrfxlib/conf.py
scripts/sphinx_extensions/inventory_builder/__init__.py
west.yml

Add nrf objects.inv to nrfxlib intersphinx mapping to allow automatic link resolution.
JIRA: NCSDK-3934

doc: allow nrfxlib to link to nrf with intersphinx

---

doc/static/js/ncs.js

* Fix an issue where navigating through http was causing a CORS error doing the AJAX request for versions.json
* Fix issue using hardcoded path indexes on variable length path prefixes.

doc: fix version switcher issues

---

west.yml

Include OT commits needed for NCP sample.

west.yml: Update sdk-zephyr revision

---

samples/esb/prx/Kconfig
samples/esb/prx/prj.conf
samples/esb/prx/src/main.c
samples/esb/ptx/Kconfig
samples/esb/ptx/prj.conf
samples/esb/ptx/src/main.c

Fixed logging configuration for ESB samples.
Signed-off-by: Kamil Piszczek <Kamil.Piszczek@nordicsemi.no>

samples: esb: fix logging configuration

---

doc/nrf/links.txt
doc/nrf/ug_thread.rst
doc/nrf/ug_thread_vendor_hooks.rst
samples/openthread/ncp/CMakeLists.txt
samples/openthread/ncp/README.rst
samples/openthread/ncp/overlay-vendor_hook.conf
samples/openthread/ncp/src/nrf_802154_radio_wrapper.c
samples/openthread/ncp/src/nrf_802154_radio_wrapper.h
samples/openthread/ncp/src/user_vendor_hook.cpp

Extension of NCP sample by vendor hooks exemplary implementation.

samples: ncp: Added vendor hooks for NCP sample

---

doc/nrf/releases/release-notes-latest.rst

Filtered out only relevant ones for us.

doc: release-notes-latest: Summarize networking changes from the upmerge

---

west.yml

west: update nrfxlib

---

applications/nrf_desktop/configuration/nrf52810dmouse_nrf52810/hid_keymap_def.h
applications/nrf_desktop/configuration/nrf52840dk_nrf52840/hid_keymap_def.h
applications/nrf_desktop/configuration/nrf52840gmouse_nrf52840/hid_keymap_def.h
applications/nrf_desktop/configuration/nrf52dmouse_nrf52832/hid_keymap_def.h
applications/nrf_desktop/configuration/nrf52kbd_nrf52832/hid_keymap_def.h

Change updates link to HID Usage Tables.

applications: nrf_desktop: Update link to HID Usage Tables

---

scripts/partition_manager/partition_manager.rst

Will be rebased to only last commit when https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/2274 is merged.

Pm subsys doc

---

applications/nrf_desktop/configuration/common/dev_descr.h
applications/nrf_desktop/src/events/ble_event.h
applications/nrf_desktop/src/modules/ble_discovery.c
applications/nrf_desktop/src/modules/dev_descr.c
applications/nrf_desktop/src/modules/hid_forward.c
applications/nrf_desktop/src/modules/info.c
applications/nrf_desktop/src/util/CMakeLists.txt
applications/nrf_desktop/src/util/hwid.c
applications/nrf_desktop/src/util/hwid.h

applications: nrf_desktop: Add HW ID discovery

---

include/bluetooth/mesh/models.h
include/bluetooth/mesh/time.h
include/bluetooth/mesh/time_cli.h
include/bluetooth/mesh/time_srv.h
subsys/bluetooth/mesh/CMakeLists.txt
subsys/bluetooth/mesh/Kconfig.models
subsys/bluetooth/mesh/time.c
subsys/bluetooth/mesh/time_cli.c
subsys/bluetooth/mesh/time_internal.h
subsys/bluetooth/mesh/time_srv.c
subsys/bluetooth/mesh/time_util.c
subsys/bluetooth/mesh/time_util.h

Adds the Bluetooth Mesh Time models to the mesh framework.
Signed-off-by: Anders Storrø anders.storro@nordicsemi.no

Bluetooth Mesh Time models.

---

doc/nrf/ug_zigbee_configuring.rst
subsys/zigbee/CMakeLists.txt
subsys/zigbee/Kconfig
subsys/zigbee/cli/zigbee_cli.c
subsys/zigbee/cli/zigbee_cli.h
subsys/zigbee/cli/zigbee_cli_cmd.c
subsys/zigbee/cli/zigbee_cli_cmd_bdb.c
subsys/zigbee/cli/zigbee_cli_cmd_zscheduler.c
subsys/zigbee/cli/zigbee_cli_utils.c
subsys/zigbee/cli/zigbee_cli_utils.h
subsys/zigbee/common/zigbee_helpers.c
subsys/zigbee/common/zigbee_logger_eprxzcl.c
subsys/zigbee/osif/zb_nrf_platform.c
subsys/zigbee/osif/zb_nrf_platform.h

CLI component ported from SDK for T&Z.

subsys/zigbee: Port CLI component (KRKNWK-5086)

---

applications/nrf_desktop/src/events/config_event.h
scripts/hid_configurator/NrfHidDevice.py

Change switches to using section to index config channel modules.

applications: nrf_desktop: New config channel module indexing

---

include/spm.rst
samples/nfc/record_text/CMakeLists.txt
samples/nfc/record_text/sample.yaml
samples/nfc/writable_ndef_msg/CMakeLists.txt
samples/nfc/writable_ndef_msg/sample.yaml
samples/nfc/writable_ndef_msg/src/ndef_file_m.c
subsys/nfc/lib/platform.c
subsys/spm/Kconfig
subsys/spm/spm.c
west.yml

Related PR: https://github.com/nrfconnect/sdk-nrfxlib/pull/193

NFC Non-Secure image support

---

doc/nrf/releases/release-notes-latest.rst

Selected important changes in drivers directly related to nRF hardware
or seeming to have potential influence on NCS users.

doc: release-notes-latest: List changes in drivers from last upmerge

---

scripts/hid_configurator/NrfHidDevice.py

Change separates transport layer for hid_configurator.

scripts: hid_configurator: Separate transport

---

applications/nrf_desktop/src/modules/power_manager.c

applications: nrf_desktop: USB standby only if wake up supported

---

cmake/mcuboot.cmake
samples/zigbee/light_switch/ota_overlay.conf
samples/zigbee/light_switch/src/main.c
samples/zigbee/network_coordinator/src/main.c
scripts/bootloader/zb_add_ota_header.py
subsys/partition_manager/Kconfig
subsys/zigbee/CMakeLists.txt
subsys/zigbee/Kconfig
subsys/zigbee/common/zigbee_ota.h
subsys/zigbee/common/zigbee_ota_client.c
subsys/zigbee/common/zigbee_ota_client.h

Extend light switch example with support for OTA DFU.
Signed-off-by: Mariusz Poslinski mariusz.poslinski@nordicsemi.no

samples: zigbee: Extend light switch example with support for OTA DFU.

---

applications/nrf_desktop/src/modules/hid_forward.c

applications: nrf_desktop: Fix state handling when USB connects

---

doc/nrf/links.txt
doc/nrf/ug_thread.rst
doc/nrf/ug_thread_tools.rst
samples/openthread/ncp/README.rst

Added a new page for Thread tools with sections about wpantund.
(KRKNWK-6807)

doc: expand wpantund documentation for Thread

---

applications/nrf_desktop/src/modules/hid_forward.c

Subscriber could mean either the peripheral connected to central
or usb_state module connecting to report.
To avoid confusion avoid using the name for peripherals.
Jira:DESK-1022

applications: nrf_desktop: Clean up naming in hid_forward

---

applications/nrf_desktop/src/modules/hid_forward.c

Unify variable names across functions.
Jira:DESK-1022

applications: nrf_desktop: hid_forward variable cleanup

---

applications/nrf_desktop/src/modules/ble_adv.c

applications: nrf_desktop: Don't advertise when BLE not ready

---

applications/nrf_desktop/src/modules/hid_forward.c

Each peripheral device gets its own queue of pending reports.
Code is prepared for routing to multiple USB devices.
Jira:DESK-1022

applications: nrf_desktop: Rework report routing in hid_forward

---

subsys/zigbee/common/zigbee_ota_client.c

Due to the bug inside ZBOSS libraries (ZOI-113), the pointer to the firmware chunk is shifted.
This workaround parses the ZCL frame once more inside the application to get the correct pointer values.
Signed-off-by; Tomasz Chyrowicz <tomasz.chyrowicz@nordicsemi.no>

zigbee: Introduce a workaround for ZOI-113

---

doc/nrf/shortcuts.txt
doc/nrf/templates/sample_README.rst

Update the sample template to make it easier to use, and to
account for the requirements of all samples that we currently
have.
PDF printout: 
[Template_ Sample — nRF Connect SDK 1.3.pdf](https://github.com/nrfconnect/sdk-nrf/files/4970726/Template_.Sample.nRF.Connect.SDK.1.3.pdf)

doc: update the sample template

---

scripts/partition_manager.py

This is done to support configurations where two or more partitions
share the same placement property.
NCSDK-5983

partition_manager: resolve ambiguous partition configurations

---

scripts/partition_manager/partition_manager.rst
subsys/partition_manager/Kconfig

This is not described and it is not clear when to set it.

docs: add documentation on PM_SINGLE_IMAGE config

---

applications/nrf_desktop/src/modules/power_manager.c

applications: nrf_desktop: Delay power down after USB suspend

---

include/nfc/tnep/tag.h
include/nfc/tnep/tag.rst
samples/nfc/tnep_poller/nrf52840dk_nrf52840.overlay
samples/nfc/tnep_poller/nrf52dk_nrf52832.overlay
samples/nfc/tnep_poller/nrf5340pdk_nrf5340_cpuapp.overlay
samples/nfc/tnep_tag/src/main.c
subsys/nfc/tnep/CMakeLists.txt
subsys/nfc/tnep/tag.c
subsys/nfc/tnep/tag.ld

This PR provides improvements for the NFC TNEP library which ensures allows to define NDEF records locally inside
callback function.

NFC TNEP improvements

---

applications/asset_tracker/src/cloud_codec/cloud_codec.c

Initialize cloud_channel_data structs before use.
Jira:CIA-49

applications: asset_tracker: cloud_codec: Initialize struct

---

applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/app_ZDebug3BLEconn.conf
applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/app_ZRelease4LLPMconn.conf

This is follow up of 781d4814ac91b529bf5cef80e150baa87c8d5c2a

applications: nrf_desktop: Rename missed config option

---

applications/nrf_desktop/src/modules/hid_forward.c

applications: nrf_desktop: Fix invalid reference to sub

---

scripts/hid_configurator/NrfHidDevice.py

scripts: hid_configurator: Don't fail when probing unknown devs

---

applications/connectivity_bridge/src/modules/uart_handler.c

Automatically re-enable UART RX upon errors.
Useful when for example UART peer resets
and leaves the pin floating temporarily.
Signed-off-by: Audun Korneliussen <audun.korneliussen@nordicsemi.no>

applications: connectivity_bridge: Improve UART RX error handling

---

applications/asset_tracker/src/main.c
lib/lte_link_control/lte_lc.c

Added handling of no sim card inserted in asset tracker and link controller.

applications: asset_tracker: add handling of no sim card inserted

---

cmake/partition_manager.cmake

When no domain was set, the files would get an excess '_' in their name.
Ref: NCSDK-6147

cmake: fix excess '_' in partition manager output files

---

applications/nrf_desktop/src/modules/Kconfig.hid_forward
applications/nrf_desktop/src/modules/hid_forward.c
applications/nrf_desktop/src/modules/usb_state.c

applications: nrf_desktop: Report queue per report type

---

Jenkinsfile

Having an agent set for Jenkins pipeline needlessly allocates a node
and increases pressue on the CI system.
REF: NCSDK-6096
Signed-off-by: Ievgenii Meshcheriakov <ievgenii.meshcheriakov@nordicsemi.no>

ci: Don't use agent for Jenkins pipeline

---

samples/openthread/coap_client/README.rst

Changed SED to MED in Thread CoAP client sample docs.
KRKNWK-7186

docs: update Thread CoAP client MED/SED info

---

applications/asset_tracker/src/main.c

The LOG message printing time to next GPS search start did
not reflect the correct time.

applications: asset_tracker: Use correct time in GPS LOG message

---

subsys/net/lib/download_client/src/coap.c

Extract the resource path from `client->file` when using CoAP, as it may contain the whole URL.

net: lib: download_client: extract file path when using CoAP

---

applications/nrf_desktop/src/events/config_event.h
applications/nrf_desktop/src/modules/hid_forward.c
scripts/hid_configurator/NrfHidDevice.py

Change adds forwarding information about peripherals connected via dongle.

applications: nrf_desktop: Config channel - connected peripherals

---

doc/nrf/ug_multiprotocol_support.rst
doc/nrf/user_guides.rst

Added document that describes how to enable multiprotocol support.
KRKNWK-6820

doc: add thread and zigbee multiprotocol guide

---

.github/workflows/labeler.yml

github: Fix labeler action

---

applications/nrf_desktop/src/modules/ble_adv.c
applications/nrf_desktop/src/modules/ble_bond.c

applications: nrf_desktop: Handle standby in ble_bond

---

subsys/zigbee/CMakeLists.txt
subsys/zigbee/Kconfig
subsys/zigbee/cli/zigbee_cli.h
subsys/zigbee/cli/zigbee_cli_cmd.c
subsys/zigbee/cli/zigbee_cli_cmd_bdb.c
subsys/zigbee/cli/zigbee_cli_cmd_zdo.c
subsys/zigbee/cli/zigbee_cli_cmd_zscheduler.c
subsys/zigbee/cli/zigbee_cli_ctx_mgr.c
subsys/zigbee/cli/zigbee_cli_ctx_mgr.h
subsys/zigbee/cli/zigbee_cli_utils.h
subsys/zigbee/cli/zigbee_cli_zdo_types.h

Introduce common context manager for Zigbee Shell commands and refactor ZDO commands to use it

Introduce common ctx manager for Zigbee Shell commands [KRKNWK-2144]

---

west.yml

Adds some required HCI APIs.
See CHANGELOG for details.

manifest: nrfxlib: NCS 1.3.1, Update to HCI conformant controller

---

applications/nrf_desktop/src/events/config_event.h
applications/nrf_desktop/src/modules/hid_forward.c
applications/nrf_desktop/src/util/config_channel_transport.c
scripts/hid_configurator/NrfHidDevice.py

Avoid using "error" with situations that happen due to normal
operation.
Jira:DESK-1066

applications: nrf_desktop: Rename config status disconnected

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/ble_qos.rst
applications/nrf_desktop/doc/qos.rst

applications: nrf_desktop: QoS module documentation

---

samples/openthread/cli/README.rst

Added a note in CLI sample about when to use diag commands.
KRKNWK-6670

doc: thread: add diag module info to cli sample

---

applications/nrf_desktop/src/modules/smp.c

Change fixes include in SMP application module.

applications: nrf_desktop: Fix include in SMP module

---

drivers/gps/nrf9160_gps/nrf9160_gps.c

Retry and interval timers was previously masked by delayed
works in the nrf9160 gps driver. This functionality is now
handled properly in the modem, and should be removed
from the driver.

drivers: gps: nrf9160_gps: Rework GPS timeout works

---

include/net/coap_utils.h

net: lib: coap_utils: Fix coap_send_request() description

---

applications/nrf_desktop/src/events/config_event.h
applications/nrf_desktop/src/hw_interface/motion_sensor.c
applications/nrf_desktop/src/modules/ble_qos.c
scripts/hid_configurator/NrfHidDevice.py
scripts/hid_configurator/NrfHidManager.py
scripts/hid_configurator/configurator_cli.py
scripts/hid_configurator/modules/config.py
scripts/hid_configurator/modules/led_stream.py
scripts/hid_configurator/modules/module_config.py
scripts/hid_configurator/modules/music_led_stream.py

Change updates configuration channel CLI.

applications: nrf_desktop: Update configuration channel CLI

---

include/bluetooth/scan.rst

Reviewed scan.rst draft created by Kamil Gawor in Jira task NCSDK-497.

docs: services: scanning module review

---

west.yml

-Includes refactoring of nrf_security: kconfig and cmake
-Includes bugfix for RSA in CC310
Ref: NCSDK-6047
Ref: NCSDK-6056

manifest: Update to nrflixb PR 240

---

doc/nrf/links.txt
doc/nrf/release_notes.rst
doc/release-notes-1.3.1.rst

doc: Release notes for NCS 1.3.1

---

west.yml

See https://github.com/nrfconnect/sdk-nrfxlib/pull/262

manifest: nrfxlib: SoftDevice Controller exposes APIs for commands

---

doc/nrf/ug_nrf9160.rst

Reviewed text. Fixed line breaks. Updated band lock chapter.

docs: updated JIRA NCSDK-6229_Bandlock_update

---

west.yml

Reverts nrfconnect/sdk-nrf#2913

Revert "manifest: Update Zephyr revision to include timer fix"

---

applications/nrf_desktop/src/modules/Kconfig.config_channel
applications/nrf_desktop/src/modules/dfu.c
applications/nrf_desktop/src/modules/hid_forward.c
applications/nrf_desktop/src/util/config_channel_transport.c
scripts/hid_configurator/modules/dfu.py

Do not write data on BLE transmission as this can fail. Instead write on sync operation and make host wait until all data has been written. Also wait for slot to become clean.
Jira:DESK-1069

applications: nrf_desktop: Improve DFU protocol

---

drivers/entropy/entropy_cc310.c

`spm_request_random_number()` requires that the application requests
exactly 144 random bytes, no different. As it's called directly in the
cc310 entropy driver, this is an unacceptable limitation, as the
`entropy_get_entropy()` function is used in various different
libraries, not aware of this shortcoming.
This commit works around this limitation in the
`entropy_cc310_rng_get_entropy` implementation.

drivers: entropy: cc310: Workaround for spm secure services limitation

---

doc/nrf/gs_testing.rst
doc/nrf/links.txt
doc/nrf/ug_logging.rst
doc/nrf/ug_thread_configuring.rst
doc/nrf/ug_zigbee_configuring.rst
doc/nrf/user_guides.rst

Documentation about how to enable and configure different
logging modules and backends in NCS was added.
KRKNWK-6767
Signed-off-by: Kamil Kasperczyk kamil.kasperczyk@nordicsemi.no

doc: Added documentation about logging possibilities in NCS.

---

doc/nrf/doc_build.rst
doc/nrf/gs_programming.rst
doc/nrf/links.txt
doc/nrf/ug_bt_mesh_configuring.rst
include/bluetooth/conn_ctx.rst
include/net/nrf_cloud.rst

Fix broken links and update references to new Zephyr IDs.

doc: Fix links 

---

doc/static/css/common.css
doc/static/css/mcuboot.css
doc/static/css/nrf.css
doc/static/css/nrfxlib.css
doc/static/css/zephyr.css
doc/zephyr/conf.py

Update the style sheets to add support for a "numbered-step" class
that displays a number before a heading.

doc: add styling for numbered headings

---

doc/nrf/links.txt
doc/nrf/ug_thread_tools.rst

Added section on Thread tools page. Updated links.
NCSDK-5509

doc: thread: add border router tool docs

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/bas.rst
applications/nrf_desktop/doc/ble_adv.rst
applications/nrf_desktop/doc/ble_bond.rst
applications/nrf_desktop/doc/ble_conn_params.rst
applications/nrf_desktop/doc/ble_discovery.rst
applications/nrf_desktop/doc/ble_latency.rst
applications/nrf_desktop/doc/ble_qos.rst
applications/nrf_desktop/doc/ble_scan.rst
applications/nrf_desktop/doc/ble_state.rst
applications/nrf_desktop/doc/dev_descr.rst
applications/nrf_desktop/doc/hid_forward.rst
applications/nrf_desktop/doc/qos.rst

Change updates BLE related documentation.

applications: nrf_desktop: Update BLE documentation

---

applications/nrf_desktop/doc/config_channel.rst
applications/nrf_desktop/doc/dev_descr.rst
applications/nrf_desktop/doc/hid_forward.rst
applications/nrf_desktop/doc/hids.rst
applications/nrf_desktop/doc/info.rst
scripts/hid_configurator/README.rst

Change updates documentation related to configuration channel.

applications: nrf_desktop: Config channel doc update

---

applications/nrf_desktop/doc/cpu_meas.rst
applications/nrf_desktop/doc/dfu.rst
applications/nrf_desktop/doc/profiler_sync.rst
applications/nrf_desktop/doc/smp.rst

Change adds documentation for the following modules: cpu_meas, profiler_sync, smp.

applications: nrf_desktop: Add cpu_meas, profiler_sync, smp doc

---

applications/nrf_desktop/src/modules/ble_scan.c

Add comment regarding initial connection parameter update and remove unnecessary scan_stop function calls.

applications: nrf_desktop: Update ble_scan

---

applications/nrf_desktop/doc/motion.rst

Change adds configuration channel related description for motion module.

applications: nrf_desktop: Config channel motion

---

applications/nrf_desktop/src/hw_interface/Kconfig.battery_charger

Cleanup dependencies in configuration for battery charger module.

applications: nrf_desktop: Cleanup bat charger config

---

applications/nrf_desktop/doc/usb_state.rst

Add information about multiple instances of USB HID device
and USB wakeup feature.
Jira:DESK-1057

applications: nrf_desktop: Update usb_state documentation

---

applications/nrf_desktop/README.rst

Change adds note related to the LLPM connection event length.

applications: nrf_desktop: Add LLPM connection event length note

---

samples/nrf9160/nrf_cloud_agps/src/main.c

This patch adds sending of service info after a
successful connection to nRF Cloud has been made.
The service info data contains information
signifying that the device publishes GPS data to
the cloud and that the respective UI element for
displaying GPS should be enabled.

samples: nrf9160: nrf_cloud_agps: Send service info

---

west.yml

- Stack based on stabilized ZBOSS version (09_10_2020)

manifest: nrfxlib: Updated version of ZBOSS stack

---

subsys/zigbee/lib/zigbee_fota/src/zigbee_fota.c

Revert workaround which parses the ZCL frame once more inside the application to get the correct pointer values.

zigbee: Revert workaround for ZOI-113 [KRKNWK-7235]

---

applications/nrf_desktop/src/modules/usb_state.c

applications: nrf_desktop: Handle USB reset in all states

---

lib/sms/sms.c

When an SMS message is received calling `at_cmd_write` to acknowledge the PDU
from within the notification callback causes an `ASSERTION FAIL` in `at_cmd`
because it is being called from the socket thread.
e.g.
```
ASSERTION FAIL [k_current_get() != socket_tid] @ WEST_TOPDIR/nrf/lib/at_cmd/at_cmd.c:361
at_cmd deadlock: socket thread blocking self
```
The fix submits a work to the system work queue to acknowledge the PDU.

lib: sms: fix assertion fail in at_cmd

---

subsys/net/lib/download_client/src/http.c
subsys/net/lib/fota_download/src/fota_download.c

Currently the FOTA download library does not work when trying to download from an offset if you already have parts of the FOTA downloaded.
Fixes for `download_client` includes restarting from offset 0 after requesting with an offset since it will return what's left of the file. Also checking if you are not moving out of bounds when receiving from a file_size.

Fix for downloading from an offset with the Fota download library

---

west.yml

- Update newest MPSL and Softdevice Controller.
Signed-off-by: Czeslaw Makarski <Czeslaw.Makarski@nordicsemi.no>

manifest: nrfxlib: Update MPSL and Softdevice Controller.

---

samples/bluetooth/mesh/light_ctrl/README.rst
samples/bluetooth/mesh/light_ctrl/sample.yaml

Fixes several inconsistencies in the Light Controller sample
documentation.

Bluetooth: Mesh: Light Ctrl sample doc fixes

---

include/bluetooth/mesh/light_ctl.h
include/bluetooth/mesh/light_ctl.rst
include/bluetooth/mesh/light_ctl_cli.h
include/bluetooth/mesh/light_ctl_cli.rst
include/bluetooth/mesh/light_ctl_srv.h
include/bluetooth/mesh/light_ctl_srv.rst
include/bluetooth/mesh/light_temp_srv.h
include/bluetooth/mesh/light_temp_srv.rst
include/bluetooth/mesh/models.h
include/bluetooth/mesh/models.rst
subsys/bluetooth/mesh/CMakeLists.txt
subsys/bluetooth/mesh/Kconfig.models
subsys/bluetooth/mesh/light_ctl_cli.c
subsys/bluetooth/mesh/light_ctl_internal.h
subsys/bluetooth/mesh/light_ctl_srv.c
subsys/bluetooth/mesh/light_temp_srv.c

Adds the following models:
- Light_CTL_cli
- Light_CTL_temp_srv
- Light_CTL_srv
Signed-off-by: Anders Storrø <anders_storro@hotmail.com>

Bluetooth: Mesh: Light CTL models

---

west.yml

Manifest update for PR#272 in nrfxlib.

manifest: zboss doc updates

---

applications/nrf_desktop/src/modules/Kconfig.hid_forward

Change updates Kconfig of hid_forward module.
Jira:DESK-1061

applications: nrf_desktop: Update hid_forward Kconfig

---

applications/asset_tracker/README.rst
samples/nrf9160/nrf_cloud_agps/README.rst

Add note in asset tracker and agps sample related to external
antenna performance in nRF9160.

doc: Add note about external antenna performance for nRF9160

---

doc/nrf/includes/boardname_tables/sample_boardnames.txt
doc/nrf/links.txt
include/shell/shell_bt_nus.rst
samples/bluetooth/shell_bt_nus/README.rst

Opening a PR to implement the fix mentioned in JIRA thread NCSDK-3653

Ncsdk 3653 shell bt nus update

---

applications/nrf_desktop/doc/dfu.rst

Change updates dfu module documentation.

applications: nrf_desktop: Update dfu documentation

---

applications/nrf_desktop/README.rst

Change updates description of flash memory layout.
Jira:DESK-1059

applications: nrf_desktop: Update flash memory layout docs

---

include/bluetooth/mesh/properties.h
include/bluetooth/mesh/sensor_types.h
subsys/bluetooth/mesh/sensor.h
subsys/bluetooth/mesh/sensor_types.c

Adds all new Device Properties from the Mesh Device Properties v2.0
specification, and sensor types for all new properties in the
Environmental properties category.

Bluetooth: Mesh: Device Properties 2.0

---

cmake/multi_image.cmake
doc/nrf/ug_multi_image.rst

Add docs for function 'add_child_image', and update samples in
multi_image.rst to be up to date.
ref: NCSDK-4985

doc: multi_image: improve add_child_image and multi_image_rst

---

samples/peripheral/lpuart/README.rst
samples/peripheral/lpuart/boards/nrf52833dk_nrf52833.conf
samples/peripheral/lpuart/boards/nrf52833dk_nrf52833.overlay
samples/peripheral/lpuart/boards/nrf5340pdk_nrf5340_cpuapp.conf
samples/peripheral/lpuart/boards/nrf5340pdk_nrf5340_cpuapp.overlay
samples/peripheral/lpuart/sample.yaml

Since I have this hardware available, I verified that it works and can be also used to run this sample.

samples: lpuart: Add two more supported board configurations.

---

subsys/net/lib/download_client/Kconfig

net: lib: download_client: fix comment in Kconfig

---

west.yml

nrfxlib: Update ZBOSS to version v3_3_0_4+10_06_2020

manifest: nrfxlib: Update ZBOSS

---

subsys/net/lib/aws_iot/src/aws_iot.c

Fix uninitialized error code if CONFIG_AWS_FOTA is not set.

net: lib: aws_iot: Initialize err

---

include/bluetooth/scan.h
include/bluetooth/scan.rst
subsys/bluetooth/Kconfig.scan
subsys/bluetooth/scan.c

This PR provides the Connection attempts filter which limits number of connection tries for given peripheral address.

Scanning module connection attemps filter

---

doc/nrf/libraries/lib_zigbee.rst
doc/nrf/libraries/zigbee/lib_zigbee_shell.rst
doc/nrf/links.txt
doc/nrf/ug_zigbee_configuring.rst

Adapted SDK documentation of CLI example to NCS.
KRKNWK-7141 and KRKNWK-6682.

docs: add rst file for zigbee shell reference

---

applications/nrf_desktop/README.rst

Change updates supported boards described in documentation.
Jira:DESK-1061

applications: nrf_desktop: Update supported boards in doc

---

applications/nrf_desktop/README.rst

Change updates heap documentation.
Jira:DESK-1061

applications: nrf_desktop: Update heap documentation

---

doc/nrf/includes/filter.js
doc/nrf/index.rst
doc/nrf/known_issues.rst
doc/nrf/release_notes.rst
doc/static/css/nrf.css
doc/static/images/dropdown.svg

Add a known-issues page with filtering functionality.

doc: Add a known issues page

---

applications/nrf_desktop/README.rst

Change updates documentation related to bootloaders.
Jira:DESK-1059

applications: nrf_desktop: Update bootloader docs

---

applications/nrf_desktop/src/modules/ble_scan.c

Change delays starting BLE scan after peer disconnection or connection error. The connection error callback can be called many times in a quick succession. That leads to submitting many ble_peer_search_events that cannot be processed. Eventually Event Manager OOM error is observed.
Jira:DESK-1099

applications: nrf_desktop: Delay BLE scan start to prevent OOM

---

include/bluetooth/mesh/gen_lvl_srv.h
include/bluetooth/mesh/gen_onoff_srv.h
include/bluetooth/mesh/light_ctl_srv.h
include/bluetooth/mesh/light_ctrl_srv.h
include/bluetooth/mesh/models.h
include/bluetooth/mesh/models.rst
include/bluetooth/mesh/scene.h
include/bluetooth/mesh/scene.rst
include/bluetooth/mesh/scene_cli.h
include/bluetooth/mesh/scene_cli.rst
include/bluetooth/mesh/scene_srv.h
include/bluetooth/mesh/scene_srv.rst
subsys/bluetooth/mesh/CMakeLists.txt
subsys/bluetooth/mesh/Kconfig.models
subsys/bluetooth/mesh/gen_lvl_srv.c
subsys/bluetooth/mesh/gen_onoff_srv.c
subsys/bluetooth/mesh/gen_plvl_srv.c
subsys/bluetooth/mesh/light_ctl_srv.c
subsys/bluetooth/mesh/light_ctrl_srv.c
subsys/bluetooth/mesh/light_temp_srv.c
subsys/bluetooth/mesh/lightness_srv.c
subsys/bluetooth/mesh/scene_cli.c
subsys/bluetooth/mesh/scene_srv.c

Adds Scene Server and Scene Client, as well as scene data entries for
all implemented models.

Bluetooth: Mesh: Scene models

---

applications/serial_lte_modem/README.rst
applications/serial_lte_modem/doc/AT_commands_intro.rst

Add "Subpages:" heading to be consistent with the rest of the
documentation.

doc: slm: add subpages headings

---

applications/nrf_desktop/doc/hid_forward.rst

applications: nrf_desktop: Update HID forward doc

---

samples/zigbee/light_switch/README.rst

Add note about overlay-fota.conf in zigbee light switch sample

doc: Add note about overlay-fota.conf in zigbee light switch sample

---

applications/asset_tracker/README.rst
applications/connectivity_bridge/README.rst
applications/nrf_desktop/README.rst
samples/nrf9160/azure_fota/README.rst
samples/nrf9160/azure_iot_hub/README.rst
samples/zigbee/light_switch/README.rst
tests/crypto/README.rst

ref: https://github.com/nrfconnect/sdk-nrf/pull/2900
Update the following with table-from-rows:
asset_tracker, connectivity_bridge, nrf_desktop, azure fota
azure_iot_hub,zigbee/light_switch, tests/crypto

doc: Update few samples and applications with table-from-rows

---

doc/nrf/releases/release-notes-1.1.0.rst
doc/nrf/releases/release-notes-1.3.0.rst
doc/nrf/ug_thread_configuring.rst
west.yml

Manifest update for PR#273 in nrfxlib.

manifest: nrf_security doc rework

---

west.yml

This updates hal_nordic revision, which includes radio driver bugfixes.

manifest: Update sdk-zephyr introducing 802.15.4 radio driver bugfixes

---

applications/nrf_desktop/doc/ble_scan.rst

Change adds information regarding connection attempt filter.
Jira:DESK-817

applications: nrf_desktop: Update ble_scan doc

---

samples/bluetooth/direct_test_mode/README.rst
samples/bluetooth/direct_test_mode/nrf5340pdk_nrf5340_cpunet.overlay
samples/bluetooth/direct_test_mode/src/dtm.c
samples/bluetooth/direct_test_mode/src/dtm.h
samples/bluetooth/direct_test_mode/src/dtm_hw.c
samples/bluetooth/direct_test_mode/src/dtm_hw.h
samples/bluetooth/direct_test_mode/src/dtm_hw_config.h
samples/nrf5340/empty_app_core/src/main.c

This PR adjusts DTM sample to the 5.2 BLE specification. 
Added features:
- CTE support
- Tx power set

DTM 5.2 features

---

doc/nrf/links.txt
doc/nrf/shortcuts.txt
doc/nrf/ug_thread.rst
doc/nrf/ug_thread_architectures.rst
doc/nrf/ug_thread_commissioning.rst
samples/openthread/ncp/README.rst

Updated OT license note and added it to relevant pages.
KRKNWK-7694

doc: thread: update license footer for ot pages

---

doc/nrf/known_issues.rst

Change adds direct advertising problems to known issues for SoftDevice Link Layer.

doc: Add direct advertising problems to known issues

---

samples/bluetooth/direct_test_mode/README.rst
samples/nrf5340/netboot/README.rst

Small doc fixes - see the separate commits.

Doc fixes after review

---

drivers/gps/nrf9160_gps/nrf9160_gps.c

Emit GPS_EVT_SEARCH_STARTED also when gps starts automatically
after position fix or timeout.
Jira: CIA-115

drivers: gps: nrf9160_gps: emit started event

---

applications/nrf_desktop/README.rst
doc/nrf/links.txt

Change adds short HLK tests description to the documentation.
Jira:DESK-1104

applications: nrf_desktop: HLK tests description

---

applications/nrf_desktop/README.rst

Change describes possible issue related to settings incompatibility after the firmware upgrade.
Jira:DESK-1103

applications: nrf_desktop: Document settings incompatibility

---

doc/nrf/links.txt
doc/nrf/ug_logging.rst
doc/nrf/ug_thread_architectures.rst
doc/nrf/ug_thread_vendor_hooks.rst
samples/openthread/cli/README.rst
samples/openthread/coap_client/README.rst
samples/openthread/coap_server/README.rst
samples/openthread/ncp/README.rst
samples/zigbee/light_bulb/README.rst
samples/zigbee/light_switch/README.rst
samples/zigbee/network_coordinator/README.rst

Fixed style on some sample pages.
Added cross-links.

doc: thread: zigbee: fixes on sample pages

---

subsys/bluetooth/mesh/gen_battery_cli.c
subsys/bluetooth/mesh/gen_plvl_cli.c
subsys/bluetooth/mesh/gen_prop_cli.c
subsys/bluetooth/mesh/gen_prop_srv.c
subsys/bluetooth/mesh/light_ctrl_srv.c
subsys/bluetooth/mesh/lightness_cli.c
subsys/bluetooth/mesh/sensor.c
subsys/bluetooth/mesh/sensor.h
subsys/bluetooth/mesh/sensor_cli.c
subsys/bluetooth/mesh/sensor_srv.c
subsys/bluetooth/mesh/sensor_types.c

Fixes a series of critical model implementation bugs in the Bluetooth Mesh subsystem discovered during qualification testing.
NCSDK-6774

Bluetooth: Mesh: Qualification testing model bugs

---

doc/nrf/known_issues.rst

Added v1.3.2 and v1.4.0 tags to known issues.
**This PR only updates the existing issues. To add new known issues, create separate PRs to this page.**

doc: update known issues for 140 release

---

samples/nrf9160/aws_iot/src/main.c

This patch adds functionality that prints received
messages and what topic the messages was received on.
NCSDK-6623

samples: nrf9160: aws_iot: Add printing of received data

---

samples/nrf9160/aws_iot/Kconfig
samples/nrf9160/aws_iot/src/main.c
subsys/net/lib/aws_fota/src/aws_fota.c
subsys/net/lib/aws_jobs/src/aws_jobs.c

Add delayed work item that tries to reconnect upon an
AWS_IOT_DISCONNECT event with configurable interval
in between retries.
**This PR also changes the default log level for certain log output in AWS jobs/fota
NCSDK-6623

samples: nrf9160: aws_iot: Add reconnection work

---

doc/nrf/known_issues.rst

Add USB related info to known issues file.

doc: Add USB known issues

---

samples/nrf9160/agps/README.rst

samples: nrf9160: agps: add mfw 1.1.x not supported to doc

---

doc/nrf/known_issues.rst

Added build system known issue for KRKNWK-7827.
Requested in NCSDK-6814.

doc: known issues: add partition overlap issue

---

scripts/partition_manager.py

This would fail since the script assumed that the size
represented the last address (as is the case with flash
which starts from address 0).
Fix by passing base address as input and calculate the
last address based on this.
Ref: NCSDK-6837

partition_manager: fix bug where static config would fail for SRAM

---

subsys/net/lib/aws_iot/src/aws_iot.c
tests/lib/date_time/CMakeLists.txt
tests/lib/date_time/prj.conf
tests/lib/date_time/src/main.c

Add missing licence headers

---

doc/nrf/index.rst
doc/nrf/known_issues.rst
doc/nrf/links.txt
doc/nrf/release_notes.rst
doc/nrf/releases/release-notes-1.4.0.rst
doc/nrf/releases/release-notes-latest.rst

Add release notes for 1.4.0 to the repo from Confluence, with edits from doc review meeting.
**To be merged just before tagging.**

docs: add 140 release notes

---

subsys/bluetooth/controller/hci_driver.c
west.yml

See CHANGELOG for additional details.
See https://github.com/nrfconnect/sdk-nrfxlib/pull/321

manifest: SoftDevice Controller with configurable ext. scanning

---

lib/date_time/date_time.c

Change log output in date time library to LOG_DBG.

lib: date_time: Change log output to LOG_DBG

---

lib/bsdlib/nrf91_sockets.c

When handed a large set of buffers, sendmsg might sometimes send only
some of the data and then report success.  According to the standards,
sendmsg is supposed to either completely succeed or return a failure
code.  This change will cause it to always block until it succeeds,
which is also slightly against the standard, but better than reporting
a success when it actually failed.
Signed-off-by: Justin Brzozoski <justin.brzozoski@signal-fire.com>

lib: bsdlib: fix issue with partial sendmsg

---

subsys/zigbee/common/zigbee_helpers.c
tests/subsys/zigbee/osif/nvram/src/main.c

Fix coverity issues having high or medium impact
in zigbee.

zigbee: Fix high & medium impact coverity issues

---

applications/serial_lte_modem/doc/FTP_AT_commands.rst
applications/serial_lte_modem/doc/GPS_AT_commands.rst
applications/serial_lte_modem/doc/Generic_AT_commands.rst
applications/serial_lte_modem/doc/HTTPC_AT_commands.rst
applications/serial_lte_modem/doc/ICMP_AT_commands.rst
applications/serial_lte_modem/doc/MQTT_AT_commands.rst
applications/serial_lte_modem/doc/TCPIP_AT_commands.rst
applications/serial_lte_modem/doc/slm_description.rst

Adding GPS commands from the Word doc.
PDF printout: 
[Application description — nRF Connect SDK 1.4.pdf](https://github.com/nrfconnect/sdk-nrf/files/5391915/Application.description.nRF.Connect.SDK.1.4.pdf)

Ncsdk 6696 slm add gps testing [DOC ONLY]

---

samples/nfc/record_text/README.rst
samples/nfc/tag_reader/README.rst
samples/nfc/tnep_poller/README.rst
samples/nfc/tnep_tag/README.rst
samples/nfc/writable_ndef_msg/README.rst

Add the table that lists the supported boards
in NFC samples.

doc: Update Requirements section in NFC samples

---

doc/nrf/known_issues.rst

Point to PR with the fix.
Ref: NCSDK-6777

known_issue: add known issue about project out of date

---

doc/nrf/includes/filter.js
doc/nrf/known_issues.rst

Added description at the top.
Make the page display only the latest official release entries upon opening the page.

doc: updates to known issues page

---

doc/static/js/ncs.js

Add support for development release versions in versions.json. Any release that uses a `-xyz` suffix is considered a development release and gets a distinct banner. The first release declared in the "VERSIONS" key in versions.json that uses only numbering is considered the last release.

doc: add support for development release pages

---

scripts/partition_manager.py

Also verify the first address, and improve printing.

partition_manager: Small refactor of address verification

---

applications/serial_lte_modem/src/main.c

Ensure that the HFCLK is running on external XTAL when UART is enabled.
The instruction in PS is that UART requires external XTAL.
JIRA# NCSDK-7004

applications: serial_lte_modem: request external XTAL for UART

---

samples/debug/ppi_trace/README.rst
samples/event_manager/README.rst
samples/nrf5340/empty_app_core/README.rst
samples/nrf9160/lte_ble_gateway/README.rst
samples/nrf9160/lwm2m_carrier/README.rst
samples/nrf9160/secure_services/README.rst
samples/peripheral/lpuart/README.rst

Update the Requirements section of few samples
by adding the table that lists the supported
development kits.

doc: Update Requirements section in samples

---

subsys/net/lib/aws_iot/src/aws_iot.c

This patch adds an atomic variable that keeps track of the
clients connection state. This variable is used to prevent the AWS IoT
library from notifying the application multiple times upon a
disconnect from AWS.

net: lib: aws_iot: Prevent multiple disconnect notifications

---

doc/nrf/includes/sample_board_rows.txt
samples/bluetooth/alexa_gadget/README.rst
samples/bluetooth/central_bas/README.rst
samples/bluetooth/central_dfu_smp/README.rst
samples/bluetooth/central_hids/README.rst
samples/bluetooth/central_hr_coded/README.rst
samples/bluetooth/central_nfc_pairing/README.rst
samples/bluetooth/central_uart/README.rst
samples/bluetooth/direct_test_mode/README.rst
samples/bluetooth/enocean/README.rst
samples/bluetooth/llpm/README.rst
samples/bluetooth/mesh/light/README.rst
samples/bluetooth/mesh/light_switch/README.rst
samples/bluetooth/peripheral_bms/README.rst
samples/bluetooth/peripheral_gatt_dm/README.rst
samples/bluetooth/peripheral_hids_keyboard/README.rst
samples/bluetooth/peripheral_hids_mouse/README.rst
samples/bluetooth/peripheral_lbs/README.rst
samples/bluetooth/peripheral_nfc_pairing/README.rst
samples/bluetooth/peripheral_uart/README.rst
samples/bluetooth/shell_bt_nus/README.rst
samples/bluetooth/throughput/README.rst

ref: NCSDK-4950
Update the Requirements section in Bluetooth samples

doc: Update Requirements section in Bluetooth samples

---

west.yml

Manifest update for bsdlib gps doc update

bsdlib: manifest update for bsdlib gps doc update

---

doc/nrf/known_issues.rst

Removed references about origin of some entries.
They are not relevant and hamper filtering.

doc: known issues: remove lines

---

doc/nrf/links.txt
doc/nrf/ug_nrf5340.rst

Updating the working with nRF53 user guide.

doc: add a deprecation note for nRF5340 PDK

---

doc/nrf/releases/release-notes-latest.rst

-Add nRF5340 development support
-Inform about memory optimizations
Signed-off-by: Piotr Szkotak <piotr.szkotak@nordicsemi.no>

doc: Update release-notes-latest.rst with Thread additions

---

applications/asset_tracker/README.rst
applications/serial_lte_modem/doc/slm_description.rst
doc/nrf/dm_code_base.rst
doc/nrf/links.txt
doc/nrf/nrfxlib.rst
doc/nrf/releases/release-notes-1.4.0.rst
doc/nrf/templates/sample_README.rst
doc/nrf/ug_ble_controller.rst
doc/nrf/ug_nrf52.rst
samples/bluetooth/llpm/README.rst
samples/mpsl/timeslot/README.rst
samples/nrf9160/azure_fota/README.rst
samples/nrf9160/azure_iot_hub/README.rst
samples/nrf9160/lwm2m_client/README.rst
samples/nrf9160/mqtt_simple/README.rst
samples/zigbee/light_bulb/README.rst
samples/zigbee/light_switch/README.rst
samples/zigbee/network_coordinator/README.rst

Update broken and redirecting links in the links.txt file.
Ref. NCSDK-7099

doc: update links.txt

---

samples/bluetooth/direct_test_mode/src/dtm.c

Use PPI/DPPI channel allocator instead of static allocation. This fixes an issue when other drivers/libraries use the same PPI/DPPI channels.

samples: dtm: Use PPI/DPPI channel allocator

---

applications/serial_lte_modem/doc/HTTPC_AT_commands.rst

<op> parameter had the wrong values for disconnect/connect

doc: updating documentation for AT#XHTTPCCON

---

doc/nrf/releases/release-notes-latest.rst

doc: add kernel changes from last upmerge

---

doc/nrf/releases/release-notes-latest.rst

This updates release notes for 1.4.99-dev1
Signed-off-by: Wojciech Bober <wojciech.bober@nordicsemi.no>

zigbee: Update release notes

---

doc/nrf/releases/release-notes-latest.rst

Only those relevant to NCS were selected.

doc: release-notes-latest: Add changes in drivers from last upmerge

---

doc/nrf/known_issues.rst

doc: known_issues: update USB known issues for 1.4.99

---

doc/nrf/releases/release-notes-latest.rst

Includes upstream and downstream changelog since 1.4.

doc: release-notes: Summarize Bluetooth Mesh changes

---

doc/nrf/releases/release-notes-latest.rst

Includes upstream and downstream changelog since 1.4.

doc: release-notes: Summarize Bluetooth Host and Controller changes

---

doc/nrf/releases/release-notes-latest.rst

Summarize all uncategorized items in their respective sections.

doc: release-notes-latest: Summarize other changes from the upmerge

---

subsys/bluetooth/mesh/light_ctrl_srv.c

If the Light control server gets an ON message while fading to the on
state, it should not reschedule the timer, as this will delay the
necessary house keeping done at transition end.

Bluetooth: Mesh: Don't reschedule LC srv transition timer

---

subsys/bluetooth/mesh/gen_plvl_srv.c
subsys/bluetooth/mesh/light_temp_srv.c
subsys/bluetooth/mesh/lightness_srv.c

When performing a delta set in the lighting models, the delta is added
to the current value, then stored in an integer that only holds 16 bits.
If the delta change overflows the 16 bit integer, it will wrap around
when stored, instead of clamping to the min/max of the storage variable.
Although clamping is done in the set-functions, it's already too late,
as the level has overflowed its variable and wrapped around.
Adds boundary clamp before storing the target values in the 16 bit
integer for gen_plvl, lightness_srv and light_temp_srv.

Bluetooth: Mesh: Fix overflow on lvl_delta

---

samples/nrf9160/udp/src/main.c

When enabling RAI the link controller checks if the current network mode
is NB-IoT (which is the only network mode that supports this feature).
This patch moves the enabling of RAI to after the modem configuration is
initialized to ensure that NB-IoT is set as the network mode before
calling lte_lc_rai_req(). Previously this API call would fail even
though NB-IoT was configured as the network mode.

samples: nrf9160: udp: Split modem configuration into init and connect

---

applications/asset_tracker/CMakeLists.txt
applications/asset_tracker/Kconfig
applications/asset_tracker/src/main.c

Motion and environment sensors can now be enabled and disabled
by the CONFIG_MOTION and CONFIG_ENVIRONMENT_SENSORS
Jira:CIA-72

applications: asset_tracker: Make sensors kConfigurable

---

subsys/bluetooth/mesh/gen_plvl_srv.c
subsys/bluetooth/mesh/light_ctl_srv.c
subsys/bluetooth/mesh/light_ctrl_srv.c
subsys/bluetooth/mesh/lightness_srv.c

Converts all instances of if min else if max and min(max( into clamp
macros in mesh.

Bluetooth: Mesh: Use clamp macro in mesh models

---

include/event_manager.rst

Change describes events with dynamic data size in documentation.
Jira:DESK-1108

event_manager: Describe events with dynamic size in doc

---

subsys/bluetooth/mesh/light_ctl_cli.c

Resolves conflicts in changes between pull requests #3423 and #3424 that
were merged without getting CI runs between them to point out the build
errors.

Bluetooth: Mesh: Follow up conflicting changes in Light CTL range

---

doc/nrf/ug_bootloader.rst
include/fw_info.h
samples/bootloader/README.rst

Updated general bootloader page structure.
Updates several procedures and provided more detailed information.
Signed-off-by: Chris Bittner <chris.bittner@nordicsemi.no>

doc: bootloader: updated readme structure

---

west.yml

Manifest update for nrfxlib PR-351

manifest: GNSS doc update

---

doc/nrf/app_power_opt.rst

Add note to power optimization user guide

doc: Add note to power optimization user guide

---

applications/asset_tracker/src/main.c

Reboot the application in case of irrecoverable error reported
from the BSD library.

applications: asset_tracker: Reboot in case of irrecoverable error

---

doc/nrf/ug_thread_tools.rst

Update instructions to point out which version to install.
Ref. KRKNWK-8130

doc: update wpantund installation instructions

---

doc/nrf/links.txt

Reorganized sections in links.txt.
Removed unused links.

doc: reorganize links.txt

---

samples/bluetooth/alexa_gadget/README.rst

Rephrased Alexa Gadgets sample name based on feedback.

doc: rename Alexa Gadgets sample

---

scripts/bootloader/provision.py

Added a check in provision.py such that it fails if a public key
contains 0xFFFF.
Ref: NCSDK-5912
Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>

bootloader: Let provision.py fail if a public key contains 0xFFFF

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/battery_charger.rst
applications/nrf_desktop/doc/ble_state.rst
applications/nrf_desktop/doc/dfu.rst
applications/nrf_desktop/doc/hid_state.rst
applications/nrf_desktop/doc/selector.rst
doc/nrf/libraries/zigbee/lib_zigbee_shell.rst
doc/nrf/libraries/zigbee/lib_zigbee_signal_handler.rst
doc/nrf/ug_thread_architectures.rst

Changed warnings to notes. Includes also general language cleanups.

doc: warnings to notes

---

samples/nrf9160/gps/src/main.c

Signed-off-by: Alexey Markevich <buhhunyx@gmail.com>

samples: nrf9160: gps: simplify flag check; use k_msleep

---

subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c

Use the common AT command interface instead of opening an AT socket
directly. There's a limited number of socket available, and using
the common interface eases debugging and error handling.

net: lib: nrf_cloud: Use AT command interface instead of AT socket

---

doc/nrf/ug_nrf5340.rst

The difference between recovering cores with west and nfjprog is not
trivial to grasp, and there are details about it that are not described
anywhere else in the documentation. Thus add an explanation about
recovery and the implications of it in the nRF53 User Guide.

doc: nRF53 UG: Add text about recovery

---

.github/workflows/compliance.yml

Update copypasta to iterate over a list of files to check. Update tests to use bash style conditional constructs.

ci: remove block copypasta in compliance check

---

.github/workflows/docbuild.yml

This depends on #3271 and #3272; commits are included here, so needs rebase once they are merged.

doc: build documentation on GH actions

---

subsys/net/lib/fota_download/src/fota_download.c

FOTA requires firmware info. Previously it was accessed using
secure services that are available only in non-secure environment.
With this patch firmware info is accessible in both non-secure
environment and non-Trustzone applications.
This patch allows building FOTA for devices without Trustzone.

net: fota: Fix build without Trustzone

---

samples/bluetooth/central_bas/CMakeLists.txt
samples/bluetooth/central_dfu_smp/CMakeLists.txt
samples/bluetooth/enocean/CMakeLists.txt
samples/bluetooth/mesh/light/CMakeLists.txt
samples/bluetooth/mesh/light_ctrl/CMakeLists.txt
samples/bluetooth/mesh/light_switch/CMakeLists.txt
samples/bluetooth/mesh/sensor_client/CMakeLists.txt
samples/bluetooth/mesh/sensor_server/CMakeLists.txt
samples/bluetooth/shell_bt_nus/CMakeLists.txt

Add NORDIC SDK APP START and NORDIC SDK APP END tags to Bluetooth
samples that did not have them.

samples: Bluetooth: Add NORDIC SDK APP START and END tags

---

include/ei_ncs.h
lib/edge_impulse/CMakeLists.txt
lib/edge_impulse/Kconfig
lib/edge_impulse/ei_ncs.cpp

Change adds wrapper that runs library code in a low-priority thread and exposes API for the application.
Jira: NCSDK-7363

lib: edge_impulse: Add NCS wrapper

---

subsys/bluetooth/mesh/light_ctrl_srv.c

The manual mode cooldown duration calculation did not treat the manual
cooldown configuration as seconds, but milliseconds. It also failed to
account for underflow when subtracting the fade duration, and always
assumed that the fade happened with the configured standby manual
duration, which would not be the case if the transition was set
manually.
Reworks the timeout function in Light Controller to account for these
errors and reduce the amount of indentation.

Bluetooth: Mesh: Fix Light Controller cooldown timer

---

samples/bluetooth/hci_lpuart/README.rst

nRF52840 example on nRF9160 DK but was referencing steps to build and run for a nRF9160 example
Signed-off-by: Akash Patel <akash.patel@nordicsemi.no>

doc: hci_lpuart: Update building and running section

---

scripts/hid_configurator/modules/dfu.py

Change fixes check for interrupted DFU process.
Jira: NCSDK-7566

scripts: hid_configurator: Fix interrupted DFU check

---

tests/lib/at_cmd_parser/at_utils/src/main.c

NCSDK-5199: Temporary fix for failing commands (HWVERSION etc.)
Signed-off-by: Dag Bjarvin <Dag.Bjarvin@nordicsemi.no>

tests:lib:at_cmd_parser: Added unit test for is_clac

---

subsys/mpsl/mpsl_fem.c

nRF21540 can be controlled via two different interfaces: GPIO and SPI.
Currently only simplified GPIO interface is supported. This patch puts
the unused yet connected pins of both interfaces in a well-defined,
inactive state.
Signed-off-by: Jedrzej Ciupis <jedrzej.ciupis@nordicsemi.no>

subsys: mpsl: Set unused nRF21540 pins to inactive state

---

samples/openthread/cli/README.rst
samples/openthread/coap_client/README.rst
samples/openthread/coap_server/README.rst
samples/openthread/common/dts-nrf21540-fem.overlay
samples/openthread/ncp/README.rst

Add FEM support to OpenThread samples.
KRKNWK-7387

samples: openthread: add FEM support to samples

---

doc/nrf/app_power_opt.rst

Making the tone more active and some other fixes.

doc: cleaning up the language in Power optimization doc

---

subsys/net/lib/azure_iot_hub/src/azure_iot_hub.c

Currently, the `user_name` is generated in runtime only when DPS is used
and in all other cases it is a build-time concatenation of Kconfig config 
parameters. However this creates an issue when using a device id that is not 
set in Kconfig but is set in runtime by the app. This patch adds runtime 
generation for the user_name for this case.
Signed-off-by: Alex Tsamakos <alex@actinius.com>

net: lib: azure_iot_hub: Fix user_name generation

---

scripts/partition_manager_report.py

Show end of the last span in pm_report.
Ref: NCSDK-7495
Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>

partition_manager: Show end of the last span in pm_report

---

subsys/net/lib/nrf_cloud/src/nrf_cloud_fota.c

add additional error logging and do not check job id if
job parsing fails.

net: lib: nrf_cloud: fota error handling

---

west.yml

Signed-off-by: Jonathan Rico <jonathan.rico@nordicsemi.no>

Bluetooth: Update softdevice controller & MPSL

---

cmake/multi_image.cmake
subsys/partition_manager/Kconfig
subsys/partition_manager/Kconfig.template.build_strategy
subsys/partition_manager/Kconfig.template.build_strategy_domain
subsys/partition_manager/partition_manager_enabled.conf

kconfig: expose if pm is enabled in kconfig

---

doc/nrf/releases/release-notes-latest.rst
samples/zigbee/light_bulb/README.rst
samples/zigbee/light_switch/README.rst
samples/zigbee/network_coordinator/README.rst

Edited structure of docs to match template.

doc: zigbee: update sample structure

---

scripts/hid_configurator/modules/dfu.py
scripts/hid_configurator/requirements.txt

Change updates usages of the imgtool API to make the code work properly with imgtool version 1.7.0.
Jira: NCSDK-7755

scripts: hid_configurator: Update handling imgtool API

---

include/shell/shell_bt_nus.rst
samples/bluetooth/shell_bt_nus/README.rst
scripts/shell/bt_nus_shell.py
scripts/shell/requirements.txt

Converted script to python 3. Kept python2 version as `scripts/shell/bt_nus_shell_py2.py` for now.
Updated documentation.

scripts: shell: bt_nus_shell: Convert to python3

---

lib/lte_link_control/lte_lc.c

Currently the link controller will log errors when trying to parse
CEREG notifications with level less than 4, as cell and PSM may
not be available.
This patch adds checks before attempting to parse CEREG notifications
to ensure that the information to be parsed is actually available.
In addition, PSM update events will now only be emitted if registered
with a network.

lib: lte_lc: Parse only available info in CEREG notifications

---

applications/asset_tracker/README.rst
doc/nrf/known_issues.rst
doc/nrf/links.txt
doc/nrf/releases/release-notes-0.3.0.rst
doc/nrf/releases/release-notes-0.4.0.rst
doc/nrf/releases/release-notes-1.0.0.rst
doc/nrf/releases/release-notes-1.1.0.rst
doc/nrf/releases/release-notes-1.2.0.rst
doc/nrf/releases/release-notes-1.3.0.rst
doc/nrf/releases/release-notes-1.4.0.rst
doc/nrf/releases/release-notes-latest.rst
doc/nrf/ug_thingy91.rst
include/net/nrf_cloud.rst
include/net/nrf_cloud_agps.rst
samples/nrf9160/agps/README.rst
samples/nrf9160/at_client/README.rst
samples/nrf9160/aws_fota/README.rst
samples/nrf9160/cloud_client/README.rst
samples/nrf9160/http_update/application_update/README.rst
samples/nrf9160/lte_ble_gateway/README.rst

Renamed in all appropriate docs

doc: renaming nRF Cloud to nRF Connect for Cloud

---

doc/nrf/drivers/entropy_cc310.rst

Added mention to nrf5340.
Reviewed and edited the text on the page.

doc: entropy_cc310 docupdate

---

applications/nrf_desktop/src/modules/Kconfig.hid

Change fixes a typo in Kconfig.hid file.

applications: nrf_desktop: Fix typo in Kconfig.hid

---

include/bluetooth/mesh/sensor_cli.h
subsys/bluetooth/mesh/sensor.c
subsys/bluetooth/mesh/sensor.h
subsys/bluetooth/mesh/sensor_cli.c
subsys/bluetooth/mesh/sensor_types.c

Various problems with the sensor model and sensor types discovered while testing. See commit messages for details.

Bluetooth: Mesh: Sensor bug fixes

---

doc/nrf/known_issues.rst

This issue is already fixed in the master branch.
See DRGN-15226.

doc: known issues: Add issue link loss when LTK request is masked

---

.github/workflows/compliance.yml

Pull in the changes from this PR:
https://github.com/zephyrproject-rtos/zephyr/pull/31452

actions: Update compliance workflow to fail on crash

---

include/bluetooth/mesh/light_ctrl_srv.h
subsys/bluetooth/mesh/light_ctrl_cli.c
subsys/bluetooth/mesh/light_ctrl_srv.c
subsys/bluetooth/mesh/model_utils.c

Major fix in 391d8e6. The rest are style fixes.

Bluetooth: Mesh: Set target_on_off when no transition provided

---

subsys/net/lib/download_client/Kconfig
subsys/net/lib/download_client/src/download_client.c

Set a thread name, to aid debugging and improve docs.

net: lib: download_client: doc and thread name

---

applications/serial_lte_modem/src/slm_at_host.c

Nordic Serial driver disable UART RX on FRAME ERROR or BREAK.
Add a recovery mechanism to re-enable RX, with 500ms delay.
NOTE the first AT command buffer received after the recovery
could have garbage data, due to no Serial Async API to drain
UART FIFO after the recovery.
JIRA reference: NCSIDB-347

applications: serial_lte_modem: Add UART recovery mechanism

---

west.yml

This fixes timing values in nRF21540 FEM documentation
Signed-off-by: Pegza, Jakub <Jakub.Pegza@nordicsemi.no>

MPSL: update manifest

---

doc/nrf/releases/release-notes-latest.rst

Release notes update pull request.

Upmerge 14.12.2020 Release Notes Update

---

samples/bluetooth/alexa_gadget/sample.yaml

Add ci_build tag to alexa_gadget bluetooth sample.
Signed-off-by: Audun Korneliussen <audun.korneliussen@nordicsemi.no>

samples: alexa_gadget: Add ci_build tag

---

west.yml

Update zephyr with pairing procedure improvement.

manifest: update zephyr with pairing procedure improvement

---

subsys/dfu/dfu_target/src/dfu_target_stream.c

Prior to this commit, the page to which the last
written offset belongs to would be erased.
This is incorrect since it has already been
erased.
Fix this by setting the 'last erased page'
variable in the stream context when
loading the bytes written
Also increase the name key buffer to be more
future proof.
Ref: NCSDK-7924

dfu_target: fix bug with loading progress

---

scripts/get_pulls_in_range.py
scripts/requirements-extra.txt

Some fixes to our requirements files and improvements to the script.

get_pulls_in_range.py improvements

---

west.yml

This commit sets newer revision of the bootloader/mcuboot.

west: Update bootloader/mcuboot revision

---

doc/nrf/includes/thread_configure_network.txt
samples/openthread/cli/README.rst

This PR updates the documentation with setting channel, panid, masterkey.
Signed-off-by: Piotr Szkotak <piotr.szkotak@nordicsemi.no>

doc: Update Thread CLI sample with setting basic parameters

---

west.yml

Update manifest to remove duplicates in zephyr modules list.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

manifest: update sdk-zephyr for Zephyr module duplicate removal

---

doc/nrf/releases/release-notes-latest.rst

Note changes related to Zephyr drivers that are relevant to NCS.

doc: release-notes-latest: Add changes in drivers from upmerge 20201214

---

applications/serial_lte_modem/src/http_c/slm_at_httpc.c
applications/serial_lte_modem/src/slm_at_tcpip.c

Close file descriptor (socket handle) in abnormal context.

applications: serial_lte_modem: Coverity Fix resource leak

---

samples/nrf9160/lwm2m_client/Kconfig
samples/nrf9160/lwm2m_client/src/lwm2m/lwm2m_firmware.c

Set a buffer for MCUboot FOTA upgrades.

samples: nrf9160: lwm2m_client: Set MCUboot buffer

---

west.yml

Allows encryption and connection parameter updates on multiple links
at the same time.

manifest: Use new softdevice controller

---

.checkpatch.conf
.github/workflows/compliance.yml
scripts/checkpatch/typedefsfile

Align with upstream Zephyr and Linux.

ci: Bump checkpatch max line length to 100

---

doc/nrf/releases/release-notes-latest.rst

Add sdk-zephyr release notes for recent upmerges.

Bluetooth: Add sdk-zephyr release notes for recent upmerges

---

doc/nrf/images/ieee802154_nrf53_multiprot_design.svg
doc/nrf/images/ieee802154_nrf53_singleprot_design.svg
doc/nrf/releases/release-notes-latest.rst
doc/nrf/ug_nrf5340.rst

- nRF53 UG update with a drawing showing the architecture of the 802.15.4
solution for multicore SoC.

doc: nRF53 UG: IEEE 802.15.4 design in multi-core SoC

---

include/bluetooth/mesh/models.rst
include/bluetooth/mesh/scheduler.rst
include/bluetooth/mesh/scheduler_cli.rst
include/bluetooth/mesh/scheduler_srv.rst

Adds files:
scheduler.rst
scheduler_srv.rst
scheduler_cli.rst
Updates models.rst

Bluetooth: Mesh: Scheduler model doc

---

applications/asset_tracker/child_image/spm/prj.conf

Align spm config with samples/spm.

applications: asset_tracker: Fix SPM config

---

doc/nrf/known_issues.rst

doc: known_issues: No RSSI temperature adjustment in 802.15.4

---

doc/nrf/releases/release-notes-latest.rst
doc/nrf/ug_nrf5340.rst

Reviewed RST files edited in PR 3860.

doc: docreview for PR 3860

---

doc/nrf/includes/build_and_run_nrf9160.txt
doc/nrf/includes/spm.txt
doc/nrf/links.txt
doc/nrf/ug_multi_image.rst
doc/nrf/ug_nrf5340.rst
doc/nrf/ug_nrf9160.rst
doc/nrf/ug_tfm.rst
include/spm.rst
samples/tfm/tfm_hello_world/README.rst

Adding TF-M information to more places in the docset.
Extending the already existing sections.

doc: TF-M updates for NCS 1.5

---

samples/openthread/coap_client/src/coap_client_utils.c
subsys/net/lib/coap_utils/coap_utils.c

It fixes: https://projecttools.nordicsemi.no/jira/browse/KRKNWK-8986

openthread: Static Analysis Fix: Uninitialized variable, NULL dereference pointer, parse warning

---

applications/asset_tracker_v2/src/cloud/aws_iot_integration.c
applications/asset_tracker_v2/src/cloud/cloud_codec/aws_iot_codec.c
applications/asset_tracker_v2/src/modules/data_module.c

Fix issues discovered by static code analysis.

applications: asset_tracker_v2: Fix static code analysis issues

---

doc/nrf/releases/release-notes-latest.rst

Note changes related to Zephyr drivers that are relevant to NCS.

doc: release-notes-latest: Add changes in drivers from the last upmerge

---

samples/openthread/cli/boards/nrf21540dk_nrf52840.overlay
samples/openthread/cli/boards/nrf52840dk_nrf52840.overlay
samples/openthread/cli/prj_nrf5340dk_nrf5340_cpuapp.conf
samples/openthread/coap_client/boards/nrf21540dk_nrf52840.overlay
samples/openthread/coap_client/boards/nrf52840dk_nrf52840.overlay
samples/openthread/coap_client/prj_nrf5340dk_nrf5340_cpuapp.conf
samples/openthread/coap_server/boards/nrf21540dk_nrf52840.overlay
samples/openthread/coap_server/boards/nrf52840dk_nrf52840.overlay
samples/openthread/coap_server/prj_nrf5340dk_nrf5340_cpuapp.conf
samples/openthread/ncp/boards/nrf52840dk_nrf52840.overlay

The PR #3872 has based on changes from #3793. #3793 has been reverted
and now we need to revert also #3872.
This reverts commit 6f4d0168ebf7fe116970f5c3ca90d4fef3d463f6.

samples: openthread: Revert #3872

---

doc/nrf/ug_tfm.rst

Address comment submitted after PR was merged.

doc: change wording of tf-m limitation

---

applications/serial_lte_modem/src/ftp_c/slm_at_ftp.c
applications/serial_lte_modem/src/slm_at_host.c

Initialize specific variables at definition.

applications: SLM: Static Analysis Fix uninitialized scalar variable

---

samples/bluetooth/throughput/README.rst

doc: format fix to Bluetooth throughput sample doc

---

applications/asset_tracker_v2/README.rst

Add note stating that work on the application is still in progress,
and that changes and improvements are to be expected going forward.

applications: asset_tracker_v2: Add note about work-in-progress

---

doc/nrf/releases/release-notes-latest.rst

-Added in release-notes-latest.txt post haste
ref: NCSDK-7915
ref: NCSDK-7780
ref: NCSDK-7910
ref: NCSDK-7914

doc: Updating crypto changelog items for nRF

---

west.yml

Updated unity to the latest from master which contains some fixes,
including fix for suiteTearDown not included in the build.
Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

west.yml: Update unity version

---

west.yml

Updated manifest for PR 410 nrfxlib.

manifest: update for PR 410 nrfxlib

---

west.yml

manifest: update for PR 414

---

doc/nrf/links.txt
doc/nrf/ug_zigbee_configuring.rst
include/zigbee/zigbee_fota.rst

Added section about upgrading Zigbee application.
Updated version number for the NCP Host package.

doc: zigbee: update configuration info

---

drivers/serial/uart_nrf_sw_lpuart.c

It may happen that receiver was reset and transmitter is finishing
previous transfer or is also in reset state and request pin is not
driven by anyone. In that case, it floats leading to unexpected gpio
interrupts. Updated driver to support handling those cases.
Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

drivers: serial: lpuart: Fix handling of unstable transmitter

---

samples/bluetooth/mesh/chat/README.rst
samples/bluetooth/mesh/light_ctrl/README.rst

Changed model to be configured and prolonged value in light control
model. Changed description about help command in chat model.
Signed-off-by: David Dilner <david.dilner@nordicsemi.no>

Bluetooth: Mesh: Fixing errors in Mesh Sample Documation

---

applications/asset_tracker_v2/README.rst

Doc fixes for asset tracker v2

doc: Doc fixes for asset tracker v2

---

include/net/fota_download.rst

Small FOTA doc update for jira NCSDK 8256

doc: update for NCSDK_8256

---

doc/nrf/releases/release-notes-latest.rst

Mention HomeKit addition in the Highlights section
of the release notes.
Signed-off-by: Mariusz Poslinski <mariusz.poslinski@nordicsemi.no>

doc: update release with HomeKit info

---

west.yml

west.yml: Bring in sample.yml fixes in sdk-zephyr

---

subsys/net/lib/aws_fota/src/aws_fota.c

When a device receives multiple notify-next messages, only
the first should be acted upon. The subsequent notify-next messages
are not processed by the library, but the payload must still be
read out so that the MQTT library can correctly receive the
next incoming messages. The message should still be marked as
an AWS FOTA message to avoid it being forwarded to the application.
This is done by returning 0 from the AWS FOTA event handler.
This patch fixes an issue where duplicate  job messages were not
marked as AWS FOTA messages and makes sure that payload is read out
for these messages.
Fixes NCSDK-8251

net: lib: aws_fota: Clear MQTT buffer when message is dropped

---

doc/nrf/known_issues.rst

doc: Update known issues for 150 release

---

doc/nrf/shortcuts.txt
doc/nrf/ug_chip.rst
samples/connectedhomeip/light_bulb/README.rst
samples/connectedhomeip/light_switch/README.rst
samples/connectedhomeip/lock/README.rst

Fixed NCSIDB-394 issue by adding a note about GN.

doc: chip: add GN required note

---

doc/nrf/known_issues.rst

Add info about not working Zigbee Shell component with development version of ZBOSS libs
Signed-off-by: Jan Gałda <jan.galda@nordicsemi.no>

Zigbee: Add known issue in Zigbee Shell

---

doc/nrf/known_issues.rst

Change adds description of HID configurator issue under Linux.
Jira: NCSDK-8304

doc: known_issues: Add HID configurator issue on Linux

---

doc/nrf/known_issues.rst

-Adding known issues for
ref: NCSDK-7857
ref: NCSDK-7914
ref: NCSDK-8075

doc: Updating known crypto issues for nRF Connect SDK v1.5.0

---

west.yml

https://github.com/nrfconnect/sdk-zephyr/pull/473

Manifest: update sdk-zephyr rev

---

west.yml

Signed-off-by: Piotr Pryga <piotr.pryga@nordicsemi.no>

west.yml: update sdk-zephyr to add connectionless Direction Finding

---

applications/asset_tracker/src/cloud_codec/cloud_codec.c
applications/asset_tracker/src/cloud_codec/cloud_codec.h
applications/asset_tracker/src/gps_controller/gps_controller.c
applications/asset_tracker/src/main.c
doc/nrf/releases/release-notes-latest.rst
include/drivers/gps.h
include/net/nrf_cloud_agps.h
lib/agps/Kconfig
lib/agps/agps.c
lib/modem_info/modem_info.c
subsys/net/lib/nrf_cloud/Kconfig
subsys/net/lib/nrf_cloud/src/nrf_cloud_agps.c

Add cell-based location and single-cell only to AGPS libraries

---

doc/nrf/libraries/caf/buttons.rst

Fix minor CAF doc issues.

---

applications/asset_tracker/src/main.c

applications: asset_tracker: Add missing break statement

---

subsys/bluetooth/mesh/lightness_srv.c

The minor improvements for debug logging to show signed values with the sign. Additionally, status is logged according to the requested representation.

Bluetooth: Mesh: Improve debug logging in Light Lightness

---

subsys/net/lib/nrf_cloud/src/nrf_cloud_fota.c

Use the correct function to free memory in cJSON items.
Fixes memory leak in nrf_cloud_fota.
CIA-213

net: lib: nrf_cloud: Correctly delete cJSON items

---

applications/machine_learning/configuration/nrf52840dk_nrf52840/buttons_def.h
applications/machine_learning/src/main.c
applications/machine_learning/src/modules/ei_data_forwarder.c
applications/machine_learning/src/modules/ml_runner.c

Change updates CAF includes to fix build issues.

applications: machine_learning: Update CAF includes

---

samples/openthread/cli/harness/nRF_Connect_SDK.py

Add DUA and Multicast support for non-BBR devices to the THCI file.
KRKNWK-9139

samples: openthread: add DUA and MATN support to THCI file

---

subsys/net/lib/nrf_cloud/src/nrf_cloud_fota.c

Even if the job will be skipped, read the MQTT payload to prevent
memory issues.
IRIS-2729

net: lib: nrf_cloud: always read MQTT payload for FOTA topics

---

tests/subsys/spm/secure_services/src/main.c

Changed asserts to look for the actual error values.
Skip spm_request_random_number if RNG service is not enabled.
Added test cases to spm_request_read.
Signed-off-by: Andreas Vibeto <andreas.vibeto@nordicsemi.no>

secure services: tests: various fixes to secure services tests

---

applications/serial_lte_modem/src/slm_at_tcp_proxy.c
applications/serial_lte_modem/src/slm_at_udp_proxy.c

Socket send() could detect error scenario like ENETDOWN (115).
Improve the handling of send() failure like below:
[Command mode]
.TCP server: terminate current client and accept new connection;
.TCP client: close connection and socket;
.UDP server: close socket;
.UDP client: close socket
[Datamode]
.quit data mode then do the same as above;
UDP data URC changed from #UDPRECV to #UDPDATA to align with TCP.

applications: serial_lte_modem: Improve handling of send errors

---

Jenkinsfile
tests/subsys/dfu/dfu_target_mcuboot/testcase.yaml
west.yml

Add support for front-end module to the softdevice controller,
using mpsl_fem.

[v1.5-branch] manifest: Update softdevice controller and mpsl

---

doc/nrf/gs_programming.rst
samples/bluetooth/peripheral_hids_keyboard/README.rst
samples/bluetooth/peripheral_uart/README.rst

Fixes as requested in NCSDK-8422

doc: general fixes to BLE samples

---

include/caf/events/module_state_event.h

Avoid compilation warnings and compliance check issues.

caf: Avoid compilation warnings.

---

subsys/net/lib/download_client/src/download_client.c
subsys/net/lib/download_client/src/parse.c

A couple of fixes for coverity issues.

net: lib: download_client: coverity fixes

---

applications/serial_lte_modem/doc/FTP_AT_commands.rst
applications/serial_lte_modem/src/ftp_c/slm_at_ftp.c
applications/serial_lte_modem/src/ftp_c/slm_at_ftp.h
applications/serial_lte_modem/src/slm_at_host.c
applications/serial_lte_modem/src/slm_at_host.h
applications/serial_lte_modem/src/slm_at_tcp_proxy.c
applications/serial_lte_modem/src/slm_at_tcp_proxy.h
applications/serial_lte_modem/src/slm_at_udp_proxy.c
applications/serial_lte_modem/src/slm_at_udp_proxy.h
doc/nrf/releases/release-notes-latest.rst
include/net/ftp_client.h
subsys/net/lib/ftp_client/src/ftp_client.c
subsys/net/lib/ftp_client/src/ftp_commands.h

Add new FTP command "uput"(unique) and "mput"(append).
Add data mode support to FTP "put", "uput" and "mput".
Add "verbose" command to turn on|off FTP control message.
Send URC for socket errors returned from ft_client lib.
Check JIRA ticket for more details.
JIRA Reference: NCSIDB-389
This PR contains 3 commits.

applications: serial_lte_modem: FTP features request

---

subsys/net/lib/fota_download/src/fota_download.c

net: lib: fota_download: Add missing log_strdup

---

applications/serial_lte_modem/src/gps/slm_at_gps.c
applications/serial_lte_modem/src/http_c/slm_at_httpc.c
applications/serial_lte_modem/src/main.c
applications/serial_lte_modem/src/mqtt_c/slm_at_mqtt.c
applications/serial_lte_modem/src/slm_at_cmng.c
applications/serial_lte_modem/src/slm_at_commands.c
applications/serial_lte_modem/src/slm_at_fota.c
applications/serial_lte_modem/src/slm_at_host.c
applications/serial_lte_modem/src/slm_at_icmp.c
applications/serial_lte_modem/src/slm_at_tcp_proxy.c
applications/serial_lte_modem/src/slm_at_tcpip.c
applications/serial_lte_modem/src/slm_at_udp_proxy.c
applications/serial_lte_modem/src/slm_util.c
applications/serial_lte_modem/src/slm_util.h

Handled filter impact level Medium issues.
Plus some level Low issues.

applications: serial_lte_modem: Static code analysis handling

---

include/dfu/pcd.rst

Flesh to flash and other minor fixes.

doc: typo fix in PCD library doc

---

subsys/net/lib/download_client/src/http.c

Detect and log 404 errors more specifically.
Jira: NCSDK-8639
Signed-off-by: Peter Skeggs <peter.skeggs@nordicsemi.no>

net: lib: download_client: Improve error logging

---

doc/nrf/ug_thread_tools.rst

It fixes commands descriptions for wpantund and pyspinel.

doc: Fix commands for Thread tools

---

applications/nrf_desktop/README.rst
applications/nrf_desktop/doc/ble_bond.rst
applications/nrf_desktop/doc/ble_conn_params.rst
applications/nrf_desktop/doc/ble_latency.rst
applications/nrf_desktop/doc/power_manager.rst
applications/serial_lte_modem/doc/slm_description.rst
applications/serial_lte_modem/doc/slm_testing.rst
doc/nrf/known_issues.rst
doc/nrf/ug_thingy91.rst
include/supl_os_client.rst
samples/bluetooth/peripheral_nfc_pairing/README.rst
samples/nrf9160/coap_client/README.rst

Updated terminology for consistency with "timeout".
"Time-out" and "bugfix" are not allowed.

doc: style: terminology update

---

lib/date_time/date_time.c

getaddrinfo() allocates memory dynamically to return results.
This patch copies needed data from results to internal module
memory and frees memory allocated by getaddrinfo() to allow
other modules in the system resolve addresses.

lib: date_time: free getaddrinfo dynamically allocated memory

---

doc/nrf/gs_programming.rst
samples/bluetooth/hci_lpuart/README.rst
samples/nrf9160/lte_ble_gateway/README.rst

Added SW10 as it replaces SW5 in newer hardware.

doc: Add SW10

---

subsys/bluetooth/mesh/scene_srv.c

When the data was stored in pages the counter that kept the number
of pages stored was not updated correctly, so when a scene was deleted
there was pages left that was not deleted from the file system.

Bluetooth: Mesh: Fixed delete scene pages.

---

lib/lte_link_control/lte_lc.c

Notifications for CEREG and CSCON unsolicited response codes need
to be enabled before the modem is set in normal fnctional mode.
Currently, the notifications are only enabled when lte_lc_init APIs
are called, so a sequence of normal --> minimal --> normal will leave
the notifications disabled.
This patch fixes this issue by enabling notifications every time
normal mode configured.
Addresses CIA-272

lib: lte_lc: Enable notifications separately

---

drivers/serial/uart_nrf_sw_lpuart.c

Introduced two additional RX states:
- RX_PREPARE - state when transfer was requested and driver is preparing.
When preparation includes starting HF clock this state is not instant.
- RX_BLOCKED - state when packet was finished and new buffer was requested.
Previously, it was covered by RX_TO_IDLE state but it must be distinguished
to support cases when buffer is not provided instantly.
Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

drivers: serial: nrf_sw_lpuart: Fix RX path state machine

---

doc/nrf/links.txt
doc/nrf/ug_bt_mesh_overview.rst
include/bluetooth/mesh.rst

NCSDK-8447:
Changed from experimental to support for dev.
Added reference to user guide for overview.
Added reference to samples.
Added reference to configuration of mesh in NCS.

doc: Mesh profile page update

---

samples/tfm/tfm_hello_world/sample.yaml

So it can be run with twister.

tfm_hello_world: Fix sample.yaml regex

---

doc/nrf/known_issues.rst

This adds the issue with bt_shell_nus as known issue.

known_issues: Add issue NCSDK-8321 with the shell_bt_nus sample

---

applications/serial_lte_modem/doc/HTTPC_AT_commands.rst
applications/serial_lte_modem/src/http_c/slm_at_httpc.c
applications/serial_lte_modem/src/slm_at_commands.c

This PR improves HTTPC service with below 2 commits:
1. applications: serial_lte_modem: integrate HTTPC to SLM data mode
2. applications: serial_lte_modem: fix infinite loop with no exit

applications: serial_lte_modem: improve HTTPC service

---

applications/asset_tracker_v2/src/modules/data_module.c

Only distribute configuration updates to other modules if there has been
a change to the current configuration. This is to avoid unnessecary
config updates.
Closes CIA-279

applications: asset_tracker_v2: Distribute device config on change.

---

doc/nrf/links.txt
doc/nrf/ug_nrf9160.rst

Updated ug_nrf9160.rst to mention FOTA samples.
Added small doc fixes.

doc: NCSDK8489 9160 userguide fota samples upd

---

west.yml

sdk-nrfxlib with updated ZBOSS production libraries.

manifest: Update sdk-nrfxlib

---

.github/workflows/manifest.yml

Manifest action update

---

doc/static/css/zephyr.css
doc/zephyr/conf.py
scripts/requirements-doc.txt

This PR updates the `sphinx_ncs_theme` so that some new tweaks are included in all docsets. Other fixes and tweaks have been added.

doc: some tweaks and fixes

---

scripts/requirements-doc.txt

Update to version 0.6.2. It includes some CSS tweaks inherited from
Zephyr.

scripts: requirements: update sphinx_ncs_theme

---

.github/workflows/manifest.yml

This version adds support for diffs and also is able to handle projects
added or removed.

actions: Update manifest action to 1.1.0

---

subsys/caf/modules/ble_state.c

Change adds broadcasting initial connection parameters. This information may be useful for some modules.
Jira: NCSDK-8937

caf: ble_state: Broadcast initial connection parameters

---

west.yml

This update contains several bug fixes,
check MPSL's and SoftDevice Controller's changelogs
Signed-off-by: Konstantinos Sotiropoulos <koso@nordicsemi.no>

manifest: Update SoftDevice Controller and MPSL

---

applications/machine_learning/configuration/nrf52840dk_nrf52840/sensor_sampler_def.h

Change increases sampling frequency for simulated acceleration to improve quality of machine learning's predictions.
Jira: NCSDK-8942

applications: machine_learning: Increase sampling frequency on DK

---

doc/nrf/known_issues.rst

Document known bluetooth issues:
- Reording of GATT notifications and write without responses
- Incomplete bond overwrite when re-pairing with a new IRK.

Known Issues: Add known bluetooth issues

---

west.yml

This update contains several bug fixes for Zephyr Bluetooth.

[v1.5-branch]: manifest: Update zephyr revision 

---

doc/nrf/gs_installing.rst

Added additional info needed for installing the GN tool.

doc: chip: update GN installation steps

---

subsys/mpsl/Kconfig.fem
subsys/mpsl/mpsl_init.c

This PR several minor bugs in MPSL FEM.

Fix minor (D)PPI issues in MPSL/FEM

---

west.yml

manifest: Update hal nordic repo

---

doc/nrf/known_issues.rst
west.yml

Includes bug fixes:
- Corrupted advertising data when support for advertising extensions is enabled.
Signed-off-by: Jonathan Rico <jonathan.rico@nordicsemi.no>

manifest: Update Softdevice controller & MPSL

---

applications/asset_tracker/README.rst
doc/nrf/links.txt
include/net/nrf_cloud.rst

Add how to use nrf cloud FOTA to the documentation.

net: lib: nrf_cloud: Add FOTA documentation

---

.github/workflows/docbuild.yml
doc/nrf/gs_recommended_versions.rst
doc/nrf/versions.txt.in
west.yml

Fix documentation build issues by importing fixes added to Zephyr as well as some CI adjustments. Changes mainly backported from master.

doc: fix documentation build problems

---

doc/nrf/known_issues.rst
doc/nrf/links.txt

doc: Update known issues for 1.5.1

---

applications/machine_learning/src/modules/ml_runner.c

Subscribing for ml_result_event in ml_runner leaves only two subscription priorities for other application modules. Change removes the subscription to let other application modules use early subscription for the event.
Jira: NCSDK-9060

applications: machine_learning: Update ml_runner synchronization

---

include/caf/events/module_state_event.h

This commit moves all the module identifiers into a specified section
and adds a possibility to iterate them and get its zero-based index.
Signed-off-by: Radoslaw Koppel <radoslaw.koppel@nordicsemi.no>

caf: events: module_state_event: Add a functionality to get module index

---

doc/nrf/gs_installing.rst

Add mentions of tools that need to be added to PATH.

doc: gs: add tool examples for PATH

---

west.yml

Update manifest for sdk-zephyr

manifest: update sdk-zephyr

---

doc/nrf/ug_zigbee.rst
doc/nrf/ug_zigbee_other_ecosystems.rst

Added a new user guide for Zigbee.

doc: add zigbee ecosystem compatibility guide

---

applications/machine_learning/configuration/thingy52_nrf52832/app_ZDebug.conf

Change updates ML model used for Thingy52. The new model is trained on acceleration data coming from HW accelerometer.
Jira: NCSDK-8943

applications: machine_learning: Update ML model on Thingy52

---

lib/at_cmd/at_cmd.c

Encountered an assert caused by at_cmd_socket_thread being created twice.
Signed-off-by: Håvard Vermeer <havard.vermeer@nordicsemi.no>

lib: at_cmd: init guard

---

doc/nrf/links.txt
doc/nrf/ug_logging.rst
doc/nrf/ug_thread.rst
doc/nrf/ug_thread_architectures.rst
doc/nrf/ug_thread_certification.rst
doc/nrf/ug_thread_commissioning.rst
doc/nrf/ug_thread_configuring.rst
doc/nrf/ug_thread_ot_integration.rst
doc/nrf/ug_thread_ot_memory.rst
doc/nrf/ug_thread_overview.rst
doc/nrf/ug_thread_supported_features.rst
doc/nrf/ug_thread_tools.rst
doc/nrf/ug_thread_vendor_hooks.rst
samples/openthread/cli/README.rst
samples/openthread/coap_client/README.rst
samples/openthread/coprocessor/README.rst

General clean-up of the Thread documentation with style fixes
and clarifications.

doc: thread: documentation fixes

---

doc/mcuboot/conf.py
doc/utils/utils.py

- Make intersphinx optional in all docsets
- Explicitly check for inventory existence

doc: intersphinx handling enhancements

---

west.yml

[KRKNWK-9861]:
add commits from branch v1.5 to master
Signed-off-by: Robert Gałat <robert.galat@nordicsemi.no>

manifest: sync HomeKit master with v1.5.1

---

doc/nrf/links.txt
doc/nrf/ug_thread_tools.rst

Cleaning up the tools section to be more consistent, instead of
having links for some tools and sections for others.
Ref. KRKNWK-9840

doc: thread: clean up tools section

---

CODEOWNERS
west.yml

Updates MPSL code owner from @hurricaneFromMoscow  to @carlopaparo.

Update mpsl codeowner

---

doc/nrf/releases/release-notes-latest.rst

Added notes on changes in flash driver, FS, stream_flash.
Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

doc: release-notes-latest: changes in FS and stream_flash from upmerge 20210305

---

doc/nrf/links.txt

Fixed the link order based on guidelines.

doc: ensure consistency in links.txt

---

doc/nrf/known_issues.rst

Add known issue and workaround for the ECC thread stack overflow issue.

known_issue: Document ECC stack overflow issue

---

lib/at_host/at_host.c

Synchronizes filling of at_buf by a separate variable rather than using
k_work_pending.
Fixes NCSDK-9052.

lib: at_host: Change at_buf synchronization

---

applications/asset_tracker_v2/README.rst
doc/nrf/links.txt

Fix link in Asset Tracker v2 documentation

doc: Fix link in Asset Tracker v2 documentation

---

.github/labeler.yml

This is the PR setup commit to collect glob strings

PR to collect glob strings

---

doc/nrf/dm_managing_code.rst
doc/nrf/getting_started.rst
doc/nrf/gs_installing.rst
doc/nrf/gs_recommended_versions.rst
doc/nrf/gs_updating.rst

Split Updating section from Installing page.

doc: gs: add updating page

---

applications/machine_learning/configuration/nrf52840dk_nrf52840/led_state_def.h
applications/machine_learning/src/events/CMakeLists.txt
applications/machine_learning/src/events/Kconfig
applications/machine_learning/src/events/ei_data_forwarder_event.c
applications/machine_learning/src/events/ei_data_forwarder_event.h
applications/machine_learning/src/modules/Kconfig.ei_data_forwarder
applications/machine_learning/src/modules/ei_data_forwarder_bt_nus.c
applications/machine_learning/src/modules/ei_data_forwarder_uart.c
applications/machine_learning/src/modules/led_state.c

Change introduces displaying state of EI data forwarder.

applications: machine_learning: Add displaying state of EI data forwarder

---

samples/zigbee/light_bulb/sample.yaml
samples/zigbee/light_switch/sample.yaml
samples/zigbee/ncp/sample.yaml
samples/zigbee/network_coordinator/sample.yaml

Add integration entries to Zigbee samples.
These changes are required to build samples on Pull Request
Signed-off-by: Jan Gałda <jan.galda@nordicsemi.no>

Zigbee: Add integration platforms to Zigbee samples

---

.github/labeler.yml
.github/workflows/labeler.yml

Bump labeler to v3, exclude rst file changes.
Marked DNM so we can do some testing before merging.

Labeler v3

---

.github/labeler.yml

Let's see if this thing works now

labeler: Remove all exclusion lines

---

include/caf/sensor_sampler.h
subsys/caf/modules/sensor_sampler.c

CAF sensor trigger implementation.
Jira: NCSDK-8613

caf: sensor trigger

---

samples/nrf5340/netboot/README.rst
subsys/pcd/Kconfig

Updating docs for the netcore bootloader nRF5340 sample.

doc: Netboot 5340 doc update

---

samples/bluetooth/mesh/light_switch/README.rst

NCSDK-5447:
Add more description about the sample to readme file

doc: Expand light switch sample overview doc

---

doc/nrf/glossary.rst

A few things I didn't make it in time to review.

doc: glossary: DT/west updates

---

samples/nrf9160/azure_iot_hub/sample.yaml

Add integration platforms to sample.yaml. See PR #4444.

samples: nrf9160: azure_iot_hub: Add integration platforms

---

west.yml

manifest: update HomeKit revision

---

include/bluetooth/mesh/light_ctrl_srv.h
include/bluetooth/mesh/scheduler_srv.h
samples/bluetooth/mesh/chat/src/model_handler.c
samples/bluetooth/mesh/light/src/model_handler.c
samples/bluetooth/mesh/light_ctrl/src/model_handler.c
samples/bluetooth/mesh/light_switch/src/model_handler.c
samples/bluetooth/mesh/sensor_client/README.rst
samples/bluetooth/mesh/sensor_client/src/model_handler.c
samples/bluetooth/mesh/sensor_server/src/model_handler.c
subsys/bluetooth/mesh/dk_prov.c
subsys/bluetooth/mesh/light_ctrl_srv.c
subsys/bluetooth/mesh/scheduler_srv.c
tests/bluetooth/tester/src/model_handler.c

Convert all Bluetooth Mesh usage of the deprecated k_work API.

Bluetooth: Mesh: Convert k_work usage

---

samples/bluetooth/direct_test_mode/Kconfig
samples/bluetooth/direct_test_mode/src/dtm.c
samples/bluetooth/direct_test_mode/src/dtm.h
samples/bluetooth/direct_test_mode/src/main.c

This PR provides the interrupt driven DTM sample

samples: bluetooth: Interrupt driven DTM sample

---

samples/tfm/tfm_hello_world/sample.yaml

samples: tfm_hello_world: Add integration_platforms to sample.yaml

---

doc/nrf/releases/release-notes-latest.rst
drivers/sensor/sensor_sim/sensor_sim.c

Along with a related driver update.

Upmerge 21 04 2021 kernel docs

---

samples/openthread/cli/sample.yaml
samples/openthread/coap_client/sample.yaml
samples/openthread/coap_server/sample.yaml
samples/openthread/coprocessor/sample.yaml

samples: openthread: Add integration_platforms to sample.yaml

---

west.yml

This commit brings in latest changes in the IEEE 802.15.4 component.
Signed-off-by: Jedrzej Ciupis <jedrzej.ciupis@nordicsemi.no>

manifest: Update the IEEE 802.15.4 subsystem

---

west.yml

Add board files to zephyr repo.

manifest: Thingy53 board files

---

samples/edge_impulse/data_forwarder/sample.yaml
samples/event_manager/sample.yaml
samples/profiler/sample.yaml
subsys/profiler/profiler_nordic.c
tests/subsys/event_manager/prj.conf
tests/subsys/event_manager/src/events/data_event.c
tests/subsys/event_manager/src/events/multicontext_event.c
tests/subsys/event_manager/src/events/order_event.c
tests/subsys/event_manager/src/events/test_events.c
tests/subsys/event_manager/testcase.yaml

Change updates sample.yaml files for:
- Event Manager sample
- Profiler sample
- EI data forwarder sample
- Event Manager test
See #4444 for details.
Jira: NCSDK-9292

tree-wide: Update sample.yaml

---

applications/connectivity_bridge/src/modules/power_handler.c

Replace all existing deprecated API with the recommended alternative.
Signed-off-by: Audun Korneliussen <audun.korneliussen@nordicsemi.no>

applications: connectivity_bridge: conversion of k_work API

---

samples/connectedhomeip/light_bulb/sample.yaml
samples/connectedhomeip/light_switch/sample.yaml
samples/connectedhomeip/lock/sample.yaml

samples: connectedhomeip: add integration_platforms to sample.yaml

---

samples/nrf9160/agps/sample.yaml
samples/nrf9160/at_host/sample.yaml
samples/nrf9160/aws_fota/sample.yaml
samples/nrf9160/aws_iot/sample.yaml
samples/nrf9160/azure_fota/sample.yaml
samples/nrf9160/cloud_client/sample.yaml
samples/nrf9160/coap_client/sample.yaml
samples/nrf9160/download/sample.yaml
samples/nrf9160/fmfu_smp_svr/sample.yaml
samples/nrf9160/gps/sample.yaml
samples/nrf9160/https_client/sample.yaml
samples/nrf9160/lte_ble_gateway/sample.yaml
samples/nrf9160/lwm2m_carrier/sample.yaml
samples/nrf9160/lwm2m_client/sample.yaml
samples/nrf9160/mqtt_simple/sample.yaml
samples/nrf9160/pdn/sample.yaml
samples/nrf9160/secure_services/sample.yaml
samples/nrf9160/sms/sample.yaml
samples/nrf9160/udp/sample.yaml

Add integration_platforms filed to the sample.yaml file in all nRF9160
samples.

samples: nrf9160: Add integration_platforms to sample.yaml

---

subsys/net/lib/azure_iot_hub/src/azure_iot_hub_dps.c

Convert the delayed work usage to adhere to the new API, as
the old one will soon be deprecated.

net: lib: azure_iot_hub: Convert delayed work usage to new API

---

samples/bootloader/sample.yaml
samples/nrf5340/netboot/sample.yaml
samples/spm/sample.yaml

See #4444 
Add information about integration platforms for these samples.

samples: bootloader: spm: add integration platforms

---

west.yml

manifest: Update revision of the homekit project

---

lib/dk_buttons_and_leds/dk_buttons_and_leds.c

Update to new k_work API
Jira: NCSDK-9411

lib: dk_buttons_and_leds: use new k_work API

---

applications/pelion_client/configuration/nrf5340dk_nrf5340_cpuapp/dts.overlay
applications/pelion_client/configuration/nrf5340dk_nrf5340_cpuappns/app_ZDebug.conf
applications/pelion_client/configuration/nrf5340dk_nrf5340_cpuappns/dts.overlay
applications/pelion_client/configuration/nrf9160dk_nrf9160ns/app_ZDebug.conf
applications/pelion_client/configuration/nrf9160dk_nrf9160ns@1.0.0/app_ZDebug.conf

Fix hardfault on spm vs app config mismatch.
Fix dts overlay conflict.

applications: pelion_client: config fixes

---

doc/nrf/shortcuts.txt
doc/nrf/ug_zigbee.rst
doc/nrf/ug_zigbee_configuring_libraries.rst
doc/nrf/ug_zigbee_supported_features.rst

Updated cross-links related to stack configuration.

doc: zigbee: update links

---

doc/nrf/known_issues.rst

* DRGN-15251: Very rare assertion fault when peripheral on Coded PHY 
* DRGN-15310: HCI Read RSSI fails

known_issues: Add some more known issues

---

applications/machine_learning/src/modules/sensor_sim_ctrl.c

applications: machine_learning: Switch to new workqueue API

---

include/caf/events/sensor_event.h
subsys/caf/modules/sensor_sampler.c

Change fixes build and initialization issues.
Jira: NCSDK-9590

caf: sensor_sampler: Fix build and initialization

---

west.yml

Updated the Find My revision that contains improvements for
the Key Management module.

manifest: update Find My revision

---

applications/nrf_desktop/sample.yaml

applications: nrf_desktop: Update sample.yaml

---

doc/nrf/releases/release-notes-latest.rst

Add bluetooth release notes for the past 2 upmerges.

doc: release-notes: Add bluetooth release notes for upmerges

---

subsys/caf/modules/ble_adv.c
subsys/caf/modules/buttons.c
subsys/caf/modules/click_detector.c
subsys/caf/modules/leds.c

Jira: NCSDK-9418
Signed-off-by: Marek Pieta <Marek.Pieta@nordicsemi.no>

caf: modules: Switch to new workqueue API

---

west.yml

manifest: update homekit revisioin

---

applications/pelion_client/src/modules/power_manager.c

Change fixes keep_alive event subscription.

applications: pelion_client: Fix keep_alive event subscription

---

doc/_extensions/external_content.py

In some workflows considering modification times may not be enough to
provide proper incremental building experience. For example, switching
branches back and forth but not performing incremental builds on every
switch.

doc: extensions: external_content: diff before copying

---

applications/nrf_desktop/src/hw_interface/battery_charger.c
applications/nrf_desktop/src/hw_interface/battery_meas.c
applications/nrf_desktop/src/hw_interface/buttons_sim.c
applications/nrf_desktop/src/hw_interface/leds.c
applications/nrf_desktop/src/hw_interface/selector_hw.c
applications/nrf_desktop/src/hw_interface/wheel.c
applications/nrf_desktop/src/modules/ble_bond.c
applications/nrf_desktop/src/modules/ble_conn_params.c
applications/nrf_desktop/src/modules/ble_latency.c
applications/nrf_desktop/src/modules/ble_scan.c
applications/nrf_desktop/src/modules/cpu_meas.c
applications/nrf_desktop/src/modules/dfu.c
applications/nrf_desktop/src/modules/hid_forward.c
applications/nrf_desktop/src/modules/hids.c
applications/nrf_desktop/src/modules/power_manager.c
applications/nrf_desktop/src/modules/profiler_sync.c
applications/nrf_desktop/src/modules/watchdog.c
applications/nrf_desktop/src/util/config_channel_transport.c
applications/nrf_desktop/src/util/config_channel_transport.h

applications: nrf_desktop: Switch to new workqueue API

---

doc/nrf/links.txt
doc/nrf/ug_thingy91.rst

Add link to nRF Connect Trace Collector in
Thingy user guide

doc: Add link to nRF Connect Trace Collector

---

tests/subsys/event_manager/src/events/multicontext_event.h
tests/subsys/event_manager/src/main.c
tests/subsys/event_manager/src/modules/test_basic.c
tests/subsys/event_manager/src/modules/test_data.c
tests/subsys/event_manager/src/modules/test_multicontext.c
tests/subsys/event_manager/src/modules/test_multicontext_handler.c
tests/subsys/event_manager/src/modules/test_oom.c
tests/subsys/event_manager/src/modules/test_subs.c

Change fixes issues reported by coverity.
Jira: NCSDK-9741

tests: event_manager: Fix coverity issues

---

applications/nrf_desktop/src/modules/watchdog.c

Change fixes false negatives in error code checking.

applications: nrf_desktop: Fix watchdog initialization

---

subsys/bluetooth/mesh/sensor_types.c
tests/subsys/bluetooth/mesh/sensor_subsys/CMakeLists.txt
tests/subsys/bluetooth/mesh/sensor_subsys/prj.conf
tests/subsys/bluetooth/mesh/sensor_subsys/sensor_types.ld
tests/subsys/bluetooth/mesh/sensor_subsys/src/main.c
tests/subsys/bluetooth/mesh/sensor_subsys/testcase.yaml

Motion sensor property unit test.

Bluetooth: Mesh: Test sensor subsystem

---

applications/asset_tracker/README.rst
doc/nrf/doc_styleguide.rst
doc/nrf/gs_installing.rst
doc/nrf/gs_modifying.rst
doc/nrf/gs_programming.rst
doc/nrf/ug_nrf5340.rst
doc/nrf/ug_thingy91.rst
include/net/aws_iot.rst
samples/bluetooth/central_bas/README.rst
samples/bluetooth/peripheral_ancs_client/README.rst
samples/bluetooth/peripheral_cts_client/README.rst
samples/bootloader/README.rst
samples/debug/ppi_trace/README.rst
samples/nrf9160/aws_fota/README.rst
samples/nrf9160/http_update/application_update/README.rst
scripts/shell/ble_console/README.rst

JIRA NCSDK-9709.
Unified all documentation so that GUI element sequences use
the same symbols.
Signed-off-by: Wille Backman <wille.backman@nordicsemi.no>

doc: unifying GUI element sequences

---

doc/nrf/links.txt
doc/nrf/ug_zigbee_configuring.rst
doc/nrf/ug_zigbee_supported_features.rst
samples/zigbee/light_bulb/README.rst
samples/zigbee/light_switch/README.rst
samples/zigbee/ncp/README.rst
samples/zigbee/network_coordinator/README.rst

Added direct links to ZBOSS API.

doc: zigbee: add links to ZBOSS API

---

subsys/bluetooth/mesh/sensor_types.c
tests/subsys/bluetooth/mesh/sensor_subsys/src/main.c

Unit tests of supported occupancy sensors:
motion,
motion threshold,
people count,
presence detected,
time since motion sensed,
time since presence detected

Bluetooth: Mesh: Occupancy sensors test

---

tests/bluetooth/tester/src/mmdl.c

Address a range of coverity issues in the mmdl.c Bluetooth Mesh model
qualification tests.

Bluetooth: Tester: MMDL: Fix coverity issues

---

applications/pelion_client/src/modules/oma_stopwatch.cpp

This commit adds functionality to recover from situation where
no value_updated notification is received.
After specified tries the pending flag is forced to be cleared.

applications: pelion_client: Implement stopwatch update timeout

---

applications/serial_lte_modem/src/mqtt_c/slm_at_mqtt.c

Add log_strdup() to string type logging.
Correct URC format.
Other cosmetic code format changes.

applications: serial_lte_modem: MQTT code format
