west.yml
Pull update to WDT driver to use it without IRQs.
=> manifest: sdk-zephyr: wdt without irq

drivers/wifi/nrf700x/src/qspi/src/qspi_if.c
cherry-pick fixes from QSPI-NOR driver.
@anangl FYI.
=> wifi: Fix QSPI clock divider usage

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
The new APIs will simplify debugging issues.
The APIs are used in samples and audio app, see
https://github.com/nrfconnect/sdk-nrf/pull/16729
and
https://github.com/nrfconnect/sdk-nrf/pull/16733
=> doc: Add changelog entry for BT APIs converting err to string

applications/serial_lte_modem/doc/slm_description.rst, doc/nrf/protocols/wifi/stack_configuration.rst, doc/nrf/releases_and_maturity/migration/migration_sysbuild.rst, samples/bluetooth/direction_finding_central/README.rst, samples/bluetooth/direction_finding_connectionless_tx/README.rst, samples/bluetooth/mesh/light/README.rst, samples/bluetooth/mesh/light_ctrl/README.rst, samples/bluetooth/mesh/light_switch/README.rst, samples/bluetooth/peripheral_uart/README.rst, samples/cellular/lwm2m_carrier/sample_description.rst, samples/zigbee/light_switch/README.rst, samples/zigbee/ncp/README.rst, scripts/partition_manager/partition_manager.rst
Changed the link pointing incorrectly to Zephyr's build system vars so that it points to the nRF Connect SDK's build system overview. Aligned formatting of EXTRA_CONF_FILE and _FILE variables (:makevar:). NCSDK-27178.
=> doc: cmake: change ref link to build system

subsys/bluetooth/controller/bt_ctlr_used_resources.h
This channel isn't needed by the implementation.
=> bluetooth: controller: free DPPI channel 13

lib/lte_link_control/lte_lc_helpers.c, lib/lte_link_control/lte_lc_helpers.h, tests/lib/lte_lc/src/main.c
Remove internal function response_is_valid() which is used to check that AT handler functions receive correct notification. This has been dead code since at_monitor was introduced and we subscribe for specific AT notifications per function. It was also not used for all AT notifications.
Also cleaning up defines in lte_lc_helpers.h.
=> lib: lte_link_control: Remove AT notification prefix check

doc/nrf/app_dev/device_guides/wifi_coex.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, dts/bindings/radio_coex/generic-radio-coex-one-wire.yaml, dts/bindings/radio_coex/sdc-radio-coex-one-wire.yaml, subsys/mpsl/cx/1wire/mpsl_cx_1wire.c, subsys/mpsl/cx/CMakeLists.txt, subsys/mpsl/cx/Kconfig
This 1-wire coex variant is based on mpsl_cx_abstract_interface.h and follows the requirements/recommendations for the nrf9160 LTE modem.
=> mpsl: cx: Add a generic coex variant using a single GPIO

lib/lte_link_control/lte_lc_helpers.c, lib/lte_link_control/lte_lc_helpers.h, tests/lib/lte_lc/src/main.c
There are many NULL and other checks that we cannot get into especially in parse_*() functions. Those parameters are never NULL from the caller in lte_lc.c. Hence, they are converted into asserts.
Unit tests using internal lte_lc_helpers.c API's have been testing NULL values. These tests are now removed.
=> lib: lte_link_control: Make some dead branches into asserts

lib/lte_link_control/lte_lc_helpers.c, lib/modem_info/modem_info.c
Change `assert` to `__ASSERT_NO_MSG` after AT parser
initialization.
This is to make it optional via Kconfig option and to
reduce the memory footprint for this basic check.
=> lib: `assert` to `__ASSERT_NO_MSG`

subsys/net/lib/wifi_credentials/wifi_credentials_shell.c
Passphrase minimum length should be WIFI_PSK_MIN_LEN. Adding check for WPA3-SAE and other security modes.
=> lib: wifi_credentials: Add passphrase length check

west.yml
Change updates sdk-zephyr to bring in fix for assertion failure in nRF Desktop application.
Jira: NCSDK-28624
=> west: Update sdk-zephyr to fix CI tests of nRF Desktop

.editorconfig
Adding an editor config file to improve developer experience. Especially nice for editors that default to a tab-size of 4 instead of 8.
The file added in this commit is an exact copy of the one found in zephyr.
EditorConfig (https://editorconfig.org) is a widely supported configuration tool that helps to ensure better consistency amongst developers by auto-configuring an editor to match the original/intended style i.e. tab-width etc
Lots of editors support this natively and those that do not probably have a plugin or extension.
=> editorconfig: Add editorconfig file

west.yml
Add soft float fallback to enable building from libs with softfp ABI enabled.
=> manifest: nrfxlib: pull soft float fallback for OT lib path

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Updated naming of sections in the changelog after recent restructuring. NCSDK-22326.
=> doc: changelog: update section naming

subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c
Return ESHUTDOWN if the socket is closed during
a coap request.
=> net: lib: nrf_cloud_coap_transport: Update error handling

samples/suit/flash_companion/prj.conf, samples/suit/recovery/prj.conf, samples/suit/recovery/sysbuild/hci_ipc.conf
The recovery application, as well as flash companion does not need to generate UICRs, BICRs, as well as MPIs.
=> samples: suit: Remove unnecessary ICRs

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/mpsl/init/mpsl_init.c
The mpsl api shall not be used after mpsl is uninitialized.
MPSL requests the HFXO when doing LFRC calibration. However, when MPSL is uninitialized it does not handle the CLOCK DONE event and does not release the HFXO, leaving the HFXO running and consuming power.
---
There may be a nicer way to stop the work handler from running, but the zephyr plug api does not prevent the work item to resubmit itself, which is the case here.
=> mpsl: Stop calibration work on mpsl uninit

subsys/net/lib/mqtt_helper/mqtt_helper.c, tests/subsys/net/lib/mqtt_helper/src/mqtt_helper_test.c
If mqtt_live fails with an error other than -EAGAIN (for example -ENOTCONN), the poll loop exits.
connection_poll_sem is still held, and no attempt is made to abort the connection, so it is not possible for the loop to recover.
Instead, we call mqtt_abort on any occasion that we break out of the loop.
This means that a disconnect event occurs, allowing us to gracefully recover.
=> mqtt_helper: Prevent mqtt_helper_thread hang on mqtt_live fail

subsys/esb/esb.c
This PR adjusts the timer's compare value calculation to correctly account for different ramp-up times.
=> esb: Correct timer compare value configuration

lib/nrf_modem_lib/lte_net_if/lte_net_if.c, tests/lib/nrf_modem_lib/lte_net_if/src/main.c
Enable modem events when using Zephyr Connection Manager. When the events are enabled, a warning will be printed when the modem detects a reset loop.
=> lib: nrf_modem_lib: lte_net_if: Enable modem events

subsys/partition_manager/Kconfig
The workaround that we have for the hardware model v1 with TF-M seems to cause build issues with non TF-M devices because of the missing NRF_SPU_* Kconfigs. Set a default 0x0 to the non TF-M devices to avoid the build issue. This configuration is not used for non TF-M devices, so it doesn't have any negative sideffects.
=> partition_manager: HW model 1 fix for non TF-M socs

west.yml
Which clears the MPC events before we enable
the MPC interrupts for nRF54L15.
Ref: NCSDK-28128
=> manifest: Bring updated TF-M

subsys/nrf_security/src/drivers/cracen/common/include/cracen/lib_kmu.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_key_ids.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/lib_kmu.c
Adds the possibility to provision keys with the REVOKED policy.
=> cracen: KMU support for rpolicy=REVOKED

subsys/nrf_security/src/drivers/cracen/common/include/cracen/mem_helpers.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/mem_helpers.c
Fixes some double read inconsitiencies and key validation in Cracen key management implementation.
=> Cracen: Fix import/export/generate key implementations

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/mac.c
Fix the hmac block buffering such that it works for all input sizes.
=> nrf_security: cracen: Fix hmac block buffering calculation

subsys/suit/metadata/include/suit_metadata.h, subsys/suit/metadata/src/suit_metadata.c, subsys/suit/orchestrator/src/suit_orchestrator_sdfw.c, subsys/suit/storage/src/suit_storage_mpi.c, subsys/suit/storage/src/suit_storage_nrf54h20.c, subsys/suit/storage/src/suit_storage_test.c
Remove the false indication that the root manifest was processed. Log manifest class ID for each manifest that is booted.
=> suit: Log class IDs for manifests

subsys/nrf_security/src/drivers/cracen/sxsymcrypt/include/sxsymcrypt/internal.h, subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/aead.c, subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/blkcipher.c, subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/chachapoly.c
Remove the aes_countermeasures field as it is no longer needed.
=> nrf_security: cracen: Remove redundant aes_countermeasures field.

doc/_utils/redirects.py
Regrouped redirect tuples based on page hierarchy. Added comments with page names.
Updated notes in the description at the top of the file.
=> doc: redirects: regroup and add comments

doc/nrf/app_dev/config_and_build/building.rst, doc/nrf/app_dev/create_application.rst, doc/nrf/app_dev/device_guides/nrf53/building_nrf53.rst, doc/nrf/app_dev/device_guides/nrf91/nrf91_programming.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_custom_pcb.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_external_memory.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54l/nrf54l15_gs.rst, doc/nrf/dev_model_and_contributions/documentation/build.rst, doc/nrf/includes/vsc_build_and_run_series.txt, doc/nrf/installation/updating.rst, doc/nrf/protocols/matter/getting_started/adding_clusters.rst, doc/nrf/protocols/thread/tools.rst, doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/transition_guide_2.4.99-cs3_to_2.7_environment.rst, doc/nrf/releases_and_maturity/migration_guides.rst, doc/nrf/shortcuts.txt, samples/bluetooth/rpc_host/README.rst, samples/caf_sensor_manager/README.rst, samples/event_manager_proxy/README.rst, samples/matter/light_bulb/README.rst, samples/suit/smp_transfer/README.rst, samples/wifi/ble_coex/README.rst, samples/wifi/thread_coex/README.rst
Added cross-links to migration guides from Updating tools and repositories page. Added links to using toolchain environment from command line to different pages.
NCSDK-28530 and NCSDK-28568.
=> doc: links: migration and environment

subsys/nrf_security/configs/nrf-config.h.template, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c
Adds full ASN.1 parsing of RSA keys so we don't have to rely on external libraries.
=> cracen: Remove dependency on MbedTLS ASN.1

subsys/sdfw_services/services/psa_crypto/Kconfig
Increase the SSF buffer size of the crypto service to 128 bytes
=> crypto service: Increase SSF buffer size to 128 bytes

subsys/nrf_security/CMakeLists.txt
Enable MBEDTLS_PSA_CRYPTO_KEY_ID_ENCODES_OWNER when we build SECDOM with the PSA crypto service enabled.
=> nrf_security: Enable OWNER ID for SSF server build

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/wifi/provisioning/softap/prj.conf
Increase CONFIG_SOFTAP_WIFI_PROVISION_THREAD_STACK_SIZE to 8192 to avoid stack overflow usage fault.
Default was 4096.
=> samples: wifi: provisioning: softap: increase stack size

lib/lte_link_control/lte_lc_modem_hooks.c, tests/lib/lte_lc_api/CMakeLists.txt, tests/lib/lte_lc_api/src/lte_lc_api_test.c
Adding tests to cover on_modem_init, on_modem_shutdown and lte_lc_on_modem_cfun.
=> tests: lib: lte_lc_api: Add tests for modem hooks

modules/memfault-firmware-sdk/memfault_lte_metrics.c
Check functional mode before fetching modem parameters. Without this check, the modem info APIs will return an error when the modem is offline.
=> modules: memfault-firmware-sdk: Don't get modem params in offline mode

lib/lte_link_control/lte_lc.c, lib/lte_link_control/lte_lc_helpers.c, tests/lib/lte_lc_api/src/lte_lc_api_test.c
Adding test coverage for edrx related tests.
Also cleaning up dead code, i.e., conditions that cannot be met, have been changed from if-statements to asserts.
=> tests: lib: lte_lc_api: Add coverage for edrx

boards/nordic/thingy91x/dts/thingy91x_wifi.dtsi, boards/nordic/thingy91x/thingy91x_nrf9151_common.dts
Change the board configuration to use PORT event rather than GPIOTE IN event for GPIO interrupts, to save power.
Add a label to expansion board node and initialize it to low output.
Turn off WiFi PMIC by default
=> board: thingy91x_nrf9151: Power optimization

subsys/bluetooth/controller/Kconfig
LE Subrating support requires the SDC multirole library. 
Update the Kconfig dependencies so this is done automatically.
=> bluetooth: controller: Select SDC multirole variant if subrating

lib/lte_link_control/lte_lc.c, tests/lib/location/src/location_test.c, tests/lib/lte_lc_api/src/lte_lc_api_test.c
XMONITOR is used in lte_lc_psm_get() and it's been using nrf_modem_at_cmd() and the response has been "manually" parsed by searching for specific commas and copying 8 characters after those. This approach had bugs if some of the interested fields were not 8 character long.
So, lte_lc_psm_get() has been changed to use nrf_modem_at_scanf().
=> lib: lte_link_control: Rewrite XMONITOR to use nrf_modem_at_scanf

applications/serial_lte_modem/boards/nrf9151dk_nrf9151_ns.overlay
Duplicate 9161 overlay file information to 9151. This makes it easier for customers to modify the overlay file according to our documentation.
See: https://github.com/nrfconnect/sdk-nrf/pull/16217#discussion_r1722716449
=> applications: serial_lte_modem: Separate 9151 overlay

boards/nordic/thingy91x/board.cmake
Since the combination of nrf53, sysbuild and nrfutil is not working properly, I suggest to revert to nrfjprog for the time being. The relevant ticket is NCSDK-28655.
=> boards: thingy91x: revert to nrfjprog

samples/cellular/modem_shell/src/at/at_cmd_mode.c, samples/cellular/modem_shell/src/cloud/cloud_lwm2m.c, samples/cellular/modem_shell/src/location/location_srv_ext_lwm2m.c, samples/cellular/modem_shell/src/location/location_srv_ext_nrf_cloud.c, samples/cellular/modem_shell/src/main.c, samples/cellular/modem_shell/src/ppp/ppp_ctrl.c, samples/cellular/modem_shell/src/ppp/ppp_mdm_data_rcv.c, samples/cellular/modem_shell/src/ppp/ppp_settings.c, samples/cellular/modem_shell/src/shell.c, samples/cellular/modem_shell/src/sms/sms.c, samples/cellular/modem_shell/src/sms/sms_shell.c, samples/cellular/modem_shell/src/sock/sock_shell.c
Removing Low-category Coverity warnings about unused includes.
=> samples: cellular: modem_shell: Coverity - Remove unused includes

samples/cellular/modem_shell/src/link/link_api.c, samples/cellular/modem_shell/src/main.c, samples/cellular/modem_shell/src/utils/mosh_print.c
Added battery voltage and temperature to `link status` command, and HW version, MFW version and MFW UUID to `version` command.
MOSH-336
=> samples: cellular: modem_shell: add printing of more modem info

doc/nrf/shortcuts.txt, samples/bluetooth/central_hids/README.rst, samples/bluetooth/peripheral_hids_keyboard/README.rst, samples/bluetooth/peripheral_hids_mouse/README.rst, samples/bluetooth/peripheral_lbs/README.rst, samples/bluetooth/peripheral_status/README.rst, samples/bluetooth/peripheral_uart/README.rst
Made following changes to some of the Bluetooth
samples:
* Mentioned Thingy:53 also as tabs in the user-interface section.
* Moved a note to shortcuts.txt, which was mentioned in different Bluetooth samples.
* Removed trademark symbol apart from the 1st instance.
=> doc: Minor updates to Bluetooth samples

samples/cellular/modem_shell/src/link/link_settings.c, samples/cellular/modem_shell/src/link/link_shell_print.c
link_shell_map_to_string() wrote failure string of 42 bytes while many callers had room for 8 or 16 bytes.
=> samples: cellular: modem_shell: link: Coverity - Buffer overflow

subsys/nrf_security/src/drivers/cracen/Kconfig, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/lib_kmu.c
When the lib kmu is included inside the TFM image it should not update the RRAMC write mode since we
configure it to have the write mode enabled during the initialization of TFM and expect it to be enabled all the time.
=> nrf_security: Don't configure RRAMC for TFM builds

doc/nrf/releases_and_maturity/known_issues.rst
Add a known issue for a null pointer dereference which may happen when using the vendor-specific HCI command Zephyr Write TX Power Level to set the TX power for a connection.
=> doc: Add known issue for SDC null pointer dereference

lib/lte_link_control/lte_lc.c, tests/lib/location/src/location_test.c, tests/lib/lte_lc_api/src/lte_lc_api_test.c
XMONITOR response may not contain all fields, i.e., there are some commas one after the other so scanf parsing cannot handle it. Reverting nrf_modem_at_scanf use for AT%XMONITOR.
at_parser usage may be considered here in the future.
This reverts commit 457ff80e166bdb721bb1a511544169b5d10f6f5f.
=> Revert "lib: lte_link_control: Rewrite XMONITOR to use nrf_modem_at_scanf"

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/net/lib/nrf_cloud/src/nrf_cloud.c, tests/subsys/net/lib/nrf_cloud/cloud/src/main.c
Fixed an issue in nrf_cloud_send() that prevented data in the provided nrf_cloud_obj structure from being sent to the bulk and bin topics.
IRIS-9540
=> net: lib: nrf_cloud: send obj data for all topics

west.yml
Pull changes from upstream to allow reading UICR registers.
=> manifest: trustedfirmware: Allow reading UICR registers

doc/nrf/libraries/security/tfm/tfm_ioctl_api.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, modules/trusted-firmware-m/tfm_boards/services/include/tfm_platform_user_memory_ranges.h
Some applications might use OTP areas for information, so they need access to read those, without exposing all UICR registers.
=> modules: TF-M: Allow reading UICR.OTP areas

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/common/src/persistent_storage/Kconfig, samples/matter/template/Kconfig.sysbuild, samples/matter/template/README.rst, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp_ns.conf, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp_ns.overlay, samples/matter/template/pm_static_nrf54l15pdk_nrf54l15_cpuapp_ns.yml
- Added configuration and partitions map to the nRF54L15 target in the Matter template sample.
Issues to be resolved:
=> samples: matter: Add TF-M build to nRF54L15 Matter samples

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/nrf_modem_lib/trace_backends/rtt/rtt.c, tests/lib/nrf_modem_lib/trace_backends/rtt/src/main.c
Allocate the modem trace buffer for the RTT backend on boot, instead of when `nrf_modem_lib_init` is called. This allows the user to delay the call to `nrf_modem_lib_init`, giving them a chance to attach to the RTT channel before the modem starts.
Without this change the start of trace logs from the RTT backend are invariably lost, as the user cannot attach until after data generation has started.
=> nrf_modem_lib: trace_backends: rtt: early alloc buf

subsys/bluetooth/services/fast_pair/fp_gatt_service.c
Allows compiler to opt-out Personalized Name notify function in case the extension is disabled. It caused build errors on some compilers if not opted-out.
=> bluetooth: fast_pair: fp_gatt_service: Allow compiler to opt-out not used code

subsys/nrf_security/src/drivers/cracen/common/include/cracen/ec_helpers.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/cracenpsa.cmake, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ec_helpers.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_derivation.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c, subsys/nrf_security/src/drivers/cracen/sicrypto/src/ed25519.c, subsys/nrf_security/src/drivers/cracen/sicrypto/src/ed448.c
Add helper functions for the common bit manipulation operations described in RFC 7748.
=> nrf_security: cracen: Add helper functions for common bit manipulation

applications/nrf5340_audio/src/modules/lc3_streamer.c, tests/nrf5340_audio/lc3_streamer/src/main.c
Fixes a bug in the lc3_streamer where the stored filename variable would be used instead of the argument variable, but before the argument buffer has been copied to the stored variable. Updated tests to catch the error.
OCT-NONE
=> applications: nrf5340_audio: lc3_streamer: Use correct filename buf

scripts/tools-versions-darwin.yml, scripts/tools-versions-linux.yml, scripts/tools-versions-win10.yml
scripts: tools-versions-*.yml: update zephyr-sdk==0.16.8
Release Notes:
Removed experimental ISO C11 <threads.h>-based gthread implementation
=> scripts: tools-versions-*.yml: update zephyr-sdk==0.16.8

cmake/sysbuild/b0_mcuboot_signing.cmake, cmake/sysbuild/image_signing_nrf700x.cmake
Fixes issues with strings not being expanded
=> cmake: sysbuild: b0/nrf700x: Fix not configuring string

samples/openthread/cli/Kconfig.sysbuild, samples/openthread/cli/src/main.c
Partition Manager is redundant on the nRF52840 dongle while sysbuild is in use.
DNM until it is verified.
=> samples: openthread: Do not use Partition Manager on nRF52 dongle

doc/nrf/drivers/uart_ipc.rst, samples/bluetooth/direct_test_mode/boards/nrf5340dk_nrf5340_cpunet.overlay
Making the `uart0` a `compatible = "nordic,nrf-ipc-uart";` does
not release the `uart0` for other purposes. On nrf5340_cpunet when
when an overlay that uses TWIM0 is used the fact that `uart0` node
is still used (regardless that redefined to use ipc uart not the
hardware uart driver) leads to compilation error.
To overcome this issue the `uart0` is no more redefined but a new
device tree node `uart_ipc` is provided. From application's point
of view this is an additional uart that is used by dtm. The
`uart0` present in device tree can be used for other purpose or
disabled.
The doc regarding the uart_ipc driver is also updated to not endorse use case
that leads to this issue.
The main goal of this PR is to enable use of nrf2220ek and nrf2240ek shields
with direct_test_mode application. This …
=> samples: dtm: nrf5340_cpunet do not redefine uart0 as ipc_uart

samples/matter/common/src/persistent_storage/Kconfig, samples/matter/lock/Kconfig, samples/matter/lock/src/access/access_data_types.cpp, samples/matter/lock/src/access/access_data_types.h, samples/matter/lock/src/access/access_manager_schedules.cpp
* increase maximum number of secure entries that can be stored
* align the maximum asset size for scheduled access feature
* align the OT and Matter stack sizes
* allow for re-setting of the same schedule with different data
* added missing serialization of mAvailable flag - it was not stored because of that
* refactor the *Schedule structs to avoid boiler plate code
* decrease the log level for schedule prints
=> samples: matter: Multiple door lock's schedules refinements

west.yml
Print the log with the error code and failure reason. This might help when debugging WiFi connection failures.
=> manifest: pull Matter patch with additional WiFi log

samples/bluetooth/iso_time_sync/sysbuild/hci_ipc/prj.conf
Add temporary workaround to fix iso_time_sync sample while we are waiting for bug fix upstream.
The fix upstream was merged here in
https://github.com/zephyrproject-rtos/zephyr/pull/76688
=> Samples: Bluetooth: fix iso_time_sync sample

doc/nrf/links.txt, doc/nrf/protocols/bt/bt_qualification/index.rst
The Bluetooth qualification page mentions Bluetooth QDID in a couple of places, but the information is inside very specific sections. This adds it much earlier on the page, and gives general instructions on how to find it for Nordic devices.
=> doc: bluetooth: Earlier reference to QDID in Bluetooth qualification

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud_fota_poll.h, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_fota, subsys/net/lib/nrf_cloud/src/nrf_cloud_fota_poll.c
Add the option to use nrf_cloud_fota_poll_process() in a
non-blocking manner.
The current, blocking behavior is maintained, and the async
option is enabled by providing a callback function for error
handling.
=> nrf_cloud_fota_poll: Add possibility to be non-blocking

subsys/nfc/ndef/ch_rec_parser.c
=> nfc:ndef: Fix memory allocation check to prevent NULL dereference

CODEOWNERS, tests/benchmarks/multicore/idle/boards/nrf54h20dk_nrf54h20_cpuapp_s2ram.overlay
=> tests: benchmarks: multicore: idle: use exit-latency-us

applications/nrf_desktop/src/modules/Kconfig.usb_state, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
The USB remote wakeup is not yet supported by DWC2 USB device controller driver. Disable the feature in application configuration.
Jira: NCSDK-28559
=> applications: nrf_desktop: Disable USB remote wakeup on nRF54H20

boards/nordic/thingy91x/CMakeLists.txt, boards/nordic/thingy91x/bmm350_init_minimal.c
Adds a minimal BMM350 initialization file to the Thingy:91 X board. The OTP memory on BMM350 is disabled on boot to save power.
=> boards: thingy91x: Add minimal BMM350 init

doc/nrf/libraries/networking/nrf_cloud_log.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud_coap.h, subsys/net/lib/nrf_cloud/coap/include/nrf_cloud_coap_transport.h, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_log_backend.c
Send binary (dictionary) logs over CoAP to d2c/bin.
Jira: IRIS-9388
=> net: lib: nrf_cloud_coap: binary log support

samples/matter/common/src/migration/migration_manager.cpp
It is expected to see some error logs if the operational keys migration fails.
=> samples: matter: add error logs to key migration process.

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/nfc/lib/platform_internal_thread.c
Fix potential NULL pointer dereferencing in ring_buf_get_data function.
Jira: NCSDK-27132
=> nfc: platform: Fix NULL pointer check and potential dereference

doc/nrf/app_dev/device_guides/nrf54h.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_architecture.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_architecture_clockman.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_architecture_pm.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs1.rst, doc/nrf/samples/other.rst, tests/benchmarks/multicore/idle/README.rst
Added firmware bundle compatibility table.
Updated nRF54H20 GS guide.
Added initial power management documentation.
Added initial clock control documentation
=> doc: Documentation edits for 2.7.99-cs1 release

drivers/mpsl/clock_control/Kconfig, west.yml
The new nRF2 clock control API is enabled by default for the nRF54H20 CPUAPP as it is used to initialize the HSFLL clock. This requires two changes to sdk-nrf:
* Don't enable MPSL clock control driver for nRF54HX as it is not supported for this platform. It was previously enabled if CLOCK_CONTROL and MPSL was enabled.
* The CPUAPP base image is a bit larger now with the addition of the API, which results in it not fitting the recovery partition set aside in the SUIT smp_transfer sample (overrun by 1200 bytes), so the partitions have been adjusted to fit the app.
=> Align to support nRF2 clock control API

.github/workflows/pip-requirements.yml
They are not needed after clone, so delete them.
=> ci: pip-requirements: do not persist Git credentials

subsys/nrf_security/include/psa/nrf_platform_key_ids.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c, subsys/nrf_security/src/drivers/cracen/silexpk/target/hw/ik/ikhardware.c
Updates IKG loader to the new strings and make use of the platform key ids header file for the domain defines.
=> cracen: Update to new IKG personalization strings

samples/matter/light_bulb/sample.yaml
Sample configuration enable testing memory load on nRF7002. The default configuration does not fit into the SoC size, thus the LTO needs to be enabled.
=> samples: matter: add record to light bulb matter sample

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c
Wrong input type used for CMAC kdf.
=> cracen: Fix KMU encryption key derivation

subsys/net/openthread/rpc/common/ot_rpc_ids.h, subsys/net/openthread/rpc/common/ot_rpc_types.h
Adding header `ifdef` to:
- ot_rpc_ids.h
- ot_rpc_types.h
=> nrf_rpc: Add header guard to OT nrfrpc headers.

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/fast_pair/locator_tag/README.rst
Updated locator_tag sample README and added release notes due to the recent changes:
* Moving the sample configuration into dedicated directory
* Rework of fp_adv module
* Addition of FP advertising state LED indication
* Addition of DFU mode
Jira: NCSDK-28293
This PR documents changes introduced in the following PR and its list of dependent PRs:
https://github.com/nrfconnect/sdk-nrf/pull/16311
=> samples: bluetooth: fast_pair: locator_tag: Update docs

doc/nrf/links.txt
Updated links of NCS older version bundles
and known issues to point to TechDocs.
=> doc: update links in links.txt to point to TechDocs

tests/benchmarks/multicore/idle/testcase.yaml
=> tests: benchmarks: multicore: idle: disable CLOCK_CONTROL for s2ram

doc/_utils/utils.py
Now that legacy docs are no longer _officially_ visible, let's drop the banner.
=> doc: utils: drop announcement message

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/location/method_gnss.c
Fixed a bug which caused only part of the satellites to be iterated when counting the number of tracked satellites. This was caused by a problem in the satellite C/N0 level check. The check has now been removed, because it is no longer relevant.
Fixed a bug which caused visiblity detection to be sometimes performed twice.
=> lib: location: Fix GNSS obstructed visibility detection

samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp_internal.conf, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp_internal.overlay, samples/matter/template/pm_static_nrf54l15pdk_nrf54l15_cpuapp_internal.yml, samples/matter/template/sample.yaml
Internal DFU (dual bank) configuration has not been defined in sample.yaml, thus additional configuration has been defined. Internal configuration is an release configuration with enabled LTO to reduce size as much as possibile.
Additionaly aligned the pm_static for internal configuration.
=> samples: matter: enable dual-bank dfu config for template on nRF54L15

subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_security.c
Several functions are not defined when building without CONFIG_LWM2M_DTLS_SUPPORT. Using IS_ENABLED() does not work in this case because the compiler is looking for the missing functions.
=> net: lwm2m_client_utils: Support build without DTLS

samples/cellular/lwm2m_client/sample.yaml
Added testcase for building the sample for purpose of evaluating LwM2M advance FWU for external MCU.
This configuration is documenetd to be used for testing that feature.
ref.: NCSIDB-1214
=> sample/cellular/lwm2m_client: extended testcase

modules/trusted-firmware-m/tfm_boards/nrf54l15_cpuapp/ns/cpuarch_ns.cmake
Hardcoded 128 MHz frequency in the TF-m build for the nRF54L15 target as the frequency setting with the NRF_CONFIG_CPU_FREQ_MHZ symbol is mandatory for this board target in nrfx v3.6.0.
=> modules: TF-m: nrf54l15_cpuapp: hardcode CPU frequency

samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_bulb/boards/nrf54l15pdk_nrf54l15_cpuapp_ns.conf, samples/matter/light_bulb/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_switch/boards/nrf54l15pdk_nrf54l15_cpuapp_ns.conf, samples/matter/light_switch/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/lock/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/lock/boards/nrf54l15pdk_nrf54l15_cpuapp_ns.conf, samples/matter/lock/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15pdk_nrf54l15_cpuapp_ns.conf, samples/matter/template/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/template/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp_internal.conf, samples/matter/thermostat/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/thermostat/boards/nrf54l15pdk_nrf54l15_cpuapp_ns.conf, samples/matter/thermostat/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/window_covering/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/window_covering/boards/nrf54l15pdk_nrf54l15_cpuapp_ns.conf, samples/matter/window_covering/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf
Enabled FPROTECT in the Matter samples working on nRF54L15 to protect Matter Factory Data.
=> samples: matter: Enable Fprotect to secure factory data.

applications/matter_bridge/Kconfig, applications/matter_bridge/Kconfig.sysbuild, applications/matter_bridge/README.rst, applications/matter_bridge/boards/nrf5340dk_nrf5340_cpuapp.conf, applications/matter_bridge/doc/matter_bridge_description.rst, applications/matter_bridge/pm_static_nrf5340dk_nrf5340_cpuapp_nrf70ek.yml, applications/matter_bridge/sample.yaml, applications/matter_bridge/sysbuild/ipc_radio/boards/nrf5340dk_nrf5340_cpunet.conf, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/common/src/bridge/Kconfig, samples/matter/common/src/bridge/ble_connectivity_manager.cpp
- modyfiy application configuration files, and  board files, to create support for nrf5340, in matter-bridge application.
- create support for nrf54h20.
- create .conf files to maximize BLE connections
- update sample.yaml
- update documentation
=> applications: matter-ble bridge over thread

drivers/mpsl/flash_sync/flash_sync_mpsl.c
The driver had two places where it was dependent on CONFIG_SOC_NRF54L15_ENGA_CPUAPP Kconfig. Change the code to make  it build for all nRF54L15 versions.
=> drivers: mpsl: flash: Add uspport for nRF54L15DK to the driver

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added a changelog entry for the HW identifier change in the nRF Desktop app and its nRF54H20 DK target.
Ref: NCSDK-21888
=> doc: release_notes: nrf_desktop: describe HW ID changes for nRF54H20 DK

applications/nrf_desktop/configuration/nrf52810dmouse_nrf52810/app.overlay, applications/nrf_desktop/configuration/nrf52820dongle_nrf52820/app.overlay, applications/nrf_desktop/configuration/nrf52833dk_nrf52820/app.overlay, dts/bindings/bluetooth/nordic,bt-hci-sdc.yaml, samples/bluetooth/direction_finding_central/sysbuild.cmake, samples/bluetooth/direction_finding_connectionless_rx/sysbuild.cmake, samples/bluetooth/direction_finding_connectionless_tx/sysbuild.cmake, samples/bluetooth/direction_finding_peripheral/sysbuild.cmake, samples/debug/ppi_trace/sysbuild.cmake, subsys/bluetooth/controller/ecdh.c, subsys/bluetooth/controller/hci_driver.c, tests/drivers/nrfx_integration_test/testcase.yaml, west.yml
The SoftDevice Controller is a different controller than the open source link layer with a different set of quirks. It should therefore have its own device tree binding.
This commit converts the SoftDevice Controller driver to use this new DTS binding instead of reusing the existing one.
This commit updates or adds additional overlays for existing samples, applications and tests that were using the open source link layer.
Updating migration guide will be done in a separate commit.
=> dts: Bluetooth: Add new DTS binding for the SoftDevice Controller

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, modules/mcuboot/Kconfig, sysbuild/CMakeLists.txt, sysbuild/Kconfig.mcuboot, sysbuild/Kconfig.sysbuild
Adds a new Kconfig option that will enable setting Kconfig options in MCUboot to enable network core updates to work if device is storing update images in external flash
NCSDK-28955
=> sysbuild: Fix nRF5340 network core updates

applications/nrf5340_audio/include/zbus_common.h, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
Adds an event for when a LE Audio packet sending has been handled, so that the application may take actions.
OCT-3109
=> applications: nrf5340_audio: LE Audio Sent ZBUS event

include/modem/at_parser.h
Fixed `at_parser_string_get()` "len" parameter description. The size of the given buffer must be at least string length + 1.
=> lib: at_parser: Fix at_parser_string_get() "len" parameter description

doc/nrf/images/conn_time_sync_diagram.svg
The timestamp mistyped, it should have been 90002 instead of 80002 as we expect the timestamp to be close to 10000 away from the previous one.
=> samples: conn_time_sync: Fix typo in diagram

doc/nrf/libraries/others/date_time.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/date_time/Kconfig, lib/date_time/date_time_core.c, samples/cellular/nrf_cloud_multi_service/overlay_nrf700x_wifi_coap_no_lte.conf, samples/cellular/nrf_cloud_multi_service/overlay_nrf700x_wifi_mqtt_no_lte.conf
Remove pending-update checks that caused date_time to be unable to schedule retries on failure. See commit log for detailed justification of change.
Also added fast retry option for NTP, so that transient DNS errors can be recovered from without waiting the full refresh period
=> lib: date_time: Retry improvements

lib/location/Kconfig
Made `CONFIG_LOCATION_METHOD_WIFI_NET_MGMT` depend on `CONFIG_LOCATION_METHOD_WIFI` to hide it when Wi-Fi location method is disabled.
=> lib: location: Hide LOCATION_METHOD_WIFI_NET_MGMT when Wi-Fi is disabled

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/wifi/radio_test/sample_description.rst, samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
[SHEL-3047]: Update command output, subcommand order and argument.
[SHEL-3047]: https://nordicsemi.atlassian.net/browse/SHEL-3047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> samples: wifi: radio_test: Correct command output and order

cmake/sysbuild/suit.cmake, cmake/sysbuild/suit_utilities.cmake, config/suit/templates/nrf54h20/default/v1/app_envelope.yaml.jinja2, config/suit/templates/nrf54h20/default/v1/rad_envelope.yaml.jinja2, config/suit/templates/nrf54h20/matter/v1/app_envelope.yaml.jinja2, config/suit/templates/nrf54h20/matter/v1/rad_envelope.yaml.jinja2, samples/suit/smp_transfer/sample.yaml, samples/suit/smp_transfer/suit/nrf54h20/app_envelope_extflash.yaml.jinja2, samples/suit/smp_transfer/suit/nrf54h20/rad_envelope_extflash.yaml.jinja2, west.yml
This commit introduces several changes which allow to severe firmware images from SUIT envelopes and extract them to raw cache files, which can then be flashed separately to the device.
=> suit: Changes in build system for extracting images to caches

drivers/wifi/nrf700x/src/shim.c
Add a null check for HAL context in the interrupt handler, this was causing locking issue operating on null. The root cause of null is not known, but this solves the locking issue when data and control paths are excited in parallel.
=> v2.6: drivers: wifi: Fix shell hang

doc/nrf/includes/sample_board_rows.txt
The documentation can render sample tables from the sample.yaml file.
=> doc: nrf: add entries for nRF54L15DK

samples/nrf_rpc/protocols_serialization/client/src/ot_shell.c, subsys/net/openthread/rpc/Kconfig, subsys/net/openthread/rpc/client/ot_rpc_coap_client.c, subsys/net/openthread/rpc/common/ot_rpc_common.c, subsys/net/openthread/rpc/common/ot_rpc_common.h, subsys/net/openthread/rpc/common/ot_rpc_ids.h, subsys/net/openthread/rpc/common/ot_rpc_types.h, subsys/net/openthread/rpc/server/ot_rpc_coap_server.c, tests/subsys/net/openthread/rpc/client/src/coap_suite.c, tests/subsys/net/openthread/rpc/common/test_rpc_env.h, tests/subsys/net/openthread/rpc/server/src/coap_suite.c
Complete the serialization of the following APIs:
- otCoapAddResource
- otCoapRemoveResource
- otSetDefaultResource
Implement serialization of the following APIs:
- otCoapSendRequest
- otCoapSendResponse
=> net: openthread: rpc: otCoAP API serialization p.2

CODEOWNERS, snippets/hw-flow-control/boards/nrf5340dk_nrf5340_cpuapp.overlay, snippets/hw-flow-control/snippet.yml
To be applied for tests which require HWFC
but board does not have it by default.
=> snippets: add hw-flow-control snippet

subsys/nrf_security/include/psa/nrf_platform_key_ids.h
=> crypto: fix incorrect usage

subsys/nrf_security/Kconfig.tls
The currently set defaults are 4 bytes less than the actual maximum allowed fragment size. This prevents communication with TLS servers which tend to use the maximum allowed fragment size, regardless of the client configuration. Hence, update the defaults accordingly, to use the maximum fragment size instead.
=> nrf_security: Update TLS in/out buffer defaults

drivers/mpsl/flash_sync/flash_sync_mpsl.c, subsys/mpsl/init/Kconfig, subsys/mpsl/init/mpsl_init.c
Let's use the SOC_COMPATIBLE_NRF54LX kconfig option instead of SOC_SERIES_NRF54LX so we treat both the real and simulated targets equally.
Requires (merged)
* https://github.com/nrfconnect/sdk-zephyr/pull/1993
=> mspl: Treat simulated nrf54l15 like real one

subsys/partition_manager/pm.yml.nvs, subsys/partition_manager/pm.yml.settings
When we have TF-M enabled with the nRF54L15 we want to minimize how many secure/non-secure regions we use, so in TF-M we make the assumption that there is one secure and one non-secure region.
This updates the non-secure storage partitions (settings/nvs) in nRF54L15 so that they are placed after the non-secure application.
=> partition_manager: Move ns storage partitions for nRF54L15

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/net/lib/nrf_provisioning/src/nrf_provisioning.c, subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c
Enable socket option SO_KEEPOPEN for nRF91x1 devices. This allows keeping the socket open while PDN is down, or modem is in flight mode.
Print a message to check the CA certificate if connection is refused.
=> net: nrf_provisioning: Add support for socket option SO_KEEPOPEN

subsys/logging/log_backend_rpc.c
Due to an issue in Zephyr logging subsystem (see upstream PR 78145), this function may be called more often than the configured periodicity (1000ms by default), which might cause sending RPC events to the RPC client indefinitely, wasting the bandwidth of the RPC communication.
=> logging: rpc: do not report log drops

doc/nrf/protocols/thread/certification.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/net/CMakeLists.txt, subsys/net/openthread/Kconfig, subsys/net/openthread/report/CMakeLists.txt, subsys/net/openthread/report/Kconfig, subsys/net/openthread/report/report_generation_utils.cmake, west.yml
The OpenThread report contains information about the current NCS and OpenThread revisions, Thread feature set, and the
difference between the current and the latest nrfxlib OpenThread directory to detect the potential changes that may impact the Thread work.
The report is shown as a build console log and as a .txt file build artefact.
Described the OpenThread build report and how to use it in the certification process.
Updated release notes.
=> net: openthread: Introduce OpenThread build report for NCS

scripts/tag_west_repos.sh
In some cases, e.g. fix releases, not all repositories need tagging.
=> scripts: tag_west_repos: make tags optional

boards/shields/nrf2240ek/nrf2240ek.conf, boards/shields/nrf2240ek/nrf2240ek.overlay
Bringing objects close to the PCB antenna of the nRF2240EK might
cause voltage drops which could in effect reset the nRF2240 what is
invisible to the remaining application.
To counteract this phenomenon the current limit of the PMIC
present on the nRF2240EK is increased to 500mA.
=> boards: shields: nrf2240ek: 500mA pmic current limit on bootup

.github/workflows/docbuild.yml, .github/workflows/docpublish.yml
Apparently some Zoomin plugins ignore the content of `custom.properties` and use the Zip file name as the uploaded bundle name. Until fixed, align Zip file names with their expected bundle name.
=> ci: doc: align Zoomin zip names with bundle names

lib/lte_link_control/Kconfig, lib/lte_link_control/lte_lc.c
Stack overflow occurs if `CONFIG_LOG_MODE_IMMEDIATE` is set. Reserving more stack with immediate logging but keeping the default stack size.
Jira: NCSDK-29063
=> lib: lte_link_control: Tune lte_lc_work_q_stack size

scripts/twister/alt/zephyr/tests/drivers/i2c/i2c_bme688/testcase.yaml
Adapt the alternative configuration of the i2c/bme688 test to run on all supported I2C speeds.
=> tests: drivers: Run i2c bme688 test with all supported i2c speeds

samples/peripheral/radio_test/src/radio_test.c
Uses the shortcut PHYEND_START instead of END_STRART for nRF54 series.
=> samples: radio_test: Align shortcuts for the nRF54 series

samples/bluetooth/radio_notification_cb/Kconfig.sysbuild
Fixes building for 53 network core
after 9e8d1713a8b12cc0c81356cc18bb0d00ebe2888a.
SOC_COMPATIBLE_NRF5340_CPUNET was not being set in a sysbuild context. Using SOC_SERIES_NRF53X instead.
=> samples: radio_notification_callback: Fix building empty app core

doc/nrf/protocols/bt/bt_stack_arch.rst
This was missed in an earlier PR.
=> doc: Bluetooth: Fix typo in the header

drivers/wifi/nrf700x/Kconfig, drivers/wifi/nrf700x/src/wifi_mgmt.c, west.yml
PS exit strategy support V2.6(Ported from V2.5-branch)
=> v2.6: PS exit strategy configuration

drivers/Kconfig, west.yml
Update sdk-zephyr with DPPI channel allocation for SW-defined IO devices on nRF54L15.
=> manifest: update sdk-zephyr version

applications/nrf_desktop/bootloader_dfu.rst, applications/nrf_desktop/doc/dfu.rst, applications/nrf_desktop/src/modules/dfu.c, applications/nrf_desktop/src/modules/dfu_mcumgr.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, scripts/hid_configurator/modules/dfu.py
=> nRF Desktop: SUIT semantic support 

scripts/quarantine_zephyr.yaml
Enabled during PDK->DK transfer but not aligned for nrf54l15.
=> scripts: quarantine_zephyr: add sample.drivers.spi.flash

applications/nrf_desktop/configuration/nrf52810dmouse_nrf52810/app.overlay, applications/nrf_desktop/configuration/nrf52820dongle_nrf52820/app.overlay, applications/nrf_desktop/configuration/nrf52833dk_nrf52820/app.overlay, dts/bindings/bluetooth/nordic,bt-hci-sdc.yaml, samples/bluetooth/direction_finding_central/sysbuild.cmake, samples/bluetooth/direction_finding_connectionless_rx/sysbuild.cmake, samples/bluetooth/direction_finding_connectionless_tx/sysbuild.cmake, samples/bluetooth/direction_finding_peripheral/sysbuild.cmake, samples/debug/ppi_trace/sysbuild.cmake, subsys/bluetooth/controller/ecdh.c, subsys/bluetooth/controller/hci_driver.c, tests/drivers/nrfx_integration_test/testcase.yaml, west.yml
The SoftDevice Controller is a different controller than the open source link layer with a different set of quirks. It should therefore have its own device tree binding.
This commit converts the SoftDevice Controller driver to use this new DTS binding instead of reusing the existing one.
This commit updates or adds additional overlays for existing samples, applications and tests that were using the open source link layer.
Updating migration guide will be done in a separate commit.
This PR reapplies what was reverted in https://github.com/nrfconnect/sdk-nrf/pull/17184
=> dts: Bluetooth: Add new DTS binding for the SoftDevice Controller (2)

scripts/twister/alt/zephyr/tests/drivers/i2c/i2c_bme688/testcase.yaml
…est case for nrf54l15dk
Fixes: https://nordicsemi.atlassian.net/browse/NCSDK-29132
=> tests: drivers: Remove unsupported i2c speed for bme688 with nrf54l15dk

drivers/wifi/nrf700x/src/wifi_util.c, west.yml
There is a race condition when recovery is in progress and in parallel Wi-Fi util commands are being executed (CTF), where the RPU context is de-initialized as part of recovery but no checks are present in the Wi-Fi util command processing causing a crash.
This needs a proper fix for all commands, but for maintenance branch fix is added only for commonly used commands.
=> drivers: wifi: Fix crash when recovery is triggered

west.yml
Mistakenly the PR ref was merged, so, update with the SHA of the merged Zephyr PR.
FYI, original PR is https://github.com/nrfconnect/sdk-nrf/pull/17277 this should ideally have the SHA, but it was merged early before the manifest update, this PR fixes that.
=> manifest: zephyr: Update PR ref with SHA

boards/shields/pca63565/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, boards/shields/pca63565/boards/nrf54l15dk_nrf54l15_cpuflpr.overlay, boards/shields/pca63565/boards/nrf54l15dk_nrf54l15_vpr_launcher.overlay, boards/shields/pca63565/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, boards/shields/pca63565/boards/nrf54l15pdk_nrf54l15_cpuflpr.overlay, boards/shields/pca63565/boards/nrf54l15pdk_nrf54l15_vpr_launcher.overlay
Delete LEDs / Buttons that collide with GPIOs used by the sensor shield.
Align LEDs / Button placement to PCA10156 rev. 0.8.1.
Switch adxl362 from spi00 to spi21 because spi00 is already configured to work with external NOR flash memory.
=> boards: shields: pca63565: Update sensor board overlay

doc/nrf/protocols/bt/bt_stack_arch.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Documents that the HCI driver has now been moved to device tree and that action is needed for applications using the Zephyr Bluetooth LE Controller.
=> doc: Bluetooth: Document HCI driver moved to DTS

subsys/mpsl/init/Kconfig, subsys/mpsl/init/mpsl_init.c
CONFIG_MPSL_HFCLK_LATENCY sets mpsl_clock_hfclk_latency_set(). It's recommended to use this kconfig instead of calling the function directly, as this ensures that it's called at a safe time.
=> mpsl: Add CONFIG_MPSL_HFCLK_LATENCY

samples/suit/smp_transfer/prj.conf, samples/suit/smp_transfer/sysbuild/smp_transfer.conf, samples/suit/smp_transfer/sysbuild/smp_transfer_bt.conf
Adjust Kconfigs, so they do not produce build-time warnings.
=> samples: Fix warnings in smp_transfer sample

boards/shields/nrf700x_nrf54h20dk/nrf700x_nrf54h20dk.overlay, west.yml
Align settings and DFU partition definition with the values, specified by the design documentation.
=> boards: nrf54h20dk: Fix settings partition

samples/matter/common/src/app/matter_init.cpp, samples/matter/common/src/dfu/ota/ota_util.cpp, samples/matter/common/src/dfu/ota/ota_util.h, samples/matter/common/src/dfu/smp/dfu_over_smp.cpp, west.yml
set External Flash to sleep always during initialization. This ensures that if External Flash is available, it will be put into deep sleep mode and consume less energy.
Additionaly align with `ExternalFlashManager` refactor.
=> samples: matter: set External Flash to sleep at init

lib/supl/os/lte_params.c
Fixed several `memset()` related compilation warnings.
=> lib: supl: Fix compilation warnings

samples/matter/light_switch/snippets/lit_icd/lit_icd.conf, west.yml
Move increasing `SYSTEM_WORKQUEUE_STACK_SIZE` for
`CHIP_ICD_LIT_SUPPORT` to Kconfig instead of manually increasing in snippets.
=> manifest: connectedhomeip: Update revision

samples/bluetooth/peripheral_uart/README.rst, samples/bluetooth/peripheral_uart/boards/nrf54h20dk_nrf54h20_cpurad.conf, samples/bluetooth/peripheral_uart/boards/nrf54h20dk_nrf54h20_cpurad.overlay
Add configuration that allows to build the sample application the nRF54H20 radio core. 
That presents possibility to run BLE firmware and use the nRF54h20 application core for other purposes.
All changes are related with nRF54H20 SoC only.
=> samples: bluetooth: peripehral_uart: All to run complete sample on nRF54H20 radio core

drivers/wifi/nrf700x/src/fmac_main.c, drivers/wifi/nrf700x/src/wifi_util.c, west.yml
* The RPU context lock is not unlocked this is causing recovery to be stuck waiting for the lock.
* Fix the improper re-initialization of RPU context lock
* FW: Fix recovery reset for every TX command
=> wifi: Fixes for recovery stress tests

doc/nrf/protocols/thread/certification.rst
Reword build report documentation as it does not determine eligibility for certification by inheritance.
=> doc: openthread: reword build report documentation

applications/nrf5340_audio/doc/building.rst, doc/nrf/app_dev/device_guides/nrf53/building_nrf53.rst, doc/nrf/app_dev/programming.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Moved information from building_nrf53.rst to programming.rst and nRF Util docs, given that it applies to more than one device series. Expanded information to include information about nRF54H and nRF54L. Linked to nRF Util docs. NCSDK-28527.
=> doc: programming: expand --recover info

samples/suit/smp_transfer/sysbuild/hci_ipc.overlay, samples/suit/smp_transfer/sysbuild/nrf54h20dk_nrf54h20_memory_map.dtsi, samples/suit/smp_transfer/sysbuild/recovery_hci_ipc.overlay
The application core dts enabled was enabling the radio core partition, which led to the radio core area being added to the application core UICR.
This in turn led to not rejecting a manifest in which the application core image was placed in the radio core area.
=> samples: suit: Fixed dts overlays - incorrect UICR generation

boards/nordic/thingy91x/thingy91x_common.dtsi
This patch updates the Thingy:91 X board files to match the latest hardware revision 0.9.1. The BMM150 magnetometer has been replaced with the BMM350 magnetometer.
=> boards: thingy91x: replace bmm150 with bmm350

boards/nordic/thingy91x/board.cmake
This patch uses the nrfutil runner by default for the Thingy:91x board. Also, the device family option was removed for the nrfjprog runner. The device family option is dangerous to use and should be avoided. For nrfutil-device, a safeguard is being put in place to remedy that problem, but nrfjprog will not be updated in that way.
=> boards: thingy91x: use nrfutil runner

samples/wifi/ble_coex/src/main.c, samples/wifi/scan/sample.yaml, samples/wifi/scan/src/main.c, samples/wifi/shutdown/src/main.c, samples/wifi/sta/sample.yaml, samples/wifi/sta/src/main.c, samples/wifi/thread_coex/src/main.h, samples/wifi/thread_coex/src/ot_coex_functions.c, samples/wifi/thread_coex/src/ot_coex_functions.h, samples/wifi/throughput/src/main.c, samples/wifi/twt/modules/traffic_gen/src/main.c, samples/wifi/twt/modules/traffic_gen/src/tcp.c, samples/wifi/twt/src/main.c, samples/wifi/wfa_qt_app/src/qt_app_main.c
Fix duplicates name by using sample name prefix.
Note: For some reason CI didn't catch this in the original PR.
=> samples: wifi: Fix duplicate twister names

applications/matter_bridge/doc/matter_bridge_description.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- Support for Thread protocol and nRF54H20 is experimental
- There is to many unnecesary buildings commands in smart-plug section
=> doc: Matter Bridge documentation enhancement

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/modem_shell/src/link/link_shell.c
Adding 'link modem' command for initializing and shutting down the modem  through nrf_modem_lib_init()/nrf_modem_lib_shutdown(). There is also an option to do AT+CFUN=0 and nrf_modem_lib_shutdown() so that we can test the timings of this scenario.
Manually doing AT+CFUN=0 and shutdown is too slow to test what applications might experience.
Jira: MOSH-610
=> samples: cellular: modem_shell: Add commands for modem init and shutdown

doc/nrf/releases_and_maturity/known_issues.rst
Added a known issue description for the QSPI fault problem happening during DFU over SMP in the Matter applications.
=> doc: added known issue entry for QSPI fault during DFU SMP

doc/nrf/releases_and_maturity/known_issues.rst, west.yml
The Matter version was updated to pull a fix for commissioning window.
=> manifest: Updated Matter repository to pull commissioning fix

lib/lte_link_control/lte_lc.c, lib/lte_link_control/lte_lc_modem_hooks.c, tests/lib/lte_lc_api/src/lte_lc_api_test.c
There are two small changes that make `lte_lc` function a little better:
1)
`lte_lc_edrx_req()` will be run directly in `lte_lc_edrx_on_modem_cfun()` when power off is issued. Earlier it was submitted to a work queue and run in `lte_lc_work_q`. Work queue was originally added because we wanted to avoid sending AT commands in the callback. However, when modem is powered off, we are not expecting AT notifications that could cause an assertion or
missing notification.
This was added in PR #15203.
Jira: NCSIDB-1347
2)
Remove power off from modem shutdown. `nrf_modem_lib` uses 'AT+CFUN=0' in `nrf_modem_lib_shutdown()` if the mode is not already '0'. So doing this also in `lte_lc` is unnecessary.
=>  lib: lte_link_control: eDRX request not in workqueue in power off

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/ram_pwrdn/Kconfig, lib/ram_pwrdn/ram_pwrdn.c, samples/openthread/cli/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/openthread/cli/snippets/low_power/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/openthread/cli/snippets/low_power/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/openthread/cli/snippets/low_power/snippet.yml, samples/openthread/cli/src/low_power.c
Updated the low power snippet by nRF54L15 DK target, configs and a dts overlay file.
=> Add nRF54L15DK to lib ram_pwrdn and OT CLI low power snippet

samples/nrf_rpc/protocols_serialization/client/CMakeLists.txt, samples/nrf_rpc/protocols_serialization/client/README.rst, samples/nrf_rpc/protocols_serialization/client/snippets/nfc/nfc.conf, samples/nrf_rpc/protocols_serialization/client/snippets/nfc/snippet.yml, samples/nrf_rpc/protocols_serialization/client/src/nfc_shell.c, samples/nrf_rpc/protocols_serialization/server/README.rst, samples/nrf_rpc/protocols_serialization/server/snippets/nfc/nfc.conf, samples/nrf_rpc/protocols_serialization/server/snippets/nfc/snippet.yml, subsys/nfc/rpc/Kconfig, subsys/nfc/rpc/client/CMakeLists.txt, subsys/nfc/rpc/client/nfc_rpc_t2t_client.c, subsys/nfc/rpc/client/nfc_rpc_t4t_client.c, tests/subsys/nfc/rpc/client/CMakeLists.txt, tests/subsys/nfc/rpc/client/src/t2t_suite.c, tests/subsys/nfc/rpc/client/src/t4t_suite.c
PR fixes the sequence of the serialized parameters in event callback serializer to make compatible client and server parts.
PR adds NFC API usage in the protocol serialization samples (both client and server) as well as extends samples documentation.
=> samples: nrf_rpc: protocol_serialization: add nfc

.github/test-spec.yml, samples/peripheral/radio_test/boards/nrf54h20dk_nrf54h20_cpurad.overlay
Sample needs more space for buffer at heap.
=> samples: peripheral: radio_test: make cpurad_dma reg bigger

samples/suit/smp_transfer/sample.yaml
It is necessary to add UART overlay to have a working solution that uses EXTMEM and UART as SMP transport.
=> samples: Add UART overlay in extflash builds

samples/peripheral/radio_test/src/radio_test.c
Fixed the radio shortcut settings for nRF52 and nRF53 devices to use the PHYEND_START 
shortcut when operating in 802.15.4 or BLE Coded PHY modes.
=> samples: radio_test: Fix shortcut configuration for nRF52 and nRF53

boards/nordic/thingy91x/thingy91x_nrf9151_pm_static.yml
When using the start-to-end placement strategy in the external_flash region, it will automatically create a partition named external_flash that fills the remainder of the external flash's address space.
The external_flash we had defined in the Thingy:91 X static partitions was covering the total space in the external flash. Which caused dynamic partitions, like modem_trace, to be placed outside of the external flash address space instead of after the last static partition.
With this fix, the modem_trace partition will be placed after the last statically defined partition in the external_flash region. Then a partition named external_flash will be placed after the modem_trace partition to fill the remaining space.
The hardcoded device name referred to an old prototype revision of the …
=> boards: thingy91x: fix external_flash static partition

west.yml
Pull in update in DVFS medlow oppoint trim entry index. This helps with on all idle current when switching to medlow DVFS oppoint.
=> manifest: update zephyr with latest DVFS oppoint data

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud.h, include/net/nrf_cloud_fota_poll.h, modules/memfault-firmware-sdk/memfault_lte_metrics.c, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_coap, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_fota_poll.c
Various fixes / cleanups needed for the [Thingy91x Out of Box firmware](https://github.com/hello-nrfcloud/firmware).
Mostly small stuff found during testing of Full Modem FOTA.
=> net: lib: nrf_cloud_coap: Various cleanups / fixes

subsys/dfu/fmfu_fdev/Kconfig
This library depends on `FLASH`, so express this dependency.
=> subsys: dfu: fmfu_dev: depend on FLASH

CODEOWNERS
Replaces https://github.com/nrfconnect/sdk-nrf/pull/15698
In preparation for the enabling of the GitHub "Require reviews from Code Owners" branch protection setting, reorganize the Codeowners file so that Vestavind is aware of changes in the files it needs to oversee.
See also: https://nordicsemi.atlassian.net/wiki/spaces/SPG/pages/635604878/CODEOWNERS+file
=> CODEOWNERS: Overhaul in order to enable required reviews

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/peripheral_hr_coded/src/main.c
Pass default params to bt_le_ext_adv_start
instead of NULL. The NULL was deferenced and used
to set parameters for starting extended advertising in the sample.
=> samples: bluetooth: fix peripheral hr coded

scripts/requirements-ci.txt, scripts/requirements-fixed.txt, scripts/tools-versions-darwin.yml, scripts/tools-versions-linux.yml, scripts/tools-versions-win10.yml
Bump Python to version 3.12 on Mac and Windows
=> tools: Python 3.12 - Mac & Windows

applications/nrf5340_audio/src/modules/lc3_streamer.c, tests/nrf5340_audio/lc3_streamer/src/main.c
Fix an incorrect string copy in LC3 streamer that used the length of the string instead of the size of buffer when copying.
OCT-3109
=> applications: nrf5340_audio: Fix incorrect string copy in LC3 streamer

CODEOWNERS, tests/benchmarks/multicore/idle_gpio/boards/nrf54h20dk_nrf54h20_cpuapp_s2ram.overlay, tests/benchmarks/multicore/idle_gpio/boards/wakeup_from_uart_pins.overlay, tests/benchmarks/multicore/idle_gpio/remote/boards/nrf54h20dk_nrf54h20_cpurad_s2ram.overlay, tests/benchmarks/multicore/idle_gpio/remote/boards/wakeup_from_uart_pins.overlay, tests/benchmarks/multicore/idle_gpio/src/main.c, tests/benchmarks/multicore/idle_gpio/testcase.yaml
At custom configuration, redefine pins used to wakeup each core. Instead of buttons, use uart rx pin.
This will make automated testing possible without additional HW.
=> tests: benchmarks: multicore: idle_gpio: add wakeups from uart rx pin

CODEOWNERS
Bluetooth related files should be handled by Dragoon by default. Some components of Bluetooth are handled exlusively by other teams or with a shared responsibility.
=> CODEOWNERS: Assign Bluetooth to ncs-dragoon by default

samples/bluetooth/peripheral_uart/sample.yaml
This commit adds build for nrf54h20 radio core to sample.yaml
=> samples: bluetooth: peripheral_uart: Add nrf54h20 cpurad to sample.yaml

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/at_shell/Kconfig, lib/at_shell/at_shell.c, subsys/net/lib/nrf_cloud/Kconfig
Added CONFIG_AT_SHELL_UNESCAPE_LF to enable reception of multiline AT commands.
Updated the at_shell() function to replace the 2 character sequence "\n" with <CR><LF>
if CONFIG_AT_SHELL_UNESCAPE_LF is enabled.
Jira: IRIS-6919
=> lib: at_shell: Add optional multiline support

subsys/suit/cache/src/suit_dfu_cache_rw.c
Skip writing padding data to cache as it significantly affects DFU time and leads to preliminary app disconnects.
=> suit: Do not write padding data

applications/nrf_desktop/configuration/nrf52840dk_nrf52840/app_mcuboot_qspi.overlay
Change adds missing USB HID DTS node for nRF52840DK in MCUboot QSPI configuration. This is necessary to support HID over USB when USB next stack is selected.
Jira: NCSDK-27740
=> applications: nrf_desktop: Fix USB next HID configuration

doc/nrf/app_dev/bootloaders_dfu/qspi_xip_split_image.rst
Removes a reference to nRF91 as this does not support QSPI
=> doc: nrf: app_dev: bootloaders_dfu: Fix QSPI nRF91 mention

CODEOWNERS
```
codeowners: Remove global default
A global default prevents the codeowners check inside the compliance
GH actions workflow to do its job of finding new files not covered by an
entry in the CODEOWNERS file. Remove it.
```
```
codeowners: Move build system file patterns to the end
In order to ensure that build system-related files are always reviewed
by the ncs-co-build-system team, move them to the bottom so that they
override the default per-folder reviewers.
```
=> CODEOWNERS tweaks

doc/nrf/app_dev/bootloaders_dfu/dfu_tools_mcumgr_cli.rst, doc/nrf/app_dev/bootloaders_dfu/index.rst, doc/nrf/app_dev/device_guides/nrf53/serial_recovery.rst, doc/nrf/links.txt, doc/nrf/protocols/bt/bt_mesh/dfu_over_bt_mesh.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/dfu/distributor/README.rst
Adds the docs removed from Zephyr.
The content has been adjusted to the NCS doc standards.
Needed for the upmerge.
=> doc: add mcumgr docs

doc/nrf/releases_and_maturity/software_maturity.rst
NCSDK-27739
We have had issues with incorrect SML table values due to the update being through nightly build,
especially in release branches. So  until the script is optimized, the only way to fix this issue is to make the tables manual (grid tables). This PR converts the present values into manual table values.
=> doc: Make all the tables in SML page manual

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/installation/install_ncs.rst, doc/nrf/installation/recommended_versions.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/migration/2.4.99-cs3_to_2.6.99-cs2/migration_guide_2.4.99-cs3_to_2.6.99-cs2_environment.rst, doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/migration_guide_2.6.99-cs2_to_2_7_environment.rst, doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/transition_guide_2.4.99-cs3_to_2.7_environment.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, doc/nrf/shortcuts.txt
Added explicit mention of the J-Link being required. Added mention of nRF54H Series working with nRF Command Line Tools. NRFU-1160.
=> doc: installation: J-Link explicit mention

cmake/sysbuild/image_signing.cmake
Adds the confirm flag when using imgtool to make signed hex files be confirmed
NCSDK-24020
=> cmake: sysbuild: signing: Fix DirectXIP signing with confirmation

subsys/bluetooth/controller/hci_driver.c
Log an error if an HCI event is too big for the static HCI buffer. If CONFIG_BT_BUF_RX_SIZE is too small you get buffer overruns.
Hopefully this can save some time for poor saps like me who spend all day trying to figure out why their code seems to produce random bus faults and other memory corruption symptoms
=> bluetooth: controller: print an error message if the event is too big

scripts/ncs-toolchain-version-minimum.txt
2.7.20240919 contains Python 3.12
Required to enforce cmake to pick proper toolchain bundle
=> toolchain: Bump minimum toolchain veresion

applications/matter_bridge/sample.yaml, scripts/quarantine_integration.yaml
Introduced several changes for sample.yaml in Matter bridge application:
* Added nrf54h20 platform to display it in the readme's supported platforms table.
* Added nrf5340 and nrf54h20 to the release configurations to display all supported platforms in the memory consumption table.
* Replaced several configurations run using simulated variant to the BLE one, as it is more error prone.
=> applications: Reworked sample.yaml configuration for Matter bridge

doc/nrf/releases_and_maturity/known_issues.rst
Added known issue about the lock sample not allowing for clearing of the user if the schedules feature is used and lock credentials are stored in the application.
=> doc: Added known issue related to clearing of the lock user

doc/nrf/app_dev/device_guides/fem/index.rst, doc/nrf/app_dev/device_guides/nrf52/index.rst, doc/nrf/app_dev/device_guides/nrf53/index.rst, doc/nrf/app_dev/device_guides/nrf54h.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf70/index.rst, doc/nrf/app_dev/device_guides/nrf91/index.rst, doc/nrf/app_dev/device_guides/pmic/index.rst, doc/nrf/includes/guides_complementary_to_app_dev.txt, doc/nrf/shortcuts.txt, samples/bluetooth/peripheral_lbs/README.rst, samples/bluetooth/peripheral_uart/README.rst
Applied edits from testing the Quick Start app with @ketile.
Added information about how Developing with pages relate to other guides
in Application development.
Broke down testing steps for samples supported in Quick Start into
passive behavior that can be observed after programming using the app
and steps that require additional applications.
=> doc: quick_start: edits from testing

samples/wifi/ble_coex/README.rst
Update readme to suit the latest documentation style.
=> samples: wifi: ble_coex: Readme update

scripts/requirements-build.txt, scripts/requirements-fixed.txt, west.yml
Pull in newest sdk-zephyr to support new fields in UICR TRACE that allow tracing via ETM and changes the format of the tddconf binding.
=> manifest: add haltium tracing

subsys/suit/Kconfig
This was not found out until suit_dfu_cleanup was used.
=> suit: Fixed missing Kconfig in push-to-cache configuration

doc/nrf/protocols/matter/end_product/bootloader.rst, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp_internal.conf, samples/matter/template/pm_static_nrf54l15dk_nrf54l15_cpuapp_internal.yml
The DFU using internal flash for nRF54L15DK does not work properly, because the mcuboot secondary partition offset is not aligned to the 4k. Due to that mcuboot erase operation is not performed properly and trailer information are not removed, what leads to swapping back the old image.
The problems was solved by increasing the settings size, to move all partitions and in result achieve aligned mcuboot partitions offset.
=> samples: matter: Fixed DFU using internal flash for nRF54L15

samples/wifi/radio_test/sample_description.rst
[SHEL-3109] Correct subcommand description placement.
Some subcommand descriptions were incorrectly placed under FICR/OTP programming tab. 
[SHEL-3109]: https://nordicsemi.atlassian.net/browse/SHEL-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> samples: wifi: radio_test: Correct description placement

.github/workflows/docbuild.yml
Otherwise it gets mixed with Sphinx content when uploading to Zoomin.
=> ci: docbuild: move Doxygen content out of html dir

samples/bluetooth/event_trigger/Kconfig.sysbuild, samples/bluetooth/event_trigger/boards/nrf52840dk_nrf52840.overlay, samples/bluetooth/event_trigger/boards/nrf52dk_nrf52832.overlay, samples/bluetooth/event_trigger/boards/nrf5340dk_nrf5340_cpunet.overlay, samples/bluetooth/event_trigger/boards/nrf54h20dk_nrf54h20_cpurad.overlay, samples/bluetooth/event_trigger/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/bluetooth/event_trigger/sample.yaml, samples/bluetooth/event_trigger/src/main.c
This PR adds support for nRF54H20 built for radio core and nRF54L15 in event_trigger sample.
=> samples: bluetooth: event_trigger: Add support for nRF54H20 (cpurad) and nRF54L15

doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_quick_start.rst
Removes redundant links.
These shouldn't be listed for quick start under samples
=> doc: remove redundant bootloader links

doc/nrf/app_dev/device_guides/nrf52/fota_update.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Documented this feature for applcation image intel-hex file built along with MCUBoot in diret-XPI with revert mode.
goes once  #17390 gets merged.
=> doc/nrf/../fota: documented auto confirmation of direct-XIP image

doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/nrf_cloud_multi_service/Kconfig, samples/cellular/nrf_cloud_multi_service/README.rst, samples/cellular/nrf_cloud_multi_service/prj.conf, samples/cellular/nrf_cloud_multi_service/src/application.c, samples/cellular/nrf_cloud_rest_device_message/Kconfig, samples/cellular/nrf_cloud_rest_device_message/src/main.c
By default, no longer send an alert on startup.
Add logging of the reset reason, and if the online alert is enabled, include that in the value.
IRIS-9688
=> samples: cellular: nrf_cloud: Control online alert

applications/serial_lte_modem/sample.yaml
Native TLS overlay no longer fits to thingy91 flash. Remove it from sample.yaml. The combination was already marked as not supported in documentation.
=> applications: serial_lte_modem: Remove thingy91 nativetls

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change adds missing release note for nRF52840 DK in MCUboot QSPI configuration (USB HID DTS node was added).
=> applications: nrf_desktop: Add release note

doc/nrf/libraries/networking/aws_iot.rst, doc/nrf/links.txt
NCSDK-28995
* Improve commands on how to install dependencies and usage of the AWS CLI.
* Improve instructions of AWS IoT setup for nRF70 Series
doc updates pending for the Create a policy section. The policy was not able to be created with the commands provided in steps 2/3 of the "Create a policy" section - discussed offline with Simon, and this will be taken care in a separate PR. Related Jira will be kept open.
=> doc: Updates to AWS IoT lib docs

tests/benchmarks/peripheral_load/sample.yaml
In coverage mode:
- RAM is overflown by ~30 kB on nRF54L15.
- ROM is overflown by ~30 kB on nRF54H20.
Remove from sample.yaml tests dedicated to be run in a coverage mode as they don't fit into available memory.
=> tests: benchmarks: peripheral_load: Remove test run in coverage mode

samples/benchmarks/coremark/sample.yaml, scripts/quarantine_integration.yaml
This should make    nrf52833 visible in table:  “The sample supports the following development kits:”  in documentation.
JIRA: NCSDK-27719
=> samples: coremark: Add nrf52833 to integration tests in cormark

subsys/sdfw_services/services/psa_crypto/psa_crypto_service.cddl, subsys/sdfw_services/services/psa_crypto/zcbor_generated/psa_crypto_service_decode.c, subsys/sdfw_services/services/psa_crypto/zcbor_generated/psa_crypto_service_encode.c
Tags are added to all pointers to enable memory checking on the server side of the service. The cbor tags are registered here: https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml
=> crypto service: change cddl to enable memory checking on server side

samples/edge_impulse/data_forwarder/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/edge_impulse/data_forwarder/sample.yaml, samples/edge_impulse/data_forwarder/src/main.c, samples/edge_impulse/wrapper/sample.yaml
Adds support for nRF54L15DK in the data_forwarder and wrapper samples.
=> samples: edge_impulse: Add support for nRF54L15DK

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/dfu/distributor/sample.yaml, samples/bluetooth/mesh/dfu/target/sample.yaml, samples/bluetooth/mesh/light/sample.yaml
This commit adds support for nRF54L15 for mesh samples that use mcuboot.
=> samples: bluetooth: mesh: Add nRF54L15 support for samples with mcuboot

subsys/net/openthread/Kconfig.defconfig
Enable `OPENTHREAD_DYNAMIC_STORE_FRAME_AHEAD_COUNTER` by default
=> kconfig: openthread: enable dynamic store of frame ahead counter

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/net/lib/nrf_cloud/src/nrf_cloud_log.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_log_backend.c
When using direct log calls with the logging backend enabled, associate a valid log source with the
injected log entry.
Jira: IRIS-9302
=> net: lib: nrf_cloud: add log source

subsys/bluetooth/controller/hci_driver.c
This avoids that the all event buffers get full making the system deadlock.
Jira: DRGN-23279
=> Bluetooth: hci_driver: Mark Anchor point update report as discardable

subsys/net/openthread/rpc/client/ot_rpc_message.c
Commit fixes accessing already freed memory in `otMessageRead` in nrf_rpc.
=> nrf_rpc: Fix memory access to freed memory.

doc/nrf/app_dev/device_guides/nrf54l/features.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf54l/testing_dfu.rst
Removed the PDK occurrences for the main nrf54L15 articles.
Updated references.
=> doc: small cleanup for nrf54l15 docs

include/esb.h, include/nfc/ndef/ch_msg.h, include/nfc/ndef/le_oob_rec.h, include/nfc/ndef/msg.h, include/nfc/ndef/text_rec.h, include/nfc/ndef/uri_msg.h
Remove references to non-existing groups. These are reported on new Doxygen versions (e.g. 1.12).
=> esb, nfc: fix Doxygen issues

applications/nrf5340_audio/doc/configuration.rst, applications/nrf5340_audio/doc/firmware_architecture.rst, doc/nrf/protocols/bt/bt_solutions.rst, samples/bluetooth/broadcast_config_tool/README.rst
Fixed inverted, incorrect info on the architecture page.
Added TMs and link to Auracast where needed.
Added Auracast to the name of the BCT to categorize it on the list of BT samples.
NCSDK-29427.
=> doc: audio: various fixes

subsys/bluetooth/host_extensions/Kconfig, subsys/bluetooth/host_extensions/radio_notification_conn_cb.c
By using the the connection anchor point events instead of the connection connection event trigger functionality the implementation can be refactored to not use an EGU instance.
This approach will also scale better to multicore architectures.
This approach also uses less FLASH.
For the radio_notification_cb sample on 53, the FLASH usage is reduced with almost 400 bytes.
For multicore devices that have different time domains on different cores, a translation mechanism is needed. This is currently not present. That is, we don't support this feauture on 53 app core, but it works nicely on 54 as that uses the global GRTC.
=> Bluetooth: radio_notification_callback: Refactor to not use EGUs

.github/labeler.yml
For certain files we know that we do not want to add a changelog entry.
The list has now been extended to include more such files.
=> labeler: Remove some files from "changelog-entry-required"

CODEOWNERS
We do not need ncs-si-muffin to review changes here.
=> CODEOWNERS: Make ncs-dragoon only codeowner for host_extensions

scripts/ci/tags.yaml
More deps for current consumption.
=> ci: tags: extend deps for ci_tests_benchmarks

subsys/bluetooth/host_extensions/Kconfig
The feature is no longer experimental.
=> Bluetooth: radio_notification_callback: Remove experimental label

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud.h, samples/cellular/nrf_cloud_multi_service/src/cloud_connection.c, samples/cellular/nrf_cloud_rest_cell_location/src/main.c, samples/cellular/nrf_cloud_rest_device_message/src/main.c, samples/cellular/nrf_cloud_rest_fota/src/main.c, subsys/net/lib/nrf_cloud/Kconfig, subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c, subsys/net/lib/nrf_cloud/src/nrf_cloud.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_fsm.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_info.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_rest.c, tests/subsys/net/lib/nrf_cloud/cloud/CMakeLists.txt, tests/subsys/net/lib/nrf_cloud/cloud/src/fakes.h
Some nRF Cloud connection information is available regardless of whether the device has successfully connected, whereas other information is only available post-connection.
Separate out the post-connection info into a new function, and call both at the appropriate times in the nrf_cloud_libraries.
Remove previous requirement to call these functions from the application.
Jira: IRIS-9653
=> net: lib: nrf_cloud: Log connection info from lib

.github/workflows/src-mirror.yml
Add garbage collector and compress package before sending to Artifactory
=> CI: Optimize packaging in workflow

subsys/mpsl/fem/Kconfig
The misleading comment that used to be true a long time ago is removed.
=> mpsl: fem: remove misleading comment

subsys/mpsl/pm/mpsl_pm_utils.c, tests/subsys/mpsl/pm/pm_test.c
This commit changes the input parameter of event time from relative to absolute time according to recent Zephyr RTOS changes. As an upmerge is imminent and we don't have any system tests in place, this can be merged as is.
=> Bluetooth: Controller: Update Zephyr PM policy function call parameter.

doc/nrf/external_comp/bt_fast_pair.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/bluetooth/services/fast_pair/fp_storage/Kconfig.fp_storage, subsys/bluetooth/services/fast_pair/fp_storage/fp_storage_ak.c, subsys/bluetooth/services/fast_pair/fp_storage/fp_storage_ak_minimal.c, subsys/bluetooth/services/fast_pair/fp_storage/fp_storage_clock.c, subsys/bluetooth/services/fast_pair/fp_storage/fp_storage_eik.c, subsys/bluetooth/services/fast_pair/fp_storage/fp_storage_manager.c, subsys/bluetooth/services/fast_pair/fp_storage/fp_storage_pn.c, subsys/bluetooth/services/fast_pair/fp_storage/fp_storage_user_reset_action.c, subsys/bluetooth/services/fast_pair/fp_storage/include_priv/fp_storage_manager.h, tests/subsys/bluetooth/fast_pair/storage/factory_reset/src/main.c
Removes bt_fast_pair_factory_reset_user_action_prepare weak function definition that could earlier be overriden to prepare for the oncoming Fast Pair factory reset.
Jira: NCSDK-25394
=> bluetooth: fast_pair: Remove the factory reset prepare user action

samples/bluetooth/broadcast_config_tool/src/main.c
- Fixes bug where pba_data was not cleared on bct stop.
- OCT-3151
=> samples: broadcast_config_tool: Clear pba_data on stop

.github/workflows/stale.yml
There are tons of stale PRs with the 'DNM' tag due to stale manifest changes, so allow closing stale PRs with the 'DNM' label.
=> ci: stale: allow DNM

.github/workflows/docbuild.yml
This option will make CI less verbose, showing only warnings/errors.
=> ci: docbuild: run Sphinx in quiet mode

doc/_zoomin/nrf.apis.tags.yml, doc/_zoomin/nrfx.apis.tags.yml, doc/_zoomin/nrfxlib.apis.tags.yml, doc/_zoomin/zephyr.apis.tags.yml
These tags will allow to change between different versions of API doc in the doc portal.
=> doc: add clustering tags for Zoomin

CODEOWNERS, subsys/zigbee/Kconfig
Make sure all choices under `ZIGBEE` have a name.
=> zigbee: name some unnamed Kconfig options

doc/nrfxlib/conf.py, west.yml
They are no longer needed as breathe has gone away.
=> manifest: pull removal of zephyr domain patches

modules/trusted-firmware-m/tfm_boards/CMakeLists.txt
This fixes an issue for the nRF54L15 when it is build with TFM and the hardware unique key library is also used. The hardware unique key library uses PSA headers which means that we need to make sure that the nrf_security generated headers are being included before the other PSA related headers.
This links the nrf_security target before it links the TFM platform targets.
Ref: NCSDK-29514
test_crypto: PR-672
=> tfm: Fix nrf54L15 linking with nrf_security targets

lib/hw_unique_key/hw_unique_key_cracen.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_kmu.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.h
To `CRACEN_KMU_KEY_USAGE_*`.
This undoes some of the changes made in
5b6a3a6354d1dd377d36b99e989c973914542836.
Keep the original naming that is also used in tests. It also makes more sense as this is a CRACEN-specific thing.
=> nrf_security: cracen: rename KMU_METADATA_SCHEME_*

samples/bluetooth/peripheral_uart/README.rst
Based on UX testing results (NCSIDB 1358).
Specified the default device name.
=> doc: peripheral UART device name fix

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c
Remove unused variable to fix compiler warning.
=> cracen: Remove unused variable

include/sdfw/sdfw_services/ssf_client_notif.h, subsys/sdfw_services/ssf_client_notif.c
A call to notif register or deregister before initializing would attempt to take an invalid semaphore. Leading to a crash.
This adds an initialized check to notif register and deregister.
Ref: NCSDK-29017
=> subsys: sdfw_services: fix crash when taking invalid semaphore

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/sms/Kconfig, lib/sms/sms.c, lib/sms/sms_submit.c, samples/cellular/sms/sample.yaml, tests/lib/sms/src/sms_test.c, tests/lib/sms/testcase.yaml
Clients can decide if they want to receive SMS-STATUS-REPORT with CONFIG_SMS_STATUS_REPORT.
When this is not set, SMS registration is done with AT+CNMI=3,2,0,0 so delivery reports are not sent to this library, and SMS header will not include a bit to request SMS delivery reports.
By default, this is ON so the change is backwards compatible.
Jira: NCSDK-29508
=> lib: sms: Possibility to disable status reports

samples/ipc/ipc_service/src/main.c
CONFIG_BOARD does not allow to distiguish between cores.
=> samples: ipc: ipc_service: show full board and target name

west.yml
Update babblesim from version v2.2 to v2.3
Including updates for the phy conversion script,
(including removing dependendy on gnu-awk)
An updated libcrypto with new APIs for CCM packet
encryption/decryption.
And some other components minor updates.
Note it remains fully backwards compatible.
=> manifest: Update pointer babblesim to v2.3

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/modem/lte_lc.h, include/modem/modem_info.h, lib/modem_info/modem_info.c, tests/lib/modem_info/src/main.c
AT Command Reference Guide has been updated based on how the modem behaves. Doing corresponding update to app side, i.e., modem_info and lte_link_control.
Jira: TNSW-62531
=> lib: modem_info: Update RSRP/RSRQ calculation

scripts/quarantine_zephyr.yaml
The scenarios are added due to missing support for nrf54l15pdk or bugs on nrf54l15dk on sdk-zephyr.
The issues will fix later.
=> scripts: quarantine_zephyr: Add quarantine for scenarios on nrf54l15{p}dk

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/conn_time_sync/src/controller_time_nrf52.c, samples/bluetooth/conn_time_sync/src/controller_time_nrf53_app.c, samples/bluetooth/iso_time_sync/src/controller_time_nrf52.c, samples/bluetooth/iso_time_sync/src/controller_time_nrf53_app.c
Fixes an unintentional toggle upon RTC wrap caused by a PPI channel being enabled.
Thanks to @ludvigsj for reporting it.
=> Samples: Bluetooth: iso_time_sync: Remove unintentional toggle upon RTC wrap

subsys/mpsl/init/mpsl_init.c
Enable application to have several modules requesting constlat. Right now, on 54l, mpsl just writes to NRF_POWER directly, disregarding what other users in system might want constlat to be.
This PR prepares for a soon commig nrfxlib PR where mpsl will rather use mpsl_constlat_request_callback to turn on constlat. If NRFX_POWER modules is enabled in config,
it will use nrfx_power_constlat_mode_request,
if not it will use NRF_POWER diretly.
=> mpsl: enable use of nrfx_power_constlat_mode

samples/benchmarks/coremark/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/benchmarks/coremark/sample.yaml, scripts/quarantine_integration.yaml
Removed support for the nRF54L15 PDK target in the CoreMark sample.
=> samples: benchmarks: coremark: remove support for nrf54l15pdk

CODEOWNERS
`/subsys/net/openthread/rpc` should be owned by
`@nrfconnect/ncs-protocols-serialization` group
=> codeowners: change owners of `/subsys/net/openthread/rpc`

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/net/http_server/src/main.c
Creating a server socket for one family type may fail while the other family type works. Do not terminate with FATAL_ERROR() in this case.
=> samples: net: http_server: No fatal error for setup_server

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/smp_svr/sysbuild.conf, samples/cellular/smp_svr/sysbuild/mcuboot/prj.conf
Add sysbuild configuration files.
This enables the sample to be properly built with overlay-serial.conf and nrf9160dk_nrf52840_mcumgr_srv.overlay.
IRIS-9783
=> samples: cellular: smp_svr: add sysbuild files

doc/nrf/includes/sample_fem_support.txt
The `sample_fem_support.txt` include file links to Zephyr documentation for information on configuring devicetree. This updates the link to point to the Configuring devicetree page in the nRF Connect SDK documentation instead.
Also makes other small improvements to the file.
=> doc: Update devictree link in include file

subsys/nrf_security/CMakeLists.txt, subsys/nrf_security/Kconfig
It was no longer enabled after the upmerge.
Ref: NCSDK-29546
=> nrf_security: fix broken builtin key support for nrf54h

.github/workflows/validate-pip-requirements-fixed-file.yml
Bring back pip-requirements.yml pipeline with limited functions which fo not require using secrets
=> actions: Re-enable pip requirements pipeline

samples/bluetooth/iso_time_sync/README.rst, samples/bluetooth/iso_time_sync/src/iso_rx.c, samples/bluetooth/iso_time_sync/src/iso_tx.c, samples/bluetooth/iso_time_sync/src/timed_led_toggle.c
This commit fixes the following:
* ~~Sample now uses absolute pin for GPIOTE, to make the LED work on platforms where the LEDs are not on port 0 (such as nRF54L15).~~
* This has been removed from this PR, as this is fixed in the already existing #17639 
* Fix a bug in the initialization of `init_val` in the GPIOTE task used for the LED, where it would always be initialized to `NRF_GPIOTE_INITIAL_VALUE_HIGH` and not take the dt_flags into account. This made the LED toggle with inverted polarity on platforms where the LEDs are active high.
* Change the LED used when `CONFIG_LED_TOGGLE_IMMEDIATELY_ON_SEND_OR_RECEIVE` is enabled to not conflict with the LED used to display synchronized toggling.
* Update references to LED numbers in the README to match the actual sample behavior.
=> Samples: Bluetooth: ISO time sync fixes

doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/modem/lte_lc.h, samples/cellular/modem_shell/src/link/link.h, samples/cellular/modem_shell/src/link/link_settings.c, samples/cellular/modem_shell/src/link/link_settings.h, samples/cellular/modem_shell/src/link/link_shell.c
Deprecate factory reset API. This functionality is trivial to implement and doesn't need a whole API within the Link Controller.
=> lib: lte_link_control: deprecate factory reset

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/ble_peripheral_lbs_coex/src/lb_service_handler.c
Align the usage of BT_LE_ADV_CONN inline declaration helper with the rest of the NCS.
Also global declaration of adv_params is optimised and cause bus failures during runtime, thus adding only lbs_conn_id to discern mesh services.
=> samples: bluetooth: mesh: align usage of BT_LE_ADV_CONN with NCS

doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/modem/lte_lc.h, samples/cellular/modem_shell/src/link/link.h, samples/cellular/modem_shell/src/link/link_shell.c
Deprecate reduced mobility API. This functionality is trivial to implement and doesn't need a whole API within the Link Controller.
=> lib: lte_link_control: deprecate reduced mobility

samples/nrf_rpc/protocols_serialization/client/src/ot_shell.c
Commit removes active_tlvs command.
Command requires binary data format those are inconvenient for human typing interface.
=> samples: protocol_serialization: remove active_tlvs command

subsys/bluetooth/rpc/host/bt_rpc_gatt_host.c
The __ASSERT() instruction used assignment instead of comparison operator, causing a failure when receiving a Write Request/Write Command.
=> bluetooth: rpc: fix assert condition

samples/bluetooth/fast_pair/locator_tag/src/dfu.c, west.yml
Replace the custom mcumgr SMP BT UUIDs with the ones available
in the smp_bt.h header file from Zephyr.
Jira: NCSDK-28457
Signed-off-by: Mateusz Kapala <mateusz.kapala@nordicsemi.no>
=> samples: bluetooth: fast_pair: locator_tag: Use SMP UUIDs from header

samples/cellular/modem_shell/src/link/link_shell.c
When passing enum type into scanf, there will be a compilation warning:
```
nrf/samples/cellular/modem_shell/src/link/link_shell.c:2046:69: warning:
format '%hu' expects argument of type 'short unsigned int *',
but argument 3 has type 'enum link_reduced_mobility_mode *' [-Wformat=]
2046 | ret = nrf_modem_at_scanf("AT%REDMOB?", "%%REDMOB: %hu", &mode);
```
Regression from PR #17579. I don't know why twister didn't capture this for that PR.
=> samples: cellular: modem_shell: redmob: Don't pass enum to scanf

applications/nrf_desktop/src/modules/Kconfig.config_channel
Change removes outdated part of configuration channel DFU Kconfig option's help.
=> applications: nrf_desktop: Remove outdated Kconfig help

scripts/tools-versions-darwin.yml, scripts/tools-versions-linux.yml, scripts/tools-versions-win10.yml
These compilers are not used in automation, only referenced in docs.
We can make customer bundle smaller by omitting them.
This PR replaces https://github.com/nrfconnect/sdk-nrf/pull/17718
Discussion about this change is in `NRFU-1082`
=> tools: remove aarch64-zephyr-elf and x86_64-zephyr-elf

subsys/net/openthread/rpc/client/ot_rpc_thread.c
This caused unit test failures on QEMU Cortex M3.
=> net: openthread: rpc: fix uninitialized variable

tests/benchmarks/power_consumption/timer_waiting/src/driver_test.c
Remove blinking LED, use k_busy_wait instead of looping to keep CPU busy, change timings.
=> tests: benchmarks: timer_waiting: modify test scenario

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/bootloader/Kconfig, subsys/bootloader/cmake/debug_keys.cmake
Removes non-workable possibility for configuring signing key using
either environmental or command-line variable (SB_SIGNING_KEY_FILE).
This has never worked.
ref.: NCSDK-28124
similar change was done for the sysbuild (#16154)
=> childimage/NSIB: Remove non-functional environmental key support

samples/bluetooth/conn_time_sync/README.rst, samples/bluetooth/conn_time_sync/src/timed_led_toggle.c
This commit fixes the following:
* Fix a bug in the initialization of `init_val` in the GPIOTE task used for the LED, where it would always be initialized to `NRF_GPIOTE_INITIAL_VALUE_HIGH` and not take the dt_flags into account. This made the LED toggle with inverted polarity on platforms where the LEDs are active high.
* Update references to LED numbers in the README to match the actual sample behavior.
=> Samples: Bluetooth: conn time sync fix

samples/tfm/tfm_psa_template/prj.conf
The Initial Attestation service requires RNG config to be able to attest the boot seed claim.
=> samples: tfm: add RNG config for tfm_psa_template

subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/hci_driver.c, subsys/bluetooth/controller/hci_internal.c
- Added Kconfig entries needed to enable Channel Sounding support in SDC
- Added HCI command handlers for Channel Sounding related commands
- Added supported commands and supported features set when Channel Sounding is enabled
- Added memory allocation for Channel Sounding in hci_driver.c
=> Bluetooth: Controller: Enable Channel Sounding support

modules/memfault-firmware-sdk/config/memfault_metrics_heartbeat_extra.def, modules/memfault-firmware-sdk/memfault_lte_metrics.c
* Add debug level logging when modem_info calls fail.
* Add collection of cell ID and tracking area code metrics when a cell update event is received.
=> Memfault LTE metrics improvements

tests/benchmarks/multicore/idle/CMakeLists.txt, tests/benchmarks/multicore/idle_gpio/CMakeLists.txt, tests/benchmarks/multicore/idle_outside_of_main/CMakeLists.txt, tests/benchmarks/multicore/idle_spim/CMakeLists.txt, tests/benchmarks/multicore/idle_spim/testcase.yaml, tests/benchmarks/multicore/idle_twim/CMakeLists.txt, tests/benchmarks/multicore/idle_twim/testcase.yaml, tests/benchmarks/multicore/idle_uarte/CMakeLists.txt, tests/benchmarks/multicore/idle_uarte/testcase.yaml, tests/benchmarks/multicore/idle_with_pwm/src/main.c
Align CMakeLists.txt between related tests.
Remove unused FILE_SUFFIX.
Fix misleading comment in a source code.
=> tests: benchmarks: multicore: Fixes to power-state tests

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_dfu.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_external_memory.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_push.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/suit/smp_transfer/README.rst
Added documentation for SUIT DFU cache partitions
and how to use them to push detached payloads for DFU to the device.
=> doc: suit: Push scenario and DFU caches documentation

boards/shields/coverage_support/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, boards/shields/coverage_support/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
Needed to receive all data from DK.
=> boards: shields: coverage_support: force hw-flow-control at coverage

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c
Protected scheme only support AES key. Add check for this when provisioning the CRACEN KMU. Returns PSA not supported error on fail.
=> nrf_security: cracen PSA: Protected scheme check for AES key

modules/trusted-firmware-m/tfm_boards/common/crypto_keys.c
- Default NS partition/client ID has changed with TF-M v2.1, and must be aligned in this file
=> tf-m: crypto keys: Update default TFM_NS_PARTITION_ID

samples/bluetooth/iso_time_sync/src/bis_receiver.c
For BIS 1 -> BIT(0) needs to be set, however this was setting BIT(1). Fix this so it syncs to correct BIS.
=> bluetooth: samples: iso_time_sync: Fix BIS bitfield

CODEOWNERS, scripts/ci/codeowners.py
In order to handle missing entries in the CODEOWNERS file properly, a              
few changes are introduced in both the CODEOWNERS file and the script              
that checks for missing entries (scripts/ci/codeowners.py):                        
- Add an '*' entry in the CODEOWNERS file. This ensures that GitHub                
assigns someone (in this case ncs-code-owners) by default whenever a             
PR introduces a file that is not covered by an entry in the file                 
- Remove the top-level section entries (i.e. applications/, samples/,              
subsys/, etc). This is so that the script can catch missing files,               
since catch-all entries like those mask those missing files                      
- Skip the processing of the '*' top-level entry in …
=> CODEOWNERS: Improve missing entry detection

doc/nrf/releases_and_maturity/known_issues.rst
This commit updates the Matter SDK revision to include fixes that improve the reliability of multicast message delivery by enabling MLDv2 reporting.
Btw. After this is merged i do plan to backport the fix to NCS 2.6 and 2.7 branches as well.
=> manifest: sdk-connectedhomeip: Fix reliability issues with multicasts

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/central_bas/sample.yaml, samples/bluetooth/central_hr_coded/sample.yaml, samples/bluetooth/multiple_adv_sets/sample.yaml, samples/bluetooth/peripheral_bms/sample.yaml, samples/bluetooth/peripheral_cgms/sample.yaml, samples/bluetooth/peripheral_cts_client/sample.yaml, samples/bluetooth/peripheral_gatt_dm/sample.yaml, samples/bluetooth/peripheral_hr_coded/sample.yaml, samples/bluetooth/peripheral_mds/README.rst, samples/bluetooth/peripheral_mds/memfault_config/memfault_metrics_heartbeat_config.def, samples/bluetooth/peripheral_mds/memfault_config/memfault_trace_reason_user_config.def, samples/bluetooth/peripheral_mds/sample.yaml, samples/bluetooth/peripheral_mds/src/main.c, samples/bluetooth/peripheral_nfc_pairing/README.rst, samples/bluetooth/peripheral_nfc_pairing/sample.yaml, samples/bluetooth/peripheral_power_profiling/README.rst, samples/bluetooth/peripheral_power_profiling/sample.yaml, samples/bluetooth/peripheral_rscs/sample.yaml, samples/bluetooth/shell_bt_nus/sample.yaml, samples/bluetooth/throughput/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/bluetooth/throughput/sample.yaml, samples/bluetooth/throughput/src/main.c
Added nRF54L15DK support in the following samples:
- central_bas
- central_hr_coded
- multiple_adv_sets
- peripheral_bms
- peripheral_cgms
- peripheral_cts_client
- peripheral_gatt_dm
- peripheral_hr_coded
- peripheral_mds
- peripheral_nfc_pairing
- peripheral_power_profiling
- peripheral_rscs
- shell_bt_nus
- throughput
=> samples: bluetooth: Add support for nRF54L15DK

subsys/net/lib/nrf_cloud/coap/src/nrfc_dtls.c
Use the function nrf_cloud_sec_tag_get() to obtain the sec tag for the CoAP DTLS connection.
This was missed in the original PR: https://github.com/nrfconnect/sdk-nrf/pull/16374
IRIS-9080
=> net: lib: nrf_cloud_coap: use nrf_cloud_sec_tag_get for dtls

subsys/suit/mci/include/suit_mci.h, subsys/suit/platform/sdfw/src/suit_plat_authenticate.c, tests/subsys/suit/common/mci_test/mci_test.c, tests/subsys/suit/unit/mocks/include/mock_suit_mci.h
In some cases, there is a need to use volatile keys for signing manifests. In such case, it is the PSA API that sets the key ID value, not the manifest.
Add a simple MCI API helper function to return the assigned key ID and handlers inside manifest authentication routines.
=> suit: Return volatile key IDs from MCI

applications/nrf5340_audio/src/audio/audio_datapath.c, applications/nrf5340_audio/src/modules/audio_i2s.c, applications/nrf5340_audio/src/modules/audio_i2s.h
- Fixes bug where the calculation for HFClock was entered incorrectly
- Old value: 39854
- New correct value: 39845.888
- OCT-NONE
=> applications: nrf5340_audio: Fix HFClock calculation

doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
These migrations are related to deprecations, so they are not yet mandatory since the deprecated functions are still available.
Move to recommended changes instead.
=> doc: nrf: move LLC migrations from mandatory to recommended

subsys/dm/timeslot_queue.c
The distance check to the next timeslot was broken, resulting in a condition which would always be false. This means that in total, there would always be a single timeslot be scheduled for the ranging, at most. Fixed this check.
=> dm: Fix timeslot distance check

CODEOWNERS, tests/benchmarks/multicore/idle_outside_of_main/testcase.yaml, tests/benchmarks/multicore/idle_spim/testcase.yaml, tests/benchmarks/multicore/idle_twim/testcase.yaml, tests/benchmarks/multicore/idle_uarte/testcase.yaml
It is used to filter tests for execution with power measurements.
=> tests: benchmarks: multicore: add tag ppk_power_measure

modules/memfault-firmware-sdk/memfault_location_metrics.c
Add a missing argument when setting neighbor cell count having both cellular and Wi-Fi locationing enabled.
=> modules: memfault: Fix location metric for Wi-Fi

applications/nrf_desktop/src/modules/Kconfig.usb_state, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change implies nRF SoC flash partial erase for USB next stack. This is done to improve stability of the USB next stack. The partial erase feature workarounds device errors that might be reported by Windows USB host in Device Manager if USB cable is connected while erasing secondary image slot in the background.
Jira: NCSDK-29573
=> applications: nrf_desktop: Imply partial flash erase for USB next

CODEOWNERS
Change owner from myself to the whole team.
=> CODEOWNERS: transfer ownership to `ncs-ll-ursus`

CODEOWNERS
Add the ownership of all the RST files and txt files to the relevant techwriter groups assigned to the different software teams
=> doc: Update the ownership of RST files

CODEOWNERS
List owners from general to more specific.
=> CODEOWNERS: fix owners for tests/benchmarks/multicore/idle

subsys/mgmt/suitfu/src/suitfu_mgmt_img.c
Until now even when in recovery firmware, the image group marked the main application image as active.
This caused that the mobile application was not able to recover the device - the confirm button for the new application image was greyed out.
This commit marks the main application as inactive when running the recovery firmware.
=> mgmt: suitfu: Make main image inactive in recovery

west.yml
Update suit-processor to a revision that accepts both 17 and 20 as suit-install key.
=> manifest: Update suit-processor revision

subsys/nrf_security/src/drivers/cracen/Kconfig
=> nrf_security: cracen: do not load microcode on nRF54L20

lib/edge_impulse/CMakeLists.txt
The Edge Impulse key API header must be in the header for the downloading of a private project to be done properly.
=> lib: edge_impulse: fix api key header

doc/nrf/releases_and_maturity/known_issues.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Adds an issue which appeared as a result of the fix in DRGN-21085. The issue is fixed for NCS 2.8.0
=> doc: Add known issue for DRGN-23231 (deadlock on link loss)

subsys/mgmt/suitfu/Kconfig
Change automatically enables SUITFU bootloader information hook if bootloader information support is enabled. This is done to ensure that proper bootloader would be reported over SMP.
Jira: NCSDK-29287
=> mgmt: suitfu: Automatically enable SUITFU bootloader information hook

cmake/sysbuild/suit.cmake, cmake/sysbuild/suit_utilities.cmake, config/suit/templates/nrf54h20/default/v1/rad_recovery_envelope.yaml.jinja2, samples/suit/smp_transfer/sample.yaml
This PR addresses two functionalities:
1) Allowing putting the SUIT DFU cache partitions in the DFU zip file, so that the file matches the agreed format
2) Separating the dfu_cache partitions used when building the main application from the dfu_cache partitions created when buillding the recovery images
=> suit: cache partitions in zip file && separate files for recovery image cache partitions

config/suit/templates/nrf54h20/default/v1/app_envelope.yaml.jinja2, config/suit/templates/nrf54h20/default/v1/app_recovery_envelope.yaml.jinja2, config/suit/templates/nrf54h20/default/v1/rad_envelope.yaml.jinja2, config/suit/templates/nrf54h20/default/v1/rad_recovery_envelope.yaml.jinja2, config/suit/templates/nrf54h20/default/v1/root_with_binary_nordic_top.yaml.jinja2, config/suit/templates/nrf54h20/matter/v1/app_envelope.yaml.jinja2, config/suit/templates/nrf54h20/matter/v1/rad_envelope.yaml.jinja2, config/suit/templates/nrf54h20/matter/v1/root_with_binary_nordic_top.yaml.jinja2, samples/suit/smp_transfer/suit/nrf54h20/app_envelope_extflash.yaml.jinja2, samples/suit/smp_transfer/suit/nrf54h20/rad_envelope_extflash.yaml.jinja2, samples/suit/smp_transfer/suit/nrf54h20/root_with_binary_nordic_top_extflash.yaml.jinja2, west.yml
With the SUIT manifest specification rev 27 the SUIT install key has changed.
Add logic inside templates, so a proper value for a proper build context will be chosen.
test-sdk-nrf: test-nrf-pr-17828
=> suit: Add support for new suit-install key

include/esb.h, samples/peripheral/radio_test/src/radio_cmd.c, samples/peripheral/radio_test/src/radio_test.c, subsys/esb/esb.c
Adds support for new 4Mbit PHY configurations including
`RADIO_MODE_MODE_Nrf_4Mbit_0BT6` and `RADIO_MODE_MODE_Nrf_4Mbit_0BT4`.
=> ESB, Radio Test: Add support for new 4Mbit mode configurations 

subsys/net/lib/nrf_cloud/src/nrf_cloud_download.c
A build error occurred when a project used CoAP downloads (for P-GPS) and also FOTA_DOWNLOAD, but not NRF_CLOUD_FOTA_POLL. Add guard for the required Kconfig.
IRIS-9685
=> net: lib: nrf_cloud: add proper coap fota dependency guard

doc/nrf/libraries/security/identity_key.rst, doc/nrf/links.txt, doc/nrf/security/tfm.rst, modules/trusted-firmware-m/Kconfig, modules/trusted-firmware-m/tfm_boards/common/tfm_hal_platform.c, samples/tfm/provisioning_image/README.rst
Add documentation for TF-M provisioning and error messages for missing provisioning with CONFIG_TFM_NRF_PROVISIONING.
=> tfm: Improve use-case for missing provisioning

scripts/docker/Dockerfile
Additionally, remove libffi7 which is included in bundle.
=> docker: Bump nrfutil-device version to 2.6.4

samples/nrf_rpc/protocols_serialization/client/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/nrf_rpc/protocols_serialization/client/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/nrf_rpc/protocols_serialization/server/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/nrf_rpc/protocols_serialization/server/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, samples/nrf_rpc/protocols_serialization/server/snippets/log_rpc/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/nrf_rpc/protocols_serialization/server/snippets/log_rpc/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay
Use all SRAM and RRAM space for the application in the protocols serialization samples.
=> samples: nrf_rpc: protocols_serialization: use all [SR]RAM

subsys/esb/esb.c
Configured the ESB to use a 16-bit preamble for
Nrf_2Mbit, Ble_2Mbit and Nrf_4Mbit modes.
=> esb: Set 16-bit preamble for 2 Mbit and 4 Mbit bitrate

samples/cellular/location/README.rst
Added missing Wi-Fi support Kconfig options to documentation.
=> samples: cellular: location: add missing Kconfig options to doc

samples/peripheral/radio_test/src/radio_test.c
Configured the Radio Test to use a 16-bit preamble for 4Mbit modes.
=> samples: radio_test: Set 16-bit preamble for 2 Mbit and 4Mbit bitrate

samples/wifi/radio_test/sample.yaml
Add build support for 54H/L targets for radio_test sample.
=> samples: wifi: radio_test: Add 54H/L support to radio test sample

subsys/nrf_security/Kconfig.legacy
-Adding a prompt for MBEDTLS_THREADING_C makes the configuration
user settable in case this needs to be disabled under very
special circumstances.
=> crypto: Add prompt for MBEDTLS_THREADING_C

samples/bluetooth/broadcast_config_tool/README.rst, samples/bluetooth/broadcast_config_tool/include/broadcast_config_tool.h, samples/bluetooth/broadcast_config_tool/src/main.c
OCT-3115
The static inline functions in broadcast_config_tool.h has been moved to upstream Zephyr. We need to remove the functions from broadcast_config_tool.h and use these instead.
=> applications: nrf5340_audio: Change source of inline functions to Zephyr

scripts/ci/tags.yaml
Changes in subsys/trusted_storage will now trigger sidewalk samples build in CI.
=> ci: Add subsys/trusted_storage to sidewalk dependancies

samples/dect/dect_phy/dect_shell/src/dect/dect_phy_shell.c
dect rx -command didn't work due to wrong initial optind index for getopt().
=> samples: dect: dect_phy: dect_shell: rx cmd fix

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/nrf_cloud.h, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_coap, subsys/net/lib/nrf_cloud/src/nrf_cloud_info.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_jwt.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_sec_tag.c
Separate sec tags used for JWT generation and DTLS. This makes it possible to point the DTLS sec tag to a dev tag to get decrypted DTLS traffic in modem traces.
=> net: nrf_cloud_coap: Separate nrf cloud coap sec tags

tests/benchmarks/multicore/idle_gpio/testcase.yaml
To prevent using boards with shields.
=> tests: benchmarks: multicore: idle_gpio: use gpio_loopback fixture

applications/machine_learning/configuration/nrf54h20dk_nrf54h20_cpuapp/app.overlay, applications/machine_learning/remote/boards/nrf54h20dk_nrf54h20_cpuppr.overlay, applications/machine_learning/sysbuild/ipc_radio/boards/nrf54h20dk_nrf54h20_cpurad.overlay, applications/matter_bridge/boards/nrf5340dk_nrf5340_cpuapp.overlay, applications/matter_bridge/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/nrf_modem_lib/nrf_modem_lib.c, samples/bluetooth/peripheral_uart/boards/nrf54h20dk_nrf54h20_cpurad.overlay, samples/matter/common/dts/nrf54h20/nrf54h20_cpuapp_memory_map.dtsi, samples/matter/common/dts/nrf54h20/nrf54h20_cpurad_memory_map.dtsi, samples/openthread/cli/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, samples/peripheral/radio_test/boards/nrf54h20dk_nrf54h20_cpurad.overlay, samples/suit/smp_transfer/sysbuild/nrf54h20dk_nrf54h20_memory_map.dtsi, snippets/nordic-bt-rpc/boards/nrf54h20dk_nrf54h20-mem-map-move.dtsi, subsys/nrf_security/Kconfig, subsys/nrf_security/src/drivers/cracen/psa_driver.Kconfig, tests/subsys/dfu/dfu_target/suit/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/subsys/suit/cache_pool_digest/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/subsys/suit/cache_sink/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/subsys/suit/flash_sink/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, west.yml
Pull in updated Nordic owned memory bindings and align NCS applications, samples, snippets, and tests. `nordic,access` replaces the `perm-*` properties.
=> devicetree: Use the nordic,access property

subsys/net/lib/nrf70_fw_ext/CMakeLists.txt, subsys/net/lib/nrf70_fw_ext/Kconfig, west.yml
NCS uses nRF70 blobs from `sdk-nrfxlib` directly without the need for `west blobs fetch hal_nordic` but upstream still uses the `west blobs fetch hal_nordic` which picks up from `sdk-nrfxlib` but a different ~branch `nrf70-devel`~ directory `upstream_fw_blobs` instead of `ncs_fw_blobs`.
=> wifi: Fix nRF70 FW blobs strategy

cmake/sysbuild/zip.cmake
Fixes issues whereby slot IDs began at 0 instead of 1
=> cmake: sysbuild: zip: Fix slot offsets in non-directXIP mode

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/ble_peripheral_lbs_coex/sample.yaml, samples/bluetooth/mesh/chat/sample.yaml, samples/bluetooth/mesh/dfu/distributor/README.rst, samples/bluetooth/mesh/dfu/distributor/sample.yaml, samples/bluetooth/mesh/dfu/target/sample.yaml, samples/bluetooth/mesh/light/README.rst, samples/bluetooth/mesh/light/sample.yaml, samples/bluetooth/mesh/light_ctrl/sample.yaml, samples/bluetooth/mesh/light_dimmer/sample.yaml, samples/bluetooth/mesh/light_switch/sample.yaml, samples/bluetooth/mesh/sensor_client/sample.yaml, samples/bluetooth/mesh/sensor_server/sample.yaml, samples/bluetooth/mesh/silvair_enocean/sample.yaml, tests/subsys/emds/emds_api/testcase.yaml, tests/subsys/emds/emds_flash/testcase.yaml
Removed support for the nrf54l15pdk, as we now have support for the nrf54l15dk. This is done both for the Bluetooth Mesh samples and the EMDS tests.
=> Bluetooth: Mesh: Removed support for nrf54l15pdk

CODEOWNERS
Add missing doc entries for RST ownership  in the code owner file
=> doc: Add missing doc entries in the code owner file

CODEOWNERS
To avoid requestiog of approvals for every bluetooth sample from ncs-si-muffin or ncs-dragoon add code owner to particular samples.
=> samples: bluetooth: Add code owners to particular samples

doc/nrf/installation/updating.rst
Added a link to the list of shells supported by nRF Util's toolchain manager command. NRFU-1283.
=> doc: updating: add link to supported shells

samples/bluetooth/direction_finding_connectionless_tx/README.rst, samples/bluetooth/direction_finding_connectionless_tx/overlay-aoa.conf, samples/bluetooth/direction_finding_connectionless_tx/overlay-aod.conf, samples/bluetooth/direction_finding_connectionless_tx/prj.conf, samples/bluetooth/direction_finding_connectionless_tx/sample.yaml
Use Angle of Arrival mode as default for Direction Finding Connectionless Tx sample.
Related to DRGN-23590
=> samples: Bluetooth: Default Direction Finding Connectionless Tx to AoA

subsys/suit/plat_err/include/suit_plat_err.h, subsys/suit/platform/sdfw/src/suit_plat_copy.c, subsys/suit/platform/src/suit_plat_error_convert.c, subsys/suit/stream/stream_sinks/src/suit_sdfw_recovery_sink.c, subsys/suit/stream/stream_sinks/src/suit_sdfw_sink.c, subsys/suit/utils/include/suit_plat_mem_util.h, subsys/suit/utils/src/suit_plat_mem_util.c
https://nordicsemi.atlassian.net/browse/NCSDK-29561
After tests of previous implementation and discussion how the behavior of SDFW and SDFW Recovery update should work, few changes were identified as necessary.
This PR provides changes needed in SDFW and SDFW Recovery sinks and error handling in the platform.
Accompanying changes in sdk-secdom are needed as well - https://github.com/nrfconnect/sdk-secdom/pull/939.
=> suit: Rework SDFW and SDFW Recovery sinks

doc/nrf/protocols/matter/end_product/versioning.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, west.yml
Switch the Matter software version string from
APP_VERSION_TWEAK_STRING to APP_VERSION_EXTENDED_STRING.
=> matter: include EXTRAVERSION in Matter software version string

samples/bluetooth/fast_pair/locator_tag/configuration/pm_static_nrf54l15dk_nrf54l15_cpuapp.yml
Updated the partition map for the nRF54L15 DK in the Fast Pair Locator Tag sample to provide more space for the MCUboot bootloader.
Ref: NCSDK-29504
=> samples: bluetooth: fast_pair: locator tag: update nrf54l15 partitions

subsys/mpsl/cx/1wire/mpsl_cx_1wire.c, subsys/mpsl/cx/3wire/mpsl_cx_3wire.c
These files use NRF_DT_GPIOTE_INST which is provided by soc_nrf_common.h. 
Include this as it is not implicitly included on bsim platforms.
=> mpsl: cx: Fix include dependency for 1wire and 3wire coex drivers

tests/benchmarks/multicore/idle_uarte/remote/src/main.c
Do not wakeup radio as it make current measurements noisy.
=> tests: benchmarks: multicore: idle_uarte: radio sleeps forever

.github/test-spec.yml
Prevent scope optimization, force to run all integration tests.
=> test-spec: force full testing for cmake and sysbuild changes

tests/benchmarks/multicore/idle_spim/remote/src/main.c, tests/benchmarks/multicore/idle_twim/remote/src/main.c
Do not wakeup radio as it make current measurements noisy.
=> tests: benchmarks: multicore: idle_twim: radio sleeps forever

applications/nrf_desktop/Kconfig.ble, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change conditionally implies CONFIG_BT_CONN_TX_NOTIFY_WQ to workaround the MPSL flash synchronization known issue.
Jira: NCSDK-29354
=> applications: nrf_desktop: Imply CONFIG_BT_CONN_TX_NOTIFY_WQ

samples/openthread/cli/harness-thci/nRF_Connect_SDK_11_12.py, samples/openthread/cli/harness-thci/nRF_Connect_SDK_13_14.py
Reverting name change intialize -> initalize. To fix thread harness issues.
=> samples: openthread: revert spellcheck fix for THCI

doc/nrf/protocols/matter/getting_started/low_power_configuration.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/common/src/Kconfig, samples/matter/common/src/board/board.cpp, samples/matter/lock/sample.yaml, samples/matter/smoke_co_alarm/sample.yaml, samples/matter/window_covering/sample.yaml
Added Kconfig that allows to disable LEDs initialization and created a configuration that uses it for nRF54L15. This is required for the power measurement purposes.
=> samples: matter: Created configuration with LEDs disabled

applications/nrf_desktop/src/modules/Kconfig.caf_settings_loader.default
Switched to using the Zephyr Memory Storage (ZMS) instead of Non-Volatile Storage (NVS) for all devices that uses the RRAM non-volatile memory (currently only the nRF54L15).
Jira: NCSDK-29634
=> applications: nrf_desktop: Switch to ZMS for RRAM-based devices

subsys/partition_manager/pm.yml.zms
During the last Zephyr upmerge the includes changed from autoconf.h to <zephyr/autoconf.h>
Fix this for the zms partition table
=> pm: zms: fix autoconf.h include

applications/nrf5340_audio/broadcast_sink/main.c, applications/nrf5340_audio/src/audio/audio_datapath.c
- If presentation delay is set to 0, use the default and print a warning.
- OCT-2952
=> applications: nrf5340_audio: Handle PD=0 in broadcast_sink

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/fast_pair/input_device/prj.conf, samples/bluetooth/fast_pair/locator_tag/configuration/prj.conf, samples/bluetooth/fast_pair/locator_tag/configuration/prj_release.conf
Change enables CONFIG_BT_CONN_TX_NOTIFY_WQ to work around the MPSL flash synchronization timeout known issue.
Jira: NCSDK-29354
=> samples: fast_pair: locator_tag: Enable CONFIG_BT_CONN_TX_NOTIFY_WQ

doc/nrf/libraries/security/trusted_storage.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Updated docs for trusted storage library to contain ZMS support in addition to NVS
=> doc: trusted storage lib doc update with zms

subsys/bluetooth/controller/hci_internal.c, west.yml
Enables the local support bit for the LE Power Class 1 Feature
=> bluetooth: Add support for LE Power Class 1 Feature

samples/nfc/writable_ndef_msg/boards/nrf54h20dk_nrf54h20_cpuapp.conf, samples/nfc/writable_ndef_msg/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/nfc/writable_ndef_msg/src/ndef_file_m.c
These changes introduce the use of the ZMS file system instead of NVS for the nRF54 series.
Ref: NCSDK-29636
=> samples: nfc: writable_ndef_msg: Migrate from NVS to ZMS for nRF54

samples/nrf_rpc/protocols_serialization/client/src/ot_shell.c
Fix argument parsing for "ot thread" shell command to be able to properly stop thread.
=> samples: protocols_serialization: client: fix "ot thread"

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_customize_dfu.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_customize_qsg.rst
This commit updates this part of the documentation taking into account changes for 2.8.0 release
=> doc: SUIT DFU customize guide fixes for 2.8.0

west.yml
Sidewalk update for NCS v2.8.0
This is a placeholder task for update Sidewalk revision in west manifest with the following changes:
nrf54L15 DK support
v1.17 lbiraries
=> manifest: sidewalk update

applications/nrf_desktop/doc/usb_state.rst, applications/nrf_desktop/src/modules/Kconfig.usb_state, applications/nrf_desktop/src/modules/usb_state.c
Removes the extra USB thread on nRF54H as it's no longer needed. Sets the CONFIG_UDC_DWC2_USBHS_VBUS_READY_TIMEOUT timeout to allow the usbd_enable() function to return error if the USB cable is not connected.
Jira: NCSDK-28000
Jira: NCSDK-28381
=> applications: nrf_desktop: Remove extra USB thread on nRF54H

samples/matter/common/src/persistent_storage/persistent_storage_shell.cpp, samples/matter/light_bulb/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/light_bulb/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/light_switch/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/light_switch/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/lock/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/lock/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/smoke_co_alarm/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp_internal.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/thermostat/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/thermostat/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/window_covering/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/window_covering/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, west.yml
After introducing mutexes in Mbed TLS, there are sometimes bus faults visible on the nRF54L15. Temporarily it has to be disabled as a workaround, to bring back the stable behavior.
By the way pulled connectedhomeip fix increasing the CHIP stack size for nRF54L15.
=> samples: matter: Disabled Mbed TLS threading for nRF54L15

applications/sdp/gpio/CMakeLists.txt, applications/sdp/gpio/src/hrt/hrt.c, applications/sdp/gpio/src/hrt/hrt.h, applications/sdp/gpio/src/hrt/hrt.s, applications/sdp/gpio/src/main.c
Depends on:
- https://github.com/nrfconnect/sdk-nrf/pull/17838
- https://github.com/nrfconnect/sdk-nrf/pull/17638
=> applications: sdp: gpio: add Hard RealTime IRQ code

boards/nordic/thingy91x/thingy91x_nrf5340_pm_static.yml, boards/nordic/thingy91x/thingy91x_nrf5340_pm_static_ext_flash.yml
This patch adds the secondary_1 partitions to thingy91x/nrf53 to ensure a working mcuboot setup.
=> boards: thingy91x: add secondary_1 partitions

samples/crypto/aes_gcm/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/crypto/ecjpake/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/crypto/eddsa/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/crypto/pbkdf2/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/crypto/spake2p/boards/nrf5340dk_nrf5340_cpuapp.conf, samples/crypto/spake2p/boards/nrf54l15dk_nrf54l15_cpuapp.conf
A few crypto sample targets were missing proper mbed TLS heap configuration.
test_crypto: PR-682
=> samples: crypto: Added missing mbed TLS heap configuration

subsys/nrf_security/src/psa_crypto_driver_wrappers.c
Added switch case required for supporting platform fw encryption keys for cracen.
Ref: NCSDK-29672
=> nrf_security: Support symmetric decryption with cracen key

snippets/emulated-nrf54l05/README.rst, snippets/emulated-nrf54l05/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, snippets/emulated-nrf54l05/snippet.yml, snippets/emulated-nrf54l10/README.rst, snippets/emulated-nrf54l10/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, snippets/emulated-nrf54l10/snippet.yml
Note that this is *not* compatible with enabling FLPR.
=> snippets: emulate the nRF54L05 and the nRF54L10 RAM and RRAM sizes

doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf54l/snippets.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added nRF54L05 and nRF54L10 snippets
=> doc: Added nRF54L05 and nRF54L10 snippets

applications/matter_bridge/doc/adding_bridged_matter_device.rst, applications/matter_bridge/src/simulated_providers/simulated_humidity_sensor_data_provider.cpp, applications/matter_bridge/src/simulated_providers/simulated_humidity_sensor_data_provider.h, applications/matter_bridge/src/simulated_providers/simulated_temperature_sensor_data_provider.cpp, applications/matter_bridge/src/simulated_providers/simulated_temperature_sensor_data_provider.h, samples/matter/common/src/bridge/matter_bridged_device.h
After the last Zephyr up-merge, getting rand number from the timer callback leads to the crypto assert.
Added scheduling rand operation to the application event.
=> applications: Fixed assert on Matter bridge

subsys/bluetooth/mesh/rpl.c, west.yml
- Adds an empty `bt_mesh_rpl_pending_store_all_nodes` function to `rpl.c` to avoid compilation errors when EMDS is enabled.
- Updates sdk-zephyr manifest
=> Pull upstream fixes for Mesh

config/suit/templates/nrf54h20/matter/v1/app_envelope.yaml.jinja2, config/suit/templates/nrf54h20/matter/v1/rad_envelope.yaml.jinja2, samples/matter/lock/Kconfig.sysbuild, samples/matter/template/Kconfig.sysbuild, sysbuild/CMakeLists.txt, west.yml
Enabled DFU over Matter OTA for nRF54H20 target.
It works using dfu_target_suit and dfu_multi_target implementations.
=> samples: matter: Enable Matter OTA on nRF54H20

doc/nrf/protocols/matter/end_product/security.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, west.yml
Device Attestation Certificates private key can be migrated from factory data to Key Management Unit (KMU) on nRF54L SoC series now in Matter samples.
Added support and documentation.
=> samples: matter: Add support for migrating DAC to KMU fo NRF54L

samples/bluetooth/broadcast_config_tool/README.rst, samples/bluetooth/broadcast_config_tool/src/main.c
OCT-3163
For ease of testing and verification we need to create a function that will generate and send test data in the BCT.
This should use the same mechanism as the normal way of sending data, namely the sent_cb to send more data.
=> applications: nrf5340_audio: Create function for using test data in BCT

applications/nrf_desktop/src/modules/Kconfig.hotfixes, applications/nrf_desktop/src/modules/constlat.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
PR introduces constlat module updates:
- switches to using nrfx_power_constlat APIs
- adds missing CAF PM events dependency
- prevents enabling module on nRF54H/nRF54L SoC - these SoCs are currently not supported
Jira: NCSDK-29534
=> applications: nrf_desktop: Constlat module updates

applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/app.overlay, applications/nrf_desktop/src/modules/Kconfig.dvfs, applications/nrf_desktop/src/modules/dvfs.c
Use clock api in nrf_desktop dvfs module.
Use notification handler to notify correct
completion of DVFS.
JIRA: NCSDK-29351
=> applications: nrf_desktop: Use clock api for DVFS

subsys/nrf_security/Kconfig
Removes a prompt, type and duplicated help text from this symbol as this is an override symbol only
=> nrf_security: Fix MBEDTLS_CFG_FILE Kconfig symbol

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/bluetooth/Kconfig.discovery, subsys/bluetooth/gatt_dm.c
Moves host calls in discovery manager callbacks to be scheduled in a separate work queue to improve robustness.
=> Bluetooth: GATT DM: Schedule host cbs in work q

subsys/nrf_security/Kconfig.legacy
This adds deprecation-warnings for enablement of legacy APIs when using nrf_security
=> Deprecate legacy Mbed TLS in Kconfigs

subsys/bluetooth/controller/Kconfig
Currently SDC supports CS as an experimental feature. It is already marked as experimental in public documentation but it should also be marked as EXPERIMENTAL in Kconfig
=> bluetooth: mark CS as experimental in Kconfig

applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_broadcast.c, applications/nrf5340_audio/src/bluetooth/bt_rendering_and_capture/volume/bt_vol_ctlr.c, applications/nrf5340_audio/src/bluetooth/bt_rendering_and_capture/volume/bt_vol_rend.c, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.h, applications/nrf5340_audio/src/modules/lc3_streamer.c, applications/nrf5340_audio/src/modules/lc3_streamer.h, samples/bluetooth/broadcast_config_tool/src/main.c
- OCT-3180
- Removed all BT_AUDIO_BROADCAST_CODE_SIZE. Ref: https://github.com/zephyrproject-rtos/zephyr/pull/80217
=> Applications: Audio: Resolved coverity issues

west.yml
Pull rebased histories for Zephyr and mcuboot.
=> manifest: Pull rebased OSS repositories

scripts/docker/Dockerfile
Backport 74ec8d27eb9ac759e32080753dc883fd82402159 from #18135.
=> [Backport v2.8-branch] dokcer: Bump nrfutil device to version 2.7.2

samples/mpsl/timeslot/README.rst, samples/mpsl/timeslot/sample.yaml, samples/mpsl/timeslot/src/main.c
The sample application didn't build for both 54H20 and 54L15 SoCs. There are different timer instances used by MPSL for new SoCs. Also the logs ofload ISR in 54H/54L are done by different peripheral.
The commit fixes the build issues.
By the way the commit enables the sample to be run in CI and adds missing information to the readme file.
=> samples: mpsl: timeslot: Fix build errors for 54L and 54H SoCs

samples/nrf_rpc/protocols_serialization/server/Kconfig
Default to using host crypto that employs PSA crypto API when SMP gets enabled. This removes the dependency on oberon and reduces the code size when using both "ble" and "openthread" snippets since OpenThread already uses PSA.
Increase BT long work stack size when PSA is used by BLE to avoid stack overflows.
=> samples: protocols_serialization: server: use PSA for SMP

applications/sdp/gpio/CMakeLists.txt, cmake/sdp.cmake, cmake/sdp_asm_check.cmake, cmake/sdp_asm_install.cmake
Add two new CMake targets: `asm_check` and `asm_update`.
`asm_check` will check if content of the already existing ASM file and the new generated by `asm_gen` are the same. If they are the same, the newly generated is removed. If they are different, a warning is printed to update ASM file, if the new one should be included in build.
`asm_update` will replace the already existing ASM file with the new one generated by `asm_gen`. If the new ASM file does not exist, a warning is printed.
I created two new CMake scripts (`sdp_asm_check` and `sdp_asm_update`) for these targets because I could not find a way to pass the logic to `add_custom_target` directly/in line. If there is a way of doing that without creating new CMake scripts, please let me know.
In the last commit `asm_check` is added as …
=> Nrfx 6388 assembly mgmt west build

samples/matter/light_bulb/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/light_switch/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/lock/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/smoke_co_alarm/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp_internal.conf, samples/matter/thermostat/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/window_covering/boards/nrf54l15dk_nrf54l15_cpuapp.conf, subsys/nrf_security/src/utils/nrf_security_mutexes.c
We noticed that if the Mbed TLS 3.6.x uses the mutexes and WAITQ_DUMB is selected as the Simple linked-list wait_q implementation is selected then various CRACEN operations sometimes lead to BUS_FAULT while trying to take a mutex.
As a workaround we need to switch to the scalable wait_q implementation, which increases ROM usage by ~2k, but works fine with CRACEN.
=> samples: matter: Fix random crashes while Cracen is used

samples/nrf_rpc/protocols_serialization/client/sample.yaml, samples/nrf_rpc/protocols_serialization/client/snippets/nfc/nfc.conf, samples/nrf_rpc/protocols_serialization/server/sample.yaml, samples/nrf_rpc/protocols_serialization/server/snippets/nfc/nfc.conf
Backport f43fe95c89648b7f8175dfdffee6f2fb3fddc637~2..f43fe95c89648b7f8175dfdffee6f2fb3fddc637 from #18177.
=> [Backport v2.8-branch] samples: nrf_rpc: protocols_serialization: remove nrf54l pdk support

samples/openthread/cli/harness-thci/nRF_Connect_SDK_11_12.py, samples/openthread/cli/harness-thci/nRF_Connect_SDK_13_14.py
Backport b3ee5e317651aaff6e128b1ed0a481df001536b4 from #18189.
=> [Backport v2.8-branch] samples: openthread: fix csl period in THCI

tests/benchmarks/power_consumption/adc/testcase.yaml, tests/benchmarks/power_consumption/adc_async/testcase.yaml, tests/benchmarks/power_consumption/flash/testcase.yaml, tests/benchmarks/power_consumption/gpio/testcase.yaml, tests/benchmarks/power_consumption/i2c/testcase.yaml, tests/benchmarks/power_consumption/spi/testcase.yaml, tests/benchmarks/power_consumption/uart_async/testcase.yaml, tests/benchmarks/power_consumption/uart_polling/testcase.yaml
Backport 24aadff4ec330a06e2a76a10639bf5a3698512f8 from #18187.
=> [Backport v2.8-branch] tests: benchmarks: power_consumption: Specify test methods.

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_architecture_memory.rst
Backport 1db926cc88199f49b2c6b9715e524807ae04664d from #17966.
=> [Backport v2.8-branch] doc: Updated 54H memory arch doc

samples/mpsl/timeslot/README.rst, samples/mpsl/timeslot/sample.yaml, samples/mpsl/timeslot/src/main.c
Backport e9520fbc67b8bbeef4b170e863e1a9cba327eceb from #18186.
=> [Backport v2.8-branch] samples: mpsl: timeslot: Fix build errors for 54L and 54H SoCs

applications/nrf_desktop/src/modules/Kconfig.dvfs
Backport 95e5c94517a04c2942fb6e26a8352b4114be5995 from #18194.
=> [Backport v2.8-branch] applications: nrf_desktop: Mark DVFS module as experimental

samples/wifi/sta/src/main.c
Backport f94bd7be086965ed813e98f0f8740518c86407df from #18185.
=> [Backport v2.8-branch] samples: wifi: sta: Fix EK(SPI) build

doc/nrf/libraries/nfc/rpc/index.rst, samples/nrf_rpc/protocols_serialization/client/README.rst, samples/nrf_rpc/protocols_serialization/server/README.rst
Backport 39ac3feb73c5eb15b88c475400ce478f131425b4 from #18155.
=> [Backport v2.8-branch] doc: add nfc rpc

samples/matter/light_bulb/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/light_switch/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/lock/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/smoke_co_alarm/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp_internal.conf, samples/matter/thermostat/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/window_covering/boards/nrf54l15dk_nrf54l15_cpuapp.conf, subsys/nrf_security/src/utils/nrf_security_mutexes.c
Backport d290578a5c17cbbb23578f299c7afc329dc7af25~2..d290578a5c17cbbb23578f299c7afc329dc7af25 from #18181.
=> [Backport v2.8-branch] samples: matter: Fix random crashes while Cracen is used

applications/sdp/gpio/CMakeLists.txt, cmake/sdp.cmake, cmake/sdp_asm_check.cmake, cmake/sdp_asm_install.cmake
Backport b24793a7c02e5ae7a72bb74b32e06e70a89ab402~2..b24793a7c02e5ae7a72bb74b32e06e70a89ab402 from #18018.
=> [Backport v2.8-branch] Nrfx 6388 assembly mgmt west build

samples/cellular/nrf_cloud_multi_service/overlay-nrf7002ek-wifi-scan-only.conf
Backport 82cfff1033b0e708a6809f1ff0b2c8ea4ea6c24a from #18236.
=> [Backport v2.8-branch] samples: mss: Fix Wi-Fi scan

applications/nrf5340_audio/sample.yaml, applications/nrf5340_audio/src/bluetooth/bt_management/dfu/bt_mgmt_dfu.c
- To fit the dynamic name into the advertising data we need to put it in the scan response.
- OCT-3068
=> applications: nrf5340_audio: Use scan reponse for DFU name

samples/bluetooth/fast_pair/locator_tag/CMakeLists.txt, samples/bluetooth/fast_pair/locator_tag/sysbuild/CMakeLists.txt
Set APPLICATION_CONFIG_DIR in samples's CMakeLists.txt (previously set through sysbuild). This is done to allow building sample after copy-pasting the source directory to another location.
Jira: NCSDK-29876
=> samples: fast_pair: locator_tag: Update setting APPLICATION_CONFIG_DIR

applications/nrf_desktop/CMakeLists.txt, applications/nrf_desktop/sysbuild/CMakeLists.txt
Set APPLICATION_CONFIG_DIR in application's CMakeLists.txt (previously was done through sysbuild). This is done to allow building application after copy-pasting the source directory to another location.
Jira: NCSDK-29876
=> applications: nrf_desktop: Update way of setting APPLICATION_CONFIG_DIR

samples/bluetooth/fast_pair/locator_tag/CMakeLists.txt, samples/bluetooth/fast_pair/locator_tag/sysbuild/CMakeLists.txt
Backport 01262c72f4e6543868c611db223901d8049f533a from #18202.
=> [Backport v2.8-branch] samples: fast_pair: locator_tag: Update setting APPLICATION_CONFIG_DIR

doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf54l/zms.rst
Backport 8ff112b0cc0783f7512fd1852b785f9114ddf0ed from #18174.
=> [Backport v2.8-branch] doc: add general ZMS info

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_external_memory.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_push.rst, samples/suit/smp_transfer/suit/nrf54h20/app_envelope_extflash.yaml.jinja2, samples/suit/smp_transfer/suit/nrf54h20/rad_envelope_extflash.yaml.jinja2, samples/suit/smp_transfer/suit/nrf54h20/root_with_binary_nordic_top_extflash.yaml.jinja2
Backport b5a6fdee6e217d1e1ae746ab0d3af1b801baa438 from #18054.
=> [Backport v2.8-branch] doc: Update FWU with external memory docs

applications/nrf5340_audio/sample.yaml, applications/nrf5340_audio/src/bluetooth/bt_management/dfu/bt_mgmt_dfu.c
Backport dca02acf4400709d3199fc9d8057d4f32072b2f2 from #18169.
=> [Backport v2.8-branch] applications: nrf5340_audio: Use scan reponse for DFU name

subsys/mgmt/suitfu/Kconfig, subsys/mgmt/suitfu/src/suitfu_mgmt.c, subsys/suit/cache/src/suit_dfu_cache_helpers.c, subsys/suit/cache/src/suit_dfu_cache_internal.h, subsys/suit/cache/src/suit_dfu_cache_rw.c
Add Kconfig to skip SUIT DFU module initialization on system startup.
=> suitfu: Allow to skip DFU initialization

samples/bluetooth/fast_pair/locator_tag/README.rst
Removed stale note from docs as DFU is already supported in the locator_tag sample.
=> samples: bluetooth: fast_pair: locator_tag: Remove stale note from docs

samples/bluetooth/fast_pair/locator_tag/README.rst
Backport 8a409bb942f5e778f08ce29b46bea6b68ec1ae0f from #18256.
=> [Backport v2.8-branch] samples: bluetooth: fast_pair: locator_tag: Remove stale note from docs

CODEOWNERS, scripts/west-commands.yml, scripts/west_commands/ncs-provision.py
This PR introduces very basic integration with temporary provisioning script which allows to provision ED29915 keys to the nRF54l15 SoC KMU slots.
This solution is temporary, aimed to provide a way of work with KMU for NCS 2.8.0.
=> west provisioning for nrf54l15

subsys/mgmt/suitfu/Kconfig, subsys/mgmt/suitfu/src/suitfu_mgmt.c, subsys/suit/cache/src/suit_dfu_cache_helpers.c, subsys/suit/cache/src/suit_dfu_cache_internal.h, subsys/suit/cache/src/suit_dfu_cache_rw.c
Backport 57e1218088634945057b8829376a8caae8442ac6 from #18126.
=> [Backport v2.8-branch] suitfu: Allow to skip DFU initialization

doc/nrf/protocols/matter/index.rst
Adds some missing version rows to the table, and hides the table itself inside a toggle to make the protocol landing page less cluttered.
=> doc: Matter: update matter version table

applications/machine_learning/sysbuild.cmake, samples/caf_sensor_manager/sysbuild.cmake, samples/event_manager_proxy/sysbuild.cmake, samples/ipc/ipc_service/sysbuild.cmake, tests/benchmarks/multicore/idle/sysbuild.cmake, tests/subsys/event_manager_proxy/sysbuild.cmake, tests/subsys/pcd/sysbuild.cmake
The image name is hard coded for dependency configuration, but when using sysbuild the image name of the default image is based on the name of the folder. This means that if sample is copied elsewhere for local modification the hard coded name may no longer match the default image name.
Improve this by using DEFAULT_IMAGE variable instead of hard coded name.
Jira: NCSDK-28028
=> sysbuild: update image specific names to use DEFAULT_IMAGE

applications/machine_learning/sysbuild.cmake, samples/caf_sensor_manager/sysbuild.cmake, samples/event_manager_proxy/sysbuild.cmake, samples/ipc/ipc_service/sysbuild.cmake, tests/benchmarks/multicore/idle/sysbuild.cmake, tests/subsys/event_manager_proxy/sysbuild.cmake, tests/subsys/pcd/sysbuild.cmake
Backport 53bebe9d9bc0430f643812334b1411a0e20a38ad from #16087.
=> [Backport v2.8-branch] sysbuild: update image specific names to use DEFAULT_IMAGE

doc/nrf/includes/wifi_credentials_shell.txt, samples/cellular/nrf_cloud_multi_service/README.rst, samples/net/http_server/README.rst, samples/wifi/shell/README.rst
`wifi_cred add` is modified now. Update the examples in samples and documentation to reflect the same.
=> treewide: Modify the `wifi_cred add` command in examples

subsys/net/lib/wifi_credentials/wifi_credentials_shell.c
There was mismatch between help screen and implementation.
=> subsys: wifi_creds: Fix help output

doc/nrf/includes/wifi_credentials_shell.txt, samples/cellular/nrf_cloud_multi_service/README.rst, samples/net/http_server/README.rst, samples/wifi/shell/README.rst
Backport d05aa8982166ac45a26773ff6e403109f8a38e29 from #18272.
=> [Backport v2.8-branch] treewide: Modify the `wifi_cred add` command in examples

applications/serial_lte_modem/src/main.c
Backport 5ea9e4212cce00ff04bdd4c12393bf20670e9a4d from #18305.
=> [Backport v2.8-branch] applications: serial_lte_modem: Fix read AT+CEREG

applications/nrf5340_audio/src/bluetooth/bt_content_control/media/bt_content_ctrl_media.c
- If a command fails in MCS, check conn status before printing error
- OCT-3182
=> applications: nrf5340_audio: Check conn for errors in MCS

applications/sdp/gpio/src/backend/backend.h, applications/sdp/gpio/src/backend/backend_mbox.c, drivers/gpio/gpio_nrfe_icmsg.c, drivers/gpio/gpio_nrfe_mbox.c, include/drivers/gpio/nrfe_gpio.h, include/sdp/nrfe_common.h
- Add MBOX improvements to ensuring that data has been read by the remote core.
- Add general structure code improvements to header files.
=> sdp: egpio: backends functionality improvements

applications/nrf5340_audio/src/bluetooth/bt_content_control/media/bt_content_ctrl_media.c
Backport 315c56a75e971ba1b4a5318d4fc600f2bfa5935b from #18306.
=> [Backport v2.8-branch] applications: nrf5340_audio: Check conn for errors in MCS

west.yml
Main changes since v2.3:
* Support for immediate RSSI measurements during abort reevaluations
* Several minor improvements in the base components, including tolerating better under-setup docker images, improved C++ compatibility, a new sanity check for problematic user provided sim_ids, and other minor improvements.
Note: Like before, bsim remains fully backwards compatible
=> manifest: Update bsim to version v2.4

doc/nrf/includes/sample_board_rows.txt, doc/nrf/protocols/thread/configuring.rst, doc/nrf/protocols/thread/overview/architectures.rst, doc/nrf/protocols/thread/overview/ot_memory.rst, doc/nrf/protocols/thread/overview/supported_features.rst
cleanup old documentation parts and add nRF54L where necessary
=> doc: openthread: cleanup and align for nRF54L

doc/nrf/includes/sample_board_rows.txt, doc/nrf/protocols/thread/configuring.rst, doc/nrf/protocols/thread/overview/architectures.rst, doc/nrf/protocols/thread/overview/ot_memory.rst, doc/nrf/protocols/thread/overview/supported_features.rst
Backport 56a2a16c79fa8f455401566eba2d12703469eebc~2..56a2a16c79fa8f455401566eba2d12703469eebc from #18311.
=> [Backport v2.8-branch] doc: openthread: cleanup and align for nRF54L

CODEOWNERS, doc/nrf/conf.py, doc/nrf/warnings.txt
It looks like the redirects extension is reporting some invalid warnings. Filter them while investigation happens.
=> doc: nrf: filter redirect warnings

tests/benchmarks/power_consumption/uart_async/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/benchmarks/power_consumption/uart_async/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/benchmarks/power_consumption/uart_async/src/driver_test.c, tests/benchmarks/power_consumption/uart_polling/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/benchmarks/power_consumption/uart_polling/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
Add zephyr,pm-device-runtime-auto for uart to use new uart PM features and reduce power consumption during test.
=> tests: benchmarks: power_consumption: uart test fixups

doc/nrf/app_dev/companion_components.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_architecture_cpu.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst
Backport 5f04936a9fa9650fca91e9761191bfc9e5f73f70 from #18142.
=> [Backport v2.8-branch] doc improvement: updates to the Using companion components page

tests/benchmarks/power_consumption/uart_async/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/benchmarks/power_consumption/uart_async/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/benchmarks/power_consumption/uart_async/src/driver_test.c, tests/benchmarks/power_consumption/uart_polling/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/benchmarks/power_consumption/uart_polling/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
Backport b01a58ad2c56ebfdfe1557777d7badabff4aed38 from #18334.
=> [Backport v2.8-branch] tests: benchmarks: power_consumption: uart test fixups

samples/bluetooth/central_smp_client/README.rst, samples/bluetooth/central_smp_client/sample.yaml, samples/bluetooth/peripheral_status/sample.yaml
Backport ae9c56ca2bfce8f04819ec382e64b02a737e7155 from #18217.
=> [Backport v2.8-branch] samples: bluetooth: Add support for nRF54L15DK

doc/nrf/external_comp/bt_fast_pair.rst, doc/nrf/external_comp/dult.rst, doc/nrf/libraries/bluetooth_services/services/fast_pair.rst, doc/nrf/libraries/others/dult.rst, doc/nrf/links.txt, samples/bluetooth/fast_pair/locator_tag/README.rst
=> doc: Document DULT motion detector feature

subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/hci_driver.c
This KConfig enables the feature bit for power class 1 in the controller.
Required if a customer wants to transmit at >10dBm
=> bluetooth: controller: hci_driver: Add option to enable power class 1

samples/nrf_compress/mcuboot_update/pm_static_nrf52840dk_nrf52840.yml, samples/nrf_compress/mcuboot_update/pm_static_nrf5340dk_nrf5340_cpuapp.yml, samples/nrf_compress/mcuboot_update/pm_static_nrf54l15dk_nrf54l15_cpuapp.yml
Backport 25fd78384b6245ea12107bcfedfa74489148d1b5 from #18310.
=> [Backport v2.8-branch] samples: nrf_compress: mcuboot_update: Update static PM files

scripts/west_commands/ncs-provision.py
Extend west ncs-provision command with option to select connected device by its serial number.
Tested using command:
`west ncs-provision upload -s nrf54l15 -k $ZEPHYR_BASE/../bootloader/mcuboot/root-ed25519.pem --dev-id <serial_number>`
Extends PR #18059
=> scripts: west_commands: extend west ncs-provision command with --dev-id

scripts/quarantine.yaml
Remove Zigbee WS from the quarantine list
=> quarantine: remove zigbee weather station from quarantine

scripts/quarantine.yaml
Backport 1c655edd98a24f884810811adfc19535a8ec6569 from #18375.
=> [Backport v2.8-branch] quarantine: remove zigbee weather station from quarantine

tests/benchmarks/power_consumption/gpio/src/driver_test.c
Backport b37e3b81de5e1bdce520620a3ca096b59a7027d3 from #18376.
=> [Backport v2.8-branch] tests: benchmarks: power_consumption: modify gpio test.

scripts/quarantine.yaml
Backport e1f2c6b39e074f9af97ad472e7d0e37cec84ea2b from #18406.
=> [Backport v2.8-branch] quarantine: add applications.machine_learning.sensor_hub

tests/benchmarks/power_consumption/spi/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/benchmarks/power_consumption/spi/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
Add overlays to enable device runtime PM for spi and reduce power consumption level during test.
=> tests: benchmarks: power_consumption: modify spi test.

samples/suit/smp_transfer/suit/nrf54h20/root_with_binary_nordic_top_extflash.yaml.jinja2
The radio and application manifests were booted in the wrong order - thus, there was an attempt to fetch
the radio manifest, before the flash_companion (started by the app manifest) was booted.
=> suit: Fix external flash template manifest

tests/benchmarks/power_consumption/spi/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/benchmarks/power_consumption/spi/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
Backport 5c0975e15af48a8e413622ffe79eb2ca672a0a71 from #18384.
=> [Backport v2.8-branch] tests: benchmarks: power_consumption: modify spi test.

doc/nrf/nrf.doxyfile.in, doc/nrfx/nrfx.doxyfile.in, doc/nrfxlib/nrfxlib.doxyfile.in, doc/zephyr/zephyr.doxyfile.in, include/net/nrf_cloud_rest.h, west.yml
We no longer insert Doxygen content in Sphinx after the removal of breathe, so let's align Doxyfiles and fix some broken references.
=> doc: remove all Doxygen rst utilities/references

scripts/west_commands/genboard/templates/nrf54l/Kconfig.board.jinja2, scripts/west_commands/genboard/west-ncs-genboard-test.sh
Fixes for nRF54L15, add NCS 2.8.0 support to test script.
=> Some fixes for west ncs-genboard

samples/bluetooth/mesh/ble_peripheral_lbs_coex/README.rst
This adds tabs with the correct LED and button numbers for nRF54 series devices to the coex sample README
=> Samples: Bluetooth: Mesh: Add nRF54 tabs to coex sample

scripts/west_commands/genboard/templates/nrf54l/Kconfig.board.jinja2, scripts/west_commands/genboard/west-ncs-genboard-test.sh
Backport 7226ffa452b578c7849dc1a1e9739a96bd49c9b8~2..7226ffa452b578c7849dc1a1e9739a96bd49c9b8 from #18228.
=> [Backport v2.8-branch] Some fixes for west ncs-genboard

samples/cellular/nrf_cloud_multi_service/overlay-nrf7002ek-wifi-scan-only.conf, scripts/quarantine.yaml
1. Revert a config change causing build error due to typo
2. Remove location + wifi tests from quarantine
=> location + Wi-Fi: Remove tests from Quarantine

samples/cellular/nrf_cloud_multi_service/overlay-nrf7002ek-wifi-scan-only.conf, scripts/quarantine.yaml
Backport 658d36e7679b2c490b77881e101f8e1e1df902c8~2..658d36e7679b2c490b77881e101f8e1e1df902c8 from #18241.
=> [Backport v2.8-branch] location + Wi-Fi: Remove tests from Quarantine

tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_boot_mode.c, tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_common.c, tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_common.h, tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_init.c, tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_recovery_boot_mode.c, tests/subsys/suit/orchestrator/orchestrator_sdfw_nrf54h20/src/test_init.c
Add tests that verify execution mode transitions as a result of suit_execution_mode_failed API call.
Ref: NCSDK-29623
=> suit: Add tests for suit_execution_mode_failed

lib/nrf_modem_lib/nrf_modem_lib_trace.c, lib/nrf_modem_lib/trace_backends/flash/flash.c
Fixes for trace flash backend.
This PR fixes an issue with the trace flash backend where there is a mismatch between the traces to read and the read trace data, such that the trace module will report that there is still trace data to read even though the backend is emptied.
=> lib: nrf_modem: fixes for flash trace backend

samples/bluetooth/mesh/light_ctrl/overlay-emds.conf, samples/bluetooth/mesh/light_ctrl/src/main.c
This fixes a problem in the light_ctrl sample where the call to `mpsl_lib_uninit` would not do anything because the required Kconfig options were not set.
* Add the required Kconfig options
* Add error checking for the call to `mpsl_lib_uninit` and a call to `log_panic` to make sure this error message is actually printed before the sample halts after pressing the EMDS button.
=> Samples: Bluetooth: Mesh: Fix MPSL uninit in light_ctrl

lib/nrf_modem_lib/nrf_modem_lib_trace.c, lib/nrf_modem_lib/trace_backends/flash/flash.c
Backport abb1738e08e66587d09801f9db9ff54ea51f6cd5 from #18348.
=> [Backport v2.8-branch] lib: nrf_modem: fixes for flash trace backend

scripts/quarantine.yaml
Twister fails, seems that the quarantine removal was premature:
https://jenkins-ncs.nordicsemi.no/job/latest/job/sdk-nrf/job/v2.8-branch/32/testReport/
Same failures expected on `main`.
=> Revert "scripts: Revert quarantine for nRF70 samples"

scripts/quarantine.yaml
Backport 7fa28ae88f77b213d16c6187d177099a54a51e1a from #18441.
=> [Backport v2.8-branch] Revert "scripts: Revert quarantine for nRF70 samples"

doc/nrf/app_dev/device_guides/nrf54l/snippets.rst
Backport 6f1c93cebeec331fecedc3f09fc9d4ac51705ead from #18242.
=> [Backport v2.8-branch] doc improvement: Add a note about TFM in the nRF54L15 snippet docs

samples/bluetooth/mesh/light_ctrl/overlay-emds.conf, samples/bluetooth/mesh/light_ctrl/src/main.c
Backport d9629b11bba6a5cb834159fae5da782ae2029952 from #18361.
=> [Backport v2.8-branch] Samples: Bluetooth: Mesh: Fix MPSL uninit in light_ctrl

subsys/net/openthread/rpc/client/ot_rpc_cli.c, subsys/net/openthread/rpc/client/ot_rpc_coap.c, subsys/net/openthread/rpc/client/ot_rpc_diag.c, subsys/net/openthread/rpc/client/ot_rpc_if.c, subsys/net/openthread/rpc/client/ot_rpc_instance.c, subsys/net/openthread/rpc/client/ot_rpc_ip6.c, subsys/net/openthread/rpc/client/ot_rpc_link.c, subsys/net/openthread/rpc/client/ot_rpc_message.c, subsys/net/openthread/rpc/client/ot_rpc_netdata.c, subsys/net/openthread/rpc/client/ot_rpc_srp_client.c, subsys/net/openthread/rpc/client/ot_rpc_thread.c, subsys/net/openthread/rpc/client/ot_rpc_udp.c, subsys/net/openthread/rpc/common/ot_rpc_common.c, subsys/net/openthread/rpc/common/ot_rpc_common.h, subsys/net/openthread/rpc/server/ot_rpc_coap.c, subsys/net/openthread/rpc/server/ot_rpc_dataset.c, subsys/net/openthread/rpc/server/ot_rpc_instance.c, subsys/net/openthread/rpc/server/ot_rpc_link.c, subsys/net/openthread/rpc/server/ot_rpc_message.c, subsys/net/openthread/rpc/server/ot_rpc_thread.c, subsys/net/openthread/rpc/server/ot_rpc_udp.c
Commit adds refactoring openthread clients to use
nrf_rpc encoders and decoders instead of zcbor API.
=> net: openthread: rpc: using nrf_rpc encoders and decoders

lib/nrf_modem_lib/nrf_modem_os_rpc.c
The nRF9280 application core has data cache with a cache line width of 32 bytes. Set the dcache alignment of ICMsg pbuf to 32 bytes to align.
=> lib: nrf_modem_lib: set data cache alignment to 32 bytes

applications/nrf_desktop/src/modules/Kconfig.hid_forward, applications/nrf_desktop/src/modules/hid_forward.c
Change allows configuring HID subscriber count in HID forward. This is needed in case a single USB HID instance is used for all of the HID peripherals connected over Bluetooth LE.
Jira: NCSDK-30002
=> applications: nrf_desktop: Add a new Kconfig for HID forward

applications/nrf_desktop/src/modules/Kconfig.hid_forward, applications/nrf_desktop/src/modules/hid_forward.c
Backport b7a15c32c6c643cf316f5a1c3937f5fdc74b7ee1 from #18435.
=> [Backport v2.8-branch] applications: nrf_desktop: Add a new Kconfig for HID forward

lib/nrf_modem_lib/nrf_modem_os_rpc.c
Backport 6a08601d3a49a52f310a271eac148edb5ac81a7b from #18432.
=> [Backport v2.8-branch] lib: nrf_modem_lib: set data cache alignment to 32 bytes

subsys/bluetooth/mesh/light_ctrl_srv.c
Previously, the scene recall was not working as expected in the
following case: If a single scene is stored when the light is on, and
then the light is dimmed/turned off by the controller, the current
scene would not be invalidated and recalling the scene would do nothing.
This commit fixes the issue by invalidating the current scene when the
light controller is re-enabled as a result of the resume timeout.
=> Bluetooth: Mesh: Fix scene recall in light_ctrl_srv

subsys/bluetooth/mesh/light_ctrl_srv.c
Backport a07804cccb31616bff75ffb0fcfb81febdbdc016 from #18390.
=> [Backport v2.8-branch] Bluetooth: Mesh: Fix scene recall in light_ctrl_srv

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cracen.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ctr_drbg.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/prng_pool.c, subsys/nrf_security/src/drivers/cracen/silexpk/target/baremetal_ba414e_with_ik/pk_baremetal.c, subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/platform/baremetal/cmdma_hw.c, subsys/nrf_security/src/threading/include/threading_alt.h, subsys/nrf_security/src/threading/threading_alt.c, subsys/nrf_security/src/utils/nrf_security_mutexes.c, subsys/nrf_security/src/utils/nrf_security_mutexes.h
Check commit messages, but this is fixes some issues with incorrect usage of mutexes.
=> nrf_security: Refactor mutexes to fix incorrect usage

subsys/partition_manager/CMakeLists.txt
Backport c1df16d8bd958e1ff60b7c8b5163456827e14928 from #18388.
=> [Backport v2.8-branch] partition_manager: Small fix to make vpr_launcher work on the nrf54l15DK

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cracen.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ctr_drbg.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/prng_pool.c, subsys/nrf_security/src/drivers/cracen/silexpk/target/baremetal_ba414e_with_ik/pk_baremetal.c, subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/platform/baremetal/cmdma_hw.c, subsys/nrf_security/src/threading/include/threading_alt.h, subsys/nrf_security/src/threading/threading_alt.c, subsys/nrf_security/src/utils/nrf_security_mutexes.c, subsys/nrf_security/src/utils/nrf_security_mutexes.h
Backport 16654ce2e3379185df257f02c5bf525f886b14b1 from #18366.
=> [Backport v2.8-branch] nrf_security: Refactor mutexes to fix incorrect usage

subsys/net/openthread/rpc/client/ot_rpc_netdata.c, subsys/net/openthread/rpc/common/ot_rpc_common.c, subsys/net/openthread/rpc/server/ot_rpc_netdata.c, tests/subsys/net/openthread/rpc/client/src/netdata_suite.c, tests/subsys/net/openthread/rpc/common/test_rpc_env.h, tests/subsys/net/openthread/rpc/server/src/ip6_suite.c, tests/subsys/net/openthread/rpc/server/src/netdata_suite.c
1. Add unit tests for APIs implemented in ot_rpc_netdata.c
2. Fix the implementation of otNetDataGet() not to use the output length if the function returns an error.
=> net: openthread: rpc: add unit tests for otNetDataXXX

tests/benchmarks/multicore/idle_with_pwm/src/main.c
Backport 7654b28a171c7a94c1293963f31556a7750ace22 from #18344.
=> [Backport v2.8-branch] NRFX-NONE: Enable device runtime PM in PWM current consumption tests

samples/crypto/psa_tls/README.rst
Backport f3ca7e56c0cf6cfbd4ebf79af0d5f931741c4c78 from #18374.
=> [Backport v2.8-branch] samples: crypto: improve psa_tls documentation

include/net/mqtt_helper.h, samples/net/mqtt/src/modules/transport/transport.c, subsys/net/lib/aws_iot/src/aws_iot.c, subsys/net/lib/aws_jobs/src/aws_jobs.c, subsys/net/lib/azure_iot_hub/src/azure_iot_hub.c, subsys/net/lib/azure_iot_hub/src/azure_iot_hub_dps.c, subsys/net/lib/mqtt_helper/mqtt_helper.c, tests/subsys/net/lib/aws_iot/src/aws_iot_test.c, tests/subsys/net/lib/azure_iot_hub/dps/src/azure_iot_hub_dps_test.c, tests/subsys/net/lib/azure_iot_hub/iot_hub/src/azure_iot_hub_test.c, tests/subsys/net/lib/mqtt_helper/src/mqtt_helper_test.c
Backport a732d97c7277d0545f72e7431f6ad9c0e6837304 from #18349.
=> [Backport v2.8-branch] net: Ensure MQTT message ID is non-zero

doc/nrf/conf.py
When building for linkcheck target, the build dir does not follow the same layout as in HTML dir, so some directories are not pre-created. This should likely be fixed better, but this workaround lets us run the target for now.
=> doc: nrf: add parents=True to doxyrunner

applications/matter_bridge/sample.yaml, samples/wifi/radio_test/sample.yaml, scripts/quarantine.yaml, west.yml
* Revert revert of quarantine, left a couple of Matter over Wi-Fi tests in Quarantine.
* Pull fixes for Wi-Fi RC1 testing issues
=> wifi: Assorted fixes for RC1 issues

west.yml
Update soc-hwmv1 to fix complilation of the UART driver when using HWMv1 (dmm.h header missing).
=> manifest: Update sdk-soc-hwmv1

doc/nrf/libraries/security/nrf_security/doc/driver_config.rst
Adding Kconfig options enabling and disabling CRACEN PSA driver features
Also fixing the precedence issue for the drivers when configuring multiple drivers
=> doc: nrf_security: fix doc for cracen driver

subsys/sdfw_services/services/suit_service/suit_update.c, subsys/suit/platform/app/src/suit_plat_version_app_specific.c
Implement a change that allows bypassing the sequence number read when only the semantic version is required.
=> samples: suit: semantic version check without sequence number read

subsys/nrf_compress/Kconfig
Lowers the default chunk size to deal with a decompression error
=> nrf_compress: Lower default chunk size

tests/benchmarks/multicore/idle_uarte/src/main.c
Enable runtime PM for UART device is CONFIG_PM_DEVICE_RUNTIME=y.
=> tests: benchmarks: multicore: idle_uarte: Enable device runtime PM

west.yml
Backport 4fff33072bdcc179d3c771e0c37961d4e14df4af from #18440.
=> [Backport v2.8-branch] manifest: Update sdk-soc-hwmv1

cmake/sysbuild/debug_keys.cmake, cmake/sysbuild/image_signing.cmake, cmake/sysbuild/sign.cmake
Fixes an issue whereby key file Kconfig values could have contained CMake variables which should have been configured to proper strings
=> cmake: sysbuild: Fix not configuring key file strings

doc/nrf/libraries/security/nrf_security/doc/driver_config.rst
Backport 829e4faee5bf7697bed67672a5491aea927a98d0 from #18464.
=> [Backport v2.8-branch] doc: nrf_security: fix doc for cracen driver

tests/benchmarks/multicore/idle_uarte/src/main.c
Backport 2e068035f234b4ff6719df9ff3a41503c9631783 from #18289.
=> [Backport v2.8-branch] tests: benchmarks: multicore: idle_uarte: Enable device runtime PM

subsys/sdfw_services/services/suit_service/suit_update.c, subsys/suit/platform/app/src/suit_plat_version_app_specific.c
Backport 1840e8c1812326720c60b7a568c1ccb6b14ad861~2..1840e8c1812326720c60b7a568c1ccb6b14ad861 from #18480.
=> [Backport v2.8-branch] samples: suit: semantic version check without sequence number read

doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
Backport 6c93155f8f1ecaff1909f2ac1c1cff6127ae38db from #18143.
=> [Backport v2.8-branch] doc improvement: Add info about ZMS in the migration guide

cmake/sysbuild/debug_keys.cmake, cmake/sysbuild/image_signing.cmake, cmake/sysbuild/sign.cmake
Backport 8729fa975dd0e32f79ded7e9af85002d68c8ed32 from #18460.
=> [Backport v2.8-branch] cmake: sysbuild: Fix not configuring key file strings

samples/bluetooth/mesh/dfu/distributor/prj.conf, samples/bluetooth/mesh/dfu/distributor/sysbuild/mcuboot.conf
This PR fixes 2 issues:
- explicitly disables RTT support in mcuboot which made JLink RTT Viewer select wrong RTT Control Block;
- explicitly enables RTT support in the sample as it turned out to not be enabled by default and is not enabled through any other Kconfig option on nRF54L15;
=> samples: bluetooth: mesh: dfu: distributor: Fix RTT support

lib/sms/sms.c
Change warning to debug log when unregistration (`AT+CNMI=0,0,0,0`) fails as SMS might have been unregistered due to `AT+CFUN=0`, or through `AT+CNMI=0,0,0,0`.
Jira: NRF91-2238
=> lib: sms: No warning log for unregistration failure

subsys/nrf_security/Kconfig.legacy
Make the MbedTLS threading configuration to depend on
the multithreading Kconfig option. The multithreading
configuration is required by both the PSA crypto
implementation which uses the Zephyr mutexes and
also by the MbedTLS legacy implementation which
may not use Zephyr mutexes for CC3XX.
=> nrf_security: Mbedlts threading dependency fix

scripts/nrf_profiler/stats_nordic.py
The `np.float` was removed (it was a deprecated alias for `float`).
=> scripts: nrf_profiler: Fix usage of deprecated `np.float`

lib/sms/sms.c
Backport a75cea7c5c1b2ecea670209458630074900b25f2 from #18403.
=> [Backport v2.8-branch] lib: sms: No warning log for unregistration failure

doc/nrf/releases_and_maturity/software_maturity.rst
Backport 7337462e4244b867a771d469ed4d4c41f80ad748 from #18438.
=> [Backport v2.8-branch] doc: fix maturity tables for crypto

scripts/nrf_profiler/stats_nordic.py
Backport 0d4e7450e27bdc501c8b8f25ae93af59602c7c93 from #18542.
=> [Backport v2.8-branch] scripts: nrf_profiler: Fix usage of deprecated `np.float`

applications/nrf_desktop/doc/hid_forward.rst, applications/nrf_desktop/doc/hid_reportq.rst, applications/nrf_desktop/modules.rst, applications/nrf_desktop/src/util/hid_reportq.h
Change introduces documentation for the HID report queue utility.
Jira: NCSDK-28433
=> applications: nrf_desktop: Add HID reportq documentation

doc/nrf/app_dev/device_guides/nrf70/features.rst, doc/nrf/links.txt
Now that we use upstream Zephyr fork for hostap, we need to document the scope of features supported in NCS as it's only a subset of upstream Zephyr.
=> doc: nrf: Add a section about hostap

subsys/nrf_security/Kconfig.legacy
Backport 1e65489985985e4c950e5e70fd54e4c69460afc7 from #18487.
=> [Backport v2.8-branch] nrf_security: Mbedlts threading dependency fix

samples/bluetooth/peripheral_power_profiling/app.overlay
Removed unused buttons from DTS, no longer wake up the application.
This ensures that these buttons are not initialized by the dk_buttons_and_leds library.
=> samples: peripheral_power_profiling: Remove unused buttons from DTS

subsys/bluetooth/services/lbs.c
The global button_state variable is only used in
CONFIG_BT_LBS_POLL_BUTTON=y.
=> bluetooth: services: lbs: button_state only used if poll is enabled

samples/bluetooth/peripheral_power_profiling/app.overlay
Backport b99305c34d77864ed2478cbd48efffe5444446cc from #18555.
=> [Backport v2.8-branch] samples: peripheral_power_profiling: Remove unused buttons from DTS

applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_conn.c, samples/bluetooth/central_bas/src/main.c, samples/bluetooth/central_hids/src/main.c, samples/bluetooth/central_nfc_pairing/src/main.c, samples/bluetooth/iso_combined_bis_and_cis/src/combined_bis_cis.c, samples/bluetooth/iso_time_sync/src/cis_central.c, samples/bluetooth/radio_notification_cb/src/central.c, subsys/bluetooth/rpc/host/bt_rpc_conn_host.c, subsys/bluetooth/scan.c, tests/bluetooth/iso/modules/central.c
Backport 9ad182c516d1c9ad329e8dd4d8b31c296cc8e99a~4..9ad182c516d1c9ad329e8dd4d8b31c296cc8e99a from #18540.
=> [Backport v2.8-branch] Bluetooth: Initialize conn passed to bt_conn_le_create to NULL

samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, west.yml
Enabled storing the DAC private key in KMU if it is available.
=> samples: matter: Enable storing DAC priv key in KMU by default.

doc/nrf/app_dev/bootloaders_dfu/mcuboot_image_compression.rst
Backport 5ac6a2b73af5792aad507169665cdd0f962b5e29 from #18560.
=> [Backport v2.8-branch] doc: nrf: app_dev: bootloaders_dfu: Fix compression static PM files

doc/nrf/releases_and_maturity/software_maturity.rst
Updated the software maturity levels in the Google Fast Pair category for the nRF54L15 device to declare the "Supported" level for the locator tag use case and its feature depedencies.
Ref: NCSDK-29887
=> doc: software_maturity: fast_pair: update status for nRF54L15

tests/drivers/pwm/gpio_loopback/Kconfig, tests/drivers/pwm/gpio_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_fast_p7_0.overlay, tests/drivers/pwm/gpio_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_fast_p7_1.overlay, tests/drivers/pwm/gpio_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_fast_p7_6.overlay, tests/drivers/pwm/gpio_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_fast_p7_7.overlay, tests/drivers/pwm/gpio_loopback/src/main.c, tests/drivers/pwm/gpio_loopback/src/test_pwm_to_gpio_loopback.c, tests/drivers/pwm/gpio_loopback/testcase.yaml
Check if fast PWM instance PWM120 is working correctly.
Check that PWM signal can be generated on all four PWM channels.
=> tests: drivers: pwm: gpio_loopback: Enable test on PWM120 instance

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, scripts/bootloader/zb_add_ota_header.py
When using a `VERSION` file to keep track of the version of a Zigbee application, `zb_add_ota_header.py` exits with an error because the `APPLICATION_VERSION_STRING` contains a version tweak, e.g. 1.0.0+3.
The issue has been raised in https://devzone.nordicsemi.com/f/nordic-q-a/102654/mcuboot-build-numbers-in-ncs/440876.
=> Zigbee: fix error when using VERSION file in Zigbee project.

tests/drivers/pwm/gpio_loopback/Kconfig, tests/drivers/pwm/gpio_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_fast_p7_0.overlay, tests/drivers/pwm/gpio_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_fast_p7_1.overlay, tests/drivers/pwm/gpio_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_fast_p7_6.overlay, tests/drivers/pwm/gpio_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_fast_p7_7.overlay, tests/drivers/pwm/gpio_loopback/src/main.c, tests/drivers/pwm/gpio_loopback/src/test_pwm_to_gpio_loopback.c, tests/drivers/pwm/gpio_loopback/testcase.yaml
Backport 1346e2b3ec21712e10aaa28dfa87312da251d490 from #18282.
=> [Backport v2.8-branch] tests: drivers: pwm: gpio_loopback: Enable test on PWM120 instance

samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, west.yml
Enabled storing the DAC private key in KMU if it is available.
=> [Backport v2.8-branch] samples: matter: Enable storing DAC priv key in KMU by default.

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, scripts/bootloader/zb_add_ota_header.py
Backport faf75378d289409567f613f0a0dcfe691f490bcc from #17424.
=> [Backport v2.8-branch] Zigbee: fix error when using VERSION file in Zigbee project.

samples/cellular/nrf_cloud_multi_service/prj.conf
The sample reads certificates while checking their validity to give better error messages.
PR #17189 optimized modem shared memory to 4kB for both TX and RX. This is too small for RX with several certificates.
Issues seen with three Root CAs causing modem to eventually crash as there is not enough RPC memory for the response.
So increasing `CONFIG_NRF_MODEM_LIB_SHMEM_RX_SIZE` by letting it use default value of ~8kB.
Jira: TNSW-64434
=> samples: cellular: nrf_cloud_multi_service: More modem RX shared memory

samples/matter/light_bulb/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/light_bulb/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_switch/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/light_switch/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/lock/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/lock/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/template/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp_internal.conf, samples/matter/template/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/thermostat/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/thermostat/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/window_covering/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/window_covering/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, west.yml
Disable `FPROTECT` in app and reenable it in mcuboot for nrf54l15
=> samples: matter: fix fprotect for mcuboot

samples/cellular/nrf_cloud_multi_service/prj.conf
Backport 1b9c39408b1f9eec99ed50ca8df18034bad8039c from #18468.
=> [Backport v2.8-branch] samples: cellular: nrf_cloud_multi_service: More modem RX shared memory

samples/bluetooth/peripheral_power_profiling/src/main.c
Disabled RAM retention saves energy in System OFF mode and can be used to showcase nRF54L15 low power consumption.
=> samples: peripheral_power_profiling: nrf54l: disable RAM retention

doc/nrf/releases_and_maturity/software_maturity.rst
Changed the software maturity level for Bluetooth Mesh to Supported for the nRF54L15.
=> doc: Mesh maturity to supported for nRF54L15

samples/matter/light_bulb/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/light_bulb/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/light_switch/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/light_switch/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/lock/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/lock/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/template/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp_internal.conf, samples/matter/template/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/thermostat/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/thermostat/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, samples/matter/window_covering/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/window_covering/sysbuild/mcuboot/boards/nrf54l15pdk_nrf54l15_cpuapp.conf, west.yml
Disable `FPROTECT` in app and reenable it in mcuboot for nrf54l15
manual backport from https://github.com/nrfconnect/sdk-nrf/pull/18580
=> [Backport v2.8-branch] samples: matter: fix fprotect for mcuboot

doc/nrf/releases_and_maturity/software_maturity.rst
Backport d697d73e6f29c2efc9de36b1c864c347d0347da5 from #18604.
=> [Backport v2.8-branch] doc: Mesh maturity to supported for nRF54L15

samples/bluetooth/peripheral_power_profiling/src/main.c
Backport 672f66c03f31adb1166132beadcdb87cb4a40f6b from #18589.
=> [Backport v2.8-branch] samples: peripheral_power_profiling: nrf54l: disable RAM retention

doc/nrf/shortcuts.txt
Updated NCP Host version shortcut to v2.2.4.
----
Changelog covered by @edmont in https://github.com/nrfconnect/sdk-nrf/pull/18192#issuecomment-2457250970
=> doc: zigbee: NCP Host v2.2.4

doc/nrf/protocols/matter/end_product/security.rst
Change default storage for DAC key on nRF54L15 to KMU.
=> doc: matter: Update default storage for DAC key on nRF54L15

doc/nrf/app_dev/companion_components.rst, doc/nrf/app_dev/device_guides/nrf54l/features.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf54l/testing_dfu.rst, doc/nrf/app_dev/device_guides/pmic/npm1300.rst, doc/nrf/links.txt, samples/matter/template/README.rst
Backport 1edc6090dfd2ba7b08f8c2baac56816e11827f9d from #18605.
=> [Backport v2.8-branch] doc: update mcuboot support info

tests/benchmarks/power_consumption/qdec/boards/nrf54h20dk_nrf54h20_cpuapp.conf, tests/benchmarks/power_consumption/qdec/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/benchmarks/power_consumption/qdec/prj.conf
Backport f09040864509648400c0eedea3868c5e1116375c from #18636.
=> [Backport v2.8-branch] tests: benchmarks: power_consumption: qdec: enable PM_DEVICE

doc/nrf/protocols/matter/end_product/security.rst
Backport e968a581947d2b81bf7c573bda3b234fb71dd12c from #18622.
=> [Backport v2.8-branch] doc: matter: Update default storage for DAC key on nRF54L15

tests/benchmarks/multicore/idle_hpu_temp_meas/testcase.yaml
Default 60s is to low and the test timed out, set to 90s
=> tests: benchmarks: increase idle HPU feature test timeout

tests/benchmarks/current_consumption/system_off/testcase.yaml
Backport 3bcaa159befe29ddf6f305378e6d55a5544ca5a8 from #18646.
=> [Backport v2.8-branch] tests: benchmarks: current_consumption: system_off: adjust test fun

doc/nrf/app_dev/config_and_build/building.rst, doc/nrf/app_dev/config_and_build/cmake/index.rst, doc/nrf/app_dev/config_and_build/config_and_build_system.rst, doc/nrf/app_dev/config_and_build/sysbuild/sysbuild_configuring_west.rst, doc/nrf/installation/install_ncs.rst
Edited sections about the nRF Connect for VSC in the general docs. Edited information about which apps sysbuild is enabled by default for. VSC-2711.
----
To be merged when the nRF Connect for VSC releases, before the final nRF Connect SDK v2.8.0 tag.
=> doc: nrfvsc: edits to general docs

doc/nrf/links.txt, doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
Updated migration guide for 2.8 with 54H info
=> doc: 54H migration guide update

subsys/partition_manager/pm.yml.tfm
With the previous method, both tfm_storage partitions (its, ps, etc) were placed "before: mcuboot_primary". This could lead to a case where mcuboot was placed after the tfm_storage partitions. To avoid this, instead place "after" mcuboot or tfm_secure.
To be a bit specific: The mentioned bug happened when I tried to build with dual bootloaders and the nRF54L15.
=> partition_manager: Make tfm storage partions avoid partitioning conflict

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/abi_compatibility.rst
Backport 83592d9790970cf7f246f70c01525e484b7845fd from #18378.
=> [Backport v2.8-branch] doc: Updated 54h gs for 2.8

doc/nrf/libraries/security/nrf_security/doc/backend_config.rst, doc/nrf/libraries/security/nrf_security/doc/configuration.rst
Documenting deprecation of legacy Mbed TLS crypto toolbox APIs
=> Deprecate legacy doc

doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_partitioning.rst, doc/nrf/links.txt, scripts/partition_manager/partition_manager.rst
Edited the structure of bootloader_partitioning page to mention memory reports of the VSC extension alongside partition_manager_report. Fixed some formatting and structure issues and typos. VSC-2712.
=> doc: bootloader_partitioning: add info about VSC

doc/nrf/app_dev/device_guides/nrf70/index.rst, doc/nrf/app_dev/device_guides/nrf70/nrf7002eb_dev_guide.rst, doc/nrf/releases_and_maturity/software_maturity.rst
Backport c69c6d9d024d70dfbc8ef9a3c3fcd6c1c7e581cd~3..c69c6d9d024d70dfbc8ef9a3c3fcd6c1c7e581cd from #18610.
=> [Backport v2.8-branch] doc: nrf70: Fix 54 Series shields

doc/nrf/app_dev/device_guides/nrf54l/building_nrf54l.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf54l/vpr_flpr.rst, doc/nrf/links.txt
Adds building article
Adds FLPR intro
=> doc: flpr and building for nrf54l15

samples/matter/template/sample.yaml
build nrf54h20 without migration manager as it is not ready for this platform yet.
=> samples: matter: build nrf54h20 without migration manager

doc/nrf/app_dev/device_guides/nrf54l/building_nrf54l.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf54l/vpr_flpr.rst, doc/nrf/links.txt
Backport 62dca66614c84c86fc82d4dda06ee04748a5b924 from #17443.
=> [Backport v2.8-branch] doc: flpr and building for nrf54l15

samples/matter/template/sample.yaml
Backport 05928ab4888950415d9f17d61d9e5100116a729a from #18667.
=> [Backport v2.8-branch] samples: matter: build nrf54h20 without migration manager

applications/connectivity_bridge/src/modules/Kconfig
Increase buffer count for Thingy:91 X to be able to capture modem traces without running out of memory.
=> applications: connectivity_bridge: Increase buffers for Thingy:91 X

applications/matter_bridge/prj.conf, applications/matter_bridge/prj_release.conf
Increase heap size to accommodate the memory required for additional bridged devices.
=> applications: matter_bridge: Increase heap size

subsys/net/openthread/rpc/server/ot_rpc_if.c
The OpenThread RPC server starts the network interface automatically on boot because otherwise no frames are delivered to the OpenThread stack.
Therefore, don't bring the interface up or down when IF_ENABLE RPC command is received. Instead, assume that IF_ENABLE command only indicates that the client has brought its interface up or down, and that it is
interested (or not) in receiving all incoming packets.
=> net: openthread: rpc: don't bring interface up in IF_ENABLE command

west.yml
[KRKNWK-19489]
* fix memory leakage on sidewlak init
* fixes for _ns board
[KRKNWK-19489]: https://nordicsemi.atlassian.net/browse/KRKNWK-19489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> manifest: update sidewalk revision

doc/nrf/libraries/caf/ble_state.rst, subsys/caf/modules/Kconfig.ble_state
Low Latency Packet Mode is not supported on the nRF53 SoC Series.
Jira: NCSDK-29545
=> caf: ble_state: Block enabling CONFIG_CAF_BLE_USE_LLPM on nRF53

subsys/net/openthread/rpc/server/ot_rpc_if.c
Backport fccaa085ed526084a1b2d5454d6d879283037569 from #18611.
=> [Backport v2.8-branch] net: openthread: rpc: don't bring interface up in IF_ENABLE command

applications/matter_bridge/prj.conf, applications/matter_bridge/prj_release.conf
Backport de74230975f08fd78e9d334b2b32d8e36b35f497 from #18662.
=> [Backport v2.8-branch] applications: matter_bridge: Increase heap size

doc/nrf/libraries/caf/ble_state.rst, subsys/caf/modules/Kconfig.ble_state
Backport fdf865b10ecc66b24e6639c2c78955c5abbd956e from #18671.
=> [Backport v2.8-branch] caf: ble_state: Block enabling CONFIG_CAF_BLE_USE_LLPM on nRF53

applications/zigbee_weather_station/README.rst, doc/nrf/includes/zigbee_deprecation.txt, doc/nrf/libraries/zigbee/index.rst, doc/nrf/libraries/zigbee/osif.rst, doc/nrf/libraries/zigbee/shell.rst, doc/nrf/libraries/zigbee/zigbee_app_utils.rst, doc/nrf/libraries/zigbee/zigbee_error_handler.rst, doc/nrf/libraries/zigbee/zigbee_fota.rst, doc/nrf/libraries/zigbee/zigbee_logger_eprxzcl.rst, doc/nrf/libraries/zigbee/zigbee_zcl_scenes.rst, doc/nrf/protocols/zigbee/architectures.rst, doc/nrf/protocols/zigbee/commissioning.rst, doc/nrf/protocols/zigbee/configuring.rst, doc/nrf/protocols/zigbee/configuring_libraries.rst, doc/nrf/protocols/zigbee/configuring_zboss_traces.rst, doc/nrf/protocols/zigbee/index.rst, doc/nrf/protocols/zigbee/memory.rst, doc/nrf/protocols/zigbee/other_ecosystems.rst, doc/nrf/protocols/zigbee/qsg.rst, doc/nrf/protocols/zigbee/supported_features.rst, doc/nrf/protocols/zigbee/tools.rst, doc/nrf/releases_and_maturity/software_maturity.rst, doc/nrf/samples/zigbee.rst, samples/zigbee/light_bulb/README.rst, samples/zigbee/light_switch/README.rst, samples/zigbee/ncp/README.rst, samples/zigbee/network_coordinator/README.rst, samples/zigbee/shell/README.rst, samples/zigbee/template/README.rst, subsys/zigbee/Kconfig
Zigbee R22 support is deprecated with nRF Connect SDK v2.8.0. This adds a note to the start of every Zigbee-related page to inform the user of this.
=> doc: zigbee: add deprecation note to all Zigbee-related pages

doc/_zoomin/ncs.tags.yml
Backport 382805bbc81b7e6ef290732d653de2a3e32c2f20 from #18462.
=> [Backport v2.8-branch] doc: update tag file for 2.8

applications/zigbee_weather_station/README.rst, doc/nrf/includes/zigbee_deprecation.txt, doc/nrf/libraries/zigbee/index.rst, doc/nrf/libraries/zigbee/osif.rst, doc/nrf/libraries/zigbee/shell.rst, doc/nrf/libraries/zigbee/zigbee_app_utils.rst, doc/nrf/libraries/zigbee/zigbee_error_handler.rst, doc/nrf/libraries/zigbee/zigbee_fota.rst, doc/nrf/libraries/zigbee/zigbee_logger_eprxzcl.rst, doc/nrf/libraries/zigbee/zigbee_zcl_scenes.rst, doc/nrf/protocols/zigbee/architectures.rst, doc/nrf/protocols/zigbee/commissioning.rst, doc/nrf/protocols/zigbee/configuring.rst, doc/nrf/protocols/zigbee/configuring_libraries.rst, doc/nrf/protocols/zigbee/configuring_zboss_traces.rst, doc/nrf/protocols/zigbee/index.rst, doc/nrf/protocols/zigbee/memory.rst, doc/nrf/protocols/zigbee/other_ecosystems.rst, doc/nrf/protocols/zigbee/qsg.rst, doc/nrf/protocols/zigbee/supported_features.rst, doc/nrf/protocols/zigbee/tools.rst, doc/nrf/releases_and_maturity/software_maturity.rst, doc/nrf/samples/zigbee.rst, samples/zigbee/light_bulb/README.rst, samples/zigbee/light_switch/README.rst, samples/zigbee/ncp/README.rst, samples/zigbee/network_coordinator/README.rst, samples/zigbee/shell/README.rst, samples/zigbee/template/README.rst, subsys/zigbee/Kconfig
Backport f952ec4a69495d42b32a95da396947622f329cb9 from #18705.
=> [Backport v2.8-branch] doc: zigbee: add deprecation note to all Zigbee-related pages

samples/peripheral/lpuart/README.rst, samples/peripheral/lpuart/boards/nrf21540dk_nrf52840.overlay, samples/peripheral/lpuart/boards/nrf52840dk_nrf52840.overlay
Backport 8013a82490e02c408cb0fa0d0fd33ca10ebdf391~2..8013a82490e02c408cb0fa0d0fd33ca10ebdf391 from #18689.
=> [Backport v2.8-branch] samples: peripheral: lpuart: Fix uart0 pins in nrf52840dk

west.yml
added nRF54l15dk fir zephyr's smp_svr's sample.yaml
=> [Backport v2.8-branch]  manifest: Update sdk-zephyr and sdk-mcuboot

drivers/serial/uart_nrf_sw_lpuart.c
Improve handling of a case when control pins do not follow the protocol behavior (e.g. they are floating). In that case driver should not trigger assert but just return to the off state.
=> drivers: serial: lpuart: Improve handling of fault cases

tests/drivers/lpuart/src/main.c
Data allocated on stack was used as a user data passed to the interrupt. By the time interrupt is handled this data could be overwritten leading to a fault. Adding static keyword to that variable.
=> tests: drivers: lpuart: Fix memory corruption

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst
Backport 1ecafe045f6d24edcbe9562a9dbb3211692f9e2a from #18733.
=> [Backport v2.8-branch] doc: Updated 54H GS guide.

tests/drivers/lpuart/src/main.c
Backport 077d132fcdd3148a2bd13c2553bf0aee1616e8e7 from #18720.
=> [Backport v2.8-branch] tests: drivers: lpuart: Fix memory corruption

drivers/serial/uart_nrf_sw_lpuart.c
Backport 31e08fd0a95a07efe01995a6fbee8c97257424cd~2..31e08fd0a95a07efe01995a6fbee8c97257424cd from #18690.
=> [Backport v2.8-branch] drivers: serial: lpuart: Improve handling of fault cases

doc/nrf/app_dev/device_guides/nrf54l/building_nrf54l.rst, doc/nrf/app_dev/device_guides/nrf54l/vpr_flpr.rst
Backport a1471e6b55e05c32bee0581ac390d965298b9689 from #18745.
=> [Backport v2.8-branch] doc: flpr support note

samples/cellular/gnss/sample.yaml, samples/cellular/http_update/application_update/sample.yaml, samples/cellular/location/sample.yaml, samples/cellular/modem_shell/sample.yaml
Replace deprecated `OVERLAY_CONFIG` with `EXTRA_CONF_FILE`. Replace deprecated `DTC_OVERLAY_FILE` with `EXTRA_DTC_OVERLAY_FILE`.
=> samples: cellular: Change deprecated OVERLAY_CONFIG and DTC_OVERLAY_FILE

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_debugging.rst
Backport a52b459a2e91f6f0373017fa3a490746903f13af from #18640.
=> [Backport v2.8-branch] doc: nrf54h20: add description of sdfw bootstatus

applications/asset_tracker_v2/overlay-nrf7002ek-wifi-scan-only.conf, samples/cellular/location/overlay-nrf700x-wifi-scan-only.conf, samples/cellular/modem_shell/overlay-nrf700x-wifi-scan-only.conf
`CONFIG_NRF_MODEM_LIB_TRACE=n` had been defined in nrf700x overlay because that was needed long time ago to make nrf91+nrf7002ek to work.
Removing it now to allow use of modem UART traces with Wi-Fi builds utilizing `nrf91-modem-trace-uart` snippet.
This change enables modem UART traces with Wi-Fi builds for nRF91 DKs and Thingy91x.
=> samples: cellular: location | modem_shell | asset_tracker_v2: Modem UART traces with Wi-Fi

subsys/net/openthread/rpc/client/ot_rpc_coap.c, subsys/net/openthread/rpc/client/ot_rpc_diag.c, subsys/net/openthread/rpc/common/ot_rpc_common.c, subsys/net/openthread/rpc/common/ot_rpc_common.h, subsys/net/openthread/rpc/server/ot_rpc_cli.c, subsys/net/openthread/rpc/server/ot_rpc_if.c, subsys/net/openthread/rpc/server/ot_rpc_instance.c, subsys/net/openthread/rpc/server/ot_rpc_ip6.c, subsys/net/openthread/rpc/server/ot_rpc_link.c, subsys/net/openthread/rpc/server/ot_rpc_message.c, subsys/net/openthread/rpc/server/ot_rpc_netdata.c, subsys/net/openthread/rpc/server/ot_rpc_thread.c, subsys/net/openthread/rpc/server/ot_rpc_udp.c
PR:
1. adds using encoders and decoders on ot servers;
2. makes using common decoding error handler
3. reverts get_uint_t refactoring to be endianness tolerant
=> net: openthread: rpc: using nrf_rpc encoders and decoders on servers

tests/benchmarks/multicore/idle_hpu_temp_meas/testcase.yaml
Backport 2c1c856bd46a2a26374a26e8e6be41271c579ab5 from #18650.
=> [Backport v2.8-branch] tests: benchmarks: increase idle HPU feature test timeout

west.yml
ANT Wireless support is transitioning to the nRF Connect SDK Add-Ons model, remove sdk-ant from the manifest for v2.8.
=> manifest: Remove ANT revision information

west.yml
Backport 5e2195616fb9554810b39352c54ec787cbcd01ba from #18751.
=> [Backport v2.8-branch] manifest: Remove ANT revision information

.github/workflows/stale.yml
- 30 days instead of 60
- Give 1 week instead of 2
- No label exemption, also delete unused issue labels (NCS does not have issues)
=> ci: stale: be more agressive

doc/nrf/links.txt
Backport 3804a4e10167b0e197ad900b67d92e84a52731f3 from #18759.
=> [Backport v2.8-branch] samples: nrf_auraconfig: Update link to lc3 data

doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_signature_keys.rst, doc/nrf/app_dev/bootloaders_dfu/qspi_xip_split_image.rst, doc/nrf/app_dev/device_guides/nrf53/building_nrf53.rst, doc/nrf/app_dev/device_guides/nrf53/qspi_xip_guide_nrf5340.rst, doc/nrf/app_dev/device_guides/nrf70/fw_patches_ext_flash.rst, doc/nrf/app_dev/device_guides/nrf91/nrf91_board_controllers.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_debugging.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/gsg_guides/nrf7002_gs.rst, doc/nrf/installation/recommended_versions.rst, doc/nrf/protocols/zigbee/qsg.rst, doc/nrf/security/ap_protect.rst, doc/nrf/shortcuts.txt, samples/nrf5340/netboot/README.rst, samples/wifi/ble_coex/README.rst, samples/wifi/shell/README.rst, samples/wifi/thread_coex/README.rst
Backport 6a8528257bedfb5b16a8ba85699e923a553f394a from #18743.
=> [Backport v2.8-branch] doc: deprecation notes for nrfjprog and nRF Command Line Tools

tests/benchmarks/multicore/idle_uarte/Kconfig, tests/benchmarks/multicore/idle_uarte/src/main.c, tests/benchmarks/multicore/idle_uarte/testcase.yaml
This test was implemented incorrectly - fix it
=> tests: benchmarks: Correct UARTE test with automatic PM

tests/benchmarks/multicore/idle_uarte/Kconfig, tests/benchmarks/multicore/idle_uarte/src/main.c, tests/benchmarks/multicore/idle_uarte/testcase.yaml
Backport db1d0d7f50f96aa7e2a0ed45fb884541eb933192 from #18767.
=> [Backport v2.8-branch] tests: benchmarks: Correct UARTE test with automatic PM

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/edge_impulse/data_forwarder/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, samples/edge_impulse/data_forwarder/sample.yaml, samples/edge_impulse/wrapper/sample.yaml
Adds support for nRF54H20DK in the data_forwarder and wrapper samples.
=> samples: edge_impulse: Add support for nRF54H20DK

doc/nrf/app_dev/device_guides/nrf54l/fota_update.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf54l/kmu_provision.rst
Added fota_update guide for nRF54l15 SoC based on the nRF52 doc.
ref.: NCSDK-29601
gen doc review link: https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18231/nrf/app_dev/device_guides/nrf54l/fota_update.html
=> doc/dev_guides/nrf54l: added fota_update & KMU guides

samples/wifi/radio_test/sample.yaml, samples/wifi/scan/sample.yaml, samples/wifi/shell/sample.yaml, samples/wifi/sta/sample.yaml
Due to missing integration platforms, 54 Series doesn't show in the auto generated table in the README.
It was broken in 8ae6472d41 ("samples: wifi: shell: Update nrf7002eb_interposer tests").
=> samples: wifi: Fix 54 series docs

samples/wifi/radio_test/sample.yaml, samples/wifi/scan/sample.yaml, samples/wifi/shell/sample.yaml, samples/wifi/sta/sample.yaml
Backport 6cb51b807ae3d36bb7f67da95db4338ad051af04 from #18797.
=> [Backport v2.8-branch] samples: wifi: Fix 54 series docs

scripts/quarantine_windows_mac.yaml
Backport db0b80c8d5ffa81b1fe528e650e6f62afc6c79ef from #18800.
=> [Backport v2.8-branch] quarantine: wifi provisioning tests on macOS

doc/nrf/libraries/nrf_rpc/nrf_rpc_uart.rst
Improve the text formatting and add "Configuration" and "Reliability" sections. Also, remove the information that nRF RPC IPC is used in BLE RPC library, as the latter can now use both IPC and UART transports.
=> doc: update nRF RPC UART documentation

include/bluetooth/services/ras.h, subsys/bluetooth/services/ras/Kconfig.ras, subsys/bluetooth/services/ras/ras_internal.h, subsys/bluetooth/services/ras/rreq/Kconfig.ras_rreq, subsys/bluetooth/services/ras/rrsp/CMakeLists.txt, subsys/bluetooth/services/ras/rrsp/Kconfig.ras_rrsp, subsys/bluetooth/services/ras/rrsp/ras_rd_buffer.c, subsys/bluetooth/services/ras/rrsp/ras_rrsp.c
Implement the ranging responder (RRSP) server role of the Ranging Service draft specification.
This allows a ranging requestor (RREQ) to retrieve channel sounding ranging data from the local device.
This implementation contains support for all mandatory features, as well as using notifications for data transfer.
=> bluetooth: services: ras: Implement Ranging Responder role of RAS

west.yml
Update sdk-nrfxlib to integrate PR-1571.
=> manifest: Update sdk-nrfxlib revision

tests/benchmarks/multicore/idle_hpu_temp_meas/testcase.yaml
90s is still not enough, increase to 120s
=> tests: benchmarks: multicore: Increase HPU test suite timeout

tests/benchmarks/peripheral_load/src/clock_thread.c, tests/benchmarks/peripheral_load/src/common.h
Extend stack for flash thread.
Wait for DVFS init in clock thread.
=> tests: benchmarks: peripheral_load: fix test

samples/openthread/cli/README.rst, samples/openthread/coprocessor/README.rst
add information that usb snippet is not supported for nrf54l15
=> samples: openthread: fix usb snippet doc for nrf54l15

tests/benchmarks/multicore/idle_hpu_temp_meas/testcase.yaml
Backport 8f38c1b38eabef8b0db5c5ea4c2be7665c09271b from #18827.
=> [Backport v2.8-branch] tests: benchmarks: multicore: Increase HPU test suite timeout

samples/openthread/cli/README.rst, samples/openthread/coprocessor/README.rst
Backport e4fbd05a4d2fefb117c7677c0533ba6f66102229 from #18831.
=> [Backport v2.8-branch] samples: openthread: fix usb snippet doc for nrf54l15

doc/nrf/links.txt, doc/nrf/releases_and_maturity/software_maturity.rst
Add NFC entry in the Maturity Level table and another table with NFC standard features support.
Additionally updated a link to a deprecated standard.
=> doc: Add NFC entry in the SW Maturity Level page.

doc/nrf/protocols/thread/certification.rst, doc/nrf/protocols/thread/overview/power_consumption.rst, doc/nrf/protocols/thread/prebuilt_libs.rst
fix wrong thread version, old build report and misaligned feature set table for Thread
=> doc: openthread: fixes for ncs 2.8.0

sysbuild/CMakeLists.txt, west.yml
Combined backport of https://github.com/nrfconnect/sdk-nrf/pull/18817 and https://github.com/nrfconnect/sdk-nrf/pull/18821
=> Backport sdk-zephyr and sdk-mcuboot changes (18817 && 18821)

tests/benchmarks/power_consumption/common/main.c, tests/benchmarks/power_consumption/gpio/src/driver_test.c
There should be single, short impulse at pin.
If it will be interrupted by irq at state high,
will trigger irq loop.
Additionally, do not light LED when sleeping.
=> tests: benchmarks: power_consumption: gpio: prevent irq when toggling

tests/benchmarks/power_consumption/common/main.c, tests/benchmarks/power_consumption/gpio/src/driver_test.c
Backport 35f5a4b16cccc59da3c5d251b6450992798c850a from #18851.
=> [Backport v2.8-branch] tests: benchmarks: power_consumption: gpio: prevent irq when toggling

doc/nrf/app_dev/device_guides/nrf54h.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_flpr.rst
Backport 8cb21c9371f70fa678950e5f9c21ccde79480d9c from #18781.
=> [Backport v2.8-branch] doc: Added 54H FLPR documentation

west.yml
Fix for non-working serial recovery with MCUboot configured for SHA512.
Fix for NCSDK-30244
=> manifest: Bring SHA512 fix for MCUboot serial recovery.

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_recovery.rst, samples/suit/recovery/README.rst
Backport 89e8eb76dae301361966f3d47fb45e03ceebaeb8 from #18859.
=> [Backport v2.8-branch] doc: samples: suit: Testing Steps for recovery sample

sysbuild/CMakeLists.txt
=> Fix MCUmgr support for SHA512 hashed images

scripts/quarantine_windows_mac.yaml
nanoPb generated files are not correct. seems to be conflict in Mac toolchain
=> quarantine: wifi provisioning tests on macOS

doc/nrf/links.txt, doc/nrf/releases_and_maturity/known_issues.rst
Added v2.8.0 to known issues.
----
=> doc: update known issues for NCS v2.8.0

doc/nrf/app_dev/bootloaders_dfu/dfu_tools_mcumgr_cli.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_flpr.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_smp.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_soc_binaries.rst, doc/nrf/drivers/wifi.rst, doc/nrf/links.txt, doc/nrf/protocols/bt/bt_qualification/index.rst, doc/nrf/protocols/matter/getting_started/memory_optimization.rst, doc/nrf/releases_and_maturity.rst, doc/nrf/releases_and_maturity/known_issues.rst, doc/nrf/releases_and_maturity/migration/migration_guide_1.x_to_2.x.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.4.99-cs3_to_2.6.99-cs2.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.7.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs1.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs2.rst, doc/nrf/releases_and_maturity/migration/migration_hwmv2.rst, doc/nrf/releases_and_maturity/migration/migration_sysbuild.rst, doc/nrf/releases_and_maturity/migration_guides.rst, doc/nrf/releases_and_maturity/release_notes.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.8.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/suit/flash_companion/README.rst
Add release notes for 2.8 release.
PR preview for the 2.8 migration guide - https://developer.nordicsemi.com/nRF_Connect_SDK_dev/doc/PR-18192/nrf/releases_and_maturity/migration/migration_guide_2.8.html
=> doc: Add release notes for 2.8 release

doc/nrf/links.txt, doc/nrf/releases_and_maturity/known_issues.rst
Backport 0a95881598725ccf32be2ec642f4805231f058e1 from #17997.
=> [Backport v2.8-branch] doc: update known issues for NCS v2.8.0

samples/peripheral/radio_test/src/radio_test.c
Fixed the lookup table to correctly handle byte durations in 4Mbit mode.
=> samples: radio_test: Fix lookup table with time per byte for 4Mbit mode

scripts/quarantine.yaml
=> quarantine: Remove obsolete entries

.github/workflows/docpublish.yml, .github/workflows/docremove.yml
There is a plan to deprecate developer.nordicsemi.com for hosting documentation builds. Instead we plan to use Azure storage.
=> ci: docpublish upload to azure instead of nordicsemi.com

include/bluetooth/services/ras.h, subsys/bluetooth/services/ras/rreq/CMakeLists.txt, subsys/bluetooth/services/ras/rreq/Kconfig.ras_rreq, subsys/bluetooth/services/ras/rreq/ras_rreq.c
Add implementation for Ranging Requestor, a Ranging Service client which can be used to obtain channel sounding ranging data from a Ranging Responder which operates as a Ranging Service server.
This current implementation can perform most mandatory features from the Ranging Profile/Ranging Service
specifications to alert an application of available ranging data and receive the data from the server.
Further work can be done to add support for reading the features from the server, receiving real time ranging data, aborting receive operation, adding filters for ranging data.
=> bluetooth: services: ras: Add RREQ implementation to RAS

samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
samples: wifi: radio_test: Fix crash during temp and rssi get
Get temperature and RSSI commands don't take any args, but due to
copy-paste, the code tries to parse the args, argv[1] without any NULL
or boundary checks causing a crash.
This bug is quite old but in nRF53 (and 52) the address 0x0 is a valid
address (IIRC mapped to begining of external flash), so, the conversion
to string passes, though it returns garbage but the check for the
returned value is completely unnecessary, so it doesn't matter if that
is invoked or not, because of this, the issue was hidden.
In nRF54H the address 0x0 is not mapped and is considered invalid and
leading to the crash.
=> samples: wifi: radio_test: Fix crash during temp and rssi get

samples/esb/esb_prx/sample.yaml, samples/esb/esb_ptx/sample.yaml, subsys/esb/esb.c
Fixed dynamic interrupts implementation.
Updated sample.yaml with a test case for dynamic interrupts.
=> esb: Fix dynamic interrupts usage

cmake/sysbuild/image_signing.cmake, cmake/sysbuild/image_signing_firmware_loader.cmake, cmake/sysbuild/image_signing_nrf700x.cmake, cmake/sysbuild/image_signing_split.cmake
Fixes an issue whereby the alignment was fixed to 4 bytes and not taken from DTS where the write block size alignment is stored
=> cmake: sysbuild: Fix image signing alignment not using write size

doc/nrf/releases_and_maturity/known_issues.rst
Post-release clarification of the Radio Test entry in Known Issues related to using 4 Mbit data rates in duty-cycle Tx mode, after checking the impact and fixing the bug.
=> doc: Update Known Issues - 4 Mbit data rate in Radio Test

scripts/quarantine_windows_mac.yaml
Change pattern to match `native_posix/native/64` platform.
=> quarantine: Exclude native posix on Windows

samples/dect/dect_phy/dect_shell/README.rst, samples/dect/dect_phy/dect_shell/src/dect/common/dect_app_time.c, samples/dect/dect_phy/dect_shell/src/dect/common/dect_common.h, samples/dect/dect_phy/dect_shell/src/dect/common/dect_common_pdu.c, samples/dect/dect_phy/dect_shell/src/dect/common/dect_common_settings.c, samples/dect/dect_phy/dect_shell/src/dect/common/dect_phy_common.h, samples/dect/dect_phy/dect_shell/src/dect/common/dect_phy_common_rx.c, samples/dect/dect_phy/dect_shell/src/dect/common/dect_phy_common_rx.h, samples/dect/dect_phy/dect_shell/src/dect/dect_phy_ctrl.c, samples/dect/dect_phy/dect_shell/src/dect/dect_phy_ctrl.h, samples/dect/dect_phy/dect_shell/src/dect/dect_phy_rx.c, samples/dect/dect_phy/dect_shell/src/dect/dect_phy_scan.c, samples/dect/dect_phy/dect_shell/src/dect/dect_phy_shell.c, samples/dect/dect_phy/dect_shell/src/dect/dect_phy_shell.h, samples/dect/dect_phy/dect_shell/src/dect/mac/dect_phy_mac.c, samples/dect/dect_phy/dect_shell/src/dect/mac/dect_phy_mac_client.c, samples/dect/dect_phy/dect_shell/src/dect/mac/dect_phy_mac_client.h, samples/dect/dect_phy/dect_shell/src/dect/mac/dect_phy_mac_common.h, samples/dect/dect_phy/dect_shell/src/dect/mac/dect_phy_mac_ctrl.c, samples/dect/dect_phy/dect_shell/src/dect/mac/dect_phy_mac_ctrl.h, samples/dect/dect_phy/dect_shell/src/dect/mac/dect_phy_mac_pdu.c, samples/dect/dect_phy/dect_shell/src/dect/mac/dect_phy_mac_shell.c, samples/dect/dect_phy/dect_shell/src/dect/perf/dect_phy_perf.c, samples/dect/dect_phy/dect_shell/src/dect/perf/dect_phy_perf_pdu.c, samples/dect/dect_phy/dect_shell/src/dect/ping/dect_phy_ping.c, samples/dect/dect_phy/dect_shell/src/dect/ping/dect_phy_ping_pdu.c, samples/dect/dect_phy/dect_shell/src/dect/rf_tool/dect_phy_rf_tool.c
Added a an option to send data in intervals: --interval <secs>
Additionally, in addition to given data, to include also modem temperature to data in json format: --get_mdm_temp
=> samples: dect_phy: dect_shell: mac: rach_tx: interval support

scripts/requirements-base.txt, scripts/west_commands/genboard/ncs_genboard.py, scripts/west_commands/genboard/schema.json, scripts/west_commands/genboard/west-ncs-genboard-test.sh
Use JSON-schema for input/output. This eases tool integration with other tooling as we have a standardized interface.
=> scripts: west: genboard: use JSON schema

applications/nrf_desktop/doc/settings_loader.rst, applications/nrf_desktop/src/modules/Kconfig.caf_settings_loader.default, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Enabled the ZMS file system for the nRF54H20 DK in the nRF Desktop application. All board targets with the MRAM technology now use ZMS by default.
Ref: NCSDK-30319
=> applications: nrf_desktop: enable zms for nrf54h20 DK target

subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_security.c, tests/subsys/net/lib/lwm2m_client_utils/src/security.c, tests/subsys/net/lib/lwm2m_client_utils/src/stubs.c, tests/subsys/net/lib/lwm2m_client_utils/src/stubs.h
When writing new content to security tag, clear existing information first, that might cause problems.
For example, when writing PSK, delete all certificates. When writing certificates, delete all PSK data.
=> net: lwm2m_client_utils: Clear sec_tag content when overwriting

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c
Changed ifdef for conditional platform keys header file inclusion. Now it matches the ifdef around the function name that requires the header (cracen_platform_keys_get_size).
Ref: NCSDK-29561
Note: Previous value (NRF54H_SERIES) was causing build failures, even on nrf54h20.
=> nrf_security: cracen: ifdef for file inclusion

samples/nrf_compress/mcuboot_update/README.rst
fota_update documentation was added so it can be referenced in the sample documentation.
=> samples/nrf_compress/mcuboot_update: use nRF54l doc references

cmake/sysbuild/fast_pair_hex.cmake, cmake/sysbuild/suit.cmake, cmake/sysbuild/suit_utilities.cmake, samples/bluetooth/fast_pair/input_device/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, samples/bluetooth/fast_pair/input_device/sample.yaml, subsys/bluetooth/services/fast_pair/Kconfig.fast_pair, subsys/bluetooth/services/fast_pair/fp_registration_data.c, sysbuild/CMakeLists.txt, west.yml
=> matter/fast pair: Add support for merging hex files without partition manager

applications/nrf5340_audio/src/audio/audio_datapath.c
- OCT-3204
- Resolved a calculation not considering wrapping
- Minor changes to naming and comments
=> Applications: Audio: Resolved wrapping calculation

subsys/bootloader/bl_validation/bl_validation.c
Fixes checking an offset using a wrong variable
=> bootloader: bl_validation: Fix checking wrong offset

samples/bluetooth/central_hids/sample.yaml, samples/bluetooth/peripheral_hids_keyboard/sample.yaml, samples/bluetooth/peripheral_hids_mouse/sample.yaml
Cleaned up references to the nRF54L15 PDK in Bluetooth HIDS samples.
Improved YAML test description of Bluetooth HIDS samples.
Ref: NCSDK-30332
=> samples: bluetooth: hids: clean up nRF54L15 PDK references

samples/nrf_rpc/protocols_serialization/client/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/nrf_rpc/protocols_serialization/server/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/nrf_rpc/protocols_serialization/server/src/fatal_error_trigger.c
Remove buttons forbidden due to overlapping with UART correctly, including swX aliases.
=> samples: protocols_serialization: fix button removal

applications/nrf_desktop/configuration/nrf52810dmouse_nrf52810/click_detector_def.h, applications/nrf_desktop/configuration/nrf52820dongle_nrf52820/click_detector_def.h, applications/nrf_desktop/configuration/nrf52833dk_nrf52820/click_detector_def.h, applications/nrf_desktop/configuration/nrf52833dk_nrf52833/click_detector_def.h, applications/nrf_desktop/configuration/nrf52833dongle_nrf52833/click_detector_def.h, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/click_detector_def.h, applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/click_detector_def.h, applications/nrf_desktop/configuration/nrf52840gmouse_nrf52840/click_detector_def.h, applications/nrf_desktop/configuration/nrf52dmouse_nrf52832/click_detector_def.h, applications/nrf_desktop/configuration/nrf52kbd_nrf52832/click_detector_def.h, applications/nrf_desktop/configuration/nrf5340dk_nrf5340_cpuapp/click_detector_def.h, applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/click_detector_def.h, applications/nrf_desktop/configuration/nrf54l15dk_nrf54l15_cpuapp/click_detector_def.h, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change updates click detector def files to allow using them also when Bluetooth LE peer control is disabled in the configuration. Without the change, files would need to be updated manually together with disabling Bluetooth LE peer control.
Jira: NCSDK-29721
=> applications: nrf_desktop: Update click detector def files

include/esb.h
Updated Doxygen documentation for tx_output_power parameter in esb_config structure.
Ref: NCSDK-30436
=> esb: Update Doxygen documentation for tx_output_power

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/central_hids/Kconfig, samples/bluetooth/peripheral_hids_keyboard/Kconfig, samples/bluetooth/peripheral_hids_mouse/Kconfig
Enabled the ZMS file system for the nRF54H20 DK in the Bluetooth HIDS samples. All board targets with the MRAM technology now use ZMS by default.
Ref: NCSDK-30318
=> samples: bluetooth: hids: enable zms for nRF54H20 target

doc/nrf/protocols/thread/certification.rst
Fix proposed device name for certification tests as previous one included spaces which are incorrectly parsed in some tests.
=> doc: openthread: fix device name for cert tests

subsys/net/openthread/rpc/Kconfig, subsys/net/openthread/rpc/client/ot_rpc_message.c, subsys/net/openthread/rpc/server/ot_rpc_message.c, tests/subsys/net/openthread/rpc/server/src/coap_suite.c, tests/subsys/net/openthread/rpc/server/src/common_fakes.c, tests/subsys/net/openthread/rpc/server/src/common_fakes.h, tests/subsys/net/openthread/rpc/server/src/message_suite.c
Commit adds unit tests for ot message manipulation in nrf rpc Openthread part.
=> nrf_rpc: Add test for ot_message allocations.

samples/bluetooth/fast_pair/input_device/Kconfig
Enabled the ZMS file system for the nRF54H20 DK in the Fast Pair Input Device sample. All board targets with the MRAM technology now use ZMS by default in this sample.
=> samples: fast_pair: input_device: enable zms for nRF54H20 target

doc/nrf/protocols/matter/getting_started/low_power_configuration.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/common/src/app/matter_init.cpp, samples/matter/light_switch/prj_release.conf, samples/matter/lock/prj_release.conf, samples/matter/smoke_co_alarm/prj_release.conf, samples/matter/window_covering/prj_release.conf
Enabled the RAM power-down feature to disable some RAM banks if possible. Thanks to that we can reduce power consumption.
=> samples: matter: Enable RAM power-down feature for Matter samples

scripts/tools-versions-darwin.yml, scripts/tools-versions-linux.yml, scripts/tools-versions-win10.yml
https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.17.0
Release Highlights:
-   all: Require glibc 2.28
-   arm-zephyr-eabi: includes ARMv7-R multi-libs
Signed-off-by: Thomas Stilwell <thomas.stilwell@nordicsemi.no>
=> scripts: tools-versions-*.yml: update zephyr-sdk==0.17.0

subsys/suit/orchestrator/src/suit_orchestrator_sdfw.c, tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_boot_mode.c, tests/subsys/suit/orchestrator/orchestrator_sdfw/src/test_recovery_boot_mode.c
Allow to skip suit-validate sequence in parent manifests.
Ref: NCSDK-30155
=> suit: Allow to skip suit-validate sequence

applications/matter_weather_station/app.overlay
The retained RAM partitions for diagnostic logs were changed in all other samples, but Matter weather station was accidentally missed.
=> applications: Aligned retained RAM partitions for diagnostic logs

doc/nrf/app_dev/device_guides/nrf70/nrf7002eb_dev_guide.rst
Add missing quotation marks around the shield target in Developing with nRF7002 EB guide.
NCSDK-30477
=> doc: wifi: fix typo in nRF7002 EB guide

subsys/suit/stream/stream_sinks/src/suit_ram_sink.c, tests/subsys/suit/ram_sink/src/main.c
There is not point to do so and it negatively affects SUIT boot time (+2.8ms).
Ref: NCSDK-30155
=> suit: Remove the possibility to erase RAM regions

.github/test-spec.yml
Dependency for tool's definition used for doc build. Fix dep for tools-versions: txt->yml.
=> test-spec: add dep for CI-doc-internal

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c
The NRF54H_SERIES define does not exist inside the secure domain build. So we replace this with the
CONFIG_PSA_NEED_CRACEN_PLATFORM_KEYS which exists
in the build.
=> nrf_security: Fix wrong ifdef for platform keys

doc/nrf/external_comp/nrf_cloud.rst, doc/nrf/releases_and_maturity/known_issues.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.0.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.2.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.3.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.5.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.6.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.7.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.8.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/nrf_cloud_rest_cell_location/README.rst, samples/cellular/nrf_cloud_rest_cell_location/src/main.c, samples/cellular/nrf_cloud_rest_device_message/src/main.c, samples/cellular/nrf_cloud_rest_fota/src/main.c
This patch makes it possible to build the nRF Cloud REST samples without checking the credentials. Jira: IRIS-9758
=> samples: cellular: nrf_cloud_rest_*: make credentials check optional

samples/nrf_rpc/protocols_serialization/client/src/main.c, west.yml
Pull new nRF RPC API that can be used to detect reboot of the remote. Use the API in protocols_serialization client.
=> nrf_rpc: detect reboot of the remote

samples/matter/common/src/diagnostic/diagnostic_logs_crash.h
Fix deprecation warning by replacing `z_arch_esf_t` with `struct arch_esf`.
=> samples: matter: Replace `z_arch_esf_t` with `struct arch_esf`

CODEOWNERS
Changed the documentation codeowners for Bluetooth HIDS samples.
=> CODEOWNERS: change the doc team for Bluetooth HIDS samples

doc/nrf/protocols/matter/overview/integration.rst, doc/nrf/protocols/thread/configuring.rst, doc/nrf/protocols/thread/overview/architectures.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/openthread/cli/sample.yaml, samples/openthread/coap_client/README.rst, samples/openthread/coap_client/sample.yaml, samples/openthread/coap_server/README.rst, samples/openthread/coap_server/sample.yaml
Remove support for nRF5340 TF-M in Thread and Matter over Thread.
=> samples: openthread: remove support for nrf5340 TF-M

subsys/mpsl/init/mpsl_init.c
the header isn't in "pm" but in "mpsl" folder.
=> Bluetooth: Controller: Fix mpsl_pm_utils include

CODEOWNERS
=> codeownes: Fix entry for modem_attest_token

samples/bluetooth/central_and_peripheral_hr/README.rst, samples/bluetooth/central_bas/README.rst, samples/bluetooth/central_hids/README.rst, samples/bluetooth/direct_test_mode/README.rst, samples/bluetooth/peripheral_ams_client/README.rst, samples/bluetooth/peripheral_ancs_client/README.rst, samples/bluetooth/peripheral_bms/README.rst, samples/bluetooth/peripheral_cts_client/README.rst, samples/bluetooth/peripheral_hids_keyboard/README.rst, samples/bluetooth/peripheral_power_profiling/README.rst, samples/bluetooth/peripheral_uart/README.rst
NCSDK-30523
Changing testing tool links from nRF Connect for Desktop to Bluetooth Low Energy app.
=> doc: Bluetooth samples: fix tool references

applications/nrf5340_audio/src/modules/audio_i2s.h
- Fixes misaligned comments in audio_i2s.h
- OCT-NONE
=> applications: nrf5340_audio: Fix comment in header file

samples/bluetooth/peripheral_uart/README.rst
NCSDK-29646
Updates to sample docs after comparing the testing the sample section of the getting started guide with
Testing sample steps of the Peripheral UART sample.
=> doc: Update testing steps of Peripheral UART sample

applications/serial_lte_modem/src/gnss/slm_at_gnss.c, applications/serial_lte_modem/src/gpio/slm_at_gpio.c, applications/serial_lte_modem/src/nrfcloud/slm_at_nrfcloud.c, applications/serial_lte_modem/src/slm_at_socket.c, applications/serial_lte_modem/src/twi/slm_at_twi.c
Previously, AT_CMD_CUSTOM did not correctly handle multiple commands which started the same, but were of varying length. This was fixed some time ago, so remove the workarounds in SLM.
=> applications: serial_lte_modem: Remove AT-command workarounds

samples/suit/smp_transfer/sysbuild/nrf54h20dk_nrf54h20_memory_map.dtsi
FLPR and PPR code partiotions ar not used in SUIT smp_transfer sample, so their partitions should not be included inside UICRs. Such partitions may open doors for potential vulnerabilities.
Ref: NCSDK-30017
=> suit: Remove unused memory ranges

.github/workflows/manifest.yml
The manifest action now has many more features at version 1.5.0. Update to the latest and start using a tree checkout to diff the manifest, which is compatible with split manifests.
=> actions: manifest: Align with upstream Zephyr

samples/crypto/psa_tls/src/psa_tls_functions_server.c
Added 200ms sleep after closing server socket to prevent "port in use" errors when creating a new socket.
=> samples: psa_tls: Add short delay between creating sockets
