nrfconnect/sdk-nrf

drivers/mpsl/flash_sync/flash_sync_mpsl.c
Reduce the number of log messages per flash operation from 2 to 1, making it easier to analyze complex logs that include debug information from the flash driver as well.
=> drivers: mpsl: Simplify flash operations logging

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/dect/dect_phy/dect_shell/README.rst, samples/dect/dect_phy/dect_shell/src/dect/common/dect_common.h, samples/dect/dect_phy/dect_shell/src/dect/common/dect_common_utils.c, samples/dect/dect_phy/dect_shell/src/dect/dect_phy_ctrl.c, samples/dect/dect_phy/dect_shell/src/dect/dect_phy_shell.c, samples/dect/dect_phy/dect_shell/src/dect/mac/dect_phy_mac_shell.c
Doing PHY API initialization when changing from/to band 4. 
Additionally, removing free-ISM support from code.
Note: band #4 support only with nRF9151 and modem mfw 1.0.2.
Jira: MOSH-622
=> samples: dect_phy: dect_shell: sett: band 4 support

samples/nrf_rpc/protocols_serialization/client/src/main.c, samples/nrf_rpc/protocols_serialization/client/src/ot_shell.c, samples/nrf_rpc/protocols_serialization/client/src/ot_shell.h
When server restarts, clear the flag indicating that the CLI has already been initialized on the server, so that it is re-initialized before the next otCliInputLine().
=> samples: nrf_rpc: ps: fix shell commands after server restart

samples/bluetooth/channel_sounding_ras_initiator/prj.conf
Using the FPU to accelerate floating point operations improves the runtime performance of estimate_distance() significantly.
runtime without FPU: ~13.5 ms
runtime with FPU:    ~7ms
=> samples: bluetooth: Add CONFIG_FPU to ranging requestor sample

samples/matter/light_bulb/sample.yaml, samples/matter/smoke_co_alarm/sample.yaml
In incoming release we are going to focus the most onsmoke co alarm. This PR removes our release reference sample for 2.8.0 ncs realease and adds smoke co alarm on nRF54L15 with diagnostic logs as a new reference.
=> samples: matter: Update release reference sample to 2.9.0 reference

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/peripheral_hids_mouse/sample.yaml
Added support for the nRF54L05 and the nRF54L10 board targets in the Bluetooth Peripheral HIDS mouse sample.
Ref: NCSDK-30655
=> samples: bluetooth: peripheral_hids_mouse: add support for nRF54L05/L10

doc/nrf/protocols/matter/getting_started/low_power_configuration.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, west.yml
Added information on how the Thread child timeout configuration impact the power consumption and child wake up time.
=> doc: Added info about Thread child timeout's impact

samples/bluetooth/iso_combined_bis_and_cis/sample.yaml
Added 54H20 to sample.yaml for iso_combined_bis_and_cis
=> samples: Bluetooth: 54H20 support for iso_combined_bis_and_cis sample

scripts/ci/tags.yaml
The intention is to speedup the CI plans running when updating the SoftDevice Controller and MPSL library revision. This is currently increasing the CI execution time by around 50 - 60 minutes.
Building samples and tests is unlikely to fail when the API is unchanged.
What can fail:
* Linking (undefined functions). This will likely have been caught before pushing a library update or when running tests.
* RAM/FLASH overflow because of increased static ram or flash usage. Out of experience this is unlikely to happen
Also added a missing entry for the MPSL FEM API.
=> scripts: ci: Update twister tags for SoftDevice Controller and MPSL

samples/bluetooth/nrf_auraconfig/prj.conf
- OCT-3218
- Increased terminal width to avoid https://github.com/zephyrproject-rtos/zephyr/pull/78130/
=> Samples: nRF Auracaster: Increased term width

scripts/twister/alt/zephyr/samples/sensor/accel_polling/sample.yaml
To debug rare problems with device.
=> scripts: twister: alt: extend logs for samples/sensor/accel_polling

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/fast_pair/locator_tag/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf
Enabled the CONFIG_FPROTECT Kconfig option in the MCUboot configuration for the nRF54L15 DK target that is part of the Fast Pair Locator Tag sample.
Ref: NCSDK-30725
=> samples: bluetooth: fast_pair: locator_tag: enable fprotect in mcuboot

doc/nrf/installation/install_ncs.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Fixed the path location for macOS.
Added information about the toolchain installation location. NCSIDB-1414.
=> doc: install_ncs: update path location for macOS

scripts/memory-threshold-list.yaml
Add memory threshold for SDP GPIO application.
=> scripts: memory-threshold: add SDP GPIO application

config/suit/templates/nrf54h20/default/v1/app_recovery_local_envelope.yaml.jinja2, config/suit/templates/nrf54h20/default/v1/root_with_binary_nordic_top.yaml.jinja2, samples/suit/smp_transfer/sysbuild/recovery.overlay, subsys/suit/recovery_button/Kconfig, subsys/suit/recovery_button/src/suit_recovery_button.c, west.yml
This commit adds the possibility to run a companion image which checks the need of entering foreground update mode based on pressing a button.
=> suit: Manifest allowing to check recovery button from companion

applications/nrf5340_audio/doc/building.rst, applications/nrf5340_audio/doc/fota.rst, applications/nrf5340_audio/doc/requirements.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- doc: nrf5340_audio: remove child image mention
Removed the mention of the child image directory from the docs.
The application uses sysbuild as other applications.
This mention was a doc bug.
OCT-3244 and NCSDK-30393.
- doc: nrf5340_audio: clarify building steps
Provided extra information for the building steps, including
cross-links. Updated configuration file list. Added a section on the
FOTA page about building. TECHDOC-3100.
=> doc: nRF5340 audio fixes

samples/dect/dect_phy/dect_shell/src/dect/dect_phy_shell.c, samples/dect/dect_phy/dect_shell/src/dect/dect_phy_shell.h, samples/dect/dect_phy/dect_shell/src/dect/ping/dect_phy_ping.c
LBT can be enabled by using following hook:
--c_tx_lbt_period <symbol_count>, where range is 2-110. Zero disables LBT which is also a default.
Additionally, --c_tx_lbt_busy_th <dbm>, can be used to set a custom threshold for LBT busy channel detection. Default is from RSSI scan BUSY threshold from settings.
Jira: MOSH-633
=> samples: dect_phy: dect_shell: ping client: LBT support

CODEOWNERS, doc/nrf/drivers/wifi/nrf70_native.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
[SHEL-3276] Add TX power calculation in nrf70 driver documentation.
[SHEL-3276]: https://nordicsemi.atlassian.net/browse/SHEL-3276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: nrf: drivers: Add TX power calculation

samples/net/azure_iot_hub/src/main.c
The response payload size was not set correctly resulting in an invalid json response. The size set was the size of the pointer (4) and not the string content.
=> samples: net: azure_iot_hub: Fix bug in response to direct method

snippets/nrf70-wifi/nrf54h20_cpuapp.overlay
Wi-Fi needs higher RAM, reinstate the same RAM as earlier custom shield (now removed) for 54H.
=> snippets: nrf70-wifi: Increase 54H Wi-Fi RAM

subsys/bluetooth/controller/Kconfig
The configuration BT_CTLR_SDC_ALLOW_PARALLEL_SCANNING_AND_INITIATING is no longer experimental.
Because there is now also a corresponding host configuration (BT_SCAN_AND_INITIATE_IN_PARALLEL), we make the default value inherit from that one.
A release note entry will be added in a separate commit, referencing a new sample application using this feature.
=> Bluetooth: Controller: Remove experimental from parallel scan+init

samples/dect/dect_phy/dect_shell/src/dect/perf/dect_phy_perf.c, samples/dect/dect_phy/dect_shell/src/dect/ping/dect_phy_ping.c, samples/dect/dect_phy/dect_shell/src/dect/rf_tool/dect_phy_rf_tool.c
Adding B4 support also for ping, perf and rf_tool commands that are having their own mdm phy api initialization.
Jira: MOSH-622
=> samples: dect_phy: dect_shell: ping/perf/rf_tool: band #4 support

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/peripheral_power_profiling/README.rst, samples/bluetooth/peripheral_power_profiling/src/main.c
Added support for the nrf54h20 board target.
Currently, the System off mode is not supported by this sample for the nRF54H20 platform.
=> samples: peripheral_power_profiling: Add support for nRF54H20 target

tests/subsys/bluetooth/fast_pair/crypto/testcase.yaml, tests/subsys/bluetooth/fast_pair/storage/account_key_storage/testcase.yaml, tests/subsys/bluetooth/fast_pair/storage/factory_reset/testcase.yaml
Adds nRF54H20 support in Fast Pair tests.
Jira: NCSDK-30335
Jira: NCSDK-30336
=> tests: subsys: bluetooth: fast_pair: Add nRF54H20 support

subsys/nrf_security/src/drivers/cracen/Kconfig
Allow disabling CRACEN_LIB_KMU and CRACEN_LOAD_MICROCODE for flash-size optimizations
Ref. KEYMS-8, NCSDK-30162
=> nrf_security: Allow user-configurability for CRACEN configs

doc/nrf/protocols/matter/end_product/watchdog.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.9.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/common/src/watchdog/Kconfig, samples/matter/common/src/watchdog/watchdog.cpp, samples/matter/common/src/watchdog/watchdog.h
Added possibility to configure watchdog CONFIG register by:
- Pausing watchdog when CPU is in the sleep state.
- Pausing watchdog when the CPU is halted by a debugger.
=> samples: matter: Extend Matter Watchdog by new configs

applications/matter_bridge/boards/nrf54h20dk_nrf54h20_cpuapp.conf, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/lock/boards/nrf54h20dk_nrf54h20_cpuapp.conf, samples/matter/template/boards/nrf54h20dk_nrf54h20_cpuapp.conf, west.yml
Enabled ZMS as Settings backend for nRF54H20 samples and other MRAM-based device that support it.
=> samples: matter: Enable ZMS in nRF54H20

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/direct_test_mode/boards/nrf54l15dk_nrf54l05_cpuapp.conf, samples/bluetooth/direct_test_mode/boards/nrf54l15dk_nrf54l05_cpuapp.overlay, samples/bluetooth/direct_test_mode/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/bluetooth/direct_test_mode/boards/nrf54l15dk_nrf54l10_cpuapp.overlay, samples/bluetooth/direct_test_mode/sample.yaml, samples/bluetooth/peripheral_lbs/sample.yaml, samples/bluetooth/peripheral_power_profiling/boards/nrf54l15dk_nrf54l05_cpuapp.conf, samples/bluetooth/peripheral_power_profiling/boards/nrf54l15dk_nrf54l05_cpuapp.overlay, samples/bluetooth/peripheral_power_profiling/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/bluetooth/peripheral_power_profiling/boards/nrf54l15dk_nrf54l10_cpuapp.overlay, samples/bluetooth/peripheral_power_profiling/sample.yaml, samples/bluetooth/peripheral_uart/boards/nrf54l15dk_nrf54l05_cpuapp.conf, samples/bluetooth/peripheral_uart/boards/nrf54l15dk_nrf54l05_cpuapp.overlay, samples/bluetooth/peripheral_uart/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/bluetooth/peripheral_uart/boards/nrf54l15dk_nrf54l10_cpuapp.overlay, samples/bluetooth/peripheral_uart/sample.yaml, samples/peripheral/radio_test/boards/nrf54l15dk_nrf54l05_cpuapp.conf, samples/peripheral/radio_test/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/peripheral/radio_test/sample.yaml
The prioritized samples to add L05 and L10 targets were: BLE: peripheral_lbs, peripheral_uart, peripheral_power_profiling, direct_test_mode and peripheral:radio_test.
=> samples: Add support for nRF54L05/L10 build targets in some samples

doc/nrf/drivers/wifi/nrf70_native.rst, doc/nrf/drivers/wifi/nrf70_portable.rst, doc/nrf/protocols/wifi/advanced_modes/offloaded_raw_tx.rst, samples/wifi/offloaded_raw_tx/src/main.c, samples/wifi/shell/sample.yaml, subsys/net/lib/hostap_crypto/Kconfig, subsys/net/lib/nrf70_fw_ext/CMakeLists.txt, west.yml
nRF70 Wi-Fi driver is now restructured, pull these changes to NCS.
=> wifi: Pull nrf_wifi driver restructuring

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/central_and_peripheral_hr/Kconfig, samples/bluetooth/central_bas/Kconfig, samples/bluetooth/central_nfc_pairing/Kconfig, samples/bluetooth/central_uart/Kconfig, samples/bluetooth/peripheral_bms/Kconfig, samples/bluetooth/peripheral_cgms/Kconfig, samples/bluetooth/peripheral_cts_client/Kconfig, samples/bluetooth/peripheral_lbs/Kconfig, samples/bluetooth/peripheral_mds/Kconfig, samples/bluetooth/peripheral_nfc_pairing/Kconfig, samples/bluetooth/peripheral_power_profiling/Kconfig, samples/bluetooth/peripheral_rscs/Kconfig, samples/bluetooth/peripheral_status/Kconfig, samples/bluetooth/peripheral_uart/Kconfig, samples/bluetooth/rpc_host/Kconfig
Enabled the ZMS file system for the nRF54H20 DK in the Bluetooth samples.
=> samples: bluetooth: Enable ZMS for nRF54H20 platform

lib/bin/lwm2m_carrier/include/lwm2m_os.h
Added more documentation to the os_storage functions. The text is based on the current zephyr nvs_read/write/delete().
=> doc: lwm2m_carrier: Improve os_storage glue documentation.

samples/wifi/radio_test/sample_description.rst
[SHEL-3277]: Update sample description with TX power equations
Dependency on https://github.com/nrfconnect/sdk-nrf/pull/19009
[SHEL-3277]: https://nordicsemi.atlassian.net/browse/SHEL-3277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: wifi: Update TX power calculation

scripts/west_commands/create_board/templates/nrf52/board.cmake.jinja2
Since custom boards may not contain the soc name as part of the board name, automatic guess does not work.
=> scripts: west_commands: create_board: fix openocd for nrf52

subsys/mpsl/init/mpsl_init.c
Mpsl now needs to enable channels in the dppi controllers that it uses.
=> mpsl: Enable dppichannel in dppic130 and dppic132

applications/matter_bridge/doc/matter_bridge_description.rst, doc/nrf/protocols/matter/end_product/test_event_triggers.rst, doc/nrf/protocols/matter/end_product/watchdog.rst, doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst, doc/nrf/protocols/matter/getting_started/low_power_configuration.rst, doc/nrf/protocols/matter/getting_started/memory_optimization.rst, doc/nrf/releases_and_maturity/known_issues.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.9.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.6.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, doc/nrf/samples/matter.rst, samples/matter/common/config.rst, samples/matter/lock/README.rst
The Matter samples share some configurations. In the case of the Kconfig options, these are not picked up by the docs build system. This adds a separate page where these options are documented.
=> doc: Matter: Add shared configurations page

samples/peripheral/radio_test/boards/nrf54h20dk_nrf54h20_cpurad_wifi_combo.overlay, samples/wifi/radio_test/sample.yaml
When a combo radio test is used for 54H, the peripheral radio test uses the same console as Wi-Fi radio test causing UICR conflicts and failing to boot both APP and RAD.
Fix the conflicts by adding an overlay to use a separate console and also not to use APP RAM in RAD.
Fixes SHEL-3287.
=> samples: Fix Wi-Fi and BLE combo radio test for 54H

subsys/sdfw_services/services/suit_service/CMakeLists.txt, subsys/sdfw_services/services/suit_service/suit_mfst_var.c, subsys/sdfw_services/services/suit_service/suit_service.cddl, subsys/sdfw_services/services/suit_service/zcbor_generated/suit_service_decode.c, subsys/sdfw_services/services/suit_service/zcbor_generated/suit_service_decode.h, subsys/sdfw_services/services/suit_service/zcbor_generated/suit_service_encode.c, subsys/sdfw_services/services/suit_service/zcbor_generated/suit_service_encode.h, subsys/sdfw_services/services/suit_service/zcbor_generated/suit_service_types.h
Added definition and implementation of SUIT SSF services for manifest-controlled variables
Ref: NCSDK-30530
=> sdfw_services: Support for SUIT manifest-controlled variables

doc/nrf/libraries/bluetooth/services/rreq.rst, doc/nrf/libraries/bluetooth/services/rrsp.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
This adds documentation for the Ranging Service Ranging Responder and Ranging Requestor.
=> doc: nrf: bluetooth: RAS RREQ and RRSP docs

subsys/nrf_security/cmake/extensions.cmake
nRF Security should not duplicate Zephyr toolchain ld flags.
=> cmake: remove duplication of TOOLCHAIN_LD_FLAGS flags

scripts/hid_configurator/README.rst, scripts/hid_configurator/modules/dfu.py
Change adds support for pure ED25519 signature (used by nRF54L based devices that enable MCUboot hardware cryptography). imgtool from MCUboot upstream repository does not support this configuration, a dedicated imgtool version from sdk-mcuboot repository must be used.
Jira: NCSDK-30745
=> scripts: hid_configurator: Support pure ED25519 signature

subsys/trusted_storage/Kconfig
=> trusted_storage: improve Kconfig description

subsys/nrf_security/cmake/extensions.cmake
Backport 27f11591d852f79ff287c35de49574e07ce98555 from #19265.
=> [Backport v2.8-branch] cmake: remove duplication of TOOLCHAIN_LD_FLAGS flags

doc/nrf/shortcuts.txt
Updated wording from "deprecation" to the more correct "archiving". NCSDK-30819.
=> doc: edit nrfjprog/CLT deprecation note

samples/bluetooth/scanning_while_connecting/src/main.c
Move flag that protects application from establishing a new connection when there is already a connection establishment process pending. This is moved to after the if to check that we have established all connections. Otherwise, we get in the scan_recv call back an attempt to establish a connection when we have used all
connection objects before we stop scanning in main.
=> samples: Bluetooth: update scanning_while_connecting

include/modem/modem_key_mgmt.h, lib/modem_key_mgmt/modem_key_mgmt.c
Handle generic CME errors from all AT%CMNG commands.
For reference, see 3GPP 27.007 Ch. 9.1.
=> lib: modem_key_mgmt: Handle generic CME errors

Jenkinsfile, test-manifests/99-default-test-nrf.yml
Use CI_LIB and test-nrf from v2.9-branch
=> ci: Use CI_LIB and test-nrf from v2.9-branch

samples/bluetooth/fast_pair/input_device/prj.conf
Just edits the comment as default configuration is already aligned with nRF54H20DK.
Jira: NCSDK-30345
=> samples: bluetooth: fast_pair: Align Tx power for nRF54H20DK

scripts/docker/Dockerfile
Bump nrfutil-device version to 2.7.7 in public docker image
=> sdk-nrf-toolchain: Bump nrfutil-device version

subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/hci_driver.c
added 3 new options to allow developers to use step mode-3 and multiple antenna during CS procedure
=> bluetooth: add Kconfig options to enable optional CS capabilities

doc/nrf/app_dev/device_guides/nrf70/wifi_advanced_security_modes.rst
Now that NCS uses hostap external crypto module, update the Kconfig option for PSA.
=> doc: nrf70: Fix PSA config option

doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf54l/nrf54l_signing_with_payload.rst, doc/nrf/app_dev/device_guides/nrf54l/vpr_flpr.rst
Backport e411ad5bcc89a0db838062ff1032c2414ca50229 from #19155.
=> [Backport v2.9-branch] doc: mcuboot signing app with flpr payload

scripts/quarantine.yaml
Backport fe34349d5cbbdd6e415cf72ac7eb72f3847a10a0 from #19235.
=> [Backport v2.9-branch] Quarantine: Remove hostap tests

scripts/docker/Dockerfile
Backport 92b2319741702da315034b0ce79185ee385e336d from #19311.
=> [Backport v2.9-branch] sdk-nrf-toolchain: Bump nrfutil-device version

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/hci_internal.c
Return an error when handling LLPM enable command in case LLPM feature is not supported (e.g. on nRF53 SoC Series).
Jira: NCSDK-29545
=> bluetooth: controller: Return an error if LLPM is not supported

doc/nrf/releases_and_maturity/releases/release-notes-2.8.0.rst
Fixed texts related to MCUboot image
compression in the 2.8 release notes.
=> doc: Minor fixes to the 2.8 release notes

doc/nrf/releases_and_maturity/releases/release-notes-2.8.0.rst
Backport 6dcaf8cf9cfc37959a1a1a5de2d98201c4e6b2e7 from #19296.
=> [Backport v2.9-branch] doc: Minor fixes to the 2.8 release notes

applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/app.overlay, applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/app_3bleconn.overlay, applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/app_4llpmconn.overlay, applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/app_common.dtsi, applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/app_release_4llpmconn.overlay, applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/app.overlay, applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/app_common.dtsi, applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/app_release.overlay
Improvements for post-merge review items from the following PR:
https://github.com/nrfconnect/sdk-nrf/pull/19033
=> nRF Desktop: common DTS HID/USBD improvements

CODEOWNERS
NCSDK- 30694
Change the doc ownership to reflect the changes in this PR: https://github.com/nrfconnect/sdk-nrf/pull/18010
Also, added ownership for
/doc/nrf/libraries/nrf_rpc/nrf_rpc_dev_info.rst
=> doc: Edits to the code owner file for the doc ownership

subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/hci_driver.c
Backport 02f9716596f378d60b0d9290756a738eedd58cad from #19226.
=> [Backport v2.9-branch] bluetooth: add Kconfig options to enable optional CS capabilities

samples/peripheral/lpuart/boards/nrf54l15dk_nrf54l05_cpuapp.conf, samples/peripheral/lpuart/boards/nrf54l15dk_nrf54l05_cpuapp.overlay, samples/peripheral/lpuart/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/peripheral/lpuart/boards/nrf54l15dk_nrf54l10_cpuapp.overlay, samples/peripheral/lpuart/sample.yaml, tests/drivers/lpuart/boards/nrf54l15dk_nrf54l05_cpuapp.conf, tests/drivers/lpuart/boards/nrf54l15dk_nrf54l05_cpuapp.overlay, tests/drivers/lpuart/boards/nrf54l15dk_nrf54l10_cpuapp.conf, tests/drivers/lpuart/boards/nrf54l15dk_nrf54l10_cpuapp.overlay, tests/drivers/lpuart/testcase.yaml
Lpuart test and sample can now be run on nRF54L05 and nRF54l10 targets.
=> tests: drivers: lpuart: allow testing on nRF54L05 and nRF54L10

west.yml
=> manifest: sdk-zephyr/sdk-nrfxlib: wifi: Pull latest fixes

doc/nrf/libraries/networking/azure_iot_hub.rst
Backport 7ec7917a1b38a4ee005e5e1c40201f8f627106e9 from #19063.
=> [Backport v2.9-branch] doc: Add instructions for how to install "nrfcredstore"

samples/bluetooth/enocean/Kconfig, samples/bluetooth/fast_pair/locator_tag/Kconfig, samples/bluetooth/peripheral_ams_client/Kconfig, samples/bluetooth/peripheral_ancs_client/Kconfig, samples/bluetooth/peripheral_mds/Kconfig, samples/bluetooth/peripheral_uart/Kconfig, subsys/net/openthread/settings_check/CMakeLists.txt
For some samples ZMS is still not selected as the default storage subsystem when the SoC family has an MRAM flash
=> Add ZMS as default storage subsystem for Soc family that has MRAM

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c
The key was imported from SICR for usage with ECB, which made it impossible to decrypt the firmware using AES-GCM directly.
Note: This actually is simply reopening PR https://github.com/nrfconnect/sdk-nrf/pull/17030 - however due to long inactivity (other priorities) the PR has been closed - now it is needed again, as the work was resumed
=> cracen: imported FWENC key used for AES-GCM

.github/workflows/enforce-toolchain-synchronization.yml
This prevents race condition issue when new toolchain bundle has to be built after PR is merged
=> [NCSDK-29365] actions: Force rebuilding toolchain bundles

samples/bluetooth/fast_pair/input_device/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
Puts Fast Pair provisioning partition right before the storage
partition.
Aligns partition sizes and addresses to be a multiple of 0x10, which is
the write block size for MRAM.
Keeps the storage partition at address divisible by 0x1000, as this is
the storage sector size.
Fixes the cpuapp_rw_partitions node deletion (earlier it was done
incorrectly).
Jira: NCSDK-30269
=> samples: bluetooth: fast_pair: input_device: Improve nRF54H20 memory map

include/debug/ppi_trace.h, subsys/debug/ppi_trace/Kconfig, subsys/debug/ppi_trace/ppi_trace.c
The ppi_trace module is rewritten and uses now nrfx_gppi API. This is to support nRF54L series devices which have multiple DPPI controllers and require passing DPPI signals through PPIB bridges. The complexity is enclosed by nrfx-provided nrfx_gppi API for most functions.
The function `ppi_trace_dppi_ch_trace` (necessary for testing behavior of RADIO peripheral with mpsl/sdc/802.15.4) requires special handling. The function is given additional parameter `dppic` to identify the DPPIC controller the `dppi_ch` belongs to. This function cannot be a simple wrapper for nrfx-provided function. It is also wrapped by DPPI_PRESENT macro.
Details in commit messages.
=> debug: ppi_trace: use nrfx_gppi to support nRF54L series devices

modules/trusted-firmware-m/CMakeLists.txt, modules/trusted-firmware-m/Kconfig, modules/trusted-firmware-m/tfm_boards/CMakeLists.txt, modules/trusted-firmware-m/tfm_boards/nrf54l15_cpuapp/ns/cpuarch_ns.cmake, modules/trusted-firmware-m/tfm_boards/ns/CMakeLists.txt, tests/tfm/tfm_psa_test/CMakeLists.txt, tests/tfm/tfm_regression_test/CMakeLists.txt
Adding in config that takes clock-frequency from device tree and passes it to TF-m.
Removing hardcoded NRF_CONFIG_CPU_FREQ_MHZ
=> nrf54l: Removing hardcoded clock frequency

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/bluetooth/services/fast_pair/fast_pair.h, samples/bluetooth/fast_pair/input_device/src/main.c, samples/bluetooth/fast_pair/locator_tag/src/main.c, subsys/bluetooth/services/fast_pair/fmdn/callbacks.c, subsys/bluetooth/services/fast_pair/fp_gatt_service.c
Updated the bt_fast_pair_info_cb_register API function in the Bluetooth Fast Pair library to allow registration of multiple callbacks.
=> bluetooth: fast_pair: allow multiple instances of info callbacks

scripts/quarantine_no_optimization.yaml, scripts/quarantine_zephyr.yaml
Backport 95082e84ba8a2502e8e68ff1bf2c221d27102252 from #19349.
=> [Backport v2.9-branch] quarantine: new failures on native_sim

doc/_extensions/table_from_rows.py
In case an entry takes multiple shileds delimited by space, handle that by moving to a list based parsing from string based parsing.
Resolves a bug for 54 Series Wi-Fi shields where `space` was used as a delimiter for multiple shields.
=> doc: extensions: Add support for space delimited shields

scripts/quarantine_zephyr.yaml
Backport 81d8a9e19b6a1a8e4eb1e06d97625b09619bc4ce from #19368.
=> [Backport v2.9-branch] quarantine: update wifi

scripts/quarantine_no_optimization.yaml, tests/subsys/net/openthread/rpc/server/src/coap_suite.c, tests/subsys/net/openthread/rpc/server/src/dataset_suite.c, tests/subsys/nfc/rpc/server/src/t2t_suite.c, tests/subsys/nfc/rpc/server/src/t4t_suite.c
Fix unit tests using FFF fakes' arguments by pointer after releasing the underlying memory.
Jira: NCSDK-30881
=> quarantine: fix RPC server tests without optimizations

applications/nrf_desktop/memory_layout.rst
Change fixes legacy child image build system reference in documentation. The child image build system was replaced by sysbuild.
Jira: NCSDK-30742
=> applications: nrf_desktop: Fix legacy multi-image ref in documentation

scripts/west_commands/ncs-provision.py
adds ability to upload key as locked.
ref.: NCSDK-30867
=> scripts: west_commands: ncs-provision locked key

subsys/mpsl/pin_debug/CMakeLists.txt, subsys/mpsl/pin_debug/Kconfig, subsys/mpsl/pin_debug/mpsl_pin_debug_nrf54.c
This commit adds support for using pin debug on nRF54L. The code has been extracted out to a separate file because has a couple of things that are different compared to nRF52 and nRF53:
- It needs to setup a PPI bridge between two domains. This is done through `nrfx_gppi_edge_connection_setup()`
- It needs to allocate DPPI channels in the domain where the GPIO pin is located.
The code hardcodes to use PORT1. We should consider moving the pin allocations to device tree to make this more flexible.
The code should be reusable for nRF54H as well.
=> mpsl: Support mpsl_pin_debug on nRF54L DK

samples/matter/smoke_co_alarm/src/default_zap/smoke_co_alarm.zap, samples/matter/smoke_co_alarm/src/default_zap/zap-generated/endpoint_config.h
Backport 8b2ef9a2f838a64bd0b585cdf2069ae619df9151 from #19375.
=> [Backport v2.9-branch] samples: matter: smoke_co_alarm: Fix cluster revision

subsys/nrf_security/src/psa_crypto_driver_wrappers.c
The case for PSA_KEY_LOCATION_CRACEN was missing.
=> nrf_security: Fix decrypt keys location check for nRF54H20

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_customize_dfu.rst
Improve manifests template files search description.
=> doc: change description of using user's own manifests

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
nRF54l10 and nRF54l05 are added as supported platforms to mesh samples Added here:https://github.com/nrfconnect/sdk-nrf/pull/19327
=> bluetooth: mesh: samples: Add changlog for mesh sample target support

applications/nrf_desktop/memory_layout.rst
Backport c6466c3c620b287c9578c1252155b99209ccf9a4 from #19377.
=> [Backport v2.9-branch] applications: nrf_desktop: Fix legacy multi-image ref in documentation

include/net/mqtt_helper.h
Add information about positive return value in case of DNS error.
=> net: lib: mqtt_helper: Fix mqtt_helper_connect() documentation

subsys/net/lib/azure_iot_hub/src/azure_iot_hub.c, tests/subsys/net/lib/azure_iot_hub/iot_hub/src/azure_iot_hub_test.c
Backport ffa08e9d4e592eaf079eb6f9dccfe14ec9d50bf5 from #19389.
=> [Backport v2.9-branch] lib: azure_iot_hub: Fix invalid message ID

scripts/west_commands/ncs-provision.py
adds new policy scheme to 'west ncs-provision' command.
This is addendum to https://github.com/nrfconnect/sdk-nrf/pull/19328 as we missed possibility to lock last generation of key family.
=> ncs-provision lock-last policy

CODEOWNERS, scripts/twister/alt/zephyr/samples/sensor/accel_polling/sample.yaml
Backport b957011b12c4a18b1f5bce2d704b83ad0b3b0b01~3..b957011b12c4a18b1f5bce2d704b83ad0b3b0b01 from #19399.
=> [Backport v2.9-branch] Fix accel polling

applications/nrf_desktop/board_configuration.rst, applications/nrf_desktop/bootloader_dfu.rst, applications/nrf_desktop/description.rst, applications/nrf_desktop/doc/dfu.rst
PR introduces documentation for MCUboot HW crypto for nRF54L SoC Series.
Jira: NCSDK-30742
=> applications: nrf_desktop: Document MCUboot HW crypto for nRF54L SoC Series

subsys/suit/utils/src/suit_plat_mem_util.c
SDFW now always uses direct write mode except when deleting. After deleting, write mode is set back to direct.
Hence it is safe to assume that the write mode is direct.
https://github.com/nrfconnect/sdk-secdom/pull/1007#discussion_r1871226492
Ref: NCSDK-30143
=> suit: utils: Get rid of MRAM write mode setting

doc/nrf/conf.py, doc/nrfxlib/conf.py, doc/zephyr/conf.py
This extension exposes a Jinja filter to obtain the GitHub URL for any document. Together with sphinx_ncs_theme 1.0.21, pages will now show a "Open on GitHub" button.
=> doc: nrf: enable gh_utils extension

doc/_extensions/page_filter.py
app.builder.script_files is now a list of `_JavaScript` objects. To access the actual file name, the `filename` property must be used. Stringification of the class contains other info like priority or type, making it unusable to obtain the path only.
=> doc: extensions: page_filter: fix script import snippet

include/net/mqtt_helper.h
Backport baaa9aaa55239a0b36ac27f2f3a6a11eb3692f8b from #19409.
=> [Backport v2.9-branch] net: lib: mqtt_helper: Fix mqtt_helper_connect() documentation

lib/modem_key_mgmt/modem_key_mgmt.c
Backport c43a9ee4b4f20161b4d364c02e0540b04cd582d9 from #19392.
=> [Backport v2.9-branch] lib: modem_key_mgmt: Add CME error code 527 - Invalid content

cmake/sysbuild/nrf700x.cmake
The FW blobs in NCS should be picked from nrfxlib.
Fix SHEL-3319.
=> sysbuild: nrf700x: Fix the FW blobs path

applications/nrf_desktop/board_configuration.rst, applications/nrf_desktop/bootloader_dfu.rst, applications/nrf_desktop/description.rst, applications/nrf_desktop/doc/dfu.rst
Backport ceb3b15891e10157518a407f8103f7be1f92374f~3..ceb3b15891e10157518a407f8103f7be1f92374f from #19356.
=> [Backport v2.9-branch] applications: nrf_desktop: Document MCUboot HW crypto for nRF54L SoC Series

doc/nrf/external_comp/bt_fast_pair.rst, doc/nrf/libraries/bluetooth/services/fast_pair.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, scripts/nrf_provision/fast_pair/README.rst
=> doc: fast_pair: Describe nRF54H20 support

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_recovery.rst
This commit documents the feature allowing to enter SUIT recovery via a button press.
=> doc: SUIT recovery button documentation

applications/nrf_desktop/sysbuild/CMakeLists.txt
Using KMU in MCUboot requires manual provisioning of the MCUboot keys. Change adds a CMake warning to ensure that user is aware that an extra step is needed before programming the board.
Jira: NCSDK-30742
=> applications: nrf_desktop: Add CMake warning for MCUboot using KMU

doc/nrf/app_dev/config_and_build/hardware/add_new_driver.rst, doc/nrf/app_dev/config_and_build/hardware/index.rst, doc/nrf/app_dev/config_and_build/hardware/use_gpio_pin_directly.rst, doc/nrf/links.txt, dts/bindings/gpio/nordic,gpio-pins.yaml
Edited the Driving the GPIO pins directly guide for style. Fixed some style issues in the nordic,gpio-pins.yaml. Added a generic page about adding drivers.
NCSDK-24813.
=> doc: devicetree: edits to driving gpio guide

samples/matter/light_switch/boards/nrf7002dk_nrf5340_cpuapp_release.conf, samples/matter/lock/boards/nrf7002dk_nrf5340_cpuapp_release.conf, samples/matter/lock/prj_thread_wifi_switched.conf
Backport 9397a22115ae70a6befc242320d5359941357e79 from #19423.
=> [Backport v2.9-branch] samples: matter: Fix WiFi release build by disabling RAM PWRDWN

applications/nrf_desktop/doc/ble_conn_params.rst
Backport 4f7540e200361c635f52dfafb8bf2143def74e18 from #19424.
=> [Backport v2.9-branch] applications: nrf_desktop: Update ble_conn_params module documentation

scripts/west_commands/ncs-provision.py
Backport c3826656c22917e3268f44122166b82ec3b461a8 from #19328.
=> [Backport v2.9-branch] scripts: west_commands: ncs-provision locked key

doc/nrf/drivers/bme68x_iaq.rst
BME68X IAQ driver was missing path to where the west config command should be executed. Added the same.
TECHDOC-3224
=> doc improvement: bme68x_iaq - Add file path to execute west config

doc/nrf/releases_and_maturity/software_maturity.rst
nRF54L05 and nRF54L10 are added to the table.
Indicate support for nRF54H20 in nPM1300 table.
=> doc: PMIC software maturity level update

doc/nrf/releases_and_maturity/software_maturity.rst
Backport e1b6e2afc766aa23cf1bebabdec52d75fd4ae648 from #19480.
=> [Backport v2.9-branch] doc: PMIC software maturity level update

doc/nrf/drivers/bme68x_iaq.rst
Backport ea721da29d5309f8b6bc0630b3f1ae2efd0c6290 from #19465.
=> [Backport v2.9-branch] doc improvement: bme68x_iaq - Add file path to execute west config

doc/nrf/releases_and_maturity/software_maturity.rst
Backport 9372500c7f89041597d1f344b533a86296dc5c88 from #19485.
=> [Backport v2.9-branch] doc: sml: Add 54L05/10 as unsupported for Wi-Fi

samples/bluetooth/mesh/dfu/distributor/README.rst
While the protocol documentation specifies that using the shell management subsystem of MCU manager via the nRF Connect Device Manager mobile application is only available for the Android app, this is missing from the sample documentation - which is added in this commit.
=> doc: bluetooth: mesh update dfu sample README

doc/requirements.txt
sphinx > 7.2 removed the module  'setup_js_tag_helper' from 'sphinx.builders.html' requiring sphinx-notfound-page >= 1.0.0 to be used to remain compatible.
Remove duplicate anytree entry.
=> doc: requirements: specify min version for sphinx-notfound-page

cmake/sysbuild/nrf700x.cmake
Backport cabe5e5d26fe555fdc9851634bc5779d16faab6d from #19448.
=> [Backport v2.9-branch] sysbuild: nrf700x: Fix the FW blobs path

scripts/memory-threshold-list.yaml
Update ROM size for SDP GPIO application with ICBMSG backend after it was increased by https://github.com/nrfconnect/sdk-nrf/pull/18179
=> scripts: memory-threshold: update ROM size for SDP GPIO

applications/sdp/gpio/README.rst, doc/nrf/applications.rst, doc/nrf/includes/sample_board_rows.txt
Backport 435c9afec4dc200bd56314490d12e625405b375b~2..435c9afec4dc200bd56314490d12e625405b375b from #19466.
=> [Backport v2.9-branch] applications: sdp: gpio: add README

applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_broadcast.c
- OCT-3255
- If broadcast name is found, but the ID has changed, print a message
=> Applications: Audio: Added print on broadcast ID mismatch

doc/CMakeLists.txt, doc/nrf/drivers/wifi/nrf70_native.rst, doc/wifi/wifi.doxyfile.in, west.yml
Pull in GDFS and GDPWR NRFS services and HSFLL clock control driver along with adaptions required for GDPWR.
test_low_level: PR-1642
test_suit_dfu: pr-19324
=> manifest: pull in gdfs gdpwr hsfll driver

.github/test-spec.yml, tests/drivers/audio/pdm_loopback/testcase.yaml
Added gpio_loopback fixture to pdm tests.
=> tests: drivers: audio: pdm_loopback: add fixture

samples/suit/smp_transfer/sysbuild/nrf54h20dk_nrf54h20_memory_map.dtsi, scripts/quarantine_zephyr.yaml, west.yml
H20 batch 0
sdk-zephyr: https://github.com/nrfconnect/sdk-zephyr/pull/2385
test_crypto: PR-729
=> manifest: update for H20 batch 0

sysbuild/Kconfig.mcuboot, west.yml
Prevents making some options configurable and sets correct limits when MCUboot is configured in single application mode
NCSDK-30866
=> sysbuild: Prevent some configuration options with single image mode

tests/drivers/audio/pdm_loopback/src/main.c
Increased error margin for PDM frequency tests to dispose of random test failures.
=> tests: drivers: audio: pdm_loobback: fix error margin

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/benchmarks/coremark/README.rst, samples/benchmarks/coremark/boards/nrf54l15dk_nrf54l05_cpuapp.conf, samples/benchmarks/coremark/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/benchmarks/coremark/sample.yaml, scripts/quarantine_integration.yaml
Change adds support for nRF54L05 and nRF54L10 SoCs (emulated on nRF54L15 DK).
Jira: NCSDK-30313
=> samples: benchmarks: coremark: Add nRF54L05 and nRF54L10 support

doc/nrf/releases_and_maturity/software_maturity.rst, samples/keys/hw_unique_key/boards/nrf54l15dk_nrf54l05_cpuapp.conf, samples/keys/hw_unique_key/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/keys/hw_unique_key/sample.yaml
Hardware unique keys are supported on 54L10/L05
=> samples: hw_unique_key: Add nRF54L10 and nRF54L05

ext/curl/lib/url.h
Corrected use of incorrect macro introduced in commit 062d82d.
=> ext: curl: fix usage of incorrect macro

samples/bluetooth/fast_pair/locator_tag/include/app_fp_adv.h, samples/bluetooth/fast_pair/locator_tag/src/fp_adv.c, samples/bluetooth/fast_pair/locator_tag/src/main.c
Removed the app_fp_adv_rpa_rotation_suspend API from the Fast Pair advertising module that is part of the Fast Pair Locator tag sample. The module now handles the RPA suspension without the need for external assistance.
Ref: NCSDK-30487
=> samples: bluetooth: fast_pair: locator_tag: remove rpa suspension API

subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_coap
This patch makes the NRF_CLOUD_COAP_DOWNLOADS option experimental again. Resumption is broken in the current version, so it is not ready for production use.
=> lib: nrf_cloud: make COAP_DOWNLOADS experimental again

doc/nrf/releases_and_maturity/software_maturity.rst
Backport a661b925006957b1d6f595624fda816e057add8f from #19552.
=> [Backport v2.9-branch] doc: maturity: Add info about nRF54L05 and nRF54L10 in NFC features

doc/nrf/releases_and_maturity/software_maturity.rst, samples/keys/hw_unique_key/boards/nrf54l15dk_nrf54l05_cpuapp.conf, samples/keys/hw_unique_key/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/keys/hw_unique_key/sample.yaml
Backport e1bc174161441ee9934d366fc4f913a8da0239c2 from #19550.
=> [Backport v2.9-branch] samples: hw_unique_key: Add nRF54L10 and nRF54L05

subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_coap
Backport b757e57e285e3c95f4a03c8d4ac5362a4aa85b02 from #19524.
=> [Backport v2.9-branch] lib: nrf_cloud: make COAP_DOWNLOADS experimental again

config/suit/templates/nrf54h20/default/v1/root_with_binary_nordic_top.yaml.jinja2
This commit modifies SUIT the root manifest template to support the scenario of updating the radio and application manifests one at a time. It assumes that in such case the radio image is always updated before the application image.
It also adds several version checks for the candidate image - these are examplary checks, it is suggested to change them to be tailored to the user needs:
- Ensuring that a compatible Nordic soc binaries bundle is installed (currently version 0.6.5 of the Nordic Top manifest)
- If the candidate only contains the radio core image, ensure that its major version of the candidate radio manifest is at most greater by 1 from the installed application manifest major version.
- If the candidate only contains the application core image, ensure that its semantic version …
=> suit: root manifest template support for independent updates

samples/openthread/coap_client/prj.conf, samples/openthread/coap_client/src/coap_client_utils.c, samples/openthread/coap_server/prj.conf, subsys/net/lib/coap_utils/coap_utils.c
For CoAP utils, `CONFIG_POSIX_API` is required only for wrapping socket calls not to require `zsock` prefix. POSIX_API brings more features than needed, is still experimental in Zephyr and causes warnings on building.
This commit changes net socket calls to use `zsock_` prefix and disables `CONFIG_POSIX_API` for OpenThread.
=> net: openthread: Remove dependency on `CONFIG_POSIX_API`

config/suit/templates/nrf54h20/default/v1/root_with_binary_nordic_top.yaml.jinja2
If APP_LOCAL_1_VERSION was undefined build failures occured due to suit-generator error.
=> suit: Fix breaking build if APP_LOCAL_1_VERSION is undefined

west.yml
nRF54L05 & nRF54L10 emulated on nRF54L15 need to have unused RAM disabled to avoid increased power consumption.
=> manifest: update sdk-zephyr to disable unused RAM on nRF54L05/L10

applications/nrf_desktop/src/modules/dvfs.c, tests/benchmarks/multicore/idle_clock_control/src/main.c, tests/benchmarks/peripheral_load/src/clock_thread.c
The clock_control_get_rate() API is not implemented for all clocks, so it must be conditionally checked. It is specifically not implemented for HSFLLs since they are dynamic, so nrf_desktop dvfs service has been updated to not rely on said API.
Ref: NRFX-6890
=> adapt to clock_control_get_rate() removed

doc/nrf/protocols/matter/index.rst
Documentation incorrectly mentions that NCS 2.9.0 uses Matter 1.3.0, while it should be 1.4.0.
=> doc: nrf: Changed Matter version for 2.9.0 to 1.4.0

doc/nrf/protocols/matter/index.rst
Backport 212213225ec4869f3924504ffb998e95d1d1d0fd from #19600.
=> [Backport v2.9-branch] doc: nrf: Changed Matter version for 2.9.0 to 1.4.0

applications/nrf_desktop/pytest/test_mcuboot_kmu.py, applications/nrf_desktop/sample.yaml
Change adds pytest test configuration for nRF54L15 DK. Using pytest is necessary to perform twister runtime tests of configurations that require MCUboot KMU keys provisioning.
Jira: NCSDK-30872
=> applications: nrf_desktop: Add pytest test for nRF54L15 DK

tests/benchmarks/multicore/idle_gpio/boards/nrf54h20dk_nrf54h20_cpuapp_s2ram.overlay, tests/benchmarks/multicore/idle_gpio/remote/boards/nrf54h20dk_nrf54h20_cpurad_s2ram.overlay, tests/benchmarks/multicore/idle_gpio/src/main.c
Turn on the led when core becomes active.
This feature is needed for the new power
consumption measurement framework.
=> tests: benchmarks: multicore: idle_gpio: Add led

doc/nrf/releases_and_maturity/releases/release-notes-2.9.0.rst
Fixing the version from 3.11.7.0 to 3.11.6.0
=> doc: fix the ZBOSS Zigbee version number

doc/nrf/releases_and_maturity/releases/release-notes-2.9.0.rst
Backport ea8f4e7c808a5982fa6e341ad82ace7c421e5f62 from #19612.
=> [Backport v2.9-branch] doc: fix the ZBOSS Zigbee version number

config/suit/templates/nrf54h20/default/v1/root_with_binary_nordic_top.yaml.jinja2
It is currently impossible write a manifest with a declared list with more than 3 components.
This lead to a failure during manifest processing.
=> suit: Fix root manifest to boot recovery with hardware button

doc/nrf/releases_and_maturity/releases/release-notes-2.9.0.rst
Adding link to the NCS 2.9.0 Webinar
=> doc: add the Webinar link to 2.9 highlights

doc/nrf/releases_and_maturity/releases/release-notes-2.9.0.rst
Backport 46924418b10722a4c4084220151f16b6ca72e3df from #19622.
=> [Backport v2.9-branch] doc: add the Webinar link to 2.9 highlights

Jenkinsfile, test-manifests/99-default-test-nrf.yml
Switching to release branch v2.9-nRF54H20
=> ci: Use CI_IB and test-nrf from v2.9-nRF54H20

applications/serial_lte_modem/src/slm_ppp.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/modem/pdn.h, lib/pdn/pdn.c
When ISP sends only IPv6 DNS records, pdn_dynamic_params_get was failing. That's the why pdn_dynamic_params_get_v6 was implemented and used as a fallback on the SLM's ppp.
Real world example:
We were using Congstar sim card in Germany.
Here was the results if CGCONTRDP when we set CGDCONT like below:
| CGDCONT    | CGCONTRDP |
| -------- | ------- |
| +CGDCONT: 0,"IP","internet" | +CGCONTRDP: 0,,"internet","","","10.74.210.210","10.74.210.211",,,,,1500 |
| +CGDCONT: 0,"IPV4V6","internet.telekom" | +CGCONTRDP: 0,,"internet.telekom","","","10.74.210.210","10.74.210.211",,,,,1500 <br/> +CGCONTRDP: 0,,"internet.telekom","","","2A01:0598:07FF:0000:0010:0074:0210:0210","2A01:0598:07FF:0000:0010:0074:0210:0211",,,,,1500 |
| +CGDCONT: 0,"IPV6","ims" | +CGCONTRDP: …
=> slm: fix IPv6 only case

lib/ram_pwrdn/Kconfig, lib/ram_pwrdn/ram_pwrdn.c, samples/matter/smoke_co_alarm/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/openthread/cli/README.rst
Add support for nRF54L10 and nRF54L05 and enable ram power down for these SoCs in Matter and OpenThread.
=> lib: ram_pwrdwn: add support for nRF54L10 and nRF54L05

.github/workflows/enforce-toolchain-synchronization.yml
Do not trigger enforce-toolchain-synchronization.yml when branch is created. 
Workflow fails on new branches due to lack of reference revision. 
It impacts all backport PRs
=> actions: Skip toolchain check on branch creation

.github/workflows/docbuild.yml, .github/workflows/docpublish.yml
Until now, we never allowed uppercase characters in tag. Allow them now.
=> ci: docbuild/docpublish: allow uppercase in tags

Jenkinsfile, test-manifests/99-default-test-nrf.yml
Switching to release branch v2.9-nRF54H20-branch
=> ci: Use CI_IB & test-nrf from v2.9-nRF54H20-branch

subsys/bluetooth/services/ras/rreq/ras_rreq.c
Running tests with UBSAN identified unaligned memory access of the ranging counter. Fix this by using net_buf_simple.
=> bluetooth: services: ras: Fix unaligned memory access in RAS

doc/nrf/releases_and_maturity/known_issues.rst
This removes repetation of KRKNWK-18776 (sidewalk issue - fixed) by more generic NCSDK-31066.
Workaround was added.
=> doc/nrf/../known_issues: note on NCSDK-31066

scripts/quarantine.yaml
Backport 6c9eaf3b402365a3f29a7d4b66f29d9354f2d57d from #19665.
=> [Backport v2.9-nRF54H20-branch] quarantine: update

.github/workflows/docbuild.yml
Removing setuptool, wheel and pip as they are most likely redundant
=> ci: fix docbuild for ubuntu 24.04

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/lte_link_control/modules/ncellmeas.c, tests/lib/lte_lc_api/src/lte_lc_api_test.c
Added handling for `%NCELLMEAS` notification with status 2 (measurement interrupted), but no cells.
NRF91-2269
=> lib: lte_link_control: fix %NCELLMEAS notification parsing

applications/matter_bridge/snippets/onoff_plug/bridge.zap, applications/matter_bridge/snippets/onoff_plug/zap-generated/endpoint_config.h, applications/matter_bridge/src/default_zap/bridge.zap, applications/matter_bridge/src/default_zap/zap-generated/endpoint_config.h, applications/matter_weather_station/src/default_zap/weather-station.zap, applications/matter_weather_station/src/default_zap/zap-generated/endpoint_config.h, samples/matter/light_bulb/src/default_zap/light_bulb.zap, samples/matter/light_bulb/src/default_zap/zap-generated/endpoint_config.h, samples/matter/light_switch/snippets/lit_icd/light_switch.zap, samples/matter/light_switch/snippets/lit_icd/zap-generated/endpoint_config.h, samples/matter/light_switch/src/default_zap/light_switch.zap, samples/matter/light_switch/src/default_zap/zap-generated/endpoint_config.h, samples/matter/lock/snippets/schedules/lock.zap, samples/matter/lock/snippets/schedules/zap-generated/endpoint_config.h, samples/matter/lock/src/default_zap/lock.zap, samples/matter/lock/src/default_zap/zap-generated/endpoint_config.h, samples/matter/smoke_co_alarm/src/default_zap/smoke_co_alarm.zap, samples/matter/smoke_co_alarm/src/default_zap/zap-generated/IMClusterCommandHandler.cpp, samples/matter/smoke_co_alarm/src/default_zap/zap-generated/endpoint_config.h, samples/matter/template/src/default_zap/template.zap, samples/matter/template/src/default_zap/zap-generated/endpoint_config.h, samples/matter/thermostat/src/default_zap/thermostat.zap, samples/matter/thermostat/src/default_zap/zap-generated/endpoint_config.h, samples/matter/window_covering/src/default_zap/window-app.zap, samples/matter/window_covering/src/default_zap/zap-generated/endpoint_config.h
According to Matter 1.4 certification IDM-10.5 test case the device should contain OTA requestor device type on endpoint 0.
In all Matter samples there is no such as device type. We need to fix it to pass the certification test case.
ref: KRKNWK-19804
=> samples: matter: Fix missing OTA requestor device type.

applications/machine_learning/app_desc.rst, applications/machine_learning/intenal_module.rst
The description was outdated after introduction of sysbuild. Updating the text to reflect the current status of the build system.
=> doc: applications: Update Machine Learning description of multi-image build

doc/nrf/releases_and_maturity/known_issues.rst
Change adds a known issue related to retransmission in the ESB.
=> doc: known_issues: Add NCSDK-30802

include/sdfw/sdfw_services/device_info_service.h, subsys/sdfw_services/services/CMakeLists.txt, subsys/sdfw_services/services/Kconfig, subsys/sdfw_services/services/device_info/CMakeLists.txt, subsys/sdfw_services/services/device_info/Kconfig, subsys/sdfw_services/services/device_info/device_info_service.c, subsys/sdfw_services/services/device_info/device_info_service.cddl, subsys/sdfw_services/services/device_info/zcbor_generated/CMakeLists.txt, subsys/sdfw_services/services/device_info/zcbor_generated/device_info_service_decode.c, subsys/sdfw_services/services/device_info/zcbor_generated/device_info_service_decode.h, subsys/sdfw_services/services/device_info/zcbor_generated/device_info_service_encode.c, subsys/sdfw_services/services/device_info/zcbor_generated/device_info_service_encode.h, subsys/sdfw_services/services/device_info/zcbor_generated/device_info_service_types.h
Enable reading device information (UUID for instance) as a service requested by a client and executed by the secure domain.
=> subsys: sdfw services: add device information service.

west.yml
Fixes issue with Application core not being booted by SDFW when Wi-Fi is enabled.
=> manifest: sdk-zephyr: Pull fix for App boot with Wi-Fi on nRF54H

doc/nrf/protocols/matter/getting_started/memory_optimization.rst, samples/matter/light_bulb/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/light_bulb/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/light_switch/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/light_switch/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/lock/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/lock/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/smoke_co_alarm/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp_internal.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/thermostat/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/thermostat/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/window_covering/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/window_covering/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, west.yml
- Remove custom heap size from nRF54L15 configs.
- Reduce Packet Buffer Pool size to 11.
=> samples: matter: Reduce memory usage

west.yml
The previous -rc1 was pointing to the same SHA, let's clean this up by pointing to the right semantic tag.
=> manifest: tf-m: Point to v2.1.1-ncs2

west.yml
Backport 1d0ff55d4dbe6ef62be8b2b9c7d31540370c043b from #19705.
=> [Backport v2.9-nRF54H20-branch] manifest: tf-m: Point to v2.1.1-ncs2

west.yml
The previous v3.6.2-ncs2-rc1 tag points to the same SHA.
=> manifest: mbedtls: Point to v3.6.2-ncs2

west.yml
Backport 0a895ba42949d3ddc868898a1068b3fc2c12f575 from #19707.
=> [Backport v2.9-nRF54H20-branch] manifest: mbedtls: Point to v3.6.2-ncs2

subsys/mpsl/init/Kconfig
The MPSL uses the CONFIG_MPSL_HFCLK_LATENCY Kconfig option to setup HFCLK latency. There is an mpsl_clock_hfclk_latency_set() API that a user can call to setup the HFCLK latency. It can also be done automatically on a user behalf while mpsl_init() is executed. That will be possible when CONFIG_MPSL_HFCLK_LATENCY is user configurable.
=> subsys: mpsl: Make the CONFIG_MPSL_HFCLK_LATENCY user configurable

.github/workflows/enforce-toolchain-synchronization.yml
If actions are enabled in nrfconnect/sdk-nrf's fork, toolchain check should not be executed. It fails if developer force pushes a branch.
=> actions: Do not trigger toolchain sync in forks

doc/nrf/app_dev/device_guides/thingy91x/thingy91x_updating_fw_programmer.rst
Correct the code to flash modem with Jlink on Thingy91:X and for Application firmware.
NCSDK-31070.
=> doc: Correct code block on Updating the Thingy:91 X firmware

doc/nrf/libraries/others/contin_array.rst, doc/nrf/libraries/others/data_fifo.rst, doc/nrf/libraries/others/pcm_stream_channel_modifier.rst, doc/nrf/libraries/others/tone.rst
Fix wrong API links in some libraries.
It wrongly points to the zboss API docs.
=> doc: Fix wrong API links in some libraries

doc/nrf/releases_and_maturity/known_issues.rst, samples/matter/light_switch/boards/nrf5340dk_nrf5340_cpuapp_release.conf, samples/matter/lock/boards/nrf5340dk_nrf5340_cpuapp_release.conf, samples/matter/smoke_co_alarm/boards/nrf5340dk_nrf5340_cpuapp_release.conf, samples/matter/window_covering/boards/nrf5340dk_nrf5340_cpuapp_release.conf
Disabled RAM power down for nRF5340 DK release configuration due to DFU failures.
=> samples: matter: Disabled RAM power down for nRF5340 DK

applications/matter_bridge/boards/nrf54h20dk_nrf54h20_cpuapp.conf, samples/matter/lock/boards/nrf54h20dk_nrf54h20_cpuapp.conf, samples/matter/template/boards/nrf54h20dk_nrf54h20_cpuapp.conf, west.yml
Fixed DAC migration process for nRF54H20 and enabled Factory Data by default for that SoC.
=> samples: matter: Enable Factory Data for nRF54H20 by default.

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.9.0-nrf54h20-rc1.rst
Bump nrfutil device version to include bugfix for erase. Add purge command after installing new bundle.
=> doc: fixes to migration guide and user guide for nrf54h20

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ctr_drbg.c
Reset the reseed counter when reseed is performed. Without this the cracen_get_random will perform reseeding for every call when reseed counter > reseed interval (Until reseed counter overflows which will have an undefined behavior).
=> nrf_security: Reset the PRNG reseed counter in Cracen PSA

doc/nrf/releases_and_maturity/known_issues.rst
The version tag didn't render properly as it had a wrong format.
=> doc: known issues: Fix an ESB 2.9.0 issue

.github/workflows/docbuild.yml
Backport d9500b94b05c776294fda96ebb0baaedb553a47e from #19674.
=> [Backport v2.9-nRF54H20-branch] ci: fix docbuild for ubuntu 24.04

doc/nrf/app_dev/config_and_build/kconfig/index.rst, doc/nrf/app_dev/device_guides/thingy91/thingy91_building_programming.rst, doc/nrf/installation/recommended_versions.rst, doc/nrf/installation/updating.rst, samples/cellular/lwm2m_client/sample_description.rst
Fixed the missing `the` before the |nRFVSC| shortcut. NCSDK-25286.
=> doc: fix to missing the for nRFVSC

west.yml
So that native YAML lists are used.
=> manifest: pull twister YAML changes for find-my

doc/nrf/releases_and_maturity/known_issues.rst
Add known issue about omitted ZCL Reporting configuration wipe when processing Mgmt_Leave_req command.
=> doc: zigbee: add known issue NCSIDB-1411

samples/dect/dect_phy/dect_shell/README.rst
The path to the sample was missing the dect_phy folder. Added now.
=> doc: fix path to DECT shell sample

doc/_extensions/static/page_filter.mjs
Update the script so it can work for v2.9.0-nRF54H20-rc1.
=> doc: fix the known issues filter script

tests/drivers/audio/pdm_loopback/boards/nrf54l20pdk_nrf54l20_cpuapp.overlay, tests/drivers/audio/pdm_loopback/testcase.yaml
Added support for testing on nRF54l20pdk.
=> tests: drivers: audio: pdm_loopback: add support for nRF54l20

doc/nrf/libraries/security/nrf_security/doc/driver_config.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
HKDF-Extract and HKDF-Expand support have been added to cracen. Updating docs to match.
=> doc: nrf_security: Adding HKDF-extract and HKDF-Expand to supported

applications/nrf5340_audio/tools/buildprog/buildprog.py, applications/nrf5340_audio/tools/buildprog/nrf5340_audio_dk_devices.py
- OCT-3261
- References to child images has been removed
- This PR also fixes so only the selected core is built
=> Applications: Audio: Removed child images from buildprog

doc/nrf/libraries/security/nrf_security/doc/driver_config.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added ed25519ph to the supported algorithms for cracen
=> docs: nrf_security: drivers: Added ed25519ph to supported

include/bluetooth/services/ras.h, subsys/bluetooth/services/ras/rreq/ras_rreq.c
Add functionality so the RAS RREQ can read the supported features of the RAS RRSP.
=> bluetooth: services: ras: rreq: Add feature read functionality

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/bluetooth/mesh/light_ctrl_srv.c
The Light Lightness Control Server was not correctly handling scene recalls. The Server now resumes the Lightness Controller automatically after a scene recall, fixing the known issue NCSDK-30033.
=> Bluetooth: mesh: Fix scene recall for Light Ctrl server

.github/workflows/compliance.yml, .github/workflows/contribs.yml, .github/workflows/create-upmerge-PRs.yml, .github/workflows/dnm.yml, .github/workflows/docbuild.yml, .github/workflows/docker.yml, .github/workflows/docpublish.yml, .github/workflows/docremove.yml, .github/workflows/enforce-toolchain-synchronization.yml, .github/workflows/labeler.yml, .github/workflows/license-reusable.yml, .github/workflows/manifest.yml, .github/workflows/oss-history.yml, .github/workflows/reapply-ci-trusted-author.yml, .github/workflows/remove-ci-requested.yml, .github/workflows/scripts-test.yml, .github/workflows/src-mirror.yml, .github/workflows/stale.yml, .github/workflows/west-commands.yml
Use fixed version of Ubuntu runner. It prevents unexpected failures when default Ubuntu runner is updated by GitHub.
It also limits number of changes which have to be backported to legacy branches.
=> actions: Use ubuntu-24.04 instead of ubuntu-latest

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/nrf_cloud_multi_service/src/application.c
In handle_at_cmd_requests() we need to initialize msg_obj so that the parser used in nrf_cloud_obj_input_decode() operates correctly.
Jira: IRIS-9984
=> samples: cellular: nrf_cloud_multi_service: Fix at cmd handling

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_pm.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_reset.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_debugging.rst
Updated reset handling to reflect the new global domain reset handling for local domain resets, plus impact on debugging experience. Also highlighted need for local domains for good power consumption numbers.
=> doc: nrf: app_dev: nrf54h20: Global reset

samples/wifi/shell/README.rst
Added a note stating that the 91 Series devices
support only scanning.
=> doc: wifi: Fix shell sample

doc/_extensions/static/page_filter.mjs
Backport d7b7d10a340fb6b6c1c53af22ca2be677618bf4c from #19664.
=> [Backport v2.9-nRF54H20-branch] doc: fix the known issues filter script

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_customize_dfu.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_recovery.rst, samples/suit/recovery/README.rst
This commit introduces changes to docs regarding SUIT recovery sample and recovery guide.
Support for recovery app configuration with external flash was added recently.
Also, minor change to Customization DFU guide was added.
=> doc: SUIT recovery and customize DFU update

tests/benchmarks/multicore/idle_pwm_loopback/Kconfig, tests/benchmarks/multicore/idle_pwm_loopback/src/main.c, tests/benchmarks/multicore/idle_pwm_loopback/testcase.yaml
Backport 5eb1bd14753f2f8642afa8e1721a1b00ee8d75d7 from #19680.
=> [Backport v2.9-nRF54H20-branch] tests: benchmarks: multicore: Test fast PWM with different GD freq.

include/bluetooth/services/hids.h, subsys/bluetooth/services/hids.c
Allow user to set argument with which notification completion callback is called.
=> subsys: bluetooth: User data in HID service callback

doc/nrf/libraries/modem/location.rst, doc/nrf/libraries/networking/nrf_cloud_agnss.rst, doc/nrf/libraries/networking/nrf_cloud_pgps.rst, doc/nrf/releases_and_maturity/releases/release-notes-1.6.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-1.7.0.rst, samples/cellular/gnss/README.rst
Added a limitation in the library documentation. GNSS API should not be used directly by the application when Location library is used. Doing so may lead to unexpected behavior, because GNSS may be in a different state than expected by the library.
=> lib: location: Update documentation

doc/nrf/app_dev/device_guides/nrf54l/cryptography.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c
Added HMAC SHA256 as a new KMU key type.
=> nrf_security: cracen: Add HMAC SHA256 to KMU key types.

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c
Test streamer gave warnings when building with ns
Updated variable to size_t to comply with mbedcrypto
=> nrf_security: drivers: cracen: fix build errors with ns

CODEOWNERS
Cleanup hids bluetooth service codeowners information.
=> CODEOWNERS: set hids service reviewers

tests/benchmarks/multicore/idle_outside_of_main/testcase.yaml
Verify current consumption when cooperative thread is used.
=> sts: benchmarks: multicore: idle_outside_of_main: add cooperative thread

applications/nrf_desktop/src/util/config_channel_transport.h, applications/nrf_desktop/src/util/dfu_lock.h, applications/nrf_desktop/src/util/hwid.h
Make hwid header includable from a c++ code.
=> applications: nrf_desktop: hwid fix c++ compatibility

applications/serial_lte_modem/src/slm_ppp.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/modem/pdn.h, lib/pdn/pdn.c, samples/cellular/modem_shell/src/link/link_api.c
We shouldn't expect 2 DNS records from ISP. Because it sends sometimes 1 and even 0. We must just try to continue to establish PPP connection.
Real world scenario:
ISP sends DNS records as:
- Onomondo eSim in Germany in NB-IoT mode: 0 (command result: +CGCONTRDP: 0,,"onomondo","","")
- Vodafone sim in Turkey in NB-IoT mode: 0 (command result: +CGCONTRDP: 0,,"internet","","")
- Turkcell sim in Turkey in NB-IoT mode: 0 (command result: +CGCONTRDP: 0,,"nbiot","","")
- JIO sim in India in NB-IoT mode: 1 (command result: +CGCONTRDP: 0,,"jionet","","","2405:0200:0800:0000:0000:0000:0000:0006","")
MOSH was already working fine with allowing like that I've implemented here for SLM. We were using MOSH in at_cmd_mode on our product. However we want to use SLM; because, SLM is an application while …
=> applications: slm: try to continue even no DNS record was sent

include/modem/lte_lc.h, lib/lte_link_control/modules/ncellmeas.c, tests/lib/location/src/location_test.c, tests/lib/lte_lc_api/src/lte_lc_api_test.c
Added check to skip `%NCELLMEAS` notification parsing when neighbor cell measurement has not been requested by calling `lte_lc_neighbor_cell_measurement()`. If the neighbor cell measurement is triggered by sending the `AT%NCELLMEAS` AT command to the modem, LTE LC does not know how the received notification should be parsed, sometimes leading to a parsing error.
Added missing time units in structs `lte_lc_cell` and `lte_lc_ncell`.
=> lib: lte_link_control: Skip parsing of unexpected %NCELLMEAS notif

samples/wifi/radio_test/radio_test_subcommands.rst, samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
[SHEL-3378] Correct description for tx tone transmission subcommand.
[SHEL-3378]: https://nordicsemi.atlassian.net/browse/SHEL-3378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> samples: wifi: radio_test: Improve tone trasmit command description

subsys/mgmt/suitfu/src/suitfu_mgmt_suit.c, subsys/suit/memory_layout/src/suit_memory_layout.c, subsys/suit/storage/Kconfig, subsys/suit/storage/include/suit_storage_internal.h, subsys/suit/storage/src/suit_storage_update.c, subsys/suit/utils/src/suit_plat_mem_util.c
Remove pieces, that were required for Eng A board support, as well as old DTS definitions.
Ref: NCSDK-30398
=> suit: Remove legacy implementation

config/suit/templates/nrf54h20/default/v1/app_recovery_local_envelope.yaml.jinja2
If recovery was run with external flash the initialization took too long, resulting in recovery not booting.
=> suit: increase synchronous invoke timeout

subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/blkcipher.c
The input variable in the function sx_blkcipher_ecb_simple is a pointer and not an array. So sizeof cannot be used to determine the array size. Replace this with the input_size variable which contains the correct iput size of the buffer.
=> nrf_security: Fix data cache buffer size in Cracen

scripts/twister/alt/zephyr/samples/sensor/accel_polling/sample.yaml
As this will fail to output coverage data - messages dropped.
=> scripts: alt: accel_polling: do not use logging with coverage

west.yml
Improve exception handling when parsing corrupted CBOR inputs
=> manifest: update suit-generator sha

west.yml
=> [Backport v2.9-nRF54H20-branch] manifest: update sdk-zephyr revision with custom jlink script removal

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, west.yml
We can speed up flash operations while performing a factory reset by disabling mpsl before that.
Thanks to that flash operations do not wait for mpsl synchronization and all write operations take less time.
=> samples: matter: disable mpsl before preforming factory reset

.github/workflows/enforce-toolchain-synchronization.yml
Action should be run only on branches which are targets of PRs.
=> actions: Limit Toolchain Sync execution

config/suit/templates/nrf54h20/default/v1/app_recovery_local_envelope.yaml.jinja2
Backport 919489e74c78bc14fed7627070e45dc7f53b0b02 from #19824.
=> [Backport v2.9-nRF54H20-branch] suit: increase synchronous invoke timeout

subsys/mgmt/suitfu/src/suitfu_mgmt_suit.c, subsys/suit/memory_layout/src/suit_memory_layout.c, subsys/suit/storage/Kconfig, subsys/suit/storage/include/suit_storage_internal.h, subsys/suit/storage/src/suit_storage_update.c, subsys/suit/utils/src/suit_plat_mem_util.c
Backport b777188d6a29f037b8990b110a6d4f1f0ff2a61b from #19776.
=> [Backport v2.9-nRF54H20-branch] suit: Remove legacy implementation

tests/psa_crypto/prj.conf, tests/psa_crypto/tests/test_ikg_identity_key_sign_verify.c, tests/psa_crypto/tests/test_kmu_write.c
Removed redundant config from psa_crypto tests
Cleaned up comment
=> tests: psa_crypto: Clean up configs

scripts/quarantine.yaml
=> quarantine: update

samples/openthread/cli/harness-thci/nRF_Connect_SDK_13_14.py
Fix incorrect default value of CSL period in 1.3/1.4 THCI
=> samples: openthread: fix THCI for Thread 1.3/1.4

tests/benchmarks/multicore/idle/testcase.yaml
Add test case that will count reboots after DUT power cycle
=> tests: benchmarks: Check if unexpected resets happens at H20

subsys/bluetooth/mesh/time_srv.c
Commit fixes uptime to tai inaccuracy conversion.
Previous implementation did not take into account
subseconds overflow that caused -1 second inaccuracy.
=> Bluetooth: Mesh: fix uptime to tai conversion inaccuracy

subsys/net/openthread/Kconfig.defconfig, west.yml
1.4 is now a default Thread version, 1.3 libraries are not needed anymore.
=> openthread: remove 1.3 prebuilt libraries

applications/matter_bridge/sample.yaml, samples/matter/light_bulb/sample.yaml, samples/matter/light_switch/sample.yaml, samples/matter/lock/sample.yaml, samples/matter/smoke_co_alarm/sample.yaml, samples/matter/template/sample.yaml
Change unifies the way of extra args definition in sample yamls in matter objects
=> samples: matter: align extra args in sample yamls

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/installation/install_ncs.rst, doc/nrf/installation/recommended_versions.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added information about the required installation of USB Driver for J-Link on Windows. Moved installation instructions to nRF Util docs and removed them from the nRF54H20 Getting Started Guide. NCD-909.
----
Related nRF Util PR https://github.com/NordicSemiconductor/nrfutil-rs/pull/2563 
----
=> doc: nrf util: usb driver prerequisite for win

doc/nrf/libraries/modem/lte_lc.rst, include/modem/lte_lc.h
Adding a note that LTE LC and `nrf_modem_at` APIs should be used together with caution.
A comment in `lte_lc_connect*` that reconnection happens automatically.
=> lib: lte_link_control: Misc doc updates

samples/bluetooth/direct_test_mode/README.rst
Refer actual encoding of the test commands and events section of BLE Core Spec in Direct test mode sample.
TECHDOC-3198
=> doc: Refer test commands section of BLE Core Spec in DTM sample

config/suit/templates/nrf54h20/default/v1/root_with_binary_nordic_top.yaml.jinja2
Since the set of selected components is local for each run-sequence and try-each sequences, the active component must be set to CAND_MFST before fetching and processing of Nordic top candidate manifest.
Ref: NCSDK-31295
=> suit: Fix Nordic top candidate verification seq

subsys/bluetooth/controller/hci_driver.c
This PR fixes deadlock in MPSL workq caused by bt_buf_get_rx with
K_FOREVER.
Previously, calling bt_buf_get_rx with K_FOREVER could block
indefinitely if the requested pool had no available buffers. This
blocking affected the MPSL work queue, preventing it from processing
other work items, including critical timeslot events like
MPSL_TIMESLOT_SIGNAL_CANCELLED and MPSL_TIMESLOT_SIGNAL_BLOCKED.
The issue becomes more severe if a background flash operation coincides
with this scenario. Flash operations often execute on the system work
queue (sysworkq), which can delay host work items responsible for
freeing buffers in the RX pool. In such cases:
- Flash operations stall, waiting for a timeslot event from the MPSL
work queue.
- The MPSL work queue remains blocked by bt_buf_get_rx.
- This …
=> bluetooth: hci_driver: Fix deadlock in MPSL workq

config/suit/templates/nrf54h20/default/v1/root_with_binary_nordic_top.yaml.jinja2
Backport 5ae88098dfb7279a30f153eb9b7f06ff691ba60c from #19867.
=> [Backport v2.9-nRF54H20-branch] suit: Fix Nordic top candidate verification seq

cmake/sysbuild/suit.cmake, cmake/sysbuild/suit_utilities.cmake, config/suit/templates/nrf54h20/default/v1/app_envelope.yaml.jinja2, config/suit/templates/nrf54h20/default/v1/rad_envelope.yaml.jinja2, samples/suit/smp_transfer/suit/nrf54h20/app_envelope_extflash.yaml.jinja2, samples/suit/smp_transfer/suit/nrf54h20/rad_envelope_extflash.yaml.jinja2, sysbuild/Kconfig.suit, west.yml
This commit contains changes to the SUIT build system allowing for encrypting images for update.
=> suit: Build system changes needed for encryption

applications/matter_bridge/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/light_bulb/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/light_switch/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/lock/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/smoke_co_alarm/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/template/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/thermostat/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/window_covering/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay
Disable GPIO forwarder in mcuboot for nRF5340 DK for nRF7002 EK compatibility.
=> samples: matter: Disable GPIO forwarder in mcuboot

applications/nrf_desktop/configuration/common/hid_report_desc.h
Handle max input and output report size in scalable way.
=> applications: nrf_desktop: generic max report size handling

boards/shields/pca63566/boards/nrf54h20dk_nrf54h20_common.dtsi, tests/benchmarks/power_consumption/common/main.c, tests/benchmarks/power_consumption/i2c/src/driver_test.c
Test was suspending test thread from the timer interrupt at random (but periodic) point. I2c driver handles power management in the thread context. Randomly suspending the test thread could lead to a case where driver did not finish requested operation and system goes to s2ram in the middle of the driver operation.
PR extends framework to allow optional requesting of the test thread suspension (instead of forcing) and test thread suspends itself when requested. It is done after driver operation is finished.
Additionally, added enabling of the runtime power management to the i2c instance used by the shield used in the test.
=> tests: benchmarks: power_consumption: i2c: Fix increased power consumpion

CODEOWNERS
The files in include/bluetooth/ and subsys/bluetooth/ are rather diverse and not necessarily related to system integration.
ncs-si-muffin can be kept as code owners of some specific headers and subdirectories if desired.
=> bluetooth: remove ncs-si-muffin as bluetooth code owners

include/bluetooth/hci_vs_sdc.h, subsys/bluetooth/controller/hci_internal.c, subsys/bluetooth/hci_vs_sdc.c
This command was deprecated a long time ago.
=> bluetooth: controller: remove vs supported commands implementation

include/bluetooth/mesh/gen_loc.h, subsys/bluetooth/mesh/gen_loc_internal.h, subsys/bluetooth/mesh/gen_loc_srv.c, subsys/bluetooth/mesh/shell/shell_loc_cli.c
Commit fixes default values for:
- Global Latitude
- Global Longitude
- Local North
- Local East
Adds intermediate default for double WGS84 latitude\longitude.
=> Bluetooth: Mesh: fix defaults for generic location srv

subsys/sdfw_services/services/echo/zcbor_generated/CMakeLists.txt, subsys/sdfw_services/services/echo/zcbor_generated/echo_service_decode.c, subsys/sdfw_services/services/echo/zcbor_generated/echo_service_decode.h, subsys/sdfw_services/services/echo/zcbor_generated/echo_service_encode.c, subsys/sdfw_services/services/echo/zcbor_generated/echo_service_encode.h, subsys/sdfw_services/services/echo/zcbor_generated/echo_service_types.h, subsys/sdfw_services/services/psa_crypto/Kconfig, subsys/sdfw_services/services/psa_crypto/psa_crypto_service.cddl, subsys/sdfw_services/services/psa_crypto/zcbor_generated/CMakeLists.txt, subsys/sdfw_services/services/psa_crypto/zcbor_generated/psa_crypto_service_decode.c, subsys/sdfw_services/services/psa_crypto/zcbor_generated/psa_crypto_service_decode.h, subsys/sdfw_services/services/psa_crypto/zcbor_generated/psa_crypto_service_encode.c, subsys/sdfw_services/services/psa_crypto/zcbor_generated/psa_crypto_service_encode.h, subsys/sdfw_services/services/psa_crypto/zcbor_generated/psa_crypto_service_types.h, subsys/sdfw_services/services/reset_evt/zcbor_generated/CMakeLists.txt, subsys/sdfw_services/services/reset_evt/zcbor_generated/reset_evt_service_decode.c, subsys/sdfw_services/services/reset_evt/zcbor_generated/reset_evt_service_decode.h, subsys/sdfw_services/services/reset_evt/zcbor_generated/reset_evt_service_encode.c, subsys/sdfw_services/services/reset_evt/zcbor_generated/reset_evt_service_encode.h, subsys/sdfw_services/services/reset_evt/zcbor_generated/reset_evt_service_types.h, subsys/sdfw_services/services/sdfw_update/zcbor_generated/CMakeLists.txt, subsys/sdfw_services/services/sdfw_update/zcbor_generated/sdfw_update_service_decode.c, subsys/sdfw_services/services/sdfw_update/zcbor_generated/sdfw_update_service_decode.h, subsys/sdfw_services/services/sdfw_update/zcbor_generated/sdfw_update_service_encode.c, subsys/sdfw_services/services/sdfw_update/zcbor_generated/sdfw_update_service_encode.h, subsys/sdfw_services/services/sdfw_update/zcbor_generated/sdfw_update_service_types.h
Relevant changes are in the second commit.
The first commit is just regenerating zcbor code.
=> sdfw_services: psa_crypto: use new tags for pointer-to-const members

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_clockman.rst
Added GDFS to 54H clock Arch doc.
=> doc: Added GDFS to 54H clock Arch doc

.github/workflows/enforce-toolchain-synchronization.yml
By default `gh pr list` limits output to 30 found PRs. `--jq` expressions  filters JSON output, not PRs, which means it is evaluated after PRs number is reduced by `--limit` .
=> actions: Bump limit of listed PRs

boards/shields/pca63566/boards/nrf54h20dk_nrf54h20_common.dtsi, tests/benchmarks/power_consumption/common/main.c, tests/benchmarks/power_consumption/i2c/src/driver_test.c
Backport 6dd7041c44f61e808133384d87069e842ae678ce~3..6dd7041c44f61e808133384d87069e842ae678ce from #19861.
=> [Backport v2.9-nRF54H20-branch] tests: benchmarks: power_consumption: i2c: Fix increased power consumpion

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/direct_test_mode/src/dtm.c, samples/peripheral/radio_test/src/main.c, subsys/esb/esb.c
Loading trim values and adding PAN workarounds in the Radio registers will improve RF performance. PANs implemented: HMPAN-18, HMPAN-103.
Ref. NCSDK-31274
=> samples: Add radio trims and PAN for nRF54H20 in DTM, RT and ESB

doc/nrf/app_dev/device_guides/nrf54l/cryptography.rst
Removed wrong key use for MKEK and MEXT
=> doc: updated IKG docs for nrf54l15

samples/bluetooth/direct_test_mode/src/dtm.c
Correct packet length calculation for BLE_1Mbit mode
=> samples: bluetooth: Bugfix in DTM

subsys/nrf_security/src/threading/threading.cmake, west.yml
This fixes a dependency when including the threading_alt.h
from nrf_security.
The CC3XX platform library provides the implementation of the
mbedtls_mutex functions and it expects the mbedTLS mutexes to be of
type nrf_cc3xx_platform_mutex_t.
The definitions of the mutexes included in the files
nrf_cc3xx_platform_mutex_(zephyr/freertos).c
The threading_alt.c in nrf_security defines the mbedTLS mutexes
as Zephyr mutexes (k_mutex). This doesn't work when the CC3XX
platform library is used, so here this dependency is added.
Ref: NCSDK-31155
=> nrf_security: Fix dependency for threading_alt.h

doc/nrf/libraries/modem/pdn.rst, include/modem/pdn.h, lib/pdn/Kconfig, lib/pdn/esm.c
Aligned terminology in the library API and documentation.
Updated ESM cause list according to 3GPP TS 24.301 v14.10.0.
=> lib: pdn: Update library API and documentation

subsys/sdfw_services/services/echo/zcbor_generated/CMakeLists.txt, subsys/sdfw_services/services/echo/zcbor_generated/echo_service_decode.c, subsys/sdfw_services/services/echo/zcbor_generated/echo_service_decode.h, subsys/sdfw_services/services/echo/zcbor_generated/echo_service_encode.c, subsys/sdfw_services/services/echo/zcbor_generated/echo_service_encode.h, subsys/sdfw_services/services/echo/zcbor_generated/echo_service_types.h, subsys/sdfw_services/services/psa_crypto/Kconfig, subsys/sdfw_services/services/psa_crypto/psa_crypto_service.cddl, subsys/sdfw_services/services/psa_crypto/zcbor_generated/CMakeLists.txt, subsys/sdfw_services/services/psa_crypto/zcbor_generated/psa_crypto_service_decode.c, subsys/sdfw_services/services/psa_crypto/zcbor_generated/psa_crypto_service_decode.h, subsys/sdfw_services/services/psa_crypto/zcbor_generated/psa_crypto_service_encode.c, subsys/sdfw_services/services/psa_crypto/zcbor_generated/psa_crypto_service_encode.h, subsys/sdfw_services/services/psa_crypto/zcbor_generated/psa_crypto_service_types.h, subsys/sdfw_services/services/reset_evt/zcbor_generated/CMakeLists.txt, subsys/sdfw_services/services/reset_evt/zcbor_generated/reset_evt_service_decode.c, subsys/sdfw_services/services/reset_evt/zcbor_generated/reset_evt_service_decode.h, subsys/sdfw_services/services/reset_evt/zcbor_generated/reset_evt_service_encode.c, subsys/sdfw_services/services/reset_evt/zcbor_generated/reset_evt_service_encode.h, subsys/sdfw_services/services/reset_evt/zcbor_generated/reset_evt_service_types.h, subsys/sdfw_services/services/sdfw_update/zcbor_generated/CMakeLists.txt, subsys/sdfw_services/services/sdfw_update/zcbor_generated/sdfw_update_service_decode.c, subsys/sdfw_services/services/sdfw_update/zcbor_generated/sdfw_update_service_decode.h, subsys/sdfw_services/services/sdfw_update/zcbor_generated/sdfw_update_service_encode.c, subsys/sdfw_services/services/sdfw_update/zcbor_generated/sdfw_update_service_encode.h, subsys/sdfw_services/services/sdfw_update/zcbor_generated/sdfw_update_service_types.h
Backport 48253248ecc493e0c3fed104f8ff090d5a55964d~2..48253248ecc493e0c3fed104f8ff090d5a55964d from #19808.
=> [Backport v2.9-nRF54H20-branch] sdfw_services: psa_crypto: use new tags for pointer-to-const members

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/modem/lte_lc.h, lib/lte_link_control/modules/ncellmeas.c, tests/lib/lte_lc_api/src/lte_lc_api_test.c
Earlier, no `LTE_LC_EVT_NEIGHBOR_CELL_MEAS` event was sent in case an error occurred during parsing of the `%NCELLMEAS` notification. Because of this, the user of the library did not have any way to determine when the operation had been completed. The implementation has been changed so, that an `LTE_LC_EVT_NEIGHBOR_CELL_MEAS` event is always sent, if `lte_lc_neighbor_cell_measurement()` has returned `0`. In case of an error, an empty `LTE_LC_EVT_NEIGHBOR_CELL_MEAS` (`current_cell` set to `LTE_LC_CELL_EUTRAN_ID_INVALID`) is sent.
Removed Kconfig links from the library header. The reason behind the change is that Breathe is no longer used when generating the documentation, and without Breathe the links do not work and only cause the generated documentation to look bad.
=> lib: lte_link_control: Send NEIGHBOR_CELL_MEAS event in case of error

samples/net/download/CMakeLists.txt
Fix compilation error when secure socket has been disabled in the sample.
Because of Kconfig dependency the sample cert file is not defined resulting in cmake error.
=> samples: net: download: Fix compilation with secure socket disabled

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add a note about fixed issue where a flash operation executed on the system workqueue might result in `-ETIMEDOUT` if there is an active Bluetooth LE connection.
Ref: https://github.com/nrfconnect/sdk-nrf/pull/18953
=> doc: release notes: Add note about fixed flash driver and ble coop

scripts/quarantine_integration.yaml
As switching to testing template with smp_dfu on nRF7002 in integration, we need it to be built there.
=> scripts: remove a sample from quarantine integration.yaml

include/modem/pdn.h, lib/bin/lwm2m_carrier/include/lwm2m_os.h
* in the PDN library the callback (de)register functions were missing retvals. These are useful to have for users such as the LwM2M carrier library.
* The LwM2M OS layer implies that ``lwm2m_os_pdn_id_get()`` returns 0 on success (which it _can_, yet it is a bit misleading).
* Added mention of -ERRNO for activate and deactivate functions.
=> doc: pdn: lwm2m_carrier: Improve the PDN header file documentation

subsys/net/openthread/Kconfig.defconfig, west.yml
Pull OT and Zephyr with diagnostic module related fixes.
=> openthread: fix diags modules

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/links.txt
Fixed the incorrect trace version in the Getting Started with nRF54H20. Condensed the installation instructions for nRF Util by adding links to the nRF Util docs. NRFU-1392.
=> doc: nrf54h20: fix trace version and rephrase text

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/dfu/fmfu_fdev/include/modem_update_decode.h, subsys/dfu/fmfu_fdev/include/modem_update_types.h, subsys/dfu/fmfu_fdev/src/modem_update_decode.c, subsys/sdfw_services/services/enc_fw/zcbor_generated/enc_fw_service_decode.c, subsys/sdfw_services/services/enc_fw/zcbor_generated/enc_fw_service_decode.h, subsys/sdfw_services/services/enc_fw/zcbor_generated/enc_fw_service_encode.c, subsys/sdfw_services/services/enc_fw/zcbor_generated/enc_fw_service_encode.h, subsys/sdfw_services/services/enc_fw/zcbor_generated/enc_fw_service_types.h, subsys/sdfw_services/services/extmem/zcbor_generated/extmem_service_decode.c, subsys/sdfw_services/services/extmem/zcbor_generated/extmem_service_decode.h, subsys/sdfw_services/services/extmem/zcbor_generated/extmem_service_encode.c, subsys/sdfw_services/services/extmem/zcbor_generated/extmem_service_encode.h, subsys/sdfw_services/services/extmem/zcbor_generated/extmem_service_types.h
=> Regenerate code with zcbor 0.9.0

doc/nrf/app_dev/create_application.rst, doc/nrf/glossary.rst, doc/nrf/integrations.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added mentions of the nRF Connect SDK Add-ons page and the ncs-app-index repository to the pages Create an application and Integrations. Added a glossary entry.
VSC-2765.
=> doc: add-ons: add information about the index

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_pm.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_reset.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_debugging.rst
Backport 40e3d4f950ed908fe321aaebf679308d3074fb83 from #19608.
=> [Backport v2.9-nRF54H20-branch] doc: nrf: app_dev: nrf54h20: Global reset

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_clockman.rst
Backport f38d3119502c014935538628b3305009dd0697ff from #19684.
=> [Backport v2.9-nRF54H20-branch] doc: Added GDFS to 54H clock Arch doc

include/bluetooth/services/hids.h, subsys/bluetooth/services/hids.c
Add information about report id as argument to the callbacks. The old callback format is kept for backwards compatibility.
=> subsys: bluetooth: pass information on report id in callbacks

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, doc/nrf/shortcuts.txt
Updated the required version of SEGGER J-Link in docs to v8.10f. NRFU-1388.
=> doc: j-link: update version to 8.10f

subsys/bluetooth/Kconfig.discovery, subsys/bluetooth/services/ras/rreq/Kconfig.ras_rreq
Add heap requirement to gatt_dm.
Make use of HEAP_MEM_POOL_ADD_SIZE_* Kconfig
to increase required heap for gatt_dm module.
Remove the requirement from ras service, since
the requirement is added to gatt_dm itself.
Jira: NCSDK-31002
=> bluetooth: Add required heap to the gatt_dm

doc/nrf/app_dev/create_application.rst
Updated one line in the freestanding application description. The line became incorrect with the recent changes in the IDE. The new line is reused from the adding_code.rst and more accurate. Reported by @kylebonnici.
=> doc: create_application: fix freestanding app desc

samples/crypto/psa_tls/sample.yaml
Added test cases for cracen backend to run TLS 1.3 tests
=> samples: psa_tls: Add TLS 1.3 tests for cracen

scripts/docker/Dockerfile
=> sdk-nrf-toolchain: Bump JLink version to v8.10f

subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.h, subsys/nrf_security/src/psa_crypto_driver_wrappers.c
This refactors the function cracen_get_opaque_size so that it returns psa_status_t and not a size_t value. With ths previous implementation it was not possible to distinguish between a key with invalid arguments or a key which is revoked. Revocation support will be added soon and this separation is needed.
=> nrf_security: Refactor get_opaque_size function

samples/crypto/psa_tls/sample.yaml
Folder naming scheme was wrong for tls 1.3 tests with cracen + oberon backend. Fixed it.
=> samples: psa_tls: Fix folder naming for tls tests

lib/location/method_gnss.c, tests/lib/location/src/location_test.c
GNSS asks for some A-GNSS data, like UTC and iono parameters, once every 24 hours. This may have caused a separate A-GNSS data request for this data alone. The implementation has now been modified to skip such a request. All data is downloaded with the next ephemeris request, which happens approximately every two hours.
=> lib: location: skip A-GNSS data request when no ephe/alm requested

cmake/dfu_multi_image.cmake, subsys/bootloader/cmake/packaging.cmake
* Move running dfu_multi_image_tool.py out of custom target to stop regenerating the image on every build.
* Fix DEPENDS for dfu_multi_image_package.
=> cmake: Prevent regenerating dfu multi image on every build

tests/benchmarks/kernel_freq_change/testcase.yaml
More time needed for stress tests.
=> tests: benchmarks: kernel_freq_change: extend timeout

doc/_extensions/page_filter.py
Updating regex in the py file to match mjs.
=> doc: fix to known issues py script

doc/nrf/app_dev/config_and_build/hardware/add_new_driver.rst, doc/nrf/app_dev/config_and_build/hardware/add_new_led_example.rst, doc/nrf/app_dev/config_and_build/hardware/index.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, doc/nrf/shortcuts.txt
Moved the steps for adding a LED node from VSC extension docs to a new page under Configuring devicetree.
VSC-2802.
=> doc: hardware: Move LED example to a separate page

doc/nrf/links.txt, doc/nrf/security/ap_protect.rst
Added link to the AP-Protect section in the nRF54L15 datasheet.
=> doc: ap_protect: add link to nRF54L15 datasheet

CODEOWNERS, tests/drivers/sdp_asm/CMakeLists.txt, tests/drivers/sdp_asm/prj.conf, tests/drivers/sdp_asm/pytest/test_sdp_asm.py, tests/drivers/sdp_asm/src/add_1.c, tests/drivers/sdp_asm/src/add_1.h, tests/drivers/sdp_asm/src/add_1.s, tests/drivers/sdp_asm/src/add_10.c, tests/drivers/sdp_asm/src/add_10.h, tests/drivers/sdp_asm/src/add_10.s, tests/drivers/sdp_asm/src/add_100.c, tests/drivers/sdp_asm/src/add_100.h, tests/drivers/sdp_asm/src/add_100.s, tests/drivers/sdp_asm/src/main.c, tests/drivers/sdp_asm/testcase.yaml
Add test that confirms operation of Software Defined Peripherals Assembly Management.
=> tests: drivers: Add test for SDP ASM

subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/hci_driver.c
Add dependencies to SoftDevice Controller specific config entries so that symbols that are not relevant for a given application cannot be configured. This requires some change to source code as well because some Kconfig entries are now undefined for some application configurations.
=> bluetooth: controller: Add dependencies to Kconfig symbols

subsys/logging/log_backend_rpc.c, subsys/logging/log_backend_rpc_history.h, subsys/logging/log_backend_rpc_history_ram.c
While the log history is being transferred to the logging RPC client, do not overwrite the least recent logs in the log history, so that the history being transferred doesn't have gaps.
=> logging: rpc: disable overwriting while history transfer

doc/nrf/links.txt, doc/nrf/protocols/matter/overview/group_communication.rst, doc/nrf/protocols/matter/overview/index.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Describing how to set up Group Communication
between the controller and a sample in the Matter
protocol documentation.
ref: KRKNWK-17365
=> doc: Matter protocol: add Group Communication

samples/bluetooth/scanning_while_connecting/README.rst, samples/bluetooth/scanning_while_connecting/src/main.c
Update bluetooth softdevice controller configuration to achieve faster connection establishment.
=> samples: Bluetooth: update scanning_while_connecting sample

subsys/esb/esb.c, subsys/esb/esb_dppi.c
Backport be1549932bd0200a7d2da4c61e2c7b8132d514d2 from #19347.
=> [Backport v2.9-branch] esb: Fix timer configuration

CODEOWNERS, doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, snippets/matter-debug/boards/nrf52840dk_nrf52840.overlay, snippets/matter-debug/boards/nrf5340dk_nrf5340_cpuapp.overlay, snippets/matter-debug/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, snippets/matter-debug/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, snippets/matter-debug/boards/nrf7002dk_nrf5340_cpuapp.overlay, snippets/matter-debug/matter_debug.conf, snippets/matter-debug/snippet.yml
Utilizing this snippet:
- Extended log buffer size
- Increased UART speed to 1M
- Eabled OpenThread debug
- Disabled log size optimization
- Switched to log mode deferred.
=> snippets: matter: Added snippet for matter debug purposes

include/bluetooth/mesh/light_temp_srv.h, subsys/bluetooth/mesh/light_temp_srv.c
| From the Mesh Model Specification v1.0.1, Section 6.4.4.1:
This model shall support model publication, as defined in Section 4.2.2 of the Mesh Profile specification.
The Mesh Profile Specification v1.0.1, Section 4.2.2 defines model publication as a composite state that controls message publishing parameters, including:
Publish Address
Publish Period
Retransmission Settings
The implementation adds publication support following the same pattern established in the light_ctl_srv, ensuring consistency with existing model implementations while fulfilling the specification's requirements. This approach maintains architectural coherence within the Bluetooth mesh stack.
=> Support for Model Publication in Light CTL Temperature Server

doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst, snippets/matter-debug/snippet.yml
We need to use exact boards for matter-debug snippet. If a user wants to add it to their board, they must increase UART speed manually. Added the update in the docs as well. 
The dts overlay with UART speed increase is not applicable to the Thingy board since it uses USB.
=> snippets: matter: Use boards instead of wildcards for matter-debug

samples/matter/common/src/binding/binding_handler.cpp, samples/matter/light_bulb/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/light_bulb/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/light_switch/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/light_switch/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/light_switch/src/shell_commands.cpp, samples/matter/lock/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/lock/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/smoke_co_alarm/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/matter/smoke_co_alarm/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp_internal.conf, samples/matter/template/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/thermostat/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/thermostat/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, samples/matter/thermostat/src/temperature_measurement/sensor.cpp, samples/matter/window_covering/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/window_covering/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf, west.yml
In few places there are missing nullptr checks, what can lead to using not allocated memory.
=> samples: matter: Added nullptr checks after memory allocation

samples/benchmarks/coremark/prj.conf, samples/benchmarks/coremark/prj_flash_and_run.conf, samples/benchmarks/coremark/prj_heap_memory.conf, samples/benchmarks/coremark/prj_multiple_threads.conf, samples/benchmarks/coremark/prj_static_memory.conf, samples/benchmarks/coremark/src/main.c
Set coremark main thread to cooperative priority at start of main - requirement to allow starting drivers form non-blocking context.
Add extra compiler flags to improve performance.
Change log level to enable seeing errors.
=> Coremark issues for NCS 3.0.0

samples/bluetooth/direct_test_mode/src/dtm.c, samples/peripheral/radio_test/src/main.c, subsys/esb/esb.c
Backport 693d1ff87bd63a48db2f719564aae9f991c09451 from #19878.
=> [Backport v2.9-nRF54H20-branch] samples: Add radio trims and PAN for nRF54H20 in DTM, RT and ESB

applications/serial_lte_modem/src/http_c/slm_at_httpc.c
Fixes a crash when AT#XHTTPCREQ is called when thread from previous call is still in process.
The issue had been seen earlier with multiple thread, but the correction never made it to main:
https://github.com/nrfconnect/sdk-nrf/pull/10285
=> applications: serial_lte_modem: Fix AT#XHTTPCREQ crash

subsys/bluetooth/mesh/gen_dtt_srv.c
Finds the element index used in `bt_mesh_dtt_srv_get` based on the composition data instead of the runtime address.
Previously, the index used to locate the DTT Server was computed based on the runtime address set during provisioning. As the Scene Setup Server extends this model (which isn't necessarily present in the same element), model initialization would fail as the address wasn't yet set.
=> Bluetooth: Mesh: Fix idx in dtt_srv_get

doc/nrf/app_dev/config_and_build/building.rst
Changed verbose build command order to reflect
proper order. Previous order caused the following error:
```
> west build -b nrf54l15dk/nrf54l15/cpuapp -vvv
ERROR: source directory -vvv does not exist
FATAL ERROR: refusing to proceed without --force due to above error
```
Signed-off-by: Helmut Lord <kellyhlord@gmail.com>
=> docs: app_dev: fixed verbose build command

samples/openthread/cli/sysbuild/ipc_radio/prj.conf
Enable carrier functions required by OPENTHREAD_DIAG.
=> samples: openthread: cli: Enable 802.15.4 carrier functions

tests/benchmarks/multicore/idle_adc/testcase.yaml, tests/benchmarks/multicore/idle_clock_control/testcase.yaml, tests/benchmarks/multicore/idle_comp/testcase.yaml, tests/benchmarks/multicore/idle_exmif/testcase.yaml, tests/benchmarks/multicore/idle_ipc/testcase.yaml, tests/benchmarks/multicore/idle_pwm_led/testcase.yaml, tests/benchmarks/multicore/idle_pwm_loopback/testcase.yaml, tests/benchmarks/multicore/idle_spim/testcase.yaml, tests/benchmarks/multicore/idle_spim_loopback/testcase.yaml, tests/benchmarks/multicore/idle_twim/testcase.yaml, tests/benchmarks/multicore/idle_uarte/testcase.yaml
Part of the idle* tests have been skipped due to incorrect tags. This commit fixes this issue.
=> tests: benchmarks: Correct tags used for coverage analysis

doc/_extensions/static/page_filter.mjs
The issue related to handling more complex release names seems to be caused by HTML class names being turned to all lowercase in rst->html conversion process.
This update in mjs will convert the filter values
to lowercase before matching with class names.
=> doc: fix known issues javascript

subsys/mpsl/pm/mpsl_pm_utils.c, tests/subsys/mpsl/pm/pm_test.c
Use the new MPSL PM API where event registration
and low latency request are handled separately.
=> pm: Use new MPSL PM API

subsys/audio_module/Kconfig
When building non-audio applications the generated .config file previously contained the entries
CONFIG_AUDIO_MODULE_NAME_SIZE
CONFIG_AUDIO_MODULE_LOG_LEVEL
which we do not want to have there.
=> applications: nrf5340_audio: Hide audio configs when not enabled

doc/nrf/releases_and_maturity/known_issues.rst
The Descriptor Device Type List does not include the OTA Requestor device on endpoint 0. This causes the Matter 1.4 certification test IDM-10.5 to fail.
=> doc: known issues: Add entry regarding Matter certification.

doc/nrf/includes/application_build_and_run_ns.txt, doc/nrf/includes/build_and_run_ns.txt
Updated doc txt includes for build_and_run_ns with info where to look for */ns variant. NCSDK-29828.
=> doc: includes: add board target info to _ns txts

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, snippets/nordic-bt-rpc/boards/nrf54h20dk_nrf54h20-mem-map-move.dtsi
The Bluetooth RPC configuration for BLE samples didn't work due to an issue in the dts file that modifies the MRAM sections mapping for this build type. Application core was given an additional storage section that was intended for Radio core.
Known Issues and Release notes will be updated through respective PRs.
=> snippets: Fix nordic-bt-rpc memory remapping for BT RPC on nRF54H20.

scripts/west_commands/ncs-provision.py
Change adds support for nRF54L05 and nRF54L10 SoCs.
Jira: NCSDK-30311
=> scripts: west_commands: ncs-provision: Support nRF54L05/nRF54L10

snippets/nordic-bt-rpc/boards/nrf54h20dk_nrf54h20-mem-map-move.dtsi
The Bluetooth RPC configuration for BLE samples didn't work due to an issue in the dts file that modifies the MRAM sections mapping for this build type. Application core was given an additional storage section that was intended for Radio core:
'cpurad_storage_partition'.
Ref. NCSDK-30458
=> [Backport v2.9-nRF54H20] snippets: Fix nordic-bt-rpc memory remapping for BT RPC on nRF54H20.

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/nrf_modem_lib/lte_net_if/lte_net_if.c, lib/nrf_modem_lib/nrf9x_sockets.c, tests/lib/nrf_modem_lib/lte_net_if/src/main.c
Update the network interface MTU before raising the connectivity event, so that the MTU as queried by downstream users is correct, instead of an assumed value based on IPv6 required minimums.
=> nrf_modem_lib: lte_net_if: query actual link MTU

scripts/quarantine_windows_mac.yaml
=> scripts: quarantine_windows_mac: quarantine sample.benchmark.coremark

lib/bin/lwm2m_carrier/include/lwm2m_os.h
- Aligned the use of "retval 0" closer to the NCS codebase style.
- Corrected some functions which can return a positive integer,
such as length (as opposed to just "0 If success").
- Added documentation for some undocumented return values.
- Minor tweaks for consistendy such as spacing, and ms to milliseconds.
=> lwm2m_carrier: doc: glue documentation improvements

CODEOWNERS, scripts/ci/tags_sdk_zephyr.yaml
Base on MAINTAINERS.yml from upstream
=> scripts: ci: add more tags for sdk-zephyr

include/net/nrf_cloud_agnss.h, lib/location/method_gnss.c, samples/cellular/gnss/src/assistance.c, samples/cellular/modem_shell/src/gnss/gnss.c, samples/cellular/modem_shell/src/gnss/gnss_shell.c
Increased the A-GNSS data buffer sizes, because it was too small when ephemerides and almanacs were received for all GPS and QZSS satellites.
=> Increase A-GNSS data buffer size

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, scripts/bootloader/zb_add_ota_header.py
Allow a patch version higher than 9 in an APPLICATION_VERSION_STRING.
=> zigbee: fix application versioning in Zigbee project

scripts/quarantine.yaml, tests/drivers/sdp_asm/pytest/test_sdp_asm.py, tests/drivers/sdp_asm/src/add_1.c, tests/drivers/sdp_asm/src/add_10.c, tests/drivers/sdp_asm/src/add_100.c, tests/drivers/sdp_asm/src/main.c
Twister is unable to build tests/drivers/sdp_asm.
However, issue is not observed when test is compiled with 'west build'.
test_low_level: PR-1796
=> tests: drivers: sdp_asm: Fix build error

samples/bootloader/src/main.c
This fix helps to test UART output from board.
=> bootloader: Use proper CR-LF end line chars

boards/nordic/thingy91x/thingy91x_nrf9151_common.dts
The mapping for blue and green LEDs has been swapped for both `leds` and `pwmleds` nodes to correctly control the desired color.
From the LED table on the [Thingy91x hardware documentation](https://docs.nordicsemi.com/bundle/ug_thingy91x/page/UG/thingy91x/hw_description/leds.html) we expect the following LED mappings:
However we can see from the current board mapping that blue and green are reversed.
https://github.com/nrfconnect/sdk-nrf/blob/84ec4da2bfb18ecc3a6adffb4ae67cb520634e04/boards/nordic/thingy91x/thingy91x_nrf9151_common.dts#L29-L43
```
➜ git rev-parse HEAD
84ec4da2bfb18ecc3a6adffb4ae67cb520634e04
```
Verify that the blue and green LEDs are reversed by running the zephyr/samples/basic/blinky application with the following patch:
```
diff --git a/samples/basic/blinky/src/main.c …
```
=> boards: thingy91x: fix swapped blue/green LEDs

subsys/bluetooth/mesh/scheduler_srv.c, tests/subsys/bluetooth/mesh/scheduler_model/action_planning/src/main.c
If the Scheduler Setup Server receives a Scheduler Action Set message setting the next scheduled task to NO_ACTIONS, it will schedule the next task in line.
Previously, the "canceled" task would be executed if it was first in line.
=> Bluetooth: Mesh: fix NO_ACTIONS scheduling

CODEOWNERS, samples/matter/lock/sample.yaml, samples/matter/smoke_co_alarm/sample.yaml, samples/matter/window_covering/sample.yaml, scripts/quarantine_integration.yaml, snippets/matter-power-consumption-tests/boards/nrf54l15dk.conf, snippets/matter-power-consumption-tests/power_consumption_tests.conf, snippets/matter-power-consumption-tests/snippet.yml
Matter requires some extra configuration for the power consumption measurements that are automatized. This change introduces snippet that simplifies it and adds dedicated variant in the sample.ymls.
=> snippets: Added snippet for Matter power consumption measurements

tests/drivers/lpuart/src/main.c
Sleep between TX start and abort needs to be shorter in order to abort ongoing transmission.
=> tests: drivers: lpuart: shorten sleep before abort

subsys/suit/orchestrator/src/suit_orchestrator_sdfw.c, subsys/suit/storage/src/suit_storage_update.c, subsys/suit/stream/stream_sinks/src/suit_sdfw_recovery_sink.c, subsys/suit/stream/stream_sinks/src/suit_sdfw_sink.c
Add a small delay before reset, so there is a better chance that MRAMC will be fast enough to update memory.
Ref: NCSDK-31415
=> suit: Add delays before resets

subsys/suit/orchestrator/src/suit_orchestrator_sdfw.c, subsys/suit/storage/src/suit_storage_update.c, subsys/suit/stream/stream_sinks/src/suit_sdfw_recovery_sink.c, subsys/suit/stream/stream_sinks/src/suit_sdfw_sink.c
Backport 4a910085c4e3b51689f81ab43673ba3574a63701 from #20083.
=> [Backport v2.9-nRF54H20-branch] suit: Add delays before resets

include/net/nrf_cloud_agnss.h, lib/location/method_gnss.c, samples/cellular/gnss/src/assistance.c, samples/cellular/modem_shell/src/gnss/gnss.c, samples/cellular/modem_shell/src/gnss/gnss_shell.c
Backport 38e71566d9d0efcf42c40067dbb77b43c3cfe813 from #20046.
=> [Backport v2.9-nRF54H20-branch] Increase A-GNSS data buffer size

doc/nrf/app_dev/device_guides/nrf70/fw_patches_ext_flash.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/wifi/shell/sample.yaml, snippets/nrf70-fw-patch-ext-flash/fw-patch-ext-flash.overlay, subsys/partition_manager/CMakeLists.txt, subsys/partition_manager/Kconfig, subsys/partition_manager/pm.yml.wifi, sysbuild/Kconfig.wifi
Drop support for non-PM based build for external flash support, now PM is mandatory for cross-platform support.
Fix SHEL-3355.
=> sysbuild: nrf70: Use PM for external flash store

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/nrf_modem_lib/nrf_modem_lib.c
`nrf_modem_lib_init` should not initialize traces or log
the firmware version UUID when `nrf_modem_init` fails,
because they require the modem library to be initialized.
However it should iterate through the init callbacks and
report the returned error.
=> lib: nrf_modem_lib: jump to init callbacks when err 

samples/suit/smp_transfer/boards/nrf54h20dk_nrf54h20_cpuapp_extflash.overlay, samples/suit/smp_transfer/sysbuild/nrf54h20dk_nrf54h20_memory_map.dtsi
Align smp_transfer partitions, as proposed in:
https://github.com/nrfconnect/sdk-nrf/pull/19044
test_suit_dfu: PR-453
=> suit: Align cpuapp partitions to new memory map

samples/mpsl/timeslot/README.rst, samples/mpsl/timeslot/src/main.c
On this board, the high frequency crystal oscillator is required or timeslot requests will not be serviced in a timely manner.
=> samples: Fix mpsl/timeslot sample on nRF54H20

doc/nrf/links.txt, doc/nrf/shortcuts.txt
Updating the links after moving these docs to a new location.
=> doc: update zboss and ncp host version and links

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.h
Adds key revocation for the platform keys stored in SICR for nRF54H20.
=> nrf_security: Add key revocation for SICR keys

scripts/west_commands/ncs-provision.py
Extended NcsProvision command for another keys slots.
=> scripts: Update west command for uploading keys to KMU

doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
We have recieved a few queries about the increase in kernel heap usage when migrated to 2.9.0 from 2.7.0, so, add a couple of notes to clarify the same.
=> doc: nrf: releases: Clarify supplicant switch to kernel heap

scripts/bootloader/asn1parse.py
As the comments of `get_ecdsa_signature()` suggest, ECDSA r/s values can be short and require left-padding with zeroes. However, [this change](https://github.com/nrfconnect/sdk-nrf/commit/df0171a3d4832dc365a0ec6a8800b07bd92fd7c2) replaced the `leftpad()` function with `ljust()`, which provides right-padding. This can cause signature verification to occasionally fail when `SB_CONFIG_SECURE_BOOT_SIGNING_OPENSSL` is used:
```
[203/205] Creating validation for zephyr.hex, storing to
Traceback (most recent call last):
File "/ncs/nrf/scripts/bootloader/validation_data.py", line 109, in <module>
main()
File "/ncs/nrf/scripts/bootloader/validation_data.py", line 99, in main
append_validation_data(signature=args.signature.read(),
File "/ncs/nrf/scripts/bootloader/validation_data.py", line 48, in …
```
=> scripts: Fix extracted ECDSA signature padding

samples/benchmarks/coremark/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, samples/benchmarks/coremark/boards/nrf54h20dk_nrf54h20_cpurad.overlay
Aligned the DTS configuration of the nRF54H20 DK Application Core build target with the current state of the Zephyr STM snippet.
Ref: NCSDK-31536
=> samples: benchmarks: coremark: align nRF54H20 DTS with STM snippet

CODEOWNERS
The following scenarion happens quite often:
1. A PR is created to a subrepo referenced in the west.yml
2. The PR is reviewed. It is merged by someone in @nrfconnect/ncs-merge.
3. The PR to sdk-nrf cannot be merged until someone in @nrfconnect/ncs-code-owners approves it.
This adds additional dependencies and increases the time to integrate the change done in the subrepo. Because the sub-PR was anyways merged by someone in @nrfconnect/ncs-merge, it seems unreasonable that these people cannot also merge the manifest-PR.
Another alternatives:
1. Always require an approval from @nrfconnect/ncs-code-owners for any PR to any subrepo. This seems unreasonable.
2. Always wait for someone in @nrfconnect/ncs-code-owners to approve the (unfinished, pointing to PR) west.yml before merging the sub-PR. …
=> CODEOWNERS: Add @nrfconnect/ncs-merge as owner for west.yml

west.yml
manifest: west.yml updated to reflect zephyr TraceRecorderSource module name change to percepio.
Change occurred on Sep 12, 2023 via this PR: https://github.com/zephyrproject-rtos/zephyr/pull/62377
Signed-off-by: Erik Tamlin <erik.tamlin@percepio.com>
=> manifest: west.yml updated to reflect zephyr module name change

samples/benchmarks/coremark/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, samples/benchmarks/coremark/boards/nrf54h20dk_nrf54h20_cpurad.overlay
Backport e61c2baaac25b5ac2af4ade25209d775ca2a1138 from #20147.
=> [Backport v2.9-nRF54H20-branch] samples: benchmarks: coremark: align nRF54H20 DTS with STM snippet

subsys/esb/esb.c, subsys/esb/esb_dppi.c, subsys/esb/esb_ppi.c, subsys/esb/esb_ppi_api.h
Manual switching between radio TX/RX and RX/TX modes in fast_switching mode instead of using DPPI. In some cases, linking the RADIO_PHYEND event to the RADIO_TASK_TXEN/RXEN task caused the radio to start transmitting or receiving before the radio was configured and the appropriate buffers were set.
=> esb: Fix radio mode switching in fast_switching mode

lib/edge_impulse/CMakeLists.ei.template, lib/edge_impulse/CMakeLists.txt, samples/edge_impulse/wrapper/src/main.c
Change suppresses build warnings related to known issues. PR also fixes build warning for EI wrapper sample.
Jira: NCSDK-31594
=> lib: edge_impulse: Suppress build warnings for Edge Impulse SDK

subsys/esb/esb.c, subsys/esb/esb_dppi.c, subsys/esb/esb_ppi.c, subsys/esb/esb_ppi_api.h
Backport f59ca2120b608861633a25ca263cc7702781575c from #20098.
=> [Backport v2.9-nRF54H20-branch] esb: Fix radio mode switching in fast_switching mode

tests/lib/edge_impulse/src/edge_impulse_zip/ei_test_params.h
Use float type for constants to prevent `-Werror=double-promotion` build warnings.
Jira: NCSDK-31594
=> tests: lib: edge_impulse: Use float type for constants

subsys/nrf_security/Kconfig, subsys/nrf_security/src/drivers/Kconfig, subsys/nrf_security/src/drivers/cracen/psa_driver.Kconfig
Removes Kconfigs that are redefined because they are defined in an out of tree repo to prevent hiding problems if these symbols are renamed or removed
=> nrf_security: Remove redefined Kconfigs

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/nrf_cloud_multi_service/src/provisioning_support.h
Replacing SAMPLE_REBOOT definition to PROVISIONING_SUPPORT. Based on #19302.
=> samples: cellular: mss: Fix for wrong header name

doc/nrf/protocols/matter/getting_started/transmission_power.rst
The Kconfig item had a wrong max TX power value.
Changed it from 3 to 8.
ref: TECHDOC-3419
=> doc: Fix to max TX power in Matter GS

applications/sdp/mspi/src/hrt/hrt-nrf54l15.s, applications/sdp/mspi/src/hrt/hrt.c, applications/sdp/mspi/src/hrt/hrt.h, applications/sdp/mspi/src/main.c, drivers/mspi/mspi_nrfe.c, include/drivers/mspi/nrfe_mspi.h
=> applications: sdp: reduced IPC structures

samples/bluetooth/fast_pair/locator_tag/README.rst, samples/bluetooth/fast_pair/locator_tag/sysbuild/ipc_radio/boards/nrf54h20dk_nrf54h20_cpurad.conf
Updated the nRF54H20 DK configuration in the Fast Pair Locator Tag sample to enable the Zephyr Power Management system for the application and radio core.
=> samples: bluetooth: fast_pair: locator_tag: enable PM for nRF54H20 DK

samples/cellular/modem_shell/src/link/link.c
increased sleep time before first info read to prevent modem failures for some nrf91 dks.
=> samples: cellular: modem_shell: increased sleep time for 1st info read

west.yml
Update sdk-zephyr to add USB hibernation exit fixes:
[nrf fromlist] drivers: udc_dwc2: Set bit 17 if needed on Hibernation Exit
[nrf fromlist] drivers: udc_dwc2: Workaround hibernation exit glitch
=> manifest: pull DWC2 hibernation exit fixes from sdk-zephyr

doc/nrf/releases_and_maturity/known_issues.rst
Add a note about potential deadlock in Bluetooth Host if C2H ACL data flow control is disabled.
=> doc: known issues: Add note about potential deadlock wo C2H acl data fc

applications/nrf5340_audio/src/modules/sd_card.c, lib/date_time/date_time_core.c, lib/gcf_sms/gcf_sms.c, lib/modem_key_mgmt/modem_key_mgmt.c, modules/wfa-qt/src/indigo_api_callback_dut.c, modules/wfa-qt/src/utils.c, samples/cellular/modem_shell/src/at/at_cmd_mode.c, samples/cellular/modem_shell/src/link/link_api.c, samples/peripheral/802154_phy_test/src/ctrl/ptt_uart_proc.c, samples/peripheral/802154_phy_test/src/ctrl/ptt_zb_perf_cmd_mode_uart.c, subsys/net/lib/download_client/src/coap.c, subsys/net/lib/downloader/src/transports/coap.c, subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c, subsys/net/lib/nrf_provisioning/src/nrf_provisioning_http.c, tests/subsys/net/lib/nrf_provisioning/src/main.c
Use `strtok_r` instead of `strtok`, as `strtok` is not reentrant and uses a global state.
=> chore: change from strtok to strtok_r

applications/nrf_desktop/bootloader_dfu.rst, doc/nrf/includes/suit_fota_update_nrfcdm_test_steps.txt, samples/bluetooth/fast_pair/locator_tag/README.rst
~Adding a page to have a similar look and feel to the MCUboot-based DFU documentation.~
~As requested by @tomchy, the new page is added as an orphan so that it can be properly integrated into the SUIT documentation set after its proper restructure.~
The rationale for adding another include file is to create linkable testing steps for FOTA over Bluetooth using MCUmgr and SMP that the applications with the SUIT support can use.
=> SUIT FOTA updates section

CODEOWNERS
Clarify ownership for ncs-si-muffin: remove entries not owned by the team and add areas under its control.
=> CODEOWNERS: Clarify entries for SI Muffin.

samples/bluetooth/fast_pair/locator_tag/README.rst, samples/bluetooth/fast_pair/locator_tag/sysbuild/ipc_radio/boards/nrf54h20dk_nrf54h20_cpurad.conf
Backport cf7bad4818b1f06c8ae2f1802588e922fa04a261~2..cf7bad4818b1f06c8ae2f1802588e922fa04a261 from #20188.
=> [Backport v2.9-nRF54H20-branch] samples: bluetooth: fast_pair: locator_tag: enable PM for nRF54H20 DK

tests/benchmarks/multicore/idle_gpio/boards/wakeup_from_uart_pins.overlay, tests/benchmarks/multicore/idle_gpio/remote/boards/wakeup_from_uart_pins.overlay, tests/benchmarks/multicore/idle_gpio/src/main.c
There is need to emulate RTS to unblock transmission on board controller side when uart driver on SoC side is not used
=> tests: benchmarks: multicore: idle_gpio: Fix uart wakeup

lib/modem_info/Kconfig, lib/modem_jwt/Kconfig, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_fota, subsys/net/lib/nrf_provisioning/Kconfig, subsys/net/lib/nrf_provisioning/Kconfig.nrf_provisioning_codec, tests/subsys/net/lib/nrf_provisioning/Kconfig
`libmodem` is enabled automatically for all nRF9 projects.
Using `select` to express a dependency is bad practice, and should be avoided in favor of `depends on`.
This is a re-opening of PR #17366, which was closed and we couldn't open (maybe due to a force push).
=> treewide: do not select NRF_MODEM_LIB

applications/nrf5340_audio/src/modules/audio_i2s.c, applications/nrf5340_audio/src/modules/audio_sync_timer.c, applications/nrf5340_audio/src/modules/audio_sync_timer.h
- OCT-2585
- Added 0.39 us delay according to nRF5340 product specification.
- This resolves a race condition on sync
=> Applications: Audio: Added delay to fix initial sync

subsys/mgmt/fmfu/Kconfig
When building an application we don't want
CONFIG_MGMT_FMFU_LOG_LEVEL_DEFAULT to turn up in the generated .config file unless CONFIG_MGMT_FMFU is enabled.
=> mgmt: fmfu: Hide MGMT_FMFU logging options when not enabled

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, doc/nrf/security/ap_protect.rst
Changed nrfjprog commands to nrfutil in the AP-Protect documentation. NCSDK-30148.
----
=> doc: ap-protect: edit nrfjprog to nrfutil

west.yml
Removes this repository as HWMv1 is no longer supported
=> manfiest: Remove HWMv1 SoC repository

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add additions for TLS credential backend and modem_key_mgmt library. Add fixes for modem_key_mgmt library.
=> doc: changelog: Add TLS credential backend and modem_key_mgmt changes

doc/nrf/links.txt
Fix broken link to application note nAN34.
The link is used in the direct_test_mode sample doc -  https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/samples/bluetooth/direct_test_mode/README.html#testing_with_a_certified_tester.
=> doc: fix broken link to application note nAN34

applications/sdp/mspi/Kconfig, applications/sdp/mspi/src/hrt/hrt-nrf54l15.s, applications/sdp/mspi/src/hrt/hrt.c, applications/sdp/mspi/src/hrt/hrt.h, applications/sdp/mspi/src/main.c, drivers/mspi/mspi_nrfe.c
Added path for receiving data on SPI (SINGLE mode only, there will be another PR for QUAD).
For now, data is transceived byte by byte, and receiving starts right after transmission. This has its disadvantages, for example:
- INB register needs to be read when the transmission is still ongoing, otherwise, the clock will not be generated when a peripheral device is sending data (not sure why)
- Because data is transceived in bytes, there is less time between writing to OUTB and reading from INB. Although I checked that the current solution works for higher frequencies, it can still be a problem when processing a lot of requests from the APP.
There will be another ticket for fixing the above issues. Right now I am adding this so that we would have at least some working solution, even if it's …
=> applications: sdp: mspi: RX

tests/benchmarks/multicore/idle_uarte/src/main.c
Prevent TX abort due to timeout.
=> tests: benchmarks: multicore: idle_uarte: extend timeout for uart TX

doc/nrf/security/tfm.rst
Limit the figure size relative to font size, because it contains text, so it should not just scale up,
if the screen is wider.
=> doc: tfm: Limit figure width relative to font size

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/net/fota_download.h, subsys/net/lib/fota_download/src/fota_download.c, subsys/net/lib/fota_download/src/util/fota_download_util.c, subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c, tests/subsys/net/lib/fota_download/src/test_fota_download.c
Add error codes for
* Unsupported protocol
* DFU failure
* Invalid configuration or invalid URI
This is because Downloader may give us -EPROTONOSUPPORT or -EINVAL and these have no equivalent on FOTA Download callbacks.
DFU failures might also be usefull to see as a separate error instead of generic INTERNAL error.
=> net: fota_download: Add more error codes to callback

applications/sdp/mspi/src/hrt/hrt-nrf54l15.s, applications/sdp/mspi/src/hrt/hrt.c, applications/sdp/mspi/src/hrt/hrt.h, applications/sdp/mspi/src/main.c
=> applications: sdp: fix surplus clock edge

samples/cellular/nrf_cloud_multi_service/sysbuild/mcuboot/boards/nrf9160dk_nrf9160.conf
The MCUBoot partition size was incorrect for this one, resulting in a failing build.
=> samples: cellular: mss: fix nrf9160 padding issue

subsys/caf/modules/Kconfig.power_manager, subsys/caf/modules/power_manager.c
The `pm_state_force` should not be used to enter `PM_STATE_SOFT_OFF`. We need to use `sys_poweroff` API instead.
Jira: NCSDK-31683
=> caf: power_manager: Use `sys_poweroff` API on nRF54H20

applications/matter_bridge/sample.yaml, scripts/quarantine.yaml
Fix the name of matter_bridge debug configuration to follow the internal rules.
=> applications: matter_bridge: fix sample name config

west.yml
Update sdk-zephyr to add [nrf fromtree] fixes:
drivers: udc_dwc2: Fix large control write transfers
drivers: udc_dwc2: Recover after STALLed OUT Data Stage
drivers: udc_dwc2: Fix multipart DMA OUT transfers
drivers: udc_dwc2: Add helpers to check operating mode
drivers: udc_dwc2: Allocate multiple of bMaxPacketSize0
drivers: udc_dwc2: Stop OUT transfers on ZLP
drivers: udc_dwc2: Rework control endpoint feeding
=> manifest: pull DWC2 control transfer fixes from sdk-zephyr

applications/ipc_radio/Kconfig, applications/ipc_radio/src/bt_hci_ipc.c
Fix ipc_radio dropping HCI packets, by utilizing
the hold buffer functionality of the IPC.
Jira: NCSDK-31261
=> applications: ipc_radio: Fix ipc_radio dropping HCI packets

scripts/bootloader/do_sign.py, scripts/bootloader/keygen.py, scripts/bootloader/provision.py, scripts/bootloader/tests/conftest.py, scripts/bootloader/tests/do_sign_test.py, scripts/bootloader/tests/keygen_test.py, scripts/bootloader/tests/utils.py, scripts/bootloader/tests/validation_data_test.py, scripts/bootloader/validation_data.py, scripts/requirements-test.txt
Simplify python scripts by removing ecdsa library and rewriting code with cryptography library,
which provides same functionality.
=> scripts: Replace ecdsa library with cryptography

west.yml
This update improves the scheduler when interrupts are disabled for a longer period of time.
Note that disabling interrupts for a longer period of time is not allowed.
=> manifest: Update nrfxlib revision with updated MPSL

subsys/suit/cache/include/suit_dfu_cache_rw.h, subsys/suit/cache/src/suit_dfu_cache_rw.c, subsys/suit/orchestrator_app/src/suit_orchestrator_app.c, tests/subsys/suit/cache_pool_digest/src/main.c, tests/subsys/suit/cache_sink/src/main.c
Add a possibility to initialize DFU partition later than at the system initialization phase.
=> suit: Allow to postpone DFU initialization

samples/bluetooth/channel_sounding_ras_initiator/prj.conf, samples/bluetooth/channel_sounding_ras_reflector/prj.conf
Reduce ranging profile samples' RAM based what CS
capabilities are used in the sample parameters.
Please read the RREQ and RRSP docs for more information about how
to configure these.
=> bluetooth: samples: Reduce RAS sample memory usage

subsys/sdfw_services/services/psa_crypto/psa_crypto_service.c
Remove the call to the ssf_psa_crypto_init since the psa_crypto is initialiazed in SDFW and it doesn't need to get initialized from the application.
=> sdfw_services: Remove call to psa_crypto_init from ssf

subsys/nrf_security/src/drivers/cracen/common/include/cracen/lib_kmu.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_kmu.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/lib_kmu.c
=> nrf_security: cracen: kmu: add slot blocking function

doc/nrf/libraries/others/nrf_compression.rst
added missing CONFIG_ to NRF_COMPRESS_ARM_THUMB
=> doc: nrf: libraries: nrf_compression minor fix

applications/sdp/mspi/Kconfig, drivers/mspi/Kconfig.nrfe
=> sdp: add Kconfigs for no-copy

subsys/net/lib/nrf_cloud/coap/include/coap_codec.h
Increase `SENSOR_SEND_CBOR_MAX_SIZE` to 64 bytes to prevent encoding error when encoding humidty double values in CBOR.
=> net: lib: nrf_cloud: Increase `SENSOR_SEND_CBOR_MAX_SIZE`

lib/date_time/Kconfig
Replaced `CONFIG_POSIX_CLOCK` option with `CONFIG_POSIX_TIMERS`, which is now used to enable `clock_gettime()` and `clock_settime()` support.
=> lib: date_time: Replace deprecated CONFIG_POSIX_CLOCK option

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/nrf_cloud_multi_service/overlay_nrf700x_wifi_coap_no_lte.conf, samples/cellular/nrf_cloud_multi_service/overlay_nrf700x_wifi_mqtt_no_lte.conf
Switch to using TFM_SFN for faster crypto.
Increase TLS credentials buffer size to 3072 to allow for both AWS and CoAP CA certs.
Jira: NCSDK-29650
=> samples: cellular: nrf_cloud_multi_service: Wi-Fi improvements

drivers/mpsl/clock_control/Kconfig, subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/hci_driver.c, subsys/mpsl/CMakeLists.txt, subsys/mpsl/Kconfig, subsys/mpsl/clock_ctrl/CMakeLists.txt, subsys/mpsl/clock_ctrl/Kconfig, subsys/mpsl/clock_ctrl/mpsl_clock_ctrl.c, subsys/mpsl/clock_ctrl/mpsl_clock_ctrl.h, subsys/mpsl/init/Kconfig, subsys/mpsl/init/mpsl_init.c
The MPLS is enhanced with possibility to use it external clock driver.
That feature requires implementation of integration layer between nrf-clock-control for nRF52, nRF53 SoC series and nrf2-clock-control for nRF54H SoC series (the nRF54L SoC series is not available yet). 
The integration with nrf-clock-control is experimental.
The integration with nrf2-clock-control is supported and enabled by default for nRF54H SoC series.
nrf2-clock-control required some changes to MSPL and SDC HCI driver initialization. The nrf2-clock-control depends on nRFS
so MPLS and SDC HCI driver that depend on MPLS need to be initialized in `POST_KERNEL` system initialization level and with priority lower than nRFS initialization priority.
Besides that there were a change in radio-notification-cb host extension …
=> mpsl: Add integration layer for MPSL external clock driver

subsys/nrf_compress/src/lzma.c
Fixes a possible issue with cleanup whereby the compiler might optimise the memset function away
=> nrf_compress: lzma: Fix cleanup

scripts/quarantine_zephyr.yaml
Test configurations for scenarios
libraries.encoding.jwt.rsa.{psa | legacy} are added to quarantine due to building issues.
=> quarantine_zephyr: Add quarantine for libraries.encoding.jwt.rsa.*

samples/openthread/cli/harness-thci/nRF_Connect_SDK_13_14.py
Fix calling `netdata register` after removing srp service
=> samples: openthread: fix THCI

cmake/sysbuild/modules/ncs_sysbuild_extensions.cmake
It is necessary to configure the BOARD variable as fast as possible, since there are scritps (i.e. UICR generation) that uses this value and fail otherwise.
Ref: NCSDK-3012
=> sysbuild: Specify BOARD if the main image sets it

samples/cellular/modem_shell/src/link/link.c, samples/cellular/modem_shell/src/link/link_api.c
When registration had already been dropped, a couple of errors were shown when trying to print registration and PDN status. AT response parsing has been improved to handle also this situation.
MOSH-640
=> samples: cellular: modem_shell: Fix errors when printing link status

applications/sdp/mspi/src/hrt/hrt-nrf54l15.s, applications/sdp/mspi/src/hrt/hrt.c, applications/sdp/mspi/src/hrt/hrt.h, applications/sdp/mspi/src/main.c
To make all code changes explicitly visible, do not use pointers to functions.
=> applications: sdp: mspi: use enum instead of pointer to function in HRT

applications/matter_bridge/boards/nrf5340dk_nrf5340_cpuapp.overlay, applications/matter_weather_station/app.overlay, samples/matter/light_bulb/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/light_bulb/boards/nrf7002dk_nrf5340_cpuapp.overlay, samples/matter/light_switch/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/light_switch/boards/nrf7002dk_nrf5340_cpuapp.overlay, samples/matter/lock/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/lock/boards/nrf7002dk_nrf5340_cpuapp.overlay, samples/matter/lock/boards/nrf7002dk_nrf5340_cpuapp_nrf7001.overlay, samples/matter/smoke_co_alarm/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/template/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/template/boards/nrf7002dk_nrf5340_cpuapp.overlay, samples/matter/window_covering/boards/nrf5340dk_nrf5340_cpuapp.overlay
IPC has been switched back to rpmsg. Revert alignment change.
This reverts commit e7055e7e2e614ee4a15bd01ae86fafaaffcbe0d4.
=> Revert "samples: matter: remove `zephyr,priority` phandle"

scripts/ci/tags.yaml
If nrfxlib/mpsl/ changes we should test that the MPSL samples still build to catch any issues.
=> scripts: ci: tags: Add nrxlib/mpsl/ to ci_samples_mpsl

lib/pdn/pdn.c
`pdn_dynamic_info_get()` logged an error if no PDN connection was active when the function was called. This may be not always be considered an error (for example by modem_shell), so it's better to not log an error in this case.
=> lib: pdn: Supress error log when no PDN connection is active

applications/sdp/mspi/src/main.c, drivers/mspi/mspi_nrfe.c, include/drivers/mspi/nrfe_mspi.h
=> applications: sdp: no copy IPC

applications/asset_tracker_v2/src/modules/Kconfig.cloud_module
Removed usage of deprecated Kconfig option `CONFIG_NRF_CLOUD_SEND_SERVICE_INFO_UI`. nRF Cloud no longer uses the UI section in the shadow. Cards are displayed based on the messages sent by the device.
=> applications: asset_tracker_v2: Remove deprecated Kconfig option

doc/nrf/releases_and_maturity/known_issues.rst
Adds a known issue for the TX processor being blocked if a callback is blocking when run in the system workqueue, and the HCI command buffer pool is empty.
=> doc: Add known issue for TX processor block

subsys/bluetooth/controller/CMakeLists.txt, subsys/bluetooth/controller/cs_antenna_switch.c, subsys/bluetooth/controller/cs_antenna_switch.h, subsys/bluetooth/controller/hci_driver.c
in order to allow customers to use their own antenna switches for cs they need a way to link their antenna switching functions to the SDC.
adding the callback for the antenna switch currently supported as well as linking the new callback to the SDC.
=> driver: creating a cs multiantenna callback

CODEOWNERS, scripts/west_commands/create_board/ncs_create_board.py, scripts/west_commands/utils/__init__.py
So that communication between VSCode and extension is standardized.
Taken from https://github.com/nrfconnect/sdk-nrf/pull/19056, without nRF54H specific bits.
=> Adjust ncs-create-board to the agreed schema

west.yml
Include:
tests: drivers: watchodg: Enable wdt_error_cases on nRF5340dk
https://github.com/nrfconnect/sdk-zephyr/pull/2483
https://github.com/zephyrproject-rtos/zephyr/pull/85575
=> manifest: update sdk-zephyr, enable WDT test on nRF5340dk

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_custom_pcb.rst
Update details on how BICR is generated.
=> doc: nrf: ug_nrf54h20_custom_pcb: update BICR details

.github/workflows/docbuild.yml, doc/CMakeLists.txt, doc/_zoomin/wifi.apis.custom.properties, doc/_zoomin/wifi.apis.tags.yml, doc/nrf/conf.py, doc/nrf/drivers/wifi.rst, doc/nrf/drivers/wifi/low_level_api.rst
=> Add support for multiple Doxygen projects, add wifi bridge

west.yml
Update CDDLs so all component indexes can be listed as an argument for set-component-index command.
=> suit: Allow for selecting 16 active components

subsys/suit/platform/sdfw/src/suit_plat_component_compatibility.c
Nordic templates will use cache components to utilize IPUC-based caches in update scenarios.
Only child manifests are allowed to do so.
Ref: NCSDK-30810
=> suit: Alow for SUIT cache in Nordic manifests

applications/asset_tracker_v2/sample.yaml
Remove Thingy91 support for LwM2M + debug builds due to memory constraints.
=> applications: asset_tracker_v2: Remove Thingy91 support

applications/asset_tracker_v2/tests/debug_module/testcase.yaml, applications/asset_tracker_v2/tests/json_common/testcase.yaml, applications/asset_tracker_v2/tests/location_module/testcase.yaml, applications/asset_tracker_v2/tests/lwm2m_codec_helpers/testcase.yaml, applications/asset_tracker_v2/tests/lwm2m_integration/testcase.yaml, applications/asset_tracker_v2/tests/nrf_cloud_codec/testcase.yaml, applications/asset_tracker_v2/tests/nrf_cloud_codec_mocked_cjson/testcase.yaml, applications/asset_tracker_v2/tests/ui_module/testcase.yaml
Build unit tests only for native_sim.
Having qemu_cortex_m3 and nRF9160 DK adds no extra value.
=> applications: asset_tracker_v2: Build unit tests for native_sim

lib/nrf_modem_lib/Kconfig
Those options indicate whether the device supports IPv4 and IPv6, which is always the case when the stack offloading is enabled on nRF9 series products.
Imply these settings.
=> lib: nrf_modem: imply NET_IPV4 and NET_IPV6

include/bluetooth/services/fast_pair/fmdn.h, samples/bluetooth/fast_pair/locator_tag/configuration/prj.conf, samples/bluetooth/fast_pair/locator_tag/configuration/prj_release.conf, samples/bluetooth/fast_pair/locator_tag/src/main.c, subsys/bluetooth/services/fast_pair/fmdn/beacon_actions.c, subsys/bluetooth/services/fast_pair/fmdn/callbacks.c, subsys/bluetooth/services/fast_pair/fmdn/include_priv/fp_fmdn_callbacks.h
The following items will be covered in separate PRs:
- documentation update (Fast Pair UG + changelog)
- support for the same functionality in the sdk-find-my sample
=> Fast Pair: FMDN: support firmware version read operation

west.yml
Remove no longer used remotes from the west manifest.
=> manifest: unused remote cleanup

subsys/logging/log_backend_rpc_history_ram.c
This commit fixes an issue where a header of a MPSC buffer was overwritten by log's header causing a log be falsely claimed.
=> logging: rpc: fix overwriting of buffer's header

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Update upstream Zephyr and MCUboot SHAs to those used in the recent upmerge.
=> doc: release-notes-changelog: Update Zephyr and MCUboot SHAs

doc/nrf/app_dev/device_guides/fem/fem_nrf21540_gpio.rst, doc/nrf/app_dev/device_guides/fem/index.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/mpsl/fem/Kconfig, subsys/mpsl/fem/nrf21540_gpio/mpsl_fem_nrf21540_gpio.c
This PR adds support for the nRF21540 Front-End Module in GPIO mode for the nRF54L Series devices.
Note: This PR contains only code related configuration and documentation. The core of the support is provided by MPSL. The MPSL is prvided by a separate PR.
https://github.com/nrfconnect/sdk-nrfxlib/pull/1652
https://github.com/nrfconnect/sdk-nrf/pull/20375
=> mpsl: fem: add support for nrf21540_gpio for nrf54l

sysbuild/Kconfig.flprcore, sysbuild/Kconfig.sysbuild
Added a new general sysbuild Kconfig file with new Kconfig options that indicate support for the FLPR core.
Ref: NCSDK-30327
=> sysbuild: add support Kconfig for flpr core

applications/nrf_desktop/configuration/nrf52810dmouse_nrf52810/prj.conf, applications/nrf_desktop/configuration/nrf52810dmouse_nrf52810/prj_release.conf, applications/nrf_desktop/configuration/nrf52820dongle_nrf52820/prj.conf, applications/nrf_desktop/configuration/nrf52820dongle_nrf52820/prj_release.conf, applications/nrf_desktop/configuration/nrf52833dk_nrf52820/prj.conf, applications/nrf_desktop/configuration/nrf52833dk_nrf52820/prj_release.conf, applications/nrf_desktop/configuration/nrf52833dk_nrf52833/prj_dongle_small.conf, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, scripts/quarantine.yaml
Change introduces memory footprint optimizations for boards based on nRF52810 and nRF52820 SoCs. The optimizations are needed to make nRF Desktop again fit in these memory-limited SoCs.
The PR also removes the fixed configurations from CI quarantine and aligns system workq stack size on nrf52810dmouse to prevent faults right after boot.
Jira: NCSDK-31675
=> applications: nrf_desktop: nRF52810 and nRF52820 optimizations

subsys/logging/log_backend_rpc_history_ram.c
This commit fixes build warning reported by NCSDK-31869.
=> logging: rpc: add missing union cast

scripts/quarantine.yaml
=> scripts: quarantine: fix sample.nrf7002.ble-wifi-provision

doc/nrf/links.txt, doc/nrf/releases_and_maturity/abi_compatibility.rst
Backport 71ae1a4df9db100b0081e205537fa34a87c2f900 from #20044.
=> [Backport v2.9-nRF54H20-branch] doc: add release docs for bundle v0.9.0

samples/bluetooth/fast_pair/input_device/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/bluetooth/fast_pair/locator_tag/configuration/boards/nrf54l15dk_nrf54l15_cpuapp.conf
Increased BT RX stack size for nrf54l15dk/nrf54l15/cpuapp target to fix stack overflows encountered during FP validator tests.
Jira: NCSDK-31777
Jira: NCSDK-31786
=> samples: bluetooth: fast_pair: Increase BT RX stack size for nRF54L

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/at_host/at_host.c
If for instance trying to use `uart3` for the AT host while `CONFIG_LOG_BACKEND_UART` is enabled, AT responses all ended up in the log, not on the chosen AT host UART device.
This builds on PR https://github.com/nrfconnect/sdk-nrf/pull/20242 by @fellerts, where a fix for this issue was first posted.
=> lib: at_host: Write AT response to correct UART device

applications/ipc_radio/src/bt_hci_ipc.c
Fix spurious error of positive return value of the function ipc_service_release_rx_buffer for icbmsg.
The function should return only negative error codes, but returns positive values passed from send_release<-send_control_message<-icmsg_send . This triggers error message on successful exit.
=> applications: ipc_radio: Fix release_rx_buffer spurious error

samples/bluetooth/peripheral_with_multiple_identities/Kconfig.sysbuild
Fix issue in the peripheral with multiple identities sample.
In the Kconfig.sysbuild file, both NRF_DEFAULT_BLUETOOTH (which enables hci_ipc)
and NRF_DEFAULT_IPC_RADIO (which enables ipc_radio) are enabled.
Only NRF_DEFAULT_IPC_RADIO is required.
=> Samples: Bluetooth: Fix peripheral with multiple identities sample

doc/nrf/samples/matter.rst
Table in Matter samples misses information about ICD. Additionally, thermostat samples does not have Thread role listed.
=> doc: Updated table for Matter samples

doc/nrf/protocols/bt/bt_mesh/dfu_over_bt_mesh.rst, scripts/bluetooth/mesh/mesh_dfu_metadata.py, tests/subsys/bluetooth/mesh/metadata_extraction/verify_metadata.py
The comp data hash is an integer (32-bit unsigned integer), and, like other integers in the JSON file (CID, PID, etc. for instance), should be stored as a number in the JSON file, not a hex-encoded string.
=> Bluetooth: Mesh: Store comp data hash as Number in JSON file

samples/cellular/nrf_cloud_multi_service/README.rst
Use the newer name for the output file generated by the device_credentials_installer.py script.
Add a note to encourage the user to clone the full utils repository.
=> docs: Update nrfcloud multi service sample readme

applications/asset_tracker_v2/src/modules/modem_module.c, lib/modem_antenna/modem_antenna.c, lib/modem_battery/modem_battery.c, lib/nrf_modem_lib/cfun_hooks.c, lib/pdn/pdn.c, modules/memfault-firmware-sdk/memfault_integration.c, modules/memfault-firmware-sdk/memfault_lte_coredump.c, samples/cellular/lwm2m_carrier/src/main.c, samples/cellular/modem_shell/src/cloud/cloud_lwm2m.c, samples/dect/dect_phy/dect_shell/src/dect/dect_phy_ctrl.c, samples/net/mqtt/src/modules/transport/credentials_provision/credentials_provision.c, subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_rai.c, subsys/net/lib/nrf_provisioning/src/nrf_provisioning.c, subsys/net/lib/tls_credentials/tls_credentials_nrf_modem.c
Adds missing checks for the return value passed by `NRF_MODEM_LIB_ON_INIT`.
=> treewide: add check for NRF_MODEM_LIB_ON_INIT return

snippets/sdp/mspi/soc/nrf54l15_cpuapp.overlay
Fix for CPUAPP sram memory size and address range.
=> snippets: sdp: mspi: fix cpuapp_sram memory size and range

cmake/sysbuild/image_signing.cmake, sysbuild/Kconfig.mcuboot, west.yml
Removes restrictions requiring a single update image and without encryption support
=> sysbuild: mcuboot: Remove some compressed update restrictions

samples/matter/common/src/bridge/bridge_storage_manager.cpp, samples/matter/common/src/persistent_storage/persistent_storage_common.h, samples/matter/lock/src/access/access_storage.cpp
Added checking the enum value returned by persistent storage. Changed PSErrorCode enum to enum class to prevent such unintuitive comparison in the future.
=> samples: matter: Improved bridge storage manager error handling

.github/workflows/docpreview.yml, .github/workflows/docpublish.yml
Add a new job that takes care of posting documentation preview
information, including:
- Link to preview site
- List of links to edited files, easing the review process
=> ci: docs: add preview links

samples/esb/esb_prx/src/main.c, samples/esb/esb_ptx/src/main.c
Backport 080349a885034679977d11e7f23c39093088c190 from #20416.
=> [Backport v2.9-nRF54H20-branch] samples: esb: Fix corrupted transmitted data in 4Mbit radio mode

subsys/nrf_security/src/drivers/cracen/cracenpsa/cracenpsa.cmake, subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ed25519.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c
Added implementation in cracenpsa of ed25519 and ed25519ph without using sicrypto
Removed the possibility of using the sicrypto implementation of ed25519 and ed25519ph through cracenpsa
Updated cracenpsa to support new implementation and 
remove references to old
=> nrf_security: drivers: cracen: adding support for ed25519 without sicrypto

cmake/sysbuild/b0_mcuboot_signing.cmake, cmake/sysbuild/image_signing.cmake, cmake/sysbuild/image_signing_firmware_loader.cmake, cmake/sysbuild/image_signing_nrf700x.cmake, cmake/sysbuild/image_signing_split.cmake
Uses the version of imgtool that zephyr has found, which prefers
the in-tree module version found inside the MCUboot directory
Fixes: NCSDK-30894
=> cmake: sysbuild: Use zephyr found imgtool

cmake/sysbuild/partition_manager.cmake
Fixes some issues around domain handling:
- The domain was not got and was always supplied as empty
- The wrong board was provided when using other board targets e.g. network core
- Checksum handling was done with a singular file instead of once per domain, which would output an erroneous warning for other domains
Seemingly not noticed that the domain handling for PM in sysbuild has never worked. This does now mean users need really silly named files like `pm_static_nrf5340dk_nrf5340_cpunet_CPUNET.yml` but that's PM.
=> cmake: sysbuild: partition_manager: Fix domain handling issues

subsys/mpsl/pm/mpsl_pm_utils.c
There was wrong macro used to wrap the core responsible for integration with MRAM latency service for nRF54h20 SoC. The macro shoudl be a Kconfig option so that the feature is enabled with MPSL PM is enabled.
The commit fixes the code.
=> mpsl: pm: Fix wrong macro to enable integration with MRAM lat service

doc/nrf/app_dev/device_guides/fem/fem_nrf21540_gpio.rst, doc/nrf/app_dev/device_guides/fem/fem_nrf21540_gpio_spi.rst, doc/nrf/app_dev/device_guides/fem/fem_nrf2220.rst, doc/nrf/app_dev/device_guides/fem/fem_simple_gpio.rst
More imperative language is used to express steps needed to enable FEM support.
The improvement initiated by comment https://github.com/nrfconnect/sdk-nrf/pull/20273#issuecomment-2663193213 but these are applied to all FEMs
=> doc improvements: fem: minor doc improvements

CODEOWNERS
This makes it easier to add and remove code owners for these areas. These folders are well known by the entire team.
=> CODEOWNERS: Use @ncs-radio-sw as code owners for mpsl/cx and mpsl/fem

include/mpsl/mpsl_work.h, subsys/mpsl/init/mpsl_init.c, subsys/mpsl/pm/Kconfig, subsys/mpsl/pm/mpsl_pm_utils.c, subsys/mpsl/pm/mpsl_pm_utils.h, tests/subsys/mpsl/pm/CMakeLists.txt, tests/subsys/mpsl/pm/kernel_minimal_mock.h, tests/subsys/mpsl/pm/pm_test.c
mpsl: pm: Change init API and add uninit API MPSL PM
Refactor initialization API and add uninitialization.
Change the initialization API to do not allow call it
when it is already initialized or if uninitialization
is started but not completed. The uninitialization
API will wait for scheduled work queue uninit item
to complete. If that is late the API will timeout.
Uninitialize API will fail when the MPSL PM is not
in initialized state.
Unit tests are changed to cover changes in the API.
=> pm: Adds uninit for MPSL PM

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/central_hids/boards/nrf5340dk_nrf5340_cpuapp_ns.conf, samples/bluetooth/peripheral_hids_keyboard/boards/nrf5340dk_nrf5340_cpuapp_ns.conf, samples/bluetooth/peripheral_hids_mouse/boards/nrf5340dk_nrf5340_cpuapp_ns.conf
Enabled the CONFIG_TFM_PROFILE_TYPE_SMALL for the
nrf5340dk/nrf5340/cpuapp/ns as it is required for the Bluetooth stack to work properly as it now uses the PSA crypto API.
Jira: NCSDK-31777
=> samples: bluetooth: hids: Enable TF-M profile small for /ns target

config/suit/templates/nrf54h20/default/v1/app_recovery_local_envelope.yaml.jinja2
A timeout in the default APP_LOCAL_3 (recovery image) manifest synchronous invoke directive resulted in manifest processing failure.
This should not be the default behavior - if the recovery application fails to boot, an attempt to run the main applciation should be made.
=> suit: Template - do not fail on synchronous invoke timeout

CODEOWNERS, tests/benchmarks/multicore/common/workaround_idle.overlay, tests/benchmarks/multicore/idle_flpr/testcase.yaml, tests/benchmarks/multicore/idle_ppr/testcase.yaml, tests/benchmarks/multicore/idle_pwm_led/testcase.yaml, tests/benchmarks/multicore/idle_pwm_loopback/testcase.yaml, tests/benchmarks/multicore/idle_spim_loopback/testcase.yaml, tests/benchmarks/multicore/idle_wdt/testcase.yaml
In tests where Application core shall enter IDLE low power state add EXTRA_DTC_OVERLAY_FILE that prevents mooving forward to S2RAM low power state.
=> tests: benchmarks: multicore: Adjust power testing at idle state

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c, west.yml
When execution in place (CONFIG_XIP) is not enabled, which in practice
means that when Zephyr is built for a RAM loaded image, the Zephyr
linker script always places the RAM loaded image in the top address
of the RAM and then loads the linker scripts defined with the Zephyr
SECTION_PROLOGUE macros.
SECTION_PROLOGUE Zephyr macros was used to set the address of the
kmu_push_area making it incompatible with RAM loaded images.
The Zephyr reserved-memory devicetree methodology works for both use
cases but it requires heavy updates of multiple device tree files and
overlays. In order to support the RAM loaded images use cases faster
initial support for reserving the memory of nrf_kmu_reserved_push_area
though devicetree is limited to RAM loaded images.
Signed-off-by: Georgios Vasilakis …
=> nrf_security: cracen: kmu: Support KMU reserved area through DTS

subsys/mpsl/clock_ctrl/Kconfig, subsys/mpsl/clock_ctrl/mpsl_clock_ctrl.c
In the nRF54h20 SoC the non-volatile memory is located in a global domain which by default configured by nrf2 clock control to run with 64MHz. That makes a code execution time longer so it doesn't fit into radio protocols time requirements. That causes e.g. Bluetooth stack to assert in radio events.
To make sure the clock needed for MRAM (non-volatile memory in nRF54h20 SoC) is always setup to highest avaialble frequency MPSL will put a request for the clock to clock control driver. In case there is any other user of the clock that runs from radio core and allows to lower the global domain clock frequency, the clock will still be stay as requested by MPSL.
=> mpsl: clock_ctrl: Add MRAM high frequency request to MPSL

subsys/bluetooth/controller/cs_antenna_switch.c
We used the GPIO number inadvertently
=> bluetooth: controller: use DIRSET mask for antenna switch gpios

doc/nrf/libraries/modem/at_params.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, include/modem/at_params.h, include/modem/modem_info.h, lib/modem_info/modem_info.c, lib/modem_info/modem_info_params.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c, tests/subsys/net/lib/nrf_provisioning/CMakeLists.txt
* Deprecates the `at_params` module.
It will be removed in a future release.
* Adds the `enum modem_info_data_type` type
for representing the LTE link information data
types.
* Adds the `modem_info_data_type_get` function
for requesting the data type of the current
modem information type.
* Deprecates the `modem_info_type_get` function
in favor of the  `modem_info_data_type_get` function.
=> Deprecate `at_params`, deprecate `modem_info_type_get`, add `enum modem_info_data_type` and `modem_info_data_type_get`

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add changelog notes about thread stack size increases for the:
* nRF Desktop
* HIDS samples
* Fast Pair samples
Jira: NCSDK-31777
=> doc: releases: Add changelog about stack size increases (nRF Desktop; HIDS samples; FP samples)

doc/nrf/external_comp/bt_fast_pair.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/bluetooth/services/fast_pair/fmdn/Kconfig
Added a restriction on the CONFIG_BT_FAST_PAIR_FMDN_TX_POWER Kconfig option in the Find My Device Network (FMDN) extension configuration. This Kconfig option should now be set to 0 at minimum as the Fast Pair specification now requires that the conducted Bluetooth transmit power for FMDN advertisements must not be lower than 0 dBm.
Ref: NCSDK-30857
=> bluetooth: fast_pair: fmdn: add restriction for fmdn tx power

scripts/quarantine_zephyr.yaml
Fixed here: https://github.com/nrfconnect/sdk-nrf/commit/1883f06ef4c288b7265552421a71afd22462566f
=> quarantine_zephyr: Enabled zephyr mesh sample again

samples/matter/common/src/app/fabric_table_delegate.h
When `CONFIG_CHIP_LAST_FABRIC_REMOVED_NONE` is enabled `CONFIG_CHIP_LAST_FABRIC_REMOVED_ACTION_DELAY` is not defined as there is no expected action.
=> samples: matter: Fix build error when CONFIG_CHIP_LAST_FABRIC_REMOVED_NONE is enabled

applications/sdp/mspi/src/hrt/hrt-nrf54l15.s, applications/sdp/mspi/src/hrt/hrt.c
Changed type uint8_t to uint32_t to be able to
send data longer than 256 bytes.
=> applications: sdp: mspi: fix for data longer than 256 bytes

modules/trusted-firmware-m/Kconfig, modules/trusted-firmware-m/tfm_boards/include/zephyr/kernel.h
Rework of zephyr nrf54l/soc.c file to get rid of TFM specific changes. Extended `kernel.h` used for TFM build to get rid of compilation errors.
=> Rework of nrf54l/soc.c to get rid of noup commits

doc/nrf/dev_model_and_contributions/code_base.rst, doc/nrf/installation/install_ncs.rst, doc/nrf/releases_and_maturity/release_notes.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.8.0-preview1.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add information about the preview tag.
=> doc: Add information about the preview tag

subsys/bluetooth/controller/CMakeLists.txt, subsys/bluetooth/controller/hci_driver.c
In order to allow users to configure their own antenna switch logic, we needed to update the sdc_support_channel_sounding function. This should change the default logic to use the new function.
Also fixed a bug in the kconfig dependency to compile with the cs antenna switch logic.
=> driver: switch to new sdc_support_channel_sounding function

applications/sdp/mspi/src/main.c
Increase delay to wait a little bit more for IPC service to be ready on APP side.
=> applications: sdp: mspi: fix for ipc bound problem

subsys/bootloader/Kconfig, subsys/bootloader/bl_boot/bl_boot.c, tests/subsys/bootloader/b0_lock/CMakeLists.txt, tests/subsys/bootloader/b0_lock/prj.conf, tests/subsys/bootloader/b0_lock/src/main.c, tests/subsys/bootloader/b0_lock/sysbuild.conf, tests/subsys/bootloader/b0_lock/testcase.yaml
Disables read and execute on memory containing NSIB
right before jumping to application.
=> B0 self lock before jump

scripts/west_commands/ncs_provision.py
When running west ncs-provision upload command locally, it is not required to add the device id if only one device is connected. Pass to nrfutil command: --traits jlink, to run command on connected device.
Before fix, when running:
`west ncs-provision upload -s nrf54l15 -k <path to key>`
received:
```
Keys file saved as /tmp/nrfutil_f2e2i8tc/keyfile.json
nrfutil device x-provision-nrf54l-keys --key-file /tmp/nrfutil_f2e2i8tc/keyfile.json --verify
Error: Missing --traits or --serial-number options. Add at least one of the options or make sure you have exactly one supported device connected
```
Also running twister with --device-serial was blocked (device id not passed), only hardware map were supported
=> scripts: west ncs-provision: allow using without dev-id

include/modem/at_params.h, tests/lib/at_cmd_parser/at_params/src/main.c
* Deprecates function signatures only outside of tests.
This addresses some related CI failures.
* Removes an unused header include.
=> include: modem: at_params: disable __deprecated for tests

subsys/suit/cache/Kconfig, subsys/suit/cache/src/suit_dfu_cache_internal.h, subsys/suit/cache/src/suit_dfu_cache_rw.c, tests/subsys/suit/fetch/Kconfig, tests/subsys/suit/fetch/boards/native_sim.overlay, tests/subsys/suit/fetch/boards/native_sim_64.overlay, tests/subsys/suit/fetch/src/test_app_ipuc.c
Change the default SUIT cache pool ID for SDFW updates to 1, so it matches other update scenarios that uses external memory for SDFW and SCFW FW transfers.
Ref: NCSDK-30810
=> suit: Use cache pool 1 for SDFW updates

snippets/sdp/mspi/board/nrf54l15dk_nrf54l15_cpuapp.overlay, snippets/sdp/mspi/snippet.yml, snippets/sdp/mspi/soc/nrf54l15_cpuapp.overlay
~Remove dummy device from MSPI API test overlay for nRF54L15, since external flash is already defined in snippets.~
~Fix device frequency in MSPI API test.~ (updated in other PR).
Fix max frequency available on SDP MSPI.
Move definition of external flash to board overlay.
=> SDP: fix max frequency and device frequency in MSPI API test

tests/benchmarks/multicore/idle_uarte/Kconfig, tests/benchmarks/multicore/idle_uarte/boards/nrf54h20dk_nrf54h20_cpuapp_fast.overlay, tests/benchmarks/multicore/idle_uarte/src/main.c, tests/benchmarks/multicore/idle_uarte/testcase.yaml
Add test case for changing GD frequency when driver is active and necessary reworks.
test_low_level: PR-1884
=> tests: benchmarks: multicore: idle_uarte: reworks

tests/benchmarks/multicore/idle_spim_loopback/Kconfig, tests/benchmarks/multicore/idle_spim_loopback/src/main.c, tests/benchmarks/multicore/idle_spim_loopback/testcase.yaml
Add test case for changing GD frequency when driver is active.
test_low_level: PR-1889
=> tests: benchmarks: multicore: idle_spim_loopback: GDF switching

tests/benchmarks/multicore/idle_pwm_loopback/Kconfig, tests/benchmarks/multicore/idle_pwm_loopback/src/main.c, tests/benchmarks/multicore/idle_pwm_loopback/testcase.yaml
Add test case for changing GD frequency when driver is active.
=> tests: benchmarks: multicore: idle_pwm_loopback: GDF switching

dts/bindings/mpc/nordic,nrf-mpc.yaml, dts/common/nordic/nrf7120_enga.dtsi, soc/nordic/nrf71/Kconfig
Update the MPC binding to cover both nRF54H20 and nRF7120 use cases. Note that the MPC IP revisions used by the two devices are compatible.
Property `protection-region-size` is renamed to `override-granularity`, a more appropriate term which comes from the datasheet. The description is also corrected, as MPC stands for Memory Privilege Controller.
=> dts: bindings: Update nordic,nrf-mpc

.github/workflows/docbuild.yml
Add a new step that checks if added or updated links are reachable, ie, return HTTP 200 (note redirects, permanent moves, etc. will count as failures so updated URLs are put in place).
=> ci: docbuild: check added or updated links

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change introduces a release note to inform that BLE legacy pairing was disabled by default in application configurations.
Jira: NCSDK-31809
=> applications: nrf_desktop: Add a note about disabling BLE legacy pairing

tests/benchmarks/multicore/idle_pwm_led/remote/Kconfig, tests/benchmarks/multicore/idle_pwm_led/src/main.c, tests/benchmarks/multicore/idle_pwm_loopback/remote/Kconfig, tests/benchmarks/multicore/idle_pwm_loopback/src/main.c, tests/benchmarks/multicore/idle_wdt/remote/Kconfig, tests/benchmarks/multicore/idle_wdt/src/main.c
There is difference in boot time between Application and Radio cores.
When current consumption test is executed on two cores, synchronize their startup.
=> tests: benchmarks: multicore: Add synchronization between cores

tests/drivers/gpio/gpio_more_loops/Kconfig, tests/drivers/gpio/gpio_more_loops/src/main.c
It was designed for H20, other platforms are not needed. It is checked with gpio tests already.
=> tests: drivers: gpio: gpio_more_loops: check pulls only at H20

subsys/suit/memory_layout/src/suit_memory_layout.c
Fix an incorrect node name of the radio core TCM memory inside the memory layout module.
=> suit: Fix incorrect node name in mem layout

samples/sensor/qdec/boards/nrf54l20pdk_nrf54l20_cpuapp.overlay
Test overlay used NFC pins. Changed them to regular pins.
=> samples: sensor: qdec: Use regular GPIOS for nRF54L20

tests/drivers/audio/pdm_loopback/testcase.yaml
With MDK 8.69.1 introduced with nrfx 3.10, nRF54L20 no longer directly supports ratio of 100 for PDM. Thus, driver is unable to get the expected sample rate of 10kHz for 1000kHz clock. Since ratio of 50 is available, new configuration has been added and the old one will remain in quarantine.
Once support for nRF54L20-specific custom ratio in PDM is provided, the case can be brought back from quarantine.
=> tests: drivers: audio: pdm_loopback: adjust nRF54L20 1000kHz

.github/workflows/docbuild.yml
Because .* is greedy, the regular expression was not valid for cases where e.g. we have >1 entry in the same line.
=> ci: docbuild: fix Doxygen links patching for Zoomin

lib/fem_al/fem_al.c
Adds 'fem_enable' call before using fem for radio operations.
* Since right now, nrf2220 is the only FEM that implements `fem_enable` call, I had to verify the new timings with it.
I used it with nRF54l15 with the following configuration:
```
RADIO_TEST_CONFIG="-DSHIELD=nrf2220ek \
-DCONFIG_PPI_TRACE=y \
-DCONFIG_NRF_802154_ENCRYPTION=n \
-DCONFIG_MPSL_BUILD_TYPE_SRC_DEBUG=y"
```
* I added custom commits to enable PPI Trace in `radio_test` and `dtm` apps.
Additionally, I disabled the `cs_gpote_pin` activation inside `pa_activation_on_timer_set` (CS is activated inside `fem_enable`).
For the verification changes see https://github.com/piotrkoziar/sdk-nrf/tree/piko/radio-test.
I ran sequence:
```c
dtm_setup_reset();
dtm_test_transmit(0x11, 20, DTM_PACKET_55);
dtm_test_receive(11); …
```
=> samples: peripheral: radio_test: enable fem before radio operation

samples/bluetooth/fast_pair/locator_tag/README.rst
Removed the documentation note regarding the experimental status of the LTO functionality in the Fast Pair Locator Tag sample.
=> samples: bluetooth: fast_pair: locator_tag: remove LTO experimental note

.github/workflows/compliance.yml, .github/workflows/docbuild.yml
Move documentation added/updated links check to the compliance workflow. This allows documentation to still build successfully and so get a preview.
=> ci: compliance: move link checks from docbuild to compliance

subsys/nrf_security/Kconfig.psa.nordic
Add PSA_WANT_ALG_SP800_108_COUNTER_CMAC and PSA_WANT_ALG_SP800_108_COUNTER_HMAC to dependecies for PSA_HAS_KEY_DERIVATION.
=> nrf_security: Update config dependency SP800

CODEOWNERS
Our team is struggling to get a review for this component, which we're highly dependent on.
=> CODEOWNERS: add protocols serialization team to subsys/nrf_rpc

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/fast_pair/input_device/prj.conf, samples/bluetooth/fast_pair/locator_tag/configuration/prj.conf, samples/bluetooth/fast_pair/locator_tag/configuration/prj_release.conf
The issue is already fixed. The workaround is no longer needed.
Jira: NCSDK-30717
=> samples: bluetooth: fast_pair: Drop MPSL flash sync timeout workaround

applications/nrf_desktop/Kconfig.ble, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
The issue is already fixed. The workaround is no longer needed.
Jira: NCSDK-30717
=> applications: nrf_desktop: Drop MPSL flash sync timeout workaround

doc/nrf/releases_and_maturity/known_issues.rst
Add mention of possible ZCL Reporting configuration data incompatibility issue after performing DFU.
=> doc: zigbee: add known issue KRKNWK-19894

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/mesh/light_ctrl/README.rst, samples/bluetooth/mesh/light_ctrl/boards/nrf52dk_nrf52832.conf, scripts/quarantine.yaml
Revert "scripts: quarantine: nRF52832 is added for mesh light ctrl sample
This reverts commit cf70bbd1ccc62e2982e9ddfa566d1d6ee43fdad8.
As we now know that the sample fits for nRF52832.
Also, to improve ram availability for the application, friendship feature is disabled by default when sample is compiled for nRF52DK.
No EMDS:
```
Memory region         Used Size  Region Size  %age Used
FLASH:      367028 B       480 KB     74.67%
RAM:       60922 B        64 KB     92.96%
IDT_LIST:          0 GB        32 KB      0.00%
```
With EMDS:
```
Memory region         Used Size  Region Size  %age Used
FLASH:      369776 B       476 KB     75.86%
RAM:       61306 B        64 KB     93.55%
IDT_LIST:          0 GB        32 KB      0.00%
```
=> Revert "scripts: quarantine: nRF52832 is added for mesh light ctrl sample

subsys/suit/storage/src/suit_storage_envelope.c
For the first operation the header size was checked before the offset was reset.
=> suit: Fix suit storage envelope

drivers/flash/flash_ipuc/flash_ipuc.c, subsys/suit/stream/stream_sinks/src/suit_dfu_cache_sink.c
In a specific case (len == CACHE_ALIGNMENT) and
unaligned address an aligned write was (incorrectly) performed, resulting in an error.
=> suit: Fix IPUC cache issues

doc/nrf/protocols/matter/end_product/security.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/common/src/app/matter_init.cpp, samples/matter/common/src/app/matter_init.h
We need to set a custom keystore manager in Matter server while using KMU.
=> samples: matter: Set custom keystore manager during the init.

dts/bindings/bluetooth/nordic,bt-cs-antenna-switch.yaml, samples/bluetooth/channel_sounding_ras_initiator/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/bluetooth/channel_sounding_ras_reflector/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, subsys/bluetooth/controller/CMakeLists.txt, subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/cs_antenna_switch.c, subsys/bluetooth/controller/cs_antenna_switch.h, subsys/bluetooth/controller/hci_driver.c
Adds relevant DTS bindings and uses zephyr/gpio.h to provide a generic API for multiantenna channel sounding.
=> bluetooth: controller: Use GPIO driver for CS antenna switching

CODEOWNERS, scripts/nrf_profiler/calc_stats.py, scripts/nrf_profiler/model_creator.py, scripts/nrf_profiler/plot_nordic.py, scripts/nrf_profiler/processed_events.py, scripts/nrf_profiler/rtt2stream.py, scripts/nrf_profiler/stats_nordic.py, scripts/nrf_profiler/stats_nordic_presets/nrf_desktop/hid_performance.json
Change applies a series of improvements to the stats calculating script:
- Clean up the script implementation
- Allow defining presets using a *.json file
- Add interval plot
- Allow to filter outliers to improve UX
Change also adds a simple, predefined test preset for the nRF Desktop application.
Jira: NCSDK-31712
=> scripts: nrf_profiler: Improve stats calculating script

boards/nordic/nrf52810dmouse/board.cmake, boards/nordic/nrf52820dongle/board.cmake, boards/nordic/nrf52833dongle/board.cmake, boards/nordic/nrf52840gmouse/board.cmake, boards/nordic/nrf52dmouse/board.cmake, boards/nordic/nrf52kbd/board.cmake, boards/nordic/thingy91/board.cmake, boards/nordic/thingy91x/board.cmake
We should use nrfutil as the default now.
nrfjprog is being phased out soon.
=> boards: use nrfutil runner by default

samples/bluetooth/scanning_while_connecting/src/main.c
Remove the RSSI distance check in the scanning_while_connecting sample. This check prevented DKs on my desk from connecting to each other and since we have device filtering based on the advertised name, I don't think the RSSI check is necessary.
=> Samples: Bluetooth: Remove RSSI distance check

include/net/nrf_cloud.h, subsys/net/lib/nrf_cloud/include/nrf_cloud_codec_internal.h, subsys/net/lib/nrf_cloud/src/nrf_cloud.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_fota.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c
Add missing support for NRF_CLOUD_TOPIC_STATE_TF. This should have been done for the MQTT JSONata Transform feature added a while back (unrelated to the gateway).
Fix uninitialized variable issue in in_last_job() in nrf_cloud_fota.c.
Remove most of the conditionals for the gateway, but add one to fix up topic suffix.
=> net: lib: nrf_cloud: misc improvements

subsys/bluetooth/controller/cs_antenna_switch.c
We switched from int ret to int err at the last minute, one line slipped through the cracks.
=> bluetooth: controller: Fix compilation error in cs_antenna_switch.c

samples/crypto/psa_tls/boards/nrf54l15dk_nrf54l15_cpuapp_ns.conf
The chip name was wrongly mentioned as nRF54L20.
Since this is overlay file for the nRF54L15DK, this needs to be nRF54L15.
=> samples: psa_tls: Fix typo in chip name

west.yml
Update zephyr with workaround for XOSTART in clock control.
=> manifest: Update zephyr with clock control XOSTART workaround

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/benchmarks/coremark/Kconfig.sysbuild, samples/benchmarks/coremark/README.rst, samples/benchmarks/coremark/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, samples/benchmarks/coremark/boards/nrf54h20dk_nrf54h20_cpuflpr.conf, samples/benchmarks/coremark/boards/nrf54h20dk_nrf54h20_cpuflpr.overlay, samples/benchmarks/coremark/boards/nrf54h20dk_nrf54h20_cpuppr.conf, samples/benchmarks/coremark/boards/nrf54h20dk_nrf54h20_cpurad.conf, samples/benchmarks/coremark/prj.conf, samples/benchmarks/coremark/prj_flash_and_run.conf, samples/benchmarks/coremark/prj_heap_memory.conf, samples/benchmarks/coremark/prj_multiple_threads.conf, samples/benchmarks/coremark/prj_static_memory.conf
Added the FLPR core support for the nRF54H20 DK board target in the CoreMark sample.
Ref: NCSDK-30327
=> samples: benchmarks: coremark: add FLPR support for nRF54H20 DK

samples/cellular/modem_shell/bt.overlay
Default nrf9160dk revision is 0.14.0 starting from mid 2023, instead of
0.7.0. Update bt.overlay (which is nrf9160dk specific) to use 0.14.0 pin
mapping.
This fixes using nrf9160dk when following "BT shell support" section in README.rst, which says to
build controller firmware with:
```
west build -p -b nrf9160dk/nrf52840
```
However it was required to use `nrf9160dk@0.7.0/nrf52840` in order to make it compatible with
(Bluetooth) host firmware. After this change it is possible to use default revision of 0.14.0 of
both Bluetooth host (nrf9160) and controller (nrf52840).
=> samples: modem_shell: bt: use 0.14.0 nrf9160dk pin mapping

applications/sdp/mspi/Kconfig, applications/sdp/mspi/boards/nrf54l15dk_nrf54l15_cpuflpr.overlay, applications/sdp/mspi/src/main.c, drivers/mspi/Kconfig.nrfe, drivers/mspi/mspi_nrfe.c, include/drivers/mspi/nrfe_mspi.h, snippets/sdp/mspi/soc/nrf54l15_cpuapp.overlay
- TIMER is set up by the Host and cleared periodically by SDP FW. If SDP FW fails to clear the TIMER, the Host receives an IRQ signalling an SDP FW error.
- Implementation of trap handler. Signals status to host and sends dump of most important registers at the time of error.
=> applications: sdp: mspi: add timer and trap handler for SDP app fault handling

samples/bluetooth/channel_sounding_ras_initiator/sample.yaml
Building this sample for this target does work, but the docs were not updated.
=> bluetooth: samples: Add nrf54l15dk/nrf54l05 to RAS requestor sample

applications/sdp/mspi/src/hrt/hrt-nrf54l15.s, applications/sdp/mspi/src/hrt/hrt.c, applications/sdp/mspi/src/main.c
Add support for QAD mode in RX path.
Currently, there are still two issues with RX QUAD mode:
- when receiving less than 4 bytes of data, there are additional clock cycles
- when sending only 1 byte before receiving, no data appears on data line
There are tickets created to resolve the above.
Note: at the current default frequency the first byte is read wrongly to be 0x00. Problem does not appear at frequencies below 4,92 MHz (counter value greater than 13).
=> applications: sdp: mspi: add QUAD mode to RX

scripts/bootloader/provision.py, scripts/bootloader/validation_data.py
Updated bootloader scripts to use little-endian byte orders whatever OS uses by default.
=> scripts: Force to use little-endian byte order

subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c, tests/subsys/net/lib/nrf_provisioning/src/coap.c
Use the CoAP ACK timeout to wait before retrying a CoAP request, rather than using a fixed delay of 500 milliseconds.
=> net: nrf_provisioning: Change retry time for a CoAP request

doc/nrf/external_comp/avsystem.rst, doc/nrf/links.txt
Replaced following error links with text in the
AVSystem guide.
* nRF Cloud integration with Coiote Device Management
* Setting observations for an object
=> doc: Replace error links with text in the AVSystem guide

.github/workflows/review-quarantine-pr.yml
Codeowners should be informed if their test configuration is added to quarantine.
First step is information about quarantine process for author of pull request.
=> .github: Add information about quarantine process to PR

applications/sdp/mspi/src/hrt/hrt-nrf54l15.s, applications/sdp/mspi/src/hrt/hrt.c, applications/sdp/mspi/src/main.c, drivers/mspi/mspi_nrfe.c, include/drivers/mspi/nrfe_mspi.h
Add calculating VTIM CNT0 top value based on desired frequency.
~Needs #20320 to make CI green.~
=> applications: sdp: mspi: add calculating counter value

samples/cellular/nrf_cloud_multi_service/README.rst
Removed the note as it does not add any value.
=> doc: improved note in nRF Cloud multi-service sample

subsys/net/lib/nrf_cloud/src/nrf_cloud_download.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps_utils.c
Fixes issue introduced in #19908:
PGPS downloads were previously wrongly redirected
through the FOTA pipeline,
but should be handed over to downloader directly.
=> subsys: net: fix CoAP downloads for PGPS downloads

.github/test-spec.yml, CODEOWNERS, modules/modules.cmake, modules/openthread/CMakeLists.txt, modules/openthread/Kconfig, modules/openthread/Kconfig.features, modules/openthread/Kconfig.thread, modules/openthread/platform/CMakeLists.txt, modules/openthread/platform/alarm.c, modules/openthread/platform/ble.c, modules/openthread/platform/crypto_psa.c, modules/openthread/platform/diag.c, modules/openthread/platform/entropy.c, modules/openthread/platform/logging.c, modules/openthread/platform/memory.c, modules/openthread/platform/messagepool.c, modules/openthread/platform/misc.c, modules/openthread/platform/openthread-core-zephyr-config.h, modules/openthread/platform/platform-zephyr.h, modules/openthread/platform/platform.c, modules/openthread/platform/radio.c, modules/openthread/platform/settings.c, modules/openthread/platform/shell.c, modules/openthread/platform/spi.c, modules/openthread/platform/uart.c, scripts/ci/license_allow_list.yaml, scripts/ci/tags.yaml
Copy OpenThread platform implementation from upstream Zephyr, based on commit 10eb60b48111d529ab30bae2a344226accb3ded6 to enable development of Nordic-specific platform implementation.
- Start using NCS implementation of OT platform
- align license allowlist
- remove sourcing files that have not been copied from upstream
- update CODEOWNERS
- clean compliance issues
- update test spec
=> modules: add OpenThread platform implementation

subsys/net/openthread/Kconfig.defconfig
Without this change, NEWLIB_LIBC_NANO gets selected even when building OpenThread application with PICOLIBC.
=> net: openthread: enable NEWLIB_LIBC_NANO only if NEWLIB_LIBC

subsys/net/lib/nrf_provisioning/src/nrf_provisioning.c, subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c
The provisioning thread should continue running even if the connection to the server is refused.
Return errno value if socket call fails.
Remove duplicate error prints.
=> net: nrf_provisioning: Improve error handling

subsys/bluetooth/controller/cs_antenna_switch.c
Found that this configuration only works if two pins are defined in DTS. Only one is really needed.
Signed-off-by: Olivier Lesage <olivier.lesage@nordicsemi.no>
=> bluetooth: controller: fix single-pin multiplexed antenna switch

applications/nrf_desktop/src/modules/fn_keys.c, applications/nrf_desktop/src/modules/hid_state.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
This simplifies maintenance and allows to use PicolibC.
Jira: NCSDK-32238
=> applications: nrf_desktop: Use bsearch from C library

applications/nrf_desktop/Kconfig.defaults
Missing dependencies in `CONFIG_LTO` default value overlay led to build issues when disabling both LTO and ISR tables local declaration using CLI arguments. Change fixes the build issues.
Jira: NCSDK-32238
=> applications: nrf_desktop: Fix enabling LTO

applications/sdp/mspi/src/hrt/hrt-nrf54l15.s, applications/sdp/mspi/src/hrt/hrt.c
Remove toggling of not used pins after sending data on SINGLE.
~This change temporary breaks sending data on QUAD, however, changes from https://github.com/nrfconnect/sdk-nrf/pull/20360 should fix it back (this change, to be more specific: https://github.com/nrfconnect/sdk-nrf/pull/20360/files#diff-1bfeb3937beffb96825c75549b69a42219ddedb103b28377bc8ef839e8f55574R393-R401)~
=> applications: sdp: mspi: remove toggling of pins after TX

applications/nrf_desktop/Kconfig.defaults, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Using minimal libc no longer reduces application's memory footprint. Currently it actually increases the memory footprint for most of the configurations. The Picolibc is used by default in Zephyr.
Jira: NCSDK-32238
=> applications: nrf_desktop: Use Picolibc

subsys/bluetooth/mesh/CMakeLists.txt, subsys/mpsl/CMakeLists.txt, subsys/mpsl/cx/CMakeLists.txt, subsys/mpsl/fem/CMakeLists.txt
Correct formatting in CMakeList.txt files in MPSL and Bluetooth Mesh subsystems to align it to common sdk-nrf format.
=> mpsl: Correct CMakeLists.txt formatting

doc/nrf/links.txt, doc/nrf/security/ap_protect.rst
Add missing information for nRF54L on enabling the access port protection mechanism.
=> doc: Add nRF54L information to ap-protect.

samples/pmic/native/npm2100_fuel_gauge/sample.yaml
Update sample.yaml to build_only.
=> samples: npm2100_fuel_gauge: Set build only

scripts/requirements-test.txt, scripts/tests/conftest.py, scripts/tests/west_commands/ncs_provision_test.py, scripts/west_commands/ncs_provision.py
Metadata must be properly set for uploaded keys to KMU.
=> scripts: ncs-provision: handle metadata for KMU

subsys/bluetooth/services/ras/rrsp/ras_rrsp.c
This is based on the following text from RAS_v1.0.pdf
3.5.2 Ranging Data Overwritten behavior
If a RAS Server supports simultaneous enabling of indications and notifications of the Ranging Data Overwritten characteristic, and the client enabled both indications and notifications, then the RAS Server shall use indications to report a Ranging Data Overwritten event.
3.4.2 Ranging Data Ready behavior
If the RAS Server supports simultaneous enabling of indications and notifications of the Ranging Data Ready characteristic, and the client enabled both indications and notifications, then the RAS Server shall use indications to report a Ranging Data Ready event.
=> bluetooth: services: prefer ind over notif in RAS when relevant

modules/openthread/platform/crypto_psa.c
A PSA crypto operation object can be initialized in multiple ways according to the documentation. For example,
1. Using a dedicated psa_xxx_operation_init() function that returns an initialized object.
2. Using memset() to zero out the operation object.
For some PSA crypto driver implementations, using the first method causes an excessive stack usage if the operation object is large and psa_xxx_operation_init() is not inlined. Instead, it is better to stick to memset() for this purpose.
=> modules: openthread: platform: optimize stack usage in crypto_psa

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/caf_sensor_manager/sample.yaml, samples/caf_sensor_manager/sysbuild/empty_net_core/boards/nrf54h20dk_nrf54h20_cpurad.overlay, samples/caf_sensor_manager/sysbuild/empty_net_core/prj.conf
Add power optimized configuration for the sample.
Enable PM and disable unused devices.
Multicore:
Normal build: 1.62mA
Optimized build: 0.068mA
Singlecore:
Normal build: 1.85mA
Optimized build: 0.107mA
Jira: NCSDK-26415
=> samples: caf_sensor_manager: Add power optimized config

subsys/bootloader/bl_boot/bl_boot.c
Fixes faulty boot logic that would do a return after changing vector addresses and a clear call stack which has undefined opeation. Also adds an error message when forwarding externally required APIs fails so it is visible to the user
=> bootloader: bl_boot: Fix faulty boot logic

subsys/nrf_compress/src/lzma.c
Fixes an issue where the variable checked was not the correct one, though the check would pass in most scenarios
=> nrf_compress: lzma: Fix last part variable check

subsys/bluetooth/controller/ecdh.c
If the ECDH thread is aborted without processing the currently requested command, any further command after a new initialization will be answered as command disallowed.
=> bluetooth: controller: Reset ECDH command on deinitialization

west.yml
Use a tag instead of a hash to point to the Oberon PSA core.
This is preparation work, when the Oberon PSA core is updated the history will be rewritten so the current commit hash needs to be preserved.
=> manifest: Use tag and not hash for Oberon PSA core

samples/bluetooth/central_and_peripheral_hr/src/main.c, samples/bluetooth/peripheral_bms/src/main.c, samples/bluetooth/peripheral_cgms/src/main.c, samples/bluetooth/peripheral_cts_client/src/main.c, samples/bluetooth/peripheral_gatt_dm/src/main.c, samples/bluetooth/peripheral_lbs/src/main.c, samples/bluetooth/peripheral_mds/src/main.c, samples/bluetooth/peripheral_rscs/src/main.c, samples/bluetooth/peripheral_status/src/main.c, samples/bluetooth/peripheral_uart/src/main.c, samples/bluetooth/shell_bt_nus/src/main.c
Making Bluetooth API calls in the `recycled`
callback context is error-prone.
The changes add the use of workqueue to resume advertising.
=> samples: bluetooth: Fix resume advertising

drivers/wifi/nrf700x/Kconfig, west.yml
Add Kconfig in init command for maximum ps poll failures count
and stbc enable in HT.
=> drivers: nrf700x: Add Kconfig for ps poll and stbc

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, doc/nrf/shortcuts.txt
Updated shortcuts.txt to list J-Link 8.18.
VSC version stays unchanged.
NRFU-1459.
=> doc: jlink: update to 8.18

doc/nrf/releases_and_maturity/releases/release-notes-3.0.0-preview1.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Correct changelog entry for Power Management
in nrfDesktop.
Change was introduced in commit:
ed4de929c5183312629087e7fe6d5a2767927269
JIRA: None
=> doc: Correct changelog entry for nrfDesktop

samples/pmic/native/npm2100_one_button/sample.yaml
=> samples: pmic: native: npm2100_one_button: force build only

lib/gcf_sms/gcf_sms.c
The strtok_r documentation says that each subsequent call that should parse the same string should set the str arguement to NULL.
Restarting the parsing based on the saveptr argument, as was previously done, only works because the context that the strtok_r function saves to saveptr happens to be the address where the function left off. (However, the save context will likely not change for this function.)
=> lib: gcf_sms: pass NULL to strtok_r to continue parsing same string

applications/matter_bridge/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/light_bulb/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/light_switch/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/lock/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/smoke_co_alarm/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/template/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/thermostat/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/matter/window_covering/sysbuild/mcuboot/boards/nrf5340dk_nrf5340_cpuapp.overlay, west.yml
*Reconnect to network after RPU recovery
*Disable GPIO forwarder in mcuboot
=> [Backport v2.9-branch] Reconnect to network after RPU recovery

samples/bluetooth/fast_pair/input_device/Kconfig.sysbuild
Fixed the issue in the Fast Pair Input Device sample, in which the default override of the SB_CONFIG_BT_FAST_PAIR_MODEL_ID does not work.
Ref: NCSDK-32057
=> samples: bluetooth: fast_pair: input_device: fix the model ID default

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c, subsys/nrf_security/src/psa_crypto_driver_wrappers.c
The ECDSA public key is 65 bytes long, but the kmu only supported keys up to 32 bytes.
The first byte is Compact Binary Representation
where only one option is supported so this is removed before storing and added back in when retrieved.
This means we only use 4 slots instead of 5 to store the key
Fix bug in psa_crypto_driver_wrappers which meant kmu keys could not be used for sign and verify hash.
Add support for storting  ecdsa keys using sha256 to the kmu
=> nrf_security: cracen: kmu: Fix ecdsa public key import

doc/nrf/app_dev/device_guides/nrf54l/kmu_provision.rst
Removed the mention of nrfjprog and updated the nrfutil one. Suggested by @evenl in PR #20920.
=> doc: kmu_provision: update nrfjprog to nrfutil

subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c
Add block2 option to a CoAP GET request. This suggests the maximum block size to the server when blockwise transfer is required.
=> net: nrf_provisioning: Add block2 option to a CoAP request

doc/nrf/protocols/matter/getting_started/custom_clusters.rst
rename `<cluster>` to `<clusterExtension>`
=> doc: matter: fix clusterExtension tab name

applications/matter_bridge/src/app_task.cpp, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/common/src/app/fabric_table_delegate.h, samples/matter/common/src/app/matter_event_handler.cpp, samples/matter/common/src/board/board.cpp, samples/matter/common/src/bridge/bridge_storage_manager.cpp, samples/matter/common/src/bridge/bridge_storage_manager.h, samples/matter/common/src/event_triggers/default_event_triggers.cpp, samples/matter/common/src/migration/migration_manager.cpp, samples/matter/common/src/persistent_storage/backends/persistent_storage_secure.cpp, samples/matter/common/src/persistent_storage/backends/persistent_storage_secure.h, samples/matter/common/src/persistent_storage/backends/persistent_storage_settings.cpp, samples/matter/common/src/persistent_storage/backends/persistent_storage_settings.h, samples/matter/common/src/persistent_storage/persistent_storage.h, samples/matter/common/src/persistent_storage/persistent_storage_impl.h, samples/matter/lock/Kconfig, samples/matter/lock/src/access/access_manager.cpp, samples/matter/lock/src/access/access_manager.h, samples/matter/lock/src/access/access_manager_credentials.cpp, samples/matter/lock/src/access/access_storage.cpp, samples/matter/lock/src/access/access_storage.h, samples/matter/lock/src/app_task.cpp, samples/matter/lock/src/bolt_lock_manager.cpp, samples/matter/lock/src/bolt_lock_manager.h, west.yml
* Remove old code handling clearing users/credentials from fabric as it's
unused and not spec compilant.
* Implement factory reset for persistent storage.
* Handle factory reset event in `lock` and `matter_bridge`.
* Add common factory reset handler in `matter_event_handler`.
=> matter: Add factory reset event handlers

samples/bluetooth/peripheral_hr_coded/src/main.c
The line for the advertising option BT_LE_ADV_OPT_REQUIRE_S8_CODING was overindented. This commit fixes the indent to align with the other advertising options.
=> Bluetooth: Samples: Fix indent in Peripheral HR Coded sample

CODEOWNERS
The ncs-sbom command was originally developed and maintained by the SI team, but Vestavind is taking over its maintenance.
=> codeowners: Move the ncs-sbom command to Vestavind

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/app_dev/programming.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/migration/migration_guide_3.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added information about the change of west runner for Nordic devices. Edited the programming page, migration guide for 3.0.0, and other affected pages. NCSDK-32305, part 1.
=> doc: west: runner allows nrfutil

applications/nrf5340_audio/doc/building.rst
Replaced nrfjprog with nrfutil in the Audio app documentation. NCSDK-30139.
=> doc: audio: nrfjprog to nrfutil update

samples/matter/lock/src/access/access_storage.cpp
When calculating free space, use `CONFIG_SETTINGS_[ZMS|NVS]` instead of `CONFIG_[ZMS|NVS]` as both `ZMS` and `NVS` may be enabled, but only one can be used as a settings backend.
=> samples: matter: lock: Use correct settings backend

samples/wifi/raw_tx_packet/src/main.c, samples/wifi/shell/src/wifi_raw_tx_pkt_shell.c
It turned out that IPPROTO_RAW is not a valid proto type for AF_PACKET sockets, so it likely won't be supported anymore in the future.
As the samples doing raw TX aren't actually using IP protocols, but just sending raw L2 frames, we could just use ETH_P_ALL as protocol when creating socket instead.
=> samples: wifi: Fix proto type used for RAW sockets

west.yml
Main changes since v2.4:
* libRandv2: New API to fill buffers & Wextra warning fixes
* libCryptov1: Add new AES-ECB API
Note: Like before, bsim remains fully backwards compatible
=> manifest: Update bsim to version v2.5

scripts/quarantine.yaml
sample.bluetooth.direction_finding_central_nrf.aod
The RAM overflow started to occur also in AOD test scenario.
=> scripts: quarantine: add bluetooth.direction_finding_central_nrf.aod

doc/nrf/app_dev/device_guides/nrf53/building_nrf53.rst
Updated building_nrf53.rst to use nrfutil instead of nrfjprog. Removed mentions of nrfjprog.
NCSDK-30157.
=> doc: nrf5340: update nrfjprog to nrfutil

subsys/net/lib/hostap_crypto/Kconfig
Legacy crypto has below issues:
* PSA RNG is enabled
* Compatible with CRYPTO which is now removed, but still works with CRYPTO_ALT due to other modules enabling necessary MbedTLS ciphers.
As the difference is only RNG, enable both PSA and Legacy ones, the ROM overhead is just a few bytes, this makes config management simpler.
=> net: lib: hostap_crypto: Fix legacy crypto

doc/nrf/app_dev/programming.rst, doc/nrf/includes/install_sdk_common_prerequisites.txt, doc/nrf/installation/install_ncs.rst, doc/nrf/installation/recommended_versions.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, doc/nrf/shortcuts.txt
Moved the common prerequisites for installing the SDK to a separate file and removed the VSC-specific J-Link version shortcut. VSC-2894.
=> doc: install: simplify prerequisites section

doc/nrf/app_dev/device_guides/fem/2220ek_dev_guide.rst
Following the doc style and usage guide, `warning::` is not appropriate here. Changed to `caution::`.
Use active voice for some sentences.
=> doc: fem: nrf2220ek doc improvement

samples/matter/common/src/event_triggers/default_event_triggers.cpp
Set user data before starting timer, as with short delays, timer may expire before setting the data.
=> samples: matter: Set user data before starting timer

doc/nrf/protocols/bt/bt_mesh/configuring.rst, doc/nrf/releases_and_maturity/migration/migration_guide_3.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Commit:
* adds documentation for Bluetooth Mesh security toolbox and key importer functionality.
* updates release notes
* updates migration guide
=> doc: Bluetooth: Mesh: documentation for security toolbox and key importer

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added list of changes done to MPSL integration layer that were needed for nRF54h20 SoC support.
=> doc: mpsl: List changes related to nRF54h20 SoC

doc/nrf/app_dev/device_guides/nrf54l/fota_update.rst, doc/nrf/app_dev/device_guides/nrf54l/kmu_basics.rst, doc/nrf/app_dev/device_guides/nrf54l/kmu_provision.rst
adds info about provisioning keys before running with bootloader
=> doc: add kmu provisioning info

subsys/bluetooth/services/fast_pair/fmdn/Kconfig, subsys/bluetooth/services/fast_pair/fmdn/clock.c
Added the kernel uptime workaround to the clock module in the FMDN extension that is part of the Fast Pair library.
Applied the workaround for the kernel uptime persistence after a system reset. The FMDN clock module assumes that the kernel uptime starts from zero after the system reboot.
Activated the workaround only for devices from the nRF54L series that use the GRTC timer as the system clock source (the default configuration). For this configuration, the kernel uptime persists after a system reset if the reset reason is of a specific type, such as a software reset (for example, triggered by the sys_reboot API).
Ref: NCSDK-32268
The following items are planned as a follow-up PR:
- changelog entry
- known issue description for NCS 2.8 and NCS 2.9
=> bluetooth: fast_pair: fmdn: add uptime workaround to the clock module

.github/workflows/compliance.yml
setuptools 77.0 release on March19 caused some packages to fail to install
=> ci: compliance action: lock setuptools becuase of failed install

samples/peripheral/802154_phy_test/README.rst, samples/peripheral/802154_phy_test/sample.yaml
Remove nrf54h20dk/nrf54h20/cpurad platform support for 802154_phy_test sample.yaml configuration
Ref: KRKNWK-20094
=> samples: 802154_phy_test: Remove nrf54h20dk support

subsys/suit/ipuc/src/suit_ipuc_sdfw.c
Erasing of the IPUC took about 500ms of time, which led to many issues.
The erasing was removed, instead different security measures were introduced, erasing parts when the
seek offset is greater than the write peek offset.
=> suit: Do not erase on IPUC write setup

tests/drivers/uart/uart_baudrate_test/testcase.yaml
Prevent enabled clock control to scale down freq,
as this affects gpio polling time.
=> tests: drivers: uart: uart_baudrate_test: keep high freq

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, scripts/hid_configurator/NrfHidManager.py
Remove HID device type mapping for DKs. A DK may use various HID roles (depending on configuration). Assigning a fixed type per board may be misleading.
Jira: NCSDK-29958
=> scripts: hid_configurator: Update TYPE2BOARDLIST

samples/bluetooth/channel_sounding_ras_initiator/README.rst, samples/bluetooth/channel_sounding_ras_initiator/src/distance_estimation.c
added better handling of multiple antenna path in Channel Sounding Initiator distance estimation algorithm.
Now distance is calculated and printed separately
for each antenna path
=> samples: bluetooth: distance measurement multiantenna improvements

samples/pmic/native/npm1300_fuel_gauge/sample.yaml, samples/pmic/native/npm1300_one_button/sample.yaml
Remove reference to unused harnesses.
Set build_only for compile targets.
=> samples: pmic: npm1300: sample.yaml cleanup

subsys/nrf_security/src/psa_crypto_driver_wrappers.c
Required when using linker options to keep all sections:
zephyr_ld_options(-Wl,--no-gc-sections)
zephyr_ld_options(-Wl,--orphan-handling=place)
=> nrf_security: Include key wrap in psa_crypto_driver_wrappers.c

applications/serial_lte_modem/Kconfig, applications/serial_lte_modem/overlay-cmux.conf, applications/serial_lte_modem/src/slm_at_host.c, applications/serial_lte_modem/src/slm_cmux.c
nRF9151DK has interface chip that automatically detects if flow
control is enabled or not. On start up, HWFC pins are floating.
On Zephyr DTS side, nRF9151 CTS pin has pull-up enabled, so if
nRF91 app core boots faster than interface chip, the serial port
might be blocked because of flow control.
Change pull-up to pull-down so nRF91 is allowed to write if interface
chip still has not enabled the HWFC pins.
If DLCI channel for AT commands has been closed, avoid sending
data to the pipe.
Channel is resumed once remote end connects to the DLCI channel.
=> applications: slm: Fix HWFC problems on nRF9151DK

drivers/mspi/mspi_nrfe.c
The `mspi_ipc_data_send` and `send_data` functions have been merged into one to prevent misuse due to the lack of `NO_COPY` distinction in the `mspi_ipc_data_send` function.
=> drivers: mspi: sdp: merge send_data functions

include/bluetooth/services/fast_pair/fmdn.h, samples/bluetooth/fast_pair/locator_tag/src/fp_adv.c, samples/bluetooth/fast_pair/locator_tag/src/main.c, subsys/bluetooth/services/fast_pair/fmdn/beacon_actions.c, subsys/bluetooth/services/fast_pair/fmdn/include_priv/fp_fmdn_state.h, subsys/bluetooth/services/fast_pair/fmdn/read_mode.c, subsys/bluetooth/services/fast_pair/fmdn/state.c, west.yml
Added the new FMDN API - bt_fast_pair_fmdn_is_provisioneda. The API can be used to check the device provisioning in the synchronous manner.
Changed the bt_fast_pair_fmdn_info_cb.provisioning_state_changed callback behaviour. The callback no longer reports the initil provisioning state after the Fast Pair subsystem is enabled with the bt_fast_pair_enable API.
Aligned the affected Fast Pair projects that use the FMDN extension.
Ref: NCSDK-30856
=> bluetooth: fast_pair: fmdn: add API for checking the provisioning state

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/caf/modules/buttons.c
Adds option to use more GPIOs. Eralier only GPIO0 and GPIO1 were supported. Now, the generic solution supports all GPIOs available in DTS.
Jira: NCSDK-31766
=> caf: modules: buttons: Add possibility to use more GPIOs

samples/cellular/modem_shell/src/link/link_shell_pdn.c
Two PDN events were missing from a mapping table. Furthermore, if an event which was missing from the table was received, modem_shell crashed. Added the missing events and implemented mapping using similar approach which is used elsewhere in the sample, which handles missing items gracefully.
TNSW-66408
=> samples: cellular: modem_shell: Fix printing of PDN events

subsys/mpsl/init/mpsl_init.c
Temporary fix that will force rramc to not go to powerdown. Mpsl gets to high interupt latency without this and stops working.
=> mpsl: Temporary fix to make 54l15/ns functionaly work

samples/wifi/scan/sample.yaml
Now that the hard dependency of scan with nrf7000 is removed, add back nRF7002DK, this aligns the docs (README).
=> samples: wifi: scan: Add back nRF7002DK

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/matter/lock/src/access/access_manager.cpp, samples/matter/lock/src/access/access_manager.h, samples/matter/lock/src/app_task.cpp, samples/matter/lock/src/app_task.h, samples/matter/lock/src/bolt_lock_manager.cpp, samples/matter/lock/src/bolt_lock_manager.h, samples/matter/lock/src/zcl_callbacks.cpp
* Remove redundant call to `BoltLockManager::[Lock|Unlock]` from
MatterPostAttributeChangeCallback.
* Return `ValidatePINResult` containing user id and credential used for
validation.
* Add support for `UserIndex`, `FabricIndex`, `SourceNode` and
`Credentials` fields.
=> samples: matter: lock: Support all fields of LockOperation event

subsys/net/openthread/rpc/server/ot_rpc_coap.c, subsys/net/openthread/rpc/server/ot_rpc_message.c, tests/subsys/net/openthread/rpc/server/src/coap_suite.c
1. Fix message handle leak after sending a CoAP response.
2. Add unit tests to verify that handle is allocated/freed.
3. Improve CoAP RPC server thread safety.
4. Other minor fixes and improvements.
=> net: openthread: rpc: fix handle leak in CoAP RPC server

subsys/caf/modules/Kconfig.power_manager, subsys/caf/modules/power_manager.c
Change implies CONFIG_PM_DEVICE_RUNTIME for nRF54H SoC Series. This is done to allow using the framework to reduce power consumption. Enabling Device Runtime Power Management also prevents from using System-Managed Device Power Management by default. The System-Managed Device Power Management does not work properly with some drivers (e.g. nrfx UARTE).
PR also switches to using imply instead of select for `CONFIG_PM_DEVICE` (the option is not required by CAF Power Manager).
Jira: NCSDK-32519
=> caf: power_manager: Imply Device Runtime Power Management for nRF54H

snippets/sdp/mspi/board/nrf54l15dk_nrf54l15_cpuapp.overlay, snippets/sdp/mspi/sdp-mspi-app.overlay, snippets/sdp/mspi/soc/nrf54l15_cpuapp.overlay, tests/zephyr/drivers/flash/common/single.overlay, tests/zephyr/drivers/flash/common/testcase.yaml
Also, add testcase that keeps checking single mode in flash driver test.
Depends on https://github.com/nrfconnect/sdk-nrf/pull/20731 and https://github.com/nrfconnect/sdk-nrf/pull/21043
=> sdp: switch to Quad mode by default

doc/nrf/external_comp/bt_fast_pair.rst, doc/nrf/releases_and_maturity/migration/migration_guide_3.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
The documentation update follows the code changes done in the following PR:
https://github.com/nrfconnect/sdk-nrf/pull/20970
=> Fast Pair: FMDN provisioning state APIs: documentation update

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/fast_pair/locator_tag/README.rst, samples/bluetooth/fast_pair/locator_tag/configuration/prj.conf
Enabled the Link Time Optimization (LTO) in the debug (default) configuration of the Fast Pair Locator Tag sample to get it aligned with the release configuration.
=> samples: bluetooth: fast_pair: locator_tag: enable lto in debug config

applications/serial_lte_modem/src/main.c, lib/modem_slm/modem_slm.c
Asserts were enabled with PR https://github.com/nrfconnect/sdk-nrf/pull/20040.
This has caused an assert to occur when pressing power pin, because GPIO callback (`power_pin_callback_wakeup()`) called `slm_at_host_power_on()`, which called `k_sleep()`, which has an assert that it's not called from interrupt context. Added most of the wake up operation into a worker.
Also added a command to `modem_slm` library for toggling power pin. In addition, adding main command for operations done in SLM shell device. Toggling power pin is done as follows:
"slmsh powerpin"
I have some follow-up PRs for SLM shell so I'll also update its documentation then regarding the new command. I'd like to get these changes in whenever they are technically OK so that test engineers can proceed testing the power pin. …
=> applications: serial_lte_modem: Fix asserts when pressing power pin

doc/nrf/gsg_guides/nrf7002_gs.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/wifi/ble_coex/README.rst, samples/wifi/shell/README.rst, samples/wifi/thread_coex/README.rst
Replace all instances of `nrfjprog` commands with
`nrfutil` commands as nrfjprog is going to be deprecated.
Fixes SHEL-3520.
=> samples: wifi: Replace nrfjprog with nrfutil

subsys/bluetooth/services/ras/rrsp/ras_rrsp.c
I don't fully understand why a80371e72d7a08cf2d7cf2fb6ad2bb7f159e004f broke this service.
However the API docs say that using 0 as attr_count will make this function search until the end, which fixes the asserts.
=> bluetooth: services: ras: Fix RAS RRSP after GATT API changes

snippets/sdp/mspi/board/nrf54l15dk_nrf54l15_cpuapp.overlay
Include reset timings to ensure flash memory is correctly reset and able to recover before usage.
=> snippet: sdp: mspi: add reset timings

applications/sdp/mspi/src/main.c, drivers/mspi/mspi_nrfe.c, include/drivers/mspi/nrfe_mspi.h
~It still needs some testing but can be reviewed already.~
~Needs the revert commit from https://github.com/nrfconnect/sdk-nrf/pull/20807 to be able to switch to QUAD mode (not enough pins declared in DTS).~
=> sdp: vio pins dependent on overlay

doc/nrf/libraries/security/nrf_security/doc/configuration.rst
Document which version of PSA Crypto we implement so that customers can know which version of the API docs they should read.
=> nrf_security: doc: Document which version of PSA Crypto we implement

west.yml
Replaces PSA ed25519 sdk-nrf specific implementation with provided from upstream.
=> manifest: Update sdk-mcuboot version

samples/matter/smoke_co_alarm/README.rst
Smoke CO alarm contains wrong QR code payload in the documentation.
=> samples: matter: Fixed QR code payload for smoke co alarm

boards/nordic/nrf7120pdk/nrf7120_cpuapp_common.dtsi, dts/bindings/wifi/nordic,nrf71.yaml, dts/common/nordic/nrf7120_enga.dtsi
Extend DTS files for nRF7120 PDF to include Wi-Fi support.
=> wifi: Add support for nRF7120 DTS

subsys/net/openthread/rpc/client/ot_rpc_srp_client.c, tests/subsys/net/openthread/rpc/client/src/srp_client_suite.c
The subtype array provided to otSrpClientAddService can be NULL but the RPC client would try to always access the array.
=> net: openthread: rpc: handle NULL service subtype array

applications/nrf_desktop/src/modules/dvfs.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
FIX nrf_desktop dvfs module consuming
ble_peer_conn_params event when it should not.
JIRA: NCSDK-31478
=> applications: nrf_desktop: Fix dvfs module consuming event

applications/sdp/mspi/src/main.c, drivers/mspi/mspi_nrfe.c
Improve setting pins DQ2 and DQ3 to high state. Now it is done only when they are defined.
I left setting them to high by default. It is done the same way for QSPI driver in `pinctrl_nrf.c`, at least for DQ3 pin (RESET).
Also, DTS does not support setting default/initial state of a pin.
~Based on https://github.com/nrfconnect/sdk-nrf/pull/20806 , please, review only two last commits.~
=> applications: sdp: mspi: Improve setting DQ2, DQ3 initial state

include/nrf_rpc/nrf_rpc_uart.h, samples/nrf_rpc/protocols_serialization/server/Kconfig, samples/nrf_rpc/protocols_serialization/server/boards/nrf52840dk_nrf52840.overlay, samples/nrf_rpc/protocols_serialization/server/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/nrf_rpc/protocols_serialization/server/src/main.c, subsys/nrf_rpc/nrf_rpc_uart.c
1. Add nrf_rpc_uart_initialized_hook() that is called when an nRF RPC UART transport instance gets ready to receive packets.
2. Use the hook in the PS server sample to toggle the LED selected with /alias/rpc-alive-led DTS property when the RPC transport is ready.
=> samples: nrf_rpc: ps_server: RPC alive LED

applications/connectivity_bridge/src/modules/usb_cdc_handler.c
App was not working when receiving RX bytes on CDC transport. Reworked interrupt handler.
=> app: conn_bridge: Fix uart cdc handler

samples/pmic/native/npm2100_fuel_gauge/src/main.c
Add missing shell command for 2SAA and 2SAAA batteries, and corresponding string values.
=> samples: npm2100_fuel_gauge: Add missing shell cmd and strings

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
Add IS_ENABLED checks to ensure a given key type is needed. This improves rom usage for many standard use cases.
To make the sonar cloud pass I had to refactor export_ecc_public_key so added that as a separate commit to make it easy to see what was the intended functional change and what is refactoring.
=> nrf_security: cracen: Exclude functions that are not needed

doc/nrf/includes/sample_dtm_radio_test_fem.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/bluetooth/direct_test_mode/README.rst, samples/bluetooth/direct_test_mode/sample.yaml, samples/peripheral/radio_test/README.rst, samples/peripheral/radio_test/sample.yaml
Add nRF2220EK support for:
- direct_test_mode
- radio_test samples.
Jira: NCSDK-31910
=> samples: Add nRF2220EK support for RT and DTM samples

doc/nrf/app_dev/device_guides/pmic/index.rst, doc/nrf/app_dev/device_guides/pmic/npm2100.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/pmic/native/npm2100_fuel_gauge/README.rst
Add "Developing with the nPM2100 PMIC" document
to the list of "Developing with PMICs" guide document.
=> doc: working_with_nrf: Add npm2100 pmic

samples/wifi/ble_coex/README.rst, samples/wifi/ble_coex/sample.yaml, samples/wifi/thread_coex/README.rst, samples/wifi/thread_coex/sample.yaml
Update the SHIELD configuration in the coexistence samples to ensure the correct overlay files are included. This change addresses the issue of missing overlay files by specifying the sample name, such as `ble_coex_SHIELD` parameter.
=> samples: wifi: Update SHIELD configuration for coex samples

doc/nrf/libraries/caf/power_manager.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change adds documentation for introduced Kconfig configuration changes.
Jira: NCSDK-32519
=> caf: power_manager: Document Kconfig changes

applications/nrf_desktop/configuration/nrf52820dongle_nrf52820/pm_static.yml, applications/nrf_desktop/configuration/nrf52833dk_nrf52820/pm_static.yml, applications/nrf_desktop/configuration/nrf52dmouse_nrf52832/pm_static.yml, applications/nrf_desktop/configuration/nrf52dmouse_nrf52832/pm_static_release.yml, applications/nrf_desktop/configuration/nrf52kbd_nrf52832/pm_static.yml, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change introduces static Partition Manager memory maps for single-image configurations. This is done to ensure that dynamic partitioning is not used.
Jira: NCSDK-30908
=> applications: nrf_desktop: Add static PM memory maps for single-image

.github/workflows/backport.yml, .github/workflows/compliance.yml, .github/workflows/contribs.yml, .github/workflows/docbuild.yml, .github/workflows/docker.yml, .github/workflows/docpublish.yml, .github/workflows/enforce-toolchain-synchronization.yml, .github/workflows/labeler.yml, .github/workflows/license-reusable.yml, .github/workflows/manifest.yml, .github/workflows/scripts-test.yml, .github/workflows/src-mirror.yml, .github/workflows/stale.yml, .github/workflows/validate-pip-requirements-fixed-file.yml
=> ci: Pin GH actions to SHAs

doc/nrf/drivers/wifi/low_level_api.rst
Fixed style issues in the Low-level API doc
under the Wi-Fi drivers section.
=> doc: wifi: Fix Low-level API doc

tests/drivers/gpio/gpio_more_loops/boards/nrf7120pdk_nrf7120_cpuapp.overlay, tests/drivers/gpio/gpio_more_loops/testcase.yaml, tests/drivers/gpio/gpio_nfct/boards/nrf7120pdk_nrf7120_cpuapp.overlay, tests/drivers/gpio/gpio_nfct/testcase.yaml, tests/drivers/lpuart/boards/nrf7120pdk_nrf7120_cpuapp.conf, tests/drivers/lpuart/boards/nrf7120pdk_nrf7120_cpuapp.overlay, tests/drivers/lpuart/testcase.yaml, tests/drivers/pwm/gpio_loopback/boards/nrf7120pdk_nrf7120_cpuapp.overlay, tests/drivers/pwm/gpio_loopback/boards/nrf7120pdk_nrf7120_cpuflpr.overlay, tests/drivers/pwm/gpio_loopback/testcase.yaml, tests/drivers/uart/uart_baudrate_test/boards/nrf7120pdk_nrf7120_cpuapp_uart00.overlay, tests/drivers/uart/uart_baudrate_test/boards/nrf7120pdk_nrf7120_cpuapp_uart21.overlay, tests/drivers/uart/uart_baudrate_test/boards/nrf7120pdk_nrf7120_cpuapp_uart22.overlay, tests/drivers/uart/uart_baudrate_test/testcase.yaml
Adding support for PWM and UART NCS twister tests
=> tests: Nrf7120 GPIO, PWM and UART twister test support

doc/nrf/protocols/esb/index.rst, subsys/esb/esb.c
This change fixes the conﬁguration of timer shorts for CONFIG_ESB_NEVER_DISABLE_TX mode.
=> esb: Fix timer shorts configuration for CONFIG_ESB_NEVER_DISABLE_TX

doc/nrf/installation/recommended_versions.rst, doc/nrf/links.txt, doc/nrf/protocols/wifi/regulatory_certification/test_setup.rst, doc/nrf/releases_and_maturity/migration/migration_guide_3.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, doc/nrf/shortcuts.txt
Removed nRF Command Line Tools section from recommended_versions.rst. Updated archiving notes to phrasing approved by stakeholders. Updated other pages to match phrasing.
NCSDK-30153.
=> doc: final archiving update for nRF CLT

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/app_jwt/CMakeLists.txt, lib/app_jwt/Kconfig, subsys/net/lib/nrf_cloud/Kconfig, subsys/net/lib/nrf_cloud/src/nrf_cloud_jwt.c
Replace internal JWT implementation with the app_jwt library.
Requires the usage of prime256v1 keys.
Adds a unit test for the app_jwt library.
=> nrfcloud: use app jwt library

subsys/net/openthread/rpc/client/ot_rpc_coap.c, subsys/net/openthread/rpc/client/ot_rpc_message.c, subsys/net/openthread/rpc/client/ot_rpc_netdiag.c, subsys/net/openthread/rpc/client/ot_rpc_udp.c, subsys/net/openthread/rpc/common/ot_rpc_types.h, subsys/net/openthread/rpc/server/ot_rpc_coap.c, subsys/net/openthread/rpc/server/ot_rpc_message.c, subsys/net/openthread/rpc/server/ot_rpc_message.h, subsys/net/openthread/rpc/server/ot_rpc_netdiag.c, subsys/net/openthread/rpc/server/ot_rpc_resource.h, subsys/net/openthread/rpc/server/ot_rpc_udp.c, tests/subsys/net/openthread/rpc/server/src/coap_suite.c, tests/subsys/net/openthread/rpc/server/src/message_suite.c
Add macros to declare/define necessary functions for internal resource tables on server.
=> net: openthread: rpc: standarize resources allocation

lib/nrf_modem_lib/nrf9x_sockets.c
Fixed buffer overflow when `getsockopt()` is called for `SO_RCVTIMEO` or `SO_SNDTIMEO` with a buffer which is too small for `struct timeval`.
=> lib: nrf_modem_lib: Fix possible buffer overflow

include/bluetooth/services/fast_pair/fast_pair.h, include/bluetooth/services/fast_pair/fmdn.h
fast_pair and fmdn header files- Remove ref from the SYS_INIT marco
=> doc: fast_pair and fmdn - Remove ref from SYS_INIT

doc/nrf/libraries/modem/modem_battery.rst
The upper bound of the voltage range was erroneously specified as 3500 mV when, instead, it should be
5000 mV according to the technical documentation
for `%XVBATLOWLVL`.
=> doc: libraries: modem_battery: fix typo

applications/serial_lte_modem/src/mqtt_c/slm_at_mqtt.c, subsys/net/lib/mqtt_helper/mqtt_helper.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c, tests/subsys/net/lib/mqtt_helper/src/mqtt_helper_test.c, west.yml
Pull MQTT 5.0 support from upstream and align NCS codebase.
=> manifest: Pull MQTT 5.0 support from upstream

CODEOWNERS, doc/tfm/conf.py, doc/tfm/wrapper.rst
Added wrapper.rst and links.txt for the TF-M docset. NCSDK-32253.
----
Wrapper preview at https://ncsdoc.z6.web.core.windows.net/PR-20809/tfm/wrapper.html -- the current index won't be replaced until this PR is merged due to server cache.
----
Next PR will add more information to the wrapper and the links.txt file.
=> doc: TF-M: add TF-M docset wrapper

doc/nrf/includes/zephyr_sample_test.txt, doc/nrf/samples.rst, doc/nrf/test_and_optimize.rst
Add information about Zephyr tests and samples
that extend their support with new Nordic development kits.
NCSDK-32190
=> doc: Add information about Zephyr tests and samples

doc/nrf/app_dev/device_guides/nrf70/power_profiling.rst, doc/nrf/protocols/wifi/regulatory_certification/adaptivity_test_procedure.rst, doc/nrf/protocols/wifi/regulatory_certification/antenna_gain_compensation.rst, doc/nrf/protocols/wifi/regulatory_certification/band_edge_compensation.rst, doc/nrf/protocols/wifi/regulatory_certification/radio_test_short_range_sample/ble_radio_test_for_per_measurements.rst, doc/nrf/protocols/wifi/regulatory_certification/test_setup.rst, doc/nrf/protocols/wifi/regulatory_certification/using_wifi_shell_sample.rst, doc/nrf/protocols/wifi/regulatory_certification/wifi_radio_test_sample/wifi_build_instructions.rst, doc/nrf/protocols/wifi/regulatory_certification/wifi_radio_test_sample/wifi_radio_test_for_per_measurements.rst, samples/wifi/throughput/README.rst
[SHEL-3047]: Update Regulatory testing with latest changes and remove errors.
[SHEL-3047]: https://nordicsemi.atlassian.net/browse/SHEL-3047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> doc: wifi: Corrections to Regulatory Testing doc

west.yml
Update revision for trusted-firmware-m:
- Fix data loss scenario with protected storage.
=> manifest: Update trusted-firmware-m

subsys/mpsl/init/Kconfig
It is a bit excessive to calibrate hfpll every 4s. Increasing to 60s to save power in the case where LFRC calibartion doesnt happen (when LFXO is used).
=> mpsl: Increase default config for how often hfpll is calibrated

applications/nrf_desktop/configuration/nrf52840dk_nrf52840/prj_fast_pair.conf, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/prj_wwcb.conf, applications/nrf_desktop/configuration/nrf52840gmouse_nrf52840/prj_fast_pair.conf, applications/nrf_desktop/configuration/nrf52840gmouse_nrf52840/prj_release_fast_pair.conf, applications/nrf_desktop/configuration/nrf52kbd_nrf52832/prj_release_fast_pair.conf, applications/nrf_desktop/configuration/nrf54l15dk_nrf54l05_cpuapp/prj_release_fast_pair.conf, applications/nrf_desktop/configuration/nrf54l15dk_nrf54l10_cpuapp/prj_fast_pair.conf, applications/nrf_desktop/configuration/nrf54l15dk_nrf54l15_cpuapp/prj_fast_pair.conf, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Support for GATT long/reliable writes allows to perform fwupd DFU over Bluetooth LE with GATT Clients that do not perform MTU exchange. This is needed to support fwupd BLE DFU with ChromeOS and Floss.
Jira: NCSDK-32719
=> applications: nrf_desktop: Enable GATT long/reliable writes

scripts/generate_psa_key_attributes.py
Turns out that the string strip function in python doesn't just strip any occurrence of any sub string which is equal to the string I pass in but also also any occurrence of any of the characters I pass in to the function. Replaced the strip function with a function that strips away only the sub-string I pass in to the function from the beginning of the string.
=> scripts: generate psa key attributes strips to many zeros

applications/nrf5340_audio/doc/building.rst, applications/nrf5340_audio/tools/buildprog/buildprog.py, applications/nrf5340_audio/tools/buildprog/nrf5340_audio_dk_devices.py, applications/nrf5340_audio/tools/buildprog/program.py, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
OCT-3320
Buildprog issues with building and programming single cores.
=> applications: nrf5340_audio: Buildprog, pristine and flashing issue

samples/bluetooth/peripheral_mds/memfault_config/memfault_platform_config.h, samples/debug/memfault/config/memfault_platform_config.h, west.yml
In Memfault SDK 1.18.0, the config
`MEMFAULT_METRICS_HEARTBEAT_INTERVAL_SECS` set via `memfault_platform_config.h` was replaced with the Kconfig option `CONFIG_MEMFAULT_METRICS_HEARTBEAT_INTERVAL_SECS`.
This commit updates the SDK version and:
- Removes references to the old config
- Adds example usage of `CONFIG_MEMFAULT_METRICS_HEARTBEAT_INTERVAL_SECS`
=> manifest: Update Memfault SDK to 1.18.0

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/esb/esb_prx/boards/nrf54l15dk_nrf54l05_cpuapp.conf, samples/esb/esb_prx/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/esb/esb_prx/sample.yaml, samples/esb/esb_ptx/boards/nrf54l15dk_nrf54l05_cpuapp.conf, samples/esb/esb_ptx/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/esb/esb_ptx/sample.yaml
Adding build support for nRF54L05 and nRF54L10 devices on the nRF54L15DK boards with required configurations.
=> samples: esb: Add support for the nRF54L05 and L10 build targets

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/cellular/modem_shell/src/sock/sock.c, samples/cellular/modem_shell/src/sock/sock.h, samples/cellular/modem_shell/src/sock/sock_shell.c
Added support for setting/getting socket options in a generic manner.
Jira: MOSH-636
=> samples: cellular: modem_shell: sock: 'option' set/get commands

subsys/dm/rpc/Kconfig
Added enabling SOC_NRF53_CPUNET_ENABLE for
Distance Measurement over RPC.
=> dm: rpc: Enable CONFIG_SOC_NRF53_CPUNET for NRF5340

applications/serial_lte_modem/sample.yaml
Only basic configuration and lwm2m carrier library related configs were in place.
Adding Ext MCU, PPP, PPP+CMUX and few more.
Jira: LRCS-96
=> applications: serial_lte_modem: Add more configurations to sample.yaml

samples/wifi/sta/src/main.c
Add a guard for the include file. There is a twister test for this, but as the is available in NCS it works, but in upstream this doesn't work as the include file is missing and hence throws a build error.
=> samples: wifi: sta: Fix Wi-Fi ready disabled build

boards/shields/nrf7002eb_interposer_p1/Kconfig.shield
Deprecate nRF7002eb interposer shield for use with nRF54 series DKs
=> boards: shields: Deprecate nRF7002eb interposer shield

applications/serial_lte_modem/boards/thingy91x_nrf9151_ns.conf, applications/serial_lte_modem/boards/thingy91x_nrf9151_ns.overlay
New versions of Thingy:91 X use connectivity bridge, which does not support hw-flow-control.
=> applications: serial_lte_modem: Disable hwfc for Thingy:91 X

applications/connectivity_bridge/README.rst, applications/connectivity_bridge/README_TEMPLATE.txt, applications/connectivity_bridge/boards/thingy91_nrf52840_readme.txt, applications/connectivity_bridge/boards/thingy91x_nrf5340_cpuapp_readme.txt, applications/connectivity_bridge/src/disk/config.c
Improve layout in USB drive Config.txt and README.txt. Document that the device advertises as the configured BLE_NAME. Change from "LTE Link Monitor" to "nRF Connect Serial Terminal".
Document that USB host is also available on Mac.
=> applications: connectivity_bridge: Improve documentation

samples/bluetooth/peripheral_uart/src/main.c
This sample uses the UART interface to communicate with the NUS.
Logging is handled using RTT.
=> samples: bluetooth: peripheral_uart: replace printk with logging API

doc/nrf/libraries/debug/memfault_ncs.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, lib/nrf_modem_lib/shell/trace.c, modules/memfault-firmware-sdk/CMakeLists.txt, modules/memfault-firmware-sdk/Kconfig, modules/memfault-firmware-sdk/include/memfault_lte_coredump_modem_trace.h, modules/memfault-firmware-sdk/memfault_lte_coredump.c, modules/memfault-firmware-sdk/memfault_lte_coredump_modem_trace.c, samples/debug/memfault/README.rst, samples/debug/memfault/boards/nrf9151dk_nrf9151_ns.conf, samples/debug/memfault/boards/nrf9151dk_nrf9151_ns.overlay, samples/debug/memfault/overlay-modem-trace-to-memfault.conf, samples/debug/memfault/sample.yaml
Add support for uploading modem traces to Memfault upon a coredump. This is useful to get the full picture of what happened leading up to a crash.
The feature is optional and guarded by a Kconfig option. It is enabled by default in the overlay `overlay-modem_trace_to_memfault.conf` added to the memfault sample.
Tests and docs has been updated accordingly.
=> modules: memfault: Add support for uploading modem traces to Memfault

.github/workflows/compliance.yml
It is possible that rebase brings changes to west.yml thus west update is needed.
=> ci: add west update to compliance
