modules/memfault-firmware-sdk/memfault_location_metrics.c
Add missing break in switch statement.
=> modules: memfault: Add missing break in switch

subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_key_ids.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c
This reverts commit 45a897f277edbf95efeb824b0e76bad47b9f69b3.
This causes issues with the platform keys and needs to be reworked.
=> Revert "nrf_security: Refactor Cracen IKG keys"

samples/nrf_rpc/protocols_serialization/client/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/nrf_rpc/protocols_serialization/server/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
Commit fixes uart dtc overlays to have working
hardware flow control.
=> samples: protocol_serialization: fix uart hw flow dtc

doc/_utils/redirects.py
Update redirects.py file for
structural changes in following PR:
* PR https://github.com/nrfconnect/sdk-nrf/pull/16623
* PR https://github.com/nrfconnect/sdk-nrf/pull/16979
=> doc: update redirects for BLE

tests/bluetooth/iso/modules/iso_broadcast_sink.c
OCT-3076
Added change to bis_bitfield.
=> Tests: Bluetooth: Updated after upmerge

scripts/quarantine.yaml
Regression after https://github.com/nrfconnect/sdk-nrf/pull/17685
=> scripts: quarantine: add quarantine for sample.softap.wifi.provision

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_architecture_reset.rst
Updated 54H architecture reset doc.
=> doc: Update 54H architecture reset doc

applications/matter_bridge/doc/matter_bridge_description.rst, doc/nrf/app_dev/device_guides/nrf91/nrf91_snippet.rst, samples/cellular/http_update/application_update/README.rst
Minor fixes to following pages
related to the 2.8 release:
* Matter Bridge applications
* nrf91_snippet.rst
* application_update sample
=> doc: Minor fixes to docs

subsys/net/lib/nrf70_fw_ext/CMakeLists.txt, west.yml
This is now updated in nrfxlib.
=> net: lib: nrf70_fw_ext: Update the FW blobs directory name

tests/benchmarks/power_consumption/gpio/src/driver_test.c
gpio_is_ready_dt returns bool, assert it directly.
=> tests: benchmarks: power_consumption: gpio: fix gpio ready check

west.yml
=> manifest: update Mbed TLS to 3.6.2

tests/benchmarks/current_consumption/system_off/testcase.yaml
Extend testcase.yaml with additional scenario.
=> tests: benchmarks: Add System OFF test with GRTC wakeup.

doc/nrf/external_comp/bt_fast_pair.rst, doc/nrf/libraries/bluetooth_services/services/fast_pair.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/bluetooth/services/fast_pair/Kconfig.fast_pair
=> fast_pair: Add bond management documentation

subsys/nrf_rpc/nrf_rpc_uart.c
PR includes:
1. fix tx flipping
2. fix rx flipping
3. redesign hdlc state machine
4. reaction on frame with broken crc
=> nrf_rpc: improve nrf54l rpc uart stability

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_fetch.rst
This commit updates this part of the documentation taking into account changes for 2.8.0 release
=> doc: SUIT How to fetch payloads guide fixes for 2.8.0

applications/nrf5340_audio/broadcast_sink/Kconfig.defaults, applications/nrf5340_audio/broadcast_sink/main.c, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/Kconfig, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.h
Add CSIS to BIS headset with scan delegator.
OCT-3088
=> applications: nrf5340_audio: Add CSIS to BIS scan delegator

west.yml
Brings in missing TLV definition.
=> manifest: MCUboot: Fix broken imgtool

cmake/version_app.cmake
Updates this variable to match the expected value
=> cmake: version_app: Change CMAKE_SOURCE_DIR to APPLICATION_SOURCE_DIR

subsys/esb/esb.c
When esb_flush_tx is called by PRX to flush the ACK payload buffer,
it is also necessary to reset the structures that store the ACK payload.
=> subsys/esb: Fix tx buffer flush logic for ACK payload

samples/nfc/writable_ndef_msg/README.rst, samples/nfc/writable_ndef_msg/src/main.c, samples/nfc/writable_ndef_msg/src/ndef_file_m.c, samples/nfc/writable_ndef_msg/src/ndef_file_m.h
The change updates documentation and
aligns comments related to the file system.
=> samples: nfc: writable_ndef_msg: Align documentation

doc/nrf/index.rst, doc/nrf/releases_and_maturity.rst, doc/nrf/releases_and_maturity/known_issues.rst, doc/nrf/releases_and_maturity/migration/migration_guide_1.x_to_2.x.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.4.99-cs3_to_2.6.99-cs2.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.7.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs1.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs2.rst, doc/nrf/releases_and_maturity/migration/migration_hwmv2.rst, doc/nrf/releases_and_maturity/migration/migration_sysbuild.rst, doc/nrf/releases_and_maturity/migration_guides.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
post-release doc update after 2.8 preview1
=> doc: post-release doc update after 2.8 preview1

scripts/docker/Dockerfile
Bump nrfutil device to version 2.7.2
=> dokcer: Bump nrfutil device to version 2.7.2

doc/nrf/index.rst, doc/nrf/releases_and_maturity.rst, doc/nrf/releases_and_maturity/known_issues.rst, doc/nrf/releases_and_maturity/migration/migration_guide_1.x_to_2.x.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.4.99-cs3_to_2.6.99-cs2.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.7.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs1.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs2.rst, doc/nrf/releases_and_maturity/migration/migration_hwmv2.rst, doc/nrf/releases_and_maturity/migration/migration_sysbuild.rst, doc/nrf/releases_and_maturity/migration_guides.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Backport 824fee8227d1b9e64606085f5f8034546c1eac95 from #18180.
=> [Backport v2.8-branch] doc: post-release doc update after 2.8 preview1

tests/benchmarks/power_consumption/adc/testcase.yaml, tests/benchmarks/power_consumption/adc_async/testcase.yaml, tests/benchmarks/power_consumption/flash/testcase.yaml, tests/benchmarks/power_consumption/gpio/testcase.yaml, tests/benchmarks/power_consumption/i2c/testcase.yaml, tests/benchmarks/power_consumption/spi/testcase.yaml, tests/benchmarks/power_consumption/uart_async/testcase.yaml, tests/benchmarks/power_consumption/uart_polling/testcase.yaml
Add test methods for power consumption tests to allow setting individual power consumption thresholds for each test.
=> tests: benchmarks: power_consumption: Specify test methods.

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_architecture_memory.rst
=> doc: Updated 54H memory arch doc

samples/openthread/cli/harness-thci/nRF_Connect_SDK_11_12.py, samples/openthread/cli/harness-thci/nRF_Connect_SDK_13_14.py
fix incorrect calculation of csl period
=> samples: openthread: fix csl period in THCI

samples/wifi/sta/src/main.c
STA sample can be used by DK's and EK's.
=> samples: wifi: sta: Fix EK(SPI) build

doc/nrf/libraries/nfc/rpc/index.rst, samples/nrf_rpc/protocols_serialization/client/README.rst, samples/nrf_rpc/protocols_serialization/server/README.rst
Commit adds nfc rpc documentation page.
=> doc: add nfc rpc

west.yml
Updates sdc with Power Class 1 Feature bit enabled
=> manifest: sdk-nrfxlib: Update SoftDevice Controller

samples/cellular/nrf_cloud_multi_service/overlay-nrf7002ek-wifi-scan-only.conf
Small config tweak to fix Wi-Fi scan on LTE-connectivity MSS builds.
Related to SHEL-3213
=> samples: mss: Fix Wi-Fi scan

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_external_memory.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_push.rst, samples/suit/smp_transfer/suit/nrf54h20/app_envelope_extflash.yaml.jinja2, samples/suit/smp_transfer/suit/nrf54h20/rad_envelope_extflash.yaml.jinja2, samples/suit/smp_transfer/suit/nrf54h20/root_with_binary_nordic_top_extflash.yaml.jinja2
Update SUIT documentation about firmware updates with external memory to match with the latest NCS codebase.
Ref: NCSDK-29735
=> doc: Update FWU with external memory docs

doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf54l/zms.rst
adds info regarding device support, enabling and optimizing ZMS
moved to the Developing with nrf54l section
=> doc: add general ZMS info

applications/nrf_desktop/CMakeLists.txt, applications/nrf_desktop/sysbuild/CMakeLists.txt
Backport 906964109b1116ec820067c1ba6b5f9941bbd823 from #18195.
=> [Backport v2.8-branch] applications: nrf_desktop: Update way of setting APPLICATION_CONFIG_DIR

snippets/hw-flow-control/boards/nrf52840dk_nrf52840.overlay, snippets/hw-flow-control/boards/nrf52dk_nrf52832.overlay, snippets/hw-flow-control/snippet.yml
Backport f65009c6c397390ef003d4281a71ab7830ab428b~2..f65009c6c397390ef003d4281a71ab7830ab428b from #18261.
=> [Backport v2.8-branch] Flow control for nrf52

doc/nrf/app_dev/bootloaders_dfu/index.rst, doc/nrf/app_dev/bootloaders_dfu/sysbuild_image_ids.rst
Backport 3ab71f2008ef9bbb55ae33428ed7aefb8d027623 from #18152.
=> [Backport v2.8-branch] doc: nrf: app_dev: bootloaders_dfu: Add sysbuild image ID docs

doc/nrf/app_dev/device_guides/nrf53/building_nrf53.rst, doc/nrf/app_dev/device_guides/nrf91/nrf91_features.rst, doc/nrf/app_dev/device_guides/nrf91/nrf91_programming.rst, doc/nrf/app_dev/device_guides/nrf91/nrf91_updating_fw_programmer.rst, doc/nrf/app_dev/device_guides/nrf91/thingy91x_updating_fw_programmer.rst, doc/nrf/external_comp/memfault.rst, doc/nrf/external_comp/nrf_cloud.rst, doc/nrf/includes/thingy91_prog_extdebugprobe.txt, doc/nrf/libraries/modem/modem_antenna.rst, doc/nrf/libraries/networking/nrf_cloud.rst, doc/nrf/links.txt, doc/nrf/protocols/lte/index.rst
Adding Thingy:91 X sections under Developing
with nRF91 Series devices.
NCSDK-29616
=> doc: Added Thingy:91 X sections under Developing with nRF91

doc/nrf/app_dev/device_guides/nrf53/building_nrf53.rst, doc/nrf/app_dev/device_guides/nrf91/nrf91_features.rst, doc/nrf/app_dev/device_guides/nrf91/nrf91_programming.rst, doc/nrf/app_dev/device_guides/nrf91/nrf91_updating_fw_programmer.rst, doc/nrf/app_dev/device_guides/nrf91/thingy91x_updating_fw_programmer.rst, doc/nrf/external_comp/memfault.rst, doc/nrf/external_comp/nrf_cloud.rst, doc/nrf/includes/thingy91_prog_extdebugprobe.txt, doc/nrf/libraries/modem/modem_antenna.rst, doc/nrf/libraries/networking/nrf_cloud.rst, doc/nrf/links.txt, doc/nrf/protocols/lte/index.rst
Backport 5d0bd86e3591411ddbdbc03e7afffa2d4fa0932c from #18165.
=> [Backport v2.8-branch] doc: Added Thingy:91 X sections under Developing with nRF91

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
=> doc: Changelog for 2.8.99

samples/nrf_compress/mcuboot_update/pm_static_nrf52840dk_nrf52840.yml, samples/nrf_compress/mcuboot_update/pm_static_nrf5340dk_nrf5340_cpuapp.yml, samples/nrf_compress/mcuboot_update/pm_static_nrf54l15dk_nrf54l15_cpuapp.yml
Updates static PM files to remove unused areas and have the secondary to ~70% of the primary
=> samples: nrf_compress: mcuboot_update: Update static PM files

subsys/bluetooth/controller/hci_internal.c
Added HCI command handler for Write Cached Remote Supported Capabilities command.
=> Bluetooth: Controller: Add Missing CS HCI cmd Handler

doc/nrf/external_comp/bt_fast_pair.rst, doc/nrf/external_comp/dult.rst, doc/nrf/libraries/bluetooth_services/services/fast_pair.rst, doc/nrf/libraries/others/dult.rst, doc/nrf/links.txt, samples/bluetooth/fast_pair/locator_tag/README.rst
Backport da3a1238454e0def13981cd6a31c5cadb34b1a49~2..da3a1238454e0def13981cd6a31c5cadb34b1a49 from #18138.
=> [Backport v2.8-branch] doc: Document DULT motion detector feature

scripts/west_commands/ncs-provision.py
Backport 19c0f9c249d0e53b50b188596133f207b68ff0d2 from #18355.
=> [Backport v2.8-branch] scripts: west_commands: extend west ncs-provision command with --dev-id

west.yml
=> [Backport v2.8-branch] manifest: Update sdk-find-my revision

doc/nrf/releases_and_maturity/software_maturity.rst
Mark Sidewalk features as supported except FUOTA.
=> doc: Update software maturity level for Sidewalk

doc/nrf/releases_and_maturity/software_maturity.rst
Backport be38147cf7c9c869a090d78bc2d5f2159f6e647b from #18382.
=> [Backport v2.8-branch] doc: Update software maturity level for Sidewalk

scripts/quarantine.yaml
=> quarantine: add applications.machine_learning.sensor_hub

doc/nrf/app_dev/board_support/board_names.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/gsg_guides/nrf9160_gs.rst, doc/nrf/links.txt
=> doc: misc updates

doc/nrf/app_dev/device_guides/nrf54l/features.rst
=> doc: nrf54l15 update features of

doc/nrf/app_dev/board_support/board_names.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/gsg_guides/nrf9160_gs.rst, doc/nrf/links.txt
Backport ae9d0e75e3fbaca8581c836839e55a527ff82c07 from #18356.
=> [Backport v2.8-branch] doc: misc updates

doc/nrf/app_dev/device_guides/nrf54l/features.rst
Backport 4bc9cdeb70a3276a45ed77748e647b9ddcdf1180 from #18307.
=> [Backport v2.8-branch] doc: nrf54l15 update features of

samples/bluetooth/mesh/ble_peripheral_lbs_coex/README.rst
Backport b62e98b291a2e29020f96631df3ebf054252c933 from #18402.
=> [Backport v2.8-branch] Samples: Bluetooth: Mesh: Add nRF54 tabs to coex sample

doc/nrf/links.txt, samples/openthread/cli/README.rst, samples/openthread/cli/sample.yaml, samples/openthread/cli/snippets/diag_gpio/boards/nrf52840dk_nrf52840.overlay, samples/openthread/cli/snippets/diag_gpio/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/openthread/cli/snippets/diag_gpio/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/openthread/cli/snippets/diag_gpio/diag_gpio.conf, samples/openthread/cli/snippets/diag_gpio/snippet.yml
Add snippets for diag gpio commands
=> samples: openthread: add diag gpio snippets

doc/nrf/app_dev/device_guides/nrf54l/snippets.rst
Add a note about TFM in the nRF54L15 snippet docs.
=> doc improvement: Add a note about TFM in the nRF54L15 snippet docs

subsys/partition_manager/CMakeLists.txt
=> partition_manager: Small fix to make vpr_launcher work on the nrf54l15DK

doc/nrf/releases_and_maturity/software_maturity.rst
doc: update software maturity level for Bluetooth
Update software maturity level for Bluetooth.
Ref: https://github.com/nrfconnect/sdk-nrfxlib/blob/main/softdevice_controller/README.rst
Signed-off-by: Yuxuan Cai <yuxuan.cai@nordicsemi.no>
=> doc: Bluetooth software maturity level 

doc/nrf/releases_and_maturity/software_maturity.rst
Backport 2272c54e7a01cbe16efe168e60a1056f8bf597fd~2..2272c54e7a01cbe16efe168e60a1056f8bf597fd from #18278.
=> [Backport v2.8-branch] doc: Bluetooth software maturity level 

samples/crypto/psa_tls/README.rst
Add note how to start openssl client/server with DTLS connection.
=> samples: crypto: improve psa_tls documentation

doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
Add info about ZMS in the migration guide.
has dependency on PR https://github.com/nrfconnect/sdk-nrf/pull/18174
=> doc improvement: Add info about ZMS in the migration guide

west.yml
Improvements to the duration and interrupt latency when writing to RRAM.
=> manifest: tf-m: pull in RRAM improvements

doc/nrf/releases_and_maturity/software_maturity.rst
Updates to Crypto API maturity table
=> doc: fix maturity tables for crypto

samples/bluetooth/mesh/dfu/distributor/prj.conf, samples/bluetooth/mesh/dfu/distributor/sysbuild/mcuboot.conf
Backport ecc960bd48e1858f36b41d1061c2dc10a487bbd4~2..ecc960bd48e1858f36b41d1061c2dc10a487bbd4 from #18508.
=> [Backport v2.8-branch] samples: bluetooth: mesh: dfu: distributor: Fix RTT support

applications/nrf_desktop/doc/hid_forward.rst
Change documents CONFIG_DESKTOP_HID_FORWARD_SUBSCRIBER_COUNT Kconfig option.
Jira: NCSDK-30002
=> applications: nrf_desktop: Update HID forward documentation

applications/nrf_desktop/doc/hid_forward.rst
Backport 825941a0fdcb7850182bf04816523ef1d48ac205 from #18506.
=> [Backport v2.8-branch] applications: nrf_desktop: Update HID forward documentation

doc/nrf/app_dev/device_guides/nrf70/features.rst, doc/nrf/links.txt
Backport 3ed5022dd772a87862f47b9a36168b94a7ccd011 from #18351.
=> [Backport v2.8-branch] doc: nrf: Add a section about hostap

west.yml
Pulls in a fix for decompression
=> [v2.8-branch] manifest: Update sdk-mcuboot

doc/nrf/app_dev/bootloaders_dfu/mcuboot_image_compression.rst
Links to files in the sample rather than the test
=> doc: nrf: app_dev: bootloaders_dfu: Fix compression static PM files

doc/nrf/releases_and_maturity/software_maturity.rst
update software maturity levels for ot and matter
=> doc: update software maturity levels for ot and matter

doc/nrf/releases_and_maturity/software_maturity.rst
Backport 44f3e797687702d3e4771362b49acbfc2048bda8 from #18584.
=> [Backport v2.8-branch] doc: update software maturity levels for ot and matter

west.yml
=> manifest: update sidewalk manifest

samples/bootloader/src/main.c, subsys/bootloader/bl_boot/bl_boot.c
Changing ifdef's for consistency improvement.
This also spares few bytes of flash.
=> bl_boot minor ifdef rework

subsys/net/lib/wifi_credentials/wifi_credentials_shell.c
Modify the arguments expected by MFP configuration in `wifi_cred add` command.
Fixes SHEL-3216.
=> net: lib: wifi_credentials: Change argument type for MFP

subsys/net/lib/wifi_credentials/wifi_credentials_shell.c
Backport 1156b42894b29fb1a73bb30743ebe5c81cbee8a3 from #18549.
=> [Backport v2.8-branch] net: lib: wifi_credentials: Change argument type for MFP

doc/nrf/shortcuts.txt
Backport 6f78a93879b27ba53cc2785ad9a0e6ca416a220b from #18612.
=> [Backport v2.8-branch] doc: zigbee: NCP Host v2.2.4

doc/nrf/app_dev/companion_components.rst, doc/nrf/app_dev/device_guides/nrf54l/features.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf54l/testing_dfu.rst, doc/nrf/app_dev/device_guides/pmic/npm1300.rst, doc/nrf/links.txt, samples/matter/template/README.rst
Updated mcuboot section in features of.
Added link to the nrf54L15 datasheet.
fixed some leftover PDK occurences
=> doc: update mcuboot support info

tests/benchmarks/power_consumption/qdec/boards/nrf54h20dk_nrf54h20_cpuapp.conf, tests/benchmarks/power_consumption/qdec/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/benchmarks/power_consumption/qdec/prj.conf
=> tests: benchmarks: power_consumption: qdec: enable PM_DEVICE

samples/bluetooth/peripheral_power_profiling/Kconfig, samples/bluetooth/peripheral_power_profiling/README.rst, samples/bluetooth/peripheral_power_profiling/src/main.c
Add Kconfig option to disable LEDs for power saving.
=> samples: peripheral_power_profiling: Add Kconfig option to disable LEDs

tests/benchmarks/current_consumption/system_off/testcase.yaml
Different thresholds are needed.
=> tests: benchmarks: current_consumption: system_off: adjust test fun

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/abi_compatibility.rst
=> doc: Updated 54h gs for 2.8

doc/nrf/app_dev/config_and_build/building.rst, doc/nrf/app_dev/config_and_build/cmake/index.rst, doc/nrf/app_dev/config_and_build/config_and_build_system.rst, doc/nrf/app_dev/config_and_build/sysbuild/sysbuild_configuring_west.rst, doc/nrf/installation/install_ncs.rst
Backport 1092cfae057228e591fc0c37a362f0f59ea7e483 from #18319.
=> [Backport v2.8-branch] doc: nrfvsc: edits to general docs

doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
Backport c667bd1969e65dc6261f310947b92cef06bfab00 from #18389.
=> [Backport v2.8-branch] doc: 54H migration guide update

doc/nrf/app_dev/device_guides/nrf70/index.rst, doc/nrf/app_dev/device_guides/nrf70/nrf7002eb_dev_guide.rst, doc/nrf/releases_and_maturity/software_maturity.rst
The shields usage is now updated.
=> doc: nrf70: Fix 54 Series shields

doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_partitioning.rst, doc/nrf/links.txt, scripts/partition_manager/partition_manager.rst
Backport a3a1f4688865addcd3c5104e18b029b99750226e from #18045.
=> [Backport v2.8-branch] doc: bootloader_partitioning: add info about VSC

doc/_zoomin/ncs.tags.yml
Update Zoomin tag file for 2.8
NCSDK-29833
=> doc: update tag file for 2.8

applications/nrf_desktop/configuration/nrf52840dk_nrf52840/prj.conf, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/prj_fast_pair.conf, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/prj_keyboard.conf, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/prj_mcuboot_qspi.conf, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/prj_mcuboot_smp.conf, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/prj_release.conf, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/prj_wwcb.conf, applications/nrf_desktop/configuration/nrf52840gmouse_nrf52840/prj.conf, applications/nrf_desktop/configuration/nrf52840gmouse_nrf52840/prj_fast_pair.conf, applications/nrf_desktop/configuration/nrf52840gmouse_nrf52840/prj_mcuboot_smp.conf, applications/nrf_desktop/configuration/nrf52840gmouse_nrf52840/prj_release.conf, applications/nrf_desktop/configuration/nrf52840gmouse_nrf52840/prj_release_fast_pair.conf, applications/nrf_desktop/doc/hfclk_lock.rst, applications/nrf_desktop/src/modules/Kconfig.hotfixes
PR introduces HF clock hotfix module improvements.
Jira: NCSDK-29545
=> applications: nrf_desktop: HF clock hotfix improvements

doc/nrf/links.txt, samples/bluetooth/nrf_auraconfig/README.rst, samples/bluetooth/nrf_auraconfig/src/main.c
- Add entry in README on how to find pre-encoded lc3-files
- Update filepath for usecases
- OCT-3166
=> samples: nrf_auraconfig: Add link to lc3-files in doc

west.yml
added nRF54l15dk fir zephyr's smp_svr's sample.yaml
=> manifest: zephyr update

doc/nrf/app_dev/device_guides/nrf54l/building_nrf54l.rst, doc/nrf/app_dev/device_guides/nrf54l/vpr_flpr.rst
Added a note on experimental support
=> doc: flpr support note

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_debugging.rst
=> doc: nrf54h20: add description of sdfw bootstatus

doc/nrf/links.txt
- Created a folder in Artifactory so that the link will never change
- OCT-3166
=> samples: nrf_auraconfig: Update link to lc3 data

subsys/mpsl/init/Kconfig, subsys/mpsl/init/mpsl_init.c, west.yml
Update sdk-nrfxlib to integrate PR-1566.
=> Manifest sdk nrfxlib 1566

doc/nrf/app_dev/device_guides/nrf54l/fota_update.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf54l/kmu_provision.rst
Backport 54f8a63b22d4b94398774334aa85ace6a5e20459 from #18231.
=> [Backport v2.8-branch] doc/dev_guides/nrf54l: added fota_update & KMU guides

scripts/quarantine_windows_mac.yaml
there is a problem with nanoPb that needs to be resolved
=> quarantine: wifi provisioning tests on macOS

CODEOWNERS, doc/nrf/libraries/networking/ot_rpc.rst, doc/nrf/links.txt, samples/nrf_rpc/protocols_serialization/client/README.rst, samples/nrf_rpc/protocols_serialization/server/README.rst
Add a documentation page about OpenThread RPC.
=> doc: document OpenThread RPC

samples/nrf_compress/mcuboot_update/src/hook.c
Fixes an issue with combining flags for checking in the slot upload complete hook
=> samples: nrf_compress: mcuboot_update: Fix wrong hook check

doc/nrf/app_dev/device_guides/nrf54l/fota_update.rst
=> doc: small FOTA fixes

doc/nrf/app_dev/device_guides/nrf54l/fota_update.rst
Backport e4172b8cfa50fcd33401147603f7895854e9c135 from #18811.
=> [Backport v2.8-branch] doc: small FOTA fixes

samples/suit/recovery/README.rst, samples/suit/smp_transfer/README.rst
Updated SUIT samples documentation.
=> doc: Updated SUIT samples documentation.

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_dfu.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_smp.rst
=> doc: Added suit and smp doc

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_recovery.rst, samples/suit/recovery/README.rst
Test steps for SUIT recovery sample.
=> doc: samples: suit: Testing Steps for recovery sample

doc/nrf/app_dev/bootloaders_dfu/dfu_tools_mcumgr_cli.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_flpr.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_smp.rst, doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_suit_soc_binaries.rst, doc/nrf/drivers/wifi.rst, doc/nrf/links.txt, doc/nrf/protocols/bt/bt_qualification/index.rst, doc/nrf/protocols/matter/getting_started/memory_optimization.rst, doc/nrf/releases_and_maturity.rst, doc/nrf/releases_and_maturity/known_issues.rst, doc/nrf/releases_and_maturity/migration/migration_guide_1.x_to_2.x.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.4.99-cs3_to_2.6.99-cs2.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.7.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs1.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs2.rst, doc/nrf/releases_and_maturity/migration/migration_hwmv2.rst, doc/nrf/releases_and_maturity/migration/migration_sysbuild.rst, doc/nrf/releases_and_maturity/migration_guides.rst, doc/nrf/releases_and_maturity/release_notes.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.8.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/suit/flash_companion/README.rst
Add release notes for 2.8 release
Minor updates to suit/flash_companion sample.
Minor Updates to nRF54l and nRF54H docs.
=> doc: Add release notes for 2.8 release

doc/nrf/releases_and_maturity/known_issues.rst
=> doc: minor known issues fix

.github/workflows/compliance.yml, .github/workflows/license-reusable.yml
v3 of actions/upload-artifact and
actions/download-artifact becomes obsolete.
=> CI: Upgrade artifact actions

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_custom_pcb.rst
=> doc: Updated 54H custom pcb guide.

scripts/quarantine_zephyr.yaml
=> scripts: quarantine_zephyr: extend for llext for nrf54l15 DK FLPR

west.yml
Call bound_handler after sending init reply.
=> nrf_rpc: pull a fix for initialization order

tests/benchmarks/current_consumption/uart_idle/boards/nrf54l15dk_nrf54l15_cpuapp_uart30.overlay, tests/benchmarks/current_consumption/uart_idle/src/main.c, tests/benchmarks/current_consumption/uart_idle/testcase.yaml
Use UART30 for nrf54l15 and verify the idle current with it
=> tests: benchmarks: Check idle current with uart30 for MLT

west.yml
Update revision for trusted-firmware-m.
=> manifest: Update trusted-firmware-m

samples/peripheral/lpuart/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/peripheral/lpuart/sample.yaml
=> samples: peripheral: lpuart: start measuring current consumption

samples/crypto/ecdsa/boards/nrf5340dk_nrf5340_cpunet.conf, samples/crypto/ecdsa/sample.yaml, samples/crypto/eddsa/boards/nrf5340dk_nrf5340_cpunet.conf, samples/crypto/eddsa/sample.yaml, samples/crypto/sha256/boards/nrf5340dk_nrf5340_cpunet.conf, samples/crypto/sha256/sample.yaml
Test the soft-float+nodsp variant of the Oberon libs
=> samples: crypto: Added limited testing on nRF5340 cpunet

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
Updated regtool requirements for 54H in docs.
=> doc: Updated regtool requirement

doc/_extensions/warnings_filter.py, doc/requirements.txt
Use latest Sphinx 7.x release.
=> doc: requirements: upgrade to Sphinx 7.4 

subsys/net/openthread/Kconfig, subsys/net/openthread/Kconfig.defconfig
Remove types from all existing configs.
=> kconfig: openthread: remove types from existing configs

samples/bluetooth/peripheral_power_profiling/boards/nrf54l15dk_nrf54l15_cpuapp_auto_conn_advert.overlay, samples/bluetooth/peripheral_power_profiling/boards/nrf54l15dk_nrf54l15_cpuapp_auto_non_conn_advert.overlay, samples/bluetooth/peripheral_power_profiling/sample.yaml
Add two test cases that will be used in the automatic power tests
=> tests: samples: automate testing with PPK for peripheral_power_profiling

tests/benchmarks/current_consumption/system_off/CMakeLists.txt, tests/benchmarks/current_consumption/system_off/testcase.yaml
Simple checking current at systemoff state.
=> tests: benchmarks: current_consumption: system_off: extend testing

doc/nrf/app_dev/device_guides/working_with_nrf/nrf54h/ug_nrf54h20_gs.rst
Updated 54h GS requirements to remove CLI tools mention.
=> doc: Updated 54h GS requirements

subsys/mpsl/pin_debug/mpsl_pin_debug_radio_core.c
the fact that this uses toggles sometimes leads to traces that are hard to read and communicate to others because the gpios alternate between "active low" and "active high" at runtime
this is made a bit better by using SET/CLR tasks/subscriptions
=> mpsl: fix pin inversion issues with MPSL_PIN_DEBUG

applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
- Fixes bug where source is deleted before all streams are stopped
- Checks streaming state of all streams in a source before deleting
- OCT-NONE
=> applications: nrf5340_audio: Delete source after all streams stopped

doc/nrf/releases_and_maturity/software_maturity.rst
Added summary table on MCUboot maturity level.
=> doc/nrf/../software_maturity: added mcuboot record

applications/nrf5340_audio/doc/building.rst
- Remove old command for DFU from documentation
- OCT-3245
=> applications: nrf5340_audio: Remove old doc for DFU

tests/benchmarks/multicore/idle_comp/src/main.c
Fix test to reach s2ram by explicit pm_device_runtime_enable/get/put calls.
=> tests: benchmarks: idle: fix pm comp test.

tests/benchmarks/power_consumption/lpcomp/testcase.yaml
Change test fixture to use correct test setup.
=> tests: benchmarks: power_consumption: fix fixture.

doc/nrf/releases_and_maturity/software_maturity.rst
https://nordicsemi.atlassian.net/browse/NCSDK-30597
Update security software maturity tables for nRF54L05 and nRF54L10
=> doc: NCSDK-30597: update software maturity tables with nRF54L05 and nRF54L10

CODEOWNERS
Update codeowners for quick track sample.
=> CODEOWNERS: Add entry for wfa_qt_app sample

scripts/quarantine.yaml
=> twister: Update quarantine with overflowing builds

scripts/quarantine.yaml
=> quarantine: fix platform name

west.yml
Update MCUboot to bring in RAM cleanup option.
=> manifest: Update MCUboot with RAM cleanup option

subsys/logging/log_backend_rpc.c, subsys/logging/log_forwarder_rpc.c
Refactor logging over RPC to use nrf_rpc_serialize.h helpers wherever possible. Also, fix instances of using an incoming packet after calling nrf_rpc_decoding_done(), which releases the packet.
=> logging: rpc: use nrf_rpc_serialize

west.yml
Pull commit with libgcc linking fixes.
=> manifest: Update sdk-sidewalk revision

applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c
Added BASS service data for fixing the IOP issue from phone. OCT-3207
=> applications: nrf5340_audio: Add BASS service data

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Cleaned up changelog for NCS 2.9.99
=> doc: changelog for 2.9.99

doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/app_dev/device_guides/nrf54l/nrf54l_signing_with_payload.rst, doc/nrf/app_dev/device_guides/nrf54l/vpr_flpr.rst
added a new article
reordered the index page
**Changelog entry will be added in the release notes PR after merging**
=> doc: mcuboot signing app with flpr payload

samples/bluetooth/nrf_auraconfig/src/nrf_auraconfig.c
- Fixes bug where data was only sent in the last BIS in a subgroup
- OCT-3251
=> samples: bluetooth: nrf_auraconfig: Fix data in all BISes

tests/bluetooth/tester/src/model_handler.c
Removing the lightness server from the composition. The reasons for doing so; PTS can not chose the correct element to run tests when there are multiple lightness server instances on different elements. There is an element already with a lightness server along with xyL and hsL servers, this element can be used to run all lightness server tests.
=> Bluetooth: Tester: remove unnecessary lightness server from composition

scripts/quarantine_no_optimization.yaml, scripts/quarantine_zephyr.yaml
=> quarantine: new failures on native_sim

samples/bluetooth/nrf_auraconfig/src/nrf_auraconfig.c
Backport b1a108d15e6aecbde5138473a399d6f5ef7fb9c4 from #19322.
=> [Backport v2.9-branch] samples: bluetooth: nrf_auraconfig: Fix data in all BISes

tests/bluetooth/tester/src/model_handler.c
Backport 3d3284b43caa842d73d8f940d3929c185b8832c4 from #19314.
=> [Backport v2.9-branch] Bluetooth: Tester: remove unnecessary lightness server from composition

scripts/quarantine_zephyr.yaml
=> quarantine: update wifi

west.yml
Update sdk-connectedhomeip revision
=> [Backport v2.9-branch] manifest: Update sdk-connectedhomeip revision

doc/nrf/app_dev/create_application.rst, doc/nrf/installation/install_ncs.rst, doc/nrf/test_and_optimize/debugging.rst
Updated documentation pages for the latest changes to the extension. VSC-2735, VSC-2760.
=> doc: wayland: update for the extension release

samples/matter/smoke_co_alarm/src/default_zap/smoke_co_alarm.zap, samples/matter/smoke_co_alarm/src/default_zap/zap-generated/endpoint_config.h
Set Smoke CO Alarm Cluster revision to 1.
=> samples: matter: smoke_co_alarm: Fix cluster revision

doc/nrf/releases_and_maturity/software_maturity.rst
=> doc: fast_pair: Update software maturity tables for NCS 2.9.0

doc/CMakeLists.txt, doc/nrf/conf.py, doc/nrfxlib/conf.py
Fix some issues that made linkcheck unusable.
=> doc: fix linkcheck issues

samples/bluetooth/mesh/ble_peripheral_lbs_coex/prj.conf, samples/bluetooth/mesh/light/overlay-dfu.conf
Increased the number of HCI command buffers for samples with additional SMP services.
One additional buffer per service added.
=> samples: Bluetooth: Mesh: increase HCI cmd buffers

west.yml
Backport 427f16d88dabe8dfc8f46cfab7c15aca7ba367c5 from #19402.
=> [Backport v2.9-branch] manifest: Update soc hwmv1 repo

doc/nrf/releases_and_maturity/software_maturity.rst
Update Sidewalk software maturity tables for nRF54L05 and nRF54L10
=> doc: Update software maturity tables with nRF54L05 and nRF54L10

doc/nrf/app_dev/create_application.rst, doc/nrf/installation/install_ncs.rst, doc/nrf/test_and_optimize/debugging.rst
Backport 22810762ee429fa3d3942c771f8cb3d13dc0b061 from #19076.
=> [Backport v2.9-branch] doc: wayland: update for the extension release

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Backport 93ac7b0d838775b1c16cc0b98b6affcddd0a5cb8 from #19241.
=> [Backport v2.9-branch] doc: changelog for 2.9.99

doc/nrf/releases_and_maturity/software_maturity.rst
nRF54L05 and nRF54L10 are added to the table
=> doc: Bluetooth software maturity level update

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_derivation.c
Adding support for PSA_ALG_HKDF_EXTRACT and PSA_ALG_HKDF_EXPAND for use with key derivation
=> nrf_security: drivers: cracen: Add support for HKDF extract and expand

subsys/bootloader/Kconfig, subsys/bootloader/bl_boot/bl_boot.c, subsys/fw_info/Kconfig, subsys/fw_info/Kconfig.template.fw_info_ext_api
~~Also enables by default on nRF54L15 SoC's~~
NCSDK-29767
=> bootloader: Add support for cleaning up RAM before application boot 

west.yml
=> [Backport v2.9-branch] manifest: Update sdk-find-my revision

doc/nrf/releases_and_maturity/software_maturity.rst
nRF54L05 and rRF54L10 are added to the table.
=> doc: Bluetooth Mesh software maturity level update

doc/nrf/releases_and_maturity/software_maturity.rst
Backport 91bd16d2ea1c2aaca18c97e2bba55d649553b7a9 from #19479.
=> [Backport v2.9-branch] doc: Bluetooth Mesh software maturity level update

doc/nrf/releases_and_maturity/software_maturity.rst
Though these are not supported, explicitly documented as columns like the rest.
=> doc: sml: Add 54L05/10 as unsupported for Wi-Fi

doc/nrf/releases_and_maturity/software_maturity.rst
update for nRF54l05, nRF54l10 and image compression feature
=> doc/software_maturity: update on bootloaders

doc/nrf/releases_and_maturity/software_maturity.rst
Backport 183e513071b2d0400f4dea08746228a155e7a164 from #19486.
=> [Backport v2.9-branch] doc/software_maturity: update on bootloaders

scripts/west_commands/ncs-provision.py
Backport fb67949177ed86969e9229dab5bd397cff141928 from #19421.
=> [Backport v2.9-branch] ncs-provision lock-last policy

applications/sdp/gpio/README.rst, doc/nrf/applications.rst, doc/nrf/includes/sample_board_rows.txt
Add simple readme for SDP GPIO application.
=> applications: sdp: gpio: add README

scripts/quarantine_zephyr.yaml
Temporary, until properly fixed.
=> scripts: quarantine_zephyr: add drivers.spi.pm_runtime

tests/psa_crypto/tests/test_ikg_identity_key_sign_verify.c, tests/psa_crypto/tests/test_ikg_key_derivation.c, tests/psa_crypto/tests/test_kmu_use.c, tests/psa_crypto/tests/test_kmu_write.c
Added tests_ to tests names to fix error in twister
=> tests: psa_crypto: Fixing twister error due to names

doc/nrf/releases_and_maturity/software_maturity.rst
Added record on HW acceleration in MCUboot.
=> doc/../software_maturity: update MCuboot status

west.yml
Update doc and maturity levels in sidewalk for ncs 2.9
=> Sidewalk update

doc/nrf/releases_and_maturity/software_maturity.rst
Backport ca5bdf052dd9745682c3af3568541d23c2f408d4 from #19521.
=> [Backport v2.9-branch] doc/../software_maturity: update MCuboot status

samples/wifi/scan/sample.yaml, samples/wifi/shell/sample.yaml, samples/wifi/sta/sample.yaml
Fix shield support handling for 54 series targets.
=> samples: wifi: Fix 54 series twister definitions

ext/curl/lib/url.h
=> ext: curl: fix compilation with nRF92

doc/nrf/app_dev/device_guides/nrf54l/cryptography.rst, doc/nrf/libraries/security/nrf_security/doc/backend_config.rst
https://nordicsemi.atlassian.net/browse/NCSDK-30162
https://nordicsemi.atlassian.net/browse/NCSDK-30163
Remove mention of SW crypto from 54L intro
Small cleanup of cryptography.rst page
Add anchor for Configuration header
Add note about CRACEN microcode
Add Kconfig option for microcode download
=> doc: Add note about microcode

doc/nrf/links.txt, doc/nrf/releases_and_maturity/known_issues.rst
=> doc: Update known issues for NCS v2.9.0

doc/nrf/links.txt, doc/nrf/releases_and_maturity/known_issues.rst
Backport 517ada704bbf290cfff6ced5cd50aa8c0bd680de from #19231.
=> [Backport v2.9-branch] doc: Update known issues for NCS v2.9.0

doc/nrf/releases_and_maturity/release_notes.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.9.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
=> doc: Update to Changelog and release notes

west.yml
Manifest PR for nrfxlib Update doc versions
=> doc: Manifest PR for nrfxlib Update doc versions

applications/serial_lte_modem/src/slm_at_host.c
Fixes an issue where non-default quit strings, with non-repeating characters, such as "abc" and "aabbcc", did not interpret the start of the quit string properly, if the last characters of the data collided with the quit string start. For example, "*aabc" and "*aaabbcc" with our example quit strings.
=> applications: serial_lte_modem: Fix datamode quit_str handling

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/abi_compatibility.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.9.0-nrf54h20-rc1.rst
Updated H20 GS and ABI comp for 2.9-nRF54H20.
=> doc: Updated H20 GS and ABI comp

.github/workflows/docpublish.yml
Monitor regex was not taking releases into account.
=> ci: docpublish: fix monitor regex

samples/bluetooth/channel_sounding_ras_initiator/src/main.c, subsys/bluetooth/services/ras/rreq/ras_rreq.c, subsys/bluetooth/services/ras/rrsp/ras_rd_buffer.c
=> bluetooth: services: ras: Various fixes/changes

.github/workflows/docbuild.yml, .github/workflows/docpublish.yml
=> Doc fixes for v2.9-nRF54H20

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Fix the target name in release notes.
=> bluetooth: sample: mesh: fix target name in release notes

samples/bluetooth/mesh/light_ctrl/src/model_handler.c, samples/bluetooth/mesh/light_dimmer/src/model_handler.c, samples/bluetooth/mesh/sensor_server/src/model_handler.c
Updating composition data page 2 records with supported latest NLC profile version.
=> samples: bluetooth: mesh: Update NLC profile versions to 1.0.1

samples/crypto/psa_tls/boards/nrf54h20dk_nrf54h20_cpuapp.conf, samples/crypto/psa_tls/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, samples/crypto/psa_tls/boards/nrf54h20dk_nrf54h20_cpurad.conf, samples/crypto/psa_tls/boards/nrf54h20dk_nrf54h20_cpurad.overlay, samples/crypto/psa_tls/sample.yaml
psa_tls sample support for nrf54h20dk/nrf54h20/cpuapp and nrf54h20dk/nrf54h20/cpurad.
test_crypto: PR-724
=> samples: psa_tls: Added support for nrf54h20

scripts/quarantine.yaml
=> quarantine: update

.github/workflows/enforce-toolchain-synchronization.yml
Backport ef172cdb46c29326938e19c3f7cd99f5af3187e4 from #19648.
=> [Backport v2.9-nRF54H20] actions: Skip toolchain check on branch creation

west.yml
=> manifest: Bring upstream l15 support

doc/nrf/app_dev/device_guides/fem/fem_nrf21540_gpio.rst, doc/nrf/app_dev/device_guides/fem/fem_nrf21540_gpio_spi.rst
NCSDK-31153
TECHDOC-3263
TECHDOC-3247
=> doc: Doc fixes for the FEM docs

tests/benchmarks/multicore/idle_clock_control/Kconfig.sysbuild, tests/benchmarks/multicore/idle_clock_control/src/main.c, tests/benchmarks/multicore/idle_clock_control/sysbuild/nrf54h20dk_nrf54h20_cpurad.conf, tests/benchmarks/multicore/idle_clock_control/testcase.yaml
Perform tests with additional clock devices
=> tests: benchmarks: Increase coverage for Clock Control

applications/matter_bridge/src/app_task.cpp, applications/matter_weather_station/src/app_task.cpp, samples/matter/light_bulb/src/app_task.cpp, samples/matter/light_switch/src/app_task.cpp, samples/matter/lock/src/app_task.cpp, samples/matter/smoke_co_alarm/src/app_task.cpp, samples/matter/template/src/app_task.cpp, samples/matter/thermostat/src/app_task.cpp, samples/matter/window_covering/src/app_task.cpp
=> samples: matter: Remove unused includes

.github/workflows/docbuild.yml, .github/workflows/oss-history.yml, west.yml
See changelog for additional details.
=> manifest: Update nrfxlib with SoftDevice Controller fixes

.github/workflows/enforce-toolchain-synchronization.yml
Backport 1c2673ac4d90f5fce13eb433686dd3e52ae42cd7 from #19842.
=> [Backport v2.9-nRF54H20-branch] actions: Limit Toolchain Sync execution

doc/nrf/app_dev/device_guides/thingy91/thingy91_building_programming.rst, doc/nrf/app_dev/device_guides/thingy91x/thingy91x_building_programming.rst
Updated build file name on Thingy:91 and 91 X docs 
app_signed.hex - > zephyr.signed.hex
=> doc: Update build file name on Thingy:91 and 91 X docs

west.yml
Manifest update check for oberon psa crypto
test_crypto: PR-726
=> manifest: update oberon psa crypto revision

west.yml
sdk-zephyr: [nrf fromlist] tests: drivers: uart: async_api: Add nrf54h20 cpuppr
=> manifest: Update sdk-zephyr revision (auto-manifest PR)

west.yml
Update sdk-nrfxlib and dragoon revision
=> [Backport v2.9-nRF54H20-branch] manifest: update sdk-nrfxlib revision

west.yml
Manifest PR for backport of
[nrf fromlist] drivers: pwm: fixes for fast PWM120
https://github.com/nrfconnect/sdk-zephyr/pull/2424
=> manifest: [nrf fromlist] drivers: pwm: fixes for fast PWM120

doc/nrf/releases_and_maturity/known_issues.rst, samples/matter/smoke_co_alarm/README.rst
Added two new known issues and fix to the smoke co alarm readme.
=> doc: Added known issues related to Matter

scripts/quarantine.yaml
Regression after find-my update.
=> scripts: quarantine: add sample.find_my.switchable_networks

.github/workflows/docbuild.yml, .github/workflows/docpublish.yml, .github/workflows/docremove.yml, doc/CMakeLists.txt
Old server is no longer available, plus some fixes are needed for the CI jobs to run.
=> ci: docs: v2.6-branch: fixes for doc uploads

doc/nrf/releases_and_maturity/known_issues.rst
* Add known issue for WiFi reconnection after RPU recovery.
* Add known issue for failing RPU recovery in Matter samples.
=> doc: Add known issues related to Matter

.github/workflows/docbuild.yml
Backport d9500b94b05c776294fda96ebb0baaedb553a47e from #19674.
=> [Backport v2.8-branch] ci: fix docbuild for ubuntu 24.04

scripts/quarantine.yaml
Quarantine drivers.sdp_asm.basic
=> scripts: quarantine: add drivers.sdp_asm.basic

west.yml
Manifest PR for backport of
[nrf fromlist] arch: riscv: option to init custom hw stacked esf memb
=> manifest: update zephyr revision, fix VPR esr init

.github/workflows/docbuild.yml
Backport d9500b94b05c776294fda96ebb0baaedb553a47e from #19674.
=> [Backport v2.9-branch] ci: fix docbuild for ubuntu 24.04

.github/test-spec.yml
Samples tested by thingy91 plan:
- samples/net/https_client
- samples/net/coap_client
- samples/net/download
- samples/net/http_server
- samples/net/mqtt
=> test-spec: Update thingy91

drivers/flash/flash_ipuc/flash_ipuc.c, scripts/quarantine.yaml
Fix warnings in flash_ipuc tests.
=> suit: Fix warnings in flash_ipuc tests

scripts/quarantine.yaml, scripts/quarantine_windows_mac.yaml
=> scripts: quarantine: extend for openthread, coremark and matter_bridge

samples/nrf5340/empty_app_core/sample.yaml, samples/nrf5340/empty_net_core/sample.yaml, samples/nrf5340/extxip_smp_svr/sample.yaml, samples/nrf5340/netboot/sample.yaml, samples/nrf5340/remote_shell/sample.yaml, scripts/ci/tags.yaml
=> samples: nrf5340: add ci tag ci_samples_nrf5340

scripts/ci/tags_sdk_zephyr.yaml, scripts/quarantine_zephyr_integration.yaml
=> scripts: ci: tags_sdk_zephyr: extend tags

subsys/net/lib/downloader/src/transports/http.c, subsys/net/lib/fota_download/src/util/fota_download_util.c, tests/subsys/net/lib/downloader/src/main.c
net: lib: downloader: Allow redirect to HTTPS from HTTP
Separate URI parsing and protocol detection to its own
function and when receiving the "Location: <URI>" header,
parse the URI again, so the next connection will use the
correct protocol and port.
Do not convert all HTTP headers to lowercase as URI
is case-sensitive. Convert just the header names, not values
after the first colon.
Then, on a FOTA util, just deliver the sec_tag always. The downloader already has a logic to detect if the sec_tag needs to be set or not.
=> net: lib: downloader: Allow redirect to HTTPS from HTTP

applications/matter_weather_station/README.rst
Restructured the doc to align it with the
application template.
ref: NCSDK-19501
=> doc: Matter weather station app restructure

subsys/nrf_security/src/psa_crypto_driver_wrappers.c
Fix missing KMU switch cases in the driver wrapper
=> nrf_security: Fix KMU singlepart cipher issues

CODEOWNERS, doc/nrf/links.txt, doc/nrf/protocols/bt/bt_mesh/overview/index.rst
Adds list of supported features to overview page to clarify exactly what is supported (and not supported) by NCS.
=> Doc: Bluetooth: Mesh: Add feature list

applications/nrf_desktop/bootloader_dfu.rst, doc/nrf/includes/suit_fota_update_nrfcdm_test_steps.txt, samples/bluetooth/fast_pair/locator_tag/README.rst
Backport 470ff085003af81802286858ee3b18bf1f62b17d~3..470ff085003af81802286858ee3b18bf1f62b17d from #19557.
=> [Backport v2.9-nRF54H20-branch] SUIT FOTA updates section

doc/nrf/app_dev/create_application.rst
Fixed the reference to wrong step.
NCSDK-31697.
=> doc: create_application: fix step mismatch

subsys/suit/mci/src/suit_mci_nrf9280.c
=> suit: Fix include in nRF9280 MCI

west.yml
Pull implementation of '-x' flag in `tcp` command
=> manifest: openthread: update revision

CODEOWNERS
Added codeowner for the GNSS sample.
=> CODEOWNERS: Add codeowner for the GNSS sample

scripts/quarantine.yaml
=> quarantine: Add quarantine for SUIT ble samples

scripts/quarantine.yaml
sample.bluetooth.peripheral_uart
=> scripts: quarantine: add sample.bluetooth.peripheral_uart

doc/nrf/releases_and_maturity/known_issues.rst
Updated to the v2-9-0-nRF54H20-rc1 tag for a Known issue from v2-9-0-nRF54H20-1.
=> doc: Updated to the v2-9-0-nRF54H20-rc1 tag for a Known issue

scripts/ci/tags.yaml, scripts/twister/alt/zephyr/samples/basic/blinky/sample.yaml, scripts/twister/alt/zephyr/tests/drivers/mspi/api/testcase.yaml, tests/drivers/gpio/egpio_basic_api/testcase.yaml, tests/drivers/gpio/egpio_more_loops/testcase.yaml, tests/drivers/sdp_asm/testcase.yaml
SDP related files should be included in a common tag.
=> scripts: ci: update tag for SDP

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Updated changelog for 2.9.0-nRF54H20-1 release.
=> doc: Updated changelog for 2.9.0-nRF54H20-1

samples/ipc/ipc_service/boards/nrf5340dk_nrf5340_cpuapp_icbmsg.conf, samples/ipc/ipc_service/boards/nrf5340dk_nrf5340_cpuapp_icbmsg.overlay, samples/ipc/ipc_service/remote/boards/nrf5340dk_nrf5340_cpunet_icbmsg.conf, samples/ipc/ipc_service/remote/boards/nrf5340dk_nrf5340_cpunet_icbmsg.overlay, samples/ipc/ipc_service/sample.yaml
Add ICBMsg configuration for nRF5340DK board.
JIRA: NCSDK-31711
=> samples: ipc: ipc_service: Add ICBMsg configuration

CODEOWNERS, scripts/generate_psa_key_attributes.py
This python script is used to generate json files that contain key data and metadata that is used by nrfutil provisioning keys into nrf54h and nrf54l devices.
=> [Backport v2.9-nRF54H20-branch] scripts: generator script for key provisioning json files

doc/nrf/releases_and_maturity/known_issues.rst
Added v2-9-0-nRF54H20 to known issues.
=> doc: Update known issues for 2.9.0-nRF54H20

doc/nrf/releases_and_maturity/known_issues.rst
Added v2-9-0-nRF54H20 to known issues.
=> [Backport] Update known issues for 2.9.0-nRF54H20

samples/esb/esb_prx/src/main.c, samples/esb/esb_ptx/src/main.c
Fixed data corruption issue in 4Mbit radio mode on nRF54H20 SoC.
=> samples: esb: Fix corrupted transmitted data in 4Mbit radio mode

subsys/suit/memory_layout/src/suit_memory_layout.c
Needed for writing to radio TCM.
=> suit: Allow RAM sink to write to radio memory

tests/benchmarks/current_consumption/system_off/boards/nrf54l15dk_nrf54l15_cpuapp_lpcomp_wakeup.overlay, tests/benchmarks/current_consumption/system_off/testcase.yaml
Add configuration with lpcomp wakeup.
=> tests: benchmarks: current_consumption: systemoff

west.yml
Updating sdk-nrfxlib with new softdevice controller
Updating to https://github.com/nrfconnect/sdk-nrfxlib/pull/1642
=> manifest: Update sdk-nrfxlib revision v2.9-branch

scripts/quarantine_zephyr.yaml
Fix the comment and move it it from won't fix section.
=> quaratine_zephyr: Fix the mesh zephyr sample entry

doc/nrf/app_dev/device_guides/wifi_coex.rst
Improved the wording of steps and converted one
numbered list to a bullet list.
=> doc improvement: minor fixes in the Wi-Fi coex page

doc/nrf/links.txt, doc/nrf/protocols/lte/index.rst
=> doc: Minor fixes to the LTE guide

.github/workflows/docpreview.yml
Otherwise finding the existing comment fails.
=> ci: docpreview: fix body-includes parameter

tests/drivers/uart/uart_baudrate_test/src/main.c
Used gpio measurement method is not fast enought for faster baudrates.
=> tests: drivers: uart: uart_baudrate_test: skip for fast baudrates

samples/cellular/modem_shell/src/link/link_api.c
Commit 8caef9d caused regression when printing LTE cell information during network search. This PR reverts the original functionality in `link_api_xmonitor_read()` and instead removes an error log which was printed when `link_api_xmonitor_read()` returned an error. It's simpler to let `link_api_xmonitor_read()` fail if cell ID and TAC can not be parsed.
=> samples: cellular: modem_shell: Fix LTE cell printing during search

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Restore on main branch changelog entries from 54h-1 branch.
=> doc: restore changelog entries from -1 branch

samples/bluetooth/direct_test_mode/src/transport/dtm_uart_twowire.c
Fix CTE setting in uart mode, which causes
code not to be executed.
Jira: NCSDK-27142
=> samples: dtm: Fix cte set causing dead core

scripts/ci/tags.yaml
=> scripts: ci: tags: update deps for ci_samples_openthread

doc/nrf/app_dev/device_guides/nrf54l/kmu_provision.rst
Updated KMU provisioning documentation for updated west ncs-provision script.
=> doc: ncs-provision: Update documentation for west KMU provisioning

.github/workflows/ai-reviewer.yml
It connets with GPT, reviews commits in PR
and post comments as NordicBuilder user.
=> CI: Add AI as PR reviewer

doc/nrf/external_comp/bt_fast_pair.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Documentation for features introduced in the following PR:
https://github.com/nrfconnect/sdk-nrf/pull/20402
=> Fast Pair firmware update intents

boards/shields/coverage_support/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, boards/shields/coverage_support/boards/nrf54h20dk_nrf54h20_cpurad.overlay
=> boards: shields: coverage_support: align memory for h20

cmake/modules/kconfig.cmake, cmake/sysbuild/modules/ncs_sysbuild_extensions.cmake
Add a flag to allow for customizing the variant application Kconfig values.
Ref: NCSDK-30812
=> sysbuild: Add flag to customize variant app config

applications/nrf_desktop/src/events/hid_event.c
Change fixes profiling description of hid_report_subscriber_event.
Jira: NCSDK-31712
=> applications: nrf_desktop: Fix hid_report_subscriber_event profiling

boards/shields/coverage_support/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, boards/shields/coverage_support/boards/nrf54h20dk_nrf54h20_cpurad.overlay
Add more FLASH for app (taken from rad).
Disable SDFW_SERVICES to save RAM.
=> boards: shields: coverage_support: extend app flash and disable SSF

tests/drivers/spi/spi_controller_peripheral/boards/nrf54l09pdk_nrf54l09_cpuapp.overlay, tests/drivers/spi/spi_controller_peripheral/testcase.yaml, tests/drivers/spi/spi_error_cases/boards/nrf54l09pdk_nrf54l09_cpuapp.overlay, tests/drivers/spi/spi_error_cases/testcase.yaml
Extends testing SPI on nrf54l09pdk using console-switching snippet.
=> tests: drivers: spi: Extend testing on nrf54l09pdk

subsys/mgmt/suitfu/src/suitfu_mgmt.c, subsys/sdfw_services/services/suit_service/suit_ipuc.c, subsys/suit/orchestrator_app/src/suit_orchestrator_app.c
=> suit: Logs correction

tests/benchmarks/multicore/idle_uarte/testcase.yaml
Fix missing message in coverage mode.
=> tests: benchmarks: multicore: idle_uarte: fix coverage after rework

scripts/quarantine_integration.yaml
Updated Find My quarantine entries to match new sample names. Added nRF54L based board targets to limit resources usage in integration builds.
Jira: NCSDK-30308
=> scripts: quarantine_integration: Update Find My and add nRF54L targets

doc/nrf/releases_and_maturity/known_issues.rst
Add known issue for problem with loading persisitent storage in Matter samples.
=> doc: Add known issue for KRKNWK-20035

subsys/suit/cache/src/suit_dfu_cache_helpers.c
The IPUC cache was being searched for URI-s before it has been initialized (before the first pull into the IPUC).
This led to issues - if only some images were already fetched and the update was interrupted, the suit-processor would detect they are already present in the cache. However, when pulling the first missing image, the IPUC cache with the detected images was erased leading to update failure.
=> suit: Workaround for IPUC caches search before initialization

west.yml
update to include fll16m remove closed loop backport
=> manifest: update to include fll16m backport

scripts/west_commands/ncs_provision.py
User should be able to upload public key to KMU using private or public PEM file.
=> scripts: ncs-provision: Allow to upload keys to KMU from public key file

doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-2.9.1.rst
Update highlights for the 2.9.1 release notes.
=> doc: Update highlights for the 2.9.1 release notes

subsys/partition_manager/Kconfig
=> partition_manager: kconfig: Fix typo

doc/nrf/includes/advanced_conf_matter.txt, samples/matter/light_bulb/README.rst, samples/matter/light_switch/README.rst, samples/matter/lock/README.rst, samples/matter/smoke_co_alarm/README.rst, samples/matter/template/README.rst, samples/matter/thermostat/README.rst, samples/matter/window_covering/README.rst
Collecting common advanced configuration methods
in Matter samples under one title and using toggle.
=> doc: Matter samples reorganization

applications/sdp/mspi/src/main.c, drivers/mspi/mspi_nrfe.c
Protection against incorrect device config parameters.
=> drivers: sdp: mspi: incorrect parameters protection

subsys/nrf_rpc/nrf_rpc_uart.c
Improve and unify debug logs for nRF RPC UART transport:
1. Use the same convention for sent and received frames:
```
>>> RX packet 539e
04 00 ff 02 ff 00 6c 6f  67                      |......lo g
<<< TX ack 539e
...
<<< TX packet 64a1
04 00 ff 03 03 00 6d 70  73 6c 5f 63 78          |......mp sl_cx
>>> RX ack 64a1
```
Make sure that checksums are added to all these messages to easily match packets with ACKs. Also, do not use hexdump for ACKs to keep the logs more concise.
2. Make sure checksums are padded to 4 characters.
3. Remove some irrelevant logs.
=> nrf_rpc_uart: improve and unify logs

include/bluetooth/services/ras.h, subsys/bluetooth/services/ras/rreq/ras_rreq.c
Fixes some issues with the step parser.
=> bluetooth: services: Fix ras rreq parse function

doc/nrf/security/tfm/tfm.rst
Added information about TF-M minimal build features in its section. NCSDK-28042.
=> doc: tfm: mention minimal build features

drivers/wifi/nrf700x/src/fmac_main.c, west.yml
Fixes a leak in regulatory processing.
=> wifi: Fix memleak in regulatory processing

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/pmic/native/npm2100_one_button/CMakeLists.txt, samples/pmic/native/npm2100_one_button/README.rst, samples/pmic/native/npm2100_one_button/boards/npm2100_pmic.dtsi, samples/pmic/native/npm2100_one_button/boards/nrf52840dk_nrf52840.overlay, samples/pmic/native/npm2100_one_button/boards/nrf5340dk_nrf5340_cpuapp.overlay, samples/pmic/native/npm2100_one_button/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/pmic/native/npm2100_one_button/prj.conf, samples/pmic/native/npm2100_one_button/sample.yaml, samples/pmic/native/npm2100_one_button/src/main.c
nPM2100 sample application demostrating power mode control and user interractions through a single button connected the PMIC.
=> samples: pmic: npm2100_one_button

.github/workflows/validate-pip-requirements-fixed-file.yml
Use Ubuntu 24.04 in GH actions
=> ci: Use Ubuntu 24.04 in GH actions

subsys/bluetooth/services/ras/rrsp/ras_rd_buffer.c
When the ranging counter wrapped, alloc() would fail due to not finding that the buffer with ranging counter 65535 could be freed.
To ensure the buffer selected to be freed is always the oldest, a new approach is used. It's based on how many counts have elapsed relative to the counter we are trying to allocate.
=> bluetooth: services: Fix RAS ring buffer alloc overflow issue

doc/nrf/samples.rst
Fix the sample order in the sample listing
=> doc: Fix sample listing

applications/sdp/mspi/src/main.c, drivers/mspi/mspi_nrfe.c
=> Tx max frequency

.github/workflows/docpreview.yml, .github/workflows/docpublish.yml
Backport 3e3b689a6dffdf867f61f9d2bc438bf7e5eb7de7~2..3e3b689a6dffdf867f61f9d2bc438bf7e5eb7de7 from #20463.
=> [Backport v2.9-nRF54H20-branch] ci: docs: add preview links

.github/workflows/docpreview.yml
Backport 7807cfafb34f7de9eb20d20448d2c48379477044 from #20514.
=> [Backport v2.9-nRF54H20-branch] ci: docpreview: fix body-includes parameter

subsys/bluetooth/mesh/CMakeLists.txt, subsys/bluetooth/mesh/Kconfig, subsys/bluetooth/mesh/key_importer.c
Commit adds functionality that reads the stored tinycrypt keys from settings and import them as persistent keys into PSA crypto library.
=> Bluetooth: Mesh: add tc to psa key converter

west.yml
tests: drivers: audio: dmic_api: Enable test execution on nrf54l15
https://github.com/nrfconnect/sdk-zephyr/pull/2325
https://github.com/zephyrproject-rtos/zephyr/pull/82436
=> manifest: Enable DMIC test on nrf54l15

.github/test-spec.yml
Do not run downstream jobs if only VERSION or .rst files changed
=> test-spec: Do not run downstream jobs if only VERSION or .rst files changed

samples/bluetooth/direct_test_mode/src/transport/dtm_uart_twowire.c
Fix a bug where setting upper bits will cause subsequent vendor specific packets to fail due to length being wrongly modified.
=> samples: dtm: Avoid adding upper bits to length for vendor specific packets

west.yml
Combo manifest update for sdk-zephyr.
=> manifest: Update sdk-zephyr with latest  cherry-picks

applications/nrf_desktop/pytest/test_mcuboot_kmu.py
With the current MCUboot implementation the board must be programmed again, because MCUboot erases application image if running before KMU is provisioned.
Jira: NCSDK-31976
=> applications: nrf_desktop: Fix MCUboot KMU pytest

scripts/quarantine.yaml
quarantine suit-platform.integration.fetch
=> scripts: quarantine: add suit-platform.integration.fetch

doc/nrf/installation/install_ncs.rst, doc/nrf/installation/recommended_versions.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Replaced toolchain-manager commands with corresponding sdk-manager ones. NRFU-1453.
=> doc: install: sdk-manager commands

doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-1.3.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-1.6.0.rst
Removed links and the last ref
=> doc: zigbee doc removal cleanup

subsys/nrf_security/src/drivers/cracen/silexpk/target/baremetal_ba414e_with_ik/pk_baremetal.c, subsys/nrf_security/src/drivers/cracen/silexpk/target/hw/ik/ikhardware.c
Add workaround to handle freezing issue on cracen light devices
Ref DLT-4048
=> nrf_security: drivers: cracen: Add workaround for ikg issues on 54l

doc/nrf/protocols/matter/getting_started/low_power_configuration.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added piece of documentation explaining how to
configure the radio driver calibration period.
=> doc: matter: Extended low power documentation

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
=> doc: Fixes to the changelog

samples/bluetooth/channel_sounding_ras_initiator/src/distance_estimation.c
replaced get_antenna_path() with bt_le_cs_get_antenna_path()
=> samples: bluetooth: use Zephyr function to get antenna path in CS sample

applications/nrf_desktop/bluetooth.rst, applications/nrf_desktop/bootloader_dfu.rst, applications/nrf_desktop/memory_layout.rst, doc/nrf/releases_and_maturity/software_maturity.rst
Changes align documentation with code.
Jira: NCSDK-30908
=> applications: nrf_desktop: Small documentation alignments

applications/serial_lte_modem/doc/CMUX_AT_commands.rst, applications/serial_lte_modem/doc/PPP_linux.rst
Add documentation regarding CONFIG_MODEM_CMUX_MTU.
=> applications: serial_lte_modem: Clarify CMUX MTU documentation

applications/serial_lte_modem/scripts/slm_start_ppp.sh, applications/serial_lte_modem/scripts/slm_stop_ppp.sh
Add parameter for defining serial port and baud rate for PPP start up script.
=> applications: serial_lte_modem: Add serial parameter for script

scripts/ci/tags.yaml
=> scripts: ci: tags: extend matter dep for mcuboot

west.yml
Pull in the Mbed TLS 3.6.3 version.
=> manifest: update Mbed TLS to 3.6.3

samples/wifi/sta/README.rst
Updated the nrf7002 current consumption in idle mode to ~15uA
SHEL-3427
=> samples: wifi: sta: Update nrf7002 current consumption

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_dfu.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_signing.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added documentation how to enable Secure Boot on the nRF54H devices using SUIT + how to sign the envelopes.
=> doc: suit: Added documentation for signing envelopes

west.yml
=> Revert "manifest: sdk-nrfxlib: Update MPSL and SoftDevice Controller"

doc/nrfxlib/conf.py
=> doc: add tabs extension nrfxlib

applications/sdp/mspi/src/hrt/hrt-nrf54l15.s, applications/sdp/mspi/src/hrt/hrt.c
=> Flash unaligned address test fix

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/esb/esb_prx/boards/nrf54h20dk_nrf54h20_cpurad.overlay, samples/esb/esb_ptx/boards/nrf54h20dk_nrf54h20_cpurad.overlay, subsys/esb/esb.c
Added workaround implementations for HMPAN-216.
=> esb: Implement workaround for HMPAN-216

doc/nrf/includes/zigbee_deprecation.txt, doc/nrf/links.txt, doc/nrf/protocols/amazon_sidewalk/index.rst, doc/nrf/samples/amazon_sidewalk.rst, doc/nrf/samples/zigbee.rst
added add-on latest links to both protocols.
=> doc: add zigbee and sidewalk links

west.yml
=> manifest: mcuboot key revocation

lib/bin/lwm2m_carrier/os/lwm2m_shell.c
Make the response for some event log and app data shell commands clearer.
=> lib: bin: lwm2m_carrier: Improve shell response for app data commands

.github/workflows/docpreview.yml, .github/workflows/docpublish.yml
Backport 3e3b689a6dffdf867f61f9d2bc438bf7e5eb7de7~2..3e3b689a6dffdf867f61f9d2bc438bf7e5eb7de7 from #20463.
=> [Backport v2.9-branch] ci: docs: add preview links

west.yml
Reverts nrfconnect/sdk-nrf#14394
=> Revert "manifest: update sdk-mcuboot: brings improved UARTE clean-up"

subsys/suit/stream/stream_sinks/src/suit_ram_sink.c
Ensure that all writes to the RAM sink are flushed from the cache.
Ref: NCSDK-31308
=> suit: FIX: Add cache mgmt in ram_sink

doc/_utils/utils.py
=> doc: utils: TF-M main page should be wrapper

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
=> doc: Clean changelog on 3.0.0 RC1

Jenkinsfile, test-manifests/99-default-test-nrf.yml
Use CI_LIB and test-nrf from v3.0-branch
=> ci: Use CI_LIB and test-nrf from v3.0-branch

subsys/sdfw_services/services/psa_crypto/psa_crypto_service.cddl
Fixed format of psa_crypto_req union.
=> sdfw_services: psa_crypto: Fix cddl

applications/serial_lte_modem/doc/slm_data_mode.rst, applications/serial_lte_modem/doc/slm_description.rst, applications/serial_lte_modem/doc/slm_testing.rst
Corrections to SLM documentation.
=> applications: serial_lte_modem: Documentation corrections

subsys/caf/modules/buttons.c
GPIO API does not allow for setting GPIOs from ISR context. The call has been moved to system workqueue context to fix the issue.
Jira: NCSDK-32667
=> caf: buttons: Fix incorrect GPIO API usage

doc/nrf/app_dev/device_guides/nrf70/fw_patches_ext_flash.rst
Backport 2cb7a3a9b65b49dae7213ea6e3142bc4c01e87c8~2..2cb7a3a9b65b49dae7213ea6e3142bc4c01e87c8 from #21376.
=> [Backport v3.0-branch] Update ext flash via SPI docs

samples/net/aws_iot/sample.yaml, samples/net/coap_client/sample.yaml, samples/net/download/sample.yaml, samples/net/https_client/sample.yaml, samples/net/mqtt/sample.yaml, samples/net/udp/sample.yaml, samples/wifi/offloaded_raw_tx/sample.yaml, samples/wifi/provisioning/ble/sample.yaml, samples/wifi/radio_test/multi_domain/sample.yaml, samples/wifi/radio_test/single_domain/sample.yaml, samples/wifi/raw_tx_packet/sample.yaml, samples/wifi/scan/sample.yaml, samples/wifi/shell/sample.yaml, samples/wifi/shutdown/sample.yaml, samples/wifi/softap/sample.yaml, samples/wifi/sta/sample.yaml, samples/wifi/twt/sample.yaml
Add nrf7002eb II support for Wi-Fi and Networking samples.
=> samples: Add nrf7002EB II support

applications/sdp/mspi/src/main.c
Added define for assert argument.
=> applications: sdp: mspi: Mode 3 assert fix

applications/serial_lte_modem/doc/slm_data_mode.rst, applications/serial_lte_modem/doc/slm_description.rst, applications/serial_lte_modem/doc/slm_testing.rst
Backport 3b8d8682f51788684e9cd782a9ffd35fb08351af from #21309.
=> [Backport v3.0-branch] applications: serial_lte_modem: Documentation corrections

doc/nrf/releases_and_maturity/software_maturity.rst
Add nPM2100 PMIC to "Power management device support" table.
=> doc: Add nPM2100 to PMIC software maturity doc

doc/nrf/protocols/wifi/debugging.rst
Backport 6a43d7f748944c8434fb2b9f3285ae209145cb8d~3..6a43d7f748944c8434fb2b9f3285ae209145cb8d from #21404.
=> [Backport v3.0-branch] doc: wifi: Improve debugging

samples/peripheral/lpuart/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.conf, samples/peripheral/lpuart/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay, samples/peripheral/lpuart/boards/nrf54lv10apdk_nrf54lv10a_cpuapp.conf, samples/peripheral/lpuart/boards/nrf54lv10apdk_nrf54lv10a_cpuapp.overlay, samples/peripheral/lpuart/sample.yaml, tests/drivers/lpuart/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.conf, tests/drivers/lpuart/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay, tests/drivers/lpuart/boards/nrf54lv10apdk_nrf54lv10a_cpuapp.conf, tests/drivers/lpuart/boards/nrf54lv10apdk_nrf54lv10a_cpuapp.overlay, tests/drivers/lpuart/testcase.yaml, tests/drivers/uart/uart_baudrate_test/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_uart00.overlay, tests/drivers/uart/uart_baudrate_test/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_uart21.overlay, tests/drivers/uart/uart_baudrate_test/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_uart22.overlay, tests/drivers/uart/uart_baudrate_test/boards/nrf54lv10apdk_nrf54lv10a_cpuapp_uart21.overlay, tests/drivers/uart/uart_baudrate_test/testcase.yaml, tests/zephyr/drivers/uart/uart_elementary/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay, tests/zephyr/drivers/uart/uart_elementary/boards/nrf54lm20apdk_nrf54lm20a_dual_uart.overlay, tests/zephyr/drivers/uart/uart_elementary/boards/nrf54lv10apdk_nrf54lv10a_cpuapp.overlay, tests/zephyr/drivers/uart/uart_elementary/boards/nrf54lv10apdk_nrf54lv10a_dual_uart.overlay, tests/zephyr/drivers/uart/uart_elementary/testcase.yaml, tests/zephyr/drivers/uart/uart_mix_fifo_poll/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay, tests/zephyr/drivers/uart/uart_mix_fifo_poll/boards/nrf54lv10apdk_nrf54lv10a_cpuapp.overlay, tests/zephyr/drivers/uart/uart_mix_fifo_poll/testcase.yaml, tests/zephyr/drivers/uart/uart_pm/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay, tests/zephyr/drivers/uart/uart_pm/boards/nrf54lv10apdk_nrf54lv10a_cpuapp.overlay, tests/zephyr/drivers/uart/uart_pm/testcase.yaml
Tests and samples for uart for L20 and L09.
=> tests: drivers: uart: enable testing for LM20 and LV10

samples/bluetooth/fast_pair/locator_tag/README.rst
Updates the DFU signature type table.
Jira: NCSDK-32692
=> doc: samples: fast_pair: locator_tag: Update the DFU signature type

applications/machine_learning/configuration/nrf54h20dk_nrf54h20_cpuapp/prj.conf, applications/machine_learning/configuration/nrf54h20dk_nrf54h20_cpuapp/prj_singlecore.conf
Change buranrgstorageacc to publicburan as the first one was deactivated some time ago.
JIRA: NCSDK-32853
=> applications: machine_learning: configuration: Update EI URI

modules/openthread/platform/crypto_psa.c
There was an issue with toPsaAlgorithm function. It should return PSA_ALG_DETERMINISTIC_ECDSA fwhile PSA ITS crypto backed is selected.
Fixes KRKNWK-20187
=> modules: openthread: Fix migration from MbedTLS to PSA

applications/sdp/mspi/src/main.c
Backport 7e8adf4c10644bd26366b8421aeae90dfbf441ba from #21414.
=> [Backport v3.0-branch] applications: sdp: mspi: Mode 3 assert fix

boards/nordic/nrf54lm20apdk/board.yml, boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.yaml, boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a_cpuapp_0_1_0.overlay, boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a_cpuapp_0_1_0.yaml, dts/common/nordic/nrf54lm20a.dtsi
Add new revision of the board. Add overlay with changed locations of LED and buttons.
=> boards: nordic: nrf54lm20apdk: Add 0.1.0 board revision

doc/nrf/releases_and_maturity/software_maturity.rst
* Update shields to EB2 only
* Update samples for54L
=> wifi: SML update mainly for 54H and 54L

applications/nrf5340_audio/doc/feature_support.rst, doc/nrf/links.txt
=> applications: nrf5340_audio: Updated QDID info

cmake/extensions.cmake, cmake/partition_manager.cmake, cmake/sysbuild/partition_manager.cmake
Removes a parameter that was removed from this function
=> cmake: extension: Remove BUILD from ncs_file() function

modules/openthread/platform/crypto_psa.c
Backport 99c26927b0ae7c6617b250036d15b9566ac3e601 from #21475.
=> [Backport v3.0-branch] modules: openthread: Fix migration from MbedTLS to PSA

doc/nrf/releases_and_maturity/software_maturity.rst
Backport ebf5aad6adaa003970af75d2fd2c8dbc80f7bfe7 from #21416.
=> [Backport v3.0-branch] doc: Add nPM2100 to PMIC software maturity doc

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_configuration.rst
Updated nrf54h20 configuration docs
=> doc: updated nRF54H20 configuration docs

applications/nrf5340_audio/src/bluetooth/bt_management/dfu/bt_mgmt_dfu.c
- OCT-3327
- In DFU mode, the device may stop advertising. Added adv restart
=> applications: nrf5340_audio: Added back adv start on DFU

doc/nrf/releases_and_maturity/software_maturity.rst
Production support for Bluetooth on nRF54H20
=> doc: Bluetooth maturity on nRF54H20

doc/nrf/releases_and_maturity/software_maturity.rst
Backport 858c8b02d2e477356dacd0a2a399c495c757477b~2..858c8b02d2e477356dacd0a2a399c495c757477b from #21485.
=> [Backport v3.0-branch] wifi: SML update mainly for 54H and 54L

doc/nrf/releases_and_maturity/software_maturity.rst
Backport 6669e31dbb1037f2e6a9c0e23cebe1c4edfb0491 from #21542.
=> [Backport v3.0-branch] doc: Bluetooth maturity on nRF54H20

doc/nrf/libraries/bluetooth/services/wifi_prov.rst
Backport d2bf2bdc12ded98b83c03af0dced143241846588 from #21261.
=> [Backport v3.0-branch] doc: bluetooth: services: wifi_prov: document provisioning protocol

samples/crypto/aes_gcm/sample.yaml, samples/crypto/sha256/sample.yaml, west.yml
https://github.com/nrfconnect/sdk-nrf/pull/21413
=> backport 21413 to v3.0-branch

applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c
- Set frame length no higher than what the capabilities support
- Use BAP preset if value is supported
- Use max frame len supported by unicast server below preset
- OCT-3349
=> applications: nrf5340_audio: Set sdu size according to cap

doc/nrf/security/tfm/tfm_supported_services.rst
Backport 2dd27d4878e7a7b81b88be832e46409b0ccbea10 from #21581.
=> [Backport v3.0-branch] doc: security: updated tfm limitations

include/tfm/ironside/se/ipc_service.h, samples/crypto/aes_gcm/boards/nrf54h20dk_nrf54h20_cpuapp_iron.conf, samples/crypto/aes_gcm/boards/nrf54h20dk_nrf54h20_cpuapp_iron.overlay, samples/crypto/ecdh/boards/nrf54h20dk_nrf54h20_cpuapp_iron.conf, samples/crypto/ecdh/boards/nrf54h20dk_nrf54h20_cpuapp_iron.overlay, samples/crypto/ecdsa/boards/nrf54h20dk_nrf54h20_cpuapp_iron.conf, samples/crypto/ecdsa/boards/nrf54h20dk_nrf54h20_cpuapp_iron.overlay, samples/crypto/rng/boards/nrf54h20dk_nrf54h20_cpuapp_iron.conf, samples/crypto/rng/boards/nrf54h20dk_nrf54h20_cpuapp_iron.overlay, samples/crypto/sha256/boards/nrf54h20dk_nrf54h20_cpuapp_iron.conf, samples/crypto/sha256/boards/nrf54h20dk_nrf54h20_cpuapp_iron.overlay, subsys/nrf_security/Kconfig, subsys/nrf_security/src/ssf_secdom/CMakeLists.txt, subsys/nrf_security/src/ssf_secdom/Kconfig, subsys/nrf_security/src/ssf_secdom/bounce_buffers.c, subsys/nrf_security/src/ssf_secdom/bounce_buffers.h, subsys/nrf_security/src/ssf_secdom/ironside_se_psa_ns_api.c, subsys/nrf_security/src/ssf_secdom/ironside_se_psa_ns_ipc.c, subsys/nrf_security/src/ssf_secdom/ironside_se_psa_ns_ipc.h, subsys/nrf_security/src/ssf_secdom/psa_manifest/sid.h, subsys/sdfw_services/Kconfig, subsys/sdfw_services/services/Kconfig.template.service
Provide support for PSA crypto services based on ironside SE.
Ref: NCSDK-32163
=> nrf_security: 54h20: ironside SE PSA Crypto support

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
Fix bug where export_ecc_public_key_from_keypair would return early
=> nrf_security: cracen: IKG export public key fails

applications/sdp/mspi/src/hrt/hrt-nrf54l15.s, applications/sdp/mspi/src/hrt/hrt.c
Fix for RX data when command, address and dummy are set to 0.
=> applications: hpf: mspi: fix for rx

doc/nrf/libraries/caf/power_manager.rst, subsys/caf/modules/Kconfig.power_manager
Change updates module documentation to align it with implementation. Change includes informing about power_off_event handling.
Jira: NCSDK-31742
=> caf: power_manager: Update documentation

west.yml
To bring the newest changes - adding an error message if too large sequence number
=> Backport: manifest: Update suit-generator revision

tests/benchmarks/multicore/common/remote_gdf_switching/src/main.c
=> tests: benchmarks: multicore: common: remote_gdf_switching: fix sync

west.yml
Manual manifest update to 3.0 branch for PR1718
=> doc: Manual manifest update for PR1718

drivers/flash/Kconfig, drivers/flash/flash_ipuc/flash_ipuc.c, subsys/suit/cache/Kconfig, subsys/suit/cache/src/suit_dfu_cache_helpers.c, subsys/suit/cache/src/suit_dfu_cache_internal.h, subsys/suit/cache/src/suit_dfu_cache_rw.c
To meet the minimal requirements.
=> NCSDK-32779: Improve cache performance

doc/nrf/app_dev/config_and_build/building.rst, doc/nrf/app_dev/config_and_build/sysbuild/sysbuild_images.rst, doc/nrf/app_dev/create_application.rst, doc/nrf/includes/vsc_build_and_run_series.txt, doc/nrf/installation/install_ncs.rst, doc/nrf/installation/updating.rst, doc/nrf/links.txt
Updated documentation for the changes in the VSC extension NCS 3.0.0 release. VSC-2894.
----
To be merged after the extension release.
=> doc: update for VSC extension release

applications/sdp/mspi/src/hrt/hrt-nrf54l15.s, applications/sdp/mspi/src/hrt/hrt.c
Backport 1f8c87193bc9006d5d69c1c030a1152539f35a3b from #21645.
=> [Backport v3.0-branch] applications: hpf: mspi: fix for rx

tests/benchmarks/multicore/common/remote_gdf_switching/src/main.c
Backport bfadf4b8f8b5fd1ac5738e29b1d441e5853f6b12 from #21693.
=> [Backport v3.0-branch] tests: benchmarks: multicore: common: remote_gdf_switching: fix sync

doc/nrf/releases_and_maturity/software_maturity.rst
Backport 94f5b7cca86192aa80d4a56cd0e6e8e8ac64325f from #21698.
=> [Backport v3.0-branch] doc: Update TF-M and PSA Crypto maturity sections

drivers/flash/Kconfig, drivers/flash/flash_ipuc/flash_ipuc.c, subsys/suit/cache/Kconfig, subsys/suit/cache/src/suit_dfu_cache_helpers.c, subsys/suit/cache/src/suit_dfu_cache_internal.h, subsys/suit/cache/src/suit_dfu_cache_rw.c
Backport a956b5da259369e8e1f81e4e9f7a0d5590a3f174~4..a956b5da259369e8e1f81e4e9f7a0d5590a3f174 from #21527.
=> [Backport v3.0-branch] NCSDK-32779: Improve cache performance

scripts/west_commands/create_board/templates/nrf54l/Kconfig.defconfig.jinja2, scripts/west_commands/create_board/templates/nrf54l/board.cmake.jinja2
Otherwise defconfig was not applied correctly.
=> west_commands: create_board: fix nrf54l Kconfig.defconfig

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c
Add fix for ikg verify failing
This was due to not correctly generating a public key
test_crypto: PR-791
=> nrf_security: cracen: fix ikg verify bug

tests/zephyr/drivers/spi/spi_controller_peripheral/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay, tests/zephyr/drivers/spi/spi_controller_peripheral/testcase.yaml, tests/zephyr/drivers/spi/spi_error_cases/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay, tests/zephyr/drivers/spi/spi_error_cases/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay, tests/zephyr/drivers/spi/spi_loopback/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay, tests/zephyr/drivers/spi/spi_loopback/testcase.yaml
=> tests: zephyr: drivers: spi: add LM20 DK support

tests/drivers/uart/uart_baudrate_test/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_uart21.overlay, tests/drivers/uart/uart_baudrate_test/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_uart22.overlay, tests/drivers/uart/uart_baudrate_test/testcase.yaml, tests/zephyr/drivers/uart/uart_async_api/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay, tests/zephyr/drivers/uart/uart_async_api/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay, tests/zephyr/drivers/uart/uart_async_api/testcase.yaml, tests/zephyr/drivers/uart/uart_elementary/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay, tests/zephyr/drivers/uart/uart_elementary/boards/nrf54lm20apdk_nrf54lm20a_dual_uart_0_0_0.overlay, tests/zephyr/drivers/uart/uart_elementary/testcase.yaml, tests/zephyr/drivers/uart/uart_errors/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay, tests/zephyr/drivers/uart/uart_errors/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay, tests/zephyr/drivers/uart/uart_errors/testcase.yaml, tests/zephyr/drivers/uart/uart_mix_fifo_poll/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay, tests/zephyr/drivers/uart/uart_mix_fifo_poll/testcase.yaml, tests/zephyr/drivers/uart/uart_pm/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay, tests/zephyr/drivers/uart/uart_pm/testcase.yaml
=> tests: zephyr: drivers: uart: enable for LM20 DK

samples/zephyr/drivers/i2c/rtio_loopback/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay, samples/zephyr/drivers/i2c/rtio_loopback/sample.yaml, tests/zephyr/boards/nrf/i2c/i2c_slave/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay, tests/zephyr/boards/nrf/i2c/i2c_slave/testcase.yaml, tests/zephyr/drivers/i2c/i2c_target_api/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay, tests/zephyr/drivers/i2c/i2c_target_api/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay, tests/zephyr/drivers/i2c/i2c_target_api/testcase.yaml
=> tests: zephyr: drivers: i2c: enable for LM20 DK

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c
Backport 3a28acce4a6b4e86e190061a50d29a76717adf42 from #21726.
=> [Backport v3.0-branch] nrf_security: cracen: fix ikg verify bug

doc/nrf/app_dev/device_guides/nrf54l/index.rst
=> doc: add nrf54l15 supported dk revisions

doc/nrf/libraries/security/trusted_storage.rst, doc/nrf/protocols/bt/bt_mesh/configuring.rst, doc/nrf/protocols/matter/end_product/security.rst, doc/nrf/security/trusted_storage.rst
Backport cc410fb280327ad98e1b55e17f317e5cfcd82eda from #21398.
=> [Backport v3.0-branch] Bluetooth: Mesh: Docs: add info about trusted storage

doc/nrf/libraries/caf/power_manager.rst, subsys/caf/modules/Kconfig.power_manager
Backport 41ff01d95c3059a534ab94b110879805d3b2c7dc from #21524.
=> [Backport v3.0-branch] caf: power_manager: Update documentation

applications/machine_learning/configuration/nrf54h20dk_nrf54h20_cpuapp/prj.conf, applications/machine_learning/configuration/nrf54h20dk_nrf54h20_cpuapp/prj_singlecore.conf
Backport c50cc549e4575f0210ffff0eae921baaf96cae1b from #21423.
=> [Backport v3.0-branch] applications: machine_learning: configuration: Update EI URI

doc/nrf/app_dev/config_and_build/building.rst, doc/nrf/app_dev/config_and_build/sysbuild/sysbuild_images.rst, doc/nrf/app_dev/create_application.rst, doc/nrf/includes/vsc_build_and_run_series.txt, doc/nrf/installation/install_ncs.rst, doc/nrf/installation/updating.rst, doc/nrf/links.txt
Backport 49c263509c740cbb3769ab9f08929adc9814ed6a from #21537.
=> [Backport v3.0-branch] doc: update for VSC extension release

doc/nrf/app_dev/device_guides/thingy91x/thingy91x_updating_fw_programmer.rst
Backport 66cc61d3670a22f6b406855d960fc6f6af179e29 from #21761.
=> [Backport v3.0-branch] doc improvement: Update to Thingy91X modem programing command

samples/zephyr/drivers/counter/alarm/sample.yaml, tests/zephyr/drivers/counter/counter_basic_api/testcase.yaml
=> tests: zephyr: drivers: counter: enable for LM20 DK

tests/zephyr/drivers/clock_control/clock_control_api/testcase.yaml, tests/zephyr/drivers/clock_control/nrf_clock_calibration/testcase.yaml, tests/zephyr/drivers/clock_control/nrf_lf_clock_start/testcase.yaml, tests/zephyr/drivers/clock_control/onoff/testcase.yaml
=> tests: zephyr: drivers: clock_control: enable for LM20 DK

west.yml
Pull changes from nrfconnect/sdk-connectedhomeip#590
=> [Backport v3.0-branch] manifest: sdk-connectedhomeip: Update revision

samples/zephyr/drivers/adc/adc_dt/sample.yaml, samples/zephyr/drivers/adc/adc_sequence/sample.yaml, tests/zephyr/drivers/adc/adc_accuracy_test/testcase.yaml, tests/zephyr/drivers/adc/adc_api/testcase.yaml, tests/zephyr/drivers/adc/adc_error_cases/testcase.yaml
=> tests: zephyr: drivers: adc: enable for LM20 DK

samples/crypto/sha256/sample.yaml
Test nrf54h20dk/nrf54h20/cpuapp/iron.
=> samples: crypto: Test nrf54h20dk/nrf54h20/cpuapp/iron

doc/nrf/protocols/matter/getting_started/custom_clusters.rst, doc/nrf/protocols/matter/getting_started/manufacturer_cluster_editor_tool.rst
Fixing the GUI element spelling and other minor fixes.
=> doc improvement: Fixes in the Matter cluster docs

scripts/quarantine_llvm.yaml
Add quarantine file used during twister tests built using llvm compiler
=> test: Add quarantine file for llvm compiler

samples/peripheral/lpuart/README.rst
=> samples: peripheral: lpuart: remove old board names

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
Backport 3ba1eb50cd182861d97e6ecd63560398cf879662 from #21359.
=> [Backport v3.0-branch] nrf_security: cracen: IKG export public key fails

scripts/quarantine_llvm.yaml
Backport 63dc325ad7570354faa06dace9589c7dba0af820 from #21815.
=> [Backport v3.0-branch] test: Add quarantine file for llvm compiler

doc/nrf/libraries/networking/aws_iot.rst
Backport db7fe7d074d3e88a44cffe3b430736f0e4b3b3d7 from #21836.
=> [Backport v3.0-branch] doc: nrf: net: aws_iot: Clarify the step

west.yml
Updated Find My revision to include the Find My changes required for the v3.0.0-rc2 tag.
Ref: NCSDK-32032
=> sdk-find-my update for 3.0.0-rc2

doc/nrf/protocols/wifi/stack_configuration.rst
With latest heap size change, Add Throughputs for usage profiles.
=> doc: wifi: Add Usage profiles Throughputs

scripts/docker/Dockerfile
Update nrfutil device to version 2.8.8
=> docker: Update nrfutil device to 2.8.8

west.yml
update nrfxlib and dragoon revision for v3.0.0 release
=> manifest: update nrfxlib and dragoon revision

applications/nrf_desktop/Kconfig.ble
Backport 2aad7c1c93a32fd44637a538574f22e0492f22e8 from #21825.
=> [Backport v3.0-branch] applications: nrf_desktop: Imply CONFIG_BT_CONN_TX_NOTIFY_WQ

.github/test-spec.yml
Do not run twister on docker changes
=> ci: Do not run twister on docker changes

boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a_cpuapp_0_2_0.overlay
=> boards: nordic: nrf54lm20apdk: fix reserved gpios at port1

boards/nordic/nrf54lm20apdk/nrf54lm20a_cpuapp_common.dtsi, boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a-pinctrl.dtsi
Added flash memory node under spi00 peripheral.
=> boards: nrf54lm20apdk: add flash memory node

doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_signature_keys.rst
Fix a tab rendering.
commit already in backport PR: #21857
=> doc/nrf/bootloader_siganture_key: fix tab

doc/nrf/releases_and_maturity/software_maturity.rst
Backport 39aedcab5cff73a7756f731892d7c86fe4206380 from #21772.
=> [Backport v3.0-branch] doc: sml: fast_pair: update for NCS v3.0.0

west.yml
Updated sdk-find-my revision to bring backport of Apple Find My add-on release notes for NCS 3.0 (https://github.com/nrfconnect/sdk-nrf/pull/21918).
=> [Backport v3.0-branch] manifest: Update sdk-find-my revision

doc/nrf/releases_and_maturity/software_maturity.rst
Recorded:
* NSIB as experimental for nRF54Ll SoCs.
* MCUboot multiple key management.
* Experimental maturity of MCUboot encryption.
=> doc/software_maturity: NSIB and MCUboot updates

doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/links.txt
This is essentially a backport of PR#21872.
=> doc: add links to comp matrices from nRF54L doc

west.yml
Pull in fix for version mismatch warning during build.
=> (3.0) manifest: tf-m: pull in version warning fix

doc/nrf/releases_and_maturity/software_maturity.rst
Backport f0819976b508dd5a9f60acd511752ce1ef1db355 from #21835.
=> [Backport v3.0-branch] doc/software_maturity: NSIB and MCUboot updates

tests/zephyr/drivers/spi/spi_loopback/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_spi00.overlay, tests/zephyr/drivers/spi/spi_loopback/testcase.yaml
=> tests: zephyr: drivers: spi: spi_loopback: check spi00 at LM20 DK

.github/workflows/docremove.yml
Use the same triggering as is in docbuild side.
=> ci: run docremove for PRs targeting release branches

samples/zephyr/sensor/accel_polling/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_2_0.overlay, samples/zephyr/sensor/accel_polling/sample.yaml, samples/zephyr/sensor/bme680/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_2_0.overlay, samples/zephyr/sensor/bme680/sample.yaml
=> samples: zephyr: sensor: accel_polling and bme680 at LM20 DK

subsys/nrf_security/src/drivers/cracen/cracenpsa/cracenpsa.cmake, subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_montgomery.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/montgomery.c
Add support for Montgomery public keys in cracen_psa Remove support for sicrypto Montgomery in key_management.c
=> nrf_security: cracen: Support montgomery curves in cracen_psa

modules/openthread/platform/ble.c
Commit add tcat related function implementation
=> net: openthread: Add tcat platform function implementation

samples/nrf_rpc/protocols_serialization/client/src/ot_shell.c, subsys/net/openthread/rpc/client/ot_rpc_netdiag.c
This commit fixes a few build warnings related to unused variables.
=> samples: nrf_rps: ps_client: fix warnings

subsys/nrf_security/include/crypto_spe.h, west.yml
Update TF-M to 2.1.2, from 2.1.1.
=> manifest: update TF-M to 2.1.2

west.yml
Pull in fix for version mismatch warning during build.
=> (2.9) manifest: tf-m: pull in version warning fix

doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/known_issues.rst
Backport 5a2969489673ee39b4b288d62f1a1db14b905af5 from #21388.
=> [Backport v3.0-branch] doc: Update known issues for NCS v3.0.0

.github/workflows/compliance.yml
Files.nordicsemi.com doesnt allow downloading just header
=> ci: fix link check for files.nordicsemi.com

doc/nrf/libraries/bluetooth/services/rreq.rst, doc/nrf/libraries/bluetooth/services/rrsp.rst, include/bluetooth/services/ras.h, samples/bluetooth/channel_sounding_ras_initiator/src/main.c, subsys/bluetooth/services/ras/ras_internal.h, subsys/bluetooth/services/ras/rreq/ras_rreq.c, subsys/bluetooth/services/ras/rrsp/ras_rd_buffer.c, subsys/bluetooth/services/ras/rrsp/ras_rrsp.c
=> bluetooth: services: Implement real-time ranging data service

west.yml
Update tf-m-tests to 2.1.2.
test_tfm: PR-196
=> manifest: sdk-zephyr: pull in updated tf-m-tests repo

west.yml
Pull changes from nrfconnect/sdk-connectedhomeip#591
=> [Backport v2.9-branch] manifest: sdk-connectedhomeip: Update revision

west.yml
=> manifest: sdk-mcuboot 54l15 key revocation fix 

applications/nrf5340_audio/broadcast_source/main.c, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c, applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
- OCT-3345
- Added more info when a broadcaster/Auracast is started
=> applications: nrf5340_audio: Broadcaster, added print info

doc/nrf/releases_and_maturity/software_maturity.rst
=> doc: Minor updates to SML page

doc/nrf/protocols/matter/getting_started/custom_clusters.rst
Update custom cluster documentation after data model changes.
=> doc: samples: matter: Update custom cluster CMake configuration changes

west.yml
Update nrfxlib and dragoon revision
=> [Backport v3.0-branch] manifest: update nrfxlib and dragoon revision

scripts/docker/Dockerfile
Update tools used in docker image
=> docker: Update tools used in docker image

doc/nrf/releases_and_maturity/known_issues.rst
=> doc/known_issues: updates on NCSDK-33207, NCSDK-33163

doc/nrf/releases_and_maturity/known_issues.rst
=> doc: wifi: update known known_issues

subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c, tests/subsys/net/lib/nrf_provisioning/src/coap.c
Free results from zsock_getaddrinfo().
=> net: nrf_provisioning: Fix memory leak

scripts/quarantine_integration.yaml
Added selected Find My Switchable Network sample build configs to quarantine to limit resources usage in integration builds.
Jira: NCSDK-32140
=> scripts: quarantine_integration: Add Find My Switchable Network entries

subsys/net/openthread/rpc/server/ot_rpc_cli.c
When "factoryreset" shell command is received over RPC, send a response to the caller before executing the command, because the factory reset automatically reboots the board, which makes the caller wait for the response indefinitely.
=> net: openthread: rpc: prevent factory reset from hanging

doc/nrf/links.txt, doc/nrf/protocols/amazon_sidewalk/index.rst
Added a github repository link.
Updated information.
=> doc: small Sidewalk page fix

doc/nrf/releases_and_maturity/known_issues.rst
Updated affected platforms for CIA-351
on the Known issues page.
=> doc: Known issues - Update platforms for CIA-351

CODEOWNERS, doc/nrf/drivers/mspi_sqspi.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add a few words about the purpose of the driver and how to configure it, along with examples of dts overlays for supported SoCs.
=> doc: nrf: drivers: Add documentation for sQSPI MSPI shim driver

subsys/mpsl/fem/nrf2220/mpsl_fem_nrf2220.c
When asserts are turned off, the function
fem_temperature_sensor_value_get provides now a valid default temperature when value can't be obtained from a temperature sensor.
=> mpsl: nrf2220: provide default temp when sensor value can't be obtained

doc/nrf/libraries/bluetooth/mesh/sensor.rst
Fixed a numbered list gone wrong.
Also a few other minor language fixes.
=> doc: fixes to Bluetooth Mesh sensors

doc/nrf/includes/sample_board_rows.txt, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/peripheral/radio_test/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.conf, samples/peripheral/radio_test/sample.yaml
Add support for nRF54LM20PDK in DTM sample
=> samples: radio_test: Add support for nRF54LM20PDK

tests/drivers/lpuart/src/main.c
RX BUF should be released after UART disable call.
=> tests: drivers: lpuart: Verify RX BUF release after UART disable

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add note about fixed issue in nrf_provisioning library for v2.9.0-branch
https://github.com/nrfconnect/sdk-nrf/pull/22174
=> doc: Update changelog for v2.9.0-branch

subsys/debug/coredump/coredump_backend_nrf_flash_partition.c
Using even the minimal RRAM write buffer reduces the core dump collection time by an order of magnitude - from >200 ms to >20 ms in the case of 4kB dump.
=> debug: coredump: use RRAM write buffer

boards/nordic/nrf54lm20pdk/board.yml, boards/nordic/nrf54lm20pdk/revision.cmake
Set default board version to 0.2.0.
=> boards: nordic: Set default version of nRF54LM20PDK board to newest one

west.yml
Update nrfxlib and dragoon revision for v2.9 bugfix release
=> [Backport v2.9-branch] Update nrfxlib and dragoon revision

samples/cellular/nrf_cloud_multi_service/overlay_coap.conf, samples/cellular/nrf_cloud_multi_service/overlay_min_coap.conf, samples/cellular/nrf_cloud_multi_service/overlay_nrf700x_wifi_coap_no_lte.conf
This PR aligns to what is required for transition from newlib to picolib
JIRA: IRIS-10147
=> samples: cellular: mss: Remove newlib references

CODEOWNERS
Updated codeowners with new doc group.
=> doc: add new doc group

applications/nrf_desktop/description.rst
Change fixes an application-specific Kconfig reference in the documentation.
=> applications: nrf_desktop: Fix app-specific Kconfig ref in doc

doc/nrf/nrf.doxyfile.in
Parallel threads base on system capabilites.
=> doc: nrf: nrf.doxyfile.in: allow doxygen to run in parallel

subsys/net/lib/nrf70_fw_ext/ext_fw_load.c
Anomaly 159 keeps appearing, we had disabled the warnings/workaround for non-XIP case but for XIP it still happens silently, so, downgrade the CPU frequency before XIP to avoid Anomaly 159 and once FW download is completed (XIP is done) then restore the CPU frequency.
Fix SHEL-3596.
=> net: lib: nrf70_fw_ext: Fix XIP anomaly 159

scripts/quarantine_zephyr.yaml
Tests reports RAM overflow issue.
=> quarantine_zephyr: Add quarantine for libraries.encoding.json

scripts/quarantine.yaml
=> scripts: quarantine: add sample.qspi.ext_flash_xip

doc/nrf/applications.rst
Mention add-ons on the application page.
=> doc: Mention add-ons on the application page

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/net/lib/nrf_cloud/coap/src/coap_codec.c
Replace returning positive ZCBOR errors for negative errno.h errors
Jira: IRIS-9368
=> net: lib: nrf_cloud: coap: Convert ZCBOR errors to errno.h errors

.github/test-spec.yml, scripts/ci/tags.yaml, scripts/quarantine.yaml, subsys/net/lib/nrf70_fw_ext/ext_fw_load.c
* Fix XIP build error for nRF52
* Fix test spec for wifi
=> Fix 52840 xip twister

subsys/bluetooth/mesh/Kconfig
Commit adds more mbedtls heap for dfu distributor role.
=> bluetooth: mesh: add more mbedtls heap for dfu distributor

applications/serial_lte_modem/overlay-ppp-cmux-linux.conf, applications/serial_lte_modem/src/slm_cmux.c, applications/serial_lte_modem/src/slm_ppp.c
PPP recv buf must be aligned to word.
=> applications: serial_lte_modem: Fix PPP recv buf align

lib/modem_slm/modem_slm.c
Added shell command "indicate" for enabling and disabling indicate callback. This is useful when testing how indications behave when application doesn't request them. Hence, app doesn't wake up UARTs and you can test how SLM behaves in this case.
Jira: LRCS-191
=> lib: modem_slm: Shell command for enable/disable indicate callback

samples/crypto/aes_gcm/sample.yaml, samples/crypto/ecdh/sample.yaml, samples/crypto/ecdsa/sample.yaml, samples/crypto/rng/sample.yaml
Add the iron variant to more crypto samples.
=> samples: crypto: Add the iron variant to more crypto samples

tests/benchmarks/multicore/idle_spim_loopback/src/main.c
Add test case for Fast SPIM slower on v2.9.0-nRF54H20-1 than on v2.8.0
=> tests: benchmarks: multicore: idle_spim_loopback

tests/drivers/gpio/gpio_nfct/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/drivers/gpio/gpio_nfct/boards/nrf54h20dk_nrf54h20_cpurad.overlay
Align to changes made in
https://github.com/zephyrproject-rtos/zephyr/pull/86280
=> tests: drivers: gpio: gpio_nfct: Fix nrf54h20dk overlay

.github/workflows/docker.yml
Push images with toolchain bundle id tag
=> docker: Push images with toolchain bundle id tag

scripts/quarantine.yaml
=> scripts: quarantine: add nrf5340_audio tests

boards/nordic/nrf54lv10dk/Kconfig.defconfig, boards/nordic/nrf54lv10dk/Kconfig.nrf54lv10dk, boards/nordic/nrf54lv10dk/board.cmake, boards/nordic/nrf54lv10dk/board.yml, boards/nordic/nrf54lv10dk/nrf54lv10a_cpuapp_common.dtsi, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a-common.dtsi, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a-pinctrl.dtsi, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a_cpuapp.dts, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a_cpuapp.yaml, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a_cpuapp_0_0_0.yaml, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a_cpuapp_0_2_0.overlay, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a_cpuapp_0_2_0.yaml, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a_cpuapp_defconfig, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a_cpuflpr_0_0_0.yaml, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a_cpuflpr_0_2_0.overlay, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a_cpuflpr_0_2_0.yaml, dts/common/nordic/nrf54lv10a.dtsi
Added 0.2.0 revision for nRF54LV10 DK.
=> boards: nordic: nrf54lv10dk: add revision 0.2.0

scripts/ci/tags.yaml
Add nrf/include/audio_defines.h
=> scripts: ci: tags: extend audio tests deps

applications/nrf5340_audio/src/modules/hw_codec.c
- Create shell command for selecting what channel to output in I2S
- OCT-3284
=> applications: nrf5340_audio: Add shell cmd for i2s output

tests/subsys/kmu/hello_for_kmu/testcase.yaml, tests/subsys/kmu/revoke/boards/nrf54lv10dk_nrf54lv10a_cpuapp.conf, tests/subsys/kmu/revoke/testcase.yaml, tests/subsys/kmu/verify_west_ncs_provision/testcase.yaml
=> tests: subsys: kmu: enable testing at LV10

boards/nordic/nrf54lm20pdk/board.yml, boards/nordic/nrf54lm20pdk/revision.cmake
Change default revision to 0.2.0.csp.
=> boards: nordic: Change default revision of the nRF54LM20 PDK

doc/nrf/external_comp/bt_fast_pair.rst, doc/nrf/releases_and_maturity/software_maturity.rst, samples/bluetooth/fast_pair/input_device/README.rst, samples/bluetooth/fast_pair/locator_tag/README.rst
SML table enhancement
Add tabs for different device Series.
=> doc: SML table enhancement

samples/bluetooth/central_hids/sample.yaml, samples/bluetooth/central_uart/sample.yaml, samples/bluetooth/peripheral_hids_keyboard/sample.yaml, samples/bluetooth/peripheral_hids_mouse/sample.yaml, samples/bluetooth/peripheral_lbs/sample.yaml, samples/bluetooth/peripheral_uart/sample.yaml
Allow automatic verification if samples boots-up and starts ble.
=> samples: bluetooth: basic console check for selected samples

scripts/ci/tags.yaml
Fix the missing samples directory.
=> ci: Fix Wi-Fi samples tag

samples/openthread/coprocessor/sample.yaml
Add `coprocessor_` before `SNIPPET`.
=> samples: openthread: coprocessor: Fix snippets in samples.yaml

boards/nordic/nrf54lm20pdk/nrf54lm20pdk_nrf54lm20a_cpuapp_0_2_0.overlay, boards/nordic/nrf54lm20pdk/nrf54lm20pdk_nrf54lm20a_cpuapp_0_2_0_csp.overlay
=> boards: nordic: nrf54lm20pdk: state uart20 and uart30 pins

scripts/quarantine.yaml
=> scripts: quarantine: add i2s tests for audiopll at h20

CODEOWNERS, boards/nordic/thingy91x/CMakeLists.txt, boards/nordic/thingy91x/sysbuild.cmake, boards/nordic/thingy91x/thingy91x_nrf5340_pm_static_ext_flash.yml, boards/nordic/thingy91x/thingy91x_nrf5340_pm_static_ext_flash_no_tfm.yml, boards/nordic/thingy91x/thingy91x_nrf5340_pm_static_no_tfm.yml, boards/nordic/thingy91x/thingy91x_nrf9151_pm_static_no_ext_flash.yml, boards/nordic/thingy91x/thingy91x_nrf9151_pm_static_no_ext_flash_no_tfm.yml, boards/nordic/thingy91x/thingy91x_nrf9151_pm_static_no_tfm.yml, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
* add special use partition tables
* make sure the correct partition table is selected for each variant
=> boards: thingy91x: partitions rework

applications/serial_lte_modem/src/slm_at_socket.c
Change the active socket to pointer in preparation for the polling changes.
Edit: Added another commit to combine sends to satisfy sonarcloud.
=> applications: serial_lte_modem: sock to pointer

applications/nrf5340_audio/src/audio/audio_system.c, applications/nrf5340_audio/src/audio/le_audio_rx.c, applications/nrf5340_audio/src/modules/audio_usb.c
- Fix bug where we only sent audio from second device connected.
- OCT-3397
=> applications: nrf5340_audio: Fix USB bidir

applications/connectivity_bridge/sample.yaml, applications/hpf/gpio/sample.yaml, applications/hpf/mspi/sample.yaml, applications/nrf5340_audio/sample.yaml, applications/serial_lte_modem/sample.yaml, scripts/ci/tags.yaml
Adding tags for applications, so that they will not be build if their dependencies were not changed.
=> More ci tags

applications/matter_weather_station/src/default_zap/weather-station.zap, applications/matter_weather_station/src/default_zap/zap-generated/endpoint_config.h
Enable mandatory attribute EndpointList in PowerSource.
=> applications: fix matter weather station's zap file

samples/matter/template/sample.yaml
Increase the coverage of validation the matter sample with legacy zms.
=> samples: matter: enable configuration with legacy zms

applications/nrf_desktop/src/modules/hids.c, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Use common callback functions for HID reports.
Jira: NCSDK-33592
=> applications: nrf_desktop: use common callbacks in hids

applications/serial_lte_modem/src/slm_at_tcp_proxy.c
Handle simultaneous TCP receive and disconnect, drain all TCP RX data on modem side before handling POLLHUP.
JIRA SLM-99
=> application: serial_lte_modem: TCP receive and disconnect

applications/nrf_desktop/doc/hid_eventq.rst, applications/nrf_desktop/doc/hid_state.rst, applications/nrf_desktop/utils.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
PR introduces documentation for HID eventq utility. PR also updates HID state module documentation to inform about HID eventq utility integration.
Jira: NCSDK-33578
=> applications: nrf_desktop: Document HID eventq utility

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cracen_mac_cmac.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cracen_mac_cmac.h, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/mac.c, subsys/nrf_security/src/psa_crypto_driver_wrappers.c
=> nrf_security: drivers: cracen: fix CMAC operations on 54LM20A

applications/serial_lte_modem/doc/SOCKET_AT_commands.rst, applications/serial_lte_modem/prj.conf, applications/serial_lte_modem/src/slm_at_host.c, applications/serial_lte_modem/src/slm_at_host.h, applications/serial_lte_modem/src/slm_at_socket.c, applications/serial_lte_modem/src/slm_at_socket.h, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add asynchronous polling with AT#XAPOLL.
=> applications_serial_lte_modem: Add AT#XAPOLL

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cipher.c
Add singlepart support for cbc pkcs7 in cracen
=> nrf_security: cracen: add singlepart support for cbc pkcs7

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/peripheral/802154_phy_test/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.conf, samples/peripheral/802154_phy_test/sample.yaml
Enable 802154_phy_test sample for nRF54LM20.
=> samples: peripherals: 802154_phy_test: Add support for nRF54LM20

samples/zephyr/smp_svr_mini_boot/sample.yaml, scripts/ci/tags.yaml
ci_samples_zephyr_smp_svr_mini_boot
=> samples: zephyr: smp_svr_mini_boot: add ci tag

doc/nrf/app_dev/device_guides/nrf54l/dfu_config.rst, doc/nrf/app_dev/device_guides/nrf54l/index.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
adds a new page on supported features.
=> doc: DFU support and recommendations nRF54L

samples/zephyr/boards/nordic/system_off/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay
=> samples: zephyr: boards: nordic: system_off: align memory regions

doc/nrf/app_dev/device_guides/fem/fem_nrf21540_gpio.rst, doc/nrf/app_dev/device_guides/fem/fem_nrf21540_gpio_spi.rst, doc/nrf/app_dev/device_guides/fem/index.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
The doc regarding nRF21540 GPIO/SPI for nRF54L is udpated.
=> doc: fem: update nRF21540 GPIO/SPI doc for nrf54L

applications/serial_lte_modem/CMakeLists.txt, applications/serial_lte_modem/src/main.c, applications/serial_lte_modem/src/slm_at_commands.c, applications/serial_lte_modem/src/slm_at_host.c, applications/serial_lte_modem/src/slm_ctrl_pin.c, applications/serial_lte_modem/src/slm_ctrl_pin.h, applications/serial_lte_modem/src/slm_ppp.c, applications/serial_lte_modem/src/slm_util.h
Move power and indicate pin handling into an own module from `main.c`.
=> applications: serial_lte_modem: Refactor power and indicate pin handling

samples/ipc/ipc_service/Kconfig.sysbuild, samples/ipc/ipc_service/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/ipc/ipc_service/boards/nrf54l15dk_nrf54l15_cpuapp_icbmsg.overlay, samples/ipc/ipc_service/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.overlay, samples/ipc/ipc_service/boards/nrf54lm20pdk_nrf54lm20a_cpuapp_icbmsg.overlay, samples/ipc/ipc_service/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay, samples/ipc/ipc_service/boards/nrf54lv10dk_nrf54lv10a_cpuapp_icbmsg.overlay, samples/ipc/ipc_service/remote/boards/nrf54l15dk_nrf54l15_cpuflpr.overlay, samples/ipc/ipc_service/remote/boards/nrf54l15dk_nrf54l15_cpuflpr_icbmsg.overlay, samples/ipc/ipc_service/remote/boards/nrf54lm20pdk_nrf54lm20a_cpuflpr.overlay, samples/ipc/ipc_service/remote/boards/nrf54lm20pdk_nrf54lm20a_cpuflpr_icbmsg.overlay, samples/ipc/ipc_service/remote/boards/nrf54lv10dk_nrf54lv10a_cpuflpr.overlay, samples/ipc/ipc_service/remote/boards/nrf54lv10dk_nrf54lv10a_cpuflpr_icbmsg.overlay, samples/ipc/ipc_service/sample.yaml, samples/ipc/ipc_service/src/main.c
Add overalys required to run the sample on nRF54L15 DK.
=> samples: ipc: ipc_service: Run sample on nRF54L15

boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a-pinctrl.dtsi, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a_cpuapp_0_2_0.overlay, boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a_cpuflpr_0_2_0.overlay
Merge configuration, add mising CTS/RTS pins for uart20.
=> boards: nordic: nrf54lv10dk: single place for uart pin defs

doc/nrf/libraries/networking/nrf_provisioning.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add new Kconfig options and minor updates.
Add changelog entry.
=> doc: nrf_provisioning: update docs

tests/zephyr/drivers/uart/uart_elementary/boards/nrf54lv10dk_nrf54lv10a_0_0_0_dual_uart.overlay
=> tests: zephyr: drivers: uart: uart_elementary: fix for lv10 0.0.0

applications/nrf_desktop/doc/hid_state.rst, applications/nrf_desktop/doc/keys_state.rst, applications/nrf_desktop/src/util/keys_state.h, applications/nrf_desktop/utils.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
PR introduces documentation for keys state utility. PR also updates HID state module documentation to inform about keys state
utility integration.
Jira: NCSDK-33999
=> applications: nrf_desktop: Document keys state utility

scripts/ci/tags.yaml
Added zephyr/modules/openthread as a trigger for openthread samples.
=> scripts: Added trigger for openthread samples

samples/bluetooth/direct_test_mode/src/dtm.c, samples/esb/esb_prx/src/main.c, samples/esb/esb_ptx/src/main.c, samples/peripheral/radio_test/src/main.c
Adjust MLTPAN-20 in samples:
- radio_test
- direct_test_mode
- esb ptx and prx
=> samples: Adjust MLTPAN-20 in selected samples

.github/test-spec.yml, tests/drivers/fprotect/negative/testcase.yaml
Test fprotect.negative parameter HW crypto conf.
=> tests: fprotect: SB with HW crypto test case

doc/nrf/links.txt, doc/nrf/protocols/zigbee/index.rst, doc/nrf/samples/zigbee.rst
as requested included github links
=> doc: zigbee: add github links

samples/peripheral/radio_test/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.conf, scripts/quarantine.yaml
=> samples: peripheral: radio_test: use NRF_SECURITY

scripts/west_commands/ncs_ironside_se_update.py
Improve error reporting for west ncs-ironside-se-update.
return codes are now checked for underlying "nrfutil device" commands, and the existence of files is now checked.
=> west: ncs-ironside-se-update: Improve error reporting

scripts/ci/tags.yaml
=> scripts: ci: tags: extend deps for ci_samples_esb

include/net/azure_iot_hub_dps.h, samples/net/coap_client/README.rst
=> net: Align Kconfig names in doc and code

cmake/sysbuild/sign.cmake, doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_main_config.rst, doc/nrf/app_dev/device_guides/nrf70/nrf70_fw_patch_update.rst, samples/bootloader/README.rst, samples/nrf5340/extxip_smp_svr/README.rst, scripts/ci/license_allow_list.yaml, tests/benchmarks/kernel_freq_change/src/kernel_context.c
=> samples/doc: Fix some undefined Kconfig references

doc/nrf/releases_and_maturity/known_issues.rst
Added record on the issue in serial recovery protocol.
=> doc/nrf/known_issues: NCSIDB-1431

samples/zephyr/smp_svr_mini_boot/pm_static.yml
Fixes wrong addresses in this file
=> samples: zephyr: smp_svr_mini_boot: Fix static PM file

applications/nrf_desktop/doc/power_manager.rst
Change fixes a Kconfig option typo in documentation.
Jira: NCSDK-34354
=> applications: nrf_desktop: Fix typo in doc

subsys/esb/esb.c
Fix the enabling mechanism of the FEM in ESB.
Jira: NCSDK-33988
=> esb: Fix FEM enabling mechanism

samples/bluetooth/event_trigger/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay
Add missing configuration for event_trigger bluetooth sample
=> samples: bluetooth: Add configuration for nRF54lv10dk

subsys/mpsl/clock_ctrl/mpsl_clock_ctrl.c
When MPSL uses nrf2 clock control e.g. on nRF54h20, is should call nrf_clock_control_resolve to get information about the LFCLK source accuracy. The LFCLK souce is unknown to the MPSL so it asks for the worst alowed LFCLK accuracy, which is 500PPM. The API should provide the most accurate and the most power efficient clock source.
=> mpsl: Use nrf2 cloc ctrl resolve API to get LFCLK accuracy

west.yml
Cherry picking to make sure we don't need it downstream.
=> manifest: zephyr: cherry pick removal of nordic,cryptocell compat

subsys/emds/emds_flash_new.c, subsys/emds/emds_flash_new.h, subsys/emds/emds_new.c
Commit adds new storing flow implementation.
For whom who wasn't from the beginning of task, this is new emds design: https://nordicsemi.atlassian.net/wiki/spaces/MESH/pages/1598554695/New+EMDS+design
=> emds: new storing flow implementation

doc/nrf/protocols/wifi/advanced_modes/raw_tx_operation.rst
=> doc: wifi: fix path to header files

doc/nrf/releases_and_maturity/migration/migration_guide_3.1.rst, samples/matter/common/src/app/matter_init.cpp, samples/matter/common/src/app/matter_init.h, samples/matter/light_bulb/src/app_task.cpp, samples/matter/light_bulb/src/zcl_callbacks.cpp
Fixed problems with not working deferred attribute persister due to missining initialization.
=> samples: matter: Fixed deferred attribute persister

scripts/memory-threshold-list.yaml
Added new scenarios and platform specifications for sample.smp_svr_mini_boot, including ROM and RAM size configurations.
Ref:  NCSDK-34399
=> scripts: update memory-threshold-list.yaml with sample.smp_svr_mini_boot

subsys/emds/emds.c
Add validation against static entries in emds_entry_add().
=> emds: prevent duplicate entry IDs

west.yml
=> manifest: mbedtls: update to 3.6.4

doc/requirements.txt
=> doc: requirements: adding natsort

doc/nrf/protocols/wifi/regulatory_certification/adaptivity_test_procedure.rst, doc/nrf/protocols/wifi/regulatory_certification/using_wifi_station_sample.rst
Correct wavegap and data rate.
=> doc: wifi: Corrections to command example

applications/serial_lte_modem/src/slm_ppp.c
When remote peer requests a DNS address from PPP using IPCP, we should offer that in the ipcp.peer_options or ipcp.my_options.
Populate this information from PDN, or use any of the known Kconfig DNS addresses as a fallback.
=> applications: serial_lte_modem: Serve DNS from PDN to PPP

doc/nrf/releases_and_maturity/software_maturity.rst, doc/nrf/security/crypto/crypto_supported_features.rst
Edited the tables for crypto feature support to list support per device. NCSDK-34128.
=> doc: crypto: supported features per device

scripts/ci/tags.yaml
=> scripts: ci: tags: extend bluetooth deps for hal_nordic

scripts/ci/tags.yaml
=> scripts: ci: tags: add missing ending / at folders

doc/nrf/links.txt, doc/nrf/releases_and_maturity/migration/migration_bicr_nRF54H20.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added migration guide for nRF54H20 BICR config.
=> doc: Added migration guide for nRF54H20 BICR config

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, subsys/esb/esb.c
Improved logic for disabling the protocol
in the esb_disable and esb_stop_rx functions.
=> esb: Improve radio disable handling

applications/machine_learning/sample.yaml, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add power optimized configuration (S2RAM) to machine_learning application.
Jira: NCSDK-32067
=> applications: machine_learning: Add power optimized configuration

applications/connectivity_bridge/sysbuild/mcuboot/prj.conf, applications/machine_learning/sysbuild/mcuboot/prj.conf, applications/nrf5340_audio/sysbuild/mcuboot/prj_fota.conf, applications/serial_lte_modem/sysbuild/mcuboot/prj.conf, samples/bluetooth/peripheral_status/sysbuild/mcuboot/prj.conf, samples/cellular/ciphersuites/sysbuild/mcuboot/prj.conf, samples/cellular/nrf_cloud_multi_service/sysbuild/mcuboot/prj.conf, samples/cellular/nrf_cloud_rest_fota/sysbuild/mcuboot/prj.conf, samples/cellular/smp_svr/sysbuild/mcuboot/prj.conf, samples/net/aws_iot/sysbuild/mcuboot/prj.conf, samples/net/azure_iot_hub/sysbuild/mcuboot/prj.conf, samples/net/https_client/sysbuild/mcuboot/prj.conf, samples/nrf5340/extxip_smp_svr/sysbuild/mcuboot/prj.conf, samples/nrf5340/extxip_smp_svr/sysbuild/mcuboot/prj_no_network_core.conf, samples/nrf5340/extxip_smp_svr/sysbuild/mcuboot/prj_no_network_core_directxip.conf, samples/nrf5340/netboot/src/main.c, samples/wifi/shell/sysbuild/mcuboot/prj.conf, tests/subsys/nrf_compress/decompression/mcuboot_update/sysbuild/mcuboot/prj.conf
Removes mention of a previously existing Kconfig
=> applications/samples/tests: Remove mention of invalid Kconfig

scripts/west_commands/ncs_ironside_se_update.py
=> improve robustness of 'west ncs-ironside-se-update'

.sonarcloud.properties
autoscan: definiton of scan scope and exclusions
=> ci: autoscan: fixing the sonar properties

samples/bluetooth/llpm/sample.yaml, samples/bluetooth/peripheral_with_multiple_identities/sample.yaml, samples/bluetooth/radio_notification_cb/sample.yaml, samples/bluetooth/scanning_while_connecting/sample.yaml, samples/bluetooth/subrating/sample.yaml
Switch samples after nrf54lm20pdk was renamed to nrf54lm20dk.
=> samples: bluetooth: Switch samples to nrf54lm20dk

doc/nrf/app_dev/device_guides/coprocessors/index.rst, doc/nrf/app_dev/device_guides/coprocessors/ug_hpf_softperipherals_comparison.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_flpr.rst, doc/nrf/app_dev/device_guides/nrf54l/vpr_flpr.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
added a guide comparing softperipherals and hpf solutions
changelog entry added
(WIP)
=> doc: hpf and softperipherals comparison

applications/nrf5340_audio/src/audio/audio_datapath.c
OCT-3418
Reduced prints in I2S ISR
Make functions inline
Reduce overall time spent in ISR
=> Applications: nrf5340_audio: Improved I2S ISR

tests/drivers/i2c/i2c_latency/src/main.c, tests/drivers/spi/spi_latency/src/main.c, tests/drivers/uart/uart_latency/src/async.c, tests/drivers/uart/uart_latency/src/common.c, tests/drivers/uart/uart_latency/src/common.h, tests/drivers/uart/uart_latency/src/int_driven.c, tests/drivers/uart/uart_latency/src/polling.c, tests/drivers/uart/uart_latency/testcase.yaml
Add averaging to:
- SPI latency test,
- I2C latency test,
- UART latency test
=> tests: drivers: Add averaging to transmission latency tests

doc/nrf/app_dev/device_guides/thingy91x/index.rst, doc/nrf/app_dev/device_guides/thingy91x/thingy91x_recover_to_factory_firmware.rst, doc/nrf/app_dev/device_guides/thingy91x/thingy91x_updating_fw_programmer.rst, doc/nrf/links.txt
Backport 1918ca2e8075fdddefe335beef6bf5f57b3a56e7 from #22963.
=> [Backport v3.1-branch] doc: Add recovery guide and update commands on the firmware page

drivers/serial/uart_nrf_sw_lpuart.c
Backport 22790df41c3d91ad47874a1bf8a32a77c4a92b8d from #23654.
=> [Backport v3.1-branch] drivers: uart_nrf_sw_lpuart: Fix interrupt driven case

applications/nrf5340_audio/src/audio/audio_datapath.c
Backport 40d7392ce441b93a818d6278874c400747a33c90 from #23630.
=> [Backport v3.1-branch] Applications: nrf5340_audio: Improved I2S ISR

.github/workflows/west-commands.yml
Backport 95a5a55be764e2dc756a43ce7b485ac3a978d65e from #23614.
=> [Backport v3.1-branch] ci: fix west-commands workflow

west.yml
Backport manifest update for
https://github.com/nrfconnect/sdk-find-my/pull/339.
=> [Backport v3.1-branch] manifest: Update sdk-find-my revision

west.yml
manifest pr for https://github.com/nrfconnect/sdk-nrfxlib/pull/1817
=> manifest: sdk-nrfxlib: v3.1-branch Update MPSL and SoftDevice Controller

scripts/tools-versions-darwin.yml, scripts/tools-versions-linux.yml, scripts/tools-versions-win10.yml
sync with internal test tool
Released 24/7/25
=> ci: upgrade `nrfutil device==2.12.6`

doc/nrf/security/ap_protect.rst, samples/tfm/tfm_psa_template/README.rst
Backport 9520aba10731b2b1e133e15ce88c91938db5ef77 from #23705.
=> [Backport v3.1-branch] doc: security: SB_CONFIG formatting

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cipher.c
Align CBC PKCS#7 padding methodology to changes made for Mbed TLS  v3.6.4
=> nrf_security: CRACEN: Align CBC PKCS#7 methodology

applications/nrf5340_audio/doc/feature_support.rst, doc/nrf/links.txt, doc/nrf/protocols/bt/bt_qualification/index.rst, doc/nrf/protocols/matter/end_product/certification.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.7.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.8.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-2.9.0.rst, doc/nrf/releases_and_maturity/releases/release-notes-3.0.0.rst
Removed DK from the comp matrix links.
NCSIDB-1528
=> doc: fix_comp_matrix_link

samples/wifi/provisioning/internal/CMakeLists.txt, subsys/net/lib/wifi_prov_core/CMakeLists.txt, subsys/net/lib/wifi_prov_core/proto/CMakeLists.txt, subsys/net/lib/wifi_prov_core/proto/generate_wifi_prov_config.py, subsys/net/lib/wifi_prov_core/proto/test_auth_modes.py
Backport 196e9eb57fbbad2c11303ab56fdcd1f95f88805a~2..196e9eb57fbbad2c11303ab56fdcd1f95f88805a from #23745.
=> [Backport v3.1-branch] net: lib: wifi_prov_core: Fix windows build

cmake/sysbuild/bootloader_dts_utils.cmake, cmake/sysbuild/sign_nrf54h20.cmake, cmake/sysbuild/zip.cmake, sysbuild/Kconfig.zip
The needed changes were linked to untangling the use of partition manager.
=> cmake: Added the possibility to generate MCUBoot zip for nrf54h20

doc/nrf/app_dev/device_guides/nrf54h/index.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_flpr.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_ppr.rst
=> doc: Added 54H PPR userguide

scripts/tools-versions-darwin.yml, scripts/tools-versions-win10.yml
=> tools: Generate bundles with gn 2223

.github/workflows/src-mirror.yml
Update sdk-manager index.json to reduce manual steps after tag is placed. Align with new API of action-src-mirror action
=> ci: Update sdk-manager index.json when tag is placed

west.yml
Includes a fix for asn1 and some BM IO changes
=> [v3.1-backport] manifest: Update sdk-mcuboot

tests/drivers/adc/adc_latency/src/main.c
Add pre-allocated sample buffer and more test cases.
=> tests: drivers: adc: Update ADC latency test

west.yml
Manifest PR for https://github.com/nrfconnect/sdk-nrfxlib/pull/1824
=> [Backport v3.1-branch] manifest: Update MPSL and SoftDevice Controller

.github/workflows/src-mirror.yml
Backport f9e9a0a458f07b889a3214ab00316d90a1210cbf from #23801.
=> [Backport v3.1-branch] ci: Update sdk-manager index.json when tag is placed

samples/bluetooth/mesh/dfu/distributor/README.rst, samples/bluetooth/mesh/dfu/target/README.rst
Updated DFU Target and DFU Distributor procedure descriptions.
=> doc: samples: bluetooth: mesh: small update in DFU procedure

doc/nrf/app_dev/device_guides/nrf54h/index.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_mcuboot_dfu.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h_ecies_x25519.rst, doc/nrf/links.txt
Backport e61f950a5759ba9ac383199fb935f04ed5f4db79 from #23421.
=> [Backport v3.1-branch] doc: Added 54H dfu MCUboot userguide

applications/nrf5340_audio/doc/feature_support.rst, samples/wifi/provisioning/internal/README.rst, samples/wifi/shutdown/README.rst
Backport 55068921c953fb88d6a09e01bd6e7294356874ad from #23830.
=> [Backport v3.1-branch] doc improvement: Fixed some doc issues

samples/bluetooth/mesh/dfu/distributor/README.rst, samples/bluetooth/mesh/dfu/target/README.rst
Backport c11cd3dc04f55e8ddc1796d73460a732ba10725d from #23874.
=> [Backport v3.1-branch] doc: samples: bluetooth: mesh: small update in DFU procedure

CODEOWNERS, doc/_utils/redirects.py, doc/_zoomin/ncs.tags.yml, doc/nrf/external_comp/bt_fast_pair/adv_manager.rst, doc/nrf/external_comp/bt_fast_pair/core.rst, doc/nrf/external_comp/bt_fast_pair/index.rst, doc/nrf/integrations.rst, doc/nrf/libraries/bluetooth/index.rst, doc/nrf/libraries/bluetooth/services/fast_pair/core.rst, doc/nrf/libraries/bluetooth/services/fast_pair/index.rst
Reorganize the Google Fast Pair integration
and libray docs.
NCSDK-34559
=> doc: Reorganize the Google Fast Pair docs

CODEOWNERS, doc/_utils/redirects.py, doc/_zoomin/ncs.tags.yml, doc/nrf/external_comp/bt_fast_pair/adv_manager.rst, doc/nrf/external_comp/bt_fast_pair/core.rst, doc/nrf/external_comp/bt_fast_pair/index.rst, doc/nrf/integrations.rst, doc/nrf/libraries/bluetooth/index.rst, doc/nrf/libraries/bluetooth/services/fast_pair/core.rst, doc/nrf/libraries/bluetooth/services/fast_pair/index.rst
Backport 8ec1b21e656999f987c7a0a3489263705d71eda3 from #23707.
=> [Backport v3.1-branch] doc: Reorganize the Google Fast Pair docs

samples/nrf_rpc/protocols_serialization/client/src/ot_shell.c
Implement more OT shell commands on the client side to increase test coverage of OT RPC APIs.
=> samples: nrf_rpc: ps_client: implement more OT shell commands

tests/benchmarks/power_consumption/adc/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay, tests/benchmarks/power_consumption/adc/testcase.yaml, tests/benchmarks/power_consumption/adc_async/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay, tests/benchmarks/power_consumption/adc_async/testcase.yaml, tests/benchmarks/power_consumption/gpio/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay, tests/benchmarks/power_consumption/gpio/testcase.yaml, tests/benchmarks/power_consumption/lpcomp/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay, tests/benchmarks/power_consumption/lpcomp/testcase.yaml, tests/benchmarks/power_consumption/timer_waiting/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay, tests/benchmarks/power_consumption/timer_waiting/testcase.yaml, tests/benchmarks/power_consumption/uart_async/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay, tests/benchmarks/power_consumption/uart_async/testcase.yaml, tests/benchmarks/power_consumption/uart_interrupt/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay, tests/benchmarks/power_consumption/uart_interrupt/testcase.yaml, tests/benchmarks/power_consumption/uart_polling/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay, tests/benchmarks/power_consumption/uart_polling/testcase.yaml
=> tests: benchmarks: power_consumption: enable testing at LV10

doc/nrf/releases_and_maturity/software_maturity.rst
Backport 30890afc6c0831e41df4eb9e643de40ecddbaeda from #23908.
=> [Backport v3.1-branch] doc: sml: fast_pair: update for NCS v3.1.0

doc/nrfx/nrfx.doxyfile.in
remove a section about drivers from nrfx doc
=> doc: fix for techdoc-3981

doc/nrf/releases_and_maturity/software_maturity.rst
This commit add information about Zigbee and related features support on SoCs.
Signed-off-by: Michal Leksinski <michal.leksinski@nordicsemi.no>
=> doc: software_maturity: update Zigbee and Sidewalk tables

scripts/quarantine.yaml
=> scripts: quarantine: add secure_storage

applications/nrf_desktop/bootloader_dfu.rst, applications/nrf_desktop/doc/cpu_meas.rst, doc/nrf/app_dev/bootloaders_dfu/mcuboot_serial_recovery.rst, doc/nrf/app_dev/device_guides/fem/fem_nrf2220.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_mcuboot_dfu.rst, doc/nrf/app_dev/device_guides/nrf54l/kmu_provision.rst, doc/nrf/app_dev/device_guides/nrf54l/vpr_flpr.rst, doc/nrf/libraries/caf/leds.rst, doc/nrf/libraries/caf/sensor_data_aggregator.rst, doc/nrf/libraries/networking/wifi_prov_core.rst, doc/nrf/libraries/security/trusted_storage.rst, doc/nrf/protocols/matter/end_product/security.rst, doc/nrf/protocols/thread/configuring.rst, doc/nrf/releases_and_maturity/migration/migration_3.1_54h_suit_ironside.rst, samples/bluetooth/fast_pair/locator_tag/README.rst, samples/bluetooth/mesh/dfu/target/README.rst, samples/cellular/modem_shell/README.rst, samples/nrf5340/netboot/README.rst, snippets/nordic-flpr/README.rst
Backport 2cf084fde86bcda7c6939c4186e4d1a6b1b028ae from #23903.
=> [Backport v3.1-branch] doc: Doc check for 3.1.0

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c
cracen_signature_prepare_ec_pubkey now returns psa_status_t. 
Fixed cracen_ecc_get_ecurve_from_psa to handle it correctly as psa_status_t instead of sx_status. 
Ensures proper error handling.
=> nrf_security: CRACEN: Fix status handling in ECC key prep

tests/drivers/adc/adc_latency/src/main.c
=> tests: drivers: adc: adc_latency: show adc value on error

doc/nrf/releases_and_maturity/known_issues.rst
Backport 5884359e63ac51250dcbfad98611512868c58a26 from #23586.
=> [Backport v3.1-branch] doc: Update known issues for NCS 3.1.0

samples/bluetooth/direct_test_mode/src/dtm.c
Simplify the statement so that it becomes easier to understand.
=> samples: direct_test_mode: Simplify statement

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c
If a blocked key is attempted to be destroyed
the provisioning slot is not cleared.
To avoid this an attempt to push the key is
done before destroying the key.
This allows us to return an error while provisioning can still happen for other slots.
=> nrf_security: CRACEN: Fix KMU key BLOCK can end up in an invalid state

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/abi_compatibility.rst, doc/nrf/releases_and_maturity/migration/migration_3.1_54h_suit_ironside.rst, doc/nrf/releases_and_maturity/migration/migration_guide_3.1.rst
Improvements to nRF54H documentation.
=> doc: Improvements to nRF54H documentation

applications/serial_lte_modem/src/slm_cmux.c
Backport 485ffe49aecacb2828347433c14ad916d730fb3a from #23973.
--
Jira: SLM-116
=> [Backport v3.1-branch] applications: serial_lte_modem: Fix cellular modem driver dialup

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_logging.rst, doc/nrf/links.txt
Backport 738c36271cb2507d9b96b005bf476d35a89944db from #23949.
=> [Backport v3.1-branch] doc: logging: link to nrfutil trace

tests/benchmarks/power_consumption/lpcomp/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/benchmarks/power_consumption/lpcomp/src/driver_test.c
Use device_pm API to get correct  current measurement results.
=> tests: benchmarks: power_consumption: lpcomp: Fix test

scripts/quarantine.yaml
=> scripts: quarantine: add sample.matter.template.smp_dfu.old_ec

samples/benchmarks/coremark/README.rst
Describes nRF54LM20 support in docs.
Jira: NCSDK-35011
=> doc: coremark: Describe nRF54LM20 support

west.yml
To align the driver with Cracen.
=> manifest: Bring Oberon with RSA OAEP update

samples/bluetooth/central_smp_client/sample.yaml, samples/bluetooth/conn_time_sync/sample.yaml, samples/bluetooth/event_trigger/sample.yaml, samples/bluetooth/iso_time_sync/sample.yaml, samples/bluetooth/llpm/sample.yaml, samples/bluetooth/multiple_adv_sets/sample.yaml, samples/bluetooth/peripheral_bms/sample.yaml, samples/bluetooth/peripheral_with_multiple_identities/sample.yaml, samples/bluetooth/radio_notification_cb/sample.yaml, samples/bluetooth/scanning_while_connecting/sample.yaml, samples/bluetooth/subrating/sample.yaml
Enable automated testing with twister.
=> samples: bluetooth: add basic console check

applications/ipc_radio/README.rst
Updated the formatting of the application-specific and sysbuild Kconfig options.
=> doc: IPC radio fw application: update Kconfigs

applications/nrf_desktop/board_configuration.rst, applications/nrf_desktop/bootloader_dfu.rst, applications/nrf_desktop/description.rst, applications/nrf_desktop/memory_layout.rst
Backport e3f8e7bb7ec7699c5435caaba282694da96fe47d~2..e3f8e7bb7ec7699c5435caaba282694da96fe47d from #24165.
=> [Backport v3.1-branch] applications: nrf_desktop: document the nRF54LM20 DK support

samples/cellular/nrf_provisioning/src/main.c
Connection manager disconnects only LTE and GNSS may still be active. Check modem's functional mode and deactivate GNSS before storing credentials to modem.
=> samples: nrf_provisioning: Check active GNSS

.github/workflows/docker.yml
Fix for missing permisons on push to ghcr
=> ci: update auth for ghcr.io in docker.yml action

scripts/docker/Dockerfile
=> docker: Update JLink version to V860

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added information about nRF54LM20 support and fixes for the certification test cases to the release notes.
=> doc: Updated release notes for Matter

dts/arm/nordic/nrf54lv10a_enga_cpuapp.dtsi, samples/crypto/psa_tls/sample.yaml
add lv10 to supported platforms in sample.yaml
set psa-rng active for lv10 in dts
=> samples: crypto: add psa_tls support to lv10

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_boot.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_clockman.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_cpu.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_ipc.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_lifecycle.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_memory.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_architecture_reset.rst, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_logging.rst
=> doc: Updated H20 arch docs

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, doc/nrf/shortcuts.txt
Updated shortcuts.txt to list J-Link 8.60.
NRFU-1607.
----
=> doc: jlink: update to 8.60

samples/net/mqtt/doc/architecture.rst
Explain why sample doesnt have a main function.
=> samples: net: MQTT: Documentation update

tests/subsys/usb/negotiated_speed/boards/nrf54lm20dk_nrf54lm20a_cpuapp.overlay
=> tests: subsys: usb: negotiated_speed: add ramdisk configuration for LM20

applications/nrf5340_audio/doc/audio_api.rst, applications/nrf5340_audio/index.rst, applications/nrf5340_audio/src/audio/audio_datapath.h, applications/nrf5340_audio/src/audio/audio_system.h, applications/nrf5340_audio/src/audio/le_audio_rx.h, applications/nrf5340_audio/src/audio/streamctrl.h, applications/nrf5340_audio/src/audio/sw_codec_select.h, applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.h, applications/nrf5340_audio/src/bluetooth/bt_rendering_and_capture/bt_rendering_and_capture.h, applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h, applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.h, applications/nrf5340_audio/src/modules/audio_i2s.h, applications/nrf5340_audio/src/modules/audio_sync_timer.h, applications/nrf5340_audio/src/modules/audio_usb.h, applications/nrf5340_audio/src/modules/button_handler.h, applications/nrf5340_audio/src/modules/lc3_file.h, applications/nrf5340_audio/src/modules/lc3_streamer.h, applications/nrf5340_audio/src/modules/led.h, applications/nrf5340_audio/src/modules/sd_card.h, applications/nrf5340_audio/src/modules/sd_card_playback.h, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added a new page listing the available audio API.
OCT-3355.
=> doc: audio: add API documentation page & update API header docs

samples/esb/esb_monitor/CMakeLists.txt, samples/esb/esb_monitor/Kconfig, samples/esb/esb_monitor/README.rst, samples/esb/esb_monitor/src/sniffer.c, samples/esb/esb_monitor/src/sniffer.h, samples/esb/esb_monitor/src/sniffer_shell.c
Implemented shell commands for runtime configuration updates
JIRA: NCSDK-35071
=> samples: esb_monitor: Implemented shell commands

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Support for nRF54LM20 FLPR was added.
=> doc: release_notes: add note about nRF54LM20 FLPR

CODEOWNERS, doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_keys.rst, doc/nrf/app_dev/device_guides/nrf54l/kmu_provision.rst, doc/nrf/links.txt, doc/nrf/scripts.rst, doc/nrf/security/key_storage.rst, scripts/generate_psa_key_attributes.py, scripts/generate_psa_key_attributes/generate_psa_key_attributes.rst, scripts/west_commands/ncs_provision.py
Included additional key types and usage schemes.
Added extra descriptions to input parameters.
Changed names of classes and input parameters.
=> scripts: Added features in generate_psa_key_attributes.py

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_gs.rst, doc/nrf/links.txt, doc/nrf/releases_and_maturity/abi_compatibility.rst, doc/nrf/releases_and_maturity/migration/migration_3.1_54h_suit_ironside.rst, doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst, doc/nrf/releases_and_maturity/migration/migration_guide_3.1.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs1.rst, doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs2.rst, doc/nrf/shortcuts.txt
New improvements to 54h soc binaries docs.
=> backports: doc: PRs 24062 - 24252 - 24316 - 20615

doc/nrf/releases_and_maturity/software_maturity.rst
SML updates for NFC
Cherry pick commit of PR https://github.com/nrfconnect/sdk-nrf/pull/24310 as the backport PR was not created due to merge conflict.
=> doc: SML updates for NFC

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, samples/app_event_manager_profiler_tracer/README.rst, scripts/nrf_profiler/stats_nordic_presets/app_event_manager_profiler_tracer.json
Change adds a new testing step demonstrating calculating statistics. Change also adds related test preset for the nRF Profiler host tools.
Jira: NCSDK-35261
=> samples: app_event_manager_profiler_tracer: Stats calculating demo

.github/workflows/backport.yml, .github/workflows/labeler.yml, .github/workflows/manifest.yml
If github-action[bot] is used, GH actions are not triggered
=> ci: Use NordicBuilder's token to open and label PRs

tests/subsys/bootloader/boot_chains/testcase.yaml, tests/subsys/kmu/hello_for_kmu/testcase.yaml
Added missing boards to hello_for_kmu and boot_chains test configurations
=> tests: nrf54lv10: added to kmu and boot_chains

samples/nrf_compress/mcuboot_update/sample.yaml
=> samples: nrf_compress: mcuboot_update: nrf54lv10

samples/nrf_compress/mcuboot_update/sample.yaml
Enable automated testing with twister.
=> samples: nrf_compress: mcuboot_update: add basic console check

doc/nrf/app_dev/device_guides/nrf52/fota_update.rst, doc/nrf/app_dev/device_guides/nrf54l/fota_update.rst
Remove mentioning options, that are no longer present in the note.
=> doc: Fix note about Direct XIP

scripts/tools-versions-darwin.yml, scripts/tools-versions-linux.yml, scripts/tools-versions-win10.yml
Update nrfutil device version to 2.13.2
=> tools: Update nrfutil device version to 2.13.2

applications/nrf_desktop/api.rst
Change aligns documentation with implementation.
Jira: NCSDK-35005
=> applications: nrf_desktop: Update source file for USB event in docs

samples/crypto/psa_tls/boards/nrf54lv10dk_nrf54lv10_cpuapp_ns.conf, samples/crypto/psa_tls/sample.yaml, samples/tfm/tfm_hello_world/sample.yaml
=> Add support for more boards to samples

doc/nrf/app_dev/device_guides/nrf54l/fota_update.rst, doc/nrf/app_dev/device_guides/nrf54l/kmu_basics.rst, doc/nrf/app_dev/device_guides/nrf54l/kmu_provision.rst
Backport 02439b1d88e65078e6deac33277b0b6b5e447041 from #24507.
=> [Backport v3.1-branch] doc: nRF54LM20 KMU support note edit

samples/nrf_compress/mcuboot_update/pm_static_nrf54l15dk_nrf54l15_cpuapp.yml, samples/nrf_compress/mcuboot_update/sample.yaml
Reduces the size of MCUboot in this build
=> samples: nrf_compress: mcuboot_update: Update nRF54L15 PM file

doc/nrf/libraries/bluetooth/services/fast_pair/core.rst
Fix rendering of documentation related to Fast Pair use-cases.
=> doc: fast_pair: Fix documentation rendering

soc/nordic/nrf71/Kconfig, soc/sercomm/nrf91/Kconfig, soc/sercomm/nrf91/Kconfig.soc
=> soc: sercomm: nrf91: Fix duplicating board Kconfigs

applications/nrf_desktop/application_kconfig.rst, applications/nrf_desktop/doc/hid_state.rst
Change updates documentation of the HID state module to introduce improvements related to HID report providers support.
Jira: NCSDK-35005
=> applications: nrf_desktop: Update HID state documentation

scripts/quarantine_zephyr.yaml
Quarantine samples for nrf54lm20dk/nrf54lm20a/cpuapp
=> scripts: quarantine_zephyr: Quarantine samples

doc/nrf/releases_and_maturity/releases/release-notes-3.1.1.rst
=> doc: add release highlights

samples/dfu/ab/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/dfu/ab/sample.yaml, samples/dfu/ab/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/dfu/ab/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/dfu/ab/sysbuild/nrf54l15dk_nrf54l15_cpuapp_common.dtsi
This commit adds support for nRF54L15 in the DFU A/B sample.
Reopening this part due to request from management
=> samples: dfu: ab sample nrf54L15 support

scripts/ci/test_plan.py, scripts/quarantine.yaml
=> scripts: quarantine: add sample.dfu.dfu_multi_image

samples/app_jwt/sample.yaml, tests/drivers/i2c/i2c_latency/testcase.yaml, tests/drivers/uart/uart_latency/testcase.yaml
This change unify name convention.
=> samples: tests: Unify name of tests/samples

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_ironside.rst
=> doc: ironside: improve booting chapter

tests/drivers/grtc/grtc_reset/testcase.yaml
=> tests: drivers: grtc: grtc_reset: fix yaml syntax

doc/_utils/redirects.py
=> doc: updated redirects.py

tests/subsys/swo/pytest/test_swo.py
=> tests: subsys: swo: show more logs from jlink tool

samples/dfu/dfu_multi_image/sysbuild/mcuboot/boards/nrf54h20dk_nrf54h20_cpuapp.conf, samples/dfu/dfu_multi_image/sysbuild/mcuboot/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, scripts/quarantine.yaml
Fixed the build errors resulting from the recent GPD changes
=> samples: dfu: dfu_multi_image: Fix GPD issues after upmerge

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst, doc/nrf/shortcuts.txt
Updated shortcuts.txt to list J-Link 8.66.
NRFU-1645.
----
=> doc: jlink: update to 8.66

subsys/nrf_security/src/drivers/cracen/cracen_sw/cracen_sw.cmake, subsys/nrf_security/src/drivers/cracen/cracen_sw/src/cracen_sw_aes_ctr.c, subsys/nrf_security/src/drivers/cracen/cracenpsa/cracenpsa.cmake, subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cipher.c
Fix bug with cmake logic for nRF54LV10A.
Remove some logic that is no longer needed.
=> Update aes ctr lv10

samples/matter/light_switch/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/lock/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/smoke_co_alarm/boards/nrf54l15dk_nrf54l10_cpuapp.conf, samples/matter/smoke_co_alarm/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/temperature_sensor/boards/nrf54l15dk_nrf54l15_cpuapp.conf, samples/matter/window_covering/boards/nrf54l15dk_nrf54l15_cpuapp.conf
Remove CONFIG POWEROFF from all matter samples.
=> samples: matter: remove POWEROFF for nRF54l15

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_ironside.rst
=> doc: add section on ironside reset handling

applications/nrf_desktop/src/hw_interface/motion_buttons.c
Change aligns state names with the motion sensor HW interface and sends an additional motion event when leaving the fetching state.
Jira: NCSDK-35474
=> applications: nrf_desktop: Update motion buttons HW interface

applications/nrf_desktop/src/hw_interface/motion_simulated.c
Change aligns internal state handling with other motion HW interfaces. Generating motion is controlled through a separate boolean. The module sends an additional motion event when leaving the fetching state.
Change also improves shell integration to prevent edge cases related to using preemptive execution context.
Jira: NCSDK-35474
=> applications: nrf_desktop: Cleanup motion simulated HW interface

west.yml
=> manifest: oberon: fix nonexistent volatile/builtin key handling

subsys/mpsl/cx/nrf700x/mpsl_cx_nrf700x.c
The Zephyr GPIO driver cannot be used from a Zero Latency Interrupt context, as its power management functions, e.g. pm_device_runtime_get attempt to take a semaphore. This can lead to system deadlocks when GPIOs are used from the ZLI.
=> mpsl: Use direct GPIO register access in coex

applications/nrf_desktop/CMakeLists.txt, subsys/app_event_manager/CMakeLists.txt, subsys/app_event_manager_profiler_tracer/CMakeLists.txt, subsys/bluetooth/adv_prov/CMakeLists.txt, subsys/bluetooth/services/fast_pair/CMakeLists.txt, subsys/bluetooth/services/fast_pair/fp_storage/CMakeLists.txt, subsys/caf/events/CMakeLists.txt, subsys/emds/CMakeLists.txt, subsys/nrf_compress/CMakeLists.txt
Fixes needed to compile using IAR.
=> iar: cmake: linker generator fixes

doc/nrf/releases_and_maturity/known_issues.rst, doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Described an issue that leads to a crash on nRF54lm20 running Matter samples.
=> doc: Add a known issue entry for Matter nRF54lm20 bug

samples/cellular/nrf_cloud_multi_service/Kconfig
Fix Kconfig style issues in the sample's Kconfig file.
=> samples: cellular: nrf_cloud_multi_service: Fix Kconfig indentations
