snippets/sdp/mspi/board/nrf54l15dk_nrf54l15_cpuapp.overlay

Remove definition of reset gpio for nRF54L15 external flash. It is on the same pin as one of data lines, and thus it should not be defined as reset gpio in dts. Instead, the MSPI driver should handle it.

snippets: sdp: mspi: remove definition of reset-gpio

---

applications/nrf_desktop/configuration/nrf52820dongle_nrf52820/ble_scan_def.h
applications/nrf_desktop/configuration/nrf52833dk_nrf52820/ble_scan_def.h
applications/nrf_desktop/configuration/nrf52833dk_nrf52833/ble_scan_def.h
applications/nrf_desktop/configuration/nrf52833dongle_nrf52833/ble_scan_def.h
applications/nrf_desktop/configuration/nrf52840dk_nrf52840/ble_scan_def.h
applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/ble_scan_def.h

Change introduces using const pointer in ble_scan_def headers. This fixes compliance issues.
Jira: NCSDK-31539

applications: nrf_desktop: Use const pointer in ble_scan_def headers

---

scripts/quarantine_zephyr.yaml

quarantine: Add test overflowing ram on flpr

---

sysbuild/Kconfig.mcuboot
west.yml

manifest: Update sdk-mcuboot
Updates MCUboot to pull in a fix for monotonic counter usage
sysbuild: mcuboot: Clarify monotonic counter usage
Clarifies that monotonic hardware counter will only be used on
the first image and disallow usage of this feature with QSPI XIP
split image updates as it is not compatible

mcuboot: Fix monotomic counter issues

---

samples/benchmarks/coremark/sysbuild.conf

Add comment to explain the purpose of the sysbuild partition manager.
JIRA: NCSDK-26736

coremark: Explain sysbuild partition manager option

---

west.yml

Updated OpenThread version to point the
ncs-thread-reference-20250402 tag

manifest: Updated OpenThread version to new tag

---

modules/openthread/platform/crypto_psa.c
subsys/net/openthread/Kconfig

To keep backward compatibility, we must use deterministic ECDSA and convert it to pure ECDSA for KMU only.
Also, once KMU can be used to store OpenThread crypto materials, we can allow disabling MBEDTLS_PSA_CRYPTO_STORAGE_C by the application, so changed select to imply.

modules: openthread: Fix ECDSA issue in OpenThread.

---

doc/nrf/app_dev/device_guides/pmic/index.rst
doc/nrf/links.txt

Adding a couple of links to the table.
The shield doc for nPM2100 in Zephyr is still missing.
Therefore, using same link twice in two places

doc: Adding links to Developing with PMICs table

---

doc/nrf/app_dev/device_guides/nrf70/wifi_advanced_security_modes.rst

wifi: enterprise: Pull support for runtime certificates

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c

`psa_export_key` would fail due to key not being populated. Add functions to populate key with attributes
Remove special case for ecc which is not needed and did not work. `psa_export_key` should now function for all supported key types.

nrf_security: cracen: Fix psa_export_key when exporting from kmu

---

scripts/reglock.py

sets maximum allowed region size in case requested size overflows.

scripts: reglock round down

---

doc/nrf/links.txt
doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
doc/nrf/protocols/matter/getting_started/tools.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Updated the Matter pages to mention the Matter over Thread power consumption whitepaper and Online Power Profiler for Matter tool as a resources that are useful in a process of optimizing and estimating the power consumption of a Matter device.

doc: Added information about Matter WP and OOP for Matter

---

lib/location/location_core.c

Fixed combining of cellular and Wi-Fi methods broken by commit 5e39c5f.
Jira: LRCS-110

lib: location: Fix combining of cell and Wi-Fi methods

---

doc/nrf/app_dev/device_guides/nrf70/wifi_advanced_security_modes.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Update the documentation in the wifi sample for
Enterprise-Mode security configuration

wifi: Add doc for enterprise mode

---

.github/workflows/compliance.yml

This commit is causing submodule fetch issues.
This reverts commit 67bf95fbdd7dc0e95244cb756b923bfb0d592e9d.

Revert "ci: add west update to compliance"

---

subsys/bluetooth/mesh/Kconfig

Increasing the default MBEDTLS_HEAP_SIZE to 1152 to accommodate all the keys used by NLC profile.

Bluetooth: Mesh: Increase MBEDTLS_HEAP_SIZE for NLC samples

---

subsys/bootloader/bl_crypto/Kconfig
subsys/bootloader/bl_crypto/bl_crypto_ed25519.c

adds automatic invalidation of previous generation keys.

bootloader: bl_crypto: kmu revocation

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/bluetooth/direct_test_mode/boards/nrf54h20dk_nrf54h20_cpurad.overlay
samples/bluetooth/direct_test_mode/src/dtm.c
samples/peripheral/radio_test/boards/nrf54h20dk_nrf54h20_cpurad.overlay
samples/peripheral/radio_test/src/radio_cmd.c
samples/peripheral/radio_test/src/radio_test.c

Implement the HMPAN-216 workaround for nRF54H20 in Radio Test and DTM using mbox, Timer CC1 and a binary sempahore to block test execution for the time required by the errata specification.

samples: Add HMPAN216 workaround in the radio_test and bluetooth/direct_test_mode samples

---

samples/bluetooth/channel_sounding_ras_initiator/src/main.c
samples/bluetooth/channel_sounding_ras_reflector/src/main.c
subsys/bluetooth/services/ras/rrsp/ras_rd_buffer.c
west.yml

The CS complete callbacks provide both status and params. In the case of errors, NULL pointer is passed to the params of callbacks.

bluetooth: samples: Apply callback changes of CS complete events

---

subsys/sdfw_services/services/psa_crypto/psa_crypto_service.c

Fixed corner case issue where prepare_out_buffer() returns a NULL pointer if the input buffer is
unaligned and the input buffer size is zero.

sdfw_services: psa_crypto: Fix bounce buffer corner case

---

scripts/quarantine_zephyr.yaml

Come from zephyr. Not compatible with NCS.

quarantine: add openthread samples

---

Kconfig.nrf
cmake/toolchain/llvm/Kconfig.defconfig

LLVM  now defaults to compiler_rt lib and LLD as linker. This means that Arm LLVM toolchain can be used out-of-the-box for nRF devices without having to pass `-DCONFIG_COMPILER_RT_RTLIB=y` and `-DCONFIG_LLVM_USE_LLD=y` on command line.

cmake: LLVM now defaults to compiler_rt lib and LLD as linker

---

lib/bin/lwm2m_carrier/os/lwm2m_shell.c

Add validation to error code shell commands to prevent adding or removing invalid values.

lib: bin: lwm2m_carrier: Add validation to error code commands

---

west.yml

This update brings improved UARTE clean-up which now resets its Pins to the default state.
~~Ref.: NCSIDB-1194~~

manifest: update sdk-mcuboot: brings improved UARTE clean-up

---

doc/nrf/nrf.doxyfile.in
subsys/nrf_security/include/crypto_compat.h
subsys/nrf_security/include/psa/client.h
subsys/nrf_security/include/psa/service.h
subsys/nrf_security/include/psa_util.h
subsys/nrf_security/include/tfm_ns_interface.h

...so that they are processed and rendered by Doxygen. Note that grouping
is still needed so that headers appear nicely in the "Topics" page.
This is a task left to the maintainers of such code.

doc: nrf: add nrf_security APIs to the Doxygen input

---

applications/nrf_desktop/nrf_desktop.ld
subsys/app_event_manager/aem.ld
subsys/event_manager_proxy/em_proxy.ld

ALIGN_WITH_INPUT is not supported with LLD and therefore linker scripts containing this flag will fail.
For LLD, then linking with -omagic (-N) achives the same as what is needed for XIP systems using ALIGN_WITH_INPUT, therefore adopt ld snippets to use the Zephyr provided SECTION_DATA_PROLOGUE() macro.

linker: replace ALIGN_WITH_INPUT with SECTION_DATA_PROLOGUE macro

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ctr_drbg.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c

Fix compilation warnings when building with the LLVM toolchain:
- add messages to uses of `_Static_assert()`
- remove unused `calc_key_bits_from_pub_key_buffer_size()`
- `#ifdef` functions only used when `PSA_NEED_CRACEN_KMU_ENCRYPTED_KEYS`

nrf_security: drivers: cracen: fix compilation warnings

---

samples/bluetooth/llpm/boards/nrf54h20dk_nrf54h20_cpuapp.conf
samples/bluetooth/llpm/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
samples/bluetooth/llpm/sysbuild/ipc_radio/boards/nrf54h20dk_nrf54h20_cpurad.conf
samples/bluetooth/llpm/sysbuild/ipc_radio/boards/nrf54h20dk_nrf54h20_cpurad.overlay

The PSA RNG is a cryptographically secure random number generator. It will be enabled by default, eventually.  For now, enable it manually.
This sample requires an increase in the number of buffers available for incoming HCI events from the controller, a workaround for a possible flow control issue in the HCI over IPC implementation.

samples: bluetooth: Enable PSA RNG on 54H in the LLPM sample

---

doc/nrf/releases_and_maturity/software_maturity.rst
subsys/bluetooth/controller/Kconfig
subsys/bluetooth/services/ras/Kconfig.ras
subsys/bluetooth/services/ras/rreq/Kconfig.ras_rreq
subsys/bluetooth/services/ras/rrsp/Kconfig.ras_rrsp

We dont want to make Channel Sounding an adopted feature

doc: Remove [EXPERIMENTAL] tag from Channel Sounding Kconfigs

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Backport 578095f45245789ca5e45d29a5f13fc8e0f11e59 from #21344.

[Backport v3.0-branch] doc: Clean changelog on 3.0.0 RC1

---

samples/nrf_rpc/protocols_serialization/server/CMakeLists.txt
samples/nrf_rpc/protocols_serialization/server/src/main.c

Wrap z_fatal_error() in order to turn off the RPC alive LED as soon as the fatal error occurs.

samples: nrf_rpc: ps_server: turn off alive LED on fatal error

---

samples/wifi/radio_test/multi_domain/radio_test_subcommands.rst
samples/wifi/radio_test/multi_domain/sample_description.rst
samples/wifi/radio_test/multi_domain/src/nrf_wifi_radio_test_shell.c

[SHEL-3021]: Implemented a new command in the Radio Test sample
to read and display battery voltage in mV.
[SHEL-3021]: https://nordicsemi.atlassian.net/browse/SHEL-3021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

samples: wifi: radio_test: Add command to read battery voltage

---

samples/wifi/radio_test/multi_domain/radio_test_subcommands.rst
samples/wifi/radio_test/multi_domain/sample_description.rst
samples/wifi/radio_test/multi_domain/src/nrf_wifi_radio_test_shell.c

Backport 773bdf7a5a55ca9a56c93125fbd8cd7abaf7d1e0~2..773bdf7a5a55ca9a56c93125fbd8cd7abaf7d1e0 from #20876.

[Backport v3.0-branch] samples: wifi: radio_test: Add command to read battery voltage

---

subsys/mpsl/init/Kconfig

For nRF54h20 we were usign QDEC130 interrupt for MPSL_LOW_PRIO_IRQN. That could cause a collision if a customer wants to use the peripheral.
Correct the IRQ number to SWI0(88) that is available in radio core and will not collide with cusomters using peripherals.

mpsl: init: Correct MPSL_LOW_PRIO_IRQN for 54h20

---

subsys/net/lib/downloader/src/transports/coap.c

Configure protocol type to DTLS/1.2 only if URI is coaps:// and then require sec_tag to be set.
If sec_tag is provided, but URI is coap:// just use normal UDP/DGRAM.
Does this need to be in NCS 3.0?

net: downloader: Don't expect DTLS even if sec_tag provided

---

applications/nrf5340_audio/src/bluetooth/bt_management/advertising/bt_mgmt_adv.c
applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c

- Add BT_LE_ADV_OPT_USE_IDENTITY when BT_PRIVACY=n
- This ensures a static address for debugging/testing purposes
- Removed old method of reading out FICR to set static addr manually
- OCT-3152

applications: nrf5340_audio: Use static address when privacy=n

---

west.yml

Latest fixes from nrf_wifi (including FW blobs).

wifi: Upmerge 2 (fixes only) (nrf_wifi)

---

sysbuild/CMakeLists.txt

Update to Kconfigs and manifest

Allow using hashing only for nrf54l devices, instead of ed25519 signature

---

samples/bluetooth/fast_pair/locator_tag/README.rst

Backport c6546981e01489ee9efbee43f664721d5bcabd05 from #21487.

[Backport v3.0-branch] doc: samples: fast_pair: locator_tag: Update the DFU signature type

---

doc/nrf/releases_and_maturity/software_maturity.rst
subsys/bluetooth/controller/Kconfig
subsys/bluetooth/services/ras/Kconfig.ras
subsys/bluetooth/services/ras/rreq/Kconfig.ras_rreq
subsys/bluetooth/services/ras/rrsp/Kconfig.ras_rrsp

Backport a939310a7a766c7bdc62343b233a69010980f6f8 from #21389.

[Backport v3.0-branch] doc: Remove [EXPERIMENTAL] tag from Channel Sounding Kconfigs

---

applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/prj.conf
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/prj_dongle.conf
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/prj_release.conf
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/prj_release_dongle.conf

The DMA support is experimental, disabling the feature improves USB HID stability. Since nRF Desktop uses only small HID reports (report size is smaller than 64 bytes), enabling the DMA is not needed.
Jira: NCSDK-29547

applications: nrf_desktop: Disable UDC DWC2 DMA on nRF54H20 DK

---

subsys/mgmt/suitfu/src/suitfu_mgmt.c
subsys/mgmt/suitfu/src/suitfu_mgmt_priv.h
subsys/mgmt/suitfu/src/suitfu_mgmt_suit_cand_env_upload.c
subsys/mgmt/suitfu/src/suitfu_mgmt_suit_image_fetch.c

This commit fixes the issue with starting a new envelope transfer while the old one has not yet finished its cleanup.
This is done interrupting any image fetching which was in progress and waiting until the cleanup has finished.

mgmt: suit: Fix starting new candidate upload before ending previous

---

subsys/nrf_security/src/core/lite/psa_core_lite.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/cracenpsa.cmake
subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_ecdsa.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_eddsa.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_primitives.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ecc.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ecc.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ecdsa.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ed25519.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/hmac.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/hmac.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/rndinrange.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c
subsys/nrf_security/src/drivers/cracen/sicrypto/src/hmac.c
subsys/nrf_security/src/drivers/cracen/sicrypto/src/iksig.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/sxsymcrypt.cmake

Add support for ECDSA in cracenpsa
Directly using silexpk/sxsymcrypt
This bypasses sicrypto, which saves on flash usage 
Adding support for hmac without sicrypto.
Remove sicrypto implementation of ECDSA being
accessible from cracenpsa.
Various refactors to support this

nrf_security: drivers: cracen: Implement ECDSA in cracenpsa

---

west.yml

Updated sdk-zephyr contains optional HFINT calibration procedure that contains a fix for nRF54L Errata 30.

[Backport v3.0-branch] manifest: update sdk-zephyr to have fix for nRF54L Errata 30

---

samples/wifi/radio_test/multi_domain/src/nrf_wifi_radio_test_shell.c

Free RX capture buffer using nrf_wifi_osal_mem_free to fix RX capture data crash.

samples: wifi: radio_test: Fix RX capture crash

---

west.yml

NCS v3.0.0-rc1 has a bug in nRF54H20 driver that results in dead USB device if the cable is disconnected while hibernated. Pull in the fix that makes USB work just fine when connected again after the cable was disconnected while hibernated.

manifest: pull in nRF54H20 USB hibernation fix

---

applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/prj.conf
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/prj_dongle.conf
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/prj_release.conf
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/prj_release_dongle.conf

Backport a6c4c44dd3eba90a2acf0f2fd203794731017947 from #21466.

[Backport v3.0-branch] applications: nrf_desktop: Disable UDC DWC2 DMA on nRF54H20 DK

---

subsys/nfc/lib/platform.c

Backport 5d31704051562b37c1c81d60cafdc71bb519a982~2..5d31704051562b37c1c81d60cafdc71bb519a982 from #21371.

[Backport v3.0-branch] nfc: lib: platform: Update T4T buffer size

---

.github/test-spec.yml

Trigger downstream bootloader tests when changes done in subsys/nrf_security
because bootloader tests were not triggered here: https://github.com/nrfconnect/sdk-nrf/pull/21266

tests: Extend test-spec with new entry for CI-boot-test

---

tests/benchmarks/multicore/idle/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
tests/benchmarks/multicore/idle/boards/nrf54h20dk_nrf54h20_cpuapp_ram_high_usage.overlay
tests/benchmarks/multicore/idle/boards/nrf54h20dk_nrf54h20_cpuapp_ram_low_usage.overlay
tests/benchmarks/multicore/idle/remote/boards/nrf54h20dk_nrf54h20_cpurad.overlay
west.yml

Align overlays inside tests with the reverted RAM memory map.
Ref: NCSDK-32650

tests: Align with reverted memory ranges

---

tests/benchmarks/current_consumption/uarte_suspend/src/main.c

Busy wait at active state to make current consumption recognision easier.

tests: benchmarks: current_consumption: uarte_suspend: active busy

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ecdsa.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c

Fix the inclusion of of hashdefs.h.

nrf_security: Fix wrong include header in Cracen PSA

---

tests/drivers/audio/pdm_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_audiopll_44k1.overlay
tests/drivers/audio/pdm_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_audiopll_48k.overlay
tests/drivers/audio/pdm_loopback/boards/nrf54l20pdk_nrf54l20_cpuapp_aclk.overlay
tests/drivers/audio/pdm_loopback/testcase.yaml

Added test cases for ACLK on nRF54L20 and AudioPLL on nRF54H20.

tests: drivers: audio: pdm_loopback: add tests for audio clocks

---

.github/test-spec.yml

Trigger ci on all code changes without documentation

.github: test-spec: Extend CI-rs-test with nrf_security changes

---

CODEOWNERS

Text files are also present in the doc/ folder, assign those to the doc leads.

codeowners: Cover .txt files in doc/

---

tests/benchmarks/current_consumption/uarte_suspend/src/main.c

Backport ce81344453298217cf4c295d9c485cb58b924d6e from #21529.

[Backport v3.0-branch] tests: benchmarks: current_consumption: uarte_suspend: active busy

---

applications/nrf5340_audio/src/audio/Kconfig

Backport 464299064fba548c5a1275086ddc7b511c097c12 from #21298.

[Backport v3.0-branch] applications: nrf5340_audio: Removed comment

---

drivers/mpsl/flash_sync/CMakeLists.txt

Fixes an issue where an if was missing which would continually emit a warning about an empty library

drivers: mpsl: flash_sync: Fix missing if

---

subsys/partition_manager/Kconfig

Remove the workaround done for the TrustZone region size since it is no longer needed.
Ref: NCSDK-28541

partition_manager: Remove hardware model v1 workaround

---

doc/nrf/app_dev/device_guides/nrf70/wifi_advanced_security_modes.rst

Instead of a URL to upstream docs which may be out of sync with NCS, point to the NCS Zephyr RST page which will always be in sync with NCS.

doc: nrf70: Fix the link to Zephyr Wi-Fi management docs

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c

Add compiler definitions around algorithm selection in kmu. This means only needed algorithms are checked at runtime.Also means algorithm configs are required for importing keys which reduces size in most use cases

nrf_security: cracen: Size optimizations kmu

---

doc/nrf/protocols/bt/bt_mesh/dfu_over_ble.rst
samples/bluetooth/mesh/light/README.rst
samples/bluetooth/mesh/light/sample.yaml

This PR adds a note to FOTA DFU P2P for Bluetooth Mesh page that the `Erase application settings` option must be disabled before performing FOTA DFU, otherwise device will boot up unprovisioned unintentionally.
This PR also adds nRF5340DK to sample.yaml file of light sample for DFU overlay. The support was added in https://github.com/nrfconnect/sdk-nrf/pull/15592 but neither sample.yaml, nor `DFU requirements` section were updated.

Bluetooth: Mesh: Fix provisioning failed issue on non-secure nRF5340DK variant after P2P DFU

---

samples/wifi/radio_test/multi_domain/src/nrf_wifi_radio_test_shell.c

Backport fd3d09b52a53ab0699429ccbe59bf71157cfda53 from #21509.

[Backport v3.0-branch] samples: wifi: radio_test: Fix RX capture crash

---

include/bluetooth/services/ras.h
samples/bluetooth/channel_sounding_ras_initiator/src/main.c

The ranging counter is the lower 12 bits of the procedure counter. This fixes an issue where procedure counter and ranging counter values were compared directly.

bluetooth: services: Add helper ft for getting the ranging counter

---

applications/nrf5340_audio/src/bluetooth/bt_management/advertising/bt_mgmt_adv.c
applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c

Backport ef585d6eb695e75eec446a0feea0f8ed36484b56 from #21421.

[Backport v3.0-branch] applications: nrf5340_audio: Use static address when privacy=n

---

CODEOWNERS
dts/common/nordic/nrf54lm20a.dtsi
samples/zephyr/drivers/audio/dmic/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay
samples/zephyr/drivers/audio/dmic/sample.yaml
scripts/ci/tags.yaml
tests/drivers/audio/pdm_loopback/boards/nrf54l_aclk.overlay
tests/drivers/audio/pdm_loopback/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay
tests/drivers/audio/pdm_loopback/testcase.yaml
tests/drivers/pwm/gpio_loopback/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay
tests/drivers/pwm/gpio_loopback/testcase.yaml
tests/zephyr/drivers/audio/dmic_api/CMakeLists.txt
tests/zephyr/drivers/audio/dmic_api/README.txt
tests/zephyr/drivers/audio/dmic_api/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay
tests/zephyr/drivers/audio/dmic_api/prj.conf
tests/zephyr/drivers/audio/dmic_api/testcase.yaml
tests/zephyr/drivers/i2s/i2s_api/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay
tests/zephyr/drivers/i2s/i2s_api/testcase.yaml
tests/zephyr/drivers/i2s/i2s_speed/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay
tests/zephyr/drivers/i2s/i2s_speed/testcase.yaml

Enable test execution on nRF54LM20A (no PDM, TDM nor PWM on nRF54LV10A).
No. | Name | nrf54LM20A
-- | -- | --
1 | nrf.extended.sample.drivers.audio.dmic | OK
2 | drivers.audio.pdm_loopback.nrf54l.1000khz | quarantine (NRFX-7154)
3 | drivers.audio.pdm_loopback.nrf54l20.1000khz | OK
4 | drivers.audio.pdm_loopback.nrf54l.1280khz | OK
5 | drivers.audio.pdm_loopback.nrf54l.1600khz | OK
6 | drivers.pwm.gpio_loopback | OK
7 | nrf.extended.drivers.audio.dmic_api | OK
8 | nrf.extended.drivers.i2s.i2s_api.gpio_loopback.54l | OK
9 | nrf.extended.drivers.i2s.i2s_speed.gpio_loopback.54l | quarantine (NRFX-7243)

Nrfx 7309 run tests on nrf54lm20apdk pt.2

---

west.yml

This suppresses the cmake Installing: ... messages output when CONFIG_TFM_BUILD_LOG_QUIET=y.

[Backport v3.0-branch] manifest: Bring TF-M with less cmake output

---

.github/test-spec.yml

The test coverage for nrf_security plans does not cover basic functionality used by Bluetooth.
https://github.com/nrfconnect/sdk-nrf/pull/21266 broke Bluetooth. Therefore we now extend the test scope
to prevent this from happening again.

test_spec: Run Bluetooth tests on nrf_security changes

---

samples/wifi/provisioning/ble/prj.conf

BLE crypto uses MbedTLS heap but doesn't configure the heap size and default heap is not enough for Wi-Fi.
Increase the heap size to accomodate both BLE and Wi-Fi.
Fixes SHEL-3560.

samples: wifi: provisioning: Fix MbedTLS heap size

---

doc/nrf/app_dev/device_guides/nrf70/wifi_advanced_security_modes.rst

Backport 1c111f33c95ccdfb3ce7a70f2b5747658cf63af0 from #21548.

[Backport v3.0-branch] doc: nrf70: Fix the link to Zephyr Wi-Fi management docs

---

modules/memfault-firmware-sdk/memfault_integration.c

In cases where an upstream device uploads data to Memfault on behalf of a downstream device, the project key is not required. This change allows the project key to be optional in those cases. For the NCS Memfault sources, this is when we are not using MDS or the Memfault Zephyr HTTP client.

modules: memfault: Check project key only when used to upload

---

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_configuration.rst

Backport 617df34c8d683ef04b12b0534fdb730245756966 from #21486.

[Backport v3.0-branch] doc: updated nRF54H20 configuration docs

---

samples/bluetooth/peripheral_uart/README.rst

Update testing steps (testing_with_nrf_connect_for_mobile) of the Peripheral UART sample:
* Added testing steps for ioS and Android devices.
* Provided detailed steps as the sample is featured in Quick Start.
NCSDK-32684
* Changed the term DK to development kit in the sample readme file, just for consistency.

doc: Update testing steps of the Peripheral UART sample

---

snippets/sdp/mspi/board/nrf54l15dk_nrf54l15_cpuapp.overlay
west.yml

- update zephyr SHA
- add necessary change in snippet

zephyr: update flash_mspi_nor

---

samples/wifi/provisioning/ble/prj.conf

Backport fe0c95e34f6411a6e1b23235afa79838cdabfe80 from #21543.

[Backport v3.0-branch] samples: wifi: provisioning: Fix MbedTLS heap size

---

.github/workflows/docbuild.yml

`/g` was missing, so it was only applied on first occurence.

ci: docbuild: apply Doxygen link patches to all occurrences

---

snippets/sdp/mspi/board/nrf54l15dk_nrf54l15_cpuapp.overlay
west.yml

Backport #21325 to v3.0-branch

Backport #21325

---

modules/openthread/CMakeLists.txt

OpenThread defines -Wc99-extension warning to warn in case OpenThread itself tries to use GNU c99 extensions.
However, this compile option propagates to Zephyr headers when those are included in an OpenThread build. This happens through mbed TLS where NCS provides a glue for mbedTLS threading to use Zephyr's threading mechanism. Zephyr itself uses GNU c99 extensions in a few places.
Therefore, disable -Wc99-extension when building OpenThread with clang.
Note, the warning is only supported by clang and not by gcc and therefore the warning is never seen with gcc, although the same GNU c99 extensions are used in this case.

cmake: disable c99-extension warning

---

include/logging/log_rpc.h
samples/nrf_rpc/protocols_serialization/client/src/log_rpc_shell.c
subsys/logging/log_backend_rpc.c
subsys/logging/log_forwarder_rpc.c
subsys/logging/log_rpc_group.h

Add RPC command to set the current time on the remote device that should be used for log timestamping.

log_rpc: add RPC command to sync log timestamps

---

CODEOWNERS
doc/nrf/app_dev/bootloaders_dfu/qspi_xip_split_image.rst

Adds a configuration file so that this sample can be flashed on a
thingy53 using nrfutil
Ref: NCSDK-30142
Requires that the new nrfutil flash runner parts are brought in via cherry-pick or upmerge

samples: nrf5340: extxip_smp_svr: Add nrfutil flash runner config

---

tests/benchmarks/multicore/idle_exmif/testcase.yaml
tests/benchmarks/multicore/idle_hpu_temp_meas/testcase.yaml
tests/benchmarks/multicore/idle_spim/testcase.yaml
tests/benchmarks/multicore/idle_twim/testcase.yaml
tests/benchmarks/multicore/idle_uarte/testcase.yaml

These are tested with different supply voltages and require more time to execute.

tests: benchmarks: Extend timeouts for I/O multicore benchmarks

---

modules/openthread/CMakeLists.txt

Backport 055626798b3c26a210a3fbe1ccce90630367eccd from #21604.

[Backport v3.0-branch] cmake: disable c99-extension warning

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c

ed25519ph would return PSA_ERROR_NOT_SUPPORTED

nrf_security: cracen: Fix ed25519ph sign bug

---

doc/nrf/security/tfm/tfm_supported_services.rst

Updated the list of limitations for TF-M.
NCSDK-32307.

doc: security: updated tfm limitations

---

doc/nrf/protocols/bt/bt_mesh/dfu_over_ble.rst
samples/bluetooth/mesh/light/README.rst
samples/bluetooth/mesh/light/sample.yaml

This is a manual backport of #21522 PR to v3.0-branch since backport PR bot is not working.

[Backport v3.0-branch] Bluetooth: Mesh: Fix provisioning failed issue on non-secure nRF5340DK variant after P2P DFU

---

samples/bluetooth/peripheral_uart/README.rst

Backport 051cce44210010252b787bfd13c78f8a64d9342b from #21373.

[Backport v3.0-branch] doc: Update testing steps of the Peripheral UART sample

---

CODEOWNERS
doc/nrf/app_dev/bootloaders_dfu/qspi_xip_split_image.rst

Backport d58029303355cd9dfe5e4e682440c3276d69f6b0~2..d58029303355cd9dfe5e4e682440c3276d69f6b0 from #20275.

[Backport v3.0-branch] samples: nrf5340: extxip_smp_svr: Add nrfutil flash runner config

---

samples/bluetooth/llpm/boards/nrf54h20dk_nrf54h20_cpuapp.conf
samples/bluetooth/llpm/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
samples/bluetooth/llpm/sysbuild/ipc_radio/boards/nrf54h20dk_nrf54h20_cpurad.conf
samples/bluetooth/llpm/sysbuild/ipc_radio/boards/nrf54h20dk_nrf54h20_cpurad.overlay

Backport 4e711da5d363cd34fc22492abde2a72685af80ba from #21410.

[Backport v3.0-branch] samples: bluetooth: Enable PSA RNG on 54H in the LLPM sample

---

doc/nrf/app_dev/device_guides/nrf54l/cryptography.rst

Document that lockable KMU keys are now identified by providing CRACEN_KEY_PERSISTENCE_READ_ONLY as part of the key lifetime attribute.

doc: Update PSA key attribute name for lockable KMU keys

---

modules/openthread/platform/diag.c
subsys/net/openthread/rpc/server/ot_rpc_netdiag.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ecdsa.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c
west.yml

clang: Fix multiple warnings

---

tests/benchmarks/current_consumption/nrf54l_errata30_idle/CMakeLists.txt
tests/benchmarks/current_consumption/nrf54l_errata30_idle/prj.conf
tests/benchmarks/current_consumption/nrf54l_errata30_idle/src/main.c
tests/benchmarks/current_consumption/nrf54l_errata30_idle/testcase.yaml

Workaround for nRF54L Errata 30 might negatively impact power consumption. Create a test to verify it.

tests: current_consumption: nrf54l: add test for Errata 30 workaround

---

applications/serial_lte_modem/doc/slm_description.rst
doc/nrf/libraries/modem/modem_slm.rst
samples/cellular/slm_shell/README.rst

Backport 66bb9d9c7812300cd57addc09cc5d06ee59ed1e9~4..66bb9d9c7812300cd57addc09cc5d06ee59ed1e9 from #21464.

[Backport v3.0-branch] applications: serial_lte_modem: doc: Improve PIN assignment instructions

---

tests/benchmarks/multicore/idle/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
tests/benchmarks/multicore/idle/boards/nrf54h20dk_nrf54h20_cpuapp_ram_high_usage.overlay
tests/benchmarks/multicore/idle/boards/nrf54h20dk_nrf54h20_cpuapp_ram_low_usage.overlay
tests/benchmarks/multicore/idle/remote/boards/nrf54h20dk_nrf54h20_cpurad.overlay
west.yml

Align overlays inside tests with the reverted RAM memory map.
Ref: NCSDK-32650

[Backport v3.0-branch]  tests: Align with memory ranges revert

---

doc/nrf/app_dev/device_guides/nrf54l/cryptography.rst

Backport 221b3d1ce502e7d6e25858c4d89007a8d042481c from #21614.

[Backport v3.0-branch] doc: Update PSA key attribute name for lockable KMU keys

---

samples/zephyr/drivers/jesd216/sample.yaml
samples/zephyr/drivers/spi_flash/sample.yaml

Current filter doesn't work as expected.
Samples are build for nrf54l20pdk and nrf54l09pdk.
After applying
boards/nrf54l15dk_nrf54l15_cpuapp_sqspi.overlay
devicetree error is reported - undefined node label 'mx25r64'.
Add platform_allow section.
Limit execution of the sample to nrf54l15dk only.

Nrfx none improve test filter

---

tests/benchmarks/current_consumption/nrf54l_errata30_idle/CMakeLists.txt
tests/benchmarks/current_consumption/nrf54l_errata30_idle/prj.conf
tests/benchmarks/current_consumption/nrf54l_errata30_idle/src/main.c
tests/benchmarks/current_consumption/nrf54l_errata30_idle/testcase.yaml

Backport 1e47150de6c2df30129b4b8f5a2e8ca50f8cfdc0 from #21622.

[Backport v3.0-branch] tests: current_consumption: nrf54l: add test for Errata 30 workaround

---

samples/matter/lock/src/app_task.cpp

Don't pass credentials to `DoorLockServer::SetLockState` until project-chip/connectedhomeip#38222 is fixed.

samples: matter: lock: Add workaround for TC-DRLK 2.3

---

tests/benchmarks/current_consumption/beacon_vs_vddh/CMakeLists.txt
tests/benchmarks/current_consumption/beacon_vs_vddh/prj.conf
tests/benchmarks/current_consumption/beacon_vs_vddh/testcase.yaml

Check advertising startup and average current consumption.

tests: benchmarks: Test BT advertising with different VDDH for nrf54h

---

doc/nrf/libraries/security/nrf_security/doc/drivers.rst
doc/nrf/nrf.doxyfile.in
subsys/nrf_security/include/nrf_security_api_structure.h

Added a container for Nordic-specific crypto driver contexts. This container adds doxygen groups for the crypto driver contexts files at subsys/nrf_security/include/psa. It also links directly to the Oberon API module and other files used in the Nordic implementation. NCSDK-30040.
----
- Doxygen API doc quality in the headers will be improved in NCSDK-33026
- No changelog entry

doc: crypto: add crypto_driver_contexts_* API

---

sysbuild/CMakeLists.txt

Backport 03f769e23932c615bd543389d6e70f4aca87fa53 from #21048.

[Backport v3.0-branch] Allow using hashing only for nrf54l devices, instead of ed25519 signature

---

doc/nrf/releases_and_maturity/software_maturity.rst

Split Oberon PSA Crypto maturity into a separate row per crypto driver. 
Removing footnote that attestation service is not working on nRF54L15.

doc: Update TF-M and PSA Crypto maturity sections

---

samples/zephyr/drivers/jesd216/sample.yaml
samples/zephyr/drivers/spi_flash/sample.yaml

Backport 9ba5ae2ed7933d122c34d917b384986c9fe24485~2..9ba5ae2ed7933d122c34d917b384986c9fe24485 from #21672.

[Backport v3.0-branch] Nrfx none improve test filter

---

samples/wifi/ble_coex/README.rst
samples/wifi/ble_coex/sample.yaml
samples/wifi/thread_coex/README.rst
samples/wifi/thread_coex/sample.yaml

Due to missing coex node for network core, coex functionality is not enabled.
Fix by passing the coex shield to the ipc_radio image also.

samples: wifi: coex: Fix shield configuration for CPUNET

---

samples/matter/lock/Kconfig
samples/matter/lock/src/app_task.cpp

Replace `#if 0` with Kconfig.
This is a follow-up to #21654.

samples: matter: lock: Add Kconfig for passing credentials to SetLockState

---

tests/zephyr/drivers/i2s/i2s_api/boards/tdm_audiopll.overlay
tests/zephyr/drivers/i2s/i2s_api/testcase.yaml
tests/zephyr/drivers/i2s/i2s_speed/boards/tdm_audiopll.overlay
tests/zephyr/drivers/i2s/i2s_speed/testcase.yaml

Add testcase with audioPLL enabled for nRF54H20 appcore.

test: zephyr: drivers: i2s: Add testing with audiopll

---

tests/subsys/kmu/pytest/test_kmu_revoke_in_app.py

The tests were occasionally failing due to timing issues between buffer clearing and board reset operations. In some instances, a "Destroy failed" message would be received after calling clear_buffer() but before reset_board() completed. This message was incorrectly matched, causing the test to not wait for the actual expected response, resulting in false negative test results.

tests: fix unstable KMU revocation test on nrf54l15

---

applications/nrf_desktop/configuration/nrf52840dk_nrf52840/images/mcuboot/prj_mcuboot_smp.conf

Change disables MCUboot LTO to workaround application boot failures.
Jira: NCSDK-32981

applications: nrf_desktop: Workaround nrf52840dk mcuboot_smp boot fail

---

sysbuild/CMakeLists.txt
sysbuild/Kconfig.mcuboot

Added Sysbuild's option for selection whether MCUboot shall use shared crypto provided by NSIB.
ref.: NCSIDB-1515

sysbuild/Kconfig.mcuboot: allow to disable external crypoto usage

---

samples/matter/lock/src/app_task.cpp

Backport 0222480e8a801adde165845917f057eadcbe4c81 from #21654.

[Backport v3.0-branch] samples: matter: lock: Add workaround for TC-DRLK 2.3

---

modules/openthread/platform/diag.c
subsys/net/openthread/rpc/server/ot_rpc_netdiag.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ecdsa.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c
west.yml

Backport of #21616
Including backport of https://github.com/nrfconnect/sdk-nrf/pull/21099 to match other clang warning backport fixes.

[v3.0-branch] clang: Fix multiple warnings

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_primitives.h
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/include/sxsymcrypt/internal.h

There is an input_buffer in the Cracen MAC driver
which is used to store intermediate data when needed. The size of this buffer was chosen based on the maximum hash block size. Since there was some hash optimizations merged earlier the maximum hash block size can now be 1 and this is problematic for cases where only CMAC is being used.
This fixes this by setting the buffer accortingly when only CMAC is enabled.

nrf_security: Fix for PSA MAC context in Cracen

---

applications/nrf_desktop/configuration/nrf52840dk_nrf52840/images/mcuboot/prj_mcuboot_smp.conf

Backport 0abbf6e7ad7a8de6dbc83227a735ac63144ce6f4 from #21629.

[Backport v3.0-branch] applications: nrf_desktop: Workaround nrf52840dk mcuboot_smp boot fail

---

drivers/mpsl/clock_control/nrfx_clock_mpsl.c
tests/drivers/audio/pdm_loopback/src/main.c
west.yml

Backport of https://github.com/nrfconnect/sdk-nrf/pull/21631

[Backport v3.0-branch] Add support for XOTUNE event

---

boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a_cpuapp_0_2_0.overlay

There is a mistake on PCA10197. Any occurrence of P1.26 is in fact MCU's P1.24.

boards: nordic: nrf54lm20apdk: Fix Button0 PCB mistake

---

tests/subsys/kmu/pytest/test_kmu_revoke_in_app.py

Backport ccc6ea882bd8da4212bf16c55cf954aef92f5b71 from #21714.

[Backport v3.0-branch] tests: fix unstable KMU revocation test on nrf54l15

---

doc/nrf/app_dev/device_guides/fem/fem_nrf21540_gpio.rst
west.yml

This PR brings Zephyr with updated default `tx-en-settle-time-us` for the nrf21540 FEM to fix the spurious emission issue.

manifest: update zephyr to contain nrf21540 tx-en timing fix

---

boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a_cpuapp_0_2_0.yaml

Add info that DK supports spi.
Needed for test execution.

boards: nordic: nrf54lm20apdk: support spi at DK

---

samples/bluetooth/conn_time_sync/src/central.c

In the disconnected callback, the array index of conn_state associated with the disconnected connection is cleared using memset. However, the size of the memset is set to the entire conn_state array size and not the size of a single element. This leads to faults due to clearing out of bounds memory if more than one device is connected to the central.

samples: conn_time_sync: Fix out of bounds behavior of conn_state memset 

---

samples/matter/manufacturer_specific/pm_static_nrf54l15dk_nrf54l10_cpuapp.yml
samples/matter/manufacturer_specific/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l10_cpuapp.conf
samples/matter/smoke_co_alarm/pm_static_nrf54l15dk_nrf54l10_cpuapp.yml
samples/matter/smoke_co_alarm/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l10_cpuapp.conf
samples/matter/template/pm_static_nrf54l15dk_nrf54l10_cpuapp.yml
samples/matter/template/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l10_cpuapp.conf

The partitions for nRF54L10 were aligned to 0x800 what is not allowed and because of that the DFU was failing. Additionally, the size used by pm for partitions had to be reduced from 1022 to 1020 kB.

samples: matter: Fixed DFU for nRF54L10

---

samples/bluetooth/fast_pair/locator_tag/configuration/pm_static_nrf5340dk_nrf5340_cpuapp_ns.yml
samples/bluetooth/fast_pair/locator_tag/configuration/pm_static_thingy53_nrf5340_cpuapp_ns.yml

Fixed the DFU issue for the non-secure targets that are based on the nRF53 SoC:
- thingy53/nrf5340/cpuapp/ns
- nrf5340dk/nrf5340/cpuapp/ns
Due to the misaligned partition size of the Primary and the Secondary slots, the MCUboot bootloader was unable to boot the new firmware correctly.
Aligned the size of the Primary and the Secondary slots to fix this issue.
Ref: NCSDK-33065

samples: bluetooth: fast_pair: locator_tag: fix DFU for nRF53 NS targets

---

tests/zephyr/drivers/spi/spi_controller_peripheral/testcase.yaml
tests/zephyr/drivers/spi/spi_error_cases/testcase.yaml
tests/zephyr/drivers/spi/spi_loopback/testcase.yaml

Allow twister execution at @0.2.0

tests: zephyr: drivers: spi: LM20@0.2.0 DK

---

samples/zephyr/drivers/watchdog/sample.yaml
tests/zephyr/drivers/watchdog/wdt_basic_api/testcase.yaml
tests/zephyr/drivers/watchdog/wdt_error_cases/testcase.yaml

Allow twister execution at @0.2.0

tests: zephyr: drivers: watchdog: support LM20@0.2.0 DK

---

tests/zephyr/drivers/timer/nrf_grtc_timer/testcase.yaml

tests: zephyr: drivers: timer: nrf_grtc_timer: enable for LM20 DK

---

tests/drivers/gpio/gpio_more_loops/testcase.yaml
tests/zephyr/drivers/gpio/gpio_basic_api/testcase.yaml

Allow twister execution at @0.2.0

tests: zephyr: drivers: gpio: LM20@0.2.0 DK

---

samples/bluetooth/fast_pair/locator_tag/configuration/pm_static_nrf5340dk_nrf5340_cpuapp_ns.yml
samples/bluetooth/fast_pair/locator_tag/configuration/pm_static_thingy53_nrf5340_cpuapp_ns.yml

Backport 64c0fc7753dc846e1bf1454c3e06e6bc6aadbf4a from #21762.

[Backport v3.0-branch] samples: bluetooth: fast_pair: locator_tag: fix DFU for nRF53 NS targets

---

samples/matter/lock/Kconfig
samples/matter/lock/src/app_task.cpp

Backport 8d871a8ded5f9ad9dc451718b0b15e826273c934 from #21696.

[Backport v3.0-branch] samples: matter: lock: Add Kconfig for passing credentials to SetLockState

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_primitives.h
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/include/sxsymcrypt/internal.h

Backport 99b35cb2b34ea5626544ad9049df993828b631d3 from #21685.

[Backport v3.0-branch] nrf_security: Fix for PSA MAC context in Cracen

---

samples/peripheral/802154_sniffer/README.rst
samples/peripheral/802154_sniffer/src/main.c

Add `bootloader` command that allows nRF52840 dongle to reboot into bootloader by pulling the P0.19 GPIO pim connected to reset to GND.
This allows easy reflashing of the dongle without physical access to the device.

samples: 802154_sniffer: add `bootloader` command.

---

doc/nrf/app_dev/device_guides/nrf53/qspi_xip_guide_nrf5340.rst
doc/nrf/app_dev/device_guides/nrf70/fw_patches_ext_flash.rst

Backport 65a713923314649ad11391076e025052d3592911 from #20957.

[Backport v3.0-branch] doc/device_guide: nrfutil for qspi

---

samples/wifi/ble_coex/README.rst
samples/wifi/ble_coex/sample.yaml
samples/wifi/thread_coex/README.rst
samples/wifi/thread_coex/sample.yaml

Backport 8191bcc5039aea89f92385062fa9db85deacc855 from #21649.

[Backport v3.0-branch] samples: wifi: coex: Fix shield configuration for CPUNET

---

samples/wifi/radio_test/multi_domain/sample.yaml

Remove `test_combo` build spport on EK due to pin conflict that cause Wi-Fi to not function properly.

samples: wifi: radio_test: Remove combo build support on EK

---

doc/nrf/protocols/matter/end_product/test_event_triggers.rst
doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
samples/matter/common/config.rst

The documentation for matter diagnostic logs snippet contains invalid snippet name.

doc: Fixed docs for matter diagnostic logs snippet

---

samples/bluetooth/peripheral_power_profiling/README.rst
samples/bluetooth/peripheral_power_profiling/prj.conf

To reduce power as much as possible in Power Profiling, this commit disables UART console by default in all targets.

samples: bluetooth: Disable console by default in Power Profiling

---

west.yml

brings fix which  allows to build MCUboot for nrf7002dk/nrf5340/cpuapp
with default configuration.

manifest: bump sdk-mcuboot

---

tests/zephyr/boards/nrf/hwinfo/reset_cause/testcase.yaml

tests: zephyr: boards: nrf: hwinfo: enable for LM20 DK

---

boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a_cpuapp_0_2_0.overlay
tests/drivers/pwm/gpio_loopback/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay
tests/drivers/pwm/gpio_loopback/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay
tests/drivers/pwm/gpio_loopback/testcase.yaml

Align PWM output for LED1 pin.

tests: drivers: pwm: gpio_loopback: enable for LM20 DK

---

subsys/bluetooth/cs_de/cs_de.c

With the new MLT 2.1 metal fix we've observed that changes in internal delays have caused us to produce negative TOF in some cases.
It's not possible for users to make sense of such results. To avoid confusion we should set these as bad.

bluetooth: services: Set RTT estimate to NAN if negative

---

west.yml

Documentation updates for sQSPI
Brings in: https://github.com/nrfconnect/sdk-nrfxlib/pull/1724

[Backport v3.0-branch] manifest: softperipheral: Documentation

---

lib/fprotect/sys_init_fprotect.c

Fixes wrongly including partition manager file when partition manager is not enabled

lib: fprotect: Fix wrong include check

---

doc/nrf/protocols/matter/end_product/test_event_triggers.rst
doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
samples/matter/common/config.rst

Backport d38bfab7c1191d2ffe24e39f2fa0d1d533ca7ab6 from #21793.

[Backport v3.0-branch] doc: Fixed docs for matter diagnostic logs snippet

---

doc/nrf/app_dev/device_guides/nrf54l/index.rst

Backport dbcf3ee6d67ac7e4c3f2df61a85b86860c1d9ad7 from #21690.

[Backport v3.0-branch] doc: add nrf54l15 supported dk revisions

---

doc/nrf/includes/wifi_credentials_shell.txt
samples/net/http_server/README.rst
samples/wifi/shell/README.rst

Wi-Fi cred shell has been renamed from wifi_cred to wifi cred.
SHEL-3589

doc: Rename command wifi_cred to wifi cred

---

samples/bluetooth/peripheral_hids_keyboard/app.overlay
samples/bluetooth/peripheral_hids_keyboard/boards/nrf54h20dk_nrf54h20_cpuapp.overlay

I dedicate this change to @MarekPieta, who wanted to make this feature work for NCS 3.0.
Notes:
- The commit adding the `app.overlay` would be reverted once the change from the following Zephyr PR is moved to NCS:
https://github.com/zephyrproject-rtos/zephyr/pull/88637
- Remove the v3.0 release from the affected releases list in the corresponding known issue that is part of the following PR:
https://github.com/nrfconnect/sdk-nrf/pull/21388
- Create a comment with a changelog entry suggestion in the release note PR:
https://github.com/nrfconnect/sdk-nrf/pull/21339

Bluetooth Peripheral HIDS keyboard: making the NFC Kconfig available

---

.github/workflows/compliance.yml
.github/workflows/docbuild.yml
.github/workflows/license-reusable.yml
.github/workflows/validate-pip-requirements-fixed-file.yml
.github/workflows/west-commands.yml

We use mostly on pull_request  will already checkouts merged code when checkout action is used without arguments. Trying to align all the actions to use same approach except compliance workflow which checks that no merge commits are created.

ci: remove rebases from actions

---

.github/workflows/stale.yml

Problem with using default token is that docremove action is not triggered when PR gets closed. Changing token should fix this problem.

ci: use different token in stale action

---

tests/benchmarks/multicore/idle_clock_control/Kconfig
tests/benchmarks/multicore/idle_clock_control/src/main.c
tests/benchmarks/multicore/idle_clock_control/testcase.yaml

Use fixtures to differentiate regular and lfrc setup

  tests: benchmarks: idle_clock_control: Fix current measurement test

---

samples/bluetooth/peripheral_power_profiling/README.rst
samples/bluetooth/peripheral_power_profiling/prj.conf

Backport 8ab384ae9d2f341edf527c3e793646670e64f7c0 from #21528.

[Backport v3.0-branch] samples: bluetooth: Disable console by default in Power Profiling

---

doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_main_config.rst
doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_mcuboot_nsib.rst

Added page which describes bare-minimum of Major's configuration
details of MCUboot.
Ref.: NCSDK-32409, NCSDK-29716, NCSIDB-1373, NCSIDB-1373
Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>

doc/nrf/mcuboot_nsib: Add page on main MCUboot's Kconfig

---

doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_adding_sysbuild.rst
doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_signature_keys.rst
doc/nrf/app_dev/device_guides/nrf54l/kmu_basics.rst
doc/nrf/app_dev/device_guides/nrf54l/kmu_provision.rst

Minimal doc update for NSIB@nRF54L on:
NSIB keys, NSIB key revocation, mcuboot key revocation.

doc/nrf/bootloader: nRF54L: updates on key management

---

subsys/bluetooth/cs_de/cs_de.c

Backport 4e15fed7e3e1c0fefdd74412e30e4edb7211eff0 from #21674.

[Backport v3.0-branch] bluetooth: services: Set RTT estimate to NAN if negative

---

doc/nrf/includes/wifi_credentials_shell.txt
samples/net/http_server/README.rst
samples/wifi/shell/README.rst

Backport 153c22b02c6c2fd93f41428d36bbba5cdb7ff6bc from #21834.

[Backport v3.0-branch] doc: Rename command wifi_cred to wifi cred

---

samples/wifi/shutdown/sample.yaml

Remove the support for the 54L target due to pin conflicts.
Fixes SHEL-3476.

samples: wifi: shutdown: Remove support for the 54L target

---

samples/peripheral/lpuart/README.rst

Backport 96410d61994371dd1e70a92f89c07cf21a35982a from #21826.

[Backport v3.0-branch] samples: peripheral: lpuart: remove old board names

---

samples/wifi/ble_coex/CMakeLists.txt
samples/wifi/ble_coex/dts.overlay
samples/wifi/thread_coex/CMakeLists.txt
samples/wifi/thread_coex/dts.overlay

This was done at the beginning as a temporary fix and is definitely not cross-platform, so, remove it to avoid build errors for 54 Series.

samples: wifi: ble_coex: Remove stale DTS overlay

---

applications/nrf_desktop/configuration/nrf52840dk_nrf52840/images/mcuboot/prj_mcuboot_smp.conf

Using RTT for logs in both application and bootloader leads to issues. Disable RTT in bootloader as a workaround.
Jira: NCSDK-33038

applications: nrf_desktop: Workaround nrf52840dk mcuboot_smp RTT issues

---

boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a_cpuapp_0_2_0.yaml
tests/zephyr/drivers/i2s/i2s_api/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay
tests/zephyr/drivers/i2s/i2s_api/testcase.yaml
tests/zephyr/drivers/i2s/i2s_speed/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay
tests/zephyr/drivers/i2s/i2s_speed/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay
tests/zephyr/drivers/i2s/i2s_speed/testcase.yaml

Add overlays required to run I2S tests on nrf54lm20a PDK.

tests: zephyr: drivers: i2s: Enable tests on PCA10197

---

subsys/mpsl/pm/mpsl_pm_utils.c

The LOW_LATENCY_PM_BIT and LOW_LATENCY_MRAM_BIT had the same value. The MPSL was notified about completion of low latency request before it actually happened.
The if statement in m_register_latency() for MRAM always returned true because of use of the same bit number for both constants.

mpsl: pm: Don't use the same bit for MRAM and PM requests

---

doc/nrf/app_dev/bootloaders_dfu/qspi_xip_split_image.rst

Replace nrfjprog usage for QSPI XIP split image support with experimental nrfutil file which needs confirmed by nrfutil team

doc: nrf: app_dev: bootloaders_dfu: Replace nrjprog usage in QSPI XIP

---

cmake/sysbuild/b0_mcuboot_signing.cmake

Fix typo in Kconfig property check. Image was signed always as for a pre-hashed signature which caused that this didn't work for PURE ED25519.

cmake/sysbuild/b0_mcuboot_signing: fixed signing with PURE signature

---

samples/wifi/ble_coex/CMakeLists.txt
samples/wifi/ble_coex/dts.overlay
samples/wifi/thread_coex/CMakeLists.txt
samples/wifi/thread_coex/dts.overlay

Backport 58cc904f237b4d6ffc33abf5e7ae098a48a5cb7e from #21849.

[Backport v3.0-branch] samples: wifi: ble_coex: Remove stale DTS overlay

---

doc/nrf/app_dev/bootloaders_dfu/qspi_xip_split_image.rst

Replace nrfjprog usage for QSPI XIP split image support with experimental nrfutil file which needs confirmed by nrfutil team

[v3.0-branch] doc: nrf: app_dev: bootloaders_dfu: Replace nrjprog usage in QSPI XIP

---

applications/serial_lte_modem/doc/SOCKET_AT_commands.rst

Backport 5abf4cabc6f5fcead8388453605f9bc1a605291a~2..5abf4cabc6f5fcead8388453605f9bc1a605291a from #21851.

[Backport v3.0-branch] Revert "applications: serial_lte_modem: doc: update socket options"

---

CODEOWNERS
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
subsys/debug/CMakeLists.txt
subsys/debug/Kconfig
subsys/debug/coredump/CMakeLists.txt
subsys/debug/coredump/Kconfig
subsys/debug/coredump/coredump_backend_nrf_flash_partition.c

Add Zephyr core dump backend that saves a core dump to the internal flash or RRAM partition named "coredump_partition".
This backend is an alternative to BACKEND_FLASH_PARTITION provided by Zephyr but it bypasses Zephyr flash device layer and uses nrfx directly, which offers the following benefits:
1. Bypasses synchronization primitives used by Zephyr flash or RRAM drivers. Currently, Zephyr flash drivers cannot be used to write to flash from a fault handler because of this.
2. Works with Partition Manager.
3. Minimizes the dependencies needed to successfully write a core dump, which is important as the core dump often needs to be written when the system is in the corrupted state.
Only flash and RRAM are supported for now (no MRAM support).

debug: coredump: add internal flash backend based on nrfx

---

scripts/docker/Dockerfile

Backport 62bd0654a3be6d213a60906af0d134b5f3494741 from #21901.

[Backport v3.0-branch] docker: Update nrfutil device to 2.8.8

---

cmake/sysbuild/b0_mcuboot_signing.cmake

Fix typo in Kconfig property check. Image was signed always as for a pre-hashed signature which caused that this didn't work for PURE ED25519.
Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>
(cherry picked from commit 73186d5a985df38ff5d0ba12344716a293fad16a)

[v3.0-branch] cmake/sysbuild/b0_mcuboot_signing: fixed signing with PURE signature

---

doc/nrf/protocols/wifi/stack_configuration.rst

Backport 3f915f397550df7169aaff3fe76e119d6b3eb1de from #21816.

[Backport v3.0-branch] doc: wifi: Add Usage profiles Throughputs

---

doc/nrf/releases_and_maturity/software_maturity.rst

Updated the Software Maturity tables for the Google Fast Pair category to align the documentation with the current status of nRF Connect SDK v3.0.0 codebase.

doc: sml: fast_pair: update for NCS v3.0.0

---

sysbuild/CMakeLists.txt
sysbuild/Kconfig.mcuboot

Backport 115d4d77fc3aa6746dc51d7c624dfe205c01aa2d from #21432.

[Backport v3.0-branch] sysbuild/Kconfig.mcuboot: allow to disable external crypoto usage

---

west.yml

Update sdk-zephyr with reduced restore time from s2ram.
Manual backport of #21497 and #21863

[Backport v4.0.99-ncs1-branch] manifest: Update sdk-zephyr revision

---

west.yml

Use the nrfconnect/sdk-hostap instead of sdk-zephyr/hostap to accomodate the fix for BTM testcase in QT.

manifest: sdk-hostap: Switch to sdk-hostap

---

tests/benchmarks/multicore/idle/testcase.yaml

Use fixtures to differentiate regular and lfrc setup and increase current limit in LFRC case.

tests: benchmarks: idle: Increase current limit at LFRC

---

tests/benchmarks/multicore/idle_clock_control/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
tests/benchmarks/multicore/idle_clock_control/src/main.c

Request different AUDIOPLL frequencies in the test.

tests: benchmarks: Add AUDIOPLL control to 'idle_clock_control' test

---

tests/benchmarks/multicore/idle_pwm_loopback/testcase.yaml

Prevent execution at DK without loopbacks.

tests: benchmarks: multicore: idle_pwm_loopback: add missing fixture

---

tests/benchmarks/multicore/idle_pwm_loopback/testcase.yaml

Backport dc28c690549286e17aec7f2c4f264221f84f7118 from #21959.

[Backport v3.0-branch] tests: benchmarks: multicore: idle_pwm_loopback: add missing fixture

---

tests/drivers/uart/uart_baudrate_test/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_uart00.overlay
tests/drivers/uart/uart_baudrate_test/testcase.yaml
tests/zephyr/drivers/uart/uart_async_api/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_uart00.overlay
tests/zephyr/drivers/uart/uart_async_api/testcase.yaml

tests: zephyr: drivers: uart: uart_async_api: fast uart at LM20

---

samples/wifi/raw_tx_packet/src/main.c

Without this, we see error prints for each and every packet.

samples: wifi: raw_tx_packet: Return in case of failure

---

samples/bluetooth/peripheral_power_profiling/sample.yaml

Extend timeout to fit all tests.

samples: bluetooth: peripheral_power_profiling: adjust timeouts

---

applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c

- Unregister SMP service if DFU mode is not active
- OCT-3356

applications: nrf5340_audio: Only register SMP when in DFU mode

---

samples/bluetooth/peripheral_power_profiling/sample.yaml

Backport 8ceb4154ea20684c34c5c4dc9b95bc07076bdcb9 from #21969.

[Backport v3.0-branch] samples: bluetooth: peripheral_power_profiling: adjust timeouts

---

samples/wifi/shell/Kconfig

Backport 338eb4aff970d7ed592f4663f0a683fd63256eb2 from #21956.

[Backport v3.0-branch] samples: wifi: shell: Increase network buffer pool sizes for nRF54H

---

samples/zephyr/drivers/audio/dmic/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay
samples/zephyr/drivers/audio/dmic/sample.yaml
tests/drivers/audio/pdm_loopback/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay
tests/drivers/audio/pdm_loopback/testcase.yaml
tests/zephyr/drivers/audio/dmic_api/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay
tests/zephyr/drivers/audio/dmic_api/testcase.yaml
west.yml

Add overlay that defines correct loopback to run the test on nRF54LM20A PDK.

Enable DMIC/PDM tests on nRF54LM20A PDK

---

applications/serial_lte_modem/sample.yaml
samples/cellular/slm_shell/sample.yaml

This is needed to have them in the supported devices list that is generated from the `integration_platforms` section of `sample.yaml`.
Similar change in slm_shell too.
These were fine-tuned to be more optimized in PR #21234 and PR #21267

applications: serial_lte_modem: Add all boards to integration_platforms

---

doc/nrf/libraries/security/nrf_security/doc/drivers.rst
doc/nrf/nrf.doxyfile.in
subsys/nrf_security/include/nrf_security_api_structure.h

Added a container for Nordic-specific crypto driver contexts. This container adds doxygen groups for the crypto driver contexts files at subsys/nrf_security/include/psa. It also links directly to the Oberon API module and other files used in the Nordic implementation. NCSDK-30040.

[Backport v3.0-branch] doc: crypto: add crypto_driver_contexts_* API

---

west.yml

Backport USB control transfer timeout fixes.

manifest: Update sdk-zephyr with USB backports

---

doc/nrf/libraries/bluetooth/services/fast_pair.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/bluetooth/fast_pair/locator_tag/src/main.c
subsys/bluetooth/services/fast_pair/fmdn/Kconfig
subsys/bluetooth/services/fast_pair/fmdn/ring.c

Fixes the CONFIG_BT_FAST_PAIR_FMDN_RING_REQ_TIMEOUT_DULT_MOTION_DETECTOR dependency. Now it depends on
CONFIG_BT_FAST_PAIR_FMDN_DULT_MOTION_DETECTOR. Aligns documentation. Also allows the locator tag sample to be built without motion detector support.
Jira: NCSDK-29944

bluetooth: fast_pair: fmdn: Fix Kconfig dependency misalignment

---

include/dfu/dfu_target_full_modem.h
include/net/nrf_cloud_alert.h

Backport 34de06968ace3f68b2b40098cbb1f4d6acd456d0~2..34de06968ace3f68b2b40098cbb1f4d6acd456d0 from #21646.

[Backport v3.0-branch]  Fix some C++ related build issues found.

---

doc/nrf/app_dev/device_guides/nrf54l/index.rst
doc/nrf/links.txt
doc/nrf/releases_and_maturity/known_issues.rst

doc: Update known issues for NCS v3.0.0

---

applications/serial_lte_modem/sample.yaml
samples/cellular/slm_shell/sample.yaml

Backport ce698d85cd6ac118d94bb4ac7cbf23ef610dcf41 from #21973.

[Backport v3.0-branch] applications: serial_lte_modem: Add all boards to integration_platforms

---

tests/drivers/timer/grtc_timer_lfrc/src/main.c

Relax timing expectation when using CONFIG_COVERAGE.

tests: drivers: timer: grtc_timer_lfrc: adjust for coverage mode

---

applications/nrf5340_audio/doc/feature_support.rst
doc/nrf/app_dev/device_guides/nrf54l/features.rst
doc/nrf/includes/install_sdk_common_prerequisites.txt
doc/nrf/installation/recommended_versions.rst
doc/nrf/links.txt
doc/nrf/releases_and_maturity.rst
doc/nrf/releases_and_maturity/known_issues.rst
doc/nrf/releases_and_maturity/migration/migration_guide_1.x_to_2.x.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.4.99-cs3_to_2.6.99-cs2.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.7.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.9.0-nRF54H20-1.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.9.rst
doc/nrf/releases_and_maturity/migration/migration_guide_3.0.rst
doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7.rst
doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs1.rst
doc/nrf/releases_and_maturity/migration/migration_guide_nRF54H20_cs_to_2_7_99-cs2.rst
doc/nrf/releases_and_maturity/migration/migration_hwmv2.rst
doc/nrf/releases_and_maturity/migration/migration_sysbuild.rst
doc/nrf/releases_and_maturity/migration_guides.rst
doc/nrf/releases_and_maturity/release_notes.rst
doc/nrf/releases_and_maturity/releases/release-notes-3.0.0.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/bluetooth/fast_pair/locator_tag/README.rst

doc: Add release notes for 3.0.0

---

samples/nrf_rpc/protocols_serialization/client/CMakeLists.txt
samples/nrf_rpc/protocols_serialization/client/snippets/ble/ble.conf
samples/nrf_rpc/protocols_serialization/client/src/bt_throughput_shell.c
samples/nrf_rpc/protocols_serialization/server/snippets/ble/ble.conf

Make it possible to run BLE throughput tests using the BLE over RPC architecture.
1. Clean BLE configuration of protocols serialization samples by removing unnecessary or default settings. Also, set the device name to "Nordic_PS".
2. Add BLE throughput service to the client sample. This requires enabline BT_SMP for both samples.
3. Add "bt_throughput advertise on" shell command, which is a replacement of "bt advertise on" that advertises the throughput service UUID.

samples: nrf_rpc: ps_client: add throughput service

---

dts/common/nordic/nrf54lm20a.dtsi

The radio in this product supports channel sounding.

dts: common: nordic: nrf54lm20a: Add CS radio capability

---

samples/bluetooth/throughput/src/main.c

According to the documentation of throughput sample, it is possible to change the default MTU, but the code hard-coded the GATT data length, so an attempt to use a reduced MTU ended up with a buffer allocation failure.

samples: bluetooth: throughput: allow reducing MTU

---

modules/openthread/platform/radio.c

Fix the return values of `otPlatRadioClearSrcMatchShortEntry` and `otPlatRadioClearSrcMatchExtEntry` to match the [OpenThread API](https://github.com/openthread/openthread/blob/3e7528e4e9cc992166dba8db471d063443d60710/include/openthread/platform/radio.h#L1078-L1098).

net: openthread: radio: fix otPlatRadioClearSrcMatch* return values

---

samples/matter/lock/src/access/access_storage.cpp

Backport d5d91c8c5f34ec2d233a945776b088a86ae39c8a from #20976.

[Backport v2.9-branch] samples: matter: lock: Use correct settings backend

---

applications/matter_bridge/src/app_task.cpp
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/matter/common/src/app/fabric_table_delegate.h
samples/matter/common/src/app/matter_event_handler.cpp
samples/matter/common/src/board/board.cpp
samples/matter/common/src/bridge/bridge_storage_manager.cpp
samples/matter/common/src/bridge/bridge_storage_manager.h
samples/matter/common/src/event_triggers/default_event_triggers.cpp
samples/matter/common/src/migration/migration_manager.cpp
samples/matter/common/src/persistent_storage/backends/persistent_storage_secure.cpp
samples/matter/common/src/persistent_storage/backends/persistent_storage_secure.h
samples/matter/common/src/persistent_storage/backends/persistent_storage_settings.cpp
samples/matter/common/src/persistent_storage/backends/persistent_storage_settings.h
samples/matter/common/src/persistent_storage/persistent_storage.h
samples/matter/common/src/persistent_storage/persistent_storage_impl.h
samples/matter/lock/Kconfig
samples/matter/lock/src/access/access_manager.cpp
samples/matter/lock/src/access/access_manager.h
samples/matter/lock/src/access/access_manager_credentials.cpp
samples/matter/lock/src/access/access_storage.cpp
samples/matter/lock/src/access/access_storage.h
samples/matter/lock/src/app_task.cpp
samples/matter/lock/src/bolt_lock_manager.cpp
samples/matter/lock/src/bolt_lock_manager.h
west.yml

- Remove old code handling clearing users/credentials from fabric as it's unused and not spec compilant.
- Implement factory reset for persistent storage.
- Handle factory reset event in lock and matter_bridge.
- Add common factory reset handler in matter_event_handler.
Fixes [KRKNWK-20041](https://nordicsemi.atlassian.net/browse/KRKNWK-20041)
[KRKNWK-20041]: https://nordicsemi.atlassian.net/browse/KRKNWK-20041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Backport v2.9-branch] matter: Add factory reset event handlers

---

subsys/esb/esb.c

Implementing back the usage of NRF_TIMER_TASK_SHUTDOWN for nRF52 family for the reason of FTPAN-78.
JIRA: NCSDK-31724

esb: Use NRF_TIMER_TASK_SHUTDOWN if supported

---

samples/cellular/nrf_provisioning/sample.yaml

Add the thingy91x as a supported board.

samples: nrf_provisioning: Add thingy91x

---

applications/serial_lte_modem/doc/SOCKET_AT_commands.rst

When creating raw socket with `<type>=3`, `<op>` parameter is unclear because values '1' and '2' refer to IPv4 and IPv6 sockets. So officially you couldn't create raw socket.
Implementation will translate <op> values of '1' and '2' into with `<type>=3` into using `AF_PACKET` as socket family so everything works nicely. Clarifying this into the documentation.

applications: serial_lte_modem: doc: Raw socket <op> clarified

---

CODEOWNERS

Tests under /nrf/test/lpuart will now
be owned also by ncs-low-level-test

codeowners: Add ncs-low-level-test as lpuart test owner

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cracen.c

-Wait for KMU busy signal for nRF54L20A and nRF54LV10A devices after
reset. This is a circumvention until this is added in MDK. This is done
in cracen_init which is called by psa_crypto_init.
Note: crypto_init is only run once in the system after reset
ref: NCSDK-33222

crypto: CRACEN: Ensure KMU status is not busy after reset

---

tests/drivers/lpuart/testcase.yaml

The configuration defined here casued a build failure in NCS 2.5.0. The issue was corrected. Testing is added to assure error will not come back.

tests: drivers: lpuart: Add user specific configuration test

---

samples/bluetooth/central_uart/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.conf
samples/bluetooth/central_uart/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay
samples/bluetooth/peripheral_uart/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.conf
samples/bluetooth/peripheral_uart/boards/nrf54lm20apdk_nrf54lm20a_cpuapp.overlay

Add support for nRF54LM20PDK in peripheral and central UART samples.

samples: peripheral_uart: central_uart: Add support for nRF54LM20PDK

---

boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a_cpuapp.dts

Commit https://github.com/nrfconnect/sdk-nrf/commit/b828ce71eafcfa3a00300226ac970adc1c725b0e enabled `bt_hci_sdc` and disabled `bt_hci_controller`, but `bt_hci_controller` is still set as the default controller.  
This commit updates the configuration to select `bt_hci_sdc` as the default controller.

boards: Select SDC for nRF54LM20A board

---

samples/cellular/nrf_cloud_multi_service/src/cloud_connection.c

The L4 up delay appears to be removable now, Wi-Fi is more stable.
IRIS-9476

samples: cellular: multi_service: Remove delay after L4 up

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
lib/at_parser/at_match.re
lib/at_parser/generated/at_match.c
tests/lib/at_parser/src/main.c

Adds support for parsing DECT NR+ modem firmware
names.

lib: at_parser: parse DECT NR+ mfw names

---

subsys/nrf_security/Kconfig.psa
subsys/nrf_security/src/zephyr/CMakeLists.txt

Allow users to disable the Zephyr SYS_INIT that invokes psa_crypto_init.
See kconfig help text for details.

nrf_security: Have psa_crypto_init.c be configurable

---

applications/serial_lte_modem/src/slm_at_sms.c

Collected rsp_buf for received concatenated SMS was from the stack. When 2nd and following parts were received, the first part was lost. So we always sent everything except the first part and not the #XSMS notification name and parameters other than the data. Moved rsp_buf to static RAM so it's preserved over multiple SMS parts.
Jira: LRCS-169

application: serial_lte_modem: sms: Fix receiving concatenated SMS

---

applications/serial_lte_modem/doc/PPP_AT_commands.rst
applications/serial_lte_modem/src/slm_ppp.c
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Add support for selecting PDN used with PPP connection into #XPPP command. E.g., AT#XPPP=1,1 for enabling PPP for PDP context with CID 1.
Jira: LRCS-149
TODO:

applications: serial_lte_modem: Add PPP PDN selection

---

CODEOWNERS
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/cellular/lte_ble_gateway/README.rst
samples/cellular/modem_shell/README.rst

The lte_ble_gateway sample is deprecated and shall be removed in the next release. The sample is not maintained and has not been updated in a while.

samples: cellular: deprecate lte_ble_gateway sample

---

samples/peripheral/lpuart/boards/nrf54lm20apdk_nrf54lm20a_cpuapp_0_0_0.overlay
samples/peripheral/lpuart/sample.yaml

Add overlay required to run the sample on nrf54lm20apdk@0.2.0 available on PCA10197.

samples: peripheral: lpuart: Enable sample on PCA10197

---

boards/nordic/nrf54lm20apdk/board.yml
boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a_cpuapp_0_2_0.overlay
boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a_cpuapp_0_2_0_csp.overlay
boards/nordic/nrf54lm20apdk/nrf54lm20apdk_nrf54lm20a_cpuapp_0_2_0_csp.yaml
boards/nordic/nrf54lm20apdk/revision.cmake
boards/nordic/nrf54lm20pdk/Kconfig.defconfig
boards/nordic/nrf54lm20pdk/Kconfig.nrf54lm20pdk
boards/nordic/nrf54lm20pdk/board.cmake
boards/nordic/nrf54lm20pdk/board.yml
boards/nordic/nrf54lm20pdk/nrf54lm20a_cpuapp_common.dtsi
boards/nordic/nrf54lm20pdk/nrf54lm20pdk_nrf54lm20a-common.dtsi
boards/nordic/nrf54lm20pdk/nrf54lm20pdk_nrf54lm20a-pinctrl.dtsi
boards/nordic/nrf54lm20pdk/nrf54lm20pdk_nrf54lm20a_cpuapp.dts
boards/nordic/nrf54lm20pdk/nrf54lm20pdk_nrf54lm20a_cpuapp_0_0_0.yaml
boards/nordic/nrf54lm20pdk/nrf54lm20pdk_nrf54lm20a_cpuapp_0_2_0.overlay
boards/nordic/nrf54lm20pdk/nrf54lm20pdk_nrf54lm20a_cpuapp_0_2_0.yaml
boards/nordic/nrf54lm20pdk/nrf54lm20pdk_nrf54lm20a_cpuapp_0_2_0_csp.overlay
boards/nordic/nrf54lm20pdk/nrf54lm20pdk_nrf54lm20a_cpuapp_0_2_0_csp.yaml
boards/nordic/nrf54lm20pdk/nrf54lm20pdk_nrf54lm20a_cpuapp_defconfig
boards/nordic/nrf54lm20pdk/revision.cmake

Added board revision 0.2.0.csp with wider access to GPIOs and changed pin assignment for UART20, LEDs and buttons.
Specific name/number for the board to be decided.

boards: nordic: nrf54lm20a: Add 0.2.0.csp board revision

---

samples/wifi/ble_coex/src/bt_throughput_test.c

Disabling BLE after disconnection was causing incorrect disconnection reason codes at the central (0x0) and the peripheral (0x8). With this fix, the disconnection reason codes are now correctly reported as 0x16 at the central and 0x13 at the peripheral.

samples: wifi: ble_coex: Fix BLE disconnection reason code

---

doc/nrf/installation/install_ncs.rst

Added information about the --ncs-version argument to the toolchain environment command. TECHDOC-3720.

doc: install: --ncs-version for toolchain env

---

applications/serial_lte_modem/src/slm_at_host.c

If the character removed using backspace was a quote, the internal state of the RX handler was not updated correctly. This caused incorrect behavior when handling the following characters.

applications: serial_lte_modem: Fix handling of quotes with backspace

---

doc/nrf/libraries/modem/modem_slm.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/modem/modem_slm.h
lib/modem_slm/Kconfig
lib/modem_slm/modem_slm.c
lib/modem_slm/modem_slm_monitor.c
samples/cellular/slm_shell/README.rst
samples/cellular/slm_shell/boards/nrf52840dk_nrf52840.overlay
samples/cellular/slm_shell/boards/nrf5340dk_nrf5340_cpuapp.conf
samples/cellular/slm_shell/boards/nrf5340dk_nrf5340_cpuapp.overlay
samples/cellular/slm_shell/boards/nrf7002dk_nrf5340_cpuapp.overlay

Rewrite of the previously unstable UART implementation between host device, which is using modem_slm lib, and device with SLM.
Removed:
- CONFIG_MODEM_SLM_DMA_MAXLEN (RX buf size)
- modem_slm_reset_uart as there is no reason to reset UART.
Added Kconfigs for UART buffers:
- CONFIG_MODEM_SLM_UART_RX_BUF_COUNT
- CONFIG_MODEM_SLM_UART_RX_BUF_SIZE
- CONFIG_MODEM_SLM_UART_TX_BUF_SIZE
Added Kconfig for buffering AT-responses:
- CONFIG_MODEM_SLM_AT_CMD_RESP_MAX_SIZE
Jira: LRCS-10

lib: modem_slm: Refactor UART implementation.

---

tests/subsys/debug/cpu_load/testcase.yaml

Fix Twister runtime error.
twisterlib.error.TwisterRuntimeError: Duplicated test scenarios found:
- debug.cpu_load found in:
[./ncs/zephyr/tests/subsys/debug/cpu_load](https://github.com/nrfconnect/sdk-zephyr/blob/main/tests/subsys/debug/cpu_load/testcase.yaml#L8)
[./ncs/nrf/tests/subsys/debug/cpu_load](https://github.com/nrfconnect/sdk-nrf/blob/main/tests/subsys/debug/cpu_load/testcase.yaml#L2)

tests: subsys: debug: cpu_load: Change duplicated test name

---

doc/nrf/app_dev/device_guides/fem/fem_nrf21540_gpio.rst
west.yml

This commit brings in zephyr containing the fix of tx-en-settle-time-us default value for the nrf21540 Front-End Module.
The doc commit is cherry picked from NCS 3.0 branch 61bd2af2997a3f0b507c848c2173d924861ac5b2
Ref: KRKNWK-20212

manifest: update zephyr to bring in nrf21540 timing fix

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_key_ids.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.h

This fixes an issue where the KMU keys 0-2 on the nRF54L15 cannot be used to store keys.
This refactors how we handle the IKG key IDs for
Cracen. Before this change we used the internal
Cracen IKG key identifiers inside the builtin key
driver. This had an issue because both the KMU keys and the IKG internal key IDs share the IDs 0-2.
To avoid this collision the IKG handling is refactored to use the reserved Cracen PSA key identifiers in the driver level and only use the internal key intentifiers deeper in the implementation in order to avoid the conflicts.
This also removes unused structs related to the IKG keys and unused code as well.
test_crypto: PR-765

nrf_security: Refactor Cracen IKG keys

---

applications/serial_lte_modem/scripts/slm_start_ppp.sh

When using Linux PPPD on a host device, use "persist" option so the PPP daemon keep the ppp link waiting for LCP configuration requrests in case SLM is not yet responding.
This makes PPPD to tolerate network lost events, at least "AT+CFUN=4" followed by "AT+CFUN=1" works OK.

applications: serial_lte_modem: Use persist option on Linux PPP

---

applications/matter_bridge/snippets/onoff_plug/zap-generated/access.h
applications/matter_bridge/src/default_zap/zap-generated/access.h
doc/nrf/releases_and_maturity/known_issues.rst
west.yml

- Update Matter SDK revision.
- Regenerate ZAP files to fix access permissions for `NodeLabel` in `BridgedDeviceBasicInformation` cluster.

applications: matter_bridge: Fix TC-ACE-2.2

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/nfc/record_text/sample.yaml
subsys/nfc/lib/platform.c

This PR is a general fix for platforms where FICR belongs to the non-secure address space.
Additionally: labelling explicit support for the build target `nrf54l15dk/nrf54l15/cpuapp/ns` in the _record_text_ sample.

nfc: add support for non-secure build targets for nRF54L15

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/platform_keys/platform_keys.c

Remove incorrect comment about AES keys.
As is plain to see in the code, the AES keys are being stored as ciphertext.

cracen: platform_keys: Remove incorrect comment about AES keys

---

doc/nrf/app_dev/device_guides/fem/fem_nrf2220.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
lib/fem_al/fem_al.c
subsys/mpsl/fem/Kconfig
subsys/mpsl/fem/common/include/mpsl_fem_twi_drv.h
subsys/mpsl/fem/common/mpsl_fem_twi_drv.c
subsys/mpsl/fem/nrf2220/mpsl_fem_nrf2220.c
subsys/mpsl/fem/nrf2240/mpsl_fem_nrf2240.c

This PR brings in a temperature compensation feature for the nrf2220 Front-End Module allowing better accuracy of output power setting.
The API exposed by the MPSL https://github.com/nrfconnect/sdk-nrfxlib/blob/main/mpsl/fem/nrf2220/include/protocol/mpsl_fem_nrf2220_protocol_api.h
is used.
The nRF2220 temperature compensation feature is enabled by the new Kconfig option
`MPSL_FEM_NRF2220_TEMPERATURE_COMPENSATION`.
The temperature is provided by either taking the SoC temperature (default) Kconfig option `MPSL_FEM_NRF2220_TEMPERATURE_SOURCE_SOC` or is provided by user `MPSL_FEM_NRF2220_TEMPERATURE_SOURCE_CUSTOM`.
The feature requires a i2c_nrfx_twim driver extension covered by PR https://github.com/nrfconnect/sdk-zephyr/pull/2585 (already in sdk-zephyr). This extension provides just the …

mpsl: nrf2220 temperature compensation

---

CODEOWNERS
scripts/ci/tags.yaml
tests/drivers/mspi/mspi_with_spis/CMakeLists.txt
tests/drivers/mspi/mspi_with_spis/boards/nrf54h20dk_nrf54h20_cpuapp_sqspi.overlay
tests/drivers/mspi/mspi_with_spis/prj.conf
tests/drivers/mspi/mspi_with_spis/src/main.c
tests/drivers/mspi/mspi_with_spis/testcase.yaml

Add a test that allows verifying the functionality of an MSPI driver using multiple SPIS peripherals (one per IO line). TX transfers only for now, with a configuration using sQSPI on nRF54H20.

tests: drivers: Add MSPI driver test based on multiple SPISes

---

applications/serial_lte_modem/doc/slm_description.rst
samples/cellular/slm_shell/README.rst

Change SLM Shell pins, RTS and CTS, to correspond to SLM Shell overlays.

samples: cellular: slm_shell: Switch RTS and CTS pins in doc

---

scripts/memory-threshold-list.yaml

Fixed the scenario matching pattern in the configuration of the Apple Find My Switchable Networks sample for the DFU switch variant.
Ref: NCSDK-31920
special thanks to @katgiadla for help :)

scripts: memory-threshold: find_my: switchable networks: fix dfu pattern

---

drivers/serial/uart_nrf_sw_lpuart.c

Fix case when UART_RX_BUF_RELEASED event is not called after explicit uart_rx_disable() call.

drivers: serial: nrf_sw_lpuart: Fix missing UART_RX_BUF_RELEASED event

---

applications/matter_bridge/snippets/onoff_plug/zap-generated/access.h
applications/matter_bridge/snippets/onoff_plug/zap-generated/endpoint_config.h
applications/matter_bridge/src/default_zap/zap-generated/access.h
applications/matter_bridge/src/default_zap/zap-generated/endpoint_config.h
west.yml

- Update Matter SDK revision.
- Regenerate ZAP files to fix access permissions for `NodeLabel` in `BridgedDeviceBasicInformation` cluster.

[Backport v2.9-branch] applications: matter_bridge: Fix TC-ACE-2.2

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cracen_mac_hmac.c

The cracen_hmac_update needs to resume the hash operation for any call apart from the first block.
This was missing before which could make the cracen_hmac_update to fail in cases where the input was not a multiple of the block size.

nrf_security: Fix HMAC update for Cracen PSA driver

---

subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c
tests/subsys/net/lib/nrf_provisioning/src/coap.c

Free results from zsock_getaddrinfo().
Signed-off-by: Juha Ylinen <juha.ylinen@nordicsemi.no>
(cherry picked from commit 7ec2d4788fb354e6271f243feaea2b0f7a109ba1)

[Backport v2.9-branch] net: nrf_provisioning: Fix memory leak

---

CODEOWNERS
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
scripts/west-commands.yml
scripts/west_commands/ncs_ironside_se_update.py

Add a new west command for performing an update.
The update command can be invoked as:
depends on https://github.com/nrfconnect/sdk-nrf/pull/22133
Ref: NCSDK-32168

scripts: add support for IRONside SE update service

---

dts/common/nordic/nrf7120_enga.dtsi

Property 'max-frequency' is going to be removed from "nordic,nrf-timer" binding.

dts: common: nordic: Remove max-frequency from timers on nrf7120

---

lib/at_host/at_host.c

If the character removed using backspace was a quote, the internal state of the RX handler was not updated correctly. This caused incorrect behavior when handling the following characters.
Make sure there are both CR and LF between the command and the output (response or notification). Otherwise the output will be printed on top of the command or the output will have offset.

lib: at_host: Improve terminal handling

---

doc/nrf/includes/sample_board_rows.txt
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/bluetooth/direct_test_mode/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.conf
samples/bluetooth/direct_test_mode/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.overlay
samples/bluetooth/direct_test_mode/sample.yaml

Add support for nRF54LM20PDK in DTM sample.

samples: bluetooth: direct_test_mode: Add support for nRF54LM20PDK

---

CODEOWNERS

Changing SLM ownership to new `ncs-lr-slm` group, which has partially same people as earlier.

CODEOWNERS: Change SLM ownership

---

soc/nordic/nrf54l/CMakeLists.txt

The nRF54L devices have a reserved RAM area which is used by the KMU as a target for the push operation.
This is done by including a linker script which defines this area. For nRF54L10/L15 this linker script is directly included by the CMake logic in the soc folder in upstream Zephyr.
Since the nRF54LM20A doesn't use the upstream Zephyr CMake logic from the soc directory we need to copy the logic here.
When the nRF54LM20A uses the upstream Zephyr CMake logic this can be removed.

soc: nrf54l: Add the linker script for the KMU push area

---

doc/requirements.txt

Broken snowballstemmer was released. As a workaround fallback to older release.

ci: fix docbuild requirements.txt

---

samples/bootloader/sample.yaml

NSIB has been ported to 54L so add it to the sample.yaml.

samples: nsib: Add 54l to the sample.yaml

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/zigbee/zigbee_app_utils.h
subsys/zigbee/lib/zigbee_app_utils/zigbee_app_utils.c

Without this change building the application with CONFIG_ZIGBEE_FACTORY_RESET=n results in a compilation error.

zigbee: subsys: Fix compilation when FACTORY_RESET is disabled

---

samples/cellular/modem_shell/src/at/at_cmd_mode.c

If the character removed using backspace was a quote, the internal state of the RX handler was not updated correctly. This caused incorrect behavior when handling the following characters.

samples: cellular: modem_shell: Fix handling of quotes with backspace

---

samples/bluetooth/channel_sounding_ras_initiator/prj.conf
samples/bluetooth/channel_sounding_ras_reflector/prj.conf
subsys/bluetooth/services/ras/Kconfig.ras

suggestion for how to simplify usage of the BT_CHANNEL_SOUNDING_REASSEMBLY_BUFFER_SIZE in our CS samples

Redefine kconfig for cs buffer

---

applications/zigbee_weather_station/src/sensor.c
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Withaout fix, negative temperatures values are wrongly logged on the console. Unification of logging added.
Signed-off-by: Michal Leksinski <michal.leksinski@nordicsemi.no>

applications: zigbee_weather_station: Fix negative values logging

---

west.yml

Updated MDK improves support for nRF54L05 and nRF54L10 erratas.

manifest: update sdk-zephyr to have MDK 8.68.2

---

samples/cellular/modem_shell/bt.overlay
tests/drivers/lpuart/boards/nrf9160dk_nrf9160.overlay
tests/drivers/lpuart/boards/nrf9160dk_nrf9160_loopback.overlay

Those are not specified anymore after migration to configuration via
pinctrl properties.

samples,tests: drop references to 'rts-pin' and 'cts-pin'

---

samples/crypto/aes_cbc/sample.yaml
samples/crypto/aes_ctr/sample.yaml

As of now multi-part operations are not supported on that device, and those samples use multi-part cipher operations.

samples: crypto: remove 54L20 from AES-CBC and AES-CTR samples

---

samples/zephyr/drivers/jesd216/sample.yaml
samples/zephyr/drivers/spi_flash/sample.yaml

samples: zephyr: drivers: jesd216: run on LM20 DK

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
scripts/hid_configurator/NrfHidDevice.py

Change ensures that discovery failure of a HID device would not affect other HID devices that work properly.
Jira: NCSDK-33350

scripts: hid_configurator: Discover HID devices independently

---

tests/zephyr/drivers/flash/common/testcase.yaml

tests: zephyr: drivers: flash: common: run for LM20 DK

---

include/esb.h

Conditional values that depend on SoC capabilities where not visible in the doc builds because they depend on preprocessor definitions from MDK.

esb: ESB API documentation - make all enum values visible

---

scripts/west_commands/create_board/schema.json

Fixed the prohibited "NCS" term in the schema for the create board west command.

fix: prohibited term in create board schema

---

doc/nrf/libraries/dfu/dfu_target.rst
include/dfu/dfu_target.h
include/dfu/dfu_target_custom.h
subsys/dfu/dfu_target/Kconfig
subsys/dfu/dfu_target/src/dfu_target.c

This pull request introduces support for custom firmware upgrades to the DFU (Device Firmware Update) target library. The changes include updates to documentation, configuration options, and the addition of a new header file for custom DFU target implementation.
* Introduced a new Kconfig option `CONFIG_DFU_TARGET_CUSTOM` to enable support for custom updates.
* Added a new header file `include/dfu/dfu_target_custom.h` with function declarations for custom DFU target implementation.
* Updated `include/dfu/dfu_target.h` to include a new image type `DFU_TARGET_IMAGE_TYPE_CUSTOM` for custom updates. [[1]](diffhunk://#diff-8857e847743854e08dd616843f7fa8327e20c35a1c1e3a40307c529da49c56c4R41-R42) [[2]](diffhunk://#diff-8857e847743854e08dd616843f7fa8327e20c35a1c1e3a40307c529da49c56c4L49-R51)
* …

dfu: Add custom device update

---

samples/wifi/thread_coex/README.rst

Replace incorrect reference to Bluetooth with Thread.

samples: wifi: thread_coex: Replace incorrect reference to Bluetooth

---

applications/serial_lte_modem/src/slm_at_host.c
applications/serial_lte_modem/src/slm_at_sms.c

When sending SMS with `#XSMS=2`, positive error codes from `sms_send_text()` are not handled properly.
`ERROR`, `CME ERROR` and `CMS ERROR` doesn't write this to return buffer and SLM got stuck. This is now fixed.
In addition, some return codes within SLM for starting SMS service and stopping it has been fine-tuned.
Jira: LRCS-89

applications: serial_lte_modem: #XSMS error response handling fixed

---

.github/test-spec.yml

The LwM2M Carrier library has a dependency on the DFU Target subsystem.

test-spec: extend the scope for lwm2m

---

tests/drivers/gpio/gpio_more_loops/boards/nrf54lm20pdk_nrf54lm20a_common_0_2_0_csp.dtsi

CI setup was reconfigured.
P1.07-P2.06 was removed.
P0.04-P0.05 was added.

tests: drivers: gpio: gpio_more_loops: Fix loopback on PCA10184

---

west.yml

Update west.yml to to run CI from sdk-zephyr PR pull/2586.

manifest: Update manifest to point to pull/2586/head

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/nfc/shell/sample.yaml
samples/nfc/writable_ndef_msg/sample.yaml

Add experimental llvm support in NFC samples:
- writable_ndef_msg
- shell
Jira: NCSDK-33298

samples: nfc: Add experimental llvm support in selected samples

---

subsys/mpsl/fem/Kconfig

Removed incomplete sentence. The description for
"Initial default gain ..." is already provided several lines below and refers to Kconfig `MPSL_FEM_NRF21540_TX_GAIN_DB`.
Ref: TECHDOC-3767

doc: fix CONFIG_MPSL_FEM_NRF21540_RUNTIME_PA_GAIN_CONTROL

---

applications/nrf_desktop/bootloader_dfu.rst

Change removes reference to a removed sysbuild Kconfig option and adds a documentation link.
Jira: NCSDK-33429

applications: nrf_desktop: Fix SUIT envelope signing doc

---

scripts/west_commands/ncs_west_helpers.py
west.yml

Rebase 05.2025

---

applications/nrf_desktop/description.rst

Change adds documentation for BLE peer control on DK. Change also improves a bit dongle peer description on nRF52840 gaming mouse.
Jira: NCSDK-30128

applications: nrf_desktop: Describle BLE peer control on DK

---

applications/nrf_desktop/description.rst

Change updates documentation describing Fast Pair Model IDs and Anti Spoofing private keys that are used by default for nRF Desktop.

applications: nrf_desktop: Update Fast Pair provisioning doc

---

doc/nrf/app_dev/board_names.rst
doc/nrf/app_dev/device_guides/nrf53/features_nrf53.rst
doc/nrf/app_dev/device_guides/nrf91/nrf91_features.rst
doc/nrf/app_dev/device_guides/thingy91x/thingy91x_building_programming.rst
doc/nrf/gsg_guides/nrf7002_gs.rst
doc/nrf/includes/application_build_and_run_ns.txt
doc/nrf/includes/build_and_run_ns.txt
doc/nrf/includes/tfm.txt
doc/nrf/libraries/security/trusted_storage.rst
doc/nrf/protocols/lte/overview.rst
doc/nrf/protocols/matter/end_product/security.rst
doc/nrf/protocols/thread/overview/security.rst
doc/nrf/samples.rst
doc/nrf/samples/tfm.rst
doc/nrf/security/tfm/index.rst
doc/nrf/shortcuts.txt

Edited notes to mention that the /ns board target is recommended for more security. Edited some of the links to the security by separation page. More thorough pass will be done in the future. NCSDK-16510.

doc: tf-m: add mention of /ns being recommended

---

scripts/hid_configurator/NrfHidDevice.py

Change fixes discovery of HID peripherals connected through a dongle.
Jira: NCSDK-33604

scripts: hid_configurator: Fix discovering dongle peers

---

tests/zephyr/drivers/spi/spi_controller_peripheral/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.overlay

Pins P1.30 and P1.31 are connected to leds, thus do not work properly in high-frequency signals, causing 8MHZ SPI testcases to fail. Moved to other loopback

tests: zephyr: drivers: spi: change pins for nRF54LM20 0.2.0

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ikg_signature.c
subsys/nrf_security/src/drivers/cracen/silexpk/target/baremetal_ba414e_with_ik/pk_baremetal.c

On CRACEN  lite the PKE-IKG interrupt can not be cleared from outside ik mode Therefore this interrupt was disabled in a previous commit. Unfortunately when power to CRACEN is turned fully off this also affects this registert meaning cracen_wait_for_interrupt can also not be used. This is therefore disabled for CRACEN lite
Fixing this exposed an issue where the IKG would sometimes hang due to a entropy error that was not handled. This is now worked around by having a error code be returned and then rerunning the function.

nrf_security: cracen: Fix hanging samples and tests with CRACEN lite

---

boards/nordic/nrf7120pdk/nrf7120pdk_nrf7120-common.dtsi
boards/nordic/nrf7120pdk/nrf7120pdk_nrf7120-emu-pinctrl.dtsi
boards/nordic/nrf7120pdk/nrf7120pdk_nrf7120_cpuapp.dts
boards/nordic/nrf7120pdk/nrf7120pdk_nrf7120_cpuapp_emu.dts
scripts/quarantine.yaml

Resolved: https://nordicsemi.atlassian.net/browse/NRFX-7694
SPI00 and UART00 cannot be enabled at the same time, set default uart for console / shell to be 20.

Resolved: Nrfx 7694 nrf extended drivers spi fails at nrf 7120 pdk nrf 7120 cpuapp

---

west.yml

Update zephyr to include fix which remove link flag duplication.

manifest: update zephyr to include link line duplication fix

---

applications/serial_lte_modem/src/gnss/slm_at_gnss.c
applications/serial_lte_modem/src/slm_cmux.c
applications/serial_lte_modem/src/slm_cmux.h
applications/serial_lte_modem/src/slm_ppp.c

Instead of ignoring PPP actions (start, stop, restart), if there is action ongoing, we queue the actions. This will allow us to notice if the PDP context comes up, so we can start even if we were closing the PPP connection.
Jira: LRCS-182

applications: serial_lte_modem: Queue PPP actions

---

boards/nordic/thingy91x/thingy91x_nrf9151_common.dts

Changes the default expansion port GPIO hog to use the regulator subsystem.
Signed-off-by: Helmut Lord <kellyhlord@gmail.com>

boards: thingy91x: exp. port hog to regulator

---

sysbuild/CMakeLists.txt

nrf-squash! sysbuild: Fix compliance issues with Kconfig
exclude region 3 usage if BOOTCONF kicks in.

sysbuild: BOOTCONF_LOCK_WRITES fix

---

include/nrf_compress/implementation.h
subsys/nrf_compress/src/arm_thumb.c
subsys/nrf_compress/src/lzma.c
subsys/suit/stream/stream_filters/src/suit_decompress_filter.c
tests/subsys/nrf_compress/decompression/arm_thumb/src/main.c
tests/subsys/nrf_compress/decompression/lzma/CMakeLists.txt
tests/subsys/nrf_compress/decompression/lzma/src/main.c
west.yml

This PR fixes the processing of the 'last part' of compressed input.
Previously, LZMA_FINISH_END was incorectly enforced and it caused
issues if decompression output reached 'dicLimit' during this
'last part' processing. Please refer to following discussion for the
detailed rationale:
https://github.com/nrfconnect/sdk-nrf/pull/20582#discussion_r1969656717
nrf_compress API was extended to support decompressed output limit
checking. This is the correct way to use LZMA_FINISH_END flag.
Also, decompression status at the end of input stream processing is now
checked.
ref: NCSDK-32340

nrf_compress: fix processing of the 'last part'

---

samples/matter/light_bulb/Kconfig.sysbuild
samples/matter/light_switch/Kconfig.sysbuild
samples/matter/lock/Kconfig.sysbuild
samples/matter/manufacturer_specific/Kconfig.sysbuild
samples/matter/template/Kconfig.sysbuild
samples/matter/thermostat/Kconfig.sysbuild
samples/matter/window_covering/Kconfig.sysbuild

This commit removes redundant configuration of sysbuild config PM_MCUBOOT_PAD.
This is no longer needed after #17334

samples: matter: do not override PM_MCUBOOT_PAD sysbuild config

---

samples/peripheral/radio_test/src/radio_cmd.c
samples/peripheral/radio_test/src/radio_test.c
samples/peripheral/radio_test/src/radio_test.h

Radio transmission is stopped on the END event,
ensuring it terminates immediately after the packet is sent.
Ref: NCSDK-33487

samples: radio_test: Modify radio transmission termination handling

---

CODEOWNERS

CODEOWNERS: Extend owners for lpuart sample

---

modules/mcuboot/Kconfig
sysbuild/Kconfig.mcuboot

The warning is no longer true, since RAM is cleared by MCUboot before starting the application.
Ref: NCSDK-28492

modules: mcuboot: Remove deprecated security warning from Kconfig

---

lib/ram_pwrdn/Kconfig
samples/matter/light_switch/boards/nrf5340dk_nrf5340_cpuapp_release.conf
samples/matter/light_switch/boards/nrf7002dk_nrf5340_cpuapp_release.conf
samples/matter/lock/boards/nrf5340dk_nrf5340_cpuapp_release.conf
samples/matter/lock/boards/nrf7002dk_nrf5340_cpuapp_release.conf
samples/matter/lock/prj_thread_wifi_switched.conf
samples/matter/smoke_co_alarm/boards/nrf5340dk_nrf5340_cpuapp_release.conf
samples/matter/window_covering/boards/nrf5340dk_nrf5340_cpuapp_release.conf

Backport a582b9997c1b0e6cd459e389063ac4042c6c569f from #21640.

[Backport v3.0-branch] lib: Implied NRF_FORCE_RAM_ON_REBOOT by RAM_POWER_DOWN_LIBRARY

---

subsys/net/lib/mqtt_helper/mqtt_helper.c
tests/subsys/net/lib/mqtt_helper/src/mqtt_helper_test.c

Part of the MQTT client struct initialization is memset() on the structure and mutex initialization. Having this as a part of the client connect doesn't work well in multi-threaded environment (as in MQTT sample), where client reconnect can be triggered from a different thread than regular client processing. In such case, the mutex structure could be reinitialized while already being in use by the MQTT helper thread, leading to asserts.
Fix this by initializing the MQTT client structure once, on MQTT helper library init.
Jira: NCSIDB-1569

net: lib: mqtt_client: Don't initialize MQTT client struct on connect

---

include/esb.h
subsys/esb/esb.c

The 4 Mb radio modes with BT=0.5 have been removed from nRF54H20 register definitions. The recommended mode for the 4 Mb data rate is BT=0.6/h=0.5 - use it as the only 4 Mb option for ESB.

esb: align 4 mbit radio data rate setting for nRF54H20 and nRF54L

---

samples/nrf5340/extxip_smp_svr/pm_static_nrf5340dk_nrf5340_cpuapp_ns.yml
west.yml

fix for LTO on mcuboot + fix of nRF5340 external xip SRAM memory partitioning.

Fix/ncsdk 33176, 33694

---

doc/nrf/releases_and_maturity/releases/release-notes-3.1.0-preview1.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

removes the information about the LM20 target

doc: remove LM20 from release notes

---

applications/nrf_desktop/configuration/nrf52840dk_nrf52840/images/mcuboot/prj_mcuboot_qspi.conf
applications/nrf_desktop/configuration/nrf52840dk_nrf52840/images/mcuboot/prj_mcuboot_smp.conf
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

LTO no longer causes boot failures, enable it to reduce the memory footprint.
Jira: NCSDK-31751
Jira: NCSDK-33013

applications: nrf_desktop: Enable LTO in MCUboot

---

lib/nrf_modem_lib/nrf_modem_os_rpc.c

Added missing icmsg instance parameter initialization. Because the parameter was not properly initialized, the icmsg handshake failed.

lib: nrf_modem_lib: Add missing parameter initialization

---

applications/nrf5340_audio/broadcast_sink/main.c
applications/nrf5340_audio/broadcast_source/main.c
applications/nrf5340_audio/src/audio/audio_datapath.c
applications/nrf5340_audio/src/audio/audio_datapath.h
applications/nrf5340_audio/src/audio/audio_system.c
applications/nrf5340_audio/src/audio/audio_system.h
applications/nrf5340_audio/src/audio/le_audio_rx.c
applications/nrf5340_audio/src/audio/le_audio_rx.h
applications/nrf5340_audio/src/audio/streamctrl.h
applications/nrf5340_audio/src/audio/sw_codec_select.c
applications/nrf5340_audio/src/audio/sw_codec_select.h
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_sink.c
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.h
applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.c
applications/nrf5340_audio/src/bluetooth/bt_stream/bt_le_audio_tx/bt_le_audio_tx.h
applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.c
applications/nrf5340_audio/src/bluetooth/bt_stream/le_audio.h
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.c
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_client.h
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.h
applications/nrf5340_audio/src/modules/audio_usb.c
applications/nrf5340_audio/unicast_client/main.c
applications/nrf5340_audio/unicast_server/main.c
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/audio_defines.h
lib/data_fifo/data_fifo.c
samples/bluetooth/nrf_auraconfig/src/nrf_auraconfig.c

- Implement new struct in broadcast_sink from end-to-end
- Implement audio struct in usb RX
- Added audio struct to USB RX all the way up to sw_encode
- Use audio struct in sw_encode
- Replace PCM data with LC3 data and update meta data
- Uses audio struct from USB all the way to le_audio_tx
- Added audio_struct to the decode function
- Implement audio_struct in unicast
- Using the new audio struct in both unicast server and client
- Implement the new audio struct in nrf_auraconfig sample
- OCT-3285

applications: nrf5340_audio: Use new audio struct

---

applications/serial_lte_modem/src/slm_at_host.c

When UDP packets are continuously sent in data mode, we need to ensure that the ring buffer for data does not loop as that can split the packet.
Jira: LRCS-211

application: serial_lte_modem: Fix UDP send in data mode

---

applications/nrf_desktop/doc/dvfs.rst
doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_quick_start.rst
doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_custom_pcb.rst
doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_suit_customize_qsg.rst
doc/nrf/app_dev/device_guides/nrf70/wifi_advanced_security_modes.rst
doc/nrf/libraries/bin/lwm2m_carrier/CHANGELOG.rst
doc/nrf/libraries/security/trusted_storage.rst
doc/nrf/protocols/bt/bt_mesh/overview/security.rst
doc/nrf/protocols/matter/end_product/index.rst
doc/nrf/protocols/matter/getting_started/adding_clusters.rst
doc/nrf/protocols/matter/getting_started/index.rst
doc/nrf/protocols/matter/getting_started/testing/thread_one_otbr.rst
doc/nrf/protocols/matter/getting_started/testing/thread_separate_otbr_linux_macos.rst
doc/nrf/protocols/matter/getting_started/testing/wifi_pc.rst
doc/nrf/protocols/matter/overview/network_topologies.rst
doc/nrf/protocols/wifi/stack_configuration.rst
doc/nrf/releases_and_maturity/known_issues.rst
doc/nrf/security/tfm/tfm_building.rst
doc/nrf/templates/cheat_sheet.rst
samples/cellular/nrf_cloud_multi_service/README.rst
samples/cellular/udp/README.rst
samples/event_manager_proxy/README.rst

In many docs, there are style violations using “we” as the subject. Cleaned up them.

doc: style fixes, stop using “we”

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/peripheral/radio_test/sample.yaml

Introduced experimental LLVM support in the radio_test sample.
Ref: NCSDK-33299

samples: peripheral: radio_test: Add experimental LLVM support

---

samples/bluetooth/peripheral_power_profiling/sample.yaml

Add support for nRF54LM20PDK in peripheral_power_profiling sample.
Ref: NCSDK-33721

samples: peripheral_power_profiling: Add support for nRF54LM20PDK

---

applications/nrf_desktop/pytest/test_mcuboot_kmu.py
doc/nrf/app_dev/device_guides/nrf54l/kmu_provision.rst
samples/bluetooth/fast_pair/locator_tag/README.rst
scripts/west_commands/ncs_provision.py
tests/subsys/kmu/pytest/common.py

Removed SoC argument from west ncs-provision command.
SoC was required in previous version of ncs-provision script, where nrfutil was not used.
Updated docs and tests.

Remove SoC argument from west ncs-provision command

---

boards/nordic/nrf54lm20pdk/nrf54lm20a_cpuapp_common.dtsi
boards/nordic/nrf54lv10dk/nrf54lv10a_cpuapp_common.dtsi

Update the lfxo node load-capacitance-femtofarad to match the chosen external lfxo on the following DK designs:
* nRF54LM20-PDK
* nRF54LV10-DK
Previous stray capacitance value was calculated incorrectly, which resulted in a too low load capacitance.

boards: Update lfxo node on nRF54LV10-DK and nRF54LM20-PDK

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c

Increase KMU encrypted workmem to handle 512 bits keys.
Fix for copy of HMAC keys.

Cracen kmu fixes

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
subsys/mpsl/init/Kconfig

The new default value will also work for some typical slower crystals.
Jira: DRGN-25262

mpsl: Increase the default of CONFIG_MPSL_HFCLK_LATENCY

---

applications/nrf5340_audio/tools/buildprog/buildprog.py
applications/nrf5340_audio/tools/buildprog/program.py
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

OCT-3386
Updated Buildprog to use nrfutil instead of nrfjprog

Applications: nrf5340_audio: Buildprog tooling update

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/net/download/CMakeLists.txt
samples/net/download/Kconfig
samples/net/download/README.rst
samples/net/download/src/main.c

The default is to provision a root CA certificate from a file. Disable this option to avoid overwriting an existing certificate already stored in the modem.
Added this kconfig option because I did not want to overwrite the nrf cloud certificate I already had stored in the modem. I thought it would be nice to have a kconfig option for this instead of having to comment out several sections in different files to disable the provisioning.

samples: net: download: add CONFIG_SAMPLE_PROVISION_CERT kconfig option

---

samples/nfc/record_launch_app/sample.yaml
samples/nfc/record_text/sample.yaml
samples/nfc/shell/sample.yaml
samples/nfc/system_off/sample.yaml
samples/nfc/tnep_tag/sample.yaml
samples/nfc/writable_ndef_msg/sample.yaml

Added support for nRF54LM20PDK in NFC samples:
- record_launch_app
- record_text
- shell
- system_off
- tnep_tag
- writable_ndef_msg
Ref: NCSDK-33608

samples: nfc: Add support for nRF54LM20PDK

---

tests/drivers/audio/dmic_dump_buffer/Kconfig
tests/drivers/audio/dmic_dump_buffer/src/main.c
tests/drivers/audio/dmic_dump_buffer/testcase.yaml

Extend test with possibility to add two microphones and check if stereo operation works correctly.

tests: drivers: audio: dmic_dump_buffer: Add stereo configuration

---

subsys/net/openthread/rpc/server/ot_rpc_cli.c
subsys/net/openthread/rpc/server/ot_rpc_coap.c
subsys/net/openthread/rpc/server/ot_rpc_dns_client.c
subsys/net/openthread/rpc/server/ot_rpc_meshdiag.c
subsys/net/openthread/rpc/server/ot_rpc_netdiag.c
subsys/net/openthread/rpc/server/ot_rpc_srp_client.c
subsys/net/openthread/rpc/server/ot_rpc_thread.c
subsys/net/openthread/rpc/server/ot_rpc_udp.c
tests/subsys/net/openthread/rpc/server/src/coap_suite.c
tests/subsys/net/openthread/rpc/server/src/dns_client_suite.c
tests/subsys/net/openthread/rpc/server/src/meshdiag_suite.c
tests/subsys/net/openthread/rpc/server/src/mocks.c
tests/subsys/net/openthread/rpc/server/src/netdiag_suite.c
tests/subsys/net/openthread/rpc/server/src/thread_suite.c

OpenThread over RPC server invoked OpenThread callbacks on the RPC client with the OpenThread stack mutex locked. This may have lead to a deadlock when the client called the server while the server was calling the client.
Therefore, unlock the OpenThread stack mutex before calling the client, and lock it again when the response arrives.

net: openthread: rpc: call client with mutex unlocked

---

doc/nrf/app_dev/device_guides/wifi_coex.rst

Update the "nRF70 Series Wi-Fi coexistence" section to reflect changes in the coex node: update node name, adjust GPIO pin numbers and configuration flags.

doc: update Wi-Fi coex guide for nRF70 Series node changes.

---

tests/drivers/uart/uart_baudrate_test/testcase.yaml
tests/zephyr/drivers/uart/uart_elementary/testcase.yaml

Follow default revision change.

tests: zephyr: drivers: uart: uart_elementary: default is csp

---

boards/nordic/thingy91x/thingy91x_nrf9151_common-pinctrl.dtsi
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Add bias-pull-up for nRF9151 UART RX pins. This fixes an issue with framing error detected when device connect or disconnect serial.

boards: thingy91x: Add bias-pull-up to UART pins

---

tests/subsys/kmu/pytest/conftest.py
tests/subsys/kmu/pytest/test_kmu_provision.py
tests/subsys/kmu/pytest/test_kmu_revoke_in_app.py
tests/subsys/kmu/pytest/test_kmu_verify_keys_in_app.py

Updated tests/subsys/kmu tests with `no_reset` fixture. This fixtures adds `--no-reset` argument to west flash, to not reset device after flashing. Works only with pytest-harness.
To test is locally, one can run:
`$ZEPHYR_BASE/scripts/twister -T tests/subsys/kmu --device-testing --hardware-map ~/tmp/hardware_map.yml --west-flash="--recover" -vv -c -ll debug`

tests: kmu: Added no_reset fixture in provisioning tests

---

drivers/mspi/mspi_sqspi.c

This is a follow-up to #21430. See individual commit messages.

drivers: mspi_sqspi: A few corrections

---

subsys/nrf_security/src/ssf_secdom/CMakeLists.txt

The ironside PSA crypto client failed to build due to missing a
TFM include path.

nrf_security: ssf_secdom: add missing include path

---

samples/matter/light_bulb/pm_static_nrf54lm20pdk_nrf54lm20a_cpuapp_internal.yml
samples/matter/light_bulb/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.conf
samples/matter/light_bulb/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp_internal.conf
samples/matter/light_switch/pm_static_nrf54lm20pdk_nrf54lm20a_cpuapp_internal.yml
samples/matter/light_switch/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.conf
samples/matter/light_switch/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp_internal.conf
samples/matter/lock/pm_static_nrf54lm20pdk_nrf54lm20a_cpuapp_internal.yml
samples/matter/lock/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.conf
samples/matter/lock/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp_internal.conf
samples/matter/manufacturer_specific/pm_static_nrf54lm20pdk_nrf54lm20a_cpuapp_internal.yml
samples/matter/manufacturer_specific/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.conf
samples/matter/manufacturer_specific/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp_internal.conf
samples/matter/smoke_co_alarm/pm_static_nrf54lm20pdk_nrf54lm20a_cpuapp_internal.yml
samples/matter/smoke_co_alarm/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.conf
samples/matter/smoke_co_alarm/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp_internal.conf
samples/matter/template/pm_static_nrf54lm20pdk_nrf54lm20a_cpuapp_internal.yml
samples/matter/template/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp_internal.conf
samples/matter/template/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.conf
samples/matter/template/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp_internal.conf
samples/matter/thermostat/pm_static_nrf54lm20pdk_nrf54lm20a_cpuapp_internal.yml
samples/matter/thermostat/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.conf
samples/matter/thermostat/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp_internal.conf
samples/matter/window_covering/pm_static_nrf54lm20pdk_nrf54lm20a_cpuapp_internal.yml
samples/matter/window_covering/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.conf
samples/matter/window_covering/sysbuild/mcuboot/boards/nrf54lm20pdk_nrf54lm20a_cpuapp_internal.conf

For nRF54LM20 DKs we must CONFIG_BOOT_MAX_IMG_SECTORS=512 in Mcuboot configuration, because the primary image size is bigger than 1024 kB (256 sectors per 4kB). Even for the internal DFU configuration.

samples: matter: Fix internal build configuration.

---

subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c
tests/subsys/net/lib/nrf_provisioning/src/coap.c

Free results from zsock_getaddrinfo().
Signed-off-by: Juha Ylinen <juha.ylinen@nordicsemi.no>
(cherry picked from commit 7ec2d4788fb354e6271f243feaea2b0f7a109ba1)

[Backport v3.0-branch] net: nrf_provisioning: Fix memory leak

---

samples/bluetooth/direct_test_mode/src/dtm.c

There is a typo in the nrf5340 errata 117 logic, where it checked for a nRF52-series device instead of a nRF53-series device. This caused a hard-fault if the function ran successfully on a nRF52-series device.
Fix is to use the same implementation as done in sample ../peripheral/radio_test
https://github.com/nrfconnect/sdk-nrf/blob/v2.9-branch/samples/peripheral/radio_test/src/radio_test.c#L721-L735

samples: bluetooth: Fix errata 117 check

---

samples/cellular/gnss/src/main.c

Fixed a couple of bugs in TTFF test mode with `CONFIG_GNSS_SAMPLE_MODE_TTFF_TEST_COLD_START` and assistance enabled. The assistance request was missing system IDs and assistance data was downloaded twice before the first GNSS start.

samples: cellular: gnss: Fix assistance in cold start test mode

---

scripts/quarantine.yaml
tests/zephyr/drivers/i2s/i2s_api/boards/tdm_audiopll.overlay
tests/zephyr/drivers/i2s/i2s_speed/boards/tdm_audiopll.overlay

ACLK can be independently connected to MCK and SCK, thus two different properies are to be used (`sck-clock-source` and `mck-clock-source`) instead of common `clock-source`.

tests: zephyr: drivers: i2s: Fix ACLK settings for TDM

---

subsys/nrf_security/src/drivers/cracen/Kconfig
subsys/nrf_security/src/drivers/cracen/cracenpsa/cracenpsa.cmake
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c
subsys/nrf_security/src/drivers/cracen/silexpk/include/silexpk/ik.h
subsys/nrf_security/src/drivers/cracen/silexpk/silexpk.cmake
subsys/nrf_security/src/drivers/cracen/silexpk/target/baremetal_ba414e_with_ik/pk_baremetal.c
subsys/nrf_security/src/drivers/cracen/silexpk/target/hw/ba414/pkhardware_ba414e.c
subsys/nrf_security/src/drivers/cracen/silexpk/target/hw/ik/ikhardware.c

Add the configuration option CRACEN_IKG
which allows to disable the IKG funcionality
if it is not needed.
This will decrease the flash usage for applications
which don't use the IKG.
Ref: NCSDK-30246
Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>

nrf_security: Make the Cracen IKG configurable

---

CODEOWNERS
cmake/sysbuild/image_signing.cmake
subsys/mcuboot/mcuboot_secondary_app.overlay
sysbuild/CMakeLists.txt
sysbuild/mcuboot.cmake

This commit adds support for the DIRECT_XIP modes
on nRF54H20

mcuboot: Support for DIRECT XIP on nRF54H (App core only)

---

scripts/ci/tags.yaml
tests/drivers/i2s/i2s_mclk/boards/tdm_mck_audiopll.overlay
tests/drivers/i2s/i2s_mclk/boards/tdm_sck_audiopll.overlay
tests/drivers/i2s/i2s_mclk/testcase.yaml

Add nRF54H20 overlays that select Audio PLL as a source of clock signal for bit-clock and/or master-clock signals.

tests: drivers: i2s: i2s_mclk: Extend test with ACLK configuration

---

tests/zephyr/drivers/adc/adc_accuracy_test/boards/nrf54l09pdk_nrf54l09_cpuapp.overlay
tests/zephyr/drivers/adc/adc_accuracy_test/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.overlay
tests/zephyr/drivers/adc/adc_accuracy_test/boards/nrf54lm20pdk_nrf54lm20a_cpuapp_0_0_0.overlay
tests/zephyr/drivers/adc/adc_accuracy_test/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay

"_" -> "-" as this makes difference in this test.

tests: zephyr: drivers: adc: adc_accuracy_test: fix reference-mv

---

scripts/bluetooth/mesh/mesh_dfu_metadata.py
tests/subsys/bluetooth/mesh/metadata_extraction/src/main.c
tests/subsys/bluetooth/mesh/metadata_extraction/verify_metadata.py

Commit:
* Fixes vendor model id extraction from elf file. Company id and model id positions were swapped.
* Extends the composition data of the metadata test by dummy vendor model.

scripts: bluetooth: mesh: fix vendor model id extraction

---

subsys/net/lib/nrf_provisioning/src/nrf_provisioning.c
subsys/net/lib/nrf_provisioning/src/nrf_provisioning_codec.c
tests/subsys/net/lib/nrf_provisioning/src/main.c

The settings subsystem uses metadata for encoding the value length, so there no need to store the null-terminator in flash.

net: nrf_provisioning: Improve storing string values

---

subsys/net/lib/nrf_provisioning/Kconfig.nrf_provisioning_cbor
subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c
subsys/net/lib/nrf_provisioning/src/nrf_provisioning_http.c
tests/subsys/net/lib/nrf_provisioning/src/coap.c
tests/subsys/net/lib/nrf_provisioning/src/main.c

Introduce a new query parameter that allows users to specify the maximum number of provisioning commands that can be received from the server.

net: nrf_provisioning: Add new query parameter

---

applications/nrf_desktop/src/modules/hids.c
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Use a generic callback for HID input report notification events. Use generic functions to handle HID feature and output reports. This simplifies adding support for new HID reports.
Jira: NCSDK-33592

applications: nrf_desktop: Use generic cbs for HID notification events and HID feature/output reports

---

subsys/bootloader/Kconfig

Removed hidden CONFIG_SB_NRF54L15_STYLE_IMPL kconfig property and use dependency on nRF54l15/05/10 directly for NSIB.
Ref.: https://github.com/nrfconnect/sdk-nrf/pull/22470#discussion_r2125729434

subsys/bootloader: removed hidden CONFIG_SB_NRF54L15_STYLE_IMPL

---

doc/nrf/includes/wifi_radio_test_subcommands.txt
doc/nrf/protocols/wifi/regulatory_certification/wifi_radio_test_sample/wifi_build_instructions.rst
samples/wifi/radio_test/multi_domain/sample.yaml

[SHEL-3458]: Introduce kconfig options for radio test combo build command, add instructions and description for sr antenna switch control.
[SHEL-3458]: https://nordicsemi.atlassian.net/browse/SHEL-3458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc: wifi: Improve radio test combo build instruction

---

applications/nrf_desktop/src/util/Kconfig
applications/nrf_desktop/src/util/Kconfig.adv_prov
applications/nrf_desktop/src/util/Kconfig.dfu_lock
applications/nrf_desktop/src/util/Kconfig.hid_reportq
applications/nrf_desktop/src/util/Kconfig.hwid

Change defines separate files for Kconfig configuration of nRF Desktop utilities. This is done to improve clarity.
Jira: NCSDK-31553

applications: nrf_desktop: Use separate files for utils Kconfig

---

applications/nrf_desktop/src/modules/Kconfig.hid_state
applications/nrf_desktop/src/modules/hid_state.c
applications/nrf_desktop/src/util/CMakeLists.txt
applications/nrf_desktop/src/util/Kconfig
applications/nrf_desktop/src/util/Kconfig.hid_eventq
applications/nrf_desktop/src/util/hid_eventq.c
applications/nrf_desktop/src/util/hid_eventq.h

PR introduces HID event queue utility. The utility can be used to enqueue keypress events.
The PR also integrates the utility in HID state application module.
Jira: NCSDK-31553

applications: nrf_desktop: Introduce HID event queue

---

.github/test-spec.yml

The downstream i2c tests are executed in the test-low-level job.

tests: drivers: i2c: Add i2c test entry to 'test-spec.yml'

---

applications/nrf_desktop/src/util/CMakeLists.txt

Change aligns format of config channel transport utility's CMakeLists entry with other nRF Desktop utilities.

applications: nrf_desktop: Align config channel CMakeLists entry

---

samples/crypto/persistent_key_usage/boards/nrf52840dk_nrf52840.conf
samples/crypto/persistent_key_usage/boards/nrf9160dk_nrf9160.conf
samples/crypto/persistent_key_usage/boards/nrf9161dk_nrf9161.conf

The CC310 HW does not support AES-GCM, so use ChaCha20-Poly1305 instead.

samples: persistent_key_usage: fix execution on devices w/ CC310

---

tests/zephyr/boards/nrf/hwinfo/reset_cause/boards/nrf54l09pdk_nrf54l09_cpuapp.overlay
tests/zephyr/boards/nrf/hwinfo/reset_cause/testcase.yaml

tests: zephyr: boards: nrf: hwinfo: enable for LV10 DK

---

subsys/bluetooth/controller/hci_driver.c

Allowing users to link-out the channel sounding mode 3 to improve flash usage.

bluetooth: improving linking for channel sounding

---

doc/nrf/releases_and_maturity/software_maturity.rst

Edited the PSA Crypto tables with cross-links.
Structured the tables to be more readable.
Removed SSF crypto service from all tables except nRF54. NCSDK-33436 and NCSDK-30216.

doc: software_maturity: update PSA crypto tables

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
subsys/mpsl/init/mpsl_init.c

Zero latensy interrupt handlers are not allowed to use kernel APIs. Zephyr documentation states that use of kernel APIs must be considered as undefined behavior. The same goes for triggering kernel scheduler by `return 1;` at end of an ISR and use of PM subsystem defined macros like ISR_DIRECT_PM.

mpsl: init: Stop triggering sched and PM from ZLI ISRs

---

doc/requirements.txt

There are two issues with sphinx in NCS that this patch tries to resolve.
First, and for an unknown reason, having `sphinx~=8.1.0` as we did before does not prevent pip from installing sphinx 8.2.x. Second, sphinx 8.2.x seems to work fine when building the NCS doc all in one go (i.e. run `ninja` with no arguments). But when building independent docsets separately, the following errors appear:
`WARNING: zephyr:board reference target not found: <board> [ref.board]`
Which corresponds to an entry similar to:
```
:zephyr:board:`<board>`
```
So, in summary:
Sphinx 8.2.x seems to have an issue with intersphinx and zephyr board names. This only seems to show when one builds docsets separately, but not if you build them together:
works: `cmake -GNinja -S. -B_build && cd _build && ninja` 
fails: …

doc: Ensure that the sphinx version used is lower than 8.2.0

---

cmake/sysbuild/b0_mcuboot_signing.cmake
cmake/sysbuild/sign.cmake

Fixes which files are included with partition manager when b0 is enabled and MCUboot is also enabled, which otherwise would have used the files without MCUboot signatures, which would fail to boot if image verification on boot is enabled
Fixes: NCSIDB-1549

sysbuild: Fix including correct files for b0 with MCUboot

---

doc/nrf/protocols/bt/bt_mesh/vendor_model/chat_sample_walk_through.rst

Fix the missing `:c:macro:` infront of some macros in the doc. Also add space after `BT_MESH_MODEL_USER_DATA` to fix link rendering issue.

Bluetooth: Mesh: Fix chat sample walkthrough doc

---

include/bluetooth/gatt_dm.h
west.yml

Two unrelated minor patches: 
1. manifest: alphabetically sort the name-allowlist
2. bluetooth: gatt_dm: silence a compiler warning for unused parameter

Minor changes to manifest and bluetooth: gatt_dm

---

subsys/bluetooth/controller/hci_internal.c

When power class 1 was enabled the feature feature bit was not being set.

bluetooth: controller: add missing feature bit for power class 1

---

doc/requirements.txt

Commit 85eb35fb4736e001b42eab68e6a7c233f842895d changed the version string for pip, with only a `<8.2.0` requirement. This however is not enough, since an arbitrary old version of sphinx would not be updated, and 8.1.0 is actually required.
Switch to manually specifying `==8.1.*`, which is equivalent to `>=8.1.0,<8.2.0`.

doc: requirements: Refine Sphinx version required

---

samples/nrf_rpc/protocols_serialization/client/README.rst
samples/nrf_rpc/protocols_serialization/server/README.rst

Update documentation of the protocols serialization samples to better match the current implementation state.
Update BLE device name, snippet description, and clarify certain statements.

samples: nrf_rpc: update documentation

---

subsys/net/lib/nrf_cloud/src/nrf_cloud_rest.c

The `total_bytes` variable in the `nrf_cloud_rest_agnss_data_get()` function was of type `size_t`, which is unsigned. The variable was used to store negative error codes, which caused the code execution to take unexpected paths.

lib: nrf_cloud: rest: Fix A-GNSS data download error handling

---

boards/nordic/nrf54lm20pdk/nrf54lm20pdk_nrf54lm20a_cpuapp.dts
boards/shields/nrf7002eb2/boards/nrf54lm20pdk_nrf54lm20a_cpuapp.overlay

Add Wi-Fi support to nRF54lm20 PDK via EB-II shield

boards: wifi: Add Wi-Fi support to nrf54lm20 PDK

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/cellular/modem_shell/README.rst
samples/cellular/modem_shell/src/at/at_cmd_mode.c
samples/cellular/modem_shell/src/at/at_cmd_mode_custom.c
samples/cellular/modem_shell/src/at/at_cmd_mode_sett.c
samples/cellular/modem_shell/src/at/at_cmd_mode_sett.h
samples/cellular/modem_shell/src/at/at_shell.c

Add ATE0 and ATE1 in AT command mode to handle echo on/off. Store last used mode in settings.

samples: cellular: modem_shell: Add ATE0/ATE1

---

subsys/net/lib/download_client/src/shell.c

Fix usage text for "config pdn_id" and "set_host" shell commands.

net: download_client: Fix shell usage texts

---

applications/serial_lte_modem/Kconfig
applications/serial_lte_modem/overlay-zephyr-modem.conf
applications/serial_lte_modem/src/slm_ppp.c

Added Kconfig CONFIG_SLM_CELLULAR_MODEM, which configures different operability between cellular modem driver other use cases, such as pppd.
In this case, we do not want to restart PPP immediately when terminated, as that is controlled by the cellular modem driver.

applications: serial_lte_modem: Cellular modem driver nw loss

---

doc/nrf/releases_and_maturity/known_issues.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Added description about CCA ED threshold default value to known issues and configuration changes to changelog.

Known issues about CCA ED configuration in nrf-802154

---

applications/serial_lte_modem/Kconfig

Long AT notifications are truncated with CMUX based on CONFIG_SLM_CMUX_NOTIFICATION_TX_BUFFER_SIZE which was 256 by default. This is now increased to match the CONFIG_AT_MONITOR_HEAP_SIZE which reserves 4kB for the notifications.
We may need to revisit this when doing memory optimizations.
Jira: SLM-98

applications: serial_lte_modem: Increase CMUX notification buffer

---

samples/wifi/provisioning/ble/prj.conf

Increase bluetooth RX stack size to prevent stack overflow.
Fixes SHEL-3623.

samples: wifi: provisioning: ble: Fix stack overflow

---

samples/bluetooth/peripheral_power_profiling/Kconfig
samples/bluetooth/peripheral_power_profiling/boards/nrf54lv10dk_nrf54lv10a_cpuapp.conf
samples/bluetooth/peripheral_power_profiling/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay
samples/bluetooth/peripheral_power_profiling/sample.yaml
samples/bluetooth/peripheral_power_profiling/src/main.c

Add support for nRF54LV10DK in peripheral_power_profiling sample.

samples: peripheral_power_profiling: Add support for nRF54LV10DK

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
subsys/nrf_security/src/psa_crypto_driver_wrappers.c

Adds support for key derivation of SPAKE2P keys with Cracen. It currently supports only SECP256R1 keys.
Ref: NCSDK-30368

nrf_security: Add Cracen key derivation for SPAKE2P keys

---

boards/nordic/nrf54lm20pdk/nrf54lm20a_cpuapp_common.dtsi
samples/bluetooth/peripheral_hids_keyboard/app.overlay
samples/bluetooth/peripheral_hids_keyboard/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay
west.yml

TODO
Upstream Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/88637
Suggested fix: https://github.com/nrfconnect/sdk-zephyr/pull/2942

Bluetooth Peripheral HIDS keyboard: nfct node enabled at board level

---

boards/nordic/nrf54lv10dk/nrf54lv10a_cpuapp_common.dtsi

Set the vregmain node to use the DCDC converter by default.

boards: nordic: nrf54lv10dk: Enable DCDC converter

---

subsys/mpsl/init/mpsl_hwres.c

The name mpsl_hwres_dppi_channel_alloc should be used instead of `mpsl_fem_hwres_dppi_channel_alloc`

mpsl: fix misspelled function name to mpsl_hwres_dppi_channel_alloc

---

subsys/mpsl/fem/common/include/mpsl_fem_utils.h
subsys/mpsl/fem/common/mpsl_fem_utils.c
subsys/mpsl/fem/nrf21540_gpio/mpsl_fem_nrf21540_gpio.c
subsys/mpsl/fem/nrf21540_gpio_spi/mpsl_fem_nrf21540_gpio_spi.c
subsys/mpsl/fem/nrf2220/mpsl_fem_nrf2220.c
subsys/mpsl/fem/nrf2240/mpsl_fem_nrf2240.c

In the MPSL the FEM configuration API will change soon (see dragoon repo PR # 13235 ). To smoothly transition through the change in public API for FEM config the new MPSL version will define a transitional macro `_MPSL_FEM_CONFIG_API_NEXT`.
The provided NCS code supports both API versions.
When the macro is not defined, the code compiles as it was before.
When the macro is defined the code is changed as required by the new MPSL API:
- For the nRF54L Series the DPPI channels and PPIB channels for FEMs are
allocated internally in MPSL. The recently provided implementation
of functions in mpsl_hwres.h is responsible for that.
- The MPSL's struct `mpsl_fem_gpiote_pin_config_t` no more contains the
`ppib_channels` field. The function `mpsl_fem_utils_gpiote_pin_init`
is no more necessary.
When …

mpsl: fem: adjust to FEM config API change

---

applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
applications/serial_lte_modem/doc/TCPUDP_AT_commands.rst
applications/serial_lte_modem/src/slm_at_socket.c
applications/serial_lte_modem/src/slm_at_tcp_proxy.c
applications/serial_lte_modem/src/slm_at_udp_proxy.c
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Adding support for `MSG_WAITACK` flag for sending data with `#XSEND`, `#XSENDTO`, `#XTCPSEND` and `#XUDPSEND`.
This flag means that modem waits for the LTE network to acknowledge the sending operation before returning.
Jira: SLM-83

applications: serial_lte_modem: Add MSG_WAITACK support

---

subsys/nrf_security/src/drivers/cracen/common/include/cracen/membarriers.h
subsys/nrf_security/src/drivers/cracen/silexpk/target/baremetal_ba414e_with_ik/pk_baremetal.c
subsys/nrf_security/src/drivers/cracen/silexpk/target/hw/ba414/pkhardware_ba414e.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/platform/baremetal/cmdma_hw.c

We are observing that
__noinline for instance, is being defined both by gcc.h from Zephyr and by a picolib header in the build dir.
Reordering the includes like this is observed to fix the issue.
I suspect that we are including internal zephyr headers that are not designed to be included directly.
See https://nordicsemi.atlassian.net/browse/NCSDK-34100 for more details

cracen: Reorder includes to fix include order issue

---

subsys/net/openthread/rpc/server/ot_rpc_link.c

Change the command for setting EUI64 over RPC to work even if EUI64 is not taken from UICR.

openthread: rpc: enable setting EUI64 at runtime only

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
lib/modem_slm/Kconfig

Remove EXPERIMENTAL status as the library has been stabilized and test coverage has been extended significantly.
Jira: SLM-16

lib: modem_slm: Remove EXPERIMENTAL status

---

.sonarcloud.properties
CODEOWNERS

adding .sonarcloud.properties to control file exclusions from the autoscan in sonarcloud

ci: adding the sonarcloud autoscan config file

---

modules/trusted-firmware-m/tfm_boards/common/dummy_provisioning.c
modules/trusted-firmware-m/tfm_boards/common/nrf_provisioning.c
west.yml

Brings TF-M where the target_cfg.c is split for
different platforms.
Ref: NCSDK-31914

Bring TF-M with split target_cfg.c

---

cmake/sysbuild/generate_default_keyfile.cmake
sysbuild/CMakeLists.txt
sysbuild/Kconfig.mcuboot
sysbuild/Kconfig.secureboot
tests/subsys/bootloader/boot_chains/Kconfig.sysbuild
tests/subsys/bootloader/boot_chains/testcase.yaml
tests/subsys/kmu/hello_for_kmu/testcase.yaml

Updated manifest to sdk-zephyr.
Changes in zephyr allows to provision KMU keys with `west flash` command, if keyfile.json (generated by west ncs-provision) is in build directory.
Changes in sdk-nrf:
Introduced the capability to automatically generate
the keyfile.json during the build process for nRF54L series devices.
Added new Kconfigs:
* SB_CONFIG_SECURE_BOOT_GENERATE_DEFAULT_KMU_KEYFILE
* SB_CONFIG_MCUBOOT_GENERATE_DEFAULT_KMU_KEYFILE
to control creating keyfile.json during the build process.
Creating keyfile.json is implemented in generate_default_keyfile.cmake.
Additionally updated tests on nrf54l15dk:
* tests/subsys/bootloader/boot_chains
* tests/subsys/kmu/hello_for_kmu
To test is manually on nrf54l15dk:
hello world + NSIB
```
west build -p -b nrf54l15dk/nrf54l15/cpuapp …
```

Generate default key file with west ncs-provision, enable automatic KMU provisioning

---

include/net/aws_iot.h
include/net/mqtt_helper.h
subsys/net/lib/aws_iot/src/aws_iot.c
subsys/net/lib/mqtt_helper/mqtt_helper.c

It's now possible to bind the mqtt client with a specific network interface, which is useful in projects with multiple network interfaces (which can even be a mix of offloaded and native ones - in this case socket dispatcher is involved). In order to be able to use this feature, we need to forward the configuration from the application down to the mqtt client library through the mqtt_helper and aws_iot libs.

net: lib: mqtt_helper && aws_iot: Allow to bind with specific network interface

---

modules/openthread/Kconfig
modules/openthread/Kconfig.features.nrf
modules/openthread/Kconfig.nrf5
modules/openthread/platform/CMakeLists.txt
modules/openthread/platform/radio_nrf5.c
subsys/net/openthread/Kconfig.defconfig

Implemented the new OpenThread radio implementation for the nRF Connect platform.
The new radio implementation is based on the nRF IEEE802.15.4 radio driver and does not use Zephyr's IEEE802.15.4 shim layer.
In this solution, the Zephyr's networking L2 layer is disabled, and radio packets are passed directly to the nRF radio.
Prepared a build environment to support building OpenThread without Zephyr's L2 and IEEE802.15.4 shim layers.
To use the new radio implementation, the `CONFIG_NET_L2_OPENTHREAD` Kconfig must be set to `n`.
Note: Documentation will be updated in the following PR.

modules: openthread: New OpenThread radio implementation for nRF

---

doc/nrf/libraries/modem/modem_info.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/modem/modem_info.h
lib/modem_info/modem_info.c

This PR adds a function to retrieve the RSRQ values from the modem, similar to the existing `modem_info_get_rsrp` function. It also adds `SNR_IDX_TO_DB`, comparable to `RSRQ_IDX_TO_DB` and `RSRP_IDX_TO_DBM`. Furthermore, the `SNR_OFFSET_VAL` is clarified to calculate the upper value of the SNR according to the [AT Commands documentation](https://docs.nordicsemi.com/bundle/ref_at_commands/page/REF/at_commands/mob_termination_ctrl_status/xsnrsq_set.html)

lib: modem_info: Add functions to retrieve RSRQ

---

cmake/sysbuild/generate_default_keyfile.cmake

Fixed the string expansion in the SB_CONFIG_BOOT_SIGNATURE_KEY_FILE Kconfig option when it is used to generate keyfile JSON for the KMU provisioning. The feature works properly now with a more complex definition of the SB_CONFIG_BOOT_SIGNATURE_KEY_FILE Kconfig option such as:
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${SB_APPLICATION_CONFIG_DIR}/..."

cmake: sysbuild: fix the string expansion for MCUboot signature key file

---

subsys/caf/modules/leds.c

Improved the CAF LEDs module by simplifying the logic for color count calcuation that was done using the DTS configuration. Now, it is no longer necessary to define a dummy array for calculating the number of supported colors for each LED instance. This improvement also resolves the build warnings for the LLVM toolchain variant.
Ref: NCSDK-34195

caf: leds: improve logic for calculating color count from DTS

---

tests/drivers/timer/grtc_timer_lfrc/src/main.c

Corrct invalif reference timer handling sequence

tests: drivers: timer: Fix GRTC with LFRC test

---

include/flash_map_pm.h
subsys/partition_manager/flash_map_partition_manager.c

Two commits:
- support for FIXED_PARTITION macro that allows to obtain direct pointer to flash_area object representing partition, instead of using flash_area_open with id;
- Zephyr manifest update with sdk-zephyr changes to flash_map tests, that conditionally disable parts of tests that are not possible to run on Partition Manager enabled build.
You can build the Zephyr flash map test using:
```
west build --sysbuild -d builds/pm-flash -b nrf52840dk/nrf52840 zephyr/tests/subsys/storage/flash_map/ -DSB_CONFIG_PARTITION_MANAGER=y -DSB_CONFIG_BOOTLOADER_MCUBOOT=y
```
to get free PM definitions that allow you to run the test on nrf52840.
Depends on:
https://github.com/nrfconnect/sdk-nrf/pull/22473

Partition Manager: support for FIXED_PARTITION macros and update of sdk-zephyr with fixed flash-map tests

---

include/bluetooth/radio_notification_cb.h
subsys/bluetooth/host_extensions/radio_notification_conn_cb.c

Seems it's not problematic to call k_work_init or k_timer_init a second time.
Changing the callback or prepare distance while there are no connections is also fine.

bluetooth: Make it possible to use radio notification cb with bt_disable

---

include/net/nrf_cloud_agnss.h

The maximum A-GNSS data size was too small, if ephemerides and almanacs were received for all GPS satellites and more than four QZSS satellites. The planned QZSS constellation size is seven satellites. The updated size leaves some margin on top of 32 GPS and 7 QZSS satellites to avoid similar problems in the future.

nrf_cloud_agnss: Increase maximum A-GNSS data size

---

samples/peripheral/lpuart/boards/nrf54lv10dk_nrf54lv10a_cpuapp.overlay

Align that uart console was changed uart20->uart30.

samples: peripheral: lpuart: align to uart console change at LV10

---

scripts/quarantine_zephyr.yaml

Quarantined test configurations are investigated.
Until fix for that, these should be quarantined.

quarantine_zephyr: Add quarantine for libraries.libc.* at NCS

---

boards/nordic/nrf54lm20pdk/nrf54lm20a_cpuapp_common.dtsi

Samples/tests which need it should enable it explicitly.

boards: nordic: nrf54lm20pdk: do not enable ext flash by default

---

subsys/nrf_security/src/core/lite/psa_core_lite.c
tests/subsys/nrf_security/psa_core_lite/src/main.c

-Added support for incremental hash for SHA-256 and SHA-512 by
adding psa_hash_setup, psa_hash_update, psa_hash_finish and
psa_hash_abort
-Testing is reusing secp256r1 test vectors for SHA-256 and
Ed25519ph test vectors for SHA-512
-Fixed copy-paste error in test case for test_hash_compute
(wrong statement for failure condition)
Note that psa_hash_verify and psa_hash_clone is not added as it is assumed to not be used in bootloader context
Note that there is no additional test-target added in test_case.yaml -Testing SHA-256: Use psa_core_lite.ecdsa test target -Testing SHA-512: Use psa_core_lite.ed25519 test target
ref: NCSDK-33725

crypto: PSA core lite: Adding incremental hash

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c

Enabled support for KMU key generation of ChaCha20 keys.
Jira: NCSDK-33844

nrf_security: drivers: cracen: Enable KMU key generation for ChaCha20

---

samples/nrf_rpc/protocols_serialization/client/src/ot_shell.c

It should print rloc16 in hex.

samples: nrf_rpc: ps_client: fix rloc16 command

---

lib/st25r3911b/st25r3911b_interrupt.c

For example: suppose the code had previously initialized the ST25R3911 and set it to wake-up mode. Later, for some reason, the application on the nRF device was rebooted.
During re-initialization, after calling st25r3911b_irq_init(), there is a short delay between enabling IRQs and starting the oscillator via osc_start(). In this interval, an IRQ may already be triggered by the chip. Since wake-up-related IRQs can occur every 10–800 ms, it’s likely that an interrupt happens before the oscillator is started.
After calling osc_start(), the code expects an interrupt signaling that the oscillator is ready. However, if the IRQ already occurred earlier, code may immediately read the IRQ registers and not find the expected oscillator-ready bit. This causes the code to misinterpret the state and …

lib: st25r3911b: Correct irq_clear to prevent spurious IRQs

---

tests/drivers/i2s/i2s_mclk/src/test_i2s_mclk.c

Relaxed expectation for coverage mode.

tests: drivers: i2s: i2s_mclk: relax expectation at coverage

---

doc/nrf/releases_and_maturity/known_issues.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/bluetooth/direct_test_mode/src/dtm.c

Fixing workaround behavior that caused assertion in RX and low packet rate in TX. Adding related doc entries

samples: bluetooth: direct_test_mode: Fix hmpan 216 workaround

---

doc/nrf/applications.rst
doc/nrf/links.txt

* Updated asset tracker Techdoc link
in the link.txt file.
* Add Asset Tracker Template into the NCS
application list.

doc: Update and list asset tracker template techdoc link

---

tests/drivers/i2s/i2s_mclk/src/test_i2s_mclk.c

Scale down expectation when coverage mode is used.

tests: drivers: i2s: i2s_mclk: scale expectation at coverage

---

doc/nrf/external_comp/bt_fast_pair.rst
doc/nrf/external_comp/dult.rst
doc/nrf/includes/fast_pair_fmdn_rename.txt
doc/nrf/libraries/bluetooth/services/fast_pair.rst
samples/bluetooth/fast_pair/locator_tag/README.rst

Created a linkable note that notifies the user about the Fast Pair extension rename. The Fast Pair Find My Device Network (FMDN) extension has been renamed to the Find Hub Network (FHN) extension, and the Find My Device app is now called the Find Hub app.
Ref: NCSDK-33576

doc: fast_pair: fmdn: add a note about the extension rename

---

applications/nrf_desktop/doc/usb_state.rst

Refactor the documentation of the USB State module from the nRF Desktop application to generalize the support for the DWC2 USB Device Controller driver.

applications: nrf_desktop: doc: usb_state: generalize dwc2 udc support

---

tests/benchmarks/current_consumption/twim_suspend/boards/nrf54h20dk_nrf54h20_cpuapp.conf
tests/benchmarks/multicore/idle_clock_control/boards/nrf54h20dk_nrf54h20_cpuapp.conf
tests/benchmarks/multicore/idle_spim/boards/nrf54h20dk_nrf54h20_cpuapp.conf

Needed to achive lowest power consumption.

tests: benchmarks: add missing conf to start radio at h20

---

include/fem_al/fem_al.h
lib/fem_al/fem_al.c
samples/bluetooth/direct_test_mode/src/dtm.c
samples/peripheral/radio_test/src/radio_test.c
subsys/esb/esb.c

In the MPSL the `mpsl_fem_tx_power_split` function will change soon (dragoon repo PR # 13369). It will have an additional  `phy` parameter and the the `mpsl_phy_t` type is extended with additional enumerators. To smoothly transition through the change in public API for FEM the new MPSL version will define a macro `_MPSL_FEM_TX_POWER_SPLIT_HAS_PHY`.
This PR adjusts NCS code to this change. For short period NCS will support both MPSL APIs, distinguished by `_MPSL_FEM_TX_POWER_SPLIT_HAS_PHY` macro.
After MPSL containing the new version is deployed the code for `!defined(_MPSL_FEM_TX_POWER_SPLIT_HAS_PHY)` will be removed.
Ref: KRKNWK-20453

mpsl: adjust for mpsl_fem_tx_power_split additional phy parameter

---

lib/fem_al/fem_al.c
subsys/esb/esb.c

The PR #22987 prepared modules for migration of MPSL FEM API to the new version signalled by the presence of the macro `_MPSL_FEM_TX_POWER_SPLIT_HAS_PHY`.
The PR #23120 brought in the MPSL containing the new API version which defined the `_MPSL_FEM_TX_POWER_SPLIT_HAS_PHY` macro.
Now the code variant for not defined `_MPSL_FEM_TX_POWER_SPLIT_HAS_PHY` is no more necessary. This commit removes it, what ends a transition in FEM mpsl_fem_tx_power_split API change. The `_MPSL_FEM_TX_POWER_SPLIT_HAS_PHY` will be removed from MPSL in the near future.
Ref: KRKNWK-20453

mpsl: fem: cleanup after transition to mpsl_fem_tx_power_split with phy

---

CODEOWNERS

This commit fixes an issue with shield ownership assignments in the CODEOWNERS file:
- Moved the general shields pattern (**/shields/) above specific shield entries
- Modified specific shield entries to include both teams:
- Added @nrfconnect/ncs-co-build-system to each specific shield entry
- Preserved original team assignments (@nrfconnect/ncs-low-level-test and @nrfconnect/ncs-radio-sw)
- Removed misleading comment about shield entry positioning
The previous configuration caused specific shield owners to be overwritten by the general @nrfconnect/ncs-co-build-system entry.

CODEOWNERS: Fix shields ownership overwrite

---

subsys/nrf_rpc/rpc_utils/server/crash_gen.c

Write to the stack array to prevent the compiler from optimizing it away.

nrf_rpc: rpc_utils: fix stack overflow trigger

---

applications/connectivity_bridge/src/disk/config.c

Rename define to avoid kconfig namespace.

applications: connectivity_bridge: Rename define

---

applications/connectivity_bridge/README.rst
applications/connectivity_bridge/boards/thingy91_nrf52840_readme.txt
applications/connectivity_bridge/boards/thingy91x_nrf5340_cpuapp_readme.txt
applications/nrf_desktop/doc/ble_qos.rst
applications/serial_lte_modem/doc/PPP_linux.rst
applications/serial_lte_modem/doc/slm_description.rst
doc/nrf/app_dev/device_guides/nrf53/logging_nrf5340.rst
doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_logging.rst
doc/nrf/app_dev/device_guides/thingy91/thingy91_connecting.rst
doc/nrf/libraries/shell/shell_bt_nus.rst
doc/nrf/protocols/thread/certification.rst
doc/nrf/protocols/wifi/regulatory_certification/test_setup.rst
doc/nrf/security/tfm/tfm_logging.rst
doc/nrf/shortcuts.txt
doc/nrf/test_and_optimize.rst
samples/bluetooth/direct_test_mode/README.rst
samples/bluetooth/enocean/README.rst
samples/bluetooth/mesh/chat/sample_description.rst
samples/bluetooth/mesh/sensor_client/README.rst
samples/bluetooth/peripheral_uart/README.rst
samples/bluetooth/rpc_host/README.rst
samples/cellular/fmfu_smp_svr/README.rst
samples/nrf5340/remote_shell/README.rst
samples/nrf_rpc/entropy_nrf53/README.rst
samples/peripheral/802154_phy_test/README.rst
samples/peripheral/802154_sniffer/README.rst
samples/peripheral/radio_test/README.rst
tests/nrf5340_audio/sw_codec_lc3/readme.txt

Removed Windows-only information about locating serial port. Added a shortcut with information how to list serial ports for Nordic devices using nRF Util.
Edited documents that mention COM ports and tty devices. Added cross links for default baud rate mentions.
NCD-685.

doc: make serial port mentions OS neutral

---

applications/nrf_desktop/src/modules/hids.c
applications/nrf_desktop/src/modules/usb_state.c
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Change ensures that the module would unsubscribe from previously used HID protocol mode before subscribing for the new HID protocol mode. This ensures that HID boot and HID report protocol mode subscriptions are not enabled at the same time.
Jira: NCSDK-34349

applications: nrf_desktop: Improve HID subscription in HIDS and USB state

---

tests/benchmarks/multicore/idle_flpr/remote/CMakeLists.txt
tests/benchmarks/multicore/idle_grtc/CMakeLists.txt
tests/benchmarks/multicore/idle_ppr/remote/CMakeLists.txt
tests/benchmarks/multicore/idle_stm/remote/CMakeLists.txt

Stop using
- CONFIG_SOC_NRF54H20_ENGB_CPUPPR
- CONFIG_SOC_NRF54H20_ENGB_CPUFLPR
as they were removed in meantime.

tests: benchmarks: multicore: Fix use of undefined Kconfigs

---

tests/benchmarks/multicore/idle_spim_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_fast_slow_pins.overlay

SPIM121 requires high-drive on P2 pins for proper transfer.

tests: idle_spim_loopback: Use high-drive for fast SPIM on P2

---

applications/nrf_desktop/doc/fn_keys.rst
applications/nrf_desktop/src/hw_interface/buttons_sim.c
applications/nrf_desktop/src/hw_interface/passkey_buttons.c
applications/nrf_desktop/src/modules/Kconfig.fn_keys
applications/nrf_desktop/src/modules/fn_keys.c
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

PR updates button_event subscription priority in the Fn keys, passkey buttons and button simulator modules to let the modules process the event before other application modules.
Jira: NCSDK-34374

applications: nrf_desktop: Update button_event subscription priority

---

samples/bluetooth/direction_finding_connectionless_tx/sample.yaml

Length of the sample name spawns build failures for Windows. This commit customizes name of sample to building requirements.

samples: Bluetooth: Rename sample direction finding

---

applications/hpf/Kconfig
applications/hpf/gpio/Kconfig
applications/hpf/mspi/Kconfig

Move options from common HPF Kconfig file to GPIO and MSPI applications' specific Kconfig files to fix building these applications out-of-tree with VS Code.
When VS Code creates an out-of-tree application, it copies only the application directory (`nrf/applications/hpf/mspi` for MSPI sample), so when built, it fails on `rsource "../Kconfig"`, because it is not visible.

applications: hpf: move common Kconfig to gpio and mspi Kconfigs

---

doc/nrf/includes/wifi_credentials_shell.txt
doc/nrf/libraries/bluetooth/services/wifi_prov.rst
doc/nrf/libraries/networking/wifi_mgmt_ext.rst
doc/nrf/releases_and_maturity/migration/2.4.99-cs3_to_2.6.99-cs2/migration_guide_2.4.99-cs3_to_2.6.99-cs2_application.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.6.rst
doc/nrf/releases_and_maturity/migration/migration_guide_2.8.rst
doc/nrf/releases_and_maturity/migration/nRF54H20_migration_2.7/migration_guide_2.4.99-cs3_to_2.7_application.rst
doc/nrf/releases_and_maturity/releases/release-notes-2.3.0.rst
doc/nrf/releases_and_maturity/releases/release-notes-2.6.0.rst
doc/nrf/releases_and_maturity/releases/release-notes-2.7.0.rst
samples/cellular/nrf_cloud_multi_service/README.rst
samples/net/azure_iot_hub/README.rst
samples/wifi/provisioning/ble/README.rst
samples/wifi/shell/README.rst
samples/wifi/sta/README.rst

Wi-Fi credentials library document has been moved upstream zephyr. Need to update page references for doc failure.

doc: Fix doc failure of Wi-Fi cred library

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_primitives.h

Empty unions are interpreted differently in C and C++:
- in C, they have size 0
- in C++, they have size 1.
This raises a warning when building with clang.

nrf_security: drivers: cracen: avoid empty unions

---

subsys/mpsl/clock_ctrl/mpsl_clock_ctrl.c
subsys/mpsl/init/mpsl_init.c

Enable use of clock control API to obtain information about a HFCLK startup time. The change affects all platforms when use external clock control.
For platforms that use CONFIG_CLOCK_CONTROL_NRF the clock driver provides this information from DTS hfxo node. If the HFXO node is not available the CONFIG_MPSL_HFCLK_LATENCY is used.
For platforms that use CONFIG_CLOCK_CONTROL_NRF2 the clock driver reads the information from BICR memory. As of now the only platform that uses it is nRF54h20.

mpls: clock_ctrl: Use clock API to get HFCLK start-up time

---

subsys/bluetooth/adv_prov/providers/tx_power.c
subsys/bluetooth/hci_vs_sdc.c
subsys/bluetooth/host_extensions/host_extensions.c
subsys/bluetooth/rpc/host/bt_rpc_internal_host.c
subsys/bluetooth/services/fast_pair/fmdn/state.c

Adapt to upstream zephyr host hci changes.

bluetooth: hci: Replace bt_hci_cmd_create() with bt_hci_cmd_alloc()

---

subsys/nrf_security/src/drivers/cracen/silexpk/src/montgomery.c

The Cracen in 54lm20 does not allow single byte writes in the PK memory. There was some single byte writes in Montgomery. This makes sure that the single byte writes are done using the relevant sx_ functions which implement workarounds for this issue when needed.
Ref: NCSDK-33957

nrf_security: Fix 54lm20 alignment issue in Cracen

---

CODEOWNERS

Set the right code owners for Bluetooth RPC library.

CODEOWNERS: add right teams to bluetooth/rpc

---

applications/nrf_desktop/src/modules/hid_provider_consumer_ctrl.c
applications/nrf_desktop/src/modules/hid_provider_keyboard.c
applications/nrf_desktop/src/modules/hid_provider_mouse.c
applications/nrf_desktop/src/modules/hid_provider_system_ctrl.c

The HID report sent error may be reported while disconnecting HID transport (BLE/USB), it may not be related to actual error. Switch from error log level to warning log level.
Jira: NCSDK-33593

applications: nrf_desktop: Use warning log on HID report sent error

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
doc/nrf/security/crypto/crypto_supported_features.rst

Removed table entries that are not supported for all three crypto drivers. NCSDK-22842 and follow-up to #22893 and #23023.

doc: crypto: updates to supported features page, part 3/3

---

subsys/mpsl/fem/simple_gpio/mpsl_fem_simple_gpio.c

The `simple_gpio` Front-End Module is enabled for nRF54L Series devices.
Note: The simple_gpio FEM for nRF54L requires an MPSL that supports the simple_gpio. This PR changes only necessary parts in the sdk-nrf.

mpsl: fem: enable simple_gpio for nRF54L series

---

doc/nrf/includes/sample_board_rows.txt
samples/benchmarks/coremark/boards/nrf54lm20dk_nrf54lm20a_cpuapp.conf
samples/benchmarks/coremark/boards/nrf54lm20dk_nrf54lm20a_cpuapp.overlay
samples/benchmarks/coremark/boards/nrf54lm20dk_nrf54lm20a_cpuflpr.conf
samples/benchmarks/coremark/boards/nrf54lm20dk_nrf54lm20a_cpuflpr.overlay
samples/benchmarks/coremark/sample.yaml

Add overlays required to run the sample on nrf54lm20dk target.

samples: benchmarks: coremark: Enable sample on nrf54lm20dk

---

cmake/sysbuild/partition_manager.cmake

The ram_flash region has FLASH_SIMULATOR as its default driver Kconfig. If the flash-simulator has been disabled in the build then this will cause a partition manager error.
Add check for flash simulator being enabled.

cmake: sysbuild: partition_manager: Handle region kconfig disabled

---

dts/common/nordic/nrf54lm20a.dtsi
dts/common/nordic/nrf54lv10a.dtsi
dts/common/nordic/nrf7120_enga.dtsi

Add missing reg parameters to DTS nodes for:
- nrf54lm20a
- nrf54lv10a
- nrf7120

dts: common: nordic: Add reg parameter for global_peripherals node

---

dts/common/nordic/nrf7120_enga.dtsi
dts/common/nordic/nrf7120_enga_secure_peripherals.dtsi

move mram-controller dtsi to secure_peripherals.dtsi as it is secure, bind compatible of mram node to soc-nv-flash as to differentiate driver from nrf54h20.

move mramc dtsi to secure dtsi

---

subsys/dfu/dfu_target/src/dfu_target_mcuboot.c

Erasing the last page is already done before writing the trailer in dfu_target_mcuboot_schedule_update.
It seems the erasing comes from a time a couple of years ago when the page was not erased inside mcuboot. Currently the code was not necessary and it caused flash wear out.

dfu_target: Do not erase last page in dfu_target_mcuboot_done

---

tests/subsys/nrf_compress/decompression/arm_thumb/testcase.yaml
tests/subsys/nrf_compress/decompression/lzma/testcase.yaml
tests/subsys/nrf_compress/decompression/mcuboot_update/Kconfig
tests/subsys/nrf_compress/decompression/mcuboot_update/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
tests/subsys/nrf_compress/decompression/mcuboot_update/modified_signing.cmake
tests/subsys/nrf_compress/decompression/mcuboot_update/src/main.c
tests/subsys/nrf_compress/decompression/mcuboot_update/sysbuild/mcuboot/boards/nrf54h20dk_nrf54h20_cpuapp.conf
tests/subsys/nrf_compress/decompression/mcuboot_update/sysbuild/mcuboot/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
tests/subsys/nrf_compress/decompression/mcuboot_update/testcase.yaml

This PR provides support for the nrf54h20dk board in the nrf_compress decompression tests.
Additional changes:
- 'main.c' - support no Partition Manager builds
- 'Kconfig' - clarify the meaning of the 'CONFIG_UPDATE_IMAGE_NUMBER' option, which is used to select the image to be updated in the mcuboot_update test. Also, no more than two images are needed.
Related: NCSDK-33627

tests: nrf_compress: Add nrf54h20 test support

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/matter/common/src/app/matter_init.cpp
scripts/quarantine.yaml
west.yml

Pulled Matter change that enabled by default usage of openthread without Zephyr L2 networking.

samples: matter: Enabled use of OT without Zephyr L2

---

scripts/docker/Dockerfile

Nrfutil device command is included in toolchain bundle.

docker: Use nrfutil device from toolchain bundle

---

samples/matter/lock/boards/nrf7002dk_nrf5340_cpuapp_nrf7001.conf
samples/matter/lock/boards/nrf7002dk_nrf5340_cpuapp_nrf7001_release.conf
scripts/quarantine.yaml

nRF7001 configuration misses LTO=y, what results in flash region overflow. Enabled LTO for this target and removed it from quarantine.

samples: matter: Fixed configuration for nrf7001

---

doc/nrf/protocols/matter/end_product/watchdog.rst

There is a mistake in the Matter docs that uses seconds unit instead of minutes.

doc: Fixed matter watchdog documentation

---

doc/nrf/app_dev/device_guides/nrf54l/dfu_config.rst
doc/nrf/app_dev/device_guides/nrf54l/ecies_x25519.rst
doc/nrf/app_dev/device_guides/nrf54l/index.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Add information of supported AES-128 encryption with ECIES-X25519 used for key exchange.

doc: nRF541l15: Add information on ECIES-X25519 support

---

samples/matter/light_bulb/sample.yaml
west.yml

Enabled Kconfig that allows to measure factory reset time in the memory profiling configuration.

samples: matter: enabled measuring factory reset time

---

CODEOWNERS
doc/nrf/external_comp/bt_fast_pair.rst
doc/nrf/external_comp/bt_fast_pair/adv_manager.rst
doc/nrf/libraries/bluetooth/services/fast_pair.rst
doc/nrf/libraries/bluetooth/services/fast_pair/adv_manager.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Added the library documentation page and the user guide page for the new Fast Pair Advertising Manager module, which is the helper module for the Google Fast Pair library.
Ref: NCSDK-34134
Additional notes:
- The PR covers the documentation for the new module that has been added in the following PR: https://github.com/nrfconnect/sdk-nrf/pull/22638
- The documentation update for the FP Locator Tag sample will be covered in a separate PR

doc: fast_pair: add documentation for the Fast Pair advertising manager

---

doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_adding_sysbuild.rst
samples/mcuboot/firmware_loader_entrance/pm_static_nrf52840dk_nrf52840.yml
samples/mcuboot/firmware_loader_entrance/pm_static_nrf54l15dk_nrf54l15_cpuapp.yml

Updates PM static files to have smaller firmware loader partitions
and to remove unused space at the end of NVM
also
doc: nrf: app_dev: bootloaders_dfu: mcuboot_nsib: Update PM usage
Updates partition manager example to reference files from a sample
NCSDK-34548

samples: mcuboot: firmware_loader_entrance: Update PM static files

---

samples/bootloader/README.rst

Removes a section which is incorrect and references things that do not exist
NCSDK-34375

samples: bootloader: readme: Remove undefined Kconfigs

---

Kconfig.nrf

NCS Applications often initialise Bluetooth and the SoftDevice Controller in the main thread.
Ensure the NCS main stack size is sufficient to cover the minimum stack usage requirements for enabling SDC. Many platforms implicitly end up with a larger default stack size via either ENTROPY_CC3XX or PSA_NEED_CRACEN_CTR_DRBG_DRIVER, but the stack size is now insufficient for others such as nRF52832 or nRF5340 cpunet.
The stack usage has not increased by a large amount, but it had been very close to 1024 and susceptible to overflowing from a marginal increase. The estimated stack size via thread analyzer is 1040 bytes, and an additional 10% margin has been added.

kconfig: Change default main stack size for softdevice

---

scripts/west_commands/create_board/config.yml
scripts/west_commands/create_board/templates/nrf53/Kconfig.defconfig.jinja2
scripts/west_commands/create_board/templates/nrf54l/board.dts.jinja2
scripts/west_commands/create_board/templates/nrf91/Kconfig.defconfig.jinja2

Fixes some issues in board templates including not using the USE_DT_CODE_PARTITION Kconfig being used or having TF-M partitions where there should not be any
Test command:
```
west ncs-create-board -r '{"root":"<OUTPUT_FOLDER>","board":"boardname","description":"description","vendor":"company","soc":"nRF54L15-QFAA"}'
```
where soc can be:
```
nRF52805-CAAA
nRF52810-QFAA
nRF52811-QFAA
nRF52820-QDAA
nRF52832-CIAA
nRF52832-QFAA
nRF52832-QFAB
nRF52833-QDAA
nRF52833-QIAA
nRF52840-QFAA
nRF52840-QIAA
nRF5340-QKAA
nRF54L15-QFAA
nRF9131-LACA
nRF9151-LACA
nRF9160-SICA
nRF9161-LACA
```

scripts: west: create_board: Fix issues in some board templates

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c

Just as 3b785730cec207fb725dbfabaa839b4e440d4477/#22877 did, include zephyr/kernel.h as the first thing to avoid redefinitions of attributes (__noinline, __deprecated, __fallthrough) in picolibc.
ref: NCSDK-34100

nrf_security: cracen: reorder includes to fix attribute redefinition

---

CODEOWNERS
boards/nordic/common/nrfutil_next.board.cmake
boards/nordic/nrf7120pdk/board.cmake
scripts/runners/nrf_common_next.py
scripts/runners/nrfutil_next.py
zephyr/module.yml

An out of tree runner for boards supported by `nrfutil device` but not yet supported in upstream zephyr. 
Inherits from nrfutil / nrf_common and then modifies to support new devices (nRF7120).

Out of tree nrfutil runner

---

CODEOWNERS

Fix duplicated ownership for ncs-lowlevel-doc group. That group shall review changes to RST files.

CODEOWNERS: Fix filter for documentation changes in hpf

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
subsys/mpsl/init/mpsl_init.c

Calling mpsl_lib_uninit() would clear the atomic do_calibration, so if the calibration work handler was entered, the work item was never rescheduled, even if mpsl_lib_init() was called later.

mpsl: continue calibrating LFRC after mpsl_lib_uninit()

---

samples/wifi/provisioning/softap/sample.yaml

Add an entry to support nrf7002EK.
Fixes SHEL-3727.

samples: wifi: provisioning: softap: Add nrf7002ek support

---

applications/machine_learning/sysbuild/ipc_radio/boards/nrf54h20dk_nrf54h20_cpurad.overlay

Correct nRF54H20 overlay in machine learning application to align with ironside.
Jira: NCSDK-34532

applications: machine_learning: Correct nRF54H20 overlay

---

modules/hal_nordic/CMakeLists.txt

Add support for custom NRFX_DIR for Sysbuild builds by checking if NRFX_DIR has been defined in Sysbuild.

modules: hal_nordic: nrfx: Add support for custom NRFX_DIR for Sysbuild

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_coap
subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap_transport.c

Add a Kconfig option to set the maximum number of CoAP request retries.

net: nrf_cloud_coap: kconfig for max_retries

---

doc/nrf/app_dev/device_guides/nrf54l/cryptography.rst
subsys/nrf_security/src/drivers/cracen/Kconfig
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cipher.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cracen.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ctr_drbg.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/kmu.h
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/include/sxsymcrypt/aes.h
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/include/sxsymcrypt/internal.h
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/include/sxsymcrypt/mac.h
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/aead.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/blkcipher.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/mac.c

nrf_security: Add protected RAM invalidation logic
Reserve two KMU slots two store random data which are used
to invalidate the protected RAM content after an operation
is finished.
Add a Kconfig so that that it is possible for size constrained
images to provision the KMU slots before usage.
Ref: NCSDK-33885
Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>
test_crypto: PR-820

nrf_security: Add protected RAM invalidation logic

---

tests/drivers/gpio/hpf_gpio_basic_api/testcase.yaml

Increase timeout for ICBMsg, which is needed for running test with coverage dump.

tests: drivers: gpio: hpf_gpio_basic_api: increase timeout

---

doc/nrf/drivers/mspi_sqspi.rst
tests/drivers/mspi/mspi_with_spis/boards/nrf54h20dk_nrf54h20_cpuapp_sqspi.overlay

This is a follow-up to commit c960096b0a6929b9c7f2fb77101141c8d1738cca ("samples: update according to new nrf54h20 RAM memory map").
After the changes applied by the above commit, the `softperiph_ram` node can no longer use empty `ranges` property, since its base address is not 0 now. Add proper address translation, so that the `sqspi` node base address is correct (not 0x3e00, what results in a bus fault when the sQSPI is initialized).
Also correct the sQSPI MSPI shim driver documentation accordingly (apart from correcting the `ranges` property for nRF54H20, restore properties that were incorrectly removed from the `reserved-memory` node for nRF54L15).

tests: drivers: mspi_with_spis: Fix ranges property in sqspi overlay

---

applications/matter_bridge/src/app_task.cpp
applications/matter_bridge/src/app_task.h
doc/nrf/releases_and_maturity/known_issues.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

The identify cluster was enabled for EP1 in Matter Bridge App, whereas it was not implemented in the code.

samples: matter: Fix identify on EP1 in Matter Bridge App

---

soc/nordic/nrf71/Kconfig.defconfig

Add Kconfig defines cache management and default uses external cache for zephyr.

soc: nrf7120: add cache config

---

samples/wifi/ble_coex/src/main.c

Zperf parameters data structure is not initialized, and with the upmerge changes a function pointer was added as part of the parameters, and if the uninitialized struct has set this to non-zero, then a random address is called by the custom loader function pointer, this causes a crash.
Initialize the parameters to zero.

samples: wifi: ble_coex: Fix crash when Zperf is started

---

doc/nrf/releases_and_maturity/known_issues.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/matter/light_switch/README.rst

There is no `tests TestGroupDemoConfig` command in Chiptool anymore. We must wrtite a new guide for the group binding.

doc: matter: Fix Matter Light Switch groupcast guide

---

subsys/bluetooth/mesh/vnd/le_pair_resp.c

Fixed an issue where Node Reset only cleared bonds for the default identity, leaving SMP and other
service bonds intact. Now clears bonds for all Bluetooth identities to ensure complete reset.

Bluetooth: mesh: clear bonds for all ids on node reset

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/key_management.c

Fix for 'psa_status' may be used uninitialized when CONFIG_SIZE_OPTIMIZATIONS=y

subsys: nrf_security: fix 'psa_status' may be used uninitialized

---

subsys/debug/coredump/coredump_backend_nrf_flash_partition.c

There was a missing (const uint32_t*) cast in
UNALIGNED_GET() macro, causing invalid core dump being written to the flash partition.

debug: coredump: fix core dump for NVMC

---

.github/workflows/docbuild.yml

Standalone Doxygen docsets have a slightly different URL scheme.

ci/docbuild: fix zoomin patching for links to standalone Doxygen docsets

---

samples/wifi/ble_coex/src/main.c

In case Zperf session fails (report not received) then the result can be NULL, add a NULL check.

samples: wifi: ble_coex: Fix possible crash if Zperf fails

---

doc/nrf/app_dev/device_guides/nrf54l/kmu_provision.rst

adds sections about new provisioning method.

doc: nrf: KMU provisioning while west flashing

---

sysbuild/CMakeLists.txt
sysbuild/Kconfig.mcuboot
west.yml

This configuration has the purpose of using keys provisioned to the internal trusted storage (ITS).

bootloader: mcuboot: Added BOOT_SIGNATURE_USING_ITS configuration

---

boards/nordic/thingy91x/board.cmake

Thingy91x runner configuration seem to be using wrong name for Jlink.
Flashing seem to work but debugging does not.

boards: thingy91x: Fix device name on runner

---

subsys/nrf_security/src/psa_crypto_driver_wrappers.c

The Oberon PSA crypto 1.5.1 introduce key encapsulation APIs. These were not added in the  psa_crypto_driver_wrapper file as they should so add them now.

nrf_security: Add key_encapsulation APIs in driver wrapper

---

drivers/mpsl/clock_control/nrfx_clock_mpsl.c
west.yml

There is a new HFCLK source HFCLK24M that might be used when
MPSL internal clok driver is enabled. That clock is used for
example by USB. The MPSL didn't support any other HFCLK except
HFXO.
The commit adds changes in MPSL clock driver that are based
on new clock API provided by the MPSL library.
Signed-off-by: Piotr Pryga <piotr.pryga@nordicsemi.no>

mpsl: Add support for HFCLK24M to MPSL clock driver

---

samples/matter/common/src/app/matter_init.cpp
samples/matter/common/src/app/matter_init.h
west.yml

During the certification process we need to support more than one locale. We can use pre defined example for All Clusters that is available in Matter SDK to assign it in our samples.
Use AllClustersExampleDeviceInfoProviderImpl instead DeviceInfoProviderImpl in Matter samples.

samples: matter: Fix locales in Matter samples

---

modules/wfa-qt/CMakeLists.txt
west.yml

Fix the Kconfig compliance error by using proper Zephyr macro
instead of a non-existent Kconfig option.

Fix Kconfig CONFIG_ZEPHYR to __ZEPHYR__

---

doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst

This commit updates the documentation about detailed Matter messages logging.

doc: matter: Add documentation about detailed logging

---

samples/wifi/shell/overlay-openthread.conf
samples/wifi/shell/sample.yaml
scripts/quarantine.yaml

This commit fixes configuration of Wi-Fi shell with OpenThread overlay by enabling proper network core image as well as optimizing the flash size to fit on nRF7002 DK.

samples: wifi: shell: Fix configuration with openthread overlay

---

doc/nrf/installation/recommended_versions.rst
doc/nrf/links.txt
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
scripts/tools-versions-darwin.yml
scripts/tools-versions-linux.yml
scripts/tools-versions-win10.yml

Including this version instead of version 8.0.0 would be preferred as it supports the "locked" mode in `nrfutil`. This mode, which is controlled by inserting a file named "locked" in the root of NRFUTIL_HOME, allows locking all functionality that changes the installed versions, both of `nrfutil` itself and of installed command. This will lower the risk of users accidentally upgrading the bundled `nrfutil`/`nrfutil device`.

tools: Upgrade `nrfutil` from 8.0.0 to 8.1.0

---

west.yml

Update sdk-zephyr and sdk-mcuboot SHAs, switching to the new rebased histories.

manifest: sdk-zephyr and sdk-mcuboot rebase

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

doc: Clean changelog on 3.1.0 RC1

---

subsys/bluetooth/controller/hci_driver.c

cs_cfg.step_mode3_supported was removed from the sdc, so we no longer need to set it when configuring the sdc

bluetooth: controller: stop using deprecated mode3 support config

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Backport 7b94e1c140b4eefcd1d709f6c85489294cac300e from #23626.

[Backport v3.1-branch] doc: Clean changelog on 3.1.0 RC1

---

applications/nrf_desktop/configuration/nrf54lm20dk_nrf54lm20a_cpuapp/images/mcuboot/prj.conf
applications/nrf_desktop/configuration/nrf54lm20dk_nrf54lm20a_cpuapp/images/mcuboot/prj_llvm.conf
applications/nrf_desktop/configuration/nrf54lm20dk_nrf54lm20a_cpuapp/images/mcuboot/prj_release.conf
applications/nrf_desktop/configuration/nrf54lm20pdk_nrf54lm20a_cpuapp/images/mcuboot/prj.conf
applications/nrf_desktop/configuration/nrf54lm20pdk_nrf54lm20a_cpuapp/images/mcuboot/prj_llvm.conf
applications/nrf_desktop/configuration/nrf54lm20pdk_nrf54lm20a_cpuapp/images/mcuboot/prj_release.conf
samples/bluetooth/fast_pair/locator_tag/sysbuild/mcuboot/boards/nrf54lm20dk_nrf54lm20a_cpuapp.conf

Enables CONFIG_FPROTECT and CONFIG_BOOT_WATCHDOG_FEED in Mcuboot image for nRF54LM20A target.

Align nRF54LM20 mcuboot configs in Fast Pair and nRF Desktop

---

subsys/net/lib/downloader/src/downloader.c

Make sure errors are forwarded to the application if reconnection fails.

net: lib: downloader: Fix error check

---

doc/nrf/app_dev/device_guides/coprocessors/index.rst
doc/nrf/app_dev/device_guides/coprocessors/ug_hpf_softperipherals_comparison.rst
doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_flpr.rst
doc/nrf/app_dev/device_guides/nrf54l/vpr_flpr.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Backport 1f634f38746c9a4a179d35a2cf25e16f65716fb3 from #23226.

[Backport v3.1-branch] doc: hpf and softperipherals comparison

---

scripts/requirements-build.txt
scripts/requirements-extra.txt

Backport fbe765ac2d592166c0a4c79539cd14f81036cb64 from #23390.

[Backport v3.1-branch] toolchain: provide the index-url to build requirements

---

subsys/bluetooth/controller/hci_driver.c

Backport 34ed1ec48b0dcf6bee9a3e4c94148cc9537b3cbb from #23627.

[Backport v3.1-branch] bluetooth: controller: stop using deprecated mode3 support config

---

applications/nrf_desktop/Kconfig.ble

Allow bonding with the same HID host on
multiple Bluetooth local identities.
JIRA: NCSDK-32518

applications: nrf_desktop: turn on BT_ID_AUTO_SWAP_MATCHING_BONDS

---

samples/bluetooth/peripheral_power_profiling/sample.yaml

Wrong overlay was used, causing different adv type to be used.

samples: bluetooth: peripheral_power_profiling: fix non conn adv for l15

---

samples/bluetooth/peripheral_power_profiling/sample.yaml

Backport 9eb2bcac6379eeda79e4329361234bb0b31487b7 from #23692.

[Backport v3.1-branch] samples: bluetooth: peripheral_power_profiling: fix non conn adv for l15

---

doc/nrf/security/ap_protect.rst
samples/tfm/tfm_psa_template/README.rst

Edited formatting of ``SB_CONFIG_*`` to :kconfig:option:`SB_CONFIG_*`. NCSDK-34763.

doc: security: SB_CONFIG formatting

---

samples/zephyr/smp_svr_mini_boot/sysbuild/mcuboot/boards/nrf54l15dk_nrf54l15_cpuapp.conf

Disable run-time CRACEN provisioning of TRNG data to KMU. KMU slots 248, 249 shall be pre-provisioned while programming with externally generate secret random values instead.

samples/zephyr/smp_svr_mini_boot: disable by TRNG KMU provisioning

---

applications/matter_bridge/sysbuild/ipc_radio/prj.conf
applications/matter_weather_station/sysbuild/ipc_radio/prj.conf
samples/matter/light_bulb/sysbuild/ipc_radio/prj.conf
samples/matter/light_bulb/sysbuild/ipc_radio/prj_release.conf
samples/matter/light_switch/sysbuild/ipc_radio/prj.conf
samples/matter/lock/sysbuild/ipc_radio/prj.conf
samples/matter/lock/sysbuild/ipc_radio/prj_release.conf
samples/matter/manufacturer_specific/sysbuild/ipc_radio/prj.conf
samples/matter/smoke_co_alarm/sysbuild/ipc_radio/prj.conf
samples/matter/smoke_co_alarm/sysbuild/ipc_radio/prj_release.conf
samples/matter/template/sysbuild/ipc_radio/prj.conf
samples/matter/template/sysbuild/ipc_radio/prj_release.conf
samples/matter/thermostat/sysbuild/ipc_radio/prj.conf
samples/matter/window_covering/sysbuild/ipc_radio/prj.conf
samples/matter/window_covering/sysbuild/ipc_radio/prj_release.conf

Changed timeslice size to 0 to workaround the issue with spinlock assert on nRF5340.

samples: matter: Fixed issue with spinlock assert on 53 family

---

scripts/tools-versions-darwin.yml
scripts/tools-versions-linux.yml
scripts/tools-versions-win10.yml

Backport d75b6f785ccbbf8f374de349fea25d89e19f77e3 from #23730.

[Backport v3.1-branch] ci: upgrade `nrfutil device==2.12.6`

---

doc/nrf/drivers/mspi_sqspi.rst
drivers/mspi/CMakeLists.txt
samples/zephyr/drivers/jesd216/boards/nrf54l15dk_nrf54l15_cpuapp_sqspi.overlay
samples/zephyr/drivers/spi_flash/boards/nrf54l15dk_nrf54l15_cpuapp_sqspi.overlay
tests/drivers/mspi/mspi_with_spis/boards/nrf54h20dk_nrf54h20_cpuapp_sqspi.overlay
tests/zephyr/drivers/flash/common/boards/nrf54l15dk_nrf54l15_cpuapp_sqspi.overlay

This is a follow-up to #23514.
Offsets of the register interface for sQSPI soft peripherals (so in consequence the base addresses of the related nodes in dts) have been changed in sQSPI v1.0.0 for both the nRF54l15 and nRF54h20. Update accordingly dts overlays in samples and tests, and also the sQSPI MSPI shim driver documentation and its cmake definitions.

samples|tests: drivers: Adjust overlays to align with sQSPI v1.0.0

---

boards/shields/pca63565/boards/nrf54l15dk_nrf54l15_cpuflpr.conf
scripts/quarantine.yaml

Backport 481c6e5ffc4809167758c41fce122f46b630f978~2..481c6e5ffc4809167758c41fce122f46b630f978 from #23694.

[Backport v3.1-branch] boards: shields: pca63565: remove NRF_SYS_EVENT on FLPR

---

samples/bluetooth/fast_pair/input_device/README.rst

Updates Personalized Name testing steps documentation, as the bug on Android has been fixed for Android 16.
Jira: NCSDK-34507

samples: bluetooth: fast_pair: input_device: Update PN testing steps doc

---

doc/nrf/drivers/mspi_sqspi.rst
drivers/mspi/CMakeLists.txt
drivers/mspi/mspi_sqspi.c
samples/zephyr/drivers/jesd216/boards/nrf54l15dk_nrf54l15_cpuapp_sqspi.overlay
samples/zephyr/drivers/spi_flash/boards/nrf54l15dk_nrf54l15_cpuapp_sqspi.overlay
tests/drivers/mspi/mspi_with_spis/boards/nrf54h20dk_nrf54h20_cpuapp_sqspi.overlay
tests/zephyr/drivers/flash/common/boards/nrf54l15dk_nrf54l15_cpuapp_sqspi.overlay
west.yml

Backport commits from https://github.com/nrfconnect/sdk-nrf/pull/23514 and #23728 to v3.1-branch.

[Backport v3.1-branch] manifest: sdk-nrfxlib: softperipheral: rev a9c676e2a695e9644c11fea3e9eef5d8e845247e

---

tests/benchmarks/power_consumption/common/main.c

Backport 8267015c604539caeeefd54f905dfe3529a54d73 from #23751.

[Backport v3.1-branch] tests: benchmark: power_consumption: Increase stack size

---

west.yml

Includes a fix for being able to use pure and sha512 for MCUboot signing

[Backport v3.1-branch] manifest: Update sdk-zephyr

---

samples/pmic/native/npm1300_fuel_gauge/src/fuel_gauge.c

Backport 20f8206a2023100a134430985b22f15d488d4fa7 from #23792.

[Backport v3.1-branch] samples: pmic: npm1300_fuel_gauge: reverse current sign

---

scripts/quarantine_windows_mac.yaml
west.yml

Removed Matter samples from Windows quarantine as related build issue was solved.

quarantine_windows: Removed Matter samples from quarantine

---

scripts/ci/test_plan.py

We always want round numbers up.
For example:
If tests_per_builder=10 and tests=11, we want to run on 2 builders

tests: Fix --tests_per_builder logic

---

tests/drivers/adc/adc_latency/src/main.c

Remove some too short tACQ test settings

tests: drivers: adc: Fix ADC latency test

---

doc/nrf/libraries/dfu/dfu_multi_image.rst

A section describing DFU multi image with SUIT was still present, which is no longer valid.

doc: Remove mention of SUIT in dfu_multi image doc

---

doc/nrf/libraries/dfu/dfu_multi_image.rst

Backport 4992ac53ce1b7777afc4d439b748a49c41a67cfa from #23808.

[Backport v3.1-branch] doc: Remove mention of SUIT in dfu_multi image doc

---

doc/nrf/app_dev/device_guides/nrf54h/index.rst
doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_flpr.rst
doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_ppr.rst

Backport f07dcd18f1bda9dd068ebb605d0c356c4f7a4186 from #23388.

[Backport v3.1-branch] doc: Added 54H PPR userguide

---

samples/cellular/nrf_provisioning/src/main.c
subsys/net/lib/nrf_provisioning/src/nrf_provisioning.c
subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c
subsys/net/lib/nrf_provisioning/src/nrf_provisioning_codec.c
tests/subsys/net/lib/nrf_provisioning/src/coap.c

For sample application: Add a delay for waiting IPv6 to establish. We might have DTLS session stored using IPv6 addresses, but if we retry too fast, there is only IPv4 network up and running and coap_client() fails to send.
For the provisioning library:
* Handle error codes coming from coap_client and forward to caller. Don't wait for semaphore if sending of CoAP failed.
* If sending of stored DTLS CID session failed, close the socket and retry. This allows falling back to IPv4 from IPv6 as it does a new getaddrinfo().
Fix PR fixes same issues as https://github.com/nrfconnect/sdk-nrf/pull/23786 and adds a recovery.

net: nrf_provisioning: Fixes for IPv6 network

---

samples/cellular/nrf_provisioning/src/main.c
subsys/net/lib/nrf_provisioning/src/nrf_provisioning.c
subsys/net/lib/nrf_provisioning/src/nrf_provisioning_coap.c
subsys/net/lib/nrf_provisioning/src/nrf_provisioning_codec.c
tests/subsys/net/lib/nrf_provisioning/src/coap.c

Backport 2df4adc4981cb7a29b5065169cc0f7eb6ac24b1a~3..2df4adc4981cb7a29b5065169cc0f7eb6ac24b1a from #23840.

[Backport v3.1-branch] net: nrf_provisioning: Fixes for IPv6 network

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Backport f4462151583d15af0f0fcf4400048ba82d6872d0 from #23809.

[Backport v3.1-branch] doc: Remove 3.1.0 release entries from changelog

---

applications/nrf_desktop/board_configuration.rst
samples/benchmarks/coremark/README.rst
samples/bluetooth/fast_pair/input_device/README.rst
samples/bluetooth/fast_pair/locator_tag/README.rst

Backport 7db5d9bd5fb598bd783bd265c59674fa7d8c804b~3..7db5d9bd5fb598bd783bd265c59674fa7d8c804b from #23883.

[Backport v3.1-branch] Fast Pair, nRF Desktop & Coremark: note about the broken nRF54H20 DK target

---

samples/dfu/dfu_target/pm_static_nrf52840dk_nrf52840.yml
samples/dfu/dfu_target/src/dfu_target_shell.c

Backport 7c54925b7f4304b45ea9c9305780762aa86da077 from #23841.

[Backport v3.1-branch] samples: dfu_target: fix partitions with partition manager

---

modules/openthread/Kconfig.nrf5
modules/openthread/platform/radio_nrf5.c

The current accuracy is set to 50ppm, which is not compliant with IEEE 802.15.4-2015. Moreover, we cannot use the CONFIG_CLOCK_CONTROL_NRF_ACCURACY kconfig as a return in the otPlatRadioGetCslAccuracy function because it must be configurable by users, depending on the used oscillators.
Fixes a critical bug KRKNWK-20578

modules: openthread: Fix OpenThread CSL Accuracy

---

subsys/bluetooth/services/ras/rreq/ras_rreq.c

Customers are coming to us with with logs from their apps, which end up being unhelpful because there are too many possible failure conditions for this log message.

bluetooth: ras: rreq: split up error logs for different API misuse cases

---

subsys/mpsl/fem/common/include/mpsl_fem_utils.h
west.yml

The nrf-802154 clock platform now uses the software-triggered interrupt to de-escalate ZLI context to a regular interrupt in order to safely use Zephyr API.

manifest: update zephyr, nrfxlib and nrf-802154 revisions

---

doc/nrf/releases_and_maturity/software_maturity.rst

Added a missing note regarding the rename of the Find My Device Network (FMDN) extension in the Google Fast Pair ecosystem. This extension is now called Find Hub Network (FHN) extension.

doc: sml: fast_pair: add a note about FMDN rename

---

doc/nrfx/nrfx.doxyfile.in

Backport 9497c4584480383dc4c146c8ae2f15a5d748e3c1 from #23871.

[Backport v3.1-branch] doc: fix for techdoc-3981

---

doc/nrf/app_dev/device_guides/nrf54l/kmu_provision.rst

Rephrase in order to be more precise: the keyfile.json generation and the provisioning during flashing are separate features.
Did as post review response to:
https://github.com/nrfconnect/sdk-nrf/pull/23569/files#r2247372554

doc/nrf/app_dev/../nrf54l/kmu_provision: correct desc. on `west flash`

---

tests/benchmarks/current_consumption/nfc_idle/testcase.yaml
tests/benchmarks/multicore/idle_spim_loopback/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
tests/benchmarks/multicore/idle_spim_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_fast.overlay
tests/benchmarks/multicore/idle_spim_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_fast_slow_pins.overlay
tests/benchmarks/multicore/idle_spim_loopback/testcase.yaml
tests/benchmarks/power_consumption/adc/testcase.yaml
tests/benchmarks/power_consumption/adc_async/testcase.yaml
tests/benchmarks/power_consumption/gpio/testcase.yaml
tests/benchmarks/power_consumption/i2c/testcase.yaml
tests/benchmarks/power_consumption/lpcomp/testcase.yaml
tests/benchmarks/power_consumption/qdec/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
tests/benchmarks/power_consumption/qdec/testcase.yaml
tests/benchmarks/power_consumption/uart_interrupt/testcase.yaml

Backport 11e9726efbaafa8db6f7e812fa2a0bc89f1b3ca2 from #23934.

[Backport v3.1-branch] tests: benchmarks: Fix failing benchmark tests

---

doc/nrf/releases_and_maturity/software_maturity.rst

SDC does not limit the number of connections to 20. Also, it is more than just the central, observer, peripheral, and broadcaster roles that can be used concurrently.

doc: software_maturity: Remove 20-connection limit from BLE support docs

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cipher.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.c
subsys/nrf_security/src/drivers/cracen/silexpk/src/blind.c
subsys/nrf_security/src/drivers/cracen/silexpk/src/iomem.c
subsys/nrf_security/src/drivers/cracen/silexpk/target/baremetal_ba414e_with_ik/pk_baremetal.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/aead.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/blkcipher.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/chachapoly.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/cmac.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/cmdma.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/cmmask.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/hash.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/hmac.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/keyref.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/mac.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/sha3.c

Update variable naming to remove single symbol variable names 
Ignored mathmatical notation
Counter variables were not changed
This should make the code more readable

nrf_security: CRACEN: Remove single symbol variable names

---

west.yml

* The documentation will be updated in the nrfxlib in the backport of this PR: https://github.com/nrfconnect/sdk-nrfxlib/pull/1826
* This PR updates the sha in manifest to point to the corresponding commit with updated docs in nrf-802154 release branch (https://github.com/nrfconnect/sdk-nrf-802154/commits/v3.1-branch/)

Final nrf-802154 docs for 3.1.0

---

subsys/bluetooth/controller/Kconfig
subsys/bluetooth/controller/hci_driver.c

Issue CS event length command when opening the HCI driver

bluetooth: hci driver: issue cs event length vs command on open()

---

tests/drivers/adc/adc_latency/testcase.yaml

The ADC latency test requires 'gpio_loopback'

tests: drivers: adc: Add fixture to ADC latency test

---

applications/matter_weather_station/README.rst
doc/nrf/protocols/matter/end_product/bootloader.rst
doc/nrf/protocols/matter/end_product/test_event_triggers.rst
samples/matter/lock/README.rst

Fixed few references in Matter docs to SB configs that were incorrect.

doc: Fixed SB configs references in Matter documents

---

subsys/bluetooth/rpc/client/bt_rpc_gap_client.c

From zephyr/bluetooth/bluetooth.h, the second parameter should be const struct

bluetooth: rpc: Correct bt_le_ext_adv_start definition

---

cmake/sysbuild/image_signing.cmake
cmake/sysbuild/image_signing_firmware_loader.cmake
cmake/sysbuild/image_signing_split.cmake
cmake/sysbuild/sign_nrf54h20.cmake
west.yml

This commit adds changes which are necessary to support the AES256 encryption algorithm in mcuboot.

bootloader: mcuboot: Changes needed to support AES256

---

doc/nrf/protocols/wifi/regulatory_certification/using_wifi_shell_sample.rst
doc/nrf/protocols/wifi/regulatory_certification/using_wifi_station_sample.rst

Update build instructions to use the correct
config file for enabling `CONFIG_NRF70_UTIL`.
Also add the missing instruction in the
`using_wifi_shell_sample` doc.
Fixes SHEL-3750.

doc: wifi: Fix `CONFIG_NRF70_UTIL` config setting

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/matter/lock/src/zcl_callbacks.cpp

The Matter Lock sample did not react to auto-relock after invoking this request by the controller.
The issue was that the callback for this feature was not implemented in the Lock sample.

samples: matter: Fix doorlock auto-relock

---

doc/nrf/links.txt

doc: fix link to IronSide SE 22.2.0+14

---

doc/nrf/app_dev/device_guides/nrf54h/ug_nrf54h20_gs.rst
doc/nrf/links.txt
doc/nrf/releases_and_maturity/abi_compatibility.rst
doc/nrf/releases_and_maturity/migration/migration_3.1_54h_suit_ironside.rst
doc/nrf/releases_and_maturity/migration/migration_guide_3.1.rst

Backport 893b0b6040e6b7bacdb5fcb57896e6a53d395066 from #24044.

[Backport v3.1-branch] doc: Improvements to nRF54H documentation

---

sysbuild/Kconfig.cracen

Limits this so it only shows for devices that support microcoding loading

sysbuild: Limit CRACEN microcode loading selection

---

applications/serial_lte_modem/sample.yaml
applications/serial_lte_modem/src/slm_ctrl_pin.c

Fix compilation errors without power or indicate pins configured, i.e., having them -1. This is regression from PR #22870. Also added these configurations into twister runs.
Jira: SLM-121

applications: serial_lte_modem: Fix compilation without pins

---

snippets/nrf91-modem-trace-uart/snippet.yml

Support TPM530M SoC for modem trace over UART.

snippet: nrf91-modem-trace-uart: Support TPM530M SOC

---

doc/nrf/releases_and_maturity/known_issues.rst

If a Matter controller attempts to commission a device to the same Matter fabric to which it is already commissioned, the failsafe procedure is triggered.
In this case, the new NOC key is discarded, but the old NOC key is not restored.
This issue is caused by a bug where the same PSA key ID is used for both the active and pending NOC keys.
When the pending key is being destroyed, the active key is also destroyed. As a result, the TC-OPCREDS-3.8 certification test fails.

doc: matter: Add known issue entry for PSA NOC bug

---

doc/nrf/app_dev/device_guides/nrf91/nrf91_building.rst
doc/nrf/shortcuts.txt

Changes to FOTA docs due to moving from child/parent images build system to the new sysbuild build system.
TECHDOC-3821

doc: update 91 Series DFU docs to reflect changes with sysbuild

---

doc/nrf/installation/install_ncs.rst
doc/nrf/installation/updating.rst
doc/nrf/links.txt

Updated install_ncs.rst and updating.rst for the latest VSC release. install_ncs.rst now mentions the step to select the SDK type. updating.rst mentions Open terminal in Welcome View.

doc: install: update for latest VSC release

---

include/tone.h
lib/tone/tone.c
tests/lib/tone/src/main.c

OCT-3436
Update the library to allow tones of 8-, 24- and 32-bit samples and 8-, 16 and 32-bit carrier widths to be generated.
Twister test cases included.

lib: tone: Generate tones of differing sample and carrier widths

---

subsys/nrf_security/src/drivers/cracen/cracenpsa/src/ecdsa.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/sign.c

ECDSA_SIGN/VERIFY_HASH should not require a hash algorithm to be present. Updated so only sign message requires one.

nrf_security: CRACEN: Let ecdsa sign/verify digest without hash

---

boards/shields/coverage_support/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
boards/shields/coverage_support/boards/nrf54h20dk_nrf54h20_cpurad.overlay

Still needed but removed during IRON integration.

boards: shields: coverage_support: extend app code partition at h20

---

applications/nrf5340_audio/doc/configuration.rst
applications/serial_lte_modem/doc/slm_description.rst
doc/nrf/releases_and_maturity/releases/release-notes-2.8.0-preview1.rst
doc/nrf/releases_and_maturity/releases/release-notes-2.8.0.rst
samples/cellular/nrf_cloud_multi_service/README.rst

Define App and sample-specific Kconfig options
that are mentioned in the 2.8 release notes.
NCSDK-30408

doc: Define App and sample-specific Kconfig options

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Adds notes related to changing memory map and crypto backend for nRF54LM20.
Jira: NCSDK-34491
Jira: NCSDK-34490

doc: fast_pair: release-notes-changelog: Add nRF54LM20 release notes

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Mentions addition of nRF54LM20 support in Coremark and Fast Pair samples.
Jira: NCSDK-34262
Jira: NCSDK-35011

doc: release-notes-changelog: nRF54LM20 support in Coremark and Fast Pair

---

subsys/nrf_security/src/CMakeLists.txt
subsys/nrf_security/src/legacy/CMakeLists.txt

Backport 4dca821cd51b3b34440cc30e765f86e38bce27b1 from #24053.

[Backport v3.1-branch] nrf_security: Moving block_cipher.c to libmbedcrypto

---

snippets/nrf91-modem-trace-uart/snippet.yml

Backport 22555da99cfb629700e7499de485f4ab7570146c from #23693.

[Backport v3.1-branch] snippet: nrf91-modem-trace-uart: Support TPM530M SOC

---

samples/benchmarks/coremark/README.rst

Backport 6df965071eee81dbb74f24fe3abb53247f0e087d from #24115.

[Backport v3.1-branch] doc: coremark: Describe nRF54LM20 support

---

doc/nrf/releases_and_maturity/software_maturity.rst
samples/bluetooth/fast_pair/locator_tag/README.rst

Backport ef853d886a5c7d7bb9b196f937d48121ad2449ac from #24110.

[Backport v3.1-branch] doc: fast_pair: Describe nRF54LM20 support

---

samples/bluetooth/direct_test_mode/src/transport/dtm_hci.c

The c standard doesn't allow doing this, so we should scope it.

samples: dtm: Scope an invalid decl inside switch statement

---

tests/drivers/timer/grtc_timer_lfrc/src/main.c

Extend limits for checks when coverage mode is used.

tests: drivers: timer: grtc_timer_lfrc: more diff allowed in coverage

---

samples/ipc/ipc_service/Kconfig.common
samples/ipc/ipc_service/Kconfig.sysbuild
samples/ipc/ipc_service/README.rst
samples/ipc/ipc_service/boards/nrf7002dk_nrf5340_cpuapp.conf
samples/ipc/ipc_service/boards/nrf7002dk_nrf5340_cpuapp_icbmsg.conf
samples/ipc/ipc_service/boards/nrf7002dk_nrf5340_cpuapp_icbmsg.overlay
samples/ipc/ipc_service/boards/nrf7002dk_nrf5340_cpuapp_icmsg.conf
samples/ipc/ipc_service/boards/nrf7002dk_nrf5340_cpuapp_icmsg.overlay
samples/ipc/ipc_service/boards/nrf7002dk_nrf5340_cpuapp_ns.conf
samples/ipc/ipc_service/remote/boards/nrf7002dk_nrf5340_cpunet.conf
samples/ipc/ipc_service/remote/boards/nrf7002dk_nrf5340_cpunet_icbmsg.conf
samples/ipc/ipc_service/remote/boards/nrf7002dk_nrf5340_cpunet_icbmsg.overlay
samples/ipc/ipc_service/remote/boards/nrf7002dk_nrf5340_cpunet_icmsg.conf
samples/ipc/ipc_service/remote/boards/nrf7002dk_nrf5340_cpunet_icmsg.overlay
samples/ipc/ipc_service/sample.yaml

Added board overlay files, updated the Kconfig to support the nRF7002DK, and revised the documentation accordingly.

samples: ipc: ipc-service: Added NRF7002DK Support

---

samples/bluetooth/central_uart/src/main.c

Update the error handling logic for the bt_scan_stop() call in the connected callback to print an error message if the function returns an error.
This fixes the issue where the error message was incorrectly printed on success.

samples: bluetooth: central_uart: fix error handling for bt_scan_stop()

---

doc/nrf/protocols/thread/overview/ot_memory.rst

In the previous PR that added measured memory values for nRF54LM20, the change that includes table to ot memory requirements was missing.

doc: Fixed ot memory requirements for nRF54LM20

---

doc/nrf/app_dev/device_guides/pmic/index.rst
doc/nrf/app_dev/device_guides/pmic/npm1304.rst
doc/nrf/links.txt
samples/pmic/native/npm13xx_fuel_gauge/README.rst
samples/pmic/native/npm13xx_one_button/README.rst

Add "Developing with the nPM1304 PMIC" document
to the list of "Developing with PMICs" guide document. Update links accordingly.

doc: working_with_nrf: Add npm1304 pmic

---

tests/lib/gcf_sms/src/main.c

This test was previously dependent on a specific Kconfig, which was never defined, and so has never been run.

tests: lib: gcf_sms: remove test_gcf_sms_cmss

---

subsys/partition_manager/pm.yml.pcd
subsys/partition_manager/pm.yml.trustzone

The PCD partition is configured as non secure from TF-M but it was placed in the secure area by partition manager. Move the PCD partition to the non secure region where it should be.
Ref: NCSDK-33735
(cherry picked from commit 2791fbf3e7f7e0048d7fe003200abb7fe18e0f14)

partition_manager: Move PCD partition to non secure flash

---

west.yml

Ticket: https://nordicsemi.atlassian.net/browse/NRFX-8270
Backport 23305.

[Backport v3.1-branch] manifest: Update sdk-zephyr revision

---

doc/nrf/releases_and_maturity/software_maturity.rst

nRF54LM20 has experimental Bluetooth support. Production support is scheduled and requires qualification evidence.

doc: experimental Bluetootth support for nRF54LM20

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
doc/nrf/releases_and_maturity/software_maturity.rst
doc/nrf/security/crypto/crypto_supported_features.rst
doc/nrf/security/crypto/drivers.rst
samples/crypto/psa_tls/README.rst

Added nRF54LM20 to the list of supported cryptographic features. Updated software_maturity.rst.
Updated other related pages.
NCSDK-30601 and NCSDK-33434.

doc: security: add nRF54LM20 support

---

subsys/bootloader/cmake/packaging.cmake

Select the application image path based on encryption support, matching the behavior of zip packaging.
Tested using nRF54L15 and Matter OTA. This change only includes application image, as support for network core or mcuboot encryption is not present in the build system today. This addresses the customer needs.

sysbuild: packaging: Fix selection of application image path

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

There are three samples which recently removed support for the thingy53 non secure target, these are the peripheral lbs/status/uart.  In the docs by accident the peripheral_status was listed twice so fix this.

doc: Minor fix in samples which don't support thingy53

---

subsys/mpsl/fem/Kconfig

Add missing Kconfig selects for `CONFIG_MPSL_FEM_NRF21540_GPIO_SPI`.

mpsl: fem: nrf21540_gpio_spi: enable missing dependencies

---

doc/nrf/releases_and_maturity/known_issues.rst

Add known issue for nRF Desktop: `System state indication LED does not work on nRF54L15 DK`.
Jira: NCSDK-34743

doc: known_issues: Add NCSDK-34743

---

subsys/bluetooth/controller/hci_driver.c

This is added to ensure the controller does not have the local feature bit set for privacy unless the hci commands are supported.
This was an issue after 7599d81 where the feature bits were moved from nrf to internal sdc.

bluetooth: controller: Use new sdc_support_le_privacy

---

boards/shields/coverage_support/boards/nrf52840dk_nrf52840.overlay

Needed as there is a lot of data at uart in coverage mode. The same as for other platforms in this shield.

boards: shields: coverage_support: add flow-control for uart at nrf52840

---

samples/dfu/dfu_target/README.rst

Sample's readme file is not generated properly due to missing an empty line.

samples: Add missing empty line in sample's readme

---

tests/subsys/ipc/ipc_latency/src/main.c
tests/subsys/ipc/ipc_latency/testcase.yaml

Test with additional configurations for nrf54h:
- with MRAM always ON
- with S2RAM enabled

tests: subsys: Extend IPC latency test

---

samples/benchmarks/coremark/boards/nrf54lv10dk_nrf54lv10a_cpuapp.conf
samples/benchmarks/coremark/sample.yaml
scripts/quarantine_integration.yaml

Enable building and execution for LV10.

samples: benchmarks: coremark: enable for LV10

---

doc/nrf/releases_and_maturity/migration/migration_guide_3.0.rst

Change adds a migration guide entry to improve visibility.
Jira: NCSDK-35238

doc: migration: Add Bluetooth LE legacy pairing entry for NCS 3.0

---

cmake/sysbuild/image_signing.cmake
cmake/sysbuild/image_signing_split.cmake
cmake/sysbuild/partition_manager.cmake

If building with revert functionality, generate the confirmed images so the application will boot after flashing the default set of artifacts.
Ref: NCSIDB-1208

cmake: Generate confirmed images in Direct XIP

---

doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_adding_sysbuild.rst

Replace section documenting reduction of flash memory size. MCUBoot's prj_minimal.conf is now deprecated.
smp_svr_mini_boot sample should be used as a reference for flash size optimization activities.
Ref: NCSIDB-1056

doc: bootloaders_dfu: Redirect to minimal config sample

---

samples/cellular/nrf_cloud_multi_service/README.rst

The help uses hyphen not underscore (nrfcloud-utils==3.0.5).

samples: cellular: nrf_cloud_multi_service: Fix typo

---

CODEOWNERS

No longer part of the Nordic org.

codeowners: Remove @vivekuppunda

---

samples/esb/esb_monitor/boards/nrf54h20dk_nrf54h20_cpurad.overlay
samples/esb/esb_prx/boards/nrf54h20dk_nrf54h20_cpurad.overlay
samples/esb/esb_ptx/boards/nrf54h20dk_nrf54h20_cpurad.overlay

Keep using uart dedicated for radio core.
test_proprietary: PR-112

samples: esb: restore default logging for h20 radio core

---

CODEOWNERS

Add the `@nrfconnect/ncs-memfault` team to the owners for the Memfault
module and sample app.
Signed-off-by: Noah Pendleton <noah.pendleton@nordicsemi.no>

CODEOWNERS: add `ncs-memfault` team to module + sample

---

scripts/tools-versions-darwin.yml
scripts/tools-versions-linux.yml
scripts/tools-versions-win10.yml

Backport 19259e162d9ae446d7fb76c85fbd6f0e99089bb2 from #24407.

[Backport v3.1-branch] tools: Update nrfutil device version to 2.13.2

---

doc/nrf/app_dev/bootloaders_dfu/mcuboot_nsib/bootloader_partitioning.rst
doc/nrf/app_dev/create_application.rst
doc/nrf/app_dev/device_guides/nrf53/building_nrf53.rst
doc/nrf/app_dev/device_guides/thingy53/building_thingy53.rst
doc/nrf/app_dev/device_guides/thingy91/thingy91_building_programming.rst
doc/nrf/includes/matter_sample_wifi_flash.txt
doc/nrf/includes/vsc_build_and_run_series.txt
doc/nrf/installation/install_ncs.rst
doc/nrf/installation/updating.rst
doc/nrf/links.txt
doc/nrf/releases_and_maturity/migration/migration_guide_3.2.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Updated the page for simplified installation of SDK and toolchain
in one bundle.
Added links to the extension UI.
TECHDOC-4046.

doc: install: updates for bundled SDK/toolchain installation

---

boards/nordic/nrf54lv10dk/board.cmake

Replace soc with board.
Soc does not exist.

boards: nordic: Clean up config name

---

modules/memfault-firmware-sdk/Kconfig
modules/memfault-firmware-sdk/config/memfault_platform_config_extra.h

Three Kconfig style issues were caught by a style script shared in https://github.com/zephyrproject-rtos/zephyr/issues/94780#issuecomment-3210257794:
```
MEMFAULT_HTTP_USES_MBEDTLS in nrf/modules/memfault-firmware-sdk/Kconfig has issues:
* default n for bool
MEMFAULT_NCS_STACK_METRICS in nrf/modules/memfault-firmware-sdk/Kconfig has issues:
* wrong help text indent
MEMFAULT_CDR_ENABLE in nrf/modules/memfault-firmware-sdk/Kconfig has issues:
* default n for bool
```
This PR addresses 2/3 of these:
- `MEMFAULT_NCS_STACK_METRICS`
- `MEMFAULT_CDR_ENABLE` – this is a redefinition of a symbol in the Memfault module to override the `default y` and select another Kconfig:
- There is no clear reason to make it `default y`. Code and RAM space added is reasonable: +460B flash, +224B RAM when …

memfault: fix kconfig style issues

---

lib/nrf_modem_lib/nrf_modem_os_rpc.c

Added IronSide SE support for nRF92.
NCSDK-33800

lib: nrf_modem_lib: Add IronSide SE support for nRF92

---

doc/nrf/app_dev/device_guides/fem/2220ek_dev_guide.rst
doc/nrf/app_dev/device_guides/fem/index.rst
doc/nrf/releases_and_maturity/software_maturity.rst

The FEM support table is updated to the form where the term `Supported` refers to maturity levels. The layout is similar to the "Protocol support" you can see [here](https://docs.nordicsemi.com/bundle/ncs-latest/page/nrf/releases_and_maturity/software_maturity.html#protocol_support)
The following FEM implementations support now nRF54LM20 SoC: `nRF2220`, `nRF21540 GPIO+SPI`. For them the SoC is claimed `Supported`. Note that implementations `nRF21540 GPIO` and `Simple GPIO` are not claimed as `Supported`.
The nRF2220EK doc is updated to mention nRF54LM20DK specifics.

doc: FEM for nRF54LM20

---

modules/memfault-firmware-sdk/Kconfig
west.yml

Upgrade the Memfault Firmware SDK to version 1.29.0 to include a fix
required to remove a Kconfig style issue. The redefinition includes a
`default n`, which causes the Kconfig style check shared in
https://github.com/zephyrproject-rtos/zephyr/issues/94780#issuecomment-3210257794 to fail.
Kconfig style check script passes after this change.
Additionally, confirmed that the Kconfig values are expected from
building the samples/debug/memfault app for a nrf9160 target:
- CONFIG_NRF_MODEM_LIB=y
- CONFIG_MEMFAULT_HTTP_USES_MBEDTLS is not set
Note this is a follow-on PR to https://github.com/nrfconnect/sdk-nrf/pull/24402.
Signed-off-by: Gillian Minnehan <gillian.minnehan@nordicsemi.no>

memfault: upgrade to 1.29.0

---

samples/zephyr/subsys/mgmt/mcumgr/smp_svr/sample.yaml

No mcuboot logs in pure_dts variant.

samples: subsys: mgmt: mcumgr: smp_svr: align expected logs

---

tests/zephyr/drivers/flash/common/testcase.yaml

As there are boards which has different configuration.

tests: zephyr: drivers: flash: common: require external_flash fixture

---

.github/test-spec.yml

Adds the ironside se update script to the secdom test spec

test-spec: update CI-secdom-test

---

samples/zephyr/subsys/mgmt/mcumgr/smp_svr/sample.yaml

Changed method to pass overlay config for MCUboot
image to get the default configuration file from MCUboot repo. It enables logging, so #24579 can be reverted.

samples: smp_svr: pure_dts: enable logs from MCUboot

---

samples/matter/contact_sensor/sysbuild/mcuboot/boards/nrf54lm20dk_nrf54lm20a_cpuapp_internal.conf
samples/matter/light_bulb/sysbuild/mcuboot/boards/nrf54lm20dk_nrf54lm20a_cpuapp_internal.conf
samples/matter/light_switch/sysbuild/mcuboot/boards/nrf54lm20dk_nrf54lm20a_cpuapp_internal.conf
samples/matter/lock/sysbuild/mcuboot/boards/nrf54lm20dk_nrf54lm20a_cpuapp_internal.conf
samples/matter/manufacturer_specific/sysbuild/mcuboot/boards/nrf54lm20dk_nrf54lm20a_cpuapp_internal.conf
samples/matter/smoke_co_alarm/sysbuild/mcuboot/boards/nrf54lm20dk_nrf54lm20a_cpuapp_internal.conf
samples/matter/temperature_sensor/sysbuild/mcuboot/boards/nrf54lm20dk_nrf54lm20a_cpuapp_internal.conf
samples/matter/template/sysbuild/mcuboot/boards/nrf54lm20dk_nrf54lm20a_cpuapp_internal.conf
samples/matter/thermostat/sysbuild/mcuboot/boards/nrf54lm20dk_nrf54lm20a_cpuapp_internal.conf
samples/matter/window_covering/sysbuild/mcuboot/boards/nrf54lm20dk_nrf54lm20a_cpuapp_internal.conf

The picolibc was enabled in mcuboot for nrf54lm20 internal configuration, what does not work and leads to mcuboot crash.

samples: matter: Fixed configuration for 54lm20 internal

---

cmake/sysbuild/sign_nrf54h20.cmake

Fix typos in nRF54H20-specific signing file to correctly pass the VID and CID values to the signing command in Direct XIP modes.

cmake: Fix VID and CID values in Direct XIP on 54

---

doc/nrf/releases_and_maturity.rst

Remove mention of devtag from the releases and maturity page.
Requested by Shantha.

doc: Remove mention of devtag from releases and maturity

---

scripts/quarantine.yaml
scripts/quarantine_zephyr.yaml

* quarantine: extend platforms for sample.bluetooth.peripherals_mds
* zephyr: more samples for nrf54lm20dk/nrf54lm20a/cpuapp

scripts: quarantine and quarantine_zephyr

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/bluetooth/mesh/sensor_client/README.rst
samples/bluetooth/mesh/sensor_client/src/model_handler.c

* Added polling toggle on first button (to include single-button hardware). This was done to avoid messaging traffic when not needed.
* Updated button mapping.
* Removed descriptor action from buttons. This is still available via shell.
* Updated docs.
Note: all PTS tests are passed.

samples: bluetooth: mesh: add poll toggle to sensor cli

---

subsys/nrf_security/src/drivers/cracen/cracen_sw/src/cracen_sw_aes_ctr.c

Remove an unnecessary check to allow for keys stored in the kmu to be used with AES in counter mode.

nrf_security: cracen: Add kmu support for ctr on nRF54LM20A

---

doc/nrf/libraries/dfu/fmfu_mgmt.rst

Added missing link to the Doxygen group of fmfu_mgmt_stat.h. NCSDK-11537.

doc: lib: fmfu_mgmt_stat.h doxygengroup link

---

subsys/nrf_security/src/drivers/cracen/cracen_sw/include/cracen_sw_common.h
subsys/nrf_security/src/drivers/cracen/cracen_sw/src/cracen_sw_aes_ctr.c
subsys/nrf_security/src/drivers/cracen/cracen_sw/src/cracen_sw_cipher.c
subsys/nrf_security/src/drivers/cracen/cracen_sw/src/cracen_sw_common.c
subsys/nrf_security/src/drivers/cracen/cracen_sw/src/cracen_sw_mac_cmac.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/include/cracen_psa_primitives.h
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/cipher.c
subsys/nrf_security/src/drivers/cracen/cracenpsa/src/common.h
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/include/sxsymcrypt/internal.h
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/blkcipher.c
subsys/nrf_security/src/drivers/cracen/sxsymcrypt/src/chachapoly.c

Refactoring of the Cracen driver for cipher to reduce stack usage. See commits for details.

nrf_security: Cracen cipher stack reduction

---

boards/shields/coverage_support/boards/nrf54l15dk_nrf54l15_cpuapp.overlay

Was used with this shield but not enabled.

boards: shields: coverage_support: enable rng for L15

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Change introduces a release note informing about removal of the Fast Pair TinyCrypt cryptographic backend.
Jira: NCSDK-35469

bluetooth: fast_pair: Add a release note for removing TinyCrypt

---

lib/st25r3911b/st25r3911b_interrupt.c

Fixed spinlock ussage with the blocking SPI API,
using mutex instead.
JIRA: NCSDK-35618

st25r3911b: Fixed wrong spinlock ussage

---

scripts/docker/Dockerfile

This fixes the following error
```
/bin/bash: line 1: bin/bash: No such file or directory
```
which happens when changing working directory (e.g. in a Dockerfile that uses this image as base and changes `WORKDIR` or by using `-w` flag in `docker run`)

docker: Use absolute path for bash in CMD

---

doc/nrf/app_dev/create_application.rst
doc/nrf/installation/install_ncs.rst

Restored links to VSCode walkthroughs as they are now handled correctly. TECHDOC-3868.
Links were removed temporarily in #24415 .

doc: install: restore walkthrough links

---

applications/nrf_desktop/doc/usb_state.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Change adds release notes for changes introduced as Zephyr upmerge fixes. Change also slightly aligns the USB state module documentation.
Jira: NCSDK-35469

applications: nrf_desktop: Add release notes for Zephyr upmerge fixes

---

subsys/net/lib/downloader/src/transports/coap.c

Retransmission logic in the CoAP downloader was not correctly implemented, causing it to not retransmit requests as expected. 
this is a simple fix which just adds re-transmission flag as a trigger to request next fragment.

net: downloader: coap: Request data fragment on retransmission flag

---

applications/nrf_desktop/src/modules/hid_provider_consumer_ctrl.c
applications/nrf_desktop/src/modules/hid_provider_keyboard.c
applications/nrf_desktop/src/modules/hid_provider_mouse.c
applications/nrf_desktop/src/modules/hid_provider_system_ctrl.c
applications/nrf_desktop/src/modules/hid_state.c
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst

Change updates HID state module to allow for delayed registration of HID report providers. Change also introduces an additional assertion in HID provider implementations to ensure safety.
Jira: NCSDK-35360

applications: nrf_desktop: Allow for delayed HID provider registration

---

scripts/quarantine.yaml
west.yml

Upgrade the Memfault SDK to version 1.30.0, which includes removal of a deprecated Zephyr bluetooth API for Zephyr 4.2+.

memfault: upgrade to 1.30.0

---

applications/nrf_desktop/doc/hid_provider_consumer_ctrl.rst
applications/nrf_desktop/doc/hid_provider_keyboard.rst
applications/nrf_desktop/doc/hid_provider_system_ctrl.rst

Change slightly aligns documentation pages of HID keyboard, system control and consumer control report providers to improve consistency.
Jira: NCSDK-35470

applications: nrf_desktop: Align HID providers' documentation

---

subsys/mpsl/init/Kconfig

The HFXO startup time is configured in bicr and is therefore not available in device tree or Kconfig
on this platform.
Going forward we could consider deprecating it completely and only rely on the device tree entries.

mpsl: Make CONFIG_MPSL_HFCLK_LATENCY on 54H unavailable

---

subsys/mpsl/init/mpsl_init.c

This API call is no longer needed. It has been a no-op for a long period of time.

mpsl: Remove call to unecessary call to mpsl_pan_rfu

---

boards/nordic/nrf54lv10dk/nrf54lv10dk_nrf54lv10a-pinctrl.dtsi

Even in sleep state TX and RTS should have pull as otherwise pins are floating and can give corrupted output on the console.

boards: nordic: nrf54lv10dk: Use pull-up for TX, RTS in sleep state

---

subsys/bluetooth/controller/hci_driver.c

The sdc_support_* functions will soon be updated to return void.
This is a temporary change to support both APIs until the new SDC support API has made its way to nrfxlib.

bluetooth: hci_driver: Prepare for new sdc_support_* API

---

subsys/bluetooth/cs_de/cs_de.c

This commit fixes an issue where the pcts in
`bt_hci_le_cs_step_data_tone_info` were not mapped to the correct antenna path in the
`cs_de_report_t`.
This would cause pcts from random antenna
paths in `cs_de_report.iq_tones[n]`, which
is expected to only contain pcts from antenna
path `n`.

bluetooth: cs_de: Fix issue with unpacking of pcts

---

scripts/quarantine.yaml
scripts/quarantine_zephyr.yaml

Test configuration for scenarios are added to quarantine due to FLASH overflow.
Jira: NCSDK-35522

quarantine: Add quarantine for machine learning

---

samples/dfu/dfu_multi_image/src/dfu_multi_image_shell.c

Add log message when DFU multi image write operation completes successfully.
This helps with testing, as it allows to avoid situations where a new command is written before the old write has finished.

samples: dfu_multi_image: Add success log for write operations

---

samples/dfu/dfu_target/src/dfu_target_shell.c

Add log message when DFU target write operation
completes successfully.
This helps with testing, as it allows to avoid situations where a new command is written before the old write has finished.

samples: dfu_target: Add success log for write operations

---

applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/app_common.dtsi
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpurad/images/ipc_radio/app.overlay
subsys/mcuboot/mcuboot_secondary_app.overlay
west.yml

Use secondary_app_partition as code partition in Direct XIP without partition manager.
This allows to define slot0/1 partitions independently from the application's code partition.
Ref: NCSDK-35612

mcuboot: Use secondary_app_partition

---

applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/images/uicr/app.overlay
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/images/uicr/app_dongle.overlay
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/images/uicr/app_release.overlay
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/images/uicr/app_release_dongle.overlay
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/images/uicr/prj.conf
applications/nrf_desktop/sysbuild/CMakeLists.txt

Updated the nRF Desktop configuration for the nRF54H20 DK board target to include the configuration of the new UICR sysbuild image.
Ref: NCSDK-35658

applications: nrf_desktop: nrf54h20dk: add uicr image configuration

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/net/nrf_cloud_fota_poll.h
include/net/nrf_cloud_pgps.h

Missing brackets were reported by a customer through DevZone when trying to compile his project in C++.
Devzone ticket: 351769

include: net: Include missing brackets

---

doc/nrf/releases_and_maturity/migration/migration_guide_3.2.rst
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/modem/lte_lc.h
lib/lte_link_control/modules/mdmev.c
lib/nrf_modem_lib/lte_net_if/lte_net_if.c
modules/memfault-firmware-sdk/memfault_lte_metrics.c
samples/cellular/modem_shell/src/link/link_shell_print.c
samples/cellular/modem_shell/src/link/link_shell_print.h
samples/cellular/nidd/src/main.c
tests/lib/lte_lc_api/src/lte_lc_api_test.c

Because of new modem events which have values, there was need to rework how modem events are delivered in `struct lte_lc_evt`.
The `enum lte_lc_modem_evt` has been replaced by a `struct lte_lc_modem_evt` which contains the modem event type and possible associated payload. This requires a minor code change to all applications using modem events.
Modem events `LTE_LC_MODEM_EVT_CE_LEVEL_0`, `LTE_LC_MODEM_EVT_CE_LEVEL_1`, `LTE_LC_MODEM_EVT_CE_LEVEL_2` and `LTE_LC_MODEM_EVT_CE_LEVEL_3` have been replaced by event `LTE_LC_MODEM_EVT_CE_LEVEL`, which has associated payload for the value.
Added support for new modem events:
```
LTE_LC_MODEM_EVT_RF_CAL_NOT_DONE
LTE_LC_MODEM_EVT_INVALID_BAND_CONF
LTE_LC_MODEM_EVT_DETECTED_COUNTRY
```
TODO:

lib: lte_link_control: Rework modem events

---

scripts/west_commands/ncs_ironside_se_update.py

nrfutil device reset --reset-kind RESET_VIA_SECDOM will incorrectly fail as SDROM spends seconds applying the update and nrfutil times out. The reset has been correctly performed, and there is no reason to fail.
To work around this issue, we accept the failure and don't exit the script.

west_commands: fix ironside update script

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
subsys/net/lib/nrf_cloud/src/nrf_cloud_log_backend.c

A customer (@jens-ajisai) reported a missing prefix: https://github.com/nrfconnect/sdk-nrf/pull/24821
Thanks @jens-ajisai for the contribution.

net: lib: nrf_cloud: Add missing CONFIG_ prefix

---

subsys/bluetooth/controller/hci_driver.c

SDC_USE_NEW_SDC_SUPPORT_API:
The sdc_support_* API that returns void is now in use in nrfxlib. So there is no need to support the old API.
SDC_USE_NEW_MEM_API:
This was added in d53b1554dbce7f3695b4d193c2ef36c39063fb7b and should have been removed a long time ago.

bluetooth: hci-driver: Remove temporary defines

---

lib/location/scan_wifi.c

If location is cancelled during Wi-Fi search, the semaphore
blocking the location positioning workqueue is not released due to
k_sem_reset() being used instead of k_sem_give(). This prevents
subsequent location requests to start Wi-Fi scans.
This commit changes k_sem_reset() to k_sem_give() and adds a test
for this scenario.
LRCS-343

lib: location: Use k_sem_give() when cancelling Wi-Fi location

---

subsys/bootloader/bl_boot/bl_boot.c

Add the cleanup, as a result also fixing the build warning about an unused function for nRF54LV15.

bootloader: Add UARTE30 peripheral cleanup

---

doc/nrf/security/psa_certified_api_overview.rst
modules/trusted-firmware-m/Kconfig
subsys/nrf_security/Kconfig.psa
subsys/nrf_security/cmake/config_to_tf-m.cmake

`CONFIG_TFM_ITS_ENCRYPTED` is the one that matters here, and this is only about TF-M.
Get rid of this confusing Kconfig option.

nrf_security: remove `CONFIG_PSA_ITS_ENCRYPTED`

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
samples/bluetooth/mesh/sensor_client/sample.yaml
scripts/quarantine.yaml

After the addition of NLC profile support, involving an increase in required RPL RAM usage, and the most recent upmerge adding a few extra bytes, this sample no longer fits in RAM on this platform. Per offline discussions, remove support for this platform.

Bluetooth: Mesh: Remove nRF52832 from sensor_client

---

applications/serial_lte_modem/README.rst
doc/nrf/links.txt

Adding note that SLM will be removed before the next NCS release.
Jira: SLM-139

applications: serial_lte_modem: Add removal note

---

include/hw_unique_key.h
include/tfm/tfm_builtin_key_ids.h
modules/trusted-firmware-m/Kconfig
modules/trusted-firmware-m/tfm_boards/common/attest_hal.c
samples/keys/hw_unique_key/src/derive_key_tfm.c
subsys/nrf_security/Kconfig
subsys/nrf_security/src/drivers/Kconfig
subsys/nrf_security/src/drivers/cracen/Kconfig

The presence of CRACEN HW peripheral now uses the same pattern as others (HAS_HW_NRF_CRACEN).

nrf_security: CRACEN: Use HAS_HW_NRF_XXX naming convention

---

doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
include/modem/nrf_modem_lib_trace.h
include/modem/trace_backend.h
lib/nrf_modem_lib/nrf_modem_lib_trace.c
lib/nrf_modem_lib/trace_backends/flash/flash.c
modules/memfault-firmware-sdk/memfault_lte_coredump.c
modules/memfault-firmware-sdk/memfault_lte_coredump_modem_trace.c
tests/lib/nrf_modem_lib/nrf_modem_lib_trace/src/main.c
tests/lib/nrf_modem_lib/nrf_modem_lib_trace/trace_backend_mock.c
tests/lib/nrf_modem_lib/trace_backends/flash/CMakeLists.txt
tests/lib/nrf_modem_lib/trace_backends/flash/boards/native_sim.overlay
tests/lib/nrf_modem_lib/trace_backends/flash/prj.conf
tests/lib/nrf_modem_lib/trace_backends/flash/src/main.c
tests/lib/nrf_modem_lib/trace_backends/flash/testcase.yaml

At a glance
* Adds new API for peeking trace data at an arbitrary offset in the modem trace backend without consuming it
* Adds a corresponding backend implementation for the flash trace backend
* Updates the Memfault modem trace upload funcitonality to use the newly introduced API.
* As part of the use of the API in Memfault, refactors the LTE coredump state machine for improved maintainability. 
* Added a new function `nrf_modem_lib_trace_peek_at` to allow peeking trace data at a specified offset without advancing the read cursor, including documentation and integration into the trace backend interface (`nrf_modem_lib_trace.h`, `trace_backend.h`, `nrf_modem_lib_trace.c`). 
* Implemented the `peek_at` operation in the flash trace backend, including a caching mechanism to optimize …

Modem trace to flash: Add tests and API to peek at offset

---

applications/matter_bridge/prj.conf
applications/matter_bridge/prj_release.conf
applications/matter_weather_station/prj.conf
applications/matter_weather_station/prj_release.conf
samples/matter/contact_sensor/prj.conf
samples/matter/contact_sensor/prj_release.conf
samples/matter/light_bulb/prj.conf
samples/matter/light_bulb/prj_release.conf
samples/matter/light_switch/prj.conf
samples/matter/light_switch/prj_release.conf
samples/matter/lock/prj.conf
samples/matter/lock/prj_release.conf
samples/matter/lock/prj_thread_wifi_switched.conf
samples/matter/manufacturer_specific/prj.conf
samples/matter/smoke_co_alarm/prj.conf
samples/matter/smoke_co_alarm/prj_release.conf
samples/matter/temperature_sensor/prj.conf
samples/matter/temperature_sensor/prj_release.conf
samples/matter/template/prj.conf
samples/matter/template/prj_release.conf
samples/matter/thermostat/prj.conf
samples/matter/thermostat/prj_release.conf
samples/matter/window_covering/prj.conf
samples/matter/window_covering/prj_release.conf

Each sample now contains appropriate product name in the prj.conf file. It can be used to indicate the sample type after flashing.

samples: matter: Define device product name for each sample

---

include/modem/lte_lc.h

Removed version notes for legacy modem firmware versions.

lib: lte_link_control: Cleanup version notes for legacy MFWs

---

doc/nrf/links.txt
doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
doc/nrf/security.rst
doc/nrf/security/tfm/tfm_supported_services.rst

Added a table mapping security component versions to the nRF Connect SDK
releases. NCSDK-35652.

doc: security: components version matrix

---

west.yml

Update the Memfault SDK version from 1.30.0 to 1.30.1 .
Release notes:
https://github.com/memfault/memfault-firmware-sdk/releases/tag/1.30.1
Primarily fixes a double fault error on nRF91 + TF-M applications, during certain fault types, when `CONFIG_LOG_MODE_DEFERRED=y`. This error prevents correctly capturing a coredump when the fault occurs.

memfault: Update to 1.30.1

---

west.yml

NCSDK-35792. Manifest update for sdk-mcu-drivers.
Changed wording for Kconfig compliance.

manifest: sdk-mcu-drivers update for Kconfig compliance

---

applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/images/mcuboot/prj.conf
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/images/mcuboot/prj_dongle.conf
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/images/mcuboot/prj_release.conf
applications/nrf_desktop/configuration/nrf54h20dk_nrf54h20_cpuapp/images/mcuboot/prj_release_dongle.conf

Enabled the CONFIG_SOC_NRF54H20_PM_S2RAM_OVERRIDE Kconfig option in the MCUboot image configuration for the nRF54H20 DK target. This change is aligned with the general direction of the MCUboot-based DFU solution for the nRF54H20 SoC. It limits the bootloader reponsibility for the wake-up from the Suspend To RAM (S2RAM) state to the bare minimum and allows more flexibility when it comes to future improvements for the power management system. These improvements can be easily updated with the DFU in the application image. On the other hand, the PM code cannot be changed in the MCUboot image in the most common case where the MCUboot is set up as an immutable bootloader.
Ref: NCSDK-35408

applications: nrf_desktop: nrf54h20dk: use MCUboot custom code for PM
