lib/nrf_modem_lib/nrf_modem_os.c
Update k_work APIs.
cc: @shantha-14
=> lib: nrf_modem: update k_work API

lib/bin/lwm2m_carrier/os/lwm2m_os.c
Update k_work API.
cc: @shantha-14
=> lib: bin: lwm2m_carrier: update k_work API

lib/modem_info/Kconfig
Signed-off-by: Markus Tacker <Markus.Tacker@NordicSemi.no>
=> lib: modem_info: fix typo

drivers/gps/nrf9160_gps/nrf9160_gps.c
Don't wait for cancellation completion if cancel_works() is called
from gps_start() or gps_stop(), as those functions could be called
(via the GPS event handling routines) from the work that is to be
canceled, and in case the work is already running at that point,
waiting for it to finish would lead to a deadlock.
=> drivers: nrf9160_gps: Fix cancellation of works in gps_start/gps_stop

west.yml
See CHANGELOG for more changes
=> manifest: SDC supports multiple advertising sets

west.yml
=> manifest: Update reference to Pelion client repository

doc/nrf/known_issues.rst
Added a small fix to the known issues page.
=> doc: Small fix to known issues page

subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c
Add an extra byte to the MQTT payload buffer to ensure that
data send to the user is always NULL-terminated.
=> net: lib: nrf_cloud: ensure MQTT payload is NULL-terminated

doc/nrf/ug_fw_update.rst
Fixed a table in ug_fw_update.rst
=> doc: Small table fix ug_fw_update

subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_connmon.c
Use the recently introduced `lte_lc_lte_mode_get()` function to obtain
the currently active network mode and set it in the Connectivity
Monitoring object.
=> samples: nrf9160: lwm2m_client: Set active LTE mode properly

applications/pelion_client/src/modules/pelion.cpp
=> applications: pelion_client: Switch to new API

west.yml
Update sdk-zephyr manifest to cherry-picked changes for ieee802154.
Signed-off-by: Rafał Kuźnia <rafal.kuznia@nordicsemi.no>
=> manifest: cherry pick ieee802154 changes for zephyr

doc/nrf/known_issues.rst
Add known issue for NCSDK-9786.
Signed-off-by: Xie, Lang <lang.xie@nordicsemi.no>
=> doc: Add the issue on wrong flash page erase time

applications/asset_tracker/README.rst, applications/connectivity_bridge/README.rst
Update the path to mcuboot overlay file in
Asset Tracker and Connectivity bridge Readme files
=> doc: Update the path to mcuboot overlay file

include/caf/events/power_event.h
Change adds doxygen documentation for power events.
Jira: NCSDK-9551
=> caf: events: Add documentation for power events

include/caf/events/ble_common_event.h
Change adds doxygen documentation for BLE common events.
Jira: NCSDK-8789
=> caf: events: Add documentation for BLE common events

west.yml
Update sdk-zephyr manifest to cherry-picked changes for
flash page erase time.
Signed-off-by: Lang Xie <lang.xie@nordicsemi.no>
=> manifest: cherry pick flash page erase time change for zephyr

subsys/net/lib/icalendar_parser/src/icalendar_parser.c
An iCalendar property can be broken up over multiple lines,
where a continued line will start with a space. In the function
unfolds those lines, the null byte can be written to a location
outside the size of the buffer. This commit fixes such flaw.
Signed-off-by: Larry Tsai <larry.tsai@nordicsemi.no>
=> net: lib: icalendar_parser: fix out of bound vulnerability

lib/pelion/Kconfig, west.yml
combined manifest update for nrfxlib #478 #480 #481
those are combined in https://github.com/nrfconnect/sdk-nrfxlib/pull/482
=> combined manifest update for nrfxlib #478 #480 #481 #483

applications/machine_learning/README.rst, applications/pelion_client/README.rst, doc/nrf/gs_modifying.rst
Edited build types sections for consistency.
Added reference to apps supporting build types.
=> doc: apps: build types consistency

include/modem/lte_lc.h, include/modem/lte_lc.rst
Update documentation for link controller.
Closes CIA-304
=> include: modem: lte_lc: Update documentation for link controller

doc/nrf/includes/tfm.txt, doc/nrf/samples.rst, samples/crypto/aes_cbc/README.rst, samples/crypto/aes_ccm/README.rst, samples/crypto/aes_ctr/README.rst, samples/crypto/aes_gcm/README.rst, samples/crypto/chachapoly/README.rst, samples/crypto/ecdh/README.rst, samples/crypto/ecdsa/README.rst, samples/crypto/hkdf/README.rst, samples/crypto/hmac/README.rst, samples/crypto/persistent_key_usage/README.rst, samples/crypto/rng/README.rst, samples/crypto/rsa/README.rst, samples/crypto/sha256/README.rst
This commit introduces some edits and improvements to the crypto samples doc.
=> doc: Crypto samples doc

applications/asset_tracker_v2/sample.yaml
Add additional testcases to sample.yaml to make CI build for all
supported cloud solutions.
CIA-330
=> applications: asset_tracker_v2: Make CI build for all cloud solutions

applications/pelion_client/README.rst, doc/nrf/ug_app_dev.rst, doc/nrf/ug_pelion.rst
=> doc: Add pelion user guide

doc/nrf/ug_edge_impulse.rst
Added minor doc improvements for Edge Impulse 1.6.0 docs.
=> doc: ei: doc improvements

include/modem/lte_lc.h
Fix API doc issue for link controller
=> doc: Fix API doc issue for link controller

samples/nrf9160/multicell_location/README.rst
=> doc: Minor doc fix in multicell sample

include/net/nrf_cloud_pgps.rst
Documentation improvement for P-GPS library
=> doc: Documentation improvement for P-GPS library

doc/nrf/doc_build.rst, doc/nrf/index.rst
Update doc building instructions by adding
the doc build command for nrfx
=> doc: Update doc building instructions

doc/nrf/releases/release-notes-latest.rst
Added missing release note entries
=> doc: nrf: releases: Added missing release note entries

doc/nrf/links.txt, doc/nrf/shortcuts.txt, doc/nrf/ug_zigbee_architectures.rst, doc/nrf/ug_zigbee_configuring.rst, doc/nrf/ug_zigbee_configuring_libraries.rst, doc/nrf/ug_zigbee_supported_features.rst, doc/nrf/ug_zigbee_tools.rst, include/zigbee/zigbee_app_utils.rst, include/zigbee/zigbee_logger_eprxzcl.rst
Applied minor edits from a doc review with the team.
=> doc: zigbee: minor edits

applications/pelion_client/README.rst, doc/nrf/ug_pelion.rst
Words have different meanings.
=> doc: pelion: Fix incorrect word

doc/nrf/glossary.rst, doc/nrf/links.txt, doc/nrf/ug_thread_tools.rst, doc/nrf/ug_zigbee_supported_features.rst
NCSDK-8842
Checking links, TOC for new pages,
copyright, other inconsistencies
=> doc: Checking doc for release

west.yml
See https://github.com/nrfconnect/sdk-nrfxlib/pull/501
=> manifest: Batch nrfxlib update

modules/tfm/tfm/boards/nrf9160/config.cmake
=> modules: tfm: Enable GCM TF-M tests

west.yml
Update HomeKit revsion
in https://github.com/nrfconnect/sdk-nrf/commit/643d82fe1f91203e331502f8cf4c9171f64b85a9 accidently  (PR https://github.com/nrfconnect/sdk-nrf/pull/4922) updated find-my revision
=> Homekit sync doc 160

subsys/zigbee/osif/zb_nrf_platform.c
The value of the register has to be reset right after booting,
so the external SW reset will not act like a NCP reset request.
Internal SW resets call platform logic, that sets the value to
the new reset source, right before rebooting the MCU.
This will make the external SW reset look like an internal
SYS_REBOOT_COLD reset type in Zigbee NCP application.
=> zigbee: Allow for external SW resets in NCP

subsys/zigbee/osif/zb_nrf_timer.c, tests/subsys/zigbee/osif/timer/mock/zboss_api.h, tests/subsys/zigbee/osif/timer/stubs/zb_types.h, tests/subsys/zigbee/zboss_api/alarm_api/src/main.c
This PR:
- Improves ZBOSS timer accuracy.
- Aligns Zigbee unit tests with new ZBOSS headers.
=> Fix issues found by Zigbee unit tests

doc/nrf/ug_tfm.rst
Adding references to new samples and reviewing one added paragraph.
=> doc: doc updates to TF-M user guide

west.yml
Update to revision fixing memory leak.
=> manifest: Update pelion repo

doc/nrf/releases/release-notes-latest.rst
Added notes for P-GPS in nRF Cloud library, Asset
Tracker, and A-GPS sample.
=> doc: nrf: releases: Added missing P-GPS release notes

west.yml
The doc update aligns the documentation with the
current state.
Signed-off-by: Rafał Kuźnia <rafal.kuznia@nordicsemi.no>
=> manifest: bring nrf_802154 doc update

doc/nrf/known_issues.rst
Add new issues, found between NCS releases.
=> zigbee: Add new known issues for NCS v1.6.0

doc/nrf/releases/release-notes-latest.rst
Modified release notes for P-GPS in nRF Cloud library, Asset
Tracker, and A-GPS sample, based on doc reviewer
comments after previous PR was merged.
=> doc: nrf: releases: Updated P-GPS release notes

doc/nrf/known_issues.rst
Add 1.6.0 label to the existing known issues.
=> doc: update current known issues for 1.6.0 release

subsys/bluetooth/mesh/light_ctl_cli.c
Fix adding status message handlers.
Signed-off-by: Agata Ponitka <agata.ponitka@codecoup.pl>
=> Bluetooth: Mesh: Fix Light CTL Client status handle

doc/nrf/releases/release-notes-latest.rst, samples/nrf9160/modem_shell/README.rst
Signed-off-by: Håvard Vermeer <havard.vermeer@nordicsemi.no>
=> doc: iot release notes additions

doc/nrf/known_issues.rst
=> doc: known_issues: Pelion quick session resume

doc/nrf/releases/release-notes-latest.rst
Top level release notes for SoftDevice Controller part in NCS v1.6.0.
Signed-off-by: Sergey Korotkov <sergey.korotkov@nordicsemi.no>
=> doc: Release notes for SDC

doc/nrf/known_issues.rst
Adds known bugs with tags to previous NCS versions.
Signed-off-by: Kamil Gawor <Kamil.Gawor@nordicsemi.no>
=> doc: update known issues with peripheral_lbs sample bug

doc/nrf/conf.py, doc/nrf/dm_adding_code.rst, doc/nrf/links.txt, doc/nrf/shortcuts.txt, doc/nrfxlib/conf.py, doc/versions.json, west.yml
Update versions for NCS 1.6 release
ref: NCSDK-8843
manifest update for PR 505
=> doc: Update versions for NCS 1.6 release

doc/nrf/gs_modifying.rst, doc/nrf/index.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/release_notes.rst, doc/nrf/releases/release-notes-1.6.0.rst, doc/nrf/releases/release-notes-latest.rst
This 1.6.0 release file includes changes from the other currently open PRs that change the release_notes_latest file.
=> doc: add release notes for 1.6.0

doc/nrf/conf.py, doc/nrf/index.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/release_notes.rst, doc/nrf/releases/release-notes-latest.rst, doc/nrfxlib/conf.py, doc/versions.json
Various post-release changes in doc.
=> doc: update versions in doc after 1.6.0 release

applications/serial_lte_modem/src/slm_at_tcpip.c
Support socket options from nrf_modem 1.2.1
Set() options
.SO_BINDTODEVICE
.SO_REUSEADDR
.SO_SNDTIMEO
.SO_SILENCE_ALL, SO_IP_ECHO_REPLY, SO_IPV6_ECHO_REPLY
.SO_TCP_SRV_SESSTIMEO:
.SO_RAI_LAST, SO_RAI_NO_DATA, SO_RAI_ONE_RESP, SO_RAI_ONGOING
SO_RAI_WAIT_MORE
Get() options
.SO_ERROR (currently pseudo-implementation)
.SO_SNDTIMEO
.SO_SILENCE_ALL, SO_IP_ECHO_REPLY, SO_IPV6_ECHO_REPLY
.SO_TCP_SRV_SESSTIMEO
Request MFWv1.3.0 or later version.
=> applications: serial_lte_modem: Support more Socket options

applications/nrf_desktop/src/modules/hids.c
Change fixes handling protocol mode. According to specification boot host shall write to protocol mode characteristic to trigger boot protocol mode after connection is established.
Jira: NCSDK-10327
=> applications: nrf_desktop: Fix handling protocol mode

subsys/bluetooth/mesh/sensor_types.c, tests/subsys/bluetooth/mesh/sensor_subsys/src/main.c, tests/subsys/bluetooth/mesh/sensor_subsys/testcase.yaml
Unit tests of supported environmental sensors.
=> Bluetooth: Mesh: Environmental sensors test

doc/nrf/links.txt
=> doc: Remove unused link from links.txt

doc/_static/css/common.css
Color of the docset switcher was wrong for nrfx.
=> doc: nrfx: fix switcher color

west.yml
Updated links.txt in nrfxlib by source.
=> manifest: nrfxlib link regrouping

subsys/bluetooth/mesh/sensor_types.c, tests/subsys/bluetooth/mesh/sensor_subsys/src/main.c
Unit tests of supported electrical input sensors.
=> Bluetooth: Mesh: Electrical input sensors test

doc/nrf/links.txt
Updated the links.txt to follow grouping guidelines.
=> doc: links: group links by URL post-1.6.0

samples/nrf9160/gps/src/supl_support.c
The used SUPL server IP address was printed incorrectly before trying to connect to the server.
The implementation tried to use an IPv6 address, although only IPv4 is currently supported.
If connecting to the server failed, the function still returned 0 and caused the SUPL library to try to send data using the socket.
=> samples: nrf9160: gps: fix SUPL IP address and socket connect handling

applications/serial_lte_modem/src/slm_at_tcp_proxy.c
This socket option has been supported by current libmodem.
Also support a FUTURE-FEATURE of testing TLS Server on modem side.
=> applications: serial_lte_modem: Enable SO_REUSEADDR for TCP server

doc/nrf/links.txt, include/zigbee/zigbee_app_utils.rst, include/zigbee/zigbee_logger_eprxzcl.rst
Improved documentation of application utilities.
Moved sections around, added additional info.
=> doc: zigbee: clarify zigbee def handler docs

tests/subsys/bluetooth/mesh/sensor_subsys/src/main.c
This commit adds tests for Device Operating Temperature sensors.
Signed-off-by: Ludvig Samuelsen Jordet <ludvig.jordet@nordicsemi.no>
=> Bluetooth: Mesh: add dev op temp sensor tests

subsys/net/lib/download_client/src/http.c
Previously, any HTTP status code other than 404 or success would only
give an ambiguous "Server did not honor partial content request" or
"Server response is not 200 Success" message.  Improve this to actually
show the status code and message from the server.
Signed-off-by: Justin Brzozoski <justin.brzozoski@signal-fire.com>
=> net: lib: download_client: improve logging on unexpected HTTP response

subsys/bluetooth/mesh/sensor_types.c, tests/subsys/bluetooth/mesh/sensor_subsys/src/main.c
Unit test of encoding\decoding the power supply output sensors
=> Bluetooth: Mesh: Power supply output sensors test

subsys/bluetooth/controller/hci_driver.c
In upcoming library updates, it will be required to configure the
supported features before configuring the required memory.
=> softdevice_controller: Configure supported features before memory

doc/nrf/ug_nrf5340.rst, doc/nrf/ug_nrf9160.rst
Update the Working with nRF53 Series user guide to remove
duplication and clarify instructions.
Ref. NCSDK-9796
=> doc: rewrite Working with nRF53 user guide

doc/nrf/lib/zzhc/zzhc.rst
Edited the file based on input from Heidi-Irene.
=> doc: zzhc: additional edits

doc/nrf/known_issues.rst, lib/bin/lwm2m_carrier/doc/certification.rst, samples/bootloader/README.rst, west.yml
doc fixes related to NCSDK-9787
=> doc: doc fixes related to NCSDK-9787

doc/nrfxlib/nrfxlib.doxyfile.in
=> doc: adding support for radiodriver APIdocs

.github/workflows/docbuild.yml, .github/workflows/docpublish.yml, .github/workflows/docremove.yml, CODEOWNERS, doc/CMakeLists.txt, doc/_extensions/doxyrunner.py, doc/_extensions/external_content.py, doc/_extensions/ncs_cache.py, doc/_scripts/cache_create.py, doc/_scripts/cache_upload.py, doc/cache.yml, doc/kconfig/conf.py, doc/mcuboot/conf.py, doc/nrf/conf.py, doc/nrfx/conf.py, doc/nrfxlib/conf.py, doc/tfm/conf.py, doc/zephyr/conf.py, scripts/requirements-doc.txt
This PR adds initial support for documentation cache.
Depends on #4572
=> doc: initial support for cache

applications/asset_tracker_v2/src/cloud/nrf_cloud_integration.c, applications/asset_tracker_v2/src/modules/cloud_module.c
Address issues suggested by static code analysis
=> applications: asset_tracker_v2: Address issues suggested by static code analysis

west.yml
Bugfix
KRKNWK-10611
- https://github.com/nrfconnect/sdk-homekit/pull/186
=> Homekit sync bugfix v161

.github/workflows/docbuild.yml, .github/workflows/docpublish.yml
The file was not correctly indicated to the doc server.
=> ci: doc: potential fix for doc publish

samples/nrf5340/multiprotocol_rpmsg/sample.yaml
=> samples: multiprotocol_rpmsg: Add build test to sample.yaml

samples/crypto/aes_cbc/sample.yaml, samples/crypto/aes_ccm/sample.yaml, samples/crypto/aes_ctr/sample.yaml, samples/crypto/aes_gcm/sample.yaml, samples/crypto/chachapoly/sample.yaml, samples/crypto/ecdh/sample.yaml, samples/crypto/ecdsa/sample.yaml, samples/crypto/hkdf/sample.yaml, samples/crypto/hmac/sample.yaml, samples/crypto/persistent_key_usage/sample.yaml, samples/crypto/rng/sample.yaml, samples/crypto/rsa/sample.yaml, samples/crypto/sha256/sample.yaml
-This adds the new CI integration_platforms list to
enforce building of the selected platforms
Ref: NCSDK-10526
Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>
=> samples: Add integration_platforms in crypto samples

subsys/net/lib/download_client/src/http.c
When not using TLS, the library made an HTTP range request
when requesting a resource from the server (requesting all the bytes).
This led the server to reply 206 but send the whole resource
in one HTTP message. This used to work, but a recently introduced
change expected the HTTP status in the response to be 200
when not using TLS, thus it started failing with EBADMSG.
This patch lets the library omit the Range header in the request,
(and expect 200) when downloading without TLS,
unless downloading from an offset.
@jbrzozoski would you like to have a look?
=> net: lib: download_client: fix expected HTTP status

subsys/bluetooth/mesh/light_ctrl_srv.c, tests/subsys/bluetooth/mesh/light_ctrl/CMakeLists.txt, tests/subsys/bluetooth/mesh/light_ctrl/prj.conf, tests/subsys/bluetooth/mesh/light_ctrl/src/main.c, tests/subsys/bluetooth/mesh/light_ctrl/testcase.yaml
Check that if the "Light On or Off" event is received in irrelevant
state machine states, the FSM implementation should not behave
unexpectedly.
=> Bluetooth: Mesh: Check invalid event combinations.

applications/machine_learning/configuration/thingy53_nrf5340_cpuapp/pm_static_ZDebug.yml, applications/machine_learning/configuration/thingy53_nrf5340_cpuapp/pm_static_ZRelease.yml
Increased settings storage size from 32k to 64k and aligned
rest of the partitions to it.
=> applications: machine_learning: Changed Thingy53 partition sizes.

applications/serial_lte_modem/doc/slm_extending.rst
Correct mistakes on "extending the application" page.
=> applications: serial_lte_modem: Doc correct extending page

applications/machine_learning/src/modules/ei_data_forwarder_bt_nus.c
Change introduces tracking NUS subscriptions in Edge Impulse data forwarder over Bluetooth NUS.
Jira: NCSDK-8850
=> applications: machine_learning: Track NUS subscriptions

include/profiler.h, samples/profiler/src/main.c, scripts/profiler/events.py, scripts/profiler/rtt_nordic_profiler_host.py, subsys/profiler/profiler_nordic.c
=> profiler: Introduce profiling strings

doc/nrf/doc_styleguide.rst, doc/nrf/templates/cheat_sheet.rst
NCSDK-9708
Improve readability, remove extraneous examples
Some matters were moved over to the cheat sheet.
Signed-off-by: Wille Backman <wille.backman@nordicsemi.no>
=> doc: updating style guide

doc/nrf/glossary.rst
Terms taken from the SDS glossary
Useful for MPSL and SDC documentation
Signed-off-by: Timothy Keys <timothy.keys@nordicsemi.no>
=> doc: Add new glossary terms

applications/nrf_desktop/configuration/common/hid_keyboard_leds.h, applications/nrf_desktop/configuration/common/hid_report_desc.h, applications/nrf_desktop/configuration/nrf52810dmouse_nrf52810/hid_keyboard_leds_def.h, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/dts.overlay, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/hid_keyboard_leds_def.h, applications/nrf_desktop/configuration/nrf52840gmouse_nrf52840/hid_keyboard_leds_def.h, applications/nrf_desktop/configuration/nrf52dmouse_nrf52832/hid_keyboard_leds_def.h, applications/nrf_desktop/configuration/nrf52kbd_nrf52832/hid_keyboard_leds_def.h, applications/nrf_desktop/src/events/hid_event.c, applications/nrf_desktop/src/events/hid_event.h, applications/nrf_desktop/src/modules/Kconfig.config_channel, applications/nrf_desktop/src/modules/ble_qos.c, applications/nrf_desktop/src/modules/hid_forward.c, applications/nrf_desktop/src/modules/hid_state.c, applications/nrf_desktop/src/modules/hids.c, applications/nrf_desktop/src/modules/usb_state.c
Change introduces handling HID output report related to keyboard LEDs.
Jira: NCSDK-9909
=> applications: nrf_desktop: Add HID output report for keyboard LEDS

doc/nrf/releases/release-notes-latest.rst, doc/nrf/shortcuts.txt, doc/nrf/ug_zigbee_configuring.rst, doc/nrf/ug_zigbee_configuring_libraries.rst, include/zigbee/zigbee_zcl_scenes.h, include/zigbee/zigbee_zcl_scenes.rst
Added documentation for the new old Zigbee library.
Related to #5145
=> doc: add documentation for Zigbee scene library

scripts/partition_manager/partition_manager.rst
ref: NCSDK-9494
Add this note to reduce confusion around partition management.
Signed-off-by: Deidre Casey <deidre.casey@nordicsemi.no>
=> doc: Add note that DTS partitions are ignored when using PM

west.yml
=> manifest: MPSL with public Coexistence API

subsys/bluetooth/gatt_dm.c
Fix cases where the device disconnection is between memory allocation
and characteristic discovery.
Characteristics data was not copied to allocated memory.
So uuid pointer was incorrect. It caused a memory fault.
Ref: NCSDK-9811
Signed-off-by: Marcin Jeliński <marcin.jelinski@nordicsemi.no>
=> bluetooth: gatt_dm: Handle invalid characteristic discovery.

west.yml
Signed-off-by: Robert Gałat <robert.galat@nordicsemi.no>
=> Manifest: update homekit manifest

doc/nrf/conf.py, doc/nrf/dm_adding_code.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/release_notes.rst, doc/nrf/releases/release-notes-1.6.1.rst, doc/nrf/releases/release-notes-latest.rst, doc/nrf/shortcuts.txt, doc/nrfxlib/conf.py, doc/versions.json, west.yml
Update documentation for 1.6.1 release
=> doc: Update documentation and versions for 1.6.1 release

applications/asset_tracker_v2/src/events/app_module_event.c, applications/asset_tracker_v2/src/events/cloud_module_event.c, applications/asset_tracker_v2/src/events/data_module_event.c, applications/asset_tracker_v2/src/events/gps_module_event.c, applications/asset_tracker_v2/src/events/modem_module_event.c, applications/asset_tracker_v2/src/events/sensor_module_event.c, applications/asset_tracker_v2/src/events/ui_module_event.c, applications/asset_tracker_v2/src/events/util_module_event.c, applications/machine_learning/src/events/ml_result_event.c, applications/nrf_desktop/src/events/battery_event.c, applications/nrf_desktop/src/events/cpu_load_event.c, applications/nrf_desktop/src/events/hid_event.c, applications/nrf_desktop/src/events/motion_event.c, applications/nrf_desktop/src/events/passkey_event.c, applications/nrf_desktop/src/events/selector_event.c, applications/pelion_client/src/events/net_event.c, applications/pelion_client/src/events/pelion_event.c, applications/pelion_client/src/events/power_manager_event.c, include/event_manager.rst, include/profiler.h, include/profiler.rst, samples/event_manager/src/events/config_event.c, samples/event_manager/src/events/measurement_event.c, samples/profiler/src/main.c, scripts/profiler/rtt_nordic_profiler_host.py, subsys/caf/events/ble_common_event.c, subsys/caf/events/button_event.c, subsys/caf/events/click_event.c, subsys/profiler/profiler_nordic.c, tests/subsys/event_manager/src/events/data_event.c
subsys: profiler: Optimize numeric data encoding
Introduces 8-bit and 16-bit data encoding. Additionally files that uses profiler are corrected so that they follow new profiler API.
Jira: NCSDK-10033
=> Profiler: Optimize numeric data encoding

west.yml
Depends on: 
Signed-off-by: Piotr Jasiński <piotr.jasinski@nordicsemi.no>
=> manifest: update homekit revision 

applications/serial_lte_modem/src/main.c
Request external XTAL before UART is powered on and release
the XTAL after it's powered off.
=> application: serial_lte_modem: Handle external XTAL

scripts/hid_configurator/README.rst
add to documentation information what packeges have to be installed to
use led steam
Jira: NCSDK-10547
=> docs: applications: add missing packages to documentation

applications/nrf_desktop/src/modules/hid_state.c
Moved updated_needed from report_data to report_state,
added sending empty report after connecting to usb while
being connected to bluetooth
Jira: NCSIDB-463
=> application nrf_desktop: Wrong button state

samples/nrf9160/modem_shell/src/gnss/gnss_supl_support.c
Refactored the DNS query and socket usage. Added support for IPv6.
Signed-off-by: Tommi Kangas <tommi.kangas@nordicsemi.no>
=> samples: nrf9160: modem_shell: refactor SUPL support implementation

doc/nrf/known_issues.rst
Update List of known issues in Thread section for NCS version
1.6.1 and 1.6.0.
Signed-off-by: Przemyslaw Bida <przemyslaw.bida@nordicsemi.no>
=> doc: Update list of known issues of Thread.

samples/nrf9160/modem_shell/src/link/link.c, samples/nrf9160/modem_shell/src/link/link.h, samples/nrf9160/modem_shell/src/link/link_api.c, samples/nrf9160/modem_shell/src/link/link_api.h, samples/nrf9160/modem_shell/src/link/link_shell.c, samples/nrf9160/modem_shell/src/ping/icmp_ping.c, samples/nrf9160/modem_shell/src/ping/icmp_ping.h, samples/nrf9160/modem_shell/src/ping/icmp_ping_shell.c, samples/nrf9160/modem_shell/src/sock/sock.c, samples/nrf9160/modem_shell/src/sock/sock.h, samples/nrf9160/modem_shell/src/sock/sock_shell.c
- Support for RAI for ping
- Move global RAI enable from 'sock' to 'link'
=> Mosh RAI changes

doc/nrf/releases/release-notes-latest.rst, include/modem/modem_info.h, include/net/nrf_cloud.h, include/net/nrf_cloud.rst, lib/modem_info/modem_info.c, lib/modem_info/modem_info_json.c, subsys/net/lib/nrf_cloud/include/nrf_cloud_codec.h, subsys/net/lib/nrf_cloud/src/nrf_cloud.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_codec.c
nRF Cloud expects a certain format for the "device" section
in the shadow.  Provide a function so the user can easily
add the device status.
Ref: CIA-386
Also added some defines and used _CS cJSON functions where
appropriate.
Ref: CIA-378
=> nrf_cloud: add function to update device status

samples/bluetooth/central_hids/src/main.c
Change fixes wrong log displayed during protocol mode change.
=> samples: central_hids: Fix wrong protocol mode log

samples/nrf9160/gps/src/main.c
It was found that a race condition was occuring with the
SUPL work queue. The queue is called by the gnss_event_handler
function, which can take place prior to the queue's
initialization. Therefor the queue's init has been moved
to preceed the gnss_event_handler function.
Signed-off-by: Richard McCrae <richard.mccrae@nordicsemi.no>
=> samples: nrf9160: gps: Move SUPL work queue init

samples/matter/weather_station/src/app_task.cpp, samples/matter/weather_station/src/app_task.h
Modified fetching data from sensors in weather station sample
to be triggered by the timer instead of loop reads.
=> samples: matter: Optimized fetching data from device sensors

doc/nrf/links.txt, west.yml
sdk-connectedhomeip upmerge containing documentation changes only
=> manifest: Updated sdk-connectedhomeip version

scripts/get_pulls_in_range.py
These were omitted in previous commits. I am the sole author of this
script.
=> scripts: get_pulls_in_range: add copyright/license

applications/serial_lte_modem/src/slm_at_tcp_proxy.c
Do not unload credential twice with same <sec_tag>, or crash.
Fix a bug in parsing incoming connection's IPv6 address.
Easier way to terminate connection when server thread quits.
=> application: serial_lte_modem: Bug-fix for native TLS

doc/nrf/links.txt, doc/nrf/releases/release-notes-latest.rst, doc/nrf/ug_matter.rst, doc/nrf/ug_matter_configuring.rst, doc/nrf/ug_matter_tools.rst, doc/nrf/ug_thread_tools.rst
Added a page that documents Matter tools.
=> doc: add Matter tools page

lib/date_time/date_time.c
Add a guard that prevents the library from performing NTP if the
device is not connected to LTE.
=> lib: date_time: Check LTE registration status before performing NTP

applications/serial_lte_modem/doc/ICMP_AT_commands.rst, applications/serial_lte_modem/src/slm_at_icmp.c, applications/serial_lte_modem/src/slm_at_socket.c, applications/serial_lte_modem/src/slm_at_tcp_proxy.c, applications/serial_lte_modem/src/slm_at_udp_proxy.c, applications/serial_lte_modem/src/slm_util.c, applications/serial_lte_modem/src/slm_util.h
Allow to specify which PDN to use in Ping test.
Prepared for NIDD test in the future.
=> application: serial_lte_modem: Add secondary PDN support to #XPING

CODEOWNERS, tests/subsys/profiler/CMakeLists.txt, tests/subsys/profiler/README.txt, tests/subsys/profiler/prj.conf, tests/subsys/profiler/src/main.c, tests/subsys/profiler/testcase.yaml
Adds unit test of the Profiler.
Jira: NCSDK-10561
=> Profiler: Unit test

doc/nrf/releases/release-notes-changelog.rst
Update of Zigbee release notes for NCS 1.7.0
Signed-off-by: Maciej Pietras <maciej.pietras@nordicsemi.no>
=> doc: Update release-notes-changelog.rst

doc/nrf/releases/release-notes-changelog.rst
Introdues the changes related to the 802.15.4 subsystem.
Signed-off-by: Czeslaw Makarski <czeslaw.makarski@nordicsemi.no>
=> doc: release-note-changelog: 802.15.4-related changes

doc/nrf/known_issues.rst, doc/nrf/releases/release-notes-changelog.rst
Release notes and known issues for Bluetooth mesh in NCS v1.7.0.
=> doc: Bluetooth: Mesh: Release notes and known issues for v1.7.0.

doc/nrf/releases/release-notes-changelog.rst
Update release notes with Thread additions.
=> doc: add Thread release notes

west.yml
General nrf-802154 radio driver update.
Signed-off-by: Rafał Kuźnia <rafal.kuznia@nordicsemi.no>
=> manifest: update nrf-802154 component

doc/_extensions/external_content.py, scripts/get_pulls_in_range.py
Documentation patches for zephyr changes in the devicetree, kernel, and testing areas.
Also a few miscellaneous changes to other areas that were mis-characterized as 'testing' due to an issue with the script that assigns areas to pull requests, and a fix to that script.
=> Post upmerge 2021 07 26: minor scripts fixes

doc/nrf/known_issues.rst
Reverted tag added in PR#5413 before known issue review was created.
=> doc: known issues: revert added tag

applications/matter_weather_station/README.rst, doc/CMakeLists.txt, doc/nrf/conf.py, doc/nrf/links.txt, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/ug_matter_architecture.rst, doc/nrf/ug_matter_configuring.rst, doc/nrf/ug_matter_tools.rst, samples/matter/light_bulb/README.rst, samples/matter/lock/README.rst
Replaced GitHub links with cross-links to Matter docset.
=> doc: matter: update links to docset

west.yml
Includes updates:
- Fixes TX power API not working on central/peripheral-only builds
Signed-off-by: Jonathan Rico <jonathan.rico@nordicsemi.no>
=> manifest: Update Softdevice Controller & MPSL revision

doc/nrf/ug_bootloader_config.rst
=> doc: add missing toc

samples/esb/README.rst
This commit adds support for nRF21540 Front-End Module to the ESB sample doc.
Ref NCSDK-10897
=> doc: add support for nRF21540 FEM to ESB sample doc

west.yml
[KRKNWK-11134]
- https://github.com/nrfconnect/sdk-homekit/pull/222
- https://github.com/nrfconnect/sdk-homekit/pull/229
=> west: update homekit manifest

doc/nrf/ug_thread_tools.rst
Starting from NCS v1.7 the OpenThread Bourder Router is supported
by NCS Thread radio co-processor sample and the documentation needs
to be adjusted.
Additionaly the OpenThread Bourder Router docker image for nRF Connect
SDK is provided which has been tested with corresponding version of
the NCS Thread radio co-processor.
=> [doc] update Thread Bourder Router documentation

doc/nrf/releases/release-notes-changelog.rst
Change includes updates for: Profiler, Common Application Framework (CAF), Pelion, Edge Impulse and nRF Desktop.
Jira: NCSDK-11010
=> doc: Update release notes changelog

doc/nrf/libraries/networking/multicell_location.rst, doc/nrf/links.txt, samples/nrf9160/multicell_location/README.rst
Add a note about reprovisioning certificates in Multicell
sample and library when using the library with nRF Cloud.
=> doc: Add a note about reprovisioning certificates

include/modem/lte_lc.h, include/net/nrf_cloud_cell_pos.h, subsys/net/lib/nrf_cloud/src/nrf_cloud_codec.c
Add defines so parameters can be omitted from cell_pos requests.
=> net: lib: nrf_cloud: improve cell_pos optional param handling

applications/serial_lte_modem/doc/Generic_AT_commands.rst, applications/serial_lte_modem/doc/slm_description.rst
Add description of the CONFIG items for GNSS services
=> application: serial_lte_modem: Doc GNSS service configs

doc/nrf/ug_thread_supported_features.rst
Add DUA short description in thread ug.
Signed-off-by: Przemyslaw Bida <przemyslaw.bida@nordicsemi.no>
=> doc: Update Thread 1.2 supportted features with DUA overview.

west.yml
This PR updates sdk-nrf-802154 and nrfxlib revisions to bring in
the latest changes in the nrf_802154 component.
=> manifest: Update sdk-nrf-802154 and nrfxlib revisions

doc/nrf/releases/release-notes-changelog.rst, samples/bluetooth/peripheral_uart/CMakeLists.txt, samples/bluetooth/peripheral_uart/Kconfig, samples/bluetooth/peripheral_uart/README.rst, samples/bluetooth/peripheral_uart/prj_cdc.conf, samples/bluetooth/peripheral_uart/sample.yaml, samples/bluetooth/peripheral_uart/src/main.c, samples/bluetooth/peripheral_uart/src/uart_async_adapter.c, samples/bluetooth/peripheral_uart/src/uart_async_adapter.h
Experimental implementation of UART ASYNC adapter.
The idea is that ASYNC adapter comes in between application that uses ASYNC UART API and the driver that provides only INTERRUPT API.
=> Ncsdk 10744 nus sample irq uart

applications/matter_weather_station/src/app_task.cpp
Currently, the BME68x sensor driver works in the forced
mode, meaning that a new measurement is started on each
sensor fetch operation. The measurement cycle consists
of reading temperature, pressure and humidity, followed
by gas detection which includes turning on the gas sensor
heater for a configured period of time.
It appears that polling the sensor too frequently causes
the gas sensor heater to impact subsequent temperature
measurement. Since it is impossible to disable the gas
detection via Kconfig, workaround the issue by decreasing
the sensor poll frequency from 1 per 250ms to 1 per 3s.
By the way, simplify the code by removing an unneeded
variable.
=> applications: matter: fix temperature in weather station

doc/nrf/ug_thread_tools.rst
Fix wrong build command, typo, language improvement.
Signed-off-by: Lukasz Maciejonczyk <lukasz.maciejonczyk@nordicsemi.no>
=> doc: openthread: Thread tools

doc/CMakeLists.txt, doc/_scripts/merge_search_indexes.py
This PR adds cross-search functionality by merging Sphinx search indexes. Thanks @doki-nordic for the idea and proof of concept script.
Alternative to https://github.com/nrfconnect/sdk-nrf/pull/5357
=> doc: add cross-search functionality

doc/nrf/libraries/caf/caf_overview.rst, include/caf/events/force_power_down_event.h, include/caf/events/keep_alive_event.h, include/caf/events/power_manager_event.h
=> doc improvement: caf: Add remaining doc for power manager events

west.yml
west.yml: Update zephyr to bring support for multi-image update
The commit brings two fromlist commits from Zephyr that:
- update mcumgr revision to support multi-image;
- add required Kconfig options to Zephyr.
Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>
=> west.yml: Update zephyr to bring support for multi-image update 

doc/nrf/libraries/networking/nrf_cloud_agps.rst, samples/nrf9160/agps/README.rst
=> doc improvement: Minor edits to the A-GPS docs

samples/nrf9160/udp/README.rst
Minor edits to the UDP sample documentation.
=> doc improvement: Fixes to the UDP sample doc

doc/nrf/libraries/bluetooth_services/mesh/scene_srv.rst, include/bluetooth/mesh/gen_plvl_srv.h, include/bluetooth/mesh/gen_ponoff_srv.h, include/bluetooth/mesh/light_ctl_srv.h, include/bluetooth/mesh/light_hsl_srv.h, include/bluetooth/mesh/light_xyl_srv.h, include/bluetooth/mesh/lightness_srv.h, include/bluetooth/mesh/scheduler_srv.h, include/bluetooth/mesh/time_srv.h, subsys/bluetooth/mesh/gen_plvl_srv.c, subsys/bluetooth/mesh/gen_ponoff_srv.c, subsys/bluetooth/mesh/gen_prop_srv.c, subsys/bluetooth/mesh/light_ctl_srv.c, subsys/bluetooth/mesh/light_ctrl_srv.c, subsys/bluetooth/mesh/light_hsl_srv.c, subsys/bluetooth/mesh/light_hue_srv.c, subsys/bluetooth/mesh/light_sat_srv.c, subsys/bluetooth/mesh/light_temp_srv.c, subsys/bluetooth/mesh/light_xyl_srv.c, subsys/bluetooth/mesh/lightness_srv.c, subsys/bluetooth/mesh/scene_srv.c, subsys/bluetooth/mesh/scheduler_srv.c, subsys/bluetooth/mesh/time_srv.c, tests/bluetooth/tester/src/model_handler.c
With the updated Model Extension feature we can represent true
relationships between models.
Signed-off-by: Michał Narajowski <michal.narajowski@codecoup.pl>
=> Bluetooth: Mesh: Use updated Model Extension API

west.yml
Update west.yml to contain the necessary tags.
=> west.yml: tagged revisions for v1.7.0-rc2

doc/nrf/app_power_opt.rst, doc/nrf/doc_build.rst, doc/nrf/doc_styleguide.rst, doc/nrf/getting_started.rst, doc/nrf/gs_assistant.rst, doc/nrf/gs_installing.rst, doc/nrf/gs_programming.rst, doc/nrf/gs_testing.rst, doc/nrf/ug_bootloader_adding.rst, doc/nrf/ug_bootloader_external_flash.rst, doc/nrf/ug_radio_fem.rst, doc/nrf/ug_thread_supported_features.rst, doc/nrf/ug_thread_tools.rst, samples/nrf9160/modem_shell/README.rst, samples/nrf9160/mqtt_simple/README.rst, samples/nrf9160/udp/README.rst, samples/spm/README.rst
Added minor edits to several pages for NCS 1.7.0.
NCSDK-11020.
----
The following tasks were created for more global doc improvements:
=> doc improvement: misc doc edits for 1.7.0

tests/subsys/net/lib/azure_iot_hub/src/main.c
Fix potential memory leak reported by coverity.
=> tests: azure_iot_hub: Fix potential memory leak

doc/nrf/gs_installing.rst, doc/nrf/index.rst, doc/nrf/ug_radio_fem.rst
Added edits suggested at the doc review meeting.
=> doc improvement: fixes after doc review meeting

applications/pelion_client/README.rst, doc/nrf/links.txt, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/ug_pelion.rst
=> doc improvement: Add link to Pelion development tools

doc/nrf/links.txt, doc/nrf/ug_nrf91_features.rst, west.yml
Adding in some general documentation for the GPS
in nrf9160 features page.
Replaces: nrfconnect#5394
Signed-off-by: Martin Lesund <martin.lesund@nordicsemi.no>
=> doc improvement: Adding in GPS doc for nrf9160

doc/nrf/gs_installing.rst, doc/nrf/gs_recommended_versions.rst
Minor fixes in linux getting started instructions
=> doc: Minor fixes in linux getting started instructions

applications/asset_tracker_v2/src/modules/debug_module.c
Send Memfault data on `MODEM_EVT_LTE_CONNECTED` in stead of
`CLOUD_EVT_CONNECTED`. This is to not be dependent on a connection
to cloud for potentially critical Memfault data such as coredumps.
CIA-411
=> applications: asset_tracker_v2: Send Memfault data on `MODEM_EVT_LTE_CONNECTED`

applications/pelion_client/sample.yaml
Make CI check if pelion client app builds.
=> application: pelion_client: Add pelion client to CI targets

doc/nrf/links.txt, samples/nrf9160/lwm2m_client/README.rst
Signed-off-by: Veijo Pesonen <veijo.pesonen@nordicsemi.no>
=> samples: nrf9160: lwm2m_client: adapt README to new Leshan web UI

west.yml
Manifest update for misc doc edits.
=> doc: manifest: homekit doc improvements for 1.7.0

subsys/partition_manager/flash_map_partition_manager.c
This PR fixes flash map offset for
partition manager.
=> partition_manager: Fix flash map offset

applications/machine_learning/README.rst, applications/matter_weather_station/README.rst, doc/nrf/gs_programming.rst, doc/nrf/shortcuts.txt, doc/nrf/ug_thingy53.rst, samples/bluetooth/mesh/light/README.rst, samples/bluetooth/mesh/light_switch/README.rst, samples/bluetooth/peripheral_lbs/README.rst, samples/bluetooth/peripheral_uart/README.rst
Change introduces user guide improvements.
=> doc: ug_thingy53: Improve user guide

doc/nrf/libraries/zigbee/shell.rst, doc/nrf/links.txt, doc/nrf/ug_zigbee.rst, doc/nrf/ug_zigbee_adding_clusters.rst
Added new guide for adding ZCL clusters to Zigbee app.
KRKNWK-11075.
=> doc: zigbee guide for adding ZCL clusters

doc/nrfxlib/nrfxlib.doxyfile.in
This PR is required for application of corrections to doxygen documentation of sdk-nrfxlib/nrf_802154
=> doc: nrf_802154: radio driver API doxygen fixes

.github/labeler.yml
update thread paths
Signed-off-by: Tomasz Kobylarz <tomasz.kobylarz@nordicsemi.no>
=> labeler: update thread paths

doc/nrf/known_issues.rst, doc/nrf/links.txt
Added 1.7.0 label to the existing known issues.
Based on #4840 .
----
For known issues discovered during RC1 testing or before release, *open a PR that points to this branch*.
----
=> doc improvement: update current known issues for 1.7.0 release

samples/nrf9160/http_update/application_update/sample.yaml, samples/nrf9160/http_update/full_modem_update/sample.yaml, samples/nrf9160/http_update/modem_delta_update/sample.yaml
Add sample.yaml for the application_update, full_modem_update and
modem_delta_update samples.
Ref: NCSDK-11283
Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>
=> samples: nrf9160: http_update: Add sample.yaml

subsys/bluetooth/controller/hci_driver.c
For now use the default values.
=> bluetooth: softdevice_controller: Use adv and scan buffer configs

applications/nrf_desktop/src/modules/hid_forward.c
Earlier, when using boot protocol, when peripheral disconnected,
we didn't forward empty HID boot reports.
That could result in pressed keys not being properly released.
Now it is fixed.
Jira: NCSDK-10668
=> applications: nrf_desktop: Forward empty HID boot reports on peripheral disconnection

lib/nrf_modem_lib/nrf91_sockets.c
Update error table for getaddrinfo errors.
cc @Rallare
=> lib: nrf_modem_lib: update offloading of getaddrinfo errors

applications/machine_learning/README.rst, applications/machine_learning/configuration/nrf52840dk_nrf52840/app_ZDebugNUS.conf, applications/machine_learning/configuration/thingy53_nrf5340_cpuapp/app_ZDebugRTT.conf, applications/nrf_desktop/README.rst, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/app_ZDebugMCUBootQSPI.conf, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/app_ZDebugMCUBootSMP.conf, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/app_ZDebug_dongle.conf, applications/nrf_desktop/configuration/nrf52840dk_nrf52840/app_ZDebug_keyboard.conf, applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/app_ZDebug3BLEconn.conf, applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/app_ZDebug4LLPMconn.conf, applications/nrf_desktop/configuration/nrf52840dongle_nrf52840/app_ZRelease4LLPMconn.conf, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/shortcuts.txt
This commit adds documentation for specialized configurations.
=> doc: Add documentation for special configurations

lib/nrf_modem_lib/nrf_modem_os.c
trace_proxy_irq_handler is using an IRQ that other users also want to
use. For instance the test zephyr/tests/kernel/gen_isr_table/ wants to
use this IRQ.
I don't see why we need to enable the IRQ when trace is disabled. So
this patch disables it when NRF_MODEM_LIB_TRACE_ENABLED=n.
NCSDK-11344
=> modem: Disable trace_proxy_irq_handler when trace is disabled

subsys/caf/modules/power_manager.c
Earlier, power down counter work has been rescheduled
on every keep alive event.
Now, on keep alive event, keep alive flag is set.
Every 1 second, flag is checked and if it's set,
flag is cleared and power down counter is reset.
Jira: NCSDK-10797
Signed-off-by: Aleksander Strzebonski <aleksander.strzebonski@nordicsemi.no>
=> caf: Power manager sets flag on keep alive

doc/nrf/includes/sample_board_rows.txt
=> Add thingy53_nrf5340_cpuapp_ns in doc files

doc/nrf/gs_installing.rst, doc/nrf/introduction.rst
Added more info about the west tool.
Moved a couple of lines from gs_installing.rst.
NCSDK-10915
=> doc: adding more west info to introduction.rst

lib/date_time/Kconfig, lib/date_time/date_time.c
Update to use new AT APIs from libmodem.
=> lib: date_time: update to use new AT APIs

subsys/bluetooth/mesh/scene_srv.c
When receiving a scene set message where the target scene matches the
current scene, the transition should just complete immediately.
=> Bluetooth: Mesh: Immediately complete scene transitions to current scene

lib/lte_link_control/lte_lc.c
The use-case for this feature is when the modem had LTE functionality disabled through AT+CFUN=20, but the modem is still operating (because of GPS). This prevents the lte_lc_connect() to fail because it tries to initially set AT%XSYSTEMMODE before setting AT+CFUN=1.
The fallback retry scheme will still work because the modem will be set offline before retrying it.
Signed-off-by: Luis Ubieda <luisf@croxel.com>
=> Added capability on LTE Link Control to connect hrough lte_lc_connect() while modem is running

samples/nrf9160/lwm2m_client/README.rst
Documentation fixes for LwM2M client sample
Include changes made in 
https://github.com/nrfconnect/sdk-nrf/pull/5589/ 
=> doc: Documentation fixes for LwM2M client sample

.github/labeler.yml
Added lwm2m label to labeler.yml
Signed-off-by: Eoin McMahon <eoin.mcmahon@nordicsemi.no>
=> Updated labeler.yml

subsys/caf/modules/power_manager.c, subsys/profiler/profiler_nordic.c
Change fixes issue related to profiler termination
Jira: NCSDK-11627
=> profiler: Fix profiler termination

doc/nrf/releases/release-notes-changelog.rst, include/fprotect.h, lib/fprotect/Kconfig, lib/fprotect/fprotect_acl.c, lib/hw_unique_key/hw_unique_key_acl.c, tests/drivers/fprotect/negative/src/main.c, tests/lib/hw_unique_key_tfm/src/main.c
~Based on https://github.com/nrfconnect/sdk-nrf/pull/4910~
=> Improve/fix hw_unique_key_is_written for ACL

lib/agps/agps.c
=> lib: agps: Add missing `log_strdup()`

lib/modem_attest_token/Kconfig, lib/modem_attest_token/modem_attest_token.c
Update to use new AT APIs in libmodem.
=> lib: modem_attest_token: update to use new AT APIs

doc/nrf/known_issues.rst
Ref. DRGN-15903, NCSIDB-332, DRGN-16317.
Signed-off-by: Thomas Stenersen <thomas.stenersen@nordicsemi.no>
=> doc: Add known issue texts for BT_CTLR_TX_PWR and discarded Ext. Adv. Reports

west.yml
Use nrfxlib revision with fixes fot ZBOSS addons.
=> maniifest: Pull fixes in ZBOSS addons docs

doc/nrf/known_issues.rst
ncs 1.7.0 nrf5340 issue into known_issues.rst
=> doc: Update known issues for Softdevice Controller

doc/nrf/releases/release-notes-changelog.rst, include/net/nrf_cloud_rest.h, subsys/net/lib/nrf_cloud/src/nrf_cloud_rest.c
Remove GPS driver references and replace with newer
GNSS interface.
=> net: lib: nrf_cloud: switch REST AGPS to GNSS interface

applications/serial_lte_modem/src/slm_at_tcp_proxy.c
It is found that, if there is incoming connection, stopping native TLS
server would cause crash due to undefined behavior of polling when the
listening socket is closed in external thread (instead of polling one)
Reworked the TCP/TLS server stop logic:
- Close listening socket only when there is no active incoming socket
- Use flag to notify server thread that stop is requested and pending
- Server thread abort poll event handling if stop is pending
- Server thread gracefully terminate before sending AT response
=> application: serial_lte_modem: BUG-FIX native TLS server stop crash

scripts/requirements-extra.txt
Fix pygit2 version in requirements due to broken release.
Signed-off-by: Maciej Perkowski <Maciej.Perkowski@nordicsemi.no>
=> requirements: Fix pygit2 version

lib/modem_jwt/Kconfig, lib/modem_jwt/modem_jwt.c, tests/lib/modem_jwt/CMakeLists.txt, tests/lib/modem_jwt/src/jwt_test.c
Update library to use new APIs from libmodem.
=> lib: modem_jwt: update to use new AT APIs

doc/nrf/glossary.rst, doc/nrf/releases/release-notes-changelog.rst
Updated glossary with terms related to Matter.
=> doc: add new terms to glossary

doc/nrf/known_issues.rst, west.yml
-Adds nrf_cc3xx_platform/nrf_cc3xx_mbedcrypto v0.9.12
ref: NCSDK-11786
=> manifest: Update to PR 568

doc/nrf/releases/release-notes-changelog.rst, doc/nrf/templates/library_template_README.rst
Added library doc template.
Related to JIRA NCSDK 1103.
=> doc: added library doc template

subsys/bluetooth/mesh/light_ctrl_srv.c
This fixes two lightness representation issues in the LC Server:
1. Property set calls are not converted to the native representation,
even though they're always being set in the ACTUAL representation in the
messages.
2. The regulator takes light values from cfg, and compares them to the
regulator output without first converting them to linear space, which
the regulator operates in.
This fixes both issues.
=> Bluetooth: Mesh: Fix Light LC Server value representation

doc/nrf/known_issues.rst
Insert a link to limitations page into softdevice controller.
Signed-off-by: Ryan Chu <ryan.chu@nordicsemi.no>
=> doc: Link to limitations documentation for Softdevice Controller

applications/asset_tracker_v2/doc/asset_tracker_v2_description.rst, applications/asset_tracker_v2/src/cloud/azure_iot_hub_integration.c, applications/asset_tracker_v2/src/cloud/cloud_codec/azure_iot_hub/azure_iot_hub_codec.c, applications/asset_tracker_v2/src/modules/cloud_module.c, doc/nrf/releases/release-notes-changelog.rst, subsys/net/lib/azure_iot_hub/src/azure_iot_hub.c
Add support for A-GPS and P-GPS in Azure IoT Hub integration.
**This PR supersedes https://github.com/nrfconnect/sdk-nrf/pull/5628**
=> application: asset_tracker_v2: Add A/P-GPS support for Azure integration

doc/_static/js/ga-tracker.js, doc/_utils/utils.py
The ID has to be adjusted to obtain correct analytics.
=> doc: adjust Google Analytics id

doc/nrf/known_issues.rst
Add issue with gaming mouse increased current to known issues.
I have a question where it should be placed in known_issues.rst file? @greg-fer?
Jira: NCSDK-12020
Signed-off-by: Jan Zyczkowski jan.zyczkowski@nordicsemi.no
=> doc: added known issue for increased current

doc/nrf/libraries/zigbee/shell.rst, doc/nrf/links.txt, doc/nrf/ug_zigbee_adding_clusters.rst, doc/nrf/ug_zigbee_memory.rst, samples/zigbee/light_bulb/README.rst, samples/zigbee/light_switch/README.rst, samples/zigbee/ncp/README.rst
Added edits for several minor issues in Zigbee docs.
NCSDK-11864.
=> doc: zigbee: fix minor issues

doc/nrf/releases/release-notes-changelog.rst, subsys/net/lib/aws_iot/src/aws_iot.c, subsys/net/lib/azure_iot_hub/src/azure_iot_hub.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c
Address Jira CIA-439 and CIA-440 for nRF Cloud, AWS IoT, and Azure.
=> MQTT ping error handling improvements

subsys/profiler/profiler_nordic.c
Ignore unused error value.
Jira: NCSDK-11353
=> profiler: Fix coverity issue

doc/nrf/drivers/pmw3360.rst, doc/nrf/releases/release-notes-changelog.rst, drivers/sensor/pmw3360/pmw3360.c, include/sensor/pmw3360.h
Change adds documentation related to pmw3360 sensor.
Jira: NCSDK-11558
=> pmw3360 sensor documentation

tests/subsys/event_manager/testcase.yaml
Added qemu_cortex_m3 to integration_platforms.
=> tests: event_manager: Add qemu_cortex_m3 to integration_platforms

doc/nrf/ug_bootloader_external_flash.rst, scripts/partition_manager/partition_manager.rst
Add links to an example file, and link between pages.
Ref: NCSDK-11484
=> doc: add more details on external flash

applications/serial_lte_modem/src/gnss/slm_at_gnss.c, doc/nrf/releases/release-notes-changelog.rst, include/net/nrf_cloud_cell_pos.h, subsys/net/lib/nrf_cloud/include/nrf_cloud_fsm.h, subsys/net/lib/nrf_cloud/src/nrf_cloud_cell_pos.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_fsm.c
add an optional callback to receive the cellular positioning data
response from nRF Cloud.
CIA-452
=> net: lib: nrf_cloud: add callback option for cell pos response

applications/asset_tracker_v2/src/cloud/cloud_codec/nrf_cloud/nrf_cloud_codec.c
Fix bugs introduced in https://github.com/nrfconnect/sdk-nrf/pull/5948
=> applications: asset_tracker_v2: Fix bugs related to multicell support in nRF Cloud build

lib/supl/os/supl_os_client.c
Updated to use the new AT command interface.
=> lib: supl: use new AT command interface

doc/_static/css/nrf.css, doc/_static/css/nrfxlib.css, west.yml
Added CSS styling for ZBOSS banner in nrfxlib.
=> doc: add ZBOSS banner CSS and manifest

applications/machine_learning/src/modules/ml_runner.c, doc/nrf/libraries/others/ei_wrapper.rst, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/ug_edge_impulse.rst, include/ei_wrapper.h, lib/edge_impulse/ei_wrapper.cpp, samples/edge_impulse/wrapper/README.rst, samples/edge_impulse/wrapper/src/main.c, tests/lib/edge_impulse/src/edge_impulse_zip/edge-impulse-sdk/ei_run_classifier_mock.cpp, tests/lib/edge_impulse/src/edge_impulse_zip/ei_test_params.h, tests/lib/edge_impulse/src/main.cpp
Expand API to provide input data sampling frequency, all labels and result data associated with every label. Change also updates related application, sample and test. Documentation is updated too.
Jira: NCSDK-12108
=> lib: edge_impulse: Expand ei_wrapper API

lib/lte_link_control/lte_lc.c
lte_lc_psm_get() uses AT%XMONITOR command to obtain the PSM config.
If the device is not camped on a cell the AT command response is
missing several fields which caused at command parsing to fail.
This is now fixed by using nrf_modem_at_cmd() instead of
nrf_modem_at_scanf().
Signed-off-by: Tuomas Hiltunen <tuomas.hiltunen@nordicsemi.no>
=> lib: lte_link_control: fix lte_lc_psm_get() when not camped on a cell

doc/nrf/links.txt, doc/nrf/shortcuts.txt
Updated links and shortcut to 3.9.0.1 ZBOSS.
=> doc: zigbee: update zboss links

doc/nrf/libraries/others/images/supl_msc.svg, doc/nrf/libraries/others/supl_os_client.rst
Updated documentation to reflect the GNSS API.
=> lib: supl: update SUPL client and SUPL client OS integration docs

applications/nrf_desktop/src/modules/hid_state.c
Change fixes finding next report state after unsubscription.
Jira: NCSDK-12337
=> applications: nrf_desktop: Fix finding next report state

applications/nrf_desktop/doc/config_channel.rst, doc/nrf/releases/release-notes-changelog.rst, scripts/hid_configurator/README.rst
Change updates configuration channel documentation to provide more implementation details related to device discovery mechanism.
Jira: NCSDK-12196
=> applications: nrf_desktop: Update documentation of config channel

applications/nrf_desktop/src/modules/usb_state.c
Fix the usb driver API usage. Proper use of len parameter
in set_report and get_report callbacks.
JIRA: NCSDK-12435
=> applications: nrf_desktop: Fix USB HID report handling

doc/nrf/releases/release-notes-changelog.rst, samples/nrf9160/gnss/Kconfig, samples/nrf9160/gnss/README.rst, samples/nrf9160/gnss/src/main.c
Added support for periodic fixes, power saving and low accuracy fixes.
Added speed accuracy and DOPs to PVT output.
=> samples: nrf9160: gnss: add new features

applications/pelion_client/configuration/nrf9160dk_nrf9160_ns/boards/nrf9160dk_nrf9160_ns_0_14_0.overlay
=> applications: pelion_client: Fix extflash config on nrf91dk 0.14.0

subsys/event_manager_profiler/event_manager_profiler.c
Fix bugs in Event Manager Profiler freom commit devide event manager.
=> event_manager: Fix bugs

samples/nrf9160/modem_shell/src/gnss/gnss_interface.c
Set the modem gnss event handler every time a MoSh gnss command is
given. Previously this did take place if gnss was already initialized.
Signed-off-by: Tuomas Hiltunen <tuomas.hiltunen@nordicsemi.no>
=> samples: nrf9160: modem_shell: always set gnss command event handler

applications/asset_tracker_v2/src/cloud/azure_iot_hub_integration.c, applications/asset_tracker_v2/src/cloud/cloud_codec/azure_iot_hub/azure_iot_hub_codec.c, applications/asset_tracker_v2/src/modules/Kconfig.app_module, doc/nrf/releases/release-notes-changelog.rst
Start sending neighbor cell measurements to Azure IoT Hub.
=> applications: asset_tracker_v2: Send neighbor cell measurements to Azure

doc/nrf/libraries/zigbee/index.rst, doc/nrf/samples/samples_zigbee.rst, doc/nrf/ug_zigbee_configuring.rst, samples/zigbee/light_bulb/README.rst, samples/zigbee/light_switch/README.rst, samples/zigbee/network_coordinator/README.rst, samples/zigbee/template/README.rst
Added table listing available Zigbee sample variants.
=> doc: zigbee: sample variant overview

doc/nrf/releases/release-notes-changelog.rst, include/net/nrf_cloud_agps.h, include/net/nrf_cloud_cell_pos.h, include/net/nrf_cloud_pgps.h, subsys/net/lib/nrf_cloud/src/nrf_cloud_agps.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_cell_pos.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_codec.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c
Ensure device is connected to the d2c topic before sending
data.
CIA-464
=> net: lib: nrf_cloud: add missing state checks to MQTT based APIs

include/modem/location.h, lib/location/method_gnss.c, lib/location/wifi/wifi_nrf_cloud_rest.c, samples/nrf9160/location/prj.conf, samples/nrf9160/location/sample.yaml
Small updates to location library and sample.
=> lib: location: Misc updates to library and sample

doc/nrf/ug_zigbee_qsg.rst, samples/zigbee/network_coordinator/README.rst, samples/zigbee/network_coordinator/src/main.c, samples/zigbee/shell/src/main.c, samples/zigbee/template/src/main.c
Branch tests:
https://jenkins-ncs.nordicsemi.no/job/latest/job/test-fw-nrfconnect-zigbee/job/test-branch/116
https://jenkins-ncs.nordicsemi.no/job/latest/job/test-fw-nrfconnect-zigbee/job/test-branch/117
=> KRKNWK-8406: Extend Zigbee Coordinator sample with Basic clusters

doc/nrf/links.txt, west.yml
New sdk-connectedhomeip revision contains DNS-SD resolving fix.
=> manifest: Updated sdk-connectedhomeip revision to pull bug fix.

include/flash_map_pm.h, west.yml
=> flash_map: add partition manager variant for FLASH_AREA_DEVICE

.github/labeler.yml
Add glob patterns for the CI-gazell-test label.
=> labeler: Add CI-gazell-test label

samples/openthread/cli/harness/nRF_Connect_SDK.py
OpenThread and it's THCI file underwent a lot of changes and currently
used by NCS THCI file is outdated and causes certification failures.
THCI in OpenThread supports also zephyr right now so this version was
copied to NCS with classes being updated properly. Without changes
included in this file Thread 1.1 certification will fail.
Signed-off-by: Marek Porwisz <marek.porwisz@nordicsemi.no>
=> samples: openthread: cert: update THCI to the latest vestion

doc/nrf/releases/release-notes-changelog.rst
Add Gazell nRF52 support to changelog.
Nice to have. Sorry if this PR is submitted late.
=> doc improvement: Add Gazell to changelog

applications/nrf_desktop/src/modules/hid_forward.c
Now, when dongle disconnects from host,
dongle sends empty hid output reports to peripheral.
Also, dongle collects the most recent hid output reports
and when peripheral connects to dongle,
those collected reports are sent.
Jira: NCSDK-10341
Signed-off-by: Aleksander Strzebonski <aleksander.strzebonski@nordicsemi.com>
=> nrf_desktop: hid_forward: Fix hid output reports handling

doc/nrf/known_issues.rst
1.8.0 is not yet released.
Issue introduced in #6093.
=> doc: revert known issue for 1.8.0

doc/nrf/libraries/gazell/gzll_glue.rst, doc/nrf/ug_gzll.rst, doc/nrf/ug_gzp.rst, west.yml
Document the Kconfig options and the glue code to enable the Gazell features.
=> Document Gazell configuration

applications/asset_tracker_v2/src/modules/Kconfig.gps_module
This adds a help text to clarify what the options mean.
=> applications: asset_tracker_v2: add help to PVT/NMEA choice

subsys/caf/modules/Kconfig.ble_bond
=> doc: caf: Fix small typo

boards/arm/thingy91_nrf9160/board_nonsecure.c
Guard calls to nrf_modem_at_printf by returning early if a modem
firmware update has been performed. If modem DFU has been performed
calls to nrf_modem_at_ is expected to fail.
Closes CIA-471
=> boards: arm: thingy91_nrf9160: Guard calls to nrf_modem_at_printf

west.yml
For https://github.com/nrfconnect/sdk-nrfxlib/pull/593
Signed-off-by: Deidre Casey <deidre.casey@nordicsemi.no>
=> doc: update nrfxlib revision for mpsl figures update

samples/nrf9160/aws_fota/src/main.c
Reboot after modem DFU.
If a modem DFU has been performed, a reboot is expected to fully
apply the new modem firmware image.
Closes CIA-344
=> nrf9160: samples: aws_fota: Reboot after modem DFU

applications/nrf_desktop/src/modules/dfu.c
This commit makes sure that when DFU is in progress
the CPU would not go into deep sleep when USB cable
is disconnected in the middle of the operation.
=> applications: nrf_desktop: Restrict power modes during DFU

doc/nrf/links.txt, west.yml
While testing RC1, we discovered a few issues related
to Matter testing tools, including Android CHIPTool.
=> manifest: pull fixes for Matter testing tools

subsys/zigbee/osif/zb_nrf_transceiver.c
Add workaround for packets being retransmitted after incorrect delay when previously transmitted packet was not ACKed.
=> zigbee: Workaround for KRKNWK-12301

applications/asset_tracker_v2/doc/asset_tracker_v2_description.rst, applications/asset_tracker_v2/doc/debug_module.rst, applications/serial_lte_modem/doc/slm_data_mode.rst, applications/serial_lte_modem/doc/slm_description.rst, doc/nrf/templates/sample_README.rst, samples/crypto/psa_tls/README.rst, samples/nrf9160/aws_fota/README.rst, samples/nrf9160/aws_iot/README.rst, samples/nrf9160/download/README.rst, samples/nrf9160/gnss/README.rst, samples/nrf9160/http_update/full_modem_update/README.rst, samples/nrf9160/location/README.rst, samples/nrf9160/lwm2m_client/README.rst, samples/nrf9160/modem_shell/README.rst, samples/nrf9160/mqtt_simple/README.rst, samples/nrf9160/sms/README.rst, samples/nrf9160/udp/README.rst, scripts/requirements-doc.txt
Fix sample config option linking
The PR temporary pulls in the associated style changes made to the theme repo (https://github.com/nrfconnect/doc-sphinx-ncs-theme/pull/4) just to make the changes visible in the PR preview (through https://github.com/nrfconnect/sdk-nrf/pull/6253/commits/dce3f1e4b5518708b368b21a6e4fdaa5547ff9b1) and this commit will be removed before merging.
=> doc: Fix sample config option linking

applications/asset_tracker_v2/src/cloud/nrf_cloud_integration.c
If the application receives a user association request it is expected
that the application explicitly disconnects the nRF cloud transport
library to allow subsequent calls to `nrf_cloud_connect`.
This is needed to complete user association after the device
has been registered to an nRF Cloud account.
Fixes CIA-478
=> applications: asset_tracker_v2: Disconnect upon an association request

applications/machine_learning/README.rst, doc/nrf/ug_bt_mesh_vendor_model_dev_overview.rst, doc/nrf/ug_gzll.rst, samples/bluetooth/direct_test_mode/README.rst
Documentaion fixes in Protocols, Applications and Samples.
NCSDK-12637.
=> doc improvement: Various doc fixes

doc/nrf/releases/release-notes-changelog.rst
Release notes for Bluetooth mesh in NCS v1.8.0.
=> doc: Bluetooth: Mesh: Release notes for v1.8.0

lib/multicell_location/services/nrf_cloud_integration.c
If callback function that handles the cellular position response from
the cloud was called with NULL 'result' argument, multicell_location
would have returned old or possibly uninitialized location. Now it'll
just print an error.
Signed-off-by: Tuomas Hiltunen <tuomas.hiltunen@nordicsemi.no>
https://projecttools.nordicsemi.no/jira/browse/NCSDK-12743
=> lib: multicell_location: handle NULL position result from cloud

applications/matter_weather_station/README.rst, doc/nrf/ug_matter.rst, doc/nrf/ug_matter_configuring.rst, doc/nrf/ug_matter_configuring_controller.rst, doc/nrf/ug_matter_configuring_env.rst, doc/nrf/ug_matter_configuring_protocol.rst, doc/nrf/ug_matter_tools.rst, samples/matter/lock/README.rst
Updated Matter dev environment docs for clarity.
=> doc: matter: rewrite matter dev environement docs

applications/machine_learning/README.rst, applications/matter_weather_station/README.rst, applications/nrf_desktop/README.rst, applications/pelion_client/README.rst, cmake/multi_image.cmake, doc/nrf/gs_modifying.rst, doc/nrf/links.txt, doc/nrf/releases/release-notes-changelog.rst
Updated build type sections with the latest info.
Added build-type-related VSC section.
=> doc improvement: gs_modifying: update build type sections

west.yml
See the CHANGELOG.rst file alongside the binary for a complete list of changes in this release.
=> manifest: nrf_modem: v1.0.1 1

doc/nrf/libraries/others/event_manager.rst
=> doc: event_manager: misc fixes

doc/nrf/index.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/release_notes.rst, doc/nrf/releases/release-notes-1.8.0.rst, doc/nrf/releases/release-notes-changelog.rst
Finalized the release notes based on changelog.
Applied other required edits for release.
NCSDK-12644.
----
=> doc: add release notes for 1.8.0

doc/nrf/conf.py, doc/nrf/index.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/release_notes.rst, doc/nrf/releases/release-notes-changelog.rst, doc/nrfxlib/conf.py, doc/versions.json
Various post-release changes in doc.
Based on nrfconnect#5604. NCSDK-12639.
=> doc: update versions in doc after 1.8.0 release

west.yml
Update manifest file with v1.5.2 tags.
=> manifest: Update manifest file with v1.5.2 tag

subsys/nfc/lib/platform.c
There is no reason for FICR_NFC_TAGHEADER0_MFGID_Msk to not be
present. And if, for whatever reason it is missing we should fail with
a compilation error instead of silently using, presumably, invalid
values.
Also leave a TODO for the next developer that adds support for TF-M
with NFCT.
=> nfct: Drop support for compiling without NFCT defines present

doc/nrf/releases/release-notes-1.5.2.rst
Update path syntax in 1.5.2 release notes.
=> doc: Update path syntax in 1.5.2 release notes

doc/nrf/links.txt, doc/nrf/ug_nrf52.rst
ref: NCSDK-12950
Signed-off-by: Deidre Casey <deidre.casey@nordicsemi.no>
=> doc: add Device Manager as FOTA update option

subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_cell_pos, subsys/net/lib/nrf_cloud/src/nrf_cloud_cell_pos.c
Adding dependency to NRF_CLOUD_MQTT
Signed-off-by: Tuomas Hiltunen <tuomas.hiltunen@nordicsemi.no>
=> lib: nrf_cloud: make NRF_CLOUD_CELL_POS depend on NRF_CLOUD_MQTT

doc/nrf/libraries/modem/pdn.rst, include/modem/pdn.h
Minor updates to the header and documentation.
=> doc: pdn: minor updates

applications/nrf_desktop/doc/battery_charger.rst
Style fix for local configs. in file.
Signed-off-by: Katherine Depa <katherine.depa@nordicsemi.no>
=> doc improvement: fix style in sdk-nrf

lib/location/method_gnss.c, lib/multicell_location/Kconfig, lib/multicell_location/services/nrf_cloud_integration.c, samples/nrf9160/modem_shell/src/gnss/gnss_interface.c, subsys/net/lib/nrf_cloud/CMakeLists.txt, subsys/net/lib/nrf_cloud/Kconfig, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_pgps, subsys/net/lib/nrf_cloud/src/nrf_cloud_jwt.c
Improve configuration handling related to REST and MQTT selections to get better compilation errors.
Let's merge this one only after PR https://github.com/nrfconnect/sdk-nrf/pull/6223 has been merged and this one rebased.
=> lib: Verification for nRF Cloud REST and MQTT configurations

samples/bluetooth/central_smp_client/README.rst
Update testing instructions as per NCSDK-6853.
=> doc: update central_smp_client testing doc

applications/nrf_desktop/doc/dfu.rst, applications/nrf_desktop/src/modules/dfu.c, doc/nrf/releases/release-notes-changelog.rst, scripts/hid_configurator/NrfHidDevice.py, scripts/hid_configurator/README.rst, scripts/hid_configurator/configurator_cli.py, scripts/hid_configurator/modules/dfu.py
Add fetch of bootloader variant in dfu module
Check if the bootloader file passed is compatible while doing dfu
Jira: NCSDK-12781
=> nrf_desktop: dfu: Config channel should distinguish bootloader type

doc/nrf/ug_thread_configuring.rst
changed Enabling to Enable in line 252.
=> doc: nrf: configuring thread: typo

doc/nrf/glossary.rst
=> doc: Glossary Update

CODEOWNERS
=> CODEOWNERS: few updates

doc/nrf/app_opt.rst, doc/nrf/ext_comps.rst, doc/nrf/protocols.rst, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/ug_app_dev.rst
Reorganizing the documentation of the Application
development section.
Ref: NCSDK-12679
=> doc: optimizing subpage levels in App development section

applications/asset_tracker_v2/README.rst, applications/asset_tracker_v2/doc/sensor_module.rst, applications/asset_tracker_v2/src/events/sensor_module_event.h, doc/nrf/links.txt
Add documentation for the sensor module.
Resolves CIA-486
=> Asset Tracker v2: Add documentation for the sensor module

applications/asset_tracker_v2/README.rst, applications/asset_tracker_v2/doc/asset_tracker_v2_description.rst, applications/asset_tracker_v2/doc/ui_module.rst, applications/asset_tracker_v2/src/events/ui_module_event.h
Add documentation for the UI module.
Resolves CIA-484
=> applications: asset_tracker_v2: Add documentation for the UI module

subsys/bluetooth/controller/hci_driver.c
Signed-off-by: Timothy Keys <timothy.keys@nordicsemi.no>
=> softdevice_controller: Fix double negative bug

doc/nrf/libraries/modem/lte_lc.rst
Makes fallback mode visible in our documentation.
=> doc: modem: documents LTE fallback mode

subsys/net/lib/aws_iot/src/aws_iot.c
Refer to correct variable in inet_pton() call.
=> lib: aws_iot: Fix static IPv4 config

lib/modem_info/modem_info.c
Port to `nrf_modem_at` and `at_notif`.
Escape % characters as necessary.
=> lib: modem_info: port to nrf_modem_at APIs

applications/nrf_desktop/doc/buttons.rst, doc/nrf/libraries/caf/buttons.rst
Clarify what KEY_ID means in button_event.
Jira: NCSDK-12407
=> doc: caf: Add description of what KEY_ID is

samples/nrf9160/http_update/full_modem_update/src/main.c
*Remove usage of at_cmd library.
=> samples: nrf9160: full_modem_update: Remove usage of at_cmd lib

.github/labeler.yml
Tests for these samples have been added.
=> labeler: Add AWS Iot and Azure Iot Hub

lib/at_host/Kconfig, lib/at_host/at_host.c
Port from at_cmd to nrf_modem_at.
=> lib: at_host: use nrf_modem_at APIs

subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_firmware.c
In case fw download is restarted a reset of dfu target is missing
causing invalid writing to dfu target.
=> net: lib: lwm2m_client_utils: fixed installing fw once it was aborted

samples/nrf9160/lwm2m_client/src/main.c
Port from at_cmd to nrf_modem_at.
=> samples: nrf9160: lwm2m_client: use nrf_modem_at APIs

samples/bluetooth/direction_finding_connectionless_rx/src/main.c
Periodic advertising synchronization create had a timeout set
to fixed value of 10 seconds. BT 5.3 Core specification defines
synchronization timeout as 6 consecutive periodic advertising
events. When advertiser set the periodic interval to be more than
1.6 second it was possible the application timeout is reached
before time allowed by BT Core specification.
Changed implementation of timeout to depend on the periodic
advertising interval.
Signed-off-by: Piotr Pryga <piotr.pryga@nordicsemi.no>
=> samples: Bluetooth: df: Fix to early per sync create timeout

doc/nrf/ug_matter_creating_accessory.rst
1. Update the described procedure to match the current
Matter API.
2. Rephrase some unclear statements.
3. Use code indentation consistently across the whole doc.
=> doc: update guide on creating Matter accessory

applications/asset_tracker_v2/README.rst, applications/asset_tracker_v2/doc/modules_common.rst, applications/asset_tracker_v2/doc/util_module.rst, applications/asset_tracker_v2/src/events/util_module_event.h, applications/asset_tracker_v2/src/main.c, applications/asset_tracker_v2/src/modules/Kconfig.util_module, applications/asset_tracker_v2/src/modules/modules_common.h, applications/asset_tracker_v2/src/modules/util_module.c, doc/nrf/releases/release-notes-changelog.rst
Add documentation for the utility module.
Resolves CIA-505
=> asset_tracker_v2: Add documentation for the utility module

subsys/zigbee/Kconfig, subsys/zigbee/cli/zigbee_cli_cmd_bdb.c, subsys/zigbee/osif/zb_nrf_platform.c
This commit changes letter case of "zboss" mentions
=> zigbee: Change "zboss" to uppercase

subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/hci_driver.c, west.yml
Updating nrfxlib and mpsl to latest version to fix bugs in periodic advertising and adding periodic advertising list feature
=> manifest: Updating nrfxlib - 2022 jan 18

applications/nrf_desktop/README.rst, doc/nrf/links.txt
Add link to nRF Desktop reference design page.
Jira: NCSDK-13052
=> applications: nrf_desktop: Add link to nordicsemi page

subsys/mpsl/cx/CMakeLists.txt, subsys/mpsl/cx/Kconfig, subsys/mpsl/cx/generic_3pin/mpsl_cx_generic_3pin.c
This commit adds experimental generic_3pin implementation of
cx interface.
Signed-off-by: Andrzej Kuros <andrzej.kuros@nordicsemi.no>
=> mpsl: cx: add generic_3pin cx implementation

doc/nrf/known_issues.rst
=> doc: Add known issue for extended scanning

west.yml
This commit updates sdk-nrf-802154 and sdk-nrfxlib revisions to bring
in the latest changes in the nrf_802154 component.
Signed-off-by: Jedrzej Ciupis <jedrzej.ciupis@nordicsemi.no>
=> west.yml: update nrf-802154 and nrfxlib revisions

subsys/caf/modules/Kconfig.factory_reset_request, subsys/caf/modules/net_state_lte.c, subsys/caf/modules/net_state_ot.c
Remove references to Pelion library - leftover from original implementation.
=> Ncsdk 13396 caf pelion cleanup

applications/machine_learning/configuration/nrf5340dk_nrf5340_cpuapp/prj.conf, applications/machine_learning/configuration/thingy52_nrf52832/prj.conf, applications/machine_learning/configuration/thingy52_nrf52832/prj_release.conf
Change fixes a typo in configurations that caused build failures.
=> applications: machine_learning: Fix typo in configuration

samples/bluetooth/peripheral_hids_keyboard/src/app_nfc.c, samples/bluetooth/peripheral_nfc_pairing/src/main.c, samples/nfc/record_launch_app/src/main.c, samples/nfc/record_text/src/main.c, samples/nfc/system_off/src/main.c, samples/nfc/tnep_tag/src/main.c, samples/nfc/writable_ndef_msg/src/main.c, west.yml
Port the new NFC library which is built by build system based on the CMake
=> NFC: Port new nfc library version

samples/zigbee/light_bulb/README.rst, samples/zigbee/light_bulb/src/main.c, samples/zigbee/network_coordinator/README.rst
- Light Bulb sample to use its default LED for identifying
- Network coordinator - add missing docs
=> Zigbee samples improvements

doc/nrf/releases/release-notes-changelog.rst, include/net/nrf_cloud.h, subsys/net/lib/nrf_cloud/include/nrf_cloud_transport.h, subsys/net/lib/nrf_cloud/src/nrf_cloud.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c
=> Disconnect when we detect a ping error

doc/mcuboot/index-ncs.rst
Removed documentation section to fix issues with doc menu.
=> doc: Updated index-ncs.rst

west.yml
This commit updates sdk-zephyr revision to patch ieee802154 driver.
Signed-off-by: Jedrzej Ciupis <jedrzej.ciupis@nordicsemi.no>
=> manifest: update sdk-zephyr revision

west.yml
* Updates softdevice-controller and mpsl.
* Fixes bugs in periodic advertising.
Signed-off-by: Aytürk Düzen <ayturk.duzen@nordicsemi.no>
=> manifest: Updating nrfxlib

samples/matter/common/src/dfu_over_smp.cpp
=> samples: matter: fix coverity warning

west.yml
Meta PR with changes needed for thingy52 fmn application
to work.
Signed-off-by: Dominik Chat <dominik.chat@nordicsemi.no>
=> manifest: meta-pr for thingy52 fmn application

applications/asset_tracker_v2/src/modules/ui_module.c, applications/asset_tracker_v2/tests/ui_module/CMakeLists.txt, applications/asset_tracker_v2/tests/ui_module/Kconfig, applications/asset_tracker_v2/tests/ui_module/prj.conf, applications/asset_tracker_v2/tests/ui_module/src/ui_module_test.c, applications/asset_tracker_v2/tests/ui_module/src/ui_module_test.h, applications/asset_tracker_v2/tests/ui_module/src/vars_internal.h, applications/asset_tracker_v2/tests/ui_module/testcase.yaml
=> applications: asset_tracker_v2: Add test for UI module

samples/nrf9160/modem_shell/README.rst, samples/nrf9160/modem_shell/src/at/at_shell.c, samples/nrf9160/modem_shell/src/main.c
=> samples: nrf9160: modem_shell: port to nrf_modem_at APIs

doc/nrf/ug_bootloader_adding.rst
Update mentions of prj_minimal.conf in ug_bootloader_adding.
=> docs: update ug_bootloader_adding

samples/openthread/cli/sample.yaml
Fix typo in integration list in sample.yaml of openthread
Signed-off-by: Maciej Perkowski <Maciej.Perkowski@nordicsemi.no>
=> samples: openthread: Fix typo in integration list

subsys/nfc/lib/platform.c
Add handling of NFC tagheaders with TF-M enabled.
Avoid using multiple read requests with both TF-M and SPM by reading
them all in one operation. This avoids the cost of doing multiple IPC
operations.
NCSDK-12126
=> nfc: Add handling of tagheaders with TF-M enabled

applications/asset_tracker_v2/README.rst, applications/asset_tracker_v2/doc/app_module.rst, applications/asset_tracker_v2/doc/asset_tracker_v2_description.rst, applications/asset_tracker_v2/doc/data_module.rst, applications/asset_tracker_v2/src/events/data_module_event.h, doc/nrf/releases/release-notes-changelog.rst
Add documentation for application and data module.
Fixes CIA-488 and CIA-483
=> applications: asset_tracker_v2: Add docs for application and data module

doc/nrf/links.txt, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/shortcuts.txt
This commit updates links to external ZBOSS stack documentation and zigbee tools.
=> doc: Update zigbee tools and ZBOSS libraries versions in the doc

applications/machine_learning/README.rst
This commit adds documentation in the application README file
about the power management implemented in machine learning.
=> applications: machine_learning: Add information about power management

scripts/quarantine.yaml
The Edge Impulse server issue is fixed.
Jira: NCSDK-13303
=> scripts: quarantine: Remove machine learning app and sample

doc/nrf/links.txt
Ref: NCSDK-13378
Signed-off-by: Deidre Casey <deidre.casey@nordicsemi.no>
=> Update VSC links with new url

doc/nrf/releases/release-notes-changelog.rst, doc/nrf/ug_thread_certification.rst, doc/nrf/ug_thread_configuring.rst, samples/openthread/cli/boards/nrf5340dk_nrf5340_cpuapp_ns.conf, samples/openthread/coap_client/boards/nrf5340dk_nrf5340_cpuapp_ns.conf, samples/openthread/coap_server/boards/nrf5340dk_nrf5340_cpuapp_ns.conf, subsys/net/openthread/Kconfig.defconfig, west.yml
=> manifest: OpenThread upmerge up to commit `ce77ab3c`

samples/crypto/aes_cbc/README.rst, samples/crypto/aes_ccm/README.rst, samples/crypto/aes_ctr/README.rst, samples/crypto/aes_gcm/README.rst, samples/crypto/chachapoly/README.rst, samples/crypto/ecdh/README.rst, samples/crypto/ecdsa/README.rst, samples/crypto/hkdf/README.rst, samples/crypto/hmac/README.rst, samples/crypto/persistent_key_usage/README.rst, samples/crypto/psa_tls/README.rst, samples/crypto/rng/README.rst, samples/crypto/rsa/README.rst, samples/crypto/sha256/README.rst, tests/crypto/README.rst
Fixed inconsistencies in spelling and structure.
=> doc improvement: style fixes in Crypto samples

samples/matter/light_bulb/README.rst, samples/matter/light_switch/README.rst, samples/matter/lock/README.rst, samples/matter/template/README.rst
Fixed inconsistencies in spelling and structure.
=> doc improvement: style fixes in Matter samples

samples/nrf5340/empty_app_core/README.rst, samples/nrf5340/multiprotocol_rpmsg/README.rst, samples/nrf5340/netboot/README.rst, samples/nrf_rpc/entropy_nrf53/README.rst
=> doc improvement: style fixes in nRF5340 samples

samples/openthread/cli/README.rst, samples/openthread/coap_client/README.rst, samples/openthread/coap_server/README.rst, samples/openthread/coprocessor/README.rst
=> doc improvement: style fixes in Thread samples

samples/nfc/record_launch_app/README.rst, samples/nfc/record_text/README.rst, samples/nfc/system_off/README.rst, samples/nfc/tag_reader/README.rst, samples/nfc/tnep_poller/README.rst, samples/nfc/tnep_tag/README.rst, samples/nfc/writable_ndef_msg/README.rst
=> doc improvement: style fixes in NFC samples

doc/nrf/ug_matter_configuring_protocol.rst
Added information about setting Matter log levels
and available device identification optional features.
=> doc: Extended Matter configuring protocol section

samples/bluetooth/mesh/ble_peripheral_lbs_coex/README.rst, samples/bluetooth/mesh/silvair_enocean/README.rst, samples/bluetooth/peripheral_hr_coded/README.rst, samples/bluetooth/peripheral_nfc_pairing/README.rst, samples/bluetooth/peripheral_uart/README.rst, samples/bluetooth/radio_coex_1wire/README.rst, samples/bluetooth/radio_coex_3wire/README.rst, samples/bluetooth/rpc_host/README.rst, samples/bluetooth/throughput/README.rst
Fixed inconsistencies in spelling and structure.
=> doc improvement: style fixes in Bluetooth samples

west.yml
Add parallelization to clang build action
Signed-off-by: Maciej Perkowski <Maciej.Perkowski@nordicsemi.no>
=> manifest: Update Zephyr revision

samples/bootloader/README.rst
=> doc improvement: style fixes for Immutable Bootloader sample

CODEOWNERS
Update TF-M entries in codeowners file.
=> CODEOWNERS: Update TF-M entries

samples/keys/hw_unique_key/README.rst
=> doc improvement: style fixes in Hardware unique key sample

west.yml
=> manifest: NCS v1.9.0-rc1

samples/nrf9160/at_client/README.rst, samples/nrf9160/aws_fota/README.rst, samples/nrf9160/aws_iot/README.rst, samples/nrf9160/azure_iot_hub/README.rst, samples/nrf9160/cloud_client/README.rst, samples/nrf9160/coap_client/README.rst, samples/nrf9160/fmfu_smp_svr/README.rst, samples/nrf9160/gnss/README.rst, samples/nrf9160/https_client/README.rst
Fixed inconsistencies in style and structure
=> doc improvement: style fixes in nRF9160 samples part-1

samples/nrf9160/http_update/application_update/README.rst, samples/nrf9160/http_update/full_modem_update/README.rst, samples/nrf9160/http_update/modem_delta_update/README.rst, samples/nrf9160/lte_ble_gateway/README.rst, samples/nrf9160/lwm2m_client/README.rst, samples/nrf9160/memfault/README.rst, samples/nrf9160/modem_shell/README.rst, samples/nrf9160/secure_services/README.rst, samples/nrf9160/sms/README.rst, samples/nrf9160/udp/README.rst
Fixed inconsistencies in style and structure
=> doc improvement: style fixes in nRF9160 samples part-2

subsys/bluetooth/mesh/light_ctrl_srv.c, tests/subsys/bluetooth/mesh/light_ctrl/src/main.c
Current implementation may produce the light's glitches, because the
output of the FSM and the regulator's output interfere when FSM
transitions to another state.
When the regulator is enabled, only the maximum of 2 states, the
Lightness Out and Regulator Output, should be published (section
6.2.3.6). If no sensor reports have been provided yet, the regulator
will drive the lightess to the maximum value. To avoid this, the
controller should publish the Lightness Out state until any sensor
report with an ambient light level is provided.
test-sdk-nrf: PR-108
Signed-off-by: Pavel Vasilyev <pavel.vasilyev@nordicsemi.no>
=> Bluetooth: Mesh: Make regulator to not interfere with controller's FSM

boards/arm/thingy91_nrf9160/pre_dt_board.cmake
=> Fix ncsdk 12745

samples/peripheral/lpuart/README.rst, samples/peripheral/radio_test/README.rst, samples/sensor/bh1749/README.rst, samples/tfm/tfm_hello_world/README.rst
Fixed inconsistencies in style and structure in
UART, Radio Test, BH1749, and Hello World samples.
=> doc improvement: style fixes in Other samples

samples/spm/README.rst
=> doc improvement: Style fixes in SPM sample

samples/debug/ppi_trace/README.rst
=> doc improvement: style fixes in PPI trace sample

samples/keys/random_hw_unique_key/README.rst
=> doc improvement: style fixes in Random HUK sample

samples/mpsl/timeslot/README.rst
=> doc improvement: Style fixes in MPSL timeslot sample

samples/peripheral/802154_phy_test/README.rst
=> doc improvement: style fixes to IEE 820.15.4 PHY test tool sample

west.yml
=> manifest: Update HomeKit manifest: Fix bug: NCSDK-13771

doc/nrf/introduction.rst
The introduction paragraph was outdated and incomplete, fix it.
=> doc: about: Rework the intro paragraph

applications/asset_tracker_v2/tests/debug_module/src/debug_module_test.c, applications/asset_tracker_v2/tests/gnss_module/src/gnss_module_test.c, applications/asset_tracker_v2/tests/ui_module/src/ui_module_test.c
Fix issues suggested by static analysis.
=> applications: asset_tracker_v2: Fix issues suggested by static analysis

west.yml
Includes the bugfix needed for nRF53.
Ref: DRGN-16808
=> manifest: Update SoftDevice Controller revision

west.yml
-Adds nrf_security documentation changes
ref: NCSDK-12816
=> manifest: Update to nrfxlib PR #652

west.yml
=> manifest: NCS v1.9.0-rc2

west.yml
This is a step in the release process
=> manifest: rebase OSS trees

lib/location/method_cellular.c
Pointer to neighbor cell information was
overwritten when handling
LTE_LC_EVT_NEIGHBOR_CELL_MEAS and resulted
corrupted information to be encoded towards
cloud when requesting positioning estimate.
Jira: NCSDK-13874
Signed-off-by: Jani Hirsimäki <jani.hirsimaki@nordicsemi.no>
=> lib: location: cellular_method: multicell fixed

doc/nrf/gs_programming.rst, doc/nrf/index.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/release_notes.rst, doc/nrf/releases/release-notes-1.9.0.rst, doc/nrf/releases/release-notes-changelog.rst
Add release notes for NCS 1.9
based on changelog.
NCSDK-13409
=> doc: Add release notes for NCS 1.9

doc/nrf/known_issues.rst
Update known issues for 1.9 release
=> doc: Update known issues for 1.9 release

west.yml
=> manifest: NCS v1.9.0

doc/nrf/conf.py, doc/nrf/index.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/release_notes.rst, doc/nrf/releases/release-notes-changelog.rst, doc/nrfxlib/conf.py, doc/versions.json
=> doc: post 1.9.0 doc update

doc/nrf/known_issues.rst
=> doc: Add known issue for Zephyr Write Tx Power for the SDC

doc/nrf/includes/tfm.txt, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/ug_nrf5340.rst, doc/nrf/ug_tfm.rst, doc/nrf/ug_thread_configuring.rst, samples/keys/hw_unique_key/README.rst, samples/openthread/cli/README.rst, samples/openthread/coap_client/README.rst, samples/openthread/coap_server/README.rst
Added information about Thread supporting TF-M.
Updated structure on some pages for clarity.
Reworked formatting of the include tfm text file.
KRKNWK-10091.
=> doc: tf-m: update thread with support information

Jenkinsfile, test-manifests/99-default-test-nrf.yml
=> ci: use forked branches of CI/Verification repositories on v1.9-branch

west.yml
* Updates softdevice-controller and mpsl.
* Fixes an issue where radio notifications in MPSL could cause an assert
Signed-off-by: Jan Müller <jan.mueller@nordicsemi.no>
=> manifest: Update ble-controller/MPSL revision

applications/nrf_desktop/doc/usb_state.rst, doc/nrf/releases/release-notes-changelog.rst
Change adds documentation of selective HID report subscription for nRF Desktop Peripherals.
Jira: NCSDK-12665
=> applications: nrf_desktop: Document selective report subscription

doc/nrf/glossary.rst
I didn't manage to review https://github.com/nrfconnect/sdk-nrf/pull/6406/ before going on vacation, so I'm just sending a follow-up PR with patches instead of a review.
=> Doc: glossary updates, January 22

subsys/bluetooth/mesh/scheduler_srv.c
Time server can return error statuses or NULL pointers due to
internal algorithm reasons. The scheduler server should handle
these situations correctly.
=> Bluetooth: Mesh: add Time model error handling in Scheduler server

lib/at_sms_cert/at_sms_cert.c
Address issues found by coverity.
=> lib: at_sms_cert: Coverity findings

doc/nrf/ug_zigbee_qsg.rst, samples/zigbee/network_coordinator/README.rst
KRKNWK-12975
Small improvements to the Zigbee quick start guide.
=> doc improvement: Zigbee QSG

subsys/net/lib/nrf_cloud/src/nrf_cloud_fota.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_rest.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c
Addressing issues reported by Coverity
=> net: lib: nrf_cloud: Coverity fixes

samples/nrf9160/modem_shell/src/link/link_api.c, samples/nrf9160/modem_shell/src/link/link_shell.c, samples/nrf9160/modem_shell/src/ping/icmp_ping_shell.c, samples/nrf9160/modem_shell/src/sock/sock.c, samples/nrf9160/modem_shell/src/utils/mosh_print.c
Fix issues reported by coverity in the modem_shell sample.
Please note, that each commit addresses a different issue, so it's best to review commit by commit to get a clear view of what was changed and why.
=> samples: nrf9160: modem_shell: Coverity fixes

west.yml
=> manifest: zephyr update with openthread fixes

lib/modem_info/modem_info_json.c
Address issues found by Coverity
=> lib: modem_info: Fix coverity issues

applications/serial_lte_modem/src/slm_at_socket.c
Use special string of "NULL"/"null" to disable hostname verify.
=> application: serial_lte_modem: fix for TLS_HOSTNAME disable

doc/nrf/conf.py, doc/nrf/dm_adding_code.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/release_notes.rst, doc/nrf/releases/release-notes-1.9.0.rst, doc/nrf/releases/release-notes-1.9.1.rst, doc/nrf/shortcuts.txt, doc/nrfxlib/conf.py, doc/versions.json
Added version and placeholder release notes file.
=> doc: update documentation and versions for NCS 1.9.1

doc/nrf/applications.rst
Changed the order of applications in doc hierarchy.
--------
To be merged after #6992
=> doc: reorder applications alphabetically

samples/nrf9160/lwm2m_client/README.rst
Documented steps for Leshan bootstrap server fixed.
=> samples: nrf9160: lwm2m_client: Fix boostrap documentation

applications/serial_lte_modem/src/slm_at_host.c
Serial Sync API added TX cache and make sure of DMA data in RAM.
See CONFIG_UART_ASYNC_TX_CACHE_SIZE.
=> application: serial_lte_modem: Remove memcpy for UART TX DMA

west.yml
Update manifest revision for sdk-zephyr and sdk-trusted-firmware-m.
=> manifest: update manifest file with 1.9.1 tags

subsys/bluetooth/mesh/shell/shell_ctl_cli.c, subsys/bluetooth/mesh/shell/shell_ctrl_cli.c, subsys/bluetooth/mesh/shell/shell_hsl_cli.c, subsys/bluetooth/mesh/shell/shell_lightness_cli.c, subsys/bluetooth/mesh/shell/shell_loc_cli.c, subsys/bluetooth/mesh/shell/shell_lvl_cli.c, subsys/bluetooth/mesh/shell/shell_onoff_cli.c, subsys/bluetooth/mesh/shell/shell_plvl_cli.c, subsys/bluetooth/mesh/shell/shell_prop_cli.c, subsys/bluetooth/mesh/shell/shell_xyl_cli.c
Updates multiple print functions in shell client models to pass value
by reference to save resources.
Signed-off-by: Anders Storrø <anders.storro@nordicsemi.no>
=> Bluetooth: Mesh: Update print args shell cli mdl

doc/nrf/ug_nrf53.rst
Update information on nRF53 user guide.
Signed-off-by: Katherine Depa <katherine.depa@nordicsemi.no>
=> doc improvement: nRF53 description

west.yml
Manifest update for PR https://github.com/nrfconnect/sdk-nrfxlib/pull/676 in nrfxlib.
KRKNWK-12936.
=> manifest: nrfxlib: zboss doc update

lib/date_time/date_time.c, lib/date_time/date_time_core.c, lib/date_time/date_time_core.h, tests/lib/date_time/src/main.c
Signed-off-by: Nick Ewalt <nicholasewalt@google.com>
=> lib: date_time: Fix uptime to UTC time conversion

applications/zigbee_weather_station/README.rst, applications/zigbee_weather_station/src/main.c, doc/nrf/libraries/zigbee/zigbee_app_utils.rst, doc/nrf/releases/release-notes-changelog.rst, include/zigbee/zigbee_app_utils.h, samples/zigbee/light_bulb/README.rst, samples/zigbee/light_bulb/src/main.c, samples/zigbee/light_switch/README.rst, samples/zigbee/light_switch/src/main.c, samples/zigbee/network_coordinator/README.rst, samples/zigbee/network_coordinator/src/main.c, samples/zigbee/shell/README.rst, samples/zigbee/shell/src/main.c, samples/zigbee/template/README.rst, samples/zigbee/template/src/main.c, subsys/zigbee/lib/zigbee_app_utils/Kconfig, subsys/zigbee/lib/zigbee_app_utils/zigbee_app_utils.c
Proposal of Factory Reset implementation in Zigbee app utils and its usage across existing samples and app.
Some old code was reformatted by uncrustify tool - seems like the tool was not used in the past for affected files.
=> Krknwk 5104 implement factory reset logic

doc/nrf/libraries/modem/location.rst
Fixed bullet formatting to avoid bolded text.
=> doc: location lib: formatting fixes

doc/nrf/releases/release-notes-changelog.rst, lib/location/location_utils.c, lib/location/location_utils.h, lib/location/method_cellular.c, lib/location/method_wifi.c
Adding current current system time from point when scanning/ncellmeas was done to
location result datetime. System time is set e.g. by datetime lib.
Jira: MOSH-257
=> lib: location: wifi and cellular: systime to location_datetime

doc/nrf/releases/release-notes-changelog.rst, samples/bluetooth/central_smp_client/README.rst
Added notes explicitly specifying that this sample
is not intended as device programmer.
Jira: NCSDK-14095
Signed-off-by: Dominik Chat <dominik.chat@nordicsemi.no>
=> samples: Updating notes for central_smp_client readme

subsys/bluetooth/mesh/sensor_types.c, tests/subsys/bluetooth/mesh/sensor_subsys/src/main.c
The voltage sensor provides range from 0.0 to 1022.0 in
1/64V units. The actual range will be from 0 to 65408V.
Signed-off-by: Aleksandr Khromykh <Aleksandr.Khromykh@nordicsemi.no>
=> Bluetooth: Mesh: fix voltage sensor units

doc/nrf/known_issues.rst
=> known_issues: Add known issues for the SDC's periodic sync impl

doc/nrf/libraries/bin/lwm2m_carrier/API_documentation.rst, doc/nrf/libraries/bin/lwm2m_carrier/app_integration.rst, doc/nrf/libraries/bin/lwm2m_carrier/index.rst
To update the structure of LwM2M bin library
as per the library template. Also, minor updates
on the content.
Jira task: NCSDK-14428
=> doc: update LwM2M bin lib structure and content

samples/bluetooth/central_and_peripheral_hr/sample.yaml, samples/bluetooth/nrf_dm/sample.yaml, samples/crypto/aes_ctr/sample.yaml, samples/crypto/persistent_key_usage/sample.yaml, tests/subsys/zigbee/osif/crypto/testcase.yaml, tests/subsys/zigbee/osif/serial/serial_via_logger/testcase.yaml
Some names of the test cases are duplicated within the project.
This commit contains the proposed names of the test scenarios.
Signed-off-by: Katarzyna Giadla <katarzyna.giadla@nordicsemi.no>
=> samples: Change duplicated names of the test cases

doc/nrf/releases/release-notes-changelog.rst, samples/nrf9160/lwm2m_client/src/lwm2m/CMakeLists.txt, samples/nrf9160/lwm2m_client/src/lwm2m/include/lwm2m_client_app.h, samples/nrf9160/lwm2m_client/src/lwm2m/lwm2m_portfolio_object.c, samples/nrf9160/lwm2m_client/src/main.c
Added Portfolio object support for lwm2m_client sample.
This is enabler for LwM2M conformance test purpose.
=> samples: lwm2m_client: Portfolio Object support

subsys/bluetooth/controller/Kconfig, west.yml
=> Allow setting MPSL and SDC build type

.github/test-spec.yml
Added test spec entries for ESB and modified Gazell.
Signed-off-by: Magne Værnes <magne.varnes@nordicsemi.no>
=> test_spec: esb: add entries

subsys/net/lib/zzhc/zzhc.c
This commit adds support for China Telecom fixed DNS.
=> net: lib: zzhc: add fixed DNS support

tests/subsys/dfu/dfu_target/mcuboot/src/main.c
Added test-case for testing dfu_target_schedule_update along with
dfu_target_mcuboot backend.
Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>
=> tests/../dfu_target/mcuboot: tests for dfu_target_schedule_update

doc/nrf/known_issues.rst, doc/nrf/ug_thingy53.rst
* Updated list of Thingy:53 apps
* Updated KRKNWK-11602 known issue
=> Doc: zigbee minor fixes

west.yml
=> manifest: change HomeKit revision 

samples/zigbee/shell/README.rst, samples/zigbee/shell/src/main.c
Shell sample already supports factory reset shell command.
Signed-off-by: Adam Szczygieł <adam.szczygiel@nordicsemi.no>
=> Zigbee shell sample: Remove button factory reset

doc/nrf/app_power_opt.rst, doc/nrf/libraries/bluetooth_services/rpc.rst, doc/nrf/libraries/tfm/tfm_ioctl_api.rst, samples/peripheral/802154_phy_test/README.rst
=> doc: Fix config option linking

samples/peripheral/802154_phy_test/src/periph_proc.c
Obtain led0 information using gpio_dt_spec. Also make it mandatory since
all boards running this sample have a led0 alias. GPIO ports are now
obtained using DEVICE_DT_GET.
=> samples: peripheral: 802154_phy_test: use DEVICE_DT_GET/gpio_dt_spec

.github/test-spec.yml
Adding test spec entry for mesh
Signed-off-by: Alperen Sener <alperen.sener@nordicsemi.no>
=> test_spec: mesh: add entry

samples/crypto/psa_tls/sample.yaml
Add integration platform to tests in psa_tls sample.yaml test cases.
=> samples: psa_tls: Add integration platform to sample.yaml

doc/_static/css/kconfig.css
Make kconfig search more prominent
=> css: Make kconfig search more prominent

applications/asset_tracker_v2/src/cloud/cloud_codec/nrf_cloud/nrf_cloud_codec.c, applications/asset_tracker_v2/src/modules/cloud_module.c, applications/serial_lte_modem/src/gnss/slm_at_gnss.c, doc/nrf/releases/release-notes-changelog.rst, include/net/nrf_cloud.h, include/net/nrf_cloud_agps.h, include/net/nrf_cloud_cell_pos.h, include/net/nrf_cloud_pgps.h, include/net/nrf_cloud_rest.h, lib/multicell_location/services/nrf_cloud_integration.c, samples/nrf9160/modem_shell/src/cloud/cloud_shell.c, subsys/net/lib/nrf_cloud/include/nrf_cloud_codec.h, subsys/net/lib/nrf_cloud/src/nrf_cloud_agps.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_cell_pos.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_codec.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_fsm.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_rest.c
Handle new error messages for location service MQTT responses.
Also, handle error codes for REST responses.
NCSDK-13107
=> Handle nRF Cloud error codes for location services

samples/nrf9160/aws_iot/README.rst
The document was missing the Configuration section.
Added it and also did some other stylistic and formatting
changes. The Testing section requires further attention.
=> doc: nRF 9160 AWS IoT sample: added Configuration section

lib/date_time/date_time_core.c
Reschedule time update work if time is updated by any source.
Don't reschedule if time is not obtained
and the work is already pending.
Signed-off-by: Tero Nikula <tero.nikula@anicare.fi>
=> lib: date_time: Modify periodic time updates

west.yml
adding entries for CI_mesh to sdk-nrfxlib
Signed-off-by: Alperen Sener <alperen.sener@nordicsemi.no>
=> manifest: add test spec

samples/nrf9160/lwm2m_client/src/main.c
Verify modem firmware update right after initializing modem lib
Add to initialize PDN who depends on CONFIG_NRF_MODEM_LIB_SYS_INIT
=> samples: nrf9160: LwM2M client modem FOTA

lib/at_host/Kconfig, lib/modem_key_mgmt/Kconfig, subsys/dfu/dfu_target/Kconfig, subsys/net/lib/aws_iot/Kconfig, subsys/net/lib/azure_iot_hub/Kconfig, subsys/net/lib/nrf_cloud/Kconfig, subsys/net/lib/nrf_cloud/Kconfig.nrf_cloud_mqtt
Some Kconfig updates to simplify the menu.
=> some Kconfig updates

.github/test-spec.yml
Added test-spec for nrf5340_audio application
Signed-off-by: Frode van der Meeren frode.vandermeeren@nordicsemi.no
=> applications: nrf5340_audio: Test-spec for audio tests

.github/test-spec.yml
Adds a new label for the lwm2m client sample.
=> Add label and triggers for lwm2m client

doc/kconfig/index.rst, doc/kconfig/regex.rst
Add a section about Regex patterns and add useful
links.
=> doc: Add more information about search in Kconfig page

doc/nrf/known_issues.rst
ref DRGN-17014
Signed-off-by: Sean Madigan <Sean.Madigan@nordicsemi.no>
=> doc: Update known issues for HFCLK staying active

applications/serial_lte_modem/src/mqtt_c/slm_at_mqtt.c
Missing acknowledgement for QoS1 Publish.
JIRA-ticket: NCSIDB-738
=> application: serial_lte_modem: BUG-FIX add MQTT Pub QoS1 handling

west.yml
Selected OpenThread changes from upstream.
=> manifest: Zephyr upmerge with OpenThread changes

doc/nrf/ug_matter_configuring_protocol.rst
Added complete list of mandatory options for Matter.
KRKNWK-13614.
=> doc: matter: update mandatory config list

applications/nrf5340_audio/CMakeLists.txt
=> applications: nrf5340_audio: Update version number

doc/nrf/conf.py, doc/nrf/index.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/releases/release-notes-changelog.rst, doc/versions.json
update versions for 1.9.99-dev1 tag.
=> doc: update versions for 1.9.99-dev1 tag

doc/nrf/conf.py, doc/nrf/index.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/releases/release-notes-changelog.rst
PR based on PR 7347.
Will be rebased once 7347 is merged.
Commit to be reviewed:
b9529e35627d01b62de5ff7d577b32e128b3db07
=> Update versions after 1.9.99 dev1 tag

include/net/download_client.h, subsys/net/lib/download_client/Kconfig, subsys/net/lib/download_client/src/coap.c, subsys/net/lib/download_client/src/download_client.c, subsys/net/lib/download_client/src/http.c
Based on discussion in PR https://github.com/nrfconnect/sdk-nrf/pull/7167 I have implemented a different approach to implement CoAP backoff mechanism for the download client
=> Download client implement coap backoff

subsys/bluetooth/controller/hci_driver.c
Deprecate usage of master in favor of central and
deprecate slave in favor of peripheral.
=> bluetooth: controller: Update SDC public API with inclusive naming

samples/nrf9160/modem_shell/prj.conf
Increased shell RX buffer size to fix problems with test automation.
=> samples: nrf9160: modem_shell: increase shell RX buffer size

doc/nrf/releases/release-notes-changelog.rst, dts/bindings/caf/caf,aggregator.yaml, include/event_manager_proxy.h, samples/caf_sensor_manager/CMakeLists.txt, samples/caf_sensor_manager/Kconfig, samples/caf_sensor_manager/README.rst, samples/caf_sensor_manager/aci/CMakeLists.txt, samples/caf_sensor_manager/boards/nrf5340dk_nrf5340_cpuapp.conf, samples/caf_sensor_manager/configuration/common/event_proxy_init.c, samples/caf_sensor_manager/configuration/common/event_proxy_init.h, samples/caf_sensor_manager/remote/CMakeLists.txt, samples/caf_sensor_manager/remote/Kconfig, samples/caf_sensor_manager/remote/boards/nrf5340dk_nrf5340_cpunet.overlay, samples/caf_sensor_manager/remote/prj.conf, samples/caf_sensor_manager/remote/src/main.c, samples/caf_sensor_manager/sample.yaml, samples/caf_sensor_manager/src/modules/Kconfig, samples/caf_sensor_manager/src/modules/workload_sim.c, samples/caf_sensor_manager/zephyr/module.yml, subsys/caf/events/sensor_data_aggregator_event.c, subsys/caf/modules/sensor_data_aggregator.c
Update sensor manager sample to use multiple cores.
Jira: NCSDK-14554
=> CAF: sensor_manager: Add sensor manager sample for multiple cores

west.yml
=> manifest: Add reference link in nrfxlib

subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_security.c
Delete the default server object, that is created on every
time the engine starts. This overwrote our lifetime value when
Short server ID happened to match.
This bug was pointed to me by @jarlamsa 
Lifetime was stored permanently, but we did not react when
it was changed on runtime, so I added that code as well.
=> net: lib: lwm2m_client_utils: Fix storing of lifetime values

west.yml
Manifest update for nrfxlib's [PR#671](https://github.com/nrfconnect/sdk-nrfxlib/pull/671).
NCSDK-12310.
=> manifest: nrfxlib softdevice figure update

samples/nrf9160/lwm2m_client/scripts/atclient.py, samples/nrf9160/lwm2m_client/scripts/device.py
Add a command line interface to the ./device.py script.
Sometimes it might be usable in testing phase just to remove
or list some security tags.
=> samples: nrf9160: lwm2m_client: Make the ./device.py executable

applications/nrf5340_audio/src/bluetooth/ble_core.c, applications/nrf5340_audio/src/bluetooth/ble_hci_vsc.h
- Fetch device ID from FICR and set that as address
=> applications: nrf5340_audio: Set random static address

scripts/nrf_provision/fast_pair/fp_provision_cli.py, scripts/nrf_provision/fast_pair/requirements.txt
Change introduces Python script for Fast Pair provisioning data.
Jira: NCSDK-14204
=> scripts: fast_pair: Add Fast Pair provisioning script

samples/nrf9160/gnss/Kconfig, samples/nrf9160/gnss/src/main.c
Small improvements for the reference position support based on PR review comments which were submitted after PR #7505 was already merged.
=> samples: nrf9160: gnss: update reference position support

applications/serial_lte_modem/src/gnss/slm_at_gnss.c
Use float instead of integer for TTFF to make it more precise
Initialize date_time at when connecting nRF Cloud
Remove an unexpected cloud message during connecting
=> application: serial_lte_modem: GNSS service update

applications/serial_lte_modem/doc/SOCKET_AT_commands.rst, applications/serial_lte_modem/doc/slm_testing.rst, applications/serial_lte_modem/src/slm_at_socket.c
Customer expect to receive URC before data for buffer handling
=> application: serial_lte_modem: Socket service receive URC

doc/nrf/links.txt, doc/nrf/shortcuts.txt
Updated shortcuts and links for NCP Host and ZBOSS.
KRKNWK-14050.
=> doc: zigbee: update ncp host and zboss versions

doc/nrf/releases/release-notes-changelog.rst, samples/bluetooth/direct_test_mode/src/fem/Kconfig, samples/bluetooth/direct_test_mode/src/fem/nrf21540.c
This PR adds a possibility to build the Direct Test Mode sample with limited hardware pinout.
=> samples: DTM/Radio Test: nRF21540 front-end module limited pinout

subsys/mpsl/init/mpsl_init.c
Allows building mpsl_init for Babblesim
=> mpsl: Make mpsl_init more future proof

applications/serial_lte_modem/doc/GNSS_AT_commands.rst, applications/serial_lte_modem/doc/SOCKET_AT_commands.rst, applications/serial_lte_modem/doc/slm_testing.rst, applications/serial_lte_modem/prj.conf
Update the testing doc with error corrections
Update the GNSS doc with some notes
Use UUID as nRF Cloud device ID by default
Update the socket doc to be more precise on socket handle value
=> application: serial_lte_modem: Doc update

doc/nrf/gs_installing.rst, doc/nrf/gs_modifying.rst, doc/nrf/gs_updating.rst, doc/nrf/releases/release-notes-changelog.rst
Expanded Updating tools and repositories with TCM-related sections.
NCSDK-14128.
=> doc: gs: add sections to updating tools

applications/nrf5340_audio/README.rst
Fixed small error in legal text.
Signed-off-by: Anna Wojdylo <anna.wojdylo@nordicsemi.no>
=> doc: small legal doc fix

samples/bluetooth/nrf_dm/sample.yaml, subsys/dm/Kconfig, subsys/dm/dm.c, west.yml
This PR updates the sample and submodule dm to version 0.7 of the nrf_dm library.
=> Alignment to version 0.7.0 of nrf_dm library

samples/bluetooth/nrf_dm/README.rst
In the sample documentation, a link to the DM module and DDF service
documentation has been added.
Signed-off-by: Marcin Jeliński <marcin.jelinski@nordicsemi.no>
=> samples: bluetooth: nrf_dm: documentation improvement

doc/nrf/links.txt, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/ug_app_dev.rst, doc/nrf/ug_pinctrl.rst
Add documentation about Pin control
=> doc: Add documentation about Pin control

west.yml
This updates the NFC library revision with
newest bug fixes and features. The NFC library
changelog contains list of the all changes.
=> manifest: Update NFC library revision

west.yml
OpenThread upmerge and related changes.
=> manifest: Zephyr update with OpenThread changes

samples/nrf9160/modem_shell/src/sock/sock.c
Use PDN ID in getaddrinfo() when doing connect() on a specific PDN.
Signed-off-by: Stig Bjørlykke <stig.bjorlykke@nordicsemi.no>
=> samples: nrf9160: modem_shell: Use PDN ID in getaddrinfo

applications/zigbee_weather_station/src/main.c, doc/nrf/releases/release-notes-changelog.rst, subsys/zigbee/osif/zb_nrf_platform.c
- Fixes Zigbee weather station application by removing incorrect buffer freeing
- Optimize calling ZBOSS API in NCS platform by skipping unnecessary processing by workqueue
=> zigbee: Fixes Zigbee weather station application and optimize calling ZBOSS API in NCS [KRKNWK-14018]

subsys/bluetooth/controller/hci_internal.c
Rename white_list to filter_accept_list
=> bluetooth: controller: Use Core v5.3 naming convention

subsys/bluetooth/services/fast_pair/crypto/fp_crypto_common.c, subsys/bluetooth/services/fast_pair/crypto/fp_crypto_mbedtls.c, subsys/bluetooth/services/fast_pair/crypto/fp_crypto_tinycrypt.c, subsys/bluetooth/services/fast_pair/fp_advertising.c, subsys/bluetooth/services/fast_pair/fp_gatt_service.c, subsys/bluetooth/services/fast_pair/fp_keys.c, subsys/bluetooth/services/fast_pair/fp_registration_data.c, subsys/bluetooth/services/fast_pair/fp_storage.c, subsys/bluetooth/services/fast_pair/include/fp_crypto.h, subsys/bluetooth/services/fast_pair/include/fp_keys.h, subsys/bluetooth/services/fast_pair/include/fp_registration_data.h, subsys/bluetooth/services/fast_pair/include/fp_storage.h, tests/subsys/bluetooth/fast_pair/crypto/src/main.c
Change adds missing prefixes for defines and functions related to crypto and registration data.
Jira: NCSDK-15192
=> bluetooth: fast_pair: Align prefixes

applications/asset_tracker_v2/src/cloud/lwm2m_integration/lwm2m_integration.c
Add missing argument to prevent build error.
=> applications: asset_tracker_v2: Add missing argument

doc/nrf/includes/build_and_run_nrf9160.txt, doc/nrf/libraries/dfu/dfu_multi_image.rst, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/templates/sample_README.rst
Added a handful of trivial edits in changelog and templates.
NCSDK-NONE.
=> doc: minor doc fixes in changelog and templates

applications/serial_lte_modem/doc/GNSS_AT_commands.rst, applications/serial_lte_modem/src/gnss/slm_at_gnss.c
Add to support READ for GNSS support/active status in modem and SLM
GPS/AGPS/PGPS/CELLPOS status (started or not).
JIRA ticket: NCSIDB-750
=> application: serial_lte_modem: Support READ command for GNSS service

subsys/bluetooth/controller/hci_internal.c
Missed removing some old names before.
=> bluetooth: controller: Remove leftover white_list reference

subsys/zigbee/osif/zb_nrf_platform.c
In some cases, the prototype of the zb_osif_is_inside_isr() is not defined (it depends on the zb_trace.h file).
Change the order of functions, so the zb_osif_is_inside_isr() is defined before it is used.
=> zigbee: Fix order of functions

applications/machine_learning/src/modules/ei_data_forwarder_uart.c, applications/nrf_desktop/src/events/config_event.h, applications/nrf_desktop/src/hw_interface/battery_charger.c, applications/nrf_desktop/src/hw_interface/motion_sensor.c, applications/nrf_desktop/src/hw_interface/selector_hw.c, applications/nrf_desktop/src/modules/ble_bond.c, applications/nrf_desktop/src/modules/ble_latency.c, applications/nrf_desktop/src/modules/ble_qos.c, applications/nrf_desktop/src/modules/dfu.c, applications/nrf_desktop/src/modules/hid_forward.c, applications/nrf_desktop/src/modules/info.c, applications/nrf_desktop/src/modules/usb_state.c, samples/edge_impulse/data_forwarder/src/main.c, subsys/caf/events/power_manager_event.c, subsys/caf/modules/ble_adv.c, subsys/caf/modules/leds.c, subsys/caf/modules/power_manager.c, subsys/caf/modules/sensor_manager.c, subsys/event_manager_proxy/event_manager_proxy.c, tests/subsys/app_event_manager/src/modules/test_multicontext.c, tests/subsys/app_event_manager/src/modules/test_subs.c
Remove bugs related to parsing, leftovers and uninitialize variables in
nrf_desktop, machine learning and caf.
Jira: NCSDK-15246
=> applications: caf: Remove parsing bugs

include/tfm/tfm_ioctl_api.h
Add API documentation for platform secure services:
- tfm_platform_firmware_info
- tfm_platform_s0_active
=> tfm: Add API documentation for platform secure services

subsys/zigbee/lib/zigbee_fota/src/zigbee_fota.c
Despite the name (`ZB_ZCL_OTA_UPGRADE_STATUS_APPLY`) this signal should not schedule the update, but just check for the image completeness.
The upgrade should be scheduled only inside `ZB_ZCL_OTA_UPGRADE_STATUS_FINISH`, which is scheduled inside the postponed upgrade scenarios.
=> zigbee: Fix incorrect FOTA upgrade schedule calls

doc/nrf/links.txt, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/ug_nrf5340.rst
Added XIP configuration section to the Working with nRF5340 DK guide.
NRFX-1830.
=> doc: xip: add section to nRF5340DK UG

applications/matter_weather_station/README.rst, doc/matter/conf.py, doc/matter/index.rst, doc/nrf/gs_installing.rst, doc/nrf/known_issues.rst, doc/nrf/ug_matter.rst, doc/nrf/ug_matter_architecture.rst, doc/nrf/ug_matter_configuring.rst, doc/nrf/ug_matter_configuring_controller.rst, doc/nrf/ug_matter_configuring_env.rst, doc/nrf/ug_matter_configuring_protocol.rst, doc/nrf/ug_matter_creating_accessory.rst, doc/nrf/ug_thread_tools.rst, samples/matter/light_bulb/README.rst, samples/matter/light_switch/README.rst, samples/matter/lock/README.rst, samples/matter/template/README.rst, samples/matter/window_covering/README.rst
- doc: matter: update mentions of Matter controller
- doc: matter: remove mentions of Project CHIP
=> doc improvement: matter: update mentions of Matter controller and remove "Project CHIP"

doc/nrf/releases/release-notes-changelog.rst, west.yml
Updated revision of nrfxlib repository to include changes in nrfxlib/zboss (removed support for expoerimental GPCB functionality)
=> manifest: Update revision of nrfxlib repository

doc/nrf/ug_nrf_cloud.rst
Change first list to unordered.
Add some additional samples to list of related ones.
=> doc: nRF Cloud user guide improvements

applications/nrf_desktop/README.rst, doc/nrf/releases/release-notes-changelog.rst
This commit documents how to enable nRF21540EK RF FEM support
in nrf_desktop application.
=> applications: nrf_desktop: Document nRF21540EK support

west.yml
Change update Zephyr revision to bring fix for the SMP issue.
Jira: NCSDK-15176
=> west.yml: Update Zephyr revision to fix SMP issue

doc/nrf/ug_thingy91.rst, doc/nrf/ug_zigbee_qsg.rst
Changed Creating application from template to Adding application.
NCSDK-15338.
=> doc: vsc: rework adding application instructions

applications/nrf_desktop/README.rst, applications/nrf_desktop/doc/ble_conn_params.rst, applications/nrf_desktop/doc/ble_scan.rst
Document reducing BLE connection interval on USB suspend.
Jira: NCSDK-15439
=> applications: nrf_desktop: Document NCSDK-14913

doc/nrf/ug_nrf_cloud.rst
A missing line made the formatting go wrong. Fixed now.
=> doc improvement: Fixing formatting in Cloud user guide

doc/nrf/index.rst
Doc update to the index page for the new layout
=> doc: Doc updates related to the new layout

applications/nrf5340_audio/README.rst, doc/nrf/app_boards.rst, doc/nrf/libraries/modem/modem_jwt.rst, doc/nrf/libraries/networking/aws_iot.rst, doc/nrf/libraries/networking/download_client.rst, doc/nrf/libraries/networking/lwm2m_client_utils.rst, doc/nrf/libraries/networking/nrf_cloud_rest.rst, doc/nrf/libraries/others/dm.rst, doc/nrf/libraries/others/spm.rst, doc/nrf/libraries/others/wave_gen.rst, doc/nrf/samples/samples_matter.rst, doc/nrf/shortcuts.txt, doc/nrf/ug_multi_image.rst, doc/nrf/ug_nrf53.rst, doc/nrf/ug_nrf5340.rst, doc/nrf/ug_nrf_cloud.rst, samples/nrf9160/aws_fota/README.rst
Edited some libraries to fix structural issues.
Fixed inconsistencies with template.
NCSDK-12980.
=> doc: fix structure issues in some libs + minor doc fixes

applications/nrf5340_audio/README.rst
Added new legal contents requested by product managers.
=> doc: nrf5340audio: edit legal section

applications/nrf5340_audio/README.rst
Added a line related to power adapter.
Late request from Niko Balabanis.
=> doc: nrf5340audio: power adapter line

doc/nrf/ug_pinctrl.rst
=> doc: minor fix in pincontrol ug

doc/nrf/gs_programming.rst, doc/nrf/ug_nrf5340.rst
Fixed an issue caused by missing include reference.
Fixed a list formatting issue.
=> doc: fix minor doc formatting issues

doc/nrf/conf.py, doc/nrf/index.rst, doc/nrf/known_issues.rst, doc/nrf/release_notes.rst, doc/nrf/releases/release-notes-changelog.rst, doc/nrfxlib/conf.py, doc/versions.json
Post-release version updates to docs.
=> doc: post 2.0.0 release doc update

subsys/bluetooth/mesh/scene_srv.c
Alter scene_register_status and scene_status_send call to use the
correct server instance. This allows the Scene setup srv to respond
to a message from the client without a dependency on the Scene srv
being bound to the same appkey.
Signed-off-by: Anders Storrø <anders.storro@nordicsemi.no>
=> Bluetooth: Mesh: Scene Srv status msg update

samples/bluetooth/mesh/ble_peripheral_lbs_coex/src/lb_service_handler.c, samples/bluetooth/mesh/chat/src/chat_cli.c, samples/bluetooth/mesh/light_ctrl/src/lc_pwm_led.c, samples/bluetooth/mesh/silvair_enocean/src/main.c, subsys/bluetooth/mesh/gen_prop_cli.c, subsys/bluetooth/mesh/gen_prop_srv.c, subsys/bluetooth/mesh/light_ctrl_srv.c, subsys/bluetooth/mesh/scheduler_srv.c, subsys/bluetooth/mesh/sensor.c, subsys/bluetooth/mesh/sensor_cli.c, subsys/bluetooth/mesh/sensor_srv.c, subsys/bluetooth/mesh/time_srv.c, subsys/bluetooth/mesh/time_util.c
Fixed issues reported by Coverity.
=> Bluetooth: Mesh: Fix issues reported by Coverity

applications/nrf_desktop/README.rst, applications/nrf_desktop/configuration/common/hid_report_desc.h, applications/nrf_desktop/configuration/common/led_state.h, applications/nrf_desktop/src/events/usb_event.h
Ensure that API documented with doxygen is visible in rst files.
Add missing documentation.
Jira: NCSDK-14306
=> applications: nrf_desktop: Link doxygen API to rst

west.yml
=> west.yml: Update Zephyr to bring in fixes for arm_thread_swap_tz test

doc/nrf/known_issues.rst
Update known issues section for Asset Tracker v2.
=> doc: nrf: Update known issues section for Asset Tracker v2

applications/nrf5340_audio/README.rst, doc/nrf/releases/release-notes-changelog.rst
Added mention of --recover to the buildprog section.
OCT-2129.
=> doc: nrf5340audio: add recover to buildprog

scripts/ncs-toolchain-version-minimum.txt
Update required toolchain version post release v2.0.0.
This file was not updated before the v2.0.0, so updating it now to
ensure main is up-to-date.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
=> scripts: Update required toolchain version to 2.0.0

doc/nrf/libraries/modem/nrf_modem_lib.rst
Minor style updates on Modem library integration layer>
Library wrapper.
=> doc improvement: Minor style updates on Library wrapper

doc/nrf/ug_bootloader_adding.rst
=> doc: Typo fix

doc/nrf/libraries/others/flash_patch.rst, doc/nrf/links.txt, doc/nrf/releases/release-notes-changelog.rst
Add documentation for the flash patch library.
=> doc: Add flash patch library documentation

doc/nrf/releases/release-notes-changelog.rst, subsys/bluetooth/services/fast_pair/fp_storage.c, subsys/bluetooth/services/fast_pair/include/fp_storage.h, tests/subsys/bluetooth/fast_pair/storage/CMakeLists.txt, tests/subsys/bluetooth/fast_pair/storage/Kconfig, tests/subsys/bluetooth/fast_pair/storage/include/storage_mock.h, tests/subsys/bluetooth/fast_pair/storage/prj.conf, tests/subsys/bluetooth/fast_pair/storage/src/main.c, tests/subsys/bluetooth/fast_pair/storage/src/settings_mock.c, tests/subsys/bluetooth/fast_pair/storage/testcase.yaml
Change introduces Fast Pair storage unit tests.
Jira: NCSDK-14857
=> tests: fast_pair: Introduce storage unit tests

include/net/multicell_location.h
More precision for latitude and longitude printing, to get same coordinates into the device that are shown in nRF cloud.
We can discuss whether all samples and some logging related to latitude and longitude are also changed as done initially in this PR.
Jira: NCSDK-15245
=> samples: nrf9160: modem_shell: More precision for position printing

doc/nrf/known_issues.rst
Change adds NCSDK-15675 to known issues.
Jira: NCSDK-15675
=> doc: known_issues: Add NCSDK-15675

subsys/bluetooth/services/fast_pair/fp_storage.c
Remember an error code in the settings set handler and return it in settings commit handler to propagate it further. Error codes returned by the settings set handler are not propagated further.
Jira: NCSDK-15693
=> bluetooth: fast_pair: Propagate settings set error in fp_storage

doc/nrf/releases/release-notes-changelog.rst
Fixes for the changelog
To be merged after https://github.com/nrfconnect/sdk-nrf/pull/7905 
=> doc: Fixes for the changelog

doc/nrf/gs_testing.rst, doc/nrf/includes/build_and_run.txt, doc/nrf/includes/build_and_run_nrf9160.txt, doc/nrf/includes/build_and_run_ns.txt, doc/nrf/includes/config_build_and_run.txt, doc/nrf/links.txt, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/ug_nrf5340.rst, samples/bluetooth/direct_test_mode/README.rst, samples/bluetooth/peripheral_uart/README.rst
Add a section about debugging to Testing an app page.
NCSDK-15709.
=> doc: gs: add debugging section to Testing an app

applications/nrf5340_audio/README.rst, applications/nrf5340_audio/tools/buildprog/buildprog.py, applications/nrf5340_audio/tools/buildprog/nrf5340_audio_dk_devices.py, applications/nrf5340_audio/tools/buildprog/program.py
Update buildscript such that it can be ran from any path. In addition,
the code has been simplified for better overview. This last part is subjective of course, but just let me know what you think!
Signed-off-by: Erik van Raalte <erik.van.raalte@nordicsemi.no>
=> applications: nrf5340_audio: Update build script

west.yml
This PR updates nRF RPC library revision.
=> nrf_rpc: Add protocol versioning

doc/nrf/gs_installing.rst
Added 2 lines in gs_installing.rst
Related to Jira NCSDK 11540.
Signed-off-by: Anna Wojdylo <anna.wojdylo@nordicsemi.no>
=> doc: linux west installation update

include/bluetooth/services/fast_pair.h, samples/bluetooth/peripheral_fast_pair/include/bt_adv_helper.h, samples/bluetooth/peripheral_fast_pair/src/bt_adv_helper.c, samples/bluetooth/peripheral_fast_pair/src/main.c, subsys/bluetooth/services/fast_pair/fp_advertising.c
Introduces API to toggle show/hide UI indication advertising option in runtime and demonstrates its usage in sample.
Jira: NCSDK-14839
This PR was earlier present here: https://github.com/MarekPieta/fw-nrfconnect-nrf/pull/13. Review comments have been addressed. Please rereview.
=> Fast Pair: Allow toggling show/hide UI indication in runtime

doc/nrf/releases/release-notes-changelog.rst, samples/bluetooth/peripheral_fast_pair/README.rst
Updates release notes and Fast Pair documentation.
Jira: NCSDK-14839
=> doc: fast_pair: Allow hiding UI indication

doc/nrf/releases/release-notes-changelog.rst, scripts/requirements-build.txt, scripts/requirements-extra.txt, scripts/requirements-fixed.txt, subsys/dfu/fmfu_fdev/include/modem_update_decode.h, subsys/dfu/fmfu_fdev/include/modem_update_types.h, subsys/dfu/fmfu_fdev/src/modem_update_decode.c, tests/modules/lib/zcbor/cddl/test.cddl, tests/modules/lib/zcbor/decode/src/main.c, tests/modules/lib/zcbor/encode/src/main.c, west.yml
Update zcbor from 0.4.0 to 0.5.1.
=> Zcbor 0.5.1

doc/nrf/releases/release-notes-changelog.rst, include/net/nrf_cloud.h, samples/nrf9160/nrf_cloud_mqtt_multi_service/prj.conf, samples/nrf9160/nrf_cloud_mqtt_multi_service/src/connection.c
Various minor improvements to logging and function organization
in the connection management thread.
Most importantly, the nRF Cloud lib is no longer de-initialized and
re-initialized on every disconnection.
IRIS-4406
Signed-off-by: Georges Oates_Larsen <georges.larsen@nordicsemi.no>
=> samples: mmss: connection process improvements

applications/nrf5340_audio/src/modules/led.c
Use gpio-dt-spec facilities to simplify code in the module. Note that
module should be refactored to make better use of Devicetree (it relies
on device labels to make some decisions, something that needs to be
fixed).
=> applications: nrf5340_audio: use gpio-dt-spec

doc/nrf/known_issues.rst
Change adds NCSDK-16060 to known issues.
Jira: NCSDK-16060
=> doc: known_issues: Add NCSDK-16060

doc/nrf/libraries/bluetooth_services/mesh/gen_plvl_srv.rst, doc/nrf/libraries/bluetooth_services/mesh/light_hue_srv.rst, doc/nrf/libraries/bluetooth_services/mesh/light_sat_srv.rst, doc/nrf/libraries/bluetooth_services/mesh/light_temp_srv.rst, doc/nrf/libraries/bluetooth_services/mesh/light_xyl_srv.rst, doc/nrf/libraries/bluetooth_services/mesh/lightness_srv.rst, doc/nrf/releases/release-notes-changelog.rst, include/bluetooth/mesh/gen_plvl_srv.h, include/bluetooth/mesh/light_hue_srv.h, include/bluetooth/mesh/light_sat_srv.h, include/bluetooth/mesh/light_temp_srv.h, include/bluetooth/mesh/light_xyl_srv.h, include/bluetooth/mesh/lightness_srv.h, subsys/bluetooth/mesh/gen_plvl_srv.c, subsys/bluetooth/mesh/light_ctl_srv.c, subsys/bluetooth/mesh/light_ctrl_srv.c, subsys/bluetooth/mesh/light_hsl_srv.c, subsys/bluetooth/mesh/light_hue_srv.c, subsys/bluetooth/mesh/light_sat_srv.c, subsys/bluetooth/mesh/light_temp_srv.c, subsys/bluetooth/mesh/light_xyl_srv.c, subsys/bluetooth/mesh/lightness_internal.h, subsys/bluetooth/mesh/lightness_srv.c, subsys/bluetooth/mesh/model_utils.h, tests/subsys/bluetooth/mesh/models/src/main.c, tests/subsys/bluetooth/mesh/models/testcase.yaml
Adding support for emds to a set of mesh model servers.
=> Bluetooth: Mesh: Added emds support to mesh models

applications/machine_learning/README.rst, applications/machine_learning/src/events/ei_data_forwarder_event.h, applications/machine_learning/src/events/ml_app_mode_event.h, applications/machine_learning/src/events/ml_result_event.h, applications/machine_learning/src/events/sensor_sim_event.h
=> applications: machine_learning: Cleanup event API references

applications/serial_lte_modem/doc/DFU_AT_commands.rst, applications/serial_lte_modem/doc/FOTA_AT_commands.rst, applications/serial_lte_modem/doc/GPIO_AT_commands.rst, applications/serial_lte_modem/doc/HTTPC_AT_commands.rst, applications/serial_lte_modem/doc/MQTT_AT_commands.rst, applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
Fixed small doc issues in Serial LTE modem docs.
=> doc: SLM small doc fix

doc/nrf/conf.py, doc/nrf/dm_adding_code.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/release_notes.rst, doc/nrf/releases/release-notes-2.0.1.rst, doc/nrf/shortcuts.txt, doc/nrfxlib/conf.py, doc/versions.json
Updated structure and release notes.
=> doc: update docs and versions for NCS 2.0.1

subsys/bluetooth/services/fast_pair/fp_keys.c
Change makes key generation failure counter global and removes counter reset on disconnection. This is done to prevent brute-force attacks.
Jira: NCSDK-15664
=> bluetooth: fast_pair: Make key generation failure counter global

applications/asset_tracker_v2/overlay-lwm2m.conf, applications/asset_tracker_v2/src/cloud/cloud_codec/Kconfig, applications/asset_tracker_v2/src/cloud/cloud_codec/lwm2m/lwm2m_codec.c
Minimize calls to `object_path_list_add()` by updating its input values
to accept a list of paths instead of individual paths.
Fixes CIA-715
=> applications: asset_tracker_v2: LwM2M codec cleanup

doc/nrf/dm_adding_code.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/release_notes.rst, doc/nrf/releases/release-notes-1.9.2.rst, doc/nrf/shortcuts.txt, doc/nrfxlib/conf.py, doc/versions.json
Added versions in the docs and release notes file for NCS 1.9.2.
=> doc: update documentation for NCS 1.9.2

doc/nrf/releases/release-notes-1.9.2.rst
=> doc: update docs to fix deployment

lib/modem_info/modem_info_json.c
This patch fixes a potential bug where the return value
of cJSON_AddItemToObject was ignored and cJSON objects
were not free'd.
Signed-off-by: Maximilian Deubel <maximilian.deubel@nordicsemi.no>
=> modem_info: json_add_obj check for memory error

doc/nrf/releases/release-notes-changelog.rst, west.yml
Update SDC and MPSL in nrfxlib.
=> manifest: update SDC and MPSL

west.yml
Update the zephyr module revision to pull in several bug fixes
related to pinctrl and updated PWM API.
=> [backport-v2.0] manifest: Update Zephyr revision

modules/trusted-firmware-m/Kconfig, west.yml
* Point to zephyr revision with an update to TFM samples
* Make sure the above builds by adding a necessary config when needed
=> manifest: Update zephyr-sdk for TFM sample changes

applications/nrf5340_audio/README.rst, doc/nrf/releases/release-notes-changelog.rst
Edited legal section based on request from Pierre.
OCT-2164.
=> doc: nrf5340audio: update legal section

west.yml
Updates SDC and MPSL
Signed-off-by: Olivier Lesage <olivier.lesage@nordicsemi.no>
=> manifest: update nrfxlib version

applications/serial_lte_modem/src/gpio/slm_at_gpio.c, applications/serial_lte_modem/src/main.c, applications/serial_lte_modem/src/twi/slm_at_twi.c
Obtain I2C devices at compile time using DEVICE_DT_GET.
=> applications: serial_lte_modem: use DEVICE_DT_GET

applications/serial_lte_modem/src/slm_at_host.c
Obtain UART devices at compile time using DEVICE_DT_GET.
Signed-off-by: Gerard Marull-Paretas <gerard.marull@nordicsemi.no>
=> applications: serial_lte_modem: at_host: use DEVICE_DT_GET

applications/nrf5340_audio/README.rst, doc/nrf/known_issues.rst
Added a HW limitation to the app readme.
Added a SW known issue to known issues.
OCT-2165.
OCT-2154.
=> doc: nrf5340audio: add limitation and known issue

doc/nrf/links.txt, doc/nrf/ug_thread_configuring.rst, doc/nrf/ug_thread_supported_features.rst
Make Thread 1.3.0 support clear.
=> doc: document transition to default Thread 1.3

doc/tfm/conf.py
TF-M has been recently upgraded to 1.6.0, which also included some
documentation layout changes. This patch updates tfm docset settings to
match with latest version changes.
Signed-off-by: Gerard Marull-Paretas <gerard.marull@nordicsemi.no>
=> doc: tfm: upgrade configuration for 1.6.0

west.yml
=> manifest: Update memfault to 0.31.5

applications/nrf5340_audio/src/audio/audio_datapath.c, applications/nrf5340_audio/src/audio/audio_datapath.h, applications/nrf5340_audio/src/bluetooth/Kconfig.defaults, applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
- Fixed bug in BIS for setting bitrate
- Added missing CONFIGs for BIS
- Set default pres delay for BIS to 10ms
=> applications: nrf5340_audio: Add missing configs for BIS

doc/nrf/libraries/bluetooth_services/mesh/sensor.rst, include/bluetooth/mesh/sensor.h, include/bluetooth/mesh/sensor_cli.h, include/bluetooth/mesh/sensor_types.h, samples/bluetooth/mesh/sensor_server/src/model_handler.c, subsys/bluetooth/mesh/sensor.c, subsys/bluetooth/mesh/sensor.h, subsys/bluetooth/mesh/sensor_cli.c, subsys/bluetooth/mesh/sensor_srv.c, subsys/bluetooth/mesh/sensor_types.c
This aligns sensor and column reporting for sensors with any number of
channels.
Signed-off-by: Ludvig Samuelsen Jordet <ludvig.jordet@nordicsemi.no>
test-sdk-nrf: sdk-nrf-PR-7676
=> bluetooth: mesh: align sensor/column reporting

samples/nrf9160/lwm2m_client/overlay-queue.conf
Updated Lifetrime to 12 hour and trigger update process
every 10minutes.
Enable PSM and eDRX.
PSM TAU to 10min and RAT to 30 seconds.
eDRX Cycle request to 10.24s and Paging time request 1.28s.
Signed-off-by: Juha Heiskanen <juha.heiskanen@nordicsemi.no>
=> samples: lwm2m_client: Power saving enable to queue mode

doc/nrf/links.txt, doc/nrf/scripts.rst, samples/bluetooth/peripheral_mds/README.rst, scripts/memfault/README.rst, scripts/memfault/mds_ble_gateway.py, scripts/memfault/requirements.txt
This adds the MDS BLE gateway script which can be used for testing the Peripheral MDS sample.
The script can connect to device with MDS service and forwards its diagnostic data to the Memfault cloud.
Please review only two last commits
=> scripts: Add MDS BLE gateway script

applications/asset_tracker_v2/doc/asset_tracker_v2_description.rst
This updates the expected log strings to use the strings which are printed by the current implementation.
=> doc: asset_tracker_v2: update event log strings

doc/nrf/links.txt, doc/nrf/releases/release-notes-changelog.rst, samples/nrf9160/nrf_cloud_mqtt_multi_service/CMakeLists.txt, samples/nrf9160/nrf_cloud_mqtt_multi_service/Kconfig, samples/nrf9160/nrf_cloud_mqtt_multi_service/README.rst, samples/nrf9160/nrf_cloud_mqtt_multi_service/prj.conf, samples/nrf9160/nrf_cloud_mqtt_multi_service/src/application.c, samples/nrf9160/nrf_cloud_mqtt_multi_service/src/application.h, samples/nrf9160/nrf_cloud_mqtt_multi_service/src/connection.c, samples/nrf9160/nrf_cloud_mqtt_multi_service/src/connection.h, samples/nrf9160/nrf_cloud_mqtt_multi_service/src/led_control.c, samples/nrf9160/nrf_cloud_mqtt_multi_service/src/led_control.h, samples/nrf9160/nrf_cloud_mqtt_multi_service/src/main.c
Added LED status indication to the MQTT Multi Service Sample
Signed-off-by: Georges Oates_Larsen <georges.larsen@nordicsemi.no>
=> samples: nrf9160: MMSS: Add LED indication

applications/nrf_desktop/doc/battery_charger.rst, doc/nrf/libraries/modem/pdn.rst, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/ug_zigbee_commissioning.rst, west.yml
Minor document fixes on the following
documents:
battery_charger.rst
pdn.rst
release-notes-changelog.rst
ug_zigbee_commissioning.rst
=> doc: Minor document fixes

doc/_static/js/ga-tracker.js, doc/_utils/utils.py
Update Google Analytics code (GA4).
Fixes NCSDK-14461
=> doc: update google analytics code

lib/location/location.c, lib/location/location_core.c, tests/lib/location/src/location_test.c
Add more unit tests for Location library.
Some minor changes into the code as well.
=> tests: lib: location: Add 2nd set of unit tests

doc/nrf/known_issues.rst, doc/nrf/releases/release-notes-changelog.rst, samples/peripheral/radio_test/boards/nrf5340dk_nrf5340_cpunet.overlay
Align the Radio Test sample configuration with
pinctrl.
=> samples: radio_test: Align with pinctrl

lib/nrf_modem_lib/nrf91_sockets.c
This commit fixes a bug introduced by a previous
commit that was setting the return value of
`getaddrinfo` to 0 even in case of error.
Also removed some error checks in `getaddrinfo`
that were not needed anymore.
Also renamed the `error` variable to `err` to
prevent confusing it with the `error` label
for `goto`.
=> lib: nrf_modem: nrf91_sockets: hotfix and cleanup

doc/nrf/releases/release-notes-changelog.rst, samples/openthread/cli/README.rst
Show the basic usage of SRP commands.
Fix some output changes from existing commands.
KRKNWK-13754
=> doc: extend Thread CLI sample with SRP information

applications/nrf5340_audio/src/audio/streamctrl.c, applications/nrf5340_audio/src/bluetooth/Kconfig, applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c, applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c, applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c, applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
- Change a lot of LOG_INF to LOG_DBG
- Set log level for ble_audio_services to 3
=> applications: nrf5340_audio: Remove unnecessary logging

doc/nrf/libraries/bluetooth_services/services/ddfs.rst, include/bluetooth/services/ddfs.h, include/bluetooth/services/rscs.h, samples/bluetooth/nrf_dm/README.rst, samples/bluetooth/nrf_dm/src/main.c, samples/bluetooth/nrf_dm/src/service.c, samples/bluetooth/peripheral_rscs/src/main.c, subsys/bluetooth/services/ddfs.c, subsys/bluetooth/services/rscs.c
Fix typos in source code and documentation. This also improves the services and samples logic.
=> Bluetooth: Clean up RSCS and DDFS services and samples

applications/nrf5340_audio/tools/buildprog/program.py
Fixed such that:
- When only programming gateway or headset, the other doesnt reset.
- Failed is no longer printed when recovering board is recovered using -f parameter
- Failed is now printing when board is turned of mid-programming
- Failed recover will now print Failed 
Signed-off-by: Khuong Huynh <khuong.huynh@nordicsemi.no>
=> applications: nrf5340_audio: Bugfix Buildprog

CODEOWNERS, include/bluetooth/bt_le_adv_prov.h, subsys/bluetooth/CMakeLists.txt, subsys/bluetooth/Kconfig, subsys/bluetooth/bt_le_adv_prov/CMakeLists.txt, subsys/bluetooth/bt_le_adv_prov/Kconfig, subsys/bluetooth/bt_le_adv_prov/core.c, subsys/bluetooth/bt_le_adv_prov/core.ld, subsys/bluetooth/bt_le_adv_prov/providers/CMakeLists.txt, subsys/bluetooth/bt_le_adv_prov/providers/Kconfig, subsys/bluetooth/bt_le_adv_prov/providers/Kconfig.flags, subsys/bluetooth/bt_le_adv_prov/providers/Kconfig.gap_appearance, subsys/bluetooth/bt_le_adv_prov/providers/Kconfig.swift_pair, subsys/bluetooth/bt_le_adv_prov/providers/Kconfig.tx_power, subsys/bluetooth/bt_le_adv_prov/providers/flags.c, subsys/bluetooth/bt_le_adv_prov/providers/gap_appearance.c, subsys/bluetooth/bt_le_adv_prov/providers/swift_pair.c, subsys/bluetooth/bt_le_adv_prov/providers/tx_power.c
Change introduces Bluetooth LE adv providers subsystem and a set of advertising data providers.
=> bluetooth: bt_le_adv_prov: Introduce Bluetooth LE adv providers

subsys/pcd/src/pcd.c
When the PCD finishes, the network core should be configured back into
non-secure. As this is the default behavior on system resets.
This will ensure that the application does not accidentally enter into
non-secure with the network core configured to be secure.
=> dfu: pcd: Configure network core to non-secure when done

include/fprotect.h, lib/fprotect/Kconfig, lib/fprotect/fprotect_acl.c, lib/hw_unique_key/Kconfig
Simplify FPROTECT configuration and align with best practices.
=> FPROTECT cleanup

applications/nrf_desktop/README.rst, doc/nrf/links.txt
Change adds information about Swift Pair support to application's documentation.
Jira: NCSDK-15055
=> applications: nrf_desktop: Inform about Swift Pair in doc

doc/nrf/releases/release-notes-changelog.rst, samples/wifi/shell/README.rst
Update release notes with Wi-Fi protocol, sample and documentation
additions.
=> docs: wifi: Update release notes

lib/lte_link_control/lte_lc.c
While looking through the link controller code for writing tests,
I encountered some bugs that should be fixed with these changes.
=> Fix bugs found while writing tests for the lte link controller

applications/asset_tracker_v2/sample.yaml
Add more build configurations for lwm2m.
=> applications: asset_tracker_v2: Add more build configurations for lwm2m

doc/nrf/libraries/bluetooth_services/bt_le_adv_prov.rst, doc/nrf/releases/release-notes-changelog.rst, include/bluetooth/bt_le_adv_prov.h
Change introduces documentation of Bluetooth LE advertising providers subsystem.
Jira: NCSDK-16344
=> bluetooth: bt_le_adv_prov: Introduce documentation

doc/nrf/glossary.rst
In other PRs, bumped to a handful of new abbreviations
that deserve an entry in the glossary.
=> doc improvement: adding new terms to the glossary

doc/nrf/ug_fw_update.rst
=> doc: Minor fix

doc/nrf/links.txt, samples/nrf9160/modem_shell/README.rst
Added documentation for some features that have been missed earlier.
Also added comments to answer some of the questions we've seen.
=> samples: nrf9160: modem_shell: Document improvements

applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c, applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c, west.yml
- Disable and enable stream if on gateway
- Change available context type if on headset
=> applications: nrf5340_audio: Implement play/pause for CIS

applications/asset_tracker_v2/tests/lwm2m_integration/CMakeLists.txt, applications/asset_tracker_v2/tests/lwm2m_integration/Kconfig, applications/asset_tracker_v2/tests/lwm2m_integration/prj.conf, applications/asset_tracker_v2/tests/lwm2m_integration/src/lwm2m_integration_test.c, applications/asset_tracker_v2/tests/lwm2m_integration/testcase.yaml
Add test for lwm2m integration layer.
=> applications: asset_tracker_v2: tests: Add test for lwm2m integration

applications/asset_tracker_v2/src/cloud/cloud_codec/lwm2m/lwm2m_codec.c, applications/asset_tracker_v2/src/cloud/cloud_codec/lwm2m/lwm2m_codec_defines.h, applications/asset_tracker_v2/tests/lwm2m_codec/CMakeLists.txt, applications/asset_tracker_v2/tests/lwm2m_codec/Kconfig, applications/asset_tracker_v2/tests/lwm2m_codec/prj.conf, applications/asset_tracker_v2/tests/lwm2m_codec/src/lwm2m_codec_test.c, applications/asset_tracker_v2/tests/lwm2m_codec/testcase.yaml
Add test for lwm2m codec
CIA-667
=> applications: asset_tracker_v2: tests: Add test for lwm2m codec

samples/bluetooth/peripheral_fast_pair/README.rst
Change reduces size of discoverable advertising notification image.
=> samples: peripheral_fast_pair: Reduce image size

doc/_scripts/software_maturity/software_maturity_scanner.py
Added the possibility to negate a symbol in a rule with '!'.
Signed-off-by: Gaute Svanes Lunde <gaute.lunde@nordicsemi.no>
=> doc: sml: added symbol negation

applications/nrf5340_audio/README.rst
- Document how to clear bonding information
=> applications: nrf5340_audio: Update doc regarding bonding

doc/nrf/libraries/networking/azure_iot_hub.rst, doc/nrf/links.txt
Add link that documents how `Azure SDK for C` is integrated in NCS
=> doc: Add link that documents how `Azure SDK for C` is integrated in NCS

west.yml
Update memfault-firmware-sdk to revision 0.33.0
=> manifest: update memfault to 0.33.0

applications/nrf5340_audio/README.rst
How to test DFU using the nRF Connect Device Manager app
=> applications: nrf5340_audio: Add DFU testing to doc

doc/nrf/drivers/sensor_stub.rst, doc/nrf/releases/release-notes-changelog.rst, samples/caf_sensor_manager/README.rst
This PR updates the doc review comments for
the PR https://github.com/nrfconnect/sdk-nrf/pull/8236.
=> doc: updates on the Senser stub driver

doc/nrf/app_build_system.rst, doc/nrf/ug_thingy91.rst
Added TF-M output files to the output file table.
NCSIDB-718.
=> doc: app_dev: expand list of output files

applications/nrf5340_audio/README.rst
Change MCUBoot key and create own DFU app
=> applications: nrf5340_audio: Add DFU to adapting for end prod doc

doc/nrf/releases/release-notes-changelog.rst, doc/nrf/ug_radio_fem.rst, subsys/mpsl/fem/CMakeLists.txt, subsys/mpsl/fem/Kconfig, subsys/mpsl/fem/common/include/mpsl_fem_power_model_interface.h, subsys/mpsl/fem/nrf21540_gpio/mpsl_fem_nrf21540_gpio.c, subsys/mpsl/fem/nrf21540_gpio_spi/CMakeLists.txt, subsys/mpsl/fem/nrf21540_gpio_spi/models/mpsl_fem_nrf21540_power_model_builtin.c, subsys/mpsl/fem/nrf21540_gpio_spi/mpsl_fem_nrf21540_gpio_spi.c, subsys/mpsl/fem/simple_gpio/mpsl_fem_simple_gpio.c, west.yml
Add handling of FEM TX power split models.
=> Add mpsl fem power models

drivers/mpsl/flash_sync/flash_sync_mpsl.c
Start using NORMAL priority quicker.
If not able to start operation within 30ms, try again
with higher priority.
Signed-off-by: Martin Tverdal <martin.tverdal@nordicsemi.no>
=> drivers/mpsl/flash_synch: Use higher priority quicker

subsys/bluetooth/services/fast_pair/fp_keys.c
Rescheduling work does not unsubmit work item that has been submitted to queue. Such work item could trigger spurious timeout right after the work was rescheduled.
Jira: NCSDK-16143
=> bluetooth: fast_pair: Improve procedure timeout handling

samples/bluetooth/peripheral_fast_pair/src/bt_adv_helper.c, samples/bluetooth/peripheral_fast_pair/src/main.c
Change simplifies works handling in the sample. The sample uses cooperative contexts which simplifies synchronization.
Jira: NCSDK-16143
=> samples: peripheral_fast_pair: Simplify works handling

west.yml
=> manifest: nrf_modem: v2.1.2

doc/mcuboot/conf.py, doc/mcuboot/index-ncs.rst, doc/mcuboot/links.txt, doc/mcuboot/readme-ncs.rst, doc/mcuboot/shortcuts.txt, doc/mcuboot/unused_files.rst, doc/mcuboot/wrapper.rst
Updated:
readme-ncs.rst
wrapper.rst
index-ncs.rst
unused_files.rst
doc/mcuboot/conf.py
Added:
doc/mcuboot/links.txt
doc/mcuboot/shortcuts.txt
=> doc: MCUboot documentation update

doc/nrf/app_memory.rst, doc/nrf/releases/release-notes-changelog.rst
Add an Gazell section in the memory optimization guide.
JIRA: NCSDK-14483
=> doc: Add an Gazell section in the memory optimization guide.

modules/trusted-firmware-m/Kconfig, west.yml
This PR is a manifest combo update for 2.1.0-rc1
Merges:
https://github.com/nrfconnect/sdk-nrf/pull/8101
https://github.com/nrfconnect/sdk-nrf/pull/8607
https://github.com/nrfconnect/sdk-nrf/pull/8499
https://github.com/nrfconnect/sdk-nrf/pull/8626
Discarded:
https://github.com/nrfconnect/sdk-nrf/pull/8533
test-sdk-nrf: sdk-nrf-PR-8101
=> manifest: combo update for 2.1.0-rc1

doc/nrf/includes/hci_rpmsg_overlay.txt, samples/bluetooth/peripheral_mds/README.rst
A numbered list was interrupted due to a missing
space. Fixed it and a few other minor things.
=> doc improvement: BT MDS sample: fixing the interrupt in a list

doc/nrf/libraries/networking/aws_fota.rst, doc/nrf/libraries/networking/aws_iot.rst
Minor document updates on the following libraries:
aws_fota.rst
aws_iot.rst
=> doc improvement: minor updates on AWS libraries

doc/nrf/ug_radio_fem.rst
Fill out the missing information in FEM documentation.
Signed-off-by: Artur Hadasz <artur.hadasz@nordicsemi.no>
=> doc: Fill out the missing information about FEMs

doc/nrf/gs_recommended_versions.rst
Update tier details on the supported operating systems table
for Windows 10 and Windows 11 OSes.
=> doc improvement: Update on the supported operating systems table

west.yml
Updated Find My revision to include release notes for v2.1.0.
Signed-off-by: Kamil Piszczek <Kamil.Piszczek@nordicsemi.no>
=> Find My: add release notes for v2.1.0

doc/nrf/ug_nrf70.rst, doc/nrf/ug_nrf7002.rst
Minor document updates in the following user guides: ug_nrf70.rst
ug_nrf7002.rst
=> doc improvement: minor updates in nRF7002 DK user guide

applications/asset_tracker_v2/overlay-azure.conf, applications/asset_tracker_v2/src/cloud/azure_iot_hub_integration.c, subsys/net/lib/azure_iot_hub/src/azure_iot_hub.c
This PR fixes an issue with Azure connections getting stuck (CIA-778) and handling of AGPS/PGPS on Azure (NCSDK-16875).
Signed-off-by: Simen S. Røstad <simen.rostad@nordicsemi.no>
Signed-off-by: Maximilian Deubel <maximilian.deubel@nordicsemi.no>
=> Azure failing testing

west.yml
Update with Coverity scan warnings fixes.
=> Wi-Fi: manifest: hostap: Pull Coverity fixes

west.yml
Update zephyr with fixes cherry-picked from upstream.
Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>
=> manifest: Update zephyr with spsc_pbuf fixes

include/dm.h
Added improvements to the Distance Measurement submodule API documentation. Improved doxygen markup.
=> dm: Improve API documentation

samples/nrf9160/lwm2m_client/scripts/coiote.py, samples/nrf9160/lwm2m_client/scripts/device.py, samples/nrf9160/lwm2m_client/scripts/provision.py
- Add support for building and flashing the AT client.
- Get device id and com ports programmatically.
- Improve logging format.
=> samples: Automate provisioning

applications/nrf5340_audio/prj.conf, applications/nrf5340_audio/src/audio/Kconfig, applications/nrf5340_audio/src/modules/Kconfig, applications/nrf5340_audio/src/utils/fw_info_app.c.in
Changed settings to remove excessive prints
Signed-off-by: Kristoffer Rist Skøien <kristoffer.skoien@nordicsemi.no>
=> applications: nrf5340_audio: Print cleanup

scripts/partition_manager/partition_manager.rst
Update documentation to include information on changes to add_region
macro.
Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>
=> partition_manager: Update documentation

doc/nrf/templates/library_template_README.rst
=> doc: update on the library template

doc/nrf/ug_matter_gs_adding_clusters.rst, doc/nrf/ug_matter_gs_tools.rst
Added minor improvements to clarify ZAP tool dependencies.
Signed-off-by: Marcin Kajor <marcin.kajor@nordicsemi.no>
=> doc: matter: improvements to Adding clusters page

samples/nrf9160/nrf_cloud_mqtt_multi_service/src/application.c, samples/nrf9160/nrf_cloud_mqtt_multi_service/src/connection.c, samples/nrf9160/nrf_cloud_mqtt_multi_service/src/fota_support.c, samples/nrf9160/nrf_cloud_mqtt_multi_service/src/led_control.c, samples/nrf9160/nrf_cloud_mqtt_multi_service/src/main.c, samples/nrf9160/nrf_cloud_rest_device_message/src/main.c, samples/nrf9160/nrf_cloud_rest_fota/src/main.c, subsys/net/lib/nrf_cloud/src/nrf_cloud.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_agps.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_cell_pos.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_client_id.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_codec.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_jwt.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps_utils.c, subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c
Fix issues in samples and libraries that support nRF Cloud.
=> treewide: fix nrfcloud coverity issues

samples/crypto/aes_gcm/src/main.c
Changed buffer length to proper value.
Signed-off-by: Marcin Gasiorek <marcin.gasiorek@nordicsemi.no>
=> samples: crypto: AES GCM sample fix

samples/nrf9160/lwm2m_client/provisioning.rst, samples/nrf9160/lwm2m_client/sample_description.rst
Doc fixes
Signed-off-by: Uma <uma.praseeda@nordicsemi.no>
=> doc: Doc fixes

doc/nrf/known_issues.rst
Added some known issues related to modem library.
=> doc: update known issues related to modemlib

lib/nrf_modem_lib/nrf_modem_os.c, west.yml
See the CHANGELOG for a complete list of changes.
=> manifest: nrf_modem: version 1.2.3

applications/asset_tracker_v2/src/main.c, applications/asset_tracker_v2/src/modules/cloud_module.c, applications/asset_tracker_v2/src/modules/data_module.c, applications/asset_tracker_v2/src/modules/debug_module.c, applications/asset_tracker_v2/src/modules/gnss_module.c, applications/asset_tracker_v2/src/modules/led_module.c, applications/asset_tracker_v2/src/modules/modem_module.c, applications/asset_tracker_v2/src/modules/modules_common.h, applications/asset_tracker_v2/src/modules/sensor_module.c, applications/asset_tracker_v2/src/modules/ui_module.c, applications/asset_tracker_v2/src/modules/util_module.c
Assert if event pointer is NULL
=> applications: asset_tracker_v2: Assert if event pointer is NULL

west.yml
Update modem OS porting guide
Signed-off-by: Fabian Nawratil <fabian.nawratil@nordicsemi.no>
=> manifest: Update to nrfxlib PR #833

include/net/lwm2m_client_utils.h, samples/nrf9160/lwm2m_client/src/main.c, subsys/net/lib/lwm2m_client_utils/CMakeLists.txt, subsys/net/lib/lwm2m_client_utils/Kconfig, subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_cellconn_obj.c
Added support for LWM2M Cellular Connectivity object (ID 10)
=> net: lwm2m_client_utils: Add cellular connectivity object support

subsys/bluetooth/controller/Kconfig, subsys/bluetooth/controller/hci_driver.c, subsys/bluetooth/controller/hci_internal.c
Add support for the Connection AoA transmitter feature.
Signed-off-by: Jan Müller <jan.mueller@nordicsemi.no>
=> subsys: bluetooth: controller: Connection AoA TX

samples/wifi/shell/README.rst, subsys/net/l2/wifi/wifi_shell.c, west.yml
wifi_shell support passing custom channel to be used in connection, implement support in the WPA supplicant to use that information.
=> Add channel sel

doc/nrfxlib/nrfxlib.doxyfile.in, west.yml
Manifest update for https://github.com/nrfconnect/sdk-nrfxlib/pull/837.
=> manifest: nrfxlib: LC3 API doc update

west.yml
Regular OpenThread update to f6df50c
=> manifest: openthread: Regular OpenThread update.

doc/nrf/app_memory.rst, doc/nrf/releases/release-notes-changelog.rst
Updates to app_memory.rst, adding
config options affecting memory footprint
for Bluetooth mesh
=> doc: Memory footprint optimization for mesh

samples/matter/lock/src/app_task.cpp
Due to the fact that 7002 DK has only 2 buttons available, we need a special handling to trigger BLE advertisement. It was not working correctly for lock sample.
Signed-off-by: Marcin Kajor <marcin.kajor@nordicsemi.no>
=> samples: matter: fix starting the BLE advertisement from UI (lock app)

samples/nrf9160/modem_shell/src/sock/sock.c
In some cases poll can return POLLIN and POLLHUP and then recv() will return 0, which was ignored and no other flags were handled. This resulted in infinite poll() loop which always results in POLLIN and POLLHUP events.
=> samples: nrf9160: modem_shell: Fix POLLHUP info during recv()

doc/nrf/introduction.rst
Restructure About the NCS page -
Change the title to Introduction
Combine the introductory content of Welcome & NCS page
Reduce the content of Git & West sections
=> doc: Restructure About the NCS page

applications/nrf5340_audio/src/audio/audio_datapath.c, applications/nrf5340_audio/src/audio/audio_system.c, applications/nrf5340_audio/src/audio/audio_system.h, applications/nrf5340_audio/src/audio/streamctrl.c, applications/nrf5340_audio/src/modules/audio_usb.c, applications/nrf5340_audio/src/utils/data_fifo.c, applications/nrf5340_audio/src/utils/data_fifo.h, tests/nrf5340_audio/data_fifo/main.c
Also removed return value from data_fifo_block_free()
=> applications: nrf5340_audio: Add return in FIFO RX block drop function

west.yml
New revision defines integration platforms
Signed-off-by: Jan Gałda <jan.galda@nordicsemi.no>
=> [ant]: Update sdk-ant revision

samples/wifi/scan/README.rst
Documentation for Wi-Fi scan sample
Signed-off-by: Triveni D <triveni.danda@nordicsemi.no>
=> samples: wifi: Scan sample documentation

doc/nrf/ug_nrf52.rst
Fixed table in ug_nf52.rst.
Signed-off-by: Anna Kielar <anna.kielar@nordicsemi.no>
=> doc: small table fix

doc/nrf/known_issues.rst
Add known issues related to  machine learning on thingy53: Issue with not going to sleep and do not wake up.
Jira: NCSDK-16644
=> doc: add known issues related to  machine learning

drivers/wifi/nrf700x/CMakeLists.txt, drivers/wifi/nrf700x/Kconfig.nrf700x, drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h, drivers/wifi/nrf700x/osal/fw_if/umac_if/src/event.c, drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c, drivers/wifi/nrf700x/osal/hw_if/hal/src/hal_api.c, drivers/wifi/nrf700x/zephyr/inc/zephyr_fmac_main.h, drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c, drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c, drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c, samples/wifi/shell/README.rst, samples/wifi/shell/overlay-scan-only.conf, samples/wifi/shell/sample.yaml
~~This needs DTS changes to get Wi-Fi boot working, they will raised by Andrzej in a separate PR. This also heavily conflicts with #8493  PR, so, leaving it as draft till that is merged.~~
All dependencies are resolved now, no functional changes in this code, just build time feature flags to save memory targeted for nRF9160 scan only support.
=> Nrf9160 scan only support

samples/wifi/sta/README.rst
Documentation for Wi-Fi station sample
Signed-off-by: Triveni Danda <triveni.danda@nordicsemi.no>
=> samples: wifi: Station sample documentation

west.yml
(dis)connect status locking fixes.
=> manifest: sdk-hostap: Pull status locking fixes

doc/nrf/ug_matter_intro_overview.rst, doc/nrf/ug_matter_overview_architecture.rst, doc/nrf/ug_matter_overview_device_types.rst
Added device type page.
KRKNWK-15343.
=> doc: matter: add device type page

doc/nrf/conf.py, doc/nrf/index.rst, doc/nrf/known_issues.rst, doc/nrf/releases/release-notes-changelog.rst, doc/versions.json
Update versions, changelog and notes for the dev tag.
=> doc: doc updates for 2.1.99-dev2

subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_security.c
On some corner cases, the code could try to convert non-existent PSK key to a proper format and write that to modem. Added a length check.
Also, sometimes, if modem did have keys, but we had not provisioned it, the code tried to write non-existing key to a modem. Fixed.
Internal ticket: NCSDK-16703
=> net: lib: lwm2m_client_utils: Check credential length before writing

west.yml
This pulls recent refactoring of Matter over WiFi connection management using Zephyr net_mgmt API and events.
Signed-off-by: Marcin Kajor <marcin.kajor@nordicsemi.no>
=> manifest: update Matter SDK to pull WiFi net_mgmt API integration

doc/nrf/shortcuts.txt, doc/nrf/ug_nrf52.rst, doc/nrf/ug_nrf91_features.rst
FOTA over BLE chapter (ug_nrf52.rst) reordered and rephrased. 
1 substitution removed from shortcuts.txt and ug_nrf91_features.
Signed-off-by: Anna Kielar <anna.kielar@nordicsemi.no>
=> doc: FOTA over BLE doc update

doc/nrf/glossary.rst, doc/nrf/introduction.rst, doc/nrf/ug_matter_gs_adding_clusters.rst, doc/nrf/ug_matter_gs_tools.rst
NCSDK-11865
Terminology fix: submodule in docs and glossary
=> doc: Submodule term fix in docs and glossary

applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c, applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
Using ADV-EXT instead of legacy ADV
=> applications: nrf5340_audio: Using ADV-EXT instead of legacy ADV

samples/nrf9160/lwm2m_client/scripts/coiote.py
Allow querying the Coiote domain from command line.
=> samples: lwm2m_client: Fix domain command from coiote script

applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
- Bugfix: Add conversational to context for bidir
=> applications: nrf5340_audio: Add supported context for bidir

doc/nrf/libraries/mpsl/mpsl_lib.rst
Language review of the MPSL library control library documentation.
Signed-off-by: Wille Backman <wille.backman@nordicsemi.no>
=> doc: language review on the MPSL library control library

doc/nrf/releases/release-notes-changelog.rst, include/modem/location.h, lib/location/location.c, lib/location/location_core.c, lib/location/method_gnss.c, samples/nrf9160/modem_shell/src/location/location_shell.c
There has earlier been method specific timeouts only.
Those will continue to exist but now we also have timeout for entire location request.
=> lib: location: Timeout for location request

applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c, applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c, applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c, applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
- Change 'for (size_t i...' to 'for (int i...'
- Change %u to %d in LOG
=> applications: nrf5340_audio: Clean up le_audio files

boards/arm/nrf5340_audio_dk_nrf5340/board.h
- Update valid mask with resistor values
=> applications: nrf5340_audio: Add support for 1.1.0 DK

doc/nrf/libraries/networking/nrf_cloud_pgps.rst
Fixed a few formatting issues and rephrased
some of the text.
=> doc: nRF Cloud P-GPS lib: formatting fixes

applications/matter_weather_station/README.rst, doc/nrf/conf.py, doc/nrf/dm_adding_code.rst, doc/nrf/known_issues.rst, doc/nrf/links.txt, doc/nrf/release_notes.rst, doc/nrf/releases/release-notes-2.1.1.rst, doc/nrf/releases/release-notes-changelog.rst, doc/nrf/shortcuts.txt, doc/nrfxlib/conf.py, doc/versions.json
Updated doc versions for NCS 2.1.1.
Added release notes.
Updated known issues.
=> doc: update documentation for NCS 2.1.1

west.yml
Added support for Connection CTE Response.
Corresponding PR in nrf: nrfconnect/sdk-nrfxlib#844
Signed-off-by: Yuxuan Cai <yuxuan.cai@nordicsemi.no>
=> manifest: update softdevice controller

applications/nrf5340_audio/src/audio/audio_system.c, applications/nrf5340_audio/src/audio/streamctrl.c
=> applications: nrf5340_audio: Audio system shell commands

west.yml
Regular OpenThread update to \`488ee63\`
=> manifest: openthread: update to `488ee63`

samples/wifi/radio_test/README.rst, samples/wifi/radio_test/ficr.rst, samples/wifi/radio_test/radio_test_subcommands.rst, samples/wifi/radio_test/sample_description.rst
Restructuring the Radio test sample documentation
to make it consistent with the structure of other samples.
=> doc: Restructure Radio test sample

applications/matter_weather_station/sample.yaml
Added release and factory data configurations to Matter weather station sample.yaml
=> applications: Added two configurations in Matter WS sample yaml

samples/nrf9160/location/README.rst
Fixed the formatting of example commands.
=> doc: nRF9160 Location sample: formatting fixes

doc/nrf/releases/release-notes-changelog.rst, doc/nrf/ug_matter_intro_overview.rst, doc/nrf/ug_matter_overview_multi_fabrics.rst, doc/nrf/ug_matter_overview_network_topologies.rst
Added a page about multi-admin.
NCSDK-15211.
=> doc: matter: add multi-admin page

subsys/bluetooth/controller/hci_internal.c
Added support for data related address changes
Signed-off-by: Burak Gorduk <burak.gorduk@nordicsemi.no>
=> bluetooth: controller: Added support for data related address changes

doc/nrf/links.txt, doc/nrf/ug_bt_fast_pair.rst, west.yml
Change introduces documentation related to TX power calibration.
Jira: NCSDK-16584
=> bluetooth: fast_pair: Add TX power calibration documentation

west.yml
Fix the Wi-Fi + Thread combo build crash.
=> manifest: sdk-hostap: Pull Wi-Fi thread combo fixes
