- doc/nrf/releases/release-notes-changelog.rst
- lib/nrf_modem_lib/Kconfig.modemlib
- lib/nrf_modem_lib/nrf_modem_lib.c
- lib/nrf_modem_lib/nrf_modem_lib_trace.c
- lib/nrf_modem_lib/nrf_modem_os.c
- tests/lib/nrf_modem_lib/nrf_modem_lib_trace/src/main.c
- west.yml
> manifest: nrf_modem v2.2.0

- west.yml
Regular OpenThread update to \`2592e34\`
> manifest: openthread: update to `2592e34`

- west.yml
Pull the Thingy:53 support in find my.
Signed-off-by: Dominik Chat <dominik.chat@nordicsemi.no>
> manifest: Update find my manifest revision.

- west.yml
Updates TF-M to include fix for build warnings.
Signed-off-by: Vidar Lillebø <vidar.lillebo@nordicsemi.no>
> manifest: Update TF-M

- doc/nrf/app_memory.rst
- Add BT_MESH_RELAY_BUF_COUNT to app_memory.rst for mesh.
- Rename `Low Power Node` to `Low Power node`.
Signed-off-by: Pavel Vasilyev <pavel.vasilyev@nordicsemi.no>
> doc: app_memory: Add BT_MESH_RELAY_BUF_COUNT

- doc/nrf/libraries/networking/nrf_cloud.rst
- doc/nrf/links.txt
- subsys/net/lib/nrf_cloud/include/nrf_cloud_fota.h
Improve documentation for nrf_cloud MQTT FOTA.
CIA-693
> net: lib: nrf_cloud: update FOTA documentation

- doc/nrf/known_issues.rst
Change adds known issue related to interrupted settings erase operation in failsafe module.
Jira: NCSDK-17706
> doc: known_issues: Add NCSDK-17706

- west.yml
Pull TF-M repository to include fix for library model hardfaulting during init.
> manifest: Pull tfm repository for library model fix

- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_structs.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/event.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
- drivers/wifi/nrf700x/zephyr/inc/zephyr_wpa_supp_if.h
- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
Support for handling MLME frames.
Enable RRM support in capabilities.
Support for wnm_bss_query wpa_cli cmd.
Signed-off-by: Sridhar Nuvusetty <sridhar.nuvusetty@nordicsemi.no>
> wifi: MBO Pre-certification bugfixes

- subsys/caf/modules/ble_adv.c
Change cleans up code to simplify adding new features.
Jira: NCSDK-17786
> caf: ble_adv: Code cleanup

- samples/nrf9160/lwm2m_client/src/events/gnss_pvt_event.c
- subsys/net/lib/lwm2m_client_utils/location/location_assistance.c
- subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_connmon.c
Fix issues found by coverity, unnecessary includes and
comparison to function pointer.
> net: lib: lwm2m_client_utils: Lwm2m coverity fixes

- doc/nrf/app_boards.rst
- west.yml
- Manifest update for nrfxlib.
- Minor heading edit in sdk-nrf docs.
> doc: manifest and updates for CMSE terminology fixes

- drivers/wifi/nrf700x/zephyr/inc/zephyr_wpa_supp_if.h
- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
- west.yml
Support for handling of un-protected deauth/disassoc frames.
Refer:[SHEL-804](https://projecttools.nordicsemi.no/jira/browse/SHEL-804) and [SHEL-814](https://projecttools.nordicsemi.no/jira/browse/SHEL-814)
Signed-off-by: Ajay Parida <ajay.parida@nordicsemi.no>
> wifi: PMF Pre-certification bugfixes

- samples/nrf9160/lwm2m_client/src/events/accel_event.c
- samples/nrf9160/lwm2m_client/src/events/sensor_event.c
- samples/nrf9160/lwm2m_client/src/events/ui_input_event.c
- samples/nrf9160/lwm2m_client/src/lwm2m/lwm2m_app_utils.c
- samples/nrf9160/lwm2m_client/src/lwm2m/lwm2m_device.c
- samples/nrf9160/lwm2m_client/src/main.c
* Removes unnecessary includes
* Removes a call to non-existing function
* Checks some return values and logs if there are any issues
> LwM2M: removes unused includes

- lib/bin/lwm2m_carrier/os/lwm2m_os.c
Updated the glue layer to facilitate switching from NB-IoT to LTE-M during in-band FOTA. (Previously only out-band RAT switching was supported).
Signed-off-by: Håvard Vermeer <havard.vermeer@nordicsemi.no>
> lib: bin: lwm2m_carrier: Enable RAT switch for in-band FOTA

- west.yml
Regular OpenThread update to \`d7de666\`
> manifest: openthread: update to `d7de666`

- west.yml
softdevice_controller: rev 295c92f1368192d1b7a9f0f199e94c191f23834a
Signed-off-by: Piotr Pryga <piotr.pryga@nordicsemi.no>
> manifest: nrfxlib: Update SDC revision

- doc/nrf/conf.py
- doc/nrf/dm_adding_code.rst
- doc/nrf/known_issues.rst
- doc/nrf/links.txt
- doc/nrf/release_notes.rst
- doc/nrf/releases/release-notes-2.1.2.rst
- doc/nrf/shortcuts.txt
- doc/nrfxlib/conf.py
- doc/versions.json
- west.yml
> doc: Doc updates for 2.1.2 release

- subsys/bluetooth/services/fast_pair/CMakeLists.txt
- subsys/bluetooth/services/fast_pair/Kconfig.fast_pair
- subsys/bluetooth/services/fast_pair/fp_gatt_service.c
- subsys/bluetooth/services/fast_pair/fp_keys.c
- subsys/bluetooth/services/fast_pair/fp_storage/include/fp_storage_pn.h
- subsys/bluetooth/services/fast_pair/include/fp_keys.h
Adds Additional Data characteristic and support for Personalized Name
Fast Pair extension.
Jira: NCSDK-14072
> bluetooth: fast_pair: Add Personalized Name extension

- scripts/requirements-doc.txt
- scripts/requirements-extra.txt
The latest update broke the extra dependency installation
Signed-off-by: Maciej Perkowski <Maciej.Perkowski@nordicsemi.no>
> hotfix: Fix pygit2 version

- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/ug_bt_mesh.rst
- doc/nrf/ug_bt_mesh_node_removal.rst
Add a user guide showing how to remove a node from the network properly.
Signed-off-by: Pavel Vasilyev <pavel.vasilyev@nordicsemi.no>
> docs: Add user guide for Node Remove procedure in Bluetooth mesh

- scripts/west-commands.yml
- scripts/west_commands/ncs_commands.py
Minimal script for upmerging Zephyr project.
Signed-off-by: Kari Hamalainen <kari.hamalainen@nordicsemi.no>
> scripts: add simple upmerge helper script

- doc/nrf/libraries/others/fw_info.rst
- subsys/fw_info/Kconfig.template.fw_info_ext_api
Docs are out-of-sync with implementation.
> doc: fw_info: Update docs to match implementation

- doc/nrf/libraries/bootloader/bl_storage.rst
- include/bl_storage.h
- samples/bootloader/README.rst
- subsys/bootloader/Kconfig
- subsys/bootloader/bl_storage/Kconfig
Documentation improvements for the bl_storage library and the NSIB bootloader.
> doc: Improve documentation for bl_storage and NSIB

- doc/nrf/libraries/bluetooth_services/scan.rst
- doc/nrf/libraries/bluetooth_services/services/ancs_client.rst
- doc/nrf/libraries/bluetooth_services/services/hogp.rst
- doc/nrf/libraries/bluetooth_services/services/hrs_client.rst
- doc/nrf/releases/release-notes-changelog.rst
- include/bluetooth/scan.h
4 files restructured to match the library template: scan.rst, ancs_client.rst, hogp.rst, hrs_client.rst. Related to Jira NCSDK_17402.
Signed-off-by: Anna Kielar <anna.kielar@nordicsemi.no>
> doc: Bluetooth services docs restructuring

- subsys/caf/modules/ble_adv.c
Change is needed to allow for advertising start/stop without affecting module state.
Jira: NCSDK-17786
> caf: ble_adv: Separate state handling from advertising control

- .github/workflows/create-upmerge-PRs.yml
- scripts/west_commands/ncs_commands.py
This Github action will perform simple Zephyr upmerge and create PRs in sdk-nrf and sdk-zephyr repos.
Signed-off-by: Kari Hamalainen <kari.hamalainen@nordicsemi.no>
> ci: Initial auto-upmerge github action

- subsys/net/lib/lwm2m_client_utils/location/location_assistance.c
Compiler doesn't like the IS_ENABLED combined with static functions.
Signed-off-by: Jarno Lämsä <jarno.lamsa@nordicsemi.no>
> net: lib: lwm2m_client_utils: Location assistance fix

- .github/test-spec.yml
Signed-off-by: Dawid Przybyło <dawid.przybylo@nordicsemi.no>
> test-spec: fem: add label CI-fem-test

- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
- Create struct for headsets and populate with streams and endpoints
- Make cis_gateway easier to read and understand
> applications: nrf5340_audio: Restructure le_audio_cis_gateway.c

- doc/nrf/libraries/bluetooth_services/mesh/sensor.rst
- doc/nrf/libraries/bluetooth_services/mesh/sensor_types.rst
- include/bluetooth/mesh/sensor.h
This adds snippets showing how to initialize sensor settings and descriptors, as well as clarifying some potentially confusing points about sensor types.
Signed-off-by: Ludvig Samuelsen Jordet <ludvig.jordet@nordicsemi.no>
> Doc: Improve Mesh sensor documentation

- west.yml
Regular OpenThread update to \`2caab0c\`
> manifest: openthread: update to `2caab0c`

- .github/workflows/check-ci-requested.yml
- .github/workflows/remove-ci-requested.yml
* CI-Requested label exists action result is checked by the CI for external contributors
* Remove the CI-Requested label on pull request change
> ci: CI-Requested label

- doc/nrf/ug_multi_image.rst
This is non-trivial and not described in docs AFAICT.
> doc: multi_image: add note on adding image from out of tree

- .github/workflows/check-ci-requested.yml
* Fail CI-Requested check only if external label is also set
> ci: fix ci-requested logic

- doc/nrf/links.txt
Reordered links in links.txt to match order criteria.
> doc: links.txt housekeeping

- include/net/nrf_cloud.h
- include/net/nrf_cloud_agps.h
- include/net/nrf_cloud_location.h
- include/net/nrf_cloud_pgps.h
- include/net/nrf_cloud_rest.h
- subsys/net/lib/nrf_cloud/include/nrf_cloud_codec.h
- subsys/net/lib/nrf_cloud/include/nrf_cloud_fota.h
- subsys/net/lib/nrf_cloud/include/nrf_cloud_fsm.h
- subsys/net/lib/nrf_cloud/include/nrf_cloud_mem.h
- subsys/net/lib/nrf_cloud/include/nrf_cloud_transport.h
Cleanup header comments so that proper documentation is produced.
Remove unused items.
IRIS-5092
> net: lib: nrf_cloud: cleanup header

- applications/nrf5340_audio/README.rst
- doc/nrf/releases/release-notes-changelog.rst
Expanded Testing FOTA section with a step about pressing button 4. OCT-2300.
> doc: nrf5340audio: add step about button 4 for dfu

- doc/nrf/includes/tfm.txt
Added link to the Processing environments section to tfm.txt.
> doc: cmse: update tfm.txt with link

- doc/nrf/releases/release-notes-changelog.rst
- samples/nrf9160/nrf_cloud_mqtt_multi_service/Kconfig
- samples/nrf9160/nrf_cloud_mqtt_multi_service/README.rst
- samples/nrf9160/nrf_cloud_mqtt_multi_service/nrf9160dk_with_nrf7002ek.overlay
- samples/nrf9160/nrf_cloud_mqtt_multi_service/overlay-nrf7002ek-wifi-scan-only.conf
- samples/nrf9160/nrf_cloud_mqtt_multi_service/src/location_tracking.c
Enables the use of the Location library Wi-Fi location method with nrf7002 EK
IRIS-5032
Signed-off-by: Georges Oates_Larsen <georges.larsen@nordicsemi.no>
> samples: mmss: Add Wi-Fi location tracking support

- doc/nrf/releases/release-notes-changelog.rst
- west.yml
This commit updates sdk-nrf-802154 and sdk-nrfxlib revision to bring in the latest changes in the nrf_802154 component.
Signed-off-by: Jędrzej Ciupis <jedrzej.ciupis@nordicsemi.no>
> manifest: update sdk-nrf-802154 revision

- doc/nrf/libraries/networking/lwm2m_location_assistance.rst
Add the API usage section to the .rst.
Signed-off-by: Jarno Lämsä <jarno.lamsa@nordicsemi.no>
> doc: lwm2m location assistance library API usage

- applications/nrf5340_audio/README.rst
- applications/nrf5340_audio/src/audio/streamctrl.c
- applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
- applications/nrf5340_audio/src/bluetooth/ble_audio_services.c
- applications/nrf5340_audio/src/bluetooth/ble_audio_services.h
- applications/nrf5340_audio/src/bluetooth/le_audio.h
- applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/software_maturity.rst
- Enable play/pause using MCS
- On CIS gateway and headset
> applications: nrf5340_audio: Implement minimum MCS functionality

- west.yml
Update Memfault firmware SDK to revision 0.35.0
> manifest: update Memfault firmware SDK

- applications/nrf_desktop/doc/ble_scan.rst
- doc/nrf/releases/release-notes-changelog.rst
Change updates BLE scan module documentation.
Jira: NCSDK-17315
> applications: nrf_desktop: Update BLE scan module documentation

- applications/nrf5340_audio/README.rst
- applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/software_maturity.rst
> applications: nrf5340_audio: Add CSIS into headsets

- drivers/wifi/nrf700x/CMakeLists.txt
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_structs.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fw_A/host_rpu_umac_if.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/event.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
- drivers/wifi/nrf700x/zephyr/inc/zephyr_ps.h
- drivers/wifi/nrf700x/zephyr/inc/zephyr_twt.h
- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_ps.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_twt.c
- west.yml
a) TWT support added to handle setup/teardown command events.
b) Power save enable/disable command support.
Signed-off-by: Ajay Parida <ajay.parida@nordicsemi.no>
> drivers: wifi: Add support for twt and power save

- applications/nrf_desktop/README.rst
- applications/nrf_desktop/doc/fast_pair_app.rst
included small adjustment to two rst files.
Signed-off-by: Anna Wojdylo <anna.wojdylo@nordicsemi.no>
> applications: nrf_desktop: Fast Pair doc fix

- applications/nrf_desktop/doc/usb_state.rst
- doc/nrf/releases/release-notes-changelog.rst
Change updates documentation for the USB state module.
Jira: NCSDK-17315
> applications: nrf_desktop: Update USB state documentation

- doc/nrf/releases/release-notes-changelog.rst
- samples/bluetooth/peripheral_fast_pair/README.rst
Change updates documentation to inform about bond removal, advertising payload update and rejecting pairing outside of pairing mode.
Jira: NCSDK-17813
> samples: peripheral_fast_pair: Update documentation

- west.yml
Updated Matter to pull several improvements and bug fixes related to the factory data management.
> manifest: Updated Matter module revision to pull factory data fix

- applications/nrf_desktop/README.rst
- doc/nrf/releases/release-notes-changelog.rst
Change introduces documentation for new configuration options and release notes.
Jira: NCSDK-17315
> applications: nrf_desktop: Document new configuration options

- include/esb.h
- subsys/esb/Kconfig
- subsys/esb/esb.c
Refactoring of the ESB protocol.
It uses now HAL and drivers instead of pure
registers operation. Also protocol logic is improved.
> esb: ESB refactoring

- applications/nrf_desktop/README.rst
Change introduces minor fix to the Fast Pair documentation.
Jira: NCSDK-17505
> applications: nrf_desktop: Minor fix in Fast Pair doc

- subsys/bluetooth/controller/Kconfig
- subsys/bluetooth/controller/hci_driver.c
- subsys/bluetooth/controller/hci_internal.c
Signed-off-by: Raphael Treccani-Chinelli <raphael.treccani@nordicsemi.no>
> bluetooth: controller support for sending PASTs

- scripts/quarantine.yaml
- west.yml
Update revision to ANT for nRF Connect SDK.
Signed-off-by: Sarah Read <sarah.read@garmin.com>
> manifest: Update sdk-ant revision

- doc/nrf/releases/release-notes-changelog.rst
Added missing changelog entry for PR#9017.
> doc: cmse: add changelog entry

- doc/nrf/ug_bt_mesh_fota.rst
Fix parsing in Bluetooth Mesh FOTA user guide.
Signed-off-by: Pavel Vasilyev <pavel.vasilyev@nordicsemi.no>
> doc: Fix parsing in Bluetooth Mesh FOTA user guide

- lib/location/method_gnss.c
Assistance data injection to GNSS sometimes failed because of a concurrency issue when valid predictions were found from flash. The fix moves the GNSS start/stop operation done to trigger assistance data request from GNSS to a work item. This ensures that the conflicting operations are done sequentially.
> lib: location: fix P-GPS assistance data injection

- samples/tfm/tfm_cert/README.rst
Fix code blocks not rendered properly.
Break long code blocks to avoid the scroll-bar.
> samples: tfm_cert: Fix code blocks not rendered properly

- west.yml
This fixes an issue with event pooling.
Signed-off-by: Martin Tverdal <martin.tverdal@nordicsemi.no>
> manifest: Update mpsl and softdevice controller

- doc/nrf/links.txt
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/ug_bt_fast_pair.rst
- samples/bluetooth/peripheral_fast_pair/README.rst
Adds documentation to Battery Notification Fast Pair extension.
Jira: NCSDK-17115
> bluetooth: fast_pair: Add Battery Notification documentation

- applications/nrf_desktop/README.rst
- applications/nrf_desktop/doc/ble_discovery.rst
- applications/nrf_desktop/doc/ble_passkey.rst
- doc/nrf/releases/release-notes-changelog.rst
Change introduces small documentation improvements to align the documentation with current implementation.
Jira: NCSDK-17315
> applications: nrf_desktop: Documentation improvements

- .github/workflows/check-ci-requested.yml
* Action never returned succeess if CI-Requested label was set
> ci: check requested logic fix

- .github/workflows/create-upmerge-PRs.yml
Adding teams notification in case action fails.
Signed-off-by: Kari Hamalainen <kari.hamalainen@nordicsemi.no>
> ci: add notifier to zephyr upmerge action

- samples/wifi/shell/README.rst
Update help text to provide information for TWT and power save commands in wifi shell.
Signed-off-by: Ravi Dondaputi <ravi.dondaputi@nordicsemi.no>
> samples: wifi: Update command output and help for power save

- applications/nrf5340_audio/README.rst
- applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
- applications/nrf5340_audio/src/bluetooth/ble_audio_services.c
- applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
Fixed release build warning for BIS gateway.
Minor log/doc fixes.
> applications: nrf5340_audio: Fix BIS release compile warnings and minor typo

- doc/nrf/links.txt
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/ug_thread_tools.rst
Fixed links
Changed installation info in Thread ug
> doc improvement: fix links for new nRF Util

- doc/nrf/libraries/bin/lwm2m_carrier/CHANGELOG.rst
- doc/nrf/libraries/bin/lwm2m_carrier/app_integration.rst
- samples/nrf9160/lwm2m_carrier/provisioning.rst
- samples/nrf9160/lwm2m_carrier/sample_description.rst
Minor updates to Lib carrier docs
> doc improvement: Minor updates to Lib carrier docs

- doc/nrf/links.txt
- doc/nrf/ug_nrf9160_gs.rst
- doc/nrf/ug_thingy91_gsg.rst
Add links to the Cellular IoT course into the GSGs of nRF9160 DK and Thingy:91
> doc improvement: Add Dev academy links to GSG

- .checkpatch.conf
- doc/nrf/ug_thread_certification.rst
- samples/openthread/cli/harness-thci-1-3/nRF_Connect_SDK_1_3.py
Thread Test Harness issues require incompatible APIs to be used in THCI files for Thread 1.3 testing. Providing here the apropriate file for such DUT.
> doc: provide THCI file for Thread 1.3 Certification testing

- west.yml
Rewording and formatting a few
nrfxlib docs.
> manifest: Doc fixes in nrfxlib

- west.yml
Regular rewrite of Matter fork history.
> matter: rebase sdk-connectedhomeip

- subsys/pcd/src/pcd.c
Fixes an issue with serial recovery on nRF5340 whereby the network core would fault due to permissions before the upgrade had finished.
> pcd: Fix issue with serial recovery on nRF5340

- scripts/requirements-fixed.txt
Add grpcio-tools package required for building Wi-Fi Provisioning sample
Signed-off-by: Bansidhar Mangalwedhekar <bansidhar.mangalwedhekar@nordicsemi.no>
> samples: wifi : Add missing python package

- doc/nrf/index.rst
- doc/nrf/known_issues.rst
- doc/nrf/libraries/networking/lwm2m_client_utils.rst
- doc/nrf/links.txt
- doc/nrf/release_notes.rst
- doc/nrf/releases/release-notes-2.2.0.rst
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/shortcuts.txt
- samples/matter/light_bulb/README.rst
- samples/matter/light_switch/README.rst
- samples/matter/lock/README.rst
- samples/matter/template/README.rst
Add release notes for 2.2.0 and other doc changes for release
NCSDK-18302
> doc: Add release notes for 2.2.0

- doc/nrf/known_issues.rst
update known issues for 2.2.0 release
----
----
> doc: update known issues for 2.2.0 release

- west.yml
Pull the fix for SAE-PWE (H2E) in MbedTLS.
> manifest: sdk-hostap: Pull SAE H2E Fix

- doc/nrf/releases/release-notes-changelog.rst
- scripts/west_commands/sbom/args.py
- scripts/west_commands/sbom/common.py
- scripts/west_commands/sbom/data_structure.py
- scripts/west_commands/sbom/file_input.py
- scripts/west_commands/sbom/git_info_detector.py
- scripts/west_commands/sbom/input_build.py
- scripts/west_commands/sbom/input_post_process.py
- scripts/west_commands/sbom/main.py
- scripts/west_commands/sbom/output_pre_process.py
- scripts/west_commands/sbom/output_template.py
- scripts/west_commands/sbom/templates/raport.spdx.jinja
- scripts/west_commands/sbom/templates/report.html.jinja
Complete SBOM report should also contains information about a source of each package (module) and its version. This commit adds that information to the "west ncs-sbom" script.
Current preview of HTML report: https://doki-nordic.github.io/test-demo-docs/temp/west-sbom-sample.html
> scripts: sbom: Report source and version information

- tests/subsys/bootloader/boot_chains/CMakeLists.txt
- tests/subsys/bootloader/boot_chains/README.txt
- tests/subsys/bootloader/boot_chains/src/main.c
- tests/subsys/bootloader/boot_chains/testcase.yaml
> tests: boot_chains: Add test for different boot chains

- west.yml
Update MCUBoot with minor bugfix
> manifest: Update MCUBoot with minor bugfix

- doc/nrf/known_issues.rst
Change introduces known issues for leaving off state on peer disconnection.
Jira: NCSDK-18587
> caf: ble_adv: Add known issue for NCSDK-18587

- samples/matter/lock/sample.yaml
Added configurations in door lock sample.yml file to use in integration system tests
Signed-off-by: Janusz Gąsior <janusz.gasior@nordicsemi.no>
> samples: matter: Samples configuration for integration system tests

- west.yml
Update Matter SDK with a fix for JSON schema.
> manifest: Update Matter SDK with fix for json schema

- doc/nrf/libraries/networking/aws_iot.rst
Update documentation to include topic handling for subscribing and publishing to custom topics.
Fixes NCSIDB-620
Signed-off-by: Simen S. Røstad <simen.rostad@nordicsemi.no>
> doc: aws_iot: Update documentation to include topic handling

- samples/nrf9160/lwm2m_client/scripts/coiote.py
Pretty print the output from Coiote helper script. Also add a helper function to query data from device cache.
> samples: nrf9160: lwm2m_client: Pretty print the output

- applications/nrf_desktop/src/modules/Kconfig.caf_settings_loader.default
- applications/nrf_desktop/src/modules/ble_bond.c
- doc/nrf/releases/release-notes-changelog.rst
- drivers/sensor/paw3212/paw3212.c
- drivers/sensor/pmw3360/pmw3360.c
Change reduces log verbosity to avoid dropping logs on boot.
Jira: NCSDK-18753
> applications: nrf_desktop: Reduce log verbosity

- subsys/net/lib/lwm2m_client_utils/lwm2m/lwm2m_cellconn_obj.c
*Remove unnecessary include
*Check return value from lte_lc_func_mode_set()
> net: lwm2m_client_utils: cellconn: Remove unused include

- lib/at_cmd_parser/at_params.c
- subsys/bluetooth/mesh/light_ctrl_srv.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_codec.c
A small set of fixes for the issues found by sonarcloud.
Signed-off-by: Balaji Srinivasan <balaji.srinivasan@nordicsemi.no>
> Static code analysis fixes

- include/bl_validation.h
- subsys/bootloader/bl_validation/bl_validation.c
Moved the implementation-specfic docs to the implementation, and added API-specific information to the API docs.
> bl_validation: Improve docs

- doc/nrf/libraries/networking/lwm2m_location_assistance.rst
Add documentation about the Wi-Fi based location assistance through LwM2M server to the nrfCloud.
Signed-off-by: Jarno Lämsä <jarno.lamsa@nordicsemi.no>
> doc: Documentation about Wi-Fi based LwM2M location assistance

- doc/nrf/migration/migration_guide_1.x_to_2.x.rst
Add a note about CONFIG_LEGACY_INCLUDE_PATH
> doc: migration guide update

- applications/nrf5340_audio/README.rst
Added links to Audio known issues section next to lines that mention serial connection. VSC-2388.
> doc: nrf5340audio: add mentions of USB known issue

- boards/arm/nrf5340_audio_dk_nrf5340/board.h
> boards: nrf5340_audio_dk: Add version 1.2.0

- doc/nrf/templates/library_template_README.rst
Minor style fixes in Library template
> doc: minor fixes in Library template

- subsys/bluetooth/controller/hci_driver.c
Signed-off-by: Olivier Lesage <olivier.lesage@nordicsemi.no>
> bluetooth: Remove setting adv count when adv isn't supported

- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/templates/Ecosystem_integration_template_README.rst
- doc/nrf/ug_bt_fast_pair.rst
Added Ecosystem integration guide template
NCSDK-17791
> doc: Add template for ecosystem integration guide

- applications/nrf5340_audio/README.rst
- applications/nrf5340_audio/src/bluetooth/Kconfig
- applications/nrf5340_audio/src/bluetooth/ble_core.c
- applications/nrf5340_audio/src/bluetooth/ble_hci_vsc.c
- applications/nrf5340_audio/src/bluetooth/ble_hci_vsc.h
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
- applications/nrf5340_audio/tools/buildprog/buildprog.py
- boards/arm/nrf5340_audio_dk_nrf5340/nrf5340_audio_dk_nrf5340_cpuapp_common.dts
- doc/nrf/releases/release-notes-changelog.rst
- Add support for Front End Module (FEM) nRF21540
> applications: nrf5340_audio: Add support for nRF21540

- applications/nrf5340_audio/README.rst
- applications/nrf5340_audio/src/audio/Kconfig
- applications/nrf5340_audio/src/audio/Kconfig.defaults
- applications/nrf5340_audio/src/audio/streamctrl.c
- applications/nrf5340_audio/src/bluetooth/Kconfig
- applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
- applications/nrf5340_audio/src/bluetooth/le_audio.h
- applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
- doc/nrf/releases/release-notes-changelog.rst
Allowing to switch between multiple
BIS gateway devices
Signed-off-by: Graham Wacey <graham.wacey@nordicsemi.no>
> applications: nrf5340_audio: Receive from one of several broadcasters

- doc/_static/css/nrf.css
- doc/nrf/includes/filter.js
Added a container element for the version tags so they wrap properly.
Signed-off-by: Gaute Svanes Lunde <gaute.lunde@nordicsemi.no>
> doc: known issues version tag container

- doc/nrf/conf.py
- doc/nrf/dm_adding_code.rst
- doc/nrf/known_issues.rst
- doc/nrf/links.txt
- doc/nrf/release_notes.rst
- doc/nrf/releases/release-notes-2.1.3.rst
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/shortcuts.txt
- doc/nrfxlib/conf.py
- doc/versions.json
Doc updates for NCS 2.1.3 bug fix release
> doc: Doc updates for 2.1.3 release

- doc/nrf/libraries/modem/nrf_modem_lib.rst
- west.yml
> doc: lib: nrf_modem: updates

- applications/asset_tracker_v2/doc/lwm2m_carrier_library.rst
- doc/nrf/includes/lwm2m_carrier_library.txt
- doc/nrf/releases/release-notes-changelog.rst
- samples/nrf9160/http_update/application_update/README.rst
- samples/nrf9160/http_update/application_update/overlay-carrier.conf
- samples/nrf9160/http_update/application_update/sample.yaml
- samples/nrf9160/http_update/application_update/src/main.c
- samples/nrf9160/http_update/common/src/update.c
This will add support for the LwM2M Carrier Library to the Application Update sample.
Signed-off-by: Markus Rekdal <markus.rekdal@nordicsemi.no>
> samples: nrf9160: http_update: Add support for Carrier Library

- subsys/dm/Kconfig
- subsys/dm/rpc/Kconfig
Introduces changes in the help text of the Kconfig option.
> dm: Improve the text help of the Kconfig options

- applications/serial_lte_modem/doc/slm_data_mode.rst
Update doc for data mode based on customer support experience.
> application: serial_lte_modem: Doc update for data mode

- applications/serial_lte_modem/doc/Generic_AT_commands.rst
- applications/serial_lte_modem/src/main.c
- applications/serial_lte_modem/src/slm_at_commands.c
- doc/nrf/releases/release-notes-changelog.rst
Add AT#XSHUTDOWN to put nRF9160 to SYSTEM OFF mode
Add doc for AT#XRESET command
Update doc for AT#XSLEEP command
> application: serial_lte_modem: Add power-off command

- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/ug_matter_device_certification.rst
Added a section about certification templates for Matter. KRKNWK-15725.
> doc: matter: certification templates section

- doc/nrf/introduction.rst
Minor updates to the introduction page
> doc: Minor updates to the introduction page

- west.yml
Updates SDC and MPSL.
Signed-off-by: Olivier Lesage <olivier.lesage@nordicsemi.no>
> bluetooth: update nrfxlib manifest revision

- applications/nrf_desktop/Kconfig.ble
- applications/nrf_desktop/src/modules/Kconfig.hids
Change cleans up HIDS configuration in the application.
Jira: NCSDK-17243
> applications: nrf_desktop: Cleanup HIDS configuration

- doc/nrf/releases/release-notes-1.5.0.rst
- west.yml
Bring in updated documentation pages.
> manifest: doc: nrf_modem: updated documentation

- applications/nrf5340_audio/README.rst
- applications/nrf5340_audio/src/bluetooth/Kconfig
- applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
- applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
- doc/nrf/releases/release-notes-changelog.rst
- Will generate a Public Broadcast Announcement based on config
- Needed for Auracast
> applications: nrf5340_audio: Add PBA

- doc/kconfig/conf.py
- doc/mcuboot/conf.py
- doc/nrf/conf.py
- doc/nrfxlib/conf.py
Update conf.py files for the docsets in which we display copyright year.
> doc: update copyright year

- applications/nrf5340_audio/README.rst
- doc/nrf/releases/release-notes-changelog.rst
Added information about pressing VOL buttons to switch headsets. VSC-2396.
> doc: nrf5340audio: add info about vol button

- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_structs.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_tx.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fw_A/host_rpu_umac_if.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/event.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
- drivers/wifi/nrf700x/zephyr/inc/zephyr_twt.h
- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_twt.c
TWT block/unblock event handling support.
Signed-off-by: Ajay Parida <ajay.parida@nordicsemi.no>
> drives: wifi: TWT block/unblock support

- west.yml
Regular OpenThread update to \`23b5b28\`
> manifest: openthread: update to \`23b5b28\`

- doc/_scripts/software_maturity/software_maturity_features.yaml
Add Wi-Fi features to software maturity.
> doc: software_maturity: Add Wi-Fi features

- doc/nrf/ug_wifi.rst
> doc: Wi-Fi protocol: fixing link to infocenter

- doc/nrf/software_maturity.rst
This is pending on #9910 , so, only draft for now, once its merged will mark it ready for review.
> Wifi sw maturity table

- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_structs.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/event.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
- west.yml
Provide regulatory hints to RPU from user.
> wifi: Add regulatory configuration by user

- west.yml
This fixes duplicate (dis)connection events.
> manifest: sdk-hostap: Pull duplicate (dis)connection events fix

- applications/matter_weather_station/sample.yaml
- samples/matter/light_bulb/sample.yaml
- samples/matter/light_switch/sample.yaml
- samples/matter/lock/sample.yaml
- samples/matter/template/sample.yaml
- samples/matter/window_covering/sample.yaml
- scripts/quarantine.yaml
Selected configurations to build in integration jobs
> samples: matter: Configurations selection to build in integration tests

- samples/matter/common/src/ota_multi_image_downloader.cpp
- samples/matter/common/src/ota_multi_image_downloader.h
- samples/matter/common/src/ota_multi_image_processor_impl.cpp
- samples/matter/common/src/ota_multi_image_processor_impl.h
- samples/matter/common/src/ota_util.cpp
- samples/matter/lock/CMakeLists.txt
- samples/matter/lock/README.rst
- samples/matter/lock/prj_thread_wifi_switched.conf
- samples/matter/lock/src/combine_ota_images.py
Implemented of OTA DFU support for Thread/WiFi
switchable application. Added a utility script for combining
two Matter OTA files. Door lock sample docs update.
Signed-off-by: Marcin Kajor <marcin.kajor@nordicsemi.no>
> matter: multi variant application OTA DFU

- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/cmd.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
Recent changes have broken Rev-A
> Fix Rev-A UMAC init

- samples/wifi/radio_test/sample_description.rst
- samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
- Remove exclusivity checks for packet rate and mcs
- Reset any ongoing tests as part of init command 
- Address following JIRA issues: [SHEL-1160]
> wifi: Radio test enhancements

- west.yml
Pulls in a bunch of LwM2M fixes.
> manifest: update Zephyr to pull LwM2M fixes

- applications/nrf_desktop/README.rst
- applications/nrf_desktop/doc/usb_state.rst
Change introduces documentation for common HID device identifiers.
Jira: NCSDK-19101
> applications: nrf_desktop: Document common HID device identifiers

- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
Fix the out of index for source stream which cause the headset cannot set QoS properly after disconnected from gateway multiple times.
> applications: nrf5340_audio: Fix bidirectional headset QoS set failed

- west.yml
Update Zephyr for cherry-pick connection handling improvement.
> applications: nrf5340_audio: Update zephyr for fixing connection issue

- .github/workflows/docbuild.yml
- scripts/tools-versions-linux.txt
Use the latest version of Doxygen.
Signed-off-by: Gerard Marull-Paretas <gerard.marull@nordicsemi.no>
> doc: update to Doxygen 1.9.6

- .github/workflows/create-upmerge-PRs.yml
Attempting to fix action so that it can be used for simulating auto-upmerge in temporal branch.
Signed-off-by: Kari Hamalainen <kari.hamalainen@nordicsemi.no>
> ci: change target branch for auto-upmerge action

- samples/nrf9160/modem_shell/src/cloud/cloud_lwm2m.c
Added updating of LwM2M session lifetime to the configured value. Otherwise the server default value is taken into use when bootstrapping is used.
Removed unnecessary LwM2M RD client stop call after de-registration failure.
Moved LwM2M RD client stop calls from the event handler to work queue, because stopping the RD client from the event handler can cause problems.
> samples: nrf9160: modem_shell: add LwM2M session lifetime update

- doc/nrf/conf.py
- doc/nrf/index.rst
- doc/nrf/known_issues.rst
- doc/nrf/releases/release-notes-changelog.rst
Update doc versions after devtag 2.2.99dev1
> doc: Update doc versions after devtag 2.2.99dev1

- samples/crypto/sha256/src/main.c
Adds how to perform a hasing operation usinghte PSA multipart API's.
Signed-off-by: Markus Swarowsky <markus.swarowsky@nordicsemi.no>
> sample: sha256 add use of PSA multi-part API's

- west.yml
Mesh friendship fixes.
Signed-off-by: Alperen Sener <alperen.sener@nordicsemi.no>
> manifest: Update Zephyr for mesh fixes

- doc/nrf/conf.py
- doc/nrf/index.rst
- doc/nrf/known_issues.rst
- doc/nrf/releases/release-notes-changelog.rst
- doc/versions.json
Update doc versions for 2.2.99-dev2 tag
> doc: Update doc versions for 2.2.99-dev2 tag

- doc/nrf/conf.py
- doc/nrf/index.rst
- doc/nrf/known_issues.rst
- doc/nrf/releases/release-notes-changelog.rst
Update doc versions after 2.2.99 dev2
> Update doc versions after 2.2.99 dev2

- west.yml
Regular OpenThread update to \`2550699\`
> manifest: openthread: update to \`2550699\`

- applications/nrf_desktop/doc/hids.rst
- applications/nrf_desktop/src/modules/Kconfig.hids
The prompt can be used to allow user explicitly enable/disable module. Change also adds Bluetooth dependency.
Jira: NCSDK-19129
> applications: nrf_desktop: Add prompt to Kconfig option enabling HIDS

- doc/nrf/conf.py
- doc/nrf/index.rst
- doc/nrf/known_issues.rst
- doc/nrf/releases/release-notes-changelog.rst
Revert doc changes after 2.2.99-dev3.
> doc: revert doc changes after 2.2.99-dev3

- doc/nrf/libraries/modem/location.rst
- doc/nrf/libraries/networking/nrf_cloud_agps.rst
Added a link to documentation for filtered ephemerides.
NCSDK-12900
> doc: lib: location: add link for filtered ephemerides

- applications/asset_tracker_v2/Kconfig
Remove deprecated LOG_MODE entry.
> applications: asset_tracker_v2: Remove LOG_MODE Kconfig

- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
Added flow control to avoid occupied too many buffers.
OCT-2436
> applications: nrf5340_audio: Improve headset mic return flow

- applications/nrf5340_audio/src/bluetooth/ble_audio_services.c
- Added hw_codec_mute when VCS is disabled
- Added return values for hw_codec_volume decrease and increase
Signed-off-by: Khuong Huynh <khuong.huynh@nordicsemi.no>
> applications: nrf5340_audio: Bugfix volume mute

- west.yml
Regular OpenThread update to \`632b630\`
> manifest: openthread: update to \`632b630\`

- samples/openthread/cli/sample.yaml
> samples: openthread: rename twister variant

- .github/test-spec.yml
Updates the PR triggers for the lwm2m client sample.
> Update file patterns for zephyr lwm2m client sample

- .github/test-spec.yml
> Add file patterns for serial lte modem application

- west.yml
> manifest: sdk-hostap: Pull WPA2-PSK-SHA256 fix

- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/ug_thread_ot_memory.rst
- doc/nrf/ug_thread_overview.rst
- doc/nrf/ug_thread_power_consumption.rst
- samples/openthread/cli/README.rst
Create an "Openthread power consumption" page and populate it with nRF5340 data.
> doc: openthread: add power consumption data

- drivers/wifi/nrf700x/zephyr/inc/zephyr_fmac_main.h
- drivers/wifi/nrf700x/zephyr/inc/zephyr_net_if.h
- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
These are handy to debug data path issues.
> drivers: wifi: Implement Ethernet statistics

- doc/nrf/includes/application_build_and_run.txt
- doc/nrf/includes/application_build_and_run_ns.txt
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/shortcuts.txt
- doc/nrf/templates/application_README.rst
Added Applications template
NCSDK-17740
> doc: Add template for applications

- doc/nrf/introduction.rst
Add Wi-Fi and nRF70 Series in the introduction paragraph.
> doc: Update Introduction documentation

- drivers/wifi/nrf700x/zephyr/inc/zephyr_fmac_main.h
- drivers/wifi/nrf700x/zephyr/src/zephyr_disp_scan.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
[SHEL-822] Utility command to do passive scan.
> drivers: wifi: support for enabling passive scan.

- applications/nrf5340_audio/README.rst
Added note about the ongoing restructuring of the app. Added a section with new dependencies.
OCT-2256.
----
> doc: nrf5340: add note about reorg + update deps

- west.yml
Regular OpenThread update to \`5507465\`
> manifest: openthread: update to \`5507465\`

- applications/nrf5340_audio/README.rst
- applications/nrf5340_audio/src/audio/Kconfig
- applications/nrf5340_audio/src/audio/Kconfig.defaults
- applications/nrf5340_audio/src/audio/audio_datapath.c
- applications/nrf5340_audio/src/audio/streamctrl.c
- applications/nrf5340_audio/src/bluetooth/Kconfig
- applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
- applications/nrf5340_audio/src/bluetooth/le_audio.h
- applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/software_maturity.rst
- west.yml
Two headsets can now
receive audio from the gateway
and send audio to the gateway
> applications: nrf5340_audio: Implement bidirectional TWS

- applications/serial_lte_modem/CMakeLists.txt
- applications/serial_lte_modem/Kconfig
- applications/serial_lte_modem/doc/AT_commands_intro.rst
- applications/serial_lte_modem/doc/CARRIER_AT_commands.rst
- applications/serial_lte_modem/doc/slm_data_mode.rst
- applications/serial_lte_modem/doc/slm_description.rst
- applications/serial_lte_modem/overlay-carrier.conf
- applications/serial_lte_modem/sample.yaml
- applications/serial_lte_modem/src/lwm2m_carrier/CMakeLists.txt
- applications/serial_lte_modem/src/lwm2m_carrier/Kconfig
- applications/serial_lte_modem/src/lwm2m_carrier/slm_at_carrier.c
- applications/serial_lte_modem/src/lwm2m_carrier/slm_at_carrier.h
- applications/serial_lte_modem/src/slm_at_commands.c
- applications/serial_lte_modem/src/slm_util.c
- applications/serial_lte_modem/src/slm_util.h
- doc/nrf/releases/release-notes-changelog.rst
Adding carrier support to application update sample and serial lte modem application.
> applications: serial_lte_modem: Add support for Carrier Library

- applications/nrf5340_audio/src/bluetooth/Kconfig
- applications/nrf5340_audio/src/bluetooth/le_audio_bis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
- doc/nrf/releases/release-notes-changelog.rst
- Add config for interleaved packing
- Dependent on controller version 3314 or newer
> applications: nrf5340_audio: Add support for interleaved packing

- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
- drivers/wifi/nrf700x/zephyr/inc/zephyr_ps.h
- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_ps.c
- west.yml
[SHEL-1126] Setting power save inactivity timer to user provided value.
Signed-off-by: Ajay Parida <ajay.parida@nordicsemi.no>
> drivers: wifi: Configure power save inactivity timer

- subsys/net/lib/download_client/src/http.c
Use `strnstr()` to avoid scanning past the client buffer.
> net: lib: download_client: use `strnstr` instead of `strstr`

- tests/crypto/test_cases/test_aes_cbc.c
- tests/crypto/test_cases/test_aes_ctr.c
- tests/crypto/test_cases/test_aes_ecb.c
- tests/crypto/test_cases/test_ecdsa.c
- tests/nrf5340_audio/sw_codec_lc3/readme.txt
Fied typos in some tests source files.
Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>
> tests: Fixed typos in some tests source files

- doc/nrf/protocols/matter/end_product/certification.rst
Rearrange Matter certification documentation.
Signed-off-by: Lukasz Duda <lukasz.duda@nordicsemi.no>
> [doc] rearrange Matter certification section

- doc/nrf/app_dev.rst
- doc/nrf/app_dev/ap_protect/index.rst
- doc/nrf/links.txt
- doc/nrf/protocols/matter/end_product/index.rst
- doc/nrf/protocols/matter/end_product/security.rst
- doc/nrf/protocols/matter/getting_started/hw_requirements.rst
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/security.rst
Added doc sections about access port protection mechanism. KRKNWK-15936.
> doc: matter: add info about approtect

- applications/matter_weather_station/README.rst
- doc/nrf/libraries/networking/lwm2m_location_assistance.rst
- drivers/sensor/bh1749/Kconfig
- lib/st25r3911b/st25r3911b_dt.h
- subsys/bootloader/Kconfig
> nrf: fixed typos in various files

- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_tx.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
These two fixes are pulled in from main_host(fixed during certification testing related to multiple access categories).
> Tx spare desc fix

- applications/nrf_desktop/Kconfig.debug
Change introduces Kconfig menu for debug options to improve user experience in menuconfig.
Jira: NCSDK-19655
> applications: nrf_desktop: Introduce Kconfig menu for debug options

- applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
OCT-2437
Correction to the switching between  broadcast sources.
The routine will be triggered on a press of button 5, causing the current source to be stopped and removed. It will next update the source name to the alternative name in the broadcast source names list. The stream will then sync and start playing, if available.
Previously the system would fail on a change of broadcast source, this was not deterministic, but rather dependent on when the change was initiated. The issue was a buffer overrun on the stack and depending on the call sequence could cause the failure. This has now been corrected and the routing generally made more robust.
Signed-off-by: Graham Wacey <graham.wacey@nordicsemi.no>
> applications: nrf5340_audio: Switching broadcast sources correction

- doc/nrf/links.txt
- doc/nrf/protocols/matter/getting_started/adding_clusters.rst
- doc/nrf/releases/release-notes-changelog.rst
- scripts/requirements-build.txt
- west.yml
* Pulled new sdk-connectedhomeip revision to get helper script
* Updated Matter adding clusters guide to recommend downloading ZAP package from github releases.
* Fixed MatterPostAttributeChangeCallback method API in the Matter adding clusters guide.
> doc: Updated guide about ZAP tool usage

- doc/nrf/working_with_nrf/nrf70/developing/images/nRF70_ug_twt_wake_interval.svg
- doc/nrf/working_with_nrf/nrf70/developing/powersave.rst
Updated some sections of operating in power save modes ug
SHEL-1236
> doc: update Operating in power save modes user guide

- doc/nrf/app_dev/optimizing/power.rst
- doc/nrf/releases/release-notes-changelog.rst
Added a new chapter in the application power optimization documentation for Power Saving Mode (PSM) usage.
> doc: nrf: add documentation for PSM usage

- doc/nrf/templates/Ecosystem_integration_template_README.rst
- doc/nrf/templates/application_README.rst
Updates on the following templates:
* Template: Ecosystem integration
* Template: Application
> doc improvement: updates on template

- doc/nrf/releases/release-notes-changelog.rst
Change updates release notes before the NCS 2.3 release.
Jira: NCSDK-19128
> applications: nrf_desktop: Update release notes

- doc/nrf/libraries/bin/lwm2m_carrier/index.rst
- samples/nrf9160/lwm2m_carrier/sample_description.rst
Added some fixes and clarifications to the LwM2M carrier library usage.
Signed-off-by: Håvard Vermeer <havard.vermeer@nordicsemi.no>
> doc improvement: updated documentation for the LwM2M carrier library

- applications/nrf5340_audio/src/audio/audio_datapath.c
- applications/nrf5340_audio/src/modules/audio_i2s.c
- Added conditions for checking "ASSERTS"
- Added conditions for starting RX/TX I2S
Signed-off-by: Khuong Huynh <khuong.huynh@nordicsemi.no>
> applications: nrf5340_audio: Bugfix I2S RX overrun

- doc/nrf/external_comp/bt_fast_pair.rst
- doc/nrf/libraries/bluetooth_services/services/fast_pair.rst
Updates the Fast Pair documentation to reflect the current progress.
Jira: NCSDK-19617
> doc: fast_pair: Update the documentation

- doc/nrf/index.rst
- doc/nrf/introduction.rst
Added nRF70 and Wi-Fi to Welcome and Index pages.
> doc improvement: updates on Welcome and Index pages

- lib/nrf_modem_lib/nrf91_sockets.c
POLLNVAL was not offloaded in the new implementation.
> lib: nrf_modem: add POLLNVAL to new poll() offloading

- doc/nrf/links.txt
- doc/nrf/protocols/matter/getting_started/advanced_kconfigs.rst
Added additional info about Amazon's FFS on the Matter page.
> doc improvement: matter: expand info about FFS

- doc/nrf/app_dev/ap_protect/index.rst
Edited tables to better present the contents.
> doc: approtect: minor style edits

- west.yml
Openthread upmerge to include fixes for CSL retransmissions bug.
> manifest: openthread: openthread upmerge to `2060039`.

- doc/nrf/protocols/matter/getting_started/index.rst
- doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
- doc/nrf/protocols/wifi/index.rst
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/samples/matter.rst
Added a new page describing how to reduce power consumption in the Matter samples and applications.
> doc: Added a guide describing low power configuration for Matter

- applications/serial_lte_modem/doc/Generic_AT_commands.rst
- applications/serial_lte_modem/doc/slm_testing.rst
- applications/serial_lte_modem/src/slm_at_commands.c
- doc/nrf/releases/release-notes-changelog.rst
Add to report the version of the modem library.
Correct mistakes in doc for this command.
> application: serial_lte_modem: Update #XSLMVER command

- applications/nrf_desktop/README.rst
- doc/nrf/getting_started/modifying.rst
- doc/nrf/shortcuts.txt
Change introduces documentation improvements for the NCS 2.3 release.
Jira: NCSDK-19128
> applications: nrf_desktop: Miscellaneous documentation improvements

- applications/serial_lte_modem/doc/DFU_AT_commands.rst
- applications/serial_lte_modem/src/dfu/dfu_host.c
- applications/serial_lte_modem/src/dfu/slm_at_dfu.c
- doc/nrf/releases/release-notes-changelog.rst
This PR is placeholder for SLM to DFU nRF52 and nRF53 which includes several enhancements.
Signed-off-by: Pirun Lee <pirun.lee@nordicsemi.no>
> application: serial_lte_modem: nRF52 DFU add crc checksum

- samples/wifi/shell/README.rst
[SHEL-1208] Update help text to provide information for ps_mode and reg_domain commands in wifi shell
> samples: wifi: Update command output and help

- applications/nrf_desktop/doc/bas.rst
- applications/nrf_desktop/doc/ble_discovery.rst
- applications/nrf_desktop/doc/ble_scan.rst
- applications/nrf_desktop/doc/ble_state_pm.rst
- applications/nrf_desktop/doc/buttons_sim.rst
- applications/nrf_desktop/doc/click_detector.rst
- applications/nrf_desktop/doc/config_channel.rst
- applications/nrf_desktop/doc/hid_forward.rst
- applications/nrf_desktop/doc/hid_state.rst
- applications/nrf_desktop/doc/hid_state_pm.rst
- applications/nrf_desktop/doc/hids.rst
- applications/nrf_desktop/doc/leds.rst
- applications/nrf_desktop/doc/power_manager.rst
- applications/nrf_desktop/doc/settings_loader.rst
- applications/nrf_desktop/doc/usb_state.rst
- applications/nrf_desktop/doc/usb_state_pm.rst
Change introduces application module's documentation improvements for the NCS 2.3 release.
Jira: NCSDK-19128
> applications: nrf_desktop: Module documentation improvements

- west.yml
This is a regular rewrite of history onto the latest upstream merge-base, applying cleanups to downstream patches as necessary.
> west.yml: rebase most OSS trees for NCS v2.3

- doc/nrf/getting_started/recommended_versions.rst
- doc/nrf/links.txt
- doc/nrf/shortcuts.txt
- doc/nrf/working_with_nrf/nrf52/gs.rst
- doc/nrf/working_with_nrf/nrf53/nrf5340_gs.rst
- doc/nrf/working_with_nrf/nrf53/thingy53_gs.rst
- doc/nrf/working_with_nrf/nrf91/nrf9160_gs.rst
- doc/nrf/working_with_nrf/nrf91/thingy91_gsg.rst
Updated Supported OS table with
MacOS 13 details.
Also updated the GS of working with pages.
Requested by Ingar Hanssen
> doc improvement: updates on Supported OS table

- drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_mgmt.c
[SHEL-1326] TWT sleep status update.(Missed during converging to single file)
> driver: wifi: TWT status update

- west.yml
- Includes bugfix for PA sync in broadcast_sink
> manifest: Update sdk-zephyr to include bugfix

- applications/nrf5340_audio/src/bluetooth/ble_audio_services.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
- Moved to lc3_configured_cb
- OCT-2371
> applications: nrf5340_audio: Move MCS discover

- doc/nrf/known_issues.rst
Due to conflict with latest MCUBOOT.
> doc: known_issues: SLM RTT logging issue

- doc/_scripts/software_maturity/software_maturity_features.yaml
> doc: scripts: software_maturity: fix typo

- doc/nrf/software_maturity.rst
Updated feature support matrix for nRF5340 Audio app. OCT-2462.
> doc improvement: nrf5340audio: update feature list

- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
Fixed play/pause not work properly in CIS mode.
> applications: nrf5340_audio: Fix play/pause not work in CIS mode

- lib/nrf_modem_lib/nrf91_sockets.c
- west.yml
Update manifest for nrf_modem v2.3.1 release.
> manifest: nrf_modem v2.3.1

- applications/nrf5340_audio/src/bluetooth/ble_audio_services.c
- Added a bool to only do the discover callback when mcs_discover has been called
> applications: nrf5340_audio: Bugfix for MCS discover

- samples/nfc/writable_ndef_msg/src/main.c
- west.yml
With fix for nrf5340 errata 160.
> mpsl: Updating mpsl

- west.yml
Update manifest file for v1.9.2-dev1 tag.
> manifest: Update manifest file for v1.9.2-dev1 tag

- drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.h
> drivers: wifi: Fix compilation warnings

- west.yml
Updates sdk-mcuboot to fix an issue whereby the configuration is not cleaned up and could cause an unbootable application in some circumstances.
> manifest: Update sdk-mcuboot revision

- doc/nrf/index.rst
- doc/nrf/known_issues.rst
- doc/nrf/links.txt
- doc/nrf/release_notes.rst
- doc/nrf/releases/release-notes-1.9.0.rst
- doc/nrf/releases/release-notes-1.9.1.rst
- doc/nrf/releases/release-notes-1.9.2.rst
- doc/nrf/releases/release-notes-2.3.0.rst
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/shortcuts.txt
- samples/bluetooth/nrf_dm/README.rst
Update the release notes and some related files for the release.
> doc: release notes for nRF Connect SDK 2.3.0

- doc/nrf/conf.py
- doc/nrf/developing/adding_code.rst
- doc/nrf/shortcuts.txt
- doc/nrfxlib/conf.py
- doc/versions.json
- west.yml
Updates in doc related to new release.
> doc: update doc version for NCS 2.3.0

- west.yml
> manifest: NCS 2.3.0

- doc/nrf/conf.py
- doc/nrf/index.rst
- doc/nrf/known_issues.rst
- doc/nrf/release_notes.rst
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrfxlib/conf.py
- doc/versions.json
Changes in doc files after the release.
> doc: 2.3.0 post-release doc update

- modules/nrfxlib/nrf_802154/sl/platform/nrf_802154_platform_sl_lptimer_zephyr.c
In case the `nrf_802154_platform_sl_lptimer_hw_task_update_ppi` is called very delayed it might happen that isr related for hw_task has already been executed thus, the `cc_event_check` won't detect too late attempt of updating ppi. This commit fixes detection of too late attempt of ppi update.
> modules: nrf_802154: fix lptimer_hw_task_update_ppi

- doc/nrf/external_comp/nrf_cloud.rst
Add additional details about nRF Cloud's capabilities. IRIS-5237
> doc: nrf: add more detail to nrf cloud integration guide

- samples/nrf9160/modem_shell/src/cloud/cloud_mqtt_shell.c
If connecting to nRF Cloud using MQTT failed, "cloud disconnect" did not stop reconnection attempts but mosh kept trying to connect forever.
> samples: nrf9160: modem_shell: Fix nRF Cloud MQTT reconnect loop

- subsys/net/openthread/Kconfig.defconfig
- west.yml
Regular OpenThread update to \`0a79c30\`
> manifest: openthread: update to \`0a79c30\`

- doc/nrf/links.txt
- samples/nrf9160/lwm2m_client/README.rst
- samples/nrf9160/lwm2m_client/fota.rst
- samples/nrf9160/lwm2m_client/scripts/coiote.py
- samples/nrf9160/lwm2m_client/scripts/fota.py
Added possibility to test Fota update with Coiote Device management server by REST API:
* Upload binaries to Coiote server
* Update firmware by given binary or Coiote resource ID
* Multi instance update for update both
* test cancel operation
* test update multi instance separately
Documented Advanced Firmware object and FOTA helper scripts.
> samples: lwm2m_client: FOTA python script's

- doc/nrf/getting_started/installing.rst
- doc/nrf/known_issues.rst
- doc/nrf/links.txt
- doc/nrf/migration/migration_guide_1.x_to_2.x.rst
- doc/nrf/releases/release-notes-2.0.0.rst
- doc/nrf/shortcuts.txt
- samples/nrf9160/lwm2m_client/sample_description.rst
Edited "Add an existing application" to "Open...". This follows changes in the VSC docs and extension. VSC-1409.
----
> doc: vsc: modify option name

- scripts/quarantine_windows.yaml
Test names changed and new native_posix samples added for asstet_tracker_v2.
> quarantine_windows: update for asset_tracker_v2 samples

- applications/nrf5340_audio/src/audio/Kconfig
- applications/nrf5340_audio/src/bluetooth/ble_audio_services.c
- applications/nrf5340_audio/src/bluetooth/ble_audio_services.h
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
Changed media control profile and service on the application side. This is to avoid the fault in birdir mode
OCT-2472
> applications: nrf5340_audio: mcc_mcp_refactor

- subsys/net/lib/rest_client/src/rest_client.c
Even if DNS takes much longer than given timeout, we continue to create and connect socket after that. Unfortunately, we cannot cancel DNS query so that may still take more than given timeout.
JIRA: MOSH-421
> net: rest_client: Add timeout check after DNS query

- doc/nrf/shortcuts.txt
Edited the shortcuts.txt for the updated zboss version.
> doc: zigbee: update zboss versions

- doc/_extensions/software_maturity_table.py
Added the following options to the `sml-table` directive: `:remove-columns:`
`:remove-rows:`
`:add-columns:`
`:add-rows:`
`:insert-values:`
These options will remove, add and override existing values in a table.
> doc: sml: added options to customize table

- doc/nrf/working_with_nrf/nrf52/developing.rst
- doc/nrf/working_with_nrf/nrf91/nrf9160.rst
- doc/nrf/working_with_nrf/nrf91/thingy91.rst
- samples/nrf9160/lwm2m_client/sample_description.rst
update VSC-related step in the LwM2M client sample NCSDK-20259
> doc: update VSC-related step in the LwM2M client sample

- applications/nrf_desktop/src/hw_interface/selector_hw.c
Change fixes port index calculation in selector_isr function.
Jira: NCSDK-20366
> applications: nrf_desktop: Fix ISR handling in selector_hw

- subsys/bluetooth/controller/hci_driver.c
> bluetooth: fixed config name

- doc/nrf/protocols/bt_mesh/configuring.rst
Extended documentation for additional configuration options in Bluetooth Mesh configuration page.
> doc: Bluetooth: Mesh: Extended additional configuration options

- applications/nrf5340_audio/src/drivers/cs47l63_comm.c
- Remove ERR_CHKs from cs47l63_comm.c
- OCT-2467
> applications: nrf5340_audio: Remove dependency from driver

- applications/nrf5340_audio/src/audio/audio_datapath.c
- Fixed bug where wrong define was used in audio_datapath.c
- Added possibility to store 32 bit samples in fifo
- OCT-2486
> applications: nrf5340_audio: Bugfix 32 bit configuration

- doc/_scripts/software_maturity/software_maturity_features.yaml
> doc: sml: Add SR co-existence entry

- west.yml
Regular OpenThread update to \`2d0d9be\`
> manifest: openthread: update to \`2d0d9be\`

- doc/nrf/conf.py
- doc/nrf/dm_adding_code.rst
- doc/nrf/known_issues.rst
- doc/nrf/links.txt
- doc/nrf/release_notes.rst
- doc/nrf/releases/release-notes-2.1.4.rst
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/shortcuts.txt
- doc/nrfxlib/conf.py
- doc/versions.json
Update doc versions, known issues, add release notes for 2.1.4
> doc: Update doc versions, add release notes for 2.1.4

- drivers/wifi/nrf700x/zephyr/inc/zephyr_wifi_mgmt.h
- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_mgmt.c
* Fix TWT Flow dumping
* Convert data types properly b/w wifi_mgmt and RPU
> TWT command and event fixes

- west.yml
> manifest: NCS 2.1.4

- subsys/bluetooth/controller/hci_internal.c
- west.yml
Add support for RF path compensation.
> manifest: bluetooth: Update SDC and MPSL libraries.

- doc/nrf/links.txt
- doc/nrf/protocols/matter/index.rst
- doc/nrf/protocols/matter/overview/dev_model.rst
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/software_maturity.rst
Added feature support matrices for different Matter versions. KRKNWK-16580.
> doc: matter: add feature support matrix

- samples/matter/lock/sample.yaml
Update samples.yaml to get switchable samples for system tests
> samples: matter: Update for switchable device system tests

- west.yml
Brings in the latest SDC changes.
> bluetooth: update nrfxlib revision

- doc/nrf/links.txt
- doc/nrf/protocols/matter/end_product/certification.rst
- doc/nrf/protocols/wifi/index.rst
Cherry-picked commits from https://github.com/nrfconnect/sdk-nrf/pull/10624 to be included in v.2.3.1.
> doc: cherry-pick Wi-Fi certification info commits

- doc/nrf/releases/release-notes-changelog.rst
- include/net/nrf_cloud.h
- subsys/net/lib/nrf_cloud/include/nrf_cloud_codec_internal.h
- subsys/net/lib/nrf_cloud/src/nrf_cloud.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_agps.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_alerts.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_fsm.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_location.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_pgps.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_rest.c
- tests/subsys/net/lib/nrf_cloud/cloud/src/fakes.h
- tests/subsys/net/lib/nrf_cloud/cloud/src/main.c
Standardize the naming of the encode and decode functions in nrf_cloud lib.
NCSDK-19174
> Standardize codec function names in nrf_cloud lib

- subsys/net/lib/nrf_cloud/src/nrf_cloud_agps.c
If A-GPS data ended unexpectedly, the parser was left in invalid state and following calls to nrf_cloud_agps_process() behaved incorrectly. The implementation now checks that there's enough data left so that the next element can be parsed.
> net: lib: nrf_cloud_agps: Make parser tolerant for invalid data

- west.yml
Regular OpenThread update to \`a4f1c7a\`
> manifest: openthread: update to \`a4f1c7a\`

- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_tx.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
Return value and type cleanup.
> wifi: Tx cleanup

- applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
Added small bugfix to check if Rx size is the same as codec
OCT-2399
> applications: nrf5340_audio: Bugfix packet size check

- .github/test-spec.yml
Audio related libraries and tests added
Signed-off-by: Kristoffer Rist Skøien <kristoffer.skoien@nordicsemi.no>
> labeler: Adding nrf5340_audio libs

- applications/nrf5340_audio/src/bluetooth/ble_audio_services.c
- Cleaned up the usage of #if
- Added functionality for ble_vcs_vol_set
OCT-2406
> applications: nrf5340_audio: Improve ble_audio_services

- applications/nrf5340_audio/README.rst
- doc/nrf/known_issues.rst
Added info about the error that happens after charging for more than 7h. OCT-2502.
> doc: nrf5340_audio: 7-hour charging error line

- CODEOWNERS
Remove Veijo Pesonen from CODEOWNERS.
> CODEOWNERS: Remove Veijo Pesonen

- doc/_scripts/software_maturity/software_maturity_features.yaml
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/software_maturity.rst
Points to table for Bluetooth hardware feature support.
> doc: bluetooth: Add feature support for Bluetooth.

- doc/nrf/libraries/modem/location.rst
Mention obstructed visibility detection in the list of location lib features. Some language and formatting tweaks.
> lib: location: mention visibility detection in the list of features

- west.yml
Adding Encrypted ITS.
Ref: NCSDK-19574
test-sdk-nrf: sdk-nrf-pr-10585
> manifest: TF-M: ITS add encryption

- samples/matter/lock/sample.yaml
NUS config changed so passkey has fixed value
> samples: matter: NUS fixed passkey added

- west.yml
Regular OpenThread update to \`2c8a0af\`
> manifest: openthread: update to \`2c8a0af\`

- samples/crypto/psa_tls/README.rst
- samples/nfc/record_launch_app/README.rst
Minor style improvements and corrections for some Sample pages.
> doc improvement: samples

- CODEOWNERS
- west.yml
Replace @sr1dh48r with @rado17.
> CODEOWNERS: Update Wi-Fi Host assignments

- doc/nrf/links.txt
- doc/nrf/releases/release-notes-changelog.rst
- samples/peripheral/radio_test/src/radio_test.c
Add workaround for nRF5340 errata chip in radio_test sample.
Jira: NCSDK-20674
> samples: radio_test: Add workaround for errata 117

- .checkpatch.conf
Added directories with images to checker exclude list.
> compliance: add image dirs to checker exclude

- drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
When there are multiple interfaces in the system the IP event handler should check if the device is ours before processing the private data.
This fixes a crash when netusb is enabled.
> drivers: wifi: Fix IP event handling

- samples/wifi/sr_coex/Kconfig
Change Wi-Fi peer address to match hardcoded IP address in the CI setup.
> samples: wifi: sr_coex: Change Wi-Fi peer IP address

- applications/zigbee_weather_station/README.rst
- doc/nrf/releases/release-notes-changelog.rst
The application descriptions in the nRF Connect SDK are being unified. This updates the Zigbee weather station's to match the new template. Also does some general language updates.
> doc: update Zigbee weather station description

- doc/nrf/working_with_nrf/nrf70/developing/constrained.rst
Thanks @kkasperczyk-no for pointing out.
> wifi: Fix nrf700x docs

- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
- drivers/wifi/nrf700x/osal/hw_if/hal/inc/fw/rpu_if.h
- drivers/wifi/nrf700x/osal/hw_if/hal/inc/hal_api.h
- drivers/wifi/nrf700x/osal/hw_if/hal/src/hal_api.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
[SHEL-1351] Utility command to get the current rpu power save state.
> driver: wifi: Utility command to get rpu power save state

- doc/nrf/libraries/networking/nrf_cloud_alerts.rst
An ordered list was a bit wrong.
Now fixed and verified being better.
> doc: nRF Cloud Alerts lib: formatting fix

- samples/event_manager_proxy/prj.conf
- samples/event_manager_proxy/prj_icmsg.conf
removing unnecessary defaults.
> samples: event manager proxy rework followup

- doc/nrf/libraries/networking/azure_iot_hub.rst
This PR reduces the number of consecutive
notes, hopefully making the doc a bit more
readable.
> doc: Azure IoT Hub lib: reducing the number of notes

- drivers/wifi/nrf700x/Kconfig.nrf700x
- drivers/wifi/nrf700x/zephyr/src/shim.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_work.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_work.h
* Separate workqueue for IRQ and BH processing to avoid serialization
* Configurable priorities
> wifi: A few RX improvements

- modules/trusted-firmware-m/Kconfig.mbedtls_minimal.defconfig
- west.yml
Update Mbed TLS and dependencies to version 3.3.0.
> manifest: Update Mbed TLS to version 3.3.0

- scripts/west_commands/ncs_commands.py
> scripts: Make ncs-upmerger signoff on reverts

- subsys/bluetooth/controller/Kconfig
> bluetooth: Update PAwR sync kconfig

- doc/nrf/releases/release-notes-changelog.rst
> doc: changelog fixes

- tests/subsys/bluetooth/mesh/scheduler_model/message_validity/src/main.c
Fixed bug where ctx was passed as NULL to scheduler client api without any defined publish parameters, triggering a segmentation fault in model_ackd_timeout_get.
Note: I hope that this will fix the bug reported by @balaji-nordic, however, I am not able to reproduce the bug locally to verify.
> Bluetooth: Mesh: Fix in scheduler message validity test

- .github/workflows/docbuild.yml
- .github/workflows/docpublish.yml
Monitor file was not being uploaded. Pack it in the archive and add it to the upload list.
> ci: doc: add missing monitor file

- .github/workflows/create-upmerge-PRs.yml
Add bsim to list of updated repos.
**NOTE: Compliance problems were already there, I have not touched the lines that are making problems**
> scripts: Fix missing bsim update in auto-upmerge workflow

- doc/nrf/protocols/matter/end_product/bootloader.rst
- doc/nrf/protocols/matter/getting_started/hw_requirements.rst
- doc/nrf/releases/release-notes-changelog.rst
This commit including tech writer review was accidentally removed in the #10783 PR.
> doc: Fixed Matter documentation related to settings size change.

- doc/nrf/app_dev/build_and_config_system/index.rst
mentioned nRF Cloud in FOTA instructions.
Related to Jira NCSIDB976.
> doc: FOTA images small fix

- applications/nrf5340_audio/src/bluetooth/Kconfig
- applications/nrf5340_audio/src/bluetooth/ble_core.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
- lib/bin/bt_ll_acs_nrf53/include/ble_hci_vsc.h
- lib/bin/bt_ll_acs_nrf53/src/ble_hci_vsc.c
For when nRF21540 is not active
OCT-2196
> applications: nrf5340_audio: Bring back TX power feature

- boards/arm/nrf52810dmouse_nrf52810/board.cmake
- boards/arm/nrf52820dongle_nrf52820/board.cmake
- boards/arm/nrf52833dongle_nrf52833/board.cmake
- boards/arm/nrf52840gmouse_nrf52840/board.cmake
- boards/arm/nrf52dmouse_nrf52832/board.cmake
- boards/arm/nrf52kbd_nrf52832/board.cmake
PR aligns nRF Desktop boards' `board.cmake` files to new convention.
Jira: NCSDK-21090
> boards: Align nRF Desktop boards' board.cmake files to new convention

- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
Set channel allocation properly according to the headset allocation. 
OCT-2400
> applications: nrf5340_audio: Fix channel allocation setting

- applications/nrf5340_audio/src/bluetooth/ble_audio_services.c
OCT-2485
Added new print which is more readable
> applications: nrf5340_audio: discover finsihed check added

- modules/trusted-firmware-m/Kconfig.psa.defconfig
- west.yml
Update manifest for nrfxlib to pull in nrf_security minor fixes.
> manifest: Pull nrf_security fixes

- applications/nrf5340_audio/src/audio/audio_datapath.c
- applications/nrf5340_audio/src/audio/audio_system.c
- applications/nrf5340_audio/src/audio/streamctrl.c
- applications/nrf5340_audio/src/bluetooth/ble_core.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
- applications/nrf5340_audio/src/main.c
Cleanup after current architecture
figure review. Removed some
dependencies
> applications: nrf5340_audio: Cleanup after curr arch review

- doc/nrf/known_issues.rst
Added description about DRGN-18651 bug
> doc: update SDC known issues

- drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
Add command in wifi_util shell to display firmware version.
> drivers: wifi: Display firmware version

- applications/serial_lte_modem/src/slm_at_host.c
Async NRF UART returns error, if enabling UART RX before disabling is completed. Delay calling UART RX enable, if disabling is ongoing.
Fixes timing issue related to: https://github.com/nrfconnect/sdk-nrf/pull/10535 for which we needed to disable some of our CI tests. 
To be merged after upmerge is completed.
> application: serial_lte_modem: FIX UART RX disable timing issue.

- drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
[SHEL-1552] As firmware can handle ltf and gi setting dynamically allow the values to set without resetting.
> drivers: wifi: Allow ltf and gi to set dynamically

- samples/bluetooth/direction_finding_central/README.rst
- samples/bluetooth/direction_finding_connectionless_rx/README.rst
- samples/bluetooth/direction_finding_connectionless_tx/README.rst
- samples/bluetooth/direction_finding_peripheral/README.rst
Cleaning up the wording, formatting, and
reusing identical text chunks as much as possible.
> doc: BT direction finding samples: cleanup and reuse

- samples/bluetooth/enocean/README.rst
- samples/bluetooth/hci_lpuart/README.rst
- samples/bluetooth/llpm/README.rst
- samples/bluetooth/multiple_adv_sets/README.rst
- samples/bluetooth/nrf_dm/README.rst
- samples/bluetooth/radio_coex_1wire/README.rst
- samples/bluetooth/rpc_host/README.rst
- samples/bluetooth/shell_bt_nus/README.rst
- samples/bluetooth/throughput/README.rst
Some rewordings and formatting fixes to the
remaining sample docs (excluding Mesh).
> doc: Cleaning up the rest of the Bluetooth samples

- doc/nrf/known_issues.rst
Added a known issue KRKNWK-16783 that affects Matter reliability.
> doc: update Matter known issues

- samples/bluetooth/central_and_peripheral_hr/README.rst
- samples/bluetooth/central_bas/README.rst
- samples/bluetooth/central_hids/README.rst
- samples/bluetooth/central_hr_coded/README.rst
- samples/bluetooth/central_nfc_pairing/README.rst
- samples/bluetooth/central_smp_client/README.rst
- samples/bluetooth/central_uart/README.rst
Some rewordings and formatting fixes to various
BT Central sample docs.
> doc: BT Central samples: cleaning up

- west.yml
Updated Matter revision to pull workaround solving problem with occassional stucks during Wi-Fi re-connection process.
> manifest: Pulled Wi-Fi reconnection fix for Matter over Wi-Fi

- applications/nrf5340_audio/src/audio/audio_datapath.c
- Added Shell command for enabling/disabling pres comp
- Removed #if and added boolean for pres_comp struct
- Added if condition for when pres/drift comp are called upon
OCT-2250
> applications: nrf5340_audio: presentation/drift comp changes

- scripts/hid_configurator/modules/dfu.py
Change introduces support for MCUboot bootloader built in direct-xip mode.
Jira: NCSDK-20586
> scripts: hid_configurator: Add MCUboot direct-xip mode support

- doc/nrf/known_issues.rst
Add a new known issue related to periodic advertiser and periodic sync to the known issues for the Sofdevice Controller.
> Doc: Add a known issue for the SDC

- lib/modem_slm/modem_slm.c
Upmerge caused a timing change where UART_RX_BUF_REQUEST comes before uart_rx_enable completes. Set next_buf before calling uart_rx_enable.
> lib: modem_slm: Fix modem SLM rx timing issue.

- CODEOWNERS
Replaced @SebastianBoe with @oyvindronningstad in samples/bootloader
Replaced @SebastianBoe with @sigvartmh in subsys/bootloader
> CODEOWNERS: Update bootloader assignments

- applications/nrf5340_audio/dfu/conf/Kconfig.dfu
- applications/nrf5340_audio/src/drivers/Kconfig
- applications/nrf5340_audio/src/utils/Kconfig
> applications: nrf5340_audio: Fix help text format in some files

- .github/workflows/docpublish.yml
> ci: docpublish: fix EOF

- doc/nrf/developing/code_base.rst
- doc/nrf/introduction.rst
edited versions and revisions section.
related to Jira NCSDK20957.
> doc: revisions info adjustments

- samples/nrf9160/modem_shell/src/cloud/cloud_lwm2m.c
There was a race condition with nRF modem library and LwM2M initialization, sometimes causing the reading of IMEI to fail. `cloud_lwm2m_init()` is now called using `NRF_MODEM_LIB_ON_INIT()` to make sure modem library has been initialized before trying to read the IMEI.
> samples: nrf9160: modem_shell: fix LwM2M initialization

- lib/hw_unique_key/hw_unique_key_kmu.c
Refactor to use nrfx_nvmc_uicr_word_read instead of a copy of the implementation.
> hw_unique_key: Refactor to use nrfx_nvmc_uicr_word_read

- west.yml
Pull error handling fix done in connection info fetch.
> manifest: sdk-hostap: Pull conn info error handling fix

- subsys/bluetooth/controller/hci_internal.c
The command complete event is generated by the controller, unless the feature is disabled, in which case it's generated by the hci driver.
> bluetooth: fix padv response data command status when not supported

- applications/serial_lte_modem/src/slm_at_fota.c
- Too long URL causes buffer overflow and crash
> application: serial_lte_modem: Add URL size check to Fota

- west.yml
Pull fix for QT certification SAE exchange variation test (10317).
> manifest: sdk-hostap: Pull WPA3-SAE fix

- applications/nrf5340_audio/src/audio/streamctrl.c
- applications/nrf5340_audio/src/bluetooth/Kconfig
- applications/nrf5340_audio/src/bluetooth/le_audio.h
- applications/nrf5340_audio/src/bluetooth/le_audio_bis_headset.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
applications: nrf5340_audio: Added bad frame info to print
OCT-2562
> applications: nrf5340_audio: Added bad frame info to print

- samples/wifi/provisioning/README.rst
- samples/wifi/radio_test/sample_description.rst
- samples/wifi/scan/README.rst
- samples/wifi/shell/README.rst
- samples/wifi/sr_coex/README.rst
- samples/wifi/sta/README.rst
Added configuration sections with
sample-specific Kconfig options.
Also other minor fixes.
Ref: NCSDK-21383
> doc: Wi-Fi sample docs clean up

- doc/nrf/templates/cheat_sheet.rst
Updating the cheatsheet to create a busy topic.
> doc: add busy topic with RST elements

- doc/nrf/getting_started.rst
- doc/nrf/getting_started/assistant.rst
- doc/nrf/getting_started/installing.rst
- doc/nrf/getting_started/modifying.rst
- doc/nrf/getting_started/programming.rst
- doc/nrf/getting_started/testing.rst
- doc/nrf/getting_started/updating.rst
- doc/nrf/glossary.rst
- doc/nrf/links.txt
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/samples.rst
- doc/nrf/shortcuts.txt
- doc/nrf/working_with_nrf/nrf52/developing.rst
- doc/nrf/working_with_nrf/nrf53/nrf5340.rst
- doc/nrf/working_with_nrf/nrf53/thingy53.rst
- doc/nrf/working_with_nrf/nrf91/nrf9160.rst
- doc/nrf/working_with_nrf/nrf91/thingy91.rst
Edited Getting Started doc pages.
Removed duplicated info and simplified some structure. Moved information to more relevant sections.
Added minor clarifications.
----
> doc: gs: small spring cleanup

- subsys/bluetooth/controller/Kconfig
Make relevant config changes for the softdevice controller.
> Bluetooth: Controller: Update kconfig for PAwR

- west.yml
Which includes changes to align it with the latest NCS/Zephyr
> manifest: Update dragoon to latest

- west.yml
Commits updates sdk zephyr with cherrypicks form zephyr implementing PSA openthread api and cleanning up kconfig options.
> manifest: zephyr: update sdk-zephyr with openthread cherrypicks.

- applications/serial_lte_modem/src/slm_at_host.c
- applications/serial_lte_modem/src/slm_at_sms.c
- applications/serial_lte_modem/src/slm_at_socket.c
Fixed some coverity issues for Serial LTE Modem.
Two of the fixes are trivial issues, one fix also had some refactoring included.
> Serial LTE Modem - Coverity fixes

- doc/nrf/external_comp/avsystem.rst
Documentation edits to match the template
> doc improvement: Documentation edits to match the template

- west.yml
Regular OpenThread update to \`4cba902\`
> manifest: openthread: update to \`4cba902\`

- scripts/quarantine_windows_mac.yaml
Update quarantine file with mesh test to match sdk-nrf.
> quarantine_windows_mac: Update for mesh test

- subsys/net/lib/download_client/src/download_client.c
- subsys/net/lib/fota_download/src/fota_download.c
Fix a typo in switch-case that was not including break.
> net: fota_download: Don't stop on network errors

- samples/nrf9160/https_client/src/main.c
added support to handle PDN_EVENT_NETWORK_DETACH.
> samples: nrf9160: https_client: handle PDN_EVENT_NETWORK_DETACH

- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_structs.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fw/host_rpu_umac_if.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/rx.c
- drivers/wifi/nrf700x/zephyr/inc/zephyr_fmac_main.h
- drivers/wifi/nrf700x/zephyr/inc/zephyr_wifi_mgmt.h
- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_mgmt.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
- west.yml
Listen interval parameters from user/app
> Extended ps

- samples/matter/common/src/bt_nus_service.cpp
After commissioning to Matter network the device was not able to connect to a phone via Bluetooth LE properly.
> samples: matter: Fix for NUS connection after commissioning

- doc/nrf/external_comp/edge_impulse.rst
- doc/nrf/links.txt
update the Edge Impulse user guide to match
with the integration template
NCSDK-19384
> doc improvement: update edge Impulse user guide

- drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_util.c
Displaying pending queue len globally but displaying outstanding tokens per-AC does't make sense, move everything to per-AC.
Also, display hardcoded peer (this will change when we AP mode support is in).
> drivers: wifi: Fix output of TX stats

- subsys/net/openthread/Kconfig.defconfig
- west.yml
update openthread to `d9abe30`
> manifest: openthread: update to `d9abe30`

- lib/dk_buttons_and_leds/dk_buttons_and_leds.c
This is the follow-up to #10646 and #10930 PRs.
Found out that the power consumption during Thingy53's idle state is around 50uA higher than on the previous NCS version.
This PR fixes the issue by having a different interrupt also with GPIO1 peripheral.
> lib: dk_buttons_and_leds: reduce power consumption for Thingy53

- doc/_extensions/ncs_tool_versions.py
Removed python code that was incompatible with 3.8.
> doc: tool_version python code compatible with 3.8

- west.yml
Pulled bug fix:
* Fixed PS timeout param type
> manifest: Updated revision to pull PS param type fix

- doc/nrf/app_dev/tfm/index.rst
- samples/bluetooth/mesh/ble_peripheral_lbs_coex/README.rst
- samples/bluetooth/mesh/chat/sample_description.rst
- samples/bluetooth/mesh/light/README.rst
- samples/bluetooth/mesh/light_dimmer/README.rst
- samples/bluetooth/mesh/sensor_client/README.rst
- samples/bluetooth/mesh/sensor_server/README.rst
- samples/bluetooth/mesh/silvair_enocean/README.rst
- samples/tfm/tfm_hello_world/README.rst
- samples/tfm/tfm_psa_template/README.rst
Various doc fixes before the 2.4 release
> doc improvement: various doc fixes for 2.4 release

- doc/nrf/conf.py
- scripts/tools-versions-darwin.yml
- scripts/tools-versions-linux.yml
- scripts/tools-versions-win10.yml
> tools: Added yml version of tools-version files

- doc/nrf/libraries/others/event_manager_proxy.rst
Update to limitation section of
Event Manager Proxy library
> doc improvement: Update to Event Manager Proxy library

- samples/debug/memfault/README.rst
The Memfault sample introduction paragraph is updated to reflect the information about Wi-Fi support.
> doc improvement: Update to Memfault sample

- doc/nrf/protocols/bt_mesh/dfu_over_ble.rst
- doc/nrf/protocols/bt_mesh/dfu_over_bt_mesh.rst
- doc/nrf/protocols/bt_mesh/fota.rst
- doc/nrf/protocols/bt_mesh/index.rst
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/working_with_nrf/nrf52/developing.rst
- samples/bluetooth/mesh/dfu/distributor/README.rst
- samples/bluetooth/mesh/dfu/target/README.rst
Aligning and cleaning up docs for mesh dfu
samples and ug
NCSDK-21597
> doc improvement: doc cleanup mesh dfu

- doc/nrf/working_with_nrf/nrf70/developing/powersave.rst
Updated TWT interval to us in user guide.
> doc: Update TWT interval from ms to us.

- west.yml
Update SoftDevice Controller and MPSL.
> manifest: update softdevice controller and mps

- subsys/net/lib/lwm2m_client_utils/location/location_wifi_ap_scanner.c
- subsys/net/lib/lwm2m_client_utils/lwm2m/gnss_assistance_obj.c
Fix 2 coverity issues from location assistance.
Unnecessary header and unused return value.
> net: lib: lwm2m_client_utils: Minor bugfixes

- west.yml
> manifest: Update for PR 983

- west.yml
Pulled bug fix:
* Fixed cpp compatibility
> manifest: Updated revision to pull cpp compatibility fix

- subsys/bluetooth/controller/Kconfig
- west.yml
Taking over manifest updates from
https://github.com/nrfconnect/sdk-nrf/pull/11344
https://github.com/nrfconnect/sdk-nrf/pull/11329
> Ncs 2.4 final manifest

- west.yml
> manifest: Rebased forked repositories for ncs-2.4.0-rc2

- doc/nrf/known_issues.rst
Added v2.4.0 tag to known issues.
----
> doc: update known issues for NCS v2.4.0

- applications/nrf5340_audio/README.rst
- doc/nrf/index.rst
- doc/nrf/known_issues.rst
- doc/nrf/links.txt
- doc/nrf/release_notes.rst
- doc/nrf/releases/release-notes-2.4.0.rst
- doc/nrf/releases/release-notes-changelog.rst
- samples/nrf9160/lwm2m_client/fota.rst
doc: Add release notes for 2.4
Add release notes and other changes
> doc: Add release notes for 2.4

- samples/bluetooth/mesh/ble_peripheral_lbs_coex/src/lb_service_handler.c
Minor improvements that have not been incorporated during bugfix PR. Using default definition and
differentiating connection events by ID to refuse customer notification about mesh events in ble handlers.
> sample: Bluetooth: Mesh: mesh coex minor improvements

- west.yml
> manifest: nrfxlib update

- applications/nrf5340_audio/src/bluetooth/le_audio_cis_headset.c
- MCS discover moved to lc3_config_cb
- Will now do discovery even if stream is paused
- OCT-2582
> applications: nrf5340_audio: Move MCS discover for headset

- lib/identity_key/identity_key.c
In case of failures in the identity key library we want to panic, and not use asserts that can be compiled out.
> lib: identity_key: Do panic instead of assert

- applications/nrf5340_audio/src/modules/hw_codec.c
- Fixes bug where previous volume was not stored
- OCT-2588
> applications: nrf5340_audio: Store prev vol on vol adjust

- west.yml
Regular OpenThread update to \`7e8f77b\`
> manifest: openthread: update to \`7e8f77b\`

- CODEOWNERS
- west.yml
Replace Czeslaw Makarski in code owner role.
> codeowners: Update the nrf_802154-related codeowners

- tests/lib/edge_impulse/prj.conf
- tests/lib/edge_impulse/src/main.cpp
> tests: edge_impulse new api

- tests/subsys/app_event_manager/prj.conf
- tests/subsys/app_event_manager/src/main.c
> tests: app_event_manager new api

- samples/wifi/sr_coex/sample.yaml
Update valid build options for both DK and EK.
> samples: wifi: sr_coex: update valid build options

- doc/nrf/libraries/dfu/fmfu_mgmt.rst
- doc/nrf/libraries/networking/ftp_client.rst
- doc/nrf/libraries/nfc/ndef/launchapp.rst
- doc/nrf/libraries/others/qos.rst
Corrected the path to the header file in a few
library docs.
> doc improvement: fixing path to header file in a few lib docs

- applications/machine_learning/CMakeLists.txt
- applications/matter_weather_station/CMakeLists.txt
- applications/nrf_desktop/CMakeLists.txt
- applications/zigbee_weather_station/CMakeLists.txt
- cmake/partition_manager.cmake
Fixes configuration loading, needed for overlaying application configuration to function correctly.
> applications: Fix configuration loading

- west.yml
Regular OpenThread update to \`edc1a3f\`
> manifest: openthread: update to \`edc1a3f\`

- scripts/print_toolchain_checksum.sh
Tools txt file was replaced by yaml.
> tools: Update toolchain script

- doc/nrf/releases/release-notes-changelog.rst
- subsys/net/lib/nrf_cloud/include/nrf_cloud_codec_internal.h
- subsys/net/lib/nrf_cloud/include/nrf_cloud_fota.h
- subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_fota.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_fsm.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_mem.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_rest.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_transport.c
Move JSON manipulation from the FOTA module to the
codec module.
IRIS-6062
> net: lib: nrf_cloud: move FOTA JSON into codec

- tests/subsys/app_event_manager/prj.conf
- tests/subsys/app_event_manager/src/modules/test_data.c
- tests/subsys/app_event_manager/src/modules/test_multicontext_handler.c
- tests/subsys/app_event_manager/src/modules/test_subs.c
tests are run multiple times with random order
> tests: app_event_manager new api with shuffling

- west.yml
Regular OpenThread update to \`d629ddc\`
> manifest: openthread: update to \`d629ddc\`

- subsys/bluetooth/mesh/shell/shell_onoff_cli.c
Fix typo in creation of onoff set shell command.
> Bluetooth: Mesh: Fix typo in onoff set shell cmd

- samples/bluetooth/mesh/ble_peripheral_lbs_coex/src/lb_service_handler.c
- subsys/bluetooth/mesh/sensor.c
- subsys/bluetooth/mesh/sensor_cli.c
- subsys/bluetooth/mesh/sensor_srv.c
- subsys/bluetooth/mesh/shell/shell_utils.c
Fixed issues reported by Coverity.
> Bluetooth: Mesh: Fixed Coverity issues

- subsys/nrf_security/Kconfig.psa
- subsys/nrf_security/cmake/psa_crypto_config.cmake
- subsys/nrf_security/configs/psa_crypto_config.h.template
- subsys/nrf_security/src/psa_crypto_driver_wrappers.c
Add option to allow application to provide random data.
ref: NCSDK-21958
> nrf_security: User supplied PRNG

- doc/_extensions/table_from_rows.py
Dynamically add a "Shields" column to the generated requirements table from the table-from-sample-yaml directive.
The shields are retrieved from the extra_args section of the sample.yaml files.
> doc: extensions: Shields in requirements table

- doc/nrf/releases/release-notes-changelog.rst
- drivers/wifi/nrf700x/Kconfig.nrf700x
- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
- include/net/l2_wifi_connect.h
- subsys/net/CMakeLists.txt
- subsys/net/Kconfig
- subsys/net/l2_wifi_if_conn/CMakeLists.txt
- subsys/net/l2_wifi_if_conn/Kconfig
- subsys/net/l2_wifi_if_conn/l2_wifi_conn.c
[SHEL-1230] Implement 'connect with stored credentials' facility.
> net: l2_wifi: Add connect call with stored credentials.

- CODEOWNERS
Update to current organization.
> CODEOWNERS: Update crypto sources to current organization

- doc/nrf/releases/release-notes-changelog.rst
- lib/modem_key_mgmt/modem_key_mgmt.c
Added support to return 1 when buffer length doesnot match certificate length
> lib: modem_key_mgmt: update modem_key_mgmt.c

- west.yml
Regular OpenThread update to \`dad7754\`
> manifest: openthread: update to \`dad7754\`

- drivers/wifi/nrf700x/osal/bus_if/bus/qspi/src/qspi.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_vif.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/default/fmac_api.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/event.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_vif.c
- drivers/wifi/nrf700x/zephyr/inc/zephyr_fmac_main.h
- drivers/wifi/nrf700x/zephyr/src/qspi/inc/rpu_hw_if.h
- drivers/wifi/nrf700x/zephyr/src/qspi/src/rpu_hw_if.c
- drivers/wifi/nrf700x/zephyr/src/shim.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
- samples/wifi/radio_test/src/nrf_wifi_radio_test_shell.c
This saves power when Wi-Fi is enabled but unused.
> wifi: Tie the Wi-Fi on/off to interface up/down

- applications/nrf5340_audio/src/bluetooth/le_audio_cis_gateway.c
Storing the capabilities correctly
> applications: nrf5340_audio: Fix for receiving capabilities

- doc/nrf/index.rst
- doc/nrf/links.txt
- doc/nrf/pmic.rst
- doc/nrf/releases/release-notes-changelog.rst
- doc/nrf/working_with_pmic/npm1300/features.rst
- doc/nrf/working_with_pmic/npm1300/gs.rst
Added Working with PMICs section to top level
Added nPM1300 features to new section
> doc: Added working with PMICs section

- doc/nrf/security/ap_protect.rst
- west.yml
> doc: manifest PR for nrfxlibPR1031

- west.yml
Regular OpenThread update to \`11a38a6\`
> manifest: openthread: update to \`11a38a6\`

- doc/nrf/releases_and_maturity/known_issues.rst
The known issue doesn't mention it affects NCS 2.2.0 as well, and additionally recommended workaround is not complete.
> doc: Updated KRKNWK-16728 known issue content

- doc/nrf/protocols/bt_mesh/concepts.rst
PR adds subclause about mesh in ble coexistence in mesh doc.
> doc: Bluetooth: Mesh: add subclause about mesh and ble coex

- west.yml
Update MPSL and SDC to the latest versions.
This adds the changes in https://github.com/nrfconnect/sdk-nrfxlib/pull/1041
> manifest: Update MPSL and SDC

- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
This change is to update the doxygen documentation for FMAC API.
> drivers: wifi: FMAC API documentation update

- doc/nrf/libraries/networking/lwm2m_location_assistance.rst
Add a paragraph about the result callback in the lwm2m location assistance documentation.
> doc: lwm2m_location_assistance result callback

- west.yml
Regular OpenThread update to `37fb770`
Signed-off-by: Maciej Baczmanski <maciej.baczmanski@nordicsemi.no>
> manifest: openthread: regular openthread upmerge `37fb770`

- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_structs.h
This set of changes addresses corrections for doxygen documentation for fmac_structs.h
> drivers: wifi: FMAC structs documentation update

- west.yml
> manifest: sdk-hostap: Pull fix for WPS

- west.yml
Change updates Find My revision to bring unit test updates.
Jira: NCSDK-21959
> west.yml: Update Find My revision

- west.yml
Pull hostap change to always request RNG from the PSA implementation.
> manifest: Pull hostap to always request RNG

- subsys/mpsl/fem/nrf21540_gpio_spi/models/mpsl_fem_nrf21540_power_model_builtin.c
- west.yml
This commit updates nrfxlib to bring in the latest changes in SDC and MPSL.
> manifest: updated nrfxlib with SDC and MPSL

- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fw/host_rpu_umac_if.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/default/fmac_api.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
- west.yml
Pass default BSS max idle time to UMAC.
> drivers: wifi: Configure BSS max idle time

- doc/nrf/protocols/matter/end_product/certification.rst
Added extra info about certification by inheritance SDO membership.
> doc: matter: clarify SDO for inheritance cert

- .github/workflows/docpublish.yml
> ci: docpublish: update zoomin upload URL

- west.yml
Regular OpenThread update to \`5beae14\`
> manifest: openthread: update to \`5beae14\`

- samples/cellular/nrf_provisioning/sample.yaml
Add 9160dk to allowed platforms.
> net: nrf_provisioning: Add platform

- doc/nrf/releases_and_maturity/known_issues.rst
Added a description of the KRKNWK-17343 bug.
> doc: update HomeKit known issues

- samples/peripheral/802154_phy_test/sample.yaml
Due to the automatisation of phy test tool tests, two more configurations are added to the sample.yaml file
> Phy test tool sample update

- applications/serial_lte_modem/doc/FOTA_AT_commands.rst
- applications/serial_lte_modem/doc/Generic_AT_commands.rst
- applications/serial_lte_modem/src/main.c
- applications/serial_lte_modem/src/slm_at_cmng.c
- applications/serial_lte_modem/src/slm_at_commands.c
- applications/serial_lte_modem/src/slm_at_fota.c
- applications/serial_lte_modem/src/slm_at_fota.h
- applications/serial_lte_modem/src/slm_at_host.c
- applications/serial_lte_modem/src/slm_settings.c
- applications/serial_lte_modem/src/slm_settings.h
- applications/serial_lte_modem/src/slm_uart_handler.c
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> applications: serial_lte_modem: implement rebootless modem FOTA

- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/radio_test/fmac_api.h
The changes incorporate cleanup of fmac_api.h file for doxygen comments in fmac_api.h for radio test
> drivers: wifi: radio-test fmac_api.h doxygen cleanup

- applications/asset_tracker_v2/tests/nrf_cloud_codec/src/nrf_cloud_codec_test.c
- tests/lib/qos/src/qos_test.c
- tests/subsys/net/lib/azure_iot_hub/dps/src/azure_iot_hub_dps_test.c
- tests/subsys/net/lib/wifi_credentials/src/main.c
- tests/subsys/net/lib/wifi_credentials_backend_psa/src/main.c
- tests/unity/unity_config.h
Add support for 64 bits macros.
> test: unity: add 64 bit support

- west.yml
> startup_file_improvements: manifest: update trusted-firmware-m

- applications/serial_lte_modem/doc/AT_commands_intro.rst
- applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
- applications/serial_lte_modem/doc/TCPUDP_AT_commands.rst
- applications/serial_lte_modem/prj.conf
- applications/serial_lte_modem/src/ftp_c/slm_at_tftp.c
- applications/serial_lte_modem/src/http_c/slm_at_httpc.c
- applications/serial_lte_modem/src/mqtt_c/slm_at_mqtt.c
- applications/serial_lte_modem/src/slm_at_commands.c
- applications/serial_lte_modem/src/slm_at_host.c
- applications/serial_lte_modem/src/slm_at_socket.c
- applications/serial_lte_modem/src/slm_at_tcp_proxy.c
- applications/serial_lte_modem/src/slm_at_udp_proxy.c
- applications/serial_lte_modem/src/slm_defines.h
- applications/serial_lte_modem/src/slm_util.c
- applications/serial_lte_modem/src/slm_util.h
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- west.yml
Additional minor changes include:
- Set a shorter connect/send timeout to #XUDPCLI.
- Improve the error logging and return codes around util_resolve_host().
- Fix a corner case in #XUDPSEND that could enter data mode even though there was no valid socket in use.
- Improve #XSSOCKETOPT error logging.
> applications: serial_lte_modem: add DTLS CID support

- CODEOWNERS
Add Tomi Fontanilles to CODEOWNERS.
> CODEOWNERS: Add Tomi Fontanilles

- west.yml
Update manifest for nrfxlib to bring in nrf_modem socket CID doc changes.
> manifest: update nrfxlib for nrf_modem socket CID doc changes

- west.yml
Add additional hooks to the net_filter in zephyr.
> manifest: Add hooks to net_filter.

- west.yml
Increasing scan window improves mesh overall throughput
Mesh AutoPTS tester fixes
> manifest: update zephyr for mesh fixes and imrovements

- west.yml
> manifest: update to latest sdk-zepher

- samples/net/mqtt/doc/description.rst
- samples/net/mqtt/overlay-tls-nrf70.conf
- samples/net/mqtt/sample.yaml
> samples: mqtt: Rename nRF7 to nRF70

- samples/matter/thermostat/README.rst
Fixed QR Code Payload and manual pairing code
> samples: matter: fix for qr-code

- doc/nrf/releases_and_maturity/known_issues.rst
Updated release tags for CVE-2023-2626 & KRKNWK-6848 issues
> doc: update Thread known issues

- doc/nrf/releases_and_maturity/known_issues.rst
Adds two known issues for some crypto configurations which may cause build failures.
> doc: Add known issues for crypto configurations

- doc/nrf/config_and_build/bootloaders_and_dfu/bootloader.rst
> doc: Secure boot doc update

- samples/cellular/modem_shell/src/gnss/gnss.c
Made A-GPS/P-GPS and REST flagging more understandable.
> samples: cellular: modem_shell: A-GPS/P-GPS flagging improvement

- scripts/requirements-fixed.txt
Pip-audit report:
Name        |Version |ID                  |Fix Versions
------------|--------|--------------------|------------
certifi     |2023.5.7|GHSA-xqr8-7jwr-rhp7 |2023.7.22
cryptography|41.0.1  |PYSEC-2023-112      |41.0.2
> tools: update pip packages with vuln

- west.yml
Improve portability of TF-M CMake platform code - manifest update
> Improve portability of TF-M CMake platform code - manifest update

- applications/nrf_desktop/doc/ble_conn_params.rst
- applications/nrf_desktop/doc/ble_latency.rst
- applications/nrf_desktop/doc/config_channel.rst
- applications/nrf_desktop/doc/hid_state.rst
- applications/nrf_desktop/doc/hids.rst
- applications/nrf_desktop/doc/motion.rst
- applications/nrf_desktop/doc/usb_state.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change introduces additional information related to the implementation details of the module.
Jira: NCSDK-22790
> applications: nrf_desktop: Improve simulated motion documentation

- drivers/wifi/nrf700x/zephyr/inc/zephyr_fmac_main.h
Update Wi-Fi driver version to 1.2.4.99.
> drivers: wifi: Update Wi-Fi driver version

- samples/net/aws_iot/boards/nrf9161dk_nrf9161_ns.conf
- samples/net/aws_iot/sample.yaml
- samples/net/mqtt/boards/nrf9161dk_nrf9161_ns.conf
- samples/net/mqtt/sample.yaml
Add missing nrf9161 board files.
Add 9161 to sample.yaml.
> samples: net: Add 9161 board files

- west.yml
Regular OpenThread update to \`992be27\`
> manifest: openthread: update to \`992be27\`

- west.yml
See sdk-nrfxlib PR:
- https://github.com/nrfconnect/sdk-nrfxlib/pull/1060
> Bluetooth: Update sdk-nrfxlib revision:

- .github/test-spec.yml
Add entry to test-spec to catch any breaking changes in shields configuration.
> CI: Update FEM scope in test-spec.yaml

- .github/workflows/docpublish.yml
Change folder on Zoomin server from dev to prod.
> doc: update target folder for doc uploads

- applications/nrf_desktop/README.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add general HID report rate measurement guide.
Jira: NCSDK-21680
> applications: nrf_desktop: Add general HID report rate measurement guide

- applications/nrf_desktop/README.rst
Update sentence about supported DK configurations to make it more general and link to proper section with more detailed information.
Jira: NCSDK-21680
> applications: nrf_desktop: Update info about supported DK configs

- samples/cellular/lwm2m_client/scripts/coiote.py
- samples/cellular/lwm2m_client/scripts/fota.py
Advanced Firmware object was renamed to
Multicomponent Firmware Update object. This caused changes to REST API.
This issue has been reported to AVSystem.
Do not merge until https://helpcenter.avsystem.com/plugins/servlet/desk/portal/17/CDM-367 is resolved. We need to check with them, what is the correct name.
> samples: lwm2m_client: Fix Coiote FOTA script

- doc/nrf/links.txt
- doc/nrf/protocols/thread/certification.rst
- doc/nrf/protocols/thread/configuring.rst
- doc/nrf/protocols/thread/device_types.rst
- doc/nrf/protocols/thread/overview/architectures.rst
- doc/nrf/protocols/thread/overview/commissioning.rst
- doc/nrf/protocols/thread/overview/communication.rst
- doc/nrf/protocols/thread/overview/index.rst
- doc/nrf/protocols/thread/overview/ot_integration.rst
- doc/nrf/protocols/thread/overview/ot_memory.rst
- doc/nrf/protocols/thread/overview/supported_features.rst
- doc/nrf/protocols/thread/prebuilt_libs.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Applies improvements that have been identified to the Thread documentation set.
> doc: Thread documentation improvements

- west.yml
Regular OpenThread update to \`70adcab\`
> manifest: openthread: update to \`70adcab\`

- drivers/wifi/nrf700x/Kconfig
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/cmd.c
Support to extend TWT service period
> Tx support outside twt sp

- include/bluetooth/mesh/light_ctl.h
- subsys/bluetooth/mesh/light_ctl_internal.h
- subsys/bluetooth/mesh/light_temp_srv.c
Commit adds support of unknown temperature range
for CTL model.
> Bluetooth: Mesh: support unknown range in ctl

- .github/workflows/docpublish.yml
Updating the folder name on Zoomin server for auto uploads of doc.
> doc: update zoomin upload path

- CODEOWNERS
Torstein Grindvik has left Nordic recently.
> CODEOWNERS: Replace torsteingrindvik

- CODEOWNERS
Jarno Lämsä have resigned from Nordic.
> CODEOWNERS: Remove jarlamsa

- samples/matter/light_bulb/sample.yaml
- samples/matter/light_switch/sample.yaml
- scripts/quarantine_integration.yaml
Definition of new configuration of light bulb matter sample and light switch matter sample needed to execute load memory tests.
> samples: matter: define sample persistence subscription configuration

- west.yml
Regular OpenThread update to \`f14d726\`
> manifest: openthread: update to \`f14d726\`

- applications/nrf_desktop/src/modules/ble_scan.c
Cleanup BLE scan module implementation before introducing new features.
Jira: NCSDK-20843
> applications: nrf_desktop: Cleanup BLE scan module implementation

- doc/nrf/libraries/bin/bt_ll_acs_nrf53/index.rst
- doc/nrf/links.txt
> applications: nrf5340_audio: Added capabilities doc for the controller

- include/audio_defines.h
> Applications: nrf5340_audio: Added audio ablk

- doc/nrf/includes/lwm2m_common_server_setup.txt
- samples/cellular/lwm2m_carrier/sample_description.rst
Formatting fixes in the sample doc.
> doc: Cellular: LwM2M carrier sample fixes

- samples/tfm/tfm_psa_template/README.rst
One of the code snippets was missing the proper
formatting. This PR fixes it.
> doc: TF-M: PSA template sample formatting fix

- samples/matter/light_bulb/sample.yaml
- samples/matter/lock/sample.yaml
sample with eagle EK switched from lock to light_bulb
> samples: matter: light_bulb eagle ek sample added

- applications/serial_lte_modem/src/gnss/slm_at_gnss.c
After a reset modem will send NRF_MODEM_GNSS_EVT_AGPS_REQ. If there is valid A-GPS data cached on modem side, app could inject current GPS time before starting GNSS, so that modem would not request new almanac and ephemerides, reducing data size for cloud downloading.
Sample log of cache data reused:
AGPS_REQ.sv_mask_ephe = 0x00000000 instead of 0xffffffff
AGPS_REQ.sv_mask_alm  = 0x00000000 instead of 0xffffffff
AGPS_REQ.data_flags   = 0x00000033
Further note:
A-GPS data is cached periodically or upon +CFUN=0.
Cached data in RAM can be purged by #XGPSDEL=511.
> applications: serial_lte_modem: Use cached A-GPS data

- west.yml
Regular OpenThread update to \`c10f650\`
> manifest: openthread: update to \`c10f650\`

- samples/cellular/lwm2m_client/src/main.c
Fix firmware Update state for handling Disconnect state.
Fix wm2m_rd_client_start() call if it return error client jump to network error which recover state.
> samples: lwm2m_client: Client state machine fix

- samples/net/azure_iot_hub/src/main.c
Add update size field for device id.
> samples: azure_iot_hub: Fix hw id

- doc/nrf/releases_and_maturity/known_issues.rst
The new commit SHA is connected to bugfix
> doc: Updated a Matter known issue with the proper commit SHA

- doc/nrf/conf.py
- doc/nrf/index.rst
- doc/nrf/releases_and_maturity.rst
- doc/nrf/releases_and_maturity/known_issues.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Revert doc versions after 2.4.99-dev1
> doc: Revert doc versions after 2.4.99-dev1

- west.yml
Regular OpenThread update to \`4ae6914\`
> manifest: openthread: update to \`4ae6914\`

- west.yml
> manifest: NCS 2.4.2

- applications/nrf5340_audio/sample.yaml
Remove the word "sample" from
the description.
> applications: nrf5340_audio: Fix description in sample.yaml

- applications/machine_learning/sample.yaml
Change aligns application name in `sample.yaml` with the application documentation.
Jira: NCSDK-23320
> applications: machine_learning: Align application name in sample.yaml

- west.yml
Updates mcuboot version to include an nRF5340 PCD fix
> manifest: Update mcuboot version

- applications/nrf5340_audio/src/modules/button_handler.c
- applications/nrf5340_audio/src/modules/power_meas.c
> Applications: nrf5340_audio: Thread renaming

- samples/pmic/native/npm1300_fuel_gauge/README.rst
Updated sample location to correct path
> samples: npm1300_fuel_gauge: Corrected sample path

- applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
- applications/serial_lte_modem/doc/TCPUDP_AT_commands.rst
- applications/serial_lte_modem/src/slm_at_socket.c
- doc/nrf/links.txt
Fix socket options: SO_SILENCE_ALL, SO_IP_ECHO_REPLY, SO_IPV6_ECHO_REPLY, SO_TCP_SRV_SESSTIMEO and TLS_CIPHERSUITE_USED.
> applications: serial_lte_modem: Fix socket options.

- applications/serial_lte_modem/src/main.c
Restore level triggering to GPIO wakeup to restore minimal power consumption in AT#XSLEEP=2.
> applications: serial_lte_modem: Wakeup level triggered

- subsys/net/lib/nrf_cloud/src/nrf_cloud_codec_internal.c
> net: lib: nrf_cloud: add mutex around modem info struct

- west.yml
Bumped Matter version to pull a commit fixing bus fault during Wi-Fi connection.
> manifest: Pulled Wi-Fi fix for Matter

- doc/nrf/test_and_optimize/optimizing/power_general.rst
Minor update to General power optimization
recommendations
> doc: General Power Optimization nitpick

- doc/nrf/device_guides/working_with_nrf/nrf70/developing/regulatory_support.rst
Minor update about the non-DFS channel
to the Operating with regulatory support UG.
> doc: wifi: update to regulatory support ug

- west.yml
> manifest: Update Sidewalk revision in west.yml

- applications/serial_lte_modem/src/gnss/slm_at_gnss.c
> applications: serial_lte_modem: fix left-out variable renaming

- west.yml
Regular OpenThread update to \`79a3a26\`
> manifest: openthread: update to \`79a3a26\`

- west.yml
> manifest: update dragoon

- west.yml
Change brings Find My alignments needed after Zephyr upmerge.
Jira: NCSDK-23491
> west.yml: Align Find My to new Zephyr

- applications/serial_lte_modem/src/nrfcloud/slm_at_nrfcloud.c
A local variable named identically to a static variable caused the command to try to send location requests with no cellular nor Wi-Fi data.
Prefix all the static variables in that file with `nrfcloud_` to discern them better.
> applications: serial_lte_modem: fix AT#XNRFCLOUDPOS

- doc/nrf/releases_and_maturity/known_issues.rst
Update known issue with the infomation about fixing the software diagnostic's feature-map.
> docs: update known issue with KRKNWK-17718 bug in Matter

- tests/bluetooth/iso/modules/iso_broadcast_sink.c
- tests/bluetooth/iso/modules/iso_broadcast_src.c
Fix sink start automatically issue.
OCT-2483
> tests: bluetooth: iso: Fix brcast sink start in default issue

- applications/matter_bridge/sample.yaml
- scripts/quarantine_integration.yaml
Define in sample.yaml debug and release configuratons for Matter BLE bridge.
> applications: matter_bridge: add matter ble bridge sample definition

- west.yml
pm_sysflash.h has been separated from sysflash.h.
> manifest: Update sdk-mcuboot with pm_sysflash.h

- samples/cellular/lwm2m_client/provisioning.rst
- samples/cellular/lwm2m_client/sample_description.rst
- samples/cellular/lwm2m_client/scripts/leshan.py
- samples/cellular/lwm2m_client/scripts/provision.py
Add support for provisioning into Leshan Bootstrap server by using the automated scripts.
> samples: lwm2m_client: Add support for Leshan provisioning

- west.yml
NSIB multi-image fix broke nRF91 this should fix the issue it introduced.
Ref. NCSDK-23305
> manifest: mcuboot: NSIB multi-image fixup

- drivers/wifi/nrf700x/Kconfig
- drivers/wifi/nrf700x/osal/bus_if/bus/spi/inc/spi.h
- drivers/wifi/nrf700x/osal/bus_if/bus/spi/src/spi.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_structs_common.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/event.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_api_common.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/tx.c
- drivers/wifi/nrf700x/osal/hw_if/hal/src/hal_fw_patch_loader.c
- drivers/wifi/nrf700x/osal/os_if/inc/osal_api.h
- drivers/wifi/nrf700x/osal/os_if/inc/osal_ops.h
- drivers/wifi/nrf700x/osal/os_if/inc/osal_structs.h
- drivers/wifi/nrf700x/osal/os_if/src/osal.c
- drivers/wifi/nrf700x/osal/utils/inc/util.h
- drivers/wifi/nrf700x/osal/utils/src/util.c
- drivers/wifi/nrf700x/zephyr/src/shim.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_fw_load.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_net_if.c
- samples/wifi/radio_test/src/nrf_wifi_radio_ficr_shell.c
Handle os specific code.
(1) Moved os specific code to shim to handle it os independent way. (2) Re-arranged code to build it for other os.
> drivers: wifi: Fix OSAL issues for other OSes

- samples/wifi/scan/src/main.c
Fixes https://devzone.nordicsemi.com/f/nordic-q-a/103719/
> Fix scan without otp prog

- doc/nrf/links.txt
- doc/nrf/protocols.rst
- doc/nrf/protocols/amazon_sidewalk/index.rst
- doc/nrf/samples.rst
- doc/nrf/samples/amazon_sidewalk.rst
Added Sidewalk sections with documentation references. 
Included for both samples and protocols.
> doc: add Sidewalk doc sections

- modules/hostap/src/supp_api.c
- modules/hostap/src/supp_api.h
- modules/hostap/src/supp_main.c
Add support for Monitor, TX-Injection mode alsong with packet filtering and channel setting for the modes
> modules: hostap: Add support for Monitor, TX-injection modes

- samples/esb/esb_prx/README.rst
- samples/esb/esp_ptx/README.rst
Minor improvements to ESB samples
____________________________________
Implementing changes not captured in PR #12343 
Added DNM until appropriate approvals are obtained.
> doc: improve esb sample

- drivers/wifi/nrf700x/osal/os_if/inc/osal_structs.h
- drivers/wifi/nrf700x/zephyr/src/shim.c
Fix assert and greater than typos.
> drivers: wifi: nrf700x: Fix typos

- drivers/wifi/nrf700x/osal/bus_if/bus/spi/src/spi.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/event.c
- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/fmac_ap.c
OSAL fixes from Linux testing.
> Fix spi bus

- doc/nrf/device_guides/working_with_nrf/nrf70/developing/constrained.rst
- doc/nrf/links.txt
Update correct configurations and UDP_RX and UDP_TX values.
> doc: nrf70: High performance profile throughput

- doc/nrf/documentation/build.rst
- doc/nrf/installation/installing.rst
- doc/nrf/links.txt
Updates the step required for Python deps reflecting the changes brought about by
https://github.com/nrfconnect/sdk-nrf/pull/11961
> doc: Doc updates related to Python deps

- doc/nrf/documentation/build.rst
Fixes a link in Doc build page
> Doc: Fixes a link in Doc build page

- doc/nrf/releases_and_maturity.rst
- doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
Add a working draft for the migration notes for 2.5
> doc: Add placeholder for migration notes

- doc/nrf/libraries/networking/aws_iot.rst
Update a note on the AWS IOT library
> doc: Update a note on the AWS IOT library

- include/flash_map_pm.h
> flash_map/pm: Add definitions for third image

- west.yml
Updates MCUboot and zephyr to include support for 3 images
> manifest: Update zephyr and mcuboot

- west.yml
> manifest: update mpsl

- doc/nrf/drivers/wifi/nrf700x/nrf700x.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h
- drivers/wifi/nrf700x/osal/fw_if/umac_if/inc/fmac_api_common.h
Add documentation for TX power ceiling options.
> doc: nrf: drivers: Add documentation for TX power ceiling

- doc/nrf/releases_and_maturity/release_notes.rst
Quick fix in Releases and Maturity toc
> doc: Quick fix in Releases and Maturity toc

- doc/nrf/conf.py
- doc/nrf/index.rst
- doc/nrf/releases_and_maturity.rst
- doc/nrf/releases_and_maturity/known_issues.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Revert doc versions after 2.4.99-dev2
> doc: Revert doc versions after 2.4.99-dev2

- subsys/bluetooth/controller/hci_internal.c
When HCI commands for legacy and extended commands are being used, a Command Disallowed error should be produced. In this case, the command complete event was missing the other (command specific) parameters in the event.
Added them.
> bluetooth: controller: Fix command complete

- doc/nrf/device_guides/working_with_nrf/nrf70/features.rst
- samples/wifi/provisioning/README.rst
- samples/wifi/radio_test/ficr.rst
- samples/wifi/radio_test/radio_test_subcommands.rst
- samples/wifi/radio_test/sample_description.rst
- samples/wifi/scan/README.rst
- samples/wifi/shell/README.rst
- samples/wifi/shutdown/README.rst
- samples/wifi/sr_coex/README.rst
- samples/wifi/sta/README.rst
- samples/wifi/twt/README.rst
Minor style fixes in Wi-Fi features guide and samples.
> doc: wifi: minor fixes in wifi docs

- west.yml
Regular OpenThread update to \`c6eaeda\`
> manifest: openthread: update to \`c6eaeda\`

- CODEOWNERS
VTPeltoketo is not working here anymore.
> CODEOWNERS: Remove Veli-Tapani Peltoketo

- doc/nrf/protocols/bt/bt_mesh/configuring.rst
- doc/nrf/protocols/matter/getting_started/low_power_configuration.rst
- doc/nrf/protocols/thread/sed_ssed.rst
- doc/nrf/test_and_optimize/optimizing/power_general.rst
Expanded power optimization page with sections for protocols. KRKNWK-17138.
> doc: power_optimization: expand docs

- applications/serial_lte_modem/Kconfig
- applications/serial_lte_modem/doc/GNSS_AT_commands.rst
- applications/serial_lte_modem/doc/NRFCLOUD_AT_commands.rst
- applications/serial_lte_modem/prj.conf
- applications/serial_lte_modem/src/gnss/Kconfig
- applications/serial_lte_modem/src/gnss/slm_at_gnss.c
- applications/serial_lte_modem/src/nrfcloud/slm_at_nrfcloud.c
- applications/serial_lte_modem/src/slm_at_commands.c
- doc/nrf/libraries/networking/nrf_cloud_pgps.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
See the changelog entries for more details.
> applications: serial_lte_modem: support A-GPS and P-GPS combined

- samples/cellular/lwm2m_client/src/main.c
- samples/cellular/modem_shell/src/cloud/cloud_lwm2m.c
- west.yml
Fetch LwM2M and CoAP related bugfixes and improvements.
> Cherry-pick LwM2M and CoAP fixes from upstream

- samples/cellular/modem_shell/src/ppp/ppp_ctrl.c
After Zephyr upmerge PPP changes, there is no ppp carrier off event anymore when lcp is disconnected, 
i.e. when ppp disconnect is initiated from PC. Thus, MOSH started to use ppp dead/running events instead to trigger the need for PPP restart.
Jira: MOSH-475
> samples: cellular: modem_shell: ppp: restarting logic changed

- west.yml
Regular OpenThread update to \`4e52d85\`
> manifest: openthread: update to \`4e52d85\`

- west.yml
Bring the commits needed by twister to support multiple testpaths within pytest scenario.
> manifest: Update sdk-zephyr for twister-pytest changes

- .github/workflows/docpublish.yml
Fix upload path for Zoomin publishing
> doc: Fix upload path for Zoomin

- CODEOWNERS
- ext/oberon/psa/core/include/mbedtls/ecp.h
- ext/oberon/psa/core/include/psa/crypto_extra.h
- ext/oberon/psa/core/include/psa/crypto_sizes.h
- ext/oberon/psa/core/include/psa/crypto_struct.h
- ext/oberon/psa/core/library/psa_crypto.c
- ext/oberon/psa/drivers/oberon_spake2p.c
- ext/oberon/psa/drivers/oberon_spake2p.h
- west.yml
test-sdk-nrf: sdk-nrf-pr-12464
> nrf_security: nrf_cc3xx v0.9.18 and PSA Oberon 1.0.8 update

- west.yml
Bring in latest changes on the sdk-zephyr main.
Combined manifest updates from:
https://github.com/nrfconnect/sdk-nrf/pull/12522
https://github.com/nrfconnect/sdk-nrf/pull/12407
https://github.com/nrfconnect/sdk-nrf/pull/12460
> manifest: Update sdk-zephyr sha

- doc/nrf/libraries/modem/location.rst
- include/modem/location.h
Also other minor improvements. Especially, adding linking to symbols and Kconfig options.
Jira: NCSDK-23432
> lib: location: Add sequence diagrams

- west.yml
Update sidewalk revision in west.yml
> manifest: update sidewalk revision

- west.yml
Add reset functionality for sta_disconnect api.
> manifest: sdk-wi-fiquicktrack-controlappc: Pull fix for sta disconnect

- applications/nrf5340_audio/tools/buildprog/buildprog.py
Add user-specific BT broadcast name option in buildprog.py.
> applications: nrf5340_audio: Add user-specific BT name

- samples/cellular/modem_shell/src/sock/sock.c
DTLS didn't work because the socket was not connected and sendto() was used instead of send().
Jira: MOSH-516
> samples: cellular: modem_shell: Fix DTLS

- applications/nrf5340_audio/src/bluetooth/bt_management/advertising/bt_mgmt_adv.c
- applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
- applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan.c
We will now print the on-air address
> Applications: nrf5340_audio: Address print alterations

- applications/serial_lte_modem/doc/TCPUDP_AT_commands.rst
- applications/serial_lte_modem/doc/slm_testing.rst
- applications/serial_lte_modem/src/slm_at_host.c
- applications/serial_lte_modem/src/slm_at_tcp_proxy.c
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- Recv even when the connection is being closed.
- Fix statuses of operations to correspond to correct errno values.
- Documentation fixes.
> applications: serial_lte_modem: SLM server fixes.

- doc/_scripts/software_maturity/software_maturity_features.yaml
Add KConfig rules to yaml input file for Sidewalk.
KRKNWK-17811
> doc: software_maturity: add Amazon Sidewalk

- samples/wifi/twt/modules/traffic_gen/src/main.c
- samples/wifi/twt/src/main.c
Updated flow id, twt response check, error handling for twt teardown and print server report when client report not received.
> Twt callback

- west.yml
Regular OpenThread update to \`57ef721\`
> manifest: openthread: update to \`57ef721\`

- drivers/wifi/nrf700x/zephyr/src/zephyr_fmac_main.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_wifi_mgmt_scan.c
- drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
- modules/hostap/Kconfig
- modules/hostap/src/supp_api.c
- modules/hostap/src/supp_main.c
- modules/hostap/src/supp_main.h
Various bug fixes around scan and scan abort leading to false negative scan busy.
> wifi: Fix scan busy issues

- lib/modem_slm/modem_slm.c
This fixes the case where the UART buffer is not null-terminated.
> lib: modem_slm: handle missing null-terminator

- subsys/net/lib/ftp_client/src/ftp_client.c
The hostname used to be resolved to an IPv6 address (if found) even if the device had only an IPv4 address, which would make the connection to any IPv6-enabled host fail.
> lib: modem_slm: fix IPv4 connection to an IPv6-enabled host

- applications/nrf5340_audio/src/bluetooth/Kconfig.defaults
- applications/nrf5340_audio/src/bluetooth/bt_management/scanning/bt_mgmt_scan_for_broadcast.c
- applications/nrf5340_audio/src/bluetooth/bt_stream/broadcast/broadcast_source.c
Minor changes after the upmerge
> Applications: nrf5340_audio: Post upmerge cleanup

- west.yml
Brings in latest changes from nrfxlib.
> manifest: nrfxlib: update to latest

- applications/serial_lte_modem/doc/NRFCLOUD_AT_commands.rst
- applications/serial_lte_modem/doc/SOCKET_AT_commands.rst
- applications/serial_lte_modem/doc/slm_testing.rst
- applications/serial_lte_modem/src/slm_at_socket.c
- doc/nrf/links.txt
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add port to RECVFROM and updates documentation.
Also piggypacked a minor change to #NRFXLOUD documentation to this.
> Slm udp server fixes

- doc/nrf/links.txt
- doc/nrf/protocols/matter/end_product/certification.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added information about the certification status of Matter samples to the Matter certifcation page.
> doc: matter: Update Matter certification page

- west.yml
Updated nrfxlib to pull GNSS API documentation update.
> manifest: Update sdk-nrfxlib with GNSS API documentation update

- doc/nrf/releases_and_maturity/software_maturity.rst
Add Sidewalk features to the Software Maturity page in doc.
> doc: add Sidewalk software maturity table

- west.yml
Pull mesh fixes for OOB upload.
> manifest: zephyr: Pull mesh fixes for OOB upload

- samples/net/azure_iot_hub/src/main.c
Add ifdef around bootloader related function.
> samples: azure_iot_hub: Fix compile error

- tests/bluetooth/tester/src/model_handler.c
This changes how the `lightness_ctx` works in the tester. The tester contained a nested `bt_mesh_lightness_srv`, but for the LCTL tests, this nested struct would not actually be the one in use, because the CTL Server defines a nested server on its own. This caused problems where the lightness would be clamped to an undefined lightness range
This commit updates `lightness_ctx` to rather use a pointer to the associated `bt_mesh_lightness_srv`.
> Bluetooth: Mesh: Fix broken LCTL tests

- doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
Add guide regarding latest LwM2M changes from Zephyr and SDK.
> doc: Add migration guide for LwM2M related changes

- doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
Added entry for A-GNSS related changes.
> doc improvement: Add migration guide entry for A-GNSS changes

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Moved misplaced entries under the correct library.
> doc improvement: Fix changelog

- west.yml
Pulled Bluetooth LE configuration update that disabled 2M phy.
> manifest: Updated Matter revision to pull BLE interop fix

- applications/nrf5340_audio/src/bluetooth/bt_management/bt_mgmt.c
Error in connected_cb will now print address and conn
> Applications: nrf5340_audio: Error print correction

- samples/openthread/cli/harness-thci-1-3/nRF_Connect_SDK_1_3.py
Update THCI files to align with GRL V59.0
KRKNWK-17899
> samples: openthread: Update THCI files for Thread 1.3

- .github/workflows/compliance.yml
- .github/workflows/pip-requirements.yml
- scripts/compile-requirements.sh
* The workflow now runs in pull_request_target context
* The workflow now posts a comment informing the author that the PR resulted in changes to the pip-requirements.txt
* If the user reacts to the comment with the :eyes: emote and reruns the check, the check will add the changes to the PR
Github actions used by this workflow:
https://github.com/NordicBuilder/action-script-diff 
https://github.com/NordicBuilder/action-comment
Example execution in sdk-nrf-testing:
https://github.com/nrfconnect/sdk-nrf-testing/pull/195
> ci: Update pip requirements-fixed compilation

- modules/hostap/CMakeLists.txt
- modules/hostap/Kconfig
- west.yml
Add a Kconfig option to disabled advanced Wi-Fi features, this saves up 28K flash.
> modules: hostap: memory optimizations

- applications/nrf5340_audio/README.rst
Added note of prints during DFU
> Applications: nrf5340_audio: DFU doc added

- subsys/net/lib/nrf_cloud/coap/src/nrf_cloud_coap.c
- subsys/net/lib/nrf_cloud/src/nrf_cloud_fsm.c
An error was logged by mistake when the initial non-delta shadow update is processed.
Jira: IRIS-7314
> net: lib: nrf_cloud: Remove benign shadow error

- doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Also, make small fixes to the release notes.
> migration_guide: add entries for SLM

- west.yml
Updates to latest nrfxlib and dragoon including bugfix
> manifest: Update nrxlib and dragoon to latest

- applications/nrf5340_audio/src/bluetooth/bt_stream/unicast/unicast_server.c
- Set to 0 if no context available
OCT-2758
> applications: nrf5340_audio: Set available contexts

- doc/nrf/protocols/matter/getting_started/adding_clusters.rst
Updated information regarding usage of ZAP Tool to generate clusters configuration.
> doc: nrf: Fixed information in the Matter adding clusters guide

- scripts/pip-audit-whitelist.yml
- scripts/tools-versions-darwin.yml
- scripts/tools-versions-linux.yml
- scripts/tools-versions-win10.yml
Dummy change to bump NcsToolchainConfigVersion in bundles.
> tools: update NcsToolchainConfigVersion

- west.yml
This pulls in the change to disconnect the STA before reset.
> manifest: sdk-wi-fiquicktrack-controlappc: Pull fix to disconnect STA

- west.yml
> manifest: mbedtls misc changes

- samples/cellular/udp/README.rst
> doc: update on cellular UDP sample

- doc/nrf/device_guides/working_with_nrf/nrf52/developing.rst
The nRF Connect Device Manager is the default mobile app to present OTA DFU feature.
CC: @philips77
> doc: Update suggested OTA DFU apps

- drivers/wifi/nrf700x/zephyr/src/qspi/src/rpu_hw_if.c
The comment had a typo, EB means expansion board, while at it also improve the text and formatting to logical blocks.
> drivers: wifi: Improve comment and formatting

- west.yml
Updated sdk-nrfxlib revision for documentation improvements.
> manifest: Update sdk-nrfxlib revision

- doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
Adds notes on MCUboot version changes and board Kconfig fragments
> doc: migration_guide: Add notes

- drivers/wifi/nrf700x/osal/fw_if/umac_if/src/event.c
- drivers/wifi/nrf700x/osal/os_if/inc/osal_api.h
> wifi: Fix radio test logging

- applications/nrf_desktop/README.rst
- applications/nrf_desktop/doc/ble_scan.rst
- applications/nrf_desktop/src/modules/Kconfig.ble_scan
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Change introduces forced scan state description to the Bluetooth LE scan module documentation. Change also updates application README.
Jira: NCSDK-23219
> doc improvement : applications: nrf_desktop: Document forced scan state

- samples/wifi/scan/Kconfig
- samples/wifi/scan/src/main.c
Doing a single scan isn't that useful, so, add a configuration to take scan interval and keep doing scan.
> samples: wifi: scan: Keep doing scan

- drivers/wifi/nrf700x/zephyr/src/zephyr_wpa_supp_if.c
During interface de-initialization WPA supplicant thread is still running and issuing calls to the driver, esp. set_supp_port (802.1x port status changing during connection and disconnection), so, for now use the network interface lock to synchronize with data path. This fixes NRF7X-93 only.
But not only set_supp_port, this is a generic race b/w control and data path and needs a wider fix which will be addressed in SHEL-2077.
> drivers: wifi: Fix crash during de-init of the interface

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> applications: nrf5340_audio: Update changelog

- doc/nrf/releases_and_maturity/migration/migration_guide_2.5.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
UART changes and removed commands.
> migration_guide: Add remaining SLM entries

- subsys/net/lib/ftp_client/src/ftp_client.c
Loop over multiple lines that may be present in the control buffer to find a reply code, giving priority to the expected one.
> applications: serial_lte_modem: fix FTP reply code reception

- west.yml
Pulled fix disabling Wi-Fi logs to decrease the flash usage.
> manifest: Pulled WiFi fix for Matter

- tests/drivers/fprotect/negative/src/main.c
The test started failing after an upmerge. It was likely because of the change that makes PICOLIB the default library. The test failed because memcpy didn't trigger a bus fault. Probably because of some compiler optimization. Switching to MINIMAL_LIBC works, but this fix doesn't require that.
Rearrange the tests and make key variables volatile to be more robust against optimization.
Also properly check the output of fprotect_is_protected()
> tests: fprotect: negative: Fix failing test

- subsys/bootloader/bl_crypto/bl_crypto_cc310_common.c
Calling bl_crypto initialization from outside of NSIB will result in a corrupted stack. This adds a check to ensure that you are inside NSIB when you are calling the initialization function.
Ref. NCSDK-23962
> bl_crypto: cc310: Do not initialize cc310 from EXT_ABI

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
> doc: Quick fix in changelog

- west.yml
Pull the mesh fixes for DFU qualification
> manifest: pull mesh dfu fix

- doc/_extensions/page_filter.py
Removed manually inserting static files, since add_css_file
and add_js_file now works as inteded.
> doc: extensions: remove duplicate static imports

- samples/openthread/cli/harness-thci-1-3/nRF_Connect_SDK_1_3.py
removed "netdata register" command from `srp_client_remove`
> samples: openthread: fix THCI files for Thread 1.3

- scripts/tag_west_repos.sh
Add sidewalk to tag_west_repos.sh.
> [v2.5-branch] scripts: Add sidewalk to tag_west_repos.sh

- subsys/bluetooth/mesh/Kconfig.models
- subsys/bluetooth/mesh/gen_plvl_srv.c
- subsys/bluetooth/mesh/gen_ponoff_srv.c
- subsys/bluetooth/mesh/light_ctl_srv.c
- subsys/bluetooth/mesh/light_ctrl_srv.c
- subsys/bluetooth/mesh/light_hsl_srv.c
- subsys/bluetooth/mesh/light_hue_srv.c
- subsys/bluetooth/mesh/light_sat_srv.c
- subsys/bluetooth/mesh/light_xyl_srv.c
- subsys/bluetooth/mesh/lightness_srv.c
- subsys/bluetooth/mesh/scene_srv.c
- subsys/bluetooth/mesh/sensor.c
- subsys/bluetooth/mesh/sensor_types.c
- subsys/bluetooth/mesh/time.c
- subsys/bluetooth/mesh/time_srv.c
Updates Bluetooth mesh model specification references to reflect Mesh Model specification version 1.1.
> Bluetooth: Mesh: Update spec ref MshMDL1.0.1->1.1

- samples/cellular/modem_shell/src/gnss/gnss.c
- samples/cellular/modem_shell/src/location/location_shell.c
- samples/cellular/modem_shell/src/utils/str_utils.c
- samples/cellular/modem_shell/src/utils/str_utils.h
Improved printing of A-GNSS data requests.
> samples: cellular: modem_shell: Improve A-GNSS request printing

- samples/cellular/modem_shell/src/link/link.c
Added a check to skip setting modem system mode if it is already correctly set, because that caused unnecessary errors in some cases.
MOSH-512
> samples: cellular: modem_shell: Improve "link funmode" command

- doc/nrf/releases_and_maturity/known_issues.rst
Minor formatting fix on Known Issues page.
> doc: Minor fix on Known Issues page

- lib/location/method_gnss.c
Remove fallback to `NRF_MODEM_GNSS_EVT_AGNSS_REQ` event for determining GNSS assistance data need.
`nrf_modem_gnss_agnss_expiry_get()` can be used with all supported modem firmware versions.
Simplified GNSS assistance data handling.
Cleaned up error logging and some comments.
> lib: location: Remove A-GNSS request fallback

- .github/workflows/pip-requirements.yml
* Github verifys a user by a verified e-mail on the account.
* Chang e-mail address to the mail in the Nordic Builder profile.
> ci: pip-requirements workflow fix user mail

- subsys/nrf_security/src/psa_crypto_driver_wrappers.c
clang-format the psa_crypto_driver_wrappers.c file
> nrf_security: Format psa_crypto_driver_wrapper.c

- .github/workflows/docker.yml
- scripts/docker/Dockerfile
- scripts/docker/entrypoint.sh
Dockerfile and Github workflow action which builds and releases Docker image. Docker image will have Nordic toolchain bundle inside it.
> ci: add dockerfile and workflow action for releasing image

- tests/tfm/tfm_psa_test/README.rst
- tests/tfm/tfm_regression_test/README.rst
Document that provisioning is required.
Copy-modified from tfm_psa_template.
> doc: tfm_regression_test: Document provisioning requirement

- applications/nrf5340_audio/src/audio/le_audio_rx.c
- Set bad_frame flag if frame_size is not matching desired_size
> applications: nrf5340_audio: Bad_frame flag for wrong sizes

- doc/nrf/device_guides/working_with_nrf/nrf70/developing/constrained.rst
- doc/nrf/device_guides/working_with_nrf/nrf70/developing/soc_combo.csv
Updated the row legend in the Host SoC support table along with some minor fixes.
> doc: wifi: minor fixes to resource constrained host ug

- lib/location/method_gnss.c
GNSS is now configured before waiting for RRC idle. This allows to detect if GNSS is not enabled in modem system or functional mode before the RRC connection has been released.
> lib: location: Make GNSS method fail faster when GNSS is disabled

- doc/nrf/releases_and_maturity/known_issues.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Added deprecation info to the changelog.
Added the won't fix label to known issues.
> doc: added HomeKit deprecation notes

- west.yml
Regular OpenThread update to \`5058500\`
> manifest: openthread: update to \`5058500\`

- samples/wifi/twt/README.rst
Update TWT sample with Kconfig option needed to be able to run the traffic server
> doc: wifi: update TWT

- west.yml
> manifest: sdk-nrfxlib: Pull nRF70 patch update rev#1c05858e8b7

- applications/serial_lte_modem/doc/MQTT_AT_commands.rst
- applications/serial_lte_modem/src/mqtt_c/slm_at_mqtt.c
- applications/serial_lte_modem/src/slm_at_commands.c
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Add a new command to configure MQTT client before connecting to a broker, enabling dynamic tuning of Keep Alive time, etc.
JIRA ticket: NCSDK-23815
> application: serial_lte_modem: Add #XMQTTCFG command

- west.yml
Bring the commits needed by twister to improve reporting of failed pytest scenarios and added parametrized scope of DUT fixture.
> manifest: update twister to improve pytest reporting

- west.yml
Fixes a regression in Wi-Fi 5GHz association.
> manifest: matter: Pull fix for 5GHz Wi-Fi

- lib/at_host/at_host.c
This commit improves the code format.
> lib: at_host: improve format

- west.yml
> manifest: sdk-nrfxlib: Pull fix for Wi-Fi docs

- applications/matter_bridge/sample.yaml
- applications/matter_weather_station/sample.yaml
- scripts/quarantine_integration.yaml
Bridge debug sample with smp_dfu added.
> samples: matter: bridge sample with smp added

- west.yml
> manifest: sdk-nrfxlib: Pull nRF70 patch update rev#4922583d657

- samples/wifi/sta/src/main.c
Add the change to log Wi-Fi status after the connection establishment. This helps for debugging.
> samples: wifi: sta: Log Wi-Fi status after connection

- subsys/bluetooth/controller/hci_internal.c
Exposes the average RSSI calculated by LE Power Control.
The commands vs_set_auto_power_control_request_param and
vs_set_power_control_apr_handling have been replaced by
vs_set_power_control_request_params.
> Update hci vs commands

- .github/workflows/docpublish.yml
Fixing path to the Zoomin dev server.
> doc: doc upload path fix

- west.yml
Bring in latest nrfxlib and dragoon
> manifest: nrfxlib: Update to latest nrfxlib and dragoon

- .github/workflows/docpublish.yml
> doc: Doc publish fix for Zoomin

- subsys/bluetooth/controller/Kconfig
- subsys/bluetooth/controller/hci_driver.c
Update to reflect change in sdc memory macro.
> bluetooth: controller: hci_driver: update iso rx pdu pool macro

- applications/nrf5340_audio/Kconfig
- applications/nrf5340_audio/Kconfig.defaults
- applications/nrf5340_audio/src/audio/Kconfig
- applications/nrf5340_audio/src/audio/streamctrl_broadcast_sink.c
- applications/nrf5340_audio/src/audio/streamctrl_broadcast_source.c
- applications/nrf5340_audio/src/audio/streamctrl_unicast_client.c
- applications/nrf5340_audio/src/audio/streamctrl_unicast_server.c
- applications/nrf5340_audio/src/modules/Kconfig
MSG_SUBSCRIBER guarantees that
messages are not lost (default
FIFO size is 16 messages).
> applications: nrf5340_audio: Implement zbus MSG_SUBSCRIBER

- scripts/quarantine_windows_mac.yaml
Remove quarantine for esb as issue is closed.
Remove quarantine for mqtt and part of asset tracker as is fixed.
Tests are passing.
> quarantine_windows_max: Remove quarantine for resolved issues

- applications/nrf5340_audio/tools/buildprog/buildprog.py
- applications/nrf5340_audio/tools/buildprog/nrf5340_audio_dk_devices.py
- applications/nrf5340_audio/tools/buildprog/program.py
> Applications: nrf5340_audio: Experimental addition of SDC in buildprog

- CMakeLists.txt
- cmake/fw_zip.cmake
- cmake/sysbuild/b0_mcuboot_signing.cmake
- cmake/sysbuild/debug_keys.cmake
- cmake/sysbuild/image_signing.cmake
- cmake/sysbuild/partition_manager.cmake
- cmake/sysbuild/provision_hex.cmake
- cmake/sysbuild/sign.cmake
- modules/tfm/zephyr/CMakeLists.txt
- samples/tfm/tfm_psa_template/sysbuild/mcuboot/prj.conf
- subsys/bootloader/cmake/packaging.cmake
- sysbuild/CMakeLists.txt
- sysbuild/Kconfig.dfu
- sysbuild/Kconfig.mcuboot
- sysbuild/Kconfig.netcore
- sysbuild/Kconfig.secureboot
- sysbuild/Kconfig.sysbuild
- sysbuild/Kconfig.xip
- sysbuild/secureboot.cmake
- west.yml
Includes many ported features from child/parent image, see commits for details
> sysbuild: Port functionality from child/parent image

- CODEOWNERS
- subsys/dfu/dfu_target/src/dfu_target_smp.c
- tests/subsys/dfu/dfu_target/smp/CMakeLists.txt
- tests/subsys/dfu/dfu_target/smp/prj.conf
- tests/subsys/dfu/dfu_target/smp/src/img_gr_stub.c
- tests/subsys/dfu/dfu_target/smp/src/img_gr_stub.h
- tests/subsys/dfu/dfu_target/smp/src/main.c
- tests/subsys/dfu/dfu_target/smp/src/os_gr_stub.c
- tests/subsys/dfu/dfu_target/smp/src/os_gr_stub.h
- tests/subsys/dfu/dfu_target/smp/src/pm_config.h
- tests/subsys/dfu/dfu_target/smp/src/smp_stub.c
- tests/subsys/dfu/dfu_target/smp/src/smp_stub.h
- tests/subsys/dfu/dfu_target/smp/testcase.yaml
- tests/subsys/net/lib/mcumgr_smp_client/CMakeLists.txt
- tests/subsys/net/lib/mcumgr_smp_client/prj.conf
- tests/subsys/net/lib/mcumgr_smp_client/src/main.c
- tests/subsys/net/lib/mcumgr_smp_client/src/nrfx.h
- tests/subsys/net/lib/mcumgr_smp_client/testcase.yaml
Added unit test for validate DFU Target SMP API. 
Added unit test for validate mcumgr_smp_client API.
Added image list count to 0 at dfu_target_smp_client_init()
> DFU target smp & MCUmgr SMP client unit tests

- doc/nrf/external_comp/memfault.rst
- doc/nrf/releases_and_maturity/known_issues.rst
- samples/debug/memfault/README.rst
Update Memfault guide to match the integration template.
Minor fix to KnownIssues page.
NCDK-21319
> doc: Update Memfault guide to match the integration template

- doc/nrf/libraries/networking/rest_client.rst
- include/net/rest_client.h
Fixing broken code structure link and minor improvements.
> net: lib: rest_client: Minor doc fixes

- tests/lib/location/src/location_test.c
Small improvements to be able to get more information when tests fail. Adding asserts on `k_sem_take()` return values.
Adding 1ms sleep to the end of all functions waiting for events.
Still not moving` TEST_ASSERT_*`'s out of `location_event_handler()` as mentioned in Jira NCSDK-21340.
Let's see if this helps or if that has to be done too.
> tests: lib: location: Improvements to make debugging easier

- doc/nrf/libraries/modem/modem_slm.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- lib/modem_slm/modem_slm.c
- samples/cellular/slm_shell/boards/nrf52840dk_nrf52840.overlay
- samples/cellular/slm_shell/boards/nrf5340dk_nrf5340_cpuapp.overlay
- samples/cellular/slm_shell/boards/nrf7002dk_nrf5340_cpuapp.overlay
Change GPIO from gpio0 to configurable via application devicetree.
> lib: modem_slm: GPIO to configurable

- doc/nrf/libraries/modem/lte_lc.rst
- doc/nrf/libraries/modem/modem_antenna.rst
- doc/nrf/libraries/modem/nrf_modem_lib/nrf_modem_lib_pm_integration.rst
- doc/nrf/libraries/modem/nrf_modem_lib/nrf_modem_lib_trace.rst
Fixed a few Kconfig and API links. Also some minor language fixes.
> doc: formatting fixes to Modem library docs

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- scripts/hid_configurator/modules/dfu.py
Change separates functions specific to handling dfu_application.zip file format. This simplifies integrating new update image file formats.
Jira: NCSDK-21843
> scripts: hid_configurator: Separate functions for dfu_application.zip

- drivers/wifi/nrf700x/zephyr/src/qspi/inc/qspi_if.h
- drivers/wifi/nrf700x/zephyr/src/qspi/inc/rpu_hw_if.h
- drivers/wifi/nrf700x/zephyr/src/qspi/src/device.c
- drivers/wifi/nrf700x/zephyr/src/qspi/src/rpu_hw_if.c
- drivers/wifi/nrf700x/zephyr/src/shim.c
> Backport 12982 to v2.5 branch

- CODEOWNERS
- doc/nrf/device_guides/working_with_nrf/nrf70/developing/powersave.rst
- doc/nrf/links.txt
- samples/wifi/shutdown/README.rst
- samples/wifi/shutdown/sample.yaml
Refer to the PS for definition of "shutdown".
> samples: wifi: shutdown: Clarify meaning of shutdown

- doc/nrf/conf.py
- doc/nrf/index.rst
- doc/nrf/releases_and_maturity.rst
- doc/nrf/releases_and_maturity/known_issues.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
Revert doc versions after 2.5.99-dev1 rel.
> doc: revert doc versions after 2.5.99-dev1

- subsys/bluetooth/controller/hci_internal.c
Fixes an assert that could happen if the LE set periodic advertising response data was issued more than once without fetching the command complete event.
> bluetooth: Fix assert when handling illegal response data cmd

- applications/nrf_desktop/src/modules/Kconfig.ble_latency
- doc/nrf/libraries/caf/ble_state.rst
- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- subsys/caf/modules/Kconfig.ble_state
- subsys/caf/modules/ble_state.c
> caf: ble_state:/applications: nrf_desktop: Rework LLPM related dependencies

- drivers/wifi/nrf700x/Kconfig
- drivers/wifi/nrf700x/inc/wifi_mgmt.h
- drivers/wifi/nrf700x/src/fmac_main.c
- drivers/wifi/nrf700x/src/net_if.c
- drivers/wifi/nrf700x/src/wifi_mgmt.c
- modules/hostap/src/supp_api.c
- west.yml
This set brings in TX-Injection changes. This also depends on https://github.com/nrfconnect/sdk-nrfxlib/pull/1118
> wifi: Add TX injection support

- drivers/wifi/nrf700x/Kconfig
- drivers/wifi/nrf700x/src/fmac_main.c
Provide a Kconfig option to select frequency band
2.4GHz, 5GHz or both(2.4 and 5 GHz).
> drivers: wifi: Provide option to select frequency

- west.yml
Regular OpenThread update to \`a05954b\`
> manifest: openthread: update to \`a05954b\`

- doc/_extensions/software_maturity_table.py
- doc/nrf/releases_and_maturity/software_maturity.rst
Added power management device table to software maturity document
> doc: software_maturity: Added PMIC maturity table

- doc/nrf/releases_and_maturity/releases/release-notes-changelog.rst
- samples/peripheral/radio_test/src/radio_cmd.c
- samples/peripheral/radio_test/src/radio_test.c
Corrected the behavior of the radio_test sample when used with FEM.
Jira: NCSDK-23709
> samples: Aligned the radio_test TX power with FEM

- doc/nrf/links.txt
- samples/bluetooth/mesh/dfu/distributor/README.rst
Add note about securing LE connection in the distributor sample when accessing SMP characteristics.
> samples: mesh: distributor: Add note about securing LE connection

- applications/serial_lte_modem/doc/FOTA_AT_commands.rst
Make explicit that it is not supported.
> slm: fix Thingy:91 full FOTA documentation

- subsys/bluetooth/services/fast_pair/fp_storage/fp_storage_ak.c
- subsys/bluetooth/services/fast_pair/fp_storage/include_priv/fp_storage_ak_priv.h
- tests/subsys/bluetooth/fast_pair/storage/account_key_storage/src/test_corrupted_data.c
Changes Fast Pair Account Key ID field to Account Key Metadata field.
Jira: NCSDK-23204
> bluetooth: fast_pair: Change Account Key ID to Metadata

- applications/nrf5340_audio/src/audio/audio_datapath.c
- Fix bug where remainder operations were done on negative numbers
- Create helper function to fix both uses in one place
> applications: nrf5340_audio: Reimplement function for calculating err_us

- applications/serial_lte_modem/src/slm_at_host.c
- applications/serial_lte_modem/src/slm_uart_handler.c
- applications/serial_lte_modem/src/slm_uart_handler.h
- doc/nrf/releases_and_maturity/known_issues.rst
> applications: serial_lte_modem: Fix indications in #XSLEEP=2
